### ISSUE TITLE
Windows phone support

### ISSUE THREAD

**Issue by priteshpatel100** [googleads/googleads-mobile-unity#100]
It would be great if this could be made compatible with windows phone also, would become much more of a cross platform solution.

**Comment by takaaptech** [comment]
Please support window phone, we have trouble when run admob on window phone devices!

**Comment by adquestionthrowaway** [comment]
I would also love Windows Phone compatibility.

**Comment by hassanselim0** [comment]
Just adding my vote to this issue :)

**Comment by vbauer** [comment]
:+1:

**Comment by BonyYousuf** [comment]
Yes, please support windows phone

**Comment by bence98** [comment]
Totally agree. I personally don't use WP, but one of my acquaintances does, but now he can't install our game :(

**Comment by rampara** [comment]
Since this plugin wraps the existing Android and iOS GMA SDKs, Windows phone support will not possible.
