### ISSUE TITLE
Its not working with IL2CPP x64

### ISSUE THREAD

**Issue by cdxgs** [googleads/googleads-mobile-unity#1001]
I'm using  Unity 2019.2 with google-ads lastest version but when i compiled with il2cpp its crashes because of class not found on Android. With mono its works perfect.  Is it general bug?

**Comment by clivelewis** [comment]
Unfortunately, you didn't provide which class is missing. But I had the same problem, which was related to AndroidX migration. You can try the solution from this thread
https://forum.unity.com/threads/androidx-vs-android-libraries.710831/#post-4825043

**Comment by naklow12** [comment]
Yes when I get build ARMv7 and 64-bit it starts crashing. Why I don't know. When I just take ARMv7 build it works well.

**Comment by fredericoraiss** [comment]
is happening to me too :(
Any solution?

**Comment by naklow12** [comment]
> is happening to me too :(
> Any solution?

Keep _Split APKs by target architecture_ **off**. (At the below at same settings page.)

**Comment by stowy** [comment]
this should be resolved in the latest plugin version.
