### ISSUE TITLE
admob ad is not show in release mode but  in debug mode ad is showing

### ISSUE THREAD

**Issue by surajbharani** [googleads/googleads-mobile-unity#1003]
please help me on this problem.....??? any one  ??

**Comment by khushboogupta17** [comment]
the same issue, I'm using 2019.3.0a12 version and AdMob is showing test ads but when I put my test ID the app crashed

**Comment by khushboogupta17** [comment]
I figured out the solution for it,change the min SDK version and target API level in the XML document according to the one in player settings in Unity

**Comment by UragayalaDeepika** [comment]
Closing this as the issue seems to be resolved. Feel free to comment here if you still have this issue.
