### ISSUE TITLE
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by DataGreed** [googleads/googleads-mobile-unity#1007]
Does this library use UIWebView? Whenever I send a build of my game to Apple I receive a warning saying that I have to remove UIWebView from the app otherwise they will reject it.

**Comment by TomFromThePool** [comment]
@DataGreed this is a Unity issue relating to Apple deprecating UIWebView. Unity have a fix in review and will backport it when available: https://issuetracker.unity3d.com/issues/ios-apple-throws-deprecated-api-usage-warning-for-using-uiwebview-when-submitting-builds-to-the-app-store-connect

**Comment by stowy** [comment]
We also have a pending release of iOS that addresses this, I will update
the Unity plugin when this is available.

**Comment by SmartProjectGMBH** [comment]
any news about this bug? Vungle and AdColony update sdk to fix this problem, can you please update adapters for these networks?

**Comment by joses1234** [comment]
@stowy Any update on this issue? I'm still getting a warning when I send a build to apple. Doing a grep command for `UIWebView` shows GoogleMobileAds.framework match. Thanks

**Comment by stowy** [comment]
This was resolved, we tested the iOS SDK for submission and received no errors. The match you are seeing is not usage of UIWebView, it is an internal class name that contains UIWebView in it.

I would ensure you are using the latest version of the iOS SDK by either doing a clean iOS build or run `pod update` in the folder of the existing build.

**Comment by sm-j** [comment]
Is this solved in latest version? because i have 7.53 version installed.
will pod update work with this version? or i should update to latest?

**Comment by stowy** [comment]
Hi, usages of UIWebView were removed in 7.55.0, see [the release notes](https://developers.google.com/admob/ios/rel-notes).

I would recommend updating to the latest version of the iOS SDK using `pod update` or doing a clean build from Unity.

**Comment by yudiz-mobilegames** [comment]
Hey @stowy , I did a clean build and even my project is using version 7.61.0 but still, I am facing the same issue when uploading it to Store.

**Comment by stowy** [comment]
@yudiz-mobilegames - I would suggest you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines - they will be able to help debug your issue with you efficiently.

I recommend privately sending them an IPA that they can review.  As far as we're concerned there is no issue with the iOS SDK as we've been able to submit apps with it successfully and many others appear to not be having any issues also, so I would think that there may be another source of the symbol in your app.
