### ISSUE TITLE
OnAdClosed event is calling for both closing ad And closing ad after complete watch

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#1010]
OnAdClosed event is calling for both closing ad while ad is playing and also called when full rewarded ad is watch and then closed.
These are two different scenarios. And it should be two events for onadclosed.

**Comment by stowy** [comment]
Hi Muhammad,

Sorry, I'm not sure I 100% follow your issue here. Can you outline the
expected behavior, actual behavior, and steps to reproduce?

Thanks,

Sam

**Comment by UragayalaDeepika** [comment]
@MuhammadWaqasOfficial Can you please share the details if you are still seeing the issue?

**Comment by ivk1800** [comment]
@MuhammadWaqasOfficial in case if user was rewarded -  called OnAdRewarded and OnAdClosed
if user force close ads called only OnAdClosed
you can create flag _isRewarded_ and check it in OnAdClosed event

**Comment by MuhammadWaqasOfficial** [comment]
@ivk1800 spot on. thanks
