### ISSUE TITLE
AdColony fails in the first 5 seconds although the MobileAds.Initialize callback is called

### ISSUE THREAD

**Issue by pruebasssaa** [googleads/googleads-mobile-unity#1012]
Hi,

Setting up mediation with AdMob and AdColony, after receiving the call from MobileAds.Initialize (), I request an ad for AdColony, although it will reject me with this warning:

```
"Failed to request ad from AdColony: Internal Error"
"Cannot configure AdColony, configuration mechanism requires 5 seconds between attempts."
```

However, if I wait approximately 3-5 seconds and then request the ad, it does not fail. It is as if the SDK was not completely initialized. I have already checked and it is not a problem in my code or there are problems in the AdColony UI, this is not urgent since another network will fill that ad, and AdColony will have possibilities in the next , but I wanted to publish it if it is possible to get some help.

Thanks,

**Comment by UragayalaDeepika** [comment]
@pruebasssaa Are you using Adcolony directly and not calling Adrequest from the admob unity plugin? Can you make sure that you followed our guidelines as mentioned here: https://developers.google.com/admob/unity/mediation/adcolony and also test it on the latest version of the SDK? Can you use our  [sample script](https://github.com/googleads/googleads-mobile-unity/tree/master/samples) and provide a sample app if still unable to find a fix.?

**Comment by vokruttabtale** [comment]
I have the same error for all version com.google.ads.mediation:adcolony started from 3.3.8.1. I've checked the same code and admob key and error is gone with version 3.3.8.0.
