### ISSUE TITLE
Everything works except the banner in Unity 2019.2.4f1

### ISSUE THREAD

**Issue by topitsky** [googleads/googleads-mobile-unity#1013]
As said in the title.
I'm using the hello world code provided by this repository.
I'm able to load the interstitial and the rewarded ad and they work perfect, but when I try to load the banner, the whole app crashes.

Is there something I'm missing? I've put my ad id and app id correctly in the settings and resolved play services.

**Comment by renataNavarro** [comment]
I have the exactly same problem. Both, Android and iOS crash when I make the request, the build is succeed but the app crashes. Interstitial it's working fine. My code it's simple and I can't figure out the problem, I've been checking every configuration and it's everything right.

**Comment by stowy** [comment]
Ok, this is related to version 2019.2.x and later versions of Unity.

[This commit](https://github.com/googleads/googleads-mobile-unity/commit/b6cf3c3144a1818224233d0856fee9de7dd9a29b) is not released yet. That would probably resolve the issue for you.

**Comment by stowy** [comment]
@renataNavarro @topitsky  Please comment and vote on this issue to get Unity to resolve this in their IDE also - https://issuetracker.unity3d.com/issues/android-androidjavaclass-dot-getstatic-returns-null-when-being-built-to-android-device

**Comment by pipe-alt** [comment]
when are they gonna push a new release for this plugin? it's been  a month  :(

**Comment by umkhan65** [comment]
@stowy this worked for me

**Comment by stowy** [comment]
Fixed in v4.0.0 released today.
