### ISSUE TITLE
Fatal Exception: java.lang.Error

### ISSUE THREAD

**Issue by amorato** [googleads/googleads-mobile-unity#1015]
We are having crashes of Adcolony plugin in Unity on Android 8.1 and 9. Seems like a new campaign.

![image](https://user-images.githubusercontent.com/32353915/64760866-09759b80-d53b-11e9-95df-30602753ed9c.png)

`Caused by java.lang.OutOfMemoryError
Failed to allocate a 59759896 byte allocation with 8699952 free bytes and 8MB until OOM, max allowed footprint 201326592, growth limit 201326592
java.lang.StringFactory.newStringFromChars (StringFactory.java:267)
java.io.BufferedReader.readLine (BufferedReader.java:400)
com.adcolony.sdk.t.a (SourceFile:562)
com.adcolony.sdk.t.c (SourceFile:526)
com.adcolony.sdk.t$4$1.run (SourceFile:292)
com.adcolony.sdk.t.a (SourceFile:700)
com.adcolony.sdk.t$4.a (SourceFile:289)
com.adcolony.sdk.ae.a (SourceFile:209)
com.adcolony.sdk.ae.b (SourceFile:182)
com.adcolony.sdk.a.f (SourceFile:188)
com.adcolony.sdk.am.run (SourceFile:62)
java.lang.Thread.run (Thread.java:764)`

We have GoogleMobileAds mediation 3.18.3

**Comment by UragayalaDeepika** [comment]
@amorato Are you able to reproduce the issue? From the logs, it seems to be an issue with the Adcolony network. Can you add more details about the error if you are able to reproduce?

**Comment by amorato** [comment]
I can reproduce it when Adcolony's library is in the apk, even with the AdColony network disabled in admob dashboard. Playing with Adcolony libraries in the apk the crash appear easily 2 - 4 minutes after admob initialization.

We tried 3 different Adcolony latest versions as graphic show the app versions.

We didn't made any changes in apk when the crash appear on Crashlytics.

**Comment by UragayalaDeepika** [comment]
@amorato  As stack trace does contain our SDK symbols, we would need more information to debug this. Can you provide us any other details like the type of Ads that you are serving, a sample project to reproduce the issue locally?

**Comment by namquang93** [comment]
We got exactly the same error in our game which is using Admob v4.1.0, Facebook SDK 7.18.0 and Firebase 6.0.0.
