### ISSUE TITLE
Any plans for Advanced Native ads in Unity ?

### ISSUE THREAD

**Issue by Opeth001** [googleads/googleads-mobile-unity#1016]
Now that Admob is finally allowing users to use the Advanced Native Ads *_* ,
Do you have plans to add the Advanced NativeAds for unity ?

Thank you.

**Comment by Opeth001** [comment]
I found out that Google is already having an ads builder package for unity which can be used to create Advanced native ads.

**Comment by kimcollin** [comment]
YES
Kim Collins
