### ISSUE TITLE
Cant tell which AdMob version is on my app

### ISSUE THREAD

**Issue by rotter** [googleads/googleads-mobile-unity#1018]
Problem: I can never tell which AdMob version is installed on my several apps, so end up having to reinstall the plugin on each app to make sure it's on the latest version.

My suggestion is to add a file with the version name on the GoogleMobileAds folder, for example AdMobVersion_3_18_3.txt

And/or add the version number on the GoogleMobileAdsSettings panel.

**Comment by desouse** [comment]
Assets\GoogleMobileAds\Api\AdRequest.cs

public const string Version

**Comment by UragayalaDeepika** [comment]
@rotter closing this. Let us know if you have any questions.

**Comment by rotter** [comment]
Thanks for the workaround, but I still think the version should be way more visible.

It's highly unlikely that I will remember which class to look for the version next time I need it, or for anyone else to guess that's the place to look at when they need to know the version...

**Comment by UragayalaDeepika** [comment]
@rotter  Thank you. I will definitely pass this feedback to our team as a feature request.
