### ISSUE TITLE
iOS compiles fine but android fails using the latest version (3.18.3)

### ISSUE THREAD

**Issue by j4hangir** [googleads/googleads-mobile-unity#1019]
With the following error:
`D8: Program type already present: com.google.ads.AdRequest$ErrorCode`.

**Comment by j4hangir** [comment]
After lots of tedious research, I had to delete `play-services-basement-*.aar` and `*lite-ads` as they were having common classes with AdMob.

**Comment by UragayalaDeepika** [comment]
@j4hangir Closing this issue. Let us know if you have any other questions.
