### ISSUE TITLE
Difference Between RewardBasedVideoAd & RewardedAd

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#1023]
Anyone explain me Difference Between RewardBasedVideoAd & RewardedAd?
I previously use ( RewardBasedVideoAd rewardBasedVideo; ) for rewarded ads logic. which is working perfectly.
Today is see RewardedAd class used to show rewarded ads in GoogleMobileAdsDemoScript.cs (the demo script).
Please help. its confusing for me.

**Comment by UragayalaDeepika** [comment]
@MuhammadWaqasOfficial Google Mobile Ads SDK introduced a new set of rewarded ad APIs, currently in beta. you can go through [our documentation](https://developers.google.com/admob/unity/rewarded-ads) to learn more about our new rewarded APIs

**Comment by UragayalaDeepika** [comment]
@MuhammadWaqasOfficial Let me know if I can help you with anything else and let us know if this can be considered as closed?

**Comment by MuhammadWaqasOfficial** [comment]
Thanks for helping. I checked the doc. 
Yes close it
