### ISSUE TITLE
Error with plugin when creating new update for application

### ISSUE THREAD

**Issue by BlueSkyHugo** [googleads/googleads-mobile-unity#1024]
When I create a new update for my app and put it on Store CHPlay, the new update will be downloaded and overwritten by the existing user. This has ruined the Admob plugin. Those users who are already there cannot display the ad. Want to display it must be a new user, or have to remove old updates and new downloads but doing so will lose the data of the saved application. Does anyone have the same situation as me, and can share with me how to fix it.
Plugin v3.18.3

**Comment by UragayalaDeepika** [comment]
@BlueSkyHugo Can you please share any device logs provided by any of your users who are not seeing ads? We haven't heard about any issues similar to this. Also, can you please confirm what a CHPlay store means?

**Comment by BlueSkyHugo** [comment]
It is the Google Play store. All the devices I have are the same, every time I create a new update for my app everything returns to its original state. Can not show ads on returning users, only on new users.

**Comment by UragayalaDeepika** [comment]
@BlueSkyHugo This doesn't sound like an issue with our Unity Plugin. If you believe that it is an issue with the plugin, please share the error that is being caused by the plugin so that we can investigate this further. Can you also check if this issue is happening with latest Unity Plugin v4.0.0?
