### ISSUE TITLE
Rotation issue

### ISSUE THREAD

**Issue by kaufcom** [googleads/googleads-mobile-unity#1028]
Hi,

We have apps which have many mini-games inside. Some are in portrait. Some are in landscape.
Now we have the issue that when we make a rotation the ad is not rotating correctly.

You can try this on your example ("GoogleMobileAdsDemoScript.cs") just add an additiona button with this few lines of code in the OnGUI():

//-------------
		Rect screenLandscape = new Rect(
			columnTwoPosition,
			0.4f * Screen.height,
			buttonWidth,
			buttonHeight);
		if (GUI.Button(screenLandscape, "Rotate"))
		{
	
			if (Screen.orientation == ScreenOrientation.Portrait)
				Screen.orientation = ScreenOrientation.LandscapeLeft;
			else
				Screen.orientation = ScreenOrientation.Portrait;
		}
//-------------

Now when you rotate, destroy, request, show an ad, you will see, depending on how you hold the device, that the ad is wrong rotated. So for example it shows a landscape ad in portrait mode rotatet. If you then use REAL ads (also with adx/google ads) you will see that the ads definitivelly are breaking. You don't see the full ad, just a part of it (buttons out of screen)....

Am i doing something wrong, or is this a real issue?

Thanks for your help! I need urgent a solution here. :)
Cheers
Roberto

Just attached a foto of an old test device and how it can looks like.

![69fc89b4-12c9-46c0-8b78-a74a65503931](https://user-images.githubusercontent.com/4690476/66052146-66f47b00-e530-11e9-80b6-c70757ad142b.jpg)

**Comment by UragayalaDeepika** [comment]
@kaufcom Can you please share a screen recording and affected Ad unit Id for us to take a look? And, is this device specific and is this happening with any specific creative? I have tried to reproduce the issue with our sample script on our test device and was not able to reproduce the issue on our end with our test Ad unit Id. It would be helpful if you could provide us the requested details to investigate the issue.

**Comment by kaufcom** [comment]
Hi,
Thanks for your help. 
Ok so here a video of a test. I have taken this time a Nexus 5 for the test.
Some of the ads are affected, some not. Mostly it happens when rotating back from landscape to portrait. You will see in the video that the ads are not completely shown. They are cut on the sites. That's because landscape ads are shown in portrait mode or vice versa. I don't want to place my ad id in public.... as I can't send a pm with github, how can I give it over to you?
Anyways even with the demo ads that you get with the demo ad unity id, you see that the image is not filling the full screen sometimes. You can see the full ad but its not in the proper orientation format (It's not portrait with a portrait ad and vice versa).
Some side notes: The unity project is build with unity 2017.4 LTS and Default orientation is set to portrait.

[video.zip](https://github.com/googleads/googleads-mobile-unity/files/3691309/video.zip)

**Comment by kaufcom** [comment]
Any news?

**Comment by kaufcom** [comment]
Hi,
After updating unity 2017.4 and all ad stuff, it works now.
Thx.
