### ISSUE TITLE
AppLovin Mediation Adaptor Update to use iOS SDK 6.9.3 ?

### ISSUE THREAD

**Issue by Spud6703** [googleads/googleads-mobile-unity#1029]
Can somebody please update the GoogleMobileAdsAppLovinMediation adaptor for Unity so that it uses AppLovin's latest iOS 6.9.3 SDK ? I've tried using 4.2.0 of the mediation adaptor and I get errors in my iOS debug output log that AppLovin says will only be fixed if I use their 6.9.3 SDK

**Comment by UragayalaDeepika** [comment]
@Spud6703 I have shared this with the team and they will update this asap. Will keep you posted once it is updated.

**Comment by Spud6703** [comment]
@UragayalaDeepika  Okay thanks! I have confirmed that simply copying the latest 6.9.3 AppLovin SDK framework over the older one that the mediation adaptor CocoaPods thing puts into the XCode build fixes the problem so hopefully it will be a simple fix for your team. It is a bit of a pain to have to do this every time I make a Unity build though so hopefully this can be fixed fairly quickly so it's all automated.
