### ISSUE TITLE
App crash on first Rewarded Ads request

### ISSUE THREAD

**Issue by DrVallo** [googleads/googleads-mobile-unity#1032]
I use the latest version of the plugin (4.0.0), the latest stable Unity version (2019.2.8f1) and the lastes version of Xcode.
When I install my game and start it for the first time on an iOS device (tested on iPhone 6s and iPhone 11 Pro with the latest version of iOS 13 installed), at the first request of a Rewarded Ads, the game crashes. There is no problem with requests for normal banners.
Once the app crashes, if the game is re-run multiple times, the Rewarded Ads are shown without problems. The problem occurs only at the absolute first request.
On Android the problem does not occur.
I leave the Xcode screens that are shown to me when the app is tested and crashed.
![image3 (1)](https://user-images.githubusercontent.com/50541389/66269004-826ac900-e843-11e9-830b-f6a0cccb7aac.jpeg)
![image1 (1)](https://user-images.githubusercontent.com/50541389/66269006-826ac900-e843-11e9-90a4-e41476cfc516.jpeg)
![image2 (1)](https://user-images.githubusercontent.com/50541389/66269007-83035f80-e843-11e9-9a61-f7b2af09f424.jpeg)
![image0](https://user-images.githubusercontent.com/50541389/66269009-83035f80-e843-11e9-8b5a-6dd5ca4b0587.jpeg)

The request for Rewarded Ads is carried out following the example in the [official guide](https://developers.google.com/admob/unity/rewarded-ads): [My code on pastebin](https://pastebin.com/Pcty4Vmi)
I can't understand why the crash occurs only at the first absolute start of the app, and the following times everything works perfectly.

**Comment by UragayalaDeepika** [comment]
@DrVallo I don't notice any specific issue with your code snippet. However, can you send any more crash logs that you may have? The screenshots you have provided does not indicate that this might be an issue with the SDK. Or  Can provide us a sample app that is able to reproduce this issue locally?

**Comment by DrVallo** [comment]
@UragayalaDeepika Unfortunately it is the first time I use Xcode to export to iOS, so I don't know where to find the crash logs that can be useful.

If it is possible to receive a private email I can send you my project, even if I have already sent the code I use to request advertisements.
I think it would be enough to install the latest stable Unity version, import the Unity AdMob v4.0.0 plugin, use my code, and export to iOS using the latest version of Xcode.

I did a lot of testing these days, but I couldn't solve the problem. I just can't understand why the game crashes only the first time I request a RewardedAd after installing the app. Subsequently, after restarting the app, the RewardedAd is always displayed without problems. Instead, normal banners have no problem.

**Comment by stowy** [comment]
@DrVallo can you please try Unity version 2019.1.11f1? And also iOS 12 -
and advise if the crash occurs with either of these variants?

Also, the crash logs should appear in the console at the bottom right panel
in Xcode. These would be helpful to include.

**Comment by DrVallo** [comment]
@stowy Unfortunately I developed my app with Unity 2019.2.x, and it is not possible for me to downgrade the version (if I try to open the project with previous versions I get an error message). I also have only two Apple devices available with iOS 13, and I don't know if it's possible to downgrade to iOS 12.
Tonight I will try to make a new test to copy the crash log you indicated to me, but as you can see from the screen, there doesn't seem to be much text.

**Comment by stowy** [comment]
Thanks @DrVallo, there should definitely be some logs in the console if you
turn off debug breakpoints. Please share what you have.

Additionally, you can send us a sample project (just the assets folder
should be fine, host it on Google drive for example and share the link).

You can download and run iOS 12 simulators for example.

Thanks

Sam

**Comment by DrVallo** [comment]
@stowy I just created a new simple Unity project, entering my current code, and adapting it for a quick test. For security reasons I have not entered the "Admob App ID". 
Download link: https://drive.google.com/drive/folders/1BVmri6x1zMUMcslLbkLR6-Icd8cAkSu4?usp=sharing

As for the crash log, I'll get it to you as soon as possible. I've just formatted my mac and I'm reinstalling everything, with the latest updates. I will try as soon as possible to test using the iOS 12 Simulator (which until now I didn't know it existed within Xcode).

**Comment by DrVallo** [comment]
@stowy @UragayalaDeepika Full log with crash log: https://pastebin.com/7ZjpFuV2

**Comment by DrVallo** [comment]
@stowy @UragayalaDeepika New device crash log: https://pastebin.com/VDtjpQ01
I tried to do other tests, but I can't understand what the problem is. The crash happens only when the app is started for the first time ever, and a rewarded ads is requested. After the crash if the app is reopened the problem no longer occurs. After the first crash, even if the iPhone is restarted, the problem no longer occurs.

**Comment by DrVallo** [comment]
@UragayalaDeepika 
I kept doing tests with the code, and I made a discovery.
Most likely the "handles" make the game crash!
Look at the code below that I tried to write.
Now the ad is shown correctly the first time the game is started (I didn't use "HandleRewardedAdLoaded"), but the game crashes when the ad is closed.

I have been trying to solve this serious problem for weeks, which does not allow me to publish my game. Can you check if I could find the problem, and tell me how I can solve it?

```using System;
using UnityEngine;
using System.Collections;
using GoogleMobileAds.Api;

public class AdMob : MonoBehaviour
{
    private static BannerView bannerView;
    private static RewardedAd rewardedAd;
#if UNITY_IOS
    private bool adsSeeComplete;
#endif
    [SerializeField] GameObject menuUi;
    [SerializeField] GameObject panelGameMode;
    [SerializeField] GameObject loadingPanel;
    [SerializeField] GameObject themeController;

    void Start()
    {
        if (SecurePlayerPrefs.GetInt("RemoveAds", 0) == 0)
        {
            RequestBanner();
        }
    }

    private void RequestBanner()
    {
#if UNITY_ANDROID
        string adUnitId = "**";
#elif UNITY_IOS
        string adUnitId = "**";
#else
        string adUnitId = "unexpected_platform";
#endif
        if (bannerView != null)
        {
            bannerView.Destroy();
        }
        // Create a 320x50 banner at the top of the screen.
        bannerView = new BannerView(adUnitId, AdSize.Banner, AdPosition.Top);

        // Create an empty ad request.
        if (SecurePlayerPrefs.GetInt("AdsPersonalized") == 1)
        {
            AdRequest request = new AdRequest.Builder().AddExtra("max_ad_content_rating", "PG").Build();
            // Load the banner with the request.
            bannerView.LoadAd(request);
        }
        else
        {
            AdRequest request = new AdRequest.Builder().AddExtra("npa", "1").AddExtra("max_ad_content_rating", "PG").AddExtra("tag_for_under_age_of_consent", "true").Build();
            // Load the banner with the request.
            bannerView.LoadAd(request);
        }
    }

    public void BannerRemove()
    {
        if (bannerView != null)
        {
            bannerView.Destroy();
        }
    }

    public void RequestRewardedAd()
    {
#if UNITY_ANDROID
        string adUnitId = "**";
#elif UNITY_IOS
        string adUnitId = "**";
#else
            string adUnitId = "unexpected_platform";
#endif
        rewardedAd = new RewardedAd(adUnitId);
        // Called when the user should be rewarded for interacting with the ad.
        rewardedAd.OnUserEarnedReward += HandleUserEarnedReward;
        // Called when the ad is closed.
        rewardedAd.OnAdClosed += HandleRewardedAdClosed;

        ChangeButtonInteraction(0);

        // Create an empty ad request.
        if (SecurePlayerPrefs.GetInt("AdsPersonalized") == 1)
        {
            AdRequest request = new AdRequest.Builder().AddExtra("max_ad_content_rating", "PG").Build();
            // Load the banner with the request.
            rewardedAd.LoadAd(request);
        }
        else
        {
            AdRequest request = new AdRequest.Builder().TagForChildDirectedTreatment(true).AddExtra("npa", "1").AddExtra("max_ad_content_rating", "PG").AddExtra("tag_for_under_age_of_consent", "true").Build();
            // Load the banner with the request.
            rewardedAd.LoadAd(request);
        }
        StartCoroutine(ShowAds());
    }
    IEnumerator ShowAds()
    {
        yield return new WaitUntil(() => rewardedAd.IsLoaded() == true);
        rewardedAd.Show();
    }

    public void HandleRewardedAdClosed(object sender, EventArgs args)
    {
#if UNITY_IOS
        themeController.GetComponent<MusicThemeController>().PauseMusic(false);
        if (adsSeeComplete)
        {
            loadingPanel.SetActive(false);
            panelGameMode.GetComponent<ButtonMode>().StartSuperChallengeMode();
        }
        else
        {
            loadingPanel.GetComponent<LoadingMenu>().sentenceType = 1;
            loadingPanel.GetComponent<LoadingMenu>().ReceiveErrorMessage();
        }
#else
        loadingPanel.GetComponent<LoadingMenu>().sentenceType = 1;
        loadingPanel.GetComponent<LoadingMenu>().ReceiveErrorMessage();
#endif
    }

    public void HandleUserEarnedReward(object sender, Reward args)
    {
#if UNITY_IOS
        adsSeeComplete = true;
#else
        loadingPanel.SetActive(false);
        panelGameMode.GetComponent<ButtonMode>().StartSuperChallengeMode();
#endif

    }
}```

**Comment by DrVallo** [comment]
@stowy @UragayalaDeepika 
Sorry for the trouble, but I wanted to know if there is any news about it. Unfortunately I can't solve the problem, and I can't publish my game.

**Comment by DongerGroup** [comment]
I have the same issue in 2019.2.10f,iOS building.

**Comment by DongerGroup** [comment]
Now I solved this problem i met

**Comment by QuanHuynhM** [comment]
@DongerGroup  I have the same issue in 2019.2.17f,iOS building. Can you suggest me solution?

**Comment by nkarabulut** [comment]
> Now I solved this problem i met

Can you share it briefly ?

**Comment by crazy78cyxapuk** [comment]
> Теперь я решил эту проблему, которую я встретил

Help pls, tell me how to fix it

**Comment by NVentimiglia** [comment]
Closing stale issue. Please update and if still an issue please reopen.
