### ISSUE TITLE
Unity Ads - Consent Ad on iOS 13

### ISSUE THREAD

**Issue by manelizzard** [googleads/googleads-mobile-unity#1038]
As per https://forum.unity.com/threads/unity-ads-dont-work-properly-on-ios-13-beta.743201/, seems there is a bug in Unity Ads and iOS 13 not showing the Consent Ad.

I guess Unity Ads should be fixed by their owners but, should **googleads-mobile-unity** update its Unity Ads mediation library once the fix is released?

**Comment by UragayalaDeepika** [comment]
@manelizzard We will make sure to update the libraries according to the latest releases
