### ISSUE TITLE
undefined symbols compiling for ios

### ISSUE THREAD

**Issue by VincentBaillet** [googleads/googleads-mobile-unity#1040]
Hi,
I try to compile the IOS version of my game, but I'm experiencing 80 undefined symbols, all related to admob (their name starting by _GADU, see screenshot for a list of some problems )
The Android version of my game works perfectly, and it as been quite simple to implement Admob for banners and rewarded-videos. 
I suppose there are some library missing, but internet gives me no clues to solve the problem.
I'm not so familiar with cocoapods, maybe i'm missing something...
need some help please.

![Capture d’écran 2019-10-17 à 17 38 21](https://user-images.githubusercontent.com/11924925/67024622-02771580-f105-11e9-94c9-8c6d6bad6593.png)

**Comment by VincentBaillet** [comment]
the problem has been resolved by removing everything related to admob in my project, then re-installing step by step the admob plugin.

**Comment by UragayalaDeepika** [comment]
@VincentBaillet closing the issue.Feel free to comment here so that we can reopen if you need anything.
