### ISSUE TITLE
IL2CPP Scripting Backend ARM64 Error - Unity 2019.1.0f2 Google Mobile Ads Sdk

### ISSUE THREAD

**Issue by adnanmiczon** [googleads/googleads-mobile-unity#1041]
i have downloaded google mobile ads Sdk for native ads from here (NATIVE ADS BUILD Unity pakage-which support native ads)

https://developers.google.com/admob/unity/native-advanced-unified

Then i am integrating in Unity 2019.1.0f2 (64-bit). Setup everything it work fine on Mono but when i change to 64-bit build for final uploading
During building apk Unity Stucks on Building native binary with IL2CP...

After that Unity Gives this Error

Failed running C:\Program Files\Unity\Editor\Data\il2cpp/build/il2cpp.exe --convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARMv7" --configuration="Release" --outputpath="F:\RaceAwardWin\Temp\StagingArea\assets\bin\Data\Native\armeabi-v7a\libil2cpp.so" --cachedirectory="F:\RaceAwardWin\Assets..\Library\il2cpp_android_armeabi-v7a/il2cpp_cache" --additional-include-directories="C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\bdwgc/include" --additional-include-directories="C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\libil2cpp/include" --tool-chain-path="F:/android-ndk-r16b-windows-x86_64/android-ndk-r16b" --profiler-report --map-file-parser="C:/Program Files/Unity/Editor/Data/Tools/MapFileParser/MapFileParser.exe" --directory=F:/RaceAwardWin/Temp/StagingArea/assets/bin/Data/Managed --generatedcppdir=F:/RaceAwardWin/Temp/StagingArea/Il2Cpp/il2cppOutput

stdout:

Building libil2cpp.so with AndroidToolChain

Output directory: F:\RaceAwardWin\Temp\StagingArea\assets\bin\Data\Native\armeabi-v7a

Cache directory: F:\RaceAwardWin\Library\il2cpp_android_armeabi-v7a\il2cpp_cache

ObjectFiles: 235 of which compiled: 219

Time Compile: 25560 milliseconds Il2CppAttributes.cpp

Time Compile: 17582 milliseconds Il2CppCompilerCalculateTypeValues1.cpp

Time Compile: 15864 milliseconds Il2CppTypeDefinitions.c

Time Compile: 15672 milliseconds Il2CppMetadataUsage.c

Time Compile: 14089 milliseconds Assembly-CSharp3.cpp

Time Compile: 10597 milliseconds ProBuilderCore-Unity5.cpp

Time Compile: 9720 milliseconds Il2CppInvokerTable.cpp

Time Compile: 5484 milliseconds Generics18.cpp

Time Compile: 5444 milliseconds ProBuilderCore-Unity51.cpp

Time Compile: 5388 milliseconds mscorlib3.cpp

Total compilation time: 151626 milliseconds.

il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: F:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ @"C:\Users\Miczon LLP\AppData\Local\Temp\tmpEC90.tmp" -o "F:\RaceAwardWin\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\linkresult_F69D8FD532EC526F74AA591119FF6C7F\libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id --sysroot "F:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\platforms\android-16\arch-arm" -gcc-toolchain "F:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" -target armv7-none-linux-androideabi -Wl,--wrap,sigaction -L "F:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a" -lgnustl_static -llog -rdynamic -fuse-ld=gold.exe

F:\RaceAwardWin\Temp\StagingArea\Il2Cpp\il2cppOutput/GoogleMobileAds2.cpp:14500: error: undefined reference to 'GADURelease'

F:\RaceAwardWin\Temp\StagingArea\Il2Cpp\il2cppOutput/GoogleMobileAds2.cpp:14500: error: undefined reference to 'GADURelease'

F:\RaceAwardWin\Temp\StagingArea\Il2Cpp\il2cppOutput/GoogleMobileAds2.cpp:15023: error: undefined reference to 'GADUCreateRewardedAd'

F:\RaceAwardWin\Temp\StagingArea\Il2Cpp\il2cppOutput/GoogleMobileAds2.cpp:14500: error: undefined reference to 'GADURelease'

F:\RaceAwardWin\Temp\StagingArea\Il2Cpp\il2cppOutput/GoogleMobileAds2.cpp:15023: error: undefined reference to 'GADUCreateRewardedAd'

F:\RaceAwardWin\Temp\StagingArea\Il2Cpp\il2cppOutput/GoogleMobileAds2.cpp:15101: error: undefined reference to 'GADUSetRewardedAdCallbacks'

F:\RaceAwardWin\Temp\StagingArea\Il2Cpp\il2cppOutput/GoogleMobileAds2.cpp:15065: error: undefined reference to 'GADURequestRewardedAd'

F:\RaceAwardWin\Temp\StagingArea\Il2Cpp\il2cppOutput/GoogleMobileAds2.cpp:14500: error: undefined reference to 'GADURelease'

F:\RaceAwardWin\Temp\StagingArea\Il2Cpp\il2cppOutput/GoogleMobileAds2.cpp:14302: error: undefined reference to 'GADUCreateRequest'

F:\RaceAwardWin\Temp\StagingArea\Il2Cpp\il2cppOutput/GoogleMobileAds2.cpp:14400: error: undefined reference to 'GADUAddKeyword'

F:\RaceAwardWin\Temp\StagingArea\Il2Cpp\il2cppOutput/GoogleMobileAds2.cpp:14380: error: undefined reference to 'GADUAddTestDevice'

F:\RaceAwardWin\Temp\StagingArea\Il2Cpp\il2cppOutput/GoogleMobileAds2.cpp:14428: error: undefined

Unity Generates some files in Temp. GoogleMobileAds2 file. i dnt knw why it is generating this file on runtime

i dont have any IOS file in my project, i already tried with different versions of unity and try every thing which mention on different forums. but my problem does not solved.
please help in this matter

**Comment by Hardik-Nadiyapara** [comment]
@adnanmiczon ,
i am facing same errors , any one have solution for this ?

**Comment by stowy** [comment]
should be fixed in latest version of the plugin.
