### ISSUE TITLE
Can't play sound in callback function

### ISSUE THREAD

**Issue by chenf33** [googleads/googleads-mobile-unity#1042]
It seems that if I play sound in callback function,game crash.
HandleUserEarnedReward,HandleRewardedAdClosed,HandleXX all will do.

**Comment by thanhtoan88** [comment]
My experience, you should call the function to play the music after a few seconds, you should use "Invoke"

**Comment by chenf33** [comment]
Thank you,I will have a try.

**Comment by DrVallo** [comment]
> My experience, you should call the function to play the music after a few seconds, you should use "Invoke"

@thanhtoan88 Could you explain yourself better? Can you leave a piece of code showing how you applied your system to resolve the error?

Thanks! :)
