### ISSUE TITLE
Admob breaks with IL2CPP stripping level Medium or High when using Early Access SDK

### ISSUE THREAD

**Issue by Arrnav** [googleads/googleads-mobile-unity#1043]
I'm using the early access SDK because I'm using Adaptive banner ads.

The issue is the exact same one found [here](https://github.com/googleads/googleads-mobile-unity/issues/832). (Issue #832), except this time around it's happening with the latest early access SDK and NOT v4.0.0

[This](https://developers.google.com/admob/unity/early-access/adaptive-banners) is where I obtained the early access GMA SDK from - 

Unity: 2019.2.9f1, Android
AdMob: Early Access SDK obtained from above guide link (I assume this should be updated as much as the v4.0.0?)
Stripping level: Medium or High

Adding Preserve attribute to any GMA related class does nothing. Still throws the null reference error.

Turning down to "Low" stripping level causes GMA to work again, but is not an option as the minor reduction in size matters in this build. Neither does link.xml work.

Please help.

**Comment by UragayalaDeepika** [comment]
@Arrnav Hi arnav Can you please share a sample project for us to take a look? You can send the details to mobileadstesting99@gmail.com if you are not comfortable sharing here.

**Comment by stowy** [comment]
This may be fixed in latest version of the plugin, please retest.
