### ISSUE TITLE
No show all ads in android!

### ISSUE THREAD

**Issue by thanhtoan88** [googleads/googleads-mobile-unity#1044]
First, I use the default ad admod id ( id ads test from google). Everything shows up perfectly!

but then i changed all my ads id, they are not displayed, my ads id is still showing on the old project, with the old admod sdk !.

so what is wrong? Please help me, thanks!

**Comment by UragayalaDeepika** [comment]
@thanhtoan88 Please reachout to [Mobile Ads SDK [Forum]](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) and our team will be able to help you out with debugging the issue.
