### ISSUE TITLE
Adaptive Banner unity 

### ISSUE THREAD

**Issue by MonierHossam** [googleads/googleads-mobile-unity#1046]
Trying to use Adaptive banner ad in unity and i used latest plugin but it give me error (AdSize' does not contain a definition for 'GetCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth').

**Comment by danielpdev** [comment]
@MonierHossam The change got introduced 2 days ago on master branch and there was not yet a package for unity released.

However, you can check here the implementation of GetCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth from AdSize https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Api/AdSize.cs

This is the commit that introduced the change and you could just use this implementation if you don't want to wait for final release of the package: https://github.com/googleads/googleads-mobile-unity/commit/9ed7018e3c63924dbda4748b5c640f9b30fbe808


Thanks and hope it clears your issue.

**Comment by MonierHossam** [comment]
@danielpdev will try it out, Thank you for your answer

**Comment by stowy** [comment]
Thanks @danielpdev, yes @MonierHossam it is not released yet, I plan to
create a release today.

**Comment by stowy** [comment]
Published v4.1.0 - https://github.com/googleads/googleads-mobile-unity/releases/tag/v4.1.0
