### ISSUE TITLE
RewardedAd causing stall/crash after device goes to sleep mode(Android)

### ISSUE THREAD

**Issue by yasirkula** [googleads/googleads-mobile-unity#1048]
Basically, after loading a rewarded video ad with **RewardedAd**, if device goes to sleep before the video is shown (my device goes to sleep mode if I don't touch anything for 30 seconds), either Unity stalls for a while or crashes after the screen is unlocked. This doesn't happen when using **RewardBasedVideoAd**.

Tested on:

> Samsung Galaxy S8 (SM-G950F)
> Unity 2017.2.0f3, 2018.4.8f1, 2019.1.8f1
> Mono scripting backend
> Gradle build system
> No minification
> No managed code stripping

Here's my test script. Pressing "Load 2" button and locking the screen after the button's label changes to "Show 2" will reproduce this issue. It doesn't happen with the "Load 1" button. 

```csharp
using GoogleMobileAds.Api;
using UnityEngine;

public class RewardedAdTest : MonoBehaviour
{
	private RewardedAd rewardedAd;

	private void Start()
	{
		MobileAds.Initialize( ( status ) => { } );
	}

	private void OnGUI()
	{
		Rect button1 = new Rect( 0, 0, Screen.width, Screen.height / 3f );
		Rect timer = new Rect( 0, Screen.height / 3f, Screen.width, Screen.height / 3f );
		Rect button2 = new Rect( 0, Screen.height * 2 / 3f, Screen.width, Screen.height / 3f );

		GUI.Box( timer, "FRAME: " + Time.frameCount );

		if( RewardBasedVideoAd.Instance.IsLoaded() )
		{
			if( GUI.Button( button1, "Show1" ) )
				RewardBasedVideoAd.Instance.Show();
		}
		else
		{
			if( GUI.Button( button1, "Load1" ) )
				RewardBasedVideoAd.Instance.LoadAd( new AdRequest.Builder().Build(), "ca-app-pub-3940256099942544/5224354917" );
		}

		if( rewardedAd != null && rewardedAd.IsLoaded() )
		{
			if( GUI.Button( button2, "Show2" ) )
			{
				rewardedAd.Show();
				rewardedAd = null;
			}
		}
		else
		{
			if( GUI.Button( button2, "Load2" ) )
			{
				rewardedAd = new RewardedAd( "ca-app-pub-3940256099942544/5224354917" );
				rewardedAd.LoadAd( new AdRequest.Builder().Build() );
			}
		}
	}
}
```

**Comment by UragayalaDeepika** [comment]
@yasirkula Hello I don't see any issue with the latest plugin. Can you please share the crash logs for us to take a look? Also, please share a sample project which reliably reproduces the issue. You can share it to mobileadstesting@gmail.com

**Comment by yasirkula** [comment]
I couldn't reproduce the crash but the stall can definitely be reproduced (`Samsung Galaxy S8 (SM-G950F)`). Here's the sample project (uses test ids): [AdmobIssueRepro.zip](https://github.com/googleads/googleads-mobile-unity/files/3801680/AdmobIssueRepro.zip)

Pressing "Load 2" button and locking the screen after the button's label changes to "Show 2" will cause the stall. It doesn't happen with the "Load 1" button.
