### ISSUE TITLE
Multiple Plugin and AndroidManifest.xml 

### ISSUE THREAD

**Issue by uokivan** [googleads/googleads-mobile-unity#1057]
I install the firebase push Messaging before, 
How can I install this admob ?
and how to update / renew the AndroidManifest.xml ?

Thanks a lot

**Comment by UragayalaDeepika** [comment]
@uokivan You can follow the guidelines as mentioned here: https://developers.google.com/admob/unity/start and the plugin would automatically update what's required in the project. If you are using Unity 4, then you would have to follow this additional step as well: https://developers.google.com/admob/unity/start#unity_4_compatibility.
