### ISSUE TITLE
GADUBanner.m error GADAdMObExtras.h not found

### ISSUE THREAD

**Issue by Kulgann** [googleads/googleads-mobile-unity#106]
This is the only issue I have with the  mobile ads sdk and the unity3d plugin. I have spent the last 2 hours on the web searching for a solution and nothing seems to work. I have followed the steps for implementing the SDK correctly and I think I have done everything else the right way. Has someone had this issue before and how do I fix it ?

**Comment by rampara** [comment]
Are you using the most up to date package for Google Mobile Ads plugin? GADUBanner.m doesn't use GADAdMobExtras.

- Ram

**Comment by rampara** [comment]
This issue is being closed due to its age. If this problem persists, please re-open the issue.
