### ISSUE TITLE
Unity Admob Mediation TestSuite CRASH!

### ISSUE THREAD

**Issue by Antik22** [googleads/googleads-mobile-unity#1064]
Hi there, I have Unity (2019.1.7f1) project where I tried to implement Google Admob Ads by Mediation (I want to use these networks: Facebook Ads, AppLovin, Unity Ads, ironSource, Vungle). Before this I successfully implemented Admob Ads without mediation, everything was working fine. Then I made everything like in integration guide (https://developers.google.com/admob/unity/mediate): imported Admob sdk (update), 5 sdks for networks mentioned above (latest) , added appId to settings and imported TestSuite (1.2.0) package for Unity.
I had a lot of problems to build and run .apk (issues with resolver and crash after launch) and finally when I ran it and it is crashing after MediationTestSuite.Show().

Here is full log from device:
> FATAL EXCEPTION: main
> 11-05 17:13:30.080   418   418 E AndroidRuntime: Process: com.simplay.rainball, PID: 418
> 11-05 17:13:30.080   418   418 E AndroidRuntime: java.lang.AssertionError: AssertionError (GSON 2.8.5): java.lang.NoSuchFieldException: ERROR
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:944)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:892)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:841)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.android.ads.mediationtestsuite.utils.n.a(MediationConfigClient.java:150)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.android.ads.mediationtestsuite.utils.n.a(MediationConfigClient.java:95)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.android.ads.mediationtestsuite.dataobjects.DataStore.a(DataStore.java:174)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.android.ads.mediationtestsuite.activities.HomeActivity.onCreate(HomeActivity.java:56)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7136)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7127)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: Caused by: java.lang.AssertionError: java.lang.NoSuchFieldException: ERROR
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.T$a.<init>(TypeAdapters.java:792)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapters$30.a(TypeAdapters.java:818)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:458)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:117)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:166)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:102)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:458)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:117)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:166)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:102)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:458)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.a(CollectionTypeAdapterFactory.java:53)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:458)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:117)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:166)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:102)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:458)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.a(CollectionTypeAdapterFactory.java:53)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:458)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:926)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	... 21 more
> 11-05 17:13:30.080   418   418 E AndroidRuntime: Caused by: java.lang.NoSuchFieldException: ERROR
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at java.lang.Class.getField(Class.java:1601)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.T$a.<init>(TypeAdapters.java:781)
> 11-05 17:13:30.080   418   418 E AndroidRuntime: 	... 40 more

Also Ads don't work at all. Nothing in console.
Run on emulator Nexus 5X (API 28)
Built by IL2CPP, .Net 4.x, Gradle 5.6.0. Added Proguard file for com.google.android.gms.ads.**, com.google.unity.**. Tested in development mode and released.
Hope for your help, thanks.

**Comment by stowy** [comment]
Hi, can you please share a sample project for this? This seems unexpected.

**Comment by Antik22** [comment]
> Hi, can you please share a sample project for this? This seems unexpected.

Hey, can you give your email and I will send you the link? I don't want to share it here.

**Comment by stowy** [comment]
Sure, send to  mobileads-sdk-support@google.com, and please reference this
issue.

**Comment by UragayalaDeepika** [comment]
Ref : https://groups.google.com/forum/#!searchin/google-admob-ads-sdk/Google$20TestSuite$20Mediation$20Crash%7Csort:date/google-admob-ads-sdk/Tuh_wm4pbyo/yQ72bU4RAAAJ

**Comment by rohitvishwakarma1819** [comment]
> > Hi, can you please share a sample project for this? This seems unexpected.
> 
> Hey, can you give your email and I will send you the link? I don't want to share it here.



> Hi there, I have Unity (2019.1.7f1) project where I tried to implement Google Admob Ads by Mediation (I want to use these networks: Facebook Ads, AppLovin, Unity Ads, ironSource, Vungle). Before this I successfully implemented Admob Ads without mediation, everything was working fine. Then I made everything like in integration guide (https://developers.google.com/admob/unity/mediate): imported Admob sdk (update), 5 sdks for networks mentioned above (latest) , added appId to settings and imported TestSuite (1.2.0) package for Unity.
> I had a lot of problems to build and run .apk (issues with resolver and crash after launch) and finally when I ran it and it is crashing after MediationTestSuite.Show().
> 
> Here is full log from device:
> 
> > FATAL EXCEPTION: main
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: Process: com.simplay.rainball, PID: 418
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: java.lang.AssertionError: AssertionError (GSON 2.8.5): java.lang.NoSuchFieldException: ERROR
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:944)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:892)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:841)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.android.ads.mediationtestsuite.utils.n.a(MediationConfigClient.java:150)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.android.ads.mediationtestsuite.utils.n.a(MediationConfigClient.java:95)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.android.ads.mediationtestsuite.dataobjects.DataStore.a(DataStore.java:174)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.android.ads.mediationtestsuite.activities.HomeActivity.onCreate(HomeActivity.java:56)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7136)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7127)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: Caused by: java.lang.AssertionError: java.lang.NoSuchFieldException: ERROR
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.T$a.(TypeAdapters.java:792)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapters$30.a(TypeAdapters.java:818)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:458)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:117)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:166)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:102)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:458)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:117)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:166)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:102)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:458)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.a(CollectionTypeAdapterFactory.java:53)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:458)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:117)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:166)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:102)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:458)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.a(CollectionTypeAdapterFactory.java:53)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:458)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at c.c.d.q.a(Gson.java:926)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	... 21 more
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: Caused by: java.lang.NoSuchFieldException: ERROR
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at java.lang.Class.getField(Class.java:1601)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	at com.google.gson.internal.bind.T$a.(TypeAdapters.java:781)
> > 11-05 17:13:30.080   418   418 E AndroidRuntime: 	... 40 more
> 
> Also Ads don't work at all. Nothing in console.
> Run on emulator Nexus 5X (API 28)
> Built by IL2CPP, .Net 4.x, Gradle 5.6.0. Added Proguard file for com.google.android.gms.ads.**, com.google.unity.**. Tested in development mode and released.
> Hope for your help, thanks.

Hey @Antik22  Did you solve the problem ?

**Comment by yanickch** [comment]
I am having the same Issue as Antik22, what was the solution for this Problem?

**Comment by yanickch** [comment]
My Unity Version is 2019.3.13f
