### ISSUE TITLE
banner rotation for landscape orientation

### ISSUE THREAD

**Issue by NMHoang05** [googleads/googleads-mobile-unity#1065]
Hello!
I want to apply Admob to my project. I followed the guide [here](https://developers.google.com/admob/unity/test-ads), the test banner displays properly in portrait orientation but in landscape orientation, it's not what I want, please check the following image:

![google admob banner](https://user-images.githubusercontent.com/20160088/68308038-c10fcf80-00de-11ea-8440-dd556138751b.png)

is there a way I can rotate the banner 90 degree?

also is it possible to scale the banner?

**Comment by NMHoang05** [comment]
is this possible?

I tried Adsize = 50, 320 but the ads failed to load with error `no fill`

**Comment by karam89** [comment]
Hello,
Were you able to show banners this way?

**Comment by NMHoang05** [comment]
Hi, 
unfortunately, I'm not able to show the banners this way.

**Comment by stowy** [comment]
this would require a different banner size assuming the rest of your game rotates, and AdMob does not have this ad size as it's not a common use case on Mobile.

**Comment by karam89** [comment]
BTW: I was able to show ads :)

You should give the banner an enough width, like 120 or 160, and the height you wish 

so it becomes a skyscraper (not a banner)

**Comment by maxammadjon95** [comment]
> BTW: I was able to show ads :)
> 
> You should give the banner an enough width, like 120 or 160, and the height you wish
> 
> so it becomes a skyscraper (not a banner)

Hello Karam.
Could you tell me how you did? I tried 120/160 but banner doesn't show. 
And I couldn't find how to place the banner into Right Center. There are options: center, bottom, top, top right, bottom right, top left, bottom left.
I want to show banner exactly as **_NMHoang05_** asked, only on right corner of screen.
