### ISSUE TITLE
Adaptive Banner Portrait Reflection Error

### ISSUE THREAD

**Issue by rotter** [googleads/googleads-mobile-unity#1067]
When using Adaptive banner, if I call the method AdSize.GetPortraitAnchoredAdaptiveBannerAdSizeWithWidth I get the following exception:

AndroidJavaException: java.lang.NoSuchMethodError: no static method with name='getPortaitBannerAdSizeWithWidth' signature='(Lcom.unity3d.player.UnityPlayerActivity;I)Ljava/lang/Object;' in class Ljava.lang.Object;
    java.lang.NoSuchMethodError: no static method with name='getPortaitBannerAdSizeWithWidth' signature='(Lcom.unity3d.player.UnityPlayerActivity;I)Ljava/lang/Object;' in class Ljava.lang.Object;

Note: if I call the method AdSize.GetCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth it works fine and I dont get any exception

**Comment by rotter** [comment]
Obs: I havent tested the other method (GetLandscape...), so it might be bugged as well

**Comment by stowy** [comment]
Thanks for reporting. I can confirm that this is a bug with the Android
implementation for portrait.  I'll provide a fix in the next update.

If you want to fix it locally then the line at
https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Platforms/Android/Utils.cs#L131
should
be:

return adSizeClass.CallStatic<AndroidJavaObject>("
getPortraitBannerAdSizeWithWidth", activity, adSize.Width);

'Portrait' was mispelled. The joys of reflection.

Cheers
Sam
