### ISSUE TITLE
Native Ads - No fill even with test adunit id

### ISSUE THREAD

**Issue by rotter** [googleads/googleads-mobile-unity#1077]
I am trying to implement Native Ads on a new game, but I cant test it, I always get "no fill" error.

I tried, without success:
- adding my device with addTestDevice
- removing any calls to addTestDevice (I read somewhere that in the past Native couldnt have addTestDevice or it would return nofill)
- using the test ad unit id for Native ( ca-app-pub-3940256099942544/2247696110 )
- using both the test ad unit and addTestDevice
- using my own "real" ad unit id (with and without addTestDevice)

I have it already implemented on another game, so Im pretty sure all the rest is fine (or at least used to work a few months ago), but I can paste here my code if needed.

Any ideas?

**Comment by UragayalaDeepika** [comment]
@rotter Please post your Ad serving issue or any other SDK related issues on our [Mobile Ads SDK forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) so that our team will assist you further.

**Comment by rotter** [comment]
Well, I dont know for sure that it's SDK related, it could very well be something caused by the plugin. But if you're so sure this bug isnt related to the plugin, I can certainly post it on the provided forum/link, thanks.
