### ISSUE TITLE
MobileAdsMediationTestSuite 1.2.1 not building on Android

### ISSUE THREAD

**Issue by rlehmannJC** [googleads/googleads-mobile-unity#1085]
The MobileAdsMediationTestSuite 1.2.1 fails the gradle build step, with the following exception:
**Exception while processing task java.io.IOException: proguard.ParseException: Expecting opening '{' at '\*\*' in line 45 of file '/Users/jenkins/.gradle/caches/transforms-2/files-2.1/70789f5548d8ad34604c5ef31e6c9c72/proguard.txt'**

The file looks like that:
> \# Add project specific ProGuard rules here.
> \# You can control the set of applied configuration files using the
> \# proguardFiles setting in build.gradle.
> \#
> \# For more details, see
> \#   http://developer.android.com/guide/developing/tools/proguard.html
> 
> \# If your project uses WebView with JS, uncomment the following
> \# and specify the fully qualified class name to the JavaScript interface
> \# class:
> \#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
> \#   public \*;
> \#}
> 
> \# Uncomment this to preserve the line number information for
> \# debugging stack traces.
> \#-keepattributes SourceFile,LineNumberTable
> 
> \# If you keep the line number information, uncomment this to
> \# hide the original source file name.
> \#-renamesourcefileattribute SourceFile
> 
> \# Keep public classes
> -keep,includedescriptorclasses class com.google.android.ads.mediationtestsuite.MediationTestSuite { \*; }
> -keep,includedescriptorclasses class com.google.android.ads.mediationtestsuite.MediationTestSuiteListener { \*; }
> -keep,includedescriptorclasses class com.google.android.gms.ads.MobileAds  { \*; }
> 
> -dontwarn org.xmlpull.v1.\*\*
> -dontnote org.xmlpull.v1.\*\*
> -keep class org.xmlpull.\*\* { \*; }
> 
> \#\#---------------Begin: proguard configuration for Gson  ----------
> \# Gson uses generic type information stored in a class file when working with fields. Proguard
> \# removes such information by default, so configure it to keep all of it.
> -keepattributes Signature
> 
> \# For using GSON Expose annotation
> -keepattributes \*Annotation\*
> 
> \# Gson specific classes
> -dontwarn sun.misc.\*\*
> 
> \# Application classes that will be serialized/deserialized over Gson
> -keep,includedescriptorclasses class com.google.android.ads.mediationtestsuite.dataobjects.\*\* { <fields>; }
> -**keep enum com.google.android.ads.mediationtestsuite.dataobjects \*\*{ \*; }** . #this is the bad line!
> 
> \# Prevent proguard from stripping interface information from TypeAdapterFactory,
> \# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
> -keep class \* implements com.google.gson.TypeAdapterFactory
> -keep class \* implements com.google.gson.JsonSerializer
> -keep class \* implements com.google.gson.JsonDeserializer
> 
> \#\#---------------End: proguard configuration for Gson  ----------

Full output:

> stderr[
> 
> FAILURE: Build failed with an exception.
> 
> \* What went wrong:
> Execution failed for task ':transformClassesAndResourcesWithProguardForDebug'.
> \> Job failed, see logs for details
> 
> \* Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> \* Get more help at https://help.gradle.org
> 
> BUILD FAILED in 35s
> ]
> stdout[
> \> Task :checkDebugClasspath
> \> Task :preBuild UP-TO-DATE
> \> Task :extractProguardFiles
> \> Task :Firebase:preBuild UP-TO-DATE
> \> Task :Firebase:preDebugBuild UP-TO-DATE
> \> Task :Firebase:checkDebugManifest
> \> Task :Firebase:processDebugManifest
> \> Task :GoogleMobileAdsMediationTestSuite:preBuild UP-TO-DATE
> \> Task :GoogleMobileAdsMediationTestSuite:preDebugBuild UP-TO-DATE
> \> Task :GoogleMobileAdsMediationTestSuite:checkDebugManifest
> \> Task :GoogleMobileAdsMediationTestSuite:processDebugManifest
> \> Task :GoogleMobileAdsPlugin:preBuild UP-TO-DATE
> \> Task :GoogleMobileAdsPlugin:preDebugBuild UP-TO-DATE
> \> Task :GoogleMobileAdsPlugin:checkDebugManifest
> \> Task :GoogleMobileAdsPlugin:processDebugManifest
> \> Task :helpshift-plugin-wrapper:preBuild UP-TO-DATE
> \> Task :helpshift-plugin-wrapper:preDebugBuild UP-TO-DATE
> \> Task :helpshift-plugin-wrapper:checkDebugManifest
> \> Task :helpshift-plugin-wrapper:processDebugManifest
> \> Task :OpenCoding:preBuild UP-TO-DATE
> \> Task :OpenCoding:preDebugBuild UP-TO-DATE
> \> Task :OpenCoding:checkDebugManifest
> \> Task :OpenCoding:processDebugManifest
> \> Task :SoomlaTraceback:preBuild UP-TO-DATE
> \> Task :SoomlaTraceback:preDebugBuild UP-TO-DATE
> \> Task :SoomlaTraceback:checkDebugManifest
> \> Task :SoomlaTraceback:processDebugManifest
> \> Task :unity-android-resources:preBuild UP-TO-DATE
> \> Task :unity-android-resources:preDebugBuild UP-TO-DATE
> \> Task :unity-android-resources:checkDebugManifest
> \> Task :unity-android-resources:processDebugManifest
> \> Task :preDebugBuild
> \> Task :Firebase:compileDebugAidl NO-SOURCE
> \> Task :GoogleMobileAdsMediationTestSuite:compileDebugAidl NO-SOURCE
> \> Task :GoogleMobileAdsPlugin:compileDebugAidl NO-SOURCE
> \> Task :helpshift-plugin-wrapper:compileDebugAidl NO-SOURCE
> \> Task :OpenCoding:compileDebugAidl NO-SOURCE
> \> Task :SoomlaTraceback:compileDebugAidl NO-SOURCE
> \> Task :unity-android-resources:compileDebugAidl NO-SOURCE
> \> Task :compileDebugAidl NO-SOURCE
> \> Task :Firebase:packageDebugRenderscript NO-SOURCE
> \> Task :GoogleMobileAdsMediationTestSuite:packageDebugRenderscript NO-SOURCE
> \> Task :GoogleMobileAdsPlugin:packageDebugRenderscript NO-SOURCE
> \> Task :helpshift-plugin-wrapper:packageDebugRenderscript NO-SOURCE
> \> Task :OpenCoding:packageDebugRenderscript NO-SOURCE
> \> Task :SoomlaTraceback:packageDebugRenderscript NO-SOURCE
> \> Task :unity-android-resources:packageDebugRenderscript NO-SOURCE
> \> Task :compileDebugRenderscript
> \> Task :checkDebugManifest
> \> Task :generateDebugBuildConfig
> \> Task :prepareLintJar
> \> Task :mainApkListPersistenceDebug
> \> Task :generateDebugResValues
> \> Task :generateDebugResources
> \> Task :Firebase:compileDebugRenderscript
> \> Task :Firebase:generateDebugResValues
> \> Task :Firebase:generateDebugResources
> \> Task :Firebase:packageDebugResources
> \> Task :GoogleMobileAdsMediationTestSuite:compileDebugRenderscript
> \> Task :GoogleMobileAdsMediationTestSuite:generateDebugResValues
> \> Task :GoogleMobileAdsMediationTestSuite:generateDebugResources
> \> Task :GoogleMobileAdsMediationTestSuite:packageDebugResources
> \> Task :GoogleMobileAdsPlugin:compileDebugRenderscript
> \> Task :GoogleMobileAdsPlugin:generateDebugResValues
> \> Task :GoogleMobileAdsPlugin:generateDebugResources
> \> Task :GoogleMobileAdsPlugin:packageDebugResources
> \> Task :helpshift-plugin-wrapper:compileDebugRenderscript
> \> Task :helpshift-plugin-wrapper:generateDebugResValues
> \> Task :helpshift-plugin-wrapper:generateDebugResources
> \> Task :helpshift-plugin-wrapper:packageDebugResources
> \> Task :OpenCoding:compileDebugRenderscript
> \> Task :OpenCoding:generateDebugResValues
> \> Task :OpenCoding:generateDebugResources
> \> Task :OpenCoding:packageDebugResources
> \> Task :SoomlaTraceback:compileDebugRenderscript
> \> Task :SoomlaTraceback:generateDebugResValues
> \> Task :SoomlaTraceback:generateDebugResources
> \> Task :SoomlaTraceback:packageDebugResources
> \> Task :unity-android-resources:compileDebugRenderscript
> \> Task :unity-android-resources:generateDebugResValues
> \> Task :unity-android-resources:generateDebugResources
> \> Task :unity-android-resources:packageDebugResources
> \> Task :mergeDebugResources
> \> Task :createDebugCompatibleScreenManifests
> \> Task :processDebugManifest
> \> Task :splitsDiscoveryTaskDebug
> \> Task :Firebase:generateDebugRFile
> \> Task :GoogleMobileAdsMediationTestSuite:generateDebugRFile
> \> Task :GoogleMobileAdsPlugin:generateDebugRFile
> \> Task :helpshift-plugin-wrapper:generateDebugRFile
> \> Task :OpenCoding:generateDebugRFile
> \> Task :SoomlaTraceback:generateDebugRFile
> \> Task :unity-android-resources:generateDebugRFile
> \> Task :processDebugResources
> \> Task :generateDebugSources
> \> Task :Firebase:generateDebugBuildConfig
> \> Task :Firebase:prepareLintJar
> \> Task :Firebase:generateDebugSources
> \> Task :Firebase:javaPreCompileDebug
> \> Task :Firebase:compileDebugJavaWithJavac
> \> Task :Firebase:processDebugJavaRes NO-SOURCE
> \> Task :Firebase:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
> \> Task :GoogleMobileAdsMediationTestSuite:generateDebugBuildConfig
> \> Task :GoogleMobileAdsMediationTestSuite:prepareLintJar
> \> Task :GoogleMobileAdsMediationTestSuite:generateDebugSources
> \> Task :GoogleMobileAdsMediationTestSuite:javaPreCompileDebug
> \> Task :GoogleMobileAdsMediationTestSuite:compileDebugJavaWithJavac
> \> Task :GoogleMobileAdsMediationTestSuite:processDebugJavaRes NO-SOURCE
> \> Task :GoogleMobileAdsMediationTestSuite:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
> \> Task :GoogleMobileAdsPlugin:generateDebugBuildConfig
> \> Task :GoogleMobileAdsPlugin:prepareLintJar
> \> Task :GoogleMobileAdsPlugin:generateDebugSources
> \> Task :GoogleMobileAdsPlugin:javaPreCompileDebug
> \> Task :GoogleMobileAdsPlugin:compileDebugJavaWithJavac
> \> Task :GoogleMobileAdsPlugin:processDebugJavaRes NO-SOURCE
> \> Task :GoogleMobileAdsPlugin:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
> \> Task :helpshift-plugin-wrapper:generateDebugBuildConfig
> \> Task :helpshift-plugin-wrapper:prepareLintJar
> \> Task :helpshift-plugin-wrapper:generateDebugSources
> \> Task :helpshift-plugin-wrapper:javaPreCompileDebug
> \> Task :helpshift-plugin-wrapper:compileDebugJavaWithJavac
> \> Task :helpshift-plugin-wrapper:processDebugJavaRes NO-SOURCE
> \> Task :helpshift-plugin-wrapper:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
> \> Task :OpenCoding:generateDebugBuildConfig
> \> Task :OpenCoding:prepareLintJar
> \> Task :OpenCoding:generateDebugSources
> \> Task :OpenCoding:javaPreCompileDebug
> \> Task :OpenCoding:compileDebugJavaWithJavac
> \> Task :OpenCoding:processDebugJavaRes NO-SOURCE
> \> Task :OpenCoding:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
> \> Task :SoomlaTraceback:generateDebugBuildConfig
> \> Task :SoomlaTraceback:prepareLintJar
> \> Task :SoomlaTraceback:generateDebugSources
> \> Task :SoomlaTraceback:javaPreCompileDebug
> \> Task :SoomlaTraceback:compileDebugJavaWithJavac
> \> Task :SoomlaTraceback:processDebugJavaRes NO-SOURCE
> \> Task :SoomlaTraceback:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
> \> Task :unity-android-resources:generateDebugBuildConfig
> \> Task :unity-android-resources:prepareLintJar
> \> Task :unity-android-resources:generateDebugSources
> \> Task :unity-android-resources:javaPreCompileDebug
> \> Task :unity-android-resources:compileDebugJavaWithJavac
> \> Task :unity-android-resources:processDebugJavaRes NO-SOURCE
> \> Task :unity-android-resources:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
> \> Task :javaPreCompileDebug
> \> Task :compileDebugJavaWithJavac
> \> Task :compileDebugNdk NO-SOURCE
> \> Task :compileDebugSources
> \> Task :mergeDebugShaders
> \> Task :compileDebugShaders
> \> Task :generateDebugAssets
> \> Task :Firebase:mergeDebugShaders
> \> Task :Firebase:compileDebugShaders
> \> Task :Firebase:generateDebugAssets
> \> Task :Firebase:packageDebugAssets
> \> Task :GoogleMobileAdsMediationTestSuite:mergeDebugShaders
> \> Task :GoogleMobileAdsMediationTestSuite:compileDebugShaders
> \> Task :GoogleMobileAdsMediationTestSuite:generateDebugAssets
> \> Task :GoogleMobileAdsMediationTestSuite:packageDebugAssets
> \> Task :GoogleMobileAdsPlugin:mergeDebugShaders
> \> Task :GoogleMobileAdsPlugin:compileDebugShaders
> \> Task :GoogleMobileAdsPlugin:generateDebugAssets
> \> Task :GoogleMobileAdsPlugin:packageDebugAssets
> \> Task :helpshift-plugin-wrapper:mergeDebugShaders
> \> Task :helpshift-plugin-wrapper:compileDebugShaders
> \> Task :helpshift-plugin-wrapper:generateDebugAssets
> \> Task :helpshift-plugin-wrapper:packageDebugAssets
> \> Task :OpenCoding:mergeDebugShaders
> \> Task :OpenCoding:compileDebugShaders
> \> Task :OpenCoding:generateDebugAssets
> \> Task :OpenCoding:packageDebugAssets
> \> Task :SoomlaTraceback:mergeDebugShaders
> \> Task :SoomlaTraceback:compileDebugShaders
> \> Task :SoomlaTraceback:generateDebugAssets
> \> Task :SoomlaTraceback:packageDebugAssets
> \> Task :unity-android-resources:mergeDebugShaders
> \> Task :unity-android-resources:compileDebugShaders
> \> Task :unity-android-resources:generateDebugAssets
> \> Task :unity-android-resources:packageDebugAssets
> \> Task :mergeDebugAssets
> \> Task :checkDebugLibraries
> \> Task :processDebugJavaRes NO-SOURCE
> \> Task :transformResourcesWithMergeJavaResForDebug
> \> Task :Firebase:mergeDebugConsumerProguardFiles
> \> Task :GoogleMobileAdsMediationTestSuite:mergeDebugConsumerProguardFiles
> \> Task :GoogleMobileAdsPlugin:mergeDebugConsumerProguardFiles
> \> Task :helpshift-plugin-wrapper:mergeDebugConsumerProguardFiles
> \> Task :OpenCoding:mergeDebugConsumerProguardFiles
> \> Task :SoomlaTraceback:mergeDebugConsumerProguardFiles
> \> Task :unity-android-resources:mergeDebugConsumerProguardFiles
> Warning: Exception while processing task java.io.IOException: proguard.ParseException: Expecting opening '{' at '\*\*' in line 45 of file '/Users/jenkins/.gradle/caches/transforms-2/files-2.1/70789f5548d8ad34604c5ef31e6c9c72/proguard.txt'
> Thread(Tasks limiter_1): destruction
> 
> \> Task :transformClassesAndResourcesWithProguardForDebug FAILED
> Request to incrementing alive workforce from 0. Current workforce (dead or alive) 0
> thread-pool size=4
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
> 127 actionable tasks: 127 executed
> ]
> exit code: 1

**Comment by JabluszkoPL** [comment]
I have the same problem

**Comment by daancode** [comment]
Same here. I have that problem with local builds and I can't find any solution for that.

**Comment by stowy** [comment]
Can you share repro steps or a sample project?

**Comment by JabluszkoPL** [comment]
@stowy 
https://drive.google.com/file/d/1LmSxAGnWRSX1oPeEj62r6YerV6O0U-bK/view?usp=sharing

**Comment by stowy** [comment]
Thanks @JabluszkoPL - I can confirm that there appears to be a syntax error in the mediation test suite proguard file on Android which is causing this error. 

To get it to build you could disable proguard or revert to an earlier version (1.2.0 I think). 

I will release an update with the fix in the next week or so.

**Comment by stowy** [comment]
I've just released Mediation Test Suite version 1.2.2 which should resolve this issue.
