### ISSUE TITLE
BannerAd - iOS: FPS drop

### ISSUE THREAD

**Issue by ishnu47** [googleads/googleads-mobile-unity#1086]
Hello,
I'm using GoogleMobileAds-v4.1.0 (with Unity 2018.4.12f1) on iOS and got these strange issues:

1. Every time the banner ad loads/refreshes, I can see a significant fps drop. Most of the time, player is dragging object, so that's easy to be seen and causes bad feeling to players.

2. When there is a banner ad showing, if I swipe the screen from top to bottom to view the phone's notifications (the game goes "WillResignActive"), and then back to the game, fps is constantly dropped to 30fps (<60fps), and the dragging action is very slow and lagging. With Unity profiler, I see that it takes most CPU time on Gfx.WaitForPresent, (our game is just a very simple 2d game) => Might it be related to Vsync?. 
And this issue never happens if I play game without the banner ad. The bad performance state will stop immediately when there is an interstitial ad showing and closed.

Thanks for your help!

**Comment by khushalkhan83** [comment]
noticed this issue with earlier versions too

**Comment by gering** [comment]
I have the same issue with versions 5.3.0. It seems that the FPS drop is related to animated banners. On some Android devices the fps drops from 60 to below 20. On iOS it drops from 60 to exactly 40.

**Comment by stowy** [comment]
Can you try disabling video ads as per the below and see if this has an impact?

<img width="1014" alt="Screen Shot 2020-08-04 at 8 52 16 AM" src="https://user-images.githubusercontent.com/5924628/89315664-fa567b00-d62f-11ea-91e1-acf577355cdf.png">

**Comment by gering** [comment]
I tried this, but w/o any effect. I think HTML5 ads are the cause.

**Comment by gering** [comment]
When profiling it seems to be related to frame sync in a weird way.
