### ISSUE TITLE
IInAppPurchaseHandler could not be found

### ISSUE THREAD

**Issue by TheSiteArtist** [googleads/googleads-mobile-unity#109]
Hi,
I have created GoogleMoblieAdsDemoHandler.cs script by copying and pasting the same git script into a new .cs file, and tried to attach it to the Main Camera.
In that script I am getting the error :The type or namespace name `IInAppPurchaseHandler' could not be found. Are you missing a using directive or an assembly reference?
1. Google Mobile Ads has been added
2. Google-play-services_lib has been added to the Plugins>Android folder.
What am I missing here?

**Comment by TheSiteArtist** [comment]
I found the answer in a reddit post.  I changed the class name to match GoogleMobileAdsDemoHandler.cs and it worked.
Here is the post:  More to the point, it looks like you're using the version 2.3 GoogleMobileAdsDemoScript.cs with the version 2.2.1 package. Try using this version of the demo script: https://raw.githubusercontent.com/googleads/googleads-mobile-plugins/c488262bbe21733eef81df6acda1c189d33c42af/unity/samples/HelloWorld/Assets/GoogleMobileAdsDemoScript.cs

**Comment by harleygirl7144** [comment]
I want it off my phone Please

**Comment by harleygirl7144** [comment]
The tracker

**Comment by ericleich** [comment]
This class was added in version 2.3.0 of the plugin. Which version are you trying to import?

**Comment by rampara** [comment]
This issue is being closed due to its age. If this problem persists, please re-open the issue.
