### ISSUE TITLE
Live Ads Appearing on test ad unit id

### ISSUE THREAD

**Issue by FaiyazMdAbdul** [googleads/googleads-mobile-unity#1100]
Live ads are appearing when i am using test ad unit id. I have even deleted the rewards ad unity id i created just to make sure.
I haven't created test device but application is registered and not uploaded on play store yet.

However this doesn't happen on the primary device i test with . It happens only on other phones.

**Comment by UragayalaDeepika** [comment]
@FaiyazMdAbdul Please post your Mobile Ads SDK related issues on[ Mobile Ads SDK Forum ](https://groups.google.com/forum/#!forum/google-admob-ads-sdk)and our team will be able to assist you further.

**Comment by AliahmadDev** [comment]
I have also noticed this issues many times with Google Mobile Ads sdk that original live ads are seen even with test IDs.

**Comment by FaiyazMdAbdul** [comment]
it happens only when birthdate of google account in device is less than 13 years of age and family controlled.
