### ISSUE TITLE
Unity plugin RewardedAd class missing getRewardItem method, for getting load time reward value

### ISSUE THREAD

**Issue by roointan** [googleads/googleads-mobile-unity#1107]
Using Unity 2019.2.3f1
Google Admob Unity Plugin version 4.1.0

Here: https://developers.google.com/admob/unity/rewarded-ads
In the list of improvement on the top of the page, this is one of the items: 'Access the reward value at ad load time."

But I don't see any getRewardItem() method of the RewardedAd object, or anything similar to access the Reward item.
I checked the Android Implementation, and it has a getRewardItem(), but not the Unity class.

https://developers.google.com/android/reference/com/google/android/gms/ads/rewarded/RewardedAd.html#getRewardItem()

**Comment by stowy** [comment]
Added in v4.2.0.
