### ISSUE TITLE
GoogleMobileAds/GoogleMobileAds.h' file not found

### ISSUE THREAD

**Issue by BuKuSiShen** [googleads/googleads-mobile-unity#1128]
Unity2018.2.21 GoogleMobileAds-v4.2.0.unitypackage  build Xcode on Windows,then build Xcode on Mac,build errror GoogleMobileAds/GoogleMobileAds.h' file not found,for help!
![image](https://user-images.githubusercontent.com/12295354/71819705-a9959880-30c7-11ea-9d51-5d74892e0555.png)

**Comment by BuKuSiShen** [comment]
I tested  build Xcode in Unity on windows with error,just now i test build xcode on Mac and build by xcworkspace with success !

**Comment by stowy** [comment]
This is a cocoapods integration issue, not related to the plugin.

**Comment by huynguyencong** [comment]
I am having the same issue. Other projects don't have that problem with Cocoapods and Admob pod.

**Comment by IanEFSG7** [comment]
So what's the solution?

**Comment by MarcoLavoro** [comment]
I have the same problem, EVERY SINGLE TIME i update google ads there are a LOT of problem, anyone know a solution for this?

**Comment by IanEFSG7** [comment]
Guys, I have found an alternative solution by simply using Enhance.co.

You can create the AAB file, and use their technology to directly inject the Google Ads or other Ads for you.

It's free and fast. Cheers.



________________________________
