### ISSUE TITLE
SmartBanner landscape doesn't show on Nexus 6

### ISSUE THREAD

**Issue by sjvc** [googleads/googleads-mobile-unity#113]
I ran the sample project on a Nexus 4, and SmartBanner it's showing correctly, in portrait and landscape. But on a Nexus 6 (Android 5.1.1) SmartBanner is showing in portrait, but not in landscape. Logcat says:

Invalid admob request error: [Ad size will not fit on screen]
There was a problem setting an ad response. ErrorCode: 1
Failed to load ad: 1

I'm using Google Mobile Ads Unity Plugin v2.3.0, and Google Play Services r25

**Comment by rampara** [comment]
We are aware of this issue and currently investigating a fix. I will follow up when I have more information.

- Ram

**Comment by sjvc** [comment]
Thanks. I hope you find a fix soon :+1:

**Comment by sjvc** [comment]
Any news about this issue?

**Comment by rampara** [comment]
Server side changes have been made to fix this issue. A push should be going out soon.

- Ram

**Comment by sjvc** [comment]
I'm glad to read it :) I can't wait for it! Thanks! :+1:
