### ISSUE TITLE
MobileAds.Initialize does not trigger callback in editor

### ISSUE THREAD

**Issue by Thaina** [googleads/googleads-mobile-unity#1133]
It just log `Dummy Initialize` and not triggering callback in editor environment

Using googleads-mobile-unity 4.2.0 and 4.2.1

**Comment by stowy** [comment]
Hi @Thaina - this is working as expected, we do not emulate SDK behavior in the editor, you need to run on an Android or iOS device.

**Comment by ericleich** [comment]
@stowy While it's true we hadn't considered doing that in the past, I think this is a valid FR. Ads currently don't load in the editor, but app code may depend on those callbacks and it breaks ability to test app code in the editor.

**Comment by Thaina** [comment]
@ericleich Thanks for your supportive argument. That's exactly why I have open this issue. I have calling Initialize function in the initial state of my app, and then the SDK just interrupt the initialization of whole app

@stowy I know that the SDK won't work in editor. But while you have dummying the initialization I hope that you would also dummy the callback too

**Comment by stowy** [comment]
Ok I'm happy to accept this as a feature request.

Note @Thaina that we do accept pull requests, so you're welcome to open one and we can work to get that submitted.

**Comment by Thaina** [comment]
@stowy Shouldn't this be as easy as just this?

https://github.com/googleads/googleads-mobile-unity/blob/d258a5004418bc363ab7ee9c9b8841484b03c511/source/plugin/Assets/GoogleMobileAds/Common/DummyClient.cs#L73-L77
