### ISSUE TITLE
iOS 13.3 Game freezes once interstitial ad is closed for iPhone 6S

### ISSUE THREAD

**Issue by YHSX88** [googleads/googleads-mobile-unity#1138]
### **Versions:**
iOS version : 13.3
Unity Version : 2019.2.17f1
AdMob plug-in version: Google Mobile Ads Unity Plugin v4.2.1
'Google-Mobile-Ads-SDK', '~> 7.53'

### **Devices:**
I can only test on iPhone 6S

### **Issue:**
Game is freezing/ becomes unresponsive once interstitial ad is closed on iPhone 6S

### **Steps to Reproduce:**
**Pre-conditions:**
Create simple game with 2 buttons: 1 to load interstitial and 1 to show interstitial

Steps:
1. Tap on Load interstitial button to load interstitial
2. Tap on Show interstitial button to show interstitial
3. Tap on X close button once the interstitial is open/displayed
4. Once Closed non of the buttons are functional anymore no animations if there is are moving etc. like total freeze.

**### Xcode: logs:**
`2020-01-14 23:03:04.629280+0200 TestAdMobIntersticial[17732:4610286] <Google> To get test ads on this device, set: GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ @"73b707355776d7db823189684b2d8817" ];
2020-01-14 23:03:04.653595+0200 TestAdMobIntersticial[17732:4610531]  - <Google>[I-ACS037005] Unable to fetch effective App ID from identity
**HandleInterstitialLoaded event received**
System.EventHandler`1:Invoke(Object, TEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

**HandleInterstitialOpened event received**
System.EventHandler`1:Invoke(Object, TEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
AdMngr:diplayInter()
UnityEngine.Events.UnityAction:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
UnityEngine.EventSystems.StandaloneInputModule:Process()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

2020-01-14 23:03:23.417546+0200 TestAdMobIntersticial[17732:4611132]  - <Google>[I-ACS037005] Unable to fetch effective App ID from identity
2020-01-14 23:03:23.496908+0200 TestAdMobIntersticial[17732:4610537] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2020-01-14 23:03:23.497043+0200 TestAdMobIntersticial[17732:4610537] WF: _WebFilterIsActive returning: NO
**HandleInterstitialLoaded event received**
System.EventHandler`1:Invoke(Object, TEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)`

**Conclusion:**
I'm attaching video as well.
[Unity.MP4.zip](https://github.com/googleads/googleads-mobile-unity/files/4061533/Unity.MP4.zip)

if more info is needed I can upload ? 
Any help is is appreciated thanks.

**Comment by khushalkhan83** [comment]
freeze my app too any solution?

**Comment by oddgames-david** [comment]
I've had android freezes with rewarded Facebook and Unity mediated adverts, I'm having some success with not allowing the rewarded ad to be disposed (putting it into a list).

**Comment by YHSX88** [comment]
I'm getting this message in xcode Version 11.4 (11E146) as soon as I close the interstitial and app freezes. BY THE WAY I'm using the latest plugin version v5.1.0

2020-05-05 08:59:45.880326+0300 him[4134:1451585] [ProcessSuspension] 0x1131e2850 - ProcessAssertion::processAssertionWasInvalidated()
2020-05-05 08:59:45.880493+0300 him[4134:1451585] [ProcessSuspension] 0x1131e2d60 - ProcessAssertion::processAssertionWasInvalidated()
2020-05-05 08:59:54.008669+0300 him[4134:1451585] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!
