### ISSUE TITLE
 Unity: Exception: UnityEngine.AndroidJavaException: java.lang.IllegalArgumentException: adSize

### ISSUE THREAD

**Issue by umairh2018** [googleads/googleads-mobile-unity#1144]
I recently added a new SDK of audience network in unity. I was using a banner ad of Facebook. but it showing this error in android devices.
**Unity: Exception: UnityEngine.AndroidJavaException: java.lang.IllegalArgumentException: adSize**
Here is my code for invoking banner ad:
```
this.adView = new AdView(AdConstants.fbBannerID, AdSize.BANNER_HEIGHT_50);
            this.adView.Register(this.gameObject);

            // Set delegates to get notified on changes or when the user interacts with the ad.
            this.adView.AdViewDidLoad = (delegate ()
            {
                Debug.Log("Banner loaded.");
                this.adView.Show(AdPosition.TOP);
            });
```
I have searched but no outcome here. Anyone using a banner ad of audience network in Unity, please guide me.

**Comment by stowy** [comment]
Sorry this does not seem relevant to the Google Mobile Ads SDK.
