### ISSUE TITLE
Poor performance on Android after show BannerView

### ISSUE THREAD

**Issue by kyuskoj** [googleads/googleads-mobile-unity#115]
I found out just showing bannerview causes significant increase of CPU temperature (58°C -> 66°C)
Is there any solution for this?

Device: Galaxy S4
Unity Version : 5.0.1f
Admob Plugin Version : v2.3.1

thanks.

**Comment by rampara** [comment]
Are you still seeing this behavior in your Unity application? If so, which version of Google Play Services is your device using and which version of the Google Play Services library is your application compiled with?

- Ram

**Comment by rampara** [comment]
Closing due to the age of this issue. Please re-open if this issue persists for you.
