### ISSUE TITLE
Android 4.4 Native Crashes

### ISSUE THREAD

**Issue by mcrvaz** [googleads/googleads-mobile-unity#1150]
Unity 2019.2.19
AdMob SDK 4.2.1
Using IL2CPP

We've recently been receiving lots of native crash reports like this:

```
Fatal Exception: java.lang.Error
libc.__memcpy_base (__memcpy_base:88)
libbinder.android::Parcel::appendFrom(android::Parcel const*, unsigned int, unsigned int) (Parcel:136)
libandroid_runtime.0006d4bb
libdvm.dvmPlatformInvoke (dvmPlatformInvoke:112)
libdvm.dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*) (dvmCallJNIMethod:398)
libdvm.000271a0
libdvm.dvmMterpStd(Thread*) (dvmMterpStd:76)
libdvm.dvmInterpret(Thread*, Method const*, JValue*) (dvmInterpret:184)
libdvm.dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list) (dvmCallMethodV:338)
libdvm.dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...) (dvmCallMethod:20)
libdvm.00055547
libc.__thread_entry (__thread_entry:72)
libc.pthread_create (pthread_create:240)
```
And this:
```
libbinder.android::acquire_object(android::sp<android::ProcessState> const&, android::flat_binder_object const&, void const*) (acquire_object:3)
libbinder.android::Parcel::appendFrom(android::Parcel const*, unsigned int, unsigned int) (Parcel:274)
libandroid_runtime.00070473
libdvm.dvmPlatformInvoke (dvmPlatformInvoke:112)
libdvm.dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*) (dvmCallJNIMethod:398)
libdvm.000271a0
libdvm.dvmMterpStd(Thread*) (dvmMterpStd:76)
libdvm.dvmInterpret(Thread*, Method const*, JValue*) (dvmInterpret:184)
libdvm.dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list) (dvmCallMethodV:338)
libdvm.dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...) (dvmCallMethod:20)
libdvm.00055577
libc.__thread_entry (__thread_entry:72)
libc.pthread_create (pthread_create:240)
```

Pretty much all of them seem to be coming from Androids 4.4.4 and always happens when opening a Rewarded Ad with the AdMob Adapter (com.google.ads.mediation.admob.AdMobAdapter).

**Comment by ishnu47** [comment]
Same here, but we're using Interstitial Ads instead.
Every time the interstitial ad showing, sometimes it crashes.

**Comment by famishedmammal** [comment]
I have been getting a huge number of crashes recently from this plugin as well.

**Comment by AAulicino** [comment]
Same thing here with the same **"__memcpy_base"**  stack trace.
More than a thousand crashes in Android 4.4.4 ...

![image](https://user-images.githubusercontent.com/6969647/73579370-f9fedc80-4460-11ea-9ed8-b2bded159522.png)
![image](https://user-images.githubusercontent.com/6969647/73579460-4518ef80-4461-11ea-8f26-20b522c8708e.png)

**Comment by famishedmammal** [comment]
My crash rate over the last 3 months
![crashes](https://user-images.githubusercontent.com/12555805/73579927-c3ad6700-4438-11ea-9eea-c2562e3421f6.png)

**Comment by famishedmammal** [comment]
Insteresting observation I have made after removing the admob plugin
![admob lmao](https://user-images.githubusercontent.com/12555805/73695704-7e36a700-468f-11ea-9d8d-67333f8dd3fb.png)

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!
