### ISSUE TITLE
Video ad not in full screen on some devices with notch.

### ISSUE THREAD

**Issue by joses1234** [googleads/googleads-mobile-unity#1166]
I'm using Admob ver 4.0.0, with mediations. Recently we noticed there are some video ads that are not displayed in full screen, specifically for devices with notch. The Video ad seems to be cut around the notch area.

I was wondering if any one has ever experienced this issue? or is it device specific only? One other thing is this might be a bug of one of our enabled admob providers but I'm not yet sure.

**Comment by stowy** [comment]
Hi @joses1234, do you want to share a screenshot? I think that this may be
intended behavior.

**Comment by joses1234** [comment]
Hi @stowy, thanks for reaching out. I've sent a screenshot here: 

![adImage](https://user-images.githubusercontent.com/47806162/73998426-9282e880-499c-11ea-9724-c5a9219e27f8.jpg)

The pink part represents my game's background.

**Comment by thiagolr** [comment]
I'm also experiencing this on my game and also on other games that I play. My guess is that it started when I upgraded my phone to Android 10.

@joses1234 Which Android version is this screenshot from?

**Comment by stowy** [comment]
@joses1234  I can't speak for all creatives here, I think you'll need to provide more detail to debug this issue.

This would be best resolved using [our support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines), can you please post your concern there and they will be able to debug with you in depth.

**Comment by vcamargo** [comment]
I notice the same with my game. I have enabled "Render outside safe area" in the Project Settings, so shouldn't Google Ads follow this setting as well?

**Comment by Hasanceliktr** [comment]
![1](https://user-images.githubusercontent.com/68238266/226303034-5f71f477-794d-4027-af8b-27c082117305.jpg)
i have the same problem is there any way to fix it?

**Comment by mlostekk** [comment]
Same problem here... Not in Unity but regular AdMob on Android
