### ISSUE TITLE
Resolve Android Dependencies without setting Android API to 28

### ISSUE THREAD

**Issue by UnityStefan** [googleads/googleads-mobile-unity#1167]
Hello,
The situation is this: I followed all the steps for setting AdMob inside my Unity project and when I start "Force Resolve" I'm getting this message:

"Jetpack (AndroidX) libraries are only supported when targeting Android API 28 and above. The currently selected target API level is 26.
Would you like to set the project's target API level to 28?" with options "Yes", "Disable Jetifier" and "No".

If I ignore it I'm getting "Resolution failed" and if I build my project banners aren't working. If I set Android API level to 28 everything is working just fine. 
Problem is that I cant just discard previous versions of Android (it would be ok to support at least from Android 8.0 and above). How can I do that?
Thanks in advance!

**Comment by pipe-alt** [comment]
you can't publish your app on the google play store with target api 26,    you need to target api 28 to publish your app, android is backward compatible, targeting api 28 is not going to "discard" previous versions of android.

https://developer.android.com/distribute/best-practices/develop/target-sdk

the "min sdk version" is the one that "discards" anything bellow the android number, not the target sdk.

**Comment by UnityStefan** [comment]
Oh, I learned something new, thank you very much.
"Problem" is now solved! :)
