### ISSUE TITLE
Target API Level 29 Incompatibility

### ISSUE THREAD

**Issue by The3Designer** [googleads/googleads-mobile-unity#1170]
I'm using the latest version of this plugin, together with Unity 2019.3.0f6 and the NDK and SDK that are installed with this version. When I set the Target API Level to 29 (for Android 10 support), I get the following error message:

![asdasdf](https://user-images.githubusercontent.com/59917065/74333216-6c3fbd00-4d8f-11ea-9063-326b797544fd.png)

When I set the Target API Level back to 28 (for Android Pie support) there are no errors. Another thing that occurs with this error, is that the Android Resolver doesn't work (with API 29 selected).

**Comment by stowy** [comment]
This looks like a Play Services resolver issue. Can you report it to their
issue tracker at https://github.com/googlesamples/unity-jar-resolver.

Before doing that though, perhaps try deleting all resolved dependencies
through the jar resolver menu and then doing Force Resolve.

**Comment by The3Designer** [comment]
> Before doing that though, perhaps try deleting all resolved dependencies
> through the jar resolver menu and then doing Force Resolve.

I'll try this and if it doesn't work I'll report it at the link you provided!
