### ISSUE TITLE
[IOS] [Bundle Id] Faild to load ads

### ISSUE THREAD

**Issue by yenmoc25** [googleads/googleads-mobile-unity#1174]
Hello everyone,
I was build ios with admob and I am having problems,
I have application on appstore with bundle id A
I test admob with bundle id A and it always return failed to load ads
then i change bundle id form A to B and test again it work well

What is going on with my bundle id?

**Comment by willmeet** [comment]
[That issue is clearly shown here how to solve admob failed to load ads http://www.technologymanias.com/2020/10/admob-ads-failed-to-load-ads-solve-this.html](http://www.technologymanias.com/2020/10/admob-ads-failed-to-load-ads-solve-this.html)
