### ISSUE TITLE
Requires new permission READ_PHONE_STATE and READ_EXTERNAL_STORAGE ???

### ISSUE THREAD

**Issue by perseus25** [googleads/googleads-mobile-unity#1178]
Hello,
After upgrade admob plugin, my app requires new permission:
READ_PHONE_STATE
READ_EXTERNAL_STORAGE

Appears from version 4.0.0 and up.
Build with Unity 2018.2.21.1f1

I can't find that permision in AndroidManifest.xml in Unity project.
Why admob needs this permissions.
How to remove them?

**Comment by mdobele** [comment]
I've found that If one of your plugin's Manifest files doesn't have a minSDK version set then these permissions can be added to your final project.  

You can add these lines to your main manifest file to ensure they get removed in your merged manifest file.

<uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:node="remove" />

**Comment by perseus25** [comment]
@mdobele Thank you very much. Saved me so much time.

**Comment by stowy** [comment]
Closing this, please let me know if any problems persist.

**Comment by dannykay1** [comment]
> @mdobele Thank you very much. Saved me so much time.

Did it fix your issue?  When I use that snipper in the manifest, unity crashes when trying to load an ad.

Unity 2018.1
Admob 4.2.1
