### ISSUE TITLE
GoogleMobileAds-native + Assembly Definition File = NullReferenceException

### ISSUE THREAD

**Issue by kerembaydogan** [googleads/googleads-mobile-unity#1182]
Hi,

I've been using assembly definition files through my project to make everything more modular.
But GoogleMobileAds-native plugin does not like assembly definition files.

Whenever I try to modularize GoogleMobileAds-native library as a unity assembly,
I get the following error:

```
NullReferenceException: Object reference not set to an instance of an object
GoogleMobileAds.Api.MobileAds._4YBpwDZuWPioo85QutHQYkXDD6Q () (at <1addeb55188b479e997f69ad44f42f0e>:0)
GoogleMobileAds.Api.MobileAds..cctor () (at <1addeb55188b479e997f69ad44f42f0e>:0)
Rethrow as TypeInitializationException: The type initializer for 'GoogleMobileAds.Api.MobileAds' threw an exception.
```

How to reproduce:

- Create Empty Unity project
- Import GoogleMobileAds-native plugin
- Create an assembly definition file for the GoogleMobileAds-native plugin
- Call MobileAds.Initialize(appId);

Because of the closed-source nature of the native plugin, I can not debug and see the problem.

When I decompiled the library I found out the point of NullReferenceException is where the plugin developers used reflection ("Type.GetType").

I think the problem is related to reflection usage by the plugin developers (Type.GetType) and code stripping by unity (il2cpp).

But I don't know why there is no problem when there is no asmdef file.

Assembly definition files are very important for large scale project and a lot of plugins comes with asmdef files these days, and I think this plugin should also provide a way to integrate asmdef files.

If you think this problem is not a bug, please tell me where can I find the opensource version of the native plugin, so I can investigate further.

Thanks for your help.

**Comment by stowy** [comment]
Should be fixed in v5.0.0.1 of native plugin (accessible via usual download link).
