### ISSUE TITLE
GoogleMobileAds.h file not found

### ISSUE THREAD

**Issue by huynguyencong** [googleads/googleads-mobile-unity#1187]
I added Admob package to Unity, generated iOS project. I saw `Google-Mobile-Ads-SDK` has been installed in my project. When I build the iOS project, it failed with error: `'GoogleMobileAds/GoogleMobileAds.h' file not found` in `GADURewardedAd.h` file. 
I tried to search on Google, but couldn't find any solution that fixes the issue. Please help me to solve this issue. Thank you!

![GoogleMobileAds.h file not found](https://i.ibb.co/3N4YK9g/Screen-Shot-2020-02-29-at-23-02-48.png)

**Comment by stowy** [comment]
Are you using the .xcworkspace version of the project? Can you please check the Podfile and Podfile.lock to ensure that the Google-Mobile-Ads-SDK has been correctly included in the cocoapods workspace?

**Comment by huynguyencong** [comment]
Thanks for your response. I just fixed it by updating the Unity Ads package in package Manager to version 3.
