### ISSUE TITLE
Automatically add GoogleMobileAds.framework & enable modules in Xcode for Unity iOS build?

### ISSUE THREAD

**Issue by timmy2702** [googleads/googleads-mobile-unity#119]
Hi guys,

I'm just wondering whether there is a way to add GoogleMobileAds.framework & enable modules in Xcode automatically while building it on Unity? It's pretty inconvenient to change the build settings in Xcode for every builds I make, especially in testing stage. Is there a way to do this with PostprocessBuildPlayer?

Thanks

**Comment by rampara** [comment]
This functionality is added in the latest version of our plugin (v3.0.0).
