### ISSUE TITLE
error: use of undeclared identifier 'nullptr'

### ISSUE THREAD

**Issue by shefich** [googleads/googleads-mobile-unity#1200]
Hi,

I am using Unity 2018.4.18 and moved to Admob SDK 5.0.0. Now I have such issue, while building to Android:

error: use of undeclared identifier 'nullptr'

So the build failed, because of this issue. As I could see more people are facing this issue, you can check Unity forum here:
https://forum.unity.com/threads/after-admob-install-il2cpp-error-is-occured.843655/

**Comment by stowy** [comment]
Ok, looks like this is not supported in 2018.4. If you upgrade to 2019.3 it will work.

I will revise to remove `nullptr` keyword.

**Comment by shefich** [comment]
Hi @stowy,

Upgrade to 2019.3 is not an option. It will be great, if you will remove or replace 'nullptr' keyword and will launch some hotfix, to have compatibility with older versions of unity.

Thank you for you attention.

**Comment by stowy** [comment]
I've just published the v5.0.1 release patch for this. Native update will be pushed shortly.

**Comment by stowy** [comment]
Native version 5.0.1.1 is now published also.
