### ISSUE TITLE
Banner LoadAd Method Also Show Banner

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#1204]
Hi, initialize and load the banner ad to show it later. But 
this.bannerView.LoadAd(request);  shows the ad by default on game start.

**Comment by stowy** [comment]
Yes this is the designed behavior. If you don't want the banner to display when it is loaded, call [BannerView.Hide()](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Api/BannerView.cs#L65) before loading it.
