### ISSUE TITLE
native ads advanced (unified) : GameObjects registering but not clickable

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#1205]
i implement native ads advanced (unified). Ad is showing and registering gameobjects successfully. But not clickable.
Note : Nothing blocking the ui elements. Boxcolliders added as well.
Please check The script Let me know if anything wrong:
[native.txt](https://github.com/googleads/googleads-mobile-unity/files/4328058/native.txt)

**Comment by MuhammadWaqasOfficial** [comment]
Solution for me : If you're displaying native ads advanced (unified) in canvas ui. Set false Raycast Target Property Of Parent holding native ads advanced (unified) gameobjects.

**Comment by stowy** [comment]
Thanks for sharing Muhammad.
