### ISSUE TITLE
Can't close a specific Interstitial on iOS

### ISSUE THREAD

**Issue by AllanRW** [googleads/googleads-mobile-unity#1206]
There's a specific type of interstitial on iOS that can't be dismissed, seems it only appears on splash interstitial on app opening, I've attached the screenshot below:
The button timer don't go below 5 seconds and the only way to dismiss is closing the app

iPhone XS Max
Admob 4.2.1
Unity 2019.2.21f

![20200313_152820](https://user-images.githubusercontent.com/40209316/76649788-24ec4e00-6540-11ea-9044-27fdd6a86a8f.jpg)

**Comment by stowy** [comment]
Thanks this is a known issue with the IOS SDK. Are you using mediation?

**Comment by AllanRW** [comment]
Good to know, no mediation just Admob.

**Comment by ChaserKnight** [comment]
I am also facing this issue, is there a fix coming soon? Many users are leaving 1 star reviews because of this. I am not using mediation, just AdMob. This needs to be fixed quickly.

**Comment by stowy** [comment]
There was a fix rolled out server-side yesterday (it was affecting certain creatives appearing on iPhone X type devices). Please check for occurrences happening from today.

**Comment by ChaserKnight** [comment]
Some of our users are still reporting such issue, that they can not close certain ads or there is no close button. Does this bug still exists?
