### ISSUE TITLE
Failed a build il2cpp on 5.0.1

### ISSUE THREAD

**Issue by InFeIM** [googleads/googleads-mobile-unity#1207]
What should I do?

> Failed running C:\Program Files\Unity2017_32f1\Editor\Data\il2cpp/build/il2cpp.exe --convert-to-cpp --emit-null-checks --enable-array-bounds-check --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARMv7" --configuration="Release" --outputpath="C:\Project_GT\branches\v3\Temp/StagingArea\assets\bin\Data\Native\armeabi-v7a\libil2cpp.so" --cachedirectory="C:\Project_GT\branches\v3\Assets\..\Library\il2cpp_android_armeabi-v7a/il2cpp_cache" --additional-include-directories="C:\Program Files\Unity2017_32f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\bdwgc/include" --additional-include-directories="C:\Program Files\Unity2017_32f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\libil2cpp/include" --tool-chain-path="C:/ProgramSub/Android SDK/android-ndk-r13b" --map-file-parser="C:\Program Files\Unity2017_32f1\Editor\Data\Tools\MapFileParser\MapFileParser.exe" --assembly="C:\Project_GT\branches\v3\Temp\StagingArea\assets\bin\Data\Managed\Assembly-CSharp-firstpass.dll" --assembly="C:\Project_GT\branches\v3\Temp\StagingArea\assets\bin\Data\Managed\Assembly-CSharp.dll" --assembly="C:\Project_GT\branches\v3\Temp\StagingArea\assets\bin\Data\Managed\E7.NativeAudio.dll" --assembly="C:\Project_GT\branches\v3\Temp\StagingArea\assets\bin\Data\Managed\UnityEngine.UI.dll" --assembly="C:\Project_GT\branches\v3\Temp\StagingArea\assets\bin\Data\Managed\Facebook.Unity.Settings.dll" --assembly="C:\Project_GT\branches\v3\Temp\StagingArea\assets\bin\Data\Managed\UnityEngine.dll" --assembly="C:\Project_GT\branches\v3\Temp\StagingArea\assets\bin\Data\Managed\Facebook.Unity.Android.dll" --assembly="C:\Project_GT\branches\v3\Temp\StagingArea\assets\bin\Data\Managed\Facebook.Unity.IOS.dll" --assembly="C:\Project_GT\branches\v3\Temp\StagingArea\assets\bin\Data\Managed\Firebase.Crashlytics.dll" --assembly="C:\Project_GT\branches\v3\Temp\StagingArea\assets\bin\Data\Managed\mscorlib.dll" --generatedcppdir="C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput" 
> 
> stdout:
> Building libil2cpp.so with AndroidToolChain.
> 	Output directory: C:\Project_GT\branches\v3\Temp\StagingArea\assets\bin\Data\Native\armeabi-v7a
> 	Cache directory: C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache
> ObjectFiles: 566 of which compiled: 0
> Total compilation time: 404 milliseconds.
> il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: C:\ProgramSub\Android SDK\android-ndk-r13b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ @"C:\Users\lim.ic\AppData\Local\Temp\tmpDF86.tmp" -o "C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\linkresult_F4EA4A322A8564772DCE3E3B6C440115\libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id --sysroot "C:\ProgramSub\Android SDK\android-ndk-r13b\platforms\android-16\arch-arm" -gcc-toolchain "C:\ProgramSub\Android SDK\android-ndk-r13b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" -target armv7-none-linux-androideabi -Wl,--wrap,sigaction -L "C:\ProgramSub\Android SDK\android-ndk-r13b\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a" -lgnustl_static -llog -Xlinker -Map="C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\linkresult_F4EA4A322A8564772DCE3E3B6C440115\libil2cpp.map" -rdynamic -fPIE -pie -fuse-ld=bfd.exe
> 
> clang++.exe: warning: argument unused during compilation: '-pie'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADURelease_m763974323':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUSetAdLoaderCallbacks_m2055661077':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:31455: undefined reference to `GADUSetAdLoaderCallbacks'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUCreateAdLoader_m419205992':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:31409: undefined reference to `GADUCreateAdLoader'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADURelease_m763974323':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUSetAdLoaderCallbacks_m2055661077':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:31455: undefined reference to `GADUSetAdLoaderCallbacks'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADURelease_m763974323':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADURequestNativeAd_m3836341943':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:31437: undefined reference to `GADURequestNativeAd'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADURelease_m763974323':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUCreateRequest_m3767898388':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30559: undefined reference to `GADUCreateRequest'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUAddKeyword_m170650300':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30647: undefined reference to `GADUAddKeyword'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUAddTestDevice_m2619105564':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30629: undefined reference to `GADUAddTestDevice'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUSetBirthday_m705684977':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30661: undefined reference to `GADUSetBirthday'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUSetGender_m1672314204':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30671: undefined reference to `GADUSetGender'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUTagForChildDirectedTreatment_m1380093157':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30681: undefined reference to `GADUTagForChildDirectedTreatment'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUCreateMutableDictionary_m1983330630':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30570: undefined reference to `GADUCreateMutableDictionary'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUSetMediationExtras_m407848486':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30611: undefined reference to `GADUSetMediationExtras'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUSetRequestAgent_m1681430595':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30721: undefined reference to `GADUSetRequestAgent'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADURequestNativeAd_m3836341943':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:31437: undefined reference to `GADURequestNativeAd'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADURelease_m763974323':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUSetNativeCustomTemplateAdUnityClient_m2417165562':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:31588: undefined reference to `GADUSetNativeCustomTemplateAdUnityClient'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUSetNativeCustomTemplateAdCallbacks_m1125841482':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:31602: undefined reference to `GADUSetNativeCustomTemplateAdCallbacks'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADURelease_m763974323':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUCreateSmartBannerView_m3209579712':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30787: undefined reference to `GADUCreateSmartBannerView'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUCreateBannerView_m637407593':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30749: undefined reference to `GADUCreateBannerView'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUCreateAnchoredAdaptiveBannerView_m831756769':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30825: undefined reference to `GADUCreateAnchoredAdaptiveBannerView'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADURelease_m763974323':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUCreateSmartBannerView_m3209579712':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30787: undefined reference to `GADUCreateSmartBannerView'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUCreateAnchoredAdaptiveBannerView_m831756769':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30825: undefined reference to `GADUCreateAnchoredAdaptiveBannerView'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUCreateBannerView_m637407593':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30749: undefined reference to `GADUCreateBannerView'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUSetBannerCallbacks_m1262466430':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30883: undefined reference to `GADUSetBannerCallbacks'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUCreateSmartBannerViewWithCustomPosition_m1719150722':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30806: undefined reference to `GADUCreateSmartBannerViewWithCustomPosition'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUCreateBannerViewWithCustomPosition_m3557624113':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30768: undefined reference to `GADUCreateBannerViewWithCustomPosition'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUCreateAnchoredAdaptiveBannerViewWithCustomPosition_m231460978':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30844: undefined reference to `GADUCreateAnchoredAdaptiveBannerViewWithCustomPosition'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADURelease_m763974323':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUCreateSmartBannerViewWithCustomPosition_m1719150722':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30806: undefined reference to `GADUCreateSmartBannerViewWithCustomPosition'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUCreateAnchoredAdaptiveBannerViewWithCustomPosition_m231460978':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30844: undefined reference to `GADUCreateAnchoredAdaptiveBannerViewWithCustomPosition'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUCreateBannerViewWithCustomPosition_m3557624113':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30768: undefined reference to `GADUCreateBannerViewWithCustomPosition'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADURequestBannerAd_m2043695255':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30923: undefined reference to `GADURequestBannerAd'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADURelease_m763974323':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADURequestBannerAd_m2043695255':
> C:\Project_GT\branches\v3\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30923: undefined reference to `GADURequestBannerAd'
> C:\Project_GT\branches\v3\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\4D0D03DA417454249FFC8667A8AE1A4E.o: In function `Externs_GADUShowBannerView_m30791<message truncated>

**Comment by khalilhoti** [comment]
i have exact same issue please help

**Comment by stowy** [comment]
As per #1208, I can confirm that this is an issue with the 5.x.x release, it will not build on Android using IL2CPP for Unity versions pre-2018 as Unity pre-2018 does not support compiling C++ source code in Plugins (eg Plugins/Android/externs.cpp).

We will likely need to move to using assembly definitions to remove the need to include C++ code for Android in order to support this. C++ source is compiled to an '__Internal' dll by Unity and hence the [DLLImport("__Internal")] for the symbols you are seeing are found.

**Comment by InFeIM** [comment]
Duplicate of #1208
