### ISSUE TITLE
 Android IL2CPP ARM64 build error in Unity 2017.4.32f1 (64-bit) version

### ISSUE THREAD

**Issue by ParkYoungJun7542** [googleads/googleads-mobile-unity#1208]
After updating to 5.0.1 version, an error occurs when building Android 64bit IL2CPP.

Unity Ver. : 2017.4.32f1

erro log
/////////////////////////////////////////////////////////////////////////
Failed running C:\Program Files\Unity2017432f1\Editor\Data\il2cpp/build/il2cpp.exe --convert-to-cpp --emit-null-checks --enable-array-bounds-check --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARMv7" --configuration="Release" --outputpath="D:\Project_GT_Common_Work\Temp/StagingArea\assets\bin\Data\Native\armeabi-v7a\libil2cpp.so" --cachedirectory="D:\Project_GT_Common_Work\Assets\..\Library\il2cpp_android_armeabi-v7a/il2cpp_cache" --additional-include-directories="C:\Program Files\Unity2017432f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\bdwgc/include" --additional-include-directories="C:\Program Files\Unity2017432f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\libil2cpp/include" --tool-chain-path="C:/android-ndk-r13b" --map-file-parser="C:\Program Files\Unity2017432f1\Editor\Data\Tools\MapFileParser\MapFileParser.exe" --assembly="D:\Project_GT_Common_Work\Temp\StagingArea\assets\bin\Data\Managed\Assembly-CSharp-firstpass.dll" --assembly="D:\Project_GT_Common_Work\Temp\StagingArea\assets\bin\Data\Managed\Assembly-CSharp.dll" --assembly="D:\Project_GT_Common_Work\Temp\StagingArea\assets\bin\Data\Managed\E7.NativeAudio.dll" --assembly="D:\Project_GT_Common_Work\Temp\StagingArea\assets\bin\Data\Managed\UnityEngine.UI.dll" --assembly="D:\Project_GT_Common_Work\Temp\StagingArea\assets\bin\Data\Managed\Facebook.Unity.Settings.dll" --assembly="D:\Project_GT_Common_Work\Temp\StagingArea\assets\bin\Data\Managed\UnityEngine.dll" --assembly="D:\Project_GT_Common_Work\Temp\StagingArea\assets\bin\Data\Managed\Facebook.Unity.Android.dll" --assembly="D:\Project_GT_Common_Work\Temp\StagingArea\assets\bin\Data\Managed\Facebook.Unity.IOS.dll" --assembly="D:\Project_GT_Common_Work\Temp\StagingArea\assets\bin\Data\Managed\Firebase.Crashlytics.dll" --assembly="D:\Project_GT_Common_Work\Temp\StagingArea\assets\bin\Data\Managed\mscorlib.dll" --generatedcppdir="D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput" 

stdout:
Building libil2cpp.so with AndroidToolChain.
	Output directory: D:\Project_GT_Common_Work\Temp\StagingArea\assets\bin\Data\Native\armeabi-v7a
	Cache directory: D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache
ObjectFiles: 566 of which compiled: 0
Total compilation time: 376 milliseconds.
il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: C:\android-ndk-r13b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ @"C:\Users\park.yj\AppData\Local\Temp\tmpBED5.tmp" -o "D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\linkresult_4B1E2AD5B062BD54B83BDE8369236202\libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id --sysroot "C:\android-ndk-r13b\platforms\android-16\arch-arm" -gcc-toolchain "C:\android-ndk-r13b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" -target armv7-none-linux-androideabi -Wl,--wrap,sigaction -L "C:\android-ndk-r13b\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a" -lgnustl_static -llog -Xlinker -Map="D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\linkresult_4B1E2AD5B062BD54B83BDE8369236202\libil2cpp.map" -rdynamic -fPIE -pie -fuse-ld=bfd.exe

clang++.exe: warning: argument unused during compilation: '-pie'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADURelease_m763974323':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUSetAdLoaderCallbacks_m2055661077':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:31455: undefined reference to `GADUSetAdLoaderCallbacks'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUCreateAdLoader_m419205992':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:31409: undefined reference to `GADUCreateAdLoader'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADURelease_m763974323':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUSetAdLoaderCallbacks_m2055661077':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:31455: undefined reference to `GADUSetAdLoaderCallbacks'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADURelease_m763974323':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADURequestNativeAd_m3836341943':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:31437: undefined reference to `GADURequestNativeAd'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADURelease_m763974323':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUCreateRequest_m3767898388':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30559: undefined reference to `GADUCreateRequest'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUAddKeyword_m170650300':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30647: undefined reference to `GADUAddKeyword'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUAddTestDevice_m2619105564':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30629: undefined reference to `GADUAddTestDevice'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUSetBirthday_m705684977':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30661: undefined reference to `GADUSetBirthday'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUSetGender_m1672314204':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30671: undefined reference to `GADUSetGender'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUTagForChildDirectedTreatment_m1380093157':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30681: undefined reference to `GADUTagForChildDirectedTreatment'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUCreateMutableDictionary_m1983330630':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30570: undefined reference to `GADUCreateMutableDictionary'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUSetMediationExtras_m407848486':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30611: undefined reference to `GADUSetMediationExtras'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUSetRequestAgent_m1681430595':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30721: undefined reference to `GADUSetRequestAgent'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADURequestNativeAd_m3836341943':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:31437: undefined reference to `GADURequestNativeAd'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADURelease_m763974323':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUSetNativeCustomTemplateAdUnityClient_m2417165562':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:31588: undefined reference to `GADUSetNativeCustomTemplateAdUnityClient'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUSetNativeCustomTemplateAdCallbacks_m1125841482':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:31602: undefined reference to `GADUSetNativeCustomTemplateAdCallbacks'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADURelease_m763974323':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUCreateSmartBannerView_m3209579712':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30787: undefined reference to `GADUCreateSmartBannerView'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUCreateBannerView_m637407593':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30749: undefined reference to `GADUCreateBannerView'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUCreateAnchoredAdaptiveBannerView_m831756769':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30825: undefined reference to `GADUCreateAnchoredAdaptiveBannerView'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADURelease_m763974323':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUCreateSmartBannerView_m3209579712':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30787: undefined reference to `GADUCreateSmartBannerView'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUCreateAnchoredAdaptiveBannerView_m831756769':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30825: undefined reference to `GADUCreateAnchoredAdaptiveBannerView'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUCreateBannerView_m637407593':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30749: undefined reference to `GADUCreateBannerView'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUSetBannerCallbacks_m1262466430':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30883: undefined reference to `GADUSetBannerCallbacks'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUCreateSmartBannerViewWithCustomPosition_m1719150722':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30806: undefined reference to `GADUCreateSmartBannerViewWithCustomPosition'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUCreateBannerViewWithCustomPosition_m3557624113':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30768: undefined reference to `GADUCreateBannerViewWithCustomPosition'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUCreateAnchoredAdaptiveBannerViewWithCustomPosition_m231460978':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30844: undefined reference to `GADUCreateAnchoredAdaptiveBannerViewWithCustomPosition'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADURelease_m763974323':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUCreateSmartBannerViewWithCustomPosition_m1719150722':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30806: undefined reference to `GADUCreateSmartBannerViewWithCustomPosition'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUCreateAnchoredAdaptiveBannerViewWithCustomPosition_m231460978':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30844: undefined reference to `GADUCreateAnchoredAdaptiveBannerViewWithCustomPosition'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUCreateBannerViewWithCustomPosition_m3557624113':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30768: undefined reference to `GADUCreateBannerViewWithCustomPosition'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADURequestBannerAd_m2043695255':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30923: undefined reference to `GADURequestBannerAd'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADURelease_m763974323':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30735: undefined reference to `GADURelease'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADURequestBannerAd_m2043695255':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30923: undefined reference to `GADURequestBannerAd'
D:\Project_GT_Common_Work\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\DDA8C2CB0DC7422EB5BD90D41E6501CE.o: In function `Externs_GADUShowBannerView_m3079181443':
D:\Project_GT_Common_Work\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_1.cpp:30903: undefine<message truncated>

**Comment by stowy** [comment]
Can you confirm that you have the `externs.cpp` file in `Assets/Plugins/Android` (included in the Google Mobile Ads Unity package) and that it is checked for inclusion in Android builds, as per below?

<img width="1792" alt="Screen Shot 2020-03-16 at 9 04 53 AM" src="https://user-images.githubusercontent.com/5924628/76777365-542fd480-6765-11ea-9f8d-d3738464ab9a.png">

**Comment by ParkYoungJun7542** [comment]
![1584413212706](https://user-images.githubusercontent.com/62228869/76817195-87499500-6845-11ea-9cd3-a1576089a57d.jpg)


Yes, and Android check is also included.

**Comment by stowy** [comment]
Thanks @ParkYoungJun7542. I can confirm that this is an issue with the 5.x.x release, it will not build on Android using IL2CPP for Unity versions pre-2018 as Unity pre-2018 does not support compiling C++ source code.

We will likely need to move to using assembly definitions to remove the need to include C++ code for Android in order to support this. C++ source is compiled to an '__Internal' dll by Unity and hence the [DLLImport("__Internal")] for the symbols you are seeing are found.

**Comment by ParkYoungJun7542** [comment]
Thank you for answer.

Once downgraded to version 4.2.1 of Admob SDK, the problem was solved.

So will Admob SDK officially support only Unity2018 or later?

**Comment by ParkYoungJun7542** [comment]
Thank you for answer.

Once downgraded to version 4.2.1 of Admob SDK, the problem was solved.

So will Admob SDK officially support only Unity2018 or later?

**Comment by ParkYoungJun7542** [comment]
Thank you for answer.

Once downgraded to version 4.2.1 of Admob SDK, the problem was solved.

So will Admob SDK officially support only Unity2018 or later?

**Comment by zhangjianshuai** [comment]
> 4.2.1



> Thank you for answer.
> 
> Once downgraded to version 4.2.1 of Admob SDK, the problem was solved.
> 
> So will Admob SDK officially support only Unity2018 or later?

Hello, I have encountered the same problem. Where is the SDK of version 4.2.1 downloaded?

**Comment by perseus25** [comment]
I think, there are still many developers who are still using versions before Unity 2019. Actually, Unity versions are released quite quickly, and change a lot, maybe unstable. Therefore, for an application that has a lot of active users, we value stability, and must consider carefully before updating Unity.
I hope the Admob plugin development team continues to support older versions of Unity.
Thank you very much.

**Comment by stowy** [comment]
I am working on a solution for pre-2018 versions. Note the version 5.0.1 does support 2018.x versions.

**Comment by cdelvalleJC** [comment]
I had this issue and was because the iOS classes don't have #IF_UNITYIOS conditional compilation, and android tries to compile this dll. I added the conditionals in these files and I could compile but,is this a valid solution?

**Comment by stowy** [comment]
Yes that is fine, that is the solution in 4.2.1.

**Comment by stowy** [comment]
@cdelvalleJC  please try the [latest release](https://github.com/googleads/googleads-mobile-unity/releases/latest).
