### ISSUE TITLE
Missing OnUserEarnedReward callback on Android

### ISSUE THREAD

**Issue by RasmusFunday** [googleads/googleads-mobile-unity#1209]
I didn't receive an `OnUserEarnedReward` callback from a `RewardedVideo`. I can see from ADB that the UnityAds activity sends the `Unity Ads event: sending view event to` message.

**Comment by stowy** [comment]
Hi, thanks for your query.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.
