### ISSUE TITLE
admob+applovin+unity mediation ios build error

### ISSUE THREAD

**Issue by marad747** [googleads/googleads-mobile-unity#1211]
unity 2019.2.17
latest plugin( admob\unity medaition), updated xcode+mac os cataline 10.15.3
![image](https://user-images.githubusercontent.com/20600166/77206627-0f5ac380-6b00-11ea-822a-b3a08f409e25.png)
![image](https://user-images.githubusercontent.com/20600166/77206649-1aadef00-6b00-11ea-8ec7-d82ec347f39d.png)
![image](https://user-images.githubusercontent.com/20600166/77206778-7d9f8600-6b00-11ea-9022-9411296622b6.png)
![image](https://user-images.githubusercontent.com/20600166/77206799-8db76580-6b00-11ea-9347-711a5c7d5be1.png)

**Comment by stowy** [comment]
Hi @marad747 
You are missing the iOS library from the Google Mobile Ads Unity plugin. Try reimporting the plugin and ensure that you import the iOS library. It should be in the Assets/Plugins/iOS folder.

**Comment by marad747** [comment]
> Hi @marad747
> You are missing the iOS library from the Google Mobile Ads Unity plugin. Try reimporting the plugin and ensure that you import the iOS library. It should be in the Assets/Plugins/iOS folder.

i just update plugin and try to build again, i have errors
![image](https://user-images.githubusercontent.com/20600166/77308161-346b5400-6d03-11ea-9034-45721f186927.png)

**Comment by stowy** [comment]
You are now missing the GoogleMobile Ads AppLovin mediation package, refer to [these instructions](https://developers.google.com/admob/unity/mediation/applovin#import).
