### ISSUE TITLE
Compilation Errors on fresh import.

### ISSUE THREAD

**Issue by itspreshu** [googleads/googleads-mobile-unity#1215]
There's a compilation error on iOS platform importing the unitypackage release 5.0.1

I Did a google search looking for a fix, but it seems that no one has reported it.

Im using last version of Windows 10 and Unity 2019.3.3f1.

![image](https://user-images.githubusercontent.com/16416516/77448706-e07a7100-6dcf-11ea-85ea-f1f19b67e66a.png)

**Comment by stowy** [comment]
This appears to be related to lines [such as this](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Platforms/iOS/BannerClient.cs#L233):

`[MonoPInvokeCallback(typeof(GADUAdViewDidReceiveAdCallback))]`

Not sure why that error is occurring, seems like a namespacing issue. .

**Comment by itspreshu** [comment]
Yeah it is a pain, because it only happens with iOS package, even if you don't want to use this platform.

**Comment by stowy** [comment]
I will have an update out in the coming weeks that adds assembly definitions to the plugin to split out the plugin into platform specific assemblies.

In the mean time I would recommend using v4.2.1 as this should negate this issue for now.

**Comment by itspreshu** [comment]
That sounds great!, I will try version 4.2.1 until the new version comes out!, Thanks @stowy !

**Comment by itspreshu** [comment]
> @itspreshu please try the [latest release](https://github.com/googleads/googleads-mobile-unity/releases/latest).

It works now!, Thanks bro.

**Comment by stowy** [comment]
Great thanks for confirming 👍
