### ISSUE TITLE
iOS AdMob Tapjoy Mediation crash issue

### ISSUE THREAD

**Issue by hungweng** [googleads/googleads-mobile-unity#1218]
Hi, when the app is trying to load Tapjoy ads, the app crash with the following error:

`Uncaught exception: NSInternalInconsistencyException: Could not load NIB in bundle: 'NSBundle </private/var/containers/Bundle/Application/E24C2A81-1AC5-416B-8299-39795736E75A/appName.app> (loaded)' with name 'TJCLoadingView'`

Can be easily reproduced using mediation test suite
In Mediation Test Suite:
Adapter Initialization Status shows Not Ready
SDK Found v12.4.2
Adapter Found v12.4.2.0
Placement Name and SDK Key Found

I'm using
Unity 2019.3.0f6
GoogleMobileAds tried both v4.2.1 and v5.0.1
Tapjoy mediation plugin v2.4.1

Every other ad sources (ironsource, facebook, unity, applovin...etc) works normally as expected

Not sure how to solve this...

**Comment by stowy** [comment]
This sounds like a TapJoy integration issue. Have you tried testing TapJoy itself or contacting TapJoy?

Also https://stackoverflow.com/questions/20336418/xcode-copied-project-not-working has the same error. So it seems the TapJoy bundle is missing perhaps? Can you check included resources in the xcode build phases?

**Comment by hungweng** [comment]
Thank you @stowy 

I followed the document here to integrate Tapjoy with mediation:
[https://developers.google.com/admob/unity/mediation/tapjoy](https://developers.google.com/admob/unity/mediation/tapjoy)

I saw that stackoverflow page as well, but I can't seem to add TapjoyResources.bundle to the build phase, is it because Tapjoy sdk was added through cocoapod?

**Comment by stowy** [comment]
According to their podspec the bundles should be included in the pod. [See the podspec here](https://github.com/CocoaPods/Specs/blob/master/Specs/1/5/3/TapjoySDK/12.4.2/TapjoySDK.podspec.json#L21).  Check your xcode workspace to see if the cocoapods installation did install the required bundles. May be worth trying a clean build.

**Comment by hungweng** [comment]
Thank you @stowy 

The bundle is included in the pod, I've also tried a clean build, but still getting the same error.
I get the same error on builds from both Unity Cloud build and local.

**Comment by TehLexAeterna** [comment]
Looks like the same issue here. See stacktrace attached.

![image](https://user-images.githubusercontent.com/11820788/79504796-1829b100-803c-11ea-895e-9ef61b0980bd.png)

**Comment by LukePenkava** [comment]
any update on this?

**Comment by stowy** [comment]
I'm really not sure that there's anything we can do here. If you don't think it's an issue with the cocoapods integration of TapJoy, I would recommend posting on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios - they will be able to help debug your issue with you efficiently.

**Comment by LukePenkava** [comment]
@stowy Thanks for quickly reply. To be honest i have no idea where could be the issue. This is what my cocoapods look like

```
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'UnityFramework' do
  pod 'GoogleMobileAdsMediationTapjoy', '12.4.2.1'
  pod 'GoogleMobileAdsMediationUnity', '3.4.2.1'
  pod 'Google-Mobile-Ads-SDK', '~> 7.58'
end
```

If there is something i can try, i will gladly do so, but to me, it seems to be an issue with the imported package for the tapjoy adapter? Right before importing it everything worked fine, after import i am getting this error:

> 2020-05-21 01:40:56.476259+0200 testapp[3764:2168218] Uncaught exception: NSInternalInconsistencyException: Could not load NIB in bundle: 'NSBundle </private/var/containers/Bundle/Application/88FD2B16-F2DF-4F7B-AAB8-E12A47E163C1/locksmith.app> (loaded)' with name 'TJCLoadingView'
> (
> 	0   CoreFoundation                      0x0000000183f40178 9624AAFD-5437-3772-A507-0F357875808D + 1253752
> 	1   libobjc.A.dylib                     0x0000000183c54c1c objc_exception_throw + 60
> 	2   CoreFoundation                      0x0000000183e2fbb8 9624AAFD-5437-3772-A507-0F357875808D + 138168
> 	3   UIKitCore                           0x0000000187d06fa8 66C0BDEB-71CF-3148-AF27-A5B055FAD9A5 + 7249832
> 	4   UIKitCore                           0x0000000187d07e08 66C0BDEB-71CF-3148-AF27-A5B055FAD9A5 + 7253512
> 	5   UnityFramework                      0x00000001042dae80 -[TJCLoadingView initWithFrame:] + 140
> 	6   UnityFramework                      0x00000001042dbbb8 -[TJCUIWebPageView initHelperWithFrame:] + 164
> 	7   UnityFramework                      0x00000001042db3dc -[TJCUIWebPageView initWithFrame:placement:] + 164
> 	8   UnityFramework                      0x00000001043331e0 -[TJEventOptimizer setupWebView] + 112
> 	9   UnityFramework                      0x0000000104333098 -[TJEventOptimizer init] + 68
> 	10  UnityFramework                      0x0000000104333034 +[TJEventOptimizer optimizer] + 48
> 	11  UnityFramework                      0x0000000104332ff4 +[TJEventOptimizer startup] + 20
> 	12  Foundation                          0x00000001843398fc 2B7BD2F3-10A8-3CBA-9DE3-5E1F48D9213E + 1321212
> 	13  CoreFoundation                      0x0000000183ebb860 9624AAFD-5437-3772-A507-0F357875808D + 710752
> 	14  CoreFoundation                      0x0000000183ebb7b4 9624AAFD-5437-3772-A507-0F357875808D + 710580
> 	15  CoreFoundation                      0x0000000183ebaf04 9624AAFD-5437-3772-A507-0F357875808D + 708356
> 	16  CoreFoundation                      0x0000000183eb5ca4 9624AAFD-5437-3772-A507-0F357875808D + 687268
> 	17  CoreFoundation                      0x0000000183eb5660 CFRunLoopRunSpecific + 480
> 	18  GraphicsServices                    0x000000018e2c6604 GSEventRunModal + 164
> 	19  UIKitCore                           0x000000018808a15c UIApplicationMain + 1944
> 	20  UnityFramework                      0x00000001040189d8 -[UnityFramework runUIApplicationMainWithArgc:argv:] + 108
> 	21  locksmith                           0x0000000100d6be1c main + 68
> 	22  libdyld.dylib                       0x0000000183d311ec 95B366E7-F5BD-3308-9416-24B35999029B + 4588
> )

**Comment by LukePenkava** [comment]
@stowy I have found this. Could the adapter be missing something like this?

https://stackoverflow.com/questions/58813504/could-not-load-nib-in-bundle-nsbundle-in-ios-swift

My knowledge of Swift is very basic, so i dont want to mess with this, but let me please know if this could help with the issue

**Comment by stowy** [comment]
The stack trace goes through to `TJCLoadingView` which is part of the TapJoy SDK. So this is an issue with the integration of the Tapjoy SDK, which is a dependency of the Google Tapjoy adapter.

**Comment by LukePenkava** [comment]
@stowy Thanks you are right. This is from their support page for the sdk.

> NB: Tapjoy does not currently support Unity 2019.3.x. If you have already updated please contact us for a workaround.

Well, i am on 2019.3, so thats apparently the issue. Will probably just drop Tapjoy for now then.

**Comment by agramonte** [comment]
I am having exactly the same error on a native build. Downgrading to version 12.3.3 of Tapjoy (the only older version I could find) resolved the issue.
