### ISSUE TITLE
Release 5.0.1 Can't compile in other platforms different to iOS & Android

### ISSUE THREAD

**Issue by SCastanedaMunoz** [googleads/googleads-mobile-unity#1225]
With the newest release many Extern calls were left in the code, this meant for Android a file called externs.cpp was added to the plugins folder. However, this did not account for any other platforms, when building to for example Universal Windows Platform if the project has GoogleMobileAds included (it will get package), but the unresolved extern calls will cause the build to not compile properly.

Either script define the extern calls with UNITY_IOS or make the solution with extern.cpp available to all platforms but iOS

Thanks!

**Comment by stowy** [comment]
@SCastanedaMunoz thanks for reporting. I'll be removing `externs.cpp` in the next release. Have you tried moving it to the Platforms folder and compiling for Windows?

**Comment by stowy** [comment]
@SCastanedaMunoz please try the [latest release](https://github.com/googleads/googleads-mobile-unity/releases/latest) (5.1.0).
