### ISSUE TITLE
Remove admob for Ios

### ISSUE THREAD

**Issue by robinDesBits** [googleads/googleads-mobile-unity#123]
Hello
I would like to use admob for android, but not for Ios, is there a solution ? I have all the time xcode error because of admob (whereas I am not suppose to use it) when I try.

**Comment by adelphia** [comment]
Did you follow the procedure for install AdMob for iOS? https://developers.google.com/admob/ios/quick-start?hl=en

**Comment by rampara** [comment]
You can also find additional documentation on our plugin [here](https://developers.google.com/admob/games#unity)

**Comment by rampara** [comment]
Closing issue due to non-response. If this issue persists, please re-open.

- Ram

**Comment by jsheikh27** [comment]
I know this post is old however I would like to reopen this question.  

I was able to get Admob working successfully for both platforms.  However, Apple has now come down hard on Kids apps that use analytics and also don't have a parental gate and this includes Ads.

After much rejection from Apple, I found out that Admob does not have a parental gate option for its Ads while Chartboost does.  However, I'm finding that Chartboost currently causes my app to crash on Android.  So I wanted to see if I can only have Admob work on Android and Chartboost on iOS.

Now here's the kicker.  I also found out that Google Analytics installs and boots up by default on iOS even though I don't use Admob at all.  It was only when I completely uninstalled Admob that Apple finally accepted my app into the store.

So any thoughts on this?  Please don't suggest 2 code bases as that would defeat the purpose of using Unity.

Thanks
