### ISSUE TITLE
Ad Closed Events not working

### ISSUE THREAD

**Issue by albus702** [googleads/googleads-mobile-unity#124]
Code: 
Interstitial.LoadAd(request);
Interstitial.AdClosed+=delegate{ Application.Quit(); };

The above code works with older versions of this package but does not work with the latest version and Unity 5.

**Comment by rampara** [comment]
In our sample application linked [here](https://github.com/googleads/googleads-mobile-unity/tree/master/unity/samples/HelloWorld), I am able to receive the ad closing and ad closed events for interstitials. Are you able to reproduce your problem in our sample application?

- Ram

**Comment by rampara** [comment]
Closing issue due to non-response. If this issue persists, please re-open.

- Ram
