### ISSUE TITLE
Facebook Adapter versions deleted

### ISSUE THREAD

**Issue by mcrvaz** [googleads/googleads-mobile-unity#1241]
As seen [here](https://github.com/googleads/googleads-mobile-ios-mediation/issues/209), they deleted some of the old(but not so) Facebook adapters from the cocoapods repository.
This breaks versions 2.6.1, 2.7.0 and 2.7.1 of the [Facebook Unity Mediation Plugin](https://developers.google.com/admob/unity/mediation/facebook#facebook-unity-mediation-plugin-changelog).
Which versions should we use now?

**Comment by mcrvaz** [comment]
Seems to be resolved with https://github.com/googleads/googleads-mobile-unity/pull/1240

**Comment by talhakaya** [comment]
I was surprised when suddenly our iOS builds stopped compiling... I guess we need to upgrade everything now. Thanks for the post.
