### ISSUE TITLE
2 files need add "using system" in Unity 5.6.3p1

### ISSUE THREAD

**Issue by EldersJavas** [googleads/googleads-mobile-unity#1249]
sorry ,my English is poor.
\editor\AndroidBuildPostProcessor.cs
\editor\ManifestProcessor.cs
Hi, everyone. Unity kept reporting errors while I was testing the plugin.
I was prompted to add "using System" to these two code files.
When I added this code, unity was error-free and working.
I don't know what the problem is.

**Comment by stowy** [comment]
thanks @EldersJavas - feel free to create a pull request if you think this is necessary.

**Comment by stowy** [comment]
Fixed by https://github.com/googleads/googleads-mobile-unity/pull/1263
