### ISSUE TITLE
Docs about supporting interstitial video ads

### ISSUE THREAD

**Issue by mpaolino** [googleads/googleads-mobile-unity#125]
It would be nice if interstitial video ads were supported, and if so,  it would be even better that documentation explicitly stated that. Could you please comment on that?

**Comment by rampara** [comment]
You can find documentation for both banners and interstitials [here](https://developers.google.com/admob/games#unity).

**Comment by mpaolino** [comment]
Thanks, I was just wondering if video interstitials formats were supported under Unity SDK plugin, its not very clear in the linked documentation. Feel free to close this issue :+1:
