### ISSUE TITLE
Allow option to leave ads disabled for a particular platform

### ISSUE THREAD

**Issue by aDu** [googleads/googleads-mobile-unity#1259]
Let's say we have a mobile game, and we only want to enable ads for iOS, but not Android.

So, I untick the Enabled "checkbox" for both Google Ad Manager and Google AdMob.

When building, I get this error:
`Neither Ad Manager nor AdMob is enabled yet.`

I want to be able to build without specifying an App Id. Of course I could just enable it and just not show the banner, but I don't know if Admob will like it if it disabled Ad serving on Android but not iOS (don't want to get terminated on Admob).

**Comment by stowy** [comment]
Hi @aDu using this method is not the appropriate way to disable AdMob in a given platform. If you use admob you need to supply an ID / setting for at least one platform.

To disable adMob in a given platform, you should surround your admob code with 
```
#if !<PLATFORM>
<Admob code>
#endif
```

**Comment by aDu** [comment]
Ok I see, thanks!
