### ISSUE TITLE
.hide / .destroy - android unsolvable issue.

### ISSUE THREAD

**Issue by BlopeetyBlop** [googleads/googleads-mobile-unity#126]
Hide and Destroy methods are not working regardless the type of implementation and usage.
Latest release, latest sdks, latest unity.
Complete fail.

**Comment by rampara** [comment]
In our sample application linked [here](https://github.com/googleads/googleads-mobile-unity/tree/master/unity/samples/HelloWorld), I am able to hide and destroy banners without issue. Are you able to reproduce your problem in our sample application?

- Ram

**Comment by BlopeetyBlop** [comment]
The issue was reproduced to the following so far.
It is unable to  target multiple scenes with simple conditional statement 
 and from all of them to exclude one in which hide() is used.
it is currently possible only to display the banerview in only one or in all scenes at the same time. 
i'm not sure that the explanation  was good enough.
e.g you can say show the banner if scene == MainScene, but it is not possible to say show this add everywhere except mainScene.

**Comment by rampara** [comment]
We have a blog post outlining best practices when showing ads in multiple scenes. You can find it [here](http://googleadsdeveloper.blogspot.com/2015/11/multiple-scenes-and-ads-in-unity.html).

- Ram
