### ISSUE TITLE
Smart Banner too small in landscape

### ISSUE THREAD

**Issue by robinDesBits** [googleads/googleads-mobile-unity#127]
Hello ! 
I'm using smart banner, but in landscape the banner is smaller than my screen width.
I tried to use a custom size, but then the banner doesn't show anymore...
AdSize adSize = new AdSize(Screen.width, 60);
banner = new BannerView ("ca-app-pub-8817389437500335/3672391604", adSize, AdPosition.Bottom);

**Comment by rampara** [comment]
I have filed a bug against the Android Google Mobile Ads SDK engineering team for this issue. As for custom sizes, that is something that is not supported at this time. 

- Ram

**Comment by rampara** [comment]
This should not longer be an issue on the latest version of the GMA SDK. Please re-open if this issue persists for you.
