### ISSUE TITLE
Fyber Ads not visible in Mediation Test Suit

### ISSUE THREAD

**Issue by JabluszkoPL** [googleads/googleads-mobile-unity#1279]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2018.4+
  * Google Mobile Ads Unity plugin version: 5.0.1
  * Platform: Android, possible iOS
  * Platform OS version: Android 9
  * Any specific devices issue occurs on: All
  * Mediation ad networks used, and their versions: 

```
- Google Mobile Ads Unity Mediation - v5.0.1
- AdColony Unity Adapter - v2.0.1
- AppLovin Unity Adapter - v4.4.1
- Chartboost Unity Adapter - v2.0.1
- Facebook Unity Adapter - v2.8.0
- InMobi Unity Adapter - v2.4.0
- Ironsource Unity Adapter - v1.5.0
- Mopub Unity Adapter - v2.9.0
- Tapjoy Unity Adapter - v2.4.1
- Unity Ads Unity Adapter - v2.4.1
- Verizon Unity Adapter - v1.2.0
- Vungle Unity Adapter - v3.2.0

- Fyber Unity Adapter - v1.1.0
- Mediation Test Suite Unity - v1.3.0
```

### [REQUIRED] Step 2: Describe the problem
I can't see Fyber ads in Mediation Test Suite, They are set for project and I can't verify that the setup is correct
#### Steps to reproduce:
* Set Fyber ads on dashboard
* Run Unity project with AdMob
* Open Mediation Test Suite and check tat there is not Fyber Ads

What happened? How can we make the problem occur?
Just launch Mediation Test Suite

**Comment by stowy** [comment]
Thanks @JabluszkoPL - we are working on a new release of Mediation Test Suite that includes Fyber, I will notify you here when this release is available, it will be within 1-2 weeks.
