### ISSUE TITLE
Banner ads explode when animating. (cycling)

### ISSUE THREAD

**Issue by paolo-lionhg** [googleads/googleads-mobile-unity#128]
I really don't know the proper term to use. But when the banner ads do the animation cycle, it just explodes. 

![screenshot_2015-10-09-15-15-18](https://cloud.githubusercontent.com/assets/14221919/10388083/8cf831be-6e99-11e5-979b-92662ce8e363.jpeg)
![screenshot_2015-10-09-15-15-23](https://cloud.githubusercontent.com/assets/14221919/10388087/914c115e-6e99-11e5-9b0f-4d726903f748.jpeg)

I am using the latest unity3d version, and latest googleads version. And I am using unity canvas for my background image and all UI. 

*On my edit, I just cropped out the screen shots.

**Comment by rampara** [comment]
Hi @paolo-lionhg,

To help debug the issue, could you provide more information.

On what platform are you seeing the issue?
Is the issue reproducible?

A charles log for an ad request where you see the issue would also be helpful.

- Ram

**Comment by paolo-lionhg** [comment]
i'm using it on android. yes it happens all the time for me. how do i get the log?

**Comment by rampara** [comment]
[This link](http://university.utest.com/how-to-set-up-charles-web-debugging-proxy-for-android-devices-and-mac) provides instructions on how to set up a Charles Web Debugging Proxy for Android Devices. Also, can you provide the following details about the device on which you are seeing the issue.

Device name
Android version
Google Play Services version

- Ram

**Comment by rampara** [comment]
Providing a sample project or apk should also be helpful for trying to find the root cause of the issue.

**Comment by paolo-lionhg** [comment]
while doing some testing i just found out it is device specific. on my samsung grand the ads work fine. but on my lenovo x2, the bug happens.

Samsung:
Model: GT-I9082
Android OS: 4.2.2
Google Services: Version 8.1.15 (2250156-034)

Lenovo:
Model: Lenovo X2-EU
Android OS: 4.4.2
Google Services: Version 8.3.00 (2353383-038)

**Comment by rampara** [comment]
I am unable to reproduce the issue on any devices available to me. If you see this issue in other devices, please update the issue with the details of the device. For now, I will not be able to debug this issue any further. 

- Ram
