### ISSUE TITLE
Unity Android Build error - More than one file was found with OS independent path 'META-INF/androidx.lifecycle_lifecycle-runtime.version'

### ISSUE THREAD

**Issue by Mr420BlazedIt** [googleads/googleads-mobile-unity#1282]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.3.11f1
  * Google Mobile Ads Unity plugin version: Latest
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem

Hi, so I've had lots of problems trying to build for android, my original issue is when I added google Ads via the zip and got many errors - so I added the unity package instead and the build now gets further.
When it gets to building Gradle I get an error that I cant resolve. I'm using the SDK, JDK , NDK, Gradle that is provided by unity.

I hope there is a solution that can fix this or maybe its so simple and I'm stupid but I cant wait to hear back!

Thank you

#### Relevant Code:

CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Java/jdk1.8.0_251\bin\java.exe -classpath "C:\Program Files\Unity\Hub\Editor\2019.3.11f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-5.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:transformResourcesWithMergeJavaResForRelease'.
> More than one file was found with OS independent path 'META-INF/androidx.lifecycle_lifecycle-runtime.version'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 7s
]
stdout[

> Configure project :launcher
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.3.11f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\28.0.3\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.3.11f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.3.11f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-28\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.3.11f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.3.11f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\28.0.3\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.3.11f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.3.11f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-28\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.3.11f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only

> Task :unityLibrary:GoogleMobileAdsPlugin:preBuild UP-TO-DATE
> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:checkReleaseManifest
> Task :unityLibrary:GoogleMobileAdsPlugin:checkReleaseManifest
> Task :launcher:extractProguardFiles
> Task :launcher:prepareLintJar
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:GoogleMobileAdsPlugin:processReleaseManifest
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin:generateReleaseResValues
> Task :unityLibrary:GoogleMobileAdsPlugin:generateReleaseResources
> Task :unityLibrary:generateReleaseBuildConfig
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResValues
> Task :unityLibrary:generateReleaseResources
> Task :unityLibrary:GoogleMobileAdsPlugin:packageReleaseResources
> Task :unityLibrary:packageReleaseResources
> Task :unityLibrary:prepareLintJar
> Task :unityLibrary:generateReleaseSources
> Task :unityLibrary:prepareLintJarForPublish
> Task :unityLibrary:mergeReleaseShaders
> Task :unityLibrary:compileReleaseShaders
> Task :unityLibrary:generateReleaseAssets
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:mergeReleaseConsumerProguardFiles
> Task :unityLibrary:GoogleMobileAdsPlugin:generateReleaseRFile
> Task :unityLibrary:GoogleMobileAdsPlugin:generateReleaseBuildConfig
> Task :unityLibrary:GoogleMobileAdsPlugin:prepareLintJar
> Task :unityLibrary:GoogleMobileAdsPlugin:generateReleaseSources
> Task :unityLibrary:GoogleMobileAdsPlugin:javaPreCompileRelease
> Task :unityLibrary:mergeReleaseJniLibFolders
> Task :launcher:preReleaseBuild
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :launcher:checkReleaseManifest
> Task :launcher:generateReleaseBuildConfig
> Task :launcher:generateReleaseSources
> Task :launcher:mainApkListPersistenceRelease
> Task :launcher:generateReleaseResValues
> Task :launcher:generateReleaseResources
> Task :unityLibrary:GoogleMobileAdsPlugin:compileReleaseJavaWithJavac
> Task :unityLibrary:GoogleMobileAdsPlugin:bundleLibCompileRelease
> Task :unityLibrary:GoogleMobileAdsPlugin:prepareLintJarForPublish
> Task :unityLibrary:GoogleMobileAdsPlugin:mergeReleaseShaders
> Task :unityLibrary:GoogleMobileAdsPlugin:compileReleaseShaders
> Task :unityLibrary:GoogleMobileAdsPlugin:generateReleaseAssets
> Task :unityLibrary:GoogleMobileAdsPlugin:packageReleaseAssets
> Task :unityLibrary:GoogleMobileAdsPlugin:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin:bundleLibResRelease
> Task :unityLibrary:GoogleMobileAdsPlugin:bundleLibRuntimeRelease
> Task :unityLibrary:GoogleMobileAdsPlugin:mergeReleaseConsumerProguardFiles
> Task :unityLibrary:GoogleMobileAdsPlugin:mergeReleaseJniLibFolders
> Task :unityLibrary:GoogleMobileAdsPlugin:transformNativeLibsWithMergeJniLibsForRelease
> Task :unityLibrary:GoogleMobileAdsPlugin:transformNativeLibsWithStripDebugSymbolForRelease
> Task :unityLibrary:GoogleMobileAdsPlugin:transformNativeLibsWithIntermediateJniLibsForRelease
> Task :unityLibrary:generateReleaseRFile
> Task :unityLibrary:javaPreCompileRelease
> Task :launcher:mergeReleaseResources
> Task :launcher:createReleaseCompatibleScreenManifests
> Task :launcher:processReleaseManifest
> Task :unityLibrary:compileReleaseJavaWithJavac
> Task :unityLibrary:bundleLibCompileRelease
> Task :launcher:processReleaseResources
> Task :unityLibrary:bundleLibResRelease
> Task :launcher:javaPreCompileRelease
> Task :unityLibrary:bundleLibRuntimeRelease
> Task :unityLibrary:transformNativeLibsWithMergeJniLibsForRelease
> Task :unityLibrary:transformNativeLibsWithStripDebugSymbolForRelease
> Task :unityLibrary:transformNativeLibsWithIntermediateJniLibsForRelease
> Task :launcher:compileReleaseJavaWithJavac
> Task :launcher:compileReleaseSources

> Task :launcher:lintVitalRelease
Calling mockable JAR artifact transform to create file: C:\Users\adunc\.gradle\caches\transforms-2\files-2.1\c68ce5ecd57e503736063238b6a91606\android.jar with input C:\Program Files\Unity\Hub\Editor\2019.3.11f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-28\android.jar

> Task :launcher:mergeReleaseShaders
> Task :launcher:compileReleaseShaders
> Task :launcher:generateReleaseAssets
> Task :launcher:mergeReleaseAssets
> Task :launcher:validateSigningRelease
> Task :launcher:signingConfigWriterRelease
> Task :launcher:processReleaseJavaRes NO-SOURCE
> Task :launcher:transformResourcesWithMergeJavaResForRelease FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
62 actionable tasks: 62 executed
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <e0e49ea825d44cdfa973f5fccb9b80fd>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <e0e49ea825d44cdfa973f5fccb9b80fd>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <e0e49ea825d44cdfa973f5fccb9b80fd>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <e0e49ea825d44cdfa973f5fccb9b80fd>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <e0e49ea825d44cdfa973f5fccb9b80fd>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <e0e49ea825d44cdfa973f5fccb9b80fd>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <e0e49ea825d44cdfa973f5fccb9b80fd>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <e0e49ea825d44cdfa973f5fccb9b80fd>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) (at <e0e49ea825d44cdfa973f5fccb9b80fd>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <e0e49ea825d44cdfa973f5fccb9b80fd>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <e0e49ea825d44cdfa973f5fccb9b80fd>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <e0e49ea825d44cdfa973f5fccb9b80fd>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <90d4bcb003fb405fb09241aed2f178aa>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by stowy** [comment]
Hi, sorry for the delayed response. This appears to be an issue with [Jar resolver](https://github.com/googlesamples/unity-jar-resolver) in that you have multiple copies of the lifecycle dependency. I would start by deleting all existing resolved android libraries using **Assets -> Play Services Resolver -> Android Resolver -> Delete Resolved Libraries**. Then resolve again using **Assets -> Play Services Resolver -> Android Resolver -> Force Resolve**. I would expect this to resolve the issue for you.

**Comment by MarconiusDMM** [comment]
I'm having a similar error trying to build Firebase, and the above solution seems to have changed nothing.

**Comment by stowy** [comment]
Can you please report this to [Jar resolver](https://github.com/googlesamples/unity-jar-resolver) as this is a dependency resolution error and not anything to do with the code in this repository as far as I'm aware.  You can also report it in [our support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) if you do not think it's a JAR resolver issue.

**Comment by amazighi** [comment]
thank you very much! 🙏
