### ISSUE TITLE
if (adSize == null) //BAD ... if ((object)adSize == null) //GOOD

### ISSUE THREAD

**Issue by pacoelayudante** [googleads/googleads-mobile-unity#1287]
Hola, I hope you are all good
I had this issue, it is pretty minor, but it might be quite a headache for someone at some point in the future (lucky for me it was very exposed, easy to find)
ISSUE:
`AdSize adSize = null;`
`if (adSize == null) //Null pointer exception!`
when trying to do a null check on adSize it tries to do this equals below, but without checking nullity in the equal itself... so I end up with a NullPointerException
AdMob CODE:
https://github.com/googleads/googleads-mobile-unity/blob/09d7fb914ad89e1b031ed1a229a81ad4c6374411/source/plugin/Assets/GoogleMobileAds/Api/Core/AdSize.cs#L117-L120

Workaround:
For now, it is resolved by casting the adSize as an object
`AdSize adSize = null;`
`if ((object)adSize == null) true;`

**Comment by stowy** [comment]
thanks for pointing this out! Will fix.

**Comment by pacoelayudante** [comment]
Wow that was blazing fast! Thank you!
Que tengas buen dia!
