### ISSUE TITLE
[bug]Unable to resolve reference 

### ISSUE THREAD

**Issue by pipe-alt** [googleads/googleads-mobile-unity#1295]
[REQUIRED] Step 1: Describe your environment

  Unity version: 2020.1b8
   Google Mobile Ads Unity plugin version: 5.1.0
   Platform: Android, unity editor 
  Platform OS version: Android 8 
   Any specific devices issue occurs on: Editor
   Mediation ad networks used, and their versions: none

[REQUIRED] Step 2: Describe the problem

 Steps to reproduce:

-install lastest 5.1.0 pluigin
-error shows in the console window 

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
"
Assembly 'Assets/ExternalDependencyManager/Editor/Google.IOSResolver_v1.2.153.dll' will not be loaded due to errors:
Unable to resolve reference 'UnityEditor.iOS.Extensions.Xcode'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
"
![bug](https://user-images.githubusercontent.com/54341095/81333524-bf659b00-9072-11ea-9b04-fc5a0c2f4a8a.png)

**Comment by stowy** [comment]
Are you running this on a Mac or Windows?

**Comment by pipe-alt** [comment]
@stowy  I'm running windows

**Comment by henimex** [comment]
i have a similar problem for adding referance of GoogleMobileAds.Api i just opened 2019.3.12f1 empty project and downloaded GoogleMobileAds-v5.1.0.unitypackage import package, switched platform, resolve player done everything as shown. but when i create my script and add googlemobileads library im getting 
`The type or namespace name 'GoogleMobileAds' could not be found (are you missing a using directive or an assembly reference?)` 

[https://hizliresim.com/ATcwzn](url)

**Comment by pipe-alt** [comment]
edit:  it also happens with plugin 5.0.1 maybe its an issue with  unity 2020.1 and the plugin

**Comment by stowy** [comment]
@pipe-alt this appears to be an issue with [Jar resolver](https://github.com/googlesamples/unity-jar-resolver) - although if you have iOS platform selected on Windows I wouldn't expect that to work since you can't install Xcode on windows. @henimex please file a separate issue for your concern.
