### ISSUE TITLE
Error when closing admob interstital ads in Unity5

### ISSUE THREAD

**Issue by yyhuang** [googleads/googleads-mobile-unity#130]
Recently I upgraded my project from Unity4.6 to Unity5.2.0f3.

I have registered InterstitialAd.AdClosed Event to control the sound of game, and after upgrading I had error messages like the following when closing interstitial ads.

> ArgumentException: set_mute can only be called from the main thread

The following code is simplified version of my code. It works correctly in Unity4.6.

``` 
    InterstitialAd page = new InterstitialAd(androidPageId);
    page.AdClosing += HandlePageClosing;
     
    void HandlePageClosing(object sender, EventArgs args) {
        // type of musicAudio is AudioSource
        musicAudio.mute = false;
    }
```

**Comment by rampara** [comment]
When ad events are forwarded from the Google Mobile Ads Android SDK to the Unity plugin through AndroidProxy, they will not be called on the main thread. To get around this, we recommend the following approach:

For actions required to be performed on the main thread before showing ad
- Perform actions before showing ad

For actions required to be performed on the main thread after showing ad
- Set a flag on the OnAdClosed ad event. The update method can check for this flag and perform actions as necessary.
- In the OnAdClosed ad event dispatch an event to a queue that is checked in the update method.

- Ram
