### ISSUE TITLE
iOS crashed with GoogleMobileAdsMediationVungle

### ISSUE THREAD

**Issue by ishnu47** [googleads/googleads-mobile-unity#1300]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2018.4.21f1
  * Google Mobile Ads Unity plugin version: 5.0.1
  * Platform: iOS
  * Platform OS version: iOS 12, iOS 13
  * Any specific devices issue occurs on: iPhone & iPad (>20% with iPhone 6s)
  * Mediation ad networks used, and their versions: Vungle v6.4.6.0

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
This crash happen randomly, and I can not reproduce on my side.
```
Crashed: com.apple.main-thread
0  myapp                         0x104aa7438 __30-[VungleConfigOperation start]_block_invoke + 4337022008
1  myapp                         0x104a860b4 __72-[VungleConfigController fetchConfigWithBackgroundInit:completionBlock:]_block_invoke_2 + 4336885940
2  myapp                         0x104a669f8 __80-[VNGNetworkManager(RequestFactory) configOperationWithBackgroundInit:complete:]_block_invoke + 4336757240
3  myapp                         0x104a6d744 -[VNGNetworkManager didCancelOperation:] + 4336785220
4  myapp                         0x104a4a0fc -[VungleNetworkOperation cancel] + 4336640252
5  myapp                         0x104a6e0e4 -[VNGNetworkManager cancelAllTransactions] + 4336787684
6  myapp                         0x104a4fae4 __53-[VunglePlacementsCoordinator appWillEnterBackground]_block_invoke + 4336663268
7  UIKitCore                      0x1c819f8c0 -[_UIBackgroundTaskInfo fireExpirationHandler] + 64
8  UIKitCore                      0x1c81a9390 _fireBackgroundExpirationHandlers + 640
9  UIKitCore                      0x1c81a903c -[UIApplication workspaceNoteAssertionExpirationImminent:] + 136
10 FrontBoardServices             0x1c92520cc __45-[FBSUIApplicationWorkspaceShim setDelegate:]_block_invoke_3 + 48
11 libdispatch.dylib              0x1c3df3184 _dispatch_client_callout + 16
12 libdispatch.dylib              0x1c3d9bfd8 _dispatch_block_invoke_direct$VARIANT$mp + 224
13 FrontBoardServices             0x1c92a3418 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 40
14 FrontBoardServices             0x1c92a30e4 -[FBSSerialQueue _queue_performNextIfPossible] + 404
15 FrontBoardServices             0x1c92a360c -[FBSSerialQueue _performNextFromRunLoopSource] + 28
16 CoreFoundation                 0x1c40a4a00 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
17 CoreFoundation                 0x1c40a4958 __CFRunLoopDoSource0 + 80
18 CoreFoundation                 0x1c40a40f0 __CFRunLoopDoSources0 + 180
19 CoreFoundation                 0x1c409f23c __CFRunLoopRun + 1080
20 CoreFoundation                 0x1c409eadc CFRunLoopRunSpecific + 464
21 GraphicsServices               0x1ce03f328 GSEventRunModal + 104
22 UIKitCore                      0x1c81ac63c UIApplicationMain + 1936
23 myapp                         0x1043718d0 main + 41 (main.mm:41)
24 libdyld.dylib                  0x1c3f28360 start + 4
```
This crash appears when I integrate mediation feature, without any code updating.

**Comment by joshuajplagonera** [comment]
Hi @ishnu47 
Based on the stack trace, it looks like a Vungle SDK specific issue. However, can you try using the [latest version of the Unity Mediation plugin for Vungle](https://github.com/googleads/googleads-mobile-unity/blob/master/mediation/Vungle/CHANGELOG.md#version-330)?

**Comment by PetrBodnar** [comment]
Hello @ishnu47

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!
