### ISSUE TITLE
Unityeditor + iOS ：EntryPointNotFoundException: GADUSetiOSAppPauseOnBackground

### ISSUE THREAD

**Issue by GITHUB243884919** [googleads/googleads-mobile-unity#1307]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2018.4.2
  * Google Mobile Ads Unity plugin version: 5.1.0
  * Platform: unity editor + ios (iOS, Android, Unity Editor)
  * Platform OS version: mac 10.15.4(eg iOS 10, Android 9)
  * Any specific devices issue occurs on: no devices
  * Mediation ad networks used, and their versions: no networks

### [REQUIRED] Step 2: Describe the problem
the unity console shows :EntryPointNotFoundException: GADUSetiOSAppPauseOnBackground
if I export to xcode then shows：
Error running CocoaPods. Please ensure you have at least version 1.0.0.  You can install CocoaPods with the Ruby gem package manager:
 > sudo gem install -n /usr/local/bin cocoapods
 > pod setup
.....
But if I type gem -v then shows :  3.0.3 and
if I type ruby -v then shows: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
and if I type gem list shows : cocoapods (1.8.4)
## Steps to reproduce:
1.import GoogleMobileAds-v5.1.0.unitypackage
2.write code in my start function:
    void Start()
    {
        MobileAds.SetiOSAppPauseOnBackground(true);
........
    }
3.run unity in editor
4.the unity console shows: EntryPointNotFoundException: GADUSetiOSAppPauseOnBackground

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
Unity console shows:
Error running CocoaPods. Please ensure you have at least version 1.0.0.  You can install CocoaPods with the Ruby gem package manager:
 > sudo gem install -n /usr/local/bin cocoapods
 > pod setup

'pod --version' returned status: 1
output: 

    [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    [0m
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:118:in `git_version': Failed to extract git version from `git --version` ("xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun\n") (RuntimeError)
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:130:in `verify_minimum_git_version!'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:49:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'

EntryPointNotFoundException: GADUSetiOSAppPauseOnBackground
GoogleMobileAds.iOS.MobileAdsClient.SetiOSAppPauseOnBackground (System.Boolean pause) (at Assets/GoogleMobileAds/Platforms/iOS/MobileAdsClient.cs:79)
GoogleMobileAds.Api.MobileAds.SetiOSAppPauseOnBackground (System.Boolean pause) (at Assets/GoogleMobileAds/Api/MobileAds.cs:98)
Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:
`void Start()
    {
        MobileAds.SetiOSAppPauseOnBackground(true);

        List<String> deviceIds = new List<String>();

        RequestConfiguration requestConfiguration;
        if (isTestMode)
        {
            deviceIds.Add(AdRequest.TestDeviceSimulator);
#if UNITY_IOS
            for (int i = 0; i < testDevices_appstore.Count; i++)
            {
                deviceIds.Add(testDevices_appstore[i]);
            }
#else
            for (int i = 0; i < testDevices_googleplay.Count; i++)
            {
                deviceIds.Add(testDevices_googleplay[i]);
            }
#endif

            requestConfiguration = new RequestConfiguration.Builder()
                .SetTagForChildDirectedTreatment(tagForChildDirectedTreatment)
                .SetTestDeviceIds(deviceIds).build();
        }
        else
        {
            requestConfiguration = new RequestConfiguration.Builder()
                .SetTagForChildDirectedTreatment(tagForChildDirectedTreatment).build();
        }

        MobileAds.SetRequestConfiguration(requestConfiguration);

        MobileAds.Initialize(OnInit);
    }`

**Comment by stowy** [comment]
Changing to iOS platform and running on Unity Editor is not a supported use case I'm afraid, the plugin that iOS uses is not compatible with Unity editor. I suggest switching to a different platform (Android works in my testing) when tryin to run in the Unity Editor.

With respect to cocoa pods not running correctly, I suggest reporting to the [Jar resolver plugin ](https://github.com/googlesamples/unity-jar-resolver)since that is what the Mobile Ads plugin uses to install dependencies and the source of your issue here.

**Comment by ChaserKnight** [comment]
After updating to the latest version (v5.1.0) of this plugin, I am also seeings this errorin unity editor "EntryPointNotFoundException: GADUSetiOSAppPauseOnBackground" issue. The earlier version (v5.0.1) of the plugin did not cause this issue. So as you said running in the editor with iOS platform is not supported use case. Has this just started from (v5.1.0)?

**Comment by GITHUB243884919** [comment]
> After updating to the latest version (v5.1.0) of this plugin, I am also seeings this errorin unity editor "EntryPointNotFoundException: GADUSetiOSAppPauseOnBackground" issue. The earlier version (v5.0.1) of the plugin did not cause this issue. So as you said running in the editor with iOS platform is not supported use case. Has this just started from (v5.1.0)?

Yes , I use admob first time, so I don't know other version。

**Comment by stowy** [comment]
I believe that previous versions that had the `externs.cpp` file may have allowed this to work. However that was removed as it was a temporary solution to enable building using IL2CPP which didn't work for all versions of Unity. So yes while version 5.0.1 may have enabled this temporarily it was not intended to be a supported use case, because of the way the Unity IDE works with iOS plugins.

**Comment by ChaserKnight** [comment]
> I believe that previous versions that had the `externs.cpp` file may have allowed this to work. However that was removed as it was a temporary solution to enable building using IL2CPP which didn't work for all versions of Unity. So yes while version 5.0.1 may have enabled this temporarily it was not intended to be a supported use case, because of the way the Unity IDE works with iOS plugins.

Thanks a lot @stowy for the quick reply helping me understand how it works. Sometimes it becomes hard for me to understand how all these plugin stuff actually works in the background. So hearing from a knowledgeable person like you helps a lot. Thanks again to you and the AdMob team for creating this great product.

**Comment by stowy** [comment]
No worries, agreed it's a bit of a complex beast at times, we're doing our best to make it easier, appreciate your feedback!
