### ISSUE TITLE
Pass onAdFailedToLoad error CODE to Unity listeners

### ISSUE THREAD

**Issue by nicolasgramlich** [googleads/googleads-mobile-unity#1309]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: `All`
  * Google Mobile Ads Unity plugin version: `5.1.0`
  * Platform: `All` (iOS, Android, Unity Editor)
  * Platform OS version: `All` (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: `All`
  * Mediation ad networks used, and their versions: `N/A`

#### Steps to reproduce:
The `onAdFailedToLoad` doesn't provide the underlying error code, which makes it "impossible" (without stupid hacks) to know if it's a `NO_FILL` error (aka don't retry) or a `ERROR_CODE_NETWORK_ERROR ` (aka retryable) error. The SDK seems to actively hide the error codes for some unknown reason and convert them to a string:

https://github.com/googleads/googleads-mobile-unity/blob/ba5ce3fd0fc55d4892f4aff93d420acda3169884/source/android-library/app/src/main/java/com/google/unity/ads/PluginUtils.java#L81-L95

This makes it very risky for any Unity developer to get banned from Admob due to a policy violation:

![image](https://user-images.githubusercontent.com/287060/82157556-06078200-9837-11ea-88f7-f0f271f26972.png)

Passing the error code alongside the message seems to be a no brainer and is likely even a non breaking change.

**Comment by stowy** [comment]
Thanks @nicolasgramlich for the feedback, agreed this could be passed in the string. You are welcome to open a pull request for this, otherwise I will put it on my list.

**Comment by nicolasgramlich** [comment]
@stowy I don't think I have the bandwidth right now. If it gets done, I'd suggest not putting it `in` the string, but as a sibling parameter of the error. Even if it ends up being a breaking change, I think it would be worth it nontheless.

**Comment by URETY** [comment]
I facing the same problem  After 2 to 3-time Loading ads... Ad loading failed until I close the application and run it again :(.

If anyone can facing the same problem and can fix it pls...  give share how u can solve it :). :)

**Comment by khalidhex** [comment]
@nicolasgramlich Can you share an example of the "hacks" to know what is the error underline ?

**Comment by NVentimiglia** [comment]
This issue should be fixed. 

https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/GoogleMobileAds/Api/AdError.cs#L40
