### ISSUE TITLE
On Unity Editor, InitializationStatus.client == null, which leads to some errors

### ISSUE THREAD

**Issue by pacoelayudante** [googleads/googleads-mobile-unity#1314]
On Editor, calling InitializationStatus.getAdapterStatusMap(), or similar functions, returns a null pointer exception error

https://github.com/googleads/googleads-mobile-unity/blob/992050ac91bd9510ed8d36de7b4cf497a4fae174/source/plugin/Assets/GoogleMobileAds/Common/DummyClient.cs#L76-L80

I discovered this while doing 
```C#
#UNITY_EDITOR
MobileAds.Initialize( (InitializationStatus initStatus)=>{
    var map = initStatus.getAdapterStatusMap(); // Error, null pointer exception, because initStatus.client == null
});
```
https://github.com/googleads/googleads-mobile-unity/blob/992050ac91bd9510ed8d36de7b4cf497a4fae174/source/plugin/Assets/GoogleMobileAds/Api/InitializationStatus.cs#L34-L37

**Comment by rotter** [comment]
I was using an older AdMob plugin (4.2.1 I think), just updated today to the latest (5.2.0) and started getting this exception every time I try to launch my game on Unity (Editor) to test anything... this seems to be a pretty serious and consistent bug (happens 100% of the time for me), I dont understand why it's ignored

**Comment by rotter** [comment]
Any updates? Still getting this exception every time I launch my games on the Editor...

**Comment by stowy** [comment]
The tagged CLs resolve this. The next release is due in the coming week and will contain this fix.

**Comment by rotter** [comment]
Thanks!!!

**Comment by pacoelayudante** [comment]
In the mean time you can reduce the annoyingness of this issue with the compile time commands of unity:
https://docs.unity3d.com/Manual/PlatformDependentCompilation.html
kinda like this
```csharp
Dictionary<string, AdapterStatus> statusMap;
#if !UNITY_EDITOR
statusMap = InitializationStatus.getAdapterStatusMap();
#endif
if (statusMap != null) ///do stuff
```

**Comment by stowy** [comment]
Release 5.3.0 has this in it.
