### ISSUE TITLE
Banner Ad is dropping frame rate of game

### ISSUE THREAD

**Issue by vibas** [googleads/googleads-mobile-unity#132]
I have integrated google admob package in my game. For interstitial Ad game is working fine. But while game play I am showing the Banner Ad which is disturbing game FPS. The game play was smooth before I integrated Admob. But now I am facing heavy lag in game play. Please help.

**Comment by rampara** [comment]
In the latest release of this plugin (v3.0.0), our sample application was updated to include a frame rate indicator. Are you seeing a drop in frame rate while displaying a banner application? If so, can you provide additional information on the type of device you're seeing this behavior on?

- Ram

**Comment by rampara** [comment]
duplicate of #236
