### ISSUE TITLE
Standard banner (320x50) shows as 960x150 banner

### ISSUE THREAD

**Issue by crezax** [googleads/googleads-mobile-unity#133]
Here is the code I use for showing my test banner:

    BannerView bannerView = new BannerView(
      BANNER_ID, AdSize.Banner, AdPosition.TopLeft);
    Debug.Log(Screen.width + " " + Screen.height);
    AdRequest request = new AdRequest.Builder()
      .AddTestDevice(DEVICE_ID)
      .Build();
    // Load the banner with the request.
    bannerView.LoadAd(request);

When I check logcat output, I get "1920 1080" as expected, but the banner takes up HUGE amount of screen space - see screenshot. Green 320x50 rectangle at bottom left for scale.

Does admob calculate screen size differently than Unity?
![screenshot_2015-11-13-15-16-05](https://cloud.githubusercontent.com/assets/3847084/11148193/8fea1a34-8a1b-11e5-875f-0a6aa0d2acc8.png)

**Comment by rampara** [comment]
Banner size units are in dp and not actual pixels. Does the green rectangle you're using for scale account for that?

- Ram

**Comment by rampara** [comment]
Closing issue due to non-response. If this issue persists, please re-open.

- Ram
