### ISSUE TITLE
Crash with Google Play Game Services Plugin

### ISSUE THREAD

**Issue by spaceduck0316** [googleads/googleads-mobile-unity#134]
Hi,
I've been using this admob plugin,
and recently I got to add Google Play Game Services (GPGS) to my project.
Each plugin works well alone,
but when I put them together, admob crashes with InterstitialAd().

I tried to solve this problem several days, but still have no idea.
Please help me to fix this issue.
Thanks.

**Comment by rampara** [comment]
Could you provide more details on the type of crash you are seeing? Logs are always helpful.

- Ram

**Comment by spaceduck0316** [comment]
Of course. Here is the link.

https://dl.dropboxusercontent.com/u/39962281/log_spaceduck_151118.txt

As I can't read the log, I hope you find something from it.
Thanks.

**Comment by rampara** [comment]
Is the google-play-services_lib folder still present within the Plugins/Android folder of your project?

- Ram

**Comment by spaceduck0316** [comment]
The folder is there, but is empty as GPGS remove theme. Should I remove the folder too? Or should I need it and all of it's contents any way?

**Comment by rampara** [comment]
You will need the content of this folder to be present.

- Ram

**Comment by spaceduck0316** [comment]
Ok, I will try to make them alive : )

**Comment by spaceduck0316** [comment]
I solved it.

Instead of importing google-play-services-lib (as it cause too many conflicts with GPGS)
I add play-services-ads to GPGS/Editor/BackgroundResolution.cs, to let GPGS imports the ads library.
And I needed to remove some of Plugin/Android/GoogleMobileAdsPlugin/AndroidManifest.xml (as it cause merging conflict)
"<activity android:name="com.google.android.gms.ads.AdActivity" ... />
 <activity android:name="com.google.android.gms.ads.purchase.InAppPurchaseActivity".../>-"

Ram, you gave me a hint.
Thanks.

**Comment by XblakninjaX** [comment]
@spaceduck0316 can you put the code ththst you added in so I can give it a try

**Comment by spaceduck0316** [comment]
@XblakninjaX It is like this:

svcSupport.DependOn("com.google.android.gms",
                                     "play-services-ads",
                                     PluginVersion.PlayServicesVersionConstraint); 

Sorry for late reply.

**Comment by creckd** [comment]
spaceduck0316 I LOVE YOU SO MUCH!!!!!!!!, i registered just so i can tell

**Comment by spaceduck0316** [comment]
@creckd Ha Ha Seems like you made it. Good!

**Comment by rampara** [comment]
The newest release of the plugin (v3.0.0) should solve compatibility issues with the Google Play Games Unity plugin. Please re-open the issue if you're still having integrating the newest release of this plugin into your Unity application.

- Ram
