### ISSUE TITLE
Conflict with latest googleads-mobile-unity and play-games-plugin-for-unity

### ISSUE THREAD

**Issue by MDReptile** [googleads/googleads-mobile-unity#135]
I attempted to import into a new project (using Unity 5.2.2) the googleads-mobile-unity package, which I setup one of the example scripts to allow me to show a banner ad at the bottom of the screen on android, and then attempted to import the play-games-plugin-for-unity package and to setup that for use in my project, and had to edit the manifest for the ads package to remove the section about IAP to allow the game to compile. This however did now show advertisements. I then followed the instructions available here:

https://www.bountysource.com/issues/28237470-google-play-game-service-and-admob-ads

Specifically the response from "claywilkinson" and the comment below from "tonghae", and this allowed the game to compile as well as show ads on device.

Using Google Play Games Plugin v0.9.27 and Google Mobile Ads Unity Plugin v2.3.1 produces this problem on Unity 5.2.2f1

**Comment by vipyugioh** [comment]
yes, I also have similar problems

**Comment by GamePandemic** [comment]
Managed to to fix this problem by copying sdk/extras/google/m2repository/com/google/android/gms/play-services-ads/8.3.0/play-services-ads-8.3.0.aar to Assets/Plugins/Android instead of google-play-services_lib as mentioned in admob plugin instructions.

Also you need to comment this line in Assets/Plugins/Android/GoogleMobileAdsPlugin/AndroidManifest.xml

**Comment by vipyugioh** [comment]
It's WORK, thank you so much GamePandemic !!!!!!!!!!!!!!!!

**Comment by rampara** [comment]
The newest release of the plugin (v3.0.0) should solve compatibility issues with the Google Play Games Unity plugin. Please re-open the issue if you're still having integrating the newest release of this plugin into your Unity application.

- Ram
