### ISSUE TITLE
Google Mobile Ad Initialisation Error : iOS

### ISSUE THREAD

**Issue by iqra-padela** [googleads/googleads-mobile-unity#1355]
* Unity version: 2019.3.15f1
  * Google Mobile Ads Unity plugin version: 5.1.0
  * Platform: iOS, Editor
  * Platform OS version: iOS 12.4.7
* Mediation ad networks used, and their versions: Iron Source (6.16.20), Facebook (5.9.0.0)

 I get the following error on the Unity Editor:
On initialising Google Mobile ads:
```
EntryPointNotFoundException: GADUInitialize
GoogleMobileAds.iOS.MobileAdsClient.Initialize (System.String appId) (at Assets/GoogleMobileAds/Platforms/iOS/MobileAdsClient.cs:47)
GoogleMobileAds.Api.MobileAds.Initialize (System.String appId) (at Assets/GoogleMobileAds/Api/MobileAds.cs:58)
```

On creating Interstitial ads:
```
EntryPointNotFoundException: GADUCreateInterstitial
GoogleMobileAds.iOS.InterstitialClient.CreateInterstitialAd (System.String adUnitId) (at Assets/GoogleMobileAds/Platforms/iOS/InterstitialClient.cs:84)
GoogleMobileAds.Api.InterstitialAd..ctor (System.String adUnitId) (at Assets/GoogleMobileAds/Api/InterstitialAd.cs:30)
```

Although this error does not occur on the physical iPhone device, the ads are not showing up, even after setting a test device ID.

Ads are working perfectly on Android.

**Comment by RodinDO** [comment]
- Unity version: 2019.3.7f1
- Google Mobile Ads Unity plugin version: 5.1.0
- Platform: iOS, Editor
- New empty project

Same error in Editor. On target device everything ok.
Perhaps there is an issue with Dummy call.

**Comment by stowy** [comment]
Refer https://github.com/googleads/googleads-mobile-unity/commit/7990ce8f4d64a5f60e58163ca653cca105311e2f

This is not yet released but you can copy the code over from `source/plugin/Assets/GoogleMobileAds/Platforms/iOS/GoogleMobileAdsClientFactory.cs`.

**Comment by rohit0786quytech** [comment]
-->Simply Replace with Google Mobile Ads Unity Plugin v5.2.0
