### ISSUE TITLE
Interstitial not working

### ISSUE THREAD

**Issue by vacu** [googleads/googleads-mobile-unity#136]
1. I used https://www.bountysource.com/issues/28237470-google-play-game-service-and-admob-ads and tried the second option by editing BackroundResolution.cs.
2. After that I edited the manifest and removed:
  * android:name="com.google.android.gms.ads.AdActivity"
  * android:name="com.google.android.gms.ads.purchase.InAppPurchaseActivity"
3. Removed the in-app purchase aidl jar from "libs"

At this point the normal ads work fine but the interstitial still doesn't work at all.

**Comment by rampara** [comment]
Are you receiving any error messages in logcat? Following the steps you mentioned above, I am able to still receive test interstitials.

- Ram

**Comment by vacu** [comment]
I am receiving the test messages as well but if i compile it and run it on my phone if goes in to the else statement as in:

if (interstitial.IsLoaded()) {
  interstitial.Show();
} else {}

**Comment by rampara** [comment]
Can you post the output under the "Ads" tag within logcat?

- Ram

**Comment by vacu** [comment]
Found the issue, the basic example doesn't show the interstitial because it doesn't wait for it to load.
Got it to work with the event handlers.

Thank you!
