### ISSUE TITLE
Google Play detected Vungle SDK as malicious.

### ISSUE THREAD

**Issue by jaceks454** [googleads/googleads-mobile-unity#1369]
* Unity version: 2018.4.23f1
  * Google Mobile Ads Unity plugin version: 5.1.0
  * Platform: Android
  * Platform OS version: any
  * Any specific devices issue occurs on: any
  * Mediation ad networks used, and their versions: Vungle 3.3.0, also used: Unity, AppLovin, Facebook, AdColony

We just received a notification from Google Play about all our games using AdMob that it is using  non-compliant version of Vungle SDK. 
We use Vungle SDK 3.3.0 and latest is 3.3.1 but plugin changelog doesn't include any information that this issue was fixed. Supported adapter version (6.5.3.0) remains the same as in SDK 3.3.0. 

Here is a part of the notice from the Google Play:

Hi Developers at XYZ,

After a recent review, we found that your app XYZ (com.XYZ) is not compliant with one or more of our Developer Program Policies. Please resolve this issue within 30 days of the issuance of this notification. See below for more information about violation and how to correct the issue.

Issue with your app
We found your app is using a non-compliant version of Vungle SDK which contains code to download or install applications from unknown sources outside of Google Play. If necessary, you can consult your SDK provider(s) for further information.

About the Malicious Behavior policy
We don't allow apps that steal data, secretly monitor or harm users, or are otherwise malicious. An app distributed via Google Play may not modify, replace, or update itself using any method other than Google Play's update mechanism. Likewise, an app may not download executable code (e.g. dex, JAR, .so files) from a source other than Google Play.

Rest of the message says that we should submit fixed apk.

**Comment by stowy** [comment]
Thanks @jaceks454 for letting us know. I would suggest for now that you remove the Vungle adapter / SDK from your project and contact Vungle to check if they're aware of this issue. 

We'll do the same and ensure that the adapters are up to date as soon as possible. It seems the latest Vungle SDK release is 6.7.0 from a couple of days ago, the current release supported by Google Mobile Ads mediation is 6.5.3.

**Comment by jaceks454** [comment]
W dniu śr., 24.06.2020 o 18:17 Samuel Stow <notifications@github.com>
napisał(a):

**Comment by jaceks454** [comment]
If if concerns someone: 
I contacted Vungle and they replied that their SDK ver 6.5 and above is compliant with Google Play policies.
And Google is flagging not only production builds but also builds from internal test and beta tracks - that was probably our case so we replaced some very old apks in those tracks with production builds.

**Comment by barryzcc** [comment]
> Thanks @jaceks454 for letting us know. I would suggest for now that you remove the Vungle adapter / SDK from your project and contact Vungle to check if they're aware of this issue.
> 
> We'll do the same and ensure that the adapters are up to date as soon as possible. It seems the latest Vungle SDK release is 6.7.0 from a couple of days ago, the current release supported by Google Mobile Ads mediation is 6.5.3.

Hi @stowy ,we try to delete the vungle sdk 6.4.11. But there are still empty vungle sdk folder that is generated after compiled when we delete the SDK. Could u tell us whether this approach is feasible?

**Comment by stowy** [comment]
hi @barryzcc I'd need to understand what your project looks like and what you deleted. You need to remove the mediation adapter folder for Vungle that you would have imported [in this step](https://developers.google.com/admob/unity/mediation/vungle#step_3_import_the_vungle_sdk_and_adapter).

I recommend asking on [our developer forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) for more detailed guidance on your personal project.
