### ISSUE TITLE
AdMob doesn't work anymore after resolving dependencies with ExternalDependencyManager

### ISSUE THREAD

**Issue by bfaf** [googleads/googleads-mobile-unity#1383]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.1f
  * Google Mobile Ads Unity plugin version: 5.2.0
  * Platform: Android
  * Platform OS version: Android 4.4 and Android 8.0
  * Any specific devices issue occurs on: LG G4 and Huawei P Smart

#### Steps to reproduce:

1. Installed AdMob unity Plugin. I have configured a scene to use it according documentation. App build and deployment works BUT when try to start Rewarded Video Ad in adb logcat I can see that some class is missing. After some research I found out that I have to install External Dependency Manager
2. I have installed External Dependency Manager for Unity 1.2.156
I made new Build and Run. The application crashed at startup. I looked again at logcat logs and see this:

```
07-13 10:18:47.082  2533  2533 E AndroidRuntime: Process: com.KrasimirChonov.LUDORelax, PID: 2533
07-13 10:18:47.082  2533  2533 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
07-13 10:18:47.082  2533  2533 E AndroidRuntime: 
07-13 10:18:47.082  2533  2533 E AndroidRuntime: ******************************************************************************
07-13 10:18:47.082  2533  2533 E AndroidRuntime: * Invalid application ID. Follow instructions here:                          *
07-13 10:18:47.082  2533  2533 E AndroidRuntime: * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
07-13 10:18:47.082  2533  2533 E AndroidRuntime: * to find your app ID.                                                       *
07-13 10:18:47.082  2533  2533 E AndroidRuntime: ******************************************************************************
```

I have checked my project so Android Manifest is in correct location:

*Assets/Plugins/Android/GoogleMobileAdsPlugin.androidlib/AndroidManifest.xml*

Inside there is correctly configured Application ID for test Ads.

**<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-3940256099942544/5224354917" />**

What could be the reason ApplicationID is not found by AdMob after installing External Dependency Manager?

Btw everything works just fine with iOS 13.5.1 with exactly this setup.

**Comment by bfaf** [comment]
[AndroidManifest.xml.txt](https://github.com/googleads/googleads-mobile-unity/files/4913476/AndroidManifest.xml.txt)

I just unpacked the .apk file. I am shocked what happened with AndroidManifest.xml file. It is attached. Is it supposed to look like this?

**Comment by bfaf** [comment]
I did the same with HelloWorld same inside your repo. I got the exactly same problem.

**Comment by stowy** [comment]
Hi,

Can you confirm that you correctly added your Application ID as per [this documentation](https://developers.google.com/admob/unity/quick-start#set_your_admob_app_id)?

For support debugging your apps, and to communicate personal information privately, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines - they will be able to help debug your issue with you efficiently.

**Comment by bfaf** [comment]
Thank you stowy.

It was my mistake after all!

I was using Ad Unit ID instead of App ID for AdMob settings screen.
