### ISSUE TITLE
java.lang.ClassNotFoundException: com.google.unity.ads.UnityAdLoaderListener

### ISSUE THREAD

**Issue by mores** [googleads/googleads-mobile-unity#1393]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2018.4.17f1
  * Google Mobile Ads Unity plugin version: 5.2.0
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: Android 8 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: Android 8

#### Steps to reproduce:
07-19 18:29:53.549 21236 21294 E Unity   : AndroidJavaException: java.lang.ClassNotFoundException: com.google.unity.ads.UnityAdLoaderListener
07-19 18:29:53.549 21236 21294 E Unity   : java.lang.ClassNotFoundException: com.google.unity.ads.UnityAdLoaderListener
07-19 18:29:53.549 21236 21294 E Unity   :      at java.lang.Class.classForName(Native Method)
07-19 18:29:53.549 21236 21294 E Unity   :      at java.lang.Class.forName(Class.java:453)
07-19 18:29:53.549 21236 21294 E Unity   :      at java.lang.Class.forName(Class.java:378)
07-19 18:29:53.549 21236 21294 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
07-19 18:29:53.549 21236 21294 E Unity   :      at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
07-19 18:29:53.549 21236 21294 E Unity   :      at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
07-19 18:29:53.549 21236 21294 E Unity   :      at android.os.MessageQueue.next(MessageQueue.java:394)
07-19 18:29:53.549 21236 21294 E Unity   :      at android.os.Looper.loop(Looper.java:142)
07-19 18:29:53.549 21236 21294 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)

#### Relevant Code:
Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml

I expect GoogleMobileAdsDependencies.xml to have something like:
<androidPackage spec="com.google.unity:android-library:3.16.0">
</androidPackage>

Where can the jar file be found that contains https://github.com/googleads/googleads-mobile-unity/tree/master/source/android-library ?

**Comment by mores** [comment]
Our .gitignore currently has 
*.jar
*.jar.meta
*.aar
*.aar.meta

So when one person 'Import the Mobile Ads Unity plugin' then checked into git - it was ignoring googlemobileads-unity.aar

Can the googlemobileads-unity.aar be put into maven somewhere so it can be downloaded at build time instead of having to be saved in source repository ?

**Comment by mores** [comment]
But now I am running into:

07-19 20:09:12.971 27937 27975 E Unity   : AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='configureUnifiedNativeAd' signature='()V' in class Ljava.lang.Object;
07-19 20:09:12.971 27937 27975 E Unity   : java.lang.NoSuchMethodError: no non-static method with name='configureUnifiedNativeAd' signature='()V' in class Ljava.lang.Object;
07-19 20:09:12.971 27937 27975 E Unity   :      at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:167)
07-19 20:09:12.971 27937 27975 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
07-19 20:09:12.971 27937 27975 E Unity   :      at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
07-19 20:09:12.971 27937 27975 E Unity   :      at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
07-19 20:09:12.971 27937 27975 E Unity   :      at android.os.MessageQueue.next(MessageQueue.java:394)
07-19 20:09:12.971 27937 27975 E Unity   :      at android.os.Looper.loop(Looper.java:142)
07-19 20:09:12.971 27937 27975 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
07-19 20:09:12.971 27937 27975 E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 

Is there another aar that is missing ?

**Comment by stowy** [comment]
Can you try removing and reimporting the plugin? It looks like you are using some combination of the native package and the public package.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!

**Comment by RomainBitard** [comment]
just my two cents after hours of trying to make it work, it's a missing dependency somewhere, (use force resolve and check any errors) or reimport the whole google admob unity sdk (it has a unity .aar in it, don't miss it)
