### ISSUE TITLE
Ad Impression problem

### ISSUE THREAD

**Issue by lijuicsoft** [googleads/googleads-mobile-unity#142]
I am using this plug in my game . Ad is loading properly , but no impression is showing in my account and no revenue is getting .

**Comment by paolo-lionhg** [comment]
just wait for it. statistics on the dashboard are not in real time. for how long to wait, that i'm not sure.

**Comment by rampara** [comment]
This issue tracker is just for reporting bugs, feature requests and discussion relating to the Google Mobile Ads Unity plugin. AdMob reporting support is available at https://support.google.com/admob/contact/performance_issues?rd=1.

- Ram
