### ISSUE TITLE
Banner position is not centered, but a little on the right.

### ISSUE THREAD

**Issue by gamedev2492** [googleads/googleads-mobile-unity#1425]
![Screenshot_20200817-222354_MonMon Forest](https://user-images.githubusercontent.com/44296763/90952875-a1d30a80-e484-11ea-9683-8e7fa5e3f643.jpg)
The banner is not centered when used: bannerView = new BannerView(adUnitId, AdSize.Banner, AdPosition.Bottom);

  * Unity version: 2019.3.13f1
  * Google Mobile Ads Unity plugin version: 5.1.0
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: Latest android
  * Any specific devices issue occurs on: Samsung Galaxy S10
  * Mediation ad networks used, and their versions: No

**Comment by gamedev2492** [comment]
Can someone tell me, is that an issue or normal behaviour???

**Comment by Str4tos** [comment]
Hello @gamedev2492. This is normal behavior because the banner has a side offset for screen cutouts and centered within the safe area of the screen.
