### ISSUE TITLE
AdMob ad don't show(unity)

### ISSUE THREAD

**Issue by f121231212** [googleads/googleads-mobile-unity#1431]
my unity version is 2020.1.3f1
When I am using unity, the console shows Dummy LoadAD, Dummy Show, etc. But when I test it on my phone it does show any AD. I set these two functions on two-button. bannerAD button does not show bannerAD. videoAD button will close my app
**There's my code**
`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GoogleMobileAds.Api;
using UnityEngine.UIElements;
using UnityEngine.UI;
using System;

public class admannger: MonoBehaviour
{
    public Text adstatus;
    string appID = "ca-app-pub-3518219641696723~8898303971";
    string bannerID = "ca-app-pub-3518219641696723/3016078445";
    string videoID = "ca-app-pub-3518219641696723/4137588427";
    string iniID = "ca-app-pub-3518219641696723/2421854529";
    InterstitialAd InterstitialAd;
    BannerView banner;
    RewardedAd video;
    // Start is called before the first frame update
    void Start()
    {
        MobileAds.Initialize(appID);
    }
    public void loadbannerAD()
    {
        this.banner = new BannerView(bannerID, AdSize.Banner, AdPosition.Bottom);
        // Called when an ad request has successfully loaded.
        this.banner.OnAdLoaded += this.HandleOnAdLoaded;
        // Called when an ad request failed to load.
        this.banner.OnAdFailedToLoad += this.HandleOnAdFailedToLoad;

    }
    public void showbannerAD()
    {
        AdRequest request = new AdRequest.Builder().Build();
        this.banner.LoadAd(request);
    }
    public void loadvideo()
    {
        this.video = new RewardedAd(videoID);
        AdRequest request = new AdRequest.Builder().Build();
        this.banner.LoadAd(request);
        // Called when an ad request has successfully loaded.
        this.video.OnAdLoaded += this.HandleOnAdLoaded;
        // Called when an ad request failed to load.
    }
    public void showvideo()
    {
        this.video.Show();
    }
    public void loadint()
    {
        this.InterstitialAd = new InterstitialAd(iniID);
        AdRequest request = new AdRequest.Builder().Build();
        this.InterstitialAd.LoadAd(request);
        // Called when an ad request has successfully loaded.
        this.InterstitialAd.OnAdLoaded += this.HandleOnAdLoaded;
        // Called when an ad request failed to load.
        this.InterstitialAd.OnAdFailedToLoad += this.HandleOnAdFailedToLoad;

    }
    public void showint()
    {
        this.InterstitialAd.Show();
    }

    public void HandleOnAdLoaded(object sender, EventArgs args)
    {
        adstatus.text = "adload";
    }

    public void HandleOnAdFailedToLoad(object sender, AdFailedToLoadEventArgs args)
    {
        adstatus.text = "fail to load";
    }

    public void HandleOnAdOpened(object sender, EventArgs args)
    {
        adstatus.text = "ad show";
    }
}
`

**Comment by willmeet** [comment]
That issue is clearly shown here how to solve admob failed to load ads http://www.technologymanias.com/2020/10/admob-ads-failed-to-load-ads-solve-this.html

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones.

Thanks for your contribution again!
