### ISSUE TITLE
iOS build fails with with 5.4.0, missing GADRewardedInterstitialAd

### ISSUE THREAD

**Issue by vloosoo** [googleads/googleads-mobile-unity#1437]
In plugin version 5.4.0 the new GADURewardedInterstitialAd.m refers to a GADRewardedInterstitialAd, but seems to be no such class in the plugin nor the current Google-Mobile-Ads-SDK 7.64 from CocoaPods ?

  * Unity version: 2019.2.21f1
  * Google Mobile Ads Unity plugin version: 5.4.0

**Comment by pelevinma** [comment]
same problem in iOS, 5.4.0

**Comment by varelaj** [comment]
Same here. And the close button on the interstitial ad in the editor, doesn’t work.

**Comment by ericleich** [comment]
Thanks for the report. The v5.4.0 build was removed as that header is indeed not yet in the iOS SDK.

**Comment by kg905812262** [comment]
Hi there, I wonder if this issue has been solved yet? I've used the latest AdMob Unity SDK (v5.4.0), but still encounter the same problem that iOS build is missing GADRewardedInterstitialAd.
