### ISSUE TITLE
Unity crashing sometimes on quitting app when showing Interstitial ad

### ISSUE THREAD

**Issue by alexey-unity** [googleads/googleads-mobile-unity#1440]
https://github.com/googleads/googleads-mobile-unity/blob/cb406a90471b9d0a2d5e0bc7178bbdd7645fd0e2/source/plugin/Assets/Plugins/iOS/GADUInterstitial.m#L99

Hello, alexey from unity here. 
You have heard probably about crashes when quitting app while showing Interstitial ad.
Now, i have proposed to several users to add 

```
if(_didResignActive) 
    return;

```
to [GADUInterstitial interstitialDidDismissScreen:] method

On one hand i agree with your assessment that we never mention that UnityIsPaused/UnityPause needs this kind of special treatement so we should strive to make it work. And i did exactly that, only to find out that 
```
self.didDismissCallback(self.interstitialClient);
```
later on will poke script, thus crashing anyway (but with a completely different callstack)

so, can we somehow get it resolved? I can promise to make pausing (or whatever other functions you might call) robust in that scenario, but, pretty please, add this _didResignActive check anyway

**Comment by stowy** [comment]
Hi Alexey, thanks for the comms. When you say the didDismissCallback pokes the script, can you perhaps provide a callstack? Would you like to create a pull request to resolve this issue that we can review?

**Comment by alexey-unity** [comment]
>>When you say the didDismissCallback pokes the script, can you perhaps provide a callstack?
```
    frame #8: 0x000000010b5e8480 UnityFramework`il2cpp::vm::ScopedThreadAttacher::ScopedThreadAttacher(this=<no summary available>) at ScopedThreadAttacher.cpp:10:28
    frame #9: 0x000000010b5e85d8 UnityFramework`il2cpp::vm::ScopedThreadAttacher::ScopedThreadAttacher(this=<no summary available>) at ScopedThreadAttacher.cpp:8:1
    frame #10: 0x0000000108789d78 UnityFramework`::ReversePInvokeWrapper_InterstitialClient_InterstitialDidDismissScreenCallback_mD44166C863F02E4DDB682BEBEDA3CA64439A21D4(___interstitialClient0=<no summary available>) at Assembly-CSharp.cpp:30855:35
    frame #11: 0x00000001089aa074 UnityFramework`-[GADUInterstitial interstitialDidDismissScreen:](self=<unavailable>, _cmd=<no summary available>, ad=<unavailable>) at GADUInterstitial.m:101:5
<...>
    frame #64: 0x000000018ca435bc UIKitCore`-[UIWindow setRootViewController:] + 284
    frame #65: 0x0000000108771ed8 UnityFramework`UnityCleanupTrampoline at UnityAppController.mm:165:34
    frame #66: 0x0000000108773aa0 UnityFramework`-[UnityAppController applicationWillTerminate:](self=<unavailable>, _cmd=<no summary available>, application=<unavailable>) at UnityAppController.mm:491:9
<...>
```

>>Would you like to create a pull request to resolve this issue that we can review?

**Comment by alexey-unity** [comment]
https://github.com/googleads/googleads-mobile-unity/pull/1441

**Comment by youdk** [comment]
if(_didResignActive) 
    return;

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones.

Thanks for your contribution again!
