### ISSUE TITLE
MobileAds.Initialize(Action<InitializationStatus> listener) has no implementation 

### ISSUE THREAD

**Issue by WouterVandenputte** [googleads/googleads-mobile-unity#1445]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.1.6ff
  * Google Mobile Ads Unity plugin version: 5.3.0 (latest version up til now)
  * Platform: Android
  * Platform OS version: Android 7.0 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: my personal Huawei device
  * Mediation ad networks used, and their versions: /

#### Steps to reproduce:

1. Make a GameObject and attach a script to it
```
    void Start()
    {
        Debug.Log("Ad controller started");
        MobileAds.Initialize(initStatus => {
            Debug.Log("initStatus: " + initStatus.ToString());
        });
        RequestBanner();
    }

    public void RequestBanner()
    {
        Debug.Log("Requesting a banner");
        .....
     }
```
2. Run the app on a physical device and inspect the log by calling `adb logcat`
3. Inspect the output log

> 09-22 20:43:25.565 17134 17151 I Unity   : Ad controller started
> 09-22 20:43:25.565 17134 17151 I Unity   : AdController:Start()
> 09-22 20:43:25.565 17134 17151 I Unity   :
> 09-22 20:43:25.565 17134 17151 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 09-22 20:43:25.565 17134 17151 I Unity   :
> 09-22 20:43:25.576  1779  2181 I qti_sensors_hal: [ACC]processReportInd: X: -0.235364 Y: 0.260008 Z: 9.858957  x_offset:0.088345 y_offset:0.516908 z_offset:0.983740
> 09-22 20:43:25.577  1779  2181 I qti_sensors_hal: [GYRO]processReportInd: X: 0.000653 Y: 0.001099 Z: 0.000168 status: 3 x_offset:-0.000272 y_offset:-0.000168 z_offset:0.000046
> 09-22 20:43:25.577  1779  2187 I qti_sensors_hal: processInd: GravityX: -0.144287 GravityY: 0.758552 GravityZ: 9.776205 acc: 3 SAM TS: 1178765454 HAL TS:3443858981146784 elapsedRealtimeNano:3443859009641689
> 09-22 20:43:25.577  1779  2189 I qti_sensors_hal: processInd: LinearAcceleration: X: 0.005342 Y: -0.002290 Z: 0.002364 acc: 3 SAM TS: 1178765454 HAL TS:3443858981146784 elapsedRealtimeNano:3443859009661220
> 09-22 20:43:25.577  1779  2191 I qti_sensors_hal: processInd: ROTV [0]: 0.010486 [1]: -0.037978 [2]: -0.995913 [3]: 0.081269 [4]: 0.174533 acc: 3 SAM TS: 1178765454 HAL TS: 3443858981146784 elapsedRealtimeNano:3443859009675960
> 09-22 20:43:25.588  1779  1790 W art     : Suspending all threads took: 8.477ms
> 09-22 20:43:25.596 17134 17151 E Unity   : AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.initialization.OnInitializationCompleteListener
> 09-22 20:43:25.596 17134 17151 E Unity   : java.lang.ClassNotFoundException: com.google.android.gms.ads.initialization.OnInitializationCompleteListener
> 09-22 20:43:25.596 17134 17151 E Unity   :      at java.lang.Class.classForName(Native Method)
> 09-22 20:43:25.596 17134 17151 E Unity   :      at java.lang.Class.forName(Class.java:400)
> 09-22 20:43:25.596 17134 17151 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
> 09-22 20:43:25.596 17134 17151 E Unity   :      at com.unity3d.player.UnityPlayer.access$300(Unknown Source)
> 09-22 20:43:25.596 17134 17151 E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source)
> 09-22 20:43:25.596 17134 17151 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:101)
> 09-22 20:43:25.596 17134 17151 E Unity   :      at android.os.Looper.loop(Looper.java:156)
> 09-22 20:43:25.596 17134 17151 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
> 09-22 20:43:25.596 17134 17151 E Unity   : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.initialization.OnInitializationCompleteListener" on path: DexPathList[[zip file "/data/app/com.somename.someapp-2/base.apk", zip file "/data/app/com.somename.someapp-2/split_config.arm64_v8a.apk"],nativeLibraryDirectories=[/data/app/c

The `Debug.Log("Requesting a banner")` is not called and the method of initializing AdMob with the appId is depcrated

**Comment by stowy** [comment]
The answer to your problem here is this:

```
09-22 20:43:25.596 17134 17151 E Unity : AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.initialization.OnInitializationCompleteListener
09-22 20:43:25.596 17134 17151 E Unity : java.lang.ClassNotFoundException: com.google.android.gms.ads.initialization.OnInitializationCompleteListener
```

Have you resolved the Android dependencies using [External dependency resolver](https://github.com/googlesamples/unity-jar-resolver)?   It looks like the Android SDK is not included in your build. Check the contents of your `Assets/Plugins/Android` folder - there should be a bunch of `.aar` files there including `play-services-ads-...`.

**Comment by ksnerv** [comment]
> The answer to your problem here is this:
> 
> ```
> 09-22 20:43:25.596 17134 17151 E Unity : AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.initialization.OnInitializationCompleteListener
> 09-22 20:43:25.596 17134 17151 E Unity : java.lang.ClassNotFoundException: com.google.android.gms.ads.initialization.OnInitializationCompleteListener
> ```
> 
> Have you resolved the Android dependencies using [External dependency resolver](https://github.com/googlesamples/unity-jar-resolver)? It looks like the Android SDK is not included in your build. Check the contents of your `Assets/Plugins/Android` folder - there should be a bunch of `.aar` files there including `play-services-ads-...`.

thanks bor u saved my life. i just fixed mine
