### ISSUE TITLE
"AndroidManifest.xml is missing." error with 5.3.0 unitypackage, but not with source.

### ISSUE THREAD

**Issue by PaulNaylor** [googleads/googleads-mobile-unity#1449]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2018.4.23f1
  * Google Mobile Ads Unity plugin version: 5.3.0 (latest)
  * Platform: Editor/Android 
  * Platform OS version: Not applicable
  * Any specific devices issue occurs on: No
  * Mediation ad networks used, and their versions: None

### [REQUIRED] Step 2: Describe the problem
When building the Android apk in the Unity Editor I get the error:
"AndroidManifest.xml is missing." for [GoogleMobileAds] 

the path to the manifest in the source is:
D:\Work\p4lsg\zenKoi\ZenKoi\Assets\Plugins\Android\GoogleMobileAdsPlugin.androidlib\...
but in the bundle is:
D:\Work\p4lsg\zenKoi\ZenKoi\Assets\Plugins\Android\GoogleMobileAdsPlugin\...

Also the .meta file associated with the GoogleMobileAdsPlugin.androidlib folder is incorrectly named in the source as:
GoogleMobileAdsPlugin.meta when it should be GoogleMobileAdsPlugin.androidlib.meta

and the ManifestProcessor.cs is only looking in the source path: "Plugins/Android/GoogleMobileAdsPlugin.androidlib/AndroidManifest.xml"

I'm assuming GoogleMobileAdsPlugin.androidlib in which case correcting the meta file for that folder and rebuilding the unity bundle should fix the problem. 

#### Steps to reproduce:

What happened? How can we make the problem occur?
Install the plugin into the Unity Editor (v2018.4.23) from the 5.3.0 unity package and try to build an APK.

Any project will do. It's not project specific.

#### Relevant Code:

See Description of the problem above: Relevant files are the parent folder of the AndroidManifest.xml, and the ManifestProcessor.cs, and unitypackage itself.

**Comment by adbourdages** [comment]
Ran into the same problem when I updated. The file was absolutely visible in Unity. After adding a couple of lines to the manifest for specifying the appId (<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-..."/>) then saving, the error went away. Unity probably detected a file change, refreshed its asset dictionary and whatever was causing it went away. Hopefully, this can help someone else.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones.

Thanks for your contribution again!
