### ISSUE TITLE
linker command failed with exit code 1, ld: framework not found GoogleMobileAds

### ISSUE THREAD

**Issue by Armend** [googleads/googleads-mobile-unity#145]
Hello everyone,

I've an issue with the GoogleMobileAds.framework. I have added it like it is described in the documentation (https://github.com/googleads/googleads-mobile-unity/tree/master/unity)
but this error shows up. 
" ld: framework not found GoogleMobileAds
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I hope someone knows how to fix this. :/

I am using Unity 5.3.0f4 Personal and 
XCode 7.2 and
Cocoapods: 0.39.0.

Thank you very much.

**Comment by rampara** [comment]
If you're using XCode 7 and above, you have to ensure either copy frameworks into your project folder or make sure framework search paths are correctly set.

- Ram

**Comment by rampara** [comment]
Closing issue due to non-response. If this issue persists, please re-open.
