### ISSUE TITLE
GoogleMobileAds removes all links to *.cs scripts in csproj

### ISSUE THREAD

**Issue by Den4ik25** [googleads/googleads-mobile-unity#1463]
In the Unity project 2019.4.1f1 decided to add GoogleMobileAds-v5.3.0.unitypackage.
After importing, when I try to open any of the *.cs scripts in VS2017 that were created before installing the plugin, I observe that all *.cs scripts disappear from the project.
Manual addition of all *.cs scripts to csproj does not help. When you reopen the project in VS2017, all the script links disappear again.

**Comment by NVentimiglia** [comment]
Closing stale issue. Please update and if still an issue please reopen.
