### ISSUE TITLE
Admob Unity Mediation Error in callback sequence

### ISSUE THREAD

**Issue by SamWLH** [googleads/googleads-mobile-unity#1464]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: __unity 2018.4.1f1___
  * Google Mobile Ads Unity plugin version: __5.3.0___
  * Platform: __Android___ (iOS, Android, Unity Editor)
  * Platform OS version: __XIaoMI(Android8.1) & HUAWEI(Android9)___ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: __3.4.2.0___

### [REQUIRED] Step 2: Describe the problem
I use Admob Unity Mediation
On my two Android devices, whenever I open the app and watch Unity RewardAds for the first time, I get no reward after the playback is complete, but I can successfully get rewards when I watch Unity RewardAds for the second time.
I can see through Log but the problem is in RewardBasedVideoAd.cs:

         public event EventHandler<EventArgs> OnAdClosed;
         public event EventHandler<Reward> OnAdRewarded;

Unity rewardAds calls OnAdClosed after the first play, and then calls OnAdRewarded
Starting from the second time, OnAdRewarded is called first and then OnAdClosed is called

I connected to admob ads and Facebook can call them in the normal order. I am not sure if the call order of these two methods is random (if the original order is random, then my question is redundant)
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones.

Thanks for your contribution again!
