### ISSUE TITLE
Unity 5.3 Compile Error.

### ISSUE THREAD

**Issue by edgarscr** [googleads/googleads-mobile-unity#147]
Hey dude i have a problem with this plugin i added on new unity version and look.  
Admob 2.3.1

Who can help me.

![image](https://cloud.githubusercontent.com/assets/16306453/11996125/535f1342-aa2f-11e5-9673-d38c77e3741f.png)

![image](https://cloud.githubusercontent.com/assets/16306453/11996130/65c887f2-aa2f-11e5-9aed-c6c67e6e761a.png)

**Comment by rampara** [comment]
I am able to build our sample project using the latest release of Unity. Have you included the google play services lib project into your Unity project?

- Ram

**Comment by edgarscr** [comment]
i have Google Play Services and Admob only. if u can help me that is awesome. and idk what u are saying with RAM i have 8 gb Ram

**Comment by rampara** [comment]
Have you followed the Android Setup instructions [here](https://github.com/googleads/googleads-mobile-unity/blob/master/unity/README.md)?

- Ram
