### ISSUE TITLE
A lot of ANRs on Play Console relate to Admob and Android 8.1

### ISSUE THREAD

**Issue by hlongvu** [googleads/googleads-mobile-unity#1475]
* Unity version: 2019.4.7f1
  * Google Mobile Ads Unity plugin version: 5.3.0
  * Platform: Android
  * Platform OS version: Android 8.1
  * Any specific devices issue occurs on: Huawei HUAWEI Y5 lite
  * Mediation ad networks used, and their versions: IronSource, version 7.0.1.1

We are seeing lots of ANRs from Play Console relate to Admob, with more than 50% happens on Android 8.1 and mostly on "Huawei HUAWEI Y5 lite" device.
Please take a look.

> Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 56. Wait queue head age: 8512.0ms.)
> 
> #00 pc 0000000000018cc4 /system/lib/libc.so (syscall+28)
> #00 pc 00000000000b71cd /system/lib/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+80)
> #00 pc 00000000003e0911 /system/lib/libart.so (art::GoToRunnable(art::Thread*)+300)
> #00 pc 00000000003e07b5 /system/lib/libart.so (art::JniMethodEnd(unsigned int, art::Thread*)+8)
> #00 pc 0000000000773b31 /system/framework/arm/boot-framework.oat (Java_android_os_BinderProxy_transactNative__ILandroid_os_Parcel_2Landroid_os_Parcel_2I+144)
> at android.os.BinderProxy.transactNative (Native method)
> at android.os.BinderProxy.transact (Binder.java:778)
> at android.app.INotificationManager$Stub$Proxy.createNotificationChannels (INotificationManager.java:1616)
> at android.app.NotificationManager.createNotificationChannels (NotificationManager.java:464)
> at android.app.NotificationManager.createNotificationChannel (NotificationManager.java:452)
> at com.google.android.gms.ads.nonagon.a.a (com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601003.333818716.333818716:20)
> at com.google.android.gms.ads.nonagon.a.a (com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601003.333818716.333818716:36)
> at com.google.android.gms.ads.nonagon.shim.v.<init> (com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601003.333818716.333818716:3)
> at com.google.android.gms.ads.ChimeraAdManagerCreatorImpl.newAdManagerByType (com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601003.333818716.333818716:11)
> at com.google.android.gms.ads.internal.client.aw.a (com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601003.333818716.333818716:7)
> at gg.onTransact (com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601003.333818716.333818716:4)
> at android.os.Binder.transact (Binder.java:627)
> at cok.a (com.google.android.gms@203915063@20.39.15 (110306-335085812):2)
> at com.google.android.gms.ads.internal.client.l.newAdManagerByType (com.google.android.gms@203915063@20.39.15 (110306-335085812))
> at com.google.android.gms.ads.AdManagerCreatorImpl.newAdManagerByType (com.google.android.gms@203915063@20.39.15 (110306-335085812):6)
> at com.google.android.gms.ads.internal.client.m.a (com.google.android.gms@203915063@20.39.15 (110306-335085812):7)
> at col.onTransact (com.google.android.gms@203915063@20.39.15 (110306-335085812):11)
> at android.os.Binder.transact (Binder.java:627)
> at com.google.android.gms.internal.ads.zzgu.transactAndReadException
> at com.google.android.gms.internal.ads.zzxg.zza
> at com.google.android.gms.internal.ads.zzve.zza
> at com.google.android.gms.internal.ads.zzvw.zzpq
> at com.google.android.gms.internal.ads.zzwn.zzqe
> at com.google.android.gms.internal.ads.zzwn.zzd
> at com.google.android.gms.internal.ads.zzyy.zza
> at com.google.android.gms.ads.BaseAdView.loadAd
> at com.google.android.gms.ads.AdView.loadAd
> at com.google.unity.ads.Banner$6.run (Banner.java:305)
> at android.os.Handler.handleCallback (Handler.java:795)
> at android.os.Handler.dispatchMessage (Handler.java:99)
> at android.os.Looper.loop (Looper.java:166)
> at android.app.ActivityThread.main (ActivityThread.java:6861)
> at java.lang.reflect.Method.invoke (Native method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:450)
> at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)
> 
>

**Comment by hlongvu** [comment]
Link to the admob-sdk google group issue: [https://groups.google.com/g/google-admob-ads-sdk/c/441WMLNnM2o/m/7VhdVwsuAQAJ](https://groups.google.com/g/google-admob-ads-sdk/c/441WMLNnM2o/m/7VhdVwsuAQAJ)

**Comment by mylastgg** [comment]
Hello! 
I am having the same issue, after a recent updated we got a spike in ANR almost identical to the one reported above, affecting mainly Android 8.1. I also wrote in the google group but I haven't been able to fix this yet. Is there any updated or suggestion from google?

**Comment by romannotroman** [comment]
Same issue. Lots of ANRs, exact the same stack trace.
Admob ignores issue for more than a year

**Comment by chenshizhan** [comment]
Why is the Admob team not paying attention to this issue, which has been going on for so long
