### ISSUE TITLE
[Native Ads] Click ads shows warning in logcat

### ISSUE THREAD

**Issue by umiringo** [googleads/googleads-mobile-unity#1476]
I tried a natived ads in my game.
When it shows up, I click the ads, it will open a url.
It seems to be right, but when I check the logcat, there are some exception when I click the ads.
I don't know whether it is a issue.
10-31 14:46:45.588 14204 14204 W Bundle  : Key x expected Float but value was a java.lang.String.  The default value 0.0 was returned.
10-31 14:46:45.589 14204 14204 W Bundle  : Attempt to cast generated internal exception:
10-31 14:46:45.589 14204 14204 W Bundle  : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Float
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.BaseBundle.getFloat(BaseBundle.java:1109)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.Bundle.getFloat(Bundle.java:841)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.BaseBundle.getFloat(BaseBundle.java:1091)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.Bundle.getFloat(Bundle.java:828)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.ads.nonagon.ad.nativead.q.b(:com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601057.333818716.333818716:4)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.ads.nonagon.ad.nativead.ah.c(:com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601057.333818716.333818716:2)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.ads.internal.formats.client.ba.a(:com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601057.333818716.333818716:45)
10-31 14:46:45.589 14204 14204 W Bundle  :      at fy.onTransact(:com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601057.333818716.333818716:4)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.Binder.transact(Binder.java:914)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.internal.ads.zzgc.zza(com.google.android.gms:play-services-ads-base@@19.0.0:21)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.internal.ads.zzaet.reportTouchEvent(com.google.android.gms:play-services-ads-lite@@19.0.0:92)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.internal.ads.zzaes.reportTouchEvent(com.google.android.gms:play-services-ads-lite@@19.0.0:78)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.unity.ads.NativeAdvancedUnifiedNativeAd$2.run(NativeAdvancedUnifiedNativeAd.java:131)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.Handler.handleCallback(Handler.java:883)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.Handler.dispatchMessage(Handler.java:100)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.Looper.loop(Looper.java:214)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.app.ActivityThread.main(ActivityThread.java:7356)
10-31 14:46:45.589 14204 14204 W Bundle  :      at java.lang.reflect.Method.invoke(Native Method)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
10-31 14:46:45.589 14204 14204 W Bundle  : Key y expected Float but value was a java.lang.String.  The default value 0.0 was returned.
10-31 14:46:45.589 14204 14204 W Bundle  : Attempt to cast generated internal exception:
10-31 14:46:45.589 14204 14204 W Bundle  : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Float
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.BaseBundle.getFloat(BaseBundle.java:1109)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.Bundle.getFloat(Bundle.java:841)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.BaseBundle.getFloat(BaseBundle.java:1091)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.Bundle.getFloat(Bundle.java:828)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.ads.nonagon.ad.nativead.q.b(:com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601057.333818716.333818716:4)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.ads.nonagon.ad.nativead.ah.c(:com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601057.333818716.333818716:2)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.ads.internal.formats.client.ba.a(:com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601057.333818716.333818716:45)
10-31 14:46:45.589 14204 14204 W Bundle  :      at fy.onTransact(:com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601057.333818716.333818716:4)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.Binder.transact(Binder.java:914)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.internal.ads.zzgc.zza(com.google.android.gms:play-services-ads-base@@19.0.0:21)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.internal.ads.zzaet.reportTouchEvent(com.google.android.gms:play-services-ads-lite@@19.0.0:92)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.internal.ads.zzaes.reportTouchEvent(com.google.android.gms:play-services-ads-lite@@19.0.0:78)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.unity.ads.NativeAdvancedUnifiedNativeAd$2.run(NativeAdvancedUnifiedNativeAd.java:131)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.Handler.handleCallback(Handler.java:883)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.Handler.dispatchMessage(Handler.java:100)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.Looper.loop(Looper.java:214)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.app.ActivityThread.main(ActivityThread.java:7356)
10-31 14:46:45.589 14204 14204 W Bundle  :      at java.lang.reflect.Method.invoke(Native Method)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
10-31 14:46:45.589 14204 14204 W Bundle  : Key duration_ms expected Integer but value was a java.lang.String.  The default value 0 was returned.
10-31 14:46:45.589 14204 14204 W Bundle  : Attempt to cast generated internal exception:
10-31 14:46:45.589 14204 14204 W Bundle  : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.BaseBundle.getInt(BaseBundle.java:1041)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.BaseBundle.getInt(BaseBundle.java:1023)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.ads.nonagon.ad.nativead.q.b(:com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601057.333818716.333818716:4)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.ads.nonagon.ad.nativead.ah.c(:com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601057.333818716.333818716:2)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.ads.internal.formats.client.ba.a(:com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601057.333818716.333818716:45)
10-31 14:46:45.589 14204 14204 W Bundle  :      at fy.onTransact(:com.google.android.gms.policy_ads_fdr_dynamite@203404601@203404601057.333818716.333818716:4)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.Binder.transact(Binder.java:914)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.internal.ads.zzgc.zza(com.google.android.gms:play-services-ads-base@@19.0.0:21)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.internal.ads.zzaet.reportTouchEvent(com.google.android.gms:play-services-ads-lite@@19.0.0:92)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.android.gms.internal.ads.zzaes.reportTouchEvent(com.google.android.gms:play-services-ads-lite@@19.0.0:78)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.google.unity.ads.NativeAdvancedUnifiedNativeAd$2.run(NativeAdvancedUnifiedNativeAd.java:131)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.Handler.handleCallback(Handler.java:883)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.Handler.dispatchMessage(Handler.java:100)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.os.Looper.loop(Looper.java:214)
10-31 14:46:45.589 14204 14204 W Bundle  :      at android.app.ActivityThread.main(ActivityThread.java:7356)
10-31 14:46:45.589 14204 14204 W Bundle  :      at java.lang.reflect.Method.invoke(Native Method)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-31 14:46:45.589 14204 14204 W Bundle  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by mdobele** [comment]
Anyone have an update on the above issue?  I also see the same as well as logs like this immediately after:
`Received log message: <Google:HTML> Invalid click coordinates detected. Click coordinate (70.42814200000001, -20.865800000000007) should be positive and within the ad view boundary.`

**Comment by NVentimiglia** [comment]
Fixed in the next release.

**Comment by nmtoan91** [comment]
@NVentimiglia 
I got this error when I click anywhere 

2024/11/10 15:22:32.358 23325 23325 Info Ads Received log message: <Google:HTML> Invalid click coordinates detected. Click coordinate (204.394792, 282.61192) should be positive and within the ad view boundary.
