### ISSUE TITLE
Why does project build normally even if I don't add google-play-services_lib folder to the project?

### ISSUE THREAD

**Issue by ghost** [googleads/googleads-mobile-unity#148]
I just noticed that the folder google-play-services_lib is empty, shouldn't build fail because of this? Interstitials are still working. I'm using unity 5.3. Does anyone have any ideas?

**Comment by rampara** [comment]
Are you including Google Play Services client library AARs or JARs in your Unity project?

- Ram

**Comment by rampara** [comment]
Closing issue due to non-response. If this issue persists, please re-open.
