### ISSUE TITLE
Rewarded Ad events and threading

### ISSUE THREAD

**Issue by kevinfoley** [googleads/googleads-mobile-unity#1480]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: Unity 2019.4.12f1
  * Google Mobile Ads Unity plugin version: v5.3.0
  * Platform: Android
  * Platform OS version: Android 8
  * Any specific devices issue occurs on: Samsung Galaxy S7 Edge
  * Mediation ad networks used, and their versions: AdColony 2.1.0, Vungle 3.5.0, Chartboost 3.1.0, Unity 2.4.7

### [REQUIRED] Step 2: Describe the problem

`RewardedAd` has an `OnAdFailedToShow` event that apparently is not handled on the main thread, causing errors if we try to access Unity features from a handler for this event. This is not noted in the [documentation](https://developers.google.com/admob/unity/rewarded-ads).

#### Steps to reproduce:

1. Create an application with **_incorrectly configured ad settings so that Rewarded ads can not be played correctly_**
2. Create a new MonoBehaviour script. 
3. In the new script, include code to initialize and display a rewarded ad. Include an event handler for `OnAdFailedToShow` which uses Unity features only accessible from main thread (see section "Relevant code")
4. Add the script from Step 3 to a GameObject in your scene.
5. In the Unity Editor, ensure "development build" is selected in the project's Build Settings menu
6. Build and Run on Android
7. Using adb logcat, monitor the console logs from the application. Note that when the ad fails to show and `HandleRewardedAdFailedToShow()` is called, errors appear in the console log about trying to access main-thread features while not on the main thread.

#### Relevant Code:

```
public string adUnitId = "ca-app-pub-3940256099942544/5224354917"; //android test ad id
private RewardedAd rewardedAd;

private void Start() {
    StartCoroutine(LoadAndShowAds());
}

private IEnumerator LoadAndShowAds() {
    LoadAds();
    yield return new WaitUntil(() => rewardedAd.IsLoaded());
    ShowAd();
}

public void LoadAds() {
    this.rewardedAd = new RewardedAd(adUnitId);
    this.rewardedAd.OnAdFailedToShow += HandleRewardedAdFailedToShow;
    // Create an empty ad request.
    AdRequest request = new AdRequest.Builder().Build();
    // Load the rewarded ad with the request.
    this.rewardedAd.LoadAd(request);
}

public void ShowAd() {
    if (this.rewardedAd.IsLoaded()) {
        this.rewardedAd.Show();
    }
}

public void HandleRewardedAdFailedToShow(object sender, AdErrorEventArgs args)
{
    Debug.Log("Ad failed to show");
    //do some things that must be done on main thread
    UnityEngine.Debug.Log(gameObject.name);
    transform.position += new Vector3(0, 1, 0);
}

```

#### Expected behavior
Either the `OnAdFailedToShow` event should stick to the main thread, or the documentation should clearly indicate that this event is not on the main thread.

**Comment by MonierHossam** [comment]
A workaround solution for this issue until  "they stick to the main thread or indicate it in the documentation as you hope", is to a set a flag when the OnAdFailedToShow function is called and then in the update function in the main thread you check if the flag is set if it is you can then do what you want in the main thread normally, I hope this helpful.

**Comment by stowy** [comment]
Hi @kevinfoley you are correct we should add this to the documentation.
The recommended approach is [shown in our HelloWorld sample](https://github.com/googleads/googleads-mobile-unity/blob/master/samples/HelloWorld/Assets/Scripts/GoogleAdMobController.cs#L57).

The reason for this is the Android callbacks do not occur in Unity's update loop and hence need to be passed back to the update loop, we call them off main thread on the android side to avoid some issues that were seen with ANRs.

You could also try the [Ad Placements beta](https://developers.google.com/admob/unity/ad-placements) as this does this automatically for you.
