### ISSUE TITLE
Facebook mediation is causing Firebase remote config to crash

### ISSUE THREAD

**Issue by xtrecoolx** [googleads/googleads-mobile-unity#1484]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.13f1
  * Google Mobile Ads Unity plugin version: 5.3.0
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: Facebook Mediation 3.0.0

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

1) Please install the latest Firebase SDKs (6.16.1) via EDMU. Please include the Firebase remote config, analytics, messaging packages. In your code, don't forget to call the firebase remote config to retrieve some values.
2) Please install the latest Admob SDK and then install the Facebook Admob mediation adapter. Call admob to show some banners.
3) Simply run your code on a real Android device and watch the logcat. You will see that the remote config will crash. 

![firebase](https://user-images.githubusercontent.com/27774921/98345603-f159b900-2025-11eb-9177-1503518c37e9.png)

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by p0w1nd** [comment]
I'm encountering a similar problem: https://github.com/googleads/googleads-mobile-unity/issues/1478

**Comment by xtrecoolx** [comment]
We can't use Facebook mediation. Please fix this.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!
