### ISSUE TITLE
Google Mobile Ads SDK was initialized incorrectly

### ISSUE THREAD

**Issue by koljanich** [googleads/googleads-mobile-unity#1497]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.1.11
  * Google Mobile Ads Unity plugin version: 5.3.0
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: 9 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: All
  * Mediation ad networks used, and their versions: no

### [REQUIRED] Step 2: Describe the problem
App crash, in log Error: "...Google Mobile Ads SDK was initialized incorrectly..." "GoogleMobileAdsPlugin.androidlib" already in project, but not resolve problem. Error stay. In other project with same unity 2020.1.11 and GoogleMobileAds-v5.3.0 all worked. App ID check 10+ times. I don't know what to do anymore ...
#### Steps to reproduce:
Manifest from Google play games:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- This file was automatically generated by the Google Play Games plugin for Unity
     Do not edit. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.google.example.games.mainlibproj"
    android:versionCode="1"
    android:versionName="1.0" >
    <application>
        <!-- The space in these forces it to be interpreted as a string vs. int -->
        <meta-data android:name="com.google.android.gms.games.APP_ID"
            android:value="\u003329506460760" />
        <!-- Keep track of which plugin is being used -->
        <meta-data android:name="com.google.android.gms.games.unityVersion"
            android:value="\u0030.10.11" />
        <activity android:name="com.google.games.bridge.NativeBridgeActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
    </application>
</manifest> 
```

Manifest from Admob: 
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.google.unity.ads" android:versionName="1.0" android:versionCode="1">
  <application>
    <uses-library android:required="false" android:name="org.apache.http.legacy" />
    <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-MY_APP_ID_CHECK_IT_10+Times" />
  </application>
</manifest>
```

**Comment by araimple** [comment]
same error occured in my project.
I have resolved this.
https://github.com/googleads/googleads-mobile-unity/pull/1494

**Comment by koljanich** [comment]
"Plugins/Android/GoogleMobileAdsPlugin.androidlib/AndroidManifest.xml" already in ManifestProcessor

**Comment by araimple** [comment]
https://github.com/googleads/googleads-mobile-unity/pull/1494#issuecomment-729400722

**Comment by koljanich** [comment]
I read. For me not work. But I copy Admob, GPG and Resolver from other my work project and all work OK.

**Comment by yCatDev** [comment]
Same here
