### ISSUE TITLE
Unity 5. Compile error.

### ISSUE THREAD

**Issue by edgarscr** [googleads/googleads-mobile-unity#150]
Please can u upload a fixed version for unity 5? i have only Admob and Playservices and i got error but this plugin. 

![](https://cloud.githubusercontent.com/assets/16306453/11978154/72224652-a95b-11e5-8ccf-8de6e5012bb3.png)

![](https://cloud.githubusercontent.com/assets/16306453/11978163/7b7bdce0-a95b-11e5-856f-e142d75aa97a.png)

![](https://cloud.githubusercontent.com/assets/16306453/11978165/7e4f3dd6-a95b-11e5-964d-30df6075b7f7.png)

**Comment by edgarscr** [comment]
Uppp

**Comment by edgarscr** [comment]
uppp

**Comment by ctykaya** [comment]
Any solutions? Same problem!!

**Comment by ericleich** [comment]
We have been working with the play games team on making the plugins work better together, particularly with importing and not having duplicate versions of Google Play services in the app. We will be releasing an update soon (hopefully this week) that will make integrating the plugin much more seamlesss. Stay tuned!

**Comment by edgarscr** [comment]
OK i hope this update fix my problem. thanks u

**Comment by TreSSorGS** [comment]
I have the same problem and .27 version don't give me the ads . Could you tell me when the new version will be ready?

**Comment by rampara** [comment]
The newest release of the plugin (v3.0.0) should solve compatibility issues with the Google Play Games Unity plugin. Please re-open the issue if you're still having integrating the newest release of this plugin into your Unity application.

- Ram
