### ISSUE TITLE
Sounds are gone just after rewarded ad!

### ISSUE THREAD

**Issue by vladici** [googleads/googleads-mobile-unity#1516]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.15f1
  * Google Mobile Ads Unity plugin version: v5.4.0
  * Platform: iOS
  * Platform OS version: iOS 14.2
  * Any specific devices issue occurs on: XS Max
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem

Just after rewarded video all sounds are gone (muted) forever! 
For now in code we do nothing about sounds. 
Game background music plays in parallel with rewarded video sounds.

**Comment by rozatlabs** [comment]
I’m having the exact same issue, users are telling me sound disappears after an ad and they have to restart the game. Also iOS 14.2, but one user was iPhone 11

**Comment by p0w1nd** [comment]
This is just a guess, but maybe it's worth trying:

AFAIK AdMob by default does not "pause" Unity when opening Ad, that's why if you don't explicitly pause game audio before showing ad then you will hear both game sound and ad sound at the same time - and for some reason, this may mess up the game audio when back from ad.

AdMob has this method to explicitly pause/resume Unity when opening/going back from ad:
`MobileAds.SetiOSAppPauseOnBackground(true);`

In the Start method of my AdManager class, I do something like this for iOS:

```
void Start()
{
    MobileAds.Initialize(initStatus => { });

    #if UNITY_IOS
        MobileAds.SetiOSAppPauseOnBackground(true);
    #endif

    GoogleMobileAds.Api.Mediation.AppLovin.AppLovin.Initialize();

    RequestRewardedAd();
    RequestInterstitialAd();
}
```

**Comment by KingKlauz** [comment]
I am facing the same exact issue. I am testing on iPhone 12 running iOS 14.4. After closing a rewarded ad, all audios are muted. I already have the MobileAds.SetiOSAppPauseOnBackground(true) code in my script. Using AdMob v5.4.0

**Comment by ttienqb** [comment]
i have same error

**Comment by yusuke-mizuno-unity** [comment]
Please Disable "Mute orher audio sources"

**Comment by Str4tos** [comment]
Hello.
Disabling "Mute other audio sources" in Unity Player settings helps with the problem.
Why do Unity Player settings mute all Unity Audio Sources after ad close?

**Comment by jungletree** [comment]
For Admob v5.0,  it seems this bug will not happen for Unity5.6, Unity2017.4.40. But will happen for unity 2018.4.22

**Comment by Object2XD** [comment]
I don't know the exact reason.

The same setting is reflected in the SDK, and when the View containing the SDK's AudioMedia is opened, Unity's AudioSource may be disabled.
(I think this is the reason why this issue does not occur with interstitial ads that do not include Audio Media.)

This setting does not need to be enabled in many games.
It is common for players to change the background music of a game.

To understand the problem in more detail, you need to know the Unity implementation.

**Comment by jungletree** [comment]
Try the following two things seems fix this bug:
1) add code ```MobileAds.SetiOSAppPauseOnBackground(true); ```
```
void Start()
{
    MobileAds.Initialize(initStatus => { });

    #if UNITY_IOS
        MobileAds.SetiOSAppPauseOnBackground(true);
    #endif
    // ......
}
```
2) Disabling "Mute other audio sources" in Unity Player settings

**Comment by beginner-lang** [comment]
I have been added in the code "MobileAds. SetiOSAppPauseOnBackground (true);",And disabled" Mute other audio sources ", but there is still a chance that my voice will disappear after the advertisement is broadcast. Note that this is not necessarily the case, but the probability is high. Even if the same advertisement is sometimes normal, sometimes the sound of the game will disappear.
Who can tell me what I should do?
Thank you!

**Comment by cathei** [comment]
I had same issue, and it still remained after setting "SetiOSAppPauseOnBackground" and disabling "Mute other audio sources".

With [some lead](https://stackoverflow.com/questions/64375326/after-advertising-sound-disappears-in-the-game), I suspected that NiceVibration plugin that my project was using is holding some kind of audio api reference, related to Haptic api they use. Fortunately I didn't have to give up the plugin or haptic feedback.

NiceVibration has `HapticController.ProcessApplicationFocus` api to release and regain haptic binding. With code like below, I was able to show ad without this issue.

```csharp
// release haptic binding
HapticController.ProcessApplicationFocus(false);

// wait until ad is closed
await ShowRewardedAd();

// regain haptic binding
HapticController.ProcessApplicationFocus(true);
```

Hope this helps anyone having same issue.

**Comment by cihadturhan** [comment]
> Hope this helps anyone having same issue.

It definitely helped! It was such a difficult issue to find. 
Thank you for your time and dedication :)

**Comment by yoneyamaharuto** [comment]
I have same problem on unity 2022.3.52

**Comment by daniellochner** [comment]
Hi @kunny. This issues seem to have resurfaced!
