### ISSUE TITLE
game crashes when calling RequestBanner()

### ISSUE THREAD

**Issue by pir4t94** [googleads/googleads-mobile-unity#152]
Hello!

I'm making a 2d game in unity and I want to have AdMob banner in my game. So I did everything like it says here: https://developers.google.com/admob/android/games , when I try to run game in Unity Editor it's not showing ads, but everything else is working even log says: Created Dummy Client, Dummy CreateBannerView, Dummy LoadAd (so i guess ads are working) but when i run the game on phone game crashes right after calling RequestBanner() i'm guessing it crashes on bannerView.LoadAd(request);

Here's my RequestBanner function:
private void RequestBanner()
{
// Create a 320x50 banner at the top of the screen.
bannerView = new BannerView("ca-app-pub-2895386526091671/9071811144", AdSize.Banner, AdPosition.Top);
// Create an empty ad request.
request = new AdRequest.Builder().Build();
// Load the banner with the request.
bannerView.LoadAd(request);
}

I tried many thing but nothing is working for me so please help me.

**Comment by ericleich** [comment]
Running on Android? Do you have any logcat output of the crash? My initial guess is you don't have the Google Play services SDK placed in Assets/Plugins/Android, and so the app crashes as soon as the plugin tries to call into that SDK.

**Comment by edgarscr** [comment]
this plugin does not work in unity 5. 
2 month with trouble to compile.
https://github.com/googleads/googleads-mobile-unity/issues/150

**Comment by pir4t94** [comment]
not importing Google Play services SDK was the problem, thanks. I get ads now but the problem is that game becomes laggy and unplayable, can I fix that somehow?

**Comment by ericleich** [comment]
Closing the issue as the original problem is solved.

The performance problem is much harder to solve. The ads sit in a resource-intensive WebView, which is  how just about every mobile ad network's SDK operates (not something the plugin can fix). That combined with a resource intensive Unity game may cause the app to slow down. There isn't really a good remedy for this, other than effective ad placement when you're not actively playing (e.g. using interstitial ads, or placing banner ads on your game over screen).
