### ISSUE TITLE
Breaking compatibility with a lot of Unity versions by adding <queries> tag in 19.6.0

### ISSUE THREAD

**Issue by arkenthera** [googleads/googleads-mobile-unity#1522]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.2.14f1
  * Google Mobile Ads Unity plugin version: _____
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: Android Min 21 Max 29 API level (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:

Include admob and try to build for Android on Unity 2019.2.x

```
.../intermediates/merged_manifests/release/arm64-v8a/AndroidManifest.xml:36: AAPT: error: unexpected element <queries> found in <manifest>.
```

#### Relevant Code:
Hi, so I'm including this in my Unity project:

```
<androidPackage spec="com.mopub.mediation:admob:19.4.0.0" mopub-key="ANDROID_ADAPTER_VERSION"/>
<androidPackage spec="com.google.android.gms:play-services-ads:19.4.0" mopub-key="ANDROID_SDK_VERSION"/>
```

This automatically gets upgraded to 19.6.0 on build an I get the error `unexpected element <queries>`. Now I researched this and figured that I need to upgrade the Gradle bundled with Unity. 

This breaks **every Unity version except [2020.1](https://developers.google.com/ar/develop/unity/android-11-build)**.

To reiterate, latest play-services-ads AAR includes **queries** tag which is not supported by *so many of the bundled Gradles across a lot of Unity versions*.

I tried doing `com.google.android.gms:play-services-ads:[19.4.0]`, but it is still getting upgraded to the latest version.

Is this an intended change?

**Comment by stowy** [comment]
This is an Android 11 compatibility issue. I recommend reviewing [this post](https://developers.google.com/ar/develop/unity/android-11-build) by ARCore for the recommended resolutions.

**Comment by arkenthera** [comment]
I am aware of that post as I already linked it on my original comment. So this means that there is nothing we can do as users, except for upgrading Gradle and that will bring whole lot of new issues.
