### ISSUE TITLE
No ads shown when designed for families is enabled

### ISSUE THREAD

**Issue by Wolfos** [googleads/googleads-mobile-unity#153]
Hi,
We have an issue where advertisements aren't served when designed for families is enabled in the Play Store. In the documentation there's talk of a setIsDesignedForFamilies tag, but this hasn't been implemented in the Unity plugin. Could that be the problem?

**Comment by ericleich** [comment]
See [this help center article](https://support.google.com/admob/answer/6223431?hl=en) for more information. The plugin does not expose the setIsDesignedForFamilies tag, but if your app was accepted by the program into the play store, then it's a "Primary child-directed app" which will automatically serve compliant ads. This method in the SDK is only for a mixed audience app that may not be in the designed for families program.

The help center article mentions that you may see fewer filled impressions if you are in this program. This is the rooting cause in your case; adding that setting through the plugin (if it were there) wouldn't have any effect.
