### ISSUE TITLE
Amob 5.4.0 and Firebase conflicts on Unity

### ISSUE THREAD

**Issue by vfilho** [googleads/googleads-mobile-unity#1532]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.16f1
  * Google Mobile Ads Unity plugin version: 5.4.0
  * Platform: iOS
  * Platform OS version: iOS 14.2
  * Any specific devices issue occurs on: NO
  * Mediation ad networks used, and their versions: NO

### [REQUIRED] Step 2: Describe the problem

- Add Firebase 6.16.1. Any module;
- Try make the build for iOS;
- You will see this message on Console:

```
iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

After the failure, "pod repo update" was executed and succeeded. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.

pod install output:

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
  In Podfile:
    Google-Mobile-Ads-SDK (= 7.67)

    GoogleMobileAdsMediationIronSource (= 7.0.3.0) was resolved to 7.0.3.0, which depends on
      Google-Mobile-Ads-SDK (>= 7.66.0)

    GoogleMobileAdsMediationUnity (= 3.5.1.1) was resolved to 3.5.1.1, which depends on
      Google-Mobile-Ads-SDK (>= 7.68.0)
```

**Comment by novavision** [comment]
You need to Update Firebase to 7.0.x, because AdMob dependent to newer Firebase Core.
But... we didn't do it, because Firebase Messaging 7.0.x+ doesn't work well on iOS and Android - there are several issues I have reported already.

**Comment by TarmoJussila** [comment]
Did you manage to solve this issue? @vfilho

**Comment by vfilho** [comment]
Yes I solved the problem I really don't remember the solution, but that one about update the firebase wasn't enough, I will keep trying remember the solution and post here if I do.
