### ISSUE TITLE
Failed to read GoogleMobileAdsSKAdNetworkIds.xml: I/O error occurred.

### ISSUE THREAD

**Issue by quanarmy** [googleads/googleads-mobile-unity#1534]
Hi. I need some help! I have problem when build my game with iOS platform.
I'm using Unity 2019.4.17f1, Admob 5.4.0.

Console log:
`BuildMethodException: [GoogleMobileAds] Failed to read GoogleMobileAdsSKAdNetworkIds.xml: I/O error occurred.
PListProcessor.ThrowBuildException (System.String message) (at Assets/Plugins/GoogleMobileAds/Editor/PListProcessor.cs:197)
PListProcessor.NotifyBuildFailure (System.String message, System.Boolean showOpenSettingsButton) (at Assets/Plugins/GoogleMobileAds/Editor/PListProcessor.cs:191)
PListProcessor.ReadSKAdNetworkIdentifiersFromXML () (at Assets/Plugins/GoogleMobileAds/Editor/PListProcessor.cs:120)
PListProcessor.OnPostProcessBuild (UnityEditor.BuildTarget buildTarget, System.String path) (at Assets/Plugins/GoogleMobileAds/Editor/PListProcessor.cs:56)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <9577ac7a62ef43179789031239ba8798>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <9577ac7a62ef43179789031239ba8798>:0)
UnityEditor.Build.BuildPipelineInterfaces+AttributeCallbackWrapper.OnPostprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:177)
UnityEditor.Build.BuildPipelineInterfaces+<>c__DisplayClass17_0.<OnBuildPostProcess>b__1 (UnityEditor.Build.IPostprocessBuildWithReport bpp) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:433)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:391)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)`

**Comment by p0w1nd** [comment]
Looking into _PListProcessor.cs_ source code I guess you need to put the `GoogleMobileAds` folder under the `Assets` folder instead of `Assets/Plugins`.

PListProcessor.cs
```
...
    private static List<string> ReadSKAdNetworkIdentifiersFromXML()
    {
        List<string> skAdNetworkItems = new List<string>();

        string path = Path.Combine(Application.dataPath,
            "GoogleMobileAds/Editor/GoogleMobileAdsSKAdNetworkItems.xml");
...
```
