### ISSUE TITLE
 AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.AdSize problem

### ISSUE THREAD

**Issue by tolgair** [googleads/googleads-mobile-unity#154]
I am always getting this error on logcat i try to integrate admob witgh google play services but it ads are not showed there are no compile errors or any thing else. I updated everything to the latest version but can not get rid of this errror. Please help me i am working on this 3 days and can not show any ads on my game here is the logcat :+1: 

 AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.AdSize
 java.lang.ClassNotFoundException: com.google.android.gms.ads.AdSize
      at java.lang.Class.classForName(Native Method)
      at java.lang.Class.forName(Class.java:251)
      at java.lang.Class.forName(Class.java:216)
      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
      at com.unity3d.player.UnityPlayer.a(Unknown Source)
      at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
 Caused by: java.lang.NoClassDefFoundError: com/google/android/gms/ads/AdSize
      ... 6 more
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.AdSize" on path: DexPathList[[zip file "/data/app/com.CpaceStudios.FruitRun-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.CpaceStudios.FruitRun-1, /vendor/
/system/lib/arm]]
      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
      at java.lang.ClassLoader.loadClass(ClassLoade

**Comment by ericleich** [comment]
It looks like you don't have Google Play services library included in the Assets/Plugins/Android folder.

**Comment by tolgair** [comment]
I also have imported google play services. So when I have copy google-play-services_lib to android folder I also get repackaging errors because of duplication I think. I somehow managed to show ads wtih the previous version but with 0.9.30 I tried every solution in internet and I still get the adsize error. Do you have any other solution? What am I doing wrong?

**Comment by theoryginal** [comment]
Hello tolgair,
Could you please check whether you have any aar file under Assets/Plugins/Android folder?  
Any duplication directly cause this issue. I used to have this error and I solved it by clearing aar files and keeping google-play-services_lib. 

By the way the aar files were imported when I used OneSignal unity file without checking duplication in the past, and later I decided to use older version of OneSignal unity integration. 

Please try this and reply, I may help further.

**Comment by tolgair** [comment]
Orhan  thank you ver much for your answer I will give it a try but I want to ask a question. I also have Google Play services plugin so is there any need to keep google-play-services_lib folder? Because it automatically deletes it when you try to build?

**Comment by theoryginal** [comment]
If you are using this [plugin](https://github.com/googleads/googleads-mobile-unity/tree/master/unity) you will need "google-play-services_lib" folder to plugin work properly (showing ads and so on). Why do you have GPS plugin already in Assets for AdMob or for other services?

**Comment by tolgair** [comment]
I have GPS plugin to use google play services as well. With my working scenario I do not have google-play-services_lib in my android folder and I am using 0.9.27 version of GPS plugin. As I say if you try to build with google-play-services_lib in android folder I get repackaging errors and  google-play-services_lib folder is autoamtically deleted. In Admob plugin tutorial they say you should copy it but if you also have GPS plugin you already have this libraries. Am I wrong?

**Comment by rampara** [comment]
The newest release of the plugin (v3.0.0) uses the [JarResolver](https://github.com/googlesamples/unity-jar-resolver) plugin to resolve Google Play Services dependencies. This should make integration of multiple Unity plugins that use Google Play Services into your Unity application easier. The entire Google Play Services library project no longer has to be included in your project. Please re-open the issue if you're still having integrating the newest release of this plugin into your Unity application.

- Ram

**Comment by radi-cho** [comment]
I had similar issue and was able to solve it (or at least work around it).
If interested feel free to take a look over my blogpost: https://medium.com/@radicho/how-to-implement-admob-in-unity-a-bit-more-detailed-guide-4baed2821cce
