### ISSUE TITLE
Events are not being called in Unity's thread on Android

### ISSUE THREAD

**Issue by miguel12345** [googleads/googleads-mobile-unity#155]
Hi,

All the interstitial events (AdOpened,AdClosed), are not being called in Unity's thread since I'm trying to enable a component on the callback and I get the following logs

> E/Unity   (28408): set_enabled can only be called from the main thread.
E/Unity   (28408): Constructors and field initializers will be executed from the loading thread when loading a scene.
E/Unity   (28408): Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.

**Comment by rampara** [comment]
When ad events are forwarded from the Google Mobile Ads Android SDK to the Unity plugin through AndroidProxy, they will not be called on the main thread. To get around this, we recommend the following approach:

For actions required to be performed on the main thread before showing ad

* Perform actions before showing ad

For actions required to be performed on the main thread after showing ad

* Set a flag on the OnAdClosed ad event. The update method can check for this flag and perform actions as necessary.
* In the OnAdClosed ad event dispatch an event to a queue that is checked in the update method.

You can also use AndroidJavaRunnable for Android calls you want performed on the UI thread.

Ram

**Comment by siddharth3322** [comment]
I am also agree with this point. My interstitial delegate are not working after upgrading to new admob sdk.

`//		interstitial.AdLoaded += HandleInterstitialLoaded;
//		interstitial.AdClosed += HandleInterstitialClosed;` 

So please share your suggestion to get back them to work.

**Comment by rampara** [comment]
In the v3.0.0 release of the plugin, the event corresponding to an ad load was changed from 'AdLoaded' to 'OnAdLoaded'. You can find the new names for the other ad events and other changes to the plugin on our [Game Developers Guide](https://developers.google.com/admob/android/games#unity)

- Ram
