### ISSUE TITLE
SDK tried to perform a networking task before being initialized [iOS] [Podfile]

### ISSUE THREAD

**Issue by DmytroSobko** [googleads/googleads-mobile-unity#1550]
[REQUIRED] Step 1: Describe your environment
Unity version: 2019.4.17
Google Mobile Ads Unity plugin version: 5.4.0
Platform: iOS
Platform OS version: iOS 14

[REQUIRED] Step 2: Describe the problem

Admob does not work for iOS, the same code works just fine for Android.
I'm currently using v5.4.0 of this plugin, which was tested with the iOS SDK 7.68.0.

The plugin displays this message "SDK tried to perform a networking task before being initialized" if such lines are added to the podfile.

target 'Unity-iPhone' do
end 

It works fine when there are no such lines, but I really need it for another Snapchat plugin I use in the project which doesn't work without it.

The whole podfile looks like this:

source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'SnapSDK', '1.6.8', :subspecs => ['SCSDKLoginKit', 'SCSDKCreativeKit']
  pod 'Google-Mobile-Ads-SDK', '~> 7.68'
end

target 'Unity-iPhone' do
  pod 'SnapSDK', '1.6.8', :subspecs => ['SCSDKLoginKit', 'SCSDKCreativeKit']
end

Steps to reproduce:
- add 5.4.0 Admob plugin version;
- make the build for iOS;
- add to the Podfile following lines:
target 'Unity-iPhone' do
end
- do pod install
- make a build
- try to load ads
[
![1](https://user-images.githubusercontent.com/47760062/104357284-a5d7f580-5515-11eb-9274-f818e8d99676.jpg)
](url)

**Comment by raheem1988** [comment]
Same issue here. Where you able to solve it?

**Comment by DmytroSobko** [comment]
Adding this to the podfile fixed the issue
use_frameworks! :linkage => :static

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
