### ISSUE TITLE
Not able to build iOS build after adding AdColony mediation

### ISSUE THREAD

**Issue by dharmeshmp** [googleads/googleads-mobile-unity#1552]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.1.17f1
  * Google Mobile Ads Unity plugin version: 5.4.0.90
  * Platform: iOS
  * Platform OS version: 
  * Any specific devices issue occurs on: 
  * Mediation ad networks used, and their versions: AdColony-2.0.1, Chartboost-3.2.0

#### Steps to reproduce:

After integrating AdColony and Chartboost in my unity project, I am getting `'GADUAdNetworkExtras.h' file not found` Error when trying to build iOS project.

![Screenshot 2021-01-15 at 2 53 57 PM](https://user-images.githubusercontent.com/8749772/104707718-c769f480-5742-11eb-9d0d-d8f448eff0c5.png)

**Comment by Zerokcm** [comment]
I have the same problem.
It seems the adColony AdMob Mediation plugin needs an update

**Comment by PriyankaM31191** [comment]
I added 'GADUAdNetworkExtras.h file from previous sdk version and this error was fixed temporarily...May be in next version they can fix this issue, but right now adding this file manually worked.

> // Copyright 2016 Google Inc. All Rights Reserved.

#import <GoogleMobileAds/GoogleMobileAds.h>

@protocol GADUAdNetworkExtras <NSObject>

- (id<GADAdNetworkExtras>)adNetworkExtrasWithDictionary:
    (NSDictionary<NSString *, NSString *> *)extras;

@end

**Comment by SRubioMiranda** [comment]
We are getting this error after manually adding GADUAdNetworkExtras.h
![screenshot2](https://user-images.githubusercontent.com/86415263/123642820-00df7980-d824-11eb-8d8a-7356b85b3335.png)

Used versions
XCode 12.5
Unity 2019.4.25f1
Admob 6.0.1 (20.1.0)
Vungle 3.6.0 (6.9.1.1 Android, 6.9.2.0 iOS)
AppLovin 5.0.0 (10.1.2.0 Android, 10.2.1.0)
UnityAds 2.7.0 (3.7.1.0 Android & iOS)
Facebook 3.3.0 (6.4.0.0 Android, 6.4.1.0 iOS)
AdColony 2.0.3 (4.1.4.1 Android, 4.1.5.0 iOS)

Any idea?

**Comment by roointan** [comment]
Putting [GADUAdNetworkExtras.h](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/Plugins/iOS/GADUAdNetworkExtras.h) in Assets/Plugins/iOS prevented the error for me.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
