### ISSUE TITLE
RECEIVE_BOOT_COMPLETED permission being automatically added to android manifest

### ISSUE THREAD

**Issue by app-dev-ind** [googleads/googleads-mobile-unity#1553]
Not sure if this is a bug or intentional, but using release v5.4.0 (in Unity2019.4.14), the followings are added to the manifest

 
```xml
 <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

<receiver
            android:name="androidx.work.impl.background.systemalarm.RescheduleReceiver"
            android:directBootAware="false"
            android:enabled="false"
            android:exported="false" >
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.TIME_SET" />
                <action android:name="android.intent.action.TIMEZONE_CHANGED" />
            </intent-filter>
        </receiver>
```
Question: Are they necessary? Can RECEIVE_BOOT_COMPLETED be turned off? I do not want to have unnecessary permissions to my app (my app does not use notifications either). Is there any adverse effect of removing this permission with
```xml
 <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" tools:node="remove" />
```
Thank you in advance.

**Comment by ChaserKnight** [comment]
I also found out this issue in my app, did you find any answer? Please someone from Google answer this, is this permission necessary?

**Comment by helpgood** [comment]
Hi @ChaserKnight, I haven't heard back from them. Google please give us an answer. Thank you in advance.

**Comment by app-dev-ind** [comment]
Hi @ChaserKnight, I haven't heard back from them. Google please give us an answer. Thank you in advance.

**Comment by app-dev-ind** [comment]
Adding more details to this thread and hoping for a response. I've added more details in case it's needed. This is not a crash or bugs. But about whether the build process added the correct and only necessary permissions.  

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.14f1 (also tried on 2019.4.10). I don't think it's related to any Unity version.
  * Google Mobile Ads Unity plugin version: v5.4.0
  * Platform: Android
  * Platform OS version: Android 9 and 10 (possibly others since the issue is on the manifest)
  * Any specific devices issue occurs on: All devices
  * Mediation ad networks used, and their versions: None



### [REQUIRED] Step 2: Describe the problem

Not sure if this is a bug or intentional, but using release v5.4.0 (in Unity2019.4.14), the followings are added to the manifest
```xml
 <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

<receiver
            android:name="androidx.work.impl.background.systemalarm.RescheduleReceiver"
            android:directBootAware="false"
            android:enabled="false"
            android:exported="false" >
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.TIME_SET" />
                <action android:name="android.intent.action.TIMEZONE_CHANGED" />
            </intent-filter>
        </receiver>
```
#### Steps to reproduce:
Build APK with the AdMob plugin active.

#### Relevant Code:
Not applicable.

=======

PS: Hi @stowy, if you have any insight on this, your reply will be much appreciated. If you're not the right person to ask, I apologize.

**Comment by ChaserKnight** [comment]
Hi @app-dev-ind did you publish any app after removing the permission like you stated in the last comment? If yes then did you face any issue or not? Please let me know. Also how did you use the remove code that you posted, I don't any idea about how to do that? So please let me know.

**Comment by app-dev-ind** [comment]
Hi @ChaserKnight. That goes to the manifest (for more info, search for **tools:node="remove" in** https://developer.android.com/studio/build/manifest-merge).

I only tested on my test devices which seems fine but I didn't know if it's safe for publishing, so I didn't remove it on the published version. I only tested it on my devices.

Hello @joshuajplagonera or other team member, any insight on this? Any insight appreciated.

**Comment by ChaserKnight** [comment]
Hi @app-dev-ind thanks for the info, should I add the **tools:node="remove"** in the AndroidManifest.xml which is in the **"Plugins/Android/GoogleMobileAdsPlugin.androidlib"** folder which is a part of AdMob plugin? I don't know much about how the manifest file work, so please tell me.

Hi @stowy please look into this issue.

**Comment by app-dev-ind** [comment]
@ChaserKnight 
Do you have "Assets/Plugins/Android/AndroidManifest.xml"? That is where I added. See "Overriding the Android manifest" in https://docs.unity3d.com/Manual/android-manifest.html

(If you add it into Plugins/Android/GoogleMobileAdsPlugin.androidlib it might work, too but it might get overwritten if you update the plugin.)

**Comment by ChaserKnight** [comment]
@app-dev-ind thank you so much for the info, it is so helpful.

**Comment by Vixxd** [comment]
I'd also like to remove this and would love to know the problems caused, if any!

**Comment by ChaserKnight** [comment]
Hello!!! is there any update on this issue? Is there someone listening from AdMob team? Hello!!! Or this plugin is abandoned now and I am just talking to the void? Hello!!! The latest version of the plugin was released in November last year. Somebody please respond.

**Comment by ChaserKnight** [comment]
This is getting ridiculous, how the AdMob team does not ever care about us developers anymore, I am getting 1 star reviews from users just because of this "run at startup" permission, that we don't ever know why it is there in our app, because you guys don't even care about explaining what's going on with this permission. I mean c'mon guys.

**Comment by ericleich** [comment]
@ChaserKnight responded at https://groups.google.com/g/google-admob-ads-sdk/c/2OXYkWnMmI0/m/Vxlj1H9cBwAJ which can be used for future discussion. Closing here because this has nothing to do with the Unity plugin, but the underlying Google Mobile Ads SDK for Android and its dependencies.

**Comment by justmeforyou** [comment]
Root
