### ISSUE TITLE
Google Mobile Ads Unity Plugin v3.0.0

### ISSUE THREAD

**Issue by edgarscr** [googleads/googleads-mobile-unity#156]
Loading **Loading** Loading **Loading** and **never end**

> NEVER END

![image](https://cloud.githubusercontent.com/assets/16306453/12770006/e1b041be-c9ee-11e5-82c4-5576b2f66077.png)

@rampara

**Comment by rampara** [comment]
I'm having trouble replicating this issue. If you can attach or link to a project where you're seeing this behavior, it can help me in investigating the problem further. 

- Ram

**Comment by edgarscr** [comment]
![image](https://cloud.githubusercontent.com/assets/16306453/12782706/2268e84a-ca4f-11e5-9029-8474a97f1c5d.png)

**Comment by rampara** [comment]
I'm not sure why you attached the image above. A unity project that exhibits the problem you mentioned would be helpful to solving this issue.

- Ram

**Comment by edgarscr** [comment]
i can't share my project.

**Comment by rampara** [comment]
Reproducing the problem in our sample application and sharing that would work too.

**Comment by Rhiojin** [comment]
I had this same exact problem. I solved it by first quitting Unity and then using explorer or finder navigate to the project folder and: delete all the play-services aar files, Delete the GoogleMobileAds folder and delete the GooglePlayGames folder. Then Reimport GooglePlayGames using v.0.9.30 package and then reimport GoogleMobileAds using the v.3.0.0 package.

Hope this helps.

**Comment by edgarscr** [comment]
Another Error.

![image](https://cloud.githubusercontent.com/assets/16306453/12814864/845aa230-cb14-11e5-9237-268f2bfc53e8.png)

**Comment by rampara** [comment]
Do you have the iOS module for Unity installed? If not, can you change the compiler directive on lines 7 and 51 in Postprocessor.cs from "#if UNITY_5" to "#if (UNITY_5 && UNITY_IOS)".

- Ram

**Comment by edgarscr** [comment]
This is how i put. and all good i think. my ads working.  finally added a new version to game.

```
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor.Callbacks;
using UnityEditor;

//#if UNITY_5
//    using UnityEditor.iOS.Xcode;
//#endif

namespace GoogleMobileAds
{
    public class Postprocessor
    {
        [PostProcessBuildAttribute(1)]
        public static void OnPostprocessBuild(BuildTarget target, string pathToBuiltProject)
        {
            BuildTarget iOSBuildTarget;
            #if UNITY_5
                iOSBuildTarget = BuildTarget.iOS;
            #else
                iOSBuildTarget = BuildTarget.iPhone;
            #endif

            if(target == iOSBuildTarget)
            {
                runPodUpdate(pathToBuiltProject);
            }
        }

        static void runPodUpdate(string path)
        {
            // Copy the podfile into the project.
            string podfile = "Assets/GoogleMobileAds/Editor/Podfile";
            string destpodfile = path + "/Podfile";
            if(!System.IO.File.Exists(destpodfile))
            {
                FileUtil.CopyFileOrDirectory(podfile, destpodfile);
            }

            try
            {
                CocoaPodHelper.Update(path);
            }
            catch (Exception e)
            {
                UnityEngine.Debug.Log("Could not create a new Xcode project with CocoaPods: " +
                    e.Message);
            }

//            #if UNITY_5
//                string pbxprojPath = path + "/Unity-iPhone.xcodeproj/project.pbxproj";
//                PBXProject project = new PBXProject();
//                project.ReadFromString(File.ReadAllText(pbxprojPath));
//                string target = project.TargetGuidByName("Unity-iPhone");
//
//                project.SetBuildProperty(target, "CLANG_ENABLE_MODULES", "YES");
//                project.AddBuildProperty(target, "OTHER_LDFLAGS", "$(inherited)");
//
//                File.WriteAllText(pbxprojPath, project.WriteToString());
//            #else
//                UnityEngine.Debug.Log("Unable to modify build settings in XCode project. Build " +
//                        "settings must be set manually");
//            #endif
        }
    }
}

```
