### ISSUE TITLE
You are trying to create a MonoBehaviour using the 'new' keyword. This is not allowed. Unity Google AdMob

### ISSUE THREAD

**Issue by gurustron** [googleads/googleads-mobile-unity#1562]
https://github.com/googleads/googleads-mobile-unity/blob/66f6ae3263582f1d0634283d4fd85986d80b42c1/source/plugin/Assets/GoogleMobileAds/Platforms/Unity/BannerClient.cs#L64

see [this](https://stackoverflow.com/q/65955147/2501279) SO question. `ButtonBehaviour` is a `MonoBehaviour`

**Comment by SavaMinic** [comment]
+1

**Comment by TimCurtis468** [comment]
+1

**Comment by soundmartell** [comment]
+1

**Comment by cathei** [comment]
+1

**Comment by onurselcuk** [comment]
+1

**Comment by NVentimiglia** [comment]
Fixed in latest.
