### ISSUE TITLE
[NSProcessInfo isiOSAppOnMac]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by tianwwMT** [googleads/googleads-mobile-unity#1563]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.15f1
  * Google Mobile Ads Unity plugin version: 7.69.0
  * Platform: iOS
  * Platform OS version: 14.0 beta (18A5301v)
  * Any specific devices issue occurs on: Currently on iPad Air 2
  * Mediation ad networks used, and their versions: AppLovinMediationGoogleAdapter (7.69.0.1)

### [REQUIRED] Step 2: Describe the problem
Crash occurs when app launching.
### Crash backtrace
`CrashType: UncaughtException 
CrashReason: -[NSProcessInfo isiOSAppOnMac]: unrecognized selector sent to instance 0x283158210
Crash stack:
0 CoreFoundation 0x000000019dae94f8 D3AFD0BA-F0B6-31BD-B65D-2DE422745537 + 1152248 
1 libobjc.A.dylib 0x000000019d80c26c objc_exception_throw + 56 
2 CoreFoundation 0x000000019d9fac4c D3AFD0BA-F0B6-31BD-B65D-2DE422745537 + 175180 
3 CoreFoundation 0x000000019daebb24 D3AFD0BA-F0B6-31BD-B65D-2DE422745537 + 1162020 
4 CoreFoundation 0x000000019daeda9c _CF_forwarding_prep_0 + 92 
5 UnityFramework 0x0000000100cc13a8 GADTransparencyAuthorizationStatus + 524 
6 UnityFramework 0x0000000100cc1258 GADTransparencyAuthorizationStatus + 188 
7 libdispatch.dylib 0x000000019d7a96d8 174B8B8A-283C-32C8-A283-8DF63F76835F + 390872 
8 libdispatch.dylib 0x000000019d74e218 174B8B8A-283C-32C8-A283-8DF63F76835F + 16920 
9 UnityFramework 0x0000000100cc1234 GADTransparencyAuthorizationStatus + 152 
10 UnityFramework 0x0000000100d04a04 GADEnvironmentIsSupported + 3664 
11 libdispatch.dylib 0x000000019d7a86f0 174B8B8A-283C-32C8-A283-8DF63F76835F + 386800 
12 libdispatch.dylib 0x000000019d7a96d8 174B8B8A-283C-32C8-A283-8DF63F76835F + 390872 
13 libdispatch.dylib 0x000000019d758f04 174B8B8A-283C-32C8-A283-8DF63F76835F + 61188 
14 CoreFoundation 0x000000019da692e0 D3AFD0BA-F0B6-31BD-B65D-2DE422745537 + 627424 
15 CoreFoundation 0x000000019da63bb8 D3AFD0BA-F0B6-31BD-B65D-2DE422745537 + 605112 
16 CoreFoundation 0x000000019da63030 CFRunLoopRunSpecific + 540 
17 GraphicsServices 0x00000001a94b4598 GSEventRunModal + 160 
18 UIKitCore 0x00000001a211b570 8C7158E2-3F37-3B7E-81BA-D084E36C5DD8 + 11433328 
19 UIKitCore 0x00000001a2121330 UIApplicationMain + 1864 
20 UnityFramework 0x0000000100626388 UnityFramework + 107400 
21 mansion 0x0000000100383e00 mansion + 32256 
22 libdyld.dylib 0x000000019d8f79d0 B0000CCF-C56D-3662-8631-1B4831962316 + 6608`

#### Steps to reproduce:

Update Google Admob to 7.69.0, then crash occurs on iPad Air 2 with iOS 14 beta(18A5301v).

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
