### ISSUE TITLE
admob banner AdPosition.Bottom

### ISSUE THREAD

**Issue by realluhui** [googleads/googleads-mobile-unity#1565]
### [REQUIRED] Step 1: Describe your environment

   * Unity version: 2018.4.18f1
   * Google Mobile Ads Unity plugin version: 5.4.0
   * Platform: Android
   * Platform OS version: Android 8.1.0
   * Any specific devices issue occurs on: nexus 5x

### [REQUIRED] Step 2: Describe the problem
i use BannerView("ad unit id", new AdSize(AdSize.FullWidth, 50), AdPosition.Bottom) to create admob banner, 
if  load banner before app view  created, May appear at the top.
or a Interstitial Ad display is closed after completion, banner May appear at the top yet

**Comment by a314266177** [comment]
I have the same problem, the banner will appear in the top left corner

**Comment by dqnhust** [comment]
I am facing this problem too.
Code:
AdSize adaptiveSize =
                AdSize.GetCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth(AdSize.FullWidth);
            _bannerView = new BannerView(bannerId, adaptiveSize, bannerPosition);
In a special devices Banner Position Always appear in the Top.
Plugin Version 6.0.0
Devices Samsung SM J320G
