### ISSUE TITLE
GoogleMobileAdsFacebookMediation 3.2.0 conflict with GoogleMobileAdUnity 5.4.0

### ISSUE THREAD

**Issue by hnim** [googleads/googleads-mobile-unity#1572]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.14f1
  * Google Mobile Ads Unity plugin version: 5.4.0
  * Platform: iOS
  * Platform OS version:  iOS 10
  * Mediation ad networks used, and their versions: GoogleMobileAdsFacebookMediation 3.2.0, FBAudienceNetwork-6.2.1

### [REQUIRED] Step 2: Describe the problem
iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

After the failure, "pod repo update" was executed and succeeded. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.

pod install output:

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In snapshot (Podfile.lock):
    GoogleAppMeasurement (= 7.0.0, ~> 7.0)

  In Podfile:
    Firebase/Core (= 7.5.0) was resolved to 7.5.0, which depends on
      FirebaseAnalytics (= 7.5.0) was resolved to 7.5.0, which depends on
        GoogleAppMeasurement (= 7.5.0)

    GoogleMobileAdsMediationFacebook (= 6.2.1.0) was resolved to 6.2.1.0, which depends on
      Google-Mobile-Ads-SDK (>= 7.69.0) was resolved to 7.69.0, which depends on
        GoogleAppMeasurement (~> 7.0)
```

pls update google mobile ad, it's out of date

**Comment by qbit86** [comment]
> pls update google mobile ad, it's out of date

@hnim
The similar issue here: https://github.com/googleads/googleads-mobile-unity/issues/1569

@joshuajplagonera
When will update for Unity plugin be available?

**Comment by joshuajplagonera** [comment]
Hi All,

I have tried replicating the issue describe here and I am not able to replicate it as everything seems to be working as expected using the same versions as outlined.

As for the Unity plugin, we are actively working on updating it.

**Comment by blueveno** [comment]
please update

**Comment by qbit86** [comment]
@uladzislaubasin 
> Meanwhile, I am moving to Unity Ads

Similarly, now I'm forced to integrate ironSource instead of abandoned Google Mobile Ads Unity Plugin :(

@ericleich [said](https://github.com/googleads/googleads-mobile-unity/issues/1569#issuecomment-790805661):
> we... are actively working to get this updated.

But no work seems to be in progress in active branches. And no comments from assignee @JillSong

**Comment by JillSong** [comment]
Hey folks, v6.0.0 is out now. This will enable mediation adapters that depend on GMA iOS SDK v8 or above and on GMA Android SDK v20 or above.
