### ISSUE TITLE
Outdated documentation for Ad Events.

### ISSUE THREAD

**Issue by jjjuande** [googleads/googleads-mobile-unity#158]
The documentation:
https://developers.google.com/admob/android/games#unity

In section *Ad events*:
*AdLoaded* is now *OnAdLoaded*
*AdClosing* it doesn't exist anymore
etc.

**Comment by rampara** [comment]
The developer documentation at the link above has been updated to reflect the changes in v3.0.0 of this plugin. 

- Ram
