### ISSUE TITLE
Mediation vungle banner issue

### ISSUE THREAD

**Issue by CodingGom** [googleads/googleads-mobile-unity#1580]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.0f1
  * Google Mobile Ads Unity plugin version: 5.4.0
  * Platform: All (iOS, Android, Unity Editor)
  * Platform OS version: - (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: mobile-ads-adapters-unity / GoogleMobileAdsVungleMediation 3.5.1
  

#### Steps to reproduce:

Hello, I use google admob mediation sdk (unity).

I can't see vungle banner in my project. Only can see admob banner.

I don't have anyting extra work like below

```
VungleRewardedVideoMediationExtras extras = new VungleRewardedVideoMediationExtras();
#if UNITY_ANDROID
    extras.SetAllPlacements(new string[] { "ANDROID_PLACEMENT_1", "ANDROID_PLACEMENT_2" });
#elif UNITY_IPHONE
    extras.SetAllPlacements(new string[] { "IOS_PLACEMENT_1", "IOS_PLACEMENT_2" });
#endif

AdRequest request = new AdRequest.Builder()
        .AddMediationExtras(extras)
        .Build();
```
        
Do I need to do anything else like the code above? Or is it a bug?

I couldn't find anything related to it in the documentation. Is it my mistake?

Please give me feedback.

#### Relevant Code:

```
        AdSize adaptiveSize =
        AdSize.GetCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth(AdSize.FullWidth);
        
        bannerView = new BannerView(bannerID, adaptiveSize, AdPosition.Bottom);
        AdRequest request = new AdRequest.Builder().TagForChildDirectedTreatment(true).Build();
        bannerView.LoadAd(request);

        bannerView.OnAdLoaded += HandleBannerOnLoad;
        bannerView.OnAdClosed += HandleBannerOnClose;
        bannerView.OnAdFailedToLoad += HandleBannerFailed;
```

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
