### ISSUE TITLE
asmdef missing in mediation packages?

### ISSUE THREAD

**Issue by mastef** [googleads/googleads-mobile-unity#1584]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.2.11f1
  * Google Mobile Ads Unity plugin version: master
  * Platform: Unity Editor
  * Platform OS version: MacOS
  * Any specific devices issue occurs on: Compilation
  * Mediation ad networks used, and their versions: UnityAds ( master ), Facebook ( master )

#### Steps to reproduce:

When trying to add the UnityAds mediation package to the latest github master version, it cannot find the references to :
```
using GoogleMobileAds.Common.Mediation.UnityAds;
using GoogleMobileAds.Mediation;
```
And throws the errors : 
```
Assets/GoogleMobileAds/Api/Mediation/UnityAds/UnityAds.cs(17,23): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'GoogleMobileAds' (are you missing an assembly reference?)
Assets/GoogleMobileAds/Api/Mediation/UnityAds/UnityAds.cs(18,23): error CS0234: The type or namespace name 'Mediation' does not exist in the namespace 'GoogleMobileAds' (are you missing an assembly reference?)
```

![image](https://user-images.githubusercontent.com/762297/112269515-08363a80-8cab-11eb-88e2-bdebb9ff2666.png)

This may be due to missing asmdef file for `GoogleMobileAds.Api.Mediation.UnityAds`, or something missing in the `GoogleMobileAds.Api.Mediation` that's one level above - but I'm not a 100% sure.

**Comment by mastef** [comment]
So to get the UnityAds mediation to work with the master branch I added a `Assets/GoogleMobileAds/Platforms/Mediation/GoogleMobileAds.Mediation.asmdef` with : 
```json
{
    "name": "GoogleMobileAds.Mediation",
    "references": [
        "GoogleMobileAds.Common"
    ]
}
``` 

And a `Assets/GoogleMobileAds/Api/Mediation/UnityAds/GoogleMobileAds.Api.Mediation.Unity.asmdef` with : 
```json
{
    "name": "GoogleMobileAds.Api.Mediation.Unity",
    "references": [
        "GoogleMobileAds.Mediation",
        "GoogleMobileAds.Common"
    ],
    "includePlatforms": [],
    "excludePlatforms": [],
    "allowUnsafeCode": false,
    "overrideReferences": false,
    "precompiledReferences": [],
    "autoReferenced": true,
    "defineConstraints": [],
    "versionDefines": [],
    "noEngineReferences": false
}
```

**Comment by NVentimiglia** [comment]
I have made note of this feature request. I cannot give a timetable, but I agree with the concerned. Thank you.
