### ISSUE TITLE
After adding Google Play Games plugin admob stop working

### ISSUE THREAD

**Issue by siddharth3322** [googleads/googleads-mobile-unity#159]
First I completely test my admob functionality then after I have added google play games plugin.

Now I have working Google play services but admob is stopped with following message.

` AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.AdSize
                                          at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
                                          at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0 
                                          at UnityEngine.AndroidJavaObject._CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
                                          at UnityEngine.AndroidJavaObject.CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
                                          at UnityEngine.AndroidJavaObject.FindClass (System.String name) [0x00000] in <filename unknown>:0 
                                          at UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) [0x00000] in <filename unknown>:0 
                                          at UnityEngine.AndroidJavaObject..ctor (System.String className, System.Object[] args) [0x00000] in <filename unknown>:0 
                                          at GoogleMobileAds.Android.Utils.Get`

Please give me some sort of help. Even I have implemented new admob 3.0 as well.

**Comment by rampara** [comment]
I'm unable to reproduce this issue by adding the latest Unity packages for the AdMob and Google Play Games plugins to a Unity project. I'm able to request and display ads. If you can share a project where you're seeing this problem, it can help me investigate further.

Ram

**Comment by rampara** [comment]
Also, if you're having issues with ad events, it is likely because ad event names changed in the latest release of our plugin. You can find more information on our [Game Developers Guide](https://developers.google.com/admob/android/games#unity)

- Ram

**Comment by siddharth3322** [comment]
I have deleted all plugins from game- admob and google play service.
downloaded latest version from store and import into project.

but now I have admob banner working correctly but can't able to authenticate google play service for me. even nothing happen in device screen. I have uploaded image of log data I am getting.

[https://www.dropbox.com/s/1s91t2icgkdzvq9/Screen%20Shot%202016-02-04%20at%202.10.25%20PM.png?dl=0&preview=Screen+Shot+2016-02-04+at+2.10.25+PM.png](url)

**Comment by rampara** [comment]
The link you posted above doesn't seem to be working.

**Comment by slamet** [comment]
I am failed **REPACKAGE after adding googleads mobile plugin **,

**Comment by rampara** [comment]
@slamet Can you provide more information on the error you're seeing? Output from the Unity console would be helpful for debugging.

**Comment by siddharth3322** [comment]
@rampara, please copy and paste above link into browser, it is working. I checked it now.

**Comment by rampara** [comment]
Does your Unity project include the appcompat-v7-x.x.x.aar in 'Assets/Plugins/Android'?

**Comment by siddharth3322** [comment]
This is my plugin/android folder data so that you can understand much better way.

[https://www.dropbox.com/s/0xftxq5ho1rys8p/plugindata.png?dl=0](url)

**Comment by rampara** [comment]
You no longer have to include the Google Play Services library project in your Unity application to use this plugin. The [JarResolver](https://github.com/googlesamples/unity-jar-resolver) library should copy the neccessary Google Play services client libraries into Unity projects at build time. Our integration instructions have been updated in our [developer docs](https://developers.google.com/admob/android/games#unity). You seem to have also have included both an AAR and library project for the Android Support Repository (appcompat-v7-x.x.x.aar and appcompat-v7-x.x.x folder).

**Comment by siddharth3322** [comment]
If I don't paste over their library project then I was getting other error.
I already know about this that it is not necessary to put Google Play Service library project.

Wait I will paste error what I get after removing library.

**Comment by siddharth3322** [comment]
If I remove google play service library then I am getting following 2 errors in debug log.

![errorcreatingserviceobj](https://cloud.githubusercontent.com/assets/3082151/12925336/dd6bd768-cf83-11e5-88e1-1374bac18dab.png)

![adsizeerror](https://cloud.githubusercontent.com/assets/3082151/12925347/e4f81938-cf83-11e5-9fd2-bec92d802868.png)

Nothing related to authentication happen on device screen.

**Comment by rampara** [comment]
Can you share a Unity project where you can reproduce this problem?

**Comment by siddharth3322** [comment]
Okay I shared my unity project so that you can get more better idea regarding problem.

I have removed other part of project because it is my working game and I don't want it to be open now.

This problem consumes my few days so please guide me in this before I have implemented number of time google play service but this time this thing is really frustrating me.

Dropbox link
[https://www.dropbox.com/s/j0wibe0r3iml04i/HotWings.zip?dl=0](url)

Please copy and paste to use this link.
I am eagerly waiting for your reply.

**Comment by rampara** [comment]
After deleting the 'res' folder from 'Assets/Plugins/Android/GoogleMobileAdsPlugin/', I was able to build the project you attached. Does this change fix your issue?

**Comment by siddharth3322** [comment]
> After deleting the 'res' folder from 'Assets/Plugins/Android/GoogleMobileAdsPlugin/', I was able to build the project you attached. Does this change fix your issue?

If res folder exist then also I can able to build the project.
But if I try to remove res folder from project then I am getting this kind of error.

Which version of Unity you are using?
I am on unity 4.6.8 and 4.6.9 both.
In both I am getting same error.

For this project I am using google play service v0.9.30.

![googleplayvariablenotfound](https://cloud.githubusercontent.com/assets/3082151/12979021/91d19252-d0fa-11e5-8bc9-0e0fcff79d78.png)

**Comment by siddharth3322** [comment]
@rampara, I am also struggling in running minimal demo.
That discussion running in this thread.

[https://github.com/playgameservices/play-games-plugin-for-unity/issues/963](url)

**Comment by rampara** [comment]
I was able to successfully build the Unity project you attached above with the latest version of Unity (5.3.2).

**Comment by baikodur** [comment]
I have a similar problem:
1. Delete 'res' folder from 'Assets/Plugins/Android/GoogleMobileAdsPlugin/' folder.
2. Check AndroidManifest.xml target version. It is "19" in this package.
3. Check in Android SDK Manager, wich version do you have.

I changed 19 to 23 and it worked.

**Comment by siddharth3322** [comment]
Initially, I tried to build plugin in unity version 4.6.9 version but all my efforts goes into dustbin.
Just I switched my project with unity 5.3+ versions and everything works like a charm.

So I advice to other members as well, first please switch to latest version of unity then try to figure out remaining errors.
