### ISSUE TITLE
Cannot find protocol declaration for 'GADRewardedAdDelegate'; did you mean 'GADNativeAdDelegate'?

### ISSUE THREAD

**Issue by ugurdeniz20** [googleads/googleads-mobile-unity#1590]
I am getting 10 errors like this. Only from 'GADRewardedAd' library. 
on XCode 12.4

**Comment by Fudds** [comment]
Having this same problem on the most recent Google Mobile Ads plugin for iOS. Mediating through ironsource

**Comment by ugurdeniz20** [comment]
Doesn't have any solution?

**Comment by riocallos** [comment]
I am getting this exact same issue. There was a similar issue here last February it was closed but it still isn't fixed. https://github.com/googleads/googleads-mobile-unity/issues/1569

**Comment by olpero** [comment]
@riocallos I had those same errors before I deleted the old files from the previous version of admob. But after that I get "Undefined symbol" errors when building with xcode.

**Comment by hlongvu** [comment]
Face this issue too, turn out because updating the plugin without delete old file at Plugins/iOS

**Comment by antonysze** [comment]
I tried to remove all old files in Plugins/iOS from the last version, it still shows the same error on my Xcode.

Unity 2019.4.18
Google Mobile Ads Unity Plugin v6.0.0
Xcode 12.4

**Comment by riocallos** [comment]
It is now somehow fixed on my side. I'm not really sure how it was fixed but I just ran pod install and then opened the xcworkspace then it was all good.

**Comment by riocallos** [comment]
> > It is now somehow fixed on my side. I'm not really sure how it was fixed but I just ran pod install and then opened the xcworkspace then it was all good.
> 
> What version Unity you used?

Unity 2018.4.34f1, XCode 12.5

**Comment by minidragon-jacky** [comment]
Facing the same problem here. I am using Unity 2019.4.21f1 and XCode 12.4.
I just found that GoogleMobileAdsDependencies sets the version of "Google-Mobile-Ads-SDK" as "~> 7.50".
However, IronSource AdMob Adapter requires "Google-Mobile-Ads-SDK" for version " >= 8.50".
So I editor GoogleMobileAdsDependencies .cs form "~> 7.50" to "=> 7.50"
And I just found that GADRewardedAdDelegate is only for version 7.X. 
So when cocoapod install version 8.50 in my project. GADRewardedAdDelegate will be missing.
I don't know how to solve it instead of waiting for official update.

**Comment by wwidelec1** [comment]
Changing my ads pods to:

pod 'GoogleMobileAdsMediationAppLovin', '6.14.6.0'
pod 'GoogleMobileAdsMediationFacebook', '6.2.0.0'
pod 'GoogleMobileAdsMediationUnity', '3.5.0.0'
pod 'Google-Mobile-Ads-SDK', '7.69'

Helped with this error, but instead i got:

Plugins/iOS/UnityAdsShowListener.h:8:45: No type or protocol named 'UnityAdsShowDelegate'
Plugins/iOS/UnityAdsUnityWrapper.m:79:15: No known class method for selector 'show:placementId:showDelegate:'

I guess it was related to what I changed. It's so frustrating.
Did someone manage to solve it?

**Comment by wwidelec1** [comment]
Update: Deleting all mediations and setting 'Google-Mobile-Ads-SDK' to 7.69 fixed it, i can build the game. But it crashes on splash screen

**Comment by erikhallgren** [comment]
Iäm having this issue as well, severly blocked by it

**Comment by erikhallgren** [comment]
> Update: Deleting all mediations and setting 'Google-Mobile-Ads-SDK' to 7.69 fixed it, i can build the game. But it crashes on splash screen

Check that error message, it probably is because of no SKAdNetwork identifier in your .plist

**Comment by wwidelec1** [comment]
@erikhallgren "Undefined symbol" is totally different error. I'm not an iOS expert, but as far as i remember, changing architectures, or adding -objC to linker flag might help with this.

**Comment by wwidelec1** [comment]
Hey @riocallos, can you send us your podfile and podfile.lock? Or type "cat Podfile.lock" in your project's location in terminal and send us the logs. It will be really helpful

**Comment by OmarMahmoud120** [comment]
same here unity 2020.2.3f1 Xcode 12.5.1 [Google Mobile Ads Unity Plugin v6.0.1](https://github.com/googleads/googleads-mobile-unity/releases/tag/v6.0.1) 
podfile.lock
PODS:
  - Google-Mobile-Ads-SDK (8.6.0):
    - GoogleAppMeasurement (< 9.0, >= 7.0)
    - GoogleUserMessagingPlatform (>= 1.1)
  - GoogleAppMeasurement (8.2.0):
    - GoogleAppMeasurement/AdIdSupport (= 8.2.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.4)
    - GoogleUtilities/MethodSwizzler (~> 7.4)
    - GoogleUtilities/Network (~> 7.4)
    - "GoogleUtilities/NSData+zlib (~> 7.4)"
    - nanopb (~> 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (8.2.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.4)
    - GoogleUtilities/MethodSwizzler (~> 7.4)
    - GoogleUtilities/Network (~> 7.4)
    - "GoogleUtilities/NSData+zlib (~> 7.4)"
    - nanopb (~> 2.30908.0)
  - GoogleUserMessagingPlatform (2.0.0)
  - GoogleUtilities/AppDelegateSwizzler (7.4.1):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.4.1):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (7.4.1):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.4.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.4.1):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.4.1)"
  - GoogleUtilities/Reachability (7.4.1):
    - GoogleUtilities/Logger
  - nanopb (2.30908.0):
    - nanopb/decode (= 2.30908.0)
    - nanopb/encode (= 2.30908.0)
  - nanopb/decode (2.30908.0)
  - nanopb/encode (2.30908.0)
  - PromisesObjC (1.2.12)

DEPENDENCIES:
  - Google-Mobile-Ads-SDK (~> 8.2)

SPEC REPOS:
  https://github.com/CocoaPods/Specs.git:
    - Google-Mobile-Ads-SDK
    - GoogleAppMeasurement
    - GoogleUserMessagingPlatform
    - GoogleUtilities
    - nanopb
    - PromisesObjC

SPEC CHECKSUMS:
  Google-Mobile-Ads-SDK: 0d6e2e065c4efe9836bca3fbd6ff9ef0bca073c2
  GoogleAppMeasurement: b52eafc9dff542d580700e708216568bd2fbf168
  GoogleUserMessagingPlatform: ab890ce5f6620f293a21b6bdd82e416a2c73aeca
  GoogleUtilities: f8a43108b38a68eebe8b3540e1f4f2d28843ce20
  nanopb: a0ba3315591a9ae0a16a309ee504766e90db0c96
  PromisesObjC: 3113f7f76903778cf4a0586bd1ab89329a0b7b97

PODFILE CHECKSUM: 11736dcdc57edbf62ff27c0fe4eee5ce9e8ea055

COCOAPODS: 1.10.1

**Comment by SRubioMiranda** [comment]
Still broken on Admob Unity Plugin v6.0.1. Will you fix it or?

**Comment by wwidelec1** [comment]
I deleted everything under Plugins/iOS and it works now. I got another error, but it was easy to fix with google

**Comment by p0w1nd** [comment]
> I deleted everything under Plugins/iOS, then updated admob and it works now. I got another error, but it was easy to fix with google

Is that "another error" about 'GADUAdNetworkExtras.h' file not found? Ref:
https://github.com/googleads/googleads-mobile-unity/issues/1617
https://github.com/googleads/googleads-mobile-unity/issues/1552

**Comment by wwidelec1** [comment]
@p0w1nd Nope, it was different. I don't remember the content, but I was albe to fix it in 5 minutes with google :)

**Comment by williamtong0228** [comment]
I also have the problem
Plugins/iOS/UnityAdsShowListener.h:8:45: No type or protocol named 'UnityAdsShowDelegate'
Plugins/iOS/UnityAdsUnityWrapper.m:79:15: No known class method for selector 'show:placementId:showDelegate:'

It could be that I updated from verified 3.6 to 3.7.1 , but later when I removed both and reinstall 3.6, it told me that it cannot find ibraries/com.unity.ads/Plugins/iOS/UnityAdsShowListener.mm in the target. 
So frustrated, I really want to go without unityads, the website  asked me to update to 3.7.x where it cannot be complied or with empty reference.

**Comment by chandujr** [comment]
Please check if this solves your issue: https://github.com/googleads/googleads-mobile-unity/issues/1569#issuecomment-874685709

**Comment by OmarMahmoud120** [comment]
I fix it by removing the ads SDK from the project totally and import it again

**Comment by RaadGames** [comment]
i have the same 10 errors , any idea how to fix this!!

**Comment by tadjeddine25** [comment]
downolad the lastest admob unity  plugin 6.1.1v https://github.com/googleads/googleads-mobile-unity/releases/tag/v6.1.1
 and follow those tips  for iOS https://www.youtube.com/watch?v=e-q_CPfu0M0

**Comment by MarcoLavoro** [comment]
any solution for this i am stuck with this FROM WEEKS!!!!!

**Comment by omert742** [comment]
Same here, still stuck on it

Please help

**Comment by NVentimiglia** [comment]
Please do it for install of the latest Google mobile ads package. This includes removing the old insulation and downloading and installing the latest. If you still have problems please reopen this case.

**Comment by haseebsohail1** [comment]
Guys any update? I am stack from weeks.
