### ISSUE TITLE
Problems with xcode

### ISSUE THREAD

**Issue by Tonykeoasa** [googleads/googleads-mobile-unity#160]
I added the package to my unity project and I am getting errors about missing GoogleMobleAds.h and could not build googlemobileads. I added the googlemobileads framework and it still isn't working. does anyone have a solution?

**Comment by rampara** [comment]
With the latest version of our plugin, a CocoaPods xcworkspace that includes the Google Mobile Ads SDK should be created when you build for iOS.

**Comment by AdnanNazir** [comment]
Yes the latest version should do. But I am not able to achieve this.
After installing cocapods I am now unable to get any xcode workspace file and so having the issue. 
WHat should I do?
![screen shot 2016-05-11 at 2 59 00 pm](https://cloud.githubusercontent.com/assets/6734301/15177354/fabba1b6-1788-11e6-92d9-78739f808290.png)

**Comment by rampara** [comment]
The current podfile distributed with the Unity plugin is incompatible with the latest version of Coocapods (1.0.0). Removing the podfile within `Assets/GoogleMobileAds/Editor/` directory and creating a new one with the `pod init` command will fix the issue. You will need to add the Google Mobile Ads pod ('Google-Mobile-Ads-SDK', '~> 7.8') to the newly created podfile.

**Comment by AdnanNazir** [comment]
Hi How I can do this ?
The PodFile is Unity is not part of a XCode Project !
![screen shot 2016-05-14 at 2 31 03 pm](https://cloud.githubusercontent.com/assets/6734301/15267649/e156458c-19e0-11e6-9b6e-5c815af6376a.png)

**Comment by rampara** [comment]
The `pod init` command should be run in within the directory for the Unity generated Xcode project.

**Comment by rampara** [comment]
Closing issue due to non-response. If this issue persists, please re-open.
