### ISSUE TITLE
Crashed: AVAudioSession Notify Thread EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000000001b0 InterruptionListener(void*, unsigned int, unsigned int, void const*)

### ISSUE THREAD

**Issue by a314266177** [googleads/googleads-mobile-unity#1603]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: __unity2018.4.11f1___
  * Google Mobile Ads Unity plugin version: __5.4.0___
  * Platform: __iOS and Android___ (iOS, Android, Unity Editor)
  * Platform OS version: __all___ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

I think the way it's probably replicated is when you're opening your app and you're playing an AD, and then you get a phone call, and you get this problem
firebase crashlytics
Crashed: AVAudioSession Notify Thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000000001b0
InterruptionListener(void*, unsigned int, unsigned int, void const*)
Crashed: AVAudioSession Notify Thread
0  AudioToolbox                   0x1b434c10c InterruptionListener(void*, unsigned int, unsigned int, void const*) + 240
1  AudioToolbox                   0x1b43ec3c8 AudioSessionPropertyListeners::CallPropertyListenersImp(AudioSessionPropertyListeners const&, unsigned int, unsigned int, void const*) + 748
2  AudioToolbox                   0x1b44e20e4 AudioSessionPropertyListeners::CallPropertyListeners(unsigned int, unsigned int, void const*) + 220
3  AudioToolbox                   0x1b4524c44 HandleAudioSessionCFTypePropertyChangedMessage(unsigned int, unsigned int, void*, unsigned int) + 824
4  AudioToolbox                   0x1b45239f4 ProcessDeferredMessage(unsigned int, __CFData const*, unsigned int, unsigned int) + 568
5  AudioToolbox                   0x1b45234c8 ASCallbackReceiver_AudioSessionPingMessage + 588
6  AudioToolbox                   0x1b43dcea4 _XAudioSessionPingMessage + 52
7  AudioToolbox                   0x1b47241a8 mshMIGPerform + 232
8  CoreFoundation                 0x1b039d594 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
9  CoreFoundation                 0x1b039cce0 __CFRunLoopDoSource1 + 440
10 CoreFoundation                 0x1b0397b04 __CFRunLoopRun + 2096
11 CoreFoundation                 0x1b0396fb4 CFRunLoopRunSpecific + 436
12 AVFAudio                       0x1b6309334 GenericRunLoopThread::Entry(void*) + 156
13 AVFAudio                       0x1b6333c60 CAPThread::Entry(CAPThread*) + 88
14 libsystem_pthread.dylib        0x1b00292c0 _pthread_body + 128
15 libsystem_pthread.dylib        0x1b0029220 _pthread_start + 44
16 libsystem_pthread.dylib        0x1b002ccdc thread_start + 4

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by a314266177** [comment]
Hope you can get effective help

**Comment by ericleich** [comment]
The plugin itself doesn't do anything with AVAudioSession. The underlying Google Mobile Ads SDK for iOS does some stuff with AVAudioSession but there are no GAD symbols in this trace to hint that this is even happening in the iOS SDK, or where to go off of. Unless there's new information, this is infeasible to fix.
