### ISSUE TITLE
Mobile Ads Unity Plugin v.3.0 Errors on iOS

### ISSUE THREAD

**Issue by Rhiojin** [googleads/googleads-mobile-unity#161]
I successfully built to android using the latest versions of PlayGames (0.9.3) and GoogleAds(3.0) however building for iOS give me the following errors:
![screenshot 2016-02-04 22 01 49](https://cloud.githubusercontent.com/assets/9193120/12829631/76e825d8-cb8b-11e5-970b-f643f741514d.png)

Apparently a typo but upon doing the suggested fix the following errors occur:
![screenshot 2016-02-04 22 09 26](https://cloud.githubusercontent.com/assets/9193120/12829774/2aece4b0-cb8c-11e5-85d9-1f3c9565ed3e.png)

a couple more apparent typos but again, with the logical edits i get these errors: 
![screenshot 2016-02-04 22 15 20](https://cloud.githubusercontent.com/assets/9193120/12829938/e6f38128-cb8c-11e5-9934-a4413e017316.png)

I only have intermediate knowledge of objc so I'm unable to proceed from this point without some help

**Comment by rampara** [comment]
Are you using the CocoaPods xcworkspace generated by Unity? If not, is the Google Mobile Ads SDK present within your Xcode project?

**Comment by Rhiojin** [comment]
I wasn't using CocoaPods.
I was erroneously using version 7.0 of the SDK. I deleted it and added 7.6 and it builds and runs fine now.
Very Many Thanks.
