### ISSUE TITLE
App id not be saved v6.0.0

### ISSUE THREAD

**Issue by hoainam1593** [googleads/googleads-mobile-unity#1615]
* Unity version: all
  * Google Mobile Ads Unity plugin version: 6.0.0
  * Platform: all (iOS, Android, Unity Editor)
  * Platform OS version: all (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: n/a
  * Mediation ad networks used, and their versions: n/a

In newest version 6.0.0, when I edit app id in GoogleMobileAdsSettings, then reopen Unity, I discover that app id not be saved

**Comment by hoainam1593** [comment]
for those who waiting for an official solution, you can hardcode appid at Assets\GoogleMobileAds\Editor\GoogleMobileAdsSettings.cs

**Comment by mdobele** [comment]
I had the same issue, you can also just manually add your IDs to the GoogleMobileAdsSettings.assett file manually by opening it in a text editor.
\Assets\GoogleMobileAds\Resources\GoogleMobileAdsSettings.assett

**Comment by bab202** [comment]
I also got the same issue, the app ids become empty every time I quit Play mode. But after I try to click `Reset` button in Unity inspector of GoogleMobileAdsSettings scriptable object, it become normal again, data can now be persisted. I use Unity 2020.3.8.

**Comment by TheMeanFiddler** [comment]
If you tick/untick the Delay App Measurement checkbox it saves the settings, including the App IDs

**Comment by ericleich** [comment]
Just wanted to acknowledge that this is on our radar, but lower priority than a few other bugs such as https://github.com/googleads/googleads-mobile-unity/issues/1616 and this probably won't make it into the first patch release post 6.0.0 given the suggested workarounds above.

**Comment by aroman** [comment]
> If you tick/untick the Delay App Measurement checkbox it saves the settings, including the App IDs

this workaround worked for me.

**Comment by thsbrown** [comment]
Just chiming in that I had this issue as well with 6.0.1 and solved it by manually entering in the values via the .asset file

**Comment by CreaProjects** [comment]
Google SDK should be tested before release, this shouldn't happens and I found another issue that make the app crash even with blank projects.
Every big issue I have is with Google SDK, last time it was the Google Cardboard SDK, I've lost days of work making fixes for Google untested SDKs! Grrr

**Comment by TheGoodEvilBen** [comment]
For all who are interested in a proper solution:

1. Locate the file "GoogleMobileAdsSettingsEditor.cs" in your project
2. Exchange the old "OnInspectorGUI()" method with this following code (the code tag on this side is not working properly. Sorry):

public override void OnInspectorGUI()
        {
            EditorGUILayout.LabelField("Google Mobile Ads App ID", EditorStyles.boldLabel);
            EditorGUI.indentLevel++;
            EditorGUI.BeginChangeCheck();
            
            GoogleMobileAdsSettings.Instance.GoogleMobileAdsAndroidAppId =
                    EditorGUILayout.TextField("Android",
                            GoogleMobileAdsSettings.Instance.GoogleMobileAdsAndroidAppId);

            GoogleMobileAdsSettings.Instance.GoogleMobileAdsIOSAppId =
                    EditorGUILayout.TextField("iOS",
                            GoogleMobileAdsSettings.Instance.GoogleMobileAdsIOSAppId);

            EditorGUILayout.HelpBox(
                    "Google Mobile  Ads App ID will look similar to this sample ID: ca-app-pub-3940256099942544~3347511713",
                    MessageType.Info);

            EditorGUI.indentLevel--;
            EditorGUILayout.Separator();

            EditorGUILayout.LabelField("AdMob-specific settings", EditorStyles.boldLabel);
            EditorGUI.indentLevel++;


            GoogleMobileAdsSettings.Instance.DelayAppMeasurementInit =
                    EditorGUILayout.Toggle(new GUIContent("Delay app measurement"),
                    GoogleMobileAdsSettings.Instance.DelayAppMeasurementInit);

            if (GoogleMobileAdsSettings.Instance.DelayAppMeasurementInit) {
                EditorGUILayout.HelpBox(
                        "Delays app measurement until you explicitly initialize the Mobile Ads SDK or load an ad.",
                        MessageType.Info);
            }

            EditorGUI.indentLevel--;
            EditorGUILayout.Separator();

            if (EditorGUI.EndChangeCheck())
            {
                OnSettingsChanged();
            }
        }


Greetings Ben

**Comment by estellise-yukihime** [comment]
I'm having this error also on v6.0.1

**Comment by jaslanflorencio** [comment]
Have same issue com 6.1.0

Found to work-arounds.
1 - Tick / untick  "Delay App Measurement" checkbox, as our colleague says on previous comments or
2 - Edit manually \Assets\GoogleMobileAds\Resources\GoogleMobileAdsSettings.asset, and add your appID.

Both workarounds is working fine.

**Comment by JuanDavidPabon** [comment]
Solucionado escribiendo manualmente el ID en el archivo GoogleMobileAdsSettings de forma: 

[SerializeField]
private string adMobAndroidAppId = "ca-app-pub-123123123123123~123123123123";

El ID es ejemplo, recuerde buscar su ID en AdMob All Apps.

**Comment by aidinzolghadr** [comment]
As of 6.0.1 none of those work in Unity 2020.3.19. Any ideas?

**Comment by AQaddora** [comment]
Hello everyone, 
I had this problem, looked for quick fixes.. nothing works with **2020.X.X**
So I had to rewrite the editor script.. here is a new version that works perfectly replace everything in the file `Assets\GoogleMobileAds\Editor\GoogleMobileAdsSettingsEditor.cs` with the following:
```Cs
using UnityEditor;

namespace GoogleMobileAds.Editor
{
    [InitializeOnLoad]
    [CustomEditor(typeof(GoogleMobileAdsSettings))]
    public class GoogleMobileAdsSettingsEditor : UnityEditor.Editor
    {
        [MenuItem("Assets/Google Mobile Ads/Settings...")]
        public static void OpenInspector()
        {
            Selection.activeObject = GoogleMobileAdsSettings.Instance;
        }
        public override void OnInspectorGUI()
        {
            serializedObject.Update ();
            base.OnInspectorGUI ();
            if (serializedObject.hasModifiedProperties) {
                GoogleMobileAdsSettings.Instance.WriteSettingsToFile ();
                serializedObject.ApplyModifiedProperties ();
                EditorUtility.SetDirty ((GoogleMobileAdsSettings) target);
            }
        }
    }
}
```

**Comment by NVentimiglia** [comment]
Fixed in next release.
