### ISSUE TITLE
Google Mobile Ads Unity Plugin v6.0.0 And Vungle 3.5.1 XCode build error

### ISSUE THREAD

**Issue by crSudo** [googleads/googleads-mobile-unity#1617]
### [REQUIRED] Step 1: Describe your environment

* Unity version: 2018.4.27f1
* Google Mobile Ads Unity plugin version: 6.0.0
* Platform: iOS
* Mediation ad networks used, and their versions: VungleUnityAdapter-3.5.1

### [REQUIRED] Step 2: Describe the problem

After building with XCode, the following error is displayed.
 /Libraries/Plugins/iOS/VungleExtrasBuilder.h:7:9: 'GADUAdNetworkExtras.h' file not found

#### Steps to reproduce:
1. Launch Unity Editor
2. Import GoogleMobileAds-v6.0.0.unitypackage
3. [Unity Editor Assets> Google Mobile Ads> Settings] Set the AdMob app ID.
4. Import GoogleMobileAdsVungleMediation.unitypackage
5. Execute Unity Editor [Build Setting]-[Build].
6. Run ***. Xcworkspace.
7. Press the Play button.

```
// TODO(you): code here to reproduce the problem
```

**Comment by qbit86** [comment]
@JillSong 
The same:
```
In file included from /Users/buildserver/buildbot/slave/U2018_IOS/build/ios_build/Libraries/Plugins/iOS/VungleExtrasBuilder.m:3:
/Users/buildserver/buildbot/slave/U2018_IOS/build/ios_build/Libraries/Plugins/iOS/VungleExtrasBuilder.h:7:9: fatal error: 'GADUAdNetworkExtras.h' file not found
#import "GADUAdNetworkExtras.h"
        ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

@crSudo 
I've added GADUAdNetworkExtras.h from the previous version: GoogleMobileAds-v5.4.0.unitypackage

**Comment by nomibuilder** [comment]
Same issue please fix

**Comment by ahmadbilal7248** [comment]
Same issue, What we need to do

**Comment by IvyKun** [comment]
Same issue with 6.1.0 and Vungle 3.6.0. Using Unity 2019.4.21f.

Have to keep using 5.4.0 for now :(

**Comment by NVentimiglia** [comment]
Hi, 

We have fixed this issue in the latest release. Please try again.
