### ISSUE TITLE
Mac, building for Android: CommandInvokationFailure: Failed to re-package resources. See the Console for details.

### ISSUE THREAD

**Issue by dps999** [googleads/googleads-mobile-unity#162]
Hi, could you help me. I have this issue when i trying to build it for Android on my Mac. If i trying to make it from Windows it's fine. I have upated android SDK and latest google-play-services_lib in Plugins/Android folder.

Also i noticed it creates some files in Plugins/Android folders like appcompat-v7-23.1.1, play-services-ads-8.4.0...  Why thas is happening? 

Maybe those files should be deleted after succeful build? Thank you.

CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Users\Serg\AppData\Local\Android\android-sdk\build-tools\23.0.1\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:\Users\Serg\AppData\Local\Android\android-sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.chartboost.sdk.unity:com.facebook:com.facebook.android:com.google.android.gms:com.google.unity:com.google.android.gms.ads:com.google.android.gms:android.support.v4:com.unity3d.ads.android -S "C:\Users\Serg\Dropbox\Asset Store Projects\JellyGarden\JellyGarden new admob\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res" -S "C:\Users\Serg\Dropbox\Asset Store Projects\JellyGarden\JellyGarden new admob\Temp\StagingArea\android-libraries\facebook-android-sdk-4.8.2\res" -S "C:\Users\Serg\Dropbox\Asset Store Projects\JellyGarden\JellyGarden new admob\Temp\StagingArea\android-libraries\facebook-android-wrapper-release\res" -S "C:\Users\Serg\Dropbox\Asset Store Projects\JellyGarden\JellyGarden new admob\Temp\StagingArea\android-libraries\google-play-services_lib\res" -S "C:\Users\Serg\Dropbox\Asset Store Projects\JellyGarden\JellyGarden new admob\Temp\StagingArea\android-libraries\play-services-ads-8.4.0\res" -S "C:\Users\Serg\Dropbox\Asset Store Projects\JellyGarden\JellyGarden new admob\Temp\StagingArea\android-libraries\play-services-basement-8.4.0\res" -S "C:\Users\Serg\Dropbox\Asset Store Projects\JellyGarden\JellyGarden new admob\Temp\StagingArea\android-libraries\support-v4-23.1.1\res" -S "C:\Users\Serg\Dropbox\Asset Store Projects\JellyGarden\JellyGarden new admob\Temp\StagingArea\android-libraries\unityads\res"

stderr[
C:\Users\Serg\Dropbox\Asset Store Projects\JellyGarden\JellyGarden new admob\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_button_bar_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <android.support.v7.widget.ButtonBarLayout>
C:\Users\Serg\Dropbox\Asset Store Projects\JellyGarden\JellyGarden new admob\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_button_bar_material.xml: note: using v17 attributes; synthesizing resource com.aaa.jellygarden:layout/abc_alert_dialog_button_bar_material for configuration v17.
C:\Users\Serg\Dropbox\Asset Store Projects\JellyGarden\JellyGarden new admob\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_material.xml:48: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <android.support.v7.widget.DialogTitle>
C:\Users\Serg\Dropbox\Asset Store Projects\JellyGarden\JellyGarden new admob\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_material.xml: note: using v17 attributes; synthesizing resource com.aaa.jellygarden:layout/abc_alert_dialog_material for configuration v17.

**Comment by rampara** [comment]
The Google Play Services library project no longer has to be included within your Unity project. Instead, the necessary Google Play services client libraries are automatically copied into Unity projects at build time. This functionality is provided via the Unity [JarResolver](https://github.com/googlesamples/unity-jar-resolver) library. 

- Ram

**Comment by dps999** [comment]
Thank you. Where can i read update manual from previous version?

**Comment by rampara** [comment]
You can find a blog post on the latest release on our [developer blog](http://googleadsdeveloper.blogspot.com/2016/02/google-mobile-ads-unity-plugin-v300.html). Our [Game Developer's Guide](https://developers.google.com/admob/android/games#unity) has also been updated to reflect the changes in the latest release.

**Comment by dps999** [comment]
Thank you. I created new empty project and import the plugins. But i receive almost the same error.

CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Users\Serg\AppData\Local\Android\android-sdk\build-tools\23.0.1\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:\Users\Serg\AppData\Local\Android\android-sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages com.google.unity

stderr[
AndroidManifest.xml:16: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.IAPTheme').

AndroidManifest.xml:18: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

Could you help me? Thank you!

**Comment by rampara** [comment]
Does your Unity project include Google Play Service client libraries (AAR files) under the 'Assets/Plugins/Android' directory?

**Comment by dps999** [comment]
Yes it was copied there.
![image](https://cloud.githubusercontent.com/assets/1697478/13000315/f0c9c8a0-d169-11e5-8d72-a1c888d11026.png)

**Comment by rampara** [comment]
It looks like you're still including the Google Play Services library project. You no longer should be.

**Comment by resetme** [comment]
Did anyone had a solution for this?

deleting Google Play Services library project give me more errors than before.

**Comment by dps999** [comment]
Thank you @rampara ! Some other plugins copied that Google Play Services again. I deleted it again and looks like it works fine.

**Comment by resetme** [comment]
go it to work using an older version with no jar resolver

**Comment by rampara** [comment]
@dps999 Glad you were able to get it working. @resetme can you provide more information on the type of errors you were receiving?

**Comment by resetme** [comment]
I fix it with the older version.
The error was CommandInvokationFailure: re-package.
Its because chartboost need to use the google play service and everytime i press setup chartboost in unity menu  it creates it own google play services, i also had google analytcis problems with some $command, $command1 inside the jar files i had to delete.

anyways, the project is very stable now and i dont want to brake it again.  Later i create a new project with chartboost and this plugins to try to solve the problem.

thank you!

**Comment by rampara** [comment]
Sounds good.
