### ISSUE TITLE
Can't build with support-v4-compat.jar and support-v4-utils.jar

### ISSUE THREAD

**Issue by GITHUB243884919** [googleads/googleads-mobile-unity#1621]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: _____Unity2018.4.10 and Unity2018.4.24
  * Google Mobile Ads Unity plugin version: _____6.0.0
  * Platform: Android, Unity Editor_____ (iOS, Android, Unity Editor)
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem
My project already exist support-v4-compat.jar and support-v4-utils.jar for other functions。
When I import admob and build it , It shows a lot of error about Duplicate class ： 
Gradle build failed. 
。。。
Execution failed for task ':checkReleaseDuplicateClasses'.
。。。
java.lang.RuntimeException: Duplicate class android.support.v4.os.ResultReceiver
。。。
 
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
CommandInvokationFailure: Gradle build failed. 
E:\Program Files\Unity2018.4.24f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\OpenJDK\Windows\bin\java.exe -classpath "E:\Program Files\Unity2018.4.24f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-5.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkReleaseDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class android.support.v4.os.ResultReceiver found in modules classes.jar (androidx.core:core:1.2.0) and jetified-support-v4-compat.jar (support-v4-compat.jar)
  Duplicate class android.support.v4.os.ResultReceiver$1 found in modules classes.jar (androidx.core:core:1.2.0) and jetified-support-v4-compat.jar (support-v4-compat.jar)
  Duplicate class android.support.v4.os.ResultReceiver$MyResultReceiver found in modules classes.jar (androidx.core:core:1.2.0) and jetified-support-v4-compat.jar (support-v4-compat.jar)
  Duplicate class android.support.v4.os.ResultReceiver$MyRunnable found in modules classes.jar (androidx.core:core:1.2.0) and jetified-support-v4-compat.jar (support-v4-compat.jar)
  Duplicate class androidx.collection.ArrayMap found in modules collection-1.0.0.jar (androidx.collection:collection:1.0.0) and jetified-support-v4-compat.jar (support-v4-compat.jar)
  Duplicate class androidx.collection.ArrayMap$1 found in modules collection-1.0.0.jar (androidx.collection:collection:1.0.0) and jetified-support-v4-compat.jar (support-v4-compat.jar)
  Duplicate class androidx.collection.ArraySet found in modules collection-1.0.0.jar (androidx.collection:collection:1.0.0) and jetified-support-v4-compat.jar (support-v4-compat.jar)
  Duplicate class androidx.collection.ArraySet$1 found in modules collection-1.0.0.jar (androidx.collection:collection:1.0.0) and jetified-support-v4-compat.jar (support-v4-compat.jar)
  Duplicate class androidx.collection.CircularArray found in modules collection-1.0.0.jar (androidx.collection:collection:1.0.0) and jetified-support-v4-compat.jar (support-v4-compat.jar)
  Duplicate class androidx.collection.CircularIntArray found in modules collection-1.0.0.jar (androidx.collection:collection:1.0.0) and jetified-support-v4-compat.jar (support-v4-compat.jar)
  Duplicate class androidx.collection.ContainerHelpers found in modules collection-1.0.0.jar (androidx.collection:collection:1.0.0) and jetified-support-v4-compat.jar (support-v4-compat.jar)
  Duplicate class androidx.collection.LongSparseArray found in modules collection-1.0.0.jar (androidx.collection:collection:1.0.0) and jetified-support-v4-compat.jar (support-v4-compat.jar)
.....

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
