### ISSUE TITLE
Server side validation no longer includes custom data nor user id in 6.0.0

### ISSUE THREAD

**Issue by wisestump** [googleads/googleads-mobile-unity#1623]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2018.4.32f1
  * Google Mobile Ads Unity plugin version: 6.0.0
  * Platform: Android
  * Platform OS version: Android 10
  * Any specific devices issue occurs on: occurs on different devices
  * Mediation ad networks used, and their versions: without mediations

#### Steps to reproduce:

1. Clone [HelloWorld sample](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld)
2. Setup AppID and Rewarded Ad adunit
3. Modify GoogleAdMobController.RequestAndLoadRewardedAd() method in order to implement sending user id for SSV.
4. Build and run project on android device
5. Request rewarded ad
6. Wait for the ad to load
7. Watch ad 
8. Receive a callback from admob server, containing no user id or custom data
#### Relevant Code:

```csharp
// create new rewarded ad instance
rewardedAd = new RewardedAd(adUnitId);

string uid = "fc45fb514scf6e9b:768a543d05b7f3bf0c03fe2e63f25464";
var options = new ServerSideVerificationOptions.Builder()
    .SetCustomData(uid.Replace(":", "%3A"))
    .SetUserId(uid.Replace(":", "%3A"))
    .Build();
rewardedAd.SetServerSideVerificationOptions(options);
// ...
rewardedAd.LoadAd(CreateAdRequest());
```
Client-side logs from Ads channel report ad requests that also contain no `userid` or `customdata` fields.

**Comment by wisestump** [comment]
The issue was that after the 6.0.0 update, `rewardedAd.SetServerSideVerificationOptions(options);` should be called after the rewarded ad has been loaded, otherwise you get a log "This should in theory never happen. If it does, please contact the plugin owners." ([this line](https://github.com/googleads/googleads-mobile-unity/blob/f733f4362c8add151091ec44e1bb6d30b4e8f2b1/source/android-library/app/src/main/java/com/google/unity/ads/UnityRewardedInterstitialAd.java#L234)).

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
