### ISSUE TITLE
Admob App Open Ads Package

### ISSUE THREAD

**Issue by idzdigital** [googleads/googleads-mobile-unity#1626]
Admob has recently launched App Open Ads. [App Open Ads Admob](https://developers.google.com/admob/android/app-open-ads)
How do we add App Open Ads to our games using this package?

**Comment by JillSong** [comment]
It's not supported in the Unity plugin yet. We'll make it available soon. Stay tuned, thanks!

**Comment by idzdigital** [comment]
Hi Jill,
Can you please share a rough estimate of when it will be available?

> It's not supported in the Unity plugin yet. We'll make it available soon. Stay tuned, thanks!
