### ISSUE TITLE
Ver 3.0.0 XCode build issue

### ISSUE THREAD

**Issue by AndersonDev** [googleads/googleads-mobile-unity#163]
Hi, when I build unity project in XCode, I have those issue:

![2016-02-07 19 21 22](https://cloud.githubusercontent.com/assets/6890368/12873871/272da372-cdd1-11e5-8d1c-27f3af27ba20.png)

And I will be very pleasure if you make more compact plugin folder structure in future. When I import plugin I have 2!! folders in Assets and 2 folder in Plugins.

**Comment by rampara** [comment]
Are you using the CocoaPods xcworkspace generated by the plugin? If not, have you included the Google Mobile Ads SDK in your Xcode project?

- Ram

**Comment by rampara** [comment]
The latest release of the plugin should fix issues with Unity Cloud Build. However, you will have to modify the plugin to disable bitcode for the Xcode generated project. This can be done by adding the following code snippet to line 61 of 'Postprocessor.cs':

project.SetBuildProperty(target, "ENABLE_BITCODE", "NO");

Once the Google Mobile Ads iOS SDK is updated to support bitcode (which should be very soon), this change will no longer be required.
