### ISSUE TITLE
Bug: app id disappears on every restart of editor after admob update!

### ISSUE THREAD

**Issue by gputhread** [googleads/googleads-mobile-unity#1635]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2018.3.10
  * Google Mobile Ads Unity plugin version: v6.0.0
  * Platform: Editor (iOS, Android, Unity Editor)
  * Platform OS version: Win10 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
update admob to v6.0.0 in unity 2018.3.10 restart editor the app id from admob console disappears causes ads to stop working.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by raft75** [comment]
Same here on Unity 2019.2.21f1

**Comment by ali-pjx** [comment]
Same here on Unity 2020.3.2f1 (LTS)

**Comment by gputhread** [comment]
Delay App Measurement was fix!
