### ISSUE TITLE
iOS UnityEditor Error on Windows with iOS support not installed

### ISSUE THREAD

**Issue by Givemeyourgits** [googleads/googleads-mobile-unity#164]
iOS doesn't work on Window, so it is very likely you won't select that component.  When using this asset, it throws an error about UnityEditor doesn't have iOS support.

It would be nice to be able to use this without requiring needless iOS support on Windows platform.

**Comment by rampara** [comment]
Can you change the compiler directive on lines 7 and 51 in Postprocessor.cs from "#if UNITY_5" to "#if (UNITY_5 && UNITY_IOS)". I will be committing a change to the repo soon to include this change.

Ram

**Comment by rampara** [comment]
The plugin has been updated to include the fix mentioned above.
