### ISSUE TITLE
Google Admob iOS Sdk 6.0.0 "not found for architecture arm64" error

### ISSUE THREAD

**Issue by tolgamacpro** [googleads/googleads-mobile-unity#1645]
* Unity version: 2020.3.7f1
  * Google Mobile Ads Unity plugin version: 6.0.0
  * Platform: iOS 
  * Platform OS version: iOS 12 
  * Xcode Version 12.5
  
   Xcode Error:
  ```
Undefined symbols for architecture arm64:
  "_GADURequestInterstitial", referenced from:
      _Externs_GADURequestInterstitial_m77D58C1021B0E1A9320F3326857B18C58380315E in GoogleMobileAds.iOS.o
     (maybe you meant: _Externs_GADURequestInterstitial_m77D58C1021B0E1A9320F3326857B18C58380315E)
ld: symbol(s) not found for architecture arm64
```
Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '7.11.0'
  pod 'Firebase/Core', '7.11.0'
  pod 'Google-Mobile-Ads-SDK', '~> 8.2'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
```

I started facing this issue after installing firebase plugin in game and installing admob latest version

How can i solve this problem?

**Comment by juandapark** [comment]
having the same issue here

**Comment by AltAirGame** [comment]
Having the Same issue...

**Comment by tolgamacpro** [comment]
I solved my problem using version 5.4.0 for ios
 and 6.0.0 for android

**Comment by ali-pjx** [comment]
> I solved my problem using version 5.4.0 for ios
> and 6.0.0 for android

I have the same error and even mediation test suit is causing same problem:

XCODE log:

`ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/admin/Desktop/MergePlane_Xcode/MP-1156-MS/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "_kGADAdLoaderAdTypeUnifiedNative", referenced from:
      -[GMTSNativeAdLoader initWithAdUnitId:rootViewController:] in GoogleMobileAdsMediationTestSuite(GMTSNativeAdLoader.o)
  "_OBJC_CLASS_$_DFPInterstitial", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o)
  "_OBJC_CLASS_$_DFPRequest", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o)
  "_OBJC_CLASS_$_DFPBannerView", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o)
  "_OBJC_CLASS_$_GADRewardBasedVideoAd", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSAdSourceCollectionViewController.o)
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSRewardedBasedVideoAdLoader.o)
  "_OBJC_CLASS_$_GADRequestError", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSMediationHelper.o)
  "_OBJC_CLASS_$_GADUnifiedNativeAd", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSAdSourceCollectionViewController.o)
  "_OBJC_CLASS_$_GADInterstitial", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSAdSourceCollectionViewController.o)
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o)
     (maybe you meant: _OBJC_CLASS_$_GADInterstitialAd)
  "_GADURequestInterstitial", referenced from:
      _Externs_GADURequestInterstitial_m77D58C1021B0E1A9320F3326857B18C58380315E in GoogleMobileAds.iOS.o
     (maybe you meant: _Externs_GADURequestInterstitial_m77D58C1021B0E1A9320F3326857B18C58380315E)`

**Comment by tolgamacpro** [comment]
> > I solved my problem using version 5.4.0 for ios
> > and 6.0.0 for android
> 
> I have the same error and even mediation test suit is causing same problem:
> 
> XCODE log:
> 
> `ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/admin/Desktop/MergePlane_Xcode/MP-1156-MS/Libraries/libiPhone-lib.a(unwind_test_arm64.o) Undefined symbols for architecture arm64: "_kGADAdLoaderAdTypeUnifiedNative", referenced from: -[GMTSNativeAdLoader initWithAdUnitId:rootViewController:] in GoogleMobileAdsMediationTestSuite(GMTSNativeAdLoader.o) "_OBJC_CLASS_$_DFPInterstitial", referenced from: objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o) "_OBJC_CLASS_$_DFPRequest", referenced from: objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o) "_OBJC_CLASS_$_DFPBannerView", referenced from: objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o) "_OBJC_CLASS_$_GADRewardBasedVideoAd", referenced from: objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSAdSourceCollectionViewController.o) objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSRewardedBasedVideoAdLoader.o) "_OBJC_CLASS_$_GADRequestError", referenced from: objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSMediationHelper.o) "_OBJC_CLASS_$_GADUnifiedNativeAd", referenced from: objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSAdSourceCollectionViewController.o) "_OBJC_CLASS_$_GADInterstitial", referenced from: objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSAdSourceCollectionViewController.o) objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o) (maybe you meant: _OBJC_CLASS_$_GADInterstitialAd) "_GADURequestInterstitial", referenced from: _Externs_GADURequestInterstitial_m77D58C1021B0E1A9320F3326857B18C58380315E in GoogleMobileAds.iOS.o (maybe you meant: _Externs_GADURequestInterstitial_m77D58C1021B0E1A9320F3326857B18C58380315E)`

Have you tried version 5.4.0 for ios?

**Comment by ali-pjx** [comment]
> > > I solved my problem using version 5.4.0 for ios
> > > and 6.0.0 for android
> > 
> > 
> > I have the same error and even mediation test suit is causing same problem:
> > XCODE log:
> > `ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/admin/Desktop/MergePlane_Xcode/MP-1156-MS/Libraries/libiPhone-lib.a(unwind_test_arm64.o) Undefined symbols for architecture arm64: "_kGADAdLoaderAdTypeUnifiedNative", referenced from: -[GMTSNativeAdLoader initWithAdUnitId:rootViewController:] in GoogleMobileAdsMediationTestSuite(GMTSNativeAdLoader.o) "_OBJC_CLASS_$_DFPInterstitial", referenced from: objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o) "_OBJC_CLASS_$_DFPRequest", referenced from: objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o) "_OBJC_CLASS_$_DFPBannerView", referenced from: objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o) "_OBJC_CLASS_$_GADRewardBasedVideoAd", referenced from: objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSAdSourceCollectionViewController.o) objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSRewardedBasedVideoAdLoader.o) "_OBJC_CLASS_$_GADRequestError", referenced from: objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSMediationHelper.o) "_OBJC_CLASS_$_GADUnifiedNativeAd", referenced from: objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSAdSourceCollectionViewController.o) "_OBJC_CLASS_$_GADInterstitial", referenced from: objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSAdSourceCollectionViewController.o) objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o) (maybe you meant: _OBJC_CLASS_$_GADInterstitialAd) "_GADURequestInterstitial", referenced from: _Externs_GADURequestInterstitial_m77D58C1021B0E1A9320F3326857B18C58380315E in GoogleMobileAds.iOS.o (maybe you meant: _Externs_GADURequestInterstitial_m77D58C1021B0E1A9320F3326857B18C58380315E)`
> 
> Have you tried version 5.4.0 for ios?

Yes, it works with 5.4.0. But using older version is obviously not a solution. Its been over a month since admob have published version 6.0.0 . And while we are using version 6 on android games, its a real pain to keep its iOS version at 5.4.0 considering our git repository and script differences between these two versions.

**Comment by saevioapps** [comment]
Same issue here. Can not build for IOS. 
Unity 2019.4.26, Google Admob iOS Sdk 6.0.0

**Comment by AnthonyEd** [comment]
``I was able to get around this by commenting out line 7897 in Classes\Native\GoogleMobileAds.iOS.cpp in XCode:

`reinterpret_cast<PInvokeFunc>(GADURequestInterstitial)(___interstitial0, ___request1);`


Note that this code looks auto-generated, so it may not appear consistently on line 7897.

**Comment by ali-pjx** [comment]
> I was able to get around this by commenting out line 7897 in Classes\Native\GoogleMobileAds.iOS.cpp in XCode:
> 
> `reinterpret_cast<PInvokeFunc>(GADURequestInterstitial)(___interstitial0, ___request1);`
> 
> Note that this code looks auto-generated, so it may not appear consistently on line 7897.

Didn't you encounter any problems ever since?

**Comment by Jur-Wind** [comment]
Same issue here. Why is this still not fixed?

**Comment by bab202** [comment]
> I was able to get around this by commenting out line 7897 in Classes\Native\GoogleMobileAds.iOS.cpp in XCode:
> 
> `reinterpret_cast<PInvokeFunc>(GADURequestInterstitial)(___interstitial0, ___request1);`
> 
> Note that this code looks auto-generated, so it may not appear consistently on line 7897.

This workaround works for me, no need to downgrade the SDK for iOS and I see no problems yet.

**Comment by ericleich** [comment]
https://github.com/googleads/googleads-mobile-unity/commit/cafefba55910fb95de3a18614f6f5c58f1c8e4ec is in version 6.0.1 which should fix the original issue reported.

**Comment by xebudda** [comment]
> [cafefba](https://github.com/googleads/googleads-mobile-unity/commit/cafefba55910fb95de3a18614f6f5c58f1c8e4ec) is in version 6.0.1 which should fix the original issue reported.

I am having the same issue with 6.01 for bannerview

**Comment by mnplays** [comment]
same issue here in 6.0.1

**Comment by rivax95** [comment]
![Uploading Captura de pantalla 2021-06-28 a las 11.35.55.png…]()
same here

**Comment by Zamaroht** [comment]
I get a similar error when trying to build using Unity Cloud Build:

```
19635: ▸ ❌;  Undefined symbols for architecture arm64
19636: ▸ > Symbol: _GADURewardedInterstitialAdGetRewardAmount
19637: ▸ > Referenced from: _Externs_GADURewardedInterstitialAdGetRewardAmount_m6546573294B2907A4ECB65887319D8BE71EC2210 in GoogleMobileAds.iOS.o
19638: ▸ ❌;  ld: symbol(s) not found for architecture arm64
19639: ▸ ❌;  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Northwind877** [comment]
same issue here in 6.0.1

**Comment by Tanek81** [comment]
Having the same issue here with both 6.0.2 and 6.1.0.
Any news on this?

**Comment by newbision** [comment]
Mac : macOS Monterey
Unity version: 2020.3.21f1
Xcode : 13.1

External Dependency Manager: [1.2.167]
Google Analytics: [8.6.1]
Firebase Cloud Messaging: [8.6.1]
Google Mobile Ads for Unity: [6.1.2]
GoogleMobileAdsMediationTestSuite

I exported Xcode project and tried to build it. But I am facing the same issue. It worked well before importing GoogleMobileAdsMediationTestSuite.

`ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Volumes/WORK/Work/SilverStar/iOS/Unity/PoketShogi_iOS/2/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "_kGADAdLoaderAdTypeUnifiedNative", referenced from:
      -[GMTSNativeAdLoader initWithAdUnitId:rootViewController:] in GoogleMobileAdsMediationTestSuite(GMTSNativeAdLoader.o)
  "_OBJC_CLASS_$_DFPInterstitial", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o)
  "_OBJC_CLASS_$_DFPRequest", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o)
  "_OBJC_CLASS_$_DFPBannerView", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o)
  "_OBJC_CLASS_$_GADRewardBasedVideoAd", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSAdSourceCollectionViewController.o)
  "_OBJC_CLASS_$_GADInterstitial", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSAdSourceCollectionViewController.o)
     (maybe you meant: _OBJC_CLASS_$_GADInterstitialAd)
  "_OBJC_CLASS_$_GADRequestError", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSMediationHelper.o)
  "_OBJC_CLASS_$_GADUnifiedNativeAd", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSAdSourceCollectionViewController.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by ali-pjx** [comment]
@newbision There is a work around that might help you, apparently  admob is working on ad inspector and I think they are not developing mediation test suite anymore, however to use it with google mobile ads versions higher than 6 you should get the newest version of mediation test suite is 2.0.0.
To do so, in the Assets/GoogleMobileAdsMediationTestSuite/Editor folder, find the file specifying the package dependencies! Its something called  GoogleMobileAdsMediationTestSuiteDependencies
After opening this file change the versions to 2.0.0.
I wish it helps
