### ISSUE TITLE
Banner not show

### ISSUE THREAD

**Issue by dtamas80** [googleads/googleads-mobile-unity#165]
Hi there,

I have a problem with the new version of admob and I can't find any solution.
A tried the test project (helloword) and the code from google developers page but the banners don't show up at all on my phone.
The project build without error, I use updated unity, sdk and I setup adUnitId to this: ca-app-pub-3940256099942544/1033173712

Can you help me what should I do next?
Thank you.

Tamás

**Comment by rampara** [comment]
Are you seeing any error messages in logcat under the Ads tag?

**Comment by dtamas80** [comment]
Where can I find it?

**Comment by rampara** [comment]
Follow the instructions on the [Android developer docs](http://developer.android.com/tools/help/adb.html) on how to use adb debugging. When you run the adb devices command you should see your device listed. Once your device is listed, run the following command:

adb logcat Ads:* *:S

Whenever you hide or show a banner or interstitial you should see a corresponding output in logcat.

**Comment by dtamas80** [comment]
For the debugging, should I connect my phone to unity via usb?

**Comment by rampara** [comment]
Adb is a command line tool independent to Unity. It will require your android device to be connected to the machine you will be running adb from.

**Comment by dtamas80** [comment]
I connected my phone, start the logcat, run the apk on the phone and there is the result.
Nothing happend for this command: adb logcat Ads:* *:S, but I tried to save the whole log

[3.txt](https://github.com/googleads/googleads-mobile-unity/files/123833/3.txt)

**Comment by rampara** [comment]
Is 'unity-plugin-library.jar' present within the 'Assets/Plugins/Android/GoogleMobileAdsPlugin/libs' directory of your Unity project?

**Comment by dtamas80** [comment]
Yes, it is present.

**Comment by rampara** [comment]
Can you provide a link to a Unity project where I can replicate this issue? It would make debugging easier.

**Comment by dtamas80** [comment]
https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld

**Comment by rampara** [comment]
Using the sample project and the latest Google Mobile Ads Unity plugin I'm able to request and display ads without issue. Can you upload and link your build of the project that is having this problem.

**Comment by dtamas80** [comment]
Please find here:
[3.zip](https://github.com/googleads/googleads-mobile-unity/files/125524/3.zip)

**Comment by rampara** [comment]
The Unity project would be more helpful for debugging over an APK.

**Comment by dtamas80** [comment]
Of course...

[adstest.zip](https://github.com/googleads/googleads-mobile-unity/files/125630/adstest.zip)

**Comment by rampara** [comment]
The project you linked is missing the 'project.properties' file from the 'Assets/Plugins/Android/GoogleMobileAdsPlugin/' directory. Adding this file back will result in the 'unity-plugin-library.jar' being included in the APK Unity produces. This should fix the issue you're seeing.

**Comment by dtamas80** [comment]
Thank you very much for your help. Finally it's working.

**Comment by rampara** [comment]
Glad you were able to get it working.
