### ISSUE TITLE
OnAdOpening is not called for a rewarded video ad until the ad is *closed*

### ISSUE THREAD

**Issue by aroman** [googleads/googleads-mobile-unity#1657]
### Describe your environment

  * Unity version: 2020.3.9f1
  * Google Mobile Ads Unity plugin version: 6.0.0
  * Platform: iOS and Android
  * Platform OS version: Android 10 and iOS 14
  * Any specific devices issue occurs on: any
  * Mediation ad networks used, and their versions: none

### Describe the problem

`OnAdOpening` is a very useful event — the documentation states it's a good time to e.g. pause background music just before the ad is shown to users. I want to do that in my app. However, I can't, because `OnAdOpening` is not called until after the ad is closed by the user. This is due to the fact that the `OnAdOpening` event is not called on the Main Thread, which means that no Unity-facing code (e.g. code to pause background music as the docs suggest) can be run directly in the event handler.

The solution offered to this by the documentation is to utilize `MobileAdsEventExecutor.ExecuteInUpdate()`. This defers execution until the next `Update()` loop, however, because the MobileAds SDK pauses the Unity player immediately when showing the ad, in practice, the next `Update()` call will not occur until after the ad closes, when the Unity player is unpaused. **This makes it impossible to handle the OnAdOpening event until after the ad is closed.**

This issue would be fixed by simply deferring the showing of the ad until one `Update()` frame after `rewardedAd.Show()` is called. However, this is all native code, so it's not possible to work around this in C#.

#### Steps to reproduce:

This is easily reproducible with the HelloWorld sample code provided in this repo. I've just added logging to point out the issue (below).

#### Relevant Code:

```cs
rewardedAd.OnAdOpening += OnAdOpening;
...
    private void OnAdOpening(object sender, EventArgs args)
    {
        Debug.Log("Good: this is called immediately when the ad is shown. " +
                  "Bad: this doesn't run on the main thread.");

        MobileAdsEventExecutor.ExecuteInUpdate(() =>
        {
            // DOES NOT EXECUTE UNTIL AD IS CLOSED OR FAILS TO SHOW
            Debug.Log("Good: this is called on the main thread. " +
                      "Bad: this doesn't run until after the ad is shown.");

        });
    }
```

**Comment by NVentimiglia** [comment]
Feature request is to fire an event before showing of an advertisement.

**Comment by aroman** [comment]
@NVentimiglia Nicholas, can you clarify whether this issue has been fixed? You labelled it a feature request and then immediately closed it.

I think you perhaps misunderstood the issue -- the feature, `OnAdOpening` already exists. However, it doesn't work as expected because the main thread is blocked by the ad itself, so the event won't be raised until after the ad is closed. This bug is easy to reproduce, as the sample ad prefab doesn't have this issue (because it doesn't block the main thread), so the event is called just before the ad is shown, as expected. However real mobile ads, the event is only raised after the ad is dismissed.
