### ISSUE TITLE
Ver 3.0.0 XCode build issue (2)

### ISSUE THREAD

**Issue by AndersonDev** [googleads/googleads-mobile-unity#166]
Sory for dublicate, https://github.com/googleads/googleads-mobile-unity/issues/163 . But I can't post reply there due to:
![2016-02-07 19 21 22](http://i.piccy.info/i9/10d1250e35d230592d5f2e092baf49d3/1455031549/2159/1001686/Er.png)

I am using Unity Cloud Build which not support CocoaPods. For me is wery slow to build with XCode(

**Comment by rampara** [comment]
The latest release of the plugin should fix issues with Unity Cloud Build. However, you will have to modify the plugin to disable bitcode for the Xcode generated project. This can be done by adding the following code snippet to line 61 of 'Postprocessor.cs': 

project.SetBuildProperty(target, "ENABLE_BITCODE", "NO");

Once the Google Mobile Ads iOS SDK is updated to support bitcode (which should be very soon), this change will no longer be required.
