### ISSUE TITLE
v6.0 Xcode Build Failed.. Oh My God!

### ISSUE THREAD

**Issue by J830930** [googleads/googleads-mobile-unity#1661]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2o2o.3.12f1
  * Google Mobile Ads Unity plugin version: v6.0.0
  * Platform: iOS(iOS, Android, Unity Editor)
  * Platform OS version: iOS11 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem

After updating to 'Google Mobile Ads SDK v6.0' and 'Firebase Unity SDK 8.0.0', 
Android builds work well, but the following error occurs when building iOS: Please solve it.
Please See My ScreenShot >> 

<img width="1552" alt="screenshot" src="https://user-images.githubusercontent.com/86246725/122782626-d6556400-d2eb-11eb-985f-f5bb36d46e36.png">

**Comment by ImanTanumihardja** [comment]
I have a similar issue.

**Comment by J830930** [comment]
Hello im sad tt

나의 iPhone에서 보냄

**Comment by mnplays** [comment]
same here. any solution?

**Comment by mnplays** [comment]
@J830930 혹시 한국인 맞으신가요? 저도 똑같은 문제를 겪고 있었는데 지금 해결이 되어서 제가 해결한 방법을 공유해 드릴까 합니다.
기존 Google Mobile Ads Unity SDK 5.x버전에서는 Assets/Plugins/iOS/ 폴더 안에 .m, .h 파일들이 다수 있었던 것이 6.0으로 올라오면서 파일들이 다 사라졌더라구요(ex. GADUAdLoader.h, GADUAdLoader.m, ... GADUxxxx.h, .m 파일들)

그냥 신규버전 SDK import만 하면 해당 파일들이 지워지지 않은 채로 남아 있습니다. 그러면 저런 에러가 나는 것 같구요, 해당 파일들을 모두 지우고 다시 빌드해보니 해당 에러는 나타나지 않았습니다.(지금은 또 다른 에러가 나긴 했습니다만..)

해당 폴더 안에 있는 unity-plugin-library.a 파일은 v6.0.0에서 새로 추가된 파일이니 지우면 안됩니다.

혹시 저처럼 기존 버전에서 업데이트를 하다가 생긴 문제라면 비슷한 케이스일 수도 있어서 리플 남겨 놓습니다.

도움이 되셨다면 좋겠네요.

**Comment by J830930** [comment]
와 ㅋㅋㅋ 방갑습니다!!!!!!감사합니다. 고민이 많았는데한번 해보고 연락드리겠습니다.와 정말 반갑습니다!! 어떤 게임 만드셨나요??!  Windows 10용 메일에서 보냄 보낸 사람: mnplays보낸 날짜: 2021년 6월 24일 목요일 오후 3:05제목: Re: [googleads/googleads-mobile-unity] v6.0 Xcode Build Failed.. Oh My God! (#1661) @J830930 혹시 한국인 맞으신가요? 저도 똑같은 문제를 겪고 있었는데 지금 해결이 되어서 제가 해결한 방법을 공유해 드릴까 합니다.기존 Google Mobile Ads Unity SDK 5.x버전에서는 Assets/Plugins/iOS/ 폴더 안에 .m, .h 파일들이 다수 있었던 것이 6.0으로 올라오면서 파일들이 다 사라졌더라구요(ex. GADUAdLoader.h, GADUAdLoader.m, ... GADUxxxx.h, .m 파일들)그냥 신규버전 SDK import만 하면 해당 파일들이 지워지지 않은 채로 남아 있습니다. 그러면 저런 에러가 나는 것 같구요, 해당 파일들을 모두 지우고 다시 빌드해보니 해당 에러는 나타나지 않았습니다.(지금은 또 다른 에러가 나긴 했습니다만..)해당 폴더 안에 있는 unity-plugin-library.a 파일은 v6.0.0에서 새로 추가된 파일이니 지우면 안됩니다.혹시 저처럼 기존 버전에서 업데이트를 하다가 생긴 문제라면 비슷한 케이스일 수도 있어서 리플 남겨 놓습니다.도움이 되셨다면 좋겠네요.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by pedromgdo** [comment]
For anyone having the same issue, the solution described by @mnplays worked for me, the English version is the following:

- Delete plugins/iOS folder (check first if there are any other plugins not related to google ads you might not want to delete)
- Re-import the latest unity package release

You should now only have one file on plugins/iOS.

**Comment by Archi97** [comment]
@pedromgdo is solves the problem with GADU files. 
but the latest version of the sdk doesnt work on empty project  #1677

**Comment by bloto** [comment]
@Archi97 It solves only compilation issue for me. Linker is still not happy, it cannot find these functions in the library. I am on 6.0.1. It doesn't find these in neither 8.2 or 8.7 of Google-Mobile-Ads-SDK.

ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/tomaszzablocki/Documents/unity/TerrainStreamer/iosBuild2/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "_GADUSetNativeCustomTemplateAdUnityClient", referenced from:
      _Externs_GADUSetNativeCustomTemplateAdUnityClient_mC9EE8442D687871FBAFE03C76F4EC9FF2A044354 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUSetNativeCustomTemplateAdUnityClient_mC9EE8442D687871FBAFE03C76F4EC9FF2A044354)
  "_GADUNativeCustomTemplateAdPerformClickOnAssetWithKey", referenced from:
      _Externs_GADUNativeCustomTemplateAdPerformClickOnAssetWithKey_m351397E554DD8BDDA0A0DD7C471B7BFF853903BE in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUNativeCustomTemplateAdPerformClickOnAssetWithKey_m351397E554DD8BDDA0A0DD7C471B7BFF853903BE)
  "_GADUNativeCustomTemplateAdImageAsBytesForKey", referenced from:
      _Externs_GADUNativeCustomTemplateAdImageAsBytesForKey_mCA71D14A0669FF065746536A26D191772B03160E in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUNativeCustomTemplateAdImageAsBytesForKey_mCA71D14A0669FF065746536A26D191772B03160E)
  "_GADUNativeCustomTemplateAdTemplateID", referenced from:
      _Externs_GADUNativeCustomTemplateAdTemplateID_m5C2B06D2A6A506A62719C7F23AF826F9FC23EF13 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUNativeCustomTemplateAdTemplateID_m5C2B06D2A6A506A62719C7F23AF826F9FC23EF13)
  "_GADUCreateRewardBasedVideoAd", referenced from:
      _Externs_GADUCreateRewardBasedVideoAd_mC8BE9A265CE84919C889A44F29F358C53CEB8B65 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUCreateRewardBasedVideoAd_mC8BE9A265CE84919C889A44F29F358C53CEB8B65)
  "_GADUCreateAdLoader", referenced from:
      _Externs_GADUCreateAdLoader_mCF0EFCBDD0B20B312EE29247FD7D54A01BE5955E in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUCreateAdLoader_mCF0EFCBDD0B20B312EE29247FD7D54A01BE5955E)
  "_GADUMediationAdapterClassNameForRewardedAd", referenced from:
      _Externs_GADUMediationAdapterClassNameForRewardedAd_m6411B33BB86417186351D163501C8359CEDB9DE1 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUMediationAdapterClassNameForRewardedAd_m6411B33BB86417186351D163501C8359CEDB9DE1)
  "_GADURequestRewardedAd", referenced from:
      _Externs_GADURequestRewardedAd_m35517DE76F59E74D07B2905BF3BD368C354FA371 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADURequestRewardedAd_m35517DE76F59E74D07B2905BF3BD368C354FA371)
  "_GADURewardedAdReady", referenced from:
      _Externs_GADURewardedAdReady_m6ADC781E09F7F82BA5BE974EB6D137EA0DBF36DE in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADURewardedAdReady_m6ADC781E09F7F82BA5BE974EB6D137EA0DBF36DE)
  "_GADUSetBirthday", referenced from:
      _Externs_GADUSetBirthday_m48F51441B4B951AB90A85F0B08F0CA3EB60FD0B5 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUSetBirthday_m48F51441B4B951AB90A85F0B08F0CA3EB60FD0B5)
  "_GADUSetRewardBasedVideoAdUserId", referenced from:
      _Externs_GADUSetRewardBasedVideoAdUserId_m425C2572AA384110F45FAC23ED8D34ACA52C3B6A in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUSetRewardBasedVideoAdUserId_m425C2572AA384110F45FAC23ED8D34ACA52C3B6A)
  "_GADUSetAdLoaderCallbacks", referenced from:
      _Externs_GADUSetAdLoaderCallbacks_m78B8458B14E17138B8CB6635542860AD26F5BF07 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUSetAdLoaderCallbacks_m78B8458B14E17138B8CB6635542860AD26F5BF07)
  "_GADUInitialize", referenced from:
      _Externs_GADUInitialize_m5557147BFEAD13809B7F7C4C05A38AFCA3B11417 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUInitializeWithCallback_m1A36086FAACEC5529AC855EF686687799039DF47, _Externs_GADUInitializeWithCallback_m56272A2A8206A8FBF319B6F256A5538F1537E5C0 , _Externs_GADUInitialize_m5557147BFEAD13809B7F7C4C05A38AFCA3B11417 , _GADUInitializeWithCallback )
  "_GADUSetRewardBasedVideoAdCallbacks", referenced from:
      _Externs_GADUSetRewardBasedVideoAdCallbacks_m91C305F8E4C91BEDC154A89DB44CB10A2833B01D in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUSetRewardBasedVideoAdCallbacks_m91C305F8E4C91BEDC154A89DB44CB10A2833B01D)
  "_GADUSetNativeCustomTemplateAdCallbacks", referenced from:
      _Externs_GADUSetNativeCustomTemplateAdCallbacks_mC0CC98990AEC5A08741701DB58F9A0E92CD53874 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUSetNativeCustomTemplateAdCallbacks_mC0CC98990AEC5A08741701DB58F9A0E92CD53874)
  "_GADURequestRewardBasedVideoAd", referenced from:
      _Externs_GADURequestRewardBasedVideoAd_mF6F51FD608E9B7D1F7CEA86DAE0871A7CA4D6F54 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADURequestRewardBasedVideoAd_mF6F51FD608E9B7D1F7CEA86DAE0871A7CA4D6F54)
  "_GADUInterstitialReady", referenced from:
      _Externs_GADUInterstitialReady_mD5048A62B0348CF741549DE3E77414F882B14FEF in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUInterstitialReady_mD5048A62B0348CF741549DE3E77414F882B14FEF)
  "_GADUMediationAdapterClassNameForBannerView", referenced from:
      _Externs_GADUMediationAdapterClassNameForBannerView_m9CFB01AF2B5434AF0D5ABB6BD0E0EE39C28EFD0C in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUMediationAdapterClassNameForBannerView_m9CFB01AF2B5434AF0D5ABB6BD0E0EE39C28EFD0C)
  "_GADUTagForChildDirectedTreatment", referenced from:
      _Externs_GADUTagForChildDirectedTreatment_m033627F64EA0AB0A2AFF7E113FF8F98F32A1327F in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUTagForChildDirectedTreatment_m033627F64EA0AB0A2AFF7E113FF8F98F32A1327F)
  "_GADUMediationAdapterClassNameForRewardedVideo", referenced from:
      _Externs_GADUMediationAdapterClassNameForRewardedVideo_m6584FD609CAC410C123C1FB6BDEF3B2A518DD322 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUMediationAdapterClassNameForRewardedVideo_m6584FD609CAC410C123C1FB6BDEF3B2A518DD322)
  "_GADUNativeCustomTemplateAdRecordImpression", referenced from:
      _Externs_GADUNativeCustomTemplateAdRecordImpression_mBAA665A9555E2C7FD11C75BF7FC51CCEC7374156 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUNativeCustomTemplateAdRecordImpression_mBAA665A9555E2C7FD11C75BF7FC51CCEC7374156)
  "_GADUSetGender", referenced from:
      _Externs_GADUSetGender_m9FC8B41AAF4C709F0B58802AA895C2789AB034AD in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUSetGender_m9FC8B41AAF4C709F0B58802AA895C2789AB034AD)
  "_GADURewardBasedVideoAdReady", referenced from:
      _Externs_GADURewardBasedVideoAdReady_mC68EA6EA0ABE36550F1E3312A5E619A6BF310463 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADURewardBasedVideoAdReady_mC68EA6EA0ABE36550F1E3312A5E619A6BF310463)
  "_GADUShowRewardBasedVideoAd", referenced from:
      _Externs_GADUShowRewardBasedVideoAd_m981F0E2149A825AE2E4E434384231EFB8CF1A24E in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUShowRewardBasedVideoAd_m981F0E2149A825AE2E4E434384231EFB8CF1A24E)
  "_GADURequestNativeAd", referenced from:
      _Externs_GADURequestNativeAd_mC2D86CAC3655599711131081D3BD3EC0BBCBDA46 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADURequestNativeAd_mC2D86CAC3655599711131081D3BD3EC0BBCBDA46)
  "_GADURequestInterstitial", referenced from:
      _Externs_GADURequestInterstitial_mAE485C0F1945AD9E2D629563369467F277FBEAEE in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADURequestInterstitial_mAE485C0F1945AD9E2D629563369467F277FBEAEE)
  "_GADUNativeCustomTemplateAdNumberOfAvailableAssetKeys", referenced from:
      _Externs_GADUNativeCustomTemplateAdNumberOfAvailableAssetKeys_m05AFE51965FFCEC827D524DCF9ACEB6913B3F8A8 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUNativeCustomTemplateAdNumberOfAvailableAssetKeys_m05AFE51965FFCEC827D524DCF9ACEB6913B3F8A8)
  "_GADUNativeCustomTemplateAdStringForKey", referenced from:
      _Externs_GADUNativeCustomTemplateAdStringForKey_m143776D8AC49A8EFAE9ABA79124A75926A8800E0 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUNativeCustomTemplateAdStringForKey_m143776D8AC49A8EFAE9ABA79124A75926A8800E0)
  "_GADUAddTestDevice", referenced from:
      _Externs_GADUAddTestDevice_m40FE864FB10B937D1798526CE4F94EB73FE11A72 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUAddTestDevice_m40FE864FB10B937D1798526CE4F94EB73FE11A72)
  "_GADUNativeCustomTemplateAdAvailableAssetKeys", referenced from:
      _Externs_GADUNativeCustomTemplateAdAvailableAssetKeys_m4F443949A2202D0F8CAEE2451EFBAB6511B323DF in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUNativeCustomTemplateAdAvailableAssetKeys_m4F443949A2202D0F8CAEE2451EFBAB6511B323DF)
  "_GADUMediationAdapterClassNameForInterstitial", referenced from:
      _Externs_GADUMediationAdapterClassNameForInterstitial_mC5FA00C3554C1E4E5151F0FA90C0CD9197B5C7D3 in Assembly-CSharp35.o
     (maybe you meant: _Externs_GADUMediationAdapterClassNameForInterstitial_mC5FA00C3554C1E4E5151F0FA90C0CD9197B5C7D3)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chandujr** [comment]
Please check if this solves your issue: https://github.com/googleads/googleads-mobile-unity/issues/1569#issuecomment-874685709

**Comment by NVentimiglia** [comment]
> @Archi97 It solves only compilation issue for me. Linker is still not happy, it cannot find these functions in the library. I am on 6.0.1. It doesn't find these in neither 8.2 or 8.7 of Google-Mobile-Ads-SDK.
> 
> Undefined symbols for architecture arm64:
> "_GADUSetNativeCustomTemplateAdUnityClient", referenced from:
> _Externs_GADUSetNativeCustomTemplateAdUnityClient_mC9EE8442D687871FBAFE03C76F4EC9FF2A044354 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUSetNativeCustomTemplateAdUnityClient_mC9EE8442D687871FBAFE03C76F4EC9FF2A044354)
> "_GADUNativeCustomTemplateAdPerformClickOnAssetWithKey", referenced from:
> _Externs_GADUNativeCustomTemplateAdPerformClickOnAssetWithKey_m351397E554DD8BDDA0A0DD7C471B7BFF853903BE in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUNativeCustomTemplateAdPerformClickOnAssetWithKey_m351397E554DD8BDDA0A0DD7C471B7BFF853903BE)
> "_GADUNativeCustomTemplateAdImageAsBytesForKey", referenced from:
> _Externs_GADUNativeCustomTemplateAdImageAsBytesForKey_mCA71D14A0669FF065746536A26D191772B03160E in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUNativeCustomTemplateAdImageAsBytesForKey_mCA71D14A0669FF065746536A26D191772B03160E)
> "_GADUNativeCustomTemplateAdTemplateID", referenced from:
> _Externs_GADUNativeCustomTemplateAdTemplateID_m5C2B06D2A6A506A62719C7F23AF826F9FC23EF13 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUNativeCustomTemplateAdTemplateID_m5C2B06D2A6A506A62719C7F23AF826F9FC23EF13)
> "_GADUCreateRewardBasedVideoAd", referenced from:
> _Externs_GADUCreateRewardBasedVideoAd_mC8BE9A265CE84919C889A44F29F358C53CEB8B65 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUCreateRewardBasedVideoAd_mC8BE9A265CE84919C889A44F29F358C53CEB8B65)
> "_GADUCreateAdLoader", referenced from:
> _Externs_GADUCreateAdLoader_mCF0EFCBDD0B20B312EE29247FD7D54A01BE5955E in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUCreateAdLoader_mCF0EFCBDD0B20B312EE29247FD7D54A01BE5955E)
> "_GADUMediationAdapterClassNameForRewardedAd", referenced from:
> _Externs_GADUMediationAdapterClassNameForRewardedAd_m6411B33BB86417186351D163501C8359CEDB9DE1 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUMediationAdapterClassNameForRewardedAd_m6411B33BB86417186351D163501C8359CEDB9DE1)
> "_GADURequestRewardedAd", referenced from:
> _Externs_GADURequestRewardedAd_m35517DE76F59E74D07B2905BF3BD368C354FA371 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADURequestRewardedAd_m35517DE76F59E74D07B2905BF3BD368C354FA371)
> "_GADURewardedAdReady", referenced from:
> _Externs_GADURewardedAdReady_m6ADC781E09F7F82BA5BE974EB6D137EA0DBF36DE in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADURewardedAdReady_m6ADC781E09F7F82BA5BE974EB6D137EA0DBF36DE)
> "_GADUSetBirthday", referenced from:
> _Externs_GADUSetBirthday_m48F51441B4B951AB90A85F0B08F0CA3EB60FD0B5 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUSetBirthday_m48F51441B4B951AB90A85F0B08F0CA3EB60FD0B5)
> "_GADUSetRewardBasedVideoAdUserId", referenced from:
> _Externs_GADUSetRewardBasedVideoAdUserId_m425C2572AA384110F45FAC23ED8D34ACA52C3B6A in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUSetRewardBasedVideoAdUserId_m425C2572AA384110F45FAC23ED8D34ACA52C3B6A)
> "_GADUSetAdLoaderCallbacks", referenced from:
> _Externs_GADUSetAdLoaderCallbacks_m78B8458B14E17138B8CB6635542860AD26F5BF07 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUSetAdLoaderCallbacks_m78B8458B14E17138B8CB6635542860AD26F5BF07)
> "_GADUInitialize", referenced from:
> _Externs_GADUInitialize_m5557147BFEAD13809B7F7C4C05A38AFCA3B11417 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUInitializeWithCallback_m1A36086FAACEC5529AC855EF686687799039DF47, _Externs_GADUInitializeWithCallback_m56272A2A8206A8FBF319B6F256A5538F1537E5C0 , _Externs_GADUInitialize_m5557147BFEAD13809B7F7C4C05A38AFCA3B11417 , _GADUInitializeWithCallback )
> "_GADUSetRewardBasedVideoAdCallbacks", referenced from:
> _Externs_GADUSetRewardBasedVideoAdCallbacks_m91C305F8E4C91BEDC154A89DB44CB10A2833B01D in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUSetRewardBasedVideoAdCallbacks_m91C305F8E4C91BEDC154A89DB44CB10A2833B01D)
> "_GADUSetNativeCustomTemplateAdCallbacks", referenced from:
> _Externs_GADUSetNativeCustomTemplateAdCallbacks_mC0CC98990AEC5A08741701DB58F9A0E92CD53874 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUSetNativeCustomTemplateAdCallbacks_mC0CC98990AEC5A08741701DB58F9A0E92CD53874)
> "_GADURequestRewardBasedVideoAd", referenced from:
> _Externs_GADURequestRewardBasedVideoAd_mF6F51FD608E9B7D1F7CEA86DAE0871A7CA4D6F54 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADURequestRewardBasedVideoAd_mF6F51FD608E9B7D1F7CEA86DAE0871A7CA4D6F54)
> "_GADUInterstitialReady", referenced from:
> _Externs_GADUInterstitialReady_mD5048A62B0348CF741549DE3E77414F882B14FEF in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUInterstitialReady_mD5048A62B0348CF741549DE3E77414F882B14FEF)
> "_GADUMediationAdapterClassNameForBannerView", referenced from:
> _Externs_GADUMediationAdapterClassNameForBannerView_m9CFB01AF2B5434AF0D5ABB6BD0E0EE39C28EFD0C in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUMediationAdapterClassNameForBannerView_m9CFB01AF2B5434AF0D5ABB6BD0E0EE39C28EFD0C)
> "_GADUTagForChildDirectedTreatment", referenced from:
> _Externs_GADUTagForChildDirectedTreatment_m033627F64EA0AB0A2AFF7E113FF8F98F32A1327F in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUTagForChildDirectedTreatment_m033627F64EA0AB0A2AFF7E113FF8F98F32A1327F)
> "_GADUMediationAdapterClassNameForRewardedVideo", referenced from:
> _Externs_GADUMediationAdapterClassNameForRewardedVideo_m6584FD609CAC410C123C1FB6BDEF3B2A518DD322 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUMediationAdapterClassNameForRewardedVideo_m6584FD609CAC410C123C1FB6BDEF3B2A518DD322)
> "_GADUNativeCustomTemplateAdRecordImpression", referenced from:
> _Externs_GADUNativeCustomTemplateAdRecordImpression_mBAA665A9555E2C7FD11C75BF7FC51CCEC7374156 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUNativeCustomTemplateAdRecordImpression_mBAA665A9555E2C7FD11C75BF7FC51CCEC7374156)
> "_GADUSetGender", referenced from:
> _Externs_GADUSetGender_m9FC8B41AAF4C709F0B58802AA895C2789AB034AD in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUSetGender_m9FC8B41AAF4C709F0B58802AA895C2789AB034AD)
> "_GADURewardBasedVideoAdReady", referenced from:
> _Externs_GADURewardBasedVideoAdReady_mC68EA6EA0ABE36550F1E3312A5E619A6BF310463 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADURewardBasedVideoAdReady_mC68EA6EA0ABE36550F1E3312A5E619A6BF310463)
> "_GADUShowRewardBasedVideoAd", referenced from:
> _Externs_GADUShowRewardBasedVideoAd_m981F0E2149A825AE2E4E434384231EFB8CF1A24E in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUShowRewardBasedVideoAd_m981F0E2149A825AE2E4E434384231EFB8CF1A24E)
> "_GADURequestNativeAd", referenced from:
> _Externs_GADURequestNativeAd_mC2D86CAC3655599711131081D3BD3EC0BBCBDA46 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADURequestNativeAd_mC2D86CAC3655599711131081D3BD3EC0BBCBDA46)
> "_GADURequestInterstitial", referenced from:
> _Externs_GADURequestInterstitial_mAE485C0F1945AD9E2D629563369467F277FBEAEE in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADURequestInterstitial_mAE485C0F1945AD9E2D629563369467F277FBEAEE)
> "_GADUNativeCustomTemplateAdNumberOfAvailableAssetKeys", referenced from:
> _Externs_GADUNativeCustomTemplateAdNumberOfAvailableAssetKeys_m05AFE51965FFCEC827D524DCF9ACEB6913B3F8A8 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUNativeCustomTemplateAdNumberOfAvailableAssetKeys_m05AFE51965FFCEC827D524DCF9ACEB6913B3F8A8)
> "_GADUNativeCustomTemplateAdStringForKey", referenced from:
> _Externs_GADUNativeCustomTemplateAdStringForKey_m143776D8AC49A8EFAE9ABA79124A75926A8800E0 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUNativeCustomTemplateAdStringForKey_m143776D8AC49A8EFAE9ABA79124A75926A8800E0)
> "_GADUAddTestDevice", referenced from:
> _Externs_GADUAddTestDevice_m40FE864FB10B937D1798526CE4F94EB73FE11A72 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUAddTestDevice_m40FE864FB10B937D1798526CE4F94EB73FE11A72)
> "_GADUNativeCustomTemplateAdAvailableAssetKeys", referenced from:
> _Externs_GADUNativeCustomTemplateAdAvailableAssetKeys_m4F443949A2202D0F8CAEE2451EFBAB6511B323DF in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUNativeCustomTemplateAdAvailableAssetKeys_m4F443949A2202D0F8CAEE2451EFBAB6511B323DF)
> "_GADUMediationAdapterClassNameForInterstitial", referenced from:
> _Externs_GADUMediationAdapterClassNameForInterstitial_mC5FA00C3554C1E4E5151F0FA90C0CD9197B5C7D3 in Assembly-CSharp35.o
> (maybe you meant: _Externs_GADUMediationAdapterClassNameForInterstitial_mC5FA00C3554C1E4E5151F0FA90C0CD9197B5C7D3)
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Are you still experiencing issues after reinstalling the package? What steps are you taking so I can see about replicating them on my end.

**Comment by bloto** [comment]
I had to remove previous google services plugin folder completelly which contained some old ios header/m files. The installer did not wipe them out so linker was trying to find externs but the new library did not have that. I think the installer could be improved to wipe it out if its possible. Cheers
