### ISSUE TITLE
Ad failed to load : 3 Error (Admob 5.4.0 and Admob 6.0.0)

### ISSUE THREAD

**Issue by tolgamacpro** [googleads/googleads-mobile-unity#1663]
* Unity version: 2020.3.7f1
  * Google Mobile Ads Unity plugin version: 5.4.0
  * Platform: Android
  * Platform OS version: Android 11
  * Other Google Plugins: Firebase 8.0.0

this morning,
i got this error 

**2021.06.22 13:42:39.917 26596 26596 Info Ads Ad failed to load : 3**

and my ads are not showing how can i fix it

![image](https://user-images.githubusercontent.com/79801940/122911969-85cc1e00-d360-11eb-9580-4909519d7a2a.png)

**Comment by tolgamacpro** [comment]
@googlebot

**Comment by matie** [comment]
Hi, probably serverside there is no ad for you available at this time. Using a vpn sometimes helps, but adding your devices to testdevices is probably a better idea. I never saw this "error" with testdevices. Although not sure if this is by coincident.

**Comment by smhlotfi** [comment]
@tolgamacpro I have the same problem. Did you fix this?

**Comment by gputhread** [comment]
Same here guys, Any fix? 😫
Admob about to deactivate my account for no ad request logging in bcoz of "ad failed to load 3" in 6 months.
Even the crawl of app ads txt not syncing!

**Comment by matie** [comment]
Hi. there are no issues at this moment. error 3 means no fill. Therefore I would suggest to have a good look at you account and implementation. It could be getting error 3 yourself, just because there are no ads to show (no fill), but it doesn't happen a lot to me.

**Comment by gputhread** [comment]
My got account got deactivated for not showing ads and after that I reactivated which leaded to reverification after which I rechecked payment profile and luckily now that Admob account started showing ads again. For me Ad failed to load : 3 got solved this way.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
