### ISSUE TITLE
ClassNotFoundException when initializing the plugin in Android

### ISSUE THREAD

**Issue by svprdga** [googleads/googleads-mobile-unity#1665]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.8f1 Personal
  * Google Mobile Ads Unity plugin version: 6.0.1
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: Android 11 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: Samsung Galaxy S10
  * Mediation ad networks used, and their versions: No

#### Steps to reproduce:

1. Integrate the plugin following the documentation
2. Add app ids and initialization as stated in the documentation
3. Launch the project in a device

#### Expected result:

The project is launched successfully without errors.

#### Actual result:

An android native exception is thrown when initializing the plugin:

```
2021/06/22 20:21:03.726 28816 28884 Error Unity AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.initialization.OnInitializationCompleteListener
2021/06/22 20:21:03.726 28816 28884 Error Unity java.lang.ClassNotFoundException: com.google.android.gms.ads.initialization.OnInitializationCompleteListener
2021/06/22 20:21:03.726 28816 28884 Error Unity 	at java.lang.Class.classForName(Native Method)
2021/06/22 20:21:03.726 28816 28884 Error Unity 	at java.lang.Class.forName(Class.java:453)
2021/06/22 20:21:03.726 28816 28884 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2021/06/22 20:21:03.726 28816 28884 Error Unity 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
2021/06/22 20:21:03.726 28816 28884 Error Unity 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
2021/06/22 20:21:03.726 28816 28884 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:101)
2021/06/22 20:21:03.726 28816 28884 Error Unity 	at android.os.Looper.loop(Looper.java:164)
2021/06/22 20:21:03.726 28816 28884 Error Unity 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
2021/06/22 20:21:03.726 28816 28884 Error Unity Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.initialization.OnInitializationCompleteListener" on path: DexPathList[[zip file "/data/app/com.DefaultCompany.com.unity.template.mobile2D--5Vug5sUhUshXM2zII3uxA==/base.apk"],nativeLibraryDirectories=[/data/app/com.DefaultCompany.com.unity.t
```

**Comment by crazybot-new** [comment]
Same issue here

**Comment by ksnerv** [comment]
same issue
