### ISSUE TITLE
Unity - Admob - Memory Limit Exceed for Bannerview

### ISSUE THREAD

**Issue by xebudda** [googleads/googleads-mobile-unity#1667]
Hello,

When i check android studio logcat while profiling APK, it gives this error several times whenever admob bannerview loads and bannerview ad changes

[ERROR:tile_manager.cc(811)] WARNING: tile memory limits exceeded, some content may not draw

I am using mac Big Sur

I have tested in empty projects in unity editors:

 2021.1.11unity editor  with 5.4 Admob SDK

and 2020.3.1 LTS unity editor with admob 6.0 sdk

I have tested in an empty scene in empty projects with only requesting bannerview once

Also tested in windows and still having the same warning

My code for request is:

if (this.bannerView != null)
{
this.bannerView.Destroy();
}

// Create a 320x50 banner at the top of the screen.
this.bannerView = new BannerView(adUnitId, AdSize.SmartBanner, AdPosition.Bottom);

// Called when an ad request has successfully loaded.
this.bannerView.OnAdLoaded += this.HandleOnAdLoaded;
// Called when an ad request failed to load.
// Called when an ad is clicked.
this.bannerView.OnAdOpening += this.HandleOnAdOpened;
// Called when the user returned from the app after an ad click.
this.bannerView.OnAdClosed += this.HandleOnAdClosed;
// Called when the ad click caused the user to leave the application.

AdRequest request = new AdRequest.Builder().Build();
bannerView.LoadAd(request);

**Comment by NVentimiglia** [comment]
This could be from a number of causes, it is pretty hard to diagnose without a sample. Please update to the latest version and try again if this is still issue please submit a sample.
