### ISSUE TITLE
Ads not displaying, HTTP load fail (Allow Arbitrary Loads already set to true!)

### ISSUE THREAD

**Issue by rebelincontrol** [googleads/googleads-mobile-unity#167]
Using Unity5, xCode 7.2, targeting iOS7 and running on iOS9 - I am having the following issue.

I'm unable to display any non-test device ads, ie test ads render correctly, and normal ads fire OnAdLoaded, along with 'NSURLSession/NSURLConnection HTTP load failed'. 

I've already set NSAllowsArbitraryLoads to 'true', under NSAppTransportSecurity in the .plist, and there are a couple of other HTTP connections that are being successfully fired, the only issue is with the ads.

Every 45 seconds or however long the refresh rate is set to, I get another log message: 
'NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9843)'

I rooted around and found that -9843 is an error code for mismatched host name - ie the host name is not allowed by the certificate. Isn't this overidden by disabling NSAppTransportSecurity?

I've spend most the day trying to get a handle on this and I've hit a dead end, I'd be grateful if you had any clues, perhaps I've set up my xCode project wrong.

Thanks

**Comment by rampara** [comment]
@rebelincontrol can you link an Xcode project where you can reproduce this error. It would help in investigating further.

**Comment by rampara** [comment]
Closing issue due to non-response. If this issue persists, please re-open.
