### ISSUE TITLE
ironSource adapter causes iOS crash

### ISSUE THREAD

**Issue by p0w1nd** [googleads/googleads-mobile-unity#1675]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.25f1
  * Google Mobile Ads Unity plugin version: 6.0.1
  * Platform: iOS
  * Platform OS version: iOS 14.5
  * Mediation ad networks used, and their versions: AppLovin, FAN, Vungle, Unity Ads, ironSource

### [REQUIRED] Step 2: Describe the problem

Android: no problem
iOS: crash with ironSource adapter `GoogleMobileAdsIronSourceMediation-2.0.3`.
Removing ironSource adapter => works perfectly.

There's version 2.1.0 of ironSource adapter but it's not available yet. "In Progress": https://developers.google.com/admob/unity/mediation/ironsource#ironsource-unity-mediation-plugin-changelog

Crash log:

```2021-06-28 17:49:36.902282+0700 PrisonEscape[61691:9467087] +[GADRequest sdkVersion]: unrecognized selector sent to class 0x1094aeaa8
2021-06-28 17:49:36.915754+0700 PrisonEscape[61691:9467087] Uncaught exception: NSInvalidArgumentException: +[GADRequest sdkVersion]: unrecognized selector sent to class 0x1094aeaa8
(
	0   CoreFoundation                      0x00000001a1c2e768 4FBDF167-161A-324C-A233-D516922C67E5 + 1218408
	1   libobjc.A.dylib                     0x00000001b66f57a8 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001a1b3676c 4FBDF167-161A-324C-A233-D516922C67E5 + 202604
	3   CoreFoundation                      0x00000001a1c312ac 4FBDF167-161A-324C-A233-D516922C67E5 + 1229484
	4   CoreFoundation                      0x00000001a1c335b0 _CF_forwarding_prep_0 + 96
	5   UnityFramework                      0x00000001075af874 +[GADMAdapterIronSourceUtils getAdMobSDKVersion] + 36
	6   UnityFramework                      0x00000001075ab650 -[ISMediationManager init] + 224
	7   UnityFramework                      0x00000001075ab558 __35+[ISMediationManager sharedManager]_block_invoke + 28
	8   libdispatch.dylib                   0x00000001a181b81c DAF30062-4C85-3B92-B159-50602A0C9D97 + 18460
	9   libdispatch.dylib                   0x00000001a181d0b4 DAF30062-4C85-3B92-B159-50602A0C9D97 + 24756
	10  UnityFramework                      0x00000001075ab538 +[ISMediationManager sharedManager] + 112
	11  UnityFramework                      0x00000001075adf3c -[GADMAdapterIronSourceRewardedAd requestRewardedAd] + 460
	12  UnityFramework                      0x000000010747f344 GAD_GADMediationRewardedAdRenderer_arm64_8_6_0 + 2116
	13  libdispatch.dylib                   0x00000001a1819a84 DAF30062-4C85-3B92-B159-50602A0C9D97 + 10884
	14  libdispatch.dylib                   0x00000001a181b81c DAF30062-4C85-3B92-B159-50602A0C9D97 + 18460
	15  libdispatch.dylib                   0x00000001a1829c70 _dispatch_main_queue_callback_4CF + 884
	16  CoreFoundation                      0x00000001a1ba8398 4FBDF167-161A-324C-A233-D516922C67E5 + 668568
	17  CoreFoundation                      0x00000001a1ba2270 4FBDF167-161A-324C-A233-D516922C67E5 + 643696
	18  CoreFoundation                      0x00000001a1ba1360 CFRunLoopRunSpecific + 600
	19  GraphicsServices                    0x00000001b91df734 GSEventRunModal + 164
	20  UIKitCore                           0x00000001a461c584 33B02AB5-5DAF-3249-8DC6-5872DF830EC5 + 12363140
	21  UIKitCore                           0x00000001a4621df4 UIApplicationMain + 168
	22  UnityFramework                      0x0000000107019a60 -[UnityFramework runUIApplicationMainWithArgc:argv:] + 108
	23  PrisonEscape                        0x0000000104d0fe1c main + 68
	24  libdyld.dylib                       0x00000001a185dcf8 E574A365-9878-348A-8E84-91E163CFC128 + 7416
)
2021-06-28 17:49:36.916348+0700 PrisonEscape[61691:9467087] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[GADRequest sdkVersion]: unrecognized selector sent to class 0x1094aeaa8'
*** First throw call stack:
(0x1a1c2e754 0x1b66f57a8 0x1a1b3676c 0x1a1c312ac 0x1a1c335b0 0x1075af874 0x1075ab650 0x1075ab558 0x1a181b81c 0x1a181d0b4 0x1075ab538 0x1075adf3c 0x10747f344 0x1a1819a84 0x1a181b81c 0x1a1829c70 0x1a1ba8398 0x1a1ba2270 0x1a1ba1360 0x1b91df734 0x1a461c584 0x1a4621df4 0x107019a60 0x104d0fe1c 0x1a185dcf8)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[GADRequest sdkVersion]: unrecognized selector sent to class 0x1094aeaa8'
terminating with uncaught exception of type NSException```

**Comment by max-ilyin-ilogos** [comment]
Facing the same issue. I've got iOS app crash with:

`Uncaught exception: NSInvalidArgumentException: +[GADRequest sdkVersion]: unrecognized selector sent to class 0x104aa5f80`

**Comment by ironnick** [comment]
same

**Comment by max-ilyin-ilogos** [comment]
Fixed IronSource NSInvalidArgumentException by using 
`<iosPod name="GoogleMobileAdsMediationIronSource" version="7.1.6.1.0">`
in IronSourceMediationDependencies.xml.

Not sure about safety of this solution, but at least exception is gone.

**Comment by max-ilyin-ilogos** [comment]
> the same issue with facebook

Fixed after updating facebook mediation adapter to v3.3.0.
https://developers.google.com/admob/unity/mediation/facebook#version-3.3.0

**Comment by wayne-tt** [comment]
I also faced the same issue.

If you refer to the link below, you can see the updated history regarding the app crash issue in v7.1.13.

https://developers.is.com/ironsource-mobile/ios/sdk-change-log/

**Comment by gnoph** [comment]
`[GADRequest sdkVersion]` had been deprecated in `Google-Mobile-Ads-SDK` since version `7.64.0`. See their release notes: https://developers.google.com/admob/ios/rel-notes. The affected method had later been removed completely in `8.0.0`. 

The first version of ironsource mediation that is compatible with admob ios 8.0.0 is `GoogleMobileAdsMediationIronSource` `7.1.0.1`

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
