### ISSUE TITLE
Version 6.0.1 - Error on Xcode - Not Buildable

### ISSUE THREAD

**Issue by Archi97** [googleads/googleads-mobile-unity#1677]
* Unity version: 2020.3.4
  * Google Mobile Ads Unity plugin version: 6.0.1
  * Platform: IOS
  * Platform OS version: _____
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:
1. Open Unity Hub and Create new project (default settings)
2. Switch platform to IOS
3. Download latest Admob plugin for unity (6.0.1) 
4. Import the package. 
5. Fill Ads APP ID in file GoogleMobileAdsSettings.asset
    5.1 Checking "Link frameworks statically" in iOS Resolver -> Settings  (does nothing same error in Xcode)
6. Build the project
7. Open Xcode Workspace file from built directory.
8. Set certificate, and app bundle identifier(if needed)
9. Hit build and run button from Xcode.

You will get error 
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/User/Desktop/TYOM/Admob test/Xcode project/Libraries/libiPhone-lib.a(unwind_test_arm64.o)

ld: in /Users/User/Desktop/TYOM/Admob test/Xcode project/Libraries/Plugins/iOS/unity-plugin-library.a(GADUBanner_e1ca55b395064147a6f81a9b54e513ca.o), could not parse object file /Users/User/Desktop/TYOM/Admob test/Xcode project/Libraries/Plugins/iOS/unity-plugin-library.a(GADUBanner_e1ca55b395064147a6f81a9b54e513ca.o): 'Invalid bitcode version (Producer: '1205.0.22.9.0_0' Reader: '1200.0.32.29_0')', using libLTO version 'LLVM version 12.0.0, (clang-1200.0.32.29)' file '/Users/User/Desktop/TYOM/Admob test/Xcode project/Libraries/Plugins/iOS/unity-plugin-library.a' for architecture arm64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please let me know what to do to fix this problem.

**Comment by ivk1800** [comment]
project not builded because unity-plugin-library.a builded with xcode 12.5.1, I unable update xcode, because 12.5.1 required mac os big sur, i run on catalina.  
how resolve: replace unity-plugin-library.a by source code from folder plugins/ios

**Comment by harrissaleem** [comment]
Anyone got this to work? I am using unity 2019.4 (LTS) and plugin 6.0.1 and cant build on iOS.
Also can someone please explain why they would just upload this package on their main admob page when its not even doing the basic things like building on iOS? :(

**Comment by mastef** [comment]
Same, fails to build on Xcode 12.4 / Catalina

**Comment by harrissaleem** [comment]
> Same, fails to build on Xcode 12.4 / Catalina

Did you try chagning the version to 6.0.2 like copybara-service mentioned?

**Comment by mastef** [comment]
> > Same, fails to build on Xcode 12.4 / Catalina
> 
> Did you try chagning the version to 6.0.2 like copybara-service mentioned?

I don't see a 6.0.2 release at https://github.com/googleads/googleads-mobile-unity/releases
Also don't see any comments from copybara-service

For now it seems both recent releases come with major issues. A lot of work to keep this package updated - very disappointing.

**Comment by bab202** [comment]
> project not builded because unity-plugin-library.a builded with xcode 12.5.1, I unable update xcode, because 12.5.1 required mac os big sur, i run on catalina.
> how resolve: replace unity-plugin-library.a by source code from folder plugins/ios

This is correct, I have no issue when build iOS with Xcode 12.5.1

**Comment by Archi97** [comment]
> > project not builded because unity-plugin-library.a builded with xcode 12.5.1, I unable update xcode, because 12.5.1 required mac os big sur, i run on catalina.
> > how resolve: replace unity-plugin-library.a by source code from folder plugins/ios
> 
> This is correct, I have no issue when build iOS with Xcode 12.5.1

I not really get the solution.  can you provide step by step instruction? 
However SDK must be fixed itself, to not give this kind of error.
Thanks

**Comment by bab202** [comment]
> I not really get the solution. can you provide step by step instruction?
> However SDK must be fixed itself, to not give this kind of error.
> Thanks

I do nothing, just build my app with Xcode 12.5.1 and see no error. I agree with you that the SDK should be tested on different versions of Xcode.

**Comment by Archi97** [comment]
> project not builded because unity-plugin-library.a builded with xcode 12.5.1, I unable update xcode, because 12.5.1 required mac os big sur, i run on catalina.
> how resolve: replace unity-plugin-library.a by source code from folder plugins/ios

I do not really get the solution. can you provide step by step instruction?
However SDK must be fixed itself, to not give this kind of error.
Thanks

**Comment by Archi97** [comment]
Yes. Just update Xcode 12.5.1 and issue will gone.
