### ISSUE TITLE
 bitcode error with unity-plugin-library.a and xcode 12.4

### ISSUE THREAD

**Issue by RoboticAccolade** [googleads/googleads-mobile-unity#1678]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.2.20f1
  * Google Mobile Ads Unity plugin version: 6.0.1
  * Platform: iOS (iOS, Android, Unity Editor)
  * Platform OS version: iOS 9+ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: build level issue
  * Mediation ad networks used, and their versions: Facebook Ads Mediation v.3.3.0

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

On installing the latest Facebook Ads Mediation plugin, I discovered it required an updated version of Google Ads.  Upon installing 6.0.0 and later 6.0.1, I ran into the following issue: unity-plugin-library.a returned an error in xcode (that didn't show up in my unity logs directly, but that's neither here nor there) claiming it could not be parsed due to an invalid bitcode version.

Googling the problem, it seems the correct solution is to update xcode, but a common workaround is to simply disable bitcode.  I thought of trying the workaround first, but to my dismay I found that my project already has enable bitcode set to No.  So I'm at a bit of a loss as to what the true problem is, or if xcode updating will actually solve my problem.

Updating xcode isn't impossible, and probably my next course of action, but to be honest it's a bit risky to fiddle too much with our build machine and I'm not certain updating will have no costs to my or other company projects using it.
<img width="557" alt="スクリーンショット 2021-06-29 18 45 51" src="https://user-images.githubusercontent.com/76253638/123782712-948e7400-d910-11eb-8d8e-eceb0c6c1480.png">
this is the error message in question, and my build settings as they were at the time this error was generated:
<img width="554" alt="スクリーンショット 2021-06-29 19 12 34" src="https://user-images.githubusercontent.com/76253638/123782830-af60e880-d910-11eb-880c-525809a3b3e5.png">

If upgrading Xcode is necessary, could you please inform me of what version I need to make unity-plugin-library.a be readable?

Also, and this is a bit outside the scope of this question, but the name seems a bit generic, for projects with multiple plugins it might be hard to keep track of.  Also a comment somewhere that people upgrading need to delete GADU* files in the same directory from older versions might be helpful (this of course being partially an issue of Unity's poor plugin handling).

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by Archi97** [comment]
#1677 Same for me.  
It happens even on empty project.

**Comment by camphongdinh** [comment]
Hi, it happened to me before. I was using Pods so my solution is go to Xcode and change Unity-framework's Build Settings -> Enabled Bitcode -> NO . For non-pods projects, I suppose you can locate the library file (maybe it is .framework or something) and disable Bitcode . Hope this helps.

**Comment by Archi97** [comment]
> Hi, it happened to me before. I was using Pods so my solution is go to Xcode and change Unity-framework's Build Settings -> Enabled Bitcode -> NO . For non-pods projects, I suppose you can locate the library file (maybe it is .framework or something) and disable Bitcode . Hope this helps.

it didn't help me. :(

**Comment by alleluso** [comment]
Same problem for me. And yes... I have Bitcode set to NO

**Comment by ironnick** [comment]
same

**Comment by mariopintoappgeneration** [comment]
I've managed to solve using a suggestion from @ivk1800: https://github.com/googleads/googleads-mobile-unity/issues/1677#issuecomment-871494388

I've replaced unity-plugin-library.a by the source code from folder [plugins/ios.](https://github.com/googleads/googleads-mobile-unity/tree/master/source/plugin/Assets/Plugins/iOS) 
You also have to add the source code from the mediation networks you're using. [here](https://github.com/googleads/googleads-mobile-unity/tree/master/mediation)

Hope it helps!

**Comment by ericleich** [comment]
The core issue is unity-plugin-library.a was built with Xcode 12.5.1 which requires you to use Xcode 12.5.1 to use the plugin. More related info at https://github.com/googleads/googleads-mobile-unity/issues/1677

We are looking into doing another release built against 12.4 because Xcode 12.5 does require an OS update to Catalina which may be cumbersome to some users. Replacing the source as described by @mariopintoappgeneration should also work, but we understand that it's preferable for the package to work out of the box.

**Comment by CheeryLee** [comment]
A small clarification: is was built using Xcode 12.5.7 that **requires Big Sur** at least. Catalina is not supported.
