### ISSUE TITLE
Building in Unity Cloud Build

### ISSUE THREAD

**Issue by AndersonDev** [googleads/googleads-mobile-unity#168]
Hi again) Sory for 3th theme. But I dont understood the steps I need to do for building my game in Unity Cloud Build with AdMob. If I only add the Plugin in Unity, cloud build say there isn't "GoogleMobileAds" module because I don't have **SDK**, rigth?
I add **SDK** _(Not Plugin)_ in Unity _(right, drag intro editor a GoogleMobileAds.framework)_ and build in XCode - all was OK, however the size of app increased for 10 MB _(It is so **much**)_!!!

And in UCB I got errors:
![er](https://cloud.githubusercontent.com/assets/6890368/12992040/cff7883c-d11a-11e5-80af-c5993b004781.png)

What I do not correct? Please write me a step by step how implement AdMob in right way. Thanks so much!

**Comment by rampara** [comment]
Follow the following steps for building with Unity Cloud Build on our latest release (3.0.1):

1. Modify the plugin to disable bitcode for the Xcode generated project. This can be done by adding the following code snippet to line 61 of 'Postprocessor.cs':

project.SetBuildProperty(target, "ENABLE_BITCODE", "NO");

*Note: Once the Google Mobile Ads iOS SDK is updated to support bitcode (which should be very soon), this change will no longer be required.

2. Copy the Google Mobile Ads iOS SDK to the 'Assets/Plugins/iOS/' folder of your Unity project.
