### ISSUE TITLE
No overload for 'HandleRewardedAdFailedToLoad'

### ISSUE THREAD

**Issue by AshwinTheGammer** [googleads/googleads-mobile-unity#1683]
* Unity version: 2019.4.13f1
  * Google Mobile Ads Unity plugin version: v6.0.1
  * Platform: Android, UnityEditor
  * Platform OS version: v10
 I'm getting this error:
 

> error CS0123: No overload for 'HandleRewardedAdFailedToLoad' matches delegate 'EventHandler<AdFailedToLoadEventArgs>'

This line of code, shows me the error:
`   this.rewardedAd.OnAdFailedToLoad += HandleRewardedAdFailedToLoad;
`
I've attached the script.
[AD.txt](https://github.com/googleads/googleads-mobile-unity/files/6747333/AD.txt)

_

**Comment by NVentimiglia** [comment]
Can you modify your method to use handle a argument of type 'AdFailedToLoadEventArgs' instead of 'AdErrorEventArgs'

See  :

https://github.com/googleads/googleads-mobile-unity/blob/219bc85e7e82bbd04d89c5bfedd235bab43e2324/source/plugin/Assets/GoogleMobileAds/Api/RewardedAd.cs#L124
