### ISSUE TITLE
ArrayTypeMismatchException on loading reward ad

### ISSUE THREAD

**Issue by LASpencer** [googleads/googleads-mobile-unity#1685]
* Unity version: 2020.3.11f
  * Google Mobile Ads Unity plugin version: 6.0.0
  * Platform: Android
  * Platform OS version: Android OS 10 / API-29
  * Any specific devices issue occurs on: LGE LM-Q730, 
  * Mediation ad networks used, and their versions: AdColony 4.2.4.0, App Lovin 10.1.2.0, Facebook 6.2.0.1, Play services ads 20.0.0, MoPub 5.15.0.0, Tapjoy 12.7.1.0, Unity 3.6.0.0

We received a bug report of an ArrayTypeMismatchException being thrown.

ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.

Callstack
```
[ 0 ] ODDFramework.AdMobCallbackLogContext.LogCallbackMessage (System.String callbackName, System.Object sender)
[ 1 ] System.EventHandler`1[TEventArgs].Invoke (System.Object sender, TEventArgs e)
[ 2 ] System.EventHandler`1[TEventArgs].Invoke (System.Object sender, TEventArgs e)
[ 3 ] System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
[ 4 ] UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args)
[ 5 ] UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, System.IntPtr jmethodName, System.IntPtr jargs)
[ 6 ] Rethrow as TargetInvocationException: GoogleMobileAds.Android.RewardedAdClient.onRewardedAdLoaded()
[ 7 ] UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args)
[ 8 ] UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, System.IntPtr jmethodName, System.IntPtr jargs)
```

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
