### ISSUE TITLE
OnUserEarnedReward is called after OnAdClosed in Android Device

### ISSUE THREAD

**Issue by desouse** [googleads/googleads-mobile-unity#1689]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2018.4.17f1
  * Target API 30
  * Google Mobile Ads Unity plugin version: 6.0.1
  * Platform: Android
  * Platform OS version: tested on 8.1 and 11
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: AppLovinUnityAdapter-5.0.0, FacebookUnityAdapter-3.3.0, UnityAdsUnityAdapter-2.7.0, VungleUnityAdapter-3.6.0

#### Steps to reproduce:

OnUserEarnedReward event is called after OnAdClosed in Android device.
For test purposes, it was used HelloWorld example project with mediation ad networks described above, and with real adUnitId(https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld)
#### Screenshot with the log:
![AppLovinBug](https://user-images.githubusercontent.com/9247348/124757719-12c5c880-df58-11eb-83b4-b8b6683ff2ac.png)

The last message after closing the ad was User Earned Reward instead of Ad Closed
![image](https://user-images.githubusercontent.com/9247348/124758403-c038dc00-df58-11eb-82c9-440ccbf2d755.png)

**Comment by ericleich** [comment]
The callback order is dependent on the adapter implementations, and typically the limiting factor is we rely on the events from the 3p SDK to then forward onto you. In this case, you're using AppLovin -- it's possible their SDK returns ad closed callback before the ad reward callback, in which case there's not much we can do about it. Holding the call to onAdClosed() until the rewarded callback is invoked is risky, because we don't know that the reward callback will happen 100% of the time.

@joshuajplagonera to dig into the AppLovin Android adapter and confirm the behavior.

**Comment by Archi97** [comment]
@ericleich  why no one of your team is answering to my question?  What is the problem.  
There is strange things on Last SKD version.  but no on from your team interested in it

**Comment by ericleich** [comment]
@Archi97 the other 3 should all be commented now.

**Comment by joshuajplagonera** [comment]
Hi All,

We currently forward `onAdClosed()` and `onUserEarnedReward()` on the same callback on the AppLovin Android adapter: https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/applovin/applovin/src/main/java/com/applovin/mediation/AppLovinIncentivizedAdListener.java#L49
It is possible that this is caused by the Unity plugin.

**Comment by ericleich** [comment]
@NVentimiglia to take a look. The Unity plugin does do some threading/queueing with events that come back, and the logs above do make it seem like the plugin is mishandling a race condition.

**Comment by Last8Exile** [comment]
Callback order wery poorly described.

I use async to to handle callbacks. After i receive onAdClosed i wait several frames for onUserEarnedReward and if it not happend - consider it as skipped (canceled) ad

**Comment by NVentimiglia** [comment]
I took a look at this issue and was unable to replicate on my first pass. Here are my steps.

- Default Hello world sample with 6.0.2 and AppLovin 5.1.0
- Modified keys to look at AppLovin
- Added debug statements to Reward Interstitials
- Tested RewardInterstial on Android
- Result was that the reward event came before the close event

Is there something I missed ?

**Comment by desouse** [comment]
> I took a look at this issue and was unable to replicate on my first pass. Here are my steps.
> 
> * Default Hello world sample with 6.0.2 and AppLovin 5.1.0
> * Modified keys to look at AppLovin
> * Added debug statements to Reward Interstitial events
> * Tested Reward Interstitial on Android
> * Result was that the reward event came before the close event
> 
> Is there something I missed ?

Hello. The only difference here - it was used Rewarded Ad instead of Rewarded Interstitial Ad.

**Comment by desouse** [comment]
I have just also tried UnityAdsUnityAdapter-2.7.0 and met the same issue.
![unityRewardBug](https://user-images.githubusercontent.com/9247348/128317159-efdcc4a9-493a-4ec3-a662-01a368440388.png)

**Comment by NVentimiglia** [comment]
Ok, I am still unable to replicate. 

What I would like you to do is open up a case (here, on the google admob sdk support group)[https://groups.google.com/g/google-admob-ads-sdk] and link this github issue. If you can include a minimal sample of this issue, I would love to fix this.

**Comment by desouse** [comment]
Done.
https://groups.google.com/g/google-admob-ads-sdk/c/ZMgTQfg2YTs

**Comment by NVentimiglia** [comment]
I was unable to replicate this issue with the AppLovin plugin. When testing AdReword showed before AdClose, as expected. I have included my demo code below.


```
    public void RequestAndLoadRewardedAd()
    {
        statusText.text = "Requesting Rewarded Ad.";

        // create new rewarded ad instance
        rewardedAd = new RewardedAd(adUnitId);

        rewardedAd.OnAdClosed += (sender, args) =>
        {
            MobileAdsEventExecutor.ExecuteInUpdate(() => {
                UnityEngine.Debug.Log("OnAdClosed");
            });

        };
        rewardedAd.OnUserEarnedReward += (sender, args) =>
        {
            MobileAdsEventExecutor.ExecuteInUpdate(() => {
                UnityEngine.Debug.Log("OnUserEarnedReward");
            });

        };

        // Create empty ad request
        rewardedAd.LoadAd(CreateAdRequest());
    }
```

**Comment by vizgl** [comment]
Got OnAdReceivedReward callback just after OnAdClosed fired. Found this issue when show UnityAds ads through mediation.
So, users didn't received rewards, because I check reward in the OnAdClosed callback
