### ISSUE TITLE
Reward Event not working on IOS

### ISSUE THREAD

**Issue by Archi97** [googleads/googleads-mobile-unity#1690]
### Environment

  * Unity version: 2020.3.4
  * Google Mobile Ads Unity plugin version: 6.0.1
  * Platform: IOS
  * Platform OS version: 14.4, 12
  * Mediation ad networks used, and their versions: Unity Ads Mediation(last version)

### The problem
On Awake function I'm hooking the events for rewarded Ad (check code section below)
The problem is that the Rewarded and Closed events are hooked, but they are never called.
after watching 5sec test ad, must work Rewarded event, and after closing - Closed event.  But they do not work. 
Other 2(opening and loading) are working great.
 Also same code works for Android perfectly.
 
 [EDIT]
 I have tested in empty project with test and production ad, both worked well. 
 But on main app both doesnt work.    What I noticed Test ad on Empty Project is 30 Sec long(like normal ad), on main app it is only 5 sec long ad.  Could it mean something? 

#### Relevant Code:
```
rewardedAd.OnAdLoaded += OnAdLoadedEvent;   //Working
rewardedAd.OnAdOpening += OnAdOpeningEvent; //Working
rewardedAd.OnUserEarnedReward += OnAdRewardedEvent; //NotWotking
rewardedAd.OnAdClosed += OnAdClosedEvent; // NotWroking

private void OnAdRewardedEvent(object sender, Reward args) {...}
private void OnAdClosedEvent(object sender, EventArgs e){...}
```

**Comment by NVentimiglia** [comment]
Can you provide more details on the problem? If I were going to fix this issue, the first thing I would do is test on an empty project; something you just tried to do. On the empty project, did you try with the 30 second long normal ads?

**Comment by Archi97** [comment]
> Can you provide more details on the problem? If I were going to fix this issue, the first thing I would do is test on an empty project; something you just tried to do. On the empty project, did you try with the 30 second long normal ads?

I have tried to do in Empty project,  and everything is working correctly. 
Then I added new scene in my project, and tested Ad's there, again, all works great. 
but in my main scenes,  the AdClosed and rewarded events dosn't work.

**Comment by vfilho** [comment]
Hi guys, we are facing the same issue but we aren't calling the LoadAd on the OnAdOpeningEvent. Android working properly, iOS freezing the video after 5 seconds. 
- Unity 2019.4.18f1
- Admob 6.0.1

**Comment by vfilho** [comment]
> Hi guys, we are facing the same issue but we aren't calling the LoadAd on the OnAdOpeningEvent. Android working properly, iOS freezing the video after 5 seconds.
> 
> * Unity 2019.4.18f1
> * Admob 6.0.1

The problem was happening in the code I had to certify that the audio was enabled. I added this code before because of a problem with the last Admob version.

**Comment by ericleich** [comment]
Good callout from @vfilho. Essentially, you do not want to drop the reference to the RewardedAd object until after you are completely done with it (e.g. after onAdClosed). If you drop the reference in C#, a [destructor](https://github.com/googleads/googleads-mobile-unity/blob/1d24d1526f044f886d09dda7b44c352841b208b8/source/plugin/Assets/GoogleMobileAds/Platforms/iOS/RewardedAdClient.cs#L150-L159) will be called, which will clear out our reference to the iOS object to prevent memory leaks. Once this link breaks, all future callbacks would not be called because the OS is cleaning up that memory.

If you want to load a new rewarded ad at open time, you'll need a separate RewardedAd object (or some array of cached ads), but make sure to keep the reference to the currently showing ad until you no longer care about any more callbacks from it.

**Comment by hippogamesunity** [comment]
The same here.
This also worked for me.
`I have removed LoadAd() from AdOpen Event, and now everything works.`
I wonder why it works on Android but not on iOS. Does reloading ads from AdOpen Event is a bad idea?

**Comment by NVentimiglia** [comment]
@Archi97 I am still unable to replicate this issue. I have bound up `LoadAd()` to `rewardAd.Show()` and everything worked as expected. I recommend you keep your work around. If you need functionality please open a support ticket [here](https://groups.google.com/g/google-admob-ads-sdk), and include your app id, ad unit id/s, and a sample app with this issue.
