### ISSUE TITLE
Apps IDs disappears for no reason

### ISSUE THREAD

**Issue by svprdga** [googleads/googleads-mobile-unity#1692]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.13f1 Personal
  * Google Mobile Ads Unity plugin version: 6.0.1
  * Platform: Unity Editor (iOS, Android, Unity Editor)
  * Platform OS version: Windows 10 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem

The app IDs disappear for no reason from time to time.

#### Steps to reproduce:

1. Install the plugin
2. Work arround, close the project, open it again...the IDs will disappear at some point.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by Archi97** [comment]
Same here.  Just opened the code and replaced String.Empty with my IDs

**Comment by Hetagkaty** [comment]
Будем ждать фикс

**Comment by madTeddy** [comment]
Check this pull request (#1695), should solve the problem.

**Comment by NVentimiglia** [comment]
Thanks, for the report and the pull request. I will be sure to include a fix.
