### ISSUE TITLE
GoogleMobileAdsSettings not saving changes

### ISSUE THREAD

**Issue by madTeddy** [googleads/googleads-mobile-unity#1694]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2018.4.36f1
  * Google Mobile Ads Unity plugin version: 6.0.1
  * Platform: Unity Editor (iOS, Android, Unity Editor)
  * Platform OS version: Windows 10 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:

1. Enter Android/iOS id in **GoogleMobileAdsSettings** scriptable object
2. Restart the Unity
3. There is empty fields again

**Comment by frenkyoptic** [comment]
Same issue on macOS unity 2020.3.14f1

**Comment by pedro15** [comment]
I still have this problem in unity 2020.3.16f1 
Plugin version: 6.1.1

**Comment by pedro15** [comment]
I fixed it :)
#1803
