### ISSUE TITLE
 App ID Disappearing every Save/Open/Build

### ISSUE THREAD

**Issue by bhavin2707** [googleads/googleads-mobile-unity#1703]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: All the unity versions (Actively using 2020.1.4f1)
  * Google Mobile Ads Unity plugin version: v6.0.1
  * Platform: Unity Editor (iOS, Android, Unity Editor)
  * Any specific devices issue occurs on: Unity Editor

### [REQUIRED] Step 2: Describe the problem
The App ID keeps disappearing from the GoogleMobileAdsSettings at Assets/GoogleMobilesAds/Resources every time I Open the project, save it or build it. The App ID just disappears and I have to go to settings and add App ID every time I want to build the app.

#### Steps to reproduce:
Simply use the latest plugin (v6.0.1, Add the App ID in the google mobile ad settings and simply make a build or reopen the project or just work for a while. The App ID will disappear.

**Comment by bab202** [comment]
Current simple workaround for this issue is check `Delay app measurement` to true on the GoogleMobileAdsSettings. Then app ids will be saved.

**Comment by Archi97** [comment]
Just open that script and instead of String.Empty put your keys

**Comment by dinukapj** [comment]
Same here. It happens repeatedly for me everytime I build

**Comment by NVentimiglia** [comment]
Hi Everyone,

This is a known issue and we do have a fix in the pipeline.
