### ISSUE TITLE
Api Update Required

### ISSUE THREAD

**Issue by FreeLearningApps** [googleads/googleads-mobile-unity#1705]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.14f1
  * Google Mobile Ads Unity plugin version: 6.0.2
  * Platform: Unity Editor
  * Platform OS version: Windows 10

#### Steps to reproduce:

What happened? How can we make the problem occur?
When I import the package to Unity 2020, Unity asks me to use the Update API.
Both when I activate it and when I don't activate it, the project shows no errors. What should I do?

![Image](https://user-images.githubusercontent.com/83022092/126008652-c323e545-19cd-4249-959e-39cebdaad4a0.png)

**Comment by NVentimiglia** [comment]
You can press "I Made a Backup. Go Ahead!"

**Comment by FreeLearningApps** [comment]
Not showing errors is a Unity bug, check here:
https://issuetracker.unity3d.com/issues/errors-are-not-thrown-when-user-declines-to-run-api-updater-for-imported-package-with-obsolete-methods

**Comment by ksnerv** [comment]
hi i also encountered this pop up. i selected "no thanks" and also received ZERO warnings/errorss after? is that normal? or should i update manually like the instruction said? is updating the api also safe?

**Comment by ksnerv** [comment]
Im f*cked. i clicked no thanks and now im trying to manualy run the API updater but its actually not available. the Run Api Updater from the menu. would i need to revert all the changes i commited? and start all over again ?

**Comment by FreeLearningApps** [comment]
It's a bit late but maybe someone can help. In case you pressed "No thanks", to be sure you can manually delete the package folders and re-import it (and press yes when prompted by the API Updater).

If you press "No thanks" no errors or warnings are shown, but I think the guys developing this package should fix this, because Unity has marked the bug as "Won't fix" and they say they can't do anything.

**Comment by ewinAT** [comment]
> ### [REQUIRED] Step 1: Describe your environment
> * Unity version: 2020.3.14f1
> * Google Mobile Ads Unity plugin version: 6.0.2
> * Platform: Unity Editor
> * Platform OS version: Windows 10
> 
> ### [REQUIRED] Step 2: Describe the problem
> #### Steps to reproduce:
> What happened? How can we make the problem occur? When I import the package to Unity 2020, Unity asks me to use the Update API. Both when I activate it and when I don't activate it, the project shows no errors. What should I do?
> 
> ![Image](https://user-images.githubusercontent.com/83022092/126008652-c323e545-19cd-4249-959e-39cebdaad4a0.png)
