### ISSUE TITLE
[iOS] InterstitialAd.OnAdClosed is never called

### ISSUE THREAD

**Issue by adbourdages** [googleads/googleads-mobile-unity#1709]
#### Step 1: Describe your environment

  * Unity version: 2019.4.16f1
  * Google Mobile Ads Unity plugin version: 6.0.1
  * Platform: iOS
  * Platform OS version: 14.6
  * Any specific devices issue occurs on: iPhone 11 Pro
  * Mediation ad networks used, and their versions: none

#### Step 2: Describe the problem

OnAdClosed is never called on iOS. Same project on Android correctly receives the callback

```
      interstitialCancellable = new InterstitialAd(_adUnitId);
      [...]
      interstitialCancellable.OnAdClosed += delegate
      {
         if( debugOutput )
            Debug.Log("[AdmobInterstitial] ad closed");
         interstitialCancellable?.Destroy();
         interstitialCancellable = null;
      };

```

#### Steps to reproduce:

Nothing special, just show an ad in-game then dismiss it. Make sure the OnAdClosed should output something in the log then watch it not show up

**Comment by NVentimiglia** [comment]
Hello @adbourdages,

I was unable to replicate the issue. I modified the sample GoogleAdMobeController.cs, adding a handler on line 168 to print out a message when OnAdClosed was called. It worked.

`interstitialAd.OnAdClosed += (sender, args) => statusText.text = "OnAdClosed";`

Is this only on iPhone 11 Pro? Have you tested this on any other devices or the simulator?

I was testing on the simulator.

**Comment by thangvu207** [comment]
interstitial.OnAdClosed not call in my iphone XR

**Comment by thangvu207** [comment]
MobileAds.SetiOSAppPauseOnBackground(true) only work with rewarded video. Game still play when Interstitial show

**Comment by adbourdages** [comment]
I can perform further tests on different devices but for next week only unfortunately. I haven't tested on the simulator.
