### ISSUE TITLE
RewardedAd Failed to show with error code 5 and low latency

### ISSUE THREAD

**Issue by adbourdages** [googleads/googleads-mobile-unity#1710]
### Step 1: Describe your environment

- Unity version: 2019.4.16f1
- Google Mobile Ads Unity plugin version: 6.0.1
- Platform: iOS
- Platform OS version: 14.6
- Any specific devices issue occurs on: iPhone 11 Pro
- Mediation ad networks used, and their versions: none

### Step 2: Describe the problem

```
Error: Error Domain=com.google.admob Code=5 "Request Error: The Google ad request was unable to be fulfilled before a timeout occurred." UserInfo={NSLocalizedDescription=Request Error: The Google ad request was unable to be fulfilled before a timeout occurred.}
    Latency: 2.701
```

- Please note the extremely short latency here (which I understand is how long before the timeout occurs). 
- It doesn't happen on all devices
- Once a device exhibits this behaviour, it keeps doing so. Restarting the app doesn't help. Restarting the device doesn't help.
- AppTransparencyTracking is implemented and returns Authorized
- I have reports of a similar thing happening on Android but haven't been able to get my hands on a device that has the issue
- The targetted adUnit is not part of any mediation groups
- Sometimes, the first time a RewardedAd is requested after the app loads, everything works correctly. Subsequent requests fail with the error message

#### Steps to reproduce:

There are no specific steps to reproduce unfortunately. It just happens for some devices.

#### Theorycrafting

- The latency displayed in the error is so low, it feels like it comes internally from the AdMob servers, not from a phone->server connection timeout
- If that is the case, why is this different that an error code 3: No inventory?

#### Relevant Code:

Here is the code for loading a RewardedAd.

```
   void LoadAd()
   {      
      if( debugOutput )
         Debug.Log("[AdmobRewardedAd] Loading an ad");
      
      _rewardedAd = new RewardedAd(_videoAdUnit);

      _rewardedAd.OnAdLoaded += delegate
      {
         if( debugOutput )
            Debug.Log("[AdmobRewardedAd] AdLoaded");
         // the state is ignored when pre-loading
         _videoAdLoadingResult = VideoAdDirectLoadingResult.Success;
      };
      _rewardedAd.OnAdFailedToLoad += delegate(object sender, AdFailedToLoadEventArgs args) 
      {       
         Debug.Log("[AdmobRewardedAd] AdFailedToLoad. Details follow.");
         Debug.Log($"[AdmobRewardedAd] Failed to load, error details: {args.LoadAdError}");
         // the state is ignored when pre-loading
         _videoAdLoadingResult = VideoAdDirectLoadingResult.Failed;
      };
      _rewardedAd.OnAdOpening += delegate
      {
         if( debugOutput )
            Debug.Log("[AdmobRewardedAd] AdOpening");
      };
      _rewardedAd.OnAdFailedToShow += delegate(object sender, AdErrorEventArgs args)
      {
         if( args.AdError != null )
            Debug.Log($"[AdmobRewardedAd] AdFailedToShow, message: {args.AdError.GetMessage()}");
         else
            Debug.Log("[AdmobRewardedAd] AdFailedToShow, missing AdError");
         _videoAdPlayingStatus = VideoAdPlayingStatus.FailedToShow;
      };
      _rewardedAd.OnUserEarnedReward += delegate
      {
         if( debugOutput )
            Debug.Log("[AdmobRewardedAd] UserEarnedReward");
         _videoAdCompletion = VideoAdCompletionStatus.Completed;
      };
      _rewardedAd.OnAdClosed += delegate
      {
         if( debugOutput )
            Debug.Log("[AdmobRewardedAd] AdClosed");
         _videoAdPlayingStatus = VideoAdPlayingStatus.Closed;
         // prepare the next ad
         LoadAd();
      };

      // Create an empty ad request.
      AdRequest request = new AdRequest.Builder().Build();
      // Load the rewarded ad with the request.
      _rewardedAd.LoadAd(request);
   }

```

**Comment by ericleich** [comment]
@adbourdages The information here does point to an underlying iOS issue with the Google Mobile Ads SDK or deeper in the stack, not the plugin itself. I recommend going through the [SDK support forum](https://groups.google.com/group/google-admob-ads-sdk) as the proper channel.

At quick glance, the latency does seem fast for a timeout. The support team on the forum will likely ask for a reproducible sample and/or Charles log to investigate further.
