### ISSUE TITLE
How to extract GoogleMobileAdsXXXMediation.unitypackagefrom the zip file?

### ISSUE THREAD

**Issue by javis007** [googleads/googleads-mobile-unity#1712]
How to extract GoogleMobileAdsXXXMediation.unitypackagefrom the zip file?

After downloading, we only have folders and no unitpackage files. We also tried to import files using create local packages, but this is different from the guided steps.
Please tell me how to obtain each Mediation.unitypackage?

**Comment by NVentimiglia** [comment]
Hello Javis007,

Thank you for reaching out. I will be happy to help you with installing the mediation unity package.

Here are the steps I take when installing the sample.

- Download the latest release, found [here](https://github.com/googleads/googleads-mobile-unity/releases).
- Make sure my project is open and Install the latest release by double clicking on it. 
- Find the mediation package I want, found [here](https://developers.google.com/admob/unity/mediate).
- These downloads are generally at the bottom with the change log.
- Extract the .unitypackage from the zip file download.
- Make sure my project is open and Install the latest release by double clicking on it. 

If I might ask, which mediation package were you installing? That way I can review and clarify the steps.

Please do not hesitate to reach out if you have any more questions.

**Comment by javis007** [comment]
Version 5.1.0
Supports AppLovin Android adapter version 10.3.1.0.
Supports AppLovin iOS adapter version 10.3.2.0.


We have been clicking until the link "Supports AppLovin Android adapter version 10.3.1.0"
Turns out to click on the link "Version 5.1.0"

thank you for your help

**Comment by javis007** [comment]
Solved the problem
