### ISSUE TITLE
READ_PHONE_STATE & WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by FreeLearningApps** [googleads/googleads-mobile-unity#1715]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.4.14
  * Google Mobile Ads Unity plugin version: 6.0.2
  * Platform: Android (iOS, Android, Unity Editor)

### [REQUIRED] Step 2: Describe the problem

I tried to upload an app to the Play Store by updating the GMA Unity Plugin to version 6.0.2, and Play Console warns me that users will have to accept these new permissions (READ_PHONE_STATE & WRITE_EXTERNAL_STORAGE). Are they really necessary? I haven't read anything about it in all the various release notes. Or is it a bug?

Here you find the question asked on the "Google Mobile Ads SDK Technical Forum" with some screenshots:
https://groups.google.com/g/google-admob-ads-sdk/c/pflZhPaq5wo/m/yR9GJNnsAgAJ?utm_medium=email&utm_source=footer

**Comment by NVentimiglia** [comment]
Hello,

Thank you for reaching out to us. However, I'm afraid that we only support the AdMob API on this forum. For Mobile Ads SDK related concerns, I recommend posting to the Google Mobile Ads SDK Developers forum for further assistance.

All the best,
