### ISSUE TITLE
System.TypeInitializationException: The GoogleMobileAds.Android.MobileAdsClient'

### ISSUE THREAD

**Issue by jonathan84clark** [googleads/googleads-mobile-unity#1717]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: Unity 2019.4.14f1 Personal
  * Google Mobile Ads Unity plugin version: v6.0.2
  * Platform: Android
  * Platform OS version: Android 9
  * Any specific devices issue occurs on: All mobile devices I tested on
  * Mediation ad networks used, and their versions: None

### [REQUIRED] Step 2: Describe the problem
When initializing Google mobile ads I get the following exception
System.TypeInitializationException: The GoogleMobileAds.Android.MobileAdsClient' threw an exception. --> UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException:com.google.android.gms.ads.initialization.OnInitializationCompleteListener at UnityEngine.AndroidJNISafe.FindClass (System.String name)
There is more to this but since it ONLY occurs on a mobile device I have to output the error to a Unity UI text object

#### Steps to reproduce:

1. Create a gameobject
2. Attach a script to that gameobject with the following in the Start function:
`	
void Start () 
{
    MobileAds.Initialize(initStatus => { });
}
`

#### Relevant Code:
`	
void Start () 
{
    MobileAds.Initialize(initStatus => { });
}
`

#### Other Info:
When debugging the problem the first issue I ran into was the following
`this.rewardedAd = new RewardedAd(adUnitId);`
Returns a null ptr but only on Mobile devices, in the editor this actually works and I am able to view a test Ad. I was actually able to get this to work in the editor without calling MobileAds.Initialize(initStatus => { });, so I added the initialize function (assuming that was why a null ptr was being returned) and now the code is getting stuck there.

Any help on this would be great. Right now I have probably 15 apps that will eventually need to be updated to the latest version of Google Ad mob, as it is continually changing. I am reluctant to make changes knowing that it may just break all of my ads.

I also noticed a bug where the Google App ID field gets cleared each time I open Unity (this is already documented though). 

Do I need a newer version of Unity to get this working? I would rather not upgrade since Unity keeps removing features from their product that I end up having to build myself from scratch.

Thanks,

Jonathan L Clark

**Comment by NVentimiglia** [comment]
Hello jonathan84clark,

I will be happy to look into this android null pointer exception. 

For me to assist you, can you please send a zip file of the project to [mobileadstesting99@gmail.com](mobileadstesting99@gmail.com) and reference [this post #1717](https://github.com/googleads/googleads-mobile-unity/issues/1717).

Thanks,

**Comment by jonathan84clark** [comment]
The project size (after removing the obj and Library directories) is 300Mb. This is a large project, that has been on the Google Play Store since 2018. I am needing to do some updates to the project however the old Google Ad mob API seems to no longer be working. Where can send the 300Mb zip file?

**Comment by jonathan84clark** [comment]
Where can I send a 300Mb zip file? I'm willing to send my project but I need another way to upload it. 

By the way, what version of Unity was the latest Google Ads SDK made with and tested with? Do you perform regression testing or is there just one version of Unity that you use?

**Comment by diyapkaba** [comment]
I have a similar issue. If you have any solution could you post here

**Comment by jonathan84clark** [comment]
It's been a while but I think you have to upgrade to the latest version of Google Ads. When you do this, you need to delete ALL other Google APIs and then re-import them. 

The Google Ads API also a conflict with the Google Play Games API (I'm not sure how much integration testing is done with the two APIs together in the same project). So last year I pulled Google Play Games from ALL my apps. I'm building a server-based score management system that doesn't involve any of the Google APIs. My API will be based on simple HTTPS requests. 

When you update to the latest version of Google Ads you will also need to update your code to the current method of requesting ads. This changes about every 6 months (just to keep you on your toes).
