### ISSUE TITLE
"The given key was not present in the dictionary" when making custom AdSize

### ISSUE THREAD

**Issue by LuanHimmlisch** [googleads/googleads-mobile-unity#1719]
* Unity version: 2020.3.14f1
  * Google Mobile Ads Unity plugin version: 6.0.2
  * Platform: Unity Editor
  * Platform OS version: Android 9

#### Steps to reproduce:

Try to make a new `AdSize` and then a `BannerView` using it.

**Log:**

```
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <695d1cc93cca45069c528c15c9fdd749>:0)
GoogleMobileAds.Unity.BannerClient.CreateBannerView (System.String adUnitId, GoogleMobileAds.Api.AdSize adSize, System.Int32 x, System.Int32 y) (at <9b4f7ff1297e48c5b72f5a695ad603e7>:0)
GoogleMobileAds.Api.BannerView..ctor (System.String adUnitId, GoogleMobileAds.Api.AdSize adSize, System.Int32 x, System.Int32 y) (at <661a0076c1404a4a859161a7abcf0253>:0)
SpamManager.RandomAd ()
```

#### Relevant Code:

```

// This works
// AdSize bannerSize = AdSize.Banner;

// This is from the docs and it doesn't works
AdSize bannerSize = new AdSize(250, 250);

// And this is what I'm trying to do, but once again it doesn't works
// AdSize bannerSize = new AdSize(UnityEngine.Random.Range(320, maxWidth+1), UnityEngine.Random.Range(50, maxHeight+1));

// This is the line that throws the error
bannerView = new BannerView(bannerId, bannerSize, (int) pos.x, (int) pos.y);

// Create an empty ad request.
AdRequest request = new AdRequest.Builder().Build();

// Load banner with the request
bannerView.LoadAd(request);

```

**Comment by NVentimiglia** [comment]
Hello LuanHimmlisch,

I confirmed that dynamic banner ad sizing is not supported with the Unity3d editor implementation of the client. This functionality is however supported with the android and iOS implementations, so you will be fine when testing on a live device.

For the Unity3d editor implementation, please use the banner standard sizes.

public static readonly AdSize Banner = new AdSize(320, 50);
public static readonly AdSize MediumRectangle = new AdSize(300, 250);
public static readonly AdSize IABBanner = new AdSize(468, 60);
public static readonly AdSize Leaderboard = new AdSize(728, 90);
public static readonly AdSize SmartBanner = new AdSize(0, 0, Type.SmartBanner);
public static readonly int FullWidth = -1;

Regards,

**Comment by LuanHimmlisch** [comment]
@NVentimiglia thanks. If there could be a way to implement dynamic banners on the Unity Editor would be very nice when testing
