### ISSUE TITLE
Cannot build in ios device. (iPad Mini 1st gen)

### ISSUE THREAD

**Issue by heha** [googleads/googleads-mobile-unity#172]
I used sdk version 3.0.0 and try to display ads. It's working fine on android. However, in ios, it cannot be built. I tried version 3.0.1 but it did not work as well. An error said:

TestProject/XCode/Libraries/Plugins/iOS/GADURequest.m:4:9: Module 'GoogleMobileAds' not found

Its code that line is:

@import GoogleMobileAds;

Or is there some binary that I should grab before able to use it unlike the android version?

**Comment by rampara** [comment]
Marking as closed since you indicated you solved this problem.
