### ISSUE TITLE
Metrics Google Analytics

### ISSUE THREAD

**Issue by mrongoz** [googleads/googleads-mobile-unity#1729]
im not see for setting Analytics on Assets > Google Mobile Ads > Settings .
And Metrics on Admob, I've been waiting a week and the metrics are not showing up.

**Comment by NVentimiglia** [comment]
Hi @mrongoz 

I am not sure what are asking in regards to the Google Mobile Ads > Settings context menu. 

For account specific questions, you can raise a request [at the support form](https://groups.google.com/g/google-admob-ads-sdk). Please be sure to [include your App Id/s and Ad Unit Id/s.](https://support.google.com/admob/answer/7356431?hl=en).
