### ISSUE TITLE
Please close my previous issue and this issue.

### ISSUE THREAD

**Issue by heha** [googleads/googleads-mobile-unity#173]
I want to close the issue by myself but github did not allow me to. Always show me an error. I wrote some instruction for newbie below:
1. Open Mac's terminal up.
2. Type "sudo gem install cocoapods" // This will install cocoapods for you. It's dependency management used for automatically install native library. In this case, Native Google Admobs iOS SDK.
3. Open XCode project via Unity-iPhone.xcworkspace NOT Unity-iPhone.xcodeproj. If not, you will get a compilation error.
4. Build it like normal. Now, it's working!

**Comment by rampara** [comment]
Glad you were able to get it working.
