### ISSUE TITLE
Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by mudassar024** [googleads/googleads-mobile-unity#1734]
###  Environment

  * Unity version: 2020.3.14f1
  * Google Mobile Ads Unity plugin version: v6.0.2
  * Platform:  Android
  * Mediation ad networks used, and their versions: IronSourceUnityAdapter-2.0.3

### Problem
Could not resolve com.google.android.gms:play-services-measurement-base:[17.5.0]
Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.

Could not GET 'https://dl.bintray.com/ironsource-mobile/android-sdk/com/google/android/gms/play-services-measurement-sdk-api/maven-metadata.xml'. Received status code 403 from server: Forbidden
#### Steps to reproduce:

Import Google Mobile ads plugin and IronSource Unity Adapter
Go to project settings/publish settings
Tick Custom Main Gradle Template
Tick Custom Gradle Properties Template
Force resolve android dependencies .
Create android build.
Android build will fail with this error
#### Error Log:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':unityLibrary:generateReleaseRFile'.
> Could not resolve all task dependencies for configuration ':unityLibrary:releaseCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-measurement-base:[17.5.0].
     Required by:
         project :unityLibrary > com.google.android.gms:play-services-measurement:17.5.0
         project :unityLibrary > com.google.android.gms:play-services-measurement-api:17.5.0
         project :unityLibrary > com.google.android.gms:play-services-measurement-sdk:17.5.0
         project :unityLibrary > com.google.android.gms:play-services-measurement-impl:17.5.0
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > Unable to load Maven meta-data from https://dl.bintray.com/ironsource-mobile/android-sdk/com/google/android/gms/play-services-measurement-base/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/ironsource-mobile/android-sdk/com/google/android/gms/play-services-measurement-base/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/ironsource-mobile/android-sdk/com/google/android/gms/play-services-measurement-base/maven-metadata.xml'. Received status code 403 from server: Forbidden
   > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:[17.5.0].
     Required by:
         project :unityLibrary > com.google.android.gms:play-services-measurement-api:17.5.0
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > Unable to load Maven meta-data from https://dl.bintray.com/ironsource-mobile/android-sdk/com/google/android/gms/play-services-measurement-sdk-api/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/ironsource-mobile/android-sdk/com/google/android/gms/play-services-measurement-sdk-api/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/ironsource-mobile/android-sdk/com/google/android/gms/play-services-measurement-sdk-api/maven-metadata.xml'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by NVentimiglia** [comment]
Hi Mudassar, I this seems like a problem with your environment. have you tried `mvn clean install` ?

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
