### ISSUE TITLE
App Ids are not saved. Need to enter them manually again each time I open the project.

### ISSUE THREAD

**Issue by EtsaiDev** [googleads/googleads-mobile-unity#1738]
Using:
Windows 10 Pro
Unity 2020.3.3f1
Google Mobile Ads Unity Plugin v6.0.2
Unity Collaborate

![GMA](https://user-images.githubusercontent.com/38283476/129544573-39d44e5c-4d64-4a23-948f-ac8b8be3a633.png)

Edit > Google Mobile Ads > Settings...
I need to enter manually App Ids for Android and iOS each time I open the project.
Once I insert Ids and save the project, Unity Collaborate is not detcting/showing any file change.
As I make Android builds through Unity, and App Id is stored locally builds are OK, but the main problem I have is that I'm using Cloud Build for iOS builds, and as App Id is not stored anywhere in the cloud, iOS build is canceled with this error:
`ASSERT: Cancelling DisplayDialog: Google Mobile Ads Error: iOS Google Mobile Ads app ID is empty. Please enter a valid app ID to run ads properly.`

**Comment by matie** [comment]
If you enable "Delay app measurements" and disable it after, it will be saved again somehow.

**Comment by EtsaiDev** [comment]
I edited GoogleMobileAdsSettings.cs file, adding manually App Ids to adMobAndroidAppId and adMobIOSAppId fields. This way changes are uploaded to cloud succesfully.

**Comment by NVentimiglia** [comment]
This is a known issue and will be fixed in a future release.
