### ISSUE TITLE
Android 8 exception using GMA 6.0.2: UnsafeAtomicHelper is broken!	

### ISSUE THREAD

**Issue by matie** [googleads/googleads-mobile-unity#1739]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.15f2
  * Google Mobile Ads Unity plugin version: 6.0.2
  * Platform: Android 
  * Platform OS version: Android 8 
  * Any specific devices issue occurs on: Samsung S7, Samsung A520F
  * Mediation ad networks used, and their versions: none

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

I've simply upgraded the version of google mobile ads from 5.4.0 to 6.0.2 and now it shows errors on at least a Samsung S7 (Android 8) and Samsung A520F, but not at a Samsung s10 (Android 10) for example. Everything seems to work fine, but I don't like those kind of exceptions :-)

- Install google mobile ads 6.02.
- initialize google mobile ads. 

08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 UnsafeAtomicHelper is broken!	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 java.lang.ExceptionInInitializerError	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.dgu.<clinit>(Unknown Source:29)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.dja.a(Unknown Source:0)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.dgv.newTaskFor(Unknown Source:0)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:117)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.dgv.a(Unknown Source:0)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.ads.internal.util.zzj.zza(Unknown Source:19)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.aas.a(Unknown Source:28)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.aif.a(Unknown Source:53)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.aif.a(Unknown Source:27)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.ads.internal.ClientApi.zzh(Unknown Source:6)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.exz.a(Unknown Source:9)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.eye.c(Unknown Source:11)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.eye.a(Unknown Source:79)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.cb.b(Unknown Source:14)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.cb.a(Unknown Source:59)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.ads.MobileAds.initialize(Unknown Source:5)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at android.os.Handler.dispatchMessage(Handler.java:101)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at android.os.Looper.loop(Looper.java:164)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: No field waiters in class Lcom/google/android/gms/internal/ads/dgu; (declaration of 'com.google.android.gms.internal.ads.dgu' appears in /data/app/com.abc.def-Fz8dJt8RgmujOudLxDPAvA==/base.apk)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.dgu$j.<clinit>(Unknown Source:91)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	... 22 more	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 Caused by: java.lang.NoSuchFieldException: No field waiters in class Lcom/google/android/gms/internal/ads/dgu; (declaration of 'com.google.android.gms.internal.ads.dgu' appears in /data/app/com.abc.def-Fz8dJt8RgmujOudLxDPAvA==/base.apk)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at java.lang.Class.getDeclaredField(Native Method)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.dgu$j.<clinit>(Unknown Source:20)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	... 22 more	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 SafeAtomicHelper is broken!	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 java.lang.RuntimeException: java.lang.NoSuchFieldException: No field thread in class Lcom/google/android/gms/internal/ads/dgu$k; (declaration of 'com.google.android.gms.internal.ads.dgu$k' appears in /data/app/com.abc.def-Fz8dJt8RgmujOudLxDPAvA==/base.apk)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:338)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater.newUpdater(AtomicReferenceFieldUpdater.java:109)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.dgu.<clinit>(Unknown Source:46)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.dja.a(Unknown Source:0)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.dgv.newTaskFor(Unknown Source:0)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:117)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.dgv.a(Unknown Source:0)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.ads.internal.util.zzj.zza(Unknown Source:19)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.aas.a(Unknown Source:28)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.aif.a(Unknown Source:53)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.aif.a(Unknown Source:27)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.ads.internal.ClientApi.zzh(Unknown Source:6)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.exz.a(Unknown Source:9)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.eye.c(Unknown Source:11)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.eye.a(Unknown Source:79)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.cb.b(Unknown Source:14)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.internal.ads.cb.a(Unknown Source:59)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.google.android.gms.ads.MobileAds.initialize(Unknown Source:5)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at android.os.Handler.dispatchMessage(Handler.java:101)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at android.os.Looper.loop(Looper.java:164)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 Caused by: java.lang.NoSuchFieldException: No field thread in class Lcom/google/android/gms/internal/ads/dgu$k; (declaration of 'com.google.android.gms.internal.ads.dgu$k' appears in /data/app/com.abc.def-Fz8dJt8RgmujOudLxDPAvA==/base.apk)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at java.lang.Class.getDeclaredField(Native Method)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:320)	
08-16 12:12:27.675	com.abc.def	26643	26710	E	dgu     	 	... 23 more	
08-16 12:12:27.683	com.abc.def	26643	26710	D	ConnectivityManager	 requestNetwork; CallingUid : 10398, CallingPid : 26643	
08-16 12:12:27.687	com.abc.def	26643	26710	I	Ads     	 Updating ad debug logging enablement.	
08-16 12:12:27.750	com.abc.def	26643	28596	W	Ads     	 Update ad debug logging enablement as false	
08-16 12:12:27.794	com.abc.def	26643	28595	E	dhh     	 SafeAtomicHelper is broken!	
08-16 12:12:27.794	com.abc.def	26643	28595	E	dhh     	 java.lang.RuntimeException: java.lang.NoSuchFieldException: No field seenExceptions in class Lcom/google/android/gms/internal/ads/dhh; (declaration of 'com.google.android.gms.internal.ads.dhh' appears in /data/app/com.abc.def-Fz8dJt8RgmujOudLxDPAvA==/base.apk)	
08-16 12:12:27.794	com.abc.def	26643	28595	E	dhh     	 	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:338)	
08-16 12:12:27.794	com.abc.def	26643	28595	E	dhh     	 	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater.newUpdater(AtomicReferenceFieldUpdater.java:109)	
08-16 12:12:27.794	com.abc.def	26643	28595	E	dhh     	 	at com.google.android.gms.internal.ads.dhh.<clinit>(Unknown Source:19)	
08-16 12:12:27.794	com.abc.def	26643	28595	E	dhh     	 	at com.google.android.gms.internal.ads.dib.a(Unknown Source:0)	
08-16 12:12:27.794	com.abc.def	26643	28595	E	dhh     	 	at com.google.android.gms.internal.ads.bqq.a(Unknown Source:269)	
08-16 12:12:27.794	com.abc.def	26643	28595	E	dhh     	 	at com.google.android.gms.internal.ads.bqm.run(Unknown Source:6)	
08-16 12:12:27.794	com.abc.def	26643	28595	E	dhh     	 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)	
08-16 12:12:27.794	com.abc.def	26643	28595	E	dhh     	 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)	
08-16 12:12:27.794	com.abc.def	26643	28595	E	dhh     	 	at java.lang.Thread.run(Thread.java:764)	
08-16 12:12:27.794	com.abc.def	26643	28595	E	dhh     	 Caused by: java.lang.NoSuchFieldException: No field seenExceptions in class Lcom/google/android/gms/internal/ads/dhh; (declaration of 'com.google.android.gms.internal.ads.dhh' appears in /data/app/com.abc.def-Fz8dJt8RgmujOudLxDPAvA==/base.apk)	
08-16 12:12:27.794	com.abc.def	26643	28595	E	dhh     	 	at java.lang.Class.getDeclaredField(Native Method)	
08-16 12:12:27.794	com.abc.def	26643	28595	E	dhh     	 	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:320)	
08-16 12:12:27.794	com.abc.def	26643	28595	E	dhh     	 	... 8 more	

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

**Comment by NVentimiglia** [comment]
Hi matie,

This looks like a complex issue that I wont be able to fix as is. [Please make a request on our support group](https://groups.google.com/g/google-admob-ads-sdk). Please include a downloadable sample project that reproduces the bug, and [include your App Id/s and Ad Unit Id/s.](https://support.google.com/admob/answer/7356431?hl=en).
