### ISSUE TITLE
where can i create REWARD_BASED_VIDEO_AD_UNIT_ID..?

### ISSUE THREAD

**Issue by hkk007** [googleads/googleads-mobile-unity#174]
in  Admob i can create only banner and interstitial.....but how can i create REWARD_BASED_VIDEO_AD_UNIT_ID ?
How is it used pls reply..
Thank you

**Comment by rampara** [comment]
At this time we are working with few publishers we have a close relationship with on the reward based video ads closed beta. If you have an account manager they would be your best point of contact for more information. If you do not have an account manager, unfortunately, you will have to wait for the beta to open up.
