### ISSUE TITLE
AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='' signature='()Ljava/lang/Object;' in class Ljava.lang.Object;

### ISSUE THREAD

**Issue by oddgames-david** [googleads/googleads-mobile-unity#1742]
* Unity version: 2020.3.15f1
  * Google Mobile Ads Unity plugin version: 6.0.2
  * Platform: Android
  * Platform OS version: 8,9,10,11
  * Any specific devices issue occurs on: Very wide range
  * Mediation ad networks used, and their versions: Tapjoy, Unity, FB, AppLovin, latest as of Aug 02.

### [REQUIRED] Step 2: Describe the problem

Receiving many java.lang.NoSuchMethodError: exceptions that aren't clearly defined that originate from adverts

[08/20/2021 14:44:31] <Exception>: AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='' signature='()Ljava/lang/Object;' in class Ljava.lang.Object;
java.lang.NoSuchMethodError: no non-static method with name='' signature='()Ljava/lang/Object;' in class Ljava.lang.Object;
com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:162)
com.unity3d.player.ReflectionHelper.nativeProxyInvoke(Native Method)
com.unity3d.player.ReflectionHelper.a(Unknown Source:0)
com.unity3d.player.ReflectionHelper$1.invoke(Unknown Source:31)
java.lang.reflect.Proxy.invoke(Proxy.java:1006)
$Proxy19.onInterstitialAdFailedToLoad(Unknown Source)
com.google.unity.ads.Interstitial$1$1$4.run(Interstitial.java:174)
java.lang.Thread.run(Thread.java:923)
UnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidReflection.GetMethodMember (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) (at <00000000000000000000000000000000>:0)
UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaObject._Call[ReturnType] (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
GoogleMobileAds.Android.ResponseInfoClient..ctor (GoogleMobileAds.Common.ResponseInfoClientType type, UnityEngine.AndroidJavaObject androidJavaObject) (at <00000000000000000000000000000000>:0)
GoogleMobileAds.Android.LoadAdErrorClient.GetResponseInfoClient () (at <00000000000000000000000000000000>:0)
GoogleMobileAds.Api.LoadAdError.GetResponseInfo () (at <00000000000000000000000000000000>:0)
ODDFramework.AdMobCallbackLogContext.OnAdFailedToLoad (System.Object sender, GoogleMobileAds.Api.AdFailedToLoadEventArgs e) (at <00000000000000000000000000000000>:0)
System.EventHandler`1[TEventArgs].Invoke (System.Object sender, TEventArgs e) (at <00000000000000000000000000000000>:0)
System.EventHandler`1[TEventArgs].Invoke (System.Object sender, TEventArgs e) (at <00000000000000000000000000000000>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, System.IntPtr jmethodName, System.IntPtr jargs) (at <00000000000000000000000000000000>:0)
Rethrow as TargetInvocationException: GoogleMobileAds.Android.InterstitialClient.onInterstitialAdFailedToLoad(UnityEngine.AndroidJavaObject)
UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, System.IntPtr jmethodName, System.IntPtr jargs) (at <00000000000000000000000000000000>:0)

#### Steps to reproduce:

Unfortunately we aren't able to reproduce in our dev builds but we have 1000's of examples from our users from the live app.

**Comment by NVentimiglia** [comment]
I will need a sample to move forward with this. If you are unable to replicate this issue, I am not hopeful that I can replicate this  issue. If you come across any additional information at the root cause, please update us.
