### ISSUE TITLE
Some mediation still seem to require xcode 12.5

### ISSUE THREAD

**Issue by Thaina** [googleads/googleads-mobile-unity#1743]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.1.17f1
  * Google Mobile Ads Unity plugin version: 6.0.2
  * Platform: iOS
  * Mediation ad networks used, and their versions: Adcolony 2.3.0 / Chartboost 3.3.1 / Unity Ads 2.7.1 / Vungle 3.6.0

### [REQUIRED] Step 2: Describe the problem

Build ios was error. With suspicious message `Could not find or use auto-linked framework 'AVFAudio'` and 

#### Steps to reproduce:

Just build normally. Suspect adcolony was the source of the problem. Maybe revert pod to `4.6.0.0` would solve? I try building it currently

#### Relevant Code:

https://forum.unity.com/threads/xcode-12-5-in-ucb.1108451/
https://stackoverflow.com/questions/67448909/xcode-complains-link-error-undefine-symbol-objc-class-skadimpression-af

**Comment by NVentimiglia** [comment]
Thanks for the information. I will look into the issue. I do know that going forward we will be building using XCode 12.5.

**Comment by Thaina** [comment]
> Thanks for the information. I will look into the issue. I do know that going forward we will be building using XCode 12.5.

Unity still having their problem upgrading cloud build to support XCode 12.5 and have no solid timeline when they could support it so would you pleased to consider still sticking with 12.4 for unity in this year?

**Comment by NVentimiglia** [comment]
We currently do not have plans to support 12.4. If this is critical, I suggest raising the issue on [the support form](https://groups.google.com/g/google-admob-ads-sdk).
