### ISSUE TITLE
Native Ads SDK version still updated?

### ISSUE THREAD

**Issue by Nyankoo** [googleads/googleads-mobile-unity#1748]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: _____
  * Google Mobile Ads Unity plugin version: _____
  * Platform: _____ (iOS, Android, Unity Editor)
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:

Is the native ads version of the SDK still updated? The non-native-ads version is quite a few updates ahead.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by NVentimiglia** [comment]
We understand that the unity mobile ads native sdk is behind in versions. We are working on and will release an updated version when it is ready.

**Comment by Nyankoo** [comment]
@NVentimiglia How's the progress on this? Feels a bit like the native ads version for Unity is kinda abandoned.

**Comment by anhnhgtv** [comment]
I am still waiting for the new version of native ads. And i have a problem with native ads. My native ads eCPM only $0.08
