### ISSUE TITLE
Error message about appcompat-v7:23.1.0+

### ISSUE THREAD

**Issue by rgap** [googleads/googleads-mobile-unity#175]
Having these versions.

- Google Play Services: 8.4.0
- Google Mobile Ads Unity Plugin: 3.0.1

Unity shows me this error, and I already updated everything in Android SKD Manager:

Google.JarResolver.ResolutionException: Cannot find candidate artifact for com.android.support:appcompat-v7:23.1.0+
  at Google.JarResolver.PlayServicesSupport.DependOn (System.String group, System.String artifact, System.String version) [0x00000] in <filename unknown>:0 
  at AdMobDependencies..cctor () [0x00039] in /Users/rgap/Desktop/googleads-mobile-unity/samples/HelloWorld/Assets/PlayServicesResolver/Editor/AdMobDependencies.cs:21 
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

**Comment by ericleich** [comment]
Hi there,

The App compat v7 resource comes from the Android support repository in SDK manager. Please also make sure you have that up to date as well.

**Comment by rgap** [comment]
It is up to date

**Comment by rampara** [comment]
Did the JarResolver library copy AARs for the remaining Google Play Services libraries into your 'Plugins/Android' directory?

**Comment by jwangc2** [comment]
I ended up putting a preprocessor flag around the whole static method in the **PlayServicesResolver/Editor/AdMobDependencies.cs** file, because it seems relevant only to the Android build, especially if you are building out for ios only:
```
#if UNITY_ANDROID
PlayServicesSupport svcSupport =
    PlayServicesSupport.CreateInstance(PluginName, EditorPrefs.GetString("AndroidSdkRoot"),
            "ProjectSettings");

svcSupport.DependOn("com.google.android.gms", "play-services-ads", "LATEST");

// Marshmallow permissions requires app-compat.
svcSupport.DependOn("com.android.support", "appcompat-v7", "23.1.0+");
#endif
```

**Comment by rampara** [comment]
Do you have the Android SDK installed on your machine?

**Comment by gsanseverino** [comment]
I had the same problem, and I solved installing the "Local Maven repository for Support Libraries" package from the Android SDK Manager.

**Comment by JACLEMGO** [comment]
@gsanseverino Also had to install "Local Maven...", thanks for the solution!

**Comment by redfist** [comment]
I have sdk, i have Local Maven, still same error massage.

**Comment by redfist** [comment]
![aae87044-eb12-11e5-9281-5a08b8b6a89c](https://cloud.githubusercontent.com/assets/16037907/14018283/40403d0a-f1cd-11e5-905c-d369c5b6b9ce.png)

**Comment by rampara** [comment]
The latest version of the plugin (v3.1.0) will prompt you to download any Google Play services dependencies or Android SDK build tools that are not present on your development machine.
