### ISSUE TITLE
Undefined symbols for architecture arm64:   "_kGADAdLoaderAdTypeNativeCustomTemplate",

### ISSUE THREAD

**Issue by FazalConsoliads** [googleads/googleads-mobile-unity#1752]
* Unity version: 2018.4.3
  * Google Mobile Ads Unity plugin version: https://developers.google.com/admob/unity/native-advanced-unified
  * Platform: iOS
  * Platform OS version: iOS 14

Undefined symbols for architecture arm64:
  "_kGADAdLoaderAdTypeNativeCustomTemplate", referenced from:
      _GADUCreateAdLoader in unity-plugin-library.a(GADUInterface_d33d7a8bcd5f8b475acd733c6a35dc81.o)
  "_OBJC_CLASS_$_GADInterstitial", referenced from:
      objc-class-ref in unity-plugin-library.a(GADUInterstitial_086edb7499729734905adee6bc26babe.o)
     (maybe you meant: _OBJC_CLASS_$_GADInterstitialAd)
  "_kGADAdLoaderAdTypeUnifiedNative", referenced from:
      _GADUCreateAdLoader in unity-plugin-library.a(GADUInterface_d33d7a8bcd5f8b475acd733c6a35dc81.o)
  "_OBJC_CLASS_$_GADRewardBasedVideoAd", referenced from:
      objc-class-ref in unity-plugin-library.a(GADURewardBasedVideoAd_d807ba2a9d3d6d4666121ccb55541cdd.o)

When using the following admob version in pods
Google-Mobile-Ads-SDK 8.9.0

**Comment by NVentimiglia** [comment]
Hi @FazalConsoliads ,

This looks like a complex issue. [Please make a request on our support group](https://groups.google.com/g/google-admob-ads-sdk). Please include a downloadable sample project that reproduces the bug, and [include your App Id/s and Ad Unit Id/s.](https://support.google.com/admob/answer/7356431?hl=en).
