### ISSUE TITLE
Google Mobile Ad Plugin & GPGs

### ISSUE THREAD

**Issue by aquariens** [googleads/googleads-mobile-unity#176]
Hello,

I am having the problem, Versions are: Android SDK 23.1.1 Unity 5.3.2f1 Google Mobile ad V. 3.0.1 and GPGS 8.4.0. Everything goes well until i add google mobile ad plugin.

What i have noticed is that when i include Google Mobile ad plugin it deletes play-services-basement-8.4.0.aar file from plugin\android folder and admob doesn't work as well as GPGs stops working.

Later i try to copy play-services-basement-8.4.0.aar manually but it gets deleted automatically over and over again.

SS included below, 

Shahzad.
![play-services-basement](https://cloud.githubusercontent.com/assets/17455752/13290906/7495c446-db37-11e5-879c-1ed2c723f276.jpg)

**Comment by rampara** [comment]
Have you declared any dependencies for the JarResolver library other than the defaults for the AdMob and Google Play Games plugins? Can you list the contents of your 'Plugins/Android' directory? 

- Ram

**Comment by aquariens** [comment]
Thanks for the reply Ram,

I didn't declare any dependencies, i am just including mobile ads plugin and the issue happens even prior to to any editing in AndroidManifest. Also note that i am not using any other plugin but only GPGs and Admob.

![admob](https://cloud.githubusercontent.com/assets/17455752/13313983/118c6fac-dbc4-11e5-80d3-75f57d38feca.jpg)

Shahzad

**Comment by rampara** [comment]
Using the latest AdMob and Google Play Games plugins in our [sample application](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld), I'm unable to reproduce your problem. If you can link a project that has this issue, I can investigate further.

**Comment by aquariens** [comment]
Dear Ram,

Thanks for your reply that gave me a hint, i created a new project and imported all my asset there, then included both plugins GPGs and Admob and it resolved the issue that i was struggling for over 3 days.

I couldn't really figure what was the problem but it seems there were some unnecessary component preventing proper dependencies resolution.

Thanks again,
