### ISSUE TITLE
Can't build GoogleMobileAds-v6.1.0 + AdColonyUnityAdapter-2.3.0 

### ISSUE THREAD

**Issue by Volodymyr-13** [googleads/googleads-mobile-unity#1761]
* Unity version: 2020.3.17f1
  * Google Mobile Ads Unity plugin version: 6.1.0
  * Platform: iOS
  * Platform OS version: 14.7.1
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: AdColonyUnityAdapter-2.3.0 

#### Steps to reproduce:

Just download latest unitypackages and try to build Xcode project.

#### Relevant Code:

Firstly, this GoogleMobileAds-v6.1.0  has another bug, which is can be fixed like that: https://github.com/googleads/googleads-mobile-unity/issues/1552#issuecomment-903421536

We skipping this, just OK, we fixed, moving next, trying to build iOS:

<img width="1132" alt="Screenshot 1" src="https://user-images.githubusercontent.com/3391456/131870592-0f6d1688-1260-4da5-8cf7-90cb22de1a9e.png">

Sample project: 

[admob.zip](https://github.com/googleads/googleads-mobile-unity/files/7100005/admob.zip)

**Comment by HAL-JP** [comment]
This can be solved.

Step 1
Select Assets-> External Dependency Manager-> iOS Resolver-> Settings.
<img width="2231" alt="スクリーンショット 2021-09-03 21 25 39" src="https://user-images.githubusercontent.com/81759313/132005259-961fca54-9e2c-4d58-bbc4-d5960edd7b2d.png">

Step 2
Enable Link frameworks statically.
<img width="397" alt="スクリーンショット 2021-09-03 21 25 51" src="https://user-images.githubusercontent.com/81759313/132005467-2989f46d-d4f8-4e54-a4cb-ac5732506294.png">

**Comment by KAMIKAZEUA** [comment]
Okay, this is fixing issue with compiling in the Xcode. 
But next, when I started it on the device via Xcode - **it works**.
Then, just tap icon on the main screen, without Xcode - **it's crashing.**

If you then open logs on the device you will found that it's due to app inactivity: 

<img width="283" alt="Screenshot 1" src="https://user-images.githubusercontent.com/3391456/132028165-466912f8-fa26-4cd7-9907-c5f7955b3ae6.png">

**Comment by KAMIKAZEUA** [comment]
So, yes, when I just trying to integrate AdColony - my game is crashing if I'm launching it without Xcode.
Please help!

**Comment by NCoso** [comment]
same issue here
working fine when launching from Xcode but hanged if open directly from iOS device

**Comment by HAL-JP** [comment]
I contact Google about this issue. 
Please wait a little more.

**Comment by hokamakaho** [comment]
GoogleMobileAds > Editor > AdColonyMediationDependencies
Open with VSCode etc.

<iosPod name = "GoogleMobileAdsMediationAdColony" version = “4.5.0.0”>
Edit, version = “4.5.0.0”> “4.7.0.0”

Then save and build.

reference
AdColony iOS Mediation Adapter Changelog
https://github.com/googleads/googleads-mobile-ios-mediation/blob/master/adapters/AdColony/CHANGELOG.md#version-4610

Unity-2019.4.22
Google Mobile Ads Unity plugin version: 6.1.0
AdColonyUnityAdapter-2.3.0

**Comment by KAMIKAZEUA** [comment]
@hokamakaho same issue - game won't launch without Xcode.

**Comment by HAL-JP** [comment]
I found a solution.
I was able to solve it with the solution of @hokamakaho.
If you can't do that, edit the version
Try version = “4.5.0.0”> “4.7.1.0”.

**Comment by KAMIKAZEUA** [comment]
Please share test project, so I can try it, if you was able to fix this.

**Comment by HAL-JP** [comment]
understood. Please try this procedure again before doing so.

step 1
Delete the existing AdMob SDK
Then import the AdMob plugins 6.1.0 and AdColony 2.3.0

Step 2
> This can be resolved.
>> >>
> Step 1
Select Assets-> External Dependency Manager-> iOS Resolver-> Settings.
> <img alt = "Screenshot 2021-09-0321 25 39" width = "2000" src = "https://user-images.githubusercontent.com/81759313/132005259-961fca54-9e2c-4d58-bbc4-d5960edd7b2d. png ">
>> >>
> Step 2
> Statically enable the link framework.
> <img alt = "Screenshot 2021-09-0321 25 51" width = "397" src = "https://user-images.githubusercontent.com/81759313/132005467-2989f46d-d4f8-4e54-a4cb-ac5732506294. png ">

Step 3
Assets / GoogleMobileAds / Editor / AdColonyMediationDependencies
Unzip and overwrite the following files.

[AdColonyMediationDependencies.xml.zip] (https://github.com/googleads/googleads-mobile-unity/files/7121578/AdColonyMediationDependencies.xml.zip)

Step 4
Assets / Plugins / iOS

https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/Plugins/iOS/GADUAdNetworkExtras.h
Add

**Comment by KAMIKAZEUA** [comment]
@HAL-JP Have no idea about what you're talking now, I asked for a complete project, which is working for you. 
Can you please share zip file here, so I can build it on my device? And then run it without Xcode, so it will NOT crash then, as you told me that it's not crashing for you already. By the way on which iOS device(iOS version, model) you're testing this?

**Comment by HAL-JP** [comment]
AdColonyUnityAdapter-2.3.0 Erase from within the project.
Then unzip and import the following:
[DemoAdColony.unitypackage.zip](https://github.com/googleads/googleads-mobile-unity/files/7121778/DemoAdColony.unitypackage.zip)

**Comment by KAMIKAZEUA** [comment]
If you were able to solve it, as you told me here https://github.com/googleads/googleads-mobile-unity/issues/1761#issuecomment-914236869 
please share me a full working project for Unity, so I'll just publish it to iOS and run/test it on the device.

**Comment by HAL-JP** [comment]
Please consult with an official Google person.
https://groups.google.com/g/google-admob-ads-sdk

**Comment by NCoso** [comment]
Still same issue, crashing when running without XCode
I see the app loads quickly if I have AppLovin adapter only (Adcolony adapter removed)
However I see huge app-load time if AdColony adapter is added (Applovin + Adcolony)

**Comment by KAMIKAZEUA** [comment]
Yep and I really wondering why this is not in **highest priority**.

**Comment by NVentimiglia** [comment]
Hi there, I was unable to replicate the issue. Here are my steps.

- Unity version: 2020.3.17f1
- Starting from the HelloWorld Sample
- Installed GoogleMobleAds 6.1.0
- Installed AdColony 2.3.0
- Built iOS project
- Ran pod Install
- Ran iOS project
- played without issue

This said, I have seen this issue before when running UnityEditor 2021. This is a known issue

> Known issue:
> iOS Resolver library cannot be loaded in Unity 2021.1.11 and 2021.1.12. It can be loaded properly with Unity 2021.1.10. See > googlesamples/unity-jar-resolver#441 for more information.

If you are still having issues, the next step would be a sample project.

**Comment by KAMIKAZEUA** [comment]
How it runs without Xcode?

**Comment by NCoso** [comment]
I was able to run the project too, but only via xCode
running from xCode the app laoded and worked as expected
then if xCode is closed and app started from devie directly -> the app crashes at startup
also crashing at startup if installed via IPA export

for now we will remove ADColony adapter, since prevents us from testing and releasing iOS; hoping to get it back once fixed

**Comment by KAMIKAZEUA** [comment]
> then if xCode is closed and app started from devie directly -> the app crashes at startup
Exactly

> for now we will remove ADColony adapter, since prevents us from testing and releasing iOS; hoping to get it back once fixed
Me too.

**Comment by chkuang-g** [comment]
Hey folks, regarding the know issue with iOS Resolver, I have made a workaround and released `1.2.167`.
https://github.com/googlesamples/unity-jar-resolver/issues/441
https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.167

Google Ads Mobile SDK can include the newer version of EDM4U. If you need it right away, you can download either `.unitypackage` version or `.tgz` version (for Unity Package Manager) [here](https://developers.google.com/unity/archive#external_dependency_manager_for_unity)

Cheer

**Comment by dhamelin** [comment]
> @NVentimiglia this bug(another user commented same situation here [#1761 (comment)](https://github.com/googleads/googleads-mobile-unity/issues/1761#issuecomment-921620082)) is still same with v6.1.2 release, when you run without Xcode - **build hangs and crashes.**
> So there is no way to integrate **AdColony** for iOS with **any latest version**, this bug should be live priority, but it's already not been fixed for **months**, this is really sad.

Hello, have you found a solution finally? I'm having the same issue but with Facebook mediation.

**Comment by Northwind877** [comment]
I have the same issue, also the older versions (4.7.1.0, 4.7.0.0) are not working for me.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
