### ISSUE TITLE
6.1.0 fails to build on Xcode 12.4 -- breaking change not communicated?

### ISSUE THREAD

**Issue by aroman** [googleads/googleads-mobile-unity#1762]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.17f1
  * Google Mobile Ads Unity plugin version: 6.1.0
  * Platform: iOS
  * Platform OS version: n/a
  * Any specific devices issue occurs on: n/a
  * Mediation ad networks used, and their versions: none

#### Steps to reproduce:

This project fails to compile under XCode 12.4.x due to a bitcode incompatibility while linking:

```
ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1205.0.22.9.0_0' Reader: '1200.0.32.29_0')', using libLTO version 'LLVM version 12.0.0, (clang-1200.0.32.29)' for architecture arm64
```

The release notes indicate that this 6.1.0 was "built and tested against Xcode 12.5". Does this mean it is intention to drop support for 12.4? If so, I definitely think that breaking change should have been MUCH more explicitly communicated in the release notes...

**Comment by NVentimiglia** [comment]
We currently do not have plans to support 12.4. If this is critical, I suggest raising the issue on the support form.

**Comment by aroman** [comment]
Thank you for clarifying. 

This is a pretty big change to just suddenly drop without any indication in the release notes. Particularly because it means  dropping support for macOS 10, which is still the only option on Unity's first-party Cloud Build offering. This has caused builds to fail for many developers, leading to frustration and confusion in the Unity forums.

In the future (or now, retroactively), please communicate these changes more explicitly in the ChangeLog.txt. That's what it's there for!
