### ISSUE TITLE
l2cppOutput/Assembly-CSharp.cpp:38642: error: undefined reference to 'SDK_Init'

### ISSUE THREAD

**Issue by iamyawer** [googleads/googleads-mobile-unity#1764]
![Capture](https://user-images.githubusercontent.com/58387331/132154583-f6c7049c-6deb-4820-9035-d93d2e415815.PNG)
So this error is being displayed for while building and halts up build at middle. Any leads ?

**Comment by NVentimiglia** [comment]
Hi @iamyawer,

I have not seen this issue, so I wont be able to give you a solution. Please raise a request [at the support form](https://groups.google.com/g/google-admob-ads-sdk). Please be sure to [include your App Id/s and Ad Unit Id/s.](https://support.google.com/admob/answer/7356431?hl=en).
