### ISSUE TITLE
App Open Ads missing in GoogleMobileAds-native.unitypackage

### ISSUE THREAD

**Issue by idzdigital** [googleads/googleads-mobile-unity#1765]
Admob App Open Ads support is now included googleads-mobile-unity package and it working fine. App open ads are still missing in GoogleMobileAds-native.unitypackage. How do I add app open ads in application having native ads as well?

**Comment by NVentimiglia** [comment]
Hi @idzdigital,

This is a known issue and we are working on a solution. We do plan on incorporating app open ads into the native ads package.

**Comment by idzdigital** [comment]
Hi,
