### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by taecg** [googleads/googleads-mobile-unity#177]
I am from the sample project released to the Android, the following is the detailed information:

02-25 13:23:42.203: I/Unity(11258): AndroidJavaException: java.lang.ClassNotFoundException: com.google.unity.ads.UnityBannerAdListener
02-25 13:23:42.203: I/Unity(11258): java.lang.ClassNotFoundException: com.google.unity.ads.UnityBannerAdListener
02-25 13:23:42.203: I/Unity(11258): 	at java.lang.Class.classForName(Native Method)
02-25 13:23:42.203: I/Unity(11258): 	at java.lang.Class.forName(Class.java:217)
02-25 13:23:42.203: I/Unity(11258): 	at java.lang.Class.forName(Class.java:172)
02-25 13:23:42.203: I/Unity(11258): 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
02-25 13:23:42.203: I/Unity(11258): 	at com.unity3d.player.UnityPlayer.a(Unknown Source)
02-25 13:23:42.203: I/Unity(11258): 	at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
02-25 13:23:42.203: I/Unity(11258): Caused by: java.lang.NoClassDefFoundError: com/google/unity/ads/UnityBannerAdListener
02-25 13:23:42.203: I/Unity(11258): 	... 6 more
02-25 13:23:42.203: I/Unity(11258): Caused by: java.lang.ClassNotFoundException: com.google.unity.ads.UnityBannerAdListener
02-25 13:23:42.203: I/Unity(11258): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
02-25 13:23:42.203: I/Unity(11258): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
02-25 13:23:42.203: I/Unity(11258): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
02-25 13:23:42.203: I/Unity(11258): 	... 6 more
02-25 13:23:42.203: I/Unity(11258):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
02-25 13:23:42.203: I/Unity(11258):   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPtr c

I guess I could be integrated in the unity with the wrong way, following my steps:
1. open the sample project.
2. import GoogleMobileAds.unitypackage.
3. copy the whole google-play-services_lib folder under the Plugins/Android/

If I am wrong please also indicate the operation,thanks!

**Comment by rampara** [comment]
With the latest version of our Unity plugin, you no longer have to copy the Google Play Services library project into your Unity project. The [JarResolver](https://github.com/googlesamples/unity-jar-resolver) library will copy the necessary AARs for the required Google Play Services into your Unity project. You can find updated steps to integrate this plugin into your Unity application on our [developer docs](https://developers.google.com/admob/android/games#importing_the_plugin_into_your_game).

**Comment by rampara** [comment]
Closing issue due to non-response. If this issue persists, please re-open.
