### ISSUE TITLE
GoogleMobileAds-v6.1.0 don't show Test Ads using test ad units

### ISSUE THREAD

**Issue by AllanRW** [googleads/googleads-mobile-unity#1770]
Latest release don't show test ads using the test ad units from the docs, only way to show test ads is to add device to Admob console as a test device. I prefer to use test ad units, is this feature removed or its a bug?

**Comment by Marounkattar** [comment]
the same problem can we know why?

**Comment by arksh1** [comment]
i got the same problem.
my plugin version is 6.0.1.
last month, it' ok. but now, i got problem. (same build)

**Comment by horoeil** [comment]
I have the same problem. QQ

Unity 2021.1.20f1
plugin version is 6.1.0

**Comment by Cptweirdo** [comment]
Same problem

Unity 2018.4.26f1
plugin v6.1.0

**Comment by AiMAnsarie** [comment]
Same problem

Unity 2020.3.10f1
Plug-in v6.1.0

**Comment by Mecze** [comment]
+1
Same problem here

**Comment by Mecze** [comment]
On one of our older projects with Admob plugin 4.2.1 it does have the same problem.

**Comment by Mecze** [comment]
Any new on this? we still receiving no test ads
Anyone found a workaround?

**Comment by TheGoodEvilBen** [comment]
The only approach currently working is using real ads with test devices

**Comment by bfaf** [comment]
Same problem with:

Unity 2021.1.22
GoogleMobileAds-v6.1.1

**Comment by khalidhex** [comment]
Christ ! does anybody found a workaround ?

**Comment by kim-young-min** [comment]
You can also test with AD Manager test ad units

https://developers.google.com/ad-manager/mobile-ads-sdk/android/test-ads

**Comment by princetongirl818** [comment]
> Fixed it
> 
> > It works for me - https://developers.google.com/admob/android/test-ads#demo_ad_units ![image](https://user-images.githubusercontent.com/9247348/136167887-35c3c537-4887-4d8a-961f-38979e08ba0a.png)
> 
> Fixed it the same way!

how did you guys fix it? @RicardoGuzmanVelasco @kim-young-min @desouse

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
