### ISSUE TITLE
_OBJC_CLASS_$_GADInterstitialAd

### ISSUE THREAD

**Issue by plutocD** [googleads/googleads-mobile-unity#1773]
* Unity version: __2020.2.1f1____
  * Google Mobile Ads Unity plugin version: __V6.1.0___
  * Platform: __IOS___ (iOS, Android, Unity Editor)
  * Platform OS version: ___IOS12__ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: __Xcode 12.1____
 * GoogleMobileAdsSdkiOS: __V8.10.0____

Xcode ERROR:
"_OBJC_CLASS_$_GADInterstitialAd", referenced from:
      objc-class-ref in unity-plugin-library.a(GADUInterstitial.o)
     (maybe you meant: _OBJC_CLASS_$_GADInterstitialAdBeta)

I Update the UnityPackage to 6.1.0,then the Xcode appear the Error.

How can i solve this problem?

**Comment by NVentimiglia** [comment]
@plutocD Hi there, can you try opening terminal and running `pod install` from the ios project folder?

**Comment by plutocD** [comment]
> @plutocD Hi there, can you try opening terminal and running `pod install` from the ios project folder?

thanks for replay.I run the pod intsall in project folder ,the error disappeard.I usually download GoogleMobileAdsSdk and import the frameworks into my Xcode project,it cause the error.
