### ISSUE TITLE
Need a public GoogleMobileAdsSettings

### ISSUE THREAD

**Issue by programming2012** [googleads/googleads-mobile-unity#1774]
Hi
   The GoogleMobileAdsSettings.cs is a internal class. But i need to fill the AppIDs use script. I can not call the GoogleMobileAdsSettings.Instance. Is there any plan to set it to public in the future？
                       Thanks

**Comment by NVentimiglia** [comment]
Hi programmin2012,

We currently do not support an API for modifying GoogleMobileAdsSettings at runtime. You can however modify the PList and AndroidManifest on your own. GoogleMobileAdsSettings works with a post process script which does exactly that.

**Comment by programming2012** [comment]
Hi NVentimiglia,
    Thanks.
    I want use GoogleMobileAdsSettings in Editor mode. I create an Inspector Button for warning. Click it can copy AppId to GoogleMobileAdsSettings. Because I often forgot to fill in GoogleMobileAdsSettings. After build it I see the error. Then I had to go back to Unity to fill it and build again. 
   In AndroidBuildPostProcessor.cs and PListProcessor.cs, I see if the AppId is empty in GoogleMobileAdsSettings, there will be throw a exception. May be can set GoogleMobileAdsSettings to public and in set property, Determine whether it is in the editor mode. Of course, this is just a suggestion. I will try to modify the PList and AndroidManifest. Ignore the exception for now.
