### ISSUE TITLE
I have about 6 games in the play store and there is more than 50% loss between the requests sent and the ads shown. How can I solve this problem? I am using codes from Admob's own site

### ISSUE THREAD

**Issue by tolgamacpro** [googleads/googleads-mobile-unity#1778]
* Unity version: 2020.3.7f1
  * Google Mobile Ads Unity plugin version: 6.0.1
  * Platform: Android,iOS
 

I have about 6 games in the play store and there is more than 50% loss between the requests sent and the ads shown. How can I solve this problem? I am using codes from Admob's own site

**Comment by NVentimiglia** [comment]
Hi @tolgamacpro,

For account specific questions, you can raise a request [at the support form](https://groups.google.com/g/google-admob-ads-sdk). Please be sure to [include your App Id/s and Ad Unit Id/s.](https://support.google.com/admob/answer/7356431?hl=en). A charles log of the network traffic would also be incredibly useful in this case.

Thanks.
