### ISSUE TITLE
I suggest you specify the podfile with the exact version

### ISSUE THREAD

**Issue by srbarrios** [googleads/googleads-mobile-unity#178]
Today,
After install the pod, it download me the version 7.7.0 but that version is not compatible with the plugin.
At the end, I realise it, and changed the Podfile to : 

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'Google-Mobile-Ads-SDK', ‘7.6.0’
```

Now works ;)

**Comment by rampara** [comment]
The latest version of the plugin (3.0.2) fixes compatibility issues with Google Mobile Ads iOS SDK v7.7.
