### ISSUE TITLE
Compromised Performance after Ads on Android

### ISSUE THREAD

**Issue by activeaqi** [googleads/googleads-mobile-unity#179]
Having trouble with admob, someone who develop AbMob on very poor ground, extreme worse.
I am using Samsung Note Edge for testing, whenever the ad comes, after few times, my device start hanging. I am also destroying the ad. 
Let me know if my device requires a processor upgrade or something!

using Unity 5.3.2
Using Android Support Library Rev. 23.1.1
Google Unity Packages are more likely bugged (google wanted that way because they are failing others and making room for their own Android Studio). I also encountered problem with other unity package but able to fix (after few weeks and wasted a lot of time).

By the way, where is the documentation of this package, unable to find any.

**Comment by rampara** [comment]
You can find documentation for the plugin on our [developer docs](https://developers.google.com/admob/android/games#unity). The [sample project](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) included in this repository displays the framerate for the application. Are you seeing a drop in framerate when displaying ads? Do you see any information in logcat when you device starts to hang that may indicate what may be causing the issue?

**Comment by rampara** [comment]
Closing issue due to non-response. If this issue persists, please re-open.
