### ISSUE TITLE
OnAdFailedToPresentFullScreenContent subscribed twice on GoogleMobileAds.Api.RewardedAd constructor

### ISSUE THREAD

**Issue by IoannisFMG** [googleads/googleads-mobile-unity#1799]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: Doesn't matter
  * Google Mobile Ads Unity plugin version: 6.0.1
  * Platform: N/A
  * Platform OS version: N/A
  * Any specific devices issue occurs on: N/A
  * Mediation ad networks used, and their versions: N/A

### [REQUIRED] Step 2: Describe the problem
Unless I'm mistaken 
https://github.com/googleads/googleads-mobile-unity/blob/30aa81e045c829b235e8e9a508a7c6f8481abbe9/source/plugin/Assets/GoogleMobileAds/Api/RewardedAd.cs#L54 and
https://github.com/googleads/googleads-mobile-unity/blob/30aa81e045c829b235e8e9a508a7c6f8481abbe9/source/plugin/Assets/GoogleMobileAds/Api/RewardedAd.cs#L83
do the same thing twice.
Is there a reason for the event to be subscribed twice?
#### Steps to reproduce:
N/A
#### Relevant Code:
N/A

**Comment by wallaby3** [comment]
This is not inspiring confidence. This user has pointed out a simple, practically one-line fix, that has been marked Priority 1. At this point - 5 months ago. It hasn't been fixed. You self-assigned it! Just, drag the mouse over the lines, press the delete key. Test the changes.

**Comment by NVentimiglia** [comment]
This will be fixed in the next release.
