### ISSUE TITLE
GADURewardBasedVideoAd.m error while building in iOS

### ISSUE THREAD

**Issue by kenglou** [googleads/googleads-mobile-unity#180]
I'm using latest unity plugin with GoogleAds IOS version 7.7 and found that there is a error message in GADURewardBasedVideoAd.m and stated that the line below doesn't have such interface:

[self.rewardBasedVideo loadRequest:request withAdUnitID:adUnitID userID:userID];

it seems like the "userID:userID" is not available and not found. had someone met this problem before?

**Comment by dawuwu** [comment]
i got the same error.

here is a thread about it with a solution:
https://groups.google.com/forum/#!topic/google-admob-ads-sdk/OVfGXHJY2tA

**Comment by kenglou** [comment]
Thanks and it works. Hopefully they solved it ASAP

**Comment by rampara** [comment]
The latest version of the plugin (3.0.2) fixes compatibility issues with Google Mobile Ads iOS SDK v7.7.
