### ISSUE TITLE
GoogleMobileAds-v6.1.0 can't build to iOS XCode 12.0.1 project by Unity 2020.3.18f1c1

### ISSUE THREAD

**Issue by zxr415** [googleads/googleads-mobile-unity#1808]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.18f1c1
  * Google Mobile Ads Unity plugin version: 6.1.0
  * Platform: iOS  (iOS, Android, Unity Editor)
  * Platform OS version: iOS10 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem
GoogleMobileAds-v6.1.0 can't build to iOS XCode 12.0.1 project by Unity, the Console hint:
"iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project."
"... "pod install" was then attempted again, and still failed..."
There is no xcworkspace files in the output directory, and my CocoaPods version is 1.11.2 

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by FotusCN** [comment]
#1817 
The error is similar

**Comment by vhnunes** [comment]
Just to notify that the [latest version of admob (6.1.2)](https://github.com/googleads/googleads-mobile-unity/releases/tag/v6.1.2) plugin for unity does not support building on xcode below 12.5.

If this is a real issue from v6.1.0 probably won`t be fixed on newer versions.

**Comment by dareerahmadmufti** [comment]
Simple just do one of the following step to resolve this issue:
- Go to Assets > External Dependency Manager > iOS Resolver > Settings:
Then disable the "Use Shell to Execute Cocoapod tools"

or 
- add LANG=en_US.UTF-8 to both .zshrc and .profile file of your macOS.
https://stackoverflow.com/questions/59405671/ios-cocoapods-requires-your-terminal-to-be-using-utf-8-encoding-after-latest

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
