### ISSUE TITLE
iOS linking error with GoogleMobileAds v6.1.1 + FacebookUnityAdapter 3.5.0

### ISSUE THREAD

**Issue by dhamelin** [googleads/googleads-mobile-unity#1815]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.18
  * Google Mobile Ads Unity plugin version: 6.1.1
  * Platform: iOS
  * Platform OS version: N/A
  * Any specific devices issue occurs on: N/A
  * Mediation ad networks used, and their versions: Facebook Adapter 3.5.0

#### Steps to reproduce:

The Xcode (v13.0) project won't link when created out of a fresh project, with Ads v6.1.1 and Facebook Adapter 3.5.0.

#### Relevant Code:

```
// Linking error:

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GADAdReward", referenced from:
      objc-class-ref in FacebookAdapter(GADFBRewardedRenderer.o)
  "_OBJC_CLASS_$_GADMobileAds", referenced from:
      objc-class-ref in FacebookAdapter(GADMediationAdapterFacebook.o)
      objc-class-ref in FacebookAdapter(GADMAdapterFacebook.o)
      objc-class-ref in FacebookAdapter(GADFBUtils.o)
  "_NSValueFromGADAdSize", referenced from:
      -[GADFBBannerAd getBannerWithSize:] in FacebookAdapter(GADFBBannerAd.o)
  "_GADClosestValidSizeForAdSizes", referenced from:
      -[GADFBBannerAd getBannerWithSize:] in FacebookAdapter(GADFBBannerAd.o)
  "_CGSizeFromGADAdSize", referenced from:
      -[GADFBBannerAd getBannerWithSize:] in FacebookAdapter(GADFBBannerAd.o)
  "_NSStringFromGADAdSize", referenced from:
      -[GADFBBannerAd getBannerWithSize:] in FacebookAdapter(GADFBBannerAd.o)
  "_GADAdSizeFromCGSize", referenced from:
      -[GADFBBannerAd getBannerWithSize:] in FacebookAdapter(GADFBBannerAd.o)
  "_OBJC_CLASS_$_GADMediatedUnifiedNativeAdNotificationSource", referenced from:
      objc-class-ref in FacebookAdapter(GADFBNativeBannerAd.o)
      objc-class-ref in FacebookAdapter(GADFBUnifiedNativeAd.o)
  "_OBJC_CLASS_$_GADNativeAdImage", referenced from:
      objc-class-ref in FacebookAdapter(GADFBNativeBannerAd.o)
      objc-class-ref in FacebookAdapter(GADFBUnifiedNativeAd.o)
      objc-class-ref in FacebookAdapter(GADFBNativeRenderer.o)
      objc-class-ref in FacebookAdapter(GADFBNativeAdBase.o)
  "_GADUnifiedNativeIconAsset", referenced from:
      -[GADFBNativeBannerAd didRenderInView:clickableAssetViews:nonclickableAssetViews:viewController:] in FacebookAdapter(GADFBNativeBannerAd.o)
      -[GADFBUnifiedNativeAd didRenderInView:clickableAssetViews:nonclickableAssetViews:viewController:] in FacebookAdapter(GADFBUnifiedNativeAd.o)
      -[GADFBNativeRenderer didRenderInView:clickableAssetViews:nonclickableAssetViews:viewController:] in FacebookAdapter(GADFBNativeRenderer.o)
ld: symbol(s) not found for architecture arm64
```
Simple Unity project to generate Xcode project with:
[https://drive.google.com/file/d/1yCF5bxKH7WCYAzH_mkgOA39vf3ZEv9RE/view?usp=sharing](https://drive.google.com/file/d/1yCF5bxKH7WCYAzH_mkgOA39vf3ZEv9RE/view?usp=sharing)

**Comment by HAL-JP** [comment]
This can be solved.

Step 1 
Select Assets-> External Dependency Manager-> iOS Resolver-> Settings. 
<img alt="スクリーンショット 2021-09-03 21 25 39" width="2000" src="https://user-images.githubusercontent.com/81759313/132005259-961fca54-9e2c-4d58-bbc4-d5960edd7b2d.png">

Step 2 
Enable Link frameworks statically.
<img alt="スクリーンショット 2021-09-03 21 25 51" width="397" src="https://user-images.githubusercontent.com/81759313/132005467-2989f46d-d4f8-4e54-a4cb-ac5732506294.png">

**Comment by dhamelin** [comment]
As mentioned in other thread, this "solution" fix the build issue but make the game crash on boot.

**Comment by dhamelin** [comment]
I got a new computer, with a fresh new setup. But same result.
1. Using the HelloWorld Sample app
2. Using latest ad mob package 6.1.2 (this compile and link fine)
3. Using Facebook Adapter 3.6.0 -> Now having the linking errors

Here's my POD file content:

```
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'GoogleMobileAdsMediationFacebook', '6.8.0.0'
  pod 'Google-Mobile-Ads-SDK', '~> 8.8'
end
target 'Unity-iPhone' do
end
use_frameworks!
```

I would be very happy to test anything if someone at Google has any hint. Is it really working for you guys? 
Our game will launch soon and Facebook Audience is very important. It gives us good eCPM. This is a must have for any serious dev and it's really frustrating that it doesn't work right now or we can't have any help on this.

**Comment by NVentimiglia** [comment]
@dhamelin Thanks for raising the issue. I was able to replicate the problem and we are looking into a fix. We will update you when we have a solution.

**Comment by dareerahmadmufti** [comment]
Same issue even exist with GoogleMobileAds v6.1.2 with FacebookUnityMediation v3.6.0, with iOS resolver settings:
- use_frameword! = true
- Link frameworks statically = true

On xcode after building project getting error of:
- Reason: image not found (something related to storyboard, after searching on internet), and app crash on load.
but with same settings and without FacebookUnityMediation the app build successfully and ads are also properly showing.

- System:
- xcode: 13.2.1
- macOS: 12.1
- Unity: 2019.4.34f0

**Comment by kungshinhean** [comment]
Having the same as @dareerahmadmufti, is there any possible quick solution for now? Please?

**Comment by Nyankoo** [comment]
@NVentimiglia Any update on a fix?

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
