### ISSUE TITLE
RewardBasedVideoAd simple Implementation not working

### ISSUE THREAD

**Issue by aquariens** [googleads/googleads-mobile-unity#182]
I am adding a simplest Implementation of RewardBasedVideoAd but unfortunately not getting success for admob interstitial ad unit.

Am I doing something wrong? as logcat is repeatedly showing message that "video is not ready yet".

I tested my add unit with interstitial and it is working fine. Using plugin 3.0.1, Unity 5.3.2, SDK 23.1.1 and GPGs 8.4 and not using any other plugin.

Moreover i couldn't find any of it's implementation in Documentation.

code as of the sample app c# below;

`using System;
using UnityEngine;
using GoogleMobileAds;
using GoogleMobileAds.Api;

// Example script showing how to invoke the Google Mobile Ads Unity plugin.
public class AdmobRewardInApp : MonoBehaviour
{
	RewardBasedVideoAd rewardBasedVideo;

	void Start ()
	{
		// Get singleton reward based video ad reference.
		rewardBasedVideo = RewardBasedVideoAd.Instance;
		// RewardBasedVideoAd is a singleton, so handlers should only be registered once.
	}
	void OnGUI ()
	{
		GUIStyle style = new GUIStyle ();

		Rect rect = new Rect (0, 0, Screen.width, Screen.height);
		style.alignment = TextAnchor.LowerRight;
		style.fontSize = (int)(Screen.height * 0.06);
		style.normal.textColor = new Color (0.0f, 0.0f, 0.5f, 1.0f);

		// Puts some basic buttons onto the screen.
		GUI.skin.button.fontSize = (int)(0.03f * Screen.height);

		Rect requestRewardedRect = new Rect (0.1f * Screen.width, 0.675f * Screen.height,
			                           0.8f * Screen.width, 0.1f * Screen.height);
		if (GUI.Button (requestRewardedRect, "Request Rewarded Video")) {
			RequestRewardBasedVideo ();
		}

		Rect showRewardedRect = new Rect (0.1f * Screen.width, 0.8f * Screen.height,
			                        0.8f * Screen.width, 0.1f * Screen.height);
		if (GUI.Button (showRewardedRect, "Show Rewarded Video")) {
			ShowRewardBasedVideo ();
		}
			
	}
		
	private void RequestRewardBasedVideo ()
	{
		#if UNITY_EDITOR
		string adUnitId = "ca-app-pub-xxxxxxxxxxxxxx/XXXXXXXXXXX";
		#elif UNITY_ANDROID
		string adUnitId = "INSERT_ANDROID_REWARD_BASED_VIDEO_AD_UNIT_ID_HERE";
		#elif UNITY_IPHONE
		string adUnitId = "INSERT_IOS_REWARD_BASED_VIDEO_AD_UNIT_ID_HERE";
		#else
		string adUnitId = "unexpected_platform";
		#endif
		// Create an empty ad request.
		AdRequest request = new AdRequest.Builder ().Build ();
		// Load the banner with the request.
		rewardBasedVideo.LoadAd (request, adUnitId);
	}

	private void ShowRewardBasedVideo ()
	{
		if (rewardBasedVideo.IsLoaded ()) {
			rewardBasedVideo.Show ();
		} else {
			print ("Reward based video ad is not ready yet.");
		}
	}
}`

Logcat is

`W/AdsUnity(16674): Reward based video ad is not ready to be shown.

E/Watchdog( 3436): !@Sync 3610 [03-05 16:33:46.376]

D/InputReader( 3436): Input event(1): value=1 when=108433298521000

D/InputReader( 3436): Input event(1): value=1 when=108433298521000

I/InputReader( 3436): Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.8838 ] when=108433298521000

D/InputReader( 3436): lastThreadEndTime = 108433140409313, currentThreadStartTime = 108433140416022, diff = 0

I/InputDispatcher( 3436): Delivering touch to (16674): action: 0x0, toolType: 1

D/ViewRootImpl(16674): ViewPostImeInputStage ACTION_DOWN

D/InputReader( 3436): Input event(1): value=0 when=108433455674000

D/InputReader( 3436): Input event(1): value=0 when=108433455674000

I/InputReader( 3436): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=108433455674000

I/InputDispatcher( 3436): Delivering touch to (16674): action: 0x1, toolType: 1

I/Unity   (16674): Reward based video ad is not ready yet.

I/Unity   (16674):  

I/Unity   (16674): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (16674): 

W/AdsUnity(16674): Reward based video ad is not ready to be shown.

D/InputReader( 3436): Input event(1): value=1 when=108433675340000

D/InputReader( 3436): Input event(1): value=1 when=108433675340000

I/InputReader( 3436): Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.8839 ] when=108433675340000

D/InputReader( 3436): lastThreadEndTime = 108433455997730, currentThreadStartTime = 108433456003938, diff = 0

I/InputDispatcher( 3436): Delivering touch to (16674): action: 0x0, toolType: 1

D/ViewRootImpl(16674): ViewPostImeInputStage ACTION_DOWN

D/InputReader( 3436): Input event(1): value=0 when=108433820888000

D/InputReader( 3436): Input event(1): value=0 when=108433820888000

I/InputReader( 3436): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=108433820888000

I/InputDispatcher( 3436): Delivering touch to (16674): action: 0x1, toolType: 1

I/Unity   (16674): Reward based video ad is not ready yet.

`

**Comment by rampara** [comment]
At this time we are working with few publishers we have a close relationship with on the reward based video ads closed beta. If you have an account manager they would be your best point of contact for more information. If you do not have an account manager, unfortunately, you will have to wait for the beta to open up.

**Comment by aquariens** [comment]
I don't have any account manager, can you please advice what other publisher you are working with? Email me info[at]shahzadamin[dot]com.

Thanks

**Comment by rampara** [comment]
Rewarded video mediation is now open to all publishers and you can set up an ad unit with rewarded video ad sources in your AdMob account.
