### ISSUE TITLE
Error apear when i import GoogleMobileAds-v6.1.2

### ISSUE THREAD

**Issue by stickylabdev** [googleads/googleads-mobile-unity#1827]
https://forum.unity.com/threads/error-apear-when-i-import-googlemobileads-v6-1-2.1187941/

I have made a game and managed to build it into an apk,

but after i import latest googlemobileads plugin GoogleMobileAds-v6.1.2 , i got this error, how to solve it please

i used unity 2019.4.31f1

**Comment by Ozzystrasza** [comment]
I am also having the same issue, been looking for days and still couldn't find a way to build.

**Comment by stickylabdev** [comment]
Yeps.... Everyone has issues

Pada tanggal Sab, 13 Nov 2021 05.10, Oziris Moreira <
***@***.***> menulis:

**Comment by felladil3** [comment]
I had the same problem, i resolved this by changing Target api level to "29"
I don't know if it will impact google store, but it works

**Comment by stickylabdev** [comment]
Nothanks

Pada tanggal Min, 23 Jan 2022 07.45, felladil3 ***@***.***>
menulis:
