### ISSUE TITLE
InAppPurchase ads, error 302

### ISSUE THREAD

**Issue by paradizIscool** [googleads/googleads-mobile-unity#183]
Hi,

I try to get inapp purchase ads working, display is ok but when I try to buy something I get a 302 error. My app is published in alpha, my shop works fine with this version.

**Comment by rampara** [comment]
Are you using the default or custom in app purchase flow? Can you post the output you are seeing in logcat under the 'Ads' tag?

**Comment by paradizIscool** [comment]
Starting ad request.
Ad finished loading.
Ad opening.
Received non-success response code 302 from pinging URL: http://googleads.g.doubleclick.net/aclk?sa=L&ai=COmsRH4neVvW6AcK5b5C2gdgDvYKQ-QeN--6r0QKIw-fTThABIK6UkCJg-_n8gogKoAGTgOPRA6gDAaoEyAFP0Fs-wQE1vCx1iV2IOpDr5dsYuEvwQUCSELB8fLdVi0zHqZxC2ZJfxeBCVmg-uSIi4W1zrRl3sudVxTtQnMd9N6oAiMlqm5baD_fipIag653ph--F8pg63ppMSfK9h7Edikj3wogK1bnjs-FA0hDfdhwJG70LQ9JJmqV19PFR72bZ_0mMFw2TVt556cUARA-RIwYjlArfTwvOaDH49GI2j0edXhjKPP0t9mZJwGGenRyv2gK5UWWnrBfP7_Vco1v_EPRzINQhE5AGAaAGGsAGC4AH1f-cLpgHAagHpr4b2AcB&num=1&cid=5GhXJfppz9SCvRgdjONmR7n4&sig=AOD64_0i13FcFLeYjWTE8J0hC9gJ5fyDsA&ms=-FhTJE1Z4iYTtm0lcNi3CrSOHUui3YaewPFaqTvPVxief3WffcUlmL3d12AbSWKA6hJyRQx87CE823-p3tSKST5iohK4x8ROuAW0SbSTs3mI3U1-hYjSR4JPoPj3NuSf91zj57lNmUJukrpxmJ1SKNuSCA5Z-qIrLu1oKeQnno7osoQ_w1SjMSsPIrv4dZb4NANFNT6hUlktN5W8FxiMshOKfZhtaHObW-hw_c6xYwDr2rAI_rOFA6pks0JyabRI_deDvJDAb1UfKOE9HAJ5Zj1dhIkQAAof7E63tW6o3VxFaeKcLyG7z73sVd1GuS-ZiutwEqw4AT2eUfzuUV5TWg&adurl=https://play.google.com/store/apps/details%3Fid%3Dcom.iscoolentertainment.wordoxfree

**Comment by paradizIscool** [comment]
Hi there, any update ?

**Comment by rampara** [comment]
Beyond the 302 error in the logs, is your in app purchase flow working as expected?

**Comment by paradizIscool** [comment]
No, nothing happen when I click on buy button.

**Comment by rampara** [comment]
What expected behavior are you not seeing? If you're using the custom in-app purchase flow, it is up to you to complete the in-app billing process yourself.

**Comment by paradizIscool** [comment]
The problem is that the process does not start, Nothing happends when user click on buy buttons, I don't know if I can do something for this issue.

**Comment by rampara** [comment]
If you're using the custom in-app purchase flow, your implementation of `ICustomInAppPurchaseProcessor` should receive a `ProcessInAppPurchase` method invocation when the user clicks the buy button. Does this not happen? Implementing the billing process is up to you. If you use the default in-app purchase flow, the billing flow will be implemented for you. You can find more information on in app purchases in our [developer docs](https://developers.google.com/admob/android/iap#playstorepurchaselistener_vs_inapppurchaselistener).

**Comment by paradizIscool** [comment]
ProcessInAppPurchase is not invoked


_interstitial = new InterstitialAd(ConfigManager.AD_UNIT_ID);
// Register for ad events.
_interstitial.OnAdLoaded += HandleInterstitialLoaded;
_interstitial.OnAdFailedToLoad += HandleInterstitialFailedToLoad;
_interstitial.OnAdOpening += HandleInterstitialOpening;
_interstitial.OnAdClosed += HandleInterstitialClosed;
_interstitial.OnAdLeavingApplication += HandleInterstitialLeavingApplication;
_interstitial.SetInAppPurchaseProcessor(new InAppPurachaseProcessor());
// Load an interstitial ad.
_interstitial.LoadAd(createAdRequest());
         


private class InAppPurachaseProcessor: ICustomInAppPurchaseProcessor
 {
        #region ICustomInAppPurchaseProcessor implementation

        public void ProcessInAppPurchase(ICustomInAppPurchase purchase)
        {
            Debug.LogFormat("ProcessInAppPurchase {0}", purchase);
        }
}
