### ISSUE TITLE
I have been getting the apk crash issue when I open apk/game.

### ISSUE THREAD

**Issue by rk042** [googleads/googleads-mobile-unity#1837]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.14f1
  * Google Mobile Ads Unity plugin version: 6.1.2 , 6.1.1
  * Platform: Android
  * Platform OS version: android 10 (eg iOS 10, Android 9)

## Logcat Error is -> 

Error Layer [Surface(name=AppWindowToken{da80eee token=Token{3780469 ActivityRecord{4bec6f0 u0 bundle id/com.unity3d.player.UnityPlayerActivity t237}}})/@0x610ff38 - animation-leash#0] No local sync point found

**Comment by stickylabdev** [comment]
the same , even the building is failed

**Comment by NVentimiglia** [comment]
Hi @rk042 ,

Can you please provide a full trace log and sample app to our [community support forums?](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines)

**Comment by rk042** [comment]
now it's working, but I did not understand the trace log and sample app
words
