### ISSUE TITLE
apk automatic closed when i open it

### ISSUE THREAD

**Issue by stickylabdev** [googleads/googleads-mobile-unity#1844]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.22f1
  * Google Mobile Ads Unity plugin version: GoogleMobileAds-v6.1.2
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: 11 RKQ1.200826.002 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: Android
  * Mediation ad networks used, and their versions: Admob

### [REQUIRED] Step 2: Describe the problem

the problem is auto closed or auto crash , i can say automatic closed super fast  when i open the apk ,

previously i just build the apk , empty project with admob plugin and with simple example , then build it then fail when i open the apk ,here is the log from monitor.bat that i got

UnityMain(19331): type=1400 audit(0.0:7121960): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=10084 scontext=u:r:untrusted_app_29:s0:c201,c257,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file p

**Comment by FreeLearningApps** [comment]
I can't interpret the error message, but if I remember correctly one of the most common crashes at the beginning is due to the absence of the app id. Make sure you entered it.

**Comment by stickylabdev** [comment]
Ijisy need tp force resolve.

Pada tanggal Min, 14 Nov 2021 10.25, FreeLearningApps <
***@***.***> menulis:

**Comment by NVentimiglia** [comment]
Hi @FreeLearningApps ,

Can you submit a bug request with sample app and full trace log of the crash to our [community forum ?](https://groups.google.com/g/google-admob-ads-sdk)
