### ISSUE TITLE
Old Files

### ISSUE THREAD

**Issue by assafcohen1** [googleads/googleads-mobile-unity#1846]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.21
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: iOS, Android, Unity Editor

### [REQUIRED] Step 2: Describe the problem

Hello, 
We use the 6.1.2 plugin for both Android and iOS
I noticed there are two old files that may be leftovers from old plugin versions - are they still needed?
externs.cpp
googlemobileads-unity.aar

Thanks!

**Comment by NVentimiglia** [comment]
Hi @assafcohen1 

It is safe to delete old unused files. We recommend to delete the old package before installing the new one.
