### ISSUE TITLE
Error building Player: CommandInvokationFailure: Failed to re-package resources.

### ISSUE THREAD

**Issue by redfist** [googleads/googleads-mobile-unity#185]
Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Program Files (x86)\Android\android-sdk\build-tools\23.0.2\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Program Files (x86)/Android/android-sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages com.google.android.gms:com.google.unity -S "D:\PROJEKTI\Ћирилица\Temp\StagingArea\android-libraries\google-play-services_lib\res" -S "D:\PROJEKTI\Ћирилица\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\res"

stderr[
ERROR: resource directory 'D:\PROJEKTI\????????\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\res' does not exist
]
stdout[

]

**Comment by rampara** [comment]
Did the JarResolver library copy Google Play Service client AARs into the the 'Assets/Plugins/Android/' directory of your project?

**Comment by redfist** [comment]
No

**Comment by rampara** [comment]
Can you try clicking 'Assets -> Google Play Services -> Resolve Client Jars' in the Unity menu.

**Comment by redfist** [comment]
I Did it, nothing happened

**Comment by rampara** [comment]
You don't receive a pop up dialog indicating 'resolution complete'? Do you see any output in the Unity console? Do you have the Android SDK installed on your machine?

**Comment by redfist** [comment]
I Have SDK and It is updated. 
I did resolve jar and get. 
ResolutionException: Cannot find candidate artifact for com.android.support:appcompat-v7:23.1.0+
Google.JarResolver.PlayServicesSupport.LoadDependencies (Boolean allClients)
Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest)
GooglePlayServices.ResolverVer1_1.DoResolution (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation) (at Assets/PlayServicesResolver/Editor/ResolverVer1_1.cs:59)
GooglePlayServices.PlayServicesResolver.MenuResolve () (at Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs:144)

**Comment by rampara** [comment]
Within the *'Assets/PlayServicesResolver/Editor/AdMobDependencies.cs'* file, can you try making the following change:

<pre><code>svcSupport.DependOn("com.android.support", "appcompat-v7", "23.1.0+");</pre></code>

to 

<pre><code>svcSupport.DependOn("com.android.support", "appcompat-v7", "LATEST");</pre></code>

**Comment by redfist** [comment]
using Google.JarResolver;
using UnityEditor;

/// AdMob dependencies file.
[InitializeOnLoad]
public static class AdMobDependencies
{
    /// The name of the plugin.
    private static readonly string PluginName = "AdMobUnity";

    /// Initializes static members of the class.
    static AdMobDependencies()
    {
        PlayServicesSupport svcSupport =
            PlayServicesSupport.CreateInstance(PluginName, EditorPrefs.GetString("AndroidSdkRoot"),
                    "ProjectSettings");

        svcSupport.DependOn("com.google.android.gms", "play-services-ads", "LATEST");

        // Marshmallow permissions requires app-compat.
		svcSupport.DependOn("com.android.support", "appcompat-v7", "LATEST");
    }
}


I get error : Google.JarResolver.ResolutionException: Cannot find candidate artifact for com.android.support:appcompat-v7:LATEST
  at Google.JarResolver.PlayServicesSupport.DependOn (System.String group, System.String artifact, System.String version) [0x00000] in <filename unknown>:0 
  at AdMobDependencies..cctor () [0x00039] in D:\PROJEKTI\Ћирилица\Assets\PlayServicesResolver\Editor\AdMobDependencies.cs:21 
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

**Comment by rampara** [comment]
Do you have the Android Support Library installed on your machine?

**Comment by redfist** [comment]
yes

**Comment by redfist** [comment]
![image](https://cloud.githubusercontent.com/assets/16037907/13798057/aae87044-eb12-11e5-9281-5a08b8b6a89c.png)

**Comment by rampara** [comment]
Do you have the *ANDROID_HOME* environment variable set to the root folder for the Android SDK?

**Comment by redfist** [comment]
yes

**Comment by rampara** [comment]
Can you install the `Local Maven repository for Support Libraries` via the SDK manager.

**Comment by redfist** [comment]
![untitled picture](https://cloud.githubusercontent.com/assets/16037907/14086938/e40d0b54-f527-11e5-9a15-19bc5d518531.png)

**Comment by redfist** [comment]
![a](https://cloud.githubusercontent.com/assets/16037907/14087026/5521606a-f528-11e5-8e24-0189e3820558.png)

**Comment by redfist** [comment]
![j](https://cloud.githubusercontent.com/assets/16037907/14087039/694f539e-f528-11e5-8fe1-e459b1fa9aa0.png)

**Comment by rampara** [comment]
Are you still running into the same issue?

**Comment by rampara** [comment]
Does the `$ANDROID_HOME/extras/android/m2repository/com/android/support/appcompat-v7` directory contain a maven-metadata.xml file? If so, does this same directory include a sub-directory with an AAR file for the support library corresponding to the version listed in the maven-metadata.xml file?

**Comment by redfist** [comment]
![123](https://cloud.githubusercontent.com/assets/16037907/14090372/3de9c98e-f53a-11e5-996e-34d0fc6bed05.png)

**Comment by TSiiven** [comment]
Hi,

I have this same problem. Here's my maven-metadata.xml
![image](https://cloud.githubusercontent.com/assets/18212247/14205982/522af0a4-f818-11e5-9487-ee0d5604242f.png)

and here's the 23.2.1 folder:
![image](https://cloud.githubusercontent.com/assets/18212247/14205924/d36263d8-f817-11e5-8217-fe48634b6ba0.png)

Have you found a resolution for this?

**Comment by rampara** [comment]
This problem is proving difficult to debug further since I'm unable to reproduce it on my end. However, since the [JarResolver](https://github.com/googlesamples/unity-jar-resolver/blob/master/source/JarResolverLib/src/Google.JarResolver/PlayServicesSupport.cs) library is open source, you can rebuild the dll with additional logging to try and find where dependency resolution is failing. Based on the console output you provided, it looks like the FindCandidate() method in PlayServicesSupport.cs is returning null. I've attached a modified version of the JarResolver library that should output additional information to the Unity log with the prefix "JarResolver-Debug". This may give you a better idea as what is causing the issue. 


[play-services-resolver-1.1.1.unitypackage.zip](https://github.com/googleads/googleads-mobile-unity/files/203392/play-services-resolver-1.1.1.unitypackage.zip)

**Comment by akira32** [comment]
Solution:http://blog.xuite.net/akira32/home/419281627

**Comment by rampara** [comment]
The latest version of the plugin (v3.1.0) integrates a refactored Play Services dependency resolver that should fix this issue. Please open a new issue if you're still having trouble with Google Play services dependencies.
