### ISSUE TITLE
Lots of crashes at loading rewarded video ads.

### ISSUE THREAD

**Issue by cryvolt** [googleads/googleads-mobile-unity#1855]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version:  2021.1.17
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: Android
  * Platform OS version: Android 10, Android 11
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: No mediation networks used

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
I am seeing lots of crashes on the google play developer console 
which I cannot reproduce. Crash rates are around 2% and not related 
to specific devices.  Here is the crash detail. 


java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2021.1.17f1
Device model      : Sony SOV36
Device fingerprint: KDDI/SOV36_jp_kdi/SOV36:9/47.2.C.1.126/1632396770:user/release-keys
Build Type        : Release
Scripting Backend : IL2CPP
ABI               : arm64-v8a
Strip Engine Code : true
Caused by
at com.google.android.gms.common.internal.Preconditions.checkNotNull(com.google.android.gms:play-services-basement@@17.6.0:2)
at com.google.android.gms.ads.rewarded.RewardedAd.load(com.google.android.gms:play-services-ads-lite@@20.2.0:2)
  at com.google.unity.ads.UnityRewardedAd$1.run (UnityRewardedAd.java:58)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:280)
  at android.app.ActivityThread.main (ActivityThread.java:6710)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
```

**Comment by NVentimiglia** [comment]
Hi @cryvolt 

We would need a full trace log and some sample code of how you are implementing things to understand this issue. If you can submit this to our [community forum,](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) we can look into helping you.
