### ISSUE TITLE
Errors with android sdk and api

### ISSUE THREAD

**Issue by boevoikovboy** [googleads/googleads-mobile-unity#1856]
when I was preparing to release the game, I put the api from 21 to 30
, unity sent a message to the Android sdk that the requested api of the platform was missing, the required api level of 30 when pressing the sdk update, a bunch of errors flew out here they are: https://cdn.discordapp.com/attachments / ...unknown.png here is each error individually: 1) https://cdn.discordapp.com/attachments / ...unknown.png
https://cdn.discordapp.com/attachments / ...unknown.png
2) https://cdn.discordapp.com/attachments / ...unknown.png
3) https://cdn.discordapp.com/attachments / ...unknown.png
4) https://cdn.discordapp.com/attachments / ...unknown.png
in google ads setting correctly inserted the plugin, 6.12

**Comment by NVentimiglia** [comment]
Hi @boevoikovboy ,

Can you please provide me with a full trace log of what is happening. A sample of the AndroidManifest.xml (or even a sample project) would help us expedite this issue. If you can open a request on the [community forums](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) with the log and sample as an attachment, we can get started,
