### ISSUE TITLE
Safety - Kids Category

### ISSUE THREAD

**Issue by phucbac** [googleads/googleads-mobile-unity#1862]
please help me 
i have visable ads untiy but Apple review have reject it 

Guideline 1.3 - Safety - Kids Category

We continue to noticed that your Kids Category app includes analytics, advertising and collects, transmits, or has the ability to share personal information or device information with third parties. Specifically: 

- Your app includes third-party analytics or third-party advertising with the ability to collect, transmit or share identifiable information, including, for example, IDFA. We found that your app references the ASIdentifierManager API, which provides access to a user's IDFA, in the following location(s) in your binary:

• Frameworks/UnityFramework.framework/UnityFramework

It would be appropriate to remove all instances of “ASIdentifierManager” from your app, even if they are not utilized in your app's functionality.

Next Steps

To resolve this issue, please remove this functionality or revise your app so that no personally identifiable information or device information is sent to third parties.

Resources

Learn more about our policies for Kids Category apps in App Store Review Guideline 1.3.

Since your App Store Connect status is Metadata Rejected, we do NOT require a new binary. To revise the metadata, visit App Store Connect to select your app and revise the desired metadata values. Once you’ve completed all changes, reply to this message in Resolution Center and we will continue the review.

**Comment by NVentimiglia** [comment]
Hi @phucbac,

You can read more about admob [child safety guidelines here](https://support.google.com/admob/answer/6223431?hl=en). That said, I noticed that the problem framework is `Frameworks/UnityFramework.framework/UnityFramework` which is not something we manage, have you tried bringing this up with Unity?
