### ISSUE TITLE
Dummy ads are not instantiated in the editor

### ISSUE THREAD

**Issue by URAmiRBin** [googleads/googleads-mobile-unity#1863]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.22f1
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: Unity Editor
  * Platform OS version: Pop!_OS 21.04
  * Any specific devices issue occurs on: MSI GP62 7RD
  * Mediation ad networks used, and their versions: -

#### Steps to reproduce:

1. Clone this repository
2. Download the latest release
3. Open HelloWorld project
4. Switch platform to Android
5. Import the Admob package
6. Auto resolve dhe dependencies
7. Play the game
8. Press on Request Banner Ad, Request Rewarded Ad ...

The status on the bottom logs `Requesting Banner Ad.` and Unity logs `Dummy LoadAd` and nothing happens.

These steps are to make sure my project is not causing any issues. For my own project, with my Windows machine everything works fine, switching to the Linux editor, dummy ads are not instantiated into the scene. It's worth mentioning that Admob works fine after the Android build from both Windows and Linux editors.

**Comment by NVentimiglia** [comment]
Hi @URAmiRBin 

There are many things that could cause this. [Please make a request on our support group](https://groups.google.com/g/google-admob-ads-sdk). Please include a downloadable sample project that reproduces the bug, and [include your App Id/s and Ad Unit Id/s.](https://support.google.com/admob/answer/7356431?hl=en).
