### ISSUE TITLE
Plugin v6.1.2 is asking for API update and removes sdk repositories

### ISSUE THREAD

**Issue by Hzboat** [googleads/googleads-mobile-unity#1868]
* Unity version: 2020.23
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: Unity Editor and Android(iOS, Android, Unity Editor)
  * Platform OS version: For general Android applications (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: Unity editor
  * Mediation ad networks used, and their versions: _____

I imported the google admob plugin to unity and wanted test out the test ads with their app IDs and banner ID. To import the plugin I came across the following pop up which is not a part of the tutorials I've watched:
![L3kwF](https://user-images.githubusercontent.com/95260124/144044832-63dd43f0-a955-49ed-bc1f-29312b5de642.png)

So I clicked with a backup on check and when I wanted add the app ID the inspector gives me the following interface which is also different from the tutorials I've seen:

![309K5](https://user-images.githubusercontent.com/95260124/144045112-7bd68a8e-8a47-47c5-859d-4176e9e9f451.png)

finally when I check the settings to build the and run it on my Android device, I come across errors that my android repositories are missing and the game installed on my android device wont open.

I tried to run the game without the admob features and it work completely fine. 
The problem arises when I import the admob plugin to my project. 

Please Help!!!

**Comment by Hzboat** [comment]
Will old admob versions work for the latest unity versions?

**Comment by NVentimiglia** [comment]
Hi @Hzboat 

We recommend uninstalling and reinstalling the plugin when doing major version changes. Moreover, I would like to confirm that in the last major version change we did modify the UI for the settings window.

Regarding the build errors, do you have a log that I may review?

**Comment by Hzboat** [comment]
> Hi @Hzboat
> 
> We recommend uninstalling and reinstalling the plugin when doing major version changes. Moreover, I would like to confirm that in the last major version change we did modify the UI for the settings window.
> 
> Regarding the build errors, do you have a log that I may review?

Thanx @NVentimiglia. Did you mean the errors from the logcat? or the console? 
For a few moments i had errors in the console about missing sdk libraries. This is with the android sdk support installation from unity. However, i had to rebuild my game with a new project and those errors did not pop up anymore. 
However, after building the game and I installed it into the android device the game glitches with a black screen in a second and does not start. I have now made my project with an admob plugin and one without. The one without the admob plugin works perfectly fine.

**Comment by NVentimiglia** [comment]
> However, i had to rebuild my game with a new project and those errors did not pop up anymore.

That's great news. 

> I have now made my project with an admob plugin and one without.

Are there any error messages that I can work with? What ad format are you using? Do you have a logcat of this error I can look at?

**Comment by Hzboat** [comment]
> 

I apologize for the delay on my response and appreciate your time in helping me regarding this issue.
Please consider the following scenario:
![Screenshot 2021-12-05 035509](https://user-images.githubusercontent.com/95260124/144727114-7a694688-64ae-4bc1-bc2a-117454d84da5.png)
Here i have just entered the test app IDs for a simulation purpose. 
Here are the console errors;
![Screenshot 2021-12-05 035358](https://user-images.githubusercontent.com/95260124/144727142-8e73bdb1-acfa-4c87-ace3-073658422af2.png)

Here are the android logcat errors i was able to capture as I installed the apk file via usb debugging:
![Screenshot 2021-12-05 035044](https://user-images.githubusercontent.com/95260124/144727173-8fc97e74-c850-4076-b60d-8660724db60a.png)
![Screenshot 2021-12-05 035215](https://user-images.githubusercontent.com/95260124/144727175-d10cdc8a-129a-4783-99cb-73e5205e011d.png)
![Screenshot 2021-12-05 035115](https://user-images.githubusercontent.com/95260124/144727176-6eaebb14-4f73-4e19-a059-1dab6b839277.png)
![Screenshot 2021-12-05 035246](https://user-images.githubusercontent.com/95260124/144727178-5ae29828-59b9-4b4a-99a2-6a427c8f1afd.png)

Here is my script for the AdManager for the app:
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GoogleMobileAds.Api;
using System;

public class AdManager : MonoBehaviour
{
    private BannerView bannerView;


    // Start is called before the first frame update
    void Start()
    {
        MobileAds.Initialize(InitializationStatus => { });

        string adUnitId = "ca-app-pub-3940256099942544/3419835294";

        BannerView bannerView = new BannerView(adUnitId, AdSize.SmartBanner, AdPosition.Bottom);
        
        AdRequest request = new AdRequest.Builder().Build();

        bannerView.LoadAd(new AdRequest.Builder().Build());

    }

}

The AppIDs used for this project:

TEST AD UNIT FOR BANNER ADS - ( ca-app-pub-3940256099942544/6300978111 )

Test app ID - ca-app-pub-3940256099942544/3419835294

Thanx again for helping me out @NVentimiglia!!!!

**Comment by NVentimiglia** [comment]
@Hzboat 
Thanks for the write up. Could it be possible to get a sample project which replicates this? You can attach a link here, or [make a request on our support group](https://groups.google.com/g/google-admob-ads-sdk).

**Comment by mastef** [comment]
> MobileAds.Initialize(InitializationStatus => { });

Don't you need to wait for the result of the callback before proceeding with the next code?

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
