### ISSUE TITLE
Cannot build for iOS with Google Mobile Plugin 6.1.2

### ISSUE THREAD

**Issue by adibacco** [googleads/googleads-mobile-unity#1870]
Cannot build for iOS 12.5.1, Googleads mobile unity plugin 6.1.2

Pods:
Downloading dependencies
Installing BoringSSL-GRPC (0.0.7)
Installing Firebase (8.9.1)
Installing FirebaseAnalytics (8.9.1)
Installing FirebaseCore (8.9.1)
Installing FirebaseCoreDiagnostics (8.9.0)
Installing FirebaseFirestore (8.9.1)
Installing FirebaseInstallations (8.9.0)
Installing FirebaseMessaging (8.9.0)
Installing Google-Mobile-Ads-SDK (8.13.0)
Installing GoogleAppMeasurement (8.9.1)
Installing GoogleDataTransport (9.1.2)
Installing GoogleUserMessagingPlatform (2.0.0)
Installing GoogleUtilities (7.6.0)
Installing PromisesObjC (2.0.0)
Installing abseil (0.20200225.0)
Installing gRPC-C++ (1.28.2)
Installing gRPC-Core (1.28.2)
Installing leveldb-library (1.22.1)
Installing nanopb (2.30908.0)

**Errors** related to GADRewardedAd showed at the end of log file attached.
Attaching full Xcode log with all info.

[Build target UnityFramework_2021-11-30T14-01-29.txt](https://github.com/googleads/googleads-mobile-unity/files/7629189/Build.target.UnityFramework_2021-11-30T14-01-29.txt)

**Comment by NVentimiglia** [comment]
@adibacco can you try running a `pod install`, and see what happens ?

- open terminal on the folder containing the xcode project
- type pod install
- if this works, run the generated workspace 
- if it does, please share your terminal output

**Comment by noxytrux** [comment]
You need to delete old Plugin files before updating to new one. There are some left overs that are no more used and been moved to library file (*.a) The same comes for mediation's. I will suggest clean install it worked for me (I had the same error output after upgrading yesterday)

**Comment by adibacco** [comment]
> 

Hi @NVentimiglia , I deleted plugin, and imported again (suggested by @noxytrux ), built with Unity. 
Then I run pod install in xcode proj dir.

Built again with Xcode but nothing has changed.
![GADRewardedAdDelegate](https://user-images.githubusercontent.com/2692833/144313644-4281a346-1e12-4f47-8128-cb30380e76b0.PNG)

**Comment by noxytrux** [comment]
You not only have to delete plugin from Assets directory you also have to delete native files from Assets/Plugins/iOS/

**Comment by adibacco** [comment]
Thank you @noxytrux , I removed all iOS plugins and now I can build for iOS. It is incredible that Unity that is so advanced, doesn't provide a method to remove a package. 
Mille grazie.
