### ISSUE TITLE
Unity Editor - Interstitial disappears on scene change and Time.timeScale remains = 0

### ISSUE THREAD

**Issue by Francesco-FL** [googleads/googleads-mobile-unity#1873]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.24f1
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: Unity Editor (iOS, Android, Unity Editor)

I'm in a scene. To switch to another scene I have to click a button. The button has two events, the first is scene change, while the second shows an interstitial (already loaded).

When I am on the app in the phone and I click on the button everything is fine, the scene changes and in the meantime I am shown the announcement, I close the announcement and the scene, as I said, has changed.

When I am in the editor, however, if I click the button, the interstitial is not shown. it's as if the scene change annoys him in the editor, and makes him disappear. It seems a marginal problem, but it is not, as showing an interstitial generates the "Pause Game" (DummyAdBehaviour: PauseGame ()), and the disappearance of the interstitial (having therefore disappeared due to the scene change and therefore not being able to close it from button to close the ad), the "Resume Game" (DummyAdBehaviour: ResumeGame ()) is not generated.

So, back to the initial example. If I am in the editor and I click that button, the "Pause Game" is generated, the scene is changed and the interstitial has disappeared. So in the new working scene I'm in, by way of I think the "Pause Game", I have a Time.timeScale = 0, which messes up all the code that works with Time. This messes up the tests done in the editor.

**Comment by FreeLearningApps** [comment]
Yes it's correct. From my experience the interstitial is normally put in the scene change, so I guess that in the editor it has to survive, as it happens in the published apps
