### ISSUE TITLE
Undefined symbols

### ISSUE THREAD

**Issue by dayjur** [googleads/googleads-mobile-unity#1875]
getting the undefined symbols headache admob 6.1.2 latest xcode 13

**Comment by NVentimiglia** [comment]
Hi @dayjur, 

The most common cause of missing symbols is missing dependencies. Please try running `pod install` inside terminal from the project directory. Once complete, run the workspace and try again.

If this does not help, feel free to reach back out with a some logging or an example project and I will take another look.
