### ISSUE TITLE
OnAdLeavingApplication, OnAdFailedToLoad no longer exist in v6.1.2

### ISSUE THREAD

**Issue by EugeneKim** [googleads/googleads-mobile-unity#1910]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.22f1 (Not version specific issue)
  * Google Mobile Ads Unity plugin version: v6.1.2
  * Platform: Unity Editor (iOS, Android, Unity Editor)
  * Platform OS version: No platform OS version specific issue.
  * Any specific devices issue occurs on: No device specific issue.
  * Mediation ad networks used, and their versions: N/A

#### Steps to reproduce:
Updated the plugin in existing Unity project to v6.1.2.
The new plug seems have removed the following event handlers:
* OnAdLeavingApplication in BannerView, InterstitialAd
* OnAdFailedToLoad in RewardedAd

Online documentation is still using the missing/removed OnAdLeavingApplication. 
For instance, https://developers.google.com/admob/unity/banner

How can I work around this breaking changes?
Please share any links about the changes, sample using the latest plugin with me.

**Comment by frolky** [comment]
OnAdFailedToLoad not removed

**Comment by EugeneKim** [comment]
@frolky 
Yes you are right. That is still there. But the signature of AdFailedToLoadEventArgs argument was changed. So my current project spit out the compile error.

**Comment by enes-alatas** [comment]
Dear @NVentimiglia , as far as I see, you closed this issue without any other action. However, I could not find a workaround or a replacement for `OnAdLeavingApplication`  here or in the documentation. Do you have any idea what could be a possible workaround/replacement for it?
