### ISSUE TITLE
Inconsistencies between Android and Unity Facebook mediation library version

### ISSUE THREAD

**Issue by IoannisFMG** [googleads/googleads-mobile-unity#1911]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: Irrelevant (but I'm using 2020.3.20f1)
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: Android
  * Platform OS version: Irrelevant
  * Any specific devices issue occurs on: Irrelevant
  * Mediation ad networks used, and their versions: Irrelevant

### [REQUIRED] Step 2: Describe the problem
We're having a hard time deciding which versions of the Facebook Mediation library we should include in our apps.
Here's why:

- The Admob SDK v6.1.2, per se, should use the `play-services-ads` library [version 20.2.0](https://github.com/googleads/googleads-mobile-unity/blob/b56b2f2dc84c8aaecc42c3a145fbf8c39828ff0e/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml#L3)
- The Admob SDK v6.1.2, per se, should use the `mediation:facebook` library [version 6.7.0](https://github.com/googleads/googleads-mobile-unity/blob/b56b2f2dc84c8aaecc42c3a145fbf8c39828ff0e/mediation/Facebook/source/plugin/Assets/GoogleMobileAds/Editor/FacebookMediationDependencies.xml#L3)
- The Facebook Android Mediation Adapter Changelog states that from [version 6.6.0](https://developers.google.com/admob/android/mediation/facebook#6.6.0.0) onwards, the Google Mobile Ads SDK version was updated to 20.3.0

So my question is:
If I tell my game to use v6.7.0 of the Facebook mediation (that requires GMA SDK v 20.3.0) and I include 20.2.0 as its resolved library, won't that potentially produce problems when released (ANRs, crashes, compilation problems, etc)?

Am I missing something here? Isn't supposed for those two SDKs to go hand in hand? At least when it comes to versions and their dependencies?

**Comment by NVentimiglia** [comment]
Hi Ioannis,

Dependency conflicts sometimes happen. I recommend modifying the [GoogleMobileAdsDependencies.xml](https://github.com/googleads/googleads-mobile-unity/blob/b56b2f2dc84c8aaecc42c3a145fbf8c39828ff0e/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml#L3) to support 20.3.0.

Thanks for pointing this out, we will make an update.

**Comment by IoannisFMG** [comment]
Thanks for the clarification! Appreciate it!
