### ISSUE TITLE
NullReferenceException when calling GoogleMobileAds.Api.MobileAds.Initialize in Android builds

### ISSUE THREAD

**Issue by geolands** [googleads/googleads-mobile-unity#1917]
NullReferenceException at GoogleMobileAds.Api.MobileAds.Initialize (System.Action`1[T] initCompleteAction) [0x00000] in <00000000000000000000000000000000>
This occurred in Android builds, but not in editor. I was calling Initialize from the Awake method of a class I created. I was able to stop the error by moving from calling in Awake to Start and by increasing the script execution order of my script. 

It appears that Initialize can be called before some pre-initialize is complete and when that occurs there isn't a proper error.

**Comment by NVentimiglia** [comment]
Please reinstall the plugin or provide more details.
