### ISSUE TITLE
Google namespace

### ISSUE THREAD

**Issue by theneken** [googleads/googleads-mobile-unity#192]
Hi! 

After i launched build in Unity Cloud Build after some minutes i got some errors (iOS and Android):

8150: [Unity] Assets/PlayServicesResolver/Editor/AdMobDependencies.cs(1,7): error CS0246: The type or namespace name `Google' could not be found. Are you missing a using directive or an assembly reference?
8151: [Unity] Assets/PlayServicesResolver/Editor/SampleDependencies.cs(17,7): error CS0246: The type or namespace name `Google' could not be found. Are you missing a using directive or an assembly reference?
8152: [Unity] - Finished compile Library/ScriptAssemblies/Assembly-CSharp-Editor.dll
8153: [Unity] Assets/PlayServicesResolver/Editor/AdMobDependencies.cs(1,7): error CS0246: The type or namespace name `Google' could not be found. Are you missing a using directive or an assembly reference?
8154: [Unity] (Filename: Assets/PlayServicesResolver/Editor/AdMobDependencies.cs Line: 1)
8155: [Unity] Assets/PlayServicesResolver/Editor/SampleDependencies.cs(17,7): error CS0246: The type or namespace name `Google' could not be found. Are you missing a using directive or an assembly reference?
8156: [Unity] (Filename: Assets/PlayServicesResolver/Editor/SampleDependencies.cs Line: 17)

When I try make Android build on my local machine everything goes fine. There's problem in plugin or in Unity Build services?

Thanks

**Comment by rampara** [comment]
Have you included the Google Mobile Ads iOS Framework and any other necessary mediation files within the 'Assets/Plugins/iOS' directory of your project?

**Comment by rampara** [comment]
Closing issue due to non-response. If this issue persists, please re-open.
