### ISSUE TITLE
Have to do pod install each time

### ISSUE THREAD

**Issue by dayjur** [googleads/googleads-mobile-unity#1935]
Unity 2021_2_f1 and admob plugin 6.1.2, latest xcode

Compile from Unity and in Xcode one gets undefined symbols...
I have to every time go into project folder and do pod install to put in missing dependencies

```

**Comment by NVentimiglia** [comment]
Hi @dayjur,

This is an option with the  [external dependency manager](https://github.com/googlesamples/unity-jar-resolver/blob/master/external-dependency-manager-latest.unitypackage).

You may enable this by changing your resolution settings.

The resolution strategy can be changed via the Assets > External Dependency Manager > iOS Resolver > Settings menu.
