### ISSUE TITLE
All java callbacks come in threads executing outside the unity main thread

### ISSUE THREAD

**Issue by EduardoLemos567** [googleads/googleads-mobile-unity#1941]
* Unity version: 2020.3.25f1
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: Android
  * Platform OS version: 9
  * Any specific devices issue occurs on: Moto Z2 Play (tested only on this, i belive its not specific to this device)
  * Mediation ad networks used, and their versions: Tested only using the test ids.

I've a few issues (`"UnityEngine.UnityException: <some Unity API func> can only be called from the main thread"`) with C# callbacks running outside the unity main thread. Easily fixed with some synchronization model like queue lambdas: using a `ConcurrentQueue<Action>` to queue all callbacks and processing them on a MonoBehaviour.Update (or even a coroutine).

Maybe its a documentation issue, because even in the samples, doesn't state anywhere you have to synchronize the callbacks with the unity thread execution.

I suggest implementing a synchronization model in your Assets or stating clearly in the docs and samples that you need to build your synchronization by yourself.

(Here's a unity dev pointing this exact same fact: https://forum.unity.com/threads/androidjavaproxy-correct-jni-thread.1059986/#post-6849917)

**Comment by NVentimiglia** [comment]
The Unity plugin is not thread safe. Please use the MobileAdEventExecutor class to dispatch callbacks back into the main thread before consumption. [Please see this example](https://github.com/googleads/googleads-mobile-unity/blob/master/samples/HelloWorld/Assets/Scripts/GoogleAdMobController.cs#L63).

That said, I agree this is annoying and have added a Feature Request.
