### ISSUE TITLE
Error after closing multiple rewarded Ads - ThreadDeserializer should not parse more data once it has been marked as terminated

### ISSUE THREAD

**Issue by EduardoLemos567** [googleads/googleads-mobile-unity#1942]
* Unity version: 2020.3.25f3
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: Android
  * Platform OS version: 9
  * Any specific devices issue occurs on: Moto Z2 Play (tested only on this)
  * Mediation ad networks used, and their versions: Tested only using the test ids.

#### Steps to reproduce:

Using only the Unity project sample: HelloWorld from this repository.

After multiple calls on: "Request Rewarded Ad" followed by "Show Rewarded Ad" and them finally closing it.
After repeating the process for 3 times (maybe can take more or less), after i close the ad, i got instantly 216
error messages on the Unity console:
`ThreadDeserializer should not parse more data once it has been marked as terminated`

In the android logcat around the same time i got multiple messages like:
>2022/02/22 11:27:35.179 671 16033 Warn AsyncOperation operation=xlb, opStatusCode=12009 [CONTEXT service_id=45 ]
2022/02/22 11:27:35.179 671 16033 Warn AsyncOperation OperationException[Status{statusCode=unknown status code: 12009, resolution=null}]
2022/02/22 11:27:35.179 671 16033 Warn AsyncOperation 	at bbwm.c(:com.google.android.gms@214815027@21.48.15 (100308-414534850):1)
2022/02/22 11:27:35.179 671 16033 Warn AsyncOperation 	at bbwm.f(:com.google.android.gms@214815027@21.48.15 (100308-414534850):45)
2022/02/22 11:27:35.179 671 16033 Warn AsyncOperation 	at agme.run(:com.google.android.gms@214815027@21.48.15 (100308-414534850):11)
2022/02/22 11:27:35.179 671 16033 Warn AsyncOperation 	at cbig.run(:com.google.android.gms@214815027@21.48.15 (100308-414534850):2)
2022/02/22 11:27:35.179 671 16033 Warn AsyncOperation 	at xtm.c(:com.google.android.gms@214815027@21.48.15 (100308-414534850):6)
2022/02/22 11:27:35.179 671 16033 Warn AsyncOperation 	at xtm.run(:com.google.android.gms@214815027@21.48.15 (100308-414534850):7)
2022/02/22 11:27:35.179 671 16033 Warn AsyncOperation 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022/02/22 11:27:35.179 671 16033 Warn AsyncOperation 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022/02/22 11:27:35.179 671 16033 Warn AsyncOperation 	at xzm.run(:com.google.android.gms@214815027@21.48.15 (100308-414534850):0)
2022/02/22 11:27:35.179 671 16033 Warn AsyncOperation 	at java.lang.Thread.run(Thread.java:798)

And them i get no `OnUserEarnedReward` callback after the error, before the error i was getting all callbacks normally. 
This also happened in a project of mine, where i reproduce the same steps from HelloWorld.

#### Relevant Code:
No relevant code, its just the sample HelloWorld on this same repository.

Here is the logcat from the moment: 
[com.DefaultCompany.GoogleAdsHelloWorld-logcat.txt](https://github.com/googleads/googleads-mobile-unity/files/8117559/com.DefaultCompany.GoogleAdsHelloWorld-logcat.txt)
(from the moment i start the app to the first error on unity console, i dont get a single exception in the logcat, just after that first error i start getting these exceptions everytime i close a rewarded Ad)

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
