### ISSUE TITLE
Everytime app ids reset

### ISSUE THREAD

**Issue by maqsuddd** [googleads/googleads-mobile-unity#1943]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.26
  * Google Mobile Ads Unity plugin version: 6.1.1
  * Platform: Unity Editor
  * Platform OS version: macOS Big Sur
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem

Everytime when App ids are filled they disappear after reopening project or after some time.

#### Steps to reproduce:

Close and Reopen project.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by xiaozzz** [comment]
I directly change the file `GoogleMobileAdsSettings.asset` as a workaround.
btw, the latest release has a lot of bugs (some lead to crash), this is the smallest one 😢

**Comment by maqsuddd** [comment]
> latest

Yes, I do the same, but when you need to build the game many times in a row, it's boring to fill in the application IDs every time.

**Comment by Francesco-FL** [comment]
I tried 7.0.2 and the bug is fixed

**Comment by maqsuddd** [comment]
The bug is fixed in 7.0.2 version now
