### ISSUE TITLE
Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_GADRewardBasedVideoAd", referenced from:       objc-class-ref in AdmobPlugin.a(AdmobPlugin.o)

### ISSUE THREAD

**Issue by miguelitolaparra** [googleads/googleads-mobile-unity#1966]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: _____
  * Google Mobile Ads Unity plugin version: GoogleMobileAds-v7.0.0, GoogleMobileAds-v6.1.2  * Platform: iOS 
  * Platform OS version: iOS 11 
  * Any specific devices issue occurs on: iPhone 11
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: 
I am trying to implement ADS AdMob in my Unity game but I am getting the following errors in Xcode.

I have searched for solutions on the internet, but after trying to follow different examples, I cannot solve it.
I have searched for other questions from this site.
I have also tried various versions of GoogleMobileAds and have no success

I don't have much experience with Xcode yet, and I don't know what else I can do

 Can you help me ?
I show the Script that controls the ads
Thanks

warning: arm64 function not 4-byte aligned: _unwind_tester from /Volumes/MIguelApps/UNITY/DestructorDeCerebro/compilaciones/iPhone/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GADRewardBasedVideoAd", referenced from:
      objc-class-ref in AdmobPlugin.a(AdmobPlugin.o)
  "_OBJC_CLASS_$_GADInterstitial", referenced from:
      objc-class-ref in AdmobPlugin.a(AdmobPlugin.o)
     (maybe you meant: _OBJC_CLASS_$_GADInterstitialAd)
  "_OBJC_CLASS_$_GADNativeExpressAdView", referenced from:
      objc-class-ref in AdmobPlugin.a(AdmobPlugin.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

#### Steps to reproduce:

Showing All Issues
Undefined symbol: _OBJC_CLASS_$_GADRewardBasedVideoAd

Undefined symbol: _OBJC_CLASS_$_GADInterstitial

Undefined symbol: _OBJC_CLASS_$_GADNativeExpressAdView

ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Volumes/MIguelApps/UNITY/DestructorDeCerebro/compilaciones/iPhone/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GADRewardBasedVideoAd", referenced from:
      objc-class-ref in AdmobPlugin.a(AdmobPlugin.o)
  "_OBJC_CLASS_$_GADInterstitial", referenced from:
      objc-class-ref in AdmobPlugin.a(AdmobPlugin.o)
     (maybe you meant: _OBJC_CLASS_$_GADInterstitialAd)
  "_OBJC_CLASS_$_GADNativeExpressAdView", referenced from:
      objc-class-ref in AdmobPlugin.a(AdmobPlugin.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)#### Relevant Code:

```
using UnityEngine;
using System.Collections;
using admob;

public class AdManager : MonoBehaviour {

	/// <summary>
/// Esta es la clase principal de administrador de AdMob que puede usar/modificar.
/// Puede establecer diferentes ID para diferentes tipos de anuncios (que se pueden obtener desde el panel de desarrollo de Admob)
/// Y puedes definir nuevas funciones públicas aquí y llamarlas más tarde dentro de tu juego
	/// </summary>

	public string admobBannerID = 		"ca-app-pub-3940256099942544/6300978111";
	public string admobInterstitialID = "ca-app-pub-3940256099942544/1033173712";
	public string admobVideoID =		"ca-app-pub-3940256099942544/5224354917";

	void Awake () {
		DontDestroyOnLoad(gameObject);
	}

	void Start () {
		initAdmob();
	}

	Admob ad;
	//bool isAdmobInited = false;

	void initAdmob() {
		
		//  isAdmobInited = true;
		ad = Admob.Instance();
		ad.bannerEventHandler += onBannerEvent;
		ad.interstitialEventHandler += onInterstitialEvent;
		ad.rewardedVideoEventHandler += onRewardedVideoEvent;
		ad.nativeBannerEventHandler += onNativeBannerEvent;
		ad.initAdmob(admobBannerID, admobInterstitialID);
		//ad.setTesting(true);
		Debug.Log("Admob Inited.");

		//showBannerAd (always)
		Admob.Instance().showBannerRelative(AdSize.Banner, AdPosition.BOTTOM_CENTER, 0);

		//cache an Interstitial ad for later use
		ad.loadInterstitial();
	}

	//gets called from other classes inside the game
	public void showInterstitial() {

		print ("Request for Full AD.");
		if (ad.isInterstitialReady()) {
			ad.showInterstitial();
		}
	}


	void onInterstitialEvent(string eventName, string msg)
	{
		Debug.Log("handler onAdmobEvent---" + eventName + "   " + msg);
		if (eventName == AdmobEvent.onAdLoaded)
		{
			Admob.Instance().showInterstitial();
		}
	}
	void onBannerEvent(string eventName, string msg)
	{
		Debug.Log("handler onAdmobBannerEvent---" + eventName + "   " + msg);
	}
	void onRewardedVideoEvent(string eventName, string msg)
	{
		Debug.Log("handler onRewardedVideoEvent---" + eventName + "   " + msg);
	}
	void onNativeBannerEvent(string eventName, string msg)
	{
		Debug.Log("handler onAdmobNativeBannerEvent---" + eventName + "   " + msg);
	}
}

```

**Comment by miguelitolaparra** [comment]
I finally found on the Unity forums a workaround to fix these errors.
Checking the Symlink Unity libraries option in the Build Settings section
can be seen in the picture
I did not say this may be enough to publish the application.
At the moment, the game works on my iPhone.

![solucionIOS](https://user-images.githubusercontent.com/28591454/158263119-1988966d-7ad9-4e7d-9ecd-abc801924827.png)

**Comment by NVentimiglia** [comment]
Glad you found the solution.

**Comment by miguelitolaparra** [comment]
> Me alegro de que hayas encontrado la solución.
Excuse me.
I did not find a solution, you can read that I still get the error when updating Xcode
Can you open my question please ?
