### ISSUE TITLE
Undefined symbols for architecture arm64: "_OBJC_CLASS_$_GADRewardBasedVideoAd", referenced from: objc-class-ref in AdmobPlugin.a(AdmobPlugin.o)

### ISSUE THREAD

**Issue by miguelitolaparra** [googleads/googleads-mobile-unity#1976]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.1.17f1
  * Google Mobile Ads Unity plugin version:GoogleMobileAds-v7.0.0, GoogleMobileAds-v6.1.2 
  * Platform: iOS (iOS, Android, Unity Editor)
  * Platform OS version: iOS 15 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: iPhone 11
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem

I am trying to implement ADS AdMob in my Unity game but I am getting the following errors in Xcode.

I have searched for solutions on the internet, but after trying to follow different examples, I cannot solve it.
I have searched for other questions from this site.
I have also tried various versions of GoogleMobileAds and have no success

I don't have much experience with Xcode yet, and I don't know what else I can do

Can you help me ?
I show the Script that controls the ads
Thanks

warning: arm64 function not 4-byte aligned: _unwind_tester from /Volumes/MIguelApps/UNITY/DestructorDeCerebro/compilaciones/iPhone/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
"OBJC_CLASS$_GADRewardBasedVideoAd", referenced from:
objc-class-ref in AdmobPlugin.a(AdmobPlugin.o)
"OBJC_CLASS$_GADInterstitial", referenced from:
objc-class-ref in AdmobPlugin.a(AdmobPlugin.o)
(maybe you meant: OBJC_CLASS$_GADInterstitialAd)
"OBJC_CLASS$_GADNativeExpressAdView", referenced from:
objc-class-ref in AdmobPlugin.a(AdmobPlugin.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

#### Steps to reproduce:
Showing All Issues
Undefined symbol: OBJC_CLASS$_GADRewardBasedVideoAd

Undefined symbol: OBJC_CLASS$_GADInterstitial

Undefined symbol: OBJC_CLASS$_GADNativeExpressAdView

ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Volumes/MIguelApps/UNITY/DestructorDeCerebro/compilaciones/iPhone/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
"OBJC_CLASS$_GADRewardBasedVideoAd", referenced from:
objc-class-ref in AdmobPlugin.a(AdmobPlugin.o)
"OBJC_CLASS$_GADInterstitial", referenced from:
objc-class-ref in AdmobPlugin.a(AdmobPlugin.o)
(maybe you meant: OBJC_CLASS$_GADInterstitialAd)
"OBJC_CLASS$_GADNativeExpressAdView", referenced from:
objc-class-ref in AdmobPlugin.a(AdmobPlugin.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

#### Relevant Code:

```
using UnityEngine;
using System.Collections;
using admob;

public class AdManager : MonoBehaviour {

	/// <summary>
/// Esta es la clase principal de administrador de AdMob que puede usar/modificar.
/// Puede establecer diferentes ID para diferentes tipos de anuncios (que se pueden obtener desde el panel de desarrollo de Admob)
/// Y puedes definir nuevas funciones públicas aquí y llamarlas más tarde dentro de tu juego
	/// </summary>

	public string admobBannerID = 		"ca-app-pub-3940256099942544/6300978111";
	public string admobInterstitialID = "ca-app-pub-3940256099942544/1033173712";
	public string admobVideoID =		"ca-app-pub-3940256099942544/5224354917";

	void Awake () {
		DontDestroyOnLoad(gameObject);
	}

	void Start () {
		initAdmob();
	}

	Admob ad;
	//bool isAdmobInited = false;

	void initAdmob() {
		
		//  isAdmobInited = true;
		ad = Admob.Instance();
		ad.bannerEventHandler += onBannerEvent;
		ad.interstitialEventHandler += onInterstitialEvent;
		ad.rewardedVideoEventHandler += onRewardedVideoEvent;
		ad.nativeBannerEventHandler += onNativeBannerEvent;
		ad.initAdmob(admobBannerID, admobInterstitialID);
		//ad.setTesting(true);
		Debug.Log("Admob Inited.");

		//showBannerAd (always)
		Admob.Instance().showBannerRelative(AdSize.Banner, AdPosition.BOTTOM_CENTER, 0);

		//cache an Interstitial ad for later use
		ad.loadInterstitial();
	}

	//gets called from other classes inside the game
	public void showInterstitial() {

		print ("Request for Full AD.");
		if (ad.isInterstitialReady()) {
			ad.showInterstitial();
		}
	}


	void onInterstitialEvent(string eventName, string msg)
	{
		Debug.Log("handler onAdmobEvent---" + eventName + "   " + msg);
		if (eventName == AdmobEvent.onAdLoaded)
		{
			Admob.Instance().showInterstitial();
		}
	}
	void onBannerEvent(string eventName, string msg)
	{
		Debug.Log("handler onAdmobBannerEvent---" + eventName + "   " + msg);
	}
	void onRewardedVideoEvent(string eventName, string msg)
	{
		Debug.Log("handler onRewardedVideoEvent---" + eventName + "   " + msg);
	}
	void onNativeBannerEvent(string eventName, string msg)
	{
		Debug.Log("handler onAdmobNativeBannerEvent---" + eventName + "   " + msg);
	}
}

```

**Comment by NVentimiglia** [comment]
Hi @miguelitolaparra 
 
 This looks like an linker error. We usually solve this by running the `pod install` command or making sure we link symbols statically. Please review your External Dependency Manager settings in:
 
 > Assets/ExternalDependencyManager/iOS Resolver/Settings

**Comment by miguelitolaparra** [comment]
Thank you @NVentimiglia 
I've already tried many things and I can't get it to work.
I have stopped that project and I am working on another one so as not to waste time
