### ISSUE TITLE
error CS0117: `GoogleMobileAds.Android.Utils' does not contain a definition for `UnityAdListenerClassName'

### ISSUE THREAD

**Issue by davidmick** [googleads/googleads-mobile-unity#198]
> Assets/GoogleMobileAds/Platforms/Android/AdListener.cs(12,26): error CS0117: `GoogleMobileAds.Android.Utils' does not contain a definition for UnityAdListenerClassName

> Assets/GoogleMobileAds/Platforms/Android/AdListener.cs(12,15): error CS1502: The best overloaded method match for `UnityEngine.AndroidJavaProxy.AndroidJavaProxy(string)' has some invalid arguments

> 
Assets/GoogleMobileAds/Platforms/Android/AdListener.cs(12,15): error CS1503: Argument `#1' cannot convert `object' expression to type `string'

are there any ways I can fix this issue? or do I need to wait for an update?

**Comment by rampara** [comment]
Are you using source files from an outdated release of the Google Mobile Ads Unity plugin? The AdListener.cs file was removed in a prior release. Can you try removing all files associated with the plugin and importing the latest unity  package.

**Comment by davidmick** [comment]
yes, and will do. Thanks. will post the an update if any more issues arise out of this.

**Comment by rampara** [comment]
Closing the issue for now. Please re-open if you run into any other problems.
