### ISSUE TITLE
Only one time full screen ad appear

### ISSUE THREAD

**Issue by siddharth3322** [googleads/googleads-mobile-unity#199]
I want to use admob fullscreen ad for iOS version of game. For this purpose I have written this code: 

`public class AdMobAdsController : MonoBehaviour
{

	private static AdMobAdsController instance;
	private InterstitialAd interstitial;

	//
	public static AdMobAdsController Instance {
		get {
			return instance;
		}
	}

	void Awake ()
	{
		instance = this;
		// Initialize an InterstitialAd.
		interstitial = new InterstitialAd ("ca-app-pub-7488836279663205/2463284978");
		interstitial.OnAdLoaded += HandleInterstitialLoaded;
		interstitial.OnAdClosed += HandleInterstitialClosed;
		interstitial.OnAdFailedToLoad += HandleInterstitialFailedToLoad;
		RequestAdMobAds ();
	}

	public void ShowAdMobInterstitials ()
	{
		Debug.Log("ad loaded : " + interstitial.IsLoaded ());
		if (interstitial.IsLoaded ())
			interstitial.Show ();
	}

	private void RequestAdMobAds ()
	{
		// Create an empty ad request.
		AdRequest request = new AdRequest.Builder ().Build ();
		// Load the interstitial with the request.
		interstitial.LoadAd (request);
	}

	public void HandleInterstitialLoaded (object sender, EventArgs args)
	{
		print ("HandleInterstitialLoaded event received.");
	}

	public void HandleInterstitialClosed (object sender, EventArgs args)
	{
		print ("HandleInterstitialClosed event received.");
		RequestAdMobAds ();
	}

	public void HandleInterstitialFailedToLoad (object sender, EventArgs args)
	{
		print ("HandleInterstitialFailedToLoad event received.");
	}
}`

Using this code, I am getting fullscreen ad for single time. After that I can't able to see any ads into my iPhone device.  At same time, I have noticed this kind of logcat event: 

> HandleInterstitialClosed event received.
AdMobAdsController:HandleInterstitialClosed(Object, EventArgs)
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

2016-04-04 21:46:46.301 fittheblock[345:30234] <Google> Request Error: Will not send request because interstitial object has been used.
HandleInterstitialFailedToLoad event received.
GoogleMobileAds.iOS.InterstitialClient:LoadAd(AdRequest)
AdMobAdsController:HandleInterstitialClosed(Object, EventArgs)

Please help me to get fullscreen ad all the time. Similar thing happening with my 2 games.

**Comment by rampara** [comment]
On iOS, GADInterstitial is a one time use object. Since the Google Mobile Ads Unity plugin is a wrapper for the Google Mobile Ads Unity SDK, the same limitations apply. You can find more information on our [developer docs](https://developers.google.com/admob/ios/interstitial#only_load_gadinterstitial_once). Every time you make a interstitial ad request, you should use a new interstitial object. Our [sample project](https://github.com/googleads/googleads-mobile-unity/blob/master/samples/HelloWorld/Assets/GoogleMobileAdsDemoScript.cs) is a good example for what best practice should be.

**Comment by siddharth3322** [comment]
@rampara, you reply was correct for this. I can able to get full screen ad multiple times.
Thanks for your quick reply.
