### ISSUE TITLE
'AdFailedToLoadEventArgs' does not contain a definition for 'Message' and cannot convert from 'method group' to 'Action<RewardedInterstitialAd, AdFailedToLoadEventArgs> and InterstitialAd' does not contain a definition for 'OnAdLeavingApplication' and no accessible extension method 'OnAdLeavingApplication' accepting a first argument of type 'InterstitialAd' 

### ISSUE THREAD

**Issue by imjunaidch** [googleads/googleads-mobile-unity#1990]
Step 1: Describe your environment

  * Unity version: 2020.3.17f1
  * Google Mobile Ads Unity plugin version: (V6.1.2)
  * Google-Mobile-Ads-SDK version="~> 8.8"
  * Platform: (Android, Unity Editor)

Step 2: Describe the problem
I just import Google Mobile Ads Unity plugin version: (V6.1.2) , wite code through documentation and have following errors.
Error # 1:
"error CS1061: 'AdFailedToLoadEventArgs' does not contain a definition for 'Message' and no accessible extension method 'Message' accepting a first argument of type 'AdFailedToLoadEventArgs' could be found (are you missing a using directive or an assembly reference?)"
My code which I wrote through documentation is

public void HandleOnAdFailedToLoad(object sender, AdFailedToLoadEventArgs args)
    {
        MonoBehaviour.print("InterstitialFailedToReceiveAd event received with message: "
                            + args.Message);
    }

Error # 2:
"error CS1503: Argument 3: cannot convert from 'method group' to 'Action<RewardedInterstitialAd, AdFailedToLoadEventArgs>'"

Code:
  private RewardedInterstitialAd rewardedInterstitialAd;
    public void RequestRewardedInterstitial()
    {
#if UNITY_ANDROID
        string adUnitId = ""; 
 AdRequest request = new AdRequest.Builder().Build();
RewardedInterstitialAd.LoadAd(adUnitId, request, adLoadCallback);
     } 
private void adLoadCallback(RewardedInterstitialAd ad, string error)
    {
        if (error == null)
        {
            rewardedInterstitialAd = ad;
            rewardedInterstitialAd.OnAdFailedToPresentFullScreenContent += HandleAdFailedToPresent;
            rewardedInterstitialAd.OnAdDidPresentFullScreenContent += HandleAdDidPresent;
            rewardedInterstitialAd.OnAdDidDismissFullScreenContent += HandleAdDidDismiss;
            rewardedInterstitialAd.OnPaidEvent += HandlePaidEvent;
        }
    }

I follow this documentation https://developers.google.com/admob/unity/rewarded-interstitial

Error # 3:
error CS1061: 'InterstitialAd' does not contain a definition for 'OnAdLeavingApplication' and no accessible extension method 'OnAdLeavingApplication' accepting a first argument of type 'InterstitialAd' could be found (are you missing a using directive or an assembly reference?)

code:
  private void RequestInterstitialAd()
    {
    string adUnitId = ""; 
// Initialize an InterstitialAd.
            this.InterstitialAd = new InterstitialAd(adUnitId);
            // Called when an ad request has successfully loaded.
            this.InterstitialAd.OnAdLoaded += HandleOnAdLoaded;
            // Called when an ad request failed to load.
            //   this.interstitial.OnAdFailedToLoad += HandleOnAdFailedToLoad;
            // Called when an ad is shown.
            this.InterstitialAd.OnAdOpening += HandleOnAdOpened;
            // Called when the ad is closed.
            this.InterstitialAd.OnAdClosed += HandleOnAdClosed;
            // Called when the ad click caused the user to leave the application.
             this.InterstitialAd.OnAdLeavingApplication += HandleOnAdLeavingApplication;
// Create an empty ad request.
            AdRequest request = new AdRequest.Builder().Build();
            // Load the interstitial with the request.
            this.InterstitialAd.LoadAd(request);
        
}

 public void HandleOnAdLeavingApplication(object sender, EventArgs args)
    {
        MonoBehaviour.print("InterstitialAdLeavingApplication event received");
    }

please tell me the reason thanks

**Comment by u1tkzw** [comment]
Hello imjunaidch.

I'm working on a Unity Plugin, but I'm just as struggling as you because the documentation hasn't been updated properly.

> Error # 1:

Try the code below.
```
public void HandleOnAdFailedToLoad(object sender, AdFailedToLoadEventArgs args)
{
    MonoBehaviour.print("InterstitialFailedToReceiveAd event received with message: "
                        + args.LoadAdError.GetMessage());
}
```

"LoadAdError" was introduced over a year ago, but the documentation hasn't been updated yet.

#unity #aderror Adds AdError and LoadAdError APIs #1424
https://github.com/googleads/googleads-mobile-unity/pull/1424


> Error # 2:

This is also the same update as Error #1, and the argument type has been changed by introducing "AdFailedToLoadEventArgs".

Try the following:
```
private void adLoadCallback(RewardedInterstitialAd ad, AdFailedToLoadEventArgs args)
{
    //
}
```


> Error # 3:

"OnAdLeavingApplication" has been removed in version 6.0.0.

https://github.com/googleads/googleads-mobile-unity/blob/02a5f6a60b8f97993b2878224d4fe801ce765c0a/ChangeLog.txt

```
**************
Version 6.0.0
**************

Plugin:
- Added support for GMA iOS SDK v8 and GMA Android SDK v20. Requires using GMA iOS SDK v8.0.0 or higher, and GMA Android SDK 20.0.0 or higher.
- Removed MobileAds.Initialize(string appId).
- Removed Birthday, Gender, TestDevices, TagForChildDirectedTreatment properties on AdRequest. TagForChildDirectedTreatment and TestDeviceIds properties are available under RequestConfiguration..
- Removed OnAdLeavingApplication event for all formats.
```

I hope it will be helpful.

**Comment by Meet-BVM** [comment]
I use 2023.3.0b8 verion and Main Fact Thing is my script work all game but one left how i solve
