### ISSUE TITLE
IllegalStateException Activity top position already set to onTop=false

### ISSUE THREAD

**Issue by oddgames-david** [googleads/googleads-mobile-unity#1995]
* Unity version: 2020.3.26f1
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: Android
  * Platform OS version: Android 10, Android 11
  * Any specific devices issue occurs on: Huge range including Samsung Galaxy Note9
  * Mediation ad networks used, and their versions: 
  
com.google.ads.mediation:adcolony:4.5.0.0'
com.google.ads.mediation:applovin:10.3.1.0
com.google.ads.mediation:facebook:6.5.1.1
com.google.ads.mediation:mopub:5.17.0.0
com.google.ads.mediation:unity:3.7.2.0

#### Steps to reproduce:

Unable to reproduce locally but have a few bugs reported to sentry that say it's happening after an ad activity is attempting to resume.

#### Stacktrace:

android.app.ActivityThread in handleTopResumedActivityChanged at line 5121
android.app.servertransaction.TopResumedActivityChangeItem in execute at line 39
android.app.servertransaction.TransactionExecutor in executeCallbacks at line 135
android.app.servertransaction.TransactionExecutor in execute at line 95
android.app.ActivityThread$H in handleMessage at line 2325
android.os.Handler in dispatchMessage at line 106
android.os.Looper in loop at line 246
android.app.ActivityThread in main at line 8633
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 602
com.android.internal.os.ZygoteInit in main at line 1130

#### Log:

0:42:12	unity.logger	Info	[ADVERTS] Showing rewarded interstitial video ad (identifier=v1_6_double_winnings_rewarded_interstitial, adapter=com.google.ads.mediation.admob.AdMobAdapter)
0:42:13	ui.lifecycle	Info	{screen: UnityPlayerActivity, state: paused}
0:42:13	ui.lifecycle	Info	{screen: AdActivity, state: created}
0:42:13	ui.lifecycle	Info	{screen: AdActivity, state: started}
0:42:13	ui.lifecycle	Info	{screen: AdActivity, state: resumed}
0:42:44	exception	Error	IllegalStateException: Activity top position already set to onTop=false

**Comment by nhathuy7996** [comment]
does anyone solved these bug? :'(

**Comment by hsahnv** [comment]
Too many crashes..

**Comment by superoidlau** [comment]
Online apps reported many such crash.
but doesn't look easy to solve.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.

**Comment by superoidlau** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
