### ISSUE TITLE
AdMob 3.0.3 with Facebook plugin failed to repackage resource

### ISSUE THREAD

**Issue by zodlanier** [googleads/googleads-mobile-unity#200]
Hey there, i came through this error:

Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
/Users/admin/Library/Android/sdk/build-tools/22.0.1/aapt package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "/Users/admin/Library/Android/sdk/platforms/android-23/android.jar" -F bin/resources.ap_ --extra-packages com.google.unity:com.unity.purchasing.googleplay:android.support.v7.appcompat:com.unity.purchasing:com.voxelbusters.utility:com.facebook:com.facebook.android:com.google.android.gms:com.voxelbusters.androidnativeplugin:com.google.android.gms.ads:com.google.android.gms:android.support.v4:android.support.v4:com.voxelbusters.utility -S

Currently, i am using Unity 5.3.2p and AdMob 3.0.3. I tried updating my local maven repository and support library but still no luck. What has gone wrong? Thanks!

**Comment by rampara** [comment]
Can you post the details of the error from the console?

**Comment by Fuatnow** [comment]
i have the same problem. did you resolve it?

**Comment by Fuatnow** [comment]
CommandInvokationFailure: Failed to re-package resources. See the Console for details.
/Users/fuatnow/adt/sdk/build-tools/23.0.1/aapt package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "/Users/fuatnow/adt/sdk/platforms/android-23/android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.google.android.gms:com.google.android.gms.ads:com.google.android.gms:android.support.v4:com.fuatnow.game.fiveLegend -S "/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res" -S "/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/google-play-services_lib/res" -S "/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/play-services-ads-8.4.0/res" -S "/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/play-services-basement-8.4.0/res" -S "/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/support-v4-23.1.1/res" -S "/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/unity-android-resources/res"

stderr[
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/unity-android-resources/res/drawable/umeng_fb_arrow_right.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/unity-android-resources/res/drawable-xhdpi/umeng_fb_audio_play_03.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/unity-android-resources/res/drawable-xhdpi/umeng_fb_keyboard.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/unity-android-resources/res/drawable-xhdpi/umeng_fb_plus.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/unity-android-resources/res/drawable-xhdpi/umeng_fb_record.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_alert_dialog_button_bar_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <android.support.v7.widget.ButtonBarLayout>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_alert_dialog_button_bar_material.xml: note: using v17 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/abc_alert_dialog_button_bar_material for configuration v17.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_alert_dialog_material.xml:48: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <android.support.v7.widget.DialogTitle>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_alert_dialog_material.xml: note: using v17 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/abc_alert_dialog_material for configuration v17.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_dialog_title_material.xml:29: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_dialog_title_material.xml: note: using v17 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/abc_dialog_title_material for configuration v17.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_screen_toolbar.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:touchscreenBlocksFocus from <android.support.v7.widget.ActionBarContainer>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_screen_toolbar.xml: note: using v21 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/abc_screen_toolbar for configuration v21.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_search_view.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_search_view.xml: note: using v17 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/abc_search_view for configuration v17.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media.xml: note: using v17 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/notification_template_big_media for configuration v17.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media_narrow.xml:60: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media_narrow.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media_narrow.xml: note: using v17 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/notification_template_big_media_narrow for configuration v17.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_lines.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_lines.xml:77: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_lines.xml:96: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_lines.xml:64: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_lines.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_lines.xml: note: using v17 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/notification_template_lines for configuration v17.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_media.xml:43: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <include>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_media.xml:33: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_media.xml: note: using v17 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/notification_template_media for configuration v17.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_part_chronometer.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <Chronometer>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_part_chronometer.xml: note: using v17 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/notification_template_part_chronometer for configuration v17.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_part_time.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <DateTimeView>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_part_time.xml: note: using v17 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/notification_template_part_time for configuration v17.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/google-play-services_lib/res/layout/place_autocomplete_item_powered_by_google.xml:28: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/google-play-services_lib/res/layout/place_autocomplete_item_powered_by_google.xml:28: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <ImageView>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/google-play-services_lib/res/layout/place_autocomplete_item_powered_by_google.xml:8: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <View>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/google-play-services_lib/res/layout/place_autocomplete_item_powered_by_google.xml: note: using v17 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/place_autocomplete_item_powered_by_google for configuration v17.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/google-play-services_lib/res/layout/place_autocomplete_item_prediction.xml:52: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <TextView>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/google-play-services_lib/res/layout/place_autocomplete_item_prediction.xml:35: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <TextView>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/google-play-services_lib/res/layout/place_autocomplete_item_prediction.xml:8: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentStart from <include>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/google-play-services_lib/res/layout/place_autocomplete_item_prediction.xml: note: using v17 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/place_autocomplete_item_prediction for configuration v17.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/google-play-services_lib/res/layout/place_autocomplete_progress.xml:2: note: removing attribute http://schemas.android.com/apk/res/android:indeterminateTint from <ProgressBar>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/google-play-services_lib/res/layout/place_autocomplete_progress.xml:2: note: removing attribute http://schemas.android.com/apk/res/android:indeterminateTintMode from <ProgressBar>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/google-play-services_lib/res/layout/place_autocomplete_progress.xml: note: using v21 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/place_autocomplete_progress for configuration v21.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:drawableStart from <CheckedTextView>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_multichoice_material.xml: note: using v13 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/select_dialog_multichoice_material for configuration v13.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:drawableStart from <CheckedTextView>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_singlechoice_material.xml: note: using v13 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/select_dialog_singlechoice_material for configuration v13.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/unity-android-resources/res/layout/umeng_fb_contact.xml:10: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <ImageView>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/unity-android-resources/res/layout/umeng_fb_contact.xml: note: using v17 attributes; synthesizing resource com.fuatnow.game.fiveLegend:layout/umeng_fb_contact for configuration v17.
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/unity-android-resources/res/layout/umeng_fb_input_contact.xml:56: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <EditText>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/unity-android-resources/res/layout/umeng_fb_input_contact.xml:56: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <EditText>
/Users/fuatnow/Unity/RMB/Temp/StagingArea/android-libraries/unity-android-resources/res/layout/umeng_fb_input_contact.xml:56: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <EditText>
/Users/fuatnow/Unity/RMB/Temp/Stag<message truncated>

**Comment by Fuatnow** [comment]
All sdks,tools and  libs is latest version.
Before i use admob-sdk2.x , it runs normal.
help me.

**Comment by Fuatnow** [comment]
I had sloved my problem.This is my operation.
When i use 2.x unity-admob sdk, it did not use PlayServiceReslover. I put googleservice-lib in Plugin-Android folder .Now,I has update 3.03 sdk, also put the lib in that folder,so there are two same res.
Remove googleservice-lib  and the android-support-v4.jar(also conflict)，it can run ok.

**Comment by rampara** [comment]
I'm glad you were able to resolve your issue.

**Comment by hameedullahjan835** [comment]
Maybe it's too late to answer, I was facing the same issue, I created a plugin this plugin contains Facebook SDK+Admob+unityads +unity IAP, all of them work together, I've created this plugin in unity 5.6.0, but I've checked it, it is working fine in unity 2017 as well, there is a scene "DemoScene", just open it everything is implemented, unity ads, admob, facebook share with callback, unityIAP.

Note: before importing the plugin kindly delete all the old plugins, also go to services and turn on unity ads.

http://www.mediafire.com/file/ccvj7ixir8ive25/FB_ADMOB_UnityIAP_UnityAds_Plugin_Hameed_Ullah_jan.unitypackage
