### ISSUE TITLE
GMA 7.0.0 Ads Inspector Single ad source test crashes on iOS

### ISSUE THREAD

**Issue by issfire** [googleads/googleads-mobile-unity#2003]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2018.4.36f1
  * Google Mobile Ads Unity plugin version: 7.0.0
  * Platform: iOS (iOS, Android, Unity Editor)
  * Platform OS version: iOS 14.8.1 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: iPhone 11
  * Mediation ad networks used, and their versions: Facebook 3.6.1, AppLovin 6.1.0

#### Steps to reproduce:

- Initialize GMA
- Open Ads Inspector
- Choose "Single Ad Source Test"
- Choose either AppLovin or Facebook (Does not matter which, we have also tested removing other ad networks, so that applovin or Facebook is the only one available)
- Restart the app. On initializing GMA, the game hard crashes.
- Please see attached crash stack.
[bugsnag_error_stacktrace_NSInvalidArgumentException_event_62446f880092f4c7e6750000.txt](https://github.com/googleads/googleads-mobile-unity/files/8381730/bugsnag_error_stacktrace_NSInvalidArgumentException_event_62446f880092f4c7e6750000.txt)

It seems like trying to get the load fail error is causing some kind of crash. 
![Code](https://user-images.githubusercontent.com/129688/160870274-aad2da57-34f0-4157-8d42-bd2a208abb44.JPG)

Note that:
- Testing with mediation disabled or with the test ad id ca-app-pub-3940256099942544/5224354917 works perfectly fine on both iOS and Android
- Testing with mediation enabled works perfectly fine on Android. On iOS this crashes occassionally with the same issue. Forcing a single ad source just makes this 100%

**Comment by NVentimiglia** [comment]
Fixed in 7.0.1.
