### ISSUE TITLE
AndroidJavaException: no method with name='setRequestAgent'

### ISSUE THREAD

**Issue by subzeroz** [googleads/googleads-mobile-unity#201]
I am trying to integrate Admob to my game. I am not getting errors in the Unity editor, but when I debug the game in Android Studio, I get this error:

`04-07 22:27:34.194: I/Unity(23566): AndroidJavaException: java.lang.NoSuchMethodError: no method with name='setRequestAgent' signature='(Ljava/lang/String;)Ljava/lang/Object;' in class Lcom/google/android/gms/ads/AdRequest$Builder; 04-07 22:27:34.194: I/Unity(23566): java.lang.NoSuchMethodError: no method with name='setRequestAgent' signature='(Ljava/lang/String;)Ljava/lang/Object;' in class Lcom/google/android/gms/ads/AdRequest$Builder; 04-07 22:27:34.194: I/Unity(23566): at com.unity3d.player.UnityPlayer.nativeRender(Native Method) 04-07 22:27:34.194: I/Unity(23566): at com.unity3d.player.UnityPlayer.a(Unknown Source) 04-07 22:27:34.194: I/Unity(23566): at com.unity3d.player.UnityPlayer$b.run(Unknown Source) 04-07 22:27:34.194: I/Unity(23566): at UnityEngine.AndroidJNISafe.CheckException () [0x00085] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJNISafe.cs:25 04-07 22:27:34.194: I/Unity(23566): at UnityEngine.AndroidJNISafe.GetMethodID (IntPtr obj, System.String name, System.String sig) [0x00013] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJNISafe.cs:68 04-07 22:27:34.194: I/Unity(23566): at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.String signature, Boolean isStatic) [0x00022] in /Users/bu `

**Comment by rampara** [comment]
Are you using the latest version of Google Play Services?

**Comment by subzeroz** [comment]
@rampara When I open the version.xml file, this is what is written inside:
`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <integer name="google_play_services_version">8487000</integer>
</resources>`

**Comment by rampara** [comment]
The unity package you linked in #193 contains out-dated versions of play-services-ads and play-services-base (which is why the setRequestAgent method is missing). Can you ensure the ANDROID_HOME environment variable points to the location where you have the latest version of the Android SDK installed.

**Comment by subzeroz** [comment]
@rampara How come I have out-dated versions of play-services-ads and play-services-base ?
I downloaded the Google Mobile Ads Unity package from here:
https://github.com/googleads/googleads-mobile-unity/releases
And also the ANDROID_Home is pointing to the correct location of the Android SDK.
Anyway if the versions are outdated, then how can I download latest versions ?

**Comment by rampara** [comment]
Version 3 and above of this Unity plugin uses the [JarResolver](https://github.com/googlesamples/unity-jar-resolver) library to resolve Google Play Services dependencies (dependencies declared in [AdMobDependencies.cs](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/PlayServicesResolver/Editor/AdMobDependencies.cs)) and copy the appropriate AAR files to the `Assets/Plugins/Android` directory of your Unity project. The JarResolver code uses the Android SDK location set in Editor preferences or defaults to ANDROID_HOME environment variable.

**Comment by subzeroz** [comment]
Sorry I did not understand what exactly are the steps I should do to make it work?

**Comment by rampara** [comment]
The first place to start would be to ensure the android SDK location under Unity editor settings points to the latest version of the Android SDK.

**Comment by Fuatnow** [comment]
I got a same problem

**Comment by rampara** [comment]
@Fuatnow does android SDK location under Unity editor settings and the ANDROID_HOME environment variable point to the latest version of the Android SDK?

**Comment by rampara** [comment]
Closing issue due to non-response. If this issue persists, please re-open.
