### ISSUE TITLE
Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by yupuyang** [googleads/googleads-mobile-unity#2019]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GADServerSideVerificationOptions", referenced from:
      objc-class-ref in unity-plugin-library.a(GADUInterface.o)
  "_GADErrorUserInfoKeyResponseInfo", referenced from:
      _GADUGetAdErrorResponseInfo in unity-plugin-library.a(GADUInterface.o)
  "_OBJC_CLASS_$_GADExtras", referenced from:
      objc-class-ref in unity-plugin-library.a(GADURequest.o)
  "_OBJC_CLASS_$_GADRequest", referenced from:
      objc-class-ref in unity-plugin-library.a(GADURequest.o)
  "_GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth", referenced from:
      +[GADUPluginUtil adaptiveAdSizeForWidth:orientation:] in unity-plugin-library.a(GADUPluginUtil.o)
  "_GADPortraitAnchoredAdaptiveBannerAdSizeWithWidth", referenced from:
      +[GADUPluginUtil adaptiveAdSizeForWidth:orientation:] in unity-plugin-library.a(GADUPluginUtil.o)
  "_CGSizeFromGADAdSize", referenced from:
      +[GADUPluginUtil safeAdSizeForAdSize:] in unity-plugin-library.a(GADUPluginUtil.o)
  "_GADLandscapeAnchoredAdaptiveBannerAdSizeWithWidth", referenced from:
      +[GADUPluginUtil adaptiveAdSizeForWidth:orientation:] in unity-plugin-library.a(GADUPluginUtil.o)
  "_OBJC_CLASS_$_GADRewardedInterstitialAd", referenced from:
      objc-class-ref in unity-plugin-library.a(GADURewardedInterstitialAd.o)
  "_GADAdSizeFullWidthPortraitWithHeight", referenced from:
      +[GADUPluginUtil adSizeForWidth:height:] in unity-plugin-library.a(GADUPluginUtil.o)
  "_GADAdSizeEqualToSize", referenced from:
      +[GADUPluginUtil safeAdSizeForAdSize:] in unity-plugin-library.a(GADUPluginUtil.o)
  "_kGADAdSizeSmartBannerLandscape", referenced from:
      -[GADUBanner initWithSmartBannerSizeAndBannerClientReference:adUnitID:adPosition:] in unity-plugin-library.a(GADUBanner.o)
      -[GADUBanner initWithSmartBannerSizeAndBannerClientReference:adUnitID:customAdPosition:] in unity-plugin-library.a(GADUBanner.o)
      +[GADUPluginUtil safeAdSizeForAdSize:] in unity-plugin-library.a(GADUPluginUtil.o)
  "_GADAdSizeFromCGSize", referenced from:
      +[GADUPluginUtil safeAdSizeForAdSize:] in unity-plugin-library.a(GADUPluginUtil.o)
      +[GADUPluginUtil adSizeForWidth:height:] in unity-plugin-library.a(GADUPluginUtil.o)
  "_OBJC_CLASS_$_GADInterstitialAd", referenced from:
      objc-class-ref in unity-plugin-library.a(GADUInterstitial.o)
  "_OBJC_CLASS_$_GADBannerView", referenced from:
      objc-class-ref in unity-plugin-library.a(GADUBanner.o)
  "_OBJC_CLASS_$_GADMobileAds", referenced from:
      objc-class-ref in unity-plugin-library.a(GADUInterface.o)
  "_OBJC_CLASS_$_GADAppOpenAd", referenced from:
      objc-class-ref in unity-plugin-library.a(GADUAppOpenAd.o)
  "_kGADAdSizeSmartBannerPortrait", referenced from:
      -[GADUBanner initWithSmartBannerSizeAndBannerClientReference:adUnitID:adPosition:] in unity-plugin-library.a(GADUBanner.o)
      -[GADUBanner initWithSmartBannerSizeAndBannerClientReference:adUnitID:customAdPosition:] in unity-plugin-library.a(GADUBanner.o)
  "_OBJC_CLASS_$_GADRewardedAd", referenced from:
      objc-class-ref in unity-plugin-library.a(GADURewardedAd.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by NVentimiglia** [comment]
Please try running pod install as described in the [Jar resolver library](https://github.com/googlesamples/unity-jar-resolver).

If this fails, please update this ticket with details about what version you are using and environment.
