### ISSUE TITLE
Adding Admob to Unity Android project is causing 'Failed to re-package resources' error

### ISSUE THREAD

**Issue by 11Sheep** [googleads/googleads-mobile-unity#202]
HI All,

I added admob to my project recently and got this error on my Android local build
I'm pretty sure that it worked before, anyway this is the configuration i use:
- Unity 4.3.4f1
- Build tools 23.03 
- Currently the Android SDK is the most updated with all components
- i am using also Google analytics (v4) in my project

Here is the error i get in Unity console: 
-----------------------------------------------------------------------------
Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Program Files (x86)\Android\android-sdk\build-tools\23.0.3\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Program Files (x86)/Android/android-sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages com.unity.purchasing.amazon:android.support.v7.appcompat:com.unity.purchasing:com.google.android.gms:com.android.vending.billing:com.google.unity:com.unity.purchasing.googleplay:com.google.android.gms.ads:com.google.android.gms:android.support.v4:com.unity3d.ads.android -S "C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\AmazonAppStore\res" -S "C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res" -S "C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\common\res" -S "C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\google-play-services_lib\res" -S "C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\GoogleAIDL\res" -S "C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\GooglePlay\res" -S "C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\play-services-ads-8.4.0\res" -S "C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\play-services-basement-8.4.0\res" -S "C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\support-v4-23.1.1\res" -S "C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\unityads-release\res"

stderr[
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_button_bar_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <android.support.v7.widget.ButtonBarLayout>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_button_bar_material.xml: note: using v17 attributes; synthesizing resource com.sheep.sheepuzzle:layout/abc_alert_dialog_button_bar_material for configuration v17.
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_material.xml:48: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <android.support.v7.widget.DialogTitle>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_material.xml: note: using v17 attributes; synthesizing resource com.sheep.sheepuzzle:layout/abc_alert_dialog_material for configuration v17.
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_dialog_title_material.xml:29: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_dialog_title_material.xml: note: using v17 attributes; synthesizing resource com.sheep.sheepuzzle:layout/abc_dialog_title_material for configuration v17.
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_screen_toolbar.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:touchscreenBlocksFocus from <android.support.v7.widget.ActionBarContainer>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_screen_toolbar.xml: note: using v21 attributes; synthesizing resource com.sheep.sheepuzzle:layout/abc_screen_toolbar for configuration v21.
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_search_view.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_search_view.xml: note: using v17 attributes; synthesizing resource com.sheep.sheepuzzle:layout/abc_search_view for configuration v17.
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml: note: using v17 attributes; synthesizing resource com.sheep.sheepuzzle:layout/notification_template_big_media for configuration v17.
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:60: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml: note: using v17 attributes; synthesizing resource com.sheep.sheepuzzle:layout/notification_template_big_media_narrow for configuration v17.
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:77: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:96: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:64: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml: note: using v17 attributes; synthesizing resource com.sheep.sheepuzzle:layout/notification_template_lines for configuration v17.
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml:43: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <include>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml:33: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml: note: using v17 attributes; synthesizing resource com.sheep.sheepuzzle:layout/notification_template_media for configuration v17.
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_chronometer.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <Chronometer>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_chronometer.xml: note: using v17 attributes; synthesizing resource com.sheep.sheepuzzle:layout/notification_template_part_chronometer for configuration v17.
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_time.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <DateTimeView>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_time.xml: note: using v17 attributes; synthesizing resource com.sheep.sheepuzzle:layout/notification_template_part_time for configuration v17.
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_powered_by_google.xml:28: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_powered_by_google.xml:28: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <ImageView>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_powered_by_google.xml:8: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <View>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_powered_by_google.xml: note: using v17 attributes; synthesizing resource com.sheep.sheepuzzle:layout/place_autocomplete_item_powered_by_google for configuration v17.
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_prediction.xml:52: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <TextView>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_prediction.xml:35: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <TextView>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_prediction.xml:8: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentStart from <include>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_prediction.xml: note: using v17 attributes; synthesizing resource com.sheep.sheepuzzle:layout/place_autocomplete_item_prediction for configuration v17.
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_progress.xml:2: note: removing attribute http://schemas.android.com/apk/res/android:indeterminateTint from <ProgressBar>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_progress.xml:2: note: removing attribute http://schemas.android.com/apk/res/android:indeterminateTintMode from <ProgressBar>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_progress.xml: note: using v21 attributes; synthesizing resource com.sheep.sheepuzzle:layout/place_autocomplete_progress for configuration v21.
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:drawableStart from <CheckedTextView>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml: note: using v13 attributes; synthesizing resource com.sheep.sheepuzzle:layout/select_dialog_multichoice_material for configuration v13.
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
C:\Users\Lior\Documents\UnityProjects\SheepPuzzleGame\PuzzleGame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlecho<message truncated>
--------------------------------------

Thanks in advance,
Lior

**Comment by subzeroz** [comment]
@11Sheep If you imported the **google-play-services_lib** folder to your Unity project, copy the file: version.xml from google-play-services_lib/res/values/ and create a folder named **res** in Plugins/Android/GoogleMobileAdsPlugin/ .
And in this new **res** folder, create another folder named **values** , then paste the version.xml there. 
If you still get the error, try to delete the whole **google-play-services_lib** folder from your project.

**Comment by rampara** [comment]
With version 3.0.0 and greater of this plugin, you no longer have to include the entire Google Play Services library project into your Unity application. The plugin uses the [JarResolver](https://github.com/googlesamples/unity-jar-resolver) library to resolve declared Google Play Services dependencies. @11Sheep After removing the Google Play Services library project, are you still running into issues?

**Comment by 11Sheep** [comment]
HI subzeroz,
And thanks for the answer.

I did what you suggested and it did not solve the problem , but when i
added the file 'play-services-analytics-8.4.0' from C:\Program Files
(x86)\Android\android-sdk\extras\google\m2repository\com\google\android\gms\play-services-analytics\8.4.0
it worked.


On Wed, Apr 13, 2016 at 8:33 PM rampara <notifications@github.com> wrote:

> With version 3.0.0 and greater of this plugin, you no longer have to
> include the entire Google Play Services library project into your Unity
> application. The plugin uses the JarResolver
> <https://github.com/googlesamples/unity-jar-resolver> library to resolve
> declared Google Play Services dependencies. @11Sheep
> <https://github.com/11Sheep> After removing the Google Play Services
> library project, are you still running into issues?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/googleads/googleads-mobile-unity/issues/202#issuecomment-209556861>
>
-- 
*Try our new mobile game (and don't forget to rate 5 star!!!) *Android
<https://play.google.com/store/apps/details?id=com.sheep.chefmaster>* | *iOS
<https://itunes.apple.com/us/app/chef-timber-world-master-cooking/id1091238300?ls=1&mt=8>



Lior Bruder | CEO | lior@11sheep.com
Office +972-3-5411131 | Fax: +972-77-4703830 | www.11sheep.com
