### ISSUE TITLE
I can not generate .xcworkspace file[GoogleMobileAds-v7.0.0] 

### ISSUE THREAD

**Issue by GITHUB243884919** [googleads/googleads-mobile-unity#2026]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: __2018.4.10___
  * Google Mobile Ads Unity plugin version: ____GoogleMobileAds-v7.0.0_
  * Platform: ___Unity Editor__ (iOS, Android, Unity Editor)
  * Platform OS version: __IOS 9___ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem
**I can not generate .xcworkspace file, unity editor show:**
[!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
  In Podfile:
    Google-Mobile-Ads-SDK (~> 9.0)
Specs satisfying the `Google-Mobile-Ads-SDK (~> 9.0)` dependency were found, but they required a higher minimum deployment target.
<img width="411" alt="WX20220416-163029@2x" src="https://user-images.githubusercontent.com/17681628/163668203-d6783175-e75e-4a22-b710-bb49106a41bc.png">

**when I enter my xcode project folder and type "pod update" , show same error**

<img width="574" alt="WX20220416-163524@2x" src="https://user-images.githubusercontent.com/17681628/163668345-4571291b-9450-4a60-9853-e54dfb374169.png">

 

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by Herschy0829** [comment]
你可以试着打开podfile文件把依赖后面的版本号删除，然后保存执行pod install

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
