### ISSUE TITLE
GoogleMobileAdsSettings reset automatically in v7.0.0

### ISSUE THREAD

**Issue by adibacco** [googleads/googleads-mobile-unity#2032]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.38f1
  * Google Mobile Ads Unity plugin version: 7.0.0
  * Platform: Anroid (iOS, Android, Unity Editor)
  * Platform OS version: Android all (eg iOS 10, Android 9)

#### Steps to reproduce:

I add my Google Mobile Ads App Ids  from Unity but after I close Unity and I restart it, the settings are gone.

**Comment by tomurtogu** [comment]
For now, you can fix this problem manually. Note that if you delete the package and re-import it, your changes are going to lost.

Open Assets\GoogleMobileAds\Editor\GoogleMobileAdsSettings.cs
Change the script like this:

`        public string GoogleMobileAdsAndroidAppId
        {
            get { return Instance.adMobAndroidAppId; }

            set { Instance.adMobAndroidAppId = value; **EditorUtility.SetDirty(Instance);** }
        }

        public string GoogleMobileAdsIOSAppId
        {
            get { return Instance.adMobIOSAppId; }

            set { Instance.adMobIOSAppId = value; **EditorUtility.SetDirty(Instance);** }
        }

        public bool DelayAppMeasurementInit
        {
            get { return Instance.delayAppMeasurementInit; }

            set { Instance.delayAppMeasurementInit = value; **EditorUtility.SetDirty(Instance);** }
        }`

**Comment by xGeorgeV** [comment]
Always use Unity Menu > Assets > Google Mobile Ads > Settings menu point for set App IDs.
If you set the App IDs at Project Window / Assets / GoogleMobileAds / Resources / GoogleMobileAdsSettings the App IDs will be deleted after restart the Unity Editor.

**Comment by NVentimiglia** [comment]
Fixed in 7.0.1.
