### ISSUE TITLE
GetHeightInPixels returns wrong value on real device (iphone6sp, iphone 7p)

### ISSUE THREAD

**Issue by FlashTang** [googleads/googleads-mobile-unity#2037]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.32f1c1
  * Google Mobile Ads Unity plugin version: 7.0.0
  * Platform: iOS
  * Platform OS version: iOS 14.8.1 and 13.2.3
 
#### Steps to reproduce:

What happened? How can we make the problem occur?
BannerView.GetHeightInPixels returns wrong value on real device(iphone 6sp, 7p) , a little bit taller than the real banner height 
but it works fine on Xcode simulator (tested on 7p 8 8p 12  12pro max....)

here is the screenshoots:
wroks fine on simulator (iphone 7p - iOS 14.5)
<img width="283" alt="Screen Shot 2022-04-28 at 4 51 08 PM" src="https://user-images.githubusercontent.com/920751/165715277-7929d6b4-5374-4e73-9261-9cc1af269bdc.png">
wrong on real device iphone7p (14.8.1)
<img width="334" alt="Screen Shot 2022-04-28 at 4 54 22 PM" src="https://user-images.githubusercontent.com/920751/165715885-f9533e1c-303c-4f6d-a222-7726b43113d6.png">
 I don't have real iphone 8p or iphone 12 pro ..  to test, so I don't know if it works fine

P.S. if I use 
`50f * Screen.dpi / 154` to get the pixel height (instead of GetHeightInPixels) , it can get the correct height on real device, but wrong on simulator... I'm confused now

Thanks.

**Comment by FlashTang** [comment]
I found the reason 
Unity , Screen.height is 1920 on real device iPhone7 plus  , but Screen.height  is 2208 on iPhone7 plus  simulator
Why Screen.height is different ?

**Comment by FlashTang** [comment]
Since I set Camera.main.orthographicSize = Screen.height / 200f , that's why on real device 150 pixel is taller
But now how can I get 2208 like admob does (seems 2208 is correct for admob)
So I can set orthographicSize to the "correct height" / 200f

**Comment by FlashTang** [comment]
I think admob should consider this on GetHeightInPixels
https://stackoverflow.com/questions/25755443/iphone-6-plus-resolution-confusion-xcode-or-apples-website-for-development

**Comment by NVentimiglia** [comment]
Hi @FlashTang ,

I am curious how you are calculating the banner height in these two situations. Could you provide a minimal sample replicating the issue so I can look further?
