### ISSUE TITLE
Not showing ads Unity Ads 7.0.0 SDK

### ISSUE THREAD

**Issue by antoniotonev** [googleads/googleads-mobile-unity#2038]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.33f1
  * Google Mobile Ads Unity plugin version: 7.0.0
  * Platform: Android
  * Platform OS version: Android 9
  * Any specific devices issue occurs on: Tested on Xiaomi Redmi 6, Xiaomi Redmi 7
  * Mediation ad networks used, and their versions: NO

### [REQUIRED] Step 2: Describe the problem

I had implemented the Admob SDK for Unity, but the ads are NOT showing on real device. Test ads are completely okay, but the real ads not showed. With old version of the SDK everything's is fine 6.1.1 test ads and live ads works. I don't have any error codes in LogCat. Do you have any idea what is wrong ?

Thank you.

**Comment by FlashTang** [comment]
Same here , iOS ,with app id and unit created several years ago
`HandleFailedToReceiveAd event received with message: Request Error: No ad to show.`
Maybe it just because "no ad to show" ?

**Comment by antoniotonev** [comment]
I don't have such kind of error. Ads just NOT showed, no error or fault codes. :( If I roll back to the old version of the SDK all ads are shown.

**Comment by FlashTang** [comment]
> I don't have such kind of error. Ads just NOT showed, no error or fault codes. :( If I roll back to the old version of the SDK all ads are shown.

Try add this handler , see if you can see the  failed message
```
bannerView.OnAdFailedToLoad += this.HandleOnAdFailedToLoad;

public void HandleOnAdFailedToLoad(object sender, AdFailedToLoadEventArgs args) {
       print("HandleFailedToReceiveAd event received with message: " + args.LoadAdError.GetMessage());
}
```

I just tried both 6.1.2 and 7.0.0 ,  no ad to show 
but the app id and unit id used in my old iOS app ( which made with adobe air 5 yeas ago) does show the banner (just tried)

**Comment by antoniotonev** [comment]
I just completely forgot for this event, because my code always worked. The error code is: "Ad failed to load : 3", which means no fill. When the fill will come, nobody knows. :D
