### ISSUE TITLE
Fullscreen ads appearing single time in android

### ISSUE THREAD

**Issue by siddharth3322** [googleads/googleads-mobile-unity#204]
At present I am getting fullscreen ad in actual device just single or twice. After that I am getting following message in logcat when I try to display ads in game.

> no fill from ad server 

I have used following code to display ads.

`void Awake ()
	{
		instance = this;
		RequestAdMobAds ();
	}

	public void ShowAdMobInterstitials ()
	{
		Debug.Log ("Is Loaded : " + interstitial.IsLoaded ());
		if (interstitial.IsLoaded ())
			interstitial.Show ();
		else
			RequestAdMobAds();
	}

	private void RequestAdMobAds ()
	{
		// Initialize an InterstitialAd.
		interstitial = new InterstitialAd ("");
		interstitial.OnAdLoaded += HandleInterstitialLoaded;
		interstitial.OnAdClosed += HandleInterstitialClosed;
		interstitial.OnAdFailedToLoad += HandleInterstitialFailedToLoad;

		// Create an empty ad request.
		AdRequest request = new AdRequest.Builder ().Build ();
		// Load the interstitial with the request.
		interstitial.LoadAd (request);
	}

	public void HandleInterstitialLoaded (object sender, EventArgs args)
	{
		print ("HandleInterstitialLoaded event received.");
	}

	public void HandleInterstitialClosed (object sender, EventArgs args)
	{
		print ("HandleInterstitialClosed event received.");
		RequestAdMobAds ();
	}

	public void HandleInterstitialFailedToLoad (object sender, EventArgs args)
	{
		print ("HandleInterstitialFailedToLoad event received.");
	}`

As well I want to mention that I am getting test ads all the time if I add device into code.
Please give me some suggestion what to do for this?

**Comment by rampara** [comment]
Since you're able to receive ads, this doesn't seem like an issue with the plugin or Google Mobile Ads SDK. This issue tracker is just for reporting issues and feature requests for the Google Mobile Ads Unity plugin. General AdMob support is available at https://support.google.com/admob/v2/.

**Comment by siddharth3322** [comment]
@rampara , I can't able to find any place where I can able to ask for help in above link.
All they are just display FAQ. Please give me some what more help in this.

**Comment by rampara** [comment]
You can also try the [Google Mobile Ads support forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).

**Comment by siddharth3322** [comment]
@rampara , Thanks for your reply. I created over new thread for this problem and hope some positive reply come for me :)
