### ISSUE TITLE
libc++abi: terminating with uncaught exception of type Il2CppExceptionWrapper

### ISSUE THREAD

**Issue by kevinsquid** [googleads/googleads-mobile-unity#2043]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.38f1
  * Google Mobile Ads Unity plugin version: 7.0.0
  * Platform: iOS (iOS, Android, Unity Editor)
  * Platform OS version: 15.4.1 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: Google Mobile Ads Native 7.0.0

### [REQUIRED] Step 2: Describe the problem

It is not possible to load a Native Ad. Once the Native Ad is requested by following the example code. The application will crash in Unity due to an unhandled Exception.

#### Steps to reproduce:

1: Start an Empty Project
2: Install Google Mobile Ads 7.0.0
3: Install Google Mobiel Ads Native
4: Follow the code snippet https://developers.google.com/admob/unity/native
5: Run the application

What happened? How can we make the problem occur?

The application will crash after executing adLoader.LoadAd() in the next update loop.

This could be a description, log/console output, etc.

libc++abi: terminating with uncaught exception of type Il2CppExceptionWrapper
dyld4 config: DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/usr/lib/libMTLCapture.dylib
terminating with uncaught exception of type Il2CppExceptionWrapper
(lldb) 

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

Progress with tutorial until the following code has been added.
```
// TODO(you): code here to reproduce the problem
```

private void RequestNativeAd() {
    AdLoader adLoader = new AdLoader.Builder(INSERT_AD_UNIT_HERE)
        .ForNativeAd()
        .Build();
    adLoader.OnNativeAdLoaded += this.HandleNativeAdLoaded;
    adLoader.OnAdFailedToLoad += this.HandleAdFailedToLoad;
    adLoader.LoadAd(new AdRequest.Builder().Build());
}

**Comment by NVentimiglia** [comment]
Hi @kevinsquid 

I did not replicate this locally. That said, could you provide any additional details or perhaps a minimal sample replicating the issue?
