### ISSUE TITLE
Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without an application ID. Google AdMob publishers, follow instructions at 

### ISSUE THREAD

**Issue by yupuyang** [googleads/googleads-mobile-unity#2045]
Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without an application ID. Google AdMob publishers, follow instructions at https://googlemobileadssdk.page.link/admob-ios-update-plist to set a valid application ID. Google Ad Manager publishers, follow instructions at https://googlemobileadssdk.page.link/ad-manager-ios-update-plist.'
*** First throw call stack:
(0x1dc1add78 0x1f4e12734 0x1dc284fcc 0x101420974 0x101420b10 0x103058c6c 0x10305a7bc 0x10305d320 0x10306e878 0x10306f264 0x24d8e2080 0x24d8e1e5c)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
*** Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without an application ID. Google AdMob publishers, follow instructions at https://googlemobileadssdk.page.link/admob-ios-update-plist to set a valid application ID. Google Ad Manager publishers, follow instructions at https://googlemobileadssdk.page.link/ad-manager-ios-update-plist.'
terminating with uncaught exception of type NSException

![image](https://user-images.githubusercontent.com/17735448/167244154-0de82658-bcd4-4641-80dc-f1ed12dbce27.png)

![image](https://user-images.githubusercontent.com/17735448/167244196-971a9baf-4c8e-4358-afcd-7947239ca3ec.png)

**Comment by yupuyang** [comment]
![image](https://user-images.githubusercontent.com/17735448/167244250-93df814e-6bcc-4aa9-a650-50b2fc37fded.png)

**Comment by sanghyeon-toodat** [comment]
Hi @NVentimiglia 
Did you find any solution for your problem?
Currently I'm facing exact same issue that you mentioned.
I want to implement defensive code to handle cases where an invalid GADApplicationId is provided.
