### ISSUE TITLE
I cannot show the banner in a Vertical Layout Group

### ISSUE THREAD

**Issue by Francesco-FL** [googleads/googleads-mobile-unity#2057]
Currently all banner positions are anchored to the screen (bottom, top, center, etc.)

It is not possible to insert several banners in a long text in the style of newspaper article.

If there was the possibility through code to manage the position of the banner ad like a normal GameObject, I could easily insert it in a Vertical Layout Group.

![image](https://user-images.githubusercontent.com/83022092/169656775-ae34182a-02cf-4dce-abbf-9bf45bbbea82.png)

**Comment by NVentimiglia** [comment]
Hi Francesco, you might want to look at Native ads for this solution.

https://developers.google.com/admob/unity/native
