### ISSUE TITLE
Ah, I just noticed that it is an error in recv_rules, which means that an exclude overflowed the "line" buffer, which is BIGPATHBUFLEN.  That should be at least 4K of space in a modern rsync.  I don't see where you're using excludes, though.  You might try specifying `--dry-run` (`-n`) and then tweak some options, such as removing `-z` and/or `-u` and see if you can figure out what is weird.  You may also need to compile a newer rsync.

### ISSUE THREAD

**Issue by Becks76** [googleads/googleads-mobile-unity#2058]
Ah, I just noticed that it is an error in recv_rules, which means that an exclude overflowed the "line" buffer, which is BIGPATHBUFLEN.  That should be at least 4K of space in a modern rsync.  I don't see where you're using excludes, though.  You might try specifying `--dry-run` (`-n`) and then tweak some options, such as removing `-z` and/or `-u` and see if you can figure out what is weird.  You may also need to compile a newer rsync.

_Originally posted by @WayneD in https://github.com/WayneD/rsync/issues/269#issuecomment-1003795089_

**Comment by NVentimiglia** [comment]
I think this was posted by mistake. Feel free to reopen if you can explain the issue and how it pertains to Google Mobile Ads.
