### ISSUE TITLE
7.0.1 iOS submission failed: The bundle at ‘App/Frameworks/UnityFramework.framework' contains disallowed file 'Frameworks'. With error code STATE_ERROR.VALIDATION_ERROR.90206

### ISSUE THREAD

**Issue by zodiac2k** [googleads/googleads-mobile-unity#2065]
Environment:

Unity version: 2020.3.34f1
Google Mobile Ads Unity plugin version: 7.0.1
Platform: iOS
Platform OS version: 12.4
Mediation ad networks used, and their versions: none

Building my app with the latest plugin works but when trying to submit my app to the appstore the following error occurs and the app is rejected:

The bundle at ‘App/Frameworks/UnityFramework.framework' contains disallowed file 'Frameworks'. With error code STATE_ERROR.VALIDATION_ERROR.90206

After some researching I found other plugins issues related to problems with the ExternalDepencyMananger V1.2.170 (and onwards). 
I moved back to ExternalDependencyManager 1.2.169 and I was able to submit my app.

I haven't had time yet to compare the build results but I seems like the new ExternalDependencyManager V1.2.171 (brought with 7.0.1) is responsible for the problem.

Kind regards,
Oliver

**Comment by NVentimiglia** [comment]
Thanks for raising awareness, I will look into this further.

**Comment by a-maurice** [comment]
Hi @zodiac2k 

Looking at the ExternalDependencyManager changes, I'm suspecting it has to do with the new Swift support options, which 1.2.170 added, and 1.2.171 enabled by default.  Can you share the Podfile and Podfile.lock that was made when you used 1.2.171?

**Comment by NVentimiglia** [comment]
Hi @zodiac2k 

In the 1.2.171 release notes:
> iOS Resolver - Link Framework Statically setting is now default to true. That is, use_frameworks! :linkage => static will be added to Podfile by default instead of use_frameworks!. This can be changed in iOS Resolver settings. This fixes odd behaviors when pods include static libraries, ex. Firebase Analytics.

Can you review this setting and see if it helps?

**Comment by jonsimantov** [comment]
There are a number of possible workarounds in [this Unity forum thread](https://forum.unity.com/threads/an-empty-folder-named-frameworks-in-unityframework-framework.751559/#post-6959384), in particular the one I directly linked to, which changes the Swift embedding settings for the project programatically. Could you try and see which (if any) help?

**Comment by Francesco-FL** [comment]
I also can't submit the app to the App Store (GMA Unity Plugin 7.0.2)
![errore 2](https://user-images.githubusercontent.com/83022092/172969294-5f830a31-b4ab-4b69-9496-890a374be8ba.jpg)

**Comment by Francesco-FL** [comment]
I also can't submit the app to the App Store
![errore 3](https://user-images.githubusercontent.com/83022092/172969632-71ceceb1-0ede-4745-880d-59a558df856e.jpg)
