### ISSUE TITLE
Unity building with CocoaPods unexpected error

### ISSUE THREAD

**Issue by m-kul** [googleads/googleads-mobile-unity#207]
Hello, 

My project works fine for android, but I just cannot build for iOS without error. I tried to open the project in Xcode and build but it also segfaulted.

What may be the reason?. (By the way I tried reinstalling iOS Support for Unity) 

Executing which argument: pod
UnityEngine.Debug:Log(Object)
GoogleMobileAds.CocoaPodHelper:ExecuteCommand(String, String, String) (at Assets/GoogleMobileAds/Editor/CocoaPodHelper.cs:47)
GoogleMobileAds.CocoaPodHelper:Update(String) (at Assets/GoogleMobileAds/Editor/CocoaPodHelper.cs:16)
GoogleMobileAds.Postprocessor:runPodUpdate(String) (at Assets/GoogleMobileAds/Editor/PostProcessor.cs:44)
GoogleMobileAds.Postprocessor:OnPostprocessBuild(BuildTarget, String) (at Assets/GoogleMobileAds/Editor/PostProcessor.cs:27)
UnityEditor.HostView:OnGUI()

Could not create a new Xcode project with CocoaPods: Encountered unexpected error while running pod
UnityEngine.Debug:Log(Object)
GoogleMobileAds.Postprocessor:runPodUpdate(String) (at Assets/GoogleMobileAds/Editor/PostProcessor.cs:48)
GoogleMobileAds.Postprocessor:OnPostprocessBuild(BuildTarget, String) (at Assets/GoogleMobileAds/Editor/PostProcessor.cs:27)
UnityEditor.HostView:OnGUI()

**Comment by rampara** [comment]
Which OS in the machine you're building your Unity application running?

**Comment by rampara** [comment]
The exception reason doesn't seem to make it through the exception handling logic. Can you change line 79 in `CocoaPodHelper.cs` to:

throw new Exception("Encountered unexpected error while running command: " + e.Message);

**Comment by m-kul** [comment]
Sorry it was totally my lack of knowlodge. It was solved after watching this video. I think this video should be refernced for newbies in the documentations. Thanks though...

https://www.youtube.com/watch?v=iEAjvNRdZa0
