### ISSUE TITLE
V7.0.2 package import crashes Unity Editor

### ISSUE THREAD

**Issue by vincent-savysoda** [googleads/googleads-mobile-unity#2073]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.33f1
  * Google Mobile Ads Unity plugin version: V7.0.2
  * Platform: Unity Editor
  * Platform OS version: Windows 10
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:
- Import the package
- Editor crashes midway through import process

**Comment by NVentimiglia** [comment]
I was unable to replicate the issue.
Can you include the editor log ?
https://github.com/googleads/googleads-mobile-unity/pull/1887

**Comment by vincent-savysoda** [comment]
Strange. It didn't crash this time that i tried it. It had crashed the last 5 attempts yesterday. Must have been a memory issue then. Closing this for now.
