### ISSUE TITLE
AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.mediation.admob.AdMobExtras

### ISSUE THREAD

**Issue by imjunaidch** [googleads/googleads-mobile-unity#2090]
I am using Unity 2020.3.32
Google Mobile Ads Unity Package 7.0.0

I got no error in unity editor but when I run my application on mobile ads are not showing on mobile. I got this error AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.mediation.admob.AdMobExtras

Please tell me how can I remove this error.

**Comment by NVentimiglia** [comment]
The Facebook adapter needs to update with support for the Android V21 Google Mobile Ads SDK. This adapter is not something we own, so we will need to reach out to the adapter owners for this.

Thanks.

**Comment by kaushikmorosq** [comment]
Hi 
any proper solution for this?

**Comment by imjunaidch** [comment]
> Hi any proper solution for this?

@kaushikmorosq I just updated everything then its works properly. Now I am using Google Mobile Ads v7.0.2 Firebase Analytics 9.0.0 Facebook Unity Adapter 3.7.0 and Unity Ads Unity Adapter 3.2.0.

I don't know what is the reason behind this error because I made many builds before but this time I got this error. After Updating every plugin then it's working now.

**Comment by kaushikmorosq** [comment]
Thank you 
using Google Mobile Ads v7.0.2 now it's working for me.
