### ISSUE TITLE
undefined symbol in ios

### ISSUE THREAD

**Issue by pezezzle** [googleads/googleads-mobile-unity#2094]
Hi, i try to use adMob in IOS. I always run in the issue with the undefined symbols.  I try every
solution i found on sackoverflow or here but nothing worked. 

i tried:
- in IOS Resolver all different options. I must cocoapod integration set to none otherwise unity run in a error.
- remove admob and add again
- install cocoapot manually in xcode because in unity it dose not work.

  * Unity version: 2021.3.4f1
  * Google Mobile Ads Unity plugin version: 7.0.2
  * Platform: iOS
  * Platform OS version: iOS 14

how can i fix this?

Undefined symbol: _OBJC_CLASS_$_GADRequest
Undefined symbol: _OBJC_CLASS_$_GADInterstitialAd
Undefined symbol: _OBJC_CLASS_$_GADBannerView
Undefined symbol: _OBJC_CLASS_$_GADRewardedAd
Undefined symbol: _kGADAdSizeSmartBannerPortrait
Undefined symbol: _GADPortraitAnchoredAdaptiveBannerAdSizeWithWidth
Undefined symbol: _CGSizeFromGADAdSize
Undefined symbol: _GADLandscapeAnchoredAdaptiveBannerAdSizeWithWidth
Undefined symbol: _GADAdSizeFromCGSize
Undefined symbol: _kGADAdSizeSmartBannerLandscape
Undefined symbol: _GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth
Undefined symbol: _GADAdSizeEqualToSize
Undefined symbol: _OBJC_CLASS_$_GADRewardedInterstitialAd
Undefined symbol: _GADAdSizeFullWidthPortraitWithHeight
Undefined symbol: _OBJC_CLASS_$_GADServerSideVerificationOptions
Undefined symbol: _OBJC_CLASS_$_GADAppOpenAd
Undefined symbol: _OBJC_CLASS_$_GADMobileAds
Undefined symbol: _OBJC_CLASS_$_GADExtras
Undefined symbol: _GADErrorUserInfoKeyResponseInfo

**Comment by NVentimiglia** [comment]
Hi, can you double check the Assets/ExternalDependencyManager/iOS Resolver/Settings? Make sure you have pods configured and installed correctly and are linking  libraries statically. If you are still blocked after this review feel free to reply with your setup.

**Comment by pezezzle** [comment]
Hi,
i have pods installed but i cannot make a build when i use default settings in
Assets/ExternalDependencyManager/iOS Resolver/Settings.

unity run in this error:

After the failure, "pod repo update" was executed and failed. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.

pod install output:

Analyzing dependencies

`/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require': dlopen(/Users/ipezbook/.gem/ruby/2.6.0/gems/ffi-1.14.2/lib/ffi_c.bundle, 0x0009): tried: '/Users/ipezbook/.gem/ruby/2.6.0/gems/ffi-1.14.2/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')) - /Users/ipezbook/.gem/ruby/2.6.0/gems/ffi-1.14.2/lib/ffi_c.bundle (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require'
	from /Users/ipezbook/.gem/ruby/2.6.0/gems/ffi-1.14.2/lib/ffi.rb:6:in rescue in <top (required)>'
	from /Users/ipezbook/.gem/ruby/2.6.0/gems/ffi-1.14.2/lib/ffi.rb:3:in <top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require'
	from /Users/ipezbook/.gem/ruby/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:2:in <top (required)>'`




with this settings below i can do a build but run in the mentioned errors: undefined symboles
<img width="401" alt="Screenshot 2022-06-16 at 08 46 18" src="https://user-images.githubusercontent.com/30518204/174009142-f1fd4122-cd49-46e3-ab40-4e991332acc8.png">

**Comment by ckocank** [comment]
I have the same problem

**Comment by GRyabkin** [comment]
I have the same issue but with option "Use shell to execute..." disabled. Pods are installed. In some old version of the google-ads-unity I had mentioned in the error files inside Assets/Plugins/iOS folder

**Comment by GRyabkin** [comment]
Resolved by totally removing any mentions of the old version Google-ADS and reinstalling again

**Comment by AbelTeam** [comment]
I also have this problem,
Does anyone have a solution to this problem?

Unity 2021.3.14f1
Google Mobile Ads Unity plugin version: 7.3.1

**Comment by mianumar** [comment]
> I also have this problem, Does anyone have a solution to this problem?
> 
> Unity 2021.3.14f1 & 2020.3.38f1 Google Mobile Ads Unity plugin version: 7.3.1

I also have the same issue.

**Comment by AbelTeam** [comment]
> 

I solved this version using source code.

https://github.com/googleads/googleads-mobile-unity/archive/refs/tags/v7.3.1.zip

[Some source code compilation issues need to be fixed.]

**Comment by YongjinK** [comment]
7.3.0 has no issue with ios Compilation. And Source code building seems work, too (as AbelTeam said, there are stupid issues: missing #if UNITY_IOS, missing GoogleMobileAds.Api asmdef etc). 
Based on the experience with this plugin for more than 1 year, one thing I found is there is no QA process in managing this "official" plugin. There can be mistakes and I also understand it as a programmer, but those mistakes must be found and filtered in QA process. If a new version makes a build process fail, that version MUST NOT be shipped. 
Wake up google, don't do tihs as a hobby. Game Ads Market is a HUGE $0.6B market in global and this plugin is a key part of that market. Please be professional, and put at least an elementary QA process here.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.

**Comment by l2fx6** [comment]
Reinstall Appodeal and Firebase helped for me.
