### ISSUE TITLE
Failed to re-package resources after import admob unity 

### ISSUE THREAD

**Issue by trunglehuynh** [googleads/googleads-mobile-unity#210]
I created an empty project and import admit unity, and I cannot build
I am using unity version 5.3.4f1(on mac)
Android SDK tools 25.1.3
android SDK platform-tools 23.1
android build tools 23.0.3
Android support library 23.2.1
Google play services 29
newest admob version

2 Errors:
First:
 CommandInvokationFailure: Failed to re-package resources. See the Console for details.
/Users/trunghuynh/Documents/android-sdk-macosx/build-tools/23.0.3/aapt package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "/Users/trunghuynh/Documents/android-sdk-macosx/platforms/android-23/android.jar" -F bin/resources.ap_ --extra-packages com.google.unity

stderr[
AndroidManifest.xml:16: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.IAPTheme').

AndroidManifest.xml:18: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

]
stdout[
Configurations:
 (default)
 v14
 v21
 xhdpi-v4

Files:
  drawable/app_banner.png
    Src: (xhdpi-v4) res/drawable-xhdpi/app_banner.png
  drawable/app_icon.png
    Src: () res/drawable/app_icon.png
  values/strings.xml
    Src: () res/values/strings.xml
  values/styles.xml
    Src: () res/values/styles.xml
    Src: (v14) res/values-v14/styles.xml
    Src: (v21) res/values-v21/styles.xml
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
  Type drawable
    drawable/app_banner.png
      Src: (xhdpi-v4) res/drawable-xhdpi/app_banner.png
    drawable/app_icon.png
      Src: () res/drawable/app_icon.png
  Type values
    values/strings.xml
      Src: () res/values/strings.xml
    values/styles.xml
      Src: () res/values/styles.xml
      Src: (v14) res/values-v14/styles.xml
      Src: (v21) res/values-v21/styles.xml
Including resources from package: /Users/trunghuynh/Documents/android-sdk-macosx/platforms/android-23/android.jar
applyFileOverlay for drawable
applyFileOverlay for layout
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: res/drawable-xhdpi/app_banner.png
Processing image: res/drawable/app_icon.png
    (processed image res/drawable/app_icon.png: 94% size of source)
    (processed image res/drawable-xhdpi/app_banner.png: 93% size of source)
    (new resource id app_banner from xhdpi-v4/drawable/app_banner.png #generated)
    (new resource id app_icon from drawable/app_icon.png #generated)
]
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.PostProcessAndroidPlayer.Exec (System.String command, System.String args, System.String workingdir, System.String[] progress_strings, Single progress_value, System.String errorMsg)
UnityEditor.Android.PostProcessAndroidPlayer.CompileResources (System.String stagingArea, System.String packageName, UnityEditor.Android.AndroidLibraries androidLibraries)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcessInternal (System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
UnityEditor.HostView:OnGUI()

Second:

Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
/Users/trunghuynh/Documents/android-sdk-macosx/build-tools/23.0.3/aapt package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "/Users/trunghuynh/Documents/android-sdk-macosx/platforms/android-23/android.jar" -F bin/resources.ap_ --extra-packages com.google.unity

stderr[
AndroidManifest.xml:16: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.IAPTheme').

AndroidManifest.xml:18: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

]
stdout[
Configurations:
 (default)
 v14
 v21
 xhdpi-v4

/app_banner.png
    Src: (xhdpi-v4) res/drawable-xhdpi/app_banner.png
  drawable/app_icon.png
    Src: () res/drawable/app_icon.png
  values/strings.xml
    Src: () res/values/strings.xml
  values/styles.xml
    Src: () res/values/styles.xml
    Src: (v14) res/values-v14/styles.xml
    Src: (v21) res/values-v21/styles.xml
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
  Type drawable
    drawable/app_banner.png
      Src: (xhdpi-v4) res/drawable-xhdpi/app_banner.png
    drawable/app_icon.png
      Src: () res/drawable/app_icon.png
  Type values
    values/strings.xml
      Src: () res/values/strings.xml
    values/styles.xml
      Src: () res/values/styles.xml
      Src: (v14) res/values-v14/styles.xml
      Src: (v21) res/values-v21/styles.xml
Including resources from package: /Users/trunghuynh/Documents/android-sdk-macosx/platforms/android-23/android.jar
applyFileOverlay for drawable
applyFileOverlay for layout
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: res/drawable-xhdpi/app_banner.png
Processing image: res/drawable/app_icon.png
    (processed image res/drawable/app_icon.png: 94% size of source)
    (processed image res/drawable-xhdpi/app_banner.png: 93% size of source)
    (new resource id app_banner from xhdpi-v4/drawable/app_banner.png #generated)
    (new resource id app_icon from drawable/app_icon.png #generated)
]

**Comment by trunglehuynh** [comment]
Within the 'Assets/PlayServicesResolver/Editor/AdMobDependencies.cs' file, can you try making the following change:

svcSupport.DependOn("com.android.support", "appcompat-v7", "23.1.0+");
to

svcSupport.DependOn("com.android.support", "appcompat-v7", "LATEST");

it works

**Comment by AdnanNazir** [comment]
It's not working rampara. 
The Error message is still there. It just changed to 
CommandInvokationFailure: Unable to convert classes into dex format
Now

**Comment by rampara** [comment]
Did the JarResolver library copy Google Play services AARs into the `Assets\Plugin\Android` directory of your Unity project? If not, can you select `Assets->Google Play services->Resolve Client Jars` within the Unity editor. Posting the full contents of the error message you're running into would also help in investigating what's happening.

**Comment by akira32** [comment]
I click Resolve Client Jars, but it appear the error message:
Win32Exception: ApplicationName='C:\Program Files (x86)\Java\jre1.8.0_20\bin\jar.exe', CommandLine='xvf "C:\Users\akira_mac\Downloads\googleads-mobile-unity-3.0.4\googleads-mobile-unity-3.0.4\samples\HelloWorld\Assets\Plugins\Android\firebase-common-9.0.1.aar"', CurrentDirectory='C:\Users\akira_mac\Downloads\googleads-mobile-unity-3.0.4\googleads-mobile-unity-3.0.4\samples\HelloWorld\Assets\Plugins\Android\firebase-common-9.0.1'
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
GooglePlayServices.DefaultResolver.ProcessAar (System.String dir, System.String aarFile) (at Assets/PlayServicesResolver/Editor/DefaultResolver.cs:213)

**Comment by akira32** [comment]
I solve this roblem by setting JAVA_HOME as C:\Program Files\Java\jdk1.8.0_05
And then click "Resolve Client Jars" and rebuild. Thanks, rampara!

**Comment by akira32** [comment]
Solution:http://blog.xuite.net/akira32/home/419281627

**Comment by rampara** [comment]
glad you were able to resolve this issue.
