### ISSUE TITLE
App open ADS: UnityAppStateEventCallback not found

### ISSUE THREAD

**Issue by Alekxss** [googleads/googleads-mobile-unity#2110]
Unity 2021.3.3, 7.0.0 version with use OnApplicationPause works, now just updated to 7.1.0 and changed to new callback and got error on device Redmi Note 9

ClassNotFoundException: com.google.unity.ads.UnityAppStateEventCallback

this how we use it:

`	private void RequestAppOpen()
	{
		AdRequest request = new AdRequest.Builder().Build();
		AppOpenAd.LoadAd(adUnitAppOpen, Screen.orientation, request, ((appOpenAd, error) =>
		{
			if (error != null)
			{
				Debug.LogFormat("Failed to load the ad. (reason: {0})", error.LoadAdError.GetMessage());
				return;
			}

			appOpen = appOpenAd;
			loadTime = DateTime.UtcNow;
		}));

		AppStateEventNotifier.AppStateChanged += OnAppStateChanged;
	}
`

**Comment by NVentimiglia** [comment]
Hi @Alekxss 

Can you uninstall the plugin and install it again? Specifically the content within the `/Plugin/` folder.

Thanks

**Comment by GamerSoulArt** [comment]
Yeah I have a same problem.
I followed what you said @NVentimiglia, still getting same error

**Comment by Alekxss** [comment]
Fixed in last versions

**Comment by rockylimandauw** [comment]
hi @Alekxss I'm using 7.2.0 and still got the exact same error messages, should I updated my Unity Version also?
im using 2021.3.1

**Comment by Alekxss** [comment]
you should have this imported:

using GoogleMobileAds.Api;
using GoogleMobileAds.Common;

вс, 23 окт. 2022 г. в 10:58, rockylimandauw ***@***.***>:
