### ISSUE TITLE
Game crashes on start after adding Google Mobile Ads

### ISSUE THREAD

**Issue by bekiryanik** [googleads/googleads-mobile-unity#2111]
Hello,

The mobile project I am working on crashed after adding the Google Mobile Ads Unity plugin. The project doesn't even open, doesn't even gives any log to adb logcat. It just shows a half-black screen and then shuts down on the android mobile device. I've tried lower versions of the plugin but all of them gave me the same result. I think this is most likely about the Unity version that I am using. By the way, the project normally works without the ads plugin very well. 

### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.4f1
  * Google Mobile Ads Unity plugin version: I have tried all versions from 6.1.2 to 7.1.0
  * Platform: Android
  * Platform OS version: Android 11.0
  * Any specific devices issue occurs on: The problem occurs on any device
  * Mediation ad networks used, and their versions: Only AdMob

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Just import the plugin to this Unity Editor version and build it for Android. I just couldn't even get a log because it crashes so fast after I start the game on the device.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by NVentimiglia** [comment]
@[bekiryanik](https://github.com/bekiryanik)

There should be some logcat available. Can you try making a [gradle build](https://docs.unity3d.com/Manual/android-gradle-overview.html)? That should allow you to launch form Android Studio with logcat armed.
