### ISSUE TITLE
Status bar could not be hidden for full screen ad.

### ISSUE THREAD

**Issue by eduardocoelho** [googleads/googleads-mobile-unity#2123]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.5f1
  * Google Mobile Ads Unity plugin version: 7.1.0
  * Platform: iOS
  * Platform OS version: iOS 15.6
  * Xcode: 13.4.1
  * Any specific devices issue occurs on: all devices
  * Mediation ad networks used, and their versions: none

Other settings:

* Unity > Project Settings > Resolution and Presentation > Status Bar:
    * Status Bar Hidden: false
    * Status Bar Style: Light

* Podfile.lock:

```
  - Google-Mobile-Ads-SDK (9.6.0):
    - GoogleAppMeasurement (< 10.0, >= 7.0)
    - GoogleUserMessagingPlatform (>= 1.1)
```

### [REQUIRED] Step 2: Describe the problem

Interstitial ads appear below the status bar, making it difficult for users to close them because many times the 'X' (close) button is behind the status bar.

The following warning message appears on the Xcode Output area:

```
<Google> Status bar could not be hidden for full screen ad. Ensure that your app is configured to allow full screen ads to control the status bar. For example, consider whether you need to set the childViewControllerForStatusBarHidden property on your ad's rootViewController.
```

#### Steps to reproduce:

Show an interstitial ad.

#### Relevant Code:

```
AdMobAds.Instance.ShowInterstitial ();
```

**Comment by NVentimiglia** [comment]
@eduardocoelho with Google Mobile Ads SDK v9.0 we have stricter enforcement of the status bar. Please see [this information on the iOS guide](https://developers.google.com/admob/ios/migration#stricter_enforcement_of_status_bar_controls).

> Stricter enforcement of status bar controls
Starting from version 9.0.0, when you present full screen format ads, your app should ensure that the ads are able to control the presentation of the status bar. You will see an error message in the logs if you fail to do so.

> Depending on the specific layout of view controllers in your app, you may not need to make any changes to ensure this, but in some cases, you may need to set your parent view controller's `modalPresentationCapturesStatusBarAppearance` property.

Hope this helps

**Comment by eduardocoelho** [comment]
Hi @NVentimiglia, thank you for your reply.

I'm aware of the mentioned article. 

Note that I'm not modifying the Xcode project generated by Unity. In this way, I'm not sure if this is a Unity or AdMob Unity plugin issue and where  I should ask for help.

Let me know if there are any workaround/post-Xcode steps.

Thanks

**Comment by NVentimiglia** [comment]
Hi @eduardocoelho ,

I agree this is not an ideal solution. Let me make a feature request to add this to the API.

**Comment by mariusgabriel1** [comment]
why is this issue still not fixed? cannot close the interstitial ad as it overlaps with the status bar

**Comment by NVentimiglia** [comment]
@eduardocoelho 

This may be solved inside Unity. Inside the Unity menu please try:

> Unity > Project Settings > Resolution and Presentation > Status Bar:

> Status Bar Hidden: false
> Status Bar Style: Light

**Comment by travisbader** [comment]
I was able to solve this by removing `View controller-based status bar appearance`: `NO` from my Info.plist
