### ISSUE TITLE
Performance Issue After Show Interstitial

### ISSUE THREAD

**Issue by diablo85xxx** [googleads/googleads-mobile-unity#2130]
### Step 1: Describe your environment

  * Unity version: 2021.2.8f1
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: Android 
  * Platform OS version: Android 12 
  * Any specific devices issue occurs on: Realme GT

### Step 2: Describe the problem

We have a html5 game with createjs framework, and shown in a Unity WebView provided by Gree (https://github.com/gree/unity-webview).

The game starts smooth at 60fps, but after the first interstitial, the performance get really bad.

Another really strange fact is that (when the fps dropped after an interstitial), if we click on standby on phone, or change application (change of focus) the game return to 60fps, and there are no other drops (even with other interstitial shown).

This problem shows up even with other Unity version, other Google Mobile Ads Unity plugin version, and other smartphone in the same manner.

**Comment by NVentimiglia** [comment]
Hi @diablo85xxx 

I am not familiar with gree web view. How exactly are you using this component with the Admob plugin?

**Comment by kunny** [comment]
For those who're still experiencing the issue, please try upgrading the plugin version to 7.4.0 (and native plugin also), which should fix a few native ad issues. Thanks!
