### ISSUE TITLE
Interstitials break Unity Editor

### ISSUE THREAD

**Issue by m1cster** [googleads/googleads-mobile-unity#2139]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.32f1
  * Google Mobile Ads Unity plugin version: 7.1.0
  * Platform: Unity Editor
  * Platform OS version: not relevant, testads in editor only
  * Any specific devices issue occurs on: not relevant, testads in editor only
  * Mediation ad networks used, and their versions: none, testads in editor only

#### Steps to reproduce:

Transition to a scene that shows the interstitial. Two problems arise in unity editor:

1. A close button for the interstitial is shown, but is not functional. As of that the OnAdClosed callback never gets called and you cannot test the integration of interstitials. Even worse: to test an app that uses interstitials in unity editor, interstitials need to be deactivated.
2. The test interstitial is shown below the UI and not above like it would be on device. Although that is not critical, it took me some time to even see that the test interstitial was there as i was fading in a blocker graphic over the UI before showing the interstitial.

#### Relevant Code:

Interstitial.OnAdClosed += OnInterstitialClosed;
Interstitial.LoadAd(GetRequest());

private void OnInterstitialClosed(object sender, EventArgs args)
{
        Debug.Log("Interstitial Closed");  // we never get here
}

**Comment by NVentimiglia** [comment]
@m1cster I was not able to replicate the issue. Tested on 7.1.0.
