### ISSUE TITLE
iOS build fails

### ISSUE THREAD

**Issue by Wolfos** [googleads/googleads-mobile-unity#214]
When building for iOS, the build will fail, asking for a framework to be imported. This framework isn't included in the plugin, nor does the documentation even mention it. After importing this framework, the same happened for Unity Ads (which worked fine before importing Admob). After fixing the Unity Ads error, the linker fails with 'library not found for -lPods' and I'm stuck there.

I'm pretty certain I shouldn't have to manually add all those frameworks, so what's going wrong here?

**Comment by Wolfos2** [comment]
Did I get banned for posting this? I can't comment anymore.

**Comment by rampara** [comment]
I'm not sure why you can't comment. This plugin uses Cocoapods to generate a xcworkspace, which you should use instead of the standard Xcode project. Any additional frameworks you want to include should be included into the xcworkspace.

**Comment by Wolfos2** [comment]
Alright, thank you. Seems like I want to read up on Cocoapods then.
