### ISSUE TITLE
iOS build doesn't compile on Xcode due to undefined symbols error

### ISSUE THREAD

**Issue by saadjumani** [googleads/googleads-mobile-unity#2140]
Hi, im trying to use version 7.10 unity 2021.3.4f1 and I can't get my project to compile on Xcode. It exports fine from unity but when I try to build in Xcodde I get the following errors. 

![image](https://user-images.githubusercontent.com/22579705/179356303-d7ca9d2e-42ad-4598-aa70-32fdfd2b0f13.png)

**Comment by NVentimiglia** [comment]
@saadjumani 

Can you double check the Assets/ExternalDependencyManager/iOS Resolver/Settings? Make sure you have pods configured and installed correctly and are linking libraries statically. If you are still blocked after this review feel free to reply with your setup.

**Comment by saadjumani** [comment]
Thank you @NVentimiglia, I checked static linking. it is compiling now but crashing when ad is called. Works fine on android, crash is only happening on iOS.

**Comment by NVentimiglia** [comment]
Hi @saadjumani can you show the crash log?

**Comment by PowZone** [comment]
- Unity version: 2021.3.14f
- Google Mobile Ads Unity plugin version: v7.3.1
- Platform OS version: IOS, Xcode 14.1

Same issue here: https://www.dropbox.com/sh/v1v513alzdrl1p6/AABKgLLIiZR27esQDJCX_PBva?dl=0

I have to add a Google Ads Framework to xcode project?

**Comment by saadjumani** [comment]
I 

> 

I developed my game on a Windows laptop, exported from there to a macbook to compile in Xcode. Thats when I faced the issue.

It was resolved when I moved the entire project to the mac. So when my unity export and xcode compilation both took place on the same laptop, the issue got automatically resolved.
