### ISSUE TITLE
Compile error when building for Android - 'ScreenOrientation.Landscape' is obsolete

### ISSUE THREAD

**Issue by troy-lamerton** [googleads/googleads-mobile-unity#2145]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.6f1
  * Google Mobile Ads Unity plugin version: 7.0.0
  * Platform: Android
  * Platform OS version: irrelevant
  * Any specific devices issue occurs on: irrelevant
  * Mediation ad networks used, and their versions: none

#### Steps to reproduce:

Open Unity project that uses AdMob in Unity 2021.3.6f1.

Try to build your project for Android.

The build fails with a compile error

`'ScreenOrientation.Landscape' is obsolete`

```
[11:30:35 AM] ##### Output
[11:30:35 AM] C:\builds\game\CosPackages\AdMob\Packages\AdMob\GoogleMobileAds\Platforms\Android\Utils.cs(170,22):
  error CS0619: 'ScreenOrientation.Landscape' is obsolete: 'Use LandscapeLeft instead (UnityUpgradable) -> LandscapeLeft'
[11:30:35 AM] *** Tundra build failed (0.21 seconds), 1 items updated, 1367 evaluated
[11:30:35 AM] C:\builds\game\CosPackages\AdMob\Packages\AdMob\GoogleMobileAds\Platforms\Android\Utils.cs(170,22):
  error CS0619: 'ScreenOrientation.Landscape' is obsolete: 'Use LandscapeLeft instead (UnityUpgradable) -> LandscapeLeft'
[11:30:35 AM] Failed to compile player scripts
```

We are using the AdMob source files as a Unity package, this might be required to reproduce the compile error.

#### Relevant Code:

This is the line using the obsolete code:

https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/GoogleMobileAds/Platforms/Android/Utils.cs#L176

**Comment by NVentimiglia** [comment]
Hi @troy-lamerton 

This is usually handled by the auto upgrader. That said, I will look into the issue.
