### ISSUE TITLE
NativeAd crash on iOS 12

### ISSUE THREAD

**Issue by pelevinma** [googleads/googleads-mobile-unity#2152]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.2
  * Google Mobile Ads Unity plugin version: 7.1.0 + Native addon 7.0.1
  * Platform: iOS
  * Platform OS version: iOS 12.1.4
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: AdMob (Facebook, Applovin, IS, Pangle, Unity, Adcolony, Tapjoy, Fyber)

### [REQUIRED] Step 2: Describe the problem

Crash not reproducible on ios 15 (only on ios 12 and possibly earlier versions)
Repeatability 100%

**Crash after code:**

		AdLoader adLoader = new AdLoader.Builder(adUnitId)
			.ForNativeAd()
			.Build();

		adLoader.OnNativeAdLoaded += OnNativeAdLoaded;
		adLoader.OnAdFailedToLoad += OnAdFailedToLoad;

		adLoader.LoadAd(CreateAdRequest());

**Crash stack:**
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x00000001006282e8 in __abort_with_payload ()
#1	0x0000000100627928 in abort_with_payload_wrapper_internal ()
#2	0x0000000100627958 in abort_with_payload ()
#3	0x00000001005e88f4 in dyld::halt(char const*) ()
#4	0x00000001005e8a10 in dyld::fastBindLazySymbol(ImageLoader**, unsigned long) ()
#5	0x0000000221004bd0 in dyld_stub_binder ()
#6	0x0000000103b4bee8 in GADUCreateAdLoader ()
#7	0x0000000104914dd4 in ::_za1hl4laeXrpCPhipDgCWTaGcooA__mKIQ1lKbrY4wFOSCkKFs3LPHi8R_m7BF56BCDC3093D85CA8EC8CF3B23093389E98350(intptr_t, String_t *, int32_t, StringU5BU5D_t7674CD946EC0CE7B3AE0BE70E6EE85F2ECD9F248 *, int32_t, NativeAdTypes_t667526929D789B3FAE35DF13A63FBAF70A5E8733 *, bool, const RuntimeMethod *) at /Users/maksim/work/builds/BF_ios/Classes/Native/GoogleMobileAdsNative.iOS.cpp:16007
#8	0x0000000104914a70 in ::AdLoaderClient__ctor_mAFBE1F5B092352C194AF1755487E1EBCF031A6E6(AdLoaderClient_tBF564FA4B9C8C4AB0E29E343EC80CF4942BA77F8 *, AdLoaderClientArgs_tF1FBCBFAF6704A3BA19BACB4662A36F384B2C3E9 *, const RuntimeMethod *) at /Users/maksim/work/builds/BF_ios/Classes/Native/GoogleMobileAdsNative.iOS.cpp:9838
#9	0x0000000104918400 in ::GoogleMobileAdsNativeClientFactory_BuildAdLoaderClient_m47E37644D08AD596D698903044B753E0F6A5B43D(GoogleMobileAdsNativeClientFactory_t56A85695ED415D0555B943F8286F9D133C1E5A17 *, AdLoaderClientArgs_tF1FBCBFAF6704A3BA19BACB4662A36F384B2C3E9 *, const RuntimeMethod *) at /Users/maksim/work/builds/BF_ios/Classes/Native/GoogleMobileAdsNative.iOS.cpp:14852
#10	0x0000000104902ca4 in ::AdLoader__ctor_mFD950168E83706A130DAEDA9F21FEB66E5CA9F64(AdLoader_t03E7A44D10C600C457300E092C4BB5E44183CA12 *, Builder_t4B72628959BFFCABD22607C0C520C3C59D2CDCFB *, const RuntimeMethod *) at /Users/maksim/work/builds/BF_ios/Classes/Native/GoogleMobileAdsNative.cpp:11773
#11	0x0000000104906378 in ::Builder_Build_m89B1D22714EC3E42966E0B0907A02DEEA792EC76(Builder_t4B72628959BFFCABD22607C0C520C3C59D2CDCFB *, const RuntimeMethod *) at /Users/maksim/work/builds/BF_ios/Classes/Native/GoogleMobileAdsNative.cpp:14381
#12	0x000000010408f240 in ::AdUnitNative_RequestAndLoadAdImpl_mF677074B97FC059969E55C1B66C58E05EDE6BD6D(AdUnitNative_tDFBED830D2CECDFFEC550601CE81E323477CBA6B *, const RuntimeMethod *) at /Users/maksim/work/builds/BF_ios/Classes/Native/Assembly-CSharp3.cpp:16039
#13	0x000000010408c9d4 in VirtualActionInvoker0::Invoke(unsigned short, Il2CppObject*) [inlined] at /Users/maksim/work/builds/BF_ios/Classes/Native/Assembly-CSharp3.cpp:21
#14	0x000000010408c9c4 in ::AdUnit_RequestAndLoadAd_mF77C137680294EF73070010FDA451F6608EF2171(AdUnit_t043FFEAD1ED6439BF0D271B135C64C0BE853F26C *, const RuntimeMethod *) at /Users/maksim/work/builds/BF_ios/Classes/Native/Assembly-CSharp3.cpp:13167
#15	0x000000010408b2f8 in VirtualActionInvoker0::Invoke(unsigned short, Il2CppObject*) [inlined] at /Users/maksim/work/builds/BF_ios/Classes/Native/Assembly-CSharp3.cpp:21
#16	0x000000010408b2e8 in AdMobManager_LoadAdIfNeeded_m4445AD134069FF64DE25188FDE7F55CC416396B3 [inlined] at /Users/maksim/work/builds/BF_ios/Classes/Native/Assembly-CSharp3.cpp:11823
#17	0x000000010408b2d8 in ::AdMobManager_ReloadAdsIfNeeded_m2A50B1804281664CCC4F535101EB0C71D9CF34C9(AdMobManager_t3C0F834E2FC790F4C764FA398B00FD080FB54352 *, const RuntimeMethod *) at /Users/maksim/work/builds/BF_ios/Classes/Native/Assembly-CSharp3.cpp:11748
#18	0x00000001048e0a58 in Action_Invoke_m7126A54DACA72B845424072887B5F3A51FC3808E_inline(Action_tD00B0A84D7945E50C2DFFC28EFEE6ED44ED2AD07*, MethodInfo const*) [inlined] at /Users/maksim/work/builds/BF_ios/Classes/Native/GoogleMobileAds.Common.cpp:4312
#19	0x00000001048e0a48 in ::MobileAdsEventExecutor_Update_mA2FA865A80DE36FC26CAD15783037324C74D5113(MobileAdsEventExecutor_t1185FA76E60746A4BF6150BBFC4BD17B123F380A *, const RuntimeMethod *) at /Users/maksim/work/builds/BF_ios/Classes/Native/GoogleMobileAds.Common.cpp:2422
#20	0x00000001038eb604 in il2cpp::vm::Runtime::InvokeWithThrow(MethodInfo const*, void*, void**) at /Users/bokken/buildslave/unity/build/External/il2cpp/builds/libil2cpp/vm/Runtime.cpp:576
#21	0x00000001038eb44c in il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) at /Users/bokken/buildslave/unity/build/External/il2cpp/builds/libil2cpp/vm/Runtime.cpp:562
#22	0x0000000102ef4260 in ::scripting_method_invoke() at /Users/bokken/buildslave/unity/build/Runtime/ScriptingBackend/Il2Cpp/ScriptingApi_Il2Cpp.cpp:292
#23	0x0000000102effda4 in ::Invoke() at /Users/bokken/buildslave/unity/build/Runtime/Scripting/ScriptingInvocation.cpp:298
#24	0x0000000102f0e5e0 in Invoke [inlined] at /Users/bokken/buildslave/unity/build/Runtime/Scripting/ScriptingInvocation.h:71
#25	0x0000000102f0e5cc in CallMethodIfAvailable [inlined] at /Users/bokken/buildslave/unity/build/Runtime/Mono/MonoBehaviour.cpp:441
#26	0x0000000102f0e59c in ::CallUpdateMethod() at /Users/bokken/buildslave/unity/build/Runtime/Mono/MonoBehaviour.cpp:540
#27	0x0000000102da1a14 in UpdateBehaviour [inlined] at /Users/bokken/buildslave/unity/build/Runtime/GameCode/Behaviour.cpp:178
#28	0x0000000102da1a08 in ::CommonUpdate<BehaviourManager>() at /Users/bokken/buildslave/unity/build/Runtime/GameCode/Behaviour.cpp:156
#29	0x0000000102e3ac50 in ::ExecutePlayerLoop() at /Users/bokken/buildslave/unity/build/Runtime/Misc/PlayerLoop.cpp:383
#30	0x0000000102e3ac90 in ::ExecutePlayerLoop() at /Users/bokken/buildslave/unity/build/Runtime/Misc/PlayerLoop.cpp:404
#31	0x0000000102e3aeec in ::PlayerLoop() at /Users/bokken/buildslave/unity/build/Runtime/Misc/PlayerLoop.cpp:508
#32	0x000000010336d8ec in UnityPlayerLoopImpl at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/LibEntryPoint.mm:327
#33	0x000000010336d878 in UnityPlayerLoop at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/LibEntryPoint.mm:353
#34	0x0000000102018690 in UnityRepaint [inlined] at /Users/maksim/work/builds/BF_ios/Classes/UnityAppController+Rendering.mm:236
#35	0x0000000102018684 in -[UnityAppController(Rendering) repaint] at /Users/maksim/work/builds/BF_ios/Classes/UnityAppController+Rendering.mm:90
#36	0x00000001020185f8 in -[UnityAppController(Rendering) repaintDisplayLink] at /Users/maksim/work/builds/BF_ios/Classes/UnityAppController+Rendering.mm:71
#37	0x0000000225a8649c in CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) ()
#38	0x0000000221819b24 in IODispatchCalloutFromCFMessage ()
#39	0x0000000221522f0c in __CFMachPortPerform ()
#40	0x000000022154a758 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ ()
#41	0x0000000221549ea4 in __CFRunLoopDoSource1 ()
#42	0x0000000221544c5c in __CFRunLoopRun ()
#43	0x00000002215440e0 in CFRunLoopRunSpecific ()
#44	0x00000002237bd584 in GSEventRunModal ()
#45	0x000000024e498c00 in UIApplicationMain ()
#46	0x00000001020180cc in -[UnityFramework runUIApplicationMainWithArgc:argv:] at /Users/maksim/work/builds/BF_ios/Classes/main.mm:96
#47	0x0000000100323e00 in main at /Users/maksim/work/builds/BF_ios/MainApp/main.mm:26
#48	0x0000000221002bb4 in start ()

**Comment by kunny** [comment]
For those who're still experiencing the issue, please try upgrading the plugin version to 7.4.0 (and native plugin also), which should fix a few native ad issues. Thanks!
