### ISSUE TITLE
App Crash when Rewarded Video is initialised and Wifi is Off (No Internet)

### ISSUE THREAD

**Issue by JamesSunny** [googleads/googleads-mobile-unity#2154]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.40f1
  * Google Mobile Ads Unity plugin version: v7.1.0
  * Platform: iOS
  * Platform OS version: iOS 15+, iOS 13.41
  * Any specific devices issue occurs on: iPhone 11, iPad Air 2
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:
Start your App without WIFI
Init a Rewarded Ad without WIFI

BTW this callback is called even when WIFI is off (no network)
MobileAds.Initialize(initStatus => { 
Debug.Log("I should not be called when WIFI is off");
});

so that function makes no sense to me.

Therefore it is impossible to actually know when Admob is ready. 
Only dirty workaround, call your own server or a random website, and when it returns 200, then load a rewarded Ad

#### Relevant Code:
https://developers.google.com/admob/unity/rewarded

  this.rewardedAd.OnAdLoaded += HandleRewardedAdLoaded;
        // Called when an ad request failed to load.
        this.rewardedAd.OnAdFailedToLoad += HandleRewardedAdFailedToLoad;
        // Called when an ad is shown.
        this.rewardedAd.OnAdOpening += HandleRewardedAdOpening;
        // Called when an ad request failed to show.
        this.rewardedAd.OnAdFailedToShow += HandleRewardedAdFailedToShow;
        // Called when the user should be rewarded for interacting with the ad.
        this.rewardedAd.OnUserEarnedReward += HandleUserEarnedReward;
        // Called when the ad is closed.
        this.rewardedAd.OnAdClosed += HandleRewardedAdClosed;

Stack Trace

HandleRewardedAdFailedToLoad event received with message: A data connection is not currently allowed.
AdsGoogle:HandleRewardedAdFailedToLoad(Object, AdFailedToLoadEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)

libc++abi: terminating with uncaught exception of type Il2CppExceptionWrapper
dyld4 config: DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
terminating with uncaught exception of type Il2CppExceptionWrapper

**Comment by NVentimiglia** [comment]
@JamesSunny 

MobileAds.initialize() should always receive completion callback. If SDK is not yet initialized, go ahead initialize it, the callback should be completed regardless of WIFI status.

**Comment by mancj** [comment]
Hi. I have completion callback in my code, also i wrapped loading interstitial code in try/catch, but i keep getting this error when network connection is off.

```cs
 MobileAds.Initialize(status =>
                {
                    Debug.Log($"Ad initialized status: {status}");
                    isInitializationCompleted = true;
                    _isInitializingLib = false;
                });
```

```cs
 public void LoadInterstitial(Action<bool> onEnd = null)
        {
            try
            {
                Debug.Log($"Load interstitial request {isInitializationCompleted} {_isInitializingLib}");
                if (!isInitializationCompleted)
                {
                    Debug.Log("Interstitial loading skipped [!isInitializationCompleted]");
                    onEnd?.Invoke(false);
                    InitializedAds();
                    return;
                }

                _destroyInterstitial();
                var adRequest = new AdRequest();
                // send the request to load the ad.
                InterstitialAd.Load(
                    _interstitialAppUnitId,
                    adRequest,
                    (InterstitialAd ad, LoadAdError error) =>
                    {
                        // if error is not null, the load request failed.
                        if (error != null || ad == null)
                        {
                            FirebaseAnalytics.LogEvent("InterstitialInitializeError");
                            Debug.LogError("interstitial ad failed to load an ad " +
                                           "with error : " + error);
                            onEnd?.Invoke(false);
                            return;
                        }

                        _interstitialLoaded = true;
                        FirebaseAnalytics.LogEvent("InitializeInterstitial");
                        Debug.Log("Interstitial ad loaded with response : " + ad.GetResponseInfo());
                        _interstitialAd = ad;
                        onEnd?.Invoke(true);
                        OnInterstitialReady?.Invoke();
                    }
                );
            }
            catch (Exception e)
            {
                _logError($"Error loading interstitial {e.StackTrace}");
                onEnd?.Invoke(false);
            }
        }
```

**Comment by mancj** [comment]
i'm facing the same issue in 8.5.2. When i call `InterstitialAd.Load` app crashes

**Comment by mancj** [comment]
## Possible fix

It is very strange that none of the 16 issues opened here do not contain a solution to this error. I spent a whole day trying to figure out the cause of the error. crash rate dropped to 89% from 100%. a lot of nerves and money spent. 

So if someone is facing this problem, **try putting your** code in `MobileAdsEventExecutor.ExecuteInUpdate`, as described in [this message](https://github.com/googleads/googleads-mobile-unity/issues/2710#issuecomment-1548683969).
I tried 3 versions of library (current actual version is 8.5.2), finally tested successfully on 8.4.1. Hope this will help you.

I searched the whole Internet, but there was no information on this problem anywhere. ExecuteInUplace is not even mentioned in the Google documentation. Google, are you kidding us?
