### ISSUE TITLE
Interstitial ad sound does not stop after closed

### ISSUE THREAD

**Issue by sjvc** [googleads/googleads-mobile-unity#2155]
* Unity version: 2021.3.6f1
  * Google Mobile Ads Unity plugin version: 7.1.0
  * Platform: iOS
  * Platform OS version: iOS 15.6
  * Any specific devices issue occurs on: iPhone SE 2020
  * Mediation ad networks used, and their versions: no

#### Steps to reproduce:

1. Set your device as a test device by adding its IDFA: https://apps.admob.com/v2/settings/test-devices/list
2. Show a interstitial test ad
3. Touch the "x" to close it, and the ad audio will continue playing (only happens on ads with audio, of course)

I tested on an iPad, and the audio stopped. I can only reproduce it on an iPhone SE 2020, and using test ads. I tried with production ads, and the audio stops. But I can't be sure it only happens on test ads, because maybe only happens in the ads that are served when I'm requesting test ads.

EDIT: I've just tested with Hello World sample app and the same happens: sound doesn't stop. Instead of using the test ad id I'm using my own interstitial ad id (interstitial test ad id does not show videos) and my own app id. I receive apps in test mode because I added the device IDFA to AdMob test devices.

**Comment by NVentimiglia** [comment]
Hi @sjvc 

This sounds like a creative issue. Can you please submit a report to the[ community forum]([our forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines)). Please include your publisher id, ad unit id for the interstitial ad, and a [network trace of](https://developers.google.com/admob/android/network-tracing) the issue. Thanks.

**Comment by sjvc** [comment]
Hello @NVentimiglia 

I think you are right: it's a creative issue. I checked the published version of my app (with a previous AdMob plugin version), with ads in test mode, and the same happens.
