### ISSUE TITLE
GADURequest.m:4:9: Module 'GoogleMobileAds' not found (issue)

### ISSUE THREAD

**Issue by benfairhurst** [googleads/googleads-mobile-unity#216]
Hi i'm hoping you can help I've come across this problem i've been through some older posts but still can't seem to fix,

![screen shot 2016-05-08 at 12 18 37](https://cloud.githubusercontent.com/assets/19250091/15097585/ab8a5f42-1517-11e6-90ac-712f777e18a8.png)

**Comment by AdnanNazir** [comment]
same issue with me

**Comment by rampara** [comment]
Are you using the Cocoapods generated xcworkspace? Note, the current podfile distributed with the Unity plugin is incompatible with the latest version of Coocapods (1.0.0). Removing the podfile within Assets/GoogleMobileAds/Editor/ directory and creating a new one with the pod init command will fix the issue. You will need to add the Google Mobile Ads pod ('Google-Mobile-Ads-SDK', '~> 7.8') to the newly created podfile.

**Comment by birdkingz** [comment]
Please provide a clearer solution for this.
I'm having this problem too using v3.0.4

**Comment by rampara** [comment]
@birdkingz with v3.0.4 of this plugin you should no longer have to modify the distributed PodFile. Are you using the Cocoapods generated xcworkspace?

**Comment by birdkingz** [comment]
@rampara I'm not using Cocoapods...do I need to use that? How to use/setup cocoapods?

**Comment by birdkingz** [comment]
Sorry, I just realised I didn't include GoogleMobileAds.framework into my Xcode project.
Just wonder is there anyway I can set it so that Unity will automatic include GoogleMobileAds.framework while building for iOS ?

**Comment by rampara** [comment]
If you install Cocoapods the Unity plugin should generate an xcworkspace that includes the GoogleMobileAds.framework. The pods you want in the generated xcworkspace can be set in the PodFile located in the  `Assets\GoogleMobileAds\Editor` directory. If you don't want to use Cocoapods you will have manually at the Google Mobile Ads SDK to the xcode project generated by Unity.

**Comment by AdnanNazir** [comment]
It's not generating, 
Unity just gets halt. 
Can you tell me what could be wrong?
![screen shot 2016-07-20 at 2 01 44 pm](https://cloud.githubusercontent.com/assets/6734301/16981655/fbdaa438-4e84-11e6-8d06-cd5deab28b16.png)

**Comment by rampara** [comment]
@AdnanNazir do you have CocoaPods installed on your development machine? Do you see any output in the Unity console that may indicate why the Google Mobile Ads SDK is not being imported into the Xcode project?

**Comment by rampara** [comment]
Closing issue due to non-response. If this issue persists, please re-open.
