### ISSUE TITLE
Include Gradle Version and/or supported Unity Editor Version in Release notes.

### ISSUE THREAD

**Issue by JBMiller** [googleads/googleads-mobile-unity#2174]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4
  * Google Mobile Ads Unity plugin version: 7.1.0
  * Platform: Unity Editor - Android
  * Platform OS version: Android 11
  * Any specific devices issue occurs on: Unity Editor / Windows PC
  * Mediation ad networks used, and their versions: N/A

### [REQUIRED] Step 2: Describe the problem

This is not a code issue, but rather, a request for clarity. TLDR: I need to know which version of this plugin to use in Unity 2019.4 and the Release Notes are unhelpful.

I have an older project made on Unity 2019.4 and I am trying to update the Google Admob plugin because the version I currently have uses a old version of com.unity3d.ads:unity-ads that is going to be deprecated on September 28, 2022. However, trying to figure out which version of Gradle each version of the Google Admob plugin depends on is a hassle (I have to go through the source code commits and try to line up release dates with commit change dates). This is important, because having an incompatible version of Gradle prevents the project from Building into an APK or App Bundle.

Can you please update Release notes to include which version of Gradle it depends on and/or which version of the Unity Editor is compatible, as Gradle is built into the Unity Editor and only certain versions of the Editor carry certain versions of Gradle. Source: https://docs.unity3d.com/2023.1/Documentation/Manual/android-gradle-overview.html.

**Comment by NVentimiglia** [comment]
Hi @JBMiller 

I am currently testing plugin version 7.0.1 using Gradle Version 6.7.1 / Android Gradle Plugin Version 4.2.2.
