### ISSUE TITLE
There is no AdPosition.Center

### ISSUE THREAD

**Issue by shhwangs** [googleads/googleads-mobile-unity#219]
Hi!
I am using Unity 5.3.4 and latest admob plugin for Unity 3.0.3.
And my game uses 'MediumRectangle' banner (300*250) and I want to place that on Center position.
But as you see blow, there is no enumeration in AdPosition.
GoogleMobileAds > Api > AdPosition.cs
```
    public enum AdPosition
    {
        Top = 0,
        Bottom = 1,
        TopLeft = 2,
        TopRight = 3,
        BottomLeft = 4,
        BottomRight = 5
    }
```

Is this official GoogleMobilaAds Unity plug-in designed for only 320*50 banner?

**Comment by rampara** [comment]
The latest version of the plugin (3.0.6) includes support for a center ad position. Also, this plugin supports the ad sizes listed [here](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Api/AdSize.cs).
