### ISSUE TITLE
admob issue with Unity Ads 

### ISSUE THREAD

**Issue by AdnanNazir** [googleads/googleads-mobile-unity#220]
I am using Unity 5.3.4 and latest admob plugin for Unity 3.0.3
The android version does compile and run well but the iOS version has issues. 
I am on Mac OS 10.11.4 with latest cocoapods 1.0.0 installed, I figured it out that the latest cocoapods is the culprit so I installed the previous version 0.39.0 which was working for me earlier. But Now It's not working as well. With cocoapods 1.0.0 I was unable to get any xcworkspace, but with cocoapods 1.0.0 I can get xcworkspace file but the code doesn't compiles, It complains of not having Unity Ads and GoogleMobileAds. 
Can you guys please help me resolve this? It's driving me nuts. 

I have attached screenshots of errors.
![screen shot 2016-05-12 at 2 01 35 pm](https://cloud.githubusercontent.com/assets/6734301/15209378/26cd9720-184a-11e6-869d-3fd5590cd986.png)
![screen shot 2016-05-12 at 2 04 26 pm](https://cloud.githubusercontent.com/assets/6734301/15209459/897752f8-184a-11e6-92b6-c932b17e7085.png)
![screen shot 2016-05-12 at 2 02 45 pm](https://cloud.githubusercontent.com/assets/6734301/15209461/89798190-184a-11e6-8827-a2ff4b0fb581.png)

**Comment by rampara** [comment]
The current podfile distributed with the Unity plugin is incompatible with the latest version of Coocapods (1.0.0). Removing the podfile within Assets/GoogleMobileAds/Editor/ directory and creating a new one with the pod init command will fix the issue. You will need to add the Google Mobile Ads pod ('Google-Mobile-Ads-SDK', '~> 7.8') to the newly created podfile.

**Comment by holykss** [comment]
I want google to solve this problem.

**Comment by rampara** [comment]
The latest version of this plugin (v3.0.4) resolves compatibility issues with CocoaPods 1.0.0.
