### ISSUE TITLE
Issue with InMobi Integration

### ISSUE THREAD

**Issue by aniluk** [googleads/googleads-mobile-unity#223]
I am trying to integrate the InMobi adapter with AdMob mediation, I have included the InMobi SDK and adapter jar files as mentioned in the integration guide. But while running the app it failes to serve the ad with following message.

Instantiating mediation adapter: com.google.ads.mediation.inmobi.InMobiAdapter
Server parameters: {"gwhirl_share_location":"1","accountid":"_MYID_","pubid":"_MYID_","placementid":"1459736269123"}
Bundle extras are null

**Comment by rampara** [comment]
Can you post the contents of logcat under the "Ads" and "Unity" tags?

**Comment by rampara** [comment]
Closing issue due to non-response. If this issue persists, please re-open.

**Comment by usmankhan2225** [comment]
i am facing this issue, please help

**Comment by usmankhan2225** [comment]
![screen shot 2017-08-15 at 6 14 42 pm](https://user-images.githubusercontent.com/31040305/29320382-68a581e2-81f0-11e7-96a8-4424cab5210f.png)

**Comment by rampara** [comment]
@usmankhan2225 it looks like the InMobi adapter is successfully created but it cannot load an ad through the InMobi SDK. Are you including the InMobi SDK in your Unity project? Are the InMobi ad placement identifiers you are using valid?

**Comment by usmankhan2225** [comment]
Yes i have included the inmobi sdk 6.x latest version along with inmobi
adapter in the ASSETS->PLUGINS->ANDROID folder.

Also included the changes required by inmobi in the MANIFEST.

Now as far as placement ids are concerned,
I think they are correct as far as i checked.

You can guide me about the keys which i need to put in admod console
through my inmobi dashboard.
-- 
Best Regards,

Muhammad Usman

Software Engineer, DevBatch Pvt. Ltd.

+92-322-4213453 | www.devbatch.com | LinkedIn
<https://www.linkedin.com/company/devbatch> | Facebook
<https://www.facebook.com/devbatchinc> | Twitter
<http://twitter.com/devbatch>
