### ISSUE TITLE
Interactive ads will run in the background after being loaded on iOS devices

### ISSUE THREAD

**Issue by sm-hoseini** [googleads/googleads-mobile-unity#2232]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.37
  * Google Mobile Ads Unity plugin version: 7.0
  * Platform: iOS 
  * Platform OS version: iOS 14 
  * Any specific devices issue occurs on: iPhone 7
  * Mediation ad networks used, and their versions: Chartboost, 8.5.02 Vungle 6.10.6

### [REQUIRED] Step 2: Describe the problem

Our iOS versions of the game have encountered a problem. Whenever any interactive (playable) ad is loaded (without calling the Show function), the ad's sound is played, apparently, the ad is running in the background (game performance drop is noticeable too).  The issue occurs only with playable ads. All other ad types work fine.

**Comment by NVentimiglia** [comment]
Hi @sm-hoseini, 

This looks like an SDK issue. Please report this to the [Help Center](https://support.google.com/admob/?hl=en#topic=7383088).
