### ISSUE TITLE
CommandInvokationFailure: Failed to re-package resources. Random Error 

### ISSUE THREAD

**Issue by AdnanNazir** [googleads/googleads-mobile-unity#225]
Hey, I am using unity 5.3.4 on Windows 10
I just now started getting this nasty bug which doesn't allow me to make an android build. Everything was working perfectly fine 1 day ago. 
I have updated my android SDK to latest and there isn't anything that I am missing.
I am stucking around it from past 3 hours and it's really getting difficult to resolve it.
For anyone interested in help I am using Google Admob SDK for Unity Latest version 3.0.3
Facebook SDK for Unity 7.5.0
Unity Ads and Unity IAP are also being used in my game and are active
I have a feeling that the firebase aar files are the actual culprit of this issue. These files weren't there last time when I checked.

Please help me

**Comment by rampara** [comment]
Can you post the error you're running into when trying to create an Android build? If you're using the latest version of Google Play Services, you will have to exclude the `firebase-common` AAR from the Android build via the Unity editor inspector as shown in the screenshot below.

<img width="1499" alt="screen shot 2016-05-24 at 3 05 43 pm" src="https://cloud.githubusercontent.com/assets/11047881/15522497/b90973a8-21c7-11e6-96d7-7fe94dced5fa.png">

**Comment by AdnanNazir** [comment]
Hi Veer !
I was getting CommandInvokationFailure: Failed to re-package resources Earlier.
[https://drive.google.com/file/d/0B_o64G6zHYhjWDIzUTRNOTRsUEU/view](url)

After unchecking android checkbox from googleFireBase AAR.
Now I am getting 
CommandInvokationFailure: Unable to convert classes into dex format
[https://drive.google.com/file/d/0B_o64G6zHYhjUGdBOFRSWC1GWjQ/view](url)

**Comment by AdnanNazir** [comment]
Ok So I managed to solve the issue the problem were I was having one AAR File support-v4-23.2.1 as Facebook Plugin and the other support-v4-23.1.1 was in Google Mobile Ads

Removing one will solve your issue

Thanks

**Comment by rampara** [comment]
The latest version of this plugin (v3.0.4) no longer requires you to exclude the firebase-common AAR from the Android build.
