### ISSUE TITLE
Execution failed for task ':launcher:mergeReleaseNativeLibs'. > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

### ISSUE THREAD

**Issue by dmichalke2** [googleads/googleads-mobile-unity#2252]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.8f1
  * Google Mobile Ads Unity plugin version: 7.1.0
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: Build fails before testing
  * Any specific devices issue occurs on: not applicable
  * Mediation ad networks used, and their versions: not applicable

### [REQUIRED] Step 2: Describe the problem

when building unity android with googlemobileads 7.1 added, we get this error:

`FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':launcher:mergeReleaseNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'lib/x86/libFirebaseCppAnalytics.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 5s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8`

#### Steps to reproduce:

build project with other plugins. not sure what causes the problem, I have to mention that we have the HMS Huawei plugin https://github.com/EvilMindDevs/hms-unity-plugin
and it often caused trouble with firebase (which we also have in the project, version 9.1.0)

#### Relevant Code:

Android Manifest screenshot, see attached.
Gradle Setup see attached.

![Screenshot_1](https://user-images.githubusercontent.com/103567574/185414047-95a523b8-32bf-47b3-beb8-b44cf82785dd.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/103567574/185414053-e08e6bcd-3bfa-4170-992a-7fba2cc6e6a8.jpg)

**Comment by NVentimiglia** [comment]
Hi @dmichalke2,

Please see https://github.com/googlesamples/unity-jar-resolver, this is the plugin responsible for resolving dependencies. That said according to[ this forum post ](https://forum.unity.com/threads/android-build-failed.1084982/) this might be fixed by changing unity versions.

**Comment by dmichalke2** [comment]
Hi,

we already use Unity Jar Resolver (aka External Dependency Manager (see screenshot 1) and it does not fix the issue.

Also we tried to do what they wrote in the forum post you mentioned (screenshot 2 solution) but this did also not solve the problem.

With "changing the unity versions", do you mean to downgrade to a lower version? Because 3.8 that we use is the latest LTS version.
