### ISSUE TITLE
Precompiled Assemblies Unity API Updater Popup

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#2258]
A very naïve question, which option i select on this popup (yes or no). Asking for updating Precompiled Assemblies through Unity API Updater in this Popup.

![precompiles assembly popup](https://user-images.githubusercontent.com/32755091/186381205-2f636d32-0758-4ba1-96b7-ac83b4db31a7.png)

**Comment by MuhammadWaqasOfficial** [comment]
just for clarification.

**Comment by Nyankoo** [comment]
@NVentimiglia Any insight on this?

**Comment by NVentimiglia** [comment]
@Nyankoo @MuhammadWaqasOfficial 

Click yes.
