### ISSUE TITLE
GooglePlayGames + GoogleMobileAds

### ISSUE THREAD

**Issue by SoulessSerpent** [googleads/googleads-mobile-unity#226]
After importing GooglePlayGames v09.34 and then GoogleMobileAds v3.0.3, when I attempt to build the application my aapt.exe crashes then I get a error message "Failed to re-package resources. See the Console for the details". Log: http://pastebin.com/HzKBm6HL
And directory image:
![capture](https://cloud.githubusercontent.com/assets/9650299/15638009/c063c9a0-265e-11e6-95f0-d35fb22c71af.PNG)

I am also using GameAnalytics as well

**Comment by rampara** [comment]
Are you still running into this issue with the latest version of the plugin (v3.0.4) ? Is the error output you provided complete? It doesn't seem to have any details on the actual cause of the error.
