### ISSUE TITLE
Duplicate class com.google.android.exoplayer2.ui.DownloadNotificationHelper

### ISSUE THREAD

**Issue by HAL-JP** [googleads/googleads-mobile-unity#2265]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.8
  * Google Mobile Ads Unity plugin version:7.2.0
  * Platform: Android (iOS, Android, Unity Editor)
  * Mediation ad networks used, and their versions:AdColonyUnityAdapter-2.6.0 AppLovinUnityAdapter-6.3.1 ChartboostUnityAdapter-3.5.1 FacebookUnityAdapter-3.7.0 FyberUnityAdapter-3.0.2 IMobileUnityAdapter-1.2.2 IronSourceUnityAdapter-2.2.3 MaioUnityAdapter-1.4.1 MyTargetUnityAdapter-3.11.2 NendUnityAdapter-5.2.0 TapjoyUnityAdapter-2.9.0 UnityAdsUnityAdapter-3.2.1 VungleUnityAdapter-3.8.2

### [REQUIRED] Step 2: Describe the problem
Build fails.

#### Steps to reproduce:
Import the AdMob plugin.
Force resolve of ExternalDependencyManager.
Build on Android.
I get an error.

#### Error Code:

`
 java.lang.RuntimeException: Duplicate class com.google.android.exoplayer2.ui.DownloadNotificationHelper found in modules jetified-com.google.android.exoplayer.exoplayer-core-2.17.1-runtime.jar (:com.google.android.exoplayer.exoplayer-core-2.17.1:) and jetified-com.google.android.exoplayer.exoplayer-ui-2.15.1-runtime.jar (:com.google.android.exoplayer.exoplayer-ui-2.15.1:)
`

**Comment by a314266177** [comment]
add in gadle  
implementation 'com.google.android.exoplayer:exoplayer-ui:2.17.1'
