### ISSUE TITLE
Why no ad load on android?

### ISSUE THREAD

**Issue by JohnTong** [googleads/googleads-mobile-unity#227]
why both banner and intersi are not loaded ? I just follow the official document here[https://developers.google.com/mobile-ads-sdk/docs/games#unity_plugin_api](url)

**Comment by JohnTong** [comment]
can anybody help me ? I just import the latest package and copy the google play service to android folder but the ad will never load. none of the events such as OnAdFailedtoLoad fire. pls help

**Comment by rampara** [comment]
Can you post the contents of logcat under the "Unity" and "Ads" tags, during an ad request?

**Comment by JohnTong** [comment]
@rampara thank you for your reply, I just export the APK to my HTC ONE M7. Honestly, I am not an android dever, so I do not know how to debug with eclipse. Would you please give me a unity project demo? really thank you!

**Comment by JohnTong** [comment]
@rampara I'm sorry but now it keeps saying 'Internal Error', how to deal with this, thank you!

**Comment by JohnTong** [comment]
@rampara even I use an increct id, it still says internal error.

**Comment by rampara** [comment]
This repository contains a [sample application](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld/Assets). It's a simple unity project that should allow you to request and display ads once you edit the `GoogleMobileAdsDemoScript.cs` script to use ad units you've set up. It should provide you with a good starting point for figuring out how to request and display ads correctly.

**Comment by JohnTong** [comment]
hi rampara, my problem get resolved. thanks a lot. @rampara

**Comment by rampara** [comment]
Glad you were able to resolve your issue.
