### ISSUE TITLE
Callbacks dont fired after personalization popup appear

### ISSUE THREAD

**Issue by CorvoOrc** [googleads/googleads-mobile-unity#2273]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: Unity 2020.3.20f1
  * Google Mobile Ads Unity plugin version: 7.2.0
  * Platform: Android
  * Platform OS version: 
  * Any specific devices issue occurs on: Samsung S20 FE
  * Mediation ad networks used, and their versions: Unity Ads 3.3.0

### [REQUIRED] Step 2: Describe the problem

Hi,
thanks for Unity plugin.

During 3 month we use AdMob with networks (AdColony, AppLovin, Facebook, Tapjoy etc.), **Rewarded** ad format, all fine.
Now we add network **Unity Ads** (waterfall) and have problem with ad callbacks when personalization popup appear.
This problem only with Unity Ads, another networks work fine.

**Problem: events OnAdOpening, OnUserEarnedReward, OnAdClosed dont fired at adapter Unity Ads at first watch on Android with Rewarded format (dont know about iOS) when personalization popup appears.**

Reproduction steps (at first watch with adapter UnityAds):
1. ad start loading
2. after loading ad (OnAdLoaded fired) personalization popup appears
3. apply or dissmis personalization popup settings, popup closed
4. video start playing
5. when video finished OnAdOpening, OnUserEarnedReward, OnAdClosed callbacks dont fired (only OnAdLoaded).
At second time all is normal - ads finished all callbacks fired. When Reset advertising ID (Settings -> Google -> Ads -> Reset advertising ID) personalization poput appears again causing a problem again.

Tested on all combination AdMob plugin 7.0.1 and 7.2.0 with Unity Ads network 3.2.1 and 3.3.0.
Reproduced on all Android mobiles that was tested so reproduce project wasnt created.

Also trying some options like disable/enable "Delay app measurement" - nothing changed, personalization popup appears just before the video start, dont at start initialization.

Attached logs with problem and without problem, filtered with "Ads" tag + some application log. (first part =======SUCCESS LOG=======, second part =======FAIL LOG=======)
[admob_unityads.txt](https://github.com/googleads/googleads-mobile-unity/files/9485075/admob_unityads.txt)

![personalization_popups](https://user-images.githubusercontent.com/9967287/188324413-f95b9e90-5a37-4425-8f18-9c5279f5b7bd.jpg)

UPD: Look like this https://forum.unity.com/threads/onunityadsshowfailure-is-triggered-always-on-first-run-when-cookie-dialog-appears.1172642/

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
