### ISSUE TITLE
Rewarded Interstitial Ad adLoadCallback Method error

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#2279]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.1.13f1
  * Google Mobile Ads Unity plugin version:7.2.0
  * Platform: Unity Editor

### [REQUIRED] Step 2: Describe the problem
Rewarded Interstitial Ad adLoadCallback Method error

#### Steps to reproduce:
Rewarded Interstitial Ad Implement guideline on (https://developers.google.com/admob/unity/rewarded-interstitial) is incorrect.

- adLoadCallback 2nd parameter is string where as in RewardedInterstitialAd class in LoadAd method, 

public static void LoadAd(string adUnitID, AdRequest request, Action<RewardedInterstitialAd, AdFailedToLoadEventArgs> adLoadCallback)

it require AdFailedToLoadEventArgs.

So it throw error, Argument 3: cannot convert from 'method group' to 'Action<RewardedInterstitialAd, AdFailedToLoadEventArgs>'

**Comment by MuhammadWaqasOfficial** [comment]
i resolved it by replacing 
 void adLoadCallback(RewardedInterstitialAd ad, string error)
to
void adLoadCallback(RewardedInterstitialAd ad, AdFailedToLoadEventArgs error)

**Comment by NVentimiglia** [comment]
Thanks for the update @MuhammadWaqasOfficial 

We will correct our docs shortly.
