### ISSUE TITLE
Native Ad Adds unnecessary permissions to AndroidManifest

### ISSUE THREAD

**Issue by IShix-g** [googleads/googleads-mobile-unity#2286]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.38f1
  * Google Mobile Ads Unity plugin version: 7.2.0
  * Platform: Android
  * Platform OS version: Android 11
  * Any specific devices issue occurs on: No
  * Mediation ad networks used, and their versions:

#### Steps to reproduce:

**What happened?**
This occurs when importing native ad plugins. If the permissions are not required for native advertising, please remove them.

Following permissions:
```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
```

**How can we make the problem occur?**
Import [Admob plugin](https://github.com/googleads/googleads-mobile-unity/releases/tag/v7.2.0) and [Admob native plugin](https://dl.google.com/googleadmobadssdk/GoogleMobileAds-native.unitypackage) to build Android app

**Sample project**
[https://drive.google.com/file/d/1GKLB6V7kvb_t6rv5sROdvPsII-sQNoim/view?usp=sharing](https://drive.google.com/file/d/1GKLB6V7kvb_t6rv5sROdvPsII-sQNoim/view?usp=sharing)

**Comment by NVentimiglia** [comment]
Thanks, will fix
