### ISSUE TITLE
GMA 7.2.0 External Dependency Manager Version Mismatch

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#2291]
Step 1: Describe your environment

  * Unity version: 2022.1.3f1
  * Google Mobile Ads Unity plugin version: 7.2.0
  * Platform: Unity Editor, Android

Step 2: Describe the problem
 External Dependency Manager Version Mismatch. 
 On https://github.com/googleads/googleads-mobile-unity/releases page say built and test with external dependency manager of version 1.2.171. But we import GMA sdk it has external dependency manager version 1.2.172.
See attachment.
![gma sdk in unity](https://user-images.githubusercontent.com/32755091/190077208-c573d8ac-e21e-4723-96a9-53e1fa21a0b5.png)
![gma sdk git](https://user-images.githubusercontent.com/32755091/190077261-6c240822-447f-4bc5-8497-c274406ae5c8.png)

**Comment by NVentimiglia** [comment]
Thanks, will fix

**Comment by ChaserKnight** [comment]
@NVentimiglia so which one is actually correct? Was the plugin actually tested with 1.2.171 or you will update the release page to state 1.2.172 ?
