### ISSUE TITLE
Why Ads are showing , huge number of requests are generating but 0 impression being recorded

### ISSUE THREAD

**Issue by Mritunjaysri01** [googleads/googleads-mobile-unity#2297]
Step 1: Describe your environment

Unity version: 2021.3.2
Google Mobile Ads Unity plugin version: 7.1.0 + Native plugin
Platform: android (iOS, Android, Unity Editor)
Platform OS version: android 8.0.0 (eg iOS 10, Android 9)
Any specific devices issue occurs on: _____
Mediation ad networks used, and their versions: none

#### Steps to reproduce:
 I have connected my apps with the googleads-mobile-unity SDK, with the ad unit IDs generated there and serving ads with the help of them.
It's clear that the ADs are being served and I can also see the huge number of requests each day, but there's no indication of an impression (0 impressions) being recorded.

**Comment by NVentimiglia** [comment]
Hi @Mritunjaysri01,

There could be a number of issues which cause reporting errors like this. The github issues tracker is ideal for edit-time integration issues, and runtime reporting issues  are best resolved through [admob support](https://admob.google.com/home/request-consult/). 

Please disclose:
- a link this github issue
- mention you are using
- your publisher id and affected ad unit ids
- any screenshots describing the issue
- also a [network trace](https://developers.google.com/admob/android/network-tracing).

Once submitted we can get you in touch with the right people.
