### ISSUE TITLE
User is unable to close all Rewarded Ads

### ISSUE THREAD

**Issue by Nyankoo** [googleads/googleads-mobile-unity#2301]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.9f1
  * Google Mobile Ads Unity plugin version: 7.2.0
  * Platform: Android
  * Platform OS version: 8.1.0
  * Any specific devices issue occurs on: BV9600Pro
  * Mediation ad networks used, and their versions: AdMob, Meta Audience Network, Applovin (all latest version)

### [REQUIRED] Step 2: Describe the problem

We can't reproduce this locally, but we got a user report that he is unable to close **_all_** Rewarded Ads since we updated to version 7.2.0 of the AdMob plugin.

Tapping on the "x" results in the screen to blink once and nothing else. The ad stays on screen and the user is unable to return to our app without force-closing it.

Please see below screenshot for an example of the issue.
![9dc93c3c-ed4e-4090-a7ed-af8a05c10858](https://user-images.githubusercontent.com/6652214/191025239-33000168-8efe-4044-bc77-96cb5557bb10.png)

**Comment by NVentimiglia** [comment]
Hi Nyankoo,

This looks like an Android SDK specific issue. Can you please follow up with the [AdMob Community forum](https://support.google.com/admob/?hl=en#topic=7383088). They will have the resources to help you with this issue.

Thanks.
