### ISSUE TITLE
App turned off as soon as it started

### ISSUE THREAD

**Issue by NurdKim** [googleads/googleads-mobile-unity#2302]
* Unity version: ___2012.3.4f1__
  * Google Mobile Ads Unity plugin version: __7.2.0___
  * Platform: __Android___ (iOS, Android, Unity Editor)
  * Platform OS version: ___Android10__ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: __Galaxy S9___
  * Mediation ad networks used, and their versions: _____

I've used GoogleMobileAds Unity Plugin 7.2.0v for banner app ads for my project.
It went back without a problem locally (windows OS), However, there was a problem with the target machine(Android 10, API level29).
Aborted as soon as the app started, this is the problem I face. Can I ask for your help?

**Comment by NVentimiglia** [comment]
Hi @NurdKim can you include a debug log of the incident?

**Comment by NurdKim** [comment]
![image](https://user-images.githubusercontent.com/113933802/191157635-a971c91e-0737-40e1-8980-1195fbaf7ef5.png)
Do I have to register an app to test banner ads?

**Comment by NurdKim** [comment]
![image](https://user-images.githubusercontent.com/113933802/191157828-286b4784-efc4-43a6-8d9a-cdf6ea29adf7.png)

Do I have to register an app to test banner ads?

**Comment by NVentimiglia** [comment]
Hi @NurdKim  You need to add the publisher Id to the GoogleMobileAds settings. You can use a test If to get started.

android: ca-app-pub-3940256099942544~3347511713

ios: ca-app-pub-3940256099942544~1458002511

For more information, see https://developers.google.com/admob/unity/quick-start

**Comment by NurdKim** [comment]
Thank you for your feedback. Have a happy day!

2022년 9월 23일 (금) 오전 7:25, Nicholas Ventimiglia ***@***.***>님이
작성:

**Comment by NurdKim** [comment]
Thank you for your feedback!! Have a happy day ~!
