### ISSUE TITLE
Redmi Note 9 black screen ads after use file picker

### ISSUE THREAD

**Issue by Alekxss** [googleads/googleads-mobile-unity#2305]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.8f1
  * Google Mobile Ads Unity plugin version: 7.2.0
  * Platform: Android
  * Platform OS version: Android 11, MIUI Global 12.5.5.0
  * Any specific devices issue occurs on: Redmi Note 9
  * Mediation ad networks used, and their versions: Facebook Audience Network 6.2.1, AdColony 4.8.0, Pangle 4.5.601, InMobi 10.0.700

### [REQUIRED] Step 2: Describe the problem

Black screen, application not response after used native file manager and try to show rewarded or interstitial ad. If fold down and open again - reload application or still keep in black screen. OS button "Back" not works, not close black ad.

This happens on Russian version on Redmi Note 9, on Indonesian not reproduce, but Indonesian version got this black screen if fold-unfold application.

#### Steps to reproduce:

1. Load rewarded ad
2. Pick file using native file manager (Android Goodies plugin, common used by Unity users)
3. Show rewarded ad
4. Black screen 70-80% times, but sometimes can work fine 3-5 ads open

**Comment by NVentimiglia** [comment]
Hi @Alekxss 

This sounds like a device specific issue which we will have trouble solving. Have you tried talking to the creator of the file picker plugin? Perhaps there is an issue relating to returning focus to the correct activity.
