### ISSUE TITLE
Editor Dummy Ads Canvas Sort Order

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#2306]
Step 1: Describe your environment

  * Google Mobile Ads Unity plugin version:7.2.0
  * Platform: Unity Editor

Step 2: Describe the problem
Dummy ads (interstitial specifically)in unity editor canvas showing behind my panels or canvas because same canvas sort order. 
To close dummy ad (interstitial specifically) have to change sort order first to bring in front and then close the ad.
i recommend to change and set sort order high in dummy ads prefabs. Else i think we are allowed to change that bit in GMA

**Comment by NVentimiglia** [comment]
Thanks, will do.
