### ISSUE TITLE
rootViewController nil issue

### ISSUE THREAD

**Issue by mugenkr** [googleads/googleads-mobile-unity#2308]
### Describe your environment
  * Unity version: 2020.3.28f1
  * Google Mobile Ads Unity plugin version: v7.0.1
  * Platform: ios
  * Platform OS version:  iOS 11 later
  * Any specific devices issue occurs on:  iOS All
  * Mediation ad networks used, and their versions: N.A

#### Relevant Code:
```
+ (UIViewController *)unityGLViewController {
  id<UIApplicationDelegate> appDelegate = [UIApplication sharedApplication].delegate;
  // your code
  if ([appDelegate respondsToSelector:@selector(rootViewController)]) {
    return [[[UIApplication sharedApplication].delegate window] rootViewController];
  }
  return nil;
}
```

#### Isn't this right?
```
  // my opinion
  if ([[appDelegate window] respondsToSelector:@selector(rootViewController)]) {
    return [[[UIApplication sharedApplication].delegate window] rootViewController];
  }
```

#### Because of this handling, every time we play an ad video in our iOS project, an error is being returned.
-> HandelRewardedAdFailedToShow event received with message: Cannot present from a nil view controller. code=17 domain=com.google.admob

**Comment by NVentimiglia** [comment]
Hi @mugenkr

I think you may be right, I will schedule a fix for this isse.
