### ISSUE TITLE
AppLovin 6.3.1 & AdMob 7.2.0 -> Dependency Issue & Update needed

### ISSUE THREAD

**Issue by dcosmin-97** [googleads/googleads-mobile-unity#2317]
### [REQUIRED] Environment

  * Unity version: 2020.3.40f1
  * Google Mobile Ads Unity plugin version: 7.2.0
  * Platform: Android
  * Platform OS version: Android 12
  * Any specific devices issue occurs on: S20 FE 5G
  * Mediation ad networks used, and their versions: 
            1.   AdColony 2.6.0
            2.   AppLovin 6.3.1
            3.   Meta 3.8.0
            4.   Pangle 1.3.0
            5.   Vungle 3.9.0

#### Steps to reproduce:
After upgrading Pangle to 1.3.0 and Vungle to 3.9.0 and force resolve 

=> AppLovin has made some changes:
Plugins/Android/androidx.annotation.annotation-1.4.0.jar => Plugins/Android/androidx.annotation.annotation-1.5.0.jar
Plugins/Android/com.applovin.applovin-sdk-11.4.5.aar => Plugins/Android/com.applovin.applovin-sdk-11.5.1.aar
Plugins/Android/com.google.ads.mediation.applovin-11.4.5.0.aar => Plugins/Android/com.google.ads.mediation.applovin-11.5.1.0.aar
Plugins/Android/androidx.media.media-1.3.1.aar => Plugins/Android/androidx.media.media-1.0.0.aar
Plugins/Android/androidx.recyclerview.recyclerview-1.2.1.aar => Removed
Plugins/Android/com.google.android.exoplayer.exoplayer-2.15.1.aar => Removed
Plugins/Android/com.google.android.exoplayer.exoplayer-common-2.15.1.aar => Removed
Plugins/Android/com.google.android.exoplayer.exoplayer-core-2.15.1.aar => Removed
Plugins/Android/com.google.android.exoplayer.exoplayer-dash-2.15.1.aar => Removed
Plugins/Android/com.google.android.exoplayer.exoplayer-extractor-2.15.1.aar => Removed
Plugins/Android/com.google.android.exoplayer.exoplayer-hls-2.15.1.aar => Removed
Plugins/Android/com.google.android.exoplayer.exoplayer-rtsp-2.15.1.aar => Removed
Plugins/Android/com.google.android.exoplayer.exoplayer-smoothstreaming-2.15.1.aar => Removed
Plugins/Android/com.google.android.exoplayer.exoplayer-transformer-2.15.1.aar => Removed
Plugins/Android/com.google.android.exoplayer.exoplayer-ui-2.15.1.aar => Removed
Plugins/Android/com.google.guava.failureaccess-1.0.1.jar => Removed
Plugins/Android/com.google.guava.guava-27.1-android.jar => Removed
Plugins/Android/com.google.guava.listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar => Removed

If you don't manually add these references back, the ads will not show!
I think this bug occurs because all the exoplayer.aar are deleted.
Will there be an update soon for AppLovin?

Thank you!

**Comment by Nyankoo** [comment]
@dcosmin-97 Can you post your workaround to make ads work again?

**Comment by SimtionR** [comment]
Applovin 6.3.1 is not working anymore with Admob 7.2.0.
They should upload a new version to support Applovin 11.5.1 or 11.5.2 SDK.
I saw they are also working to release Applovin 11.5.2 for Android so it might take a while.


Can someone provide any updates

**Comment by NVentimiglia** [comment]
Thanks for this report. We are aware of the issue and looking into a solution.

**Comment by dcosmin-97** [comment]
@NVentimiglia  Hello!

I have some questions regarding AdMob 7.3.0 -> latest release.

All the new mediated networks releases are tested with Admob 7.2.0 and if you look here: https://github.com/googleads/googleads-mobile-android-mediation, they will specify the following: 
- Built and tested with:
- Google Mobile Ads SDK version 21.2.0.

If you force resolve in Unity, AdMob 7.2.0, you will have :
![image](https://user-images.githubusercontent.com/66071707/195979990-d944ff7b-94da-4e19-ae89-804c5e47bb03.png)
-> com.google.android.gms.play-services-ads-21.3.0 is already added.

My questions:
Should we update to Admob 7.3.0 to support 21.3.0 or Admob 7.2.0 will work fine with SDK 21.3.0? 
If we update to AdMob 7.3.0, all the releases from the mediated networks that were tested with 7.2.0 will work on 7.3.0? 
Should we stay on AdMob 7.2.0 and wait for all the mediated networks to be compatible with 7.2.0 and then wait for the mediated networks to receive an update for 7.3.0 before downloading AdMob 7.3.0? 

I ask all of these questions because there are a lot of networks still on Admob 7.1.0 and something might crash without knowing what to do. I think there are a lot of updates and some things are still behind.

Thank you!

**Comment by NVentimiglia** [comment]
Hi @dcosmin-97
 
 - Yes Unity plugin version 7.3.0 will work with Android SDK 21.3.0.
 - Unity Plugin 7.3.0 has a minimum Android SDK of 21.1.0 due to the Response Info additions.
 - Unity plugin 7.2.0 does not require 21.3.0, [but if there is a need](https://developers.google.com/admob/android/rel-notes), you can manually update if you like.
