### ISSUE TITLE
OnAdOpening not working after error AFMA_ReceiveMessage is not defined (:1)

### ISSUE THREAD

**Issue by BTooLs** [googleads/googleads-mobile-unity#232]
Hello, we have a problem with an old adUnit (>30 days old)
- Unity 5.3.4.f1
- AdMob 3.0.2 and play-services-ads 8.4.0
- tested with AdMob 3.03 and play-services-ads and ads-lite 9.0.2

Interstitial works, but the banner:

`I/Ads     (17326): Starting ad request.
W/Ads     (17326): The webview is destroyed. Ignoring action.
E/Ads     (17326): JS: Uncaught ReferenceError: AFMA_ReceiveMessage is not defined (:1)
I/Ads     (17326): Scheduling ad refresh 60000 milliseconds from now.
I/Ads     (17326): Ad finished loading.`

**adMobBannerView.OnAdLoaded** is called
no other event is called inside Unity (including **OnAdOpening**)

The banner is visible (test ad & real ad) but the OnAdOpening event is not triggered.

This is the response from googleads.g

`HTTP/1.1 200 OK
P3P: policyref="https://googleads.g.doubleclick.net/pagead/gcn_p3p_.xml", CP="CURa ADMa DEVa TAIo PSAo PSDo OUR IND UNI PUR INT DEM STA PRE COM NAV OTC NOI DSP COR"
X-Afma-ActiveView: {"click_string":"BukE5ErZWV7SYAeeHzAaL9rioBgCd2tySrgIAABABOAGIAQGgBjk","is_active_view_immediate_enabled":true,"activeview_cpm_urls":[],"active_experiment_ids":""}
X-Afma-Gws-Query-Id: ErZWV90-9cLMBs_0qLgJ
X-Afma-Debug-Dialog: AdGroup+Creative+ID+0=80960714565&Click+URL+0=/aclk%3Fsa%3Dl%26ai%3DCXGJvErZWV7SYAeeHzAaL9rioBuXBms4Endrckq4C5Kvp5bgBEAEgwuzcIGCDpeGF6BuIAQGgAfvU0tcDqQJcl1_jwfGoPqgDAaoEqwFP0KRrr9OmD-qGCqLB5jaug1HpVoAVAngnMU0S58xUscPfGse4kYgqMUp112Plv7fSuB8j3bL-31f_H2gtBQM-bG9sMls-S-BEUVMmSGRof4iY_xD8EAe1OLCVMTgCo2iwAQnDOxS1mAP0QoSjdG-_BRzseZDZBz45M6RTBOTLqNPDOCuHbZLL0n7nUIG6fkUigvsoT540Vby4ENRR02PfQd__zjC0IE0j2gaQBgGgBjnABguAB-2qrSiYBwGoB6a-G9gHAQ%26num%3D1%26cid%3DCAASEuRo4GfQx8GiQYbbAbX_LjW0cg%26sig%3DAOD64_1FibdXcipo50jqP_vYKjDm60a02Q%26adurl%3Dhttps://developers.google.com/mobile-ads-sdk/
X-Afma-Use-Https: false
X-Afma-Refresh-Rate: 60
X-Afma-Content-Url-Opted-Out: true
Content-Type: text/html; charset=UTF-8
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Date: Tue, 07 Jun 2016 11:54:58 GMT
Server: cafe
Cache-Control: private
X-XSS-Protection: 1; mode=block
Alternate-Protocol: 443:quic
Alt-Svc: quic=":443"; ma=2592000; v="34,33,32,31,30,29,28,27,26,25"
Transfer-Encoding: chunked

<!DOCTYPE html><html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><script src="https://googleads.g.doubleclick.net/mads/static/formats/templates.js"></script><script>document.addEventListener("touchmove", function(e) {e.preventDefault();});</script><style>* {background:transparent;font-family:sans-serif;margin:0px;padding:0px;-ms-user-select:none;-webkit-user-select:none;}a {text-decoration:none;}</style><script>(function(){window.ss=function(){};}).call(this);(function(){var c=this;var e=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},m=function(a,b){return a<b?-1:a>b?1:0};var n;a:{var p=c.navigator;if(p){var q=p.userAgent;if(q){n=q;break a}}n=""};var r=-1!=n.indexOf("Opera"),t=-1!=n.indexOf("Trident")||-1!=n.indexOf("MSIE"),u=-1!=n.indexOf("Edge"),v=-1!=n.indexOf("Gecko")&&!(-1!=n.toLowerCase().indexOf("webkit")&&-1==n.indexOf("Edge"))&&!(-1!=n.indexOf("Trident")||-1!=n.indexOf("MSIE"))&&-1==n.indexOf("Edge"),w=-1!=n.toLowerCase().indexOf("webkit")&&-1==n.indexOf("Edge"),x=function(){var a=c.document;return a?a.documentMode:void 0},y;a:{var z="",A=function(){var a=n;if(v)return/rv\:([^\);]+)(\)|;)/.exec(a);if(u)return/Edge\/([\d\.]+)/.exec(a);if(t)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(w)return/WebKit\/(\S+)/.exec(a);if(r)return/(?:Version)[ \/]?(\S+)/.exec(a)}();A&&(z=A?A[1]:"");if(t){var B=x();if(null!=B&&B>parseFloat(z)){y=String(B);break a}}y=z}var C=y,D={},E=function(a){if(!D[a]){for(var b=0,d=e(String(C)).split("."),f=e(String(a)).split("."),k=Math.max(d.length,f.length),l=0;0==b&&l<k;l++){var K=d[l]||"",L=f[l]||"",M=RegExp("(\\d*)(\\D*)","g"),N=RegExp("(\\d*)(\\D*)","g");do{var g=M.exec(K)||["","",""],h=N.exec(L)||["","",""];if(0==g[0].length&&0==h[0].length)break;b=m(0==g[1].length?0:parseInt(g[1],10),0==h[1].length?0:parseInt(h[1],10))||m(0==g[2].length,0==h[2].length)||m(g[2],h[2])}while(0==b)}D[a]=0<=b}},F=c.document,G=F&&t?x()||("CSS1Compat"==F.compatMode?parseInt(C,10):5):void 0;var H;if(!(H=!v&&!t)){var I;if(I=t)I=9<=Number(G);H=I}H||v&&E("1.9.1");t&&E("9");var J={},O=function(a,b){void 0!==J[a]||(J[a]=[]);var d=J[a][b];d||(J[a][b]=!0);if(!d)if(d=document.getElementById(a),window.css)css(a,"nb",b,!0,void 0);else if(d){var f=d.href,k=f+("&nb="+b);d.href=2E3<k.length?f:k}};window.cla=function(a,b){if(0>b||parseInt(b,10)!==b)b=17;O(a,b)};window.cll=function(a,b){O(a,b||1)};window.clb=function(a){O(a,2)};window.clh=function(a,b){O(a,b||0)};}).call(this);(function(){var d=this;var g=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},m=function(a,b){return a<b?-1:a>b?1:0};var n;a:{var p=d.navigator;if(p){var q=p.userAgent;if(q){n=q;break a}}n=""};var r=-1!=n.indexOf("Opera"),t=-1!=n.indexOf("Trident")||-1!=n.indexOf("MSIE"),u=-1!=n.indexOf("Edge"),v=-1!=n.indexOf("Gecko")&&!(-1!=n.toLowerCase().indexOf("webkit")&&-1==n.indexOf("Edge"))&&!(-1!=n.indexOf("Trident")||-1!=n.indexOf("MSIE"))&&-1==n.indexOf("Edge"),w=-1!=n.toLowerCase().indexOf("webkit")&&-1==n.indexOf("Edge"),x=function(){var a=d.document;return a?a.documentMode:void 0},y;a:{var z="",A=function(){var a=n;if(v)return/rv\:([^\);]+)(\)|;)/.exec(a);if(u)return/Edge\/([\d\.]+)/.exec(a);if(t)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(w)return/WebKit\/(\S+)/.exec(a);if(r)return/(?:Version)[ \/]?(\S+)/.exec(a)}();A&&(z=A?A[1]:"");if(t){var B=x();if(null!=B&&B>parseFloat(z)){y=String(B);break a}}y=z}var C=y,D={},E=function(a){if(!D[a]){for(var b=0,c=g(String(C)).split("."),e=g(String(a)).split("."),f=Math.max(c.length,e.length),l=0;0==b&&l<f;l++){var K=c[l]||"",L=e[l]||"",M=RegExp("(\\d*)(\\D*)","g"),N=RegExp("(\\d*)(\\D*)","g");do{var h=M.exec(K)||["","",""],k=N.exec(L)||["","",""];if(0==h[0].length&&0==k[0].length)break;b=m(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||m(0==h[2].length,0==k[2].length)||m(h[2],k[2])}while(0==b)}D[a]=0<=b}},F=d.document,G=F&&t?x()||("CSS1Compat"==F.compatMode?parseInt(C,10):5):void 0;var H;if(!(H=!v&&!t)){var I;if(I=t)I=9<=Number(G);H=I}H||v&&E("1.9.1");t&&E("9");var J=function(a,b,c,e){if(window.css)css(b,c,e,void 0,void 0);else if(a){b=a.href;var f="&"+c+"=";c=b.indexOf(f);0>c?e=b+f+e:(c+=f.length,f=b.indexOf("&",c),e=0<=f?b.substring(0,c)+e+b.substring(f):b.substring(0,c)+e);a.href=2E3<e.length?b:e}};var O=null,P=function(a){O=a};document.addEventListener&&document.addEventListener("mousedown",P,!0);window.xy=function(a,b,c){c=c||b;if((a=a||O)&&b&&c){var e=Math.round(a.clientY-c.offsetTop),f=b.id;J(b,f,"nx",Math.round(a.clientX-c.offsetLeft));J(b,f,"ny",e)}};}).call(this);function st(id) {var a = document.getElementById(id);if (a) {xy(window.event, a);}}function ha(a,x){  clh(a,x);}function ia(a,e,x) {cll(a,x);}function ja(a,x) {cla(a,x);}function ga(o,e,x) {if (document.getElementById) {var a=o.id.substring(1),p="",r="",g=e.target,t,f,h;if (g) {t=g.id;f=g.parentNode;if (f) {p=f.id;h=f.parentNode;if (h)r=h.id;}} else {h=e.srcElement;f=h.parentNode;if (f)p=f.id;t=h.id;}if (t==a||p==a||r==a)return true;ia(a,e,x);top.location.href=document.getElementById(a).href;}}</script></head><body onload="onLoad()"><div id="google_ad"></div><script>renderAd(document.getElementById('google_ad'), {"creatives":[{"destination_url":"//googleads.g.doubleclick.net/aclk?sa=l\u0026ai=CXGJvErZWV7SYAeeHzAaL9rioBuXBms4Endrckq4C5Kvp5bgBEAEgwuzcIGCDpeGF6BuIAQGgAfvU0tcDqQJcl1_jwfGoPqgDAaoEqwFP0KRrr9OmD-qGCqLB5jaug1HpVoAVAngnMU0S58xUscPfGse4kYgqMUp112Plv7fSuB8j3bL-31f_H2gtBQM-bG9sMls-S-BEUVMmSGRof4iY_xD8EAe1OLCVMTgCo2iwAQnDOxS1mAP0QoSjdG-_BRzseZDZBz45M6RTBOTLqNPDOCuHbZLL0n7nUIG6fkUigvsoT540Vby4ENRR02PfQd__zjC0IE0j2gaQBgGgBjnABguAB-2qrSiYBwGoB6a-G9gHAQ\u0026num=1\u0026cid=CAASEuRo4GfQx8GiQYbbAbX_LjW0cg\u0026sig=AOD64_1FibdXcipo50jqP_vYKjDm60a02Q\u0026adurl=https://developers.google.com/mobile-ads-sdk/","image_creative":{"image_url":"https://googleads.g.doubleclick.net/simgad/7919192385492986811","height":90,"width":728,"is_1_5_click_enabled":true},"use_native_browser":true,"buttons":[{"image_url":"https://googleads.g.doubleclick.net/pagead/images/mobile_unified_button_icon_white.png","text":"Visit Site","background_color_bottom":"#16E","background_color_top":"#26D","border_color":"#3344aa","action_urls":{"click_url":"//googleads.g.doubleclick.net/aclk?sa=l\u0026ai=CXGJvErZWV7SYAeeHzAaL9rioBuXBms4Endrckq4C5Kvp5bgBEAEgwuzcIGCDpeGF6BuIAQGgAfvU0tcDqQJcl1_jwfGoPqgDAaoEqwFP0KRrr9OmD-qGCqLB5jaug1HpVoAVAngnMU0S58xUscPfGse4kYgqMUp112Plv7fSuB8j3bL-31f_H2gtBQM-bG9sMls-S-BEUVMmSGRof4iY_xD8EAe1OLCVMTgCo2iwAQnDOxS1mAP0QoSjdG-_BRzseZDZBz45M6RTBOTLqNPDOCuHbZLL0n7nUIG6fkUigvsoT540Vby4ENRR02PfQd__zjC0IE0j2gaQBgGgBjnABguAB-2qrSiYBwGoB6a-G9gHAQ\u0026num=1\u0026cid=CAASEuRo4GfQx8GiQYbbAbX_LjW0cg\u0026sig=AOD64_1FibdXcipo50jqP_vYKjDm60a02Q\u0026adurl=https://developers.google.com/mobile-ads-sdk/","final_destination_url":"https://developers.google.com/mobile-ads-sdk/","u2_tracking_url":"https://developers.google.com/mobile-ads-sdk/","u2_final_url":"https://developers.google.com/mobile-ads-sdk/"},"text_color":"#eee","is_hidden":false}],"creative_type":2,"creative_conversion_urls":[]}],"height":90,"width":800,"attribution":{"destination_url":"https://www.google.com/ads/preferences/html/mobile-about.html","icon_url":"https://googleads.g.doubleclick.net/pagead/images/mtad/ad_choices_blue.png","text":"AdChoices","position":0,"user_feedback_data":{"ad_feedback_text":"Stop seeing this ad","mute_icon_url":"https://googleads.g.doubleclick.net/pagead/images/mtad/x_white.png","pub_feedback_text":"Ad covers the page","pub_feedback_icon_url":"https://googleads.g.doubleclick.net/pagead/images/mtad/x_white.png","conversion_url":"https://googleads.g.doubleclick.net/pagead/conversion/?ai=CXGJvErZWV7SYAeeHzAaL9rioBuXBms4Endrckq4C5Kvp5bgBEAEgwuzcIGCDpeGF6BuIAQGgAfvU0tcDqQJcl1_jwfGoPqgDAaoEqwFP0KRrr9OmD-qGCqLB5jaug1HpVoAVAngnMU0S58xUscPfGse4kYgqMUp112Plv7fSuB8j3bL-31f_H2gtBQM-bG9sMls-S-BEUVMmSGRof4iY_xD8EAe1OLCVMTgCo2iwAQnDOxS1mAP0QoSjdG-_BRzseZDZBz45M6RTBOTLqNPDOCuHbZLL0n7nUIG6fkUigvsoT540Vby4ENRR02PfQd__zjC0IE0j2gaQBgGgBjnABguAB-2qrSiYBwGoB6a-G9gHAQ\u0026sigh=a68IqvmivWw","close_button_token":"LppjV6NRYK4Indrckq4CEJWUpVMYlbaUKXAB","interaction_conversion":{"label":"user_feedback_menu_interaction","label_instance":"","include_close_button_token":false},"mute_conversion":{"label":"user_feedback_menu_option","label_instance":"1","include_close_button_token":true},"mute_undo_conversion":{"label":"user_feedback_undo","label_instance":"1","include_close_button_token":true},"pub_feedback_conversion":{"label":"user_feedback_menu_option","label_instance":"3","include_close_button_token":true},"pub_feedback_undo_conversion":{"label":"user_feedback_undo","label_instance":"3","include_close_button_token":true},"survey_header":"What was wrong with this ad?","survey_options":[{"text":"Repetitive","conversion":{"label":"mute_survey_option","label_instance":"2","include_close_button_token":true}},{"text":"Inappropriate","conversion":{"label":"mute_survey_option","label_instance":"8","include_close_button_token":true}},{"text":"Irrelevant","conversion":{"label":"mute_survey_option","label_instance":"7","include_close_button_token":true}}],"back_icon_url":"https://googleads.g.doubleclick.net/pagead/images/mtad/back_blue.png","mute_confirmation_header":"Thanks for the feedback!","mute_confirmation_text":"We’ll review this ad to improve your experience in the future.","pub_feedback_confirmation_header":"Thanks for the feedback!","pub_feedback_confirmation_text":"We’ll use your feedback to review ads on this site.","encoded_cookie":"CAASEuRo4GfQx8GiQYbbAbX_LjW0cg","undo_text":"Undo","closing_countdown_text":"Closing ad: %1$d","attribution_text":"AdChoices","attribution_icon_url":"https://googleads.g.doubleclick.net/pagead/images/mtad/ad_choices_blue.png","attribution_destination_url":"https://www.google.com/ads/preferences/html/mobile-about.html","ad_feedback_icon_url":"https://googleads.g.doubleclick.net/pagead/images/mtad/x_white.png","is_rtl_language":false,"feedback_options":[{"text":"Ad covers the page","conversion":{"label":"user_feedback_menu_option","label_instance":"3","include_close_button_token":true},"undo_conversion":{"label":"user_feedback_undo","label_instance":"3","include_close_button_token":true}},{"text":"Stop seeing this ad","conversion":{"label":"user_feedback_menu_option","label_instance":"1","include_close_button_token":true},"survey":{"header":"What was wrong with this ad?","options":[{"text":"Irrelevant","conversion":{"label":"mute_survey_option","label_instance":"7","include_close_button_token":true}},{"text":"Inappropriate","conversion":{"label":"mute_survey_option","label_instance":"8","include_close_button_token":true}},{"text":"Repetitive","conversion":{"label":"mute_survey_option","label_instance":"2","include_close_button_token":true}}]},"undo_conversion":{"label":"user_feedback_undo","label_instance":"1","include_close_button_token":true}}],"mute_panel_data":{}},"disable_client_rendered_attribution":false},"flags":[{"name":"gmob_evaluate_interstitial_as_fullscreen","value":"true"},{"name":"uses_octagon_sdk","value":"true"},{"name":"gmob_app_promo_u2_click_handling","value":"true"},{"name":"ignore_clicks_during_sjax_duration","value":"0"},{"name":"click_delay_for_non_interstitials_ms","value":"1000"},{"name":"is_app_promo","value":"false"},{"name":"creative_conversion_url","value":"https://googleads.g.doubleclick.net/pagead/conversion/?ai=CXGJvErZWV7SYAeeHzAaL9rioBuXBms4Endrckq4C5Kvp5bgBEAEgwuzcIGCDpeGF6BuIAQGgAfvU0tcDqQJcl1_jwfGoPqgDAaoEqwFP0KRrr9OmD-qGCqLB5jaug1HpVoAVAngnMU0S58xUscPfGse4kYgqMUp112Plv7fSuB8j3bL-31f_H2gtBQM-bG9sMls-S-BEUVMmSGRof4iY_xD8EAe1OLCVMTgCo2iwAQnDOxS1mAP0QoSjdG-_BRzseZDZBz45M6RTBOTLqNPDOCuHbZLL0n7nUIG6fkUigvsoT540Vby4ENRR02PfQd__zjC0IE0j2gaQBgGgBjnABguAB-2qrSiYBwGoB6a-G9gHAQ\u0026sigh=a68IqvmivWw"},{"name":"interstitial_image_scale","value":"true"},{"name":"interstitial_image_scale_limit","value":"1.5"},{"name":"image_1_5_click_ignore","value":"true"},{"name":"image_1_5_click_default_border_definition","value":"10,10,10,10"},{"name":"interstitial_image_action_icon_bgcolor","value":"#3f3f3f"},{"name":"interstitial_image_action_icon_fgcolor","value":"#eeeeee"},{"name":"interstitial_image_action_icon_arrowcolor","value":"white"}],"link_target":"_top"});</script><script>if (window.top && window.top.postMessage) {window.top.postMessage('{"googMsgType": "adpnt"}', '*');}</script></body></html>`

**Comment by rampara** [comment]
Is this error consistency reproducible for every ad request? If not, how often are you seeing this error? Can you provide a Charles log for an ad request where you see this issue?

**Comment by rampara** [comment]
This is benign warning that can be ignored. A future update to the Ads SDK will remove it.
