### ISSUE TITLE
Crash on Kindle Fire devices

### ISSUE THREAD

**Issue by slaczky** [googleads/googleads-mobile-unity#233]
My app has the latest plugin version 3.0.4 and build with Unity 5.3.4f1. It does not have Google Play Games Services.
App crashes at startup on Kindle Fire devices. On other devices no crashes. Attached logcat
[logcat.txt](https://github.com/googleads/googleads-mobile-unity/files/315859/logcat.txt)

**Comment by rampara** [comment]
Within the the `Assets/Plugin/Android` directory project of your Unity project, is an AAR corresponding to the v4 support library present (will be named support-v4-XX.X.X.aar, where X is the version number) ? If not, can you ensure the support library is installed on your machine.

**Comment by slaczky** [comment]
Solved it by click on "Resolve Client Jars" button.

**Comment by rampara** [comment]
Glad you were able to resolve your issue.
