### ISSUE TITLE
invalid

### ISSUE THREAD

**Issue by AnyMindG** [googleads/googleads-mobile-unity#2339]
I have Setup Tapjoy as an ad network on the IronSource dashboard but not getting any ads for Rewarded and Interstitial on iOS Simulator.

Logs for Tapjoy:

Tapjoy Request: https://connect.tapjoy.com/api/connect/v3?timezone=Asia%2FKolkata&os_version=15.5&timestamp=1666107961&brightness=0.5&pub_build_ver=iphonesimulator15.5&debug=true&language_code=en&platform=iOS&app_id=7f259309-c147-4f59-b036-ebe7471ec58c&vendor_id=3EA9837E-10A0-48E3-B7A9-F0936E220DFB&total_disk=245107&session_id=8c9f9fdfe7cfd11d7bd91d1469c15593a565c50a6f3f5f01bda0df6cc0994037&advertising_id=00000000-0000-0000-0000-000000000000&ad_tracking_enabled=true&store_view=true&fq30=2&display_h=2778&omidpv=1.3.16-tapjoy&session_total_count=14&below_consent_age=1&connection_type=wifi&library_revision=c098be6&display_d=489&theme=light&sdk_type=event&volume=0.6&kb_lang=en-US%2Cemoji&plugin=native&us_privacy=1YYY&pkg_ver=1.0.0&verifier=515ae29fc110121c9fd1aef1f82f253b00ab95f5e818ff1fa5ace6ad7ff362a7&display_w=1284&analytics_id=DFEEE3D0-7CB1-4B59-803C-932CAF2EAE4A&install_id=2B476E28-08D7-47B0-AC32-7F39AEF20840-16701-00000EE7234FED3B&avail_disk=52156&installed=1665990208616&device_type=iPhone

[TJLog level: 4] Content request delivered successfully for placement AppLaunch, contentAvailable: 0, mediationAgent: (null)

[TJLog level: 4] [TJSystemPlacement] ended: requestDidSucceed: AppLaunch, but content is not available

[TJLog level: 4] Failed to open URL: about:blank

[TJLog level: 4] Events proxy is ready

[TJLog level: 4] Tapjoy remote device debugging is disabled.

**Note: Getting the ads with MAX mediation but not with IronSource.**

**Comment by NVentimiglia** [comment]
Hi @AnyMindG,

This is a Tapjoy request. You should talk to Tapjoy support about this issue. That said, if you send a full charles log with Admob traces, I will take a look.
