### ISSUE TITLE
The name 'JsonUtility' does not exist in the current context

### ISSUE THREAD

**Issue by michaeljoshua55555** [googleads/googleads-mobile-unity#234]
I created a new unity project in unity 4.6 and i imported the plugin.
I am getting this error:
The name 'JsonUtility' does not exist in the current context
What should I do? Need help

![admob](https://cloud.githubusercontent.com/assets/14315441/16162140/26f0dfc0-34ef-11e6-9d64-95d658ca8a33.JPG)

**Comment by rampara** [comment]
The latest version of the plugin (v3.0.5) resolves this issue.
