### ISSUE TITLE
Google Mobile Ads and VR

### ISSUE THREAD

**Issue by Peny20** [googleads/googleads-mobile-unity#2340]
Hello, from what I found on the internet, Google Mobile Ads does not support VR like Cardboard. Am I wrong? If yes, what ad formats are supported? Is VR support planned? When?

**Comment by NVentimiglia** [comment]
Hi @Peny20 

For a vr ad, I would look at [native ads](https://developers.google.com/admob/unity/native) .

Hope that helps.

**Comment by Peny20** [comment]
Thank you for your answer. So I can place it in scene as some kind of billboard on 3d object? Can it work only on impressions?

**Comment by NVentimiglia** [comment]
Hi Penny,

Yes. Essentially the Native Ad returns an image which you can apply to a 3d mesh.
