### ISSUE TITLE
Release 7.3.0 seems to have class files with version 55 - incompatible with Unity's JDK

### ISSUE THREAD

**Issue by shahprateek317** [googleads/googleads-mobile-unity#2343]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.8f1
  * Google Mobile Ads Unity plugin version: 7.3.0
  * Platform: Unity Editor (iOS, Android, Unity Editor)
  * Platform OS version: Build Issue - target SDK 30 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: N/A
  * Mediation ad networks used, and their versions: N/A

### [REQUIRED] Step 2: Describe the problem

The googlemobileads-unity.aar that is part of the 7.3.0 unitypackage seems to have classes with major version 55, which is incompatible with Unity's JDK 1.8 (version 52), and so the build fails with the following error:

`java.io.IOException: Can't read [C:\Users\shahp\.gradle\caches\transforms-2\files-2.1\328b84521e30516b8226e4c8a181416f\jetified-googlemobileads-unity-runtime.jar(;;;;;;;**.class)] (Can't process class [com/google/unity/ads/AdNetworkExtras.class] (Unsupported version number [55.0] (maximum 54.0, Java `10)))​
`

#### Steps to reproduce:
Simply build an apk with the above setup, with the 7.3.0 release. Also javap into any of the classes in the aar file shows the major version as 55.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by manwithsteelnerves** [comment]
Can someone try [this](https://forum.unity.com/threads/build-error-on-android-app-bundle.1322166/#post-8546147) solution?

**Comment by shahprateek317** [comment]
> Can someone try [this](https://forum.unity.com/threads/build-error-on-android-app-bundle.1322166/#post-8546147) solution?

Thanks - I can confirm that this leads to a successful build in Unity, as opposed to the build fail reported in the OP.

**Comment by shahprateek317** [comment]
Sorry - jumped the gun on closing this - the build now fails with the following error:

* What went wrong:
A problem occurred configuring project ':launcher'.
> Could not resolve all artifacts for configuration ':launcher:classpath'.
   > Could not resolve com.guardsquare:proguard-gradle:7.1.0.
     Required by:
         project :launcher
      > Could not resolve com.guardsquare:proguard-gradle:7.1.0.
         > Could not get resource 'https://jcenter.bintray.com/com/guardsquare/proguard-gradle/7.1.0/proguard-gradle-7.1.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/guardsquare/proguard-gradle/7.1.0/proguard-gradle-7.1.0.pom'.
               > Read timed out

**Comment by shahprateek317** [comment]
Pasting the baseProjectTemplate file here for reference:

// GENERATED BY UNITY. REMOVE THIS COMMENT TO PREVENT OVERWRITING WHEN EXPORTING AGAIN

allprojects {
    buildscript {
        repositories {**ARTIFACTORYREPOSITORY**
            google()
            jcenter()
        }

        dependencies {
            // If you are changing the Android Gradle Plugin version, make sure it is compatible with the Gradle version preinstalled with Unity
            // See which Gradle version is preinstalled with Unity here https://docs.unity3d.com/Manual/android-gradle-overview.html
            // See official Gradle and Android Gradle Plugin compatibility table here https://developer.android.com/studio/releases/gradle-plugin#updating-gradle
            // To specify a custom Gradle version in Unity, go do "Preferences > External Tools", uncheck "Gradle Installed with Unity (recommended)" and specify a path to a custom Gradle version
            classpath 'com.android.tools.build:gradle:4.0.1'
            classpath 'com.guardsquare:proguard-gradle:7.1.0' 
            **BUILD_SCRIPT_DEPS**
        }
    }

    repositories {**ARTIFACTORYREPOSITORY**
        google()
        jcenter()
        flatDir {
            dirs "${project(':unityLibrary').projectDir}/libs"
        }
        maven { url "https://maven.google.com/"}
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by shahprateek317** [comment]
Okay - changed repositories from jcenter to mavenCentral and the build went through. Marking this as closed for now. Will reopen if the build creates further issues.
