### ISSUE TITLE
App Open Ads problem

### ISSUE THREAD

**Issue by DmitryPtukhin** [googleads/googleads-mobile-unity#2348]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: Unity 2021.1.20f1
  * Google Mobile Ads Unity plugin version: 7.1.0
  * Platform: Android 
  * Platform OS version: Android 6, Android 7, Android 12 
  * Any specific devices issue occurs on: Samsung galaxy A13, Asus ZenPad P00C, Motorola G22, Lenovo TB-7504X
  * Mediation ad networks used, and their versions: MetaAudienceNetworkUnityAdapter-3.8.0, GoogleMobileAdsUnityAdsMediation3.2.1

#### Steps to reproduce:

1. Open game https://play.google.com/store/apps/details?id=com.byv.TheCatapult2
3. Sometimes go out of focus and return back to game
4. BUG

sometimes u just enter game and ad in background appear

### **_What happened? How can we make the problem occur?_**

Hello.

We have discovered a serious issue affecting a large number of apps on Google Play.

When testing our game “com.byv.TheCatapult2”, a bug with sound was found.
During the game, strange music began to play in the background.

Links to video with this bug:
https://drive.google.com/file/d/10VOp8sc1T1q8F72-lAM2hR6z_b8W6NkU/view?usp=sharing
https://drive.google.com/file/d/1lOozzwxmLRlWfp1mci7GFYz0Fah4iJoD/view?usp=sharing

This bug was also found in our other apps.

Also, this bug was found  in not our application “com.vpnbeaver.vpn”
https://play.google.com/store/apps/details?id=com.vpnbeaver.vpn

Link to video with this bug in the game “com.vpnbeaver.vpn”:
https://drive.google.com/file/d/1gQSzb1iyJeVyzOQiQFsqgzhOc4iOO_6W/view?usp=sharing
https://drive.google.com/file/d/1MUeI8WnTnNk_ErOkC0HMWijM4nrKY_Zb/view?usp=sharing
https://drive.google.com/file/d/1YqbB08tc0Y4RnbU6osRHUHtWEvG6duBD/view?usp=sharing
https://drive.google.com/file/d/1WflzI48Mvb_uYlJFzMBOsw4elh-r5jlj/view?usp=sharing

This bug was found  in not our application “com.ivy.galaxyshooting.sky”
https://play.google.com/store/apps/details?id=com.ivy.galaxyshooting.sky&hl=en&gl=US

Link to video with this bug in the application “com.ivy.galaxyshooting.sky”:
https://drive.google.com/file/d/1hDrBBUqfDPf2C69-LxKmLbz4XZqyaGg2/view?usp=sharing

### **Where's the bug from**

We are thinking that the bug is related to the new type of advertising “App Open Ads”.
https://developers.google.com/admob/unity/app-open?hl=en

It is called and launched in the background of the game.
We are reaching out to you because we have never used this type of ad format in our games.
There is no declaration of this type of ad format in the code of our games and there is no calling/loading of this type of ad format.
We believe that the error is directly somewhere on the SDK side.

**These are the ads that are running on background:**

beaver vpn (com.vpnbeaver.vpn) ad https://tpc.googlesyndication.com/sadbundle/$csp%3Der-p$/7450208535015352882/071021_G_1945_Adwords_320x480_10b21_HLW_ThinhTV_EN.html

The Catapult 2 (com.byv.TheCatapult2) ad
https://tpc.googlesyndication.com/sadbundle/$csp%3Der-p$/2180557668924924531/index.html

### **_This could be a description, log/console output, etc._**

```
2022-10-27 10:31:46.826 27966-27966/? I/PlayCore: UID: [10180]  PID: [27966] PrewarmService : prewarm(com.vpnbeaver.vpn)
2022-10-27 10:31:46.827 27966-28346/? I/PlayCore: UID: [10180]  PID: [27966] PrewarmService : Initiate binding to the service.
2022-10-27 10:31:46.830 27966-27966/? I/PlayCore: UID: [10180]  PID: [27966] PrewarmService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.prewarmservice.PrewarmService})
2022-10-27 10:31:46.830 27966-28346/? I/PlayCore: UID: [10180]  PID: [27966] PrewarmService : linkToDeath
2022-10-27 10:31:46.833 26863-27064/? I/Finsky: [4162] sug.c(1): prewarm called with callingPackage: com.vpnbeaver.vpn
2022-10-27 10:31:46.833 662-939/? I/hwcomposer: [HWCDisplay] [Display_0 (type:1)] fps:43.871449,dur:1002.93,max:55.62,min:9.85  
2022-10-27 10:31:46.883 27966-27966/? I/Ads: JS: Cocos Creator v2.4.6 (https://tpc.googlesyndication.com/sadbundle/$csp%3Der-p$/3731451773548068240/071021_G_1945_Adwords_320x480_10a21_HLW_ThinhTV_EN.html:1)
2022-10-27 10:31:46.984 26863-26863/? I/Finsky: [2] suj.c(2): /resolveLink request succeeded
```

**Comment by NVentimiglia** [comment]
Hi @DmitryPtukhin 

First of all thank you for the detailed report, the videos really help.

When you say BUG, what experience are you describing? Is this a crash, the ad not showing, or something else? From the looks of the video, it looks like that the experience is that the ad does not show on landscaped phones.

Second, can you provide additional log/console? The log provided does not include enough details. What I am looking for is anything which includes: 1) the google namespace, 2) Lifecycle events such as application pause, 3) any error or exception details.

**Comment by DmitryPtukhin** [comment]
It is not a crash/anr. The Ad appears in background with music. You cannot see the ad itself. The only way to close it is via killing the app. If minimized the ad with music is still running. Sometimes it appears when changing focus, sometimes no. It is weird cuz we use only banner, rewarded and interstitial ad formats and we do not show them on the start of the game(where this ad randomly starts).
We are not showing this ad. And it is also on landscaped devices and portrait devices too.

https://docs.google.com/document/d/1c94GMyQhvql55cD3CTteJFochfxYONLYHLQmd03-1hw/edit?usp=sharing

**Comment by NVentimiglia** [comment]
Hi @DmitryPtukhin 

Correct me if I am wrong, but it seems the AppOpenAd will automatically present itself with the full screen content presented. Is this correct?

Second, I am having difficulty understanding the log. It includes all device messages and It is hard to find which ones pertain to your application. Could you provide a minimal sample app of the issue?

**Comment by NVentimiglia** [comment]
@DmitryPtukhin 

Can you provide replication steps for this issue ?

**Comment by NVentimiglia** [comment]
Hi @DmitryPtukhin,

To properly debug the problem I need a minimal sample app, or replication steps that I can apply to our HelloWorld sample. I am unable to verify that this issue is due to AdMob from a close source apk.
