### ISSUE TITLE
Failed to repackage resources in Unity 4.6

### ISSUE THREAD

**Issue by michaeljoshua55555** [googleads/googleads-mobile-unity#235]
I tried deleting two lines under inapp purchases, but still this error is there

This is the message i am getting in the console. What should I do?

Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Program Files (x86)\Android\android-sdk\build-tools\23.0.2\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Program Files (x86)/Android/android-sdk/platforms/android-23\android.jar" -F bin/resources.ap_ --extra-packages com.google.unity

stderr[
AndroidManifest.xml:17: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

]
stdout[
Configurations:
 (default)

Files:
  drawable\app_icon.png
    Src: () res\drawable\app_icon.png
  values\strings.xml
    Src: () res\values\strings.xml
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
  Type drawable
    drawable\app_icon.png
      Src: () res\drawable\app_icon.png
  Type values
    values\strings.xml
      Src: () res\values\strings.xml
Including resources from package: C:\Program Files (x86)\Android\android-sdk\platforms\android-23\android.jar
applyFileOverlay for drawable
applyFileOverlay for layout
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: res\drawable\app_icon.png
    (processed image res\drawable\app_icon.png: 94% size of source)
    (new resource id app_icon from drawable\app_icon.png #generated)
]

**Comment by rampara** [comment]
Did JarResolver library run and copy the required Google Play services components into your Unity project? You can check the `Assets/Plugins/Android` directory to see if Google Play services AAR files are present. You can also run JarResolver library manually from the `Assets->Google Play Services->Resolve Client Jars` menu option.

**Comment by rampara** [comment]
Closing issue due to non-response. If this issue persists, please re-open.
