### ISSUE TITLE
Frame rate drops on some older devices

### ISSUE THREAD

**Issue by faztp12** [googleads/googleads-mobile-unity#236]
When the Ad is being loaded, there is some significant frame drops on some older devices; It works flawlessly on powerful devices. Is there a way to load it on a background thread ? Peeked into the java-android part of this project and saw that loading is done on UIThread; (runOnUIThread(() => ) ?; not so familiar with java); 
Any help to make the load seamless is appreciated :)

**Comment by rampara** [comment]
Do you have a test app where you're able to reproduce the frame drops? Certain parts of the ad loading and displaying process must be performed on the UI thread and there currently isn't a way around that. But, optimizing the performance of the plugin is something that is important to us. If you have a test app I can use to reproduce the frame drops and give me an idea of the type of device you're using, I can investigate the performance issues.

**Comment by emdizzle** [comment]
I've noticed a frame rate drop as well when new ads are loaded. It seems that when the process is refreshing an ad, loading a new one in the background, is when the frame rates drop. This is especially noticeable on a game that is running at 60fps. I've been testing on an iPhone 7, so there shouldn't be any processing issues.

**Comment by rampara** [comment]
@emdizzle are you able to reproduce the frame rate drop in the sample application included in this repo? Are you noticing the frame drop for specific creative or for all ads?

**Comment by emdizzle** [comment]
@rampara I just looked at the sample apps, I thought the "Roll-A-Ball" sample would be good. I loaded it up but there is nothing on the MainScene. Is there another sample app that you would recommend?

**Comment by lawjeremy** [comment]
I am having a similar problem. Im a Unity noob, so I may be something in my code causing the problem, but my game runs smooth when I remove the ads. With the ads in its very choppy. I am testing on an older device (iPad 2 on iOS 9) but I don't that explains this poor performance. I'll install the sample application tonight and see if I can replicate the frame rate drop with it.

**Comment by rampara** [comment]
@lawjeremy are you still experiencing frame rate drops with the latest version of the plugin and GMA iOS SDK?

**Comment by rampara** [comment]
Closing issue as all ad rendering is performed by the Google Mobile Ads SDK. SDK issues can be raised on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
