### ISSUE TITLE
AndroidJavaException: java.lang.IllegalAccessError on RewardedAd loading

### ISSUE THREAD

**Issue by questionabledev** [googleads/googleads-mobile-unity#2367]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.39f1
  * Google Mobile Ads Unity plugin version: 7.3.0
  * Platform: Android
  * Platform OS version: Android 11
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: None

#### Steps to reproduce:

We updated the plugin from version 6.1.2 to 7.3.0

After the update an error started occurring when trying to load `RewardedAd`

Error log:
```
2022.11.01 13:33:21.324 24736 24736 Error AndroidRuntime java.lang.IllegalAccessError: Field 'com.google.unity.ads.UnityRewardedAd.activity' is inaccessible to class 'com.google.unity.ads.UnityRewardedAd$1'
2022.11.01 13:33:21.324 24736 24736 Error AndroidRuntime 	at com.google.unity.ads.UnityRewardedAd$1.run(UnityRewardedAd.java:59)
2022.11.01 13:33:21.324 24736 24736 Error AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:938)
2022.11.01 13:33:21.324 24736 24736 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:99)
2022.11.01 13:33:21.324 24736 24736 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:260)
2022.11.01 13:33:21.324 24736 24736 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8260)
2022.11.01 13:33:21.324 24736 24736 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2022.11.01 13:33:21.324 24736 24736 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
2022.11.01 13:33:21.324 24736 24736 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

**Comment by NVentimiglia** [comment]
@questionabledev Can you try removing the GoogleMobileAds plugin , including the plugins directory, and installing it again?

If that does work, can you provide a minimal sample application, or provide additional details on your environment so I can look into replicating this issue on my end?

**Comment by questionabledev** [comment]
Reinstalling the plugin didn't work. I'm afraid I cannot provide a sample application right now. What kind of environment information do you need?

**Comment by questionabledev** [comment]
The problem has been resolved after we updated Unity Editor to version 2021.3.13f1
