### ISSUE TITLE
Always seen "OnRewarded Toast on Video Done

### ISSUE THREAD

**Issue by kenglou** [googleads/googleads-mobile-unity#237]
Can i disable the Toast?

**Comment by rampara** [comment]
Are you seeing this toast for all rewarded video ads or just ads from a specific network? Are you seeing the toasts on Android or iOS?

**Comment by kenglou** [comment]
Hi,

I found this problem in previous 3.0.3 plugins. in 3.0.4 it's gone. No problem now.
Thank you.
