### ISSUE TITLE
Cannot build when disable Bitcode

### ISSUE THREAD

**Issue by KrKgg** [googleads/googleads-mobile-unity#2381]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.13f
  * Google Mobile Ads Unity plugin version: v7.3.0
  * Platform: IOS
  * Platform OS version: IOS, Xcode 14.1
  * Mediation ad networks used, and their versions: 
1. Meta 3.9.0
2. AppLovin 6.4.1
3. Unity Ads 3.4.1

#### Steps to reproduce:

With Xcode 14, I have added Firebase, and when the build is asked to Disable Bitcode, but when I build with ENABLE_BITCODE = NO in Unity_Iphone and UnityFrameworks, I am getting the error as shown below.

<img width="247" alt="Screenshot 2022-10-31 at 00 06 04" src="https://user-images.githubusercontent.com/13317332/200894706-88283c9e-d553-4f72-8e67-9b8049e0e40f.png">

**Comment by NVentimiglia** [comment]
Thanks @KrKgg

I will look into this and get back to you.

**Comment by PowZone** [comment]
- Unity version: 2021.3.14f
- Google Mobile Ads Unity plugin version: v7.3.1
- Platform OS version: IOS, Xcode 14.1

Similar issue here. Project doesn't compile if I disable bitcode to avoid this error:

'/.../unity-plugin-library.a(GADPAIDIdentifier.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/.../unity-plugin-library.a' for architecture arm64

**Comment by PowZone** [comment]
I solved using this tutorial:
http://shobhitsamaria.com/cocoapods-installation-failure-while-building-unity-project-for-ios/

My problems were:
- cocoapods for M1: I had to uninstall and reinstall 
- I was opening the xcodeproj instead of the xcworkspace

**Comment by Nyankoo** [comment]
We're running into the same issue with these errors:

error build: Undefined symbol: _kGADAdLoaderAdTypeNative
error build: Undefined symbol: _kGADAdSizeBanner
error build: Undefined symbol: _kGADSimulatorID

**Comment by NVentimiglia** [comment]
Fixed in the latest release (8.0.0).
