### ISSUE TITLE
Unity Native Ad Example

### ISSUE THREAD

**Issue by demirersin** [googleads/googleads-mobile-unity#239]
Anybody can give an example about Native Ads on Unity Admob SDK ? 

Received error HTTP response code: 403 ( or 400)
What does this error meaining ?

**Comment by rampara** [comment]
Are you referring to custom native template ads?

**Comment by demirersin** [comment]
Yes. I am referring  Custom Native Template Ads. Can you give an Example. And what is that errors ;
"Received error HTTP response code: 403 ( or 400)"

**Comment by Russel1** [comment]
Is Native Ads supported by Unity AdMob SDK? I can't see this on admob documentation.

**Comment by rampara** [comment]
[Custom native template](https://firebase.google.com/docs/admob/android/games#doubleclick_for_publishers_support) ads are supported by the Google Mobile Ads Unity plugin. A sample application for custom native template ads will be up soon.

**Comment by rampara** [comment]
Commit 73695ae5aa583329cb2c6768a545a4626c838c2c added a sample application for custom native template ads.

**Comment by herbou** [comment]
https://github.com/herbou/UnityAdmobUnifiedNativeAd

Video tutorial:
https://youtu.be/M-XdptsCWtQ
