### ISSUE TITLE
Unable to merge manifest

### ISSUE THREAD

**Issue by michaeljoshua55555** [googleads/googleads-mobile-unity#240]
I am using android native plugin
and googleads-mobile unity in my project

I am not able to build currently: 
This is the error i am getting in the console

Error building Player: CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
C:\Program Files\Java\jdk1.8.0_65\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Program Files (x86)/Android/android-sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\unity5.3.4\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Error: [Temp\StagingArea\AndroidManifest-main.xml:8, D:\Unity5Projects\34HammerTrumpv1\Temp\StagingArea\android-libraries\play-services-basement-9.0.2\AndroidManifest.xml:5] Trying to merge incompatible /manifest/application/meta-data[@name=com.google.android.gms.version] element:
  <meta-data
      @android:name="com.google.android.gms.version"
--    @android:value="8487000">
  <meta-data
      @android:name="com.google.android.gms.version"
++    @android:value="@integer/google_play_services_version">
]
stdout[
[Temp\StagingArea\AndroidManifest-main.xml:8, D:\Unity5Projects\34HammerTrumpv1\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\AndroidManifest.xml:11] Skipping identical /manifest/application/meta-data[@name=com.google.android.gms.version] element.
[Temp\StagingArea\AndroidManifest-main.xml, D:\Unity5Projects\34HammerTrumpv1\Temp\StagingArea\android-libraries\play-services-ads-lite-9.0.2\AndroidManifest.xml:10] Skipping identical /manifest/application/activity[@name=com.google.android.gms.ads.AdActivity] element.
]

**Comment by rampara** [comment]
It looks like you're trying to use different versions of Google Play Services together. Can you use SDK manager to ensure that all of the Google Play Services you are using are updated to the latest version.

**Comment by rampara** [comment]
Closing issue due to non-response. If this issue persists, please re-open.
