### ISSUE TITLE
Unity 5 google admobs android banner and interstitial not shown in device whet built ..

### ISSUE THREAD

**Issue by nothingbuthappend** [googleads/googleads-mobile-unity#241]
hello guys I have a trouble about admob since a week .
first I donloaded admob plugins from googleads/googleads-mobile-unity

then opened play servicesresolver right click selected then check resolve client jar in editor wrote succesfully done .
used this script for singleton .

using UnityEngine;
using System.Collections;
using System;
using GoogleMobileAds.Api;

public class ReklamScript : MonoBehaviour
{
private static ReklamScript instance = null;

public string bannerID;
public string interstitialID;

public bool testMod = false;
public string testDeviceID;

private BannerView bannerReklam;
private InterstitialAd interstitialReklam;

void Awake()
{
    if( instance == null )
    {
        instance = this;
        DontDestroyOnLoad( this );
    }
    else if( this != instance )
    {
        Destroy( gameObject );
        return;
    }
}

void Start()
{
    if( this != instance )
        return;

    BannerReklamAl();
    InterstitialReklamAl();
}

void BannerReklamAl()
{
    bannerReklam = new BannerView( bannerID, AdSize.SmartBanner, AdPosition.Top );

    AdRequest reklamiAl;
    if( testMod )
        reklamiAl = new AdRequest.Builder().AddTestDevice( AdRequest.TestDeviceSimulator )
            .AddTestDevice( testDeviceID ).Build();
    else
        reklamiAl = new AdRequest.Builder().Build();

    bannerReklam.LoadAd( reklamiAl );
    bannerReklam.Hide();
}

void InterstitialReklamAl()
{
    if( interstitialReklam != null )
        interstitialReklam.Destroy();

    interstitialReklam = new InterstitialAd( interstitialID );
    interstitialReklam.OnAdClosed -= InterstitialDelegate;
    interstitialReklam.OnAdClosed += InterstitialDelegate;

    AdRequest reklamiAl;
    if( testMod )
        reklamiAl = new AdRequest.Builder().AddTestDevice( AdRequest.TestDeviceSimulator )
            .AddTestDevice( testDeviceID ).Build();
    else
        reklamiAl = new AdRequest.Builder().Build();

    interstitialReklam.LoadAd( reklamiAl );
}

public void InterstitialDelegate( object sender, EventArgs args )
{
    InterstitialReklamAl();
}

/*void OnGUI()
{
    if( GUI.Button( new Rect( Screen.width / 2 - 150, 0, 300, 150 ), "Banner Goster" ) )
        ReklamScript.BannerGoster();

    if( GUI.Button( new Rect( Screen.width / 2 - 150, 150, 300, 150 ), "Banner Gizle" ) )
        ReklamScript.BannerGizle();

    if( GUI.Button( new Rect( Screen.width / 2 - 150, 300, 300, 150 ), "Interstitial Goster" ) )
        ReklamScript.InsterstitialGoster();
}
*/

public static void BannerGoster()
{
    if( instance == null )
        return;

    if( instance.bannerReklam == null )
        instance.BannerReklamAl();

    instance.bannerReklam.Show();
}

public static void BannerGizle()
{
    if( instance == null )
        return;

    if( instance.bannerReklam == null )
        return;

    instance.bannerReklam.Hide();
}

public static void InsterstitialGoster()
{
    if( instance == null )
        return;

    if( instance.interstitialReklam == null )
        instance.InterstitialReklamAl();

    instance.StopCoroutine( instance.InsterstitialCoroutine() );
    instance.StartCoroutine( instance.InsterstitialCoroutine() );
}

IEnumerator InsterstitialCoroutine()
{
    while( !interstitialReklam.IsLoaded() )
        yield return null;

    interstitialReklam.Show();
}

}

I am calling banner with ReklamScript.BannerGoster ();
here is android manifest

package="com.google.unity"
android:versionName="1.0"
android:versionCode="1">
android:targetSdkVersion="19" />

android:value="@integer/google_play_services_version" />

android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
android:theme="@android:style/Theme.Translucent" />

android:theme="@style/Theme.IAPTheme"/>

in editor succesfully loading ads .displaying dummy load ad ,etc.
but when I built to my device and boom.
there is no ads?
guys ı finished my app since 10 days but cant implementing ads to my game ..
PLS Any help will be appreciated .

**Comment by rampara** [comment]
Do you have any output in logcat under the "Ads" or "Unity" tags that indicates the cause of ads not loading?

**Comment by nothingbuthappend** [comment]
hello again sir.I have android studio that installed .my device plugged to dekstop in my  android studio
there is small icon at bottom left named logcat.over it my device shown. 
but how can I see logcat about google admob I dont know.

**Comment by nothingbuthappend** [comment]
06-27 16:26:48.158 10142-10154/? E/MessageFilterUtils: com.sec.chaton#flipboard.app#com.android.contacts#com.android.server.telecom#com.android.email#com.google.android.gm#com.android.vending#com.android.mms#com.google.android.youtube#com.android.incallui#com.android.calendar#com.android.phone#com.google.android.apps.plus#com.google.android.talk#com.whatsapp
06-27 16:26:48.158 10142-10154/? E/MessageFilterUtils: com.google.android.gm
06-27 16:26:48.158 10142-10154/? E/MessageFilterUtils: com.google.android.youtube
06-27 16:26:48.158 10142-10154/? E/MessageFilterUtils: com.google.android.apps.plus
06-27 16:26:48.158 10142-10154/? E/MessageFilterUtils: com.google.android.talk
06-27 16:26:51.268 12789-12900/? E/GmsUtils: Failed to connect to Google API client: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
06-27 16:26:51.438 12789-12910/? E/GmsUtils: Failed to connect to Google API client: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
                                             contents_sample_state: [ agr({[5 ,3]=1, [1 ,1]=1, [1]=168, [1 ,5 ,28]=91, [1 ,1 ,5]=4, [1 ,1 ,5 ,28]=9, [5]=13, [1 ,28]=16, [1 ,5 ,28 ,28]=1, [28]=2, [5 ,28]=1, [3 ,5 ,28]=2, [3]=7, [1 ,5]=85})  ]
06-27 16:26:52.868 12789-12933/? E/GmsUtils: Failed to connect to Google API client: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}

**Comment by nothingbuthappend** [comment]
06-27 16:29:13.599 12766-13976/? I/GAv4: Google Analytics 8.4.87 is starting up. To enable debug logging on a device run:
                                           adb shell setprop log.tag.GAv4 DEBUG
                                           adb logcat -s GAv4
06-27 16:29:16.549 14019-14019/? I/GAv4: Google Analytics 8.4.87 is starting up. To enable debug logging on a device run:
                                           adb shell setprop log.tag.GAv4 DEBUG
                                           adb logcat -s GAv4

**Comment by nothingbuthappend** [comment]
06-27 16:29:09.689 776-881/? D/StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{f1f5c91 u0 d0 com.sirius.zombierising/com.unity3d.player.UnityPlayerActivity}
06-27 16:29:10.349 1859-1859/? I/cm.log.servpro: [forcestop_listener][D]/  onAccessibilityEvent com.unity3d.player.UnityPlayerActivity, mListened = false
06-27 16:29:10.369 776-930/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{bfa17e6 u0 com.sirius.zombierising/com.unity3d.player.UnityPlayerActivity t9073} time:28096585
06-27 16:29:10.659 13819-13883/? I/AppsFlyer_1.18: WARNING:checkPlatform Not Built using Unity 22.
06-27 16:29:10.869 776-881/? D/StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{f1f5c91 u0 d0 com.sirius.zombierising/com.unity3d.player.UnityPlayerActivity}
06-27 16:29:13.839 13702-13808/? I/AppsFlyer_1.18: WARNING:checkPlatform Not Built using Unity 22.

**Comment by nothingbuthappend** [comment]
what its mean =?

**Comment by rampara** [comment]
Can you run the command listed below to limit logcat output to the "Ads" and "Unity" tags.

`adb logcat Unity:* Ads:* *:S`

**Comment by nothingbuthappend** [comment]
I can probaly look it tomorrow..:(
Now im at home.and computer must stay in business.
Thx very much .

**Comment by nothingbuthappend** [comment]
I ran with this command line then  gives very long list that seems There is no kind of description about unity and ads  .I can not explain what is the problem?
06-28 14:40:50.610  8975  9060 I Unity   :
06-28 14:40:50.610  8975  9060 I Unity   : (Filename: ./artifacts/generated/comm
on/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
06-28 14:40:50.610  8975  9060 I Unity   :

**Comment by rampara** [comment]
You can use the `adb logcat -c` command to clear logcat history before running through your Unity app. This should reduce logcat content. Are you also having trouble getting ads with the [sample application](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld)?

**Comment by nothingbuthappend** [comment]
WHen I tried tu built my apk to my device failed.in unity editor says 
Error building Player: CommandInvokationFailure: Unable to install APK to device. Please make sure the Android SDK is installed and is properly configured in the Editor. See the Console for more details. 
C:/Users/dell/AppData/Local/Android/sdk\platform-tools\adb.exe -s "0c508379" install -r "C:\Users\dell\Documents\le petit prince\Temp\StagingArea\Package.apk"

stderr[

]
stdout[
[  0%] /data/local/tmp/Package.apk

**Comment by Everest1986** [comment]
Hi All, 
I have similar problem please find my log below. Could anybody help me?  Whole week i try to figure it out. 

> **Banner:**
> I/Ads     (16645): Starting ad request.
> 
> I/Ads     (16645): Use AdRequest.Builder.addTestDevice("17F2B8177B4B56D0B45Z78C2D204D7BC") to get test ads on this device.
> 
> W/Ads     (16645): There was a problem getting an ad response. ErrorCode: 0
> 
> W/Ads     (16645): Failed to load ad: 0
> 
> I/Unity   (16645): HandleFailedToReceiveAd event received with message: Internal error
> 
> I/Unity   (16645): UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
> 
> I/Unity   (16645): UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> 
> I/Unity   (16645): UnityEngine.Logger:Log(LogType, Object)
> 
> I/Unity   (16645): UnityEngine.Debug:Log(Object)
> 
> I/Unity   (16645): UnityEngine.MonoBehaviour:print(Object) (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineMonoBehaviourBindings.gen.cs:106)
> 
> I/Unity   (16645): GoogleMobileAdsDemoScript:HandleAdFailedToLoad(Object, AdFailedToLoadEventArgs) (at G:\Admob\Assets\samples\HelloWorld\Assets\GoogleMobileAdsDemoScript.cs:253)
> 
> I/Unity   (16645): GoogleMobileAds.Api.BannerView:<BannerView>m__8(Object, AdFailedToLoadEventArgs) (at G:\Admob\Assets\GoogleMobileAds\Api\BannerView.cs:45)
> 
> I/Unity   (16645): GoogleMobileAds.Android.BannerClient:onAdFailedToLoad(String) (at G:\Admob\Assets\GoogleMobileAds\Platforms\Android\BannerClient.cs:86)
> 
> I/Unity   (16645): System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
> 
> I/Unity   (16645): System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[
> 
> E/Ads     (12275): Failed to connect to https://googleads.g.doubleclick.net/pagead/drt/m. No DSID retrieved.
> 
> 
> 
> **Interstitial:**
> I/Ads     (16645): Starting ad request.
> 
> I/Ads     (16645): Use AdRequest.Builder.addTestDevice("17F2B8177B4B56D0B45Z78C2D204D7BC") to get test ads on this device.
> 
> W/Ads     (16645): There was a problem getting an ad response. ErrorCode: 0
> 
> W/Ads     (16645): Failed to load ad: 0
> 
> I/Unity   (16645): HandleInterstitialFailedToLoad event received with message: Internal error
> 
> I/Unity   (16645): UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
> 
> I/Unity   (16645): UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> 
> I/Unity   (16645): UnityEngine.Logger:Log(LogType, Object)
> 
> I/Unity   (16645): UnityEngine.Debug:Log(Object)
> 
> I/Unity   (16645): UnityEngine.MonoBehaviour:print(Object) (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineMonoBehaviourBindings.gen.cs:106)
> 
> I/Unity   (16645): GoogleMobileAdsDemoScript:HandleInterstitialFailedToLoad(Object, AdFailedToLoadEventArgs) (at G:\Admob\Assets\samples\HelloWorld\Assets\GoogleMobileAdsDemoScript.cs:287)
> 
> I/Unity   (16645): GoogleMobileAds.Api.InterstitialAd:<InterstitialAd>m__12(Object, AdFailedToLoadEventArgs) (at G:\Admob\Assets\GoogleMobileAds\Api\InterstitialAd.cs:44)
> 
> I/Unity   (16645): GoogleMobileAds.Android.InterstitialClient:onAdFailedToLoad(String) (at G:\Admob\Assets\GoogleMobileAds\Platforms\Android\InterstitialClient.cs:99)
> 
> I/Unity   (16645): System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
> 
> I/Unity   (16645): System.Reflection.MonoMethod:In
> 
>

**Comment by rampara** [comment]
@Everest1986 are you unable to receive test ads with the sample application from this repository?

**Comment by rampara** [comment]
@Everest1986 Using the code from your post above, I'm able to request and display ads without issue. Can you post a Charles log of your ad request? It may help narrow down what's causing the issue you're seeing.

**Comment by Everest1986** [comment]
I don't know why but it working now :P  Thank you for your time.

**Comment by Everest1986** [comment]
Funny thing when I use Charles and set proxy setting (8888) on device I see adds on my device. Unfortunately when I use 4G or my standard network without proxy setting I have network error.

**Comment by rampara** [comment]
Glad you were able to get it working.

**Comment by ChaimHong** [comment]
Hi All,
I have similar problem please find my log below. Could anybody help me? Whole week i try to figure it out.

`I/Ads: Starting ad request.
I/Ads: No fill from ad server.
W/Ads: Failed to load ad: 3
I/Unity: HandleNativeExpressAdFailedToReceiveAd event received with message: No fill
         
         (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
D/AdsUnity: Calling destroy() on NativeExpressAdView
I/Ads: Starting ad request.
W/Ads: There was a problem getting an ad response. ErrorCode: 0
W/Ads: Failed to load ad: 0
I/Unity: HandleRewardBasedVideoFailedToLoad event received with message: Internal error
         
         (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)`

when i click the native ads / rewardedvideo !

**Comment by rampara** [comment]
@ChaimHong Are banners and interstitials loading correctly for you or do all ad formats fail to load?

**Comment by Everest1986** [comment]
@ChaimHong  Did you use some Xiaomi device to test ads ?

**Comment by ChaimHong** [comment]
@rampara just interstitials/rewardvideo fail

**Comment by ChaimHong** [comment]
@rampara @Everest1986 now all ad formats success to load

**Comment by rampara** [comment]
Glad you were able to get everything working.

**Comment by bee0806** [comment]
hello there i have similar problem too. All of the ads fail to load. I've already test the sample application from this repository, but the result is same. the ads didn't show. here is my logcat :

> I/Ads     (10554): Use AdRequest.Builder.addTestDevice("6D1C6289F7A2F34B0B0E8C8938B79C43") to get test ads on this device.
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
W/Ads     (21552): Timed out waiting for ad response.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
W/Ads     (21552): Failed to load ad: 2
W/Ads     (10554): Timed out waiting for ad response.
I/Ads     (10554): Scheduling ad refresh 60000 milliseconds from now.
W/Ads     (10554): Failed to load ad: 2
I/Unity   (10554): HandleFailedToReceiveAd event received with message: Network Error
I/Unity   (10554):  
I/Unity   (10554): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
I/Unity   (10554): 
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
I/Ads     (10554): Starting ad request.
I/Ads     (10554): Use AdRequest.Builder.addTestDevice("6D1C6289F7A2F34B0B0E8C8938B79C43") to get test ads on this device.
I/Ads     (10554): Starting ad request.
I/Ads     (10554): Use AdRequest.Builder.addTestDevice("6D1C6289F7A2F34B0B0E8C8938B79C43") to get test ads on this device.
I/Unity   (10554): Interstitial is not ready yet
I/Unity   (10554):  
I/Unity   (10554): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
I/Unity   (10554): 
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
I/Ads     (21552): Ad is not visible. Not refreshing ad.
I/Ads     (21552): Scheduling ad refresh 60000 milliseconds from now.
W/Ads     (10554): Timed out waiting for ad response.
I/Ads     (10554): Scheduling ad refresh 60000 milliseconds from now.
W/Ads     (10554): Failed to load ad: 2
I/Unity   (10554): HandleFailedToReceiveAd event received with message: Network Error
I/Unity   (10554):  
I/Unity   (10554): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

**Comment by rampara** [comment]
@bee0806 You seem to be running into network errors. Does the device you're testing with have full network connectivity?

**Comment by bee0806** [comment]
@rampara so the problem is the network. i wonder, does admob need strong network connection?. my network working fine with browsing and downloading or it just need stable connection?.

**Comment by rampara** [comment]
The likely cause of the error you'e seeing is a timeout in receiving an ad response from the AdMob ad server. This timeout is probably more aggressive than the ones used by the apps you're using for browsing.

**Comment by bee0806** [comment]
thanks @rampara it make me clear now. i'll check it out and try it with other connection. thanks for the supports.

**Comment by rampara** [comment]
Glad to be of help.
