### ISSUE TITLE
OnAdRewarded don't use

### ISSUE THREAD

**Issue by OleksiyMukhnyak** [googleads/googleads-mobile-unity#242]
I use google plugin 3.0.4 with Unity 5.3.5f1 and standard GoogleMobileAdsDemoScript cs. I create "debug" UI text and show there all AdMob event (OnAdLoaded, OnAdFailedToLoad, OnAdOpening...) in Android build. But OnAdRewarded never use. Help me.
AdMob account:
![image](https://cloud.githubusercontent.com/assets/11583903/16455664/d7c2638c-3e1d-11e6-8a08-82454866c3f7.png)
![image](https://cloud.githubusercontent.com/assets/11583903/16455712/04852ec2-3e1e-11e6-96b8-d99a2786d264.png)
Code:
![image](https://cloud.githubusercontent.com/assets/11583903/16455765/349cf9aa-3e1e-11e6-9990-035842d485e3.png)
![image](https://cloud.githubusercontent.com/assets/11583903/16455791/5112e856-3e1e-11e6-8969-de283e972abc.png)

**Comment by rampara** [comment]
I'm having trouble reproducing this issue. Can you provide a test app I can use to reproduce it?

**Comment by rio900** [comment]
when OnAdRewarded  must call?

**Comment by OleksiyMukhnyak** [comment]
After 30 min, when I add Chartboost to Rewarded interstitial, video don't load (always failed load). 

![](https://cloud.githubusercontent.com/assets/11583903/16455712/04852ec2-3e1e-11e6-96b8-d99a2786d264.png)

**Comment by rampara** [comment]
I tried doing a quick test with the sample project from the GitHub link above. The rewarded interstitial ad unit from the sample does not seem to be receiving any fill from Chartboost. I used a test ad unit was able to receive Chartboost rewarded interstitials without issue. The OnRewarded ad event was also invoked as expected, upon video completion. To troubleshoot, I would start by ensuring the configuration options used for Chartboost are correct.

**Comment by OleksiyMukhnyak** [comment]
I need enter field "Ad location"?
![image](https://cloud.githubusercontent.com/assets/11583903/16486734/4d8fdb6a-3ecf-11e6-85d8-8e4790f23c87.png)

**Comment by rampara** [comment]
The "Ad Location" field doesn't seem to be required. Are you sure the "App ID" and "App Signature" field you are using are valid?

**Comment by OleksiyMukhnyak** [comment]
![image](https://cloud.githubusercontent.com/assets/11583903/16487951/9afa17b0-3ed6-11e6-93bb-3aa3c5c377bd.png)
![image](https://cloud.githubusercontent.com/assets/11583903/16487988/c56f756c-3ed6-11e6-90f7-6bc07542d4b9.png)
I need use Test Mode in Chartboost?

**Comment by rampara** [comment]
Checking if you can receive test ads will be a good place to start.

**Comment by jordidc** [comment]
Same error here, using the sample app with my ad-unit.

Only see OnAdLoaded, OnAdOpening, OnAdClosed events, never OnAdRewarded one.

![adunit](https://cloud.githubusercontent.com/assets/22094205/18379830/c8d847b2-7674-11e6-8836-e8c65a7e8c2f.png)

**Comment by rampara** [comment]
@jordidc Which third-party ad network are you receiving rewarded video ads from?

**Comment by jordidc** [comment]
I have more than one ad network. There is any way to check wich one is giving me the video or it's better to test each one separetely?

**Comment by rampara** [comment]
The easiest way would be to test separately. Unless the ad creative clearly indicates the ad network the ad is from.

**Comment by jordidc** [comment]
@rampara For the ad creative seems that the video is from adMob.


![screenshot_2016-09-22-10-37-32](https://cloud.githubusercontent.com/assets/22094205/18741888/ca64859a-80b1-11e6-8421-3ea54eb4e17d.png)

**Comment by rampara** [comment]
Closing as this issue has now been fixed.
