### ISSUE TITLE
SSV callback not called for UnityAds rewarded ads

### ISSUE THREAD

**Issue by binouze** [googleads/googleads-mobile-unity#2428]
### [REQUIRED] Step 1: Describe your environment

* Unity version: 2021.3.12f1
* Google Mobile Ads Unity plugin version: 7.3.1
* Platform: iOS/Android
* Platform OS version: iOS 16 / Android 11
* Any specific devices issue occurs on: All devices tested
* Mediation ad networks used, and their versions:
  - Unity Ads Unity Mediation Plugin 3.4.1
  - AdColony Unity Mediation Plugin 2.6.0
  - AppLovin Unity Mediation Plugin 6.4.2
  - Vungle Unity Mediation Plugin 3.9.0

### [REQUIRED] Step 2: Describe the problem

After playing rewarded Ad, the SSV callback is not called for UnityAds ads, 
all other networks calls the SSV callback once the video is complete but not Unity.

#### Steps to reproduce:

 - Set an SSV callback for your adUnit
 - Using the test tools set Unity as single ad test source.
 - Play a rewarded video.
 - no SSV callback called...

#### Note:
I don't think it's a code issue on my side as all other networks get the callback at the end of the video.

**Comment by binouze** [comment]
Hi, 
Just see that the OnPaidEvent is not called for UnityAds too.
Maybe related ?

**Comment by binouze** [comment]
Hi,
When not using a test device, all is working as expected.
Any way to get it work in test mode ?

**Comment by NVentimiglia** [comment]
Hi @binouze,

I was not able to replicate this initially, and looking into getting a second opinion. I will update you on this issue soon.
