### ISSUE TITLE
GADPAIDIdentifier.o / Bitcode compilation problem

### ISSUE THREAD

**Issue by PowZone** [googleads/googleads-mobile-unity#2431]
- Unity version: 2021.3.14f
- Google Mobile Ads Unity plugin version: v7.3.1
- Platform OS version: IOS, Xcode 14.1

I used this guide as reference to setup the project:
https://developers.google.com/admob/ios/quick-start?hl=en-US#import_the_mobile_ads_sdk

But after this setup I still get the following error:

**'/.../unity-plugin-library.a(GADPAIDIdentifier.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/.../unity-plugin-library.a' for architecture arm64**

If I disable bitcode, as suggested in this message, many more errors appear

**Comment by dhamelin** [comment]
Bitcode under Xcode 14 is now deprecated, so you should start looking at your project without it.

Your issue is probably the same as: https://github.com/googleads/googleads-mobile-unity/issues/2381

**Comment by PowZone** [comment]
I solved using this tutorial:
http://shobhitsamaria.com/cocoapods-installation-failure-while-building-unity-project-for-ios/

My problems were:

- I had to set set Bitcode to NO
- cocoapods for M1: I had to uninstall and reinstall
- I was opening the xcodeproj instead of the xcworkspace
