### ISSUE TITLE
Undefined symbols for architecture arm64:   "_objc_msgSend$error", referenced from:       _GADUAdapterResponseInfoAdError in unity-plugin-library.a(GADUInterface.o)

### ISSUE THREAD

**Issue by shwuhk** [googleads/googleads-mobile-unity#2437]
* Unity version: 2020.3.15f2
  * Google Mobile Ads Unity plugin version: 7.3.1
  * Platform: iOS (iOS, Android, Unity Editor)
  * Platform OS version: iOS11 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: XCode 13.2.1
  * Mediation ad networks used, and their versions: Admob

A complete empty 2D unity project. Import Mobile Ads Unity plugin to the project, fill in the admob id and then export xcode project. It give the following error when build.
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/10464157/204153160-41c9c54d-1a4e-463d-ad94-06091265ccdf.png">

**Comment by AbelTeam** [comment]
I solved this version using source code.

https://github.com/googleads/googleads-mobile-unity/archive/refs/tags/v7.3.1.zip

[Some source code compilation issues need to be fixed.]
