### ISSUE TITLE
FBLPromises.framework does not contain bitcode - Xcode 14.1

### ISSUE THREAD

**Issue by dcosmin-97** [googleads/googleads-mobile-unity#2440]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.42f1
  * Google Mobile Ads Unity plugin version: 7.3.1
  * Platform: iOS
  * Mediation ad networks used, and their versions: AdColony 2.6.0, Applovin 6.4.3, Meta 3.9.0, Pangle 1.3.1, Vungle 3.9.0
  * Firebase 10.1.1
  

### [REQUIRED] Step 2: Describe the problem

When I want to build in Xcode 14.1, I get the following errors:
/Build/Products/ReleaseForRunning-iphoneos/PromisesObjC/FBLPromises.framework/FBLPromises(FBLPromise.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target
/Build/Products/ReleaseForRunning-iphoneos/PromisesObjC/FBLPromises.framework/FBLPromises' for architecture arm64

In pods I have everything with Enable Bitcode = NO

I have tried to follow the tutorial from here: https://stackoverflow.com/questions/72904371/fblpromises-framework-does-not-contain-bitcode-failing-build but it doesn't work.

I cannot download Xcode 13.x because of macOS Ventura

Has anyone found a solution?
Thank you!

![image](https://user-images.githubusercontent.com/66071707/204870432-e58fb8f0-5e4e-4726-ae43-704f00f37bd3.png)

**Comment by GAGOSIAN84** [comment]
I also encountered this error.
Select Unity-iPhone project not Pods.
set Enable Bitcode No to Unity-iPhone target and UnityFramework.

**Comment by mkprivates** [comment]
bitcode is deprecated. you can and should turn it off completely. It can be done via plist.

**Comment by AftabUfaq** [comment]
> bitcode is deprecated. you can and should turn it off completely. It can be done via plist.
> this feature won't be available in xcode 15

how can I disable this is info.plist  can you provide any example.


when I disable this in build.setting then app build successfully but it crashes on launch

**Comment by 3583Bytes** [comment]
I can't deploy any iOS builds anymore due to this error.  Setting Enable Bitcode to No or Yes or any combination does not seem to make the error go away.  Is there a fix for this?

**Comment by NVentimiglia** [comment]
Thanks for the workaround.

We will be handling bitcode differently in future releases.
