### ISSUE TITLE
Null Reference Exception on Android & iOS in LoadAdError.GetMessage()

### ISSUE THREAD

**Issue by mkprivates** [googleads/googleads-mobile-unity#2441]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.1f1
  * Google Mobile Ads Unity plugin version: GoogleMobileAds-v7.3.0
  * Platform: iOS, Android
  * Platform OS version: Android 12, iOS 15.7.1
  * Any specific devices issue occurs on: iPhone SE, Poco X3 Pro
  * Mediation ad networks used, and their versions: None

#### Steps to reproduce:

Import GoogleMobileAds-v7.3.0 into your project.
Subscribe to BannerView.OnAdFailedToLoad and in the subscribed method Debug.Log the result of this method LoadAdError.GetMessage() that is called on OnAdFailedToLoad event argument.
Ensure Thread safety.
Compile it onto Android & iOS
Make conditions so an ad doesn't load. (turn off your internet connection) 
Observe the result:

Android:
Null Reference Exception in IAdErrorClient inherited class.
iOS:
Thread 1: EXC_BAD_ACCESS (code=2, address=0x16fc77e80)
Application Crash.

#### Relevant Code:

```
    _bannerView = new BannerView(AdmobConstants.BannerAdUnitId, AdSize.Banner, AdPosition.Top);
    _bannerView.OnAdFailedToLoad += FailedToLoadHandler;
```

```
            private void FailedToLoadHandler(object sender, AdFailedToLoadEventArgs e)
            {
                YourUnityClass.ExecuteFromMainThread(() =>
                {
                    Debug.Log($"{e?.LoadAdError.GetMessage()}");
                });
            }

```

**Comment by NVentimiglia** [comment]
Hi @mkprivates thanks for raising awareness, I will look deeper into this issue. That said, here is a work around.

```
private void FailedToLoadHandler(object sender, AdFailedToLoadEventArgs e)
            {
                 string errorMessage = e?.LoadAdError.GetMessage();
                MobileEventsExecutor.ExecuteFromMainThread(() =>
                {
                    Debug.Log($"errorMessage");
                });
            }

```
Explanation is this could be a race condition related to releasing of resources in IOS.

**Comment by mkprivates** [comment]
> Platform: iOS, Android

No workaround, I provided that info to show that it fails even on main thread.

**Comment by bartutiryakioglu** [comment]
I am having the same issue when I tried to extract error message from load error => java.lang.Exception: NullReferenceException : Object reference not set to an instance of an object.
       at GoogleMobileAds.Api.AdapterResponseInfo.get_AdError(GoogleMobileAds.Api.AdapterResponseInfo)

Below is how I handle ad mob errors

`var errorInfo = error?.GetResponseInfo()?.GetLoadedAdapterResponseInfo();
                if (errorInfo?.AdError != null)
                {
                    Debug.Log($"Rewarded Load Failed {errorInfo.AdError?.GetCode()} {error.GetResponseInfo().GetResponseId()}");
                }`
Good amount of Android users are having this issue. Hope you could find a solution for this problem

**Comment by NVentimiglia** [comment]
Hi @bartutiryakioglu can you please confirm your plugin version and replication steps?

**Comment by bartutiryakioglu** [comment]
Hi Nicholas, I solved this problem by downgrading to 7.3.1. Thank you for
your reply.

**Comment by Hetagkaty** [comment]
How soon can we expect a fix?

**Comment by NVentimiglia** [comment]
Hi @Hetagkaty 

I posted a work around above.

**Comment by Hetagkaty** [comment]
> I posted a work around above.

I have version 7.4.1 with new API
And I am getting this error without even extracting the error message.

**Comment by NVentimiglia** [comment]
@Hetagkaty 

This error is cause by accessing a native object after it is disposed. This can be solved by making sure the object is accessed in the same frame as it is messaged.

```
private void FailedToLoadHandler(object sender, AdFailedToLoadEventArgs e)
            {
                string errorMessage = e.LoadAdError.GetMessage();
                // Code executed in this function are executed at a later time.
                // The native object may be cleaned up already, resulting in the null.
                MobileEventsExecutor.ExecuteFromMainThread(() =>
                {
                    Debug.Log(errorMessage);
                });
            }
```
