### ISSUE TITLE
[AppLovinSdk] Unable to find AppLovin SDK key

### ISSUE THREAD

**Issue by shefich** [googleads/googleads-mobile-unity#2448]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: every version
  * Google Mobile Ads Unity plugin version: every version
  * Platform: Android
  * Platform OS version: every version
  * Any specific devices issue occurs on: start

#### Steps to reproduce:

I added AppLovin Unity Mediation Plugin 6.4.3 and it has such error on the app start:

#### Relevant Code:

Error:
2022.12.06 17:39:46.850 26196 26196 Error AppLovinSdk [AppLovinSdk] Unable to find AppLovin SDK key. Please add  meta-data android:name="applovin.sdk.key" android:value="YOUR_SDK_KEY_HERE" into AndroidManifest.xml.
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk [AppLovinSdk] Called with an invalid SDK key from: java.lang.Throwable:
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.applovin.impl.sdk.n.a(Unknown Source:423)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.applovin.sdk.AppLovinSdk.getInstance(Unknown Source:105)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.applovin.sdk.AppLovinSdk.getInstance(Unknown Source:14)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.applovin.sdk.AppLovinSdk.getInstance(Unknown Source:5)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.applovin.sdk.AppLovinSdk.initializeSdk(Unknown Source:2)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.applovin.sdk.AppLovinSdk.initializeSdk(Unknown Source:1)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.unity3d.player.ReflectionHelper.nativeProxyInvoke(Native Method)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.unity3d.player.ReflectionHelper.a(Unknown Source:0)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.unity3d.player.ReflectionHelper$1.invoke(Unknown Source:29)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at $Proxy23.onInitializationComplete(Unknown Source)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.google.android.gms.ads.internal.client.zzec.zzb(com.google.android.gms:play-services-ads-lite@@21.3.0:8)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.google.android.gms.internal.ads.zzbrw.zzbI(com.google.android.gms:play-services-ads-lite@@21.3.0:3)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.google.android.gms.internal.ads.zzasa.onTransact(com.google.android.gms:play-services-ads-base@@21.3.0:3)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at android.os.Binder.transact(Binder.java:1200)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at [afj.be](http://afj.be/)(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:2)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.google.android.gms.ads.internal.initialization.f.e(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:0)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.google.android.gms.ads.nonagon.initialization.f.run(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:2)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at android.os.Handler.handleCallback(Handler.java:942)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at android.os.Handler.dispatchMessage(Handler.java:99)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at ass.a(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:0)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.google.android.gms.ads.internal.util.f.a(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:1)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at ass.dispatchMessage(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:0)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at android.os.Looper.loopOnce(Looper.java:226)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at android.os.Looper.loop(Looper.java:313)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at android.app.ActivityThread.main(ActivityThread.java:8741)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at java.lang.reflect.Method.invoke(Native Method)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
2022.12.06 17:39:46.851 26196 26196 Error AppLovinSdk

**Comment by NVentimiglia** [comment]
Hi @shefich 

This sounds like an AppLovinSDK issue and you may want to contact AppLovin for help with issue. That said, here are some tings you can try:

1. Make sure the AppLovin SDK is installed correctly using the External dependency manager (EDM)
2. Make sure all assets are resolved in the EDM using the menu ` Assets > External Dependency Manager > Android Resolver > Force Resolve`.
3. Make sure the `Plugins/Android/AndroidManifest.xml` file is configured  with the app lovin key as described by the error.

**Comment by shefich** [comment]
Hi @NVentimiglia 

As I understand Admob are initializing Applovin with the help of this code: "GoogleMobileAds.Api.Mediation.AppLovin.AppLovin.Initialize();" So it's your issue, not the AppLovin team.
Also your team had created this plugin: https://developers.google.com/admob/unity/mediation/applovin
I am using only it, no AppLovin SDK. 
The issue is pretty old: https://groups.google.com/g/google-admob-ads-sdk/c/CDidFx4TwIo

BTW. I tried and unferstand all the steps which you mentioned. None of them helps.

**Comment by shefich** [comment]
Ok, I think removing this line: "GoogleMobileAds.Api.Mediation.AppLovin.AppLovin.Initialize();" fixes the issue.
I placed it after Google Mobile Ads initialization and it gives the error.
I just don't understand where it should be?

**Comment by NVentimiglia** [comment]
Hi @shefich If you are not using AppLovin, please remove the AppLovin SDK and mediation adapter.

**Comment by shefich** [comment]
Hi @NVentimiglia, as I mentioned previously: "I am using plugin: https://developers.google.com/admob/unity/mediation/applovin
I am using only it, no AppLovin SDK."
And it gives the error. Also everything set up as described in your tutorial on setting up AppLovin mediation through Unity Admob. I mean keys, etc.

**Comment by NVentimiglia** [comment]
Hi @shefich 

1.  You still need to register with AppLovin to get the correct key. The AppLovin adapter is just that, an adapter. It connects our SDK with the AppLovin SDK. This assumes you have proper configurations setup for both networks.
2. Once you have the AppLovin SDK configured correctly, you can set up the AppLovin key [here](https://github.com/googleads/googleads-mobile-unity/blob/main/mediation/AppLovin/source/plugin/Assets/GoogleMobileAds/Editor/AppLovinPostProcessBuild.cs#L36)

**Comment by shefich** [comment]
Hi @NVentimiglia thank you for you message.
But as you can read the start of the topic, my platform is Android and you gave the link to the iOS Post Process script.
Regarding the first step, Of course i made all these, because my mediation group is wroking. The only issue is with this strange error. I am ttesting integration with the gesture on my phone and I can see AppLovin Adapter found and Initialized, I can see AppLovin ad and so on.

**Comment by NVentimiglia** [comment]
@shefich 

This issue seems pretty complex and may be out of the scope of what I can provide here. Please reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines). From there I will be able to provide better support and escalate to the mediation experts.

**Comment by sumitmangukiya** [comment]
Please add meta-data in Menifest File
         
         <meta-data
            android:name="applovin.sdk.key"
            android:value="Add Your Api Key" />

**Comment by og-abdul-mateen** [comment]
Did you find a solution for it?
