### ISSUE TITLE
MobileAds.Initialize() very slow after clearing the Google Play Services cache

### ISSUE THREAD

**Issue by RaulLpg** [googleads/googleads-mobile-unity#2449]
### [REQUIRED] Step 1: Describe your environment
  * Unity version: 2021.3.4f1
  * Google Mobile Ads Unity plugin version: 6.1.0 and 7.3.0
  * Platform: Android
  * Platform OS version: 6.0.1
  * Any specific devices issue occurs on: Sony Xperia Z3
  * Mediation ad networks used, and their versions: none
  * Extra: We are using admob through the EasyMobile plugin

#### Steps to reproduce:
- Go to phone settings -> Apps and find the Google Play Services
- Go to storeage
- Tap the "Clear cache" button and then "Manage storage"
- Tap "Clear all data"

After this, when I open the game which calls MobileAds.Initialize() kind of early in it's startup flow, I observe the mentioned very long initialization time. 

I added some debugging lines to measure the time MobileAds.Initialize() takes, and it is taking in the order of 10s + in the best cases.

This behaviour is not observed if I kill the app and open it again without clearing the Google Play Services app data/cache (or if I only clear my app's data/cache). In fact, my debugging code shows MobileAds.Initialize() takes less than 1s in this case.

Maybe this is the expected behaviour if Google Play Services app is caching the ads, so it makes sense for the initialization time to be higher after clearing it, but the problem is that the call to MobileAds.Initialize() this seems to be blocking the calling thread (the main unity thread in our case), despite having a callback.

Note that I did the same test in a more mother phone running Android 12 and I could not reproduce the issue.

Maybe this is a long shot and maybe this exact issue just occurs in very old devices, but it might be a lead to invesitgate further.

**Comment by NVentimiglia** [comment]
Hi @RaulLpg can you please try out the loading optimization beta ?

https://developers.google.com/admob/unity/optimize-initialization

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
