### ISSUE TITLE
[BUG] IOS-Builds failing with Google-Mobile-Ads-SDK 9.5.0 and greater

### ISSUE THREAD

**Issue by frankvHoof93** [googleads/googleads-mobile-unity#2453]
### Step 1: Describe your environment

  * Unity version: 2021.3.6f1
  * Google Mobile Ads Unity plugin version: 7.3.1
  * Platform: iOS (XCode) (iOS, Android, Unity Editor)
  * Platform OS version: N.A. (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: XCide
  * Mediation ad networks used, and their versions: Not Relevant

#### Steps to reproduce:

After updating AdMob to 7.3.1 (from 7.2.0) and EDM4U to 1.2.175 (from 1.2.171), and running a 'pod update', my app no longer builds in XCode. It now fails during building with an output of "XXX does not contain bitcode' for either the com.google.ads.mobile-plugin or the GoogleAppMeasurement-plugin.

Output of previous (working) pod install (all working versions):
Installing AdColony (4.9.0)
Installing AppLovinSDK (11.4.2)
Installing AppsFlyerFramework (6.5.4)
Installing FBAEMKit (11.2.1)
Installing FBSDKCoreKit (11.2.1)
Installing FBSDKCoreKit_Basics (11.2.1)
Installing FBSDKGamingServicesKit (11.2.1)
Installing FBSDKLoginKit (11.2.1)
Installing FBSDKShareKit (11.2.1)
Installing FacebookGamingServices (11.2.1)
Installing Google-Mobile-Ads-SDK (9.5.0)
Installing GoogleAppMeasurement (9.1.0)
Installing GoogleMobileAdsMediationAdColony (4.9.0.0)
Installing GoogleMobileAdsMediationAppLovin (11.4.2.0)
Installing GoogleMobileAdsMediationIronSource (7.2.2.1.0)
Installing GoogleMobileAdsMediationTapjoy (12.10.0.0)
Installing GoogleMobileAdsMediationUnity (4.2.1.0)
Installing GoogleUserMessagingPlatform (2.0.0)
Installing GoogleUtilities (7.7.0)
Installing IronSourceSDK (7.2.2.1)
Installing LegacyGamingServices (11.2.1)
Installing PromisesObjC (2.1.0)
Installing TapjoySDK (12.10.0)
Installing UnityAds (4.2.1)
Installing nanopb (2.30909.0)

Output of current (non-working) pod install (includes non-working versions):
Installing AdColony (4.9.0)
Installing AppLovinSDK (11.4.2)
Installing AppsFlyerFramework (6.5.4)
Installing FBAEMKit (11.2.1)
Installing FBSDKCoreKit (11.2.1)
Installing FBSDKCoreKit_Basics (11.2.1)
Installing FBSDKGamingServicesKit (11.2.1)
Installing FBSDKLoginKit (11.2.1)
Installing FBSDKShareKit (11.2.1)
Installing FacebookGamingServices (11.2.1)
Installing Google-Mobile-Ads-SDK (9.14.0)
Installing GoogleAppMeasurement (10.3.0)
Installing GoogleMobileAdsMediationAdColony (4.9.0.0)
Installing GoogleMobileAdsMediationAppLovin (11.4.2.0)
Installing GoogleMobileAdsMediationIronSource (7.2.2.1.0)
Installing GoogleMobileAdsMediationTapjoy (12.10.0.0)
Installing GoogleMobileAdsMediationUnity (4.2.1.0)
Installing GoogleUserMessagingPlatform (2.0.1)
Installing GoogleUtilities (7.10.0)
Installing IronSourceSDK (7.2.2.1)
Installing LegacyGamingServices (11.2.1)
Installing PromisesObjC (2.1.1)
Installing TapjoySDK (12.10.0)
Installing UnityAds (4.2.1)
Installing nanopb (2.30909.0)

It appears that any version of the GMA-SDK > 9.5.0 and any version of the GoogleAppMeasurement >= 9.5.0 are failing due to missing bitcode.

Error-Logs:

'/Users/jenkins/Desktop/RogueLikeTestBuild/Libraries/com.google.ads.mobile/Plugins/iOS/unity-plugin-library.a(GADPAIDManager.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/jenkins/Desktop/RogueLikeTestBuild/Libraries/com.google.ads.mobile/Plugins/iOS/unity-plugin-library.a' for architecture arm64

'/Users/jenkins/Library/Developer/Xcode/DerivedData/Unity-iPhone-fzhjdsnpncqtmwanqwqpjsxduvvm/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurement/WithoutAdIdSupport/GoogleAppMeasurement.framework/GoogleAppMeasurement(APMAdExposureReporter.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/jenkins/Library/Developer/Xcode/DerivedData/Unity-iPhone-fzhjdsnpncqtmwanqwqpjsxduvvm/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurement/WithoutAdIdSupport/GoogleAppMeasurement.framework/GoogleAppMeasurement' for architecture arm64

**Comment by NVentimiglia** [comment]
Confirmed, I will push for a fix.

**Comment by joaoborks** [comment]
As a workaround, you could try to temporarily disable bitcode for iOS. However, you might get into the issue described as #2450 as well. Maybe try both workarounds?

**Comment by HAL-JP** [comment]
Bitcode was removed in the GoogleAppMeasurement 10.1.0 release because it is no longer supported by Xcode 14.

It's recommended to remove bitcode from your Build Settings.

If you still want to use bitcode in an Xcode 13 build, stick with an earlier Firebase release.
