### ISSUE TITLE
Admob 7.3.0 crashes after loading or before watching ads

### ISSUE THREAD

**Issue by henry-dreamo** [googleads/googleads-mobile-unity#2454]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.14f1
  * Google Mobile Ads Unity plugin version: 7.3.0
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: 
![image](https://user-images.githubusercontent.com/88139855/207805317-64be3936-5cbe-4414-9d86-9991b702cc5a.png)
  * Any specific devices issue occurs on: moto e⁶ plus, Xperia L1
  * Mediation ad networks used, and their versions: None

#### Steps to reproduce:

When receiving a callback that an interstitial or reward ad has been loaded, or when attempting an exposure, the following crash message is received.

![image](https://user-images.githubusercontent.com/88139855/207805117-370d61ea-3fa9-4f53-8f93-9206499c22db.png)

This problem has been going on for more than 5 months, I would like to know if it is a memory issue, is it related to the garbage collector, or is it due to some other reason?

**Comment by NVentimiglia** [comment]
Hi @henry-dreamo 

Can you provide any more details? Specifically something which tracks back to Admob?

I did a quick audit of our Android code where Dictionary is used. I found a number of places where we create and populate a dictionary, but found no calls to Remove().

**Comment by henry-dreamo** [comment]
Hi @NVentimiglia 

The last log before the crash was related to AdMob.
Since I couldn't see the Android native code, I thought Admob was the most likely option.
If Admob can't find the corresponding call stack, it's a different issue.
I'll close the issue. thank you.
