### ISSUE TITLE
Gradle build failed: Failed to transform googlemobileads-unity-.aar to match attributes {artifactType=android-manifest, org.gradle.status=integration}

### ISSUE THREAD

**Issue by Ragethunder** [googleads/googleads-mobile-unity#2459]
* Unity version: 2021.3.16f1
  * Google Mobile Ads Unity plugin version: v7.3.1
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: Android Target 31 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: editor
  * Mediation ad networks used, and their versions: Ironsource

I updated all the plugins I use to the latest version, including google mobile ads. After building I got the following Gradle build failed error message:
```
* What went wrong:
Execution failed for task ':launcher:preReleaseBuild'.
> Could not resolve all files for configuration ':launcher:releaseRuntimeClasspath'.
   > Failed to transform googlemobileads-unity-.aar (:googlemobileads-unity:) to match attributes {artifactType=android-manifest, org.gradle.status=integration}.
      > Execution failed for JetifyTransform: C:\repos\project\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\libs\googlemobileads-unity.aar.
         > Failed to transform 'C:\repos\project\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\libs\googlemobileads-unity.aar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)
```
I tried removing the plugin and resolving for android again and the build passes. 

Am I missing something? Gradle used for this is the one that comes with unity (6.1.1) and target API level is set to 31.

**Comment by smartpo** [comment]
Have you managed this issue already? I got the same

**Comment by NVentimiglia** [comment]
@smartpo  @Ragethunder 

This might be a gradle / java build time issue. Please describe your android environment. What version Gradle and Java are you using. Often this can be fixed by changing the JRE or Gradle runtime.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.

**Comment by S4NT14G0** [comment]
For anyone struggling with this.  I had to upgrade project in Unity from 2019.4 to 2021.3.8f1 in order to get the newer version of gradle (6.1.1).  Once I did this my build with admob started working.  

https://docs.unity3d.com/Manual/android-gradle-overview.html
