### ISSUE TITLE
Mediation: addNetworkExtrasBundle error CS1061

### ISSUE THREAD

**Issue by avvie** [googleads/googleads-mobile-unity#247]
So i am using this code: 
`AdRequest request = new AdRequest.Builder()
							
							.addNetworkExtrasBundle(AdMobAdapter as AndroidJavaClass, AdColonyBuilder())
							.AddKeyword("game")
    						//.AddTestDevice(AdRequest.TestDeviceSimulator)       // Simulator.
    						//.AddTestDevice(SystemInfo.deviceUniqueIdentifier)  // My test device.
    						.Build();`
which produces the error 
Assets/Scripts/Controller.cs(743,58): error CS1061: Type `GoogleMobileAds.Api.AdRequest.Builder' does not contain a definition for `addNetworkExtrasBundle' and no extension method `addNetworkExtrasBundle' of type `GoogleMobileAds.Api.AdRequest.Builder' could be found (are you missing a using directive or an assembly reference?)

I have originally tried 
`AdRequest request = new AdRequest.Builder()
							
							.addNetworkExtrasBundle(AdMobAdapter.class, AdColonyBuilder())
							.AddKeyword("game")
    						//.AddTestDevice(AdRequest.TestDeviceSimulator)       // Simulator.
    						//.AddTestDevice(SystemInfo.deviceUniqueIdentifier)  // My test device.
    						.Build();`
 and in this case it will give : 
Assets/Scripts/Controller.cs(743,98): error CS1525: Unexpected symbol `class', expecting `identifier'

Any ideas? I spent some time looking what is wrong and why but couldnt figure it out

**Comment by rampara** [comment]
The `AdRequest.Builder` does not currently support functionality for adding network extra bundles.

**Comment by turkenh** [comment]
How can we use mediation networks then ?
Isn't it mandatory adding "addNetworkExtrasBundle" to use a third party mediation?

**Comment by rampara** [comment]
Which network you mediating to that has mandatory network extras?
