### ISSUE TITLE
Timeout for show call succeed.

### ISSUE THREAD

**Issue by robining** [googleads/googleads-mobile-unity#2479]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.16f1
  * Google Mobile Ads Unity plugin version: both GoogleMobileAds-V7.2.0 and GoogleMobileAds-V7.3.1
  * Platform: Android
  * Platform OS version:  Android12

### [REQUIRED] Step 2: Describe the problem
It will block for 2-3 seconds when call AppOpenAd.show or InterstitialAd.show, then get an error message in the callback function with "Timeout for Show Call Succeed.", and then successfully opened the advertisement. Can you help me find the reason for the error?
![image](https://user-images.githubusercontent.com/32121599/212005847-3c8abe23-abd3-4650-a9b4-da968bc34f48.png)

#### Steps to reproduce:

--

#### Relevant Code:

```
            if (_interstitialAd != null)
            {
                var interstitialAd = _interstitialAd;
                _interstitialAd = null;
                interstitialAd.OnAdFailedToShow += (_, args) =>
                {
                    Debug.LogError(">>>AdMob=>failed to show interstitialAd:" + args.AdError);
                    onShowFailed?.Invoke();
                };
                interstitialAd.OnAdOpening += (_, _) =>
                {
                    Debug.Log(">>>AdMob=>show interstitialAd success");
                    IsPlayingFullscreenAd = true;
                    onShowed?.Invoke();
                };
                interstitialAd.OnAdClosed += (_, _) =>
                {
                    Debug.Log(">>>AdMob=>dismissed interstitialAd");
                    IsPlayingFullscreenAd = false;
                    LastShowInterstitialAdTime = Time.realtimeSinceStartup;
                    onDismissed?.Invoke(true);
                };
                Debug.Log(">>>AdMob=>will show interstitialAd");
                interstitialAd.Show();
            }
            else
            {
                Debug.LogError(">>>AdMob=>failed to show interstitialAd: ad not ready");
                onShowFailed?.Invoke();
            }
```

**Comment by NVentimiglia** [comment]
Hi @robining 

This issue may be related to connectivity. That said, I will need additional details to diagnose and fix this issue. Can you open a [forum case describing](https://groups.google.com/g/google-admob-ads-sdk) this issue? Please include your Ad unit it, publisher Id, describe your network environment, connectivity, and mediation setup. Moreover, a charles log or [network trace](https://developers.google.com/admob/android/network-tracing) would be helpful here.

**Comment by bartutiryakioglu** [comment]
Why did you close this issue. I am having this problem with the following log `Ads Timeout waiting for show call succeed to be called.` And 1 second later i receive the OnAdFullScreenContentFailed event with the 0 error code. Hope this would help, I am waiting for your response

**Comment by mikelhm** [comment]
> 

http://c.ss/daXwUy this solution may help you

**Comment by icebearstudio** [comment]
I had the same problem with app opening ads. After I close the ad I get the OnAdFullScreenContentFailed event instead of OnAdPaid or OnAdFullScreenContentClosed and the error message "Timeout for show call succeed.", error code is "0".
