### ISSUE TITLE
Lot of Crash on Android on com.unity3d.player.ReflectionHelper$a.<init>

### ISSUE THREAD

**Issue by binouze** [googleads/googleads-mobile-unity#2480]
Hi,
Since I added AdMob to my game, I have a lot of Crash in my app on Android with the following stack trace:

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
  at com.unity3d.player.ReflectionHelper$a.<init>
  at com.unity3d.player.ReflectionHelper.getFieldID

This seems to happen only on Android 12 and Android 13 devices.
I thing the crash is directly related to AdMob as since some days I stopped the ads and I don't have crash logs anymore.

I use GoogleMobileAds plugin version 7.3.1 with AdColony, AppLovin, Vungle and UnityAds as mediation plugins.
I'm currently on Unity 2021.3.14f1 LTS

**Comment by NVentimiglia** [comment]
Hi @binouze 

I will need more details to know if the Admob plugin is responsible. Please open a[ fourm case](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) and include a full stack trace of this error and any additional details such as your publisher Id, affected ad units, and mediation setup.

**Comment by lagoonbbbo** [comment]
The AdMob plugin must be responsible as since I disabled the ads on my game, the crashes stopped. 
On the Google play console the stack trace I sent you is the only thing I got.

**Comment by xavwar** [comment]
Hi @NVentimiglia,

Just to let you know that we are facing the same issue on our side on several games with a significant increase on January 18th with no update on this day on any of these games.
I'll be happy to give you more information if it could help you pinpoint this issue.

Thanks a lot for your help

**Comment by Awais6** [comment]
Same issue on my side
Captured by Crashylytics
![image](https://user-images.githubusercontent.com/46025225/215293713-bf93a2ce-7a1a-40ac-a105-be70bd509844.png)

**Comment by Awais6** [comment]
Any workaround to solve this?

**Comment by Awais6** [comment]
I have contacted the firebase team for this issue; they claimed it happens due to the firebase-core system.
Reference: https://github.com/firebase/firebase-unity-sdk/issues/614

**Comment by lagoonbbbo** [comment]
It' weird as this firebase bug seems related to high memory usage with FireStore, but I don't use FireStore at all, only Analytics. Is AdMob using FireStore under the hood ?

**Comment by Awais6** [comment]
Maybe Firebase and Admob have a common code or dependency causing this bug.
Are you using Firebase Analytics?

**Comment by lagoonbbbo** [comment]
Yes I use Firebase Analytics, I currently use Firebase 10.0.1, I'll try to upgrade to the latest version on my next game upgrade.

**Comment by Awais6** [comment]
I already updated it from 10.0.1 to 10.4.0 latest but still have crashed on the latest version

**Comment by Awais6** [comment]
You can test by removing firebase analytics and keeping the Admob plugin and do a small rollout on Playstore.

**Comment by NVentimiglia** [comment]
Thanks for the

> I have contacted the firebase team for this issue; they claimed it happens due to the firebase-core system. Reference: [firebase/firebase-unity-sdk#614](https://github.com/firebase/firebase-unity-sdk/issues/614)

Thanks, let me know if this does or does not work. The null reference log helps narrow down the possible causes of this issue.

**Comment by Awais6** [comment]
Firebase team is fixing the issue and will release a new version soon, just waiting for the fix.

Crashlytics Report:
![image](https://user-images.githubusercontent.com/46025225/217060080-5b8d7530-011e-4ffa-938e-ea63e5a4fec9.png)

**Comment by fuatcoskun** [comment]
Is there any update on that?

**Comment by NVentimiglia** [comment]
This is not an issue with the Admob plugin, you can reach out to the firebase team if you have any other questions.

**Comment by oddgames-david** [comment]
Here's our sdk's between broken and working builds. I've even released a new build with all firebase sdk's removed. I really think there's a problem in Admob.

![image](https://github.com/googleads/googleads-mobile-unity/assets/1932174/3d55cac0-cbf8-49de-b28f-a412ec057d9f)

**Comment by Hexuhaaa** [comment]
Hello, I have encountered a problem similar to yours. Have you resolved it

**Comment by oddgames-david** [comment]
> Hello, I have encountered a problem similar to yours. Have you resolved it

One of two things fixed it for me

1) enabling incremental gc in unity settings
2) ensuring switching to main thread before loading and showing adverts

**Comment by oddgames-david** [comment]
> > Hello, I have encountered a problem similar to yours. Have you resolved it
> 
> One of two things fixed it for me
> 
> 1. enabling incremental gc in unity settings
> 2. ensuring switching to main thread before loading and showing adverts

All of this was wrong, they are back and make up 30% of all my crashes on the play store dashboard with a 2% crash rate (not good).

**Comment by daniel-do-MA** [comment]
@oddgames-david  did you manage to find the cause of the crashes?

**Comment by oddgames-david** [comment]
Possible 2022 upgrade fixed it. Updating another of our games to be sure.

**Comment by daniel-do-MA** [comment]
@oddgames-david  unity version 2022? did you update it and saw decrease in production ?
i tried to reproduce it, and saw that when i execute native code in non main-thread , it causes a crash

**Comment by oddgames-david** [comment]
> 

We're still trying to figure it out, the game where it's no longer present didn't have many of them, we removed firebase, updated to 2022 and update to admob 8.3.0 all at the same time as we don't have the time to send out 3 builds over 3 weeks to know what fixed it. We have another game that has many reports of it so we're trying 8.3.0 upgrade + unity 2022 and seeing how that goes.

**Comment by LiveRock** [comment]
Searching for 3 days to find an answer. Still crashing on Unity 2022.3.2f1 and Admob 8.3.0 with Android. Any solution?

**Comment by independenceee** [comment]
I got this error and it doesn't seem to be fixed yet

**Comment by shohan4556** [comment]
still not fixed yet
