### ISSUE TITLE
Getting IABTCF_AddtlConsent

### ISSUE THREAD

**Issue by desouse** [googleads/googleads-mobile-unity#2509]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.19f1
  * Google Mobile Ads Unity plugin version: 7.4.0
  * Platform: Android
  * Platform OS version: Android 11
  * Mediation ad networks used, and their versions: Applovin, Unity Ads, Vungle

#### Steps to reproduce:

According to the documentation I need to send consent manually to vendors who are not yet registered on the IAB Europe Global Vendor List (https://support.google.com/admanager/answer/9681920?hl=en)

https://developers.google.com/admob/unity/mediation/applovin#eu_consent_and_gdpr
https://developers.google.com/admob/unity/mediation/unity#eu_consent_and_gdpr
https://developers.google.com/admob/unity/mediation/vungle#eu_consent_and_gdpr

To do this I need to retrieve values from SharedPreferences by key IABTCF_AddtlConsent
![Screenshot_1](https://user-images.githubusercontent.com/9247348/215432528-32c66d04-aaa4-43e3-a737-2a627c0dfba2.png)

The question is: Does your plugin have a solution for this or do I need to write some code like the one below?

#### Relevant Code:

```
AndroidJavaClass unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
AndroidJavaObject currentActivity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity");
AndroidJavaClass preferenceManagerClass = new AndroidJavaClass("android.preference.PreferenceManager");
AndroidJavaObject sharedPreferences = preferenceManagerClass.CallStatic<AndroidJavaObject>("getDefaultSharedPreferences", currentActivity);
return sharedPreferences.Call<string>("getString", "IABTCF_AddtlConsent", "");
```

**Comment by NVentimiglia** [comment]
Google has defined a temporary technical specification (called “[Additional Consent Mode](https://support.google.com/admanager/answer/9681920)") intended only for use alongside IAB Europe’s Transparency & Consent Framework (TCF) v2.0 to serve as a bridge for vendors who are not yet registered on the IAB Europe Global Vendor List (GVL). 

This specification enables you to propagate additional consent—alongside their TCF v2.0 implementation—for companies that are not yet registered with the IAB Europe Global Vendor List but are on [Google's Ad Tech Providers (ATP) list](https://support.google.com/admanager/answer/9012903).

Note that the “additional_consent” string only allows for the CMP to pass ad tech provider IDs to Google where the requirements of Google’s [EU User Consent Policy](https://www.google.com/about/company/user-consent-policy/) have been met in respect of those vendors. In that sense, it is “all or nothing.” It is intended as a temporary patch to minimize publisher disruption until vendors register with the TCF v2.0. 

Hope that helps,
Nick

**Comment by desouse** [comment]
Thank you for your answer. But how about the TCF consent string?
![Screenshot_1](https://user-images.githubusercontent.com/9247348/215692296-496925c6-dd34-4766-9269-881ceff86538.png)
Vendors who are already registered on the IAB Europe Global Vendor List retrieve this string from SharedPreferences using their own tools. However, some of these vendors don't do this and require to pass them the TCF consent string manually. Does your plugin have a solution that allows retrieving the TCF consent string? Or maybe the solution will appear later?

**Comment by NVentimiglia** [comment]
@desouse 

I understand your confusion. The _temporary_ technical specification (called “[Additional Consent Mode](https://support.google.com/admanager/answer/9681920)") does suggest modifying the TC string manually, which goes against best practices. I also do not see an API for retrieving this string once modified from the UMP SDK.

Let me escalate, and I will get back to you.

**Comment by NVentimiglia** [comment]
Hi @desouse 

We currently do not have the ability to request the IAB Europe Global Vendor List from the UMP SDK. Your solution of going through Android prefs directly is a suggested work around. I will make note of this request and send it to the UMP team.

Thanks for the feedback.

**Comment by desouse** [comment]
Great. Thank you a lot!

**Comment by Suraj-SPG** [comment]
Any update on this? How do we get **IABTCF_AddtlConsent** in unity ? I'm tring with PlayerPrefs.GetString but value is null.
