### ISSUE TITLE
Module 'GoogleMobileAds' not found on Xcode 7.3

### ISSUE THREAD

**Issue by Solid-Metal** [googleads/googleads-mobile-unity#251]
Unity used : 5.4f1
Xcode : 7.3
sdk : googleads v3.0.5

getting error on basically all GADU stuff because of @import GoogleMobileAds

i already tried everything i get from the internet, still cant fix it, anyone can help?

**Comment by rampara** [comment]
The Google Mobile Ads Unity plugin should use CocoaPods to create an xcworkspace that includes the Google Mobile Ads iOS framework. If you don't have CocoaPods installed, you will have to manually download and include the Google Mobile Ads iOS framework into your xcode project.

**Comment by AdnanNazir** [comment]
Hey Rampara!
I am having almost the same issue. Unity is unable to make XCode project build. 
Can you suggest what could be wrong ?

**Comment by rampara** [comment]
@AdnanNazir I responded within #216.

**Comment by AZERQSDF** [comment]
How fix the problem
https://www.youtube.com/watch?v=rxO_rcMxGU4
