### ISSUE TITLE
I can't see the consent forms on built android app, but it shows on the editor.

### ISSUE THREAD

**Issue by lanzin0** [googleads/googleads-mobile-unity#2516]
* Unity version: 2020.3.9f1
  * Google Mobile Ads Unity plugin version: 21.5.0
  * Platform: Android
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

I don't know if I'm using the code correctly, but in the Editor I can see and interact with a test form. When I build the app and test it out, the form doesn't show. I tried to call another function in the ShowConsentForm one and it gets called.

#### Relevant Code:

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GoogleMobileAds.Api;
using GoogleMobileAds.Common;
using GoogleMobileAds.Ump.Api;

public class GDPR : MonoBehaviour
{
    private ConsentForm consentForm;
    public GameObject bottonePlay;

    void Start()
    {
        if (PlayerPrefs.GetInt("GDPR", -1) == -1)
        {
            ResetConsentInformation();
        }
    }

    void Update()
    {
        if (PlayerPrefs.GetInt("GDPR") != -1)
        {
            bottonePlay.SetActive(true);
        }
    }

    public void ResetConsentInformation()
    {
        ConsentInformation.Reset();

        UpdateConsentInformation();
    }

    public void UpdateConsentInformation()
    {
        var tagForUnderAgeOfConsent = false;

        var consentRequestParameters = new ConsentRequestParameters();
        consentRequestParameters.TagForUnderAgeOfConsent = tagForUnderAgeOfConsent;

        ConsentInformation.Update(consentRequestParameters,
            (FormError error) =>
            {
                if (error == null)
                {
                    LoadConsentForm();
                }
                else
                {

                }

            });
    }

    public void LoadConsentForm()
    {
        ConsentForm.Load(
                (ConsentForm form, FormError error) =>
                {
                    if (form != null)
                    {
                        consentForm = form;
                        ShowConsentForm();
                    }
                    else
                    {

                    }
                });
    }

    public void ShowConsentForm()
    {
        consentForm.Show(
                 (FormError error) =>
                 {
                     if (error == null)
                     {

                     }
                     else
                     {

                     }
                 });
    }

}

```

**Comment by NVentimiglia** [comment]
Hi @lanzin0 

Can you submit a logcat of the session so I can review ?

**Comment by lanzin0** [comment]
> 

Hey sorry, I don't know how to do that. I've tried other things in the meanwhike. I know for sure that the ShowConsentForm function gets called because I put a variable in it which gets changed. On the editor everything works fine, but I am not sure of the Update Consent Form part, is it well written?

**Comment by NVentimiglia** [comment]
@lanzin0 

The code looks ok for the most part. I think the use of ` if (PlayerPrefs.GetInt("GDPR") != -1)` may cause issues as we suggest to use `ConsentInformation` to check for status and not rolling a solution yourself.

Please send me a LogCat when you get a chance so I can diagnose the issue.

**Comment by lanzin0** [comment]
> 

Hi, I don't know how to do the LogCat thing. 

About the consent information, I'll try using consentstatus to start the function. Supposing that I don't manage to make it work, would it be the same using a form made by myself and changing "npa" values for AdMob?

By the way, thank you very much for everything so far.

**Comment by lanzin0** [comment]
Ok so I wrote 
`    void Start()
    {
        if (ConsentInformation.ConsentStatus == ConsentStatus.Required)
        {
            LoadConsentForm();
        }
    }`
and everything is just like before. This time however the function doesn't even get called, so I suppose I have made some mistake in the code.

**Comment by NVentimiglia** [comment]
@lanzin0 

Thanks for the update, will be happy to provide a code review if you can add more context.
