### ISSUE TITLE
Issue after enabling the ARM 64 IL2CPP

### ISSUE THREAD

**Issue by jatinJV** [googleads/googleads-mobile-unity#2518]
java.io.IOException: Can't read [C:\Users\shahp\.gradle\caches\transforms-2\files-2.1\328b84521e30516b8226e4c8a181416f\jetified-googlemobileads-unity-runtime.jar(;;;;;;;**.class)] (Can't process class [com/google/unity/ads/AdNetworkExtras.class] (Unsupported version number [55.0] (maximum 54.0, Java 10)))​

**Comment by NVentimiglia** [comment]
Hi @jatinJV 

Can you give me some additional details regarding your environment? What version of unity, the plugin, gradle, and java are you using? what is your build process and settings?
