### ISSUE TITLE
Pre-compiled assemblies use obsolete APIs

### ISSUE THREAD

**Issue by Watcher3056** [googleads/googleads-mobile-unity#2519]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.13f1
  * Google Mobile Ads Unity plugin version: 7.4.0
  * Platform: Unity Editor
  * Platform OS version: Any
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
After importing plugin Unity offers to upgrade pre-compiled assemblies as they are using API that was obsolete.

**Comment by NVentimiglia** [comment]
To maximize compatibility with the most developers possible, we compile our assemblies against Unity 2018. This may cause the obsolete pre-compiled warning. This warning is benign and should not break anything.

If this warning worries you, you may download the source and compile it yourself. Let me know if you need additional assistance.
