### ISSUE TITLE
Android App Crashed on Start

### ISSUE THREAD

**Issue by danielcdcj** [googleads/googleads-mobile-unity#2520]
Step 1: Describe your environment

  * Unity version: 2021.3.18f1, running on M1 Mac with macOS Monterey v12.5
  * Google Mobile Ads Unity plugin version: v7.0.2
  * Platform: Android
  * Platform OS version: Android 12
  * Any specific devices issue occurs on: Android Emulator running API level 31 Android
  * Mediation ad networks used, and their versions: None

Step 2: Describe the problem
The build is successful and is installed onto the android device; however, the app opens up and immediately crashed.

#### Steps to reproduce:

1. Create a new Unity project with v2021.3.18f1.
2. Download [GoogleMobileAds-v7.0.2.unitypackage](https://github.com/googleads/googleads-mobile-unity/releases/download/v7.0.2/GoogleMobileAds-v7.0.2.unitypackage)
3. Import it by going to Assets -> Import Package -> Custom Package...; Enable Auto Resolution when asked.
4. Put in the test Google Mobile Ads ID for both Android and iOS
5. Set target API level to 31, Set Scripting Backend to IL2CPP and add ARM64 under Target Architecture
6. Build And Run onto an Android Device.

My project file
[MyNewProject.zip](https://github.com/googleads/googleads-mobile-unity/files/10669121/MyNewProject.zip)

**Comment by NVentimiglia** [comment]
Hi @danielcdcj 

I downloaded the project to take a look. The project has an empty scene file without any scripts running GoogleMobileAds. Are you sure you submitted the complete sample?

That said, if you could include a logcat and exception message, it would help very much.
