### ISSUE TITLE
Android 13 + Rewarded + Landscape bug: ad skippable after few seconds - reward is giving out!

### ISSUE THREAD

**Issue by arpaplus** [googleads/googleads-mobile-unity#2526]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: ANY
  * Google Mobile Ads Unity plugin version: ANY
  * Platform: Android (only)
  * Platform OS version: Android 13

#### Steps to reproduce:

Install an app with AdMob rewarded video integrated to your **Android 13** device.
Run it, run a rewarded video ad and press multiple times on a closing button: ad unexpectedly closes and reward given out.

Please check the video with bug being reproduced: https://www.youtube.com/watch?v=Rk9uc4JX9Ec

We tested it on multiple games built with various Unity and AdMob versions.

**Comment by NVentimiglia** [comment]
Hi @arpaplus,

I was able to replicate the issue. We will fix this issue, thank you for the report.
