### ISSUE TITLE
Android Build failed after adding admob

### ISSUE THREAD

**Issue by lijuicsoft** [googleads/googleads-mobile-unity#253]
Hi, i am using Unity 4.7.1 and Google Mobile Ads Unity Plugin v3.0.5
After adding abmob plugin , i cant take build . Following error is showing

```
Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
D:\InstallLocation\Android_SDK\build-tools\23.0.3\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "D:/InstallLocation/Android_SDK/platforms/android-23\android.jar" -F bin/resources.ap_ --extra-packages com.google.unity

stderr[
AndroidManifest.xml:17: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.IAPTheme').

AndroidManifest.xml:19: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

]
stdout[
Configurations:
 (default)

Files:
  drawable\app_icon.png
    Src: () res\drawable\app_icon.png
  values\strings.xml
    Src: () res\values\strings.xml
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
  Type drawable
    drawable\app_icon.png
      Src: () res\drawable\app_icon.png
  Type values
    values\strings.xml
      Src: () res\values\strings.xml
Including resources from package: D:\InstallLocation\Android_SDK\platforms\android-23\android.jar
applyFileOverlay for drawable
applyFileOverlay for layout
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: res\drawable\app_icon.png
    (processed image res\drawable\app_icon.png: 94% size of source)
    (new resource id app_icon from drawable\app_icon.png #generated)
]
```
Here is **screenshots** of  **Assets/Plugins/Android directory**

![unity1](https://cloud.githubusercontent.com/assets/7496536/17172399/90b452e2-5412-11e6-95ab-2b0eb7f8a80a.png)
![u2](https://cloud.githubusercontent.com/assets/7496536/17172406/962a2e04-5412-11e6-80a8-a32c64d2c1a9.png)

Here is   **screenshots** of  **Android SDK Manager**

![sdk 1](https://cloud.githubusercontent.com/assets/7496536/17172412/a0233dd8-5412-11e6-895e-350f40a4aeca.png)

![sdk 2](https://cloud.githubusercontent.com/assets/7496536/17172419/a965de6e-5412-11e6-8493-518f81035dcc.png)

**Comment by rampara** [comment]
Do you have the Android SDK installed on your development machine? If so, can you post the contents of the `Assets/Plugins/Android` directory of your Unity project?

**Comment by lijuicsoft** [comment]
@rampara , i have installed Android Sdk  and  i could take apk build  before adding Google Admob plugins . Here is the screen shot of Assets/Plugins/Android directory  
![unity1](https://cloud.githubusercontent.com/assets/7496536/17090079/6d1135cc-524a-11e6-9034-30e83472ffd5.png)

**Comment by lijuicsoft** [comment]
Ram , please check the question update

**Comment by lijuicsoft** [comment]
Ram ,
I have got solution 
Right click on Assets > PlayServicesResolver folder and select Google Play Services > Resolve Client Jars to fix any dependency import issues.

https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/game-engines/TpqvTLvtDEc

**Comment by eanjo7** [comment]
me too, what is the solution for it? can I ask what version of admob sdk is this? 
because google admob will disbale sdk 6.4.1 and below
