### ISSUE TITLE
Admob User Messaging Platform implementation guide for Unity leads to errors.

### ISSUE THREAD

**Issue by RiccardoCantone** [googleads/googleads-mobile-unity#2535]
* Unity version: 2021.3.19f1
  * Google Mobile Ads Unity plugin version: 7.4.1
  * Platform: Unity Editor
  * Platform OS version: Android
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: Admob

I tried implementing the User Messaging Platform in my Unity project closely following the official guide at https://developers.google.com/admob/unity/privacy  (see implementation code below), but I get the following errors:

Assets\Scripts\UserMessagingPlatformManager.cs(21,45): error CS0117: 'DebugGeography' does not contain a definition for 'DEBUG_GEOGRAPHY_EEA'

Assets\Scripts\UserMessagingPlatformManager.cs(36,28): error CS0117: 'ConsentInformation' does not contain a definition for 'RequestConsentInfoUpdate'

Assets\Scripts\UserMessagingPlatformManager.cs(60,21): error CS0117: 'ConsentForm' does not contain a definition for 'LoadConsentForm'

Assets\Scripts\UserMessagingPlatformManager.cs(76,13): error CS0120: An object reference is required for the non-static field, method, or property 'ConsentForm.Show(Action<FormError>)'

What could be the problem?

#### Relevant Code:

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GoogleMobileAds.Ump;
using GoogleMobileAds.Ump.Api;
using GoogleMobileAds.Common;

public class UserMessagingPlatformManager : MonoBehaviour
{
    
    

    // Start is called before the first frame update
    
    void Start()
    {
        
        var debugSettings = new ConsentDebugSettings
        {
            // Geography appears as in EEA for debug devices.
            DebugGeography = DebugGeography.DEBUG_GEOGRAPHY_EEA,
            TestDeviceHashedIds = new List<string>
            {
                "TEST-DEVICE-HASHED-ID"
            }
        };
        // Set tag for under age of consent.
        // Here false means users are not under age.
        ConsentRequestParameters request = new ConsentRequestParameters
        {
            TagForUnderAgeOfConsent = false,
           // ConsentDebugSettings = debugSettings,
        };

        // Check the current consent information status.
        ConsentInformation.RequestConsentInfoUpdate(request, OnConsentInfoUpdated);
    }


    void OnConsentInfoUpdated(FormError error)
    {
        if (error != null)
        {
            // Handle the error.
            UnityEngine.Debug.LogError(error);
            return;
        }
        // If the error is null, the consent information state was updated.
        // The consent information state was updated.
        // You are now ready to check if a form is available.
        if (ConsentInformation.IsConsentFormAvailable())
        {
            LoadConsentForm();
        }
    }

    void LoadConsentForm()
    {
        // Loads a consent form.
        ConsentForm.LoadConsentForm(OnLoadConsentForm);
    }

    void OnLoadConsentForm(FormError error)
    {
        if (error != null)
        {
            // Handle the error.
            UnityEngine.Debug.LogError(error);
            return;
        }

        // The consent form was loaded.
        // You are now ready to show the form.
        if(ConsentInformation.ConsentStatus == ConsentStatus.Required)
        {
            ConsentForm.Show(OnShowForm);
        }
    }

    void OnShowForm(FormError error)
    {
        if (error != null)
        {
            // Handle the error.
            UnityEngine.Debug.LogError(error);
            return;
        }

        // Handle dismissal by reloading form.
        LoadConsentForm();
    }

    

   
}

```

**Comment by NVentimiglia** [comment]
Hi @RiccardoCantone,

At first glance your implementation looks correct. Moreover, you are using the correct version of the Unity plugin (7.4.1). I suspect that this is a dependency issue in nature. Lets try this:

1.  Remove the Unity plugin, specifically the `.dll` files.
2. If that does not help, you can submit your `.dll` files here and I will take a look.

Looking forwarder to helping further,

**Comment by gollobo** [comment]
@RiccardoCantone The code is the old first implementation of the user messaging platform, in the current plugin version is different. The documentation relies in the old, documentation is wrong, see the github example code to see valid code.

Example:
- DebugGeography.DEBUG_GEOGRAPHY_EEA --> DebugGeography.EEA
- ConsentInformation.RequestConsentInfoUpdate --> ConsentInformation.Update
And almost all the code in the documentation

**Comment by RiccardoCantone** [comment]
> @RiccardoCantone The code is the old first implementation of the user messaging platform, in the current plugin version is different. The documentation relies in the old, documentation is wrong, see the github example code to see valid code.
> 
> Example:
> 
> * DebugGeography.DEBUG_GEOGRAPHY_EEA --> DebugGeography.EEA
> * ConsentInformation.RequestConsentInfoUpdate --> ConsentInformation.Update
>   And almost all the code in the documentation

Thank you very much for your response. I used the github example to implement UMP in my project and it worked! I just have one more question. Right now I can only see the test version of the consent form in my app. How can I enable the real consent form I published on the Admob platform under "Privacy and Messaging"? If I remove the Debug settings, no form will show up.

**Comment by RiccardoCantone** [comment]
> Hi @RiccardoCantone,
> 
> At first glance your implementation looks correct. Moreover, you are using the correct version of the Unity plugin (7.4.1). I suspect that this is a dependency issue in nature. Lets try this:
> 
> 1. Remove the Unity plugin, specifically the `.dll` files.
> 2. If that does not help, you can submit your `.dll` files here and I will take a look.
> 
> Looking forwarder to helping further,

Thank you for your response. It turns out the guide wasn't up-to-date.

**Comment by gollobo** [comment]
@RiccardoCantone I have the same problem! I just opened another issue with that error: https://github.com/googleads/googleads-mobile-unity/issues/2543

**Comment by RiccardoCantone** [comment]
@gollobo I'll subscribe to your issue, then. Trouble shared is trouble halved, at least.

**Comment by NVentimiglia** [comment]
Guide is now up to date, Thank you.

**Comment by og-abdul-mateen** [comment]
> > @RiccardoCantone The code is the old first implementation of the user messaging platform, in the current plugin version is different. The documentation relies in the old, documentation is wrong, see the github example code to see valid code.
> > Example:
> > 
> > * DebugGeography.DEBUG_GEOGRAPHY_EEA --> DebugGeography.EEA
> > * ConsentInformation.RequestConsentInfoUpdate --> ConsentInformation.Update
> >   And almost all the code in the documentation
> 
> Thank you very much @gollobo for your response. I used the github example to implement UMP in my project and it worked! I just have one more question. Right now I can only see the test version of the consent form in my app. How can I enable the real consent form I published on the Admob platform under "Privacy and Messaging"? If I remove the Debug settings, no form will show up. @NVentimiglia

How did you manage to go around this?
