### ISSUE TITLE
Misleading xml doc in RewardedAd

### ISSUE THREAD

**Issue by IoannisFMG** [googleads/googleads-mobile-unity#2549]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: ANY
  * Google Mobile Ads Unity plugin version: 7.4.0
  * Platform: SDK (iOS, Android, Unity Editor)
  * Platform OS version: N/A (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: N/A
  * Mediation ad networks used, and their versions: N/A

### [REQUIRED] Step 2: Describe the problem
You indicate the following:
https://github.com/googleads/googleads-mobile-unity/blob/519a227c3928ec6ff3396931dc5c2bb77b02f213/source/plugin/Assets/GoogleMobileAds/Api/RewardedAd.cs#L102-L107
and 
https://github.com/googleads/googleads-mobile-unity/blob/519a227c3928ec6ff3396931dc5c2bb77b02f213/source/plugin/Assets/GoogleMobileAds/Api/RewardedAd.cs#L109-L114

At first I think you are suggesting developers to map different events for different callbacks.
The `OnUserEarnedReward` event (which is non-existent, but OK, that could be a typo) is the one that is called when the user has earned the reward.
The `OnPaidEvent` is when the ad has produced income. 
The xml doc suggests to use them the other way around. Essentially swapping them. Is that correct?

But also, the "new way" to record whether users have earned their rewards is via a callback passed when calling the `Show` method:
https://github.com/googleads/googleads-mobile-unity/blob/519a227c3928ec6ff3396931dc5c2bb77b02f213/source/plugin/Assets/GoogleMobileAds/Api/RewardedAd.cs#L223-L232

Do we still need to use the class event along with the method parameter?

Am I missing something?

**Comment by NVentimiglia** [comment]
@IoannisFMG 

Thank you for raising awareness. I have confirmed this is an issue and will get a fix to the xml-doc comments.

That said you are correct in the solution:

`OnUserEarnedReward` is deprecated in favor of `Show(Action<Reward>)`.

`OnPaidEvent` is deprecated in favor of `OnAdPaid`.

**Comment by NVentimiglia** [comment]
This will be fixed in the next release.
