### ISSUE TITLE
Ad mediatation Using Google Admob for Unity

### ISSUE THREAD

**Issue by AdnanNazir** [googleads/googleads-mobile-unity#255]
hEY hi Guys!
I hope all are doing great. I am just wondering, is there any simplified SDK less solution to server ads mediated from different Ads Networks?
Just wanted to know, how hard it is to accomplish in Unity3D?
I do make Unity Plugins and just wanted to know, Is it really simple to achieve this easily ?
May be I can make a plugin to do the job. Actually I was just seeing Admob reward video meditation and don't have any idea and unable to see anywhere how can I do it in Unity to work for both android and iOS ?
Also Is there anyway to not use any meditation service ?
Thanks

**Comment by rampara** [comment]
This plugin currently supports [SDK-less mediation](https://support.google.com/admob/answer/3063564?hl=en#sdk-less) and [rewarded video mediation](https://firebase.google.com/docs/admob/android/games#rewarded_video_mediation) out of the box. At this time, rewarded video ads are only available from third-party networks that you've selected for mediation.
