### ISSUE TITLE
Y position of banner ad is inverted in editor

### ISSUE THREAD

**Issue by psrar** [googleads/googleads-mobile-unity#2553]
* Unity version: 2021.3.16f1
  * Google Mobile Ads Unity plugin version: 7.4.1
  * Platform: Android, Unity Editor
  * Platform OS version: Android 13 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: tested on Google Pixel 4
  * Mediation ad networks used, and their versions: no

1) _bannerView = new BannerView(_bannerUnitId, adSize, x, y);
2) On Unity, bigger Y value means banner will be higher
3) On Android, bigger Y value means banner will be lower

Cannot provide project files ;(
But code does not differ from official sample.

**Comment by NVentimiglia** [comment]
Hi @psrar 

I see the issue, on Editor the anchor is incorrect. 
![image](https://user-images.githubusercontent.com/125889/221068688-bc7bf87e-8f21-4aa7-9af3-01e7f4102fb2.png)

Thank you raising awareness. Closing the issue with a fix in the works.

**Comment by NVentimiglia** [comment]
b/270630552 for reference

**Comment by NVentimiglia** [comment]
This will be fixed in the next release.
