### ISSUE TITLE
AdMob SDK not initizializing if it fails for the first time

### ISSUE THREAD

**Issue by bartutiryakioglu** [googleads/googleads-mobile-unity#2561]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.18f1
  * Google Mobile Ads Unity plugin version: 7.3.0
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: Meta, Vungle, Pangle

### [REQUIRED] Step 2: Describe the problem
If AdMob does not initialize any adapter at first try (main reason is being not connected to internet), it won't initialize for the next tries whether the internet connection is established or not

#### Steps to reproduce:

- Launch App
- Disconnect internet
- Initialize SDK
- Connect internet

**Comment by NVentimiglia** [comment]
@bartutiryakioglu what did you notice to determine that the adapter was not initialized? Do you have a charles log or debug trace?

**Comment by gollobo** [comment]
I’ve noticed the same thing, if the app starts offline, and then you connect to the internet does not start the SDK and no ads are displayed. In the native Android and iOS SDK this is automatic.

**Comment by bartutiryakioglu** [comment]
> @bartutiryakioglu what did you notice to determine that the adapter was not initialized? Do you have a charles log or debug trace?

If any mediation network (including GoogleAdMob) is not initialized, I accept the SDK is not initialized. If it fails for the first try, it won't succeed for any other tries on that session.
