### ISSUE TITLE
'MobileAds' does not contain a definition for 'RaiseAdEventsOnUnityMainThread'

### ISSUE THREAD

**Issue by RiccardoCantone** [googleads/googleads-mobile-unity#2562]
Google Mobile Ads SDK v7.4.1
Unity editor v2021.3.19f1 LTS
Target Platform: Android
App status: not published yet

The "Get Started" Admob initialization official guide suggests synchronizing Mobile Ads SDK events and callbacks with the main Unity thread by using the following line of code:

MobileAds.RaiseAdEventsOnUnityMainThread = true;

Unfortunately, if I use it, I get the following error:

Assets\Scripts\AdInitializerScript.cs(32,19): error CS0117: 'MobileAds' does not contain a definition for 'RaiseAdEventsOnUnityMainThread'.

I closely followed the implementation guide and everything else seems to be working, if I don't include that line. What could be causing this?

#### Relevant Code:

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GoogleMobileAds;
using GoogleMobileAds.Api;

public class AdInitializerScript : MonoBehaviour
{
    public static AdInitializerScript instanceAdInitializer;

    void Awake()
    {
        if(instanceAdInitializer == null)
        {
            instanceAdInitializer = this;
        }
        else
        {
            Destroy(gameObject);
            return;
        }
        GameManager.instance.ad_initializer_script = this;
        // When true all events raised by GoogleMobileAds will be invoked
        // on the Unity main thread. The default value is false.
        MobileAds.RaiseAdEventsOnUnityMainThread = true;
        // Initialize the Google Mobile Ads SDK.
        MobileAds.Initialize(initStatus => {GameManager.instance.initializerCalledBack = true; });
    }
}

```

**Comment by NVentimiglia** [comment]
Hi @RiccardoCantone 

`RaiseAdEventsOnUnityMainThread` is scheduled for 7.4.2. We will correct the docs.
