### ISSUE TITLE
Failed to initialize decoder error

### ISSUE THREAD

**Issue by MuradAlvv** [googleads/googleads-mobile-unity#2568]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.2.9
  * Google Mobile Ads Unity plugin version: 7.4.1 / 7.4.0 both
  * Platform: Android
  * Platform OS version: Android 11 
  

#### Steps to reproduce:
Import Google Mobile Ads
Setup (for example) Rewarded ad
Build it

Sometimes ads shown but sometimes i get error in logcat and after that  ads doesn't work at all untill i reload app.

2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer Video codec error
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer   qi: Decoder init failed: OMX.qcom.video.decoder.vp9, Format(1, null, null, video/x-vnd.on2.vp9, null, -1, en, [1280, 720, -1.0], [-1, -1])
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer       at qj.ag(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:19)
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer       at qj.Q(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:4)
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer       at vy.Q(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:1)
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer       at qj.aA(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:3)
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer       at qj.L(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:2)
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer       at jn.m(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:58)
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer       at jn.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:129)
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer       at android.os.Handler.dispatchMessage(Handler.java:102)
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer       at android.os.Looper.loop(Looper.java:246)
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer       at android.os.HandlerThread.run(HandlerThread.java:67)
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer   Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer       at android.media.MediaCodec.native_configure(Native Method)
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer       at android.media.MediaCodec.configure(MediaCodec.java:2127)
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer       at android.media.MediaCodec.configure(MediaCodec.java:2043)
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer       at qj.as(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:14)
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer       at qj.ag(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:15)
2023.03.05 05:35:50.498 18825 21882 Error MediaCodecVideoRenderer       ... 9 more
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal Playback error
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal   hp: MediaCodecVideoRenderer error, index=1, format=Format(1, null, null, video/x-vnd.on2.vp9, null, -1, en, [1280, 720, -1.0], [-1, -1]), format_supported=YES
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       at jn.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:138)
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       at android.os.Handler.dispatchMessage(Handler.java:102)
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       at android.os.Looper.loop(Looper.java:246)
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       at android.os.HandlerThread.run(HandlerThread.java:67)
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal   Caused by: qi: Decoder init failed: OMX.qcom.video.decoder.vp9, Format(1, null, null, video/x-vnd.on2.vp9, null, -1, en, [1280, 720, -1.0], [-1, -1])
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       at qj.ag(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:19)
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       at qj.Q(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:4)
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       at vy.Q(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:1)
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       at qj.aA(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:3)
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       at qj.L(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:2)
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       at jn.m(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:58)
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       at jn.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:129)
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       ... 3 more
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal   Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       at android.media.MediaCodec.native_configure(Native Method)
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       at android.media.MediaCodec.configure(MediaCodec.java:2127)
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       at android.media.MediaCodec.configure(MediaCodec.java:2043)
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       at qj.as(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:14)
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       at qj.ag(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:15)
2023.03.05 05:35:50.501 18825 21882 Error ExoPlayerImplInternal       ... 9 more

and after this error i get loadAd error: 
Rewarded ad failed to load an ad with error : {
"Code": 0, .....

**Comment by MuradAlvv** [comment]
I fixed it. This error appearing while reloading scene and LoadAd functions does not have time to complete. To fix it i made adsManager object singleton so its saved even  when i reload my scene

**Comment by NVentimiglia** [comment]
Thanks for the update!
