### ISSUE TITLE
Android il2cpp is now official in Unity 5.4 - any updates to the plugin in sight?

### ISSUE THREAD

**Issue by rdaros** [googleads/googleads-mobile-unity#257]
As far as I know, il2cpp for Android is not supported in the GoogleAds plugin at the moment because it was an experimental feature in Unity. Now il2cpp is official and stable in Unity 5.4, so an update to the plugin should be in order. Any plans?

**Comment by rampara** [comment]
Android il2cpp compatibility has been added to the latest version of the plugin (3.0.6).
