### ISSUE TITLE
[iOS] AdMob unable to initialise if Cocoapods is configured to create static library and has empty main target

### ISSUE THREAD

**Issue by 256p** [googleads/googleads-mobile-unity#2588]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2023.1.0b1
  * Google Mobile Ads Unity plugin version: 7.4.1
  * Platform: iOS
  * Platform OS version: tested on iOS 15.7.1 and iOS 16.3.1 but the issue seems not to be related to a specific version
  * Any specific devices issue occurs on: any device
  * Mediation ad networks used, and their versions: no mediation

### [REQUIRED] Step 2: Describe the problem

In short, I'm getting an error (code 2) "SDK tried to perform a networking task before being initialized." in OnAdFailedToLoad after initCompleteAction with the status "Rady". This happens only if in External Dependency Manager iOS resolver settings I remove "use_frameworks!" from Podfile and leave "add the main target to Podfile" option enabled.
Podfile that is causing error:
```
source 'https://github.com/CocoaPods/Specs'
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'UnityFramework' do
  pod 'Google-Mobile-Ads-SDK', '~> 10.0'
end
target 'Unity-iPhone' do
end
```
It seems that the unity plugin isn't initializing the native Google Mobile Ads iOS framework. If add call `[GADMobileAds.sharedInstance startWithCompletionHandler:nil];` after initCompleteAction then the error disappears. The problem is that I need to call the iOS framework directly from Unity code while it should be done by the Google Ads Unity plugin.

#### Steps to reproduce:

1. Add AdMob Unity plugin exactly as described in the Get Started guide. In short:
    1.1. Import AdMob unitypackage
    1.2. Add app ID and initialize by invoking `MobileAds.Initialize`
    1.3. After initCompleteAction is invoked, add ad loading for example for a rewarded ad (or add a button for loading, doesn't really matter)
2. In Assets -> External Dependency Manager -> iOS Resolver -> Settings disable "Add use_frameworks! to Podfile" and enable "Always add the main target to Podfile"
3. Build and Run
4. In init logs should be visible that GADMobileAds state is Ready but if trying to load ad getting the error "SDK tried to perform a networking task before being initialized."

#### Relevant Code:

```
source 'https://github.com/CocoaPods/Specs'
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'UnityFramework' do
  pod 'Google-Mobile-Ads-SDK', '~> 10.0'
end
target 'Unity-iPhone' do
end
```

**Comment by NVentimiglia** [comment]
@256p 

This seems like a project specific issue. Can you please visit the [google support group](https://groups.google.com/g/google-admob-ads-sdk) with an minimal sample project demonstrating this problem?
