### ISSUE TITLE
Proguard issue

### ISSUE THREAD

**Issue by Nazir616** [googleads/googleads-mobile-unity#2592]
GMA version=7.4.1
Unity Version=2020.3.27
Description :
My issue is with AppOpenAd when it is called on foreground. Every thing is working fine when minify is disabled in unity. When I enabled Minify and add proguard file
 "-keep class com.google.unity.** { *;}
-keep class com.google.android.gms.ads.** {*;}
-keep class com.google.ads.mediation.** {*;}
-keep public class com.google.** { *; }"
Then ads show successfully but AppOpenAd is not called from app state changed 

 public void OnAppStateChanged(AppState state)
    {
        // Display the app open ad when the app is foregrounded.
        UnityEngine.Debug.Log("App State is " + state);
        // OnAppStateChanged is not guaranteed to execute on the Unity UI thread.
        MobileAdsEventExecutor.ExecuteInUpdate(() =>
        {
            if (state == AppState.Foreground)
            {
                ShowAppOpenAd();
               
            }
        });
    }
 
but when I call it form "OnApplicationPause " it show successfully. Please provide me proguard for App state change. Thanks

**Comment by Nazir616** [comment]
Thanks.Solved

**Comment by n2dev** [comment]
-keep class androidx.lifecycle.** { ;} causes r8 error, but -keep class androidx.lifecycle.** { *;} worked for me.
