### ISSUE TITLE
Banner Size Changed When Refreshed In Mediation

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#2595]
Step 1: Describe your environment

- Unity version: 2020.3.41f1
- Google Mobile Ads Unity plugin version: 7.3.1
- Platform: Unity Editor
- Platform OS version: Android
- Mediation ad networks used, and their versions: AppLovinUnityAdapter-6.5.1, MetaAudienceNetworkUnityAdapter-3.9.0, UnityAdsUnityAdapter-3.5.0

Step 2: Describe the problem
I am using admob mediation and include these ad networks (Unity3d, Applovin and Facebook Meta Audience Network).
For banner i set standard size 320x50.
Banner is showing correctly in game with given size but when it refreshed with other mediated ad networks mentioned above, Its size changed ( which i think is the size coming from mediated ad networks).
Due to which my game content is overlapped and  comes under violation.

![OtherAdNetworkBanner](https://user-images.githubusercontent.com/32755091/228152972-246c6ddc-ef9c-4702-99b3-cfaeeb562ba6.JPEG)
![AdmobBanner](https://user-images.githubusercontent.com/32755091/228152981-3fd0a32c-4fe9-40fa-be09-d1d924d064b7.JPEG)

**Comment by MuhammadWaqasOfficial** [comment]
confirming this issue on my other game as well.

**Comment by NVentimiglia** [comment]
@MuhammadWaqasOfficial 

Can you reach out to https://groups.google.com/g/google-admob-ads-sdk for this issue?

Please include your publisher id, affected ad unit ids, and if possible a charles log and minimal sample ap.
