### ISSUE TITLE
update sdk  error

### ISSUE THREAD

**Issue by G0561** [googleads/googleads-mobile-unity#2601]
2023-03-30 08:08:17.036243-0700 shudu-mobile[10184:72318] *** Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without AppMeasurement. Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-update-plist to include the AppMeasurement framework and set the -ObjC linker flag. Google Ad Manager publishers, follow instructions here: https://googlemobileadssdk.page.link/ad-manager-ios-update-plist'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff8004288ab __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80004dba3 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff80042851d -[NSException init] + 0
	3   shudu-mobile                        0x000000010a2f454f GADApplicationVerifyPublisherInitializedCorrectly + 302
	4   shudu-mobile                        0x000000010a2f4701 GADApplicationVerifyPublisherInitializedCorrectly + 736
	5   libdispatch.dylib                   0x000000010c9cbd18 _dispatch_call_block_and_release + 12
	6   libdispatch.dylib                   0x000000010c9ccf5b _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x000000010c9cfa28 _dispatch_queue_override_invoke + 1488
	8   libdispatch.dylib                   0x000000010c9e1e77 _dispatch_root_queue_drain + 414
	9   libdispatch.dylib                   0x000000010c9e2b17 _dispatch_worker_thread2 + 278
	10  libsystem_pthread.dylib             0x00007ff836172c0f _pthread_wqthread + 257
	11  libsystem_pthread.dylib             0x00007ff836171bbf start_wqthread + 15
)
2023-03-30 08:08:17.038489-0700 shudu-mobile[10184:72088] cocos2d: surface size: 2556x1179
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without AppMeasurement. Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-update-plist to include the AppMeasurement framework and set the -ObjC linker flag. Google Ad Manager publishers, follow instructions here: https://googlemobileadssdk.page.link/ad-manager-ios-update-plist'
terminating with uncaught exception of type NSException
CoreSimulator 857.14 - Device: iPhone 14 Pro (EBEC268D-F01D-4EAF-A860-ACA778C50E31) - Runtime: iOS 16.2 (20C52) - DeviceType: iPhone 14 Pro
(lldb) 

crazy error ，it's like https://stackoverflow.com/questions/66411662/the-google-mobile-ads-sdk-was-initialized-without-appmeasurement

**Comment by NVentimiglia** [comment]
Hi @G0561 

This usually occurs due to a misconfigured plist file. Its possible that EDM or cocoapods did not fire correctly. I will need to see additional details about your setup such as your plist file or a minimal sample which replicates the issue.

This is a complex issue which may require the passing of sensitive file back and forth, can you open a ticket on the [google support group](https://groups.google.com/g/google-admob-ads-sdk)?
