### ISSUE TITLE
[Question] Implementation of RaiseAdEventsOnUnityMainThread

### ISSUE THREAD

**Issue by takazawa-gg** [googleads/googleads-mobile-unity#2603]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: _____
  * Google Mobile Ads Unity plugin version: _____
  * Platform: _____ (iOS, Android, Unity Editor)
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem

I am checking the code for v8.0.0 and it appears that MobileAds.RaiseAction() is not used for InterstitialAd.
Does this mean that InterstitialAd callbacks are executed in the main thread and therefore not needed?

I would like to take advantage of RaiseAdEventsOnUnityMainThread, but I hope it is not an omission in the implementation.

**Comment by NVentimiglia** [comment]
Hi @takazawa-gg This is included on Version 8.0.0 of the plugin.
