### ISSUE TITLE
Android Crash Bug ClassNotFoundException

### ISSUE THREAD

**Issue by ImperialCrise** [googleads/googleads-mobile-unity#2606]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.22f1
  * Google Mobile Ads Unity plugin version: 8.0.0
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: Android 12 (eg iOS 10, Android 9)

#### Steps to reproduce:

I just did a simple C# script where i use : 

```
    private AdRequest CreateAdRequest()
    {
        return new AdRequest.Builder()
            .AddKeyword("game")
            .AddExtra("color_bg", "9B30FF")
            .Build();
    }
```

But i get an error on Android : 

```
04-01 21:03:00.273 18923 18971 E Unity   : AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.AdRequest$Builder
04-01 21:03:00.273 18923 18971 E Unity   : java.lang.ClassNotFoundException: com.google.android.gms.ads.AdRequest$Builder
04-01 21:03:00.273 18923 18971 E Unity   :      at java.lang.Class.classForName(Native Method)
04-01 21:03:00.273 18923 18971 E Unity   :      at java.lang.Class.forName(Class.java:454)
04-01 21:03:00.273 18923 18971 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
04-01 21:03:00.273 18923 18971 E Unity   :      at com.unity3d.player.UnityPlayer.access$500(Unknown Source:0)
04-01 21:03:00.273 18923 18971 E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:114)
04-01 21:03:00.273 18923 18971 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:102)
04-01 21:03:00.273 18923 18971 E Unity   :      at android.os.Looper.loopOnce(Looper.java:226)
04-01 21:03:00.273 18923 18971 E Unity   :      at android.os.Looper.loop(Looper.java:313)
04-01 21:03:00.273 18923 18971 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
04-01 21:03:00.273 18923 18971 E Unity   : Caused by: java.lang.ClassNotFoundException: com.google.android.gms.ads.AdRequest$Builder
04-01 21:03:00.273 18923 18971 E Unity   :      ... 9 more
04-01 21:03:00.273 18923 18971 E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0
04-01 21:03:00.273 18923 18971 E Unity   :   at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x00000] in <00000000000000000000000000000000>:0
04-01 21:03:00.273 18923 18971 E Unity   :   at UnityEngine.AndroidJ
```

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by ImperialCrise** [comment]
i did Deleted the resolved Libraries and clicked Resolve from the external resolver, i got the same error

**Comment by NVentimiglia** [comment]
@ImperialCrise 

The Android build is not including the Google Mobile Ads SDK dependency.  The is usually fixed by using the External Dependency Manager and running Android > Force Resolved. It sounds like you already tried that.

Next steps are :

1. Include an image of your External Dependency Manager Settings.
2. Include a log of the External Dependency Manager Force Resolved Process. We can review this for errors.
3. Include a link to your exported Android Studio project. We can verify the dependencies there.
