### ISSUE TITLE
Google AdMob native ads clickable but Not recording Impressions

### ISSUE THREAD

**Issue by Nazir616** [googleads/googleads-mobile-unity#2607]
I am using GMA version 7.4.1 and Google Admob  Native AddOn latest available .Every thing working fine But on Admob dashboard Admob native ads  showing requests and clicks but zero impressions all time.My code for native advance admob is Here"
/*
CopyRight Reserved

Developer : Ahsan
*/

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GoogleMobileAds.Api;
using GoogleMobileAds.Common;
using UnityEngine.UI;

public class AdmobNative : MonoBehaviour
{
    public bool test;
    public string NativeAdanceID;
    private NativeAd nativeAd;
    [SerializeField] RawImage adIcon;
    [SerializeField] RawImage BodyImage;
    [SerializeField] RawImage adChoices;
    [SerializeField] Text adHeadline;
    [SerializeField] Text adCallToAction;
    [SerializeField] Text adAdvertiser;
    private bool nativeAdLoaded;
    #region Instance
    public static AdmobNative Instance;
    private readonly object bodyText;

    void Awake()
    {
        Instance = this;
    }

    #endregion

    #region CoreFunctions
    void Start()
    {
        if (test)
        {
            NativeAdanceID = "ca-app-pub-3940256099942544/2247696110";
        }
            Requestnative();
       
    }
    private void OnEnable()
    {
        //if (test)
        //{
        //    NativeAdanceID = "ca-app-pub-3940256099942544/2247696110";
        //}

        //Requestnative();
       
    }
    

    void Requestnative()
    {
        AdLoader adLoader = new AdLoader.Builder(NativeAdanceID)
        .ForNativeAd()
        .Build();
        adLoader.OnNativeAdLoaded += this.HandleNativeAdLoaded;
        adLoader.OnAdFailedToLoad += this.HandleAdFailedToLoad;
        adLoader.LoadAd(new AdRequest.Builder().Build());
    }

    private void HandleNativeAdLoaded(object sender, NativeAdEventArgs args)
    {
        Debug.Log("Native ad loaded.");
        this.nativeAd = args.nativeAd;
        nativeAdLoaded = true;
    }

    private void HandleAdFailedToLoad(object sender, AdFailedToLoadEventArgs args)
    {
        //Debug.Log("Native ad failed to load: " + args.Message);
    }
    private void Update()
    {
        if (this.nativeAdLoaded)
        {
            this.nativeAdLoaded = false;
            DisplayAd(nativeAd);
        }
     }
    AdRequest AdRequestBuild()
    {
        return new AdRequest.Builder().Build();
    }

    void DisplayAd(NativeAd ad)
    {
        Texture2D iconTexture = this.nativeAd.GetIconTexture();
        Texture2D iconAdChoices = this.nativeAd.GetAdChoicesLogoTexture();
        if (this.nativeAd.GetImageTextures().Count > 0)
        {
            List<Texture2D> goList = this.nativeAd.GetImageTextures();
            BodyImage.texture = goList[0];
            List<GameObject> list = new List<GameObject>();
            list.Add(BodyImage.gameObject);
            this.nativeAd.RegisterImageGameObjects(list);

        }
        string headline = this.nativeAd.GetHeadlineText();
        string cta = this.nativeAd.GetCallToActionText();
        string advertiser = this.nativeAd.GetAdvertiserText();
        adIcon.texture = iconTexture;
        adChoices.texture = iconAdChoices;
        adHeadline.text = headline;
        adAdvertiser.text = advertiser;
        adCallToAction.text = cta;

        //register gameobjects
        nativeAd.RegisterIconImageGameObject(adIcon.gameObject);
        nativeAd.RegisterAdChoicesLogoGameObject(adChoices.gameObject);
        nativeAd.RegisterHeadlineTextGameObject(adHeadline.gameObject);
        nativeAd.RegisterCallToActionGameObject(adCallToAction.gameObject);
        nativeAd.RegisterAdvertiserTextGameObject(adAdvertiser.gameObject);
      
    }
    void DestroyNative()
    {
        nativeAd.Destroy();
    }

    #endregion

    public void ShowNativeAd()
    {
        Requestnative();
    }
    public void HideNativeAd()
    {
        DestroyNative();
    }
}
Please help me to solve this issue.

**Comment by tera-jet** [comment]
Did you find the solution for this?

**Comment by Nazir616** [comment]
Yes,I used latest google mobile ads sdk and my problem solved.
