### ISSUE TITLE
Preferred Way To Initialize And Load Ads For First Time

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#2612]
Step 1: Describe your environment

Unity version: 2020.3.41f1
- Google Mobile Ads Unity plugin version: 7.4.1
- Platform: Android, IOS
- Mediation ad networks used, and their versions: No

Step 2: Describe the problem
I am curious that Which is the prefered way to initialize and load ads for first time. Inside the MobileAds.Initialize or after that or both are same and safe.

MobileAds.Initialize(initStatus => { });
//Initialize Banner Ad //in case old API
//Load Banner Ad

//Initialize Interstitial Ad //in case old API
//Load Interstitial Ad

//Initialize Rewarded Ad //in case old API
//Load Rewarded Ad

//Initialize Rewarded Inter Ad //in case old API
//Load Rewarded Inter Ad

OR

MobileAds.Initialize(initStatus => { 

//Initialize Banner Ad //in case old API
//Load Banner Ad

//Initialize Interstitial Ad //in case old API
//Load Interstitial Ad

//Initialize Rewarded Ad //in case old API
//Load Rewarded Ad

//Initialize Rewarded Inter Ad //in case old API
//Load Rewarded Inter Ad

});

**Comment by NVentimiglia** [comment]
@MuhammadWaqasOfficial 

The second case. Please load the ads after MobileAds is initialized.


```
MobileAds.Initialize(initStatus => {

//Initialize Banner Ad //in case old API
//Load Banner Ad

//Initialize Interstitial Ad //in case old API
//Load Interstitial Ad

//Initialize Rewarded Ad //in case old API
//Load Rewarded Ad

//Initialize Rewarded Inter Ad //in case old API
//Load Rewarded Inter Ad

});
```
