### ISSUE TITLE
Code Bugs | Spell Mistakes On Google Admob > Mobile Ads (Unity) Page's

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#2613]
Step 1: Describe your environment

- Not Required

Step 2: Describe the problem

Code bugs/Spell mistakes on Google Admob > Mobile Ads (Unity) Page's
- On [SDK Migration](https://developers.google.com/admob/unity/migration#full_screen_formats_now_use_a_static_load_method) Page
   Spell mistake InterstitialAd and LoadError
   
![Migration](https://user-images.githubusercontent.com/32755091/230369303-1cf4bfaf-c34e-44a3-884a-e8f24b72500a.png)

- On [Banner Ads](https://developers.google.com/admob/unity/banner#listen_to_banner_view_events) Page
    => 
    is missing in 
    _bannerView.OnAdFullScreenContentOpened
    _bannerView.OnAdFullScreenContentClosed
     
![BannerEvents](https://user-images.githubusercontent.com/32755091/230367110-36d63f6d-6518-490c-bd11-edd821fe9730.png)

**Comment by NVentimiglia** [comment]
@MuhammadWaqasOfficial 

Thank you! I have confirmed the problem with Interstitial ad and BannerView. The [LoadAdError](https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/GoogleMobileAds/Api/InterstitialAd.cs#L73) looks to be correct.

**Comment by MuhammadWaqasOfficial** [comment]
Still spelling mistake with LoadAdError in interstitial section. 
- Correct Spelling LoadAdError
- Incorrect Spelling LoaAdError (letter d of Load is missing)
On [SDK Migration](https://developers.google.com/admob/unity/migration#full_screen_formats_now_use_a_static_load_method) Page
![Migration](https://user-images.githubusercontent.com/32755091/230542859-328c92e5-0c17-4bee-8ea2-09d0f382820a.png)

**Comment by MuhammadWaqasOfficial** [comment]
=> is still missing in banner events in [Banner Ads](https://developers.google.com/admob/unity/banner#listen_to_banner_view_events) Page
![BannerEvents](https://user-images.githubusercontent.com/32755091/230543417-88dec0f6-d631-4b93-a4eb-26a068ce3f75.png)
