### ISSUE TITLE
[Editor] The Ad Placeholders are not visible due to their sort order value

### ISSUE THREAD

**Issue by AssetKid** [googleads/googleads-mobile-unity#2614]
### Step 1: Describe your environment

  * Unity version: 2021 LTS
  * Google Mobile Ads Unity plugin version: v8.0.0
  * Platform: Unity Editor
  * Platform OS version: N/A
  * Any specific devices issue occurs on: N/A
  * Mediation ad networks used, and their versions: N/A

### Step 2: Describe the problem

The editor ad placeholders have a sort order of zero (0). If you have a canvas in your game with a higher sort order, the placeholders will not show.

#### Steps to reproduce:

1. Open the `Hello World` sample project.
2. Change the `UI` canvas `Sort Order` value to `5`.

![image](https://user-images.githubusercontent.com/40426812/230383286-c34c6885-7e35-467d-aae9-6f672b56833b.png)

3. Enter play mode.
4. Request & show a Banner, Interstitial or Rewarded ad.

The ad placeholders should be visible in the scene but since their canvas `Sort Order` is 0, they **ARE NOT** visible.

Setting the placeholders canvas `Sort Order` to a high value like 999 fixes this issue.

**Comment by MuhammadWaqasOfficial** [comment]
i also submit this bug back sep 20, 2022. Wonder why it still doesn't  resolved yet.
https://github.com/googleads/googleads-mobile-unity/issues/2306
