### ISSUE TITLE
ads not showing in build file

### ISSUE THREAD

**Issue by thomas2000fft** [googleads/googleads-mobile-unity#2615]
hello, i have been created a game with unity and i implemented admob ads to my project and i did everything correctly and ads are showing in unity editor properly but when i build an apk file and test it white phone they are not showing, as if there is no ads in my project, i have been trying to solve this issue for days but i didnt manage to solve it, thank you

**Comment by NVentimiglia** [comment]
@thomas2000fft 

We are going to need more information to triage your unique situation. Please [submit a support request to the support forums](https://groups.google.com/g/google-admob-ads-sdk). Include a sample of your application, publisher id, and affected ad units. A charles log / debug trace would also be helpful.
