### ISSUE TITLE
OnAdFullScreenContentClosed event is trigger delayed after a Video Interstitial is closed

### ISSUE THREAD

**Issue by aceloq** [googleads/googleads-mobile-unity#2616]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: Unity Editor 2020.3.46f1
  * Google Mobile Ads Unity plugin version: Google Ads Mobile Unity 7.4.1
  * Platform: Android
  * Platform OS version: Any
  * Any specific devices issue occurs on: it happened in several of our test devices, like Xiaomi Redmi Note 6 Pro
  * Mediation ad networks used, and their versions: Meta Audience Network v3.9.1

#### Steps to reproduce:

#2029
The same issue persists, I mentioned as a reference.
OnAdFullScreenContentClosed event is triggered with a delay depending on the device after the video interstitial is closed. 

Occurs only in interstitials. It works fine in test ads and using admob test ad units. Occurs only real ads. I'm using Admob mediation and other ad services are fine. It only happens with Admob video interstitial Ads. This issue doesn't happen on all devices. Some devices have issue. For example, the Xiaomi Redmi Note 6 Pro device has a delay of about 2 seconds. I've seen a delay of up to 5 seconds on some low hardware devices.

This is an annoying issue.I hope it will be solved soon.

**Comment by NVentimiglia** [comment]
Hi @aceloq 

This looks like a complex issue outside of the Unity plugin itself. Can you submit a [support request to the admob forums](https://groups.google.com/g/google-admob-ads-sdk). Please include a sample app, publisher id, ad unit ids, and a charles log if possible. Once we have this we will have what we need to solve this issue.

**Comment by aceloq** [comment]
> Hi @aceloq
> 
> This looks like a complex issue outside of the Unity plugin itself. Can you submit a [support request to the admob forums](https://groups.google.com/g/google-admob-ads-sdk). Please include a sample app, publisher id, ad unit ids, and a charles log if possible. Once we have this we will have what we need to solve this issue.

I don't think this issue is ad unit or game related. Because my 2 different games has Admob and both have the same issue. I think sample app not needed. Because when I test the admob unity sample presented here git project with real ad units, there is the same issue. I looked at the forum you sent and there were people had this issue even 3 years ago. But, still unresolved. Also I will share with the logs again.
