### ISSUE TITLE
Error building Player: CommandInvokationFailure: Failed to recompile android resource files with bundle id have "super"

### ISSUE THREAD

**Issue by tnbao91** [googleads/googleads-mobile-unity#262]
I use latest version 3.0.5 when I setup my bundle id to "super.geo.chasing" I got this error

CommandInvokationFailure: Failed to recompile android resource files.
C:/Program Files/Java/jdk1.8.0_31\bin\javac.exe -bootclasspath "D:/Soft/Mobile/android-sdk-windows\platforms\android-24\android.jar" -d "D:\workspace\TortoiseSVN\New Unity Project\Temp\StagingArea\bin\classes" -source 1.6 -target 1.6 -encoding UTF-8 "android\support\v4\R.java" "android\support\v7\appcompat\R.java" "com\google\android\gms\R.java" "com\google\android\gms\ads\R.java" "com\google\android\gms\ads\impl\R.java" "com\google\android\gms\base\R.java" "com\google\android\gms\clearcut\R.java" "com\google\android\gms\drive\R.java" "com\google\android\gms\games\R.java" "com\google\android\gms\nearby\R.java" "com\google\android\gms\tasks\R.java" "com\google\unity\R.java" "super\geo\chasing\R.java"

stderr[
super\geo\chasing\R.java:8: error: <identifier> expected
package super.geo.chasing;
       ^
super\geo\chasing\R.java:8: error: class, interface, or enum expected
package super.geo.chasing;
             ^
super\geo\chasing\R.java:8: error: class, interface, or enum expected
package super.geo.chasing;
              ^
3 errors
]
stdout[

]
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.PostProcessor.Tasks.TasksCommon.Exec (System.String command, System.String args, System.String workingdir, System.String errorMsg)
UnityEditor.Android.PostProcessor.Tasks.BuildResources.CompileResources (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.Tasks.BuildResources.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.HostView:OnGUI()

**Comment by rampara** [comment]
The error log you posted seems to indicate an issue within the file "super\geo\chasing\R.java". I don't see any issues related to the Google Mobile Ads Unity plugin.

**Comment by eanjo7** [comment]
I have the same error in building im stuck for 2 days! :( pls help!

CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Users\myName\AppData\Local\Android\sdk1\build-tools\24.0.2\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I 

"C:/Users/amjo/AppData/Local/Android/sdk1\platforms\android-24\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.google.unity:com.google.android.gms.ads.impl:com.google.android.gms.ads:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.clearcut:com.google.android.gms:com.google.android.gms.tasks:android.support.v4 -S 


Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.

**Comment by rampara** [comment]
Did the JarResolver library run and copy the required Google Play services AARs into the `Assets/Plugins/Android` directory of your Unity project? Can you post the contents of this directory?

**Comment by eanjo7** [comment]
Im using 5.1.1 version of unity, when i delete the jarResolver, and the project. that I see.
the apps succesfuly build, but when I tried it, theres no ads apearing.
i tried this complete tutorial: https://www.youtube.com/watch?v=NR1xOMxLm04

pls help Im strugling for a week :(

**Comment by rampara** [comment]
@eanjo7 the video you linked contains instructions for an outdated version of the plugin. Current integration instructions can be found in our [developer docs](https://firebase.google.com/docs/admob/android/games#requirements). You should not be deleting the JarResolver library. You can force it to run by selecting `Assets -> Google Play Services -> Resolve Client Jars` in the Unity editor. The JarResolver library will copy the required Google Play services AARs to the `Assets/Plugins/Android` directory of your Unity project.

**Comment by eanjo7** [comment]
Hi thankyou for your help and reply.
I managed to build it in new, and everything goes well no bugs and build it succesfully.

BUT, when I installed it, theres no ads showing up, why? is there something in a test version or something to be modified? ads realy not showing.

**Comment by rampara** [comment]
In logcat (under the `Ads` and `Unity` tags) do you see anything that may indicate why you're not receiving ads?

**Comment by rampara** [comment]
Closing as issue was resolved as an environment setup problem.
