### ISSUE TITLE
Why I can`t find the GoogleMobileAds.framework

### ISSUE THREAD

**Issue by gxhdky2345** [googleads/googleads-mobile-unity#263]
Why I can`t find the GoogleMobileAds.framework from the 	link	:	 
https://github.com/googleads/googleads-mobile-unity/releases	.please help me .thank you

**Comment by floatinghotpot** [comment]
This project is only the plugin for Unity. 

The `GoogleMobileAds.framework` is in the AdMob SDK for iOS, get it here:
https://firebase.google.com/docs/admob/ios/download

**Comment by rampara** [comment]
@floatinghotpot is correct. Also, if you have Cocoapods installed on your development machine, the plugin will automatically generate an xcworkspace with the Google Mobile Ads iOS SDK at build time.
