### ISSUE TITLE
Undefined symbols for architecture armv7, arm64 when link iOS binary

### ISSUE THREAD

**Issue by floatinghotpot** [googleads/googleads-mobile-unity#264]
AdMob plugin for Unity, v3.0.5
AdMob SDK for iOS v7.10.0
Unity 5.3.5f1
Xcode v7.3.1
iOS SDK v9.3

Error log:
```
Undefined symbols for architecture armv7:
  "_GADUShowRewardBasedVideoAd", referenced from:
      _Externs_GADUShowRewardBasedVideoAd_m892979392 in Bulk_Assembly-CSharp_2.o
      _RewardBasedVideoAdClient_ShowRewardBasedVideoAd_m553031711 in Bulk_Assembly-CSharp_2.o
     (maybe you meant: _Externs_GADUShowRewardBasedVideoAd_m892979392)
  "_GADURewardBasedVideoAdReady", referenced from:
      _Externs_GADURewardBasedVideoAdReady_m2978385106 in Bulk_Assembly-CSharp_2.o
      _RewardBasedVideoAdClient_IsLoaded_m2511569259 in Bulk_Assembly-CSharp_2.o
     (maybe you meant: _Externs_GADURewardBasedVideoAdReady_m2978385106)
... ...
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbols for architecture arm64:
  "_GADUShowRewardBasedVideoAd", referenced from:
      _Externs_GADUShowRewardBasedVideoAd_m892979392 in Bulk_Assembly-CSharp_2.o
      _RewardBasedVideoAdClient_ShowRewardBasedVideoAd_m553031711 in Bulk_Assembly-CSharp_2.o
     (maybe you meant: _Externs_GADUShowRewardBasedVideoAd_m892979392)
  "_GADURewardBasedVideoAdReady", referenced from:
      _Externs_GADURewardBasedVideoAdReady_m2978385106 in Bulk_Assembly-CSharp_2.o
      _RewardBasedVideoAdClient_IsLoaded_m2511569259 in Bulk_Assembly-CSharp_2.o
     (maybe you meant: _Externs_GADURewardBasedVideoAdReady_m2978385106)
... ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Exactly the same error as other two guys reported on Stackoverflow, but no answer yet.
See:
* http://stackoverflow.com/questions/38365633/unity-ios-build-error-in-xcode-at-admob-library
* http://stackoverflow.com/questions/34855271/google-mobile-ads-in-unity-ios-shows-error

Note: I followed the docs, and use mod_pbxproj to change the xcode project file.
```python
    project.add_flags( {
            'ENABLE_BITCODE' : 'NO',
            'CLANG_ENABLE_MODULES': 'YES',
            'IPHONEOS_DEPLOYMENT_TARGET': '6.0',
            'OTHER_LDFLAGS':'-ObjC $(inherited)'
        } )
```

And, also double check, the GoogleMobileAds.framework is in the list of frameworks to link, and it does contains the architecture armv7 and arm64.
```bash
$ cd GoogleMobileAds.framework/
$ lipo -info GoogleMobileAds
Architectures in the fat file: GoogleMobileAds are: armv7 armv7s i386 x86_64 arm64
```

And here is the last command line to trigger the error:
`
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -L/Users/liming/workspace/Unity/tanku5ios/Target/ios/build/Release-iphoneos -L/Users/liming/workspace/Unity/tanku5ios/Target/ios/3pp/ShareSDK/Support/PlatformSDK/WeChatSDK -L/Users/liming/workspace/Unity/tanku5ios/Target/ios/../../../../../../../usr/lib -L/Users/liming/workspace/Unity/tanku5ios/Target/ios -L/Users/liming/workspace/Unity/tanku5ios/Target/ios/Libraries -F/Users/liming/workspace/Unity/tanku5ios/Target/ios/build/Release-iphoneos -F/Users/liming/workspace/Unity/tanku5ios/Target/ios/3pp/GoogleAds -F/Users/liming/workspace/Unity/tanku5ios/Target/ios/3pp/ShareSDK -F/Users/liming/workspace/Unity/tanku5ios/Target/ios/3pp/ShareSDK/Support/Optional -F/Users/liming/workspace/Unity/tanku5ios/Target/ios/3pp/ShareSDK/Support/PlatformSDK/QQSDK -F/Users/liming/workspace/Unity/tanku5ios/Target/ios/3pp/ShareSDK/Support/Required -filelist /Users/liming/workspace/Unity/tanku5ios/Target/ios/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/tankcraft.LinkFileList -Xlinker -map -Xlinker /Users/liming/workspace/Unity/tanku5ios/Target/ios/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/tankcraft-LinkMap-normal-arm64.txt -miphoneos-version-min=6.0 -dead_strip -weak_framework CoreMotion -weak-lSystem -ObjC -ObjC -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -liPhone-lib -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework CFNetwork -framework CoreGraphics -framework CoreLocation -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -weak_framework iAd -framework MediaPlayer -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -framework GameKit -framework GoogleMobileAds -framework ShareSDK -framework ShareSDKExtension -framework ShareSDKUI -framework TencentOpenAPI -lWeChatSDK -framework MOBFoundation -framework ShareSDKConnector -framework AdSupport -framework CoreBluetooth -framework CoreTelephony -framework EventKit -framework EventKitUI -framework Foundation -framework MobileCoreServices -framework SafariServices -framework SystemConfiguration -framework StoreKit -framework JavaScriptCore -framework ImageIO -framework GameKit -lz -lstdc++ -licucore -lsqlite3 -Xlinker -dependency_info -Xlinker /Users/liming/workspace/Unity/tanku5ios/Target/ios/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/tankcraft_dependency_info.dat -o /Users/liming/workspace/Unity/tanku5ios/Target/ios/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/tankcraft
`

**Comment by rampara** [comment]
I'm having trouble reproducing this error. Have you modified the plugin? If not, can you link me to a stripped down sample project where you can reproduce the issue.

**Comment by floatinghotpot** [comment]
Thanks for the prompt reply and the very important tips. 

I made a very very stupid mistake. I carelessly removed the objc files under Plugins/iOS, as it looks very similar to the header files in framework.

Now I re-extract the objc files from `GoogleMobileAds.unitypackage`, and it builds pass.

You saved my day. Thanks!
