### ISSUE TITLE
Missing dependencies cause crash when registering AppStateChanged callback

### ISSUE THREAD

**Issue by aaronflippo** [googleads/googleads-mobile-unity#2645]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.29.f1
  * Google Mobile Ads Unity plugin version: 8.8.0
  * Platform: Android
  * Platform OS version: Android 11 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem

Calling this during startup (to register app stage change events for OnOpen ads):

	AppStateEventNotifier.AppStateChanged += OnAppStateChanged;
	

Results in the following exception:
2023-04-12 11:44:43.679 13474-13538/? E/Unity: AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/DefaultLifecycleObserver;
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/DefaultLifecycleObserver;
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
     Caused by: java.lang.ClassNotFoundException: androidx.lifecycle.DefaultLifecycleObserver
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method) 
        at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0) 
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20) 
      at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
      at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x00000] in <00000000000000000000000000000000>:0 
      at UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) [0x00000] in <00000

#### Steps to reproduce:

1. Try to execute the following code: AppStateEventNotifier.AppStateChanged += OnAppStateChanged;

It looks like an important dependency may have been removed in commit 598e82e:
https://github.com/googleads/googleads-mobile-unity/commit/598e82e48b7b19ba8bbc3d4c6a70fa9b27d4fe63

Adding these lines back into the GoogleMobileAdDependencies.xml file fixes this for me:

  <androidPackage spec="androidx.lifecycle:lifecycle-common-java8:2.4.1">
    <repositories>
      <repository>https://maven.google.com/</repository>
    </repositories>
  </androidPackage>
  <androidPackage spec="androidx.lifecycle:lifecycle-process:2.4.1">
    <repositories>
      <repository>https://maven.google.com/</repository>
    </repositories>
  </androidPackage>

#### Relevant Code:

```
See above
```

**Comment by NVentimiglia** [comment]
@aaronflippo 

I am glad you found a work around, that said the dependencies should have resolved on their own as they are included by the google mobile ads aar file.

Can you help us out by including a log of your external dependency manager resolution process?

` Assets > External Dependency Manager > Android Resolver >  Force Resolve`

**Comment by DavianMachete** [comment]
> ### Step 0: Are you in the right place?
> ### [REQUIRED] Step 1: Describe your environment
> * Unity version: 2020.29.f1
> * Google Mobile Ads Unity plugin version: 8.8.0
> * Platform: Android
> * Platform OS version: Android 11 (eg iOS 10, Android 9)
> * Any specific devices issue occurs on: _____
> * Mediation ad networks used, and their versions: _____
> 
> ### [REQUIRED] Step 2: Describe the problem
> Calling this during startup (to register app stage change events for OnOpen ads):
> 
> ```
> AppStateEventNotifier.AppStateChanged += OnAppStateChanged;
> ```
> 
> Results in the following exception: 2023-04-12 11:44:43.679 13474-13538/? E/Unity: AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/DefaultLifecycleObserver; java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/DefaultLifecycleObserver; at com.unity3d.player.UnityPlayer.nativeRender(Native Method) at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0) at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:223) at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20) Caused by: java.lang.ClassNotFoundException: androidx.lifecycle.DefaultLifecycleObserver at com.unity3d.player.UnityPlayer.nativeRender(Native Method)  at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)  at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)  at android.os.Handler.dispatchMessage(Handler.java:102)  at android.os.Looper.loop(Looper.java:223)  at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)  at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x00000] in <00000000000000000000000000000000>:0 at UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) [0x00000] in <00000
> 
> #### Steps to reproduce:
> 1. Try to execute the following code: AppStateEventNotifier.AppStateChanged += OnAppStateChanged;
> 
> It looks like an important dependency may have been removed in commit [598e82e](https://github.com/googleads/googleads-mobile-unity/commit/598e82e48b7b19ba8bbc3d4c6a70fa9b27d4fe63): [598e82e](https://github.com/googleads/googleads-mobile-unity/commit/598e82e48b7b19ba8bbc3d4c6a70fa9b27d4fe63)
> 
> Adding these lines back into the GoogleMobileAdDependencies.xml file fixes this for me:
> 
> https://maven.google.com/ https://maven.google.com/
> #### Relevant Code:
> ```
> See above
> ```

This worked for me too, just added the removed lines. Thank you...

**Comment by ThinhHB** [comment]
Thanks @aaronflippo , that worked for me!

**Comment by faisalameerCS** [comment]
Adding the following dependencies in the GoogleMobileAdsDependencies.xml worked for me.

<androidPackage spec="androidx.lifecycle:lifecycle-process:2.7.0">
	<repositories>
		<repository>https://maven.google.com/</repository>
	</repositories>
</androidPackage>

**Comment by rdavdin** [comment]
> Adding the following dependencies in the **GoogleMobileAdsDependencies.xml** worked for me.
> 
> ```
> <androidPackage spec="androidx.lifecycle:lifecycle-process:2.7.0">
> 	<repositories>
> 		<repository>https://maven.google.com/</repository>
> 	</repositories>
> </androidPackage>
> ```

This worked for me with compileSdkVersion 34

**Comment by aaronflippo** [comment]
Just popping in to say this is still an issue with the latest plugin in Unity 2022.3, with the latest dependency manager.
The fix still works.

> @aaronflippo
> 
> I am glad you found a work around, that said the dependencies should have resolved on their own as they are included by the google mobile ads aar file.
> 
> Can you help us out by including a log of your external dependency manager resolution process?
> 
> ` Assets > External Dependency Manager > Android Resolver > Force Resolve`

Sorry for not getting back to you earlier - where would I find this log?

**Comment by dcosmin-97** [comment]
Yes, this should be opened again.

**Comment by VirtueSky** [comment]
598e82e48b7b19ba8bbc3d4c6a70fa9b27d4fe63 This way is very effective. However, if you import Google Mobile Ads using UPM, it won't work every time you pull/push the source.

**Comment by VirtueSky** [comment]
https://github.com/googleads/googleads-mobile-unity/releases/tag/v10.4.2
Lifecycle was added back in version 10.4.2
