### ISSUE TITLE
This feature requires ASM7

### ISSUE THREAD

**Issue by Nyankoo** [googleads/googleads-mobile-unity#2650]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: _____
  * Google Mobile Ads Unity plugin version: 8.0.0
  * Platform: Android
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem

As it seems issue #2559 will not be re-opened, I open a new bug report as this is still an issue.

The AdMob plugin should work with recent versions of Unity, which it currently does not.

**Comment by NVentimiglia** [comment]
@Nyankoo 

Can you provide me some additional details :


- How are you generating this error? Are you building from Unity or is this a gradle build?
- What version of Java and Gradle are you building against?
- Are there any other plugins installed with Admob?

**Comment by voidreader** [comment]
I also faced this issue too under Unity 2021.3 & Java 1.8

**Comment by AllanRW** [comment]
also have this issue, the workaround I found is to downgrade the API level to 30 than make a build, when I get back to level 33 it works, but sometimes starts to fail again and I have to repeat the process.

**Comment by ihcy-hub** [comment]
Simultaneous import with AppLovin MAX Unity triggers This feature requires ASM7

**Comment by KevinTydlacka** [comment]
I'm also seeing this after upgrading AdMob plugin from 7.2.0 to 8.1.0.

- Building from Unity (2021.3.9f1).
- Default Unity JDK (1.8.0_152) and Android SDK/NDK.
- Targeting API 31, minimum 24.
- Downloading and using an updated Gradle version (6.9.4) does not resolve the issue
- Clean building, deleting Unity Project's `Bee` directory does not resolve the issue.
- Disabling R8, using AndroidX/enabling Jetifire do not resolve the issue.

The interesting bit is that we also are manually integrating the AppLovin MAX `.unitypackage` (among many others). A bare Unity project with just the AdMob plugin builds fine for Android, but I see this error once I add the AppLovin MAX plugin.

Is there some dependency magic that is backfiring when AdMob has to play well with some other packages?

**Comment by KevinTydlacka** [comment]
@NVentimiglia any insight on this?

**Comment by hiro5238** [comment]
Try it.
I was able to solve the problem.   
- Unity 2021.3.25f1
- Google Mobile Ads Unity Plugin v8.2.0
- Gradle v6.9.4  [Gradle Releases](https://gradle.org/releases/)
- baseProjectTemplate.gradle
```
dependencies {
   classpath 'com.android.tools.build:gradle:4.2.0'
   **BUILD_SCRIPT_DEPS**
}
```

[Android Gradle plugin release notes Older versions](https://developer.android.com/build/releases/gradle-plugin#expandable-1)
[AppLovin-MAX-Unity-Plugin Issues #153](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/153)

**Comment by NVentimiglia** [comment]
> I'm also seeing this after upgrading AdMob plugin from 7.2.0 to 8.1.0.
> 
> * Building from Unity (2021.3.9f1).
> * Default Unity JDK (1.8.0_152) and Android SDK/NDK.
> * Targeting API 31, minimum 24.
> * Downloading and using an updated Gradle version (6.9.4) does not resolve the issue
> * Clean building, deleting Unity Project's `Bee` directory does not resolve the issue.
> * Disabling R8, using AndroidX/enabling Jetifire do not resolve the issue.
> 
> The interesting bit is that we also are manually integrating the AppLovin MAX `.unitypackage` (among many others). A bare Unity project with just the AdMob plugin builds fine for Android, but I see this error once I add the AppLovin MAX plugin.
> 
> Is there some dependency magic that is backfiring when AdMob has to play well with some other packages?

Thank you for the clear reproduction steps.

**Comment by Nyankoo** [comment]
@NVentimiglia I assume this is fixed in the next update?
