### ISSUE TITLE
Code Correction in Documentation

### ISSUE THREAD

**Issue by ankitbourasi0** [googleads/googleads-mobile-unity#2651]
there  is a code error in the documentation of the interstitial ad example 
void RegisterReloadHandler(InterstitialAd ad)
    {
        // Raised when the ad closed full-screen content.
        ad.OnAdFullScreenContentClosed += ()
        {
            Debug.Log("Interstitial Ad full screen content closed.");

            // Reload the ad so that we can show another as soon as possible.
            LoadInterstitialAd();
        };
        //
missing arrow function 
expected ()=>
found ()

**Comment by NVentimiglia** [comment]
@ankitbourasi0 

This should be fixed now, thank you.
