### ISSUE TITLE
UMP - ConsentInformation.Update - too long timeout - bug?

### ISSUE THREAD

**Issue by MichalKlacko** [googleads/googleads-mobile-unity#2652]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.1.21f
  * Google Mobile Ads Unity plugin version: 8.0.0
  * Platform: iOS
  * Platform OS version: 16.3.1.
  * Any specific devices issue occurs on:  all devices
  * Mediation ad networks used, and their versions: none

### [REQUIRED] Step 2: Describe the problem

It seems that UPM consent form has way too long "timeout" configured. 
I used sample code from here: https://developers.google.com/admob/unity/privacy and add it on startup of my game (this code is run as a very first line/s of code as I want to get consent before I initialise MobileAds or other analytic tools). It works perfectly but when I test it with very slow internet connection or with (100% packet loss via debug options) it just keeps hanging for almost a minute before it results in error.
I didn't find any option how to configure timeout.

I don't know if this is intended or If i'm using it in wrong way, but for me it's a major issue as most users would kill the app if it would be loading for a minute on first start. Other tools (including Ads part of this SDK MobileAds) has more reasonable timeouts, but 60 seconds seems more like a bug.

From debugging I find out it's stuck on:

`ConsentInformation.Update(request, OnConsentInfoUpdated);`

Edit: In case of No internet connection - all runs fine. Problem is only when internet is faulty, very slow or high packet loss) easiest to replicate is to use iOS build in Network limiter with 100% loss option.

Thanks for any info on how to resolve this.

**Comment by NVentimiglia** [comment]
@MichalKlacko 

Thank you for bringing this to my attention. Let me take a look and get back to you.

**Comment by NVentimiglia** [comment]
This should be resolved in the latest release.
