### ISSUE TITLE
Feature Request : Banner Ad Position For Middle Left And Middle Right

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#2657]
Step 1: Describe your environment

  * Unity version: Not Required
  * Google Mobile Ads Unity plugin version: Not Required
  * Platform: Not Required
  * Platform OS version: Not Required

Step 2: Describe the problem

Please Add Option Of Banner Ad Position For Middle Left And Middle Right in GoogleMobileAds.Api.AdPosition

namespace GoogleMobileAds.Api
{
    public enum AdPosition
    {
        Top,
        Bottom,
        TopLeft,
        TopRight,
        BottomLeft,
        BottomRight,
        Center
    }
}

**Comment by NVentimiglia** [comment]
Hi @MuhammadWaqasOfficial 

We do support [custom positioning for banner views](https://developers.google.com/admob/unity/banner#optional_create_a_banner_view_with_a_custom_position).

```
// Create a 320x50 banner ad at coordinate (0,50) on screen.
_bannerView = new BannerView(_adUnitId, AdSize.Banner, 0, 50);
```

**Comment by MuhammadWaqasOfficial** [comment]
you are right that we have custom positioning for banner. But isn't convenient to add mentioned positions in by default.
thanks. just saying.

**Comment by NVentimiglia** [comment]
@MuhammadWaqasOfficial 

That is fair, I will suggest this as a feature request.
