### ISSUE TITLE
Consent Request About Precompiled Assemblies

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#2658]
Step 1: Describe your environment

  * Unity version: 2021.3.23f1
  * Google Mobile Ads Unity plugin version: 7.4.1
  * Platform: Unity Editor

  * Any specific devices issue occurs on: Consent Request About Precompiled Assemblies
 Step 2: Describe the problem
When i import GMA Unity 7.4.1 this popup appears. Will i let 'Unity's API's Updater'  update these assemblies?
![popup](https://user-images.githubusercontent.com/32755091/233077535-4465b79e-3411-44ee-ae33-6213e8bb002e.png)

**Comment by MuhammadWaqasOfficial** [comment]
If i press no, this consent popup keep reappearing. When i click yes. unity turns Plugins->Android->GoogleMobileAdsPlugin.androidlib folder to file, Named GoogleMobileAdsPlugin in unity. However i see it in file explorer it is still GoogleMobileAdsPlugin.androidlib folder.
i think its not impact the workflow. its the same thing.

Sorry for such a naïve question but its better to understand the reason.

**Comment by NVentimiglia** [comment]
@MuhammadWaqasOfficial 

To support all versions of unity, we must build our SDK on older versions of Unity engine. As a result, newer installs of Unity need to update the SDK binaries. Please click yes, you should use a Unity engine binary which is compatible with your specific Unity install.
