### ISSUE TITLE
Handlers have not been called

### ISSUE THREAD

**Issue by duchanhleo** [googleads/googleads-mobile-unity#266]
My handlers have not been called. When I call show ad, it still show up normally. Anyone get the same issue?
`isLoadingInterstitial = true;
			interstitial = new InterstitialAd (Ids.ADMOB_INTERSTITIAL_ID);
			// Register for ad events.
			interstitial.OnAdLoaded += HandleInterstitialLoaded;
			interstitial.OnAdFailedToLoad += HandleInterstitialFailedToLoad;
			interstitial.OnAdOpening += HandleInterstitialOpened;
			interstitial.OnAdClosed += HandleInterstitialClosed;
			interstitial.OnAdLeavingApplication += HandleInterstitialLeftApplication;`

**Comment by rampara** [comment]
Are you seeing this issue on Android or on iOS? Are you able to reproduce the issue in the [sample application](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) from this repository?

**Comment by wloczykij89** [comment]
I'm seeing this issue only on iOS. Sometimes it works correctly, but it often happens that It cannot receive interstitial.OnAdClosed event :/

**Comment by rampara** [comment]
Are you able to reproduce the issue in sample application included in this repository? Are you using the latest version of the GMA iOS SDK? Are you seeing this issue with across all creative (including test ad creative)?

**Comment by wloczykij89** [comment]
Hey, nevermind. I've seen it in a number of projects, but the bug was on my side. I'm sorry to bother your head but that bug was very tricky and I was very desperate :p
So, events and all stuff works really great! Tested on Android & iOS.

**Comment by rampara** [comment]
Glad you were able to resolve the problem. Closing the issue. @duchanhleo please re-open if the issue persists for you.
