### ISSUE TITLE
BannerClient.Dispose() for iOS causes error

### ISSUE THREAD

**Issue by dfruit** [googleads/googleads-mobile-unity#267]
public void Dispose()
        {
            DestroyBannerView();
            ((GCHandle)bannerViewPtr).Free();
        }

public void DestroyBannerView()
        {
            Externs.GADURemoveBannerView(BannerViewPtr);
            BannerViewPtr = IntPtr.Zero;
        }

When calling BannerClient.Dispose() for iOS, bannerViewPtr will be set to IntPtr.Zero before being converted to GCHandle and called Free() on. This may cause an error. Also a local variable, bannerClientPtr, created in CreateBannerView() as a CGHandle instance, has never been freed. This may cause a memory leak. Guess this bannerClientPtr variable should be the one that is meant to be freed in Dispose().

**Comment by rampara** [comment]
Good catch. This has been fixed in the latest version of the plugin (3.0.6) with change propagated to all ad formats.
