### ISSUE TITLE
Interstitial events are not called on the main Unity thread

### ISSUE THREAD

**Issue by cobbertine** [googleads/googleads-mobile-unity#2676]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.8f1
  * Google Mobile Ads Unity plugin version: 8.1.0
  * Platform: Android
  * Platform OS version: Target: API 33
  * Any specific devices issue occurs on: Tested on a device running Android 8.0.0
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem

Interstitial ad events do not occur on the main Unity thread, despite setting "MobileAds.RaiseAdEventsOnUnityMainThread" to true. Depending on what actions are taken in this event call-back, this may result in the application crashing. Below, I have some code that demonstrates this, and here is what the logcat output looks like when the interstitial test ad is closed:

```
04-25 17:12:52.738  7594  7872 I Unity   : Is this the main thread? False
04-25 17:12:52.738  7594  7872 I Unity   :
--------- beginning of crash

```

The crash observered here occurred when enabling a TextMeshPro UI object. No crash occurred when enabling a normal Text UI object.

NOTE: This issue will only occur on an Android device, when testing it out on the PC in the Unity editor, the interstitial event is called on the main Unity thread.

#### Steps to reproduce:

**Option 1:**
- Download the supplied Unity Asset file and import it into a new Unity project

**Option 2:**
- Create a new Unity project
- Create a new script called "TestAdmobThreadingIssue.cs" and add the code below into it
- Create a Canvas object and a TextMeshPro object under that
- De-activate the TextMeshPro object in the inspector
- Create a new GameObject and add the TestAdmobThreadingIssue component to it
- Drag the TextMeshPro object from the Inspector into the "uiObject" field

**In both cases:**
- Make sure the Unity project is on the Android platform
- Imported the Admob SDK (v8.1.0)
- Ensure the TextMeshPro package + extras are included in the project
- Build and run the app on an Android phone with logcat running. 
- Close the interstitial ad when it appears
- Observe the logcat output

#### Relevant Code:

```cs
using UnityEngine;
using GoogleMobileAds.Api;

public class TestAdmobThreadingIssue : MonoBehaviour
{
    // A TextMeshPro UI object under the canvas object.
    [SerializeField]
    private GameObject uiObject = null;
    // Official Test ID
    private string interstitialAdUnitID = "ca-app-pub-3940256099942544/1033173712";
    private System.Threading.Thread unityThread =  null;
    private InterstitialAd interstitial = null;

    private void Start()
    {
        this.unityThread = System.Threading.Thread.CurrentThread;

        MobileAds.RaiseAdEventsOnUnityMainThread = true;
        MobileAds.Initialize(initStatus => {});         

        InterstitialAd.Load(interstitialAdUnitID, new AdRequest.Builder().Build(), (InterstitialAd ad, LoadAdError loadAdError) =>
        {
            this.interstitial = ad;

            if(this.interstitial != null)
            {
                this.interstitial.OnAdFullScreenContentClosed += () => 
                {
                    // Output can be false, despite `RaiseAdEventsOnUnityMainThread = True`
                    print($"Is this the main thread? {(System.Threading.Thread.CurrentThread.ManagedThreadId == this.unityThread.ManagedThreadId)}");
                    // Activating GameObject from the background thread; this will cause a crash.
                    this.uiObject.SetActive(true);
                };

                if(this.interstitial.CanShowAd() == true)
                {
                    this.interstitial.Show();
                }
            }
        });
    }
}
```
[AdmobThreadIssue.zip](https://github.com/googleads/googleads-mobile-unity/files/11320733/AdmobThreadIssue.zip)

**Comment by cobbertine** [comment]
I have created a pull request that fixes this here: #2678

**Comment by TheGoodEvilBen** [comment]
I just wanted to mention that this problem exists for rewarded interstitials as well.

**Comment by NVentimiglia** [comment]
Confirmed, thank you.
