### ISSUE TITLE
MediationExtras conflicts in AdColony Mediation 

### ISSUE THREAD

**Issue by Kaosc** [googleads/googleads-mobile-unity#2677]
* Unity version: 2021.3.23f1 
  * Google Mobile Ads Unity plugin version: 8.0.0
  * Platform: Android
  * Platform OS version: Android 12
  * Any specific devices issue occurs on: none
  * Mediation ad networks used, and their versions: Adcolony: 2.6.1

Specified warning appears in unity editor console:

``` bash
Assets\GoogleMobileAds\Api\Mediation\AdColony\AdColonyMediationExtras.cs(5,44): warning CS0436: 
The type 'MediationExtras' in 'Assets/GoogleMobileAds/Api/Mediation/MediationExtras.cs' conflicts with the imported type 
'MediationExtras' in 'GoogleMobileAds.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'. 
Using the type defined in 'Assets/GoogleMobileAds/Api/Mediation/MediationExtras.cs'.
```

**Comment by NVentimiglia** [comment]
Thank you, b/279765851 for reference.

**Comment by NVentimiglia** [comment]
@Kaosc 

Looking into this issue I was unable to reproduce the problem. Can you try uninstalling the plugin and adapter and trying again?
