### ISSUE TITLE
Crashes on Android: libmonochrome.so

### ISSUE THREAD

**Issue by Davidnovarro** [googleads/googleads-mobile-unity#2680]
* Unity version: 2021.3.21f1
  * Google Mobile Ads Unity plugin version: 8.0.0
  * Platform: Android
  * Platform OS version: Android 11, 12
  * Any specific devices issue occurs on Samsung a21 (Galaxy A21), Samsung a20p (Galaxy A20)
  * Mediation ad networks used, and their versions: Applovin 6.6.0, IronSource 7.3.0.0
  
I confirm that this issue is related to Admob SDK, it happens right after AdActivity screen as reported by Firebase Crashlytics 

[FATAL:output_surface_provider_webview.cc(81)] Non-owned context lost!
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 7974 >>> com.cooperbit.brawlparty <<<

backtrace:
  #00  pc 0x00000000027dc2c8  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #01  pc 0x0000000003487088  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #02  pc 0x00000000052d8364  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #03  pc 0x0000000003131148  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #04  pc 0x0000000003193a78  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #05  pc 0x0000000003191320  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #06  pc 0x000000000304e278  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #07  pc 0x0000000001a1b148  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #08  pc 0x00000000034928bc  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #09  pc 0x0000000003492b50  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #10  pc 0x0000000001a1b148  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #11  pc 0x0000000003492fa4  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #12  pc 0x0000000003493638  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #13  pc 0x00000000034859dc  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #14  pc 0x00000000034843f0  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #15  pc 0x000000000348d1a0  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #16  pc 0x000000000347bee8  /data/app/~~UIdZaX1ZCQUBcDzQsYmmHQ==/com.google.android.webview-HgjTmNDoD5DhmBSiSmvymQ==/base.apk!libmonochrome.so
  #17  pc 0x0000000000002488  /system/lib64/libwebviewchromium_plat_support.so (android::(anonymous namespace)::draw_gl(int, void*, android::uirenderer::DrawGlInfo const&, android::uirenderer::WebViewOverlayData const&)+312)
  #18  pc 0x00000000007535cc  /system/lib64/libhwui.so (android::uirenderer::WebViewFunctor::drawGl(android::uirenderer::DrawGlInfo const&)+140)
  #19  pc 0x0000000000752f48  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::GLFunctorDrawable::onDraw(SkCanvas*)+1120)
  #20  pc 0x0000000000723ef0  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+88)
  #21  pc 0x0000000000912068  /system/lib64/libhwui.so (SkGpuDevice::drawDrawable(SkDrawable*, SkMatrix const*, SkCanvas*)+352)
  #22  pc 0x0000000000731b00  /system/lib64/libhwui.so (android::uirenderer::$_36::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.17071800435366954541)+128)
  #23  pc 0x0000000000582afc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+3572)
  #24  pc 0x0000000000581b90  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+240)
  #25  pc 0x00000000004e4bbc  /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.17071800435366954541)+84)
  #26  pc 0x0000000000582afc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+3572)
  #27  pc 0x0000000000581b90  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+240)
  #28  pc 0x00000000004e4bbc  /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.17071800435366954541)+84)
  #29  pc 0x0000000000582afc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+3572)
  #30  pc 0x0000000000581b90  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+240)
  #31  pc 0x00000000004e4bbc  /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.17071800435366954541)+84)
  #32  pc 0x0000000000582afc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+3572)
  #33  pc 0x0000000000581b90  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+240)
  #34  pc 0x00000000004e4bbc  /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.17071800435366954541)+84)
  #35  pc 0x0000000000582afc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+3572)
  #36  pc 0x0000000000581b90  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+240)
  #37  pc 0x00000000004e4bbc  /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.17071800435366954541)+84)
  #38  pc 0x0000000000582afc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+3572)
  #39  pc 0x0000000000581b90  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+240)
  #40  pc 0x00000000005cb2cc  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrameImpl(SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, bool, android::uirenderer::Rect const&, SkCanvas*, SkMatrix const&)+572)
  #41  pc 0x00000000005c82f4  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrame(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, bool, android::uirenderer::Rect const&, sk_sp<SkSurface>, SkMatrix const&)+164)
  #42  pc 0x00000000005c7e38  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, android::uirenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, android::uirenderer::FrameInfoVisualizer*)+432)
  #43  pc 0x000000000063b76c  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+1484)
  #44  pc 0x000000000063a0f8  /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c1671e787f244890c877724752face20+784)
  #45  pc 0x000000000064b774  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+156)
  #46  pc 0x000000000064b4dc  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+84)
  #47  pc 0x000000000001223c  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+260)
  #48  pc 0x0000000000011acc  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+404)
  #49  pc 0x00000000000ed048  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264)
  #50  pc 0x000000000008b1c0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

**Comment by NVentimiglia** [comment]
Thank you,

I do not see any reference to the Unity plugin or SDK in this stack trace, but I will run this by the android team to see if there is anything we can do. b/279766934 for reference.

**Comment by NVentimiglia** [comment]
@Davidnovarro 

Looking into this issue it does not appear to be caused by the Google Unity plugin. This may however be caused by the Google Mobile Ads SDK, but I can not confirm this. Can you please open up a support ticket on [the google mobile ads sdk support group?](https://groups.google.com/g/google-admob-ads-sdk)

**Comment by daniellochner** [comment]
Hi there. I am experiencing the same issue.

**Comment by vfilho** [comment]
The same here and yet guys. May somebody help us with this?

**Comment by Sohail8338** [comment]
Hi. There. Experiencing the game using latest version of GMA plugin and untiy 2022.3.11 Lts
#00  pc 0x00000000050975ec  /data/app/~~oX2VzooAmDLqvoUdfrDRQw==/com.google.android.webview-LDVu0vouUdCD6n9pMjEIjg==/base.apk!libmonochrome.so

**Comment by Bernabeu33** [comment]
I have the same problem, how can I solve it and I need your help

**Comment by chaoshengyuan** [comment]
I have the same problem, how can I solve it and I need your help.

[FATAL:crashpad_client_linux.cc(745)] Render process (23891)'s crash wasn't handled by all associated  webviews, triggering application crash.




backtrace:
  #00  pc 0x0000000004adc4d0  /data/app/~~F3twGqpr23aALCgCCmTXLw==/com.google.android.trichromelibrary_642216533-ERaflBwpyx09pRNOmMN5Eg==/base.apk!libmonochrome_64.so (BuildId: c064be5ff2a235a357349c021663865bc1608cc9)
  #01  pc 0x0000000006a44b8c  /data/app/~~F3twGqpr23aALCgCCmTXLw==/com.google.android.trichromelibrary_642216533-ERaflBwpyx09pRNOmMN5Eg==/base.apk!libmonochrome_64.so (BuildId: c064be5ff2a235a357349c021663865bc1608cc9)
  #02  pc 0x0000000004adc594  /data/app/~~F3twGqpr23aALCgCCmTXLw==/com.google.android.trichromelibrary_642216533-ERaflBwpyx09pRNOmMN5Eg==/base.apk!libmonochrome_64.so (BuildId: c064be5ff2a235a357349c021663865bc1608cc9)
  #03  pc 0x0000000007c6e560  /data/app/~~F3twGqpr23aALCgCCmTXLw==/com.google.android.trichromelibrary_642216533-ERaflBwpyx09pRNOmMN5Eg==/base.apk!libmonochrome_64.so (BuildId: c064be5ff2a235a357349c021663865bc1608cc9)
  #04  pc 0x00000000028091c8  /data/app/~~F3twGqpr23aALCgCCmTXLw==/com.google.android.trichromelibrary_642216533-ERaflBwpyx09pRNOmMN5Eg==/base.apk!libmonochrome_64.so (BuildId: c064be5ff2a235a357349c021663865bc1608cc9)
  #05  pc 0x0000000004b1de5c  /data/app/~~F3twGqpr23aALCgCCmTXLw==/com.google.android.trichromelibrary_642216533-ERaflBwpyx09pRNOmMN5Eg==/base.apk!libmonochrome_64.so (BuildId: c064be5ff2a235a357349c021663865bc1608cc9)
  #06  pc 0x000000000746b844  /data/app/~~F3twGqpr23aALCgCCmTXLw==/com.google.android.trichromelibrary_642216533-ERaflBwpyx09pRNOmMN5Eg==/base.apk!libmonochrome_64.so (BuildId: c064be5ff2a235a357349c021663865bc1608cc9)
  #07  pc 0x000000000746b7ec  /data/app/~~F3twGqpr23aALCgCCmTXLw==/com.google.android.trichromelibrary_642216533-ERaflBwpyx09pRNOmMN5Eg==/base.apk!libmonochrome_64.so (BuildId: c064be5ff2a235a357349c021663865bc1608cc9)
  #08  pc 0x0000000004b45c80  /data/app/~~F3twGqpr23aALCgCCmTXLw==/com.google.android.trichromelibrary_642216533-ERaflBwpyx09pRNOmMN5Eg==/base.apk!libmonochrome_64.so (BuildId: c064be5ff2a235a357349c021663865bc1608cc9)
  #09  pc 0x0000000000018184  /system/lib64/libutils.so (android::Looper::pollInner(int)+916)
  #10  pc 0x0000000000017d84  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+116)
  #11  pc 0x0000000000152eb4  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+48)
  #12  pc 0x00000000001a45dc  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+108)
  #13  pc 0x0000000000507058  /system/framework/arm64/boot-framework.oat (android.os.MessageQueue.next+232)
  #14  pc 0x00000000005046d4  /system/framework/arm64/boot-framework.oat (android.os.Looper.loopOnce+100)
  #15  pc 0x00000000005045d4  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+516)
  #16  pc 0x00000000002da32c  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread.main+732)
  #17  pc 0x0000000000218be8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568)
  #18  pc 0x000000000028600c  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+220)
  #19  pc 0x000000000062cc48  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1388)
  #20  pc 0x000000000059b3e8  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+56)
  #21  pc 0x00000000000b2f74  /apex/com.android.art/javalib/arm64/boot.oat (art_jni_trampoline+132)
  #22  pc 0x00000000007bccbc  /system/framework/arm64/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+140)
  #23  pc 0x00000000007c517c  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2652)
  #24  pc 0x0000000000218be8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568)
  #25  pc 0x000000000028600c  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+220)
  #26  pc 0x000000000062d3d0  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+452)
  #27  pc 0x000000000062d8c4  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+96)
  #28  pc 0x0000000000503d70  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+620)
  #29  pc 0x00000000000b0bf8  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124)
  #30  pc 0x00000000000bd0fc  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+840)
  #31  pc 0x0000000000002684  /system/bin/app_process64 (main+1580)
  #32  pc 0x000000000004a088  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+100)

**Comment by PenceOnly** [comment]
I have the same problem, Many prompt webview crashes，Is there a good solution？

**Comment by trdin** [comment]
I have the same problem, any updates ?

**Comment by JerryMu** [comment]
same problem
