### ISSUE TITLE
Set Location Feature Required.

### ISSUE THREAD

**Issue by kenglou** [googleads/googleads-mobile-unity#269]
Hi,

I wish to know that is that a way to set the Location of Target Ads in AdRequest? I see it inside the documentation but unfortunately not able to be found in Unity3d Plugins.

Thank you.

**Comment by rampara** [comment]
Which documentation are you referring to? Currently, providing location based targeting information is not supported in the Unity plugin.

**Comment by rampara** [comment]
The GMA SDK will automatically use location data from users who have granted your apps permission to do so. More information can be found in this [help center article](https://support.google.com/admob/answer/6373176?hl=en).
