### ISSUE TITLE
Slow Application/Scene loading time

### ISSUE THREAD

**Issue by AllanonPP** [googleads/googleads-mobile-unity#2694]
* Unity version: 2020.3.38f1
  * Google Mobile Ads Unity plugin version: 8.1.0
  * Platform: Android

I can't give any exact data. But the application loading time and the transition between scenes have greatly increased (about 10-15 seconds). FPS has gone down a lot in the app.
version 8.0.0 and version 8.1.0
Tested on dozens of devices. Everywhere is the same.

I had to roll back to version 7.3.1
There is no such problem, but there are problems with ANR

* no other changes were made during the tests. The code has not been edited.

Guys, please release a stable version.

**Comment by NVentimiglia** [comment]
@AllanonPP 

Can you provide your settings, replication steps or a sample application? Looking at the hello world sample, I see no issue/slowdown in loading scenes.
