### ISSUE TITLE
Banner video ads - feature request

### ISSUE THREAD

**Issue by MagicForest342** [googleads/googleads-mobile-unity#2703]
Is it possible to implement video ads in banners?

**Comment by NVentimiglia** [comment]
Hi @MagicForest342 

Admob banner ads support text, image, rich media (html), and video as content.  Please see [this help center article on how to make sure your banner ads are set up to accept video ads](https://support.google.com/admob/answer/7311346?hl=en). That said, the ad serving process is complex, and is not directly controlled by the ad/game publisher.
