### ISSUE TITLE
App  crashes when requesting ad (IOS)

### ISSUE THREAD

**Issue by Byte-Size-Coder** [googleads/googleads-mobile-unity#2710]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.13
  * Google Mobile Ads Unity plugin version: 8.1.0
  * Platform: IOS (iOS, Android, Unity Editor)
  * Platform OS version: recent versions we test on our devices
  * Any specific devices issue occurs on: just all IOS devices currently

#### Steps to reproduce:

I created an issue a month or so ago that is now closed https://github.com/googleads/googleads-mobile-unity/issues/2589 I was told in the latest release that it would have the fix. When I checked the latest release notes, there was no indication that this issue was fixed. I also then Updated to the last release  and tested and the same issue was occuring as highlighted in this issue. I was unsure what to do in regards as I made a comment on it but never got a response so I decided to create a new issue.

The following is screenshot of the error appears when the crash happens. It seems to be something related to UI:
 
![image](https://github.com/googleads/googleads-mobile-unity/assets/14350613/25cb629e-5616-409a-96fb-ae5a789bf8dd)

![image](https://github.com/googleads/googleads-mobile-unity/assets/14350613/1222ca38-0d67-4d11-9075-419eb01170c5)

![image](https://github.com/googleads/googleads-mobile-unity/assets/14350613/179ef4e7-268e-4cc5-bafc-d162b467650a)

#### Relevant Code:

Here is the area in code (we have a Ad manager script that has this method that is called when requesting ad)

```
     private void RequestRewardedAd(string adUnitId)
    {
        currentRewardedAdID = adUnitId;
        // Create an empty ad request.
        AdRequest request = new AdRequest.Builder().Build();
#if UNITY_IOS
        // setting this to "1" means no personalize ads, "0" or not set means personalize ad
        string personalizeAdResult = PlayerPrefs.GetString(PlayerPrefKey.PERSONALIZED_ADS, "1");

        request.Extras.Add("npa", personalizeAdResult);
#endif
        // Load a new ad with using the id
        //OnRewardedAdLoaded is called once add is loaded or has failed to load
        MobileAdsEventExecutor.ExecuteInUpdate(() =>
        {
            RewardedAd.Load(adUnitId, request, OnRewardedAdLoaded);
        });
    }

    private void HandleRewardedAdLoaded(RewardedAd rewardedAd,LoadAdError loadAdError)
    {
        if (!rewardedAd.CanShowAd() || debugAdFail)
        {
            HandleRewardedAdFailedToLoad(loadAdError);
            return;
        }
        

        RewardedAdLoadedEvent.Instance.Invoke();
        // Called when an ad is shown.
        rewardedAd.OnAdFullScreenContentOpened += HandleRewardedAdOpening;
        // Called when an ad request failed to show.
        rewardedAd.OnAdFullScreenContentFailed += HandleRewardedAdFailedToShow;
        // Called when the ad is closed.
        rewardedAd.OnAdFullScreenContentClosed += HandleRewardedAdClosed;

        MobileAdsEventExecutor.ExecuteInUpdate(() =>
        {
            rewardedAd.Show(HandleUserEarnedReward);
        });

    }
```

If you need anything else please do not hesitate to ask! Thank you.

**Comment by armando0820** [comment]
private void RequestRewardedAd(string adUnitId)
    {
        currentRewardedAdID = adUnitId;
        // Create an empty ad request.
        AdRequest request = new AdRequest.Builder().Build();
#if UNITY_IOS
        // setting this to "1" means no personalize ads, "0" or not set means personalize ad
        string personalizeAdResult = PlayerPrefs.GetString(PlayerPrefKey.PERSONALIZED_ADS, "1");

        request.Extras.Add("npa", personalizeAdResult);
#endif
        // Load a new ad with using the id
        //OnRewardedAdLoaded is called once add is loaded or has failed to load
        MobileAdsEventExecutor.ExecuteInUpdate(() =>
        {
            RewardedAd.Load(adUnitId, request, OnRewardedAdLoaded);
        });
    }

    private void HandleRewardedAdLoaded(RewardedAd rewardedAd,LoadAdError loadAdError)
    {
        if (!rewardedAd.CanShowAd() || debugAdFail)
        {
            HandleRewardedAdFailedToLoad(loadAdError);
            return;
        }
        

        RewardedAdLoadedEvent.Instance.Invoke();
        // Called when an ad is shown.
        rewardedAd.OnAdFullScreenContentOpened += HandleRewardedAdOpening;
        // Called when an ad request failed to show.
        rewardedAd.OnAdFullScreenContentFailed += HandleRewardedAdFailedToShow;
        // Called when the ad is closed.
        rewardedAd.OnAdFullScreenContentClosed += HandleRewardedAdClosed;

        MobileAdsEventExecutor.ExecuteInUpdate(() =>
        {
            rewardedAd.Show(HandleUserEarnedReward);
        });

    }
.

**Comment by NVentimiglia** [comment]
Hi @Byte-Size-Coder 

- I would like to help but looking at this issue it may require me to reach out to other experts and the [help forum](https://groups.google.com/g/google-admob-ads-sdk) may be a better channel to raise this concern. If we can not solve this issue quickly, I recommend reaching out there and include a link to this issue, a full (txt) crash log , a charles/network log so we also be helpful, and a sample application or steps to replicate this in the hello world sample if possible.

- Looking at the `HandleRewardedAdLoaded` implementation, I see a misuse of MobileAdsEventExecutor. All events should use implement `ExecuteInUpdate` in their handlers. The rule is : "if the line of code could or does touch any Unity element, it should be included in the `ExecuteInUpdate` callback. 

- For instance :

```
   private void RequestRewardedAd(string adUnitId)
    {
        currentRewardedAdID = adUnitId;
        // Create an empty ad request.
        AdRequest request = new AdRequest.Builder().Build();
#if UNITY_IOS
        // setting this to "1" means no personalize ads, "0" or not set means personalize ad
        string personalizeAdResult = PlayerPrefs.GetString(PlayerPrefKey.PERSONALIZED_ADS, "1");

        request.Extras.Add("npa", personalizeAdResult);
#endif
        // Load a new ad with using the id
        //OnRewardedAdLoaded is called once add is loaded or has failed to load
        MobileAdsEventExecutor.ExecuteInUpdate(() =>
        {
            RewardedAd.Load(adUnitId, request, OnRewardedAdLoaded);
        });
    }

    private void HandleRewardedAdLoaded(RewardedAd rewardedAd,LoadAdError loadAdError)
    {
        // Called when an ad is shown.
        rewardedAd.OnAdFullScreenContentOpened += HandleRewardedAdOpening;
        // Called when an ad request failed to show.
        rewardedAd.OnAdFullScreenContentFailed += HandleRewardedAdFailedToShow;
        // Called when the ad is closed.
        rewardedAd.OnAdFullScreenContentClosed += HandleRewardedAdClosed;

        MobileAdsEventExecutor.ExecuteInUpdate(() =>
        {
            if (!rewardedAd.CanShowAd() || debugAdFail)
            {
                // This event might touch Unity elements.
                HandleRewardedAdFailedToLoad(loadAdError);
                return;
            }
            rewardedAd.Show(HandleUserEarnedReward);
            // This event might touch Unity elements.
            RewardedAdLoadedEvent.Instance.Invoke();
        });

    }
```

Additionally I would make sure each handler registered above (HandleRewardedAdClosed, HandleRewardedAdOpening, ect) uses the MobileAdsEventExecutor in a similar way.


Additionally you may look into using [RaiseAdEventsOnUnityMainThread ](https://developers.google.com/admob/unity/quick-start#raise_ad_events_on_the_unity_main_thread) to simplify this code.

Hope this helps, looking forward to hearing back with additional details.

**Comment by Byte-Size-Coder** [comment]
@NVentimiglia By taking your advice and adding the "ExecuteInUpdate" method everywhere I believe it fixed the problem. Hopfully can confirm this in the next few days. Thank you for the reply and apologizes it took a bit to respond.

**Comment by NVentimiglia** [comment]
@Byte-Size-Coder happy to help.
