### ISSUE TITLE
No overload for method `DoResolution` takes `3` arguments

### ISSUE THREAD

**Issue by Boscillator** [googleads/googleads-mobile-unity#272]
I'm getting that error after installing the package.
The full text is `Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs(113,47): error CS1501: No overload for method `DoResolution' takes `3' arguments`.

I also have google play games services installed.

Thanks in advance!

**Comment by nb05** [comment]
Same issue

**Comment by nb05** [comment]
I had same issue just comment the line and enjoy.
working with ads and google play service.

finally.

**Comment by frankiefanstar** [comment]
same issue,googleads-mobile-unity version 3.0.7 ,Unity 4.7.0

**Comment by frankiefanstar** [comment]
Refer to _**PlayServicesResolver/Editor/ResolverVer1_1.cs**_
I change the error line from 
```
PlayServicesResolver.Resolver.DoResolution(
                    GPGSDependencies.svcSupport,
                    "Assets/Plugins/Android",
                    PlayServicesResolver.HandleOverwriteConfirmation);
```
to
```
PlayServicesResolver.Resolver.DoResolution(
                    GPGSDependencies.svcSupport,
                    "Assets/Plugins/Android",
                    PlayServicesResolver.HandleOverwriteConfirmation,
					() => {});
```
the error is gone.

**Comment by rampara** [comment]
This issue should be resolved in the latest version of the plugin (v.3.1.0).
