### ISSUE TITLE
RewardedInterstitialAd events are not called on the main Unity thread

### ISSUE THREAD

**Issue by TheGoodEvilBen** [googleads/googleads-mobile-unity#2728]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.16f1
  * Google Mobile Ads Unity plugin version: 7.4.1
  * Platform: Android
  * Platform OS version: Target: API 33
  * Any specific devices issue occurs on: Tested on different devices with different Android versions
  * Mediation ad networks used, and their versions: 

#### Steps to reproduce:

Rewarded interstitial ad events do not occur on the main Unity thread, despite setting "MobileAds.RaiseAdEventsOnUnityMainThread" to true. Depending on what actions are taken in this event call-back, this may result in the application crashing.

This problem was already mentioned in the issue https://github.com/googleads/googleads-mobile-unity/issues/2676

#### Relevant Code:

As you can see here: https://github.com/googleads/googleads-mobile-unity/blob/v8.2.0/source/plugin/Assets/GoogleMobileAds/Api/RewardedInterstitialAd.cs

The events are still called via 

`_client.OnAdClicked += () =>
            {
                if (OnAdClicked != null)
                {
                    OnAdClicked();
                }
            };
`
            
but should be called via

`
_client.OnAdClicked += () =>
            {
             MobileAds.RaiseAction(() =>
                {
                    if (OnAdClicked != null)
                    {
                        OnAdClicked ();
                    }
                });
            };
`

**Comment by NVentimiglia** [comment]
Hi @TheGoodEvilBen 

We have confirmed the issue and a fix will be available with the next release. Thank you for raising awareness. 

Let me know if you need any additional support.
