### ISSUE TITLE
8.2.0 version is not working on iOS

### ISSUE THREAD

**Issue by Davidnovarro** [googleads/googleads-mobile-unity#2729]
#### Environment

  * Unity version: 2021.3.25f1
  * Google Mobile Ads Unity plugin version: 8.2.0
  * Platform: iOS
  * Platform OS version: iOS 16
  * Any specific devices issue occurs on Any iOS device
  * Mediation ad networks used, and their versions: Applovin, IronSource, Meta, Unity Ads

#### Issue

When using the 8.2.0 version on iOS I get "called the non-existent method" exceptions, it seems like Unity strips Admob assemblies. Here are some exception examples.

Exception: Error: called non-existent method System.Collections.Generic.HashSet`1<System.String> GoogleMobileAds.Api.AdRequest::get_Keywords()...

Exception: Error: called non-existent method GoogleMobileAds.Api.MaxAdContentRating GoogleMobileAds.Api.RequestConfiguration::get_MaxAdContentRating()...

#### Steps to reproduce:

Just build a sample app on iOS using the provided SDK / Unity Engine versions

**Comment by DenizPiri** [comment]
We are experiencing the same issue on our side. However for us, we have the same errors on Android too. We use the "Medium" stripping level on both Android and iOS.

**Comment by DenizPiri** [comment]
When we change the stripping level to "Minimum", it still doesn't work for us.

Always getting this exception:

```
Exception: Error: called non-existent method System.Collections.Generic.HashSet`1<System.String> GoogleMobileAds.Api.AdRequest::get_Keywords()
GoogleMobileAds.Api.AdRequest.get_Keywords () (at <00000000000000000000000000000000>:0)
GoogleMobileAds.iOS.Utils.BuildAdRequest (GoogleMobileAds.Api.AdRequest request, System.String nativePluginVersion) (at <00000000000000000000000000000000>:0)
GoogleMobileAds.iOS.RewardedAdClient.LoadAd (System.String adUnitID, GoogleMobileAds.Api.AdRequest request) (at <00000000000000000000000000000000>:0)
```

We also tried specifically preserving AdRequest class via the link.xml file, it still doesn't work.

**Comment by NVentimiglia** [comment]
@DenizPiri 

Thank you for raising awareness, I am looking into this issue.

I was able to replicate this issue. That said, I think I may have a work around - I did not replicate the issue when I broke apart the code into multiple lines.

```
        var age = MaxAdContentRating.G;
        // Configure TagForChildDirectedTreatment and test device IDs.
        var rc =
            new RequestConfiguration.Builder()
            .SetTagForChildDirectedTreatment(TagForChildDirectedTreatment.Unspecified)
            .SetMaxAdContentRating(age)
            .SetTestDeviceIds(deviceIds);
        var requestConfiguration = rc.build();
        UnityEngine.Debug.Log(requestConfiguration.MaxAdContentRating);
        MobileAds.SetRequestConfiguration(requestConfiguration);
```

**Comment by NVentimiglia** [comment]
@DenizPiri 

I think the issue may be solved by reinstalling the plugin. I reverted my changes with the exception of `.SetMaxAdContentRating(MaxAdContentRating.G)`, and rebuilt/ran the project on device. 

This time I did not experience the exception at all. 

The only difference is I made sure I uninstalled my plugin and [installed 8.2.0 first](https://github.com/googleads/googleads-mobile-unity/releases/tag/v8.2.0). I also deleted my iOS project folder to make sure it was clean.

Please let me know if this helps.

**Comment by DenizPiri** [comment]
Ok, I think I know what the problem was.
![image](https://github.com/googleads/googleads-mobile-unity/assets/519796/352ed35f-c8c8-4596-a852-f049816190c2)

When I did the admob upgrade on my PC, SVN (we use TortoiseSVN) was simply not picking some of those files up as modified. In our case, this was GoogleMobileAds.Android.dll, however, the GoogleMobileAds.Core.dll was committed. So, GoogleMobileAds.Android was trying to use the property version of the `Extras` member, which now is a simple public field in GoogleMobileAds.Core.

Simply moving that folder away, doing an SVN update, then copying the contents of the moved away folder back in made SVN pick up the modifications. After a commit, it all works fine now on both Android and iOS platforms!

**Comment by Davidnovarro** [comment]
I confirm, removing the SDK and a clean reinstall solves the problem
