### ISSUE TITLE
Fail to instantiate adapter

### ISSUE THREAD

**Issue by icyh4mmer** [googleads/googleads-mobile-unity#274]
I implemented vungle mediation, Vungle itself is already working, but when I'm trying to load ads trough admob, i get "no fill" error and log warning: 

"W/Ads(29158): Fail to instantiate adapter com.vungle.mediation.VungleAdapter"

I downloaded VungleAdapter and put it in to Plugins/Android folder. I use this code for initalization and loading: 

```
RewardBasedVideoAd rewardBasedVideo;
AdRequest adRequest;
rewardBasedVideo = RewardBasedVideoAd.Instance;
adRequest = new AdRequest.Builder().Build();
rewardBasedVideo.LoadAd(adRequest, videoAdUnitId);
```

Does anyone have any idea what could be the issue here?

**Comment by rampara** [comment]
Is there anything else in logcat, either from the GMA SDK or Vungle SDK, that may indicate the cause of the adapter failing to instantiate? If you share a project where you reproduce the issue, it would help me investigate.

**Comment by icyh4mmer** [comment]
Hi, I figured out what's the issue. PlayservicerResolver or more exactly AdMobDependencies.cs was importing .aar files with "LATEST" version which in my case imported 9.4.0 aar-s. I changed this line to:  `svcSupport.DependOn("com.google.android.gms", "play-services-ads", "8.4.0"); `
and now everything works properly as it was supposed to.

**Comment by rampara** [comment]
If you're using the latest vungle SDK and adapter, you should be able to use (and would want to take take advantage of new features and bug fixes) the latest version of Google Play services.

**Comment by icyh4mmer** [comment]
I'm aware of that, but it simply doesn't work :(
