### ISSUE TITLE
pangle Adapter not found

### ISSUE THREAD

**Issue by realluhui** [googleads/googleads-mobile-unity#2741]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.2.19f1
  * Google Mobile Ads Unity plugin version: 8.2.0
  * Platform: Android
  * Platform OS version: Android 8.1.0
  * Any specific devices issue occurs on: Any Android device
  * Mediation ad networks used, and their versions: Applovin 6.7.0  Meta AudienceNetwork 3.10.0  Pangle 2.1.0

### [REQUIRED] Step 2: Describe the problem

After successful initialization of admob,  Call  MobileAds.OpenAdInspector To Check, It Show Pangle Adapter not found, Other Mediation ad networks is ok.

**Comment by NVentimiglia** [comment]
Hi @realluhui 

Can you please submit this issue to the [Google SDK help forum?](https://groups.google.com/g/google-admob-ads-sdk). Please include your publisher id and affect ad units when making this request. Additionally, a charles log of the problem may also be needed.
