### ISSUE TITLE
Amazon Admob Mediation Vungle: Regarding Google Play Site Display Issues

### ISSUE THREAD

**Issue by crSudo** [googleads/googleads-mobile-unity#2742]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: Unity 2020.3.38f1
  * Google Mobile Ads Unity plugin version: GoogleMobileAds-v7.4.1
  * Platform: Amazon
  * Platform OS version: FireOS 8.3.1.8
  * Mediation ad networks used, and their versions: VungleUnityAdapter-3.9.2

### [REQUIRED] Step 2: Describe the problem
※I am Japanese. I am translating using Google Translate. Please let us know if you have any misunderstandings.

When you touch the screen with an end card,
A dialog will open asking you to select "Silk Browser" or "App Store".
If you select "Silk Browser", the GooglePlay site will open instead of the Amazon site.
* "App store" will open the app store in the Amazon device correctly.

#### Steps to reproduce:
1. Launch Unity Editor
2. Import GoogleMobileAds-v7.4.1.unitypackage
3. [Unity Editor Assets> Google Mobile Ads> Settings] Set the AdMob app ID.
4. Import GoogleMobileAdsVungleMediation.unitypackage
5. Copy [samples]-[HelloWorld] of googleads-mobile-unity-main to Unity project.
6. GoogleAdMobController.cs: Change adUnitId in RequestAndLoadInterstitialAd().
7. Execute Unity Editor [Build Setting]-[Export].
8. Start the project in AndroidStudio and create an apk.
9. Launch the app.
10. Select [Request Interstitial Ad].
11. Select [Show Interstitial Ads].
12. After watching the ad, touch the screen.
13. A dialog will open asking you to select "Silk Browser" or "App Store".
14. Select "Silk Browser".

**Comment by NVentimiglia** [comment]
Hi @crSudo I am unfamiliar with [Silk Browser](https://www.amazon.com/Amazon-com-Amazon-Silk-Web-Browser/dp/B01M35MQV4). Can you please post this issue to the [Google ads help forums?](https://groups.google.com/g/google-admob-ads-sdk) They are better equipped to solve this issue.

**Comment by crSudo** [comment]
Understood.
I posted on the Google Ads help forum.

**Comment by NVentimiglia** [comment]
TY!
