### ISSUE TITLE
iOS Bug: Ad callbacks not triggering (reproducible)

### ISSUE THREAD

**Issue by dethroneofall** [googleads/googleads-mobile-unity#2753]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.23f1
  * Google Mobile Ads Unity plugin version: 8.1.0
  * Platform: iOS (iOS, Android, Unity Editor)
  * Platform OS version: 15.4.1 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: any iOS device
  * Mediation ad networks used, and their versions: yes

### [REQUIRED] Step 2: Describe the problem

1. build and run the provided project on iOS
2. open the app and wait for AdMob to initialize and load an ad
3. show ad
4. press the X button on the interstitial test ad to close it
5.  Immediately collapse the game

Expected result: the ad closes and the OnAdClosed callback is triggered
Actual result: the ad closes but the OnAdClosed callback is NOT triggered

MobileAdsEventExecutor.ExecuteInUpdate not helped 

using [the sample code from this repository](https://github.com/googleads/googleads-mobile-unity/blob/master/samples/HelloWorld/Assets/Scripts/GoogleAdMobController.cs) and [the official guide](https://developers.google.com/admob/unity/interstitial)

#### Relevant Code:

```

```

**Comment by NVentimiglia** [comment]
@dethroneofall 

Which ad format and mediation adapters are being used here?

**Comment by dethroneofall** [comment]
> @dethroneofall
> 
> Which ad format and mediation adapters are being used here? I will need additional details in in order to replicate and triage this issue.

AppLovin and Meta
but that's not the problem here
I have the same problem as here
https://github.com/googleads/googleads-mobile-unity/issues/1879

**Comment by NVentimiglia** [comment]
@dethroneofall 

I still need more information to go ahead and triage this case. Can you please can you please open a support case on the on the [help forum](https://groups.google.com/g/google-admob-ads-sdk)? Please reference this issue, the mediation networks used, the ad formats affected, and include the problematic ad unit ids.

**Comment by dethroneofall** [comment]
> @dethroneofall
> 
> I still need more information to go ahead and triage this case. Can you please can you please open a support case on the on the [help forum](https://groups.google.com/g/google-admob-ads-sdk)? Please reference this issue, the mediation networks used, the ad formats affected, and include the problematic ad unit ids.

hi, no one is replying on the forum
I say that the bug on the link is still there and + is played if you press the X button and collapse the application very quickly

**Comment by NVentimiglia** [comment]
@dethroneofall 

- Please link me to the forum post so I can take a look. The forum post allows me to escalate the issue to other departments and get the right people involved to fix the issue.
- I am still having trouble understanding the issue. To properly triage the issue I will need to know which ad formats are involved and potentially the ad unit Ids and a charles log / network trace.
