### ISSUE TITLE
Hello World doesn't use demo ad unit IDs

### ISSUE THREAD

**Issue by stewartmiles** [googleads/googleads-mobile-unity#276]
There are demo Ad unit IDs e.g https://github.com/firebase/quickstart-cpp/blob/master/admob/testapp/src/common_main.cc#L57 why not use them in the Hello World sample to reduce the amount of setup a user needs to do before they display an ad.

**Comment by rampara** [comment]
Resolved in 244d4bb417d971827689d4b4c4b536ad2d41f307.
