### ISSUE TITLE
Can I use the sdk on the Unity WebGL Platform?

### ISSUE THREAD

**Issue by alexfiftyfour** [googleads/googleads-mobile-unity#277]
Hi,

is it possible that I build and integrate the sdk in my Unity WebGL game?

Thanks,

Alex

**Comment by rampara** [comment]
This plugin integrates the Google Mobile Ads SDK into Android and iOS mobile applications. Since the GMA SDK does not support WebGL, this plugin can't be used to integrate AdMob and DoubleClick ads into WebGL applications.
