### ISSUE TITLE
error when building unexpected element <property> found in <manifest><application>.

### ISSUE THREAD

**Issue by RomainBitard** [googleads/googleads-mobile-unity#2770]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.21f1
  * Google Mobile Ads Unity plugin version: latest
  * Platform: android 
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: unity ads latest

#### Steps to reproduce:
I added the unityads adapter and when I build I get
.gradle\caches\transforms-2\files-2.1\d7ed882264ea80439f05351530561451\com.unity3d.ads.unity-ads-4.7.0\AndroidManifest.xml:18:5-113: AAPT: error: unexpected element <property> found in <manifest><application>.

**Comment by RomainBitard** [comment]
it worked perfectly without the adapter, (banner, rewarded and interstitial ads from admob)

**Comment by RomainBitard** [comment]
When I look the androidmanifest that comes with the google unity plugin there is no property element
![image](https://github.com/googleads/googleads-mobile-unity/assets/13960970/51be7041-06fa-42ad-bf52-214eb9574e55)

**Comment by NitroFuNyx** [comment]
Have the same error....

**Comment by RomainBitard** [comment]
> Have the same error....
Do you have the same problem on the sample project ?
I'll try that later

**Comment by RomainBitard** [comment]
I don't know if it works yet because I don't see the unity ads adapter getting initialized unfortunately

**Comment by amoswazana** [comment]
Hey guys, we are running into the same issue when building for Android.
It seems to have been resolved on Unity's end (see link: https://forum.unity.com/threads/android-build-fails-with-unity-ads-4-7-0.1433146/)
In short: we need to update to version 4.7.1.

**Comment by amoswazana** [comment]
@RomainBitard 
Yep, should be soon though.
For now I have tested with Unity SDK 4.6.1 (Plugin version 3.6.1) and it seems to work.

**Comment by NVentimiglia** [comment]
@amoswazana 

Thanks for the research! I will let the mediation folks know.

**Comment by RomainBitard** [comment]
> 
What do you mean we need to update? Is there anything we can do ?

**Comment by amoswazana** [comment]
@RomainBitard 
By "we need to update to 4.7.1" I mean the Google Mobile Ads team needs to update the GoogleMobileAdsUnityAdsMediation.unitypackage file to point to the newest Unity Ads version.
For now we can downgrade to version 3.6.1 of the unitypackage, it seems to work.

**Comment by RomainBitard** [comment]
That's what I understood but I wanted to make sure. I tried to implement
admob sdk on another project and I have this issue even though I didn't use
the unity adapter.
third party libs are horrendous to integrate with unity as far as my
experience goes oO

**Comment by RomainBitard** [comment]
> @RomainBitard By "we need to update to 4.7.1" I mean the Google Mobile Ads team needs to update the GoogleMobileAdsUnityAdsMediation.unitypackage file to point to the newest Unity Ads version. For now we can downgrade to version 3.6.1 of the unitypackage, it seems to work.

I used the latest unity adapter and changed the unity dependency to the 4.7.1 and it worked on my PC. 

Dunno if my whole admob mediation is working though I don't have any adapter showing in the logs even though I call initStatus.getAdapterStatusMap();
Do you know what might be wrong ? 
I have 2 adapters in logs 1 KO one OK (even though I added 4+)
com.google.ads.mediation.admob.AdMobAdapter Description: Failed to initialize adapter. com.google.ads.mediation.admob.AdMobAdapter does not implement the initialize() method. status : not ready.
2023/06/18 23:09:43.433 16615 16646 Info Unity Ads - AdsManager - Adapter: com.google.android.gms.ads.MobileAds status : ready

**Comment by RomainBitard** [comment]
@NVentimiglia @amoswazana any ideas ? I asked on google groups but no ones answered

**Comment by xy2080** [comment]
哈喽，今天我遇到了同样的问题，已经解决啦
1、升级Unity Gradle到6.7.1版本
2、Assets-Plugin-Android-baseProjectTemplate.gradle文件，设置com.android.tools.build:gradle:4.2.1

**Comment by ankittanwar456** [comment]
Thanks @xy2080. It also worked for me.

**Comment by shahrukhhp1** [comment]
A bit late but still if anyone is trying to fix this issue, here's what you can do : 
Goto this file -> `Assets\GoogleMobileAds\Editor\GoogleMobileAdsDependencies.xml`
and change 
`androidPackage spec`
Change to:
`androidPackage spec="com.google.android.gms:play-services-ads:[22.3.0]"`
 
Remember to keep version number in box parenthesis. After this I resolved my dependencies and build the game and it created apk successfully :)

**Comment by fortunacio** [comment]
Official doc: https://github.com/googleads/googleads-mobile-unity/releases

**### Added Editor Options to enable removing the property tag from the Android Manifest of the GMA Android SDK. This is enabled by default for projects using Android Gradle Plugin version 4.2.1 and lower. GMA Android SDK 22.4.0 and above introduces a property tag in its Android Manifest that is not compatible with lower versions of Android Gradle Plugin (used by Unity 2022.1 and below).**

I couldn't find the "editor option" so, for me, changing  play-services-ads:22.6.0 to play-services-ads:22.3.0 works.

Also if you are using auto resolution for Android dependencies you must change this file:
Assets/IronSource/Editor/ISAdMobAdapterDependencies.xml with the correct version, otherwise the autoresolution gonna be overriding your downgrade.

Unity Version: 2021.3.19

**Comment by valerieapps** [comment]
> Official doc: https://github.com/googleads/googleads-mobile-unity/releases
> 
> **### Added Editor Options to enable removing the property tag from the Android Manifest of the GMA Android SDK. This is enabled by default for projects using Android Gradle Plugin version 4.2.1 and lower. GMA Android SDK 22.4.0 and above introduces a property tag in its Android Manifest that is not compatible with lower versions of Android Gradle Plugin (used by Unity 2022.1 and below).**
> 
> I couldn't find the "editor option" so, for me, changing play-services-ads:22.6.0 to play-services-ads:22.3.0 works.
> 
> Also if you are using auto resolution for Android dependencies you must change this file: Assets/IronSource/Editor/ISAdMobAdapterDependencies.xml with the correct version, otherwise the autoresolution gonna be overriding your downgrade.
> 
> Unity Version: 2021.3.19

Go to the menu bar > Assets > Google Mobile Ads > Settings..
You will see the option "Remove property tag from GMA" in the inspector with a check box. Check it and make sure your minimum API is 24 or higher. This will solve the problem without changing play srvices version.

**Comment by vincent-savysoda** [comment]
> A bit late but still if anyone is trying to fix this issue, here's what you can do : Goto this file -> `Assets\GoogleMobileAds\Editor\GoogleMobileAdsDependencies.xml` and change `androidPackage spec` Change to: `androidPackage spec="com.google.android.gms:play-services-ads:[22.3.0]"`
> 
> Remember to keep version number in box parenthesis. After this I resolved my dependencies and build the game and it created apk successfully :)

Sadly I've already tried this but it still doesn't work for me. (This is with Audience Network mediation)

**Comment by alexandrampolta** [comment]
I fixed this by 
cordova platform remove android
cordova platform add android
and the Gradle issue was fixed , don't waste time updating Gradle if already is
