### ISSUE TITLE
GoogleMobileAds 8.3.0 Mediation maio 1.4.3 for iOS: Crash when launching the app.

### ISSUE THREAD

**Issue by crSudo** [googleads/googleads-mobile-unity#2772]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: Unity 2021.3.23f1
  * Google Mobile Ads Unity plugin version: GoogleMobileAds-v8.3.0
  * Platform: iOS
  * Platform OS version: iOS 15.1
  * Mediation ad networks used, and their versions: MaioUnityAdapter-1.4.3

### [REQUIRED] Step 2: Describe the problem
※I am Japanese. I am translating using Google Translate. Please let us know if you have any misunderstandings.

When I launch the app it crashes.

2023-06-15 17:16:18.416522+0900 GMA830MaioU2021[7989:2855864] Error loading /var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/UnityFramework.framework/UnityFramework:  dlopen(/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): Library not loaded: @rpath/MaioOB.framework/MaioOB
  Referenced from: /private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: tried: '/usr/lib/swift/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/UnityFramework.framework/Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/../../Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/UnityFramework.framework/Frameworks/MaioOB.framework/MaioOB' (no such file), '/usr/lib/swift/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/UnityFramework.framework/Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/../../Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/UnityFramework.framework/Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/MaioOB.framework/MaioOB' (no such file), '/System/Library/Frameworks/MaioOB.framework/MaioOB' (no such file)
2023-06-15 17:16:18.418194+0900 GMA830MaioU2021[7989:2855864] Error loading /var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/UnityFramework.framework/UnityFramework:  dlopen(/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): Library not loaded: @rpath/MaioOB.framework/MaioOB
  Referenced from: /private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: tried: '/usr/lib/swift/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/UnityFramework.framework/Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/../../Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/UnityFramework.framework/Frameworks/MaioOB.framework/MaioOB' (no such file), '/usr/lib/swift/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/UnityFramework.framework/Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/../../Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/UnityFramework.framework/Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/FE2E798C-59E3-437C-AB6B-BDC8493FB47D/GMA830MaioU2021.app/Frameworks/MaioOB.framework/MaioOB' (no such file), '/System/Library/Frameworks/MaioOB.framework/MaioOB' (no such file)

#### Steps to reproduce:
 1. Launch Unity Editor
 2. Import GoogleMobileAds-v8.3.0.unitypackage
 3. [Unity Editor Assets> Google Mobile Ads> Settings] Set the AdMob app ID.
 4. Import GoogleMobileAdsMaioMediation.unitypackage
 5. Copy [samples]-[HelloWorld] of googleads-mobile-unity-main to Unity project.
 6. Change [_adUnitId] in InterstitialAdController.cs to the ID created by our company.
 7. Add a script that I created to set [ENABLE_BITCODE] to [NO].
 8. Execute Unity Editor [Build Setting]-[Build].
 9. From the Finder, double-click Unity-iPhone.xcworkspace to launch XCode.
10. Press the Play button to start the application.

The application crashes.

Best Regards
crSudo

**Comment by NVentimiglia** [comment]
Hi @crSudo

Thank you, I was able to confirm the issue. We will look into this and get back to you. b/287474470

**Comment by NVentimiglia** [comment]
Hi @crSudo 

Looking further into this issue :
Library not loaded: @rpath/MaioOB.framework/MaioOB

Seems like the MaioOB framework is not properly linked to the project. If you link MsioOB.xcframework to the app, it should run properly: 
![image](https://github.com/googleads/googleads-mobile-unity/assets/125889/e627890f-c96d-4455-866a-39959543643f)

**Comment by crSudo** [comment]
@NVentimiglia 

We apologize for the delay in getting back to you.
When I added MaioOB.xcframework and ran the app, the following error occurred.
I also tried using the following SDK, but an error occurred.

dyld[1059]: Library not loaded: @rpath/MaioOB.framework/MaioOB
  Referenced from: /private/var/containers/Bundle/Application/73991801-E477-4536-A86B-9F03E636FA33/GMA_8_5_3_Unity2022.app/GMA_8_5_3_Unity2022
  Reason: tried: '/private/var/containers/Bundle/Application/73991801-E477-4536-A86B-9F03E636FA33/GMA_8_5_3_Unity2022.app/Frameworks/MaioOB.framework/MaioOB' (no such file), '/private/var/containers/Bundle/Application/73991801-E477-4536-A86B-9F03E636FA33/GMA_8_5_3_Unity2022.app/Frameworks/MaioOB.framework/MaioOB' (no such file), '/System/Library/Frameworks/MaioOB.framework/MaioOB' (no such file)
(lldb) 

dyld`:
    0x102b829ac <+0>:  mov    x16, #0x209
    0x102b829b0 <+4>:  svc    #0x80
->  0x102b829b4 <+8>:  b.lo   0x102b829d0               ; <+36>
    0x102b829b8 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x102b829bc <+16>: mov    x29, sp
    0x102b829c0 <+20>: bl     0x102b49568               ; cerror_nocancel
    0x102b829c4 <+24>: mov    sp, x29
    0x102b829c8 <+28>: ldp    x29, x30, [sp], #0x10
    0x102b829cc <+32>: ret    
    0x102b829d0 <+36>: ret    

Thread 1: signal SIGABRT

Best Regards
crSudo
