### ISSUE TITLE
GoogleMobileAds 8.3.0 : A warning is output when [samples]-[HelloWorld] is started.

### ISSUE THREAD

**Issue by crSudo** [googleads/googleads-mobile-unity#2773]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: Unity 2021.3.23f1
  * Google Mobile Ads Unity plugin version: GoogleMobileAds-v8.3.0
  * Platform: iOS

### [REQUIRED] Step 2: Describe the problem
※I am Japanese. I am translating using Google Translate. Please let us know if you have any misunderstandings.

When [samples]-[HelloWorld] is executed, the following warning is output to the console.

The referenced script (Unknown) on this Behaviour is missing!
The referenced script on this Behaviour (Game Object 'Txt_Status') is missing!

#### Steps to reproduce:
 1. Launch Unity Editor
 2. Import GoogleMobileAds-v8.3.0.unitypackage
 3. [Unity Editor Assets> Google Mobile Ads> Settings] Set the AdMob app ID.
 4. Copy [samples]-[HelloWorld] of googleads-mobile-unity-main to Unity project.
 5. Open the GoogleMobileAdsScene scene.
 6. Press the Play button to start the application.

Best Regards
crSudo

**Comment by NVentimiglia** [comment]
@crSudo

Thanks Again, I see the issue and will issue a fix.

**Comment by crSudo** [comment]
Thank you for your reply.

I copied [samples]-[HelloWorld] again, but the following error was output.

Problem detected while opening the Scene file: 'Assets/samples/HelloWorld/Assets/Scenes/GoogleMobileAdsScene.unity'.
Check the following logs for more details.
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Prefab instance problem: GoogleMobileAds (Missing Prefab with guid: 14b7f179c2c5148188b1b282d47b96ee)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Best Regards
crSudo
