### ISSUE TITLE
The namespace 'GoogleMobileAds.Api.Mediation' already contains a definition for 'MediationExtras'

### ISSUE THREAD

**Issue by RomainBitard** [googleads/googleads-mobile-unity#2777]
Latest admob and adcolony adapter
Assets\GoogleMobileAds\Mediation\AdColony\Api\MediationExtras.cs(24,27): error CS0101: The namespace 'GoogleMobileAds.Api.Mediation' already contains a definition for 'MediationExtras'

It appears admob adapter brings a duplicate class with it

**Comment by NVentimiglia** [comment]
Duplicate of #2776 2776

**Comment by RomainBitard** [comment]
> Duplicate of #2776 2776

It's not a duplicate :) it's vungle and adcolony adapter that brings a duplicated class

**Comment by NVentimiglia** [comment]
Ty, I will escalate.

**Comment by shefich** [comment]
I have the same issue.
Duplicated class comes with Liftoff Monetize Unity Mediation Plugin Changelog
[Version 4.0.0](https://dl.google.com/googleadmobadssdk/mediation/unity/liftoffmonetize/LiftoffMonetizeUnityAdapter-4.0.0.zip)

**Comment by NVentimiglia** [comment]
@shefich 

Thank you! Looking at [the source](https://github.com/googleads/googleads-mobile-unity/tree/main/mediation/LiftoffMonetize/source/plugin/Assets/GoogleMobileAds/Mediation/LiftoffMonetize/Api) this should not happen. I will get this fixed.

**Comment by shefich** [comment]
@NVentimiglia still waiting for the fix. As I can see Liftoff Monetize Unity Mediation Plugin is 4.0.0 as it was before.

**Comment by NVentimiglia** [comment]
Thanks for the reminder. I have sent a request over to the mediation team to fix this.

**Comment by NVentimiglia** [comment]
Closing as this issue is fixed.
