### ISSUE TITLE
Hello World example not working - Prefab 'GoogleMobileAds' is corrupted

### ISSUE THREAD

**Issue by michalzembron** [googleads/googleads-mobile-unity#2779]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.1f1
  * Google Mobile Ads Unity plugin version: 8.3.0
  * Platform: Unity Editor
  * Platform OS version: Windows 11
  * Any specific devices issue occurs on: No
  * Mediation ad networks used, and their versions: None

### [REQUIRED] Step 2: Describe the problem

After creating a new project, adding the google mobile ads library to it and importing the Hello World sample, I get an error referring to the file 'GoogleMobileAds.prefab':

"Prefab 'GoogleMobileAds.prefab' has unexpected file IDs and is likely to be corrupt"

and when I try to open this prefab I get this error:

"Prefab Variant problem. Missing Prefab Variant parent: 'GoogleMobileAds (Missing Prefab with guid: 14b7f179c2c5148188b1b282d47b96ee)'"

#### Steps to reproduce:

Create a new project, add the Google Mobile Ads library and import Hello World sample.

**Comment by NVentimiglia** [comment]
@michalzembron Confirmed, we will prioritize a fix.
