### ISSUE TITLE
GoogleMobileAds.Ump.Api.FormError

### ISSUE THREAD

**Issue by Nyankoo** [googleads/googleads-mobile-unity#2780]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.27f1
  * Google Mobile Ads Unity plugin version: 8.0.0
  * Platform: Android
  * Platform OS version: Android 10
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: Applovin, Meta

#### Steps to reproduce:

When implementing UMP, the following error is thrown: GoogleMobileAds.Ump.Api.FormError

It seems AdMob is logging this error internally, so I can't get more details on this. Here is the logcat that AdMob logs:
```
2023.06.20 14:16:26.504 25099 25099 Error Unity GoogleMobileAds.Ump.Api.FormError
2023.06.20 14:16:26.504 25099 25099 Error Unity  #0 0x7a15f52d04 (libunity.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #1 0x7a16303530 (libunity.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #2 0x7a15c309a4 (libunity.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #3 0x7a15c30894 (libunity.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #4 0x7a132060fc (libil2cpp.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #5 0x7a1304eee8 (libil2cpp.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #6 0x7a1304ed5c (libil2cpp.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #7 0x7a1304f298 (libil2cpp.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #8 0x7a13097c0c (libil2cpp.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #9 0x7a13f35420 (libil2cpp.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #10 0x7a1461c400 (libil2cpp.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #11 0x7a146209e8 (libil2cpp.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #12 0x7a12fb45f8 (libil2cpp.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #13 0x7a1304ef6c (libil2cpp.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #14 0x7a1304ed5c (libil2cpp.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #15 0x7a15e76208 (libunity.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #16 0x7a15e84ffc (libunity.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #17 0x7a15c6d6ac (libunity.so) ? 0x0
2023.06.20 14:16:26.504 25099 25099 Error Unity  #18 0x7a37eef410 (base.odex) ? 0x0
```

#### Relevant Code:

The implementation is the same as here: https://developers.google.com/admob/unity/privacy

**Comment by NVentimiglia** [comment]
@Nyankoo 

I was unable to see this issue on 8.3.0 running on an Android 10 device. Can you provide any additional details?

**Comment by Nyankoo** [comment]
@NVentimiglia Sadly no, as the exception appears to be thrown inside of the AdMob SDK. I wrapped all calls in try-catch blocks but nothing is propagated upwards for taking a closer look.

I'm currently waiting on the next AdMob update, which hopefully fixes issues mentioned in other issue threads, so I'm unable to test with version 8.3.0.

**Comment by Nyankoo** [comment]
@NVentimiglia Quick question: does the DSGVO form on the AdMob dashboard needs to be published when the call is made? When I want to publish it in the dashboard, it notifies me that I need to add the SDK Code first before publishing. so it's still a draft.
Could this be the issue or should an app update with the SDK be published first before publishing the DSGVO form?

**Comment by NVentimiglia** [comment]
@Nyankoo 

Yes you should [Create GDPR messages for apps
](https://support.google.com/admob/answer/10113207?hl=en&ref_topic=10105230&sjid=6191571710344230491-NA). 

Considering how mysterious this issue is, I suggest you [open a case on the support forum](https://groups.google.com/g/google-admob-ads-sdk). Please include a minimal code sample, your app id, and a reference to this issue.

**Comment by Nyankoo** [comment]
@NVentimiglia Just tested it and yes, the GDPR form needs to be published on the AdMob dashboard, otherwise the exception is thrown.

I feel the documentation is a bit unclear on this and the exception not very helpful. Maybe the exception should give more feedback on this to help other developers running into this?

**Comment by NVentimiglia** [comment]
@Nyankoo 

Correct, you will need to [create and publish the GDPR message first](https://support.google.com/admob/answer/10113207?hl=en).
