### ISSUE TITLE
AppLovin mediation editor script causes error for the iOS build

### ISSUE THREAD

**Issue by majidkh** [googleads/googleads-mobile-unity#2784]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3
  * Google Mobile Ads Unity plugin version: 8.3.0
  * Platform: iOS Editor
  * Platform OS version: Any iOS Version
  * Any specific devices issue occurs on:  All Devices
  * Mediation ad networks used, and their versions: AppLovin

### [REQUIRED] Step 2: Describe the problem

Editor fails to build for the iOS

#### Steps to reproduce:

What happened? How can we make the problem occur?

Add the SDK and build it for iOS

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem

To fix it, change the following:

#if UNITY_IOS

to

#if UNITY_IOS && UNITY_EDITOR

in the AppLovinPostProcessBuild.cs file. 


```

**Comment by NVentimiglia** [comment]
Hi @majidkh 

I have confirmed this issue and am actively working for a fix.

**Comment by majidkh** [comment]
Thanks @NVentimiglia , If you guys can give me permission to submit pull requests, I can submit one for you to merge.

**Comment by NVentimiglia** [comment]
@majidkh 

Please confirm this is still an Issue. I see AppLovinPostProcessBuild.cs  in the Editor folder and that it is working as expected when exporting the iOS project.

**Comment by majidkh** [comment]
Yes it happens for me, see the error below:

GoogleMobileAds/Mediation/AppLovin/Editor/AppLovinPostProcessBuild.cs(18,19): error CS0234: The type or namespace name 'Callbacks' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)

Adding the following on top of the file fixed the issue for me:

#if UNITY_IOS && UNITY_EDITOR

**Comment by NVentimiglia** [comment]
@majidkh What development environment are you using? I am using Unity 2021.3.26f1 and Visual Studio Community.

**Comment by EpsilonD3lta** [comment]
This can be an issue, if like me, you added custom asmdef file (GoogleMobileAds.Runtime in my case) to the top level folder. "Editor" named folder does not work if there is asmdef file up in the hierarchy. It is stated in the documentation in part "Special Folders":
https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html

The correct solution in such case is to add asmdef file to every mediation editor folder MediationName.Editor with Editor platform selected.
