### ISSUE TITLE
Interstitial not showing on Unity Editor

### ISSUE THREAD

**Issue by nimdanet** [googleads/googleads-mobile-unity#2785]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.43f1
  * Google Mobile Ads Unity plugin version: 8.3
  * Platform: Unity Editor
  * Platform OS version: MacOS Ventura 13.0
  * Any specific devices issue occurs on: no
  * Mediation ad networks used, and their versions: no

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Everytime I play interstitial on Editor Unity it freezes and Interstitial is not showed. I discorvered that this "freeze" is because Admob set Time.timeScale = 0 when playing ads so no problems here but since interstitial is never showed the game is stuck. 

More info:
- Banner and Rewarded Video are working normally
- On Mobile (Android and iOS) is working normally

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by NVentimiglia** [comment]
@nimdanet I just took a look at the sample and everything was working fine for me. Can you make sure you are on the latest sample / plugin and provide more detail such as a stack trace?
![image](https://github.com/googleads/googleads-mobile-unity/assets/125889/409abaec-0b98-4d85-a3b9-1aba89dc5c46)

**Comment by nimdanet** [comment]
Hello! In an attempt to get you the logs I saw that "load" was showing right after "show" (this "load" is reloading the ad, not the first load). Then I discovered that I was reloading the ad on OnOpen rather than OnClose. My mistake :( but you helped me a lot finding this with your further questions. Thanks a lot for that.

**Comment by NVentimiglia** [comment]
Glad you got it fixed!
