### ISSUE TITLE
RewardedAd.OnAdPaid callback is never called.

### ISSUE THREAD

**Issue by wwforever-nw** [googleads/googleads-mobile-unity#2788]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.14f
  * Google Mobile Ads Unity plugin version: 8.3.0
  * Platform: iOS, Android (iOS, Android, Unity Editor)
  * Platform OS version: AOS 11, iOS 16 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: both
  * Mediation ad networks used, and their versions: Meta 3.10.0

#### Steps to reproduce:

The RewardedAd.OnAdPaid callback is never called.

When this callback comes, we expect that we have earned advertising revenue and set a local variable to true to reward the user.
For now, this callback is fired in the test ad, but not called in the live build.
Same issue with GoogldAds 7.4.1. When using 6.0.2, the OnUserEarnedReward event fired fine.
Is it ok to replace it with this (Show(Action<Reward> userRewardEarnedCallback)) and treat it as if we expected a return to occur?

Or is it normal that the OnAdPaid callback does not fire in the Google Play Console internal test version? Is it normal that it doesn't happen on iOS test flights as well?
Will OnAdPaid happen when the Google and Apple stores are officially launched?

**Comment by NVentimiglia** [comment]
@wwforever-nw

`RewardedAd.OnAdPaid` is only raised on production builds with test ads disabled.

**Comment by wwforever-nw** [comment]
Thank you for answer.
I checked the log that OnAdPaid was called in the test ad.
Does a production build refer to a release state that can be downloaded by regular users on the Google Play Store?
Or is an internal test version also possible? Of course, test ads are not set up.

**Comment by wwforever-nw** [comment]
Found the same issues here.
It doesn't seem to have been resolved.

https://groups.google.com/g/google-admob-ads-sdk/c/SSXcrOU9lFg?pli=1
https://support.google.com/admob/thread/207623955/onadpaid-appopen-issue?hl=en
https://stackoverflow.com/questions/75475185/problems-with-the-onadpaid-event-admob

**Comment by wwforever-nw** [comment]
I think I've found a solution, but I'm not sure.
We don't know if advertising revenue has occurred because AdPaid didn't come if we rewarded with the callback received from Show.
Can I handle it through Show as it is in the link?
https://groups.google.com/g/google-admob-ads-sdk/c/MZWDDVqxanM

**Comment by wwforever-nw** [comment]
I wonder if advertising revenue occurred when using the Show method.
OnAdPaid is used instead of OnUserEarnedReward, but it seems strange to reward the user unconditionally even though no callback has occurred.
The OnAdPaid event is triggered when the ad is estimated to generate revenue, and I want to give a reward only at this time.
Finally, OnAdPaid works for test ads. Rather, it doesn't happen with formal ads.

**Comment by wwforever-nw** [comment]
Could this possibly be a solution?
https://support.google.com/admob/answer/11322405

**Comment by NVentimiglia** [comment]
@wwforever-nw 

I am not sure that I am following along. Looking at the [sample](https://github.com/googleads/googleads-mobile-unity/blob/main/samples/HelloWorld/Assets/Scripts/RewardedAdController.cs), I was able to log out OnAdPaid and the user reward. Do you have a minimal code example showing this not working?

**Comment by wwforever-nw** [comment]
https://support.google.com/admob/answer/11322405
I set it to the one in the link above and it works fine.
The issue has been resolved.
However, the documentation below seems to be updated. I couldn't find anything related to this issue.
https://developers.google.com/admob/unity/rewarded?hl=en
Thank you for caring so far!
