### ISSUE TITLE
Crash in Android6.0.1

### ISSUE THREAD

**Issue by SamLi0760** [googleads/googleads-mobile-unity#279]
When RewardBasedVideoAd is cache successful ,then i show the RewardBasedVideoAd.....

09-29 17:07:08.338: D/AndroidRuntime(14603): Shutting down VM
09-29 17:07:08.339: E/AndroidRuntime(14603): FATAL EXCEPTION: main
09-29 17:07:08.339: E/AndroidRuntime(14603): Process: com.xl.lrbattle.sjsj, PID: 14603
09-29 17:07:08.339: E/AndroidRuntime(14603): java.lang.Error: FATAL EXCEPTION [main]
09-29 17:07:08.339: E/AndroidRuntime(14603): Unity version     : 5.3.5f1
09-29 17:07:08.339: E/AndroidRuntime(14603): Device model      : LGE Nexus 5X
09-29 17:07:08.339: E/AndroidRuntime(14603): Device fingerprint: google/bullhead/bullhead:6.0.1/MTC20F/3031278:user/release-keys
09-29 17:07:08.339: E/AndroidRuntime(14603): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
09-29 17:07:08.339: E/AndroidRuntime(14603): 	at java.util.regex.Matcher.appendEvaluated(Matcher.java:131)
09-29 17:07:08.339: E/AndroidRuntime(14603): 	at java.util.regex.Matcher.appendReplacement(Matcher.java:111)
09-29 17:07:08.339: E/AndroidRuntime(14603): 	at java.util.regex.Matcher.replaceAll(Matcher.java:319)
09-29 17:07:08.339: E/AndroidRuntime(14603): 	at java.lang.String.replaceAll(String.java:1353)
09-29 17:07:08.339: E/AndroidRuntime(14603): 	at com.google.android.gms.ads.internal.mediation.k.a(:com.google.android.gms.DynamiteModulesA:75)
09-29 17:07:08.339: E/AndroidRuntime(14603): 	at com.google.android.gms.ads.internal.c.b(:com.google.android.gms.DynamiteModulesA:179)
09-29 17:07:08.339: E/AndroidRuntime(14603): 	at com.google.android.gms.ads.internal.reward.mediation.i.run(:com.google.android.gms.DynamiteModulesA:85)
09-29 17:07:08.339: E/AndroidRuntime(14603): 	at android.os.Handler.handleCallback(Handler.java:739)
09-29 17:07:08.339: E/AndroidRuntime(14603): 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-29 17:07:08.339: E/AndroidRuntime(14603): 	at android.os.Looper.loop(Looper.java:148)
09-29 17:07:08.339: E/AndroidRuntime(14603): 	at android.app.ActivityThread.main(ActivityThread.java:5422)
09-29 17:07:08.339: E/AndroidRuntime(14603): 	at java.lang.reflect.Method.invoke(Native Method)
09-29 17:07:08.339: E/AndroidRuntime(14603): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-29 17:07:08.339: E/AndroidRuntime(14603): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by rampara** [comment]
Which version of Google Play services are you compiling your Unity app with?

**Comment by SamLi0760** [comment]
Unity version : 5.3.5f1

**Comment by rampara** [comment]
This issue is not specific to this plugin but the GMA SDK. You should report the issue on the Google Mobile Ads [support forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
