### ISSUE TITLE
how does temporarily stop showing ads?

### ISSUE THREAD

**Issue by Koshei12** [googleads/googleads-mobile-unity#280]
how does temporarily stop showing ads?

**Comment by rampara** [comment]
I'm not sure I understand your question. Are you trying to stop serving ads once you've already distributed your app? If so, you would have to stop ad serving via ad unit configuration settings at [apps.admob.com](https://apps.admob.com/).

**Comment by rampara** [comment]
Closing due to non-response and age of issue.
