### ISSUE TITLE
Nox editor memory issue

### ISSUE THREAD

**Issue by eungyukm** [googleads/googleads-mobile-unity#2800]
### Describe your environment

  * Unity version: Unity 2020.3.48f1
  * Google Mobile Ads Unity plugin version: Admob 8.3.0
  * Platform: Android
  * Platform OS version: Android 7
  * Any specific devices issue occurs on: Nox Player
  * Mediation ad networks used, and their versions: GoogleMobileAds 8.3.0

### Describe the problem

Hello,

I'm contacting you regarding an issue I'm experiencing while implementing AdMob rewarded ads. When applying ads in Unity version 2020.3.48f1, I'm facing a problem where the maximum memory decreases to about 1.8GB.

Here's the code snippet I've used for initialization:

```
Copy code
MobileAds.Initialize((InitializationStatus initStatus) =>
{
    // This callback is called once the MobileAds SDK is initialized.
});
```
To increase the memory, I have created 2000 cubes per second using the following code. However, when doing so, the app terminates due to memory limitations at around 1.8GB. Interestingly, when the plugin is not applied, the memory can reach up to 2.5GB. I'm wondering what could be causing this issue.

The test device I'm using is Nox (64-bit) with Android 7, 4 CPU cores, and 4GB RAM.

Thank you.

**Comment by NVentimiglia** [comment]
Hi @eungyukm 

I share your sentiment that GoogleMobileAds should be memory efficient, but I am not sure of what my next steps will be here. If I had an example which clearly showed a memory leak, I could advocate for a fix.

**Comment by eungyukm** [comment]
Thank you for your reply.

I appreciate your understanding and willingness to assist. I understand that having a clear example showcasing a memory leak would be helpful for advocating a fix. I have further investigated the issue and prepared a more detailed example that demonstrates the problem.

The steps to reproduce the maximum memory decrease in the Nox emulator are as follows:

1. Import the packages below to build AdMob in Unity version 2020.3.48f1.
2. Run the Nox Android 7 (64-bit) emulator.
3. Connect Unity Profiler to check the point at which the Out of Memory error occurs.
Below is the image of the maximum memory:
Please let me know if you need any further clarification or if there are any additional steps I should consider.
![image](https://github.com/googleads/googleads-mobile-unity/assets/86348187/aed1a8a8-4e86-454e-8974-fefb2751fadf)
![image](https://github.com/googleads/googleads-mobile-unity/assets/86348187/b95b95b9-0ae5-4c84-9669-b016fb1ebe28)

This is GoogleAds Unity Package           


[GoogleAds.zip](https://github.com/googleads/googleads-mobile-unity/files/11911536/GoogleAds.zip)

**Comment by eungyukm** [comment]
This is an issue that occurs only in app players like Nox.

**Comment by NVentimiglia** [comment]
@eungyukm 

Fixing issues only related to the Nox emulator is our of my expertise. If you can replicate a memory leak on a production device, I can take another look.
