### ISSUE TITLE
[error] Unity] Error: IL2CPP error Unresolved type reference : System.Void in module `GoogleMobileAds.Common.dll` with scope `GoogleMobileAds.Core, Version=8.1.0.0, Culture=neutral, PublicKeyToken=null`)

### ISSUE THREAD

**Issue by RomainBitard** [googleads/googleads-mobile-unity#2805]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.21f1
  * Google Mobile Ads Unity plugin version: 8.3.0
  * Platform: iOS

#### Steps to reproduce:
I can't build I have this error
[error] [2023-07-03T14:23:13Z - Unity] Error: IL2CPP error (no further information about what managed code was being converted is available)
[warning] [2023-07-03T14:23:13Z - Unity] System.AggregateException: One or more errors occurred. (Unresolved type reference : System.Void in module `GoogleMobileAds.Common.dll` with scope `GoogleMobileAds.Core, Version=8.1.0.0, Culture=neutral, PublicKeyToken=null`)
[warning] [2023-07-03T14:23:13Z - Unity]  ---&#62; System.ArgumentException: Unresolved type reference : System.Void in module `GoogleMobileAds.Common.dll` with scope `GoogleMobileAds.Core, Version=8.1.0.0, Culture=neutral, PublicKeyToken=null`

**Comment by NVentimiglia** [comment]
@RomainBitard 

Can you provide replication steps? Do you know what event was being fired or method called to generate this crash?

**Comment by NVentimiglia** [comment]
@RomainBitard 

This line `GoogleMobileAds.Core, Version=8.1.0.0` is strange. Can you delete your DLLs and reinstall them? All DLLs should be on 8.3.0.

**Comment by RomainBitard** [comment]
It was on a cloud build I believe, I deleted everything and retried with 8.3.0 and it seemed to build without this error

**Comment by NVentimiglia** [comment]
Thanks for the update.
