### ISSUE TITLE
Unity 5.5.0b6 crashes after importing package

### ISSUE THREAD

**Issue by RoAnduku** [googleads/googleads-mobile-unity#281]
Hello,

When GoogleMobileAds.unitypackage is imported into a project, the editor will crash. It will also break that project, making it inaccessible (100% crash rate).
This is recoverable by manually deleting the imported data from the Assets folder. (GoogleMobileAds, PlayServicesResolver and Plugins folders).

See the attached fatal error.

This does not happen in Unity 5.4.1.

I don't whether this is a priority or not, since it happens on the latest beta release.
Also, I'm aware that this might be a problem in Unity, and not in the googleads package.

Hope this helps,
Kudos.

![unitycrash](https://cloud.githubusercontent.com/assets/609490/19243819/f12b9bb8-8f21-11e6-934f-984ba6af5ce2.png)

**Comment by rampara** [comment]
This issue should be resolved in the latest version of the plugin (3.1.1)
