### ISSUE TITLE
Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_GoogleMobileAdsMediationTestSuite"

### ISSUE THREAD

**Issue by mtsatryan** [googleads/googleads-mobile-unity#2812]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.10f1
  * Google Mobile Ads Unity plugin version: 10.0
  * Platform: IOS 
  * Platform OS version: IOS 12.0
  * Any specific devices issue occurs on: none
  * Mediation ad networks used, and their versions: 'GoogleMobileAdsMediationAdColony', '4.9.0.2', 'GoogleMobileAdsMediationAppLovin', '11.9.0.0', 'GoogleMobileAdsMediationFacebook', '6.12.0.1', 'GoogleMobileAdsMediationIronSource', '7.2.7.0.1', 'GoogleMobileAdsMediationMintegral', '7.3.6.0', 'GoogleMobileAdsMediationPangle', '5.2.0.9.0', 'GoogleMobileAdsMediationTapjoy', '13.0.1.0', 'GoogleMobileAdsMediationUnity', '4.7.0.0', 'GoogleMobileAdsMediationVungle', '6.12.2.0'

### [REQUIRED] Step 2: Describe the problem
I have a problem with building an archive build for IOS TestFlight release. When archiving the build Xcode brings linking error: 

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GoogleMobileAdsMediationTestSuite", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite-plugin-library.a(GADUMediationTestClient.o)

#### Steps to reproduce:

I use this pod file (pod install) and use Xcode workspace to build an archive.

`
source 'https://github.com/CocoaPods/Specs'
source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

target 'UnityFramework' do
  pod 'GoogleMobileAdsMediationAdColony', '4.9.0.2'
  pod 'GoogleMobileAdsMediationAppLovin', '11.9.0.0'
  pod 'GoogleMobileAdsMediationFacebook', '6.12.0.1'
  pod 'GoogleMobileAdsMediationIronSource', '7.2.7.0.1'
  pod 'GoogleMobileAdsMediationMintegral', '7.3.6.0'
  pod 'GoogleMobileAdsMediationPangle', '5.2.0.9.0'
  pod 'GoogleMobileAdsMediationTapjoy', '13.0.1.0'
  pod 'GoogleMobileAdsMediationUnity', '4.7.0.0'
  pod 'GoogleMobileAdsMediationVungle', '6.12.2.0'
  pod 'Google-Mobile-Ads-SDK', '~> 10.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static `

**Comment by NVentimiglia** [comment]
Hi @mtsatryan 

Mediation Test Suite is deprecated in favor of [ad inspector](https://developers.google.com/admob/unity/ad-inspector) and is to be sunsetted on September 30, 2023. [Documentation](https://developers.google.com/admob/unity/deprecated-mediation-test-suite) will be removed then also.

https://developers.google.com/admob/unity/migrate-to-ad-inspector
