### ISSUE TITLE
The UMP consent popup has terrible performance on Android due to hardware acceleration being disabled

### ISSUE THREAD

**Issue by emathis11** [googleads/googleads-mobile-unity#2814]
* Unity version: 2022.3.3f1
  * Google Mobile Ads Unity plugin version: 8.3.0
  * Platform: Android
  * Platform OS version: Android 12
  * Any specific devices issue occurs on: All, but particularly slow on a Samsung S21
  * Mediation ad networks used, and their versions: None

Unity forces `android:hardwareAccelerated` to be set to `false` on the main player activity, causing the UMP popup to be extremely slow on some devices, as bad as 1-2 FPS on a Samsung S21, after scrolling for a few seconds. Likely because the UMP SDK uses a WebView to display the popup, which has notoriously bad performance without hardware acceleration.

Setting hardware acceleration to `true` (with a post-process script) makes the consent popup smooth and fixes the problem. But this is a very bad workaround as setting it to `true` can [cause huge performance drops in-game](https://forum.unity.com/threads/android-hardwareaccelerated-is-forced-false-in-all-activities.532786/).

Proposed solution by Unity is to display the WebView in a separate activity that is hardware accelerated. Is this something you can implement? As, currently, it makes the UMP SDK for Unity unusable on some devices.

**Comment by NVentimiglia** [comment]
@emathis11 

Thank you for reaching out. We are aware of this consideration and are working for a solution.

**Comment by vavakadopano** [comment]
Hi there, We are having the same problem with AdMob Unity SDK 7.4.1 for GDPR Compliance. When showing the compliance message fps drops to 1-2 on most devices.

Devices with fps drop:
Pixel 2 
HUAWEI Smart Z
Mi 10T

Devices without fps drop:
POCO X5 Pro 5G

Is there any progress on this error?

**Comment by Nyankoo** [comment]
@vavakadopano The issue was fixed in the latest AdMob release for Android, but as stated here (#2853), the Unity release will be _somewhere_ in this quarter.

**Comment by vavakadopano** [comment]
Is this official information form Google developers? ;)

**Comment by NVentimiglia** [comment]
Fix included with 8.5

Please reopen if you run into this issue.
