### ISSUE TITLE
This feature requires ASM7

### ISSUE THREAD

**Issue by Nyankoo** [googleads/googleads-mobile-unity#2817]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.27f1
  * Google Mobile Ads Unity plugin version: 8.4.0
  * Platform: Android
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem

As the original issue #2650 was closed even when reported that the issue is still present with the latest AdMob version (8.4.0), I'm opening a new bug report for this.

The issue happens after resolving Android dependencies with the External Dependency Manager. A clean build is then required as a workaround, which is really bad as it defeats the purpose of incremental builds in Unity on larger projects.

As someone in the old bug report mentioned, this is caused by the AppLovin unitypackage. I tested this with AdMob version 8.4.0 and AppLovin package version 6.8.0.

**Comment by NVentimiglia** [comment]
@Nyankoo 

I am happy we have a workaround. I have made the feature request to fully support incremental builds.

**Comment by nikolocogr** [comment]
I have the same issue and its a big problem with Unity Cloud Builder!!!
For android builds, the only way to get a successful build is to select Clean Build.
Clean build takes much more time to build and for automatic builds there is no clean build option!

**Comment by Nyankoo** [comment]
@NVentimiglia In which version was this fixed? Can't find anything in the changelog of the most recent versions.

**Comment by daniel-do-MA** [comment]
@Nyankoo what is minimum API level configured in player settings?  for me it was 22 , after raise it 24 , problem solved
