### ISSUE TITLE
Is it possible to build xcode proj on PC?

### ISSUE THREAD

**Issue by JohnTong** [googleads/googleads-mobile-unity#282]
As I say in title, I want to export an xcode project on pc and copy to mac to build to iphone.
When doing this, it log info says cocoapods issue and no xcode project create. If I copy this proj to xcode and run on iphone it crash.  Can anyone help?

**Comment by rampara** [comment]
To build and deploy Unity projects for the iOS platform, you will need to use a mac development machine.
