### ISSUE TITLE
Status bar pops up and cant close interstitial ad

### ISSUE THREAD

**Issue by msharif42** [googleads/googleads-mobile-unity#2825]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.5
  * Google Mobile Ads Unity plugin version: 8.4.1, 8.4.0, 8.3.0, ...
  * Platform: Android
  * Platform OS version: Android 13
  * Any specific devices issue occurs on: Google Pixel 6, Pixel 4a
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem
I received a warning from google play that there is an interstitial ad appears during gameplay and does not offer users an option to skip within 15 seconds [Screenshot1](https://drive.google.com/file/d/1wDvFTxp8wPzsw6SQ5sieVsNLrwIDlj5t/view) [Screenshot2](https://drive.google.com/file/d/1ReO8CHKNgGpILt15G85yiADbH7R_pkbr/view)
I can not reproduce the exact error but what I found may be the reason. I have tested it on my Google Pixel 6, and it looks like when the interstitial ad is showing, the status bar pops up and cuts a portion in both the upper and lower sides [Screenshot3](https://drive.google.com/file/d/150YIrPi2uQ_nSxFj3We_qvrawJteC9en/view) [Screenshot4](https://drive.google.com/file/d/1nkSBsgkelFQIwr_uO6a5T6xq6IeVBYWS/view?usp=sharing). The status bar remains there forever. But, I can press the cross button and close the ad. After closing the ad the status bar goes away. I am guessing whatever device they are using for testing, the status bar hides the cross button and that's why they can't close the ad, or it is an issue where the cross button actually never appears. I found another thing in One Plus 8 and Moto G Fast devices when the interstitial ad appears the navigation bar also appears [Screenshot5](https://drive.google.com/file/d/1rpACfX_en5GvSy-F4Cf2CuN16OXsZcPa/view)

#### Steps to reproduce:
1. Import the package to a brand new Unity project.
2. Show an interstitial ad on Pixel 6
3. Status bar pops up and crops part of the ad in both top and down

**Comment by NVentimiglia** [comment]
@msharif42 

On Android, the Interstitial ad is rendered within its own Activity.  Usually when we see a missing close button on Android it is a creative issue. Specifically the ad creator did not implement [mraid](https://www.iab.com/guidelines/mraid/#:~:text=MRAID%2C%20or%20%E2%80%9CMobile%20Rich%20Media,will%20run%20in%20mobile%20apps.) correctly.

The process here is to open a [support request on the forum](https://groups.google.com/g/google-admob-ads-sdk). The support staff will need something to identify the creative; Usually this means a charles log from a replicated incident.

**Comment by msharif42** [comment]
@NVentimiglia I also thought so at first and I understand your point. This is something I received from google play and I even asked for their testing environment but they don't want to provide any. Just telling me to solve the problem or my app will be removed. They are getting this for multiple different ads (as pointed out in the issue). As I can't re-create the situation I can't give Charles a log. Any idea how to hide the status bar when the ad appears?

**Comment by NVentimiglia** [comment]
@msharif42 

Understood, I will follow up on my end and see if there is anything I can do.

**Comment by msharif42** [comment]
@NVentimiglia As google play is not giving me any device info and I can't reproduce the issue, my only hope is to hide the status bar, upload an update and rely on my luck for now. I compiled and run the example from here [Android Interstitial Official Example](https://github.com/googleads/googleads-mobile-android-examples/tree/main/java/admob/InterstitialExample) and looks like the status bar is not there in landscape mode, in case it helps you. Thanks in advance.

**Comment by NVentimiglia** [comment]
> @NVentimiglia What I found I activated "Optimize Initialization" and "Optimize Ad Loading" in Ads Setting. If I turned them off, then the status bar will not pop up anymore. Sorry for not mentioning that part earlier. The original objection of google play is still there and I can't reproduce it. If you believe it's a 100% creative problem and nothing to do from your side or my side then you can close this issue. I'll just try my luck again. Thanks

I am not replicating this when testing against the test ads. Enabling the feature, I see no status bar for any of the full screen ads.

**Comment by msharif42** [comment]
@NVentimiglia I can replicate the status bar pop-up issue in my Pixel 6 and Pixel 4a by enabling the features. Did you use any Pixel 6 or 4a? Also try landscape mode.
