### ISSUE TITLE
No such proxy method: GoogleMobileAds.Ump.Android.OnConsentFormDismissedListener.onConsentFormDismissed(null)

### ISSUE THREAD

**Issue by majidkh** [googleads/googleads-mobile-unity#2826]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.5.f1
  * Google Mobile Ads Unity plugin version: 8.4.1
  * Platform: _____ (iOS, Android, Unity Editor) Android
  * Platform OS version: _____ (eg iOS 10, Android 9) Android 13
  * Any specific devices issue occurs on: _____ Google Pixel 6a
  * Mediation ad networks used, and their versions: _____ N/A 

### [REQUIRED] Step 2: Describe the problem

After user dismissed the consent form, following error appears:

2023/07/19 11:04:25.078 345 345 Error Unity Exception: No such proxy method: GoogleMobileAds.Ump.Android.OnConsentFormDismissedListener.onConsentFormDismissed(null)

#### Steps to reproduce:

What happened? How can we make the problem occur?

Delete the game and reinstall it, After loading the consent form and showing it, close it and the above error happens.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by majidkh** [comment]
Same error happens also when building the Sample project in the repository.

![Screenshot_20230719-174113](https://github.com/googleads/googleads-mobile-unity/assets/521087/0dff5c0f-6554-401e-9663-4d6bb7194188)

**Comment by NVentimiglia** [comment]
@majidkh 

I did not replicate the issue, please double check my steps to make sure I did not miss anything.

1.  export gradle project.
2. build / run project on device.
3. Goto UMP scene, set debug to EEA
4. reset information, request update, load form, show form.
5. exit app, open settings, uninstall app.
6. open gradle project output/apk directory. Drag apk onto simulator.
7. reopen app.
3. Goto UMP scene, set debug to EEA
8. request update, load form, show form.

**Comment by majidkh** [comment]
It happens even with the Sample project, I am on Unity version: 2022.3.5.f1 and use GoogleAds Unity plugin version: 8.4.1.

Happens all the time at my end.

I made my own plugin now to use the UMP Android and it works fine using my own plugin, the error happens only in Unity and only when running on an Android device. in Editor works fine.

**Comment by majidkh** [comment]
It might been patched with the following commit:

https://github.com/googleads/googleads-mobile-unity/commit/adcb8e6383ba7be60cdd9d3f52f0162a55d7dbe6

**Comment by NVentimiglia** [comment]
@majidkh No, I think this issue is separate from the commit linked.

I am still unable to replicate this. I switched to Unity 2022 and did a direct from editor install this time.

https://github.com/googleads/googleads-mobile-unity/pull/2829

As part of the above changes, I have an updated UMP controller. Please try it out, if this fails, please send me an APK and/or project.

**Comment by luizjunior** [comment]
I'm seeing this error showing on my last google play's build

Exception: No such proxy method: GoogleMobileAds.Ump.Android.OnConsentFormDismissedListener.onConsentFormDismissed(null)

**Comment by luizjunior** [comment]
> It happens even with the Sample project, I am on Unity version: 2022.3.5.f1 and use GoogleAds Unity plugin version: 8.4.1.
> 
> Happens all the time at my end.
> 
> I made my own plugin now to use the UMP Android and it works fine using my own plugin, the error happens only in Google Ads UMP Unity and only when running on an Android device. in Editor works fine.
> 
> The steps:
> 
> * Git clone the repository
> * Open the sample project in Unity
> * import google mobile ads Unity SDK (8.4.1)
> * Delete the app on the android if you already built it
> * Build and run on the Android Device ( do not export gradle, just build and run in unity )
> * Tap on the update consent button, load form and show form
> * Close the form
> 
> If still unable to produce , I can upload the sample project here.

can you please share your plugin? I'm getting a lot of this error on a production build

**Comment by NVentimiglia** [comment]
@luizjunior 

This may be caused by a missing android dependency. Please make sure that the external dependency manager is pulling in `com.google.android.ump.user-messaging-platform-2.1.0.aar`.

**Comment by luizjunior** [comment]
> @luizjunior
> 
> This may be caused by a missing android dependency. Please make sure that the external dependency manager is pulling in `com.google.android.ump.user-messaging-platform-2.1.0.aar`.

Hi @NVentimiglia thanks for your reply...

I've just install Unity 2022.3.7f1 LTS, Google Mobile Ads Unity Plugin v8.5.1 and I've implemented the new form method ConsentForm.LoadAndShowConsentFormIfRequired.

The form is displayed, but when I choose the CONSENT option, then a error is displayed on the logcat:

Error Unity Exception: No such proxy method: GoogleMobileAds.Ump.Android.OnConsentFormDismissedListener.onConsentFormDismissed(null)

I'm attaching a screen shot for the Android plugins folder and my GDPR message setup


<img width="1168" alt="my_form_setup" src="https://github.com/googleads/googleads-mobile-unity/assets/419266/7ce2d5e3-3922-42ce-a2a1-47b22d568734">
<HR>

<img width="1186" alt="my_android_plugins" src="https://github.com/googleads/googleads-mobile-unity/assets/419266/0eae70c7-a913-43d3-9ab7-1e266f3f4962">
<HR>

<img width="585" alt="unity_exception" src="https://github.com/googleads/googleads-mobile-unity/assets/419266/93d35214-ae42-458e-9ea7-2a91636636e6">

**Comment by Nyankoo** [comment]
@NVentimiglia Facing the same issue with v8.5.1. It seems that is has nothing to do with a missing android dependency, similar to #2866, but with a lot of things missing in the latest wrapper.

**Comment by majidkh** [comment]
@NVentimiglia  Here is the build .apk file with sample project together. 

Its using the Test App Id from here: https://developers.google.com/admob/android/quick-start

( The issue happens in this scene: GoogleMobileAdsScene )

[build.zip](https://github.com/googleads/googleads-mobile-unity/files/12333008/build.zip)
[HelloWorld.zip](https://github.com/googleads/googleads-mobile-unity/files/12333110/HelloWorld.zip)

Unity Version: 2022.3.7f1 ( Silicon)
Admob Unity SDK version: 8.5.1

Hope this helps!

**Comment by NVentimiglia** [comment]
@Nyankoo @majidkh 

Thank you, I will take a look.

**Comment by NVentimiglia** [comment]
@Nyankoo @majidkh 

What android API levels and devices are you experiencing this on?

I see reference to Android 13 and Pixel 6a

**Comment by Nyankoo** [comment]
@NVentimiglia Mi A2 Lite with Android 10

**Comment by majidkh** [comment]
> @Nyankoo @majidkh
> 
> What android API levels and devices are you experiencing this on?
> 
> I see reference to Android 13 and Pixel 6a

Thats correct.

**Comment by NVentimiglia** [comment]
@majidkh  @Nyankoo 

There was an issue with the hello world application that requested the consent form twice, can you try with the latest version of the hello world application?

**Comment by majidkh** [comment]
That project I attached was the latest version.

**Comment by NVentimiglia** [comment]
@majidkh @Nyankoo

Are you by chance passing null into the `ConsentForm.Show()` method?

**Comment by Nyankoo** [comment]
@NVentimiglia No. 
```
ConsentForm.LoadAndShowConsentFormIfRequired(onFormDismissed);
private void onFormDismissed(FormError error){}
```

**Comment by CraZCodr** [comment]
Hi, I'm getting the same exception since I switched from Unity 2022.3.4f1 to 2022.3.5f1.
Also tried 2022.3.6f1 and 2022.3.7f1 - the exception persists.

When switching back to 2022.3.4f1 the exception does not happen.

Device: Xiaomi Redmi Note 10 Pro, Android 13.

**Comment by NVentimiglia** [comment]
@Nyankoo @CraZCodr  @majidkh 

We have identified and confirmed the issue and are looking into a fix.

**Comment by desouse** [comment]
It looks like this is a Unity bug.

https://unity.com/releases/editor/whats-new/2022.3.5#:~:text=Android%3A%20AndroidJavaProxy%20correctly%20maps%20null%20variables%20(e.g%20empty%20string)%20for%20reflection%20search%20%2B%20automatic%20tests%20for%20AndroidJavaProxy.%20(UUM%2D30243)

https://forum.unity.com/threads/exceptions-after-uum-30243-fix.1465151/

**Comment by luizjunior** [comment]
I can confirm that.

Runing on Unity 2022.3.4f1 (before the "FIX") it works fine, but it shows the error on Unity 2022.4.7f1 

> It looks like this is a Unity bug.
> 
> https://unity.com/releases/editor/whats-new/2022.3.5#:~:text=Android%3A%20AndroidJavaProxy%20correctly%20maps%20null%20variables%20(e.g%20empty%20string)%20for%20reflection%20search%20%2B%20automatic%20tests%20for%20AndroidJavaProxy.%20(UUM%2D30243)
> 
> https://forum.unity.com/threads/exceptions-after-uum-30243-fix.1465151/

**Comment by NVentimiglia** [comment]
Thank you!

**Comment by usamanawaz789** [comment]
Is there any update on this?

**Comment by NVentimiglia** [comment]
@usamanawaz789 

The fix is scheduled for release this week.
