### ISSUE TITLE
Conflicts with Play games plugin

### ISSUE THREAD

**Issue by macpatel** [googleads/googleads-mobile-unity#283]
I had installed Admob plugin earlier and now wanted to integrate Play Game Plugin. https://github.com/playgameservices/play-games-plugin-for-unity

After installing got below errors 

`
Error   1   The type 'Google.JarResolver.PlayServicesSupport' exists in both 'E:\Game Development\Projects\crane-and-turtle\Assets\AdsAssets\PlayServicesResolver\Editor\JarResolverLib.dll' and 'E:\Game Development\Projects\crane-and-turtle\Assets\PlayServicesResolver\Editor\Google.JarResolver.dll'  E:\Game Development\Projects\crane-and-turtle\Assets\AdsAssets\PlayServicesResolver\Editor\IResolver.cs 74  27  crane-and-turtle.CSharp.Editor
`

The issue seems to be related with compatibility between both the plugins.

Any resolution other than hacking around ?

-Mahesh

**Comment by rdaros** [comment]
Same issue here... On top of the errors mentioned in original post, I also get a few warnings such as:

`Assets/PlayServicesResolver/Editor/CommandLineDialog.cs(27,38): warning CS0436: The type `GooglePlayServices.TextAreaDialog' conflicts with the imported type `GooglePlayServices.TextAreaDialog'. Ignoring the imported type definition`

**Comment by macpatel** [comment]
Hey @rdaros 

Got the response on Play games unity plugin. You can try that. I have dropped the plan for integrating play games plugin for now.

https://github.com/playgameservices/play-games-plugin-for-unity/issues/1431

-Mahesh

**Comment by rdaros** [comment]
Thanks @macpatel !

**Comment by rampara** [comment]
As mentioned in the linked issue from the play games unity repository, it looks like you have imported multiple copies of PlayServicesResolver classes in your Unity project. Those files should only be present under the `Assets/PlayServicesResolver` directory of your Unity project.

**Comment by macpatel** [comment]
@rampara nothing manually added, first imported admob plugin and then play store plugin.

@rdaros can you confirm if the solution worked for you ?

**Comment by rampara** [comment]
When importing Unity packages the Unity editor will display the files being imported. Which plugin created the `AdsAssets` directory?

**Comment by chuakc92** [comment]
Try looking up Google.JarResolver.dll and remove it.

**Comment by rampara** [comment]
Closing this issue due to non-response. Please re-open if this issue persists for you.
