### ISSUE TITLE
[UMP] MobileAds.RaiseAdEventsOnUnityMainThread behaviour

### ISSUE THREAD

**Issue by dreamcodestudio** [googleads/googleads-mobile-unity#2841]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.34f1
  * Google Mobile Ads Unity plugin version: 8.3.0
  * Platform: iOS, Android
  * Platform OS version: Any
  * Any specific devices issue occurs on: iPhone 13, iPhone 8 Plus, Samsung A52
  * Mediation ad networks used, and their versions: AdColony, AppLovin, IronSource, Mintegral, Pangle, Tapjoy, UnityAds

### [REQUIRED] Step 2: Describe the problem
Official Sample of [UMPController](https://github.com/googleads/googleads-mobile-unity/blob/main/samples/HelloWorld/Assets/Scripts/GoogleUmpController.cs)
included
`MobileAds.RaiseAdEventsOnUnityMainThread = true;`
and documentation of [AdColony](https://developers.google.com/admob/unity/mediation/adcolony) network inform about Privacy Options
`These options must be set before you [initialize the Google Mobile Ads SDK](https://developers.google.com/admob/unity/quick-start#initialize_the_mobile_ads_sdk) to ensure they get forwarded properly to AdColony's SDK.`

It contradicts each other, because in source code MobileAds, `synchronizationContext `created only after `MobileAds.Initialize`
![image](https://github.com/googleads/googleads-mobile-unity/assets/7010398/856d138f-cd49-4969-803f-192267104bc4)

Can you separate handling `RaiseAdEventsOnUnityMainThread` flag in indepent method?

#### Steps to reproduce:

Because in current order
MobileAds.RaiseAdEventsOnUnityMainThread = true => Show User Consent=> SetPrivacyConsentString

Callback not invoked until `MobileAds.Initialize`

#### Relevant Code:

```
//Show User Consent form
MobileAds.RaiseAdEventsOnUnityMainThread = true;

ConsentInformation.Update(consentRequestParameters,
                // OnConsentInformationUpdate
                (FormError error) =>
                {
                    UpdateUI();

                    if (error == null)
                    {
                        // The consent information updated successfully.
                        Debug.Log(string.Format(
                                "Consent information updated to {0}. You may load the consent " +
                                "form.", ConsentInformation.ConsentStatus));
                    }
                    else
                    {
                        // The consent information failed to update.
                        Debug.LogError("Failed to update consent information with error: " +
                                error.Message);
                    }

                });
```
```
//Set user consent flags
        AdColonyAppOptions.SetPrivacyFrameworkRequired(AdColonyPrivacyFramework.GDPR, isRequired: true);
        AdColonyAppOptions.SetPrivacyConsentString(AdColonyPrivacyFramework.GDPR, consentString);
        AppLovin.SetHasUserConsent(consent);
        IronSource.SetConsent(consent);
        Tapjoy.SetUserConsent(consentString);
        UnityAds.SetConsentMetaData("gdpr.consent", consent);
```

```
//At the end, initializing the Google Mobile Ads SDK.
        MobileAds.Initialize(initStatus => { });
```

**Comment by NVentimiglia** [comment]
@dreamcodestudio 

Got it, you have identified a race condition exposed by the new UMP workflow because we now initialize the SDK at a much later time in the lifecycle.

Thank you.

**Comment by dreamcodestudio** [comment]
> RaiseAdEventsOnUnityMainThread

In current SDK we handle User Consent Form callback via our SyncContext, but it's good if you resolve it via `RaiseAdEventsOnUnityMainThread` flag, i think is more expected lifecycle
