### ISSUE TITLE
unity 5 2d game admob interstitial not working

### ISSUE THREAD

**Issue by toni4321** [googleads/googleads-mobile-unity#285]
my admob interstial not working on my game here is my code: can you tell me someone how to show interstitial on menu scene and when is game over to show immediately.

using UnityEngine;
using System.Collections;
using UnityEngine.UI;
using GoogleMobileAds;
using GoogleMobileAds.Api;

public class iuManager : MonoBehaviour {

	private BannerView BannerView;
	private InterstitialAd interstitial;
	public menu bc;
	public Button[] buttons;
	public Text scoreText;
	bool gameOver;
	int score;

	// Use this for initialization
	void Start () {

		RequestBanner ();
		RequestInterstitial ();
		gameOver = false;
		score = 0;
		InvokeRepeating ("scoreUpdate", 1.0f, 0.5f);
	}

	// Update is called once per frame
	void Update () {
		scoreText.text = "Score: " + score;
	}

	void scoreUpdate(){
		if (gameOver == false) {
			score += 14;
		}
	}

	public void gameOverActivated(){
		gameOver = true;
		foreach (Button button in buttons) {
			button.gameObject.SetActive (true);
		}
			
	}
		

	public void play (){
		Application.LoadLevel ("level1");
		bc.bacSound.Stop ();
	}

	public void Pause (){
		if (Time.timeScale == 1) {
			Time.timeScale = 0;

			foreach (Button button in buttons) {
				button.gameObject.SetActive (true);

			}

		} 
		else if (Time.timeScale == 0) {
			Time.timeScale = 1;
			foreach (Button button in buttons) {
				button.gameObject.SetActive (false);
			}
		}
			
	}

	public void Replay(){
		Application.LoadLevel (Application.loadedLevel);
		if (Time.timeScale == 0) {
			Time.timeScale = 1;
		}

	
	
	}

	public void Menu(){
		Application.LoadLevel ("menuScene");
		ShowInterstitial ();
		if (Time.timeScale == 0) {
			Time.timeScale = 1;
		}
	}

	public void Exit(){
		Application.Quit ();

	}

	private void RequestBanner()
	{
		#if UNITY_EDITOR
		string adUnitId = "unused";
		#elif UNITY_ANDROID
		string adUnitId = "ca-app-pub-3940256099942544/6300978111";
		#elif UNITY_IPHONE
		string adUnitId = "INSERT_IOS_BANNER_AD_UNIT_ID_HERE";
		#else
		string adUnitId = "unexpected_platform";
		#endif

		// Create a 320x50 banner at the top of the screen.
		BannerView bannerView = new BannerView(adUnitId, AdSize.Banner, AdPosition.Top);
		// Create an empty ad request.
		AdRequest request = new AdRequest.Builder().Build();
		bannerView.LoadAd(request);
		}

		private void RequestInterstitial()
		{
		#if UNITY_ANDROID
		string adUnitId = "ca-app-pub-3940256099942544/1033173712";
		#elif UNITY_IPHONE
		string adUnitId = "INSERT_IOS_INTERSTITIAL_AD_UNIT_ID_HERE";
		#else
		string adUnitId = "unexpected_platform";
		#endif

		// Initialize an InterstitialAd.
		InterstitialAd interstitial = new InterstitialAd(adUnitId);
		// Create an empty ad request.
		AdRequest request = new AdRequest.Builder().Build();
		interstitial.LoadAd(request);
		}

		private void ShowInterstitial ()
		{
		if (interstitial.IsLoaded ()) {
		interstitial.Show ();
		} else {
		print ("Interstitial is not ready yet.");
		}
		}

}

**Comment by rampara** [comment]
Are you deploying to the Android or iOS platform? You don't have an interstitial ad unit defined for iOS. You should also use [ad events](https://firebase.google.com/docs/admob/unity/start#ad_events) to get more information about the ad request failures. The [sample application](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) also serves as an example of how to request and display interstitial ads.

**Comment by toni4321** [comment]
in android platform can you tell me how to request and display interstitial on this code
