### ISSUE TITLE
Google User Messaging Platform 2.1.0 support?

### ISSUE THREAD

**Issue by Nyankoo** [googleads/googleads-mobile-unity#2853]
Do we already have a timeframe for when Google User Messaging Platform 2.1.0 will be included in the Unity release? The new update seems to improve quite a bit, so that should be a priority for the next release.

**Comment by NVentimiglia** [comment]
@Nyankoo 

Google User Messaging Platform is a priority and we hope to submit an update this quarter.

**Comment by Inspyro** [comment]
I think the update is already available?
https://github.com/googleads/googleads-mobile-unity/releases/tag/v8.5.0

**Comment by Nyankoo** [comment]
Seems like conflicting information?

**Comment by NVentimiglia** [comment]
@NVentimiglia 

Yes, the updates should be available in 8.5.0


https://github.com/googleads/googleads-mobile-unity/releases/tag/v8.5.0
