### ISSUE TITLE
Ads not shown in Editor after upgrade to 8.4.1

### ISSUE THREAD

**Issue by raft75** [googleads/googleads-mobile-unity#2855]
* Unity version: 2020.3.48f1
  * Google Mobile Ads Unity plugin version: v8.4.1
  * Platform: Unity Editor on Windows 11

I've updated from plugin v7.4.0 to v8.4.1 and now I don't see any more test banners in Unity Editor.
Banners are correctly shown when the build is installed on an Android device.
I don't understand if this is a bug or a (removed) feature.
During the upgrade, I've been asked if I wanted to remove obsolete files, among which the DummyAds folder inside GoogleMobileAds\Editor\Resources, I answered yes.
The DummyAds folder is missing now.

**Comment by NVentimiglia** [comment]
@raft75 Can you try uninstalling and reinstalling the plugin? I suspect this is due to the files being moved. Moreover, any error messages in the console will help me diagnose the issue.

**Comment by raft75** [comment]
Now it's working, thanks. 
It's possible that the issue was caused by upgrading over an existing 7.40 AdMob plugin. 
This time, before importing version 8.4.1, I deleted the folders ExternalDependencyManager, GoogleMobileAds, and Plugins. 
I also noticed that the folder GoogleMobileAds\Editor\Resources\PlaceholderAds has been created now (which was missing in the previous installation).
