### ISSUE TITLE
Conflict with Google Play Games Services

### ISSUE THREAD

**Issue by TheProProgrammer** [googleads/googleads-mobile-unity#2856]
* Unity version: 2022.3.5f1
  * Google Mobile Ads Unity plugin version: 8.4.1
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: Android 11 (eg iOS 10, Android 9)

#### Steps to reproduce:
Add AdMob unity plugin after you've already added Google Play Games Services Plugin

#### What happens:
It conflicts with the existing files for Google Play Games Servies files located in Assets/ExternalDependenciesManager and attempts to change them, in turn crashing Google play games services.

**Comment by NVentimiglia** [comment]
@TheProProgrammer 

Which error are you encountering? I Installed [Google Play Games](https://github.com/playgameservices/play-games-plugin-for-unity/releases) and saw now file conflicts from vs. 11 of the package.

**Comment by TheProProgrammer** [comment]
![image](https://github.com/googleads/googleads-mobile-unity/assets/45878555/65828f93-f2ef-4769-9e2c-0c47ac54a608)
The files marked by the warning signs are used by Google Play Games, now when I import and setup Admob it builds fine, but neither Google Play Games services nor AdMob work. (Google Play Games was working prior)

**Comment by NVentimiglia** [comment]
Aaah yes, both google play and admob have a shared dependency on external dependency manager. Glad you got it to work.
