### ISSUE TITLE
Unity 5.4.2 "WARNING: No compatible versions of com.android.support:support-v4 required by...." issue

### ISSUE THREAD

**Issue by phatal** [googleads/googleads-mobile-unity#286]
When I trying to launch In unity editor in soncole looks like all is good
![consolescreen](https://cloud.githubusercontent.com/assets/14150045/19417088/a1136696-93cd-11e6-8c70-f61879ab999f.PNG)

but when I test APK at device (NEXUS 5), nothing happen.
SDK screens:
![sdk1](https://cloud.githubusercontent.com/assets/14150045/19417096/ee60b066-93cd-11e6-8bc7-e898297c14a4.PNG)
![sdk2](https://cloud.githubusercontent.com/assets/14150045/19417097/f02317fe-93cd-11e6-8f7a-2b80a96f89ff.PNG)

**Comment by rampara** [comment]
The latest version of the plugin no longer has the Android Support Library as a dependency.
