### ISSUE TITLE
Advanced Native Ad - InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings.

### ISSUE THREAD

**Issue by tudorpopa39** [googleads/googleads-mobile-unity#2872]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.31f
  * Google Mobile Ads Unity plugin version: 8.5.1
  * Platform: iOS
  * Platform OS version: 16.6

### [REQUIRED] Step 2: Describe the problem

```
InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings.
```

Every time I show a Native Ad on iOS, I got this error. It seems Native Ad does not work with New Input System.

I implement like it should, disabling all raycast target, and I added the box colliders on variables.

<img width="601" alt="Screenshot 2023-08-10 at 23 50 38" src="https://github.com/googleads/googleads-mobile-unity/assets/16446036/d358018c-f097-40cf-9610-7fe906f25925">

Is there a solution for not switching to Both systems?

**Comment by NVentimiglia** [comment]
Hi @tudorpopa39 

Native ads should not depend on `UnityEngine.Input`. Looking at the source I see no use of this dependency.

Most likely the dependency is being pulled in by a Unity specific configuration.

**Comment by tudorpopa39** [comment]
@NVentimiglia 
I thought ```UnityEngine.Input``` is use to managed clicks on the native ad variables, like icon, body, or call to action button. 
What is your suggestion?

**Comment by NVentimiglia** [comment]
@tudorpopa39 

I do see use of `UnityEngine.UI;` and `UnityEngine.EventSystems;` in the button tracking code. That may be it.

I will bring this up with the native ads team.

**Comment by NVentimiglia** [comment]
Submitted feature request b/308642111

**Comment by Doreamonsky** [comment]
is this problem fixed?
