### ISSUE TITLE
Assembly has reference to non-existent assembly 'GoogleMobileAds' (Assets/GoogleMobileAds/Editor/GoogleMobileAds.Editor.asmdef)

### ISSUE THREAD

**Issue by AltCtrlDel1999** [googleads/googleads-mobile-unity#2885]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2018.4.11f
  * Google Mobile Ads Unity plugin version:8.3.0
  * Platform: Android
  * Platform OS version: All OS versions
  * Any specific devices issue occurs on: No
  * Mediation ad networks used, and their versions: 

### [REQUIRED] Step 2: Describe the problem
When integrating AdMob plugin v8.3.0 in unity 2018 getting below error 
Assembly has reference to non-existent assembly 'GoogleMobileAds' (Assets/GoogleMobileAds/Editor/GoogleMobileAds.Editor.asmdef)

#### Steps to reproduce:

1) Integrate AdMob SDK plugin v8.3.0
2)  Build the app
3) Issue observed  - Assembly has reference to non-existent assembly 'GoogleMobileAds'

**Comment by NVentimiglia** [comment]
Hi @AltCtrlDel1999 

Can you share some more details about your project structure? For instance are you using [Assembly definitions](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html). If so, you may need to register your assemblies with the editor assembly.

**Comment by AltCtrlDel1999** [comment]
I have created a empty project in Unity Editor v2018.4.11f and just imported the AdMob Unity plugin and  got the error mentioned above

**Comment by AltCtrlDel1999** [comment]
<img width="348" alt="Screenshot 2023-08-23 at 2 06 53 PM" src="https://github.com/googleads/googleads-mobile-unity/assets/57938708/68930d39-0900-415a-bc8f-ec5de68c6fc2">

**Comment by NVentimiglia** [comment]
Hi @AltCtrlDel1999 

The current min version for Google Mobile Ads for Unity is 2019. That said, there are older version of the plugin.

https://github.com/googleads/googleads-mobile-unity/releases
