### ISSUE TITLE
[feat] Creating SKAdNetwork by built-in networks

### ISSUE THREAD

**Issue by dreamcodestudio** [googleads/googleads-mobile-unity#2887]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.34f1
  * Google Mobile Ads Unity plugin version: 8.5.0
  * Platform: iOS
  * Platform OS version: Any
  * Any specific devices issue occurs on: Any iOS
  * Mediation ad networks used, and their versions: AdColony, AppLovin, IronSource, Mintegral, Pangle, Tapjoy, UnityAds

### [REQUIRED] Step 2: Describe the problem
Good solution if SKAdNetwork will be recreate by built-in networks `GoogleMobileAdsSKAdNetworkItems.xml` on PostProcess, like it implemented in AppLovin SDK.
They scan Unity projects and as result generate `GoogleMobileAdsSKAdNetworkItems.xml` ids.

Because stamp between release can too long and list of ids by link https://developers.google.com/admob/unity/3p-skadnetworks
can be different in Unity packages or contains missing ids, how it happened with ironSource

#### Steps to reproduce:

Build Xcode Project

**Comment by dreamcodestudio** [comment]
Is there any way to keep the GoogleMobileAdsSKAdNetworkItems.xml file up to date based on enabled networks?

**Comment by NVentimiglia** [comment]
Hi @dreamcodestudio 

> For example it not contains primary ironSource id, but support it

Thank you for the awareness, I will let the iOS team know.

> Is there any way to keep the GoogleMobileAdsSKAdNetworkItems.xml file up to date based on enabled networks?

This is something we are looking into.

**Comment by NVentimiglia** [comment]
Closing, feature request submitted.
