### ISSUE TITLE
Error running cocoapods. Please ensure you have at least version  1.0.0.

### ISSUE THREAD

**Issue by oliverbenns** [googleads/googleads-mobile-unity#289]
```
...You can install cocoapods with the Ruby gem package manager:  > sudo gem install -n /usr/local/bin cocoapods
```

Hey guys I seem to get this error whenever I click build for my iOS project. I've checked my versioning and see that everything is all there. Please help!
- Cocoapods 1.1.0.rc.3
- Ruby 2.3.0 (installed with Rvm 0.31.2)
- Running Unity 5.4.2

I can run commands just find with `pod`cli.

Thanks

**Comment by rampara** [comment]
does the `which pod` command work as expected for you?

**Comment by n1bab** [comment]
@rampara having the same issue

**Comment by n1bab** [comment]
All commands for pod working as expected inside cli

**Comment by rampara** [comment]
@n1bab do you see `pod' command not found` or `Error running cocoapods` in the console output before getting the error message posted above.

**Comment by sam-mckay** [comment]
@rampara I'm also having this issue, i get the Error running cocoapods message

I was previously also getting the pod command not found but a reinstall of cocoapods killed that error, not sure whats causing this other error though, any ideas? 

Thanks,

Sam

**Comment by rampara** [comment]
@sam-mckay what is the location of your cocoapods install?

**Comment by sam-mckay** [comment]
@rampara That issue has now been resolved but it didn't seem to want to copy the frameworks over, and i'm yet to test manually copying them over as suggested here:
https://groups.google.com/forum/#!topic/google-admob-ads-sdk/55COuO1SH2M

**Comment by rampara** [comment]
@sam-mckay Are you seeing issues with frameworks not being copied over with the latest version of the plugin (v3.1.3). The latest release pulls in fixes from the JarResolver library that addresses iOS framework resolution issues. Also, are you seeing any output in the Unity console that may indicate why frameworks are not being copied over?

**Comment by rampara** [comment]
Closing this issue due to non-response. Please re-open if this issue persists for you.
