### ISSUE TITLE
Can't close AdMob reward due to iOS safearea issue

### ISSUE THREAD

**Issue by llmagicll** [googleads/googleads-mobile-unity#2892]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.16f1
  * Google Mobile Ads Unity plugin version: 8.4.1, 8.5.1
  * Platform: iOS
  * Platform OS version: 16.6
  * Any specific devices issue occurs on: non-device related
  * Mediation ad networks used, and their versions: AdMob

### [REQUIRED] Step 2: Describe the problem

Incorrect Safe Area Layout in Some Reward Templates

Certain reward templates display an incorrect safe area layout. This results in layouts that intersect the status bar and cannot be closed.

##### Screenshot of the correct safe area layout

![image](https://github.com/googleads/googleads-mobile-unity/assets/2182193/04f79fec-887b-47f7-8d02-676fb7ddbb56)

##### Screenshot of the incorrect safe area layout

![image](https://github.com/googleads/googleads-mobile-unity/assets/2182193/49a4c797-8348-435a-a903-66fa17ba3843)

![image](https://github.com/googleads/googleads-mobile-unity/assets/2182193/565b3d44-3a1f-444b-8582-fd2180cb30ca)

#### Steps to reproduce:

1. request a reward ad and present

#### Relevant Code:

```
Presenting a reward video
```

**Comment by NVentimiglia** [comment]
@llmagicll 

This is a creative / formats issue and you should submit your request to the official [google support forum](https://groups.google.com/g/google-admob-ads-sdk). I would like to help you here, but our specialty is specifically the Unity plugin portion of the code - where this is more of a serving / creative issue.

When you make this request link this original post, include a charles log (Google support will need this to find the incorrect creative), and your ad unit id and app id.

Hope this helps
