### ISSUE TITLE
com.google.unity.ump.UnityConsentFormCallback class not found

### ISSUE THREAD

**Issue by mrcece** [googleads/googleads-mobile-unity#2896]
### [REQUIRED] Step 1: Describe your environment

  * Unity version:  2022.3.6
  * Google Mobile Ads Unity plugin version: v8.5.2
  * Platform: Android
  * Platform OS version: Android 13
  * Any specific devices issue occurs on:
  * Mediation ad networks used, and their versions: 

#### Steps to reproduce:
I implemented UMP to show GDPR message I've created on Admob panel. I followed the [Admob's doc](https://developers.google.com/admob/unity/privacy) but I got this error message on LogCat:
`AndroidJavaException: java.lang.ClassNotFoundException: com.google.unity.ump.UnityConsentFormCallback`

**Comment by NVentimiglia** [comment]
Confirmed the issue, thank you for the report.

**Comment by LambdaStudiosPH** [comment]
I encountered the same error using v8.5.2. @mrcece  when you tested in an actual device did the consent dialogue appear? I tried on mine but its not appearing even after adding the hash device id. Im trying to figure out if the com.google.unity.ump.UnityConsentFormCallback  is the cause of it not appearing or not

**Comment by mrcece** [comment]
There is noting, just error on actual device.

**Comment by LambdaStudiosPH** [comment]
Same result. Looks like v8.5.2 is fully broken.

**Comment by LambdaStudiosPH** [comment]
@mrcece  what version are you now using? Is v8.5.1 fine and doesnt have this error? I need the consent asap and it loooks like the fix for v8.5.2 would take another two weeks to be released

**Comment by mrcece** [comment]
I don't know. It is firt time to try

**Comment by umitcankomur** [comment]
Adding `-keep class com.google.unity.** {*;}` to the custom proguard file solved the issue for me.

**Comment by GeorgesGraire** [comment]
> Adding `-keep class com.google.unity.** {*;}` to the custom proguard file solved the issue for me.

I have the same problem as the others, and adding this line to the proguard file didn't help.

![image](https://github.com/googleads/googleads-mobile-unity/assets/82153698/b03bd6ca-8626-4c50-9710-ce3261a3bac3)

**Comment by GeorgesGraire** [comment]
> > > Adding `-keep class com.google.unity.** {*;}` to the custom proguard file solved the issue for me.
> > 
> > 
> > I have the same problem as the others, and adding this line to the proguard file didn't help. @NVentimiglia
> > ![image](https://user-images.githubusercontent.com/82153698/263665687-b03bd6ca-8626-4c50-9710-ce3261a3bac3.png)
> > In the Unity logs, not error is raised but actual validation logs:
> > ![image](https://user-images.githubusercontent.com/82153698/263707758-d41dd8a5-dd0e-4b84-8d13-ba8e662b0c59.png)
> 
> These are all the proguard rules I added. `-keep class com.google.unity.ads.** { *; } -keep public class com.google.android.gms.ads.**{ public *; } -keep public class com.google.ads.**{ public *; } -keep public class com.google.android.ump.**{ public *; } -keep class com.google.ads.consent.** { <fields>; } -keep class com.google.unity.** { *; } -keepattributes *Annotation* -keepattributes Signature`

Unfortunately still the same error, I wonder why it works on your side and not mine. Also it's my first time implementing the AdMob GDPR consent form so maybe I'm doing something wrong. I'm relying on the the sample scripts.

**Comment by mrcece** [comment]
@GeorgesGraire I updated my project to 2022.3.8 then it works. Problem is about openjdk.

**Comment by GeorgesGraire** [comment]
> @GeorgesGraire I updated my project to 2022.3.8 then it works. Problem is about openjdk because External dependency tool cant find the right libraries.

Thanks! I updated Unity to the latest 2022.3.8 LTS version and the consent form is now displayed.

**Comment by LambdaStudiosPH** [comment]
Its not working on latest 2021 LTS release

**Comment by NVentimiglia** [comment]
Hi Everyone,

We think this issue may be a caching issue related to upgrading from `8.5.1`. I was able to replicate this issue at first on my end, but by deleting my `Assets/Plugins` folder and reinstalling the plugin, I solved the issue.

If anyone else runs into this issue again, please feel free to reopen this issue and ping me.

**Comment by rO5h** [comment]
@NVentimiglia  Still getting this error.
I tried adding all the rules mentioned above to the custom proguard file,
I tried deleting the plugins folder and reinstalling it.
I'm using unity version 2023.1.5f1 and google mobile ads 8.5.2

**Comment by gollobo** [comment]
@rO5h try a Clean Build after deleting the plugins folder and reinstalling it, solved the issue for me.

**Comment by JenzSahlin** [comment]
We had the same problem! We cleared the cache from the library folder and after that it worked!

**Comment by dginovker** [comment]
Deleted Library folder and updated proguard files, but still crashing for us. Upgrading Unity isn't an option, since our project is quite large and we can't afford random things breaking. We also can't simply delete the whole Android/Plugins folder, since we have a lot of various plugins in there.

**Comment by Keyden** [comment]
update to unity2021.3.32 solve this problem

**Comment by Seanm07** [comment]
I'm still getting this issue in the 8.5.3 release of the plugin, previously the project was using 8.4.1 and I deleted the GoogleMobileAds and Plugins folder before updating.

I've tried force resolving, doing a clean build, adding proguard rules mentioned in here.
I'm using Unity 2022.2.20f1 with google version handler 1.2.177

This is the full error I'm getting when trying to call ConsentInformation.Update:

AndroidJavaException: java.lang.ClassNotFoundException: com.google.unity.ump.UnityConsentFormCallback
java.lang.ClassNotFoundException: com.google.unity.ump.UnityConsentFormCallback
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at com.unity3d.player.ReflectionHelper.nativeProxyInvoke(Native Method)
	at com.unity3d.player.ReflectionHelper.-$$Nest$smnativeProxyInvoke(Unknown Source:0)
	at com.unity3d.player.ReflectionHelper$a.invoke(Unknown Source:29)
	at java.lang.reflect.Proxy.invoke(Proxy.java:913)
	at $Proxy13.onConsentInfoUpdateSuccess(Unknown Source)
 	at com.google.android.gms.internal.consent_sdk.zzt.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:3

Strangely I can confirm the class com.google.unity.ump.UnityConsentFormCallback is inside Assets/Plugins/Android/googlemobileads-unity.aar but inspecting a built apk in android studio the folders com/google/unity/ump is not inside any of the classes.dex

**Comment by fightaway** [comment]
@NVentimiglia I still face this problem

**Comment by devjh4** [comment]
We have same problem

Log cat error
AndroidJavaException: java.lang.ClassNotFoundException: com.google.unity.ump.UnityConsentFormCallback
    java.lang.ClassNotFoundException: com.google.unity.ump.UnityConsentFormCallback
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at com.unity3d.player.ReflectionHelper.nativeProxyInvoke(Native Method)
        at com.unity3d.player.ReflectionHelper.-$$Nest$smnativeProxyInvoke(Unknown Source:0)
        at com.unity3d.player.ReflectionHelper$a.invoke(Unknown Source:29)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy17.onConsentInfoUpdateSuccess(Unknown Source)
        at com.google.android.gms.internal.consent_sdk.zzt.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8762)
        at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.interna

Unity version 2022.3.14f1 lts
Admob 8.6.0

**Comment by juaprebo** [comment]
Hi @NVentimiglia, I'm getting this error instead: 
`Error calling loadAndShowConsentFormIfRequired: java.lang.NoSuchMethodError: No static method loadAndShowConsentFormIfRequired(Landroid/app/Activity;Lcom/google/android/ump/ConsentForm$OnConsentFormDismissedListener;)V in class Lcom/google/android/ump/UserMessagingPlatform; or its super classes (declaration of 'com.google.android.ump.UserMessagingPlatform' appears in /data/app/com.codigames.idle.police.department.tycoon.cop-gZFnL55G4WNFyXudceTtfw==/base.apk!classes3.dex)`

I'm on Unity 2020.3.20f1 (there Is not possible to update) and GoogleMobileAdsPlugin version 8.7.0.
Thank you.

**Comment by bit-man** [comment]
Just to let you know that if this failure occurs at Gitlab CI cleaning runners cache did the trick for me (_Clear runner caches_ button)

**Comment by SponsorAds** [comment]
I love how google earns Billions on our backs and not a single hint of support for their ever breaking libs on every single minor update.
This is a Priority 1 issue... and it is now over 8 months old....
