### ISSUE TITLE
Event callback when ad is clicked?

### ISSUE THREAD

**Issue by wfowler1** [googleads/googleads-mobile-unity#29]
It'd be great if your game could tell (either through an event or some such wizardry) whether or not an ad has been clicked. For example, I give the player the option of waiting five minutes to proceed in the game or to click an ad and proceed immediately. Or, reward 50 energy points for clicking a banner, that sort of thing.

**Comment by rampara** [comment]
Is there a reason you did not want to use the HandleAdOpened callback for this purpose?

Ram

**Comment by rampara** [comment]
This issue is being closed due to its age. If this problem persists please re-open the issue.

**Comment by andpanda** [comment]
It is against AdMob policy to incentive Ad clicking.
