### ISSUE TITLE
Conflicts with Google Play Services plugin

### ISSUE THREAD

**Issue by KhubaibQaiser** [googleads/googleads-mobile-unity#290]
I am developing a 2D game in unity and using google play services plugin (https://github.com/playgameservices/play-games-plugin-for-unity). The problem is when I import the admob plugin and try to build the project the build crashes and gives the error shown in the image. Can you guide me what should I do?
![err](https://cloud.githubusercontent.com/assets/6773396/19465101/d2d8871c-951a-11e6-94c4-3864155f810e.png)

**Comment by rampara** [comment]
Are you using the latest versions of plugins for both Google Mobile Ads and Google Play Games?

**Comment by KhubaibQaiser** [comment]
Solved! The latest version 0.9.35 is working fine with the admob plugin. Thanks.

**Comment by rampara** [comment]
Glad you were able to get your issue resolved.
