### ISSUE TITLE
Empty adapters list in the Ad Inspector, UnityAds not listed

### ISSUE THREAD

**Issue by jonasmora** [googleads/googleads-mobile-unity#2902]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.7f1
  * Google Mobile Ads Unity plugin version: 8.5.1
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: Android 12 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: Pixel 3
  * Mediation ad networks used, and their versions: UnityAdsUnityAdapter-3.8.0

#### Steps to reproduce:

I'm using the sample HelloWorld from this repo. It happens with any adapter, this is just a specific one. I added GoogleMobileAds-v8.5.1, then the UnityAdsUnityAdapter-3.8.0, force resolve, build.

I'm using the Google Mobile Ads App ID from an app that's in production serving ads successfully with an older version.

I modified InterstitialAdController Android _adUnitId, and RewardedAdController Android _adUnitId, also with production values serving ads successfully with an older version.

The adapters list is empty in the ad inspector. If an Interstitial or Rewarded video is loaded, only AdMob is listed as an option.

The adapters aren't listed in the MobileAds.Initialize callback, only com.google.gms.ads.MobileAds is Ready.

Am I missing something?

**Comment by NVentimiglia** [comment]
Hi @jonasmora

Please use your app id with your configured bidding / mediation chain. Please update your ad units to be your own ad units as well. Also make sure to set up your device as a test device. Once you do these things, Ad Inspector should work.

https://developers.google.com/admob/unity/test-ads

**Comment by jonasmora** [comment]
Hi @NVentimiglia, I'm using my app id, and my ad units. I also enabled my device as test device. I still think nothing of that is necessary, the adapter is not being listed in the initialize callback. It's not that is initialized with an error, it's not being listed at all.

**Comment by NVentimiglia** [comment]
@jonasmora 

Understood. Next steps Is I will need some specific details. Can you open a case with the [Google SDK team](https://groups.google.com/g/google-admob-ads-sdk). Please include your app id, ad units, and any screen shots / logs showing the missing adapters.

**Comment by jonasmora** [comment]
I already did, thanks.
