### ISSUE TITLE
Cannot click on native ads

### ISSUE THREAD

**Issue by nmtoan91** [googleads/googleads-mobile-unity#2911]
### Step 0: Are you in the right place?
Hi, I'm trying to install native ads in my game. I can load the fill the ads textures/text but it is not clickable.
Here is my steps:
1. I create a Screen Space camera and drag the Camera to it.
2. I use RawImage ->  add boxcollider  -> Adjust the size of boxcoliders.
3. I register them to the ads API:
```
if (!MyAdmob.I.nativeAd.RegisterIconImageGameObject(imageIcon.gameObject))
            {
                Debug.LogError("ERROR RegisterIconImageGameObject");
            }
```
I even use a snap code to check the collider and it works fine (I can touch the RawImage using raycast):
```
Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
            RaycastHit hit;
            if (Physics.Raycast(ray, out hit, 1000))  Debug.Log("hit " + hit.transform.name);
            else  Debug.Log("DONOT hit");
```

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.7
  * Google Mobile Ads Unity plugin version:  8.5.2
  * Platform: Android
  * Platform OS version:  Android 12

**Comment by NVentimiglia** [comment]
I see you are interchanging physics3d (Raycast) with physics2d (Boxcollider). Please make sure to the 3D physics stack (Raycast, MeshCollider, Rigidbody) and make sure they are layered correctly with the main camera.

**Comment by nmtoan91** [comment]
Hi @NVentimiglia, I believe BoxClider is physics3D. 
In the [tutorial ](https://developers.google.com/admob/unity/native), they use BoxCollider too.

**Comment by NVentimiglia** [comment]
I double checked the sample

- BoxCollider2D is correct.
- There is no rigidbody attached to the elements.
- The Layer is UI.

Can you take a look at the EventSystem inspector to make sure the NativeAdElement is being hit.

**Comment by nmtoan91** [comment]
@NVentimiglia 
I changed to use BoxCollider2D, but it still doesn't work.
I removed rigibody and set layer to UI. 

![image](https://github.com/googleads/googleads-mobile-unity/assets/26214365/189470aa-36c3-44ba-87f3-4f204729e6c6)

![image](https://github.com/googleads/googleads-mobile-unity/assets/26214365/1f6f7d38-6276-4d90-902f-c5635d2bcae6)

**Comment by NVentimiglia** [comment]
@nmtoan91 

Is there any messages on the `EventSystem` inspector? It should display the element which is being targeted by the Unity UI / physics system.

**Comment by nmtoan91** [comment]
@NVentimiglia 
Here is the screenshot of the EventSystem when I hover the mouse on the Ads Image. 
However,  can you give a sample scene that works, please?

![image](https://github.com/googleads/googleads-mobile-unity/assets/26214365/6527f370-ce0a-4b3e-8657-fd87dafe21c2)

**Comment by nmtoan91** [comment]
@NVentimiglia I'm sorry, I'm still struggling with this error. Could you help me to check?

**Comment by NVentimiglia** [comment]
@nmtoan91 can you provide a minimal sample, and I will take a look.
