### ISSUE TITLE
 The type or namespace name 'RewardBasedVideoAd' could not be found 

### ISSUE THREAD

**Issue by Pixchel69** [googleads/googleads-mobile-unity#2916]
All things are in the title.

When I try to install Google Ads mobiles, I got this error

**Comment by NVentimiglia** [comment]
Hi @Pixchel69 what release are you using? I do not see this type either.

https://github.com/search?q=repo%3Agoogleads%2Fgoogleads-mobile-unity%20path%3A%2F%5Esource%5C%2F%2F%20RewardBasedVideoAd&type=code

**Comment by Pixchel69** [comment]
Google ads 8.5.2 with unity 2021.23.1f

**Comment by desouse** [comment]
@Pixchel69 RewardBasedVideoAd was removed 2 years ago
https://github.com/googleads/googleads-mobile-unity/releases/tag/v6.0.0

**Comment by NVentimiglia** [comment]
@Pixchel69 please remove the plugin to ensure a fresh install, and update to the latest version.
