### ISSUE TITLE
Error when switch to android platform?

### ISSUE THREAD

**Issue by ForestJungle** [googleads/googleads-mobile-unity#292]
Hello everyone.I received this error when I switch plugins to android Platform in Unity.When I run editor then it show this under error.Can Anyone help?Thanks.
Unable to find the Android SDK manager tool.  Required Android packages (extra-google-m2repository, extra-android-m2repository) can not be installed.  Android SDK path not set.  Set the Android SDK property using the Unity "Edit > Preferences > External Tools" menu option on Windows or the "Unity > Preferences > External Tools" menu option on OSX. Alternatively, set the ANDROID_HOME environment variable
UnityEngine.Debug:LogError(Object)
GooglePlayServices.ResolverVer1_1:DoResolution(PlayServicesSupport, String, OverwriteConfirmation, Action)
GooglePlayServices.PlayServicesResolver:Resolve(Action)
GooglePlayServices.PlayServicesResolver:AutoResolve()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by ForestJungle** [comment]
I fixed this error.You only need turn on SDK manager and install these package:
Android Support Repository
Google Repository
Google play services

**Comment by rampara** [comment]
Glad you were able to resolve your issue.
