### ISSUE TITLE
Unity 3.8.0 - Resolution failed

### ISSUE THREAD

**Issue by dcosmin-97** [googleads/googleads-mobile-unity#2925]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.30f1
  * Google Mobile Ads Unity plugin version: 8.5.2
  * Platform: Android - Unity Editor
  * Mediation ad networks used, and their versions: Applovin 6.8.0, Liftoff 4.0.0, Meta 3.10.0, Mintegral 1.2.1, Pangle 2.3.0 and Unity 3.8.0

#### Steps to reproduce:
Just add all the packages without unity 3.8.0 and force resolve. Everything will be fine.
Add Unity 3.8.0 and force resolve again. You will get the following error:
Resolution failed

Failed to fetch the following dependencies:
org.jetbrains.kotlin:kotlin-bom:1.8.10

Initially I also had Firebase analytics 11.4.0 and Crashlytics 11.4.0 but I started a new project to test just the mediations. 
Is there a short fix for this? 
Thank you!

**Comment by NVentimiglia** [comment]
@dcosmin-97 I see this issue. I am raising awareness for this issue. Thank you for your patience.

**Comment by dcosmin-97** [comment]
@NVentimiglia  Hello! Thank you for your response! 
Is AdColony going to get a fix soon? It shows errors in the editor when you import it over Google Admob 8.5.2.

**Comment by NVentimiglia** [comment]
@dcosmin-97 

I do not see any errors in the editor with AdColonyUnityAdapter-2.6.2 2 and Admob 8.5.2

**Comment by dcosmin-97** [comment]
@NVentimiglia try to add Admob 8.5.2, Liftoff 4.0.0, Meta 3.10.0, Mintegral 1.2.1, Pangle 2.3.0 and AdColony over them. It will show the errors regarding MediationExtras.

**Comment by luizjunior** [comment]
same problem here with Meta Mediation Adapter [Version 3.11.0]

**Comment by nealohb** [comment]
Same problem for me, using identical mediation setup as luizjunior. Meta is the culprit - removing it and everything works fine.

Also for whatever reason when Meta is involved there are depency conflicts which causes a lot of depencies to get bumped to use the latest version (resulting in downloading versions that are not officially supported). For me it looks like this:

Some conflicting dependencies were found.
The following dependency versions were modified:
com.google.ads.mediation:applovin:11.10.1.0 --> com.google.ads.mediation:applovin:11.+
com.google.ads.mediation:facebook:6.15.0.0 --> com.google.ads.mediation:facebook:6.+
com.google.ads.mediation:unity:4.8.0.0 --> com.google.ads.mediation:unity:4.+
com.google.android.gms:play-services-ads:22.3.0 --> com.google.android.gms:play-services-ads:+
com.google.android.gms:play-services-auth:20.4.1+ --> com.google.android.gms:play-services-auth:+
com.google.android.gms:play-services-base:18.2.0 --> com.google.android.gms:play-services-base:+
com.google.android.gms:play-services-games:23.1.0+ --> com.google.android.gms:play-services-games:+
com.google.android.gms:play-services-nearby:17.0.0+ --> com.google.android.gms:play-services-nearby:+
com.google.android.play:review:2.0.1+ --> com.google.android.play:review:+
com.google.android.ump:user-messaging-platform:2.1.0 --> com.google.android.ump:user-messaging-platform:+
com.google.firebase:firebase-analytics:21.3.0 --> com.google.firebase:firebase-analytics:+
com.google.firebase:firebase-auth:22.1.1 --> com.google.firebase:firebase-auth:+
com.google.firebase:firebase-common:20.3.3 --> com.google.firebase:firebase-common:+
com.google.firebase:firebase-config:21.4.1 --> com.google.firebase:firebase-config:+
com.google.firebase:firebase-database:20.2.2 --> com.google.firebase:firebase-database:+
com.google.firebase:firebase-functions:20.3.1 --> com.google.firebase:firebase-functions:+
com.unity3d.ads:unity-ads:4.8.0 --> com.unity3d.ads:unity-ads:+

**Comment by ThaurD** [comment]
i think it is gradle problem. When I updated Unity to 2022, the problem was solved @dcosmin-97

**Comment by dcosmin-97** [comment]
> i think it is gradle problem. When I updated Unity to 2022, the problem was solved @dcosmin-97

Thank you!
I will try that.
By default, Unity 2022 has <html><body>


Unity version | Gradle version | Android Gradle Plug-in version
-- | -- | --
2022.3 | 7.2 | 7.1.2


</body>
</html>

Has anyone tried this?

**Comment by dcosmin-97** [comment]
> i think it is gradle problem. When I updated Unity to 2022, the problem was solved @dcosmin-97

I have tried with Unity 2022 and it still does not work

**Comment by NVentimiglia** [comment]
This is a known issue and we are working on a fix.

As a work around you can hard code the maximum version of the google mobile ads Android sdk in the `GoogleMobileAdsDependencies.xml` file.

```
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.android.gms:play-services-ads:[22.3.0]">
      <repositories>
        <repository>https://maven.google.com/</repository>
      </repositories>
    </androidPackage>
  </androidPackages>

  <iosPods>
    <iosPod name="Google-Mobile-Ads-SDK" version="~> 10.9">
      <sources>
        <source>https://github.com/CocoaPods/Specs</source>
      </sources>
    </iosPod>
  </iosPods>
</dependencies>
```

**Comment by cyrusamirabadi** [comment]
I resolved this issue by adding my "App ID" to the "Android Manifest" file:

<meta-data android:name="unityplayer.UnityActivity" android:value="true"
android:name="com.google.android.gms.ads.APPLICATION_ID"
android:value="ca-app-pub-3940256099942544~3347511713"/>

Just remember to change it with your app id and also don't forget to restart your Unity.

**Comment by dcosmin-97** [comment]
> This is a known issue and we are working on a fix.
> 
> As a work around you can hard code the maximum version of the google mobile ads Android sdk in the `GoogleMobileAdsDependencies.xml` file.
> 
> ```
> <dependencies>
>   <androidPackages>
>     <androidPackage spec="com.google.android.gms:play-services-ads:[22.3.0]">
>       <repositories>
>         <repository>https://maven.google.com/</repository>
>       </repositories>
>     </androidPackage>
>   </androidPackages>
> 
>   <iosPods>
>     <iosPod name="Google-Mobile-Ads-SDK" version="~> 10.9">
>       <sources>
>         <source>https://github.com/CocoaPods/Specs</source>
>       </sources>
>     </iosPod>
>   </iosPods>
> </dependencies>
> ```

I have tried this and it is not working for me

**Comment by NVentimiglia** [comment]
@dcosmin-97 

- Was there any change in behaviour?
- You can also try using Unity 2022.3 or greater


@cyrusamirabadi 

- This sounds like a different issue. Were there any prebuild errors. If you can double check the `External Dependency Manager > Android Resolver > Force Resolve` command, that could be reporting issues.

**Comment by dcosmin-97** [comment]
> @dcosmin-97
> 
>     * Was there any change in behaviour?
> 
>     * You can also try using Unity 2022.3 or greater
> 
> 
> @cyrusamirabadi
> 
>     * This sounds like a different issue. Were there any prebuild errors. If you can double check the `External Dependency Manager > Android Resolver > Force Resolve` command, that could be reporting issues.

Try with the following setup:
Unity 2022.3.11f1
Admob 8.5.2
Firebase Analytics & Crashlytics 11.6.0
Applovin 6.9.1
Liftoff 4.0.0
Meta 3.11.0
Mintegral 1.2.1
Pangle 2.3.0
Admob setup with com.google.android.gms:play-services-ads:[22.3.0]

Everything is working fine with the above setup.
If you add Unity 3.8.0 and force resolve, you will get the error:
Resolution failed
Failed to fetch the following dependencies:
org.jetbrains.kotlin:kotlin-bom:1.8.10

I have tried other things as well, but no results. Any other ideas?
Thank you!

**Comment by NVentimiglia** [comment]
Hi everyone, 
I have posted a work around for this issue here :
https://developers.google.com/admob/unity/gradle

**Comment by NVentimiglia** [comment]
Closing, if you face continued issues, please reopen.
