### ISSUE TITLE
iPad Ads Sound Issue

### ISSUE THREAD

**Issue by bloodmango** [googleads/googleads-mobile-unity#2927]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.38f1
  * Google Mobile Ads Unity plugin version: 7.0.1(AOS 20.6.0, iOS 9.0.0)
  * Platform: iOS(iPad)
  * Platform OS version: iOS
  * Any specific devices issue occurs on: Only iPad
  * Mediation ad networks used, and their versions: 
  * Mediation(AOS, iOS)
  * Facebook Mediation(6.10.0.0 / 6.9.0.1)
  * Facebook Audience Network(6.4.0/6.9.0 )
  * Tapjoy(12.9.1.0)
  * UnityAds (4.2.1)
  * Vungle (6.11.0.0)
  * IronSource(7.2.1.0 / 7.2.0)
  * AppLovin (11.3.3.0 / 11.4.3)
  * Fyber (8.1.3.0 / 8.1.3.1)
  * Pangle (4.3.0.8.0 / 4.3.0.4.0)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

**There is an issue where the ad sound does not turn off intermittently after playing.**
Download Link : https://apps.apple.com/kr/app/%EA%B1%B4%EC%89%BD%EB%B0%B0%ED%8B%80-%ED%86%A0%ED%83%88%EC%9B%8C%ED%8E%98%EC%96%B4/id1397714781

https://github.com/googleads/googleads-mobile-unity/assets/29276457/8c707c51-d25f-4dc5-a8d8-6e2487e18b1d

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by NVentimiglia** [comment]
@bloodmango 

Thanks for the issue report. This is probably a creative issue, which means I need to report the creative on my end. To do this I will need the creative Id. If you can record a [network trace](https://developers.google.com/admob/ios/network-tracing) of the bad ad I can forward this to the bad ads team.

**Comment by bloodmango** [comment]
@NVentimiglia 
Since this problem occurs after the ad has been viewed, it may not be easy to receive a creative ID from the user.
Is there an API that can obtain creativeID for viewed advertisements?

> @bloodmango
> 
> Thanks for the issue report. This is probably a creative issue, which means I need to report the creative on my end. To do this I will need the creative Id. If you can record a [network trace](https://developers.google.com/admob/ios/network-tracing) of the bad ad I can forward this to the bad ads team.

**Comment by NVentimiglia** [comment]
@bloodmango 

Rest assured I am following up on my end as I see other publishers with this issue. That said, I understand the difficulties, and any additional details (such as the creative id) would help.
