### ISSUE TITLE
Reward Video can't show on Android Version 3.1.0

### ISSUE THREAD

**Issue by ForestJungle** [googleads/googleads-mobile-unity#293]
Hello Everyone.Banner and Popups works fine on android but Reward video doesn't work.I don't know why.Please suggestion for me.thanks.

**Comment by rampara** [comment]
Which ad network are you mediating rewarded video ads from? Have you included the SDK and adapters for that ad network in your Unity project?

**Comment by ForestJungle** [comment]
Hi rampara. I use two ad networks is Unity ads and Vungle.They are still pending.... should I  add more sdk for each seperate ad network?So why don't I use plugins of Unity ads and Vungle without should use Admob?

**Comment by rampara** [comment]
To mediate rewarded video ads through the AdMob mediation platform and Unity plugin, you will have to add the adapters and SDKs for both Unity Ads and Vungle to the `Assets/Plugins/Android` directory of your Unity project.

**Comment by ForestJungle** [comment]
I downloaded adapaterunityandroid and push to Assset/Plugins/Android.for Unity greater 5.0 support Unity services and I don't need import sdk unity 2.0.But I build android and test it still reponse "Failed".Where am I wrong? :)

**Comment by rampara** [comment]
Why do you not need to include the SDK for Unity Ads?

**Comment by ForestJungle** [comment]
As you said.I'm using Unity 5.4.1f1 which have Unity services integrated all about Unity Ads,In app purchase...I only need setup unity services on server and then get ID.

**Comment by rampara** [comment]
Mediating Unity ads through the AdMob mediation platform is currently incompatible with the Unity Ads integration provided directly through the Unity IDE. To receive Unity Ads through this plugin you will have to manually include the Unity Ads SDK in your project.

**Comment by ForestJungle** [comment]
I imported Vungle SDK and use itself to show video Ads.Now I only use google mobile ads to show banner and Interstitial.I'm wondering If using seperate sdk ad network so why should I via admob to load video rewarded? thanks.:)

**Comment by rampara** [comment]
You can find more information on the benefits of the AdMob mediation platform in this [help center doc](https://support.google.com/admob/answer/3063564). As your original problem has been addressed, I am closing this issue.
