### ISSUE TITLE
How to disable SDK crash reporting for Firebase Crashlytics?

### ISSUE THREAD

**Issue by T-1K** [googleads/googleads-mobile-unity#2932]
As [Firebase](https://firebase.google.com/docs/crashlytics/troubleshooting?platform=unity#no-crashes-admob-sdk) suggests,
```
App also uses the Google Mobile Ads SDK but not getting crashes
If your project uses Crashlytics alongside the Google Mobile Ads SDK,
it's likely that the crash reporters are interfering when registering exception handlers. 
To fix the issue, turn off crash reporting in the Mobile Ads SDK by calling disableSDKCrashReporting.
```
 we would like to turn off Mobile Ads reporting. What is the equivalent API for `disableSDKCrashReporting` on this plugin?

**Comment by NVentimiglia** [comment]
@T-1K

This is currently not supported from the Unity plugin. I have drafted a feature request, to get this API included.

That said, if you need this urgently you can [call the iOS SDK API directly](https://developers.google.com/admob/unity/custom-events#optional_call_third-party_sdk_native_methods_from_c_scripts) to accomplish this. This API is iOS only, so you do not need to implement much of the C# layer in this guide.

Let me know if you need any help.

**Comment by amjaliks** [comment]
Hi @NVentimiglia, I would like to express my interest in having disableSDKCrashReporting exposed in the Unity plugin as well.
