### ISSUE TITLE
link.xml GUID keeps changing

### ISSUE THREAD

**Issue by amjaliks** [googleads/googleads-mobile-unity#2933]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.48f1
  * Google Mobile Ads Unity plugin version: 8.5.2
  * Platform: Unity Editor
  * Platform OS version: macOS
  * Any specific devices issue occurs on: n/a
  * Mediation ad networks used, and their versions: n/a

#### Observed behavior:
After building the project, the `BuildPreProcessor` copies _link.xml_. Each time this copy action occurs using `AssetDatabase.CopyAsset`, the Unity Editor creates a new _.meta_ file with a new GUID.

#### Expected behavior:
The _link.xml_ should be copied without changing or generating a new GUID for its associated _.meta_ file.

#### Steps to reproduce:

1. Add SDK to a project as UPM package.
2. Build a project.

#### Suggested fix:

Check for the destination _link.xml_ existence before copying, and use `File.copy` instead of `AssetDatabase.CopyAsset` if it already exists. More info can be found on [Unity forum](https://forum.unity.com/threads/assetdatabase-copyasset-changes-guid-of-target.540124/#post-7281097).

**Comment by NVentimiglia** [comment]
Thank you for the feature request. As a temporary work around I would recommend ignore link.xml.meta on any git repositories.

**Comment by NVentimiglia** [comment]
b/308646658

**Comment by kerembaydogan** [comment]
I still have this problem. 

Unity version: 2023.2.20f1
Google Mobile Ads Unity plugin version: 9.2.0
Platform: Unity Editor
Platform OS version: macOS
Any specific devices issue occurs on: n/a
Mediation ad networks used, and their versions: n/a
