### ISSUE TITLE
Exception in onConsentFormDismissed when using Development Build

### ISSUE THREAD

**Issue by eirikost** [googleads/googleads-mobile-unity#2937]
### Environment

  * Unity version: 2022.3.8f1
  * Google Mobile Ads Unity plugin version: 8.5.2
  * Platform: Android
  * Platform OS version: Android 6, 9, 10, 13
  * Any specific devices issue occurs on: -
  * Mediation ad networks used, and their versions: AdMob
  * Development Build

#### Steps to reproduce:

1. Follow the documentation to setup ads with consent: https://developers.google.com/admob/unity/privacy
2. In OnConsentInfoUpdated, handle consent success like this:
```
if (ConsentInformation.CanRequestAds())
{
    MobileAds.Initialize(HandleInitCompleteAction);
}
```
3. In HandleInitCompleteAction we request banner and interstitial ads:

```
private void HandleInitCompleteAction(InitializationStatus initstatus)
{
    PrintStatus("Initialization complete");
    MobileAdsEventExecutor.ExecuteInUpdate(() =>
    {
        RequestBannerAd(); // The exception also occurs without having ad requests here
        _bannerView.Hide();
        RequestInterstitial();
    });
}
```

4. Deploy the app to an Android device with Development Build enabled
6. Banner ads are not working
7. The logs show that the crash happened during a call to onConsentFormDismissed:
```
09-15 19:30:56.497 12727 12918 D Unity   : Uploading Crash Report
09-15 19:30:56.497 12727 12918 E Unity   : UnityException: Internal_CreateGameObject can only be called from the main thread.
09-15 19:30:56.497 12727 12918 E Unity   : Constructors and field initializers will be executed from the loading thread when loading a scene.
09-15 19:30:56.497 12727 12918 E Unity   : Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
09-15 19:30:56.497 12727 12918 E Unity   :   at GoogleMobileAds.Common.MobileAdsEventExecutor.Initialize () [0x00000] in <00000000000000000000000000000000>:0
09-15 19:30:56.497 12727 12918 E Unity   :   at GoogleMobileAds.Ump.Android.ConsentFormClient.onConsentFormDismissed (UnityEngine.AndroidJavaObject error) [0x00000] in <00000000000000000000000000000000>:0
09-15 19:30:56.497 12727 12918 E Unity   :   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <00000000000000000000000000000000>:0
09-15 19:30:56.497 12727 12918 E Unity   :   at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0
09-15 19:30:56.497 12727 12918 E Unity   :   at UnityEngine.AndroidJ
```

The workaround for me is to call RequestBannerAd again later when using Development Build since the banner view remains null after the first attempt. Note that the status "Initialization complete" is logged but none of the callbacks for the banner ad seems to be called as they do not log anything.

Not a critical problem, I was just wondering if it's just me or if there's something in the plugin that could be fixed. I cannot see that I have any debug specific code that should cause this issue.

**Comment by NVentimiglia** [comment]
@eirikost 

can you share the implementation for `RequestBannerAd` and `RequestInterstitial `? What concerns me is that we should not be creating game objects from the Android clients.

**Comment by eirikost** [comment]
@NVentimiglia

Sure, see the code below. I only destroy and create the ads as done in [this guide](https://developers.google.com/admob/unity/banner/anchored-adaptive), but we need to avoid that?

```
private void RequestBannerAd()
    {
#if UNITY_EDITOR
        string adUnitId = "unused";
#elif UNITY_ANDROID
        string adUnitId = "ca-app-pub-xxxx";
        if (_isDebugBuild)
        {
            adUnitId = "ca-app-pub-3940256099942544/6300978111"; //Fake
            PrintStatus("Using fake banner ad");
        }
#elif (UNITY_5 && UNITY_IOS) || UNITY_IPHONE
        string adUnitId = "ca-app-pub-xxxxx";
#else
        string adUnitId = "unexpected_platform";
#endif

        // Clean up banner before reusing
        if (_bannerView != null)
        {
            _bannerView.Destroy();
        }

        _bannerView = new BannerView(adUnitId, AdSize.GetLandscapeAnchoredAdaptiveBannerAdSizeWithWidth(450), AdPosition.Top);

        _bannerView.OnBannerAdLoaded += () =>
        {
            PrintStatus("Banner ad loaded.");
            OnAdLoadedEvent.Invoke();
        };

        _bannerView.OnBannerAdLoadFailed += (LoadAdError error) =>
        {
            PrintStatus("Banner ad failed to load with error: " + error.GetMessage());
            OnAdFailedToLoadEvent.Invoke();
        };
        _bannerView.OnAdImpressionRecorded += () =>
        {
            PrintStatus("Banner ad recorded an impression.");
        };
        _bannerView.OnAdClicked += () =>
        {
            PrintStatus("Banner ad recorded a click.");
        };
        _bannerView.OnAdFullScreenContentOpened += () =>
        {
            PrintStatus("Banner ad opening.");
            OnAdOpeningEvent.Invoke();
        };
        _bannerView.OnAdFullScreenContentClosed += () =>
        {
            PrintStatus("Banner ad closed.");
            OnAdClosedEvent.Invoke();
        };
        _bannerView.OnAdPaid += (AdValue adValue) =>
        {
            string msg = string.Format("{0} (currency: {1}, value: {2}",
                                        "Banner ad received a paid event.",
                                        adValue.CurrencyCode,
                                        adValue.Value);
            PrintStatus(msg);
        };
        // Load a banner ad
        _bannerView.LoadAd(CreateAdRequest());
    }
```


```
private void RequestInterstitial()
{
    #if UNITY_EDITOR
    string adUnitId = "unused";
    #elif UNITY_ANDROID
    string adUnitId = "ca-app-pub-xxxx";
    if (_isDebugBuild)
        adUnitId = "ca-app-pub-3940256099942544/1033173712"; //Fake
    #elif (UNITY_5 && UNITY_IOS) || UNITY_IPHONE
    string adUnitId = "ca-app-pub-xxxx";
    #else
    string adUnitId = "unexpected_platform";
    #endif

    // Clean up interstitial before using it
    if (_interstitialAd != null)
    {
        _interstitialAd.Destroy();
    }

    // Load an interstitial ad
    InterstitialAd.Load(adUnitId, CreateAdRequest(),
        (InterstitialAd ad, LoadAdError loadError) =>
        {
            if (loadError != null)
            {
                PrintStatus("Interstitial ad failed to load with error: " + loadError.GetMessage());
                return;
            }
            else if (ad == null)
            {
                PrintStatus("Interstitial ad failed to load.");
                return;
            }

            PrintStatus("Interstitial ad loaded.");
            _interstitialAd = ad;

            ad.OnAdFullScreenContentOpened += () =>
            {
                PrintStatus("Interstitial ad opening.");
                OnAdOpeningEvent.Invoke();
            };
            ad.OnAdFullScreenContentClosed += () =>
            {
                PrintStatus("Interstitial ad closed.");
                OnAdClosedEvent.Invoke();
            };
            ad.OnAdImpressionRecorded += () =>
            {
                PrintStatus("Interstitial ad recorded an impression.");
            };
            ad.OnAdClicked += () =>
            {
                PrintStatus("Interstitial ad recorded a click.");
            };
            ad.OnAdFullScreenContentFailed += (AdError error) =>
            {
                PrintStatus("Interstitial ad failed to show with error: " + error.GetMessage());
            };
            ad.OnAdPaid += (AdValue adValue) =>
            {
                string msg = string.Format("{0} (currency: {1}, value: {2}",
                                           "Interstitial ad received a paid event.",
                                           adValue.CurrencyCode,
                                           adValue.Value);
                PrintStatus(msg);
            };
        });
}
```

**Comment by NVentimiglia** [comment]
Hi @eirikost,
I think the problem is [this code](https://github.com/googleads/googleads-mobile-unity/blob/9b78bbb7327de1f31768edbf7b895dbabde21564/source/plugin/Assets/GoogleMobileAds/Platforms/Unity/BaseAdClient.cs#L26) which I will ask to be removed. The good news is this is UnityEditor code only and will not affect android or iOS deplotments.

That said, have you looked into using the main thread option?
https://developers.google.com/admob/unity/global-settings#raise_ad_events_on_the_unity_main_thread

**Comment by eirikost** [comment]
@NVentimiglia 
That's great, thank you!

Yea, it happened even though the main thread option was enabled.

**Comment by NVentimiglia** [comment]
@eirikost 

Looking at the stack trace I think the problem code is before the initializer.  I do not see `Initialization complete` in the trace. And the event in question is UMP, not initialization. Can you share the full initialization code? 

```
09-15 19:30:56.497 12727 12918 D Unity   : Uploading Crash Report
09-15 19:30:56.497 12727 12918 E Unity   : UnityException: Internal_CreateGameObject can only be called from the main thread.
09-15 19:30:56.497 12727 12918 E Unity   : Constructors and field initializers will be executed from the loading thread when loading a scene.
09-15 19:30:56.497 12727 12918 E Unity   : Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
09-15 19:30:56.497 12727 12918 E Unity   :   at GoogleMobileAds.Common.MobileAdsEventExecutor.Initialize () [0x00000] in <00000000000000000000000000000000>:0
09-15 19:30:56.497 12727 12918 E Unity   :   at GoogleMobileAds.Ump.Android.ConsentFormClient.onConsentFormDismissed (UnityEngine.AndroidJavaObject error) [0x00000] in <00000000000000000000000000000000>:0
```

```
if (ConsentInformation.CanRequestAds())
{
    MobileAds.Initialize(HandleInitCompleteAction);
}
private void HandleInitCompleteAction(InitializationStatus initstatus)
{
    PrintStatus("Initialization complete");
    MobileAdsEventExecutor.ExecuteInUpdate(() =>
    {
        RequestBannerAd(); // The exception also occurs without having ad requests here
        _bannerView.Hide();
        RequestInterstitial();
    });
}
```

**Comment by hau99** [comment]
> 
> 
> ### Environment
> 
>   * Unity version: 2022.3.8f1
>   * Google Mobile Ads Unity plugin version: 8.5.2
>   * Platform: Android
>   * Platform OS version: Android 6, 9, 10, 13
>   * Any specific devices issue occurs on: -
>   * Mediation ad networks used, and their versions: AdMob
>   * Development Build
> 
> ### Describe the problem
> 
> #### Steps to reproduce:
> 
> 1. Follow the documentation to setup ads with consent: https://developers.google.com/admob/unity/privacy
> 2. In OnConsentInfoUpdated, handle consent success like this:
> ```
> if (ConsentInformation.CanRequestAds())
> {
>     MobileAds.Initialize(HandleInitCompleteAction);
> }
> ```
> 3. In HandleInitCompleteAction we request banner and interstitial ads:
> 
> ```
> private void HandleInitCompleteAction(InitializationStatus initstatus)
> {
>     PrintStatus("Initialization complete");
>     MobileAdsEventExecutor.ExecuteInUpdate(() =>
>     {
>         RequestBannerAd(); // The exception also occurs without having ad requests here
>         _bannerView.Hide();
>         RequestInterstitial();
>     });
> }
> ```
> 
> 4. Deploy the app to an Android device with Development Build enabled
> 6. Banner ads are not working
> 7. The logs show that the crash happened during a call to onConsentFormDismissed:
> ```
> 09-15 19:30:56.497 12727 12918 D Unity   : Uploading Crash Report
> 09-15 19:30:56.497 12727 12918 E Unity   : UnityException: Internal_CreateGameObject can only be called from the main thread.
> 09-15 19:30:56.497 12727 12918 E Unity   : Constructors and field initializers will be executed from the loading thread when loading a scene.
> 09-15 19:30:56.497 12727 12918 E Unity   : Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
> 09-15 19:30:56.497 12727 12918 E Unity   :   at GoogleMobileAds.Common.MobileAdsEventExecutor.Initialize () [0x00000] in <00000000000000000000000000000000>:0
> 09-15 19:30:56.497 12727 12918 E Unity   :   at GoogleMobileAds.Ump.Android.ConsentFormClient.onConsentFormDismissed (UnityEngine.AndroidJavaObject error) [0x00000] in <00000000000000000000000000000000>:0
> 09-15 19:30:56.497 12727 12918 E Unity   :   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <00000000000000000000000000000000>:0
> 09-15 19:30:56.497 12727 12918 E Unity   :   at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0
> 09-15 19:30:56.497 12727 12918 E Unity   :   at UnityEngine.AndroidJ
> ```
> 
> The workaround for me is to call RequestBannerAd again later when using Development Build since the banner view remains null after the first attempt. Note that the status "Initialization complete" is logged but none of the callbacks for the banner ad seems to be called as they do not log anything.
> 
> Not a critical problem, I was just wondering if it's just me or if there's something in the plugin that could be fixed. I cannot see that I have any debug specific code that should cause this issue.

**Comment by NVentimiglia** [comment]
@hau99 

I think the problem is in your controller and how it handles the response from the consent form.

```
UnityException: Internal_CreateGameObject can only be called from the main thread.
```

I would need to see the full solution to diagnose.

**Comment by eirikost** [comment]
@NVentimiglia 

Sure thing, here are my start and awake functions, and some more!

```
void Start()
{
    MobileAds.RaiseAdEventsOnUnityMainThread = true;

    MobileAds.SetiOSAppPauseOnBackground(true);

    var debugSettings = new ConsentDebugSettings
    {
        DebugGeography = DebugGeography.NotEEA,
        TestDeviceHashedIds = new List<string>
        {
                "xxx" //Censored
        }
    };

    var request = new ConsentRequestParameters
    {
        TagForUnderAgeOfConsent = false,
        ConsentDebugSettings = debugSettings
    };

    var deviceIds = new List<String>() { AdRequest.TestDeviceSimulator };

    var requestConfiguration = new RequestConfiguration {
        TagForChildDirectedTreatment = TagForChildDirectedTreatment.Unspecified,
        TestDeviceIds = deviceIds,
    };

    MobileAds.SetRequestConfiguration(requestConfiguration);

    if (!DataManager.Instance.PlayerData.IsAdsRemoved || _isDebugBuild){
        ConsentInformation.Update(request, OnConsentInfoUpdated);
    }
    else
    {
        PrintStatus("Ads are removed");
    }
}

void Awake() {
    _isDebugBuild = Debug.isDebugBuild;

    if (Instance){
        Destroy(gameObject);
    }
    else {
        Instance = this;
        DontDestroyOnLoad(gameObject);
    }
}

void OnConsentInfoUpdated(FormError consentError)
{
    if (consentError != null)
    {
        // Handle the error.
        PrintError(consentError);
        
        return;
    }

    // If the error is null, the consent information state was updated.
    // You are now ready to check if a form is available.
    ConsentForm.LoadAndShowConsentFormIfRequired((FormError formError) =>
    {
        if (formError != null)
        {
            // Consent gathering failed.
            PrintError(consentError);
            return;
        }

        // Consent has been gathered.
        if (ConsentInformation.CanRequestAds())
        {
            MobileAds.Initialize(HandleInitCompleteAction);
        }
    });
}

private void HandleInitCompleteAction(InitializationStatus initstatus)
{
    PrintStatus("Initialization complete");

    // Callbacks from GoogleMobileAds are not guaranteed to be called on the main thread.
    // We use MobileAdsEventExecutor to schedule these calls on the next Update() loop.
    MobileAdsEventExecutor.ExecuteInUpdate(() =>
    {
        RequestBannerAd();
        _bannerView.Hide();
        RequestInterstitial();
    });
}

void Update()
{   
    if (Menu.SceneChange && (!DataManager.Instance.PlayerData.IsAdsRemoved || _isDebugBuild)){
        PrintStatus("Time: " + Time.time + " next interstitial: " + (_timeLastInterstitial + _intervalInterstitial));
        if (Time.time > (_timeLastInterstitial + _intervalInterstitial)){
            ShowInterstitial();
            _timeLastInterstitial = Time.time;
            RequestInterstitial();
        }
        Menu.SceneChange = false;
    }
}

private AdRequest CreateAdRequest()
{
    return new AdRequest();
}

private void PrintError(FormError error)
{
    if (_isDebugBuild)
    {
        PrintStatus(error.Message);
        Debug.LogError(error);
    }
}

private void PrintStatus(string status)
{
    if (_isDebugBuild)
        Debug.Log("Eirik: Ads " + status);
}
```

**Comment by NVentimiglia** [comment]
`MobileAdsEventExecutor.ExecuteInUpdate()` should not be needed if `MobileAds.RaiseAdEventsOnUnityMainThread = true;`

That said, I would recommend removing the code which touches game objects from the handlers. Looking at the code I do not see anything which touches game objects, so I would recommend cutting it in half until you find the code. Alternatively if you can replicate the error in the hello world sample project, I can take a look.
