### ISSUE TITLE
'VungleAdapter/VungleAdNetworkExtras.h' file not found

### ISSUE THREAD

**Issue by dcosmin-97** [googleads/googleads-mobile-unity#2938]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.30f1
  * Google Mobile Ads Unity plugin version: 8.5.2
  * Platform: Unity Editor - macOS
  * Mediation ad networks used, and their versions: applovin 6.9.0, Liftoff 4.0.0, Meta 3.11.0, Mintegral 1.2.1, Pangle 2.3.0, Firebase Crashlytics and Analytics 11.4.0

### [REQUIRED] Step 2: Describe the problem

When building on iOS, I receive the following error: 
'VungleAdapter/VungleAdNetworkExtras.h' file not found

![WhatsApp Image 2023-09-16 at 22 00 23](https://github.com/googleads/googleads-mobile-unity/assets/66071707/2a9a3dcd-3b4a-4ec4-83f0-6353987f9701)

Fix: 
If you update from version 3.9.2, delete the following from Plugins/iOS:
- VungleExtrasBuilder.h
- VungleExtrasBuilder.m
- GADUMVungleInterface.m

The update will not delete them automatically and there will be issues.

**Comment by RomainBitard** [comment]
Wow good find, cost me a unity cloud build T_T, thanks dude

**Comment by RomainBitard** [comment]
@dcosmin-97 do you know if I should delete all the files in this folder or it's mandatory to keep them as cocoapods won't add them if needed ?

**Comment by dcosmin-97** [comment]
> @dcosmin-97 do you know if I should delete all the files in this folder or it's mandatory to keep them as cocoapods won't add them if needed ?

Hello!
What do you mean by deleting all the files? 
These are the files from old versions that are not deleted automatically when you update the Vungle SDK (Liftoff SDK)
    VungleExtrasBuilder.h
    VungleExtrasBuilder.m
    GADUMVungleInterface.m

So, you have to manually delete them.

**Comment by RomainBitard** [comment]
Hey thanks for the reply. I was wondering if you could clean this folder and if the build system or xcode would add necessary files or if they are imported manually when importing admob

**Comment by RomainBitard** [comment]
> @dcosmin-97 
Damn it's odd because I still have the problem...
In my "LiftoffMonetizeExtrasBuilder.m" from GoogleMobileAdsLiftoffMonetizeMediation.unitypackage
I have "#import <LiftoffMonetizeAdapter/VungleAdNetworkExtras.h>"

**Comment by RomainBitard** [comment]
it might not be the same problem though [error] [2023-10-08T20:01:32.663Z] - 7.3.23.2.7.4 - INFO: ❌  /BUILD_PATH/rbitard.french-crapette.iosbuild/temp20231008-2582-vaclx8/Libraries/GoogleMobileAds/Mediation/LiftoffMonetize/Plugins/iOS/LiftoffMonetizeExtrasBuilder.m:17:9: 'LiftoffMonetizeAdapter/VungleAdNetworkExtras.h' file not found

**Comment by RomainBitard** [comment]
I'll remove liftoff and meta, wtf google, each time I update the sdk there are bugs
