### ISSUE TITLE
App Open ads no non-static method with name 'loadAd' (8.5.2)

### ISSUE THREAD

**Issue by ToanTruongAnh** [googleads/googleads-mobile-unity#2939]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2023.1.12f1
  * Google Mobile Ads Unity plugin version: 8.5.2
  * Platform: Android
  * Platform OS version: Android 13
  * Any specific devices issue occurs on:  Mi pad 5
  * Mediation ad networks used, and their versions: AppLovin,Irronsource, Unity,Tapjoy,Adcolony

#### Steps to reproduce:

Use sample code from Open App ads and try to load ad.

#### Relevant Code:
UnityEngine.AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='loadAd' signature='(Ljava/lang/String;Lcom.google.android.gms.ads.AdRequest;)V' in class Ljava.lang.Object;
09-18 22:16:13.050 28623  7544 E Unity   :   at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00000] in <00000000000000000000000000000000>:0 
09-18 22:16:13.050 28623  7544 E Unity   :   at UnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0 
09-18 22:16:13.050 28623  7544 E Unity   :   at AppOpenAdManager.LoadAd () [0x00000] in <00000000000000000000000000000000>:0
```
// TODO(you): code here to reproduce the problem
```

**Comment by ToanTruongAnh10** [comment]
Hi @NVentimiglia  , i checked and has a warning: 

"Some conflicting dependencies were found.
The following dependency versions were modified:
com.google.firebase:firebase-crashlytics-ndk:18.4.3 --> com.google.firebase:firebase-crashlytics-ndk:+"

Here is my Android Dependency:

([rootProject] + (rootProject.subprojects as List)).each { project ->
    project.repositories {
        def unityProjectPath = $/file:///**DIR_UNITYPROJECT**/$.replace("\\", "/")
        maven {
            url "https://maven.google.com"
        }
        maven {
            url (unityProjectPath + "/Assets/Firebase/m2repository") // Assets/Firebase/Editor/AnalyticsDependencies.xml:18, Assets/Firebase/Editor/AppDependencies.xml:22, Assets/Firebase/Editor/AuthDependencies.xml:20, Assets/Firebase/Editor/CrashlyticsDependencies.xml:20, Assets/Firebase/Editor/FirestoreDependencies.xml:20, Assets/Firebase/Editor/RemoteConfigDependencies.xml:20
        }
        maven {
            url "https://maven.google.com/" // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7, Assets/GoogleMobileAds/Editor/GoogleUmpDependencies.xml:7, Assets/GoogleMobileAdsNative/Editor/GoogleMobileAdsNativeDependencies.xml:7
        }
        maven {
            url "https://repo.maven.apache.org/maven2/" // Assets/GoogleMobileAds/Mediation/AdColony/Editor/AdColonyMediationDependencies.xml:24, Assets/GoogleMobileAds/Mediation/AppLovin/Editor/AppLovinMediationDependencies.xml:24, Assets/GoogleMobileAds/Mediation/UnityAds/Editor/UnityMediationDependencies.xml:25, Assets/GoogleMobileAds/Mediation/UnityAds/Editor/UnityMediationDependencies.xml:33
        }
        maven {
            url "https://android-sdk.is.com/" // Assets/GoogleMobileAds/Mediation/IronSource/Editor/IronSourceMediationDependencies.xml:24
        }
        maven {
            url "https://sdk.tapjoy.com/" // Assets/GoogleMobileAds/Mediation/Tapjoy/Editor/TapjoyMediationDependencies.xml:24
        }
        maven {
            url (unityProjectPath + "/Assets/GoogleSignIn/Editor/m2repository") // Assets/GoogleSignIn/Editor/GoogleSignInSupportDependencies.xml:9
        }
        maven {
            url "https://dl.google.com/dl/android/maven2/" // Assets/GoogleMobileAds/Mediation/AdColony/Editor/AdColonyMediationDependencies.xml:24, Assets/GoogleMobileAds/Mediation/AppLovin/Editor/AppLovinMediationDependencies.xml:24, Assets/GoogleMobileAds/Mediation/IronSource/Editor/IronSourceMediationDependencies.xml:24, Assets/GoogleMobileAds/Mediation/Tapjoy/Editor/TapjoyMediationDependencies.xml:24, Assets/GoogleMobileAds/Mediation/UnityAds/Editor/UnityMediationDependencies.xml:25
        }
        mavenLocal()
        mavenCentral()
    }
}
dependencies {
    implementation 'com.google.ads.mediation:adcolony:4.8.0.2' // Assets/GoogleMobileAds/Mediation/AdColony/Editor/AdColonyMediationDependencies.xml:24
    implementation 'com.google.ads.mediation:applovin:11.11.3.0' // Assets/GoogleMobileAds/Mediation/AppLovin/Editor/AppLovinMediationDependencies.xml:24
    implementation 'com.google.ads.mediation:ironsource:7.3.1.0' // Assets/GoogleMobileAds/Mediation/IronSource/Editor/IronSourceMediationDependencies.xml:24
    implementation 'com.google.ads.mediation:tapjoy:13.1.2.0' // Assets/GoogleMobileAds/Mediation/Tapjoy/Editor/TapjoyMediationDependencies.xml:24
    implementation 'com.google.ads.mediation:unity:4.8.0.0' // Assets/GoogleMobileAds/Mediation/UnityAds/Editor/UnityMediationDependencies.xml:25
    implementation 'com.google.android.gms:play-services-ads:22.3.0' // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
    implementation 'com.google.android.gms:play-services-auth:16+' // Assets/GoogleSignIn/Editor/GoogleSignInDependencies.xml:10
    implementation 'com.google.android.gms:play-services-base:18.2.0' // Assets/Firebase/Editor/AppDependencies.xml:17
    implementation 'com.google.android.ump:user-messaging-platform:2.1.0' // Assets/GoogleMobileAds/Editor/GoogleUmpDependencies.xml:7
    implementation 'com.google.code.gson:gson:2.8.5' // Assets/GoogleMobileAdsNative/Editor/GoogleMobileAdsNativeDependencies.xml:7
    implementation 'com.google.firebase:firebase-analytics:21.3.0' // Assets/Firebase/Editor/RemoteConfigDependencies.xml:15
    implementation 'com.google.firebase:firebase-analytics-unity:11.5.0' // Assets/Firebase/Editor/AnalyticsDependencies.xml:18
    implementation 'com.google.firebase:firebase-app-unity:11.5.0' // Assets/Firebase/Editor/AppDependencies.xml:22
    implementation 'com.google.firebase:firebase-auth:22.1.2' // Assets/Firebase/Editor/AuthDependencies.xml:13
    implementation 'com.google.firebase:firebase-auth-unity:11.5.0' // Assets/Firebase/Editor/AuthDependencies.xml:20
    implementation 'com.google.firebase:firebase-common:20.3.3' // Assets/Firebase/Editor/AppDependencies.xml:13
    implementation 'com.google.firebase:firebase-config:21.4.1' // Assets/Firebase/Editor/RemoteConfigDependencies.xml:13
    implementation 'com.google.firebase:firebase-config-unity:11.5.0' // Assets/Firebase/Editor/RemoteConfigDependencies.xml:20
    implementation 'com.google.firebase:firebase-crashlytics-ndk:18.4.3' // Assets/Firebase/Editor/CrashlyticsDependencies.xml:13
    implementation 'com.google.firebase:firebase-crashlytics-unity:11.5.0' // Assets/Firebase/Editor/CrashlyticsDependencies.xml:20
    implementation 'com.google.firebase:firebase-firestore:24.8.1' // Assets/Firebase/Editor/FirestoreDependencies.xml:13
    implementation 'com.google.firebase:firebase-firestore-unity:11.5.0' // Assets/Firebase/Editor/FirestoreDependencies.xml:20
    implementation 'com.google.signin:google-signin-support:1.0.4' // Assets/GoogleSignIn/Editor/GoogleSignInSupportDependencies.xml:9
    implementation 'com.unity3d.ads:unity-ads:4.8.0' // Assets/GoogleMobileAds/Mediation/UnityAds/Editor/UnityMediationDependencies.xml:33
}
android {
  packagingOptions {
      exclude ('/lib/armeabi/*' + '*')
      exclude ('/lib/mips/*' + '*')
      exclude ('/lib/mips64/*' + '*')
      exclude ('/lib/x86/*' + '*')
      exclude ('/lib/x86_64/*' + '*')
  }
}
UnityEngine.Debug:Log (object)
Google.Logger:Log (string,Google.LogLevel) (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:124)
GooglePlayServices.PlayServicesResolver:Log (string,Google.LogLevel) (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:1076)
GooglePlayServices.PlayServicesResolver:MenuDisplayLibraries () (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2320)

**Comment by ToanTruongAnh10** [comment]
Updated: 
I tried to update Firebase lib to the newest and seems the problem is fixed.
