### ISSUE TITLE
iOS Test Device Identifiers Changing with every install

### ISSUE THREAD

**Issue by rmgalante** [googleads/googleads-mobile-unity#2940]
### Step 0: Are you in the right place?

I tried this first.
    https://groups.google.com/g/google-admob-ads-sdk/c/U49xMrRt37o

### [REQUIRED] Step 1: Describe your environment

  * Unity version: **2022.3.5f1**
  * Google Mobile Ads Unity plugin version: **8.5.2**
  * Platform: **iOS** (iOS, Android, Unity Editor)
  * Platform OS version: **iPadOS 16.6.1 and iOS 16.6.1** (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: **iPad Air 5th Generation and iPhone 13**
  * Mediation ad networks used, and their versions: none

### [REQUIRED] Step 2: Describe the problem

I integrated the Google Mobile Ads Unity Plugin v 8.5.2 into my Unity app on my Mac. In my AdMob account, I set the AdMob Privacy and messaging section with a GDPR message and an IDFA explainer.

I'm testing the ConsentDebugSettings in my Android devices and my iOS devices. I want to make sure the consent form appears. So I created a ConsentDebugSettings object with DebugGeography set to DebugGeography.EEA. I am passing the test device identifiers that appear in my iOS console and Android logcat console.

The Android devices return the same test device identifiers every time I build and install the app to test.

The iOS devices return a different test device identifier in the UMP SDK packet every time I build and install the app to test. It looks like a GUID, not a hashed value. For example, I'm getting UMP SDK test identifier values like FB8FFEB5-9595-44EE-BF54-08DF3AB368AF. That doesn't look like the hashed value I get from my Android devices. Nor does it looks like the test device identifier I get from the Google Mobile Ads console message, "To get test ads on this device, set test identifiers to [some hashed value]."

All of my devices are configured as test devices. And they have been used in another app that I have published. This is the first time I'm trying the EEA consent and IDFA explainer logic with the UMP.

Is this a bug in the UMP API for iOS?

On my iOS devices, I see the IDFA explainer every time I uninstall and reinstall the app. I do not see the consent form.

On the Android devices, I see the consent form. Of course, I do not see the IDFA explainer.

I am unable to test the consent form on iOS due to this issue. Any help would be appreciated.

#### Steps to reproduce:

What happened? How can we make the problem occur?

I have a simple Unity app, which uses my bundle identifier and my dev provisioning profile. It uses my app's AdMob AppID. You would have to change these to test it. I can send the code but you should be able to reproduce this in your own test environment.

This could be a description, log/console output, etc.

From my iPad Air device I see this console message, "<UMP SDK> To enable debug mode for this device, set: UMPDebugSettings.testDeviceIdentifiers = @[ @"3534D356-EF9F-4325-811E-AF18C5D6C352" ];".

From my iPhone device I see this message, "<UMP SDK> To enable debug mode for this device, set: UMPDebugSettings.testDeviceIdentifiers = @[ @"FB8FFEB5-9595-44EE-BF54-08DF3AB368AF" ];".

These change every time I reinstall the app.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem

var debugSettings = new ConsentDebugSettings
{
    DebugGeography = DebugGeography.EEA,
    TestDeviceHashedIds = new List<string> { "myAndroidIdsWork", "myIOSIdsKeepChanging" } 
};
ConsentRequestParameters request = new ConsentRequestParameters
{
    TagForUnderAgeOfConsent = false,
}
request.ConsentDebugSettings = debugSettings;
ConsentInformation.Update(request, OnConsentInfoUpdated);

```
This works in my Android devices. It doesn't work in my iOS devices.

**Comment by NVentimiglia** [comment]
Hi @rmgalante 

While I look into this issue, as a work around can you use the [TestDeviceSimulatpr](https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/GoogleMobileAds/Api/Core/AdRequest.cs#L40) constant as a TestDeviceHashedId ?

**Comment by rmgalante** [comment]
Hello,

Thank you for your assistance.

I put the strings, “TestDeviceSimulator” and “SIMULATOR”, in the list of test device ids.

It made no difference.

I see the IDFA explainer. I do not see the consent form.

Rob

**Comment by NVentimiglia** [comment]
@rmgalante 

Hi, are you also configuring the RequestConfiguraiton with the `TestDeviceSimulator` consent ?

**Comment by rmgalante** [comment]
Hello,

I've attached a script that I used in a test project to generate the issue. It has the name, StartUI.cs, and is embedded in a zip file.

I tested it this time on a simulator. It shows the IDFA explainer, but not the EU consent form. I tested it on my devices as well.

I attached a console log as well. That is in a DOCX file. You will see on page 2 the following log entries.

StartUI.CheckGDPRConsentStatus called with debug settings
StartUI:CheckGDPRConsentStatus()

Regards.

[Console.docx](https://github.com/googleads/googleads-mobile-unity/files/12748162/Console.docx)
[StartUI.zip](https://github.com/googleads/googleads-mobile-unity/files/12748166/StartUI.zip)

**Comment by NVentimiglia** [comment]
@rmgalante 

Can you try calling `MobileAds/SetRequestConfiguration` first.

```
 // Configure your RequestConfiguration with Child Directed Treatment
            // and the Test Device Ids.
            MobileAds.SetRequestConfiguration(new RequestConfiguration
            {
                TestDeviceIds = TestDeviceIds
            });
```

If that fails I will need a network trace to identify the issue. If it comes to that, the [Google Help Group](https://groups.google.com/g/google-admob-ads-sdk) would be a better channel to submit this request.

**Comment by Yuyuyang** [comment]
I meet the same problem as you. The test id in the Xcode log changes after I re-install my test app and the consent form  doesn't show.

**Comment by rmgalante** [comment]
They never did anything to fix the problem. They kept asking me to change my code to try different things. After a couple of attempts to help them debug the problem, I gave up.

I stopped because it was costing me time, and getting me nowhere.

Eventually, I submitted my application to the App Store. It works, and the ads are served.

But I was never able to test the EU logic with their API.

Regards.

**Comment by mhctseu** [comment]
Same issue here. My workaround is just update the installation and not uninstall & install.

**Comment by sperochon** [comment]
Same here but on Flutter (maybe that will help someone here too...)

I resolved it by retrieving the iOS **identifierVendor** value dynamically (using device_info_plus package)
to be able to test UMP SDK IDFA message displaying prior to ATT popup.

```
final deviceInfo = DeviceInfoPlugin();
final iosInfo = await deviceInfo.iosInfo;
final identifierForVendor = iosInfo.identifierForVendor;

final params = ConsentRequestParameters(
  consentDebugSettings: ConsentDebugSettings(
    debugGeography: DebugGeography.debugGeographyNotEea,
    testIdentifiers: [identifierForVendor ?? ""],
  ),
);
ConsentInformation.instance.requestConsentInfoUpdate(
    params,
   ...
```

**Comment by AbnerYangBB** [comment]
use `UIDevice.current.identifierForVendor?.uuidString` instead of get it from console.

**Comment by MADahab** [comment]
For Unity do this:


```
using System.Security.Cryptography;
using System.Text;

public static class MD5Utility
{
    public static string ToMd5(string input)
    {
        using var md5 = MD5.Create();
        byte[] inputBytes = Encoding.UTF8.GetBytes(input);
        byte[] hashBytes = md5.ComputeHash(inputBytes);

        StringBuilder sb = new();
        foreach (byte b in hashBytes)
        {
            sb.Append(b.ToString("x2"));
        }
        return sb.ToString();
    }
}
```

In your Ad Mob initialize file :

```
using UnityEngine.iOS;

private void InitializeAdMob()
    {
        var config = new RequestConfiguration()
        {
            TestDeviceIds = new List<string>
            {
                MD5Utility.ToMd5(Device.vendorIdentifier)
            },
        };

        MobileAds.SetRequestConfiguration(config);
        MobileAds.Initialize(initStatus =>
        {
            Debug.Log("AdMob initialized successfully.");

        });
    }
```

**Comment by MADahab** [comment]
For unity do this:

```
using System.Security.Cryptography;
using System.Text;

public static class MD5Utility
{
    public static string ToMd5(string input)
    {
        using var md5 = MD5.Create();
        byte[] inputBytes = Encoding.UTF8.GetBytes(input);
        byte[] hashBytes = md5.ComputeHash(inputBytes);

        StringBuilder sb = new();
        foreach (byte b in hashBytes)
        {
            sb.Append(b.ToString("x2"));
        }
        return sb.ToString();
    }
}
```

In ur Admob file:

```
using UnityEngine.iOS;

void RequestGDPRConsent()
    {
        ConsentRequestParameters parameters = new()
        {
            TagForUnderAgeOfConsent = false,
            ConsentDebugSettings = new ConsentDebugSettings
            {
                DebugGeography = DebugGeography.EEA,
                TestDeviceHashedIds = new List<string> { Device.vendorIdentifier },
            }
        };

        ConsentInformation.Update(parameters, OnConsentInfoUpdated);
    }


void OnConsentInfoUpdated(FormError consentError)
    {
       // is the consent logic
    }

private void InitializeAdMob()
    {
        var config = new RequestConfiguration()
        {
            TestDeviceIds = new List<string>
            {
            MD5Utility.ToMd5(Device.advertisingIdentifier),
            MD5Utility.ToMd5(Device.vendorIdentifier)
            },
        };

        MobileAds.SetRequestConfiguration(config);
        MobileAds.Initialize(initStatus =>
        {
            Debug.Log("AdMob initialized successfully.");

        });
    }

```

**Comment by carljohansen** [comment]
In my case it was my own dumb mistake.  I have two "apps" in AdMob, being the Android and iOS flavours of my app.  I had created a consent form for the Android flavour but not the iOS flavour.
