### ISSUE TITLE
AppStateEventNotifier.AppStateChanged not calling while app goes in background or foreground in android device v 8.5.2

### ISSUE THREAD

**Issue by vikaspatel-unity** [googleads/googleads-mobile-unity#2944]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.32f
  * Google Mobile Ads Unity plugin version: 8.5.2
  * Platform: Android
  * Platform OS version: Android 13

#### Steps to reproduce:

run in android device AppStateEventNotifier.AppStateChanged  callback will not called so any operation on that callback such as showing openad will not work.

**Comment by dev23012301** [comment]
i also tested it in Unity Admob 8.4.1 and 8.5.2 ,AppStateEventNotifier.AppStateChanged not calling

**Comment by NVentimiglia** [comment]
Update `GoogleMobileAdsDependencies.xml` with the following 

```
    <androidPackage spec="androidx.lifecycle:lifecycle-common-java8:2.4.1">
      <repositories>
        <repository>https://maven.google.com/</repository>
      </repositories>
    </androidPackage>
    <androidPackage spec="androidx.lifecycle:lifecycle-process:2.4.1">
      <repositories>
        <repository>https://maven.google.com/</repository>
      </repositories>
    </androidPackage>
```

**Comment by vikaspatel-unity** [comment]
@NVentimiglia  updated GoogleMobileAdsDependencies.xml and its work. Also requested for PR.

**Comment by NVentimiglia** [comment]
@vikaspatel-unity 

Agreed. I am closing this issue as fixed but will push for the Feature Request.

**Comment by vikaspatel-unity** [comment]
@NVentimiglia  PR cant be merged directly ?
