### ISSUE TITLE
App closes immediately after opening

### ISSUE THREAD

**Issue by Kumici13** [googleads/googleads-mobile-unity#2949]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.19f1
  * Google Mobile Ads Unity plugin version: 8.5.2
  * Platform: iOS (iOS, Android, Unity Editor)
  * Platform OS version: 16.5.1 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: Any iOS device
  * Mediation ad networks used, and their versions: /

### [REQUIRED] Step 2: Describe the problem

As title says app closes immediately after opening. Everything works in editor and on android, but iOS builds have this problem.
We were using unity mediation and switched to adMob if that helps. We use testflight to test our builds.

**Comment by NVentimiglia** [comment]
@Kumici13 

Do you have a stack trace or debug log from this experience?

**Comment by Kumici13** [comment]
I have this log, but I can provide you anything if you give me instructions how to log it. 
[Log.txt](https://github.com/googleads/googleads-mobile-unity/files/12738835/Log.txt)

**Comment by Kumici13** [comment]
Fixed it, some kind of conflict with Facebook sdk, deleted it, now everything works.
