### ISSUE TITLE
Internal error on Android OS 12 when running reward ads in Unity

### ISSUE THREAD

**Issue by k0uhe1D** [googleads/googleads-mobile-unity#2950]
## Details

When I implement AdoMod in Unity as documented and run Rewarded ads, I get an Internal error on some Android devices.

Do you have a solution or information about this issue?

- GoogleAdmob: Initialize Success is confirmed.
- I have confirmed that it works on Android 13 pixel7Pro
- Internal error occurs on Android OS 12 / amsung SM-G991U1

## env
Unity 2021.3.7f1
TargetAPI Level 33
minimum API Level 24
Google Mobile Ads Unity Plugin v8.5.2

## err code

```
  [Error] [AdMob]Rewarded ad A failed to load an ad with error : {
  "Code": 0,
  "Message": "Internal error.",
  "Domain": "com.google.android.gms.ads",
  "Cause": "null",
  "Response Info": {
    "Response ID": "****",
    "Mediation Adapter Class Name": "",
    "Adapter Responses": [
      {
        "Adapter": "com.google.ads.mediation.admob.AdMobAdapter",
        "Latency": 60001,
        "Ad Source Name": "AdMob Network",
        "Ad Source ID": "****",
        "Ad Source Instance Name": "AdMob (default)",
        "Ad Source Instance ID": "",
        "Credentials": {
          "pubid": "ca-app-pub-51664******"
        },
        "Ad Error": {
          "Code": 0,
          "Message": "Internal error.",
          "Domain": "com.google.android.gms.ads",
          "Cause": "null"
        }
      }
    ],
    "Response Extras": {
      "mediation_group_name": "AdMob (default)"
    }
  }
}
```

**Comment by NVentimiglia** [comment]
Thank you,

I will forward these details to the engineering team. Closing this issue, feel free to reopen if you have additional details.

b/302192711
