### ISSUE TITLE
AdColony 2.6.2 MediationExtras errors

### ISSUE THREAD

**Issue by dcosmin-97** [googleads/googleads-mobile-unity#2960]
[REQUIRED] Step 1: Describe your environment

    Unity version: 2021.3.30f1
    Google Mobile Ads Unity plugin version: 8.5.2
    Platform: Unity Editor
    Mediation ad networks used, and their versions: Applovin 6.9.1, Liftoff 4.0.0, Meta 3.11.0, Mintegral 1.2.1, Pangle 2.3.0

Using this setup, if you import AdColony 2.6.2 into the project, a lot of MediationExtras errors will appear.

**Comment by NVentimiglia** [comment]
Thank you,

I see this issue and will get this issue looked at.

**Comment by NVentimiglia** [comment]
@dcosmin-97 We have confirmed this is an issue, and are looking into releasing a fix.

**Comment by dcosmin-97** [comment]
@NVentimiglia Hi! I think that AdColony will be closed until the fix will be released. DTExchange is going to cover adcolony, but there is an issue with DTExchange at the moment as specified in #2997 .I will probably will open a new bug.

**Comment by NVentimiglia** [comment]
@dcosmin-97 Thank you
