### ISSUE TITLE
Rewarded ads mute the game's sound on Android devices

### ISSUE THREAD

**Issue by tomurtogu** [googleads/googleads-mobile-unity#2969]
* Unity version: 2020.3.33f1
  * Google Mobile Ads Unity plugin version: 8.5.2
  * Platform: Android
  * Platform OS version:  All 
  * Any specific devices issue occurs on: Samsung Galaxy Tab A, Samsung Galaxy A13 5G, Samsung Galaxy A03, Lenovo Tab M10 etc..
  * Mediation ad networks used, and their versions: Applovin 6.9.1 , Meta Audience 3.11.0

Problem: The game's sound mutes after watching rewarded ads.

#### Steps to reproduce:

There is an issue reported by many players that I haven't observed in test ads. They say that after watching rewarded ads and returning to the game, there is no sound in the game anymore, but it gets fixed when they restart the game. Since I can't watch real ads, I can't determine which network is causing the issue. Let me reiterate that there is no issue with test ads. I initially thought it might be a temporary issue related to the creatives, but it's been a while, and I've received numerous error reports about this problem.

```

**Comment by NVentimiglia** [comment]
@tomurtogu 

To follow up on this issue I will need a reliable way to replicate this issue. Can you provide steps? Being that this is ad specific, we may need a creative Id (collected from Charles log) to replicate this.
