### ISSUE TITLE
(UMP) ConsentInformation.Update(request, OnConsentInfoUpdated) isnt working correctly if you call it a second time.

### ISSUE THREAD

**Issue by LambdaStudiosPH** [googleads/googleads-mobile-unity#2974]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.1.38f1
  * Google Mobile Ads Unity plugin version: v8.5.2
  * Platform:Android
  * Platform OS version: non-specific
  * Any specific devices issue occurs on: Poco F5
  * Mediation ad networks used, and their versions: None

#### Steps to reproduce:

Context: im trying to show an age gate. asking users for their age ONLY IF consentStatus is Required then setting the value of  request.TagForUnderAgeOfConsent  to true/false depending on the input from the age screen.

Expected result: if is TagForUnderAgeOfConsent is set to true on the second  ConsentInformation.Update the UMP Consent form should not be allowed to be displayed to user.

Actual result: Its still showing the consent form even if up call  ConsentInformation.Update a second time with an updated request parameters like TagForUnderAgeOfConsent = true

NOTE: THIS ONLY HAPPENS WHEN TESTED ON REAL DEVICE. IT WORKS FINE IN UNITY EDITOR. THE CONSENT FORM DOESNT SHOW IF AGE IS BELOW AGE ON THE EDITOR

I tried hardcoding a new request parameter with TagForUnderAgeOfConsent = true on the second ConsentInformation.Update call but the consent is still appearing.

I tried debug log the request.TagForUnderAgeOfConsent  before calling the second ConsentInformation.Update() and can confirm that TagForUnderAgeOfConsent   is true but the consent still shows afterwards

#### Relevant Code:

public class GDPRConsentManager : MonoBehaviour
{
    private ConsentRequestParameters request;

    // Start is called before the first frame update
    void Start()
    {
        var debugSettings = new ConsentDebugSettings
        {
            // Geography appears as in EEA for debug devices.
            DebugGeography = DebugGeography.EEA,
            TestDeviceHashedIds = new List<string>
        {}};

        // Set tag for under age of consent.
        // Here false means users are not under age of consent.
        request = new ConsentRequestParameters
        {
            TagForUnderAgeOfConsent = false,
            ConsentDebugSettings = debugSettings,
        };

        // Check the current consent information status.
        ConsentInformation.Update(request, OnConsentInfoUpdated);
    }
    void OnConsentInfoUpdated(FormError consentError)
    {
        if (consentError != null)
        {
            // Handle the error.
            UnityEngine.Debug.LogError(consentError);
            return;
        }

        if (ConsentInformation.ConsentStatus == ConsentStatus.Required)
        {
            ShowAgeScreen(ProceedWithConsent);
        }
        else
        {
            LoadAndShowConsentForm();
        }
    }

    private void ProceedWithConsent()
    {
        // This callback is called after the age screen is completed by the user
        ConsentInformation.Update(request, (updateError) => // ive debugged it request.TagForUnderAgeOfConsent  is true and even if i pass a new instantiated request with TagForUnderAgeOfConsent to true the consent form still appear when it shouldnt
        {
            if (updateError != null)
            {
                // Handle the error.
                UnityEngine.Debug.LogError(updateError);
                return;
            }
            LoadAndShowConsentForm();

            Debug.Log("TagForUnderAgeOfConsent: " + request.TagForUnderAgeOfConsent);
        });
    }

    void ShowAgeScreen(Action callback)
    {
        // Display the age screen
        UIManager.Instance.AgeScreenPanel.SetActive(true);

        Button confirmButton = UIManager.Instance.AgeScreenPanel.GetComponentInChildren<Button>();

        // Remove any previous listeners attached to the button
        confirmButton.onClick.RemoveAllListeners();

        confirmButton.onClick.AddListener(() =>
        {
            // Retrieve birth year from InputField and determine age
            var isUnderAgeOfConsent = (int)UIManager.Instance.AgeSlider.value < 16;
            request.TagForUnderAgeOfConsent = isUnderAgeOfConsent;

            // Hide the age screen
            UIManager.Instance.AgeScreenPanel.SetActive(false);

            // Call the provided callback
            callback.Invoke();
        });
    }

    private static void LoadAndShowConsentForm()
    {
        // If the error is null, the consent information state was updated.
        // You are now ready to check if a form is available.
        ConsentForm.LoadAndShowConsentFormIfRequired((FormError formError) =>
        {
            if (formError != null)
            {
                // Consent gathering failed.
                UnityEngine.Debug.LogError(formError);
                return;
            }

            // Consent has been gathered.
            if (ConsentInformation.CanRequestAds())
            {
                AdsManager.Instance.InitializeSDK();
            }
        });
    }
}

**Comment by NVentimiglia** [comment]
Hi @LambdaStudiosPH 

I have confirmed the issue and request this gets fixed. b/307621561

**Comment by ericleich** [comment]
Agree that if the last call to ConsentInformation.Update() indicates under age of consent, `ConsentForm.LoadAndShowConsentFormIfRequired()` shouldn't actually load/show a form. And this should still be investigated/fixed.

In the meantime, since you're explicitly putting in the age gate here, you could work around this for now by avoiding the call to `LoadAndShowConsentFormIfRequired()` if the user is under 16.
