### ISSUE TITLE
Android: GoogleMobileAds 8.5.2: ChartboostUnityAdapter-4.3.0 An error occurs in Android Studio.

### ISSUE THREAD

**Issue by crSudo** [googleads/googleads-mobile-unity#2977]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: Unity 2022.3.10f1
  * Google Mobile Ads Unity plugin version: GoogleMobileAds-v8.5.2
  * Platform: Android
  * Mediation ad networks used, and their versions: ChartboostUnityAdapter-4.3.0
  * Android Studio version: Android Studio 2022_3_1_20

### [REQUIRED] Step 2: Describe the problem
※I am Japanese. I am translating using Google Translate. Please let us know if you have any misunderstandings.

When you export from Unity and open it in Android Studio, the following warning is output.

    Failed to resolve: com.chartboost:chartboost-sdk:9.4.0
    <a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Affected Modules: <a href="openFile:D:/GMA_8_5_2_Unity2022/_bin/unityLibrary/build.gradle">unityLibrary</a>

Also, when you run [Build]-[Build Bundle(s) / APK(s)]-[Build APK(s)], the following error is output.

*This is not all. Since there are a lot of them, I will only post some of them.

    FAILURE: Build completed with 13 failures.

    1: Task failed with an exception.
    -----------
    * What went wrong:
    Execution failed for task ':launcher:checkDebugDuplicateClasses'.
    > Could not resolve all files for configuration ':launcher:debugRuntimeClasspath'.
       > Could not find com.chartboost:chartboost-sdk:9.4.0.
         Searched in the following locations:
           - https://dl.google.com/dl/android/maven2/com/chartboost/chartboost-sdk/9.4.0/chartboost-sdk-9.4.0.pom
           - https://repo.maven.apache.org/maven2/com/chartboost/chartboost-sdk/9.4.0/chartboost-sdk-9.4.0.pom
           - https://maven.google.com/com/chartboost/chartboost-sdk/9.4.0/chartboost-sdk-9.4.0.pom
           - file:/C:/Users/sudo/.m2/repository/com/chartboost/chartboost-sdk/9.4.0/chartboost-sdk-9.4.0.pom
           - file:/D:/ApplicationUnity_SDK/Google/_Ads/GoogleMobileAds/_Unity/GMA_8_5_2_Unity2022_wk/_bin/unityLibrary/libs/chartboost-sdk-9.4.0.jar
           - file:/D:/ApplicationUnity_SDK/Google/_Ads/GoogleMobileAds/_Unity/GMA_8_5_2_Unity2022_wk/_bin/unityLibrary/libs/chartboost-sdk.jar
         Required by:
             project :launcher > project :unityLibrary > com.google.ads.mediation:chartboost:9.4.0.0
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

#### Steps to reproduce:
I am setting it up while looking at the following site.
https://developers.google.com/admob/unity/quick-start
https://developers.google.com/admob/unity/mediation/chartboost

 1. Launch Unity Editor
 2. Import GoogleMobileAds-v8.5.2.unitypackage
 3. [File]-[Build Settings]: Change to Android and select [Switch Platform].
 4. [Enable Android Auto-resolution?]: Select [Enable].
 5. Select [Assets]-[External Dependency Manager]-[Android Resolver]-[Resolve].
 6. [Assets]-[Google Mobile Ads]-[Settings] Set the AdMob app ID.
 7. Import GoogleMobileAdsChartboostMediation.unitypackage
 8. Select [Assets]-[External Dependency Manager]-[Android Resolver]-[Force Resolve].
 9. [File]-[Build Settings]-[Player Settings]-[Publishing Settings]
    Check the boxes for the following

    -[Custom Main Gradle Template]
    -[Custom Gradle Properties Template]
10. [File]-[Build Settings] Check [Export Project].
11. Select [Assets]-[External Dependency Manager]-[Android Resolver]-[Force Resolve].
12. [Build Setting]-[Export]. 
    Select a new folder, create [_bin], and select [Select Folder].
13. Start Android Studio and open project.

Best Regards
crSudo

**Comment by NVentimiglia** [comment]
Hi @crSudo 

I was able to install the chartboost dependencies.. Here are my steps:

- Launch Unity Editor / Hello World project
- Confirm Android build target
- Import GoogleMobileAds-v8.5.2.unitypackage
- Import GoogleMobileAdsChartboostMediation.unitypackage
- Select [Assets]-[External Dependency Manager]-[Android Resolver]-[Resolve].
  -  This process took several attempts, but eventually passed.
- I did **NOT** use a Custom Main Gradle Template] or [Custom Gradle Properties Template]
- Build and deployed the gradle project.

Can you try again perhaps without the custom templates ?

![image](https://github.com/googleads/googleads-mobile-unity/assets/125889/7f53b4ea-9af5-4c33-bd3d-d79d6bed692a)

**Comment by crSudo** [comment]
Thank you for your reply.

When I removed [Custom Main Gradle Template] and [Custom Gradle Properties Template], I was able to create the APK correctly.
However, when using [Build]-[Generate Signed Bundle/APK] in Android Studio, the following error was output.

    /unityLibrary/build/.transforms/c0b55bcb1be3e381e2e5ca0107142380/transformed/out/jars/classes.jar!/META-INF/annotation.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
    /unityLibrary/build/.transforms/c0b55bcb1be3e381e2e5ca0107142380/transformed/out/jars/classes.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
    /unityLibrary/build/.transforms/c0b55bcb1be3e381e2e5ca0107142380/transformed/out/jars/classes.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.

I was able to resolve the issue by doing the following:

1. Check [File]-[Build Settings]-[Player Settings]-[Publishing Settings]-[Custom Base Gradle Template].
2. Open the output \Assets\Plugins\Android\baseProjectTemplate.gradle in a text editor and modify it as follows.
     id 'com.android.application' version '7.4.2' apply false
     id 'com.android.library' version '7.4.2' apply false
3. [Build Setting]-[Export]. 
4. Open \gradle\wrapper\gradle-wrapper.properties in the output folder with a text editor and modify it as follows.
     distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip
5. Open the project in Android Studio and run [Build]-[Generate Signed Bundle/APK].

However, when importing MetaAudienceNetworkUnityAdapter-3.11.0 into the above environment, the following error was output.
How should I deal with this?

    2 files found with path 'META-INF/kotlinx_coroutines_core.version'.
    Adding a packagingOptions block may help, please refer to
    https://developer.android.com/reference/tools/gradle-api/7.4/com/android/build/api/dsl/ResourcesPackagingOptions
    for more information

■ Regarding the report of our investigation results
When using ChartboostUnityAdapter-4.1.1, even custom templates could be built correctly and no errors were output.
It seems that things have gone wrong since ChartboostUnityAdapter-4.2.0.

Best Regards
crSudo

**Comment by NVentimiglia** [comment]
@crSudo 

In your launcher and grandle template can you try adding


```
android {...
    packagingOptions {      
        resources.excludes.add("META-INF/*") 
    }
}
```

**Comment by rusitschka** [comment]
The package name/location of Chartboost SDK seems to have changed:

- New: https://central.sonatype.com/artifact/com.cleveradssolutions/chartboost
- Old: https://mvnrepository.com/artifact/com.chartboost/chartboost-sdk

Last version at old location is 9.2.1 but recent AdMob mediation adapter requires 9.4.0.

**Comment by oshionniemela** [comment]
I'm getting the same issue with trying to update the Chartboost adapter (ChartboostUnityAdapter-4.5.0). It's not able to find `<androidPackage spec="com.google.ads.mediation:chartboost:9.6.0.0">` when building my project to Android. 

I then noticed that the last Chartboost version to be updated to https://repo.maven.apache.org/maven2/com/chartboost/chartboost-sdk/ was version 9.2.1 (back in March 2023). This seems to be where it would get the pom files. Any idea why chartboost-sdk pom files haven't been uploaded here since last March? When I look at other ad networks like UnityAds, AppLovin, etc they are still being updated here.

I can manually download it from https://maven.google.com/com/google/ads/mediation/chartboost/9.6.0.0/chartboost-9.6.0.0.pom, but I'm not sure how to change the ChartboostMediationDependencies.xml file to download it from there instead of the `https://repo.maven.apache.org/maven2/` location. I tried changing `<repository>https://repo.maven.apache.org/maven2/</repository>` to `<repository>https://maven.google.com/</repository>` (in the ChartboostMediationDependencies.xml) and that didn't work either.

So right now I am unable to use a newer version of Chartboost because of this issue. Still have to use `<androidPackage spec="com.google.ads.mediation:chartboost:9.2.1.1">`

**Comment by AlirezaTabasi7** [comment]
@oshionniemela I have exact problem as yours in my own project. Thank you for providing more info on the matter and if you ever found a way please let me know.

**Comment by oshionniemela** [comment]
@AlirezaTabasi7  I'm still waiting for a response from Google to respond here, so in the meantime I am still using the old version `<androidPackage spec="com.google.ads.mediation:chartboost:9.2.1.1">` for Android. Hopefully they'll see this and start correctly uploading the updated Chartboost packages again. @NVentimiglia

**Comment by shefich** [comment]
I have the same error upon build:
"> Could not find com.chartboost:chartboost-sdk:9.6.0.
     Required by:
         project :launcher > project :unityLibrary > com.google.ads.mediation:chartboost:9.6.0.0"
@NVentimiglia hope you can fix it.

**Comment by oshionniemela** [comment]
Alright, I figured out the issue. It looks like Chartboost hasn't been uploading their Chartboost SDK to `https://repo.maven.apache.org/maven2/` or `https://dl.google.com/dl/android/maven2/` since version 9.2.1.1 of last year for some reason, but they are instead uploading their SDK to jfrog.io. So to correctly download the Chartboost SDK you need to change the ChartboostMediationDependencies.xml android repository line to `<repository>https://cboost.jfrog.io/artifactory/chartboost-ads/</repository>` so my whole dependencies area looks like this now: ```<dependencies>
  <androidPackages>ss
    <androidPackage spec="com.google.ads.mediation:chartboost:9.6.0.0">
      <repositories>
        <repository>https://cboost.jfrog.io/artifactory/chartboost-ads/</repository>
      </repositories>
    </androidPackage>
  </androidPackages>

  <iosPods>
    <iosPod name="GoogleMobileAdsMediationChartboost" version="9.6.0.0"/>
  </iosPods>
</dependencies>```

**Comment by NVentimiglia** [comment]
Please try again with the latest release, things are now working for me.

@crSudo 

![image](https://github.com/googleads/googleads-mobile-unity/assets/125889/d52b03c9-de6a-4aaa-8221-11f57c266bce)

If you still have issues, reopen this issue and ping me.

**Comment by shefich** [comment]
@NVentimiglia the issue is the same:
`* What went wrong:
Execution failed for task ':launcher:mergeReleaseResources'.
> Could not resolve all files for configuration ':launcher:releaseRuntimeClasspath'.
   > Could not find com.chartboost:chartboost-sdk:9.6.0.
     Required by:
         project :launcher > project :unityLibrary > com.google.ads.mediation:chartboost:9.6.0.0`

9.2.1 isn't the latest release.

@oshionniemela your workaround works. Thank you.

**Comment by AlirezaTabasi7** [comment]
Hey @NVentimiglia 
I'm not able to create build anyway and I get the error below:

C:\Users\Alire\.gradle\caches\transforms-2\files-2.1\b6c9d730173911441158be404a49b93d\com.google.android.gms.play-services-ads-lite-22.6.0\AndroidManifest.xml:49:5-117: AAPT: error: unexpected element <property> found in <manifest><application>.

**Comment by crSudo** [comment]
@NVentimiglia 

Sorry for the late reply.
I was able to create an app by making the following settings.

Unity 2022.3.10f1
Android Studio 2022.3.1 Patch 2

GoogleMobileAds-v8.7.0
ChartboostUnityAdapter-4.5.0

■Unity
 1. Launch Unity Editor
 2. Create a new project.
 3. Import GoogleMobileAds-v8.7.0.unitypackage
 4. [File]-[Build Settings]: Change to Android and select [Switch Platform].
 5. [Enable Android Auto-resolution?]: Select [Enable].
 6. Select [Assets]-[External Dependency Manager]-[Android Resolver]-[Resolve].
 7. [Assets]-[Google Mobile Ads]-[Settings] Set the AdMob app ID.
 8. Import GoogleMobileAdsChartboostMediation.unitypackage
 9. Select [Assets]-[External Dependency Manager]-[Android Resolver]-[Force Resolve].
10. [File]-[Build Settings]-[Player Settings]-[Publishing Settings]
    **** If checked, an error will occur. ****
    -[Custom Main Gradle Template] : OFF
    -[Custom Gradle Properties Template] : OFF
11. [File]-[Build Settings]-[Player Settings]-[Other Settings]
    [Configuration]-[Scripting Backend] Changed to [IL2CPP]
    [Configuration]-[Target Architectures] Check [ARMv7], [ARM64]
12. [File]-[Build Settings] Check [Export Project].
13. Select [Assets]-[External Dependency Manager]-[Android Resolver]-[Force Resolve].
14. [Build Setting]-[Export]. 
    Select a new folder, create [_bin], and select [Select Folder].

■Android Studio
 1. Start Android Studio and open project.
 2. Open build.gradle(Module.launcher), add [resources.excludes.add("META-INF/*")], and click Sync Now.
 3. Open gradle.properties. add [android.suppressUnsupportedCompileSdk=33], and click Sync Now.
 4. Run [Build]-[Generate Signed Bundle/APK] to create an apk.

However, the reason why mainTemplate.gradle cannot be output is inconvenient because the following settings must also be performed, so I would like you to fix it so that it will work even if it is output.
・classpath 'com.android.support:multidex:1.0.3'
・multiDexEnabled true

Best Regards
crSudo

**Comment by crSudo** [comment]
@NVentimiglia 
I looked into the differences between aar between Android Studio and Unity.

◇AndroidStudio
If you add the url 'https://cboost.jfrog.io/artifactory/chartboost-ads/'

[Project]-[External Libraries]
Gradle: com.chartboost:chartboost-sdk:9.6.0@aar
Gradle: com.google.ads.mediation:chartboost:9.6.0.0@aar

◇Unity
[File]-[Build Settings]-[Player Settings]-[Publishing Settings]
-[Custom Main Gradle Template] : OFF
-[Custom Gradle Properties Template] : OFF
[Assets]-[External Dependency Manager]-[Android Resolver]-[Force Resolve]

\Assets\Plugins\Android内
com.chartboost.chartboost-sdk-9.2.1.aar
com.google.ads.mediation.chartboost-9.6.0.0.aar

■I checked each Admob site.
https://developers.google.com/admob/unity/mediation/chartboost#version-4.5.0 ： [Supports Chartboost Android adapter version 9.6.0.0.]
is linked to the URL below.
https://github.com/googleads/googleads-mobile-android-mediation/blob/main/ThirdPartyAdapters/chartboost/CHANGELOG.md#version-9600
If you look at this site, Chartboost SDK version 9.6.0.

I think it is correct to use Chartboost SDK 9.6.0, what do you think?

Best Regards
crSudo

**Comment by AlirezaTabasi7** [comment]
I had same problems and fixed it by steps below:

Unity version is 2021.3.26f1
GoogleMobileAds 8.7
Chartboost mediation 9.6.0.
Min Api android 22 (5.1)
Target API 34

Follow google document linked below like this:
https://developers.google.com/admob/unity/gradle

1- download gradle version 6.7.1 binary file here:
https://gradle.org/next-steps/?version=6.7.1&format=bin

2- Extract it anywhere and make unity use this one instead of default gradle installed with the editor.

3- In android player settings check custom "base" gradle template and not "main" gradle temple nor custom gradle properties.

4- Open the Assets/Plugins/Android/baseProjectTemplate.gradle file and set the dependencies to use Gradle build tools 4.2.0.
buildscript { dependencies { classpath 'com.android.tools.build:gradle:4.2.0' **BUILD_SCRIPT_DEPS** } } 
5- Force resolve your project using External dependency manager 1.2.177 and it should resolve successfully.

6- Make sure to check Use R8 in minify code section if needed and to not check release which causes other errors.

7- lastly from build menu press clean build which is under build button itself.

Also Thanks @oshionniemela for Chartboost dependecy workaround which worked like a charm.

Hope this helps.
