### ISSUE TITLE
Is any additional config required to link to Firebase?

### ISSUE THREAD

**Issue by jahester** [googleads/googleads-mobile-unity#298]
The AdMob Firebase documentation isn't specific to the Unity plugin, so I'm unsure of the integration steps.  If I click the "Link to Firebase" button in the AdMob console, is any additional configuration required within this plugin or is an additional SDK required?

**Comment by rampara** [comment]
Integration instructions and examples with Firebase can be found [here](https://github.com/firebase/quickstart-unity).
