### ISSUE TITLE
sdk not init when running on SDK version 8.5.2 with Xcode 15, 2022.3.11 LTS

### ISSUE THREAD

**Issue by phuongdmp7** [googleads/googleads-mobile-unity#2983]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.11 LTS
  * Google Mobile Ads Unity plugin version: 8.5.2
  * Xcode 15, mac os sonoma 14
  * devices test Platform: iOS 17

#### Relevant Code:

```
MobileAds.RaiseAdEventsOnUnityMainThread = true;
            this.logService.Log("ggads start init");
            MobileAds.Initialize(_ =>
            {
                this.logService.Log("ggads finished init");
                this.LoadAppOpenAd();
                this.IntervalCall(5);
            });
```

#### Steps to reproduce:

Everything ok before apple release new xcode, and ios. 
Now when i run above code just only receive log "ggads start init" and not see "ggads finished init"

**Comment by tuha263** [comment]
I got the same issue, please helppp!!!!

**Comment by DuyMaiBui** [comment]
Same

**Comment by Banhbaochien98** [comment]
Me too :(((

**Comment by superbderrick** [comment]
How do I fix this?:
