### ISSUE TITLE
Adaptive Banner cause severe performance issue when it's an animated banner

### ISSUE THREAD

**Issue by jacattrongnlh** [googleads/googleads-mobile-unity#2988]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.14
  * Google Mobile Ads Unity plugin version: 8.5.2
  * Platform: Android
  * Platform OS version: Android 11
  * Any specific devices issue occurs on: Redmi 9T
  * Mediation ad networks used, and their versions: admob only

#### Steps to reproduce:

Reproduce project:
https://github.com/jacattrongnlh/AdmobAdaptiveBanner

Steps:
- Build the APK from the repo. (or download the build from Releases tab)
- Run it on a device.
- Wait a few seconds for Admob initialization.
- Tap on the button "Adaptive Banner" to load an adaptive banner.
- Drag and hold the Scroll View (as in keep your finger down and drag it, do not lift the finger up when scrolling).
- Tap on the button "Default Banner" to load the default size banner.
- Drag and hold the Scroll View.

Comparing the framerate of the Scroll View before and after loading the adaptive banner, you can see that the Scroll View was smooth and responsive before the banner was shown. After the banner is shown, the Scroll View becomes very laggy when you drag it.

The framerate of the game is unaffected, it's the rate of UI's responsiveness that is affected.

Attaching Android Studio to profile the performance, you can see the CPU usage is significantly high when the animated Adaptive banner is displayed. When a static default banner is displayed, the CPU usage is not as high.

Profiler Screenshot: https://drive.google.com/file/d/1PMpr7BfkEkYLCFPDUJGb1MixbHUlKFqB/view?usp=sharing

Video recorded showing the problem: https://drive.google.com/file/d/1KX3ht2Exx9SYfDN7ZUpx6cf0zXaX986Q/view?usp=drive_link

**Comment by Ceikry** [comment]
Apologies, we've discovered the root cause and it's not directly related to googleads-mobile-unity.

**Comment by NVentimiglia** [comment]
Hi @jacattrongnlh 

This is a complex issue which is best sent over to the [Google Support Group](https://groups.google.com/g/google-admob-ads-sdk). The team there has the resources to triage this issue and get it in the hands of the right team.
