### ISSUE TITLE
AdMob and Google Analytics packages conflict

### ISSUE THREAD

**Issue by andrew-grischenko** [googleads/googleads-mobile-unity#299]
The problem: **Google Analytics and AdMob Unity packages, both from Google, are not compatible**
Unity 5.3, SDK 24
@rampara 
Steps:
1. Create new empty Unity project 
2. Install the AdMob plugin
3. Install [Google Analytics plugin](https://raw.githubusercoantent.com/googleanalytics/google-analytics-plugin-for-unity/master/GoogleAnalyticsV4.unitypackage)
4. Try to run project in Editor - get the error "Assets/PlayServicesResolver/Editor/GADependencies.cs(8,19): error CS0433: The imported type `Google.JarResolver.PlayServicesSupport' is defined multiple times"

Attempts to resolve the issue leads to issues further in building the package for Android with duplicated classes etc.

**Comment by rampara** [comment]
The Google Analytics plugin needs to be updated to pull in the latest version of [Play Services Resolver](https://github.com/googlesamples/unity-jar-resolver). As a workaround, you can import the analytics plugin first, delete the content in the `Assets/PlayServicesResolver/` directory and then import the AdMob plugin.

You will need to manually add Analytics as a Play services dependency via the code below:

`Google.VersionHandler.InvokeInstanceMethod(
            svcSupport, "DependOn",
            new object[] { "com.google.android.gms", "play-services-analytics",
                           "LATEST" },
            namedArgs: new Dictionary<string, object>() {
                {"packageIds", new string[] {
                        "extra-google-m2repository",
                        "extra-android-m2repository"} }
            });`

This code can be added to the [AdMobDependencies.cs](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Editor/AdMobDependencies.cs) file or to a new file that declares Play services dependencies.

**Comment by andrew-grischenko** [comment]
I followed your steps, it runs in Editor, but fails to package Android resources with error "Unable to convert classes into dex format" and the dump below


Error building Player: CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/Andrew/Library/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/ainternal/zzlu;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzlv;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzlw;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzlx;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzly;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzlz;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzma;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzmb;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzmc;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:613)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:2a77)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at SDKMain.main(SDKMain.java:129)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:605)
	... 9 more
]
stdout[
processing archive /Users/Andrew/Projects/AdMob-VS-GA/Temp/StagingArea/android-libraries/GoogleMobileAdsPlugin/libs/./unity-plugin-library.jar...
processing com/google/unity/BuildConfig.class...
processing com/google/unity/ads/Banner.class...
processing com/google/unity/ads/Banner$1.class...
processing com/google/unity/ads/Banner$1$1.class...
processing com/google/unity/ads/Banner$2.class...
processing com/google/unity/ads/Banner$3.class...
processing com/google/unity/ads/Banner$4.class...
processing com/google/unity/ads/Banner$5.class...
processing com/google/unity/ads/CustomNativeAd.class...
processing com/google/unity/ads/CustomNativeAd$1.class...
processing com/google/unity/ads/CustomNativeAd$2.class...
processing com/google/unity/ads/Interstitial.class...
processing com/google/unity/ads/Interstitial$1.class...
processing com/google/unity/ads/Interstitial$1$1.class...
processing com/google/unity/ads/Interstitial$2.class...
processing com/google/unity/ads/Interstitial$3.class...
processing com/google/unity/ads/Interstitial$4.class...
processing com/google/unity/ads/Interstitial$5.class...
processing com/google/unity/ads/NativeAdLoader.class...
processing com/google/unity/ads/NativeAdLoader$1.class...
processing com/google/unity/ads/NativeAdLoader$2.class...
processing com/google/unity/ads/NativeAdLoader$3.class...
processing com/google/unity/ads/NativeAdLoader$3$1.class...
processing com/google/unity/ads/NativeAdLoader$3$2.class...
processing com/google/unity/ads/NativeAdLoader$3$3.class...
processing com/google/unity/ads/NativeAdLoader$4.class...
processing com/google/unity/ads/NativeExpressAd.class...
processing com/google/unity/ads/NativeExpressAd$1.class...
processing com/google/unity/ads/NativeExpressAd$1$1.class...
processing com/google/unity/ads/NativeExpressAd$2.class...
processing com/google/unity/ads/NativeExpressAd$3.class...
processing com/google/unity/ads/NativeExpressAd$4.class...
processing com/google/unity/ads/NativeExpressAd$5.class...
processing com/google/unity/ads/NativeExpressAd$6.class...
processing com/google/unity/ads/PluginUtils.class...
processing com/google/unity/ads/RewardBasedVideo.class...
processing com/google/unity/ads/RewardBasedVideo$1.class...
processing com/google/unity/ads/RewardBasedVideo$1$1.class...
processing com/google/unity/ads/RewardBasedVideo$2.class...
processing com/google/unity/ads/RewardBasedVideo$3.class...
processing com/google/unity/ads/UnityAdListener.class...
processing com/google/unity/ads/UnityCustomNativeAdListener.class...
processing com/google/unity/ads/UnityRewardBasedVideoAdListener.class...
processing archive /Users/Andrew/Projects/AdMob-VS-GA/Temp/StagingArea/android-libraries/play-services-ads-9.8.0/libs/./classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/ads/
ignored resource com/google/android/gms/ads/internal/
processing com/google/android/gms/ads/internal/ClientApi.class...
processing com/google/android/gms/ads/internal/InterstitialAdParameterParcel.class...
ignored resource com/google/android/gms/ads/internal/cache/
processing com/google/android/gms/ads/internal/cache/CacheEntryParcel.class...
processing com/google/android/gms/ads/internal/cache/CacheOffering.class...
processing com/google/android/gms/ads/internal/cache/zza.class...
processing com/google/android/gms/ads/internal/cache/zza$1.class...
processing com/google/android/gms/ads/internal/cache/zza$2.class...
processing com/google/android/gms/ads/internal/cache/zza$3.class...
processing com/google/android/gms/ads/internal/cache/zza$4.class...
processing com/google/android/gms/ads/internal/cache/zzb.class...
processing com/google/android/gms/ads/internal/cache/zzc.class...
processing com/google/android/gms/ads/internal/cache/zzd.class...
processing com/google/android/gms/ads/internal/cache/zze.class...
processing com/google/android/gms/ads/internal/cache/zzf.class...
processing com/google/android/gms/ads/internal/cache/zzf$zza.class...
processing com/google/android/gms/ads/internal/cache/zzf$zza$zza.class...
processing com/google/android/gms/ads/internal/cache/zzg.class...
ignored resource com/google/android/gms/ads/internal/formats/
processing com/google/android/gms/ads/internal/formats/zzb.class...
processing com/google/android/gms/ads/internal/formats/zzg.class...
processing com/google/android/gms/ads/internal/formats/zzh.class...
processing com/google/android/gms/ads/internal/formats/zzj.class...
processing com/google/android/gms/ads/internal/formats/zzj$1.class...
processing com/google/android/gms/ads/internal/formats/zzj$2.class...
processing com/google/android/gms/ads/internal/formats/zzj$3.class...
processing com/google/android/gms/ads/internal/formats/zzj$3$1.class...
processing com/google/android/gms/ads/internal/formats/zzj$3$1$1.class...
processing com/google/android/gms/ads/internal/formats/zzj$3$2.class...
processing com/google/android/gms/ads/internal/formats/zzj$3$3.class...
processing com/google/android/gms/ads/internal/formats/zzj$3$4.class...
processing com/google/android/gms/ads/internal/formats/zzj$3$5.class...
processing com/google/android/gms/ads/internal/formats/zzl.class...
processing com/google/android/gms/ads/internal/formats/zzl$1.class...
processing com/google/android/gms/ads/internal/formats/zzl$2.class...
ignored resource com/google/android/gms/ads/internal/overlay/
processing com/google/android/gms/ads/internal/overlay/AdLauncherIntentInfoParcel.class...
processing com/google/android/gms/ads/internal/overlay/AdOverlayInfoParcel.class...
processing com/google/android/gms/ads/internal/overlay/zza.class...
processing com/google/android/gms/ads/internal/overlay/zzaa.class...
processing com/google/android/gms/ads/internal/overlay/zzaa$zza.class...
processing com/google/android/gms/ads/internal/overlay/zzb.class...
processing com/google/android/gms/ads/internal/overlay/zzc.class...
processing com/google/android/gms/ads/internal/overlay/zzc$1.class...
processing com/google/android/gms/ads/internal/overlay/zzc$2.class...
processing com/google/android/gms/ads/internal/overlay/zzc$3.class...
processing com/google/android/gms/ads/internal/overlay/zzc$4.class...
processing com/google/android/gms/ads/internal/overlay/zzc$5.class...
processing com/google/android/gms/ads/internal/overlay/zzc$6.class...
processing com/google/android/gms/ads/internal/overlay/zzc$7.class...
processing com/google/android/gms/ads/internal/overlay/zzc$8.class...
processing com/google/android/gms/ads/internal/overlay/zzd.class...
processing com/google/android/gms/ads/internal/overlay/zzd$1.class...
processing com/google/android/gms/ads/internal/overlay/zzd$2.class...
processing com/google/android/gms/ads/internal/overlay/zzd$zza.class...
processing com/google/android/gms/ads/internal/overlay/zzd$zzb.class...
processing com/google/android/gms/ads/internal/overlay/zzd$zzc.class...
processing com/google/android/gms/ads/internal/overlay/zzd$zzd.class...
processing com/google/android/gms/ads/internal/overlay/zzd$zzd$1.class...
processing com/google/android/gms/ads/internal/overlay/zze.class...
processing com/google/android/gms/ads/internal/overlay/zzf.class...
processing com/google/android/gms/ads/internal/overlay/zzg.class...
processing com/google/android/gms/ads/internal/overlay/zzh.class...
processing com/google/android/gms/ads/internal/overlay/zzi.class...
processing com/google/android/gms/ads/internal/overlay/zzj.class...
processing com/google/android/gms/ads/internal/overlay/zzk.class...
processing com/google/android/gms/ads/internal/overlay/zzk$1.class...
processing com/google/android/gms/ads/internal/overlay/zzk$2.class...
processing com/google/android/gms/ads/internal/overlay/zzl.class...
processing com/google/android/gms/ads/internal/overlay/zzm.class...
processing com/google/android/gms/ads/internal/overlay/zzn.class...
processing com/google/android/gms/ads/internal/overlay/zzo.class...
processing com/google/android/gms/ads/internal/overlay/zzp.class...
processing com/google/android/gms/ads/internal/overlay/zzs.class...
processing com/google/android/gms/ads/internal/overlay/zzt.class...
processing com/google/android/gms/ads/internal/overlay/zzu.class...
processing com/google/android/gms/ads/internal/overlay/zzv.class...
processing com/google/android/gms/ads/internal/overlay/zzv$1.class...
processing com/google/android/gms/ads/internal/overlay/zzw.class...
processing com/google/android/gms/ads/internal/overlay/zzw$1.class...
processing com/google/android/gms/ads/internal/overlay/zzw$zza.class...
processing com/google/android/gms/ads/internal/overlay/zzx.class...
processing com/google/android/gms/ads/internal/overlay/zzy.class...
processing com/google/android/gms/ads/internal/overlay/zzz.class...
ignored resource com/google/android/gms/ads/internal/purchase/
processing com/google/android/gms/ads/internal/purchase/GInAppPurchaseManagerInfoParcel.class...
processing com/google/android/gms/ads/internal/purchase/zza.class...
processing com/google/android/gms/ads/internal/purchase/zzb.class...
processing com/google/android/gms/ads/internal/purchase/zzc.class...
processing com/google/android/gms/ads/internal/purchase/zzc$1.class...
processing com/google/android/gms/ads/internal/purchase/zzd.class...
processing com/google/android/gms/ads/internal/purchase/zze.class...
processing com/google/android/gms/ads/internal/purchase/zzf.class...
processing com/google/android/gms/ads/internal/purchase/zzg.class...
processing com/google/android/gms/ads/internal/purchase/zzh.class...
processing com/google/android/gms/ads/internal/purchase/zzh$zza.class...
processing com/google/android/gms/ads/internal/purchase/zzi.class...
processing com/google/android/gms/ads/internal/purchase/zzi$1.class...
processing com/google/android/gms/ads/internal/purchase/zzj.class...
processing com/google/android/gms/ads/internal/purchase/zzk.class...
processing com/google/android/gms/ads/internal/purchase/zzl.class...
ignored resource com/google/android/gms/ads/internal/request/
processing com/google/android/gms/ads/internal/request/AdRequestInfoParcel.class...
processing com/google/android/gms/ads/internal/request/AdRequestInfoParcel$zza.class...
processing com/google/android/gms/ads/internal/request/AdResponseParcel.class...
processing com/google/android/gms/ads/internal/request/AutoClickProtectionConfigurationParcel.class...
processing com/google/android/gms/ads/internal/request/CapabilityParcel.class...
processing com/google/android/gms/ads/internal/request/LargeParcelTeleporter.class...
processing com/google/android/gms/ads/internal/request/LargeParcelTeleporter$1.class...
processing com/google/android/gms/ads/internal/request/StringParcel.class...
processing com/google/android/gms/ads/internal/request/zza.class...
processing com/google/android/gms/ads/internal/request/zza$zza.class...
processing com/google/android/gms/ads/internal/request/zzb.class...
processing com/google/android/gms/ads/internal/request/zzb$1.class...
processing com/google/android/gms/ads/internal/request/zzb$2.class...
processing com/google/android/gms/ads/internal/request/zzb$zza.class...
processing com/google/android/gms/ads/internal/request/zzc.class...
processing com/google/android/gms/ads/internal/request/zzc$1.class...
processing com/google/android/gms/ads/internal/request/zzc$zza.class...
processing com/google/android/gms/ads/internal/request/zzc$zzb.class...
processing com/google/android/gms/ads/internal/request/zzd.class...
processing com/google/android/gms/ads/internal/request/zzd$1.class...
processing com/google/android/gms/ads/internal/request/zzd$2.class...
processing com/google/android/gms/ads/internal/request/zzd$zza.class...
processing com/google/android/gms/ads/internal/request/zzd$zzb.class...
processing com/google/android/gms/ads/internal/request/zze.class...
processing com/google/android/gms/ads/internal/request/zzf.class...
processing com/google/android/gms/ads/internal/request/zzg.class...
processing com/google/android/gms/ads/internal/request/zzh.class...
processing com/google/android/gms/ads/internal/request/zzi.class...
processing com/google/android/gms/ads/internal/request/zzj.class...
processing com/google/android/gms/ads/internal/request/zzk.class...
processing com/google/android/gms/ads/internal/request/zzk$zza.class...
processing com/google/android/gms/ads/internal/request/zzk$zza$zza.class...
processing com/google/android/gms/ads/internal/request/zzl.class...
processing com/google/android/gms/ads/internal/request/zzl$zza.class...
processing com/google/android/gms/ads/internal/request/zzl$zza$zza.class...
processing com/google/android/gms/ads/internal/request/zzm.class...
processing com/google/android/gms/ads/internal/request/zzn.class...
processing com/google/android/gms/ads/internal/request/zzn$1.class...
processing com/google/android/gms/ads/internal/request/zzn$2.class...
processing com/google/android/gms/ads/internal/request/zzn$2$1.class...
processing com/google/android/gms/ads/internal/request/zzn$2$2.class...
processing com/google/android/gms/ads/internal/request/zzn$3.class...
processing com/google/android/gms/ads/internal/request/zzn$zza.class...
processing com/google/android/gms/ads/internal/request/zzn$zzb.class...
processing com/google/android/gms/ads/internal/request/zzn$zzc.class...
processing com/google/android/gms/ads/internal/request/zzo.class...
ignored resource com/google/android/gms/ads/internal/safebrowsing/
processing com/google/android/gms/ads/internal/safebrowsing/SafeBrowsingConfigParcel.class...
processing com/google/android/gms/ads/internal/safebrowsing/zza.class...
processing com/google/android/gms/ads/internal/safebrowsing/zzb.class...
processing com/google/android/gms/ads/internal/safebrowsing/zzc.class...
processing com/google/android/gms/ads/internal/safebrowsing/zzd.class...
processing com/google/a<message truncated>

**Comment by rampara** [comment]
It seems like your Unity project contains multiple copies of the same Google Play services classes. Can you try removing all Play services AARs from the `Assets/Plugins/Android` directory of your project and letting Play Services Resolver re-import the appropriate files.

**Comment by andrew-grischenko** [comment]
I did, it copied files, but on build I get the same error as above. If it helps, the dummy project with just these 2 plugins is attached. 
[AdMob-VS-GA.zip](https://github.com/googleads/googleads-mobile-unity/files/556897/AdMob-VS-GA.zip)

**Comment by rampara** [comment]
@andrew-grischenko where did you move the analytics dependency declaration to in the sample project you attached?

**Comment by andrew-grischenko** [comment]
In the AdMobDependencies.cs, lines 43..51

**Comment by rampara** [comment]
That is the declaration of the `play-services-ads` dependency.

**Comment by andrew-grischenko** [comment]
OK, it seems I missed it, apologies :(

Added this in the AdMobDependencies.cs:

```
		Google.VersionHandler.InvokeInstanceMethod( 
			svcSupport, "DependOn", 
			new object[] { "com.google.android.gms", "play-services-analytics", 
							"LATEST" }, 
			namedArgs: new Dictionary<string, object>() { 
				{"packageIds", new string[] { 
						"extra-google-m2repository", 
						"extra-android-m2repository"} } 
			});
```

I got the issue that was discussed here https://github.com/playgameservices/play-games-plugin-for-unity/issues/1428, but after deleting the files "GoogleDependencyAdMobUnity.xml" and "GoogleAarExplodeCache.xml" in the "ProjectSettings" folder and restart of Unity the libraries have been updated to 9.8.0 and the test package successfully compiled.  

I'll check later today on the real project and the device and will confirm if the issue was resolved.

**Comment by andrew-grischenko** [comment]
Yes, it works! Thank you for the support. So, the workaround is:

1.Import the Google Analytics plugin first, delete the content in the Assets/PlayServicesResolver/ directory and then import the AdMob plugin.
2.Manually add Analytics as a Play services dependency via the code below. This code can be added to the AdMobDependencies.cs file or to a new file that declares Play services dependencies.

`Google.VersionHandler.InvokeInstanceMethod( svcSupport, "DependOn", new object[] { "com.google.android.gms", "play-services-analytics", "LATEST" }, namedArgs: new Dictionary<string, object>() { {"packageIds", new string[] { "extra-google-m2repository", "extra-android-m2repository"} } });`

3.If errors occur, exit Unity, remove all Play services AARs from the Assets/Plugins/Android directory of the project and remove the files "GoogleDependencyAdMobUnity.xml" and "GoogleAarExplodeCache.xml" in the "ProjectSettings" folder and restart of Unity.
5.Launch Unity and let Play Services Resolver re-import the appropriate files.
6.It should work after that.

**Comment by rampara** [comment]
Glad you were able to get everything working.
