### ISSUE TITLE
GoogleMobileAds incompatible with latest Firebase. Can't build.

### ISSUE THREAD

**Issue by cephalo3** [googleads/googleads-mobile-unity#2994]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: __2022.3.11f1___
  * Google Mobile Ads Unity plugin version: _8.5.2____
  * Platform: _Android____ (iOS, Android, Unity Editor)
  * Platform OS version: __33___ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: __unity ads adapter___

### [REQUIRED] Step 2: Describe the problem
Can't build with the following error
CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity\Hub\Editor\2022.3.11f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK\bin\java.exe -classpath "C:\Program Files\Unity\Hub\Editor\2022.3.11f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-7.2.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "bundleRelease"

Environment Variables:
NVIDIAWHITELISTED = 0x01
RegionCode = NA
USERDOMAIN = LAPTOP-S1VAPN5Q
ProgramFiles = C:\Program Files
USERPROFILE = C:\Users\ricar
ChocolateyLastPathUpdate = 132531244055716855
PROCESSOR_ARCHITECTURE = AMD64
PROCESSOR_REVISION = a502
OneDriveConsumer = C:\Users\ricar\OneDrive
OS = Windows_NT
CHROME_CRASHPAD_PIPE_NAME = \\.\pipe\crashpad_7380_SAIDXNWHSJPXXJDW
PROCESSOR_IDENTIFIER = Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
ProgramW6432 = C:\Program Files
SENTRY_ACCESS_TOKEN = 3df78d9e53f8456aa90fbae044ce1a6261421ab1d0014674bc2e933477289017
JAVA_HOME = C:\Program Files\Unity\Hub\Editor\2022.3.11f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK
CommonProgramFiles = C:\Program Files\Common Files
DriverData = C:\Windows\System32\Drivers\DriverData
ComSpec = C:\WINDOWS\system32\cmd.exe
AMPLITUDE_API_KEY = 28f3cae0b33b8b3702120c9ed1a935aa
PSModulePath = C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
ANDROID_NDK_ROOT = C:\Program Files\Unity\Hub\Editor\2022.3.11f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK
ChocolateyInstall = C:\ProgramData\chocolatey
HEAP_CLIENT_TOKEN = 1717415662
platformcode = KV
NUMBER_OF_PROCESSORS = 8
AMPLITUDE_API_KEY_STAGING = 83ee04fccc67e4fcc7dd527c4c6f1e21
WOOTRIC_CLIENT_TOKEN = NPS-aa8be4c3
JAVA_TOOL_OPTIONS = -Dfile.encoding=UTF-8
DEBUG_ENV_VAR = UnityHub
TMP = C:\Users\ricar\AppData\Local\Temp
HOMEDRIVE = C:
TEMP = C:\Users\ricar\AppData\Local\Temp
Path = C:\Python311\Scripts\;C:\Python311\;C:\Python310\Scripts\;C:\Python310\;C:\Python39\Scripts\;C:\Python39\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\ProgramData\chocolatey\bin;;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Users\ricar\AppData\Local\Microsoft\WindowsApps;C:\Users\ricar\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\ricar\.dotnet\tools;C:\Users\ricar\AppData\Roaming\npm
USERNAME = ricar
COMPUTERNAME = LAPTOP-S1VAPN5Q
BURST_ANDROID_MIN_API_LEVEL = 22
PATHEXT = .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
LAUNCH_DARKLY_CLIENT_TOKEN_STAGING = 60a7e30fafc7e60e33446282
ALLUSERSPROFILE = C:\ProgramData
SystemDrive = C:
OnlineServices = Online Services
HEAP_CLIENT_TOKEN_STAGING = 3786794399
EFC_9332 = 1
windir = C:\WINDOWS
HOMEPATH = \Users\ricar
PUBLIC = C:\Users\Public
CommonProgramFiles(x86) = C:\Program Files (x86)\Common Files
APPDATA = C:\Users\ricar\AppData\Roaming
OneDrive = C:\Users\ricar\OneDrive
PROCESSOR_LEVEL = 6
CommonProgramW6432 = C:\Program Files\Common Files
ProgramFiles(x86) = C:\Program Files (x86)
SystemRoot = C:\WINDOWS
SESSIONNAME = Console
LOGONSERVER = \\LAPTOP-S1VAPN5Q
LOCALAPPDATA = C:\Users\ricar\AppData\Local
LAUNCH_DARKLY_CLIENT_TOKEN = 60a7e30fafc7e60e33446283
SHIM_MCCOMPAT = 0x810000001
USERDOMAIN_ROAMINGPROFILE = LAPTOP-S1VAPN5Q
ProgramData = C:\ProgramData
ORIGINAL_XDG_CURRENT_DESKTOP = undefined

stderr[
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Note: C:\Users\ricar\OneDrive\Documents\ForwardLine\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.gms.internal.consent_sdk.zza found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzaa found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzab found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzac found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzad found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzae found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzaf found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzag found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzah found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzai found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzaj found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzak found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzal found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzam found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzan found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzao found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzap found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzaq found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzar found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzas found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzat found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzau found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzav found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzaw found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzax found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzay found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzaz found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzb found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzba found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzbb found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzbc found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzbd found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzbe found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzbf found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzbg found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consent_sdk.zzbh found in modules com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and com.google.android.ump.user-messaging-platform-2.1.0-runtime (:com.google.android.ump.user-messaging-platform-2.1.0:)
     Duplicate class com.google.android.gms.internal.consen<message truncated>
#### Steps to reproduce:

What happened? How can we make the problem occur?

This is what happens when I try to build with the latest package manager version of Firebase. I have used this combo before without issue in previous versions. I think it's time to make a package manager version of this plugin. I'm not sure I want to go back to the unitypackage version of Firebase. It just works so well.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by NVentimiglia** [comment]
Hi,

I have replicated the issue and started looking into a fix.

**Comment by NVentimiglia** [comment]
@cephalo3 
 I have a work around, be sure to setup unity to use [gradle resolution](https://developers.google.com/admob/unity/quick-start#include_external_dependencies) and use the Android Studio Export option when building.

**Comment by NVentimiglia** [comment]
Also note Firebase requires Gradle 7.8 minversion. You may need to update Unity to 2022.3 or upgrade your [gradle](https://developers.google.com/admob/unity/gradle)

**Comment by cephalo3** [comment]
Thanks for the work around! I've never actually tried building with Android Studio, but I'll give it a shot. Good thing to know how to do I guess.

**Comment by cephalo3** [comment]
I am getting the same problem in Android Studio. I have no idea what to do about it. Does AS have a resolver I have to activate?
