### ISSUE TITLE
Interstitial ads on test devices do not respect volume settings

### ISSUE THREAD

**Issue by batteredhedgehog** [googleads/googleads-mobile-unity#2995]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: _____2022.3.8f1
  * Google Mobile Ads Unity plugin version: _____8.5.3
  * Platform: _____ Android
  * Platform OS version: _____ Android 14
  * Any specific devices issue occurs on: _____Google pixel 6a configured as test device
  * Mediation ad networks used, and their versions: _____none

### [REQUIRED] Step 2: Describe the problem

Playing an interstitial ad on a device configured as a test device plays at full volume  after volume is changed by calling
            MobileAds.SetApplicationVolume(0.2f);
This makes it impossible to test that implementation is functioning as required.

#### Steps to reproduce:

1. Initialize MobileAds
2. Configure your device as a test device.
3. call MobileAds.SetApplicationVolume(0.2f);
4. play the interstital ad.

What happened? How can we make the problem occur?
The ad played at full volume.

This could be a description, log/console output, etc.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
```

**Comment by NVentimiglia** [comment]
@mastef 

This looks like a super complex issue which will need help from the SDK team to solve. Can you open up a support request on the [Google support group](https://developers.google.com/admob/unity/support) so that we can involve them?

Can you please include which devices and platform you are experiencing this on ?

**Comment by batteredhedgehog** [comment]
@NVentimiglia 
Have you ever tried to do anything through that google group?  Its not a sensible place to be.   All issues I have tried to resolve there have gone absolutely nowhere - and been very repetitive and frustrating.  Unfortunately I'm unwilling to go back there to try anything.

**Comment by batteredhedgehog** [comment]
@NVentimiglia .  Platform and devices are listed in the original post.

**Comment by mastef** [comment]
@NVentimiglia I think you tagged me in the wrong issue

**Comment by NVentimiglia** [comment]
> @NVentimiglia Have you ever tried to do anything through that google group? Its not a sensible place to be. All issues I have tried to resolve there have gone absolutely nowhere - and been very repetitive and frustrating. Unfortunately I'm unwilling to go back there to try anything.

@batteredhedgehog fair enough. I prefer github myself, but for some issue I need to be able to forward the issue to other teams. For me to do this, I need to go through the google support system.

You can also submit the issue [by email](https://developers.google.com/admob/unity/support).

**Comment by batteredhedgehog** [comment]
@NVentimiglia 
No problem.  I submitted a request via email. I'll let you know if / when they get back to me.

**Comment by batteredhedgehog** [comment]
@NVentimiglia .  They have asked me for a sample project to reproduce the issue.  I'll see if I can create one quickly.

**Comment by batteredhedgehog** [comment]
OK.. I think I've worked out what the problem is.  
Changing the volume via MobileAds.SetApplicationVolume() does not alter the volume for preloaded ads.  This is not documented anywhere.  It would be nice if this were documented.
Muting the volume via MobileAds.SetApplicationMuted() DOES mute the volume of preloaded ads - which is inconsistent with the volume method.

Is it ok to destroy pre-loaded ads before they are shown when users adjust the volume?  I'm not going to get penalised by the diligent admob enforcers?

**Comment by NVentimiglia** [comment]
@batteredhedgehog Thanks for the information, I will make note of this.

**Comment by NVentimiglia** [comment]
Closing, this is a product / ad formats issue. I have sent over a request to this team to look into the issue, but will be closing the issue here as this is not a unity plugin issue.
