### ISSUE TITLE
AdWorker causing java.lang.OutOfMemoryError errors in pthread_create

### ISSUE THREAD

**Issue by mastef** [googleads/googleads-mobile-unity#2996]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.4f1 - 2022.3.10f1 
  * Google Mobile Ads Unity plugin version: 8.5.2
  * Platform: Android
  * Platform OS version: Android 10, 9, 11, 8.1, Others
  * Any specific devices issue occurs on: Samsung a02, Motorola Malta, Xiaomi Olivelite, Xiaomi Pine, Alcatel Aquaman 10.4G,  Others
  * Mediation ad networks used, and their versions: No

#### Steps to reproduce:

We have constant reports of crashes across a wide variety of devices that AdWorker causes an "Out of Memory" crash - it's the top crash reason for our app in the "Crashes and ANRs" section if the Google Play Console.

![image](https://github.com/googleads/googleads-mobile-unity/assets/762297/1ca3148a-ce96-45e8-985a-efcd0277c009)
![image](https://github.com/googleads/googleads-mobile-unity/assets/762297/fef3a8a2-67bc-4884-a75d-3f86cb2d0527)

Top 2 devices affected seem to be Samsung a02 and Motorola Malta, but the device list is long.
![image](https://github.com/googleads/googleads-mobile-unity/assets/762297/803098aa-969f-49eb-b123-f063412ff3e9)

Out of the 30+ stacktraces, 95% are caused by `AdWorker(Default)` or `AdWorker(ClientSingle)`. One was caused be `firebase-installations-executor-19`, and 2 by `ScionFrontendApi`. All seem admob or google product related.

Example stack traces are mostly identical.

```
java.lang.Error
Exception java.lang.Error: FATAL EXCEPTION [AdWorker(ClientSingle) #1]
Unity version     : 2022.3.10f1
Device model      : motorola Moto G (5) Plus
Device fingerprint: motorola/potter_nt/potter_nt:8.1.0/OPS28.85-17-6-3/c366b:user/release-keys
CPU supported ABI : [armeabi-v7a, armeabi]
Build Type        : Release
Scripting Backend : IL2CPP
Libs loaded from  : lib/arm
Strip Engine Code : true

Caused by: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
  at java.lang.Thread.nativeCreate
  at java.lang.Thread.start (Thread.java:733)
  at java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:970)
  at java.util.concurrent.ThreadPoolExecutor.processWorkerExit (ThreadPoolExecutor.java:1038)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1180)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)
```

```
java.lang.Error
Exception java.lang.Error: FATAL EXCEPTION [firebase-installations-executor-19]
Unity version     : 2022.3.4f1
Device model      : Xiaomi 220733SG
Device fingerprint: Redmi/ice_id/ice:12/SP1A.210812.016/V13.0.7.0.SGMIDXM:user/release-keys
CPU supported ABI : [armeabi-v7a, armeabi]
Build Type        : Release
Scripting Backend : IL2CPP
Libs loaded from  : lib/arm
Strip Engine Code : true

Caused by: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
  at java.lang.Thread.nativeCreate
  at java.lang.Thread.start (Thread.java:884)
  at java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:975)
  at java.util.concurrent.ThreadPoolExecutor.processWorkerExit (ThreadPoolExecutor.java:1043)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1185)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:920)
```

```
java.lang.Error
Exception java.lang.Error: FATAL EXCEPTION [AdWorker(ClientSingle) #1]
Unity version     : 2022.3.4f1
Device model      : motorola moto g pure
Device fingerprint: motorola/ellis_retail/ellis:12/S3RHS32.20-42-10-4-6-1-2/ec027:user/release-keys
CPU supported ABI : [armeabi-v7a, armeabi]
Build Type        : Release
Scripting Backend : IL2CPP
Libs loaded from  : lib/arm
Strip Engine Code : true

Caused by: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
  at java.lang.Thread.nativeCreate
  at java.lang.Thread.start (Thread.java:976)
  at java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:954)
  at java.util.concurrent.ThreadPoolExecutor.processWorkerExit (ThreadPoolExecutor.java:1022)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1159)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:644)
  at java.lang.Thread.run (Thread.java:1012)
```

```
java.lang.Error
Exception java.lang.Error: FATAL EXCEPTION [AdWorker(ClientSingle) #1]
Unity version     : 2022.3.4f1
Device model      : samsung SM-A022M
Device fingerprint: samsung/a02ub/a02:11/RP1A.200720.012/A022MUBS3BWF2:user/release-keys
CPU supported ABI : [armeabi-v7a, armeabi]
Build Type        : Release
Scripting Backend : IL2CPP
Libs loaded from  : lib/arm
Strip Engine Code : true

Caused by: java.lang.OutOfMemoryError: Could not allocate JNI Env: Failed anonymous mmap(0x0, 8192, 0x3, 0x22, -1, 0): Operation not permitted. See process maps in the log.
  at java.lang.Thread.nativeCreate
  at java.lang.Thread.start (Thread.java:887)
  at java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:975)
  at java.util.concurrent.ThreadPoolExecutor.processWorkerExit (ThreadPoolExecutor.java:1043)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1185)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:923)
```

How can we find out what the underlying issue is?

**Comment by NVentimiglia** [comment]
@mastef 

This looks like a super complex issue which will need help from the Android SDK team to solve. Can you open up a support request on the [Google support group](https://developers.google.com/admob/unity/support) so that we can involve them?

**Comment by mastef** [comment]
@NVentimiglia possibly related to this forum thread, although their stacktraces are longer https://groups.google.com/g/google-admob-ads-sdk/c/pujkgoldM2s/m/A6feyiU6BgAJ

Somebody got around it by hacking the bytecode values for maxPoolSize and corePoolSize. Maybe you could expose those values through the SDK?

**Comment by NVentimiglia** [comment]
@mastef Sounds like a change which would require review from the Android team. Best to include that detail in the support ticket. Feel free to CC me or this thread.

**Comment by mastef** [comment]
> @mastef Sounds like a change which would require review from the Android team. Best to include that detail in the support ticket. Feel free to CC me or reference this thread.

I'm not sure how your internal system works - can you find a case number 00208702 ?

Related issues seem to be :
https://groups.google.com/g/google-admob-ads-sdk/c/pujkgoldM2s/m/A6feyiU6BgAJ
https://groups.google.com/g/google-admob-ads-sdk/c/EHcInQAG9VY/m/dZ2aG_XHAgAJ
https://groups.google.com/g/google-admob-ads-sdk/c/VMOG00FIOlw/m/mX6dHGL9AgAJ
https://groups.google.com/g/google-admob-ads-sdk/c/IqHshzM-Dsc/m/bar6wOSyAQAJ

Although I'm not sure how they are able to get the longer stacktraces - so not 100% sure if it's the same cause. There can be multiple causes why a thread is being created.

**Comment by mastef** [comment]
> @mastef Sounds like a change which would require review from the Android team. Best to include that detail in the support ticket. Feel free to CC me or reference this thread.

@NVentimiglia I'm not sure how your internal system works - can you find a case number 00208702 ?

Related issues seem to be :
https://groups.google.com/g/google-admob-ads-sdk/c/pujkgoldM2s/m/A6feyiU6BgAJ
https://groups.google.com/g/google-admob-ads-sdk/c/EHcInQAG9VY/m/dZ2aG_XHAgAJ
https://groups.google.com/g/google-admob-ads-sdk/c/VMOG00FIOlw/m/mX6dHGL9AgAJ
https://groups.google.com/g/google-admob-ads-sdk/c/IqHshzM-Dsc/m/bar6wOSyAQAJ

Although I'm not sure how they are able to get the longer stacktraces - so not 100% sure if it's the same cause. There can be multiple causes why a thread is being created.

So although multiple threads have the same error, they may have different causes.

**Comment by NVentimiglia** [comment]
@mastef 

Thanks for the research. A thread for your specific case is still suggested. I have limited ability to help with Java errors, and going through the group should get the problem forwarded to the right team.

**Comment by mastef** [comment]
> @mastef
> 
> Thanks for the research. A thread for your specific case is still suggested. I have limited ability to help with Java errors, and going through the group should get the problem forwarded to the right team.

I have received a private reply and sent them something in this thread https://groups.google.com/g/google-admob-ads-sdk/c/pujkgoldM2s/m/A6feyiU6BgAJ - but literally every other google thread that had that question and the asker sending their info on a pthread_create issue - ended up with an answer 10 months later with "it can happen due to many reasons / we can't reproduce this"

Meanwhile : 

![image](https://github.com/googleads/googleads-mobile-unity/assets/762297/9a843741-43ad-4d07-9dda-a2edeb49ad4c)

![image](https://github.com/googleads/googleads-mobile-unity/assets/762297/e8da5903-4e20-4d2a-90bb-bf0796e85ae5)

Ideally I'm thinking of disabling admob for these devices if I can figure out how...

**Comment by NVentimiglia** [comment]
Closing this issue as it needs to be handled by the Android SDK team.

https://groups.google.com/g/google-admob-ads-sdk

**Comment by superbderrick** [comment]
Any updates?:

**Comment by mastef** [comment]
> November 17, 2023: "The team has recently identified the issue and is currently working on a potential fix. I will respond here as soon as I have a resolution from the team. Any fix for this would be included in a future release for the Android Google Mobile Ads SDK."

**Comment by nan-li** [comment]
Hi @mastef, where did you receive this update on November 17? I am looking for the same information.

**Comment by sidsharma2002** [comment]
@mastef Hi, do you know can I also change the bytecode like he did ? any resources ?
