### ISSUE TITLE
AdMob 8.5.3 - Unity 3.8.0 and Meta 3.11.0 - Resolution failed - org.jetbrains.kotlin:kotlin-bom:1.8.10

### ISSUE THREAD

**Issue by dcosmin-97** [googleads/googleads-mobile-unity#2997]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.12f1
  * Google Mobile Ads Unity plugin version: 8.5.3
  * Platform: Android - Editor
  * Mediation ad networks used, and their versions: 
       - Firebase 11.6.0 - crashlytics, analytics
       - Meta 3.11.0
       - Pangle 2.3.0
       - Applovin 6.9.1
       - Liftoff 4.0.0
       - Mintegral 1.2.1

#### Steps to reproduce:

If you add Unity 3.8.0 and start resolving, you will receive the following error:
Failed to fetch the following dependencies:
org.jetbrains.kotlin:kotlin-bom:1.8.10

I have tested this with both 
com.google.android.gms:play-services-ads:[22.3.0]
com.google.android.gms:play-services-ads:22.3.0

The issue is that you can either have Meta or Unity. You cannot have both of them in the same project.

Do you have any temporary fix for this?
Maybe some gradle script to handle the org.jetbrains.kotlin:kotlin-bom:1.8.10 error?

**Comment by NVentimiglia** [comment]
@dcosmin-97 

This issue is cause by the EDM. There are two ways to solve it.

1) Do not use EDM to resolve dependencies. We have [updated out getting started guide](https://developers.google.com/admob/unity/quick-start#include_external_dependencies) with this step.

2) Update the `launcher/build.gradle` file with a pick first instruction

```
android {
   ... 
packagingOptions {
    pickFirst "META-INF/kotlinx_coroutines_core.version"
}
```

**Comment by dcosmin-97** [comment]
> @dcosmin-97
> 
> This issue is cause by the EDM. There are two ways to solve it.
> 
>     1. Do not use EDM to resolve dependencies. We have [updated out getting started guide](https://developers.google.com/admob/unity/quick-start#include_external_dependencies) with this step.
> 
>     2. Update the `launcher/build.gradle` file with a pick first instruction
> 
> 
> ```
> android {
>    ... 
> packagingOptions {
>     pickFirst "META-INF/kotlinx_coroutines_core.version"
> }
> ```

Hello!

Thank you!
I couldn't manage to fix this in Unity 2022.3.12f1 so I moved back to 2021.
I have managed to get a normal build with both Unity 3.8.0 and Meta 3.11.0 using the gradle tutorial and everything worked OK.

The new issue is that if I add DT Exchange over this mediation configuration, it will crash again.

**Comment by VaasInsanity** [comment]
> > @dcosmin-97
> > This issue is cause by the EDM. There are two ways to solve it.
> > ```
> > 1. Do not use EDM to resolve dependencies. We have [updated out getting started guide](https://developers.google.com/admob/unity/quick-start#include_external_dependencies) with this step.
> > 
> > 2. Update the `launcher/build.gradle` file with a pick first instruction
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > android {
> >    ... 
> > packagingOptions {
> >     pickFirst "META-INF/kotlinx_coroutines_core.version"
> > }
> > ```
> 
> Hello!
> 
> Thank you! I couldn't manage to fix this in Unity 2022.3.12f1 so I moved back to 2021. I have managed to get a normal build with both Unity 3.8.0 and Meta 3.11.0 using the gradle tutorial and everything worked OK.
> 
> The new issue is that if I add DT Exchange over this mediation configuration, it will crash again.

Hello, 
what gradle tutorial you followed to make a build? am getting resolution failed, with same adapters. in Unity 2021.3.0f1

**Comment by dcosmin-97** [comment]
@VaasInsanity Hi! I just used the options from here:  https://developers.google.com/admob/unity/quick-start#include_external_dependencies and update gradle here: https://developers.google.com/admob/unity/gradle . This is a workaround at the moment. If you have DTExchange in the setup, it will fail at the moment

**Comment by NVentimiglia** [comment]
Hello everyone,

We have [launched v8.6.0](https://github.com/googleads/googleads-mobile-unity/releases/tag/v8.6.0) of the Google Mobile Ads for Unity Plugin. This is an important patch release that resolves compatibility issues between older AGP version 4.0.1(Unity editors below 2022.3) and Android GMA SDKv 22.4 and above. 

Previously, we have published[ this workaround](https://developers.google.com/admob/unity/gradle) instructing you on how to upgrade Unity's Gradle installation. While this option is still recommended, this additional step is no longer required with and after v8.6.0 of the Plugin

In Google Mobile Ads Settings you will see two new options; **"Enable kotlix.coroutines packaging options."** and **"Remove property tag from GMA Android SDK."**. Make sure both of these options are enabled and your build should work as expected.

![image](https://github.com/googleads/googleads-mobile-unity/assets/125889/9028b373-c3eb-4a20-8e7d-52c0b133c84e)

Lastly, if you see any issues with this release, please report the problem here, and I will be happy to help you out.

Nick

**Comment by dheerajakula** [comment]
hey @NVentimiglia I still have the same issue of conflicting packages, even after checking both of those options

```
* What went wrong:
Execution failed for task ':unityLibrary:mergeReleaseJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'META-INF/kotlinx_coroutines_core.version' from inputs:
      - E:\CrickStarzz\Library\Bee\Android\Prj\Mono2x\Gradle\unityLibrary\libs\org.jetbrains.kotlinx.kotlinx-coroutines-core-1.7.1.jar
      - E:\CrickStarzz\Library\Bee\Android\Prj\Mono2x\Gradle\unityLibrary\libs\org.jetbrains.kotlinx.kotlinx-coroutines-core-jvm-1.7.1.jar
     Adding a packagingOptions block may help, please refer to
     https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
     for more information
```
  
unity version: 2022.3.13f1 LTS
ads unity plugin: v8.6.0

**Comment by vinkini** [comment]
Can you try bypassing EDM by turning on `Custom Main Gradle Template` and `Custom Gradle Settings Template` in `Build` under `Publishing Settings` in the `Player Settings` window. This should result in default gradle resolution thereby bypassing this issue.

**Comment by dheerajakula** [comment]
Thanks! @vinkini this fixed the issue:
I tried the same solution on 2023.2.1f1 but faced with same error like this user: [namespace error](https://www.reddit.com/r/Unity3D/comments/16ydr0s/error_while_evaluating_property_namespace_of_task/)
But this fix works after downgrading to 2022.3.13f1 LTS

**Comment by ChaserKnight** [comment]
> Hello everyone,
> 
> We have [launched v8.6.0](https://github.com/googleads/googleads-mobile-unity/releases/tag/v8.6.0) of the Google Mobile Ads for Unity Plugin. This is an important patch release that resolves compatibility issues between older AGP version 4.0.1(Unity editors below 2022.3) and Android GMA SDKv 22.4 and above.
> 
> Previously, we have published[ this workaround](https://developers.google.com/admob/unity/gradle) instructing you on how to upgrade Unity's Gradle installation. While this option is still recommended, this additional step is no longer required with and after v8.6.0 of the Plugin
> 
> In Google Mobile Ads Settings you will see two new options; **"Enable kotlix.coroutines packaging options."** and **"Remove property tag from GMA Android SDK."**. Make sure both of these options are enabled and your build should work as expected.
> 
> ![image](https://private-user-images.githubusercontent.com/125889/283959015-9028b373-c3eb-4a20-8e7d-52c0b133c84e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMTI2MjQsIm5iZiI6MTcwMjExMjMyNCwicGF0aCI6Ii8xMjU4ODkvMjgzOTU5MDE1LTkwMjhiMzczLWMzZWItNGEyMC04ZTdkLTUyYzBiMTMzYzg0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQwODU4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjQ3MGE2YjZlMmVkMzdhYWViYjczZjY3OTlmMmM0ZGZmODlmNzM4Mzc3N2VlMTU3NzQ1MGVmNTViNTdmNTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o_H1HKuiecNwQw6QTAY59RTCKkyZU0dYydVlt8o-TrM)
> 
> Lastly, if you see any issues with this release, please report the problem here, and I will be happy to help you out.
> 
> Nick

@NVentimiglia I am using Unity 2022.3.10f1, should I turn on "Remove property tag from GMA Android SDK" or keep it off? As it is not on by default, I am not sure what to do with Unity 2022.3.10f1. Please let me know. I kept the "Enable kotlinx.coroutines packaging option." on as it is on by default.

**Comment by vinkini** [comment]
For 2022.3 and above, its advised to keep it off. For GMA Android SDK v22.4.0 and above, we need Android Gradle Plugin version 4.2.2 and above. 2022.3 and above ships with higher version of AGP so there is no need to strip out the property tag. 

The "Enable kotlinx.coroutines packaging option" is required if "Custom Main Gradle Template" is not turned on in Publishing Settings under Player Settings.

**Comment by ChaserKnight** [comment]
> For 2022.3 and above, its advised to keep it off. For GMA Android SDK v22.4.0 and above, we need Android Gradle Plugin version 4.2.2 and above. 2022.3 and above ships with higher version of AGP so there is no need to strip out the property tag.
> 
> The "Enable kotlinx.coroutines packaging option" is required if "Custom Main Gradle Template" is not turned on in Publishing Settings under Player Settings.

Thanks a lot for the quick response. I have turned on both of these in player settings:

- "Custom Main Gradle Template"
- "Custom Gradle Properties Template"

Following [this official guide](https://developers.google.com/admob/unity/quick-start#include_external_dependencies), so should I now turn off "Enable kotlinx.coroutines packaging option."? Please let me know.

**Comment by vinkini** [comment]
If youn turn on `Custom Main Gradle Template`, toggling `Enable kotlinx.coroutines packaging option` will have no adverse impact. Please let us know if you see build errors. These options were added purely to prevent Build errors when building for Android.

**Comment by ChaserKnight** [comment]
> toggling

by "toggling `Enable kotlinx.coroutines packaging option`", do you mean turning it on or off?

**Comment by ChaserKnight** [comment]
> If youn turn on `Custom Main Gradle Template`, toggling `Enable kotlinx.coroutines packaging option` will have no adverse impact. Please let us know if you see build errors. These options were added purely to prevent Build errors when building for Android.

Hi @vinkini requesting you to please let me know if I should keep the `Enable kotlinx.coroutines packaging option`checkbox on or off as I have turner on `Custom Main Gradle Template` in the player settings.

**Comment by raveneer** [comment]
I'm trying the same thing and found out that I can't use Unity and Meta together. Am I right?
I changed [gradle](https://developers.google.com/admob/unity/quick-start?hl=ko#include_external_dependencies). 
- I can build GoogleMobileAdsUnityAdsMediation.3.9.0
- I can build MetaAudienceNetworkUnityAdapter-3.11.0
- I Can Not build with together
