### ISSUE TITLE
user AD_ID

### ISSUE THREAD

**Issue by MariuszJendrzejczak** [googleads/googleads-mobile-unity#2999]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.5f1
  * Google Mobile Ads Unity plugin version: 8.5.1 , 8.5.3 test on both
  * Platform: Android, 
  * Platform OS version: Android 13

#### Steps to reproduce:

Making empty unity project and adding GoogleMoblie Ads for Unity plugin

#### Issue

I have an application targeted at children, so it cannot contain the Ad_ID declaration. The Google Mobile Ads plugin uses it, so to restrict it, I've implemented code in the manifest that removes this permission:

```
<uses-permission
    android:name="com.google.android.gms.permission.AD_ID"
    tools:node="remove"/>
<meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />
```

After building the project, I decompiled it to check if the manifest really does not contain this permission. It doesn't. However, when I upload such a build to the Play Store, I receive information that my build contains the Ad_ID permission and I can't upload it since I declared that I do not use it in the application.

I am not sure if this is a fault of the plugin itself because the checked manifest does not have this permission, or the logic of the app verification on the Play Store, or maybe I am incorrectly removing this permission from the manifest.

**Comment by NVentimiglia** [comment]
Hi @MariuszJendrzejczak 

This looks like an Android SDK concern. Can you submit this to the [Google SDK team](https://developers.google.com/admob/unity/support)?

Thanks.

**Comment by MariuszJendrzejczak** [comment]
I made some future tests, and it turns up, that even with totaly empty unity poroject i get the same error. 
I assume, I need to write ticket to google app store help desk.
