### ISSUE TITLE
Very first consent request (prior to user giving consent) contains AAID, violating GDPR.

### ISSUE THREAD

**Issue by batteredhedgehog** [googleads/googleads-mobile-unity#3003]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: _____2022.3.8f1
  * Google Mobile Ads Unity plugin version: _____8.5.3
  * Platform: _____Android
  * Platform OS version: _____ Android 14
  * Any specific devices issue occurs on: _____Pixel 6a
  * Mediation ad networks used, and their versions: _____none

### [REQUIRED] Step 2: Describe the problem

I have configured admob with no mediation.
I am calling UMP consent as suggested in the documentation, before I initialize admob.
I use charles proxy to look at the packets sent.
The very first packet my app sends is a consent request - which includes the AAID ..  which violates GDPR.  See below image.
I do not want to disable personalised ads.
How am I supposed to prevent this from happening.  I have searched the documentation and cannot find an answer.  I have also reached out to the admob google group - and received a nonsensical answer which pointed me to an irrelevant document.

![Screenshot from 2023-11-07 14-20-01](https://github.com/googleads/googleads-mobile-unity/assets/108918687/b48f11a3-d725-4fca-8546-f35baa71dba5)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by batteredhedgehog** [comment]
This is easy to demonstrate with the google provided  unity admob HelloWorld sample.

1. Create a unity project.
2. Install and configure the admob plugin.
3. Copy the HelloWorld code from this repository.
4. Install charles proxy on your pc
5. configure charles proxy as an ssl proxy.
6. set your android device to use the charles proxy.
7. Install the charlesproxy unityplugin from [this page](https://support.unity.com/hc/en-us/articles/115002917683-Using-Charles-Proxy-with-Unity)
8. Set your build platform to android
9. build and run the application on a device.
10. The first call from the app in the charles proxy log contains the adid as shown in the above screen shot.

**Comment by LambdaStudiosPH** [comment]
i think this is the reason why my app will get removed on december 4. Im using the gdpr consent and suddenly google flagged my app saying its transmitting advertising id. Please help us fix this. thanks admins.
![image](https://github.com/googleads/googleads-mobile-unity/assets/143337634/361ff301-33e9-46c1-9638-b227de2389fd)

**Comment by NVentimiglia** [comment]
@batteredhedgehog 

This is fixed in UMP SDK 2.1.0, which is available on Android 22.5.0. You can update your `ExternalDependencies.xml` file to pull in this dependency explicitly.

**Comment by batteredhedgehog** [comment]
This is what is already listed in my AndroidResolverDependencies.xml

```
<dependencies>
  <packages>
    <package>com.google.android.gms:play-services-ads:[22.3.0]</package>
    <package>com.google.android.gms:play-services-base:18.2.0</package>
    <package>com.google.android.ump:user-messaging-platform:2.1.0</package>
    <package>com.google.firebase:firebase-analytics:21.3.0</package>
    <package>com.google.firebase:firebase-analytics-unity:11.6.0</package>
    <package>com.google.firebase:firebase-app-unity:11.6.0</package>
    <package>com.google.firebase:firebase-common:20.3.3</package>
    <package>com.google.firebase:firebase-config:21.4.1</package>
    <package>com.google.firebase:firebase-config-unity:11.6.0</package>
  </packages>
  ...
```

Notice that it already includes ump 2.1.0.  Do you mean I also need to include play-services-ads:22.5.0 ?

If so, according to the release notes that dependency is pinned because of another bug [Google Mobile Ads Unity Plugin v8.5.3](https://github.com/googleads/googleads-mobile-unity/releases/tag/v8.5.3)

I'm not sure where that leaves me..

**Comment by batteredhedgehog** [comment]
See #2930

**Comment by batteredhedgehog** [comment]
@NVentimiglia 
I might be wrong, but you seem to be underestimating the urgency of this issue.  Won't anyone who tries to publish an app that uses the google mobile ads unity plugin v8.5.3  likely get rejected from the play store - as possibly evidenced by @LambdaStudiosPH above.

**Comment by batteredhedgehog** [comment]
@NVentimiglia 
As with #2930, updating dependencies to play-services-ads:22.5.0 leads to build failures.  My Project Settings -> Player -> Android -> Other Settings -> Target Api Level is set to highest installed.  You can try it yourself with your own HelloWorld sample app.

```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Note: /home/jules/src/AdmobSample/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/unity3d/player/UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:checkReleaseAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > One or more issues found when checking AAR metadata values:
     
     Dependency 'androidx.privacysandbox.ads:ads-adservices-java:1.0.0-beta05' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency 'androidx.privacysandbox.ads:ads-adservices:1.0.0-beta05' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /home/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:190)

```

**Comment by batteredhedgehog** [comment]
ok.. apologies for the many posts.
So I managed to get it to build.  I had to manually select 34 as the target API in unity and get it to download the SDK.

Using your HelloWorld code. After I updated the dependency to play-services-ads:22.5.0 and updated the targetAPI level to 34, the build succeeded.
Then I set up charles proxy again.. with identical results.  The adid and device info are in the first request as in the above screenshot.

I really think you should dedicate some time to testing this yourself.  As it stands, admob with UMP is unusable.

**Comment by s4relok** [comment]
I'm having the same issue: 

Google Play rejects my updates with the message:

> For example, the destinations of Android Advertising ID transmission may include, but are not limited to, **fundingchoicesmessages.google.com**

This request seems to be containing AD_ID. 

Using: 
Google Mobile Ads Unity Plugin v8.5.3
It includes dependency on com.google.android.ump:user-messaging-platform:2.1.0

Also I tried set true to "TagForUnderAgeOfConsent" setting:

```
ConsentRequestParameters request = new ConsentRequestParameters
{
       TagForUnderAgeOfConsent = true,
       ConsentDebugSettings = debugSettings
};
```

The same result: app rejected.

**Comment by batteredhedgehog** [comment]
I know I'm being a bit negative but I am baffled that the sdks dont have unit or integration tests that ensure that private ids and data are not sent with UMP consent requests.  Its pretty core to the library.  I find it extraordinary that it falls to developers who are trying to implement (and believe me I have tried - it has taken me weeks to get to this point) a google policy requirement to find such fundamental flaws.

**Comment by pescador07** [comment]
I have the same problem  :(

**Comment by batteredhedgehog** [comment]
OK..  seeing as there is no response here, not even to acknowledge the problem - I'll try to do some of the legwork to keep things moving.

@pescador07 , @s4relok , @LambdaStudiosPH  - I'm thinking there could be a lot of reasons for app rejection.  The specifics of your rejections sound like they may be related to this problem.

Can any of you verify on a real device that you are actually hitting this issue by looking at the data sent from your apps?  You'll need to use some sort of SSL proxy.  Most people seem to use charles proxy.  Its a bit fiddly, but not that hard to set up.  It is well documented on the internet for all platforms (Windows, Linux, Macos).  Your looking for the "adid" in the request data for the first consent HTTPS request from your app - as shown in the screnshot in my original post.

**Comment by NVentimiglia** [comment]
@batteredhedgehog 
@pescador07 

I see the issue, we are looking into a fix for the issue.

**Comment by NVentimiglia** [comment]
We are removing this functionality from UMP 2.2.0.  Please update to the latest UMP SDK when it is released.

**Comment by batteredhedgehog** [comment]
Thanks @NVentimiglia . 
I'm sure your realise that policy requirement for using a CMP in admob becomes active in January.  Is there a release time frame?  
Any suggestions for people who's apps are being rejected now because of this?

**Comment by pescador07** [comment]
Hello everyone, I have sent a version of the app for review without calling UMP consent and Google says that the ID problem continues, is this normal?

Thanks

**Comment by s4relok** [comment]
> Hello everyone, I have sent a version of the app for review without calling UMP consent and Google says that the ID problem continues, is this normal?

I've tried the same apprach. And yep, still the update was rejected because of AD_ID. It seems that the request to **fundingchoicesmessages.google.com** happens even without calling it manually.

At this moment I made a radical move and disabled Google Ads in my game at all (switched to Unity Ads). And only after this the update was OK-d.

Now waiting for the new release of the plugin to try again.

**Comment by LambdaStudiosPH** [comment]
@pescador07  Has your update been approved, but the warning still appears like mine, or was your update completely rejected?

i also removed the code that calls the UMP consent dialogue i even forced all ads to be non-personalized but the warning is still present. Even tho this update has been approved and now live on google play the warning is still present which is weird

this yellow warning is still present on my policy tab on console. it says 20 days before my app will get removed.
![image](https://github.com/googleads/googleads-mobile-unity/assets/143337634/2fd94867-c65c-48ee-a069-d04abe1b647e)

**Comment by s4relok** [comment]
> this yellow warning is still present on my policy tab on console.

I also have the warning on my policy tab on console. Although I don't call the admob at all now.

**Comment by pescador07** [comment]
@LambdaStudiosPH 

The update has been approved, but the warning still appears.
I have 18 days left.

**Comment by batteredhedgehog** [comment]
@s4relok , @pescador07  - the only way to know for sure what data is being transmitted and whether you're still sending the adid  is to look yourself with an ssl proxy.  Use charles proxy.  It will take you maximum 1 hour to set it up and test.  
There are other ways to log https traffic - but using an ssl proxy is definitive.

**Comment by s4relok** [comment]
@pescador07, @LambdaStudiosPH

I contacted to Google Play to ask if I should do something else.

They answered: 

> I see the changes you've made to your app, which was resubmitted previously and has been approved.
> Please note that in some instances, **the warning may continue to be displayed after the review has been completed**.
> If you successfully resolved the issue, no further action is required and you do not need to contact us about this warning.

@batteredhedgehog 

Thank you for the advice. You're right. This warning pushes us into checking it manually. I'm going to try it now.

**Comment by LambdaStudiosPH** [comment]
@s4relok  @Ned11  @pescador07  
How is it going, everyone? Do any of you have any updates regarding this issue? Has anyone here reached the 30-day deadline in the policy center? What was the result? Was your app removed?  

I also messaged Google Support, and they also responded, saying, 'Sometimes the yellow warning may continue to be displayed.' However, I'm worried that when the deadline ends, my app will still be removed from Google Play.

**Comment by pcwings** [comment]
> @s4relok @Ned11 @pescador07 How is it going, everyone? Do any of you have any updates regarding this issue? Has anyone here reached the 30-day deadline in the policy center? What was the result? Was your app removed?
> 
> I also messaged Google Support, and they also responded, saying, 'Sometimes the yellow warning may continue to be displayed.' However, I'm worried that when the deadline ends, my app will still be removed from Google Play.

I find this insane. How is this a reply?? "You may or may not have your livelihood active in X days, you'll find out which then". How is that a valid reply? Forced to implement something, from Google, used Google's software that gets rejected, by Google and get a response from Google that's vague and rolling a dice with our livelihood? If someone reads this from Google, contact whoever you can and tell them to pick up their game, this really isn't good enough. This cluster needs unwinding.

**Comment by NVentimiglia** [comment]
Thanks for the feedback everyone. I understand this is frustrating. I will update this thread when 2.2.0 is released.

**Comment by pescador07** [comment]
Good morning, the same thing happens to me. Google support answers me "Sometimes the yellow warning may continue to be displayed.". I'm arguing with them because it doesn't seem acceptable to me, but they always answer me the same thing, that I should review the policies and blah blah blah... It seems incredible to me that the warning is displayed even though everything is fine, and they see it as normal.
Sorry for my English...

<img width="1088" alt="Captura de pantalla 2023-11-21 a las 9 13 18" src="https://github.com/googleads/googleads-mobile-unity/assets/36237969/1b390bef-7b18-4194-9537-7198dc1419c8">

**Comment by NVentimiglia** [comment]
@pescador07 

Thanks for the update. This issue will be fixed in the `2.2.0` release. We expect this to land shortly after the Thanksgiving holiday is complete.

**Comment by s4relok** [comment]
@pcwings @pescador07 @Ned11 @LambdaStudiosPH 

My waiting time is over. Tha warning still hangs, but now it shows "(overdue)" instead of "days left".

![screenshot 2023-11-25 090005](https://github.com/googleads/googleads-mobile-unity/assets/1317976/a9672374-2c7f-49a7-99e5-7e7df442c94a)

The app is not removed.

**Comment by protoDean** [comment]
Any updates on UMP 2.2.0?

**Comment by batteredhedgehog** [comment]
It's nearly January 14.  Is this likely to get fixed soon?

**Comment by ericleich** [comment]
The UMP Android 2.2.0 release is expected next week. iOS expected later this month. We've retested/verified Android 2.1.0 is not sending ad ID when [TagForUnderAgeOfConsent](https://developers.google.com/admob/unity/reference/class/google-mobile-ads/ump/api/consent-request-parameters#tagforunderageofconsent) is set on the parameters passed to [ConsentInformation.Update()](https://developers.google.com/admob/unity/reference/class/google-mobile-ads/ump/api/consent-information#update). So it's unclear some users are seeing Android app store rejections.

One workaround for Android to stop transmitting ad ID is to have your app target Android 13 and remove access to the [permission](https://support.google.com/googleplay/android-developer/answer/6048248?hl=en#) required to access ad ID. I would only recommend this to work around any play store rejections though, as this does have a side effect that consented users won't have an AD_ID set either.

```
<uses-permission android:name="com.google.android.gms.permission.AD_ID" tools:node="remove" />
```

**Comment by batteredhedgehog** [comment]
> The UMP Android 2.2.0 release is expected next week. iOS expected later this month.

Thanks @ericleich .

Will the 2.2.0 fix this issue so that we can use UMP without violating google play policy?

**Comment by ericleich** [comment]
@batteredhedgehog yes that’s correct, though I’ll reiterate that its still perplexing that 2.1.0 is getting rejected.

For those getting rejected, are your apps mixed audience or primarily directed towards children?

**Comment by LambdaStudiosPH** [comment]
@ericleich making the ad non-personalized and not showing the consent form fixed my issue. My app is still live to this day. The yellow policy warning on play console that ive showed months ago here also already disappeared. I think most of us only received the 30 days app removal policy yellow warning. But the warning disappears  after 1-2 months

**Comment by ericleich** [comment]
Thanks for the update @LambdaStudiosPH.

Returning here to acknowledge that the Android 2.2 release I mentioned above did not end up happening this week, but is targeted for next week.

**Comment by raft75** [comment]
I have the same issue.
Plugin v8.7.0 released yesterday is still using UMP 2.1.0, so it doesn't solve this, right?
@LambdaStudiosPH could you please share the code to make the ads non-personalized?

**Comment by ericleich** [comment]
UMP 2.2.0 was released today - https://developers.google.com/admob/android/privacy/release-notes.

You can include it by updating [GoogleMobileAdsDependencies.xml](https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml) to explicitly declare UMP as a dependency.

```
  <androidPackages>
    <androidPackage spec="com.google.android.gms:play-services-ads:22.6.0">
      <repositories>
        <repository>https://maven.google.com/</repository>
      </repositories>
    </androidPackage>
    <androidPackage spec="com.google.android.ump:user-messaging-platform:2.2.0">
      <repositories>
        <repository>https://maven.google.com/</repository>
      </repositories>
    </androidPackage>
  </androidPackages>
```

**Comment by 1993tht** [comment]
Does anyone know when a new version using UMP 2.2.0 will be released? Thanks.

**Comment by FelixUnico** [comment]
Updating to the version v8.7.0 and using the version UMP 2.2.0 has worked for me, it is very important to be approved to launch it 100%

**Comment by 1993tht** [comment]
Hi FelixUnico, 
Is it true that UMP 2.2.0 doesn't send AD_ID?
I don't know how to check whether my app sent or not.
Thanks.

**Comment by raft75** [comment]
@1993tht you can check AD_ID with Charles Proxy:
[](https://support.unity.com/hc/en-us/articles/115002917683-Using-Charles-Proxy-with-Unity)

**Comment by 1993tht** [comment]
Thank raft75.

Build for Android 5.0 and above when using plugin 8.7.0, there will be no error. Let's try it.

**Comment by FelixUnico** [comment]
> Hi FelixUnico, Is it true that UMP 2.2.0 doesn't send AD_ID? I don't know how to check whether my app sent or not. Thanks.

Yes, that's correct, I used Charles to check the requests and everything is correct, my kids game was approved.

**Comment by 1993tht** [comment]
Thanks FelixUnico,

Even though my app is approved, the warning is still displayed.
Like you said, it sounds like good news.
Have a good day.

**Comment by FelixUnico** [comment]
> Thanks FelixUnico,
> 
> Even though my app is approved, the warning is still displayed. Like you said, it sounds like good news. Have a good day.

I have had some games with these errors for months, and 15 emails saying "don't worry, it's a bug."

Have a nice day, too!!

**Comment by batteredhedgehog** [comment]
> UMP 2.2.0 was released today - https://developers.google.com/admob/android/privacy/release-notes.

Thanks @ericleich , @NVentimiglia 

Apologies that it took a while for me to get back to this.  I have tested and can verify that for me ad-id is no longer included in first consent request.

Feel free to close this case.
