### ISSUE TITLE
(UMP) Result of `ConsentInformation.PrivacyOptionsRequirementStatus` is swapped on iOS

### ISSUE THREAD

**Issue by marcelo-fanatee** [googleads/googleads-mobile-unity#3007]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.28f1
  * Google Mobile Ads Unity plugin version: 8.5.2, 8.5.3
  * Platform: iOS
  * Platform OS version: 16.6.1
  * Any specific devices issue occurs on: no
  * Mediation ad networks used, and their versions: none

#### Steps to reproduce:

Result of `ConsentInformation.PrivacyOptionsRequirementStatus` is swapped on iOS  

- initialize consent information
- use `ConsentForm.LoadAndShowConsentFormIfRequired`
  - IF consent form was Required and did appear `ConsentInformation.PrivacyOptionsRequirementStatus` will be NotRequired
  - IF consent form was NotRequired `ConsentInformation.PrivacyOptionsRequirementStatus` will be Required

I believe the issue is that the enum for privacy options requirement status are different in ios plugin code and cs code  
so value gets swapped when coming from native side

On android it works as expected

iOS plugin:
https://github.com/googleads/googleads-mobile-unity/blob/2934ba783fc9296affed109752f64a9f5c4f9069/source/plugin/Assets/Plugins/Ump/iOS/GADUConsentInformation.h#L32-L41

Unity cs:
https://github.com/googleads/googleads-mobile-unity/blob/2934ba783fc9296affed109752f64a9f5c4f9069/source/plugin/Assets/GoogleMobileAds/Ump/Api/PrivacyOptionsRequirementStatus.cs#L20-L36

**Comment by ericleich** [comment]
Thanks for the report and good catch. https://github.com/googleads/googleads-mobile-unity/pull/3010 will be merged into the next release.
