### ISSUE TITLE
CommandInvokationFailure: Failed to re-package resources Library/Android/sdk/build-tools/23.0.3/aapt

### ISSUE THREAD

**Issue by Evsun** [googleads/googleads-mobile-unity#301]
I still having this issue until now, i have use the latest version of googleAdsPlugin and still getting this error.
I don't know what step i miss but i follow the documentation exactly but this what i got..

CommandInvokationFailure: Failed to re-package resources.
/Users/everjnewtron/Library/Android/sdk/build-tools/23.0.3/aapt package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "/Users/everjnewtron/Library/Android/sdk/platforms/android-23/android.jar" -F bin/resources.ap_ --extra-packages com.google.unity:com.voxelbusters.utility:com.voxelbusters.androidnativeplugin:android.support.v4:com.voxelbusters.utility -S "/Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res" -S "/Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/support-v4-23.4.0/res"

stderr[
/Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable/app_icon_custom_white.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/layout/np_webview_layout.xml:13: note: removing attribute http://schemas.android.com/apk/res/android:showDividers from <LinearLayout>
/Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/layout/np_webview_layout.xml: note: using v11 attributes; synthesizing resource com.gookindonesia.mathpuzzleevolution:layout/np_webview_layout for configuration v11.
AndroidManifest.xml:16: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.IAPTheme').

AndroidManifest.xml:18: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: /Users/everjnewtron/Library/Android/sdk/platforms/android-23/android.jar
applyFileOverlay for drawable
trying overlaySet Key=app_icon_custom_coloured.png
trying overlaySet Key=app_icon_custom_white.png
trying overlaySet Key=ic_launcher.png
trying overlaySet Key=np_webview_back_button_normal.png
trying overlaySet Key=np_webview_close_button_normal.png
trying overlaySet Key=np_webview_forward_button_normal.png
trying overlaySet Key=np_webview_reload_button_normal.png
trying overlaySet Key=app_banner.png
trying overlaySet Key=app_icon.png
applyFileOverlay for layout
trying overlaySet Key=np_progressbar_layout.xml
trying overlaySet Key=np_webview_layout.xml
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
trying overlaySet Key=nativeplugins_file_paths.xml
applyFileOverlay for raw
trying overlaySet Key=nativeplugins.png
applyFileOverlay for color
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: res/drawable-xhdpi/app_banner.png
Processing image: res/drawable/app_icon.png
Processing image: /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable/app_icon_custom_coloured.png
Processing image: /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable/app_icon_custom_white.png
    (processed image res/drawable/app_icon.png: 94% size of source)
Processing image: /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable-mdpi/ic_launcher.png
    (processed image /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable-mdpi/ic_launcher.png: 96% size of source)
Processing image: /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable-hdpi/ic_launcher.png
    (processed image res/drawable-xhdpi/app_banner.png: 93% size of source)
Processing image: /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable-xhdpi/ic_launcher.png
    (processed image /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable-hdpi/ic_launcher.png: 97% size of source)
Processing image: /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable/np_webview_back_button_normal.png
    (processed image /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable/np_webview_back_button_normal.png: 45% size of source)
Processing image: /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable/np_webview_close_button_normal.png
    (processed image /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable/np_webview_close_button_normal.png: 91% size of source)
Processing image: /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable/np_webview_forward_button_normal.png
    (processed image /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable/np_webview_forward_button_normal.png: 88% size of source)
Processing image: /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable/np_webview_reload_button_normal.png
    (processed image /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable-xhdpi/ic_launcher.png: 97% size of source)
    (processed image /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable/app_icon_custom_coloured.png: 85% size of source)
    (processed image /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable/np_webview_reload_button_normal.png: 115% size of source)
    (processed image /Users/everjnewtron/Documents/Android/Unity/MP Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/drawable/app_icon_custom_white.png: 80% size of source)
    (new resource id app_banner from xhdpi-v4/drawable/app_banner.png #generated)
    (new resource id app_icon from drawable/app_icon.png #generated)
    (new resource id app_icon_custom_coloured from drawable/app_icon_custom_coloured.png #generated)
    (new resource id app_icon_custom_white from drawable/app_icon_custom_white.png #generated)
    (new resource id ic_launcher from mdpi-v4/drawable/ic_launcher.png #generated)
    (new resource id ic_launcher from hdpi-v4/drawable/ic_launcher.png #generated)
    (new resource id ic_launcher from xhdpi-v4/drawable/ic_launcher.png #generated)
    (new resource id np_webview_back_button_normal from drawable/np_webview_back_button_normal.png #generated)
    (new resource id np_webview_close_button_normal from drawable/np_webview_close_button_normal.png #generated)
    (new resource id np_webview_forward_button_normal from drawable/np_webview_forward_button_normal.png #generated)
    (new resource id np_webview_reload_button_normal from drawable/np_webview_reload_button_normal.png #generated)
    (new resource id np_progressbar_layout from /Users/everjnewtron/Documents/Android/Unity/MP Fuck Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/layout/np_progressbar_layout.xml)
    (new resource id np_webview_layout from /Users/everjnewtron/Documents/Android/Unity/MP Fuck Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/layout/np_webview_layout.xml)
    (new resource id nativeplugins_file_paths from /Users/everjnewtron/Documents/Android/Unity/MP Fuck Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/xml/nativeplugins_file_paths.xml)
    (new resource id nativeplugins from /Users/everjnewtron/Documents/Android/Unity/MP Fuck Baru/Temp/StagingArea/android-libraries/native_plugins_lib/res/raw/nativeplugins.png)
]
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.PostProcessor.Tasks.TasksCommon.Exec (System.String command, System.String args, System.String workingdir, System.String errorMsg, Int32 retiresOnFailure)
UnityEditor.HostView:OnGUI()

Please help me with this error.. i've stuck here for 3 days :(

**Comment by rampara** [comment]
Can you post the contents of the `Assets/Plugins/Android` directory of your Unity project?

**Comment by Evsun** [comment]
It just contain this http://tinypic.com/r/wmhtue/9

I am also using Cross Platform Native Plugins – Lite Version from Voxell.
When i run the project without GoogleAds plugin, it can compile but when i add the GoogleAds plugin, it just give me the error above

**Comment by rampara** [comment]
It looks like the Play Services Resolver didn't copy the required dependencies into your project. Do you see any output in the Unity console that may indicate why this didn't happen? Can you try manually running dependency resolution by selecting `Assets->Play Services Resolver->Android Resolver->Resolve Client Jars`. The `Assets/Plugins/Android` should then contain the required Google Play services dependencies.

**Comment by Evsun** [comment]
There's no Android folder inside my Play Service Resolver folder, it just contain folder named Editor. This is what it look : http://tinypic.com/r/fliu1e/9..
Is there something i miss?

**Comment by rampara** [comment]
`Assets->Play Services Resolver->Android Resolver->Resolve Client Jars ` is a menu option in the Unity editor.

**Comment by rampara** [comment]
It also looks like you're using an older version of the plugin. Can you remove all files associated with the Google Mobile Ads Unity plugin and re-import the latest version of the plugin.

**Comment by Evsun** [comment]
okkay i have try it but i just got a message "Resolver not enabled. Android platform must be selected.".. what android platform that i need to select? I have select the android platform in build settings..

**Comment by Evsun** [comment]
I have try to use the newest plugin with new project but still it didn't works

**Comment by Evsun** [comment]
Okay i have do that and solve the problem above but now comes a new problem, when i compile i got error on my console that said "Assets/PlayServicesResolver/Editor/IResolver.cs(74,27): error CS0433: The imported type `Google.JarResolver.PlayServicesSupport' is defined multiple times" how to solve this?

**Comment by Evsun** [comment]
Okay i can solve that problem, it because the plugin from Voxxel i used is need to be upgrade. Thanks..

**Comment by rampara** [comment]
Glad you were able to get everything working.
