### ISSUE TITLE
Request: Test ads in editor

### ISSUE THREAD

**Issue by kiberzauras** [googleads/googleads-mobile-unity#302]
I want to request that there would be test ads placeholders available in unity editor too. Now we must make builds and open it in our devices which takes a lot of time when trying to test tiny changes.

**Comment by rampara** [comment]
The Google Mobile Ads SDK is required to request and display ads (even test ads). Since the GMA SDK is only available on the Android and iOS platforms, there would be no way to receive test ads in the Unity Editor.
