### ISSUE TITLE
Can't add comments to this repo?

### ISSUE THREAD

**Issue by oliverbenns** [googleads/googleads-mobile-unity#303]
I wanted to comment on 2 issues to help resolve problems for others, and also reply to my own issue, but I can't. Why is that? I've only created 1 issue so not sure why I'm restricted? This has been ongoing for 3/4 weeks.

![screen shot 2016-11-10 at 22 02 56](https://cloud.githubusercontent.com/assets/1992355/20196181/749c9e16-a791-11e6-8ca1-26c063a48fa8.png)

**Comment by rampara** [comment]
Not sure why you're experiencing this issue but there are no restrictions set on commenting on issues within this repository. Closing issue as it's not a issue pertaining to the plugin.
