### ISSUE TITLE
With normal internal logic, after watching the motivational advertisement, the game itself loses all sound

### ISSUE THREAD

**Issue by mingxtInGitHub** [googleads/googleads-mobile-unity#3031]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: Unity2020.3.48
  * Google Mobile Ads Unity plugin version: 8.5.3
  * Platform: IOS/Android (iOS, Android, Unity Editor)
  * Platform OS version: This issue exists in various versions, even newer versions

#### Steps to reproduce:

Our game only incorporates motivational advertisements, and after watching the advertisements, the entire sound of the game disappears. This problem does not necessarily occur, it has randomness.

We are certain that this is not related to our internal logic. This issue has been ongoing for a long time, not only in this version of AdMobSDK, but also in previous versions. Moreover, the device and IOS or Android versions where this issue occurs are not specific, making it difficult to find the pattern of this issue occurring.

In a recent IOS test, we encountered this issue again without changing the advertising logic, and every time we watched an advertisement, it would inevitably cause the entire game to lose sound. However, the advertisement itself had sound, and this issue was only resolved after we tried restarting the phone, and it was strange that this issue never occurred again.

Its specific triggering time is when after watching the advertisement and clicking the close advertisement button in the upper right corner, we also caught an error on XCode:
>Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>

>0x130084480 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'WebProcess NearSuspended Assertion' for process with PID=63,772, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}

It's not just iOS that has this issue, we've also encountered it on Android and other iOS devices before, but because it can't surface, we find it difficult to catch its errors.

**Comment by NVentimiglia** [comment]
@mingxtInGitHub 

We have had other publishers raise sound related issues. These issues are pretty hard to nail down and I would love to solve this.

1. Do you have a charles log which can identify the bad creative ?
2. Can you replicate this issue with regularity (and modify the sample to demonstrate this?) ?

If you can, please make a [bug submission](https://developers.google.com/admob/unity/support) and I can take a look.
