### ISSUE TITLE
(UMP)If you enable all options in Manage options and click the Confirm choices button, the advertisement will not be loaded. 

### ISSUE THREAD

**Issue by jeffyuio1129** [googleads/googleads-mobile-unity#3035]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.10f1
  * Google Mobile Ads Unity plugin version: 8.6.0
  * Platform: iOS, Android
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem

If you enable all options in Manage options and click the Confirm choices button, the advertisement will not be loaded. 

It seems that the advertisement does not load when using the Confirm choices button regardless of option selection. Can you tell me how to solve this problem?

![Screenshot_20231122_113501_Jewel_Gold_Empire 1](https://github.com/googleads/googleads-mobile-unity/assets/25237638/a972e9ad-af65-43a8-811f-d092c90536a0)
![Screenshot_20231122_113440_Jewel_Gold_Empire 1](https://github.com/googleads/googleads-mobile-unity/assets/25237638/974f0f5c-fcab-4b7e-8d1a-683188860424)

**Comment by NVentimiglia** [comment]
@jeffyuio1129 

Confirmed, I ran into this issue on The Java Banner Example.

**Comment by NVentimiglia** [comment]
@jeffyuio1129 

The reason you aren't seeing any ads,is that in addition to providing purposes consent (the first screen that you see when clicking "Manage Options") you also need to provide vendor consent (scroll to bottom of purposes page -> click "Vendor preferences"). Both purposes consent and vendor consent are required for any vendor (in our case, Google) to work properly/show ads.

That said, I also raised concern that this second vendor preferences page was confusing and have the UX people looking into making this more clear.
