### ISSUE TITLE
Build fails Unity 2022.1.7f1 / Could not load compiled classes for settings file

### ISSUE THREAD

**Issue by SamTyurenkov** [googleads/googleads-mobile-unity#3039]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.7f1
  * Google Mobile Ads Unity plugin version: 8.6.0
  * Platform: Unity Editor
  * Platform OS version: Windows 11
  * Any specific devices issue occurs on: -
  * Mediation ad networks used, and their versions: Unity Ads Mediation Adapter v3.8.0

#### Steps to reproduce:

0) I had an old version of Google Mobile Ads without mediation, which was working correctly in production (showing ads). I wanted to update and also add mediation feature.
1) I followed guides and added Google Mobile Ads plugin latest version (8.6.0) and Unity Ads mediation adapter (3.8.0) both latest at the current moment.
2) In Unity Editor I added my App Id, and resolved dependencies with EDM. 
3) In Google Mobile Ads Asset I toggled the recommended checkboxes on. 
4) In build settings I enabled all custom gradle templates (they were enabled since my previous working version of Google Mobile Ads)
5) I target automatic highestly installed API (34)

Trying to build fails with error:
```
Starting a Gradle Daemon, 1 incompatible and 2 stopped Daemons could not be reused, use --status for details
FAILURE: Build failed with an exception.

* What went wrong:
Could not load compiled classes for settings file 'E:\UNITY3D\Tanks2020-alpha\Tanks2020\Library\Bee\Android\Prj\IL2CPP\Gradle\settings.gradle' from cache.
> settings_dz1zcyl9jumc6xcdfchs43lvp
```

If I change the branch back to master of my project - I can correctly build, targeting API 34. 
With custom gradle templates and EDM resolved dependencies from older version. 
So the problem only occurs after installation of latest version.

![image](https://github.com/googleads/googleads-mobile-unity/assets/19373777/8d145bc2-0a37-45a7-a57f-fd7939caef04)

I can share private project repository on github, but I will need your email.

#### Relevant Code:

I didnt change much codewise, there were some method updates in the Interface between game logic and ads initialization, but they are not related to the current problem.

**Comment by NVentimiglia** [comment]
@SamTyurenkov 

I am not seeing this issue. The issue is probably with your Java or gradle configuration.

- Try upgrading to Unity 2022.3 which uses a newer gradle and Java.
- Try [Using a custom gradle install](https://developers.google.com/admob/unity/gradle)

Lastly I once experienced a caching issue on Mac where it could not find the correct Java install. I solved this by toggling the Android Settings (Disabling and then Enabling them).

![image](https://github.com/googleads/googleads-mobile-unity/assets/125889/e6cb6970-43d1-4869-80c2-8ca75fd93669)

**Comment by SamTyurenkov** [comment]
@NVentimiglia somehow the problem is gone, I guess I randomly did something that you mentioned or something else. 

Besides what you mentioned with cache, I did an all assets reimport and manually deleted some folders in Library (not only cache i think). 

Also Unity didnt prompt to update JDK, I had to manually trigger it or copy from android studio, not sure.
