### ISSUE TITLE
can't even start unity after importing

### ISSUE THREAD

**Issue by Achyut-Sagar** [googleads/googleads-mobile-unity#304]
Hi, I just imported the package. and this error dialog appears.
![screen shot 2016-11-11 at 11 11 36 am](https://cloud.githubusercontent.com/assets/4437304/20205535/afbe3de2-a7ff-11e6-9028-da942f7c2d97.png)

on quitting and restarting unity, same dialog appears. I can't go further.

**Comment by rampara** [comment]
Are you using the latest version of the plugin? What version of Unity are you using?

**Comment by Achyut-Sagar** [comment]
Yes, Plugin's latest. and I'm using Unity v5.2.0f3.

**Comment by rampara** [comment]
Can you try updating to the latest version of Unity and seeing if this issue persists.

**Comment by Achyut-Sagar** [comment]
I'll update Unity, but that'll take a while. Any other quick work around?

**Comment by rampara** [comment]
Don't think there is another workaround. This looks like a [PlayServicesResolver](https://github.com/googlesamples/unity-jar-resolver) issue that was resolved when using a newer version of Unity.

**Comment by Achyut-Sagar** [comment]
Upgrading Unity resolved this issue. Thanks.
