### ISSUE TITLE
"MediationExtras" definition Editor compilation conflicts between several adapters

### ISSUE THREAD

**Issue by MayisGM** [googleads/googleads-mobile-unity#3041]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.41
  * Google Mobile Ads Unity plugin version: 8.6.0
  * Platform: Unity Editor
  * Platform OS version: N/A
  * Any specific devices issue occurs on: N/A
  * Mediation ad networks used, and their versions: AdColonyUnityAdapter-2.6.2, AppLovinUnityAdapter-6.9.1, LiftoffMonetizeUnityAdapter-4.0.0, MetaAudienceNetworkUnityAdapter-3.11.0, UnityAdsUnityAdapter-3.8.0

### [REQUIRED] Step 2: Describe the problem

After importing Google Mobile Ads Unity plugin latest version and mediation adapters described above, Unity Editor can't compile scripts. Please find all errors in the Editor console below:

### Error 1
```
Assets\GoogleMobileAds\Mediation\LiftoffMonetize\Api\MediationExtras.cs(24,27): error CS0101: The namespace 'GoogleMobileAds.Api.Mediation' already contains a definition for 'MediationExtras'
```
### Error 2
```
Assets\GoogleMobileAds\Mediation\AdColony\Api\AdColony\AdColonyMediationExtras.cs(21,18): error CS0534: 'AdColonyMediationExtras' does not implement inherited abstract member 'MediationExtras.AndroidMediationExtraBuilderClassName.get'
```

### Error 3
```
Assets\GoogleMobileAds\Mediation\AdColony\Api\AdColony\AdColonyMediationExtras.cs(21,18): error CS0534: 'AdColonyMediationExtras' does not implement inherited abstract member 'MediationExtras.IOSMediationExtraBuilderClassName.get'
```

### Error 4
```
Assets\GoogleMobileAds\Mediation\LiftoffMonetize\Api\LiftoffMonetizeInterstitialMediationExtras.cs(20,18): error CS0534: 'LiftoffMonetizeInterstitialMediationExtras' does not implement inherited abstract member 'MediationExtras.AndroidMediationExtraBuilderClassName.get'
```

### Error 5
```
Assets\GoogleMobileAds\Mediation\LiftoffMonetize\Api\LiftoffMonetizeInterstitialMediationExtras.cs(20,18): error CS0534: 'LiftoffMonetizeInterstitialMediationExtras' does not implement inherited abstract member 'MediationExtras.IOSMediationExtraBuilderClassName.get'
```

### Error 6
```
Assets\GoogleMobileAds\Mediation\LiftoffMonetize\Api\LiftoffMonetizeRewardedVideoMediationExtras.cs(20,18): error CS0534: 'LiftoffMonetizeRewardedVideoMediationExtras' does not implement inherited abstract member 'MediationExtras.AndroidMediationExtraBuilderClassName.get'
```

### Error 7
```
Assets\GoogleMobileAds\Mediation\LiftoffMonetize\Api\LiftoffMonetizeRewardedVideoMediationExtras.cs(20,18): error CS0534: 'LiftoffMonetizeRewardedVideoMediationExtras' does not implement inherited abstract member 'MediationExtras.IOSMediationExtraBuilderClassName.get'
```

### Error 8
```
Assets\GoogleMobileAds\Mediation\LiftoffMonetize\Api\MediationExtras.cs(31,16): error CS0111: Type 'MediationExtras' already defines a member called '.ctor' with the same parameter types
```

As you can see mostly conflicts are between AdColony and Liftoff adapters.

Is there a way temporarily fix these issues, or maybe some older versions of these adapters are compatible with Google Mobile Ads Unity plugin 8.6.0 version, so I can downgrade adapters?

I see there is a log in Liftoff Monetize Unity Mediation Plugin Changelog which says:
[Next Version] Fixed a duplicate definition warning for MediationExtras.

Any ETA about the next version release?

**Comment by NVentimiglia** [comment]
@MayisGM 

I can confirm the issue. We have a fix in the works.

**Comment by bilalahadtech** [comment]
i am also facing such issues,
using admob and unity mediation latest versions in 2021.3.30 
test ads works fine but only admob not the unity, if we select unity testing then unity ads shown upto some extend

actual issue is, with live ads ids it didn't shown any ads and game stucks on splash

i'm new on it......when i import unity advertisement from package manager it shows error on build for duplicate calss of unity ads...how to fix?

**Comment by NVentimiglia** [comment]
> i am also facing such issues, using admob and unity mediation latest versions in 2021.3.30 test ads works fine but only admob not the unity, if we select unity testing then unity ads shown upto some extend
> 
> actual issue is, with live ads ids it didn't shown any ads and game stucks on splash
> 
> i'm new on it......when i import unity advertisement from package manager it shows error on build for duplicate calss of unity ads...how to fix?

This sounds like a different issue. The issue in the original post is an edit time error which prevents the build from even running. Your issue is runtime.

Runtime issues (especially dealing with mediaiton) are somewhat outside the scope of the plugin and need support from the Google Mobile Ads Team. Can you open a [support case](https://developers.google.com/admob/unity/support). They will want to know the affected ad unit ids, platform, and a [charles log or network trace](https://developers.google.com/admob/android/network-tracing) will also be helpful.
