### ISSUE TITLE
ShowPrivacyOptionsForm

### ISSUE THREAD

**Issue by beaaxxx** [googleads/googleads-mobile-unity#3047]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.13
  * Google Mobile Ads Unity plugin version: 8.6.0
  * Platform: Android

#### Steps to reproduce:

I have a question about displaying again GDPR message when user clicks "privacy options button" in settings.
In docs and sample project "hello world" is used **ConsentForm.LoadAndShowConsentFormIfRequired** same method when the message is displayed for the first time.

        /// <summary>
        /// Shows the privacy options form to the user.
        /// </summary>
        /// <remarks>
        /// Your app needs to allow the user to change their consent status at any time.
        /// Load another form and store it to allow the user to change their consent status
        /// </remarks>
        public void ShowPrivacyOptionsForm(Action<string> onComplete)
        {
            Debug.Log("Showing privacy options form.");

            // combine the callback with an error popup handler.
            onComplete = (onComplete == null)
                ? UpdateErrorPopup
                : onComplete + UpdateErrorPopup;

            ConsentForm.LoadAndShowConsentFormIfRequired((FormError showError) =>
            {
                UpdatePrivacyButton();
                if (showError != null)
                {
                    // Form showing failed.
                    if (onComplete != null)
                    {
                        onComplete(showError.Message);
                    }
                }
                // Form showing succeeded.
                else if (onComplete != null)
                {
                    onComplete(null);
                }
            });
        }

        

But when I using this method **ConsentForm.LoadAndShowConsentFormIfRequired**, the form is not displayed. Maybe I'm doing something wrong that it doesn't show up again.
Instead if I use method **ConsentForm.showPrivacyOptionsForm** message displays after clicking manually the button "privacy buttons". 

        ConsentForm.ShowPrivacyOptionsForm((FormError showError) =>
        {
            UpdatePrivacyButton();
            if (showError != null)
            {
                // Form showing failed.
                if (onComplete != null)
                {
                    onComplete(showError.Message);
                }
            }
            // Form showing succeeded.
            else if (onComplete != null)
            {
                onComplete(null);
            }
        });
        
What's the difference between this methods? Can I use this method ConsentForm.showPrivacyOptionsForm in this case?

**Comment by ChaserKnight** [comment]
I am also facing the same issue. Calling "ConsentForm.LoadAndShowConsentFormIfRequired" from the "Privacy Options" button does not display the form, but "ConsentForm.ShowPrivacyOptionsForm" does display it. Which method should we use?

**Comment by NVentimiglia** [comment]
Hi,

I have confirmed this issue and will push for a fix.

For a workaround, this should work.

```
        public void ShowPrivacyOptionsForm(Action<string> onComplete)
        {
            Debug.Log("Showing privacy options form.");

            // combine the callback with an error popup handler.
            onComplete = (onComplete == null)
                ? UpdateErrorPopup
                : onComplete + UpdateErrorPopup;

            ConsentForm.Load((ConsentForm form, FormError showError) =>
            {
                if(form != null)
                {
                    form.Show((FormError error2) =>
                    {
                        if (onComplete != null)
                        {
                            onComplete(showError.Message);
                        }
                    });
                }
                else
                {
                    if (onComplete != null)
                    {
                        onComplete(showError.Message);
                    }
                }
                UpdatePrivacyButton();
            });
        }
```

**Comment by NVentimiglia** [comment]
This is now fixed, please pull the latest version of the sample.
