### ISSUE TITLE
AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.ump.UserMessagingPlatform

### ISSUE THREAD

**Issue by pedromgdo** [googleads/googleads-mobile-unity#3049]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.31f
  * Google Mobile Ads Unity plugin version: 8.5.3
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: Android 13 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: No
  * Mediation ad networks used, and their versions: No mediation, only Admob

#### Steps to reproduce:

- Call ConsentInformation.Update()
- AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.ump.UserMessagingPlatform

#### Relevant Code:

```
        ConsentRequestParameters consentParams = new ConsentRequestParameters()
        {
            TagForUnderAgeOfConsent = false,
        };
        ConsentInformation.Update(consentParams,OnConsentInfoUpdated);
```

#### Notes

I am using proguard, but even with custom rules it still gives this error.

**Comment by pedromgdo** [comment]
Fixed it by adding the following to the proguard file:
`
-keep public class com.google.android.ump.**{
   public *;
}

-keep public class com.google.android.gms.ads.**{
   public *;
}`
This should either be documented or treated as a bug.

**Comment by NVentimiglia** [comment]
Glad you got things working.

Closing this issue as we have a work around and this is really a Android deployment issue.
