### ISSUE TITLE
Erro after building, what to do?

### ISSUE THREAD

**Issue by istolenhit** [googleads/googleads-mobile-unity#305]
FileNotFoundException: Could not load file or assembly 'UnityEditor.iOS.Extensions.Xcode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Google.IOSResolver..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Google.IOSResolver
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

**Comment by rampara** [comment]
Did you encounter this error while attempting to build an iOS project on the Windows platform?

**Comment by rampara** [comment]
Closing this issue due to non-response. Please re-open if this issue persists for you.
