### ISSUE TITLE
UnityConsentFormCallback class not found exception

### ISSUE THREAD

**Issue by devjh4** [googleads/googleads-mobile-unity#3053]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.14f1 lts
  * Google Mobile Ads Unity plugin version: 8.6.0
  * Platform: Android
  * Platform OS version: Android 13
  * Any specific devices issue occurs on:
  * Mediation ad networks used, and their versions:

### [REQUIRED] Step 2: Describe the problem

We try to use UMP in GoogleMobileAds but it's not work.
We try to debug function and use our device hash id, but it make just error.

```
Code
var debugSettings = new ConsentDebugSettings
{
    // Geography appears as in EEA for debug devices.
    DebugGeography = DebugGeography.EEA,
    TestDeviceHashedIds = new List<string>
    {
        "device_hash_id"
    }
};

ConsentRequestParameters request = new ConsentRequestParameters
{
    TagForUnderAgeOfConsent = false,
    ConsentDebugSettings = debugSettings
};

// Check the current consent information status.
ConsentInformation.Update(request, OnConsentInfoUpdated);

Log cat error

AndroidJavaException: java.lang.ClassNotFoundException: com.google.unity.ump.UnityConsentFormCallback
java.lang.ClassNotFoundException: com.google.unity.ump.UnityConsentFormCallback
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:454)
at com.unity3d.player.ReflectionHelper.nativeProxyInvoke(Native Method)
at com.unity3d.player.ReflectionHelper.-$$Nest$smnativeProxyInvoke(Unknown Source:0)
at com.unity3d.player.ReflectionHelper$a.invoke(Unknown Source:29)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy17.onConsentInfoUpdateSuccess(Unknown Source)
at com.google.android.gms.internal.consent_sdk.zzt.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8762)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.interna
```

**Comment by NVentimiglia** [comment]
@devjh4 

The happens from failure to resolve and include the android arr files as a dependency. Can you verify that these dependencies are included in the Android Studio project?

**Comment by devjh4** [comment]
> @devjh4
> 
> The happens from failure to resolve and include the android arr files as a dependency. Can you verify that these dependencies are included in the Android Studio project?

https://developers.google.com/admob/unity/quick-start?hl=en

I worked according to this guide.
Did Force resolve, it worked well and also build succeed but log cat show that error.

**Comment by devjh4** [comment]
@NVentimiglia 

https://developers.google.com/admob/unity/quick-start?hl=en

I worked according to this guide.
Did Force resolve, it worked well and also build succeed but log cat show that error.

**Comment by NVentimiglia** [comment]
@devjh4 

I attempted to replicate this on Unity Editor 2021 on Android and I did not see this error. This leads me to believe that one of us is missing a step. Can you verify that the APK includes the `com.google.unity.ump` dependency?

**Comment by devjh4** [comment]
@NVentimiglia 

Thank you for your answer.
I checked the dependencies and everything was normal.

I suspected the cache, so I deleted all files in the Unity project library folder and then proceeded with the build, so there was no problem. 

Thank you for your help.
