### ISSUE TITLE
Mediation adapters API explanation needed

### ISSUE THREAD

**Issue by MayisGM** [googleads/googleads-mobile-unity#3054]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: Any
  * Google Mobile Ads Unity plugin version: 8.6.0
  * Platform: Any (iOS, Android, Unity Editor)
  * Platform OS version: Any (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: All
  * Mediation ad networks used, and their versions: AppLovin, Liftoff Monetize, Unity Ads

### [REQUIRED] Step 2: Describe the problem

We are currently integrating Google-certified CMP to our project to collect user consent for ad serving. We have a few important questions regarding this:

Question 1) Will Google Mobile Ads Unity plugin automatically retrieve TC String during initialization and pass the user ad preferences to other partner mediation networks while requesting ads?

In some mediation partner adapters integration guide we can see requirements to pass user consent flag, like this: 

```
//AppLovin adapter guide
AppLovin.SetHasUserConsent(true);

//Liftoff Monetize adapter guide
LiftoffMonetize.UpdateConsentStatus(VungleConsentStatus.OPTED_IN, "1.0.0"); //for Android platform

LiftoffMonetize.SetGDPRStatus(true); //for iOS platform
LiftoffMonetize.SetGDPRMessageVersion("1.0.0"); //for iOS platform

//Unity Ads
UnityAds.SetConsentMetaData("gdpr.consent", true);
```

Question 2) If the answer to the question 1 is Yes, then do we need still pass this consent flag to mediation adapters described above?

Question 3) If we anyway need to pass consent flag to mediation adapters manually, then how can we do this? How can we retrieve user consent as one Boolean flag?

**Comment by NVentimiglia** [comment]
@MayisGM 

No, the UMP SDK does not communicate with any other third parties. These third parties should read the TCF string themselves as defined in [the spec](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md).

For specifics and implementations instructions for other ad networks, please consult the development guide published by those networks.

**Comment by MayisGM** [comment]
> @MayisGM
> 
> No, the UMP SDK does not communicate with any other third parties. These third parties should read the TCF string themselves as defined in [the spec](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md).
> 
> For specifics and implementation instructions for other ad networks, please consult the development guide published by those networks.

Ok. As there is still unclear things, so let me reformulate the question.  We use Applovin through the admob mediation in two ways. 1. Real time  bidding 2. Waterfall.  There is Applovin admob adapter plugin. Can you please explain me how the plugin will read the TC string (or should it read the TC string normally).

**Comment by NVentimiglia** [comment]
@MayisGM 

The adapter will not read the TCF string and is not responsible for consent management. The SDKs (Admob / AppLovin) are responsible for reading the TCF strings.

As far as reading the TCF string goes, I can speak that Admob implements the TCF spec, however I can not speak for AppLovin or guarantee that they have implemented the TCF string correctly. That said, we have exposed the AppLovin APIs so that you can implement their protocol.

**Comment by Inspyro** [comment]
@NVentimiglia 
Can you ask your mediation partners such as AppLovin how this will be handled. We know that AppLovin officially supports Google UMP through their SDK, but as far as we are aware it is unsupported when integrated via mediation - thus not complying to EU regulations.

We would assume that Google Admob automatically enforces TCF Strings for their Mediation partners and removes all outdated API calls such as `SetGDPRStatus` etc

**Comment by NVentimiglia** [comment]
@Inspyro 

Will do, let me forward this thread to the mediation expert to see if there is anything more we can do.

**Comment by zenith-jacob** [comment]
Any news?

**Comment by NVentimiglia** [comment]
Hi @zenith-jacob 

We check that ad technology providers and other programmatic demand sources don’t violate Google policy and have at least one legal basis for processing data prior to including them in the mediation waterfall.

[Changes for Additional Consent v2](https://support.google.com/admob/answer/9681920#update) include an update to support vendors disclosed in the CMP to support vendors disclosed in the CMP. Disclosed vendors are eligible to participate in the mediation waterfall.
