### ISSUE TITLE
Admob Events And Callbacks Issue With Unity Main Thread

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#3061]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.23f1
  * Google Mobile Ads Unity plugin version: 8.0.0 to 8.6.0
  * Platform: iOS, Android

### [REQUIRED] Step 2: Describe the problem
I need guidance regarding "Admob Events And Callbacks Issue's With Unity Main Thread". As @NVentimiglia  mentioned in previous resolved issue https://github.com/googleads/googleads-mobile-unity/issues/2854#issuecomment-1672202297 , that "Google mobile ads is not thread safe and does not always return events and callbacks on the unity main thread". Which in a result got untraced crashes and ANR's ( most untraced crashes are like SIGSEGC Libunity.so etc.)
So what is safer approach we do when handling our code/logic in Admob events and callback? other than MobileAds.RaiseAdEventsOnUnityMainThread = true; solution.
What we do if we can't touch unity engine objects or how we can safely touch unity engine objects in Admob events and callback

**Comment by MuhammadWaqasOfficial** [comment]
![What_Is_This](https://github.com/googleads/googleads-mobile-unity/assets/32755091/57dd7cc6-1f63-4c85-a46f-0183fa31765b)
Also can someone explain what's happening in this step? Ignore if not related to admob.
Thanks

**Comment by NVentimiglia** [comment]
@MuhammadWaqasOfficial 

RaiseAdEventsOnUnityMainThread is a an runtime API which wraps calls and events in a synchronization context. The picture you are showing is unrelated and looks specific to building / gradle.

**Comment by MuhammadWaqasOfficial** [comment]
@NVentimiglia yes picture was not related and removed.
Need help for issue explains above https://github.com/googleads/googleads-mobile-unity/issues/3061#issue-2037316534

**Comment by NVentimiglia** [comment]
> @NVentimiglia yes picture was not related and removed. Need help for issue explains above [#3061 (comment)](https://github.com/googleads/googleads-mobile-unity/issues/3061#issue-2037316534)

1. Use RaiseAdEventsOnUnityMainThread
2. Roll your own RaiseAdEventsOnUnityMainThread using a [SyncronizationContext](https://learn.microsoft.com/en-us/dotnet/api/system.threading.synchronizationcontext?view=net-8.0)
3. Roll your own queue based event dispatcher using an Update loop. e.g.


```
bool hasUpdate;
void OnAdmobEvent()
{
    hasUpdate = true;
}

void Update()
{
    if (hasUpdate)
    {
        // Modify UnityEngineObjects here.
    }
    hasUpdate = false;
}
```
