### ISSUE TITLE
FPS drops after Rewarded Ad loading

### ISSUE THREAD

**Issue by T-1K** [googleads/googleads-mobile-unity#3065]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.32f1
  * Google Mobile Ads Unity plugin version: 8.1.0
  * Platform: Android
  * Platform OS version: Android 10
  * Any specific devices issue occurs on: Xiaomi Redmi 9C
  * Mediation ad networks used, and their versions: -

#### Steps to reproduce:

As suggested, we cache Reward Ad way before showing it. FPS drops during ad loading process slighlty (which is understandable) but it drops again after the load finishes and **stays that level**. Destroying rewarded ad object does not have any effect on FPS, only showing the ad fixes FPS. According to Unity Profiler, most increase happens on Rendering after the load.
We only observe this behaviour on this specific test device.

#### Relevant Code:

**Comment by T-1K** [comment]
Here is the top markers by Abs Diff from the Unity Profiler. Left (blue) is before loading, Right (orange) is after.
![image](https://github.com/googleads/googleads-mobile-unity/assets/90188408/91b3276a-ff5b-4634-959e-2563ccabf629)

**Comment by NVentimiglia** [comment]
Hi @T-1K 

Thank you for profiling this. Performance is a moving target, but something we care about. I will see what I can do.

**Comment by NVentimiglia** [comment]
Closing as a feature request.
