### ISSUE TITLE
[Feature Request] Add AdRequest.IsTestDevice()

### ISSUE THREAD

**Issue by trepmog** [googleads/googleads-mobile-unity#3068]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.2.3
  * Google Mobile Ads Unity plugin version: 8.6.0
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: any
  * Any specific devices issue occurs on: any
  * Mediation ad networks used, and their versions: none

#### Steps to reproduce:

The Android SDK documentation 
https://developers.google.com/admob/android/test-ads
says to check AdRequest.isTestDevice() "to confirm that your device was properly added as a test device."

This function does not seem to exist in the Unity plugin. It would be very useful to me.

**Comment by NVentimiglia** [comment]
@trepmog 

I imagine we did not include this API because it is not present on the iOS SDK, meaning this API will not function correctly (about) half of the time. I will raise awareness with the SDK team and see what they say.
