### ISSUE TITLE
Rewarded Video is always CLOSE and FAILED?

### ISSUE THREAD

**Issue by ForestJungle** [googleads/googleads-mobile-unity#307]
Hi Admob Unity Team.I set up full everything on account and in Unity I also do everything as tutorials but I still doesn't work.Can anyone say for me what I am missing? Thanks a lot!
![admob](https://cloud.githubusercontent.com/assets/21006187/20290112/a493cffe-ab10-11e6-8c38-2b4a1e348e5a.png)
![untitled](https://cloud.githubusercontent.com/assets/21006187/20290120/ad5c01ba-ab10-11e6-9d4d-a696f9d5f47e.png)

**Comment by rampara** [comment]
I'm not sure I understand what you mean by always close and failed. What incorrect behavior are you experiencing? Do you see any output in logcat (under the `Unity` and `Ads` tags) that may indicate what's causing your issue?

**Comment by ForestJungle** [comment]
Hi rampara.You know I mean when I debug all delegate and then HandleRewardBasedVideoClosed and HandleRewardBasedVideoFailedToLoad method always call.Don't have anything video loaded.I also use some sample project https://drive.google.com/file/d/0B_ZafC3Djh1ROVFvNV9FUnFDNkE/view
Video loaded But fill rate is very low.I mean 800 request then it response 34 Impressions.When I use native Unity ads or Vungle Plugin without Admob.Fill rate is 100%.With all everything I post about what I am doing.Can you say for me What I am missing in project?Finally sorry my English.Thank you so much.

**Comment by rampara** [comment]
In the sample project you linked you're not using a valid ad unit, making it difficult for me to debug the low fill rate you're encountering. I would also recommend updating the the latest version of this plugin and using the latest version of Google Play services.

**Comment by ForestJungle** [comment]
I'm using Ad unit ID:: ca-app-pub-3145944329985331/1712734601 for rewarded video.You can check for me.Yes,I updated everything latest version.

**Comment by rampara** [comment]
@ForestJungle it looks like the issue where you're seeing onAdClosed after calling show is because you didn't declare the ad activity for Vungle in your Android manifest.  

You can find Vungle's Android integration instructions [here](https://support.vungle.com/hc/en-us/articles/204222794-Get-started-with-Vungle-Android-SDK).

**Comment by ForestJungle** [comment]
@rampara I declared ad activity in Manifest.And when I use older libs of Vungle(vungle-publisher-adaptive-id-3.3.5,dagger-2.1) then It does work.But Fill rate admob is very low.I posted Ad Unity ID of rewarded admob.Plz check it.Thanks.

**Comment by rampara** [comment]
Closing issue as original problem has been resolved. As this issue tracker is only for issues pertaining to the Google Mobile Ads Unity plugin, problems with low fill rate should be taken up at the [AdMob help center](https://support.google.com/admob/?hl=en#topic=2740022) or [AdMob support forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
