### ISSUE TITLE
Unity Ads Plugin 3.9.0: Incorrect SDK Version Reference in UnityMediationDependencies.xml

### ISSUE THREAD

**Issue by amjaliks** [googleads/googleads-mobile-unity#3073]
### Step 1: Describe your environment

* Platform: Android
* Mediation ad networks used, and their versions: Unity Ads 3.9.0

### Step 2: Describe the problem

The Unity Ads plugin version 3.9.0, while correctly referencing the Android adapter 4.9.2.0, still references the outdated Unity Ads SDK 4.8.0. The `UnityMediationDependencies.xml` file needs to be updated to reference `com.unity3d.ads:unity-ads:4.9.2`.

**Comment by NVentimiglia** [comment]
Thanks for letting me know, I will ask the mediation team to make a release.
