### ISSUE TITLE
AdMob Ads not showing

### ISSUE THREAD

**Issue by acemgaming** [googleads/googleads-mobile-unity#308]
I am using Unity 5.4.1f, AdMob plugin 3.1.2.
Both interstitial ads and banner ads do not show up using the the basic tutorial code.

**Comment by rampara** [comment]
@acemgaming Which platform are you deploying to (Android or iOS)? On iOS do you see any output in the console that indicates why ad requests or ad displaying is not working? On Android you can find this information in logcat under the Unity tag. Also, the [sample application](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) in this repo is a good reference of a working integration with AdMob in Unity.

**Comment by rampara** [comment]
Closing due to non-response. Please re-open if this issue persists for you.
