### ISSUE TITLE
The size of BannerView may not be obtained

### ISSUE THREAD

**Issue by NUTRACTOR** [googleads/googleads-mobile-unity#3080]
Describe your environment

  * Unity version: 2022.3.16f1
  * Google Mobile Ads Unity plugin version: 8.6.0
  * Platform: iOS
  * Platform OS version: iOS 17.0.3
 

Describe the problem

I am using the OnBannerAdLoaded callback to get the BannerView size.
But sometimes GetHeightInPixels() does not return the proper value.
Sometimes it is accurate, but in my case it returned 0 about 1 out of 5 times.
I know this Issue has been a problem before, but this issue has not been fixed yet.

**Comment by NVentimiglia** [comment]
'GetHeightInPixels' is not a suitable way to get banner height in Unity. Anchored banner height is never larger than the lesser of 15% of the device's height or 90 density independent pixels and never smaller than 50 density independent pixels. You can read more in this [section](https://developers.google.com/admob/unity/banner/anchored-adaptive#implementation_notes).

**Comment by NUTRACTOR** [comment]
The result of this calculation method is different from the result obtained with GetHeightInPixels.
Even if GetHeightInPixels returns a minimum value, this calculation will result in a value greater than the minimum.

**Comment by NVentimiglia** [comment]
I will let the plugin team know about this issue, and suggest they look into a fix.
