### ISSUE TITLE
Increase in "Input Dispatching Timed Out" ANR

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#3082]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.23f1
  * Google Mobile Ads Unity plugin version: 8.2.0, 8.6.0
  * Platform: Android

### [REQUIRED] Step 2: Describe the problem

"Input Dispatching Timed Out" ANR is increased in almost all my games. ANR threshold increases from 0.5%. Almost all "Input Dispatching Timed Out" ANR points towards google ads. Also play console mentioning that these ANRs are marked as SDK-related.
Check screenshot attached.

![GameAnr](https://github.com/googleads/googleads-mobile-unity/assets/32755091/ea3c6a42-27ed-4de0-8446-c7b8c00589c9)

**Comment by NVentimiglia** [comment]
Please try the [Android optimization beta](https://developers.google.com/admob/unity/optimize-initialization)

If that does not work,  report this to our [support team](https://developers.google.com/admob/unity/support).

Please include the crash log.

**Comment by MuhammadWaqasOfficial** [comment]
> Please try the [Android optimization beta](https://developers.google.com/admob/unity/optimize-initialization)
> 
> If that does not work, report this to our [support team](https://developers.google.com/admob/unity/support).
> 
> Please include the crash log.

Isn't enabling these two options conflicts with this MobileAds.RaiseAdEventsOnUnityMainThread = true;
Just curious before trying. Thanks

![settings](https://github.com/googleads/googleads-mobile-unity/assets/32755091/721a47e5-fb10-4abb-9a3d-11b8e415e455)

**Comment by NVentimiglia** [comment]
> > Please try the [Android optimization beta](https://developers.google.com/admob/unity/optimize-initialization)
> > If that does not work, report this to our [support team](https://developers.google.com/admob/unity/support).
> > Please include the crash log.
> 
> Isn't enabling these two options conflicts with this MobileAds.RaiseAdEventsOnUnityMainThread = true; Like they mentioned initialization and ad loading goes in background thread. Just curious before trying. Thanks
> 
> ![settings](https://private-user-images.githubusercontent.com/32755091/293141963-721a47e5-fb10-4abb-9a3d-11b8e415e455.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzUxNzMsIm5iZiI6MTcwNDMzNDg3MywicGF0aCI6Ii8zMjc1NTA5MS8yOTMxNDE5NjMtNzIxYTQ3ZTUtZmIxMC00YWJiLTlhM2QtMTFiOGU0MTVlNDU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAyMjExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1OTUyNzBmZjc5M2Y4Y2Y3NTM2MmJkOWFjZjAyYzU1ZTE2ODE5M2Q5ZGM2OTllMTc3NzliYTBkZTg0MGE5ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Z-EJGOKM1QkgDJgPDjbKTJmU1Og6CA12wFbejy3w2g)

- `RaiseAdEventsOnUnityMainThread` synchronizes the result of events.
- `Android optimization` pushes commands onto a background thread.
- The two features work together.
