### ISSUE TITLE
IOS crashes GADMutableArrayAddObject

### ISSUE THREAD

**Issue by Fuduji95** [googleads/googleads-mobile-unity#3083]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.5f1c1
  * Google Mobile Ads Unity plugin version:8.6.0
  * Platform: iOS
  * Platform OS version: iPhone OS 17.1.2
  * Any specific devices issue occurs on:iPhone 14
  * Mediation ad networks used, and their versions: View Podfile file

#### Steps to reproduce:

Version 'Google Mobile Ads SDK' and '10.14' caused a crash during game startup, probably during SDK initialization. Version 10.13 started and initialized normally, but Interactive ads encountered issues and could not be clicked

[Podfile.txt](https://github.com/googleads/googleads-mobile-unity/files/13782899/Podfile.txt)
[SolitaireTripeaksTravel-2023-12-28-155626.ips.txt](https://github.com/googleads/googleads-mobile-unity/files/13782900/SolitaireTripeaksTravel-2023-12-28-155626.ips.txt)
![t](https://github.com/googleads/googleads-mobile-unity/assets/22970561/a385448b-acde-49ff-88ce-21c771e88b57)

**Comment by Fuduji95** [comment]
Do I need to provide feedback on this issue under IOS SDK?

**Comment by NVentimiglia** [comment]
Hi,

I have submitted this issue to engineering to take a look (b/318589289). Any additional details will help.

**Comment by NVentimiglia** [comment]
@Fuduji95 

Can you give a few more details on what you do when you encounter this bug? You mention "Version 'Google Mobile Ads SDK' and '10.14' caused a crash during game startup, probably during SDK initialization". Any more details you have would help us tract down the cause of this issue.

**Comment by Fuduji95** [comment]
> @Fuduji95
> 
> Can you give a few more details on what you do when you encounter this bug? You mention "Version 'Google Mobile Ads SDK' and '10.14' caused a crash during game startup, probably during SDK initialization". Any more details you have would help us tract down the cause of this issue.

The Podfile.txt file contains a series of SDKs, such as pod 'Google Mobile Ads SDK', '~>10.13' (actually 10.14) changed to pod 'Google Mobile Ads SDK', and '10.13' (specified version). Everything is normal. As for "caused a crash during game startup, potentially during SDK initialization", this is my guess. The application did not crash immediately upon startup, and crashed within about ten seconds. There are two of my files above, one is Podfile and the other is the crash information file ips.txt. I'm sorry, as the issue was resolved by downgrading to 10.13, I did not attempt to reproduce this crash using the smallest engineering project

**Comment by NVentimiglia** [comment]
@Fuduji95 

Do you think this happened during ad loading then?

**Comment by Fuduji95** [comment]
> @Fuduji95
> 
> What I am trying to do is narrow down the problem API so that I can send the engineer in the right direction. Any intuition on which API you may be calling will help. For instance, do you think this happened during ad loading or ad showing?

I tried to reproduce this issue, but unfortunately it was not successful, and it seems that no one else has encountered this problem. It may be due to my other actions causing the crash. Please close this issue
