### ISSUE TITLE
MobileAds.RaiseAdEventsOnUnityMainThread    Vs    MobileAdsEventExecutor.ExecuteInUpdate

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#3086]
### Step 1: Describe your environment

  * Unity version: 2021.3.23f1
  * Google Mobile Ads Unity plugin version: 8.0.0 To 8.6.0
  * Platform: iOS, Android, Unity Editor

### Step 2: Describe the problem
if we set 
**MobileAds.RaiseAdEventsOnUnityMainThread = true;**

do we still need 
**MobileAdsEventExecutor.ExecuteInUpdate(() =>{ });**

as we know Callbacks from GoogleMobileAds are not guaranteed to be called on the main thread and MobileAdsEventExecutor is used to schedule these calls on the next Update() loop (as mentioned in 
**googleads-mobileunity/samples/HelloWorld/Assets/Scripts/GoogleAdMobController.cs**)

Any help appreciated. Thanks

**Comment by MuhammadWaqasOfficial** [comment]
Update:
GoogleAdMobController.cs is removed in HellowWorld sample project
MobileAdsEventExecutor.ExecuteInUpdate implementation is also removed from initialization.

**Comment by NVentimiglia** [comment]
Hi @MuhammadWaqasOfficial 

MobileAds.RaiseAdEventsOnUnityMainThread  replaces  MobileAdsEventExecutor.ExecuteInUpdate. If you use RaiseAdEventsOnUnityMainThread you do not need to use ExecuteInUpdate.
