### ISSUE TITLE
AppOpenAd Not Showing on Android 13

### ISSUE THREAD

**Issue by Bricoda** [googleads/googleads-mobile-unity#3087]
* Unity version: 2022.3.16f1
  * Google Mobile Ads Unity plugin version: v8.6.0
  * Platform: Android 
  * Platform OS version: Android 13

After Loading "AppOpenAd" ads on the unity editor and after testing, the application can display ads, and it can convert from Foregrounded to Backgrounded.
But after testing it on Android 13, it does not record any events after resuming the application.
It is assumed that the advertisement will appear after moving to Foregrounded.
```
if (state == AppState.Foreground)
             {
                 ShowAd();
             }
```
But the application on Android is not able to log the AppState event.

"state" can be printed.
In my case, I printed it as text, but it does not change or record any event.

`text.text = ("App State changed to : " + state);
`

**Comment by NVentimiglia** [comment]
For AppOpenAds to work on Android please add the following dependencies:

#### [Android Only] Add lifecycle dependencies

Modify the `GoogleMobileAdsDependencies.xml` file to include and import the
Android lifecycle dependencies.

```xml
<dependencies>
  <androidPackages>
    <androidPackage spec="androidx.lifecycle:lifecycle-common-java8:2.6.2">
      <repositories>
        <repository>https://maven.google.com/</repository>
      </repositories>
    </androidPackage>
    <androidPackage spec="androidx.lifecycle:lifecycle-process:2.6.2">
      <repositories>
        <repository>https://maven.google.com/</repository>
      </repositories>
    </androidPackage>
  </androidPackages>
</dependencies>
```

**Comment by Bricoda** [comment]
@NVentimiglia Thank you. The issue has been solved.
