### ISSUE TITLE
OnClose event won't trigger on iOS device

### ISSUE THREAD

**Issue by MAypDeca** [googleads/googleads-mobile-unity#3088]
* Unity version: 2020LTS
  * Google Mobile Ads Unity plugin version: 8.5.1
  * Platform: iOS
  * Platform OS version: iOS 14, 17  
  * Mediation: UnityAds

We have been using GoogleAdmob SDK version 6.0.0 until now, but after we upgraded to the latest version (8.5.1), we observed that in iOS devices (not in the editor or debug builds, which is used test prefab for Admob), OnClose event wouldn't trigger, In Android side everything working properly, and all events are triggered correctly but on iOS OnClose event will not invoke.

I tried to enable SetiOSAppPauseOnBackground so the behavior gets the same as Android as the documents mentioned, but it was ineffective.

In the log section, no error or any kind of warning/info log is shown for this issue.

**Comment by NVentimiglia** [comment]
Hi @MAypDeca 

What ad format are you trying out? Can you provide some sample code?

**Comment by MAypDeca** [comment]
Hello @NVentimiglia, sorry for the long delay,
We mostly use Rewarded ads.
For sample codes, I will try to provide them. 
But the overall process is that in the code, we would wait until the OnClose event is called, and in that we set some boolean also, we are using `MobileAdsEventExecutor.ExecuteInUpdate` to handle the main thread for unity.

**Comment by kaninhot004** [comment]
@MAypDeca If you had function that destroy Reward Ad in ShowReward callback just delay it.
(Mine was solved by move destroy Reward Ad to OnFullScreenClose + Delay before destroy.)

**Comment by MAypDeca** [comment]
Thank you @kaninhot004. Good call actually we are removing the Reward Ad in the callback of it.
I will try it and see if it works.
