### ISSUE TITLE
Wrong UnityMediationDependencies.xml file

### ISSUE THREAD

**Issue by desouse** [googleads/googleads-mobile-unity#3096]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.10f1
  * Google Mobile Ads Unity plugin version: 8.6.0
  * Platform: Android
  * Platform OS version: _____
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: Unity Ads Mediation (3.9.0)

#### Steps to reproduce:

The last plugin Unity Ads Mediation (3.9.0) (https://developers.google.com/admob/unity/mediation/unity#version-3.9.0) contains wrong UnityMediationDependencies.xml file. Mediation adapter version was upgraded to 4.9.2.0 while Unity Ads SDK version is 4.8.0

#### Relevant Code:
![UnityMediationDependencies](https://github.com/googleads/googleads-mobile-unity/assets/9247348/86519a76-14cc-4adf-bc92-0047c4d4e3d3)

**Comment by NVentimiglia** [comment]
Hi @desouse 

Agree that this is not correct. I will take a look.

In the mean time, I see that Maven has 4.9.2 of com.unity3d.ads, so you can try updating manually.
