### ISSUE TITLE
AppLovin + Meta + UnityAds == Infinite loop during dependencies resolving

### ISSUE THREAD

**Issue by dhamelin** [googleads/googleads-mobile-unity#3100]
#### Steps to reproduce:
Using the sample HelloWorld code

- Import GoogleMobileAds-v8.6.0
- Import AppLovinUnityAdapter-6.9.1

 (Dependencies resolves)

- Import MetaAudienceNetworkUnityAdapter-3.11.0
 
(Dependencies resolves)
 
- Import UnityAdsUnityAdapter-3.8.0

Infinite loop during resolve phase. The "Resolution Attempt" keeps increasing, not sure what's different between each attempt..

<img width="1796" alt="Screenshot 2024-01-11 at 1 51 43 PM" src="https://github.com/googleads/googleads-mobile-unity/assets/22534627/b9cd3c85-23ac-49a1-acd2-4bbbb86bacb7">

**Comment by NVentimiglia** [comment]
There is an issue with EDM4U which will fail like this if it can not find a dependency.

Two solutions 

- Do not use EDM4U and use a [custom gradle template](https://developers.google.com/admob/unity/gradle).
- Modify the [Dependencies.xml](https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml) to have hard coded versions. ([example](https://github.com/googleads/googleads-mobile-unity/commit/8a46b1e346beea09a37da2f633e52d3899818b29))

**Comment by 256p** [comment]
FYI

Previously I have encountered a similar problem, where dependency resolution lasted several hours. 
EDM4U devs said that it won't be fixed and advised to use custom gradle template 
https://github.com/googlesamples/unity-jar-resolver/issues/591#issuecomment-1396658690

**Comment by NVentimiglia** [comment]
Thanks,

We now suggest [the same](https://developers.google.com/admob/unity/gradle#unity_20221_and_earlier).
