### ISSUE TITLE
Duplicate class with Firebase

### ISSUE THREAD

**Issue by cephalo3** [googleads/googleads-mobile-unity#3101]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: _2022.3.17f1____
  * Google Mobile Ads Unity plugin version: __8.5.3___
  * Platform: __Android___ (iOS, Android, Unity Editor)
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
Can't build latest GoogleMobileAds with the latest Firebase

There is a module collision with the following error message:
Duplicate class com.google.android.gms.internal.consent_sdk.zza found in modules jetified-com.google.android.ump.user-messaging-platform-2.0.0-runtime (:com.google.android.ump.user-messaging-platform-2.0.0:) and jetified-user-messaging-platform-2.1.0-runtime (com.google.android.ump:user-messaging-platform:2.1.0)

There are many similar messages but it all refers to the same module.

I tried exporting to Android Studio but I can't make the problem go away. I don't even know why this is a collision because the two packages use different version of the same package. How can I edit the right build.gradle file to force one or the other to use the other module. I'm not even sure I know what needs to be done. I don't know why this is a collision.

I tried downgrading GoogleMobileAds to the last one that uses com.google.android.ump.user-messaging-platform-2.0.0 but I still got the same error. What is going on and what do I need to put in my build.gradle file?

```

**Comment by NVentimiglia** [comment]
Hi @cephalo3 

It sounds like the google mobile ads and firebase are both pulling in the UMP SDK.

The solution here is to modify the Google Mobile Ads [Dependency file](https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml) to make sure that both SDKs are pulling in the same version of the UMP SDK.

Alternatively, you can try using [gradle resolution](https://developers.google.com/admob/unity/gradle).

**Comment by NVentimiglia** [comment]
@cephalo3 

I was unable to see any conflict when installing Firebase  Analytics alongside Google Mobile Ads.

Can you let me know what firebase plugin which shows this problem?

**Comment by cephalo3** [comment]
Ok, I finally after months solved this problem. Firebase puts the library in a weird spot in the assets folder, and EDM4U doesn't catch it. I solved the problem by merely deleting it It is an aar file. I don't have access to the exact name at the moment. I'm not sure which Firebase package contributes that library, but I am using Firestore, Auth, Functions and Messaging.

**Comment by NVentimiglia** [comment]
Glad you fixed it. Some of these Android issues can be confusing to diagnose.
