### ISSUE TITLE
Test Ads won't show (No ad to show error) if consent is declined

### ISSUE THREAD

**Issue by dhamelin** [googleads/googleads-mobile-unity#3104]
Unity 2021.3.31, tested on iOS with AdMob SDK 8.6.0

### [REQUIRED] Step 2: Describe the problem

When I accept the consent, my test ads works fine.
If I decline consent, test ads result in "no ad to show" error.

Is that an expected behaviour or is it a sign of an issue in my code (or the SDK)?

**Comment by NVentimiglia** [comment]
Hi @dhamelin 

No ad to show is a serving error. This usually means that your implementation is correct but something (such as a policy error) is preventing the ads from serving.

Please take a look at your admob account and the [policy center](https://support.google.com/admob/answer/10448801?hl=en&sjid=15664975450537145569-NC) and resolve any errors.
