### ISSUE TITLE
ConsentInformation.PrivacyOptionsRequirementStatus always return Required

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#3109]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.23f1
  * Google Mobile Ads Unity plugin version: 8.6.0
  * Platform: Unity Editor
  * Mediation ad networks used, and their versions: None

### [REQUIRED] Step 2: Describe the problem
ConsentInformation.PrivacyOptionsRequirementStatus is always returning    Required, doesn't matter region is NotEEA, EEA or consent for gdpr shown or not, or start game after consent is taken.
you can use sample project and add 
Debug.Log(ConsentInformation.PrivacyOptionsRequirementStatus);
 line in UpdatePrivacyButton method in sample project GoogleMobileAdsConsentController.cs script.
 
#### Relevant Code:
```
void UpdatePrivacyButton()
{
    if (_privacyButton != null)
    {
        _privacyButton.interactable =
            ConsentInformation.PrivacyOptionsRequirementStatus ==
                PrivacyOptionsRequirementStatus.Required;
        Debug.Log(ConsentInformation.PrivacyOptionsRequirementStatus);
    }
}
```

**Comment by MuhammadWaqasOfficial** [comment]
for time being i am using **ConsentInformation.ConsentStatus** to config my privacy policy button placed in settings screen.

```
if (ConsentInformation.ConsentStatus == ConsentStatus.Obtained)
{
    PrivacyPolicyBtnText.text = "Update GDPR Consent";
    PrivacyPolicyBtn.onClick.AddListener(() => AdsManager.Instance.UpdateGdprConset());
}
else
{
    PrivacyPolicyBtnText.text = "Privacy Policy";
    PrivacyPolicyBtn.onClick.AddListener(() => AdsManager.Instance.ShowPrivacyPolicy());
}
```

**Comment by MuhammadWaqasOfficial** [comment]
Why response to issues is too late here in [issue tracker section](https://github.com/googleads/googleads-mobile-unity/issues). Every time it takes 1 to 4 days. Is there any specific reason for late reply? what we to do to get quick response?

**Comment by NVentimiglia** [comment]
@MuhammadWaqasOfficial 

I will push to get this fixed in the next release. Thank you for the awareness.

**Comment by MuhammadWaqasOfficial** [comment]
next release means?
resolved in 8.7.0?

> @MuhammadWaqasOfficial
> 
> I will push to get this fixed in the next release. Thank you for the awareness.

**Comment by NVentimiglia** [comment]
@MuhammadWaqasOfficial 

Yes, please try 8.7. If it continues, please reopen this issue.

**Comment by zhangjianshuai** [comment]
same issue here,  SDK version 8.7.0, platform is iOS; 
this API "GoogleMobileAds.Ump.Api.ConsentInformation.PrivacyOptionsRequirementStatus" always return PrivacyOptionsRequirementStatus.Required
, Therefore, the player cannot actively set the form options.  please help me; @NVentimiglia

**Comment by MuhammadWaqasOfficial** [comment]
> same issue here, SDK version 8.7.0, platform is iOS; this API "GoogleMobileAds.Ump.Api.ConsentInformation.PrivacyOptionsRequirementStatus" always return PrivacyOptionsRequirementStatus.Required , Therefore, the player cannot actively set the form options. please help me; @NVentimiglia
> 
> The return value on Android is correct

use this for time being https://github.com/googleads/googleads-mobile-unity/issues/3109#issuecomment-1895326791

**Comment by zhangjianshuai** [comment]
> > same issue here, SDK version 8.7.0, platform is iOS; this API "GoogleMobileAds.Ump.Api.ConsentInformation.PrivacyOptionsRequirementStatus" always return PrivacyOptionsRequirementStatus.Required , Therefore, the player cannot actively set the form options. please help me; @NVentimiglia
> > The return value on Android is correct
> 
> use this for time being [#3109 (comment)](https://github.com/googleads/googleads-mobile-unity/issues/3109#issuecomment-1895326791)

thanks, I'll try it;

**Comment by MuhammadWaqasOfficial** [comment]
> > > same issue here, SDK version 8.7.0, platform is iOS; this API "GoogleMobileAds.Ump.Api.ConsentInformation.PrivacyOptionsRequirementStatus" always return PrivacyOptionsRequirementStatus.Required , Therefore, the player cannot actively set the form options. please help me; @NVentimiglia
> > > The return value on Android is correct
> > 
> > 
> > use this for time being [#3109 (comment)](https://github.com/googleads/googleads-mobile-unity/issues/3109#issuecomment-1895326791)
> 
> thanks, I'll try it; But there's a problem, You have no way of knowing if the player is an EU player?

yes we can find that.

```
var requestParameters = new ConsentRequestParameters
{
    TagForUnderAgeOfConsent = false,
};
ConsentInformation.Update(requestParameters, (FormError updateError) =>
{
    if (updateError != null)
    {
        return;
    }

    if (ConsentInformation.ConsentStatus == ConsentStatus.NotRequired)
    {
         //Non-EU Player
    }
    else if (ConsentInformation.ConsentStatus == ConsentStatus.Required)
    {
        // EU Player
    }
    else if (ConsentInformation.ConsentStatus == ConsentStatus.Unknown)
    {
        //Unknown Region
    }
});
```
