### ISSUE TITLE
A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction

### ISSUE THREAD

**Issue by Hassan051** [googleads/googleads-mobile-unity#3116]
[REQUIRED] Step 1: Describe your environment
Unity version: 2023Lts
Google Mobile Ads Unity plugin version: 8.7.0
Platform: Unity Editor
Platform OS version: Windows 11
Any specific devices issue occurs on: -
Mediation ad networks used, and their versions: none
[REQUIRED] Step 2: Describe the problem
Steps to reproduce:
Create a blank Unity Project (2D template tested)
Import GoogleMobileAds-v8.7.0.unitypackage
Let External Dependency Manager to resolve dependencies
Switch target platform to Android
In menu Assets, Google Mobile Ads, Settings set an app id
In Build Settings enable Build App Bundle (Google Play)
In Player Settings assign a package name
Minimum API level 23, target API level 34
Build
The build fails with the popup "A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction".

![287394970-fabd709e-a450-4ad4-9e9d-62a38259ee69](https://github.com/googleads/googleads-mobile-unity/assets/34217449/a4c8827f-0436-4831-8bd5-63d77a119dd6)

**Comment by NVentimiglia** [comment]
@Hassan051 

Please reinstall the plugin, this should not happen. If it continues, can you please provide a full error log?

**Comment by Hassan051** [comment]
Hi @NVentimiglia I reinstalled the plugin but I'm still facing the same error This is My project settings and the full error log, I hope to find a solution to this.

- My project settings :-
![Screenshot 2024-01-30 191703](https://github.com/googleads/googleads-mobile-unity/assets/34217449/1e158c57-33c9-4250-94e8-2a9ed7e9f5bf)
![Screenshot 2024-01-30 191547](https://github.com/googleads/googleads-mobile-unity/assets/34217449/bc629894-d55c-47e3-b562-18b2259ae560)
![Screenshot 2024-01-30 191623](https://github.com/googleads/googleads-mobile-unity/assets/34217449/21e0694a-7efe-4c2c-a522-bdf8479a5eb1)

-the full error log :-
> Configure project :launcher
WARNING:The option setting 'android.bundle.enableUncompressedNativeLibs=false' is deprecated.
The current default is 'true'.
It will be removed in version 8.0 of the Android Gradle plugin.
You can add the following to your build.gradle instead:
android {
    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}
WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 34

This Android Gradle plugin (7.3.1) was tested up to compileSdk = 33

This warning can be suppressed by adding
    android.suppressUnsupportedCompileSdk=34
to this project's gradle.properties

The build will continue, but you are strongly encouraged to update your project to
use a newer Android Gradle Plugin that has been tested with compileSdk = 34

> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:mobilenotifications.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:mobilenotifications.androidlib:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:mobilenotifications.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:mobilenotifications.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:generateReleaseResValues
> Task :unityLibrary:generateReleaseResValues
> Task :unityLibrary:mobilenotifications.androidlib:generateReleaseResValues
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:generateReleaseResources
> Task :unityLibrary:generateReleaseResources
> Task :unityLibrary:mobilenotifications.androidlib:generateReleaseResources
> Task :launcher:preBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :launcher:generateReleaseResValues
> Task :launcher:generateReleaseResources
> Task :launcher:createReleaseCompatibleScreenManifests
> Task :launcher:extractDeepLinksRelease
> Task :unityLibrary:mobilenotifications.androidlib:packageReleaseResources
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:packageReleaseResources
> Task :unityLibrary:mobilenotifications.androidlib:extractDeepLinksRelease
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:extractDeepLinksRelease
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:packageReleaseResources
> Task :unityLibrary:extractDeepLinksRelease
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:compileReleaseLibraryResources
> Task :unityLibrary:compileReleaseLibraryResources
> Task :unityLibrary:generateReleaseBuildConfig
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:generateReleaseBuildConfig
> Task :unityLibrary:mobilenotifications.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:mobilenotifications.androidlib:compileReleaseLibraryResources
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:javaPreCompileRelease
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:javaPreCompileRelease
> Task :unityLibrary:mobilenotifications.androidlib:generateReleaseBuildConfig
> Task :unityLibrary:mobilenotifications.androidlib:javaPreCompileRelease
> Task :unityLibrary:mobilenotifications.androidlib:writeReleaseAarMetadata
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:writeReleaseAarMetadata
> Task :unityLibrary:writeReleaseAarMetadata
> Task :unityLibrary:mobilenotifications.androidlib:parseReleaseLocalResources
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:parseReleaseLocalResources
> Task :unityLibrary:mergeReleaseShaders
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:mergeReleaseShaders
> Task :unityLibrary:mobilenotifications.androidlib:mergeReleaseShaders
> Task :unityLibrary:mobilenotifications.androidlib:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:mobilenotifications.androidlib:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:parseReleaseLocalResources
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:packageReleaseAssets
> Task :unityLibrary:mobilenotifications.androidlib:packageReleaseAssets
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:mobilenotifications.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:bundleLibResRelease NO-SOURCE
> Task :unityLibrary:mobilenotifications.androidlib:bundleLibResRelease NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:mergeReleaseJniLibFolders
> Task :unityLibrary:mobilenotifications.androidlib:mergeReleaseJniLibFolders
> Task :unityLibrary:mobilenotifications.androidlib:mergeReleaseNativeLibs NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:mergeReleaseNativeLibs NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:prepareReleaseArtProfile UP-TO-DATE
> Task :unityLibrary:mobilenotifications.androidlib:prepareReleaseArtProfile UP-TO-DATE

> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:processReleaseManifest
package="com.google.unity.ads" found in source AndroidManifest.xml: C:\Users\hm898\Desktop\BlockPuzzleProII\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\GoogleMobileAdsPlugin.androidlib\AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace
This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

> Task :unityLibrary:processReleaseManifest

> Task :unityLibrary:mobilenotifications.androidlib:processReleaseManifest
package="com.unity.androidnotifications" found in source AndroidManifest.xml: C:\Users\hm898\Desktop\BlockPuzzleProII\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\mobilenotifications.androidlib\src\main\AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace
This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:mobilenotifications.androidlib:copyReleaseJniLibsProjectOnly
> Task :launcher:checkReleaseDuplicateClasses FAILED
> Task :unityLibrary:packageReleaseAssets
> Task :launcher:mapReleaseSourceSetPaths
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:generateReleaseRFile
> Task :unityLibrary:mobilenotifications.androidlib:generateReleaseRFile
?? actionable tasks: ?? executed, ? up-to-date

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by MuhammadWaqasOfficial** [comment]
@Hassan051 the error trace you share is actually a warning and show as error when failed. 
Are you using firebase 11.7.0?
The real error is [this](https://github.com/firebase/firebase-unity-sdk/issues/945) .  And its happen in merging AndroidManifest file.
Solution 1: Upgrade Gradle Version or build with 2023 with has required gradle.
Solution 2: In Plugins->Android->AndroidManifest file remove the <property tools:node="removeAll"  /> line and add . Its unclear for now what's the consequences of this solution but you will be able to build the game.

**Comment by timi9999** [comment]
> @Hassan051
> 
> Please reinstall the plugin, this should not happen. If it continues, can you please provide a full error log?

I tried everything and nothing worked

**Comment by NVentimiglia** [comment]
@timi9999 

Can you submit the UnityEditor log ? it should contain more details about `MergeJavaResWorkAction`.
