### ISSUE TITLE
GMA 8.7.0 - Execution failed for task ':launcher:mergeReleaseJavaResource'

### ISSUE THREAD

**Issue by madTeddy** [googleads/googleads-mobile-unity#3124]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: **2020.3.48f1**
  * Google Mobile Ads Unity plugin version: **8.7.0**
  * Platform: **Android**
  * Mediation ad networks used, and their versions: **Applovin 6.9.1**
  * Gradle Version: **6.9.4**
  * Gradle Plugin Version: **4.2.0**

### [REQUIRED] Step 2: Describe the problem

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:mergeReleaseJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'META-INF/kotlinx-serialization-json.kotlin_module' from inputs:
      - C:\Users\razeb\.gradle\caches\transforms-3\601683efc9a8009dee4a884706bb4564\transformed\jetified-org.jetbrains.kotlinx.kotlinx-serialization-json-1.3.2.jar
      - C:\Users\razeb\.gradle\caches\transforms-3\f8521230d3476b2848d15cbf5122e7e7\transformed\jetified-org.jetbrains.kotlinx.kotlinx-serialization-json-jvm-1.3.2.jar
     Adding a packagingOptions block may help, please refer to
     https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
     for more information
```

**Comment by madTeddy** [comment]
Ok. The checkbox _"Enable kotlinx.coroutines packaging option"_ was not helpful. But with additional **packagingOptions** in **Main Gradle Template** and **Launcher Template**:
```
packagingOptions {
    pickFirst('META-INF/kotlinx-serialization-json.kotlin_module')
}
``` 
Build was successful. If this bug is not on my side, please fix it.

**Comment by NVentimiglia** [comment]
Glad you got this working. You are correct that we need the packagingOptions which is added by the SDK.

If you run into more issues, please reopen
Nick
