### ISSUE TITLE
Reopen：Android: GoogleMobileAds 8.5.2: ChartboostUnityAdapter-4.3.0 An error occurs in Android Studio. #2977

### ISSUE THREAD

**Issue by crSudo** [googleads/googleads-mobile-unity#3126]
@NVentimiglia 
sorry. I didn't know how to reopen, so I posted a new one.

If you look at the site below, it says to check [Custom Main Gradle Template] and [Custom Gradle Properties Template].
If this is left as is, I think this document needs to be revised.
https://developers.google.com/admob/unity/quick-start

Also, when I checked the following site, the url 'https://cboost.jfrog.io/artifactory/chartboost-ads/' was listed.
When I tried adding [url 'https://cboost.jfrog.io/artifactory/chartboost-ads/'] to [\Assets\GoogleMobileAds\Mediation\Chartboost\Editor\ChartboostMediationDependencies.xml], the APK I was able to create it.

https://github.com/googleads/googleads-mobile-android-mediation/blob/main/ThirdPartyAdapters/chartboost/build.gradle
`    allprojects {
        repositories {
            google()
            mavenCentral()
            maven {
                url 'https://cboost.jfrog.io/artifactory/chartboost-ads/'
            }
        }
    }
`

I think the Unity version also needs to be modified, what do you think?

Best Regards
crSudo

**Comment by crSudo** [comment]
@NVentimiglia 
sorry. I posted to the wrong place...
I looked into the differences between aar between Android Studio and Unity.

◇AndroidStudio
If you add the url 'https://cboost.jfrog.io/artifactory/chartboost-ads/'

[Project]-[External Libraries]
Gradle: com.chartboost:chartboost-sdk:9.6.0@aar
Gradle: com.google.ads.mediation:chartboost:9.6.0.0@aar

◇Unity
[File]-[Build Settings]-[Player Settings]-[Publishing Settings]
-[Custom Main Gradle Template] : OFF
-[Custom Gradle Properties Template] : OFF
[Assets]-[External Dependency Manager]-[Android Resolver]-[Force Resolve]

\Assets\Plugins\Android内
com.chartboost.chartboost-sdk-9.2.1.aar
com.google.ads.mediation.chartboost-9.6.0.0.aar

■I checked each Admob site.
https://developers.google.com/admob/unity/mediation/chartboost#version-4.5.0 ： [Supports Chartboost Android adapter version 9.6.0.0.]
is linked to the URL below.
https://github.com/googleads/googleads-mobile-android-mediation/blob/main/ThirdPartyAdapters/chartboost/CHANGELOG.md#version-9600
If you look at this site, Chartboost SDK version 9.6.0.

I think it is correct to use Chartboost SDK 9.6.0, what do you think?

Best Regards
crSudo

**Comment by NVentimiglia** [comment]
@crSudo 

You can try. I dont see anything that would break (such as an API removal). The unity adapter releases usually run a little behind the Android releases.

Nick
