### ISSUE TITLE
Different error codes for No Fill error on iOS and Android

### ISSUE THREAD

**Issue by spdhag** [googleads/googleads-mobile-unity#3127]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.10f1
  * Google Mobile Ads Unity plugin version: 8.6.0
  * Platform: iOS, Android
  * Platform OS version: all supported
  * Mediation ad networks used, and their versions: AppLovin 6.9.1, Unity Ads 3.8.0

#### Steps to reproduce:

After implementing the Ads Consent Form, we noticed more no fill errors which is expected, but the error code given on iOS and Android are different. Android Error Code 3 while on ios No fill is Error Code 1

**Comment by NVentimiglia** [comment]
Hi @spdhag 

That is expected. The Admob SDK has differences on iOS and Android, this is one of them. The Unity plugin does its best to reconcile these differences, but some will persist.

Thanks,
Nick
