### ISSUE TITLE
JarResolver error last release

### ISSUE THREAD

**Issue by ceceomer** [googleads/googleads-mobile-unity#313]
What can I do?
![untitled](https://cloud.githubusercontent.com/assets/10334894/20673104/6a402916-b58c-11e6-938b-2b46578eb6aa.png)

**Comment by rampara** [comment]
Do you have any other warnings or errors in the console output from Play Services resolver that might indicate the cause of your error? Which versions are declaring as dependencies for AdMob and Analytics?

**Comment by chuakc92** [comment]
Try removing Google.JarResolver.dll.

**Comment by rampara** [comment]
Closing this issue due to non-response. Please re-open if this issue persists for you.
