### ISSUE TITLE
play-services-ads:22.6.0->A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

### ISSUE THREAD

**Issue by dannisliang** [googleads/googleads-mobile-unity#3144]
### [REQUIRED] Step 1: Describe your environment

Unity version: 2021.3.33f1
Google Mobile Ads Unity plugin version: 8.7.0
Platform: Android - Unity Editor

The resolve will complete without errors.

The issue when you try to build:
FAILURE: Build completed with 2 failures.

#### Relevant Code:

```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade 
```

**Comment by AgianNAgain** [comment]
Shoutout for Alireaza, I had the same problem on the same environment and it was fixed using the steps he mentions here 
https://github.com/googleads/googleads-mobile-unity/issues/3042#issuecomment-1919833720
