### ISSUE TITLE
App Open ads malfunction during testing in the Unity Editor

### ISSUE THREAD

**Issue by amjaliks** [googleads/googleads-mobile-unity#3151]
### Step 1: Describe your environment

  * Unity version: 2022.3.19f1
  * Google Mobile Ads Unity plugin version: 8.7.0
  * Platform: Unity Editor
  * Platform OS version: macOS 14.2

### Step 2: Describe the problem

When I attempt to display the App Open ad in the Editor, it briefly flashes and then immediately closes (disappears) by itself. After the ad closes, it fails to call the OnAdFullScreenContentClosed callback.

The code loading the App Open ad:
```csharp
AppOpenAd.Load(appOpenAdUnitId, request, (ad, _) => {
    var success = ad != null;
    if (success) {
        appOpenAd = ad;
    }
});
```

The code showing the App Open ad:
```csharp
appOpenAd.OnAdFullScreenContentOpened += () => {
    onShown?.Invoke();
};
appOpenAd.OnAdFullScreenContentClosed += () => {
    onClosed?.Invoke();
};

appOpenAd.Show();
```

**Comment by NVentimiglia** [comment]
I was not able to see any issue on the [HelloWorld AppOpen Sample](https://github.com/googleads/googleads-mobile-unity/blob/e78587416e342514ec373c6a37d5452f75776f9f/samples/HelloWorld/Assets/Scripts/AppOpenAdController.cs). 


 
Please take a look at the sample code to make sure there is nothing else going on in your code which might cause the ad to close prematurely. Also try adding some log statements around `OnAppStateChanged` as that could trigger the ad to show.

If you push a more complete sample I can take another look.
