### ISSUE TITLE
[BUG] AdMob causes game's Time Scale to be 0

### ISSUE THREAD

**Issue by kiraio-moe** [googleads/googleads-mobile-unity#3155]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.19f1
  * Google Mobile Ads Unity plugin version: v8.7.0
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: Android 11 (eg iOS 10, Android 9)

### [REQUIRED] Step 2: Describe the problem

For unknown reasons, the game `Time Scale` is set to `0` when you initialized the ads. So, your game seems like "freezed" because of ANR while in reality isn't. To fix this, just set the game time scale to 1 with `Time.timeScale`.

#### Steps to reproduce:

- Make a dummy project.
- Test the ads with a basic Ads Initialization, Banner and Interstitial Ads implementation.

\* I have attached the sample project. Make sure to comment the code to set the time scale to 1 in `Assets/Scripts/Manager/ManageScene.cs`.

Attachment(s):
[zero-time-scale-bug.zip](https://github.com/googleads/googleads-mobile-unity/files/14232716/zero-time-scale-bug.zip)

**Comment by NVentimiglia** [comment]
I tried looking at ManageScene and could not see any reference to GoogleMobile Ads. Can you replicate this in the HelloWorld sample, or only the custom implementation?

Looking at the code, I see we do pause the game, but only on the UnityEditor ([here](https://github.com/googleads/googleads-mobile-unity/blob/e78587416e342514ec373c6a37d5452f75776f9f/source/plugin/Assets/GoogleMobileAds/Platforms/Unity/AdBehaviour.cs#L18)). Are you seeing this on Android / iOS ?

**Comment by kiraio-moe** [comment]
> I tried looking at ManageScene and could not see any reference to GoogleMobile Ads. Can you replicate this in the HelloWorld sample, or only the custom implementation?

All the code for ads implementation are inside `Assets/Scripts/Ads` folder. You can see I initialize the ad in `AdsManager.cs`.

> Looking at the code, I see we do pause the game, but only on the UnityEditor ([here](https://github.com/googleads/googleads-mobile-unity/blob/e78587416e342514ec373c6a37d5452f75776f9f/source/plugin/Assets/GoogleMobileAds/Platforms/Unity/AdBehaviour.cs#L18)). Are you seeing this on Android / iOS ?

I see both on Editor & Android.

**Comment by NVentimiglia** [comment]
@kiraio-moe 

Looking at the source code I see two references to `Time.TimeScale`, both reside within the Unity platform.

https://github.com/search?q=repo%3Agoogleads%2Fgoogleads-mobile-unity%20Time.timeScale&type=code

That said, the Android interstitial ad is a different Activity which could cause Unity to pause on its own if you disable the `Run In Background` option.  I think this is what you are seeing.

https://docs.unity3d.com/ScriptReference/Application-runInBackground.html

**Comment by dqnhust** [comment]
Hey @kiraio-moe 
I think the scenario goes like this:

When initializing AdMob or UMP, the Unity Editor will display an UMP popup or interstitial, or reward ad and pause the game (timeScale=0).
Then, the developer will do something that causes the popup to be destroyed (such as switching scenes).
Of course, this happens very quickly (within a few frames), so the developer may not realize that their game logic has destroyed the popup that AdMob is showing. Meanwhile, AdMob thinks it needs to pause the game for the user to click the close button.
That’s the assumption I’m considering, and I believe it might help you.

**Comment by NVentimiglia** [comment]
@kiraio-moe let me know if you need further help. As @dqnhust pointed out the logic which we use to run on the editor (for all platforms) is not the same logic used on device.

**Comment by kiraio-moe** [comment]
> When initializing AdMob or UMP, the Unity Editor will display an UMP popup or interstitial, or reward ad and pause the game (timeScale=0). Then, the developer will do something that causes the popup to be destroyed (such as switching scenes).

I'd switching to another scene and yes, the AdMob ad get destroyed quickly before the scene is switched.
Is there any ways I can display an ad properly before switching a scene?
