### ISSUE TITLE
[build] jetified-liftoffmonetize-unity-android-library-runtime.jar: D8: java.lang.NullPointerException

### ISSUE THREAD

**Issue by dreamcodestudio** [googleads/googleads-mobile-unity#3159]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.34f1
  * Google Mobile Ads Unity plugin version: 8.7.0
  * Platform: Android
  * Platform OS version: Any
  * Any specific devices issue occurs on: Samsung A52
  * Mediation ad networks used, and their versions: LiftoffMonetize-5.0.0, AdColony-2.6.2,   AppLovin-7.0.0, IronSource-2.5.0

#### Steps to reproduce:

1. Setup Unity Environment by config:

> Android Minimum API Level = 21
> Target platform = Android
> Scripting Backend = Mono
> API Level  = .NET Standard 2.0

2. Build in APK or AAB format

In result Unity shows `Gradle build failed` :

```
Note: E:\Develop\Repository\project-w\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
ERROR:E:\Develop\Gradle_Custom_Cache\caches\transforms-2\files-2.1\9bef87ee189eda4132d78fbe6f56ebfb\jetified-liftoffmonetize-unity-android-library-runtime.jar: D8: java.lang.NullPointerException

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:mergeExtDexDebug'.
> Could not resolve all files for configuration ':launcher:debugRuntimeClasspath'.
   > Failed to transform liftoffmonetize-unity-android-library-.aar (:liftoffmonetize-unity-android-library:) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-incremental-transform=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.status=integration, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: E:\Develop\Gradle_Custom_Cache\caches\transforms-2\files-2.1\9bef87ee189eda4132d78fbe6f56ebfb\jetified-liftoffmonetize-unity-android-library-runtime.jar.
         > Error while dexing.
```

On previous version of `LiftoffMonetize-4.0.0` project build succеsefully.

**Comment by shefich** [comment]
Same for me.

**Comment by NaeemHB** [comment]
Any Solution?

**Comment by desouse** [comment]
The same problem. @NVentimiglia please pay attention.

**Comment by NVentimiglia** [comment]
@desouse 

Thanks for your patience. Just returned from vacation, I will take a look.

**Comment by dcosmin-97** [comment]
I had to downgrade back to 4.0.0 😌

**Comment by NaeemHB** [comment]
when we downgrade ,not getting impression ,only found requests.

**Comment by NaeemHB** [comment]
![Solution](https://github.com/googleads/googleads-mobile-unity/assets/114641115/0a3b4ed3-111b-4f8a-b744-71c19225ae31)
go to google mobile ads > Mediation > LiftoffMonetize >Plugins >Android > liftoffmonetize-unity-android-library 
then check all boxes as shown in pic ,Apply and get your build ..

**Comment by dcosmin-97** [comment]
> ![Solution](https://private-user-images.githubusercontent.com/114641115/306581895-0a3b4ed3-111b-4f8a-b744-71c19225ae31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTA2MzAsIm5iZiI6MTcwODUxMDMzMCwicGF0aCI6Ii8xMTQ2NDExMTUvMzA2NTgxODk1LTBhM2I0ZWQzLTExMWItNGY4YS1iNzQ0LTcxYzE5MjI1YWUzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQxMDEyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDk5ZTU2Yzg4MzE1NTJjYTYxYTJiZjRiNzRkOTA1NWNjNjk5OTEzYmNkYjdlOGRiOWU5ZGMxMGMzMWZjOGM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sF2lVI8g70fddXt86saiYxpyeq776m-IhEovSOQCiqo) go to google mobile ads > Mediation > LiftoffMonetize >Plugins >Android > liftoffmonetize-unity-android-library then check all boxes as shown in pic ,Apply and get your build ..

Thank you, I think you should be hired by the testing team. I don't think these updates are tested lately

**Comment by shefich** [comment]
> ![Solution](https://private-user-images.githubusercontent.com/114641115/306581895-0a3b4ed3-111b-4f8a-b744-71c19225ae31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTY2MjEsIm5iZiI6MTcwODUxNjMyMSwicGF0aCI6Ii8xMTQ2NDExMTUvMzA2NTgxODk1LTBhM2I0ZWQzLTExMWItNGY4YS1iNzQ0LTcxYzE5MjI1YWUzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQxMTUyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGJkZmE2YjY3YmVjNDY3OTlkMTVmZjA2NDEyMjJmYWZjZDNjMWUyODE1ZDhhNTBkZmU0YjI5MzZmMjVhYWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.omiYfG4WX65IObEFbfmfTgml3gKx9cFEUTFaXjYQ1lU) go to google mobile ads > Mediation > LiftoffMonetize >Plugins >Android > liftoffmonetize-unity-android-library then check all boxes as shown in pic ,Apply and get your build ..

You can see that Android platform **Excluded**
Don't think that this is normal behaviour for the plugin for Android platform.

**Comment by dreamcodestudio** [comment]
> > ![Solution](https://private-user-images.githubusercontent.com/114641115/306581895-0a3b4ed3-111b-4f8a-b744-71c19225ae31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTY2MjEsIm5iZiI6MTcwODUxNjMyMSwicGF0aCI6Ii8xMTQ2NDExMTUvMzA2NTgxODk1LTBhM2I0ZWQzLTExMWItNGY4YS1iNzQ0LTcxYzE5MjI1YWUzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQxMTUyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGJkZmE2YjY3YmVjNDY3OTlkMTVmZjA2NDEyMjJmYWZjZDNjMWUyODE1ZDhhNTBkZmU0YjI5MzZmMjVhYWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.omiYfG4WX65IObEFbfmfTgml3gKx9cFEUTFaXjYQ1lU) go to google mobile ads > Mediation > LiftoffMonetize >Plugins >Android > liftoffmonetize-unity-android-library then check all boxes as shown in pic ,Apply and get your build ..
> 
> You can see that Android platform **Excluded** Don't think that this is normal behaviour for the plugin for Android platform.

 i thinks not, because it exclude native adapter from mobile builds

**Comment by NVentimiglia** [comment]
Thanks for the updates, I was able to confirm the issue and engineering is looking into the issue.

**Comment by MuhammadWaqasOfficial** [comment]
@NVentimiglia is this issue is by liftoff mediation plugin 5.0.0 or admob? Just need to know so can skip 8.7 and wait for 8.7.1 or liftoff 5.0
Thanks

**Comment by dreamcodestudio** [comment]
> @NVentimiglia is this issue is by liftoff mediation plugin 5.0.0 or admob? Just need to know so can skip 8.7 and wait for 8.7.1 or liftoff 5.0
> Thanks

it's Liftoff adapter issue

**Comment by NVentimiglia** [comment]
I think this issue was Liftoff v5. I will be closing this issue. If this issue is not fixed on your end please reopen and tell me about your environment.

**Comment by shefich** [comment]
@NVentimiglia  The issue with [Liftoff v5](https://developers.google.com/admob/unity/mediation/liftoff-monetize#liftoff-monetize-unity-mediation-plugin-changelog) still exist.
Unity 2022.3.21
Admob 8.7.0
AppLovin 7.0.1
Mintegral 1.4.0
Unity Ads Legacy 3.9.0
Minimum API Level 22
Target API Level 34
Don't know how to reopen the issue.

**Comment by allenliuinvungle** [comment]
The issue still exist.  Please use my [project](https://drive.google.com/file/d/1H-Nopxj_3U1ffdnCOy5S3WkDaoDV1891/view?usp=sharing) to reproduce the issue @NVentimiglia

**Comment by daniel-valore** [comment]
I am facing this issue in my project!
My environment is very similar from @shefich.

**Comment by DiaoYung** [comment]
You had to downgrade back to 4.0.0
