### ISSUE TITLE
Wrong RewardBasedVideoAd OnAdFailedToLoad 

### ISSUE THREAD

**Issue by Deathwing** [googleads/googleads-mobile-unity#316]
I checked your code, and your code for RewardBasedVideoAd OnAdFailedToLoad is wrong (maybe copy paste error^^):
![grafik](https://cloud.githubusercontent.com/assets/2003861/20832184/15db93c4-b889-11e6-8676-ef8ea58efc4b.png)

**Comment by Deathwing** [comment]
The same is also for BannerAd.cs :)

**Comment by rampara** [comment]
Fixed in 87bb6b5b970b38e9fddc44cb1fa7523096adf1c0.
