### ISSUE TITLE
Allow us to to set App ID programmatically 

### ISSUE THREAD

**Issue by umar-hyatt** [googleads/googleads-mobile-unity#3170]
Issue:
I would like to request the ability to set the App ID programmatically in the Google Mobile Ads SDK. Currently, it seems that the App ID needs to be set in the AndroidManifest.xml file, and there is no provision for dynamically setting it in code.

**Comment by NVentimiglia** [comment]
Hi @umar-hyatt I agree this is a good feature request. This change is something that requires significant changes to the Android SDK. There is an invite to make this changes, but I do not expect it to land this year.

Closing this issue as intended, feel free to reopen if you have more details.

**Comment by RomainBitard** [comment]
Great idea, it used to be possible but it's not anymore, any plans ?
