### ISSUE TITLE
[UMP] Google User Messaging Platform: iOS app after reinstallation, the device hashed test id is reset

### ISSUE THREAD

**Issue by KarahanOnarlar** [googleads/googleads-mobile-unity#3179]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.35
  * Google Mobile Ads Unity plugin version: 8.6.0
  * Platform: iOS

### [REQUIRED] Step 2: Describe the problem
User Messaging Platform: Hashed test device id changes if the application is uninstalled and reinstalled. As a result, when testing flows such as UMP and ATT or when making changes, the unity build needs to be purchased twice. This is pure torture as the app has to be uninstalled to show ATT again. This problem does not exist on the Android side.

#### Steps to reproduce:
After getting the test device id during the first installation, uninstall the application and install it again. You will see that the test device ids are different.

**Comment by NVentimiglia** [comment]
In testing I was unable to confirm this behaviour. That said, the test device Id is not set by Google Mobile Ads or even Unity - it is issued by the device emulator. It is out of our control.
