### ISSUE TITLE
Ad mediation with Unity SDK

### ISSUE THREAD

**Issue by kgooble** [googleads/googleads-mobile-unity#318]
Is it possible to do ad mediation using the GoogleMobileAd Unity SDK (this project)? I have been trying to integrate the Vungle adapter but have had no success. I can get test interstitial ads to show up on my Android device, however the ads are only from Admob and none appear to be sent from Vungle. I don't see any exceptions or reference to Vungle in my logcat. Here's what I've tried:

- Downloaded the Vungle Android SDK & adapter from [here](https://support.vungle.com/hc/en-us/articles/207604108-QuickStart-Guide-for-AdMob-Mediation-Vungle-Android-)
- Placed the 3 JAR files and 1 AAR file from above in `Assets/Plugins/Android`
- Updated my project's `AndroidManifest.xml` file to include the activities & permissions mentioned in the above Vungle link
- My project's gradle file (in `build_output/app/build.gradle`) included an entry for Vungle which was `compile project(':VungleAdapter')`, but changing it to `compile(name:'VungleAdapter', 'ext':'aar')` made no difference.

Does anyone have any suggestions? Am I supposed to place the adapter/SDK in `Assets/Plugins/Android` or somewhere else? I haven't found any instructions on how to integrate ad mediation for Google Admob in Unity anywhere, any help would be greatly appreciated!

**Comment by pescode** [comment]
Yes it is possible, you can take a look at my project... feel free to use it!
[https://github.com/pescode/Unity5-Admob-with-Mediation](https://github.com/pescode/Unity5-Admob-with-Mediation)

**Comment by ericleich** [comment]
@kgooble some ideas:

1. Are you sure that Vungle is the preferred network in the mediation settings in the AdMob UI? If you are willing to share your ad unit ID, we can confirm.
2. Check the logcat for something like "Could not find adapter com.vungle.mediation..." or something similar. If that's the case, your ad unit is pointing to Vungle correctly, but the Vungle adapter is not included in the actual build.
3. It's possible Vungle is getting called first and the adapter is present, but the Vungle SDK isn't there, and so the adapter fails. Or Vungle failed to fetch an ad, and so the mediation request backfilled to AdMob.

**Comment by kgooble** [comment]
@pescode Thanks! I actually took a look at your project and tried to adapt what you did there to my project, but that didn't work. When I tried importing your plugin to a clean project and building that, the "Load interstitial" button crashed the app.

@ericleich Thanks for responding! Here are the answers to your questions:
1. Here is our ad unit ID, please check it: `ca-app-pub-2828729856183504/4874227074`
2. There is nothing in the logcat about vungle, I grepped for it but nothing showed up.
3. I still have Vungle on test mode, if that makes a difference. I'm pretty certain that I have both the adapter and the SDK in my project.

**Comment by rampara** [comment]
@kgooble I'm able to successfully request and display Vungle ads in the sample application included in this rep with the following steps:

1. Import latest version of Google Mobile Ads Unity plugin into sample application.
2. Open main scene in `Scripts`
3. Copy latest version of Vungle Adapter (VungleAdapter.aar) to `Assets/Plugins/Android` directory of sample application.
4. Copy latest version of Vungle SDK (vungle-publisher-adaptive-id-4.0.3.jar + 2 additional JARs) to `Assets/Plugins/Android` directory of sample application.
5. Add Vungle activities to Android manifest file at `Assets/Plugins/Android/GoogleMobileAdsPlugin/`
6. Change line 240 of `Scripts/GoogleMobileAdsDemoScript.cs` to use a vungle ad unit.

It's important to note that if your ad unit settings are configured is such as way that the CPM value for Vungle is hard-coded to a low value, AdMob ads will be deemed more valuable and served over Vungle mediated ads. You can use Ad network optimization to get more accurate CPM values from Vungle, or use a higher hard-coded CPM value for Vungle that is more reflective of their CPM rates.

**Comment by kgooble** [comment]
@rampara Thank you for the detailed steps! Unfortunately, when I attempted to do this on the HelloWorld sample project in this repository, I hit several snags:

1. I had to change the Android version in the Unity player settings to KitKat; the default, API 9, resulted in a manifest merge issue - the VungleAdapter.aar expects a minimum SDK version of 11. I figured I would change it to KitKat since that's what I use on my project.
2. I had to copy a `version.xml` and `values.xml` file into `Assets/Plugins/Android/GoogleMobileAdsPlugin/res/values`.
3. I had to add `<permission android:name="android.permission.INTERACT_ACROSS_USERS_FULL" android:protectionLevel="signature”/>` to the `Assets/Plugins/Android/GoogleMobileAdsPlugin/AndroidManifest.xml` file.

Even after taking these measures, I still ended up with an error when I opened the app (that caused it to crash immediately):
```
E/AndroidRuntime(12571): Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.ads.MobileAds
E/AndroidRuntime(12571):        at com.google.unity.ads.RewardBasedVideo$1.run(RewardBasedVideo.java:65)
E/AndroidRuntime(12571):        at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(12571):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(12571):        at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime(12571):        at android.app.ActivityThread.main(ActivityThread.java:5602)
E/AndroidRuntime(12571):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(12571):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(12571):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/AndroidRuntime(12571):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/AndroidRuntime(12571):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  605):   Force finishing activity com.beans.baz/com.unity3d.player.UnityPlayerActivity
```

I'm thinking that there must be some base difference in my Android setup that's causing these issues. I'm using Unity 5.4.2f1. My tools versions are:
- Android SDK Tools Rev 25.2.3
- Android SDK Platform-tools Rev 25.0.1
- Android Support Repository Rev 40
- Android Support Library Rev 23.2.1
- Google Play Services Rev 38
- Google Repository Rev 40

I'm not sure what else it could be at this point. I also tried taking the steps you described in my own project, including increasing the CPM for Vungle, but this did not make a difference.

**Comment by rampara** [comment]
Can you post the contents of your `Assets/Plugins/Android` directory?

**Comment by kgooble** [comment]
In the sample project, the contents are:

```
✔ ls -lR
total 2624
drwxr-xr-x  10 shahrin  staff   340B  7 Dec 11:05 GoogleMobileAdsPlugin/
-rw-r-----@  1 shahrin  staff   327B  7 Nov 19:01 GoogleMobileAdsPlugin.meta
-rw-r--r--@  1 shahrin  staff    29K  7 Dec 10:39 VungleAdapter.aar
-rw-r--r--   1 shahrin  staff   441B  7 Dec 10:40 VungleAdapter.aar.meta
-rw-r--r--@  1 shahrin  staff    28K  7 Dec 10:39 dagger-2.7.jar
-rw-r--r--   1 shahrin  staff   441B  7 Dec 10:40 dagger-2.7.jar.meta
-rw-r--r--@  1 shahrin  staff   2.4K  7 Dec 10:39 javax.inject-1.jar
-rw-r--r--   1 shahrin  staff   441B  7 Dec 10:40 javax.inject-1.jar.meta
-rw-r--r--@  1 shahrin  staff   1.2M  7 Dec 10:39 vungle-publisher-adaptive-id-4.0.3.jar
-rw-r--r--   1 shahrin  staff   441B  7 Dec 10:40 vungle-publisher-adaptive-id-4.0.3.jar.meta

./GoogleMobileAdsPlugin:
total 48
-rw-r-----  1 shahrin  staff   1.6K  7 Dec 11:05 AndroidManifest.xml
-rw-r-----@ 1 shahrin  staff   178B  7 Nov 19:01 AndroidManifest.xml.meta
drwxr-xr-x  4 shahrin  staff   136B  7 Dec 10:37 libs/
-rw-r-----@ 1 shahrin  staff   192B  7 Nov 19:01 libs.meta
-rw-r-----@ 1 shahrin  staff    39B  7 Nov 19:01 project.properties
-rw-r-----@ 1 shahrin  staff   175B  7 Nov 19:01 project.properties.meta
drwxr-xr-x  4 shahrin  staff   136B  7 Dec 10:52 res/
-rw-r--r--  1 shahrin  staff   191B  7 Dec 10:52 res.meta

./GoogleMobileAdsPlugin/libs:
total 88
-rw-r--r--@ 1 shahrin  staff    36K  7 Nov 19:01 unity-plugin-library.jar
-rw-r--r--@ 1 shahrin  staff   175B  7 Nov 19:01 unity-plugin-library.jar.meta

./GoogleMobileAdsPlugin/res:
total 8
drwxr-xr-x  6 shahrin  staff   204B  7 Dec 10:52 values/
-rw-r--r--  1 shahrin  staff   191B  7 Dec 10:52 values.meta

./GoogleMobileAdsPlugin/res/values:
total 32
-rw-r--r--  1 shahrin  staff   849B  7 Dec 10:52 values.xml
-rw-r--r--  1 shahrin  staff   174B  7 Dec 10:52 values.xml.meta
-rw-r--r--  1 shahrin  staff   132B  7 Dec 10:52 version.xml
-rw-r--r--  1 shahrin  staff   174B  7 Dec 10:52 version.xml.meta
```

**Comment by rampara** [comment]
Are you using the latest version of this plugin? Newer releases include the JarResolver library which should automatically copy required Google Play dependencies into the `Assets/Plugins/Android` directory of your project (which aren't present in the contents you posted). Once these dependencies are copied into your project you shouldn't need to add any other XML files or perform manifest changes (other than the ones required for Vungle).

You can manually force dependency resolution by selecting `Assets->Play Services Resolver->Android Resovler->Resolve Client Jars` in the Unity editor. If this operation fails, you should seem output in the Unity console indicating the reason.

**Comment by kgooble** [comment]
@rampara After resolving the client jars, the sample project worked! Thank you! I'm going to see if I can get my own project to work now.

**Comment by kgooble** [comment]
Just an update: Rewarded ads successfully load Vungle ads for me now. Thanks so much for the help!
