### ISSUE TITLE
[Android] Application Preferences Returns the wrong shared preferences instance for User Messaging Platform

### ISSUE THREAD

**Issue by KarahanOnarlar** [googleads/googleads-mobile-unity#3180]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.35
  * Google Mobile Ads Unity plugin version: 8.7.0
  * Platform: Android

### [REQUIRED] Step 2: Describe the problem
I don't understand why it is documented this way in the Google documents, but the shared preferences example where the User Messaging Platform SDK writes the data is not [PreferenceManager.getDefaultSharedPreferences(activity)](https://github.com/googleads/googleads-mobile-unity/blob/9638b2ba76e0466d4c96a0a48b2b8816f36e49ca/source/android-library/app/src/main/java/com/google/unity/ads/UnityApplicationPreferences.java#L31).

After much effort, I was able to find the real preference example. This needs to be fixed because we need to be able to read our consent statuses in order to set up our own front disclosure panels and comply with GDPR & Apple etc policies.
For example, in our case, we are using the pre-Att description panel, so we want ATT ourselves. And we need to apply ATT permission only if the necessary permissions have been granted. Otherwise, Apple rejects the update because another permission is requested even though the user does not give permission.

Since I am currently writing my own plugin, this is not a problem for me, but it is a problem for those who are not aware of it.

#### Relevant Code:
Here is the correct code. Apart from Unity, this also needs to be fixed in the Google documents for Android.
```
  public UnityApplicationPreferences(final Activity activity)
{
    defaultSharedPreferences = activity.getSharedPreferences(activity.getPackageName().concat("_preferences");
}
```

**Comment by NVentimiglia** [comment]
Hi @KarahanOnarlar 

I was not able to replicate this on Unity 2023 and plugin version 8.7.0.

I changed the hello world sample like this :

![image](https://github.com/googleads/googleads-mobile-unity/assets/125889/e33bd055-3e6b-4c28-8d05-e2041a75e52d)

And was able to retrieve the `IABTCF_PurposeConsents` value:

<img width="423" alt="image" src="https://github.com/googleads/googleads-mobile-unity/assets/125889/adba0453-27f3-4e59-83cd-325d31d7c843">

**Comment by KarahanOnarlar** [comment]
Hi @NVentimiglia 

Are we sure this is for the android platform and not ios because I tested it maybe dozens of times and the results were always empty. There is no problem on iOS side, only Android.

Let me also send you the screenshot of the shared pref code where the actual values I found by scraping the ump v2.2.0 SDK are set.
![Ekran görüntüsü 2024-03-06 030658](https://github.com/googleads/googleads-mobile-unity/assets/94073609/32eb280a-c9c0-490c-9874-82d35937a3d4)

**Comment by KarahanOnarlar** [comment]
This is the code that I detected and reached while watching logcat, thanks to the logs saying that the data was not found. The zzco.zza code I chose is the code in my previous message.
![image](https://github.com/googleads/googleads-mobile-unity/assets/94073609/460b49b4-53dc-452a-8c9c-bbae0783d712)

**Comment by NVentimiglia** [comment]
@KarahanOnarlar 

I just retested this on Unity 2021 and 2023 to rule out a difference in engines.

High level here is my understanding :

- UMP SDK runs consent process, writing the TCF string to Android Application Preferences.
- We use our ApplicationPreferences to read the Android Application Preferences TCF string.
- I ran the application twice per engine. The first time I consent, the second time I did not consent.
- When I consented I received back the `111...` string.
- When I did not consent I received back `0`.
- This is as expected as far as I can see.

The decompiled code is interesting, but to get this fixed I need clear replication steps.

**Comment by KarahanOnarlar** [comment]
@NVentimiglia This is really weird because I tried dozens of times with the exact same code contained in ApplicationPreferences and the results were all empty. Otherwise I wouldn't have spent so much time dealing with minified source code.

Although there are things I said before, all I know to reproduce is to build on the android device using ump sdk v2.2.0 and query the tcf string or isGdpr value. It works smoothly on iOS device, but the data is empty on Android.

**Comment by NVentimiglia** [comment]
@KarahanOnarlar 

Can you modify the helloworld sample app and link me to the fork / zip ?
