### ISSUE TITLE
[UMP] Release the User Messaging Platform SDK as a separate unity package

### ISSUE THREAD

**Issue by KarahanOnarlar** [googleads/googleads-mobile-unity#3181]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.35
  * Google Mobile Ads Unity plugin version: 8.7.0
  * Platform: iOS, Android, Unity Editor

### [REQUIRED] Step 2: Describe the problem
Release the User Messaging Platform sdk as a separate unity package for those using other mediation platforms such as Ironsource. It will make things easier for those who want to install UMP without installing the Admob SDK. It will make things easier for those who want to install UMP without installing the Admob SDK. It's frustrating to deal with this since Ironsource hasn't yet integrated ump into its sdk like Applovin.

Here are just the dependencies to speed things up if you want to do it.

#### Files:

1. [GoogleUmpDependencies.xml](https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/GoogleMobileAds/Editor/GoogleUmpDependencies.xml)
2. [Editor/Resources/Ump](https://github.com/googleads/googleads-mobile-unity/tree/main/source/plugin/Assets/GoogleMobileAds/Editor/Resources/Ump)

#### A copy of [MobileAds.RaiseAction(Action action)](https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/GoogleMobileAds/Api/MobileAds.cs) code should be created for ump like this:
Note: RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad) is the right place to set the SynchronizationContext. [It is called immediately after Awake and OnEnable](https://docs.unity3d.com/ScriptReference/RuntimeInitializeOnLoadMethodAttribute.html).
```
public class MainThreadEventExecuter
{
    private static SynchronizationContext _synchronizationContext;
    private static int? _unityMainThreadId;

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
    public static void Initialize()
    {
        _synchronizationContext ??= SynchronizationContext.Current;
        _unityMainThreadId ??= Thread.CurrentThread.ManagedThreadId;
    }
    public static void RaiseAction(Action action)
    {
        if (action == null) return;
        if (_synchronizationContext == null || Thread.CurrentThread.ManagedThreadId == _unityMainThreadId)
        {
            action();
            return;
        }
        _synchronizationContext.Post(state => action(), action);
    }
```

#### For Android:
Only two files are available at. They just need to be placed in the Plugins folder.

1. [UnityConsentForm.java](https://github.com/googleads/googleads-mobile-unity/blob/main/source/android-library/app/src/main/java/com/google/unity/ump/UnityConsentForm.java)
2. [UnityConsentFormCallback.java](https://github.com/googleads/googleads-mobile-unity/blob/main/source/android-library/app/src/main/java/com/google/unity/ump/UnityConsentFormCallback.java)

#### For iOS:
- [source/plugin/Assets/Plugins/Ump/iOS](https://github.com/googleads/googleads-mobile-unity/tree/main/source/plugin/Assets/Plugins/Ump/iOS)

Apart from these, extra dependencies on the Admob SDK are as follows.

I write with the codes I have parsed to help others. It is enough to create the GADUObjectCache.m & GADUObjectCache.h file as it is and the others as code files and put them in the plugins folder. If the Admob SDK is not removed along with the files in the plugins folder, conflicts will occur.

1. [GADUObjectCache.m](https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/Plugins/iOS/GADUObjectCache.m) & [GADUObjectCache.h](https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/Plugins/iOS/GADUObjectCache.h) => Dependency: All
2. [GADUTypes.h](https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/Plugins/iOS/GADUTypes.h) => Dependency: Only the following code
```
#import <Foundation/Foundation.h>

/// Base type representing a GADU* pointer.
typedef const void *GADUTypeRef;
```
3. [GADUInterface.m](https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/Plugins/iOS/GADUInterface.m) => Dependency: Only the following code
```
// Copyright 2014 Google Inc. All Rights Reserved.

#import "GADUObjectCache.h"
#import "GADUTypes.h"

#pragma mark - Other methods
/// Removes an object from the cache.
void GADURelease(GADUTypeRef ref) {
  if (ref) {
    GADUObjectCache *cache = GADUObjectCache.sharedInstance;
    [cache removeObjectForKey:[(__bridge NSObject *)ref gadu_referenceKey]];
  }
}
```
4. [GADUPluginUtil.h](https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/Plugins/iOS/GADUPluginUtil.h) => Dependency: Only the following code
```
// Copyright 2016 Google Inc. All Rights Reserved.

#import <Foundation/Foundation.h>

@interface GADUPluginUtil : NSObject

/// Returns the Unity view controller.
+ (UIViewController *)unityGLViewController;

@end
```
5. [GADUPluginUtil.m](https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/Plugins/iOS/GADUPluginUtil.m) => Dependency: Only the following code
```
// Copyright 2016 Google Inc. All Rights Reserved.

#import "GADUPluginUtil.h"

@implementation GADUPluginUtil

+ (UIViewController *)unityGLViewController {
  id<UIApplicationDelegate> appDelegate = [UIApplication sharedApplication].delegate;
  return appDelegate.window.rootViewController;
}

@end
```

**Comment by NVentimiglia** [comment]
Thanks @KarahanOnarlar 

He have considered releasing the UMP SDK on its own in the past. I will submit this feature request to engineering for consideration.

**Comment by NVentimiglia** [comment]
Submitted this feature request to Engineering, they are considering it. Closing the issue here.

**Comment by boldcatgames** [comment]
> Submitted this feature request to Engineering, they are considering it. Closing the issue here.

Hello! Any news?

**Comment by supergardener** [comment]
Hi, Any updates?

**Comment by NehirYigitKarahan** [comment]
> Submitted this feature request to Engineering, they are considering it. Closing the issue here.

@NVentimiglia Hi, is there any updates ?
