### ISSUE TITLE
Manual Ads Show after loading

### ISSUE THREAD

**Issue by litemesa** [googleads/googleads-mobile-unity#319]
Hi,
currently Ads shows immediately after loading.
Is it possible to add some flag to the AdRequest::Extras or some flag to the NativeExpressAdView::LoadAd() function, so it will load Ads but not show. In this case we will be able to call manually NativeExpressAdView::Show() when we need it.

For example, after game over we have time to prepare Ads, but we cannot do this and start loading Ads only when player goes to relevant screen, and here we have some delay, because if connection is slow, ads can load for 2 or 4 seconds, and players are looking on empty screen.

Cheers,
Eugene

**Comment by rampara** [comment]
Although no such functionality is directly supported, what you can do to have the same behavior is call `Hide()` on an ad before loading it, and call `Show()` at an appropriate time later. 

As an example:

```
// Preload native express ad 
NativeExpressAdView nativeExpressAdView = new NativeExpressAdView(
            "ca-app-pub-3940256099942544/1072772517",
            new AdSize(320, 150),
            AdPosition.Top);
nativeExpressAdView.Hide();
nativeExpressAdView.LoadAd(new AdRequest.Builder().Build());

...

// Show ad at an appropriate time later
nativeExpressAdView.Show();
```

**Comment by rampara** [comment]
Closing this issue due to non-response. If you're still having difficulty showing ads after they have loaded, please re-open this issue.

**Comment by litemesa** [comment]
Oh, sorry, I forgot to leave a comment: you workoraund works perfectly, thank you
