### ISSUE TITLE
[Android] Bottom banner position is wrong when portrait upside down with navigation bar displayed

### ISSUE THREAD

**Issue by YuuWoods** [googleads/googleads-mobile-unity#3190]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.20f1
  * Google Mobile Ads Unity plugin version: 8.7.0
  * Platform: Android
  * Platform OS version: Android 14
  * Any specific devices issue occurs on: Pixel 7 and Emulator
  * Mediation ad networks used, and their versions: none

#### Steps to reproduce:

Bottom banner position is wrong when portrait upside down with navigation bar displayed.

Not hide Setting
<img src="https://github.com/googleads/googleads-mobile-unity/assets/32125305/013ea90e-bcf1-4be5-bc81-1b416d66d603" width=33% height=33%>

Not hide Portrait
<img src="https://github.com/googleads/googleads-mobile-unity/assets/32125305/e342b0a1-2afa-4210-bf11-0aa7ad8bb131" width=10% height=10%>

Not hide PortraitUpsideDown
<img src="https://github.com/googleads/googleads-mobile-unity/assets/32125305/fac691f9-1b06-4c11-a050-c704493465c0" width=10% height=10%>

Hide Setting
<img src="https://github.com/googleads/googleads-mobile-unity/assets/32125305/3044e069-f6d3-4382-ad88-192b6881c70a" width=33% height=33%>

Hide Portrait
<img src="https://github.com/googleads/googleads-mobile-unity/assets/32125305/3b9e6846-e4bf-4c49-b3e9-3117abab2786" width=10% height=10%>

Hide PortraitUpsideDown
<img src="https://github.com/googleads/googleads-mobile-unity/assets/32125305/a4ea539f-d8c1-4216-ac72-14ebe30f19e7" width=10% height=10%>

##### Sample project
[admobtest.zip](https://github.com/googleads/googleads-mobile-unity/files/14471322/admobtest.zip)

The folders below have been emptied.
- admobtest > Assets > GoogleMobileAds
- admobtest > Library
- admobtest > Logs
- admobtest > obj > Debug

Admob App ID is empty.

**Comment by NVentimiglia** [comment]
@YuuWoods 

Thank you, I have sent this issue to engineering for fixing.

**Comment by NVentimiglia** [comment]
Bug is in the hands of engineering, closing this case here.
