### ISSUE TITLE
Android Resolving Dependencies Failed

### ISSUE THREAD

**Issue by zhouzhuli** [googleads/googleads-mobile-unity#3191]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.2.8
  * Google Mobile Ads Unity plugin version: 8.4.1
  * Platform: Unity Editor
  * Platform OS version: _____
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem
Running Gradle...

F:\Test Projects\Test Build\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "F:\Test Projects\Test Build\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=E:/Unity/2022.2.8f1/Editor/Data/PlaybackEngines/AndroidPlayer\SDK" "-PTARGET_DIR=F:\Test Projects\Test Build\Assets\Plugins\Android" "-PMAVEN_REPOS=https://maven.google.com/" "-PPACKAGES_TO_COPY=com.google.android.gms:play-services-ads:22.6.0;com.google.android.ump:user-messaging-platform:2.1.0" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=7.1.2"
Executing command: F:\Test Projects\Test Build\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "F:\Test Projects\Test Build\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=E:/Unity/2022.2.8f1/Editor/Data/PlaybackEngines/AndroidPlayer\SDK" "-PTARGET_DIR=F:\Test Projects\Test Build\Assets\Plugins\Android" "-PMAVEN_REPOS=https://maven.google.com/" "-PPACKAGES_TO_COPY=com.google.android.gms:play-services-ads:22.6.0;com.google.android.ump:user-messaging-platform:2.1.0" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=7.1.2"

Reporting analytics data: /androidresolver/resolve/gradle/failed/fetch?unityVersion=2022.2.8f1&unityPlatform=WindowsEditor&installSource=unitypackage&version=1.2.177&scope= 'Android Resolver: Gradle Resolve: Tool Extraction Failed'
ERROR: Gradle failed to fetch dependencies.

Failed to run 'F:\Test Projects\Test Build\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "F:\Test Projects\Test Build\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=E:/Unity/2022.2.8f1/Editor/Data/PlaybackEngines/AndroidPlayer\SDK" "-PTARGET_DIR=F:\Test Projects\Test Build\Assets\Plugins\Android" "-PMAVEN_REPOS=https://maven.google.com/" "-PPACKAGES_TO_COPY=com.google.android.gms:play-services-ads:22.6.0;com.google.android.ump:user-messaging-platform:2.1.0" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=7.1.2"'
stdout:

stderr:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'PlayServicesResolverGradle'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build.jetifier:jetifier-processor:1.0.+.
     Required by:
         project :
      > Failed to list versions for com.android.tools.build.jetifier:jetifier-processor.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-processor/maven-metadata.xml.
            > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-processor/maven-metadata.xml'.
               > Connect to 127.0.0.1:4780 [/127.0.0.1] failed: Connection refused: connect
      > Failed to list versions for com.android.tools.build.jetifier:jetifier-processor.
         > Unable to load Maven meta-data from https://repo.maven.apache.org/maven2/com/android/tools/build/jetifier/jetifier-processor/maven-metadata.xml.
            > Could not get resource 'https://repo.maven.apache.org/maven2/com/android/tools/build/jetifier/jetifier-processor/maven-metadata.xml'.
               > Could not GET 'https://repo.maven.apache.org/maven2/com/android/tools/build/jetifier/jetifier-processor/maven-metadata.xml'.
                  > Connect to 127.0.0.1:4780 [/127.0.0.1] failed: Connection refused: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s

exit code: 1
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by NVentimiglia** [comment]
@zhouzhuli

> Connect to 127.0.0.1:4780 [/127.0.0.1] failed: Connection refused: connect

This might be a firewall or proxy issue. I have experienced this in the past due to charles proxy running.

**Comment by zhouzhuli** [comment]
Thanks! How did you solve this problem? It doesn’t work even if the network
proxy is not turned on.
