### ISSUE TITLE
error CS0117: `System.Version' does not contain a definition for `Parse'

### ISSUE THREAD

**Issue by Prashant1011** [googleads/googleads-mobile-unity#3197]
I am getting the issue when import  GoogleMobileAds-v8.7.0 Package in Unity.

Assets/GoogleMobileAds/Editor/GoogleMobileAdsSettings.cs(31,39): error CS0117: `System.Version' does not contain a definition for `Parse'.

Step 1: Describe your environment

Unity version: 2018.4.25f1
Google Mobile Ads Unity plugin version: 8.7.0
Platform: Unity Editor
Platform OS version: Windows 11
.NET version  8.0.201

Step 2: Describe the problem

I am getting this issue for my old project.
If i create new Project it's worked fine.
Switch target platform to Android
In menu Assets, Google Mobile Ads Not showing
In Build Settings disabled Build App Bundle (Google Play)
In Player Settings assign a package name
Minimum API level 16, target API level Automatic (highest Installed)
Import GoogleMobileAds-v8.7.0.unitypackage
Getting Issue

![image](https://github.com/googleads/googleads-mobile-unity/assets/43678021/0ba7e28c-5a03-4673-a7a8-924b50bd77ce)

![image](https://github.com/googleads/googleads-mobile-unity/assets/43678021/df3c56ea-9033-4543-ad1f-b9cfbece26f8)

**Comment by NVentimiglia** [comment]
@Prashant1011 Please use Unity 2019.4 or higher.
