### ISSUE TITLE
UMP on iOS auto show when reopen game

### ISSUE THREAD

**Issue by phuongdmp7** [googleads/googleads-mobile-unity#3205]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.20 LTS
  * Google Mobile Ads Unity plugin version: 8.7.0
  * Platform: iOS (iOS, Android, Unity Editor)
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem
I do not call manually show UMP but when second game session UMP always auto show. 
How can i turn off this?

**Comment by NVentimiglia** [comment]
Hi @phuongdmp7 

UMP does nothing on its own, everything which UMP loads and shows is invoked from API calls. If you show your code, maybe I can help.

By default UMP shows on the first session in which you call it, which sounds like the second session in your case.
