### ISSUE TITLE
Conflicts with Play games plugin on iOS

### ISSUE THREAD

**Issue by marekdaniluk** [googleads/googleads-mobile-unity#321]
Latest versions of both plugins gives Unity build error:
```
Pod install failed. See the output below for details.

Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `GooglePlayGames (~> 5.0)` required by `Podfile`

Specs satisfying the `GooglePlayGames (~> 5.0)` dependency were found, but they required a higher minimum deployment target.

UnityEngine.Debug:LogError(Object)
Google.IOSResolver:Log(String, Boolean, LogLevel)
Google.IOSResolver:OnPostProcessInstallPods(BuildTarget, String)
UnityEditor.HostView:OnGUI()
```
You can reproduce this issue on clean project and trying to create xcode project from Unity.

**Comment by rampara** [comment]
@marekdaniluk are you using any other plugins that use the JarResolver library in your Unity project? Also, can you try setting the target minimum iOS value to a higher value in your player build settings?

**Comment by marekdaniluk** [comment]
@rampara no, only those two plugins. I imported them to new project using Unity 5.3.6p2 and Target minimum iOS version set to 6.0. I am afraid I am tied to this configuration.

**Comment by rampara** [comment]
Latest versions of both Google Mobile Ads and Google Play Games require an iOS 7.0 or higher deployment target.

**Comment by rampara** [comment]
Closing this issue due to non-response. Please re-open if this issue persists for you.
