### ISSUE TITLE
Interstitial ads not showing full screen on iPhone 6 Plus

### ISSUE THREAD

**Issue by birdkingz** [googleads/googleads-mobile-unity#322]
Happens on v3.1.3
Please check the attached screenshot:

https://drive.google.com/open?id=0B79FLKapSRPscTBoMVZWV1N5X0U

EDIT: Using Google Mobile Ads iOS SDK v7.15

**Comment by rampara** [comment]
Is this issue consistently reproducible for you? Are you able to capture a Charles log for an ad request where you see the incorrectly rendered interstitial?

**Comment by birdkingz** [comment]
Yes, every time the ads appear it will appear in this way.
Where/How can I capture a "Charles log"?

**Comment by rampara** [comment]
Can you provide me with the ad unit you are using to request interstitial ads? Also, the official [Charles](https://www.charlesproxy.com/documentation/) has documentation on how to setup a Charles proxy as well as collect logs.

**Comment by birdkingz** [comment]
It seems the ads is working fine now. 
I'm guessing maybe is the publisher site using the wrong image size as an ad.
