### ISSUE TITLE
Build Failed 

### ISSUE THREAD

**Issue by mubsharrehman1** [googleads/googleads-mobile-unity#3223]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.20
  * Google Mobile Ads Unity plugin version: 8.7.0
  * Platform: Android Unity Editor
  * Platform OS version: API 33
  * Mediation ad networks used, and their versions: 
  unity:4.9.2.0
  mintegral:16.6.34.0
  facebook:6.15.0.0
  applovin:12.1.0.1

### [REQUIRED] Step 2:  Build APK
Error
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 33

This Android Gradle plugin (7.1.2) was tested up to compileSdk = 32

This warning can be suppressed by adding
    android.suppressUnsupportedCompileSdk=33
to this project's gradle.properties
![error 1](https://github.com/googleads/googleads-mobile-unity/assets/163096327/209a97a2-8e1d-41b8-b845-216dea7c286b)

![error 2](https://github.com/googleads/googleads-mobile-unity/assets/163096327/6e9f2d89-d2b8-4f5a-9d62-549ba03b1977)

#### Steps to reproduce:

Build APK

CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity\Hub\Editor\2022.3.20f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK\bin\java.exe -classpath "C:\Program Files\Unity\Hub\Editor\2022.3.20f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-7.2.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

Environment Variables:
SHIM_MCCOMPAT = 0x810000001
PROCESSOR_ARCHITECTURE = AMD64
JAVA_HOME = C:\Program Files\Unity\Hub\Editor\2022.3.20f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK
AMPLITUDE_API_KEY_GREENBUCKET_PROD = c86fea37a9e1d3f0878b96e15b111c7c
DriverData = C:\Windows\System32\Drivers\DriverData
USERDOMAIN = DESKTOP-0F77OJF
CommonProgramFiles(x86) = C:\Program Files (x86)\Common Files
COMPUTERNAME = DESKTOP-0F77OJF
DEBUG_ENV_VAR = UnityHub
LOGONSERVER = \\DESKTOP-0F77OJF
AMPLITUDE_TOKEN_GREENBUCKET_PROD = yyzPzalJDwrQcYNuOZam0bhKb26WyyhK
AMPLITUDE_API_KEY_YELLOWBUCKET_DEV = 48835b4d1f5e342aefe5f016324d296a
ProgramData = C:\ProgramData
SESSIONNAME = Console
AMPLITUDE_TOKEN_YELLOWBUCKET_PROD = Ph-837Q6GNodAkyc2MRkxVPUcjlIET4d
NVIDIAWHITELISTED = 0x01
ALLUSERSPROFILE = C:\ProgramData
SystemRoot = C:\WINDOWS
windir = C:\WINDOWS
AMPLITUDE_API_KEY_REDBUCKET_DEV = 46b8b46515e7632fc42a504b72e05fd0
ProgramFiles(x86) = C:\Program Files (x86)
ProgramW6432 = C:\Program Files
OS = Windows_NT
PROCESSOR_IDENTIFIER = Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
HEAP_CLIENT_TOKEN_STAGING = 3786794399
HOMEPATH = \Users\MubsharRehman
FPS_BROWSER_USER_PROFILE_STRING = Default
AMPLITUDE_TOKEN_REDBUCKET_DEV = U4PSN7S7PuYVRODivvdcFwbu8R6IHGqa
CHROME_CRASHPAD_PIPE_NAME = \\.\pipe\crashpad_3892_LTWGGUAMXWWWXZJM
PROCESSOR_LEVEL = 6
JAVA_TOOL_OPTIONS = -Dfile.encoding=UTF-8
CommonProgramFiles = C:\Program Files\Common Files
ZES_ENABLE_SYSMAN = 1
PUBLIC = C:\Users\Public
USERDOMAIN_ROAMINGPROFILE = DESKTOP-0F77OJF
TEMP = C:\Users\MUBSHA~1\AppData\Local\Temp
ProgramFiles = C:\Program Files
CommonProgramW6432 = C:\Program Files\Common Files
AMPLITUDE_TOKEN_YELLOWBUCKET_DEV = wKi8foVigDditGFvmZewRFWsEbX9Y0YO
AMPLITUDE_API_KEY_GREENBUCKET_DEV = 3ded2a762163603391a425f688f990c8
AMPLITUDE_API_KEY_REDBUCKET_PROD = ca12bb461ea96f9bdf5df4ded7d52994
HOMEDRIVE = C:
AMPLITUDE_API_KEY_STAGING = 83ee04fccc67e4fcc7dd527c4c6f1e21
USERNAME = MubsharRehman
OneDrive = C:\Users\MubsharRehman\OneDrive
AMPLITUDE_API_KEY_YELLOWBUCKET_PROD = e03a9bbe92dc38a88cdb068d24c65b46
IGCCSVC_DB = AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAVFJKbQ9O3kCPZ94sr5DGbgQAAAACAAAAAAAQZgAAAAEAACAAAADUBnYgtKLFuROMmiYAzsr/x6ncLIdBtyaH6I2oWo5dVwAAAAAOgAAAAAIAACAAAAD0fTqL1funQPPE+54V7txNb3JtW3huG0CdVdAFQLwVgmAAAABco2/w8Cp6pqtHgyhoGnpYlyjj2fnJnxwWBi2KhmQ+5TrTRrI5QLv5Am/DdUS4Ov3KqrvZyNPp+gnIAudzrSVydH9gCI1XsjCse5XriWoJD1g0O7yLMY/WKC81yx5TrENAAAAA2P13GjncfcLE7AR1Mr4uJkn4YJBc+XU2kYb4lKMUT6WWD3ESjU0H7EbuWnQPe5I48y/D87XADC1YPYJLjr4guQ==
PATHEXT = .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
AMPLITUDE_TOKEN_REDBUCKET_PROD = QqyoFpcWPi7V17p80_46CF6-sNGRGbHo
NUMBER_OF_PROCESSORS = 8
AMPLITUDE_TOKEN_GREENBUCKET_DEV = 84H2gMm_FJzhr3mBaX1lM1JVukmCM7d9
AMPLITUDE_DEPLOYMENT_KEY_RED_BUCKET_DEV = client-wbjHYrmeSR87GmWOE7LDpf7sUySOIKHm
ComSpec = C:\WINDOWS\system32\cmd.exe
ORIGINAL_XDG_CURRENT_DESKTOP = undefined
EFC_8608 = 1
PROCESSOR_REVISION = 8c01
AMPLITUDE_DEPLOYMENT_KEY_RED_BUCKET_PROD = client-zH8Y7OK1i331EKuG77C6UxN8ygcM6LzS
TMP = C:\Users\MUBSHA~1\AppData\Local\Temp
SystemDrive = C:
AMPLITUDE_API_KEY = 28f3cae0b33b8b3702120c9ed1a935aa
FPS_BROWSER_APP_PROFILE_STRING = Internet Explorer
SENTRY_ACCESS_TOKEN = 3df78d9e53f8456aa90fbae044ce1a6261421ab1d0014674bc2e933477289017
HEAP_CLIENT_TOKEN = 1717415662
APPDATA = C:\Users\MubsharRehman\AppData\Roaming
Path = C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Users\MubsharRehman\AppData\Local\Microsoft\WindowsApps;C:\Users\MubsharRehman\AppData\Local\GitHubDesktop\bin;C:\Users\MubsharRehman\.dotnet\tools
PSModulePath = C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
LOCALAPPDATA = C:\Users\MubsharRehman\AppData\Local
USERPROFILE = C:\Users\MubsharRehman
WOOTRIC_CLIENT_TOKEN = NPS-aa8be4c3

stderr[
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> Could not resolve all files for configuration ':launcher:releaseRuntimeClasspath'.
   > Could not find com.google.firebase:firebase-analytics-unity:11.4.0.
     Required by:
         project :launcher > project :unityLibrary
   > Could not find com.google.firebase:firebase-app-unity:11.4.0.
     Required by:
         project :launcher > project :unityLibrary
   > Could not find com.google.firebase:firebase-config-unity:11.4.0.
     Required by:
         project :launcher > project :unityLibrary
   > Could not find com.mbridge.msdk.oversea:mbbid:16.6.34.
     Required by:
         project :launcher > project :unityLibrary > com.google.ads.mediation:mintegral:16.6.34.0
   > Could not find com.mbridge.msdk.oversea:reward:16.6.34.
     Required by:
         project :launcher > project :unityLibrary > com.google.ads.mediation:mintegral:16.6.34.0
   > Could not find com.mbridge.msdk.oversea:mbnative:16.6.34.
     Required by:
         project :launcher > project :unityLibrary > com.google.ads.mediation:mintegral:16.6.34.0
   > Could not find com.mbridge.msdk.oversea:mbbanner:16.6.34.
     Required by:
         project :launcher > project :unityLibrary > com.google.ads.mediation:mintegral:16.6.34.0
   > Could not find com.mbridge.msdk.oversea:newinterstitial:16.6.34.
     Required by:
         project :launcher > project :unityLibrary > com.google.ads.mediation:mintegral:16.6.34.0
   > Could not find com.mbridge.msdk.oversea:mbsplash:16.6.34.
     Required by:
         project :launcher > project :unityLibrary > com.google.ads.mediation:mintegral:16.6.34.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
]
stdout[
WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 33

This Android Gradle plugin (7.1.2) was tested up to compileSdk = 32

This warning can be suppressed by updating
    android.suppressUnsupportedCompileSdk=34,33
to this project's gradle.properties

The build will continue, but you are strongly encouraged to update your project to
use a newer Android Gradle Plugin that has been tested with compileSdk = 33
> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:validateDependencies UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :launcher:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:generateReleaseResValues UP-TO-DATE
> Task :launcher:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:generateReleaseResources UP-TO-DATE
> Task :launcher:writeReleaseApplicationId UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:generateReleaseResources UP-TO-DATE
> Task :launcher:analyticsRecordingRelease
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:packageReleaseResources UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseResources UP-TO-DATE
> Task :launcher:generateReleaseResValues UP-TO-DATE
> Task :launcher:createReleaseCompatibleScreenManifests UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:parseReleaseLocalResources UP-TO-DATE
> Task :launcher:extractDeepLinksRelease UP-TO-DATE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:parseReleaseLocalResources UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:processReleaseManifest UP-TO-DATE
> Task :launcher:extractProguardFiles UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:packageReleaseResources UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseRFile UP-TO-DATE
> Task :launcher:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:processReleaseManifest UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:parseReleaseLocalResources UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:processReleaseManifest UP-TO-DATE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:generateReleaseRFile UP-TO-DATE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseJavaWithJavac UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibCompileToJarRelease UP-TO-DATE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:generateReleaseRFile UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseNativeLibs NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:stripReleaseDebugSymbols NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:copyReleaseJniLibsProjectAndLocalJars UP-TO-DATE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:compileReleaseJavaWithJavac UP-TO-DATE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:bundleLibCompileToJarRelease UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:compileReleaseJavaWithJavac UP-TO-DATE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:bundleLibCompileToJarRelease UP-TO-DATE
> Task :unityLibrary:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:mergeReleaseNativeLibs NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:stripReleaseDebugSymbols NO-SOURCE
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:copyReleaseJniLibsProjectAndLocalJars UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:mergeReleaseNativeLibs NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:stripReleaseDebugSymbols NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:copyReleaseJniLibsProjectAndLocalJars UP-TO-DATE
> Task :launcher:checkReleaseDuplicateClasses FAILED
> Task :unityLibrary:packageReleaseResources UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:extractReleaseAnnotations UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:extractReleaseAnnotations
> Task :unityLibrary:com.voxelbusters.essentialkit.androidlib:extractReleaseAnnotations
> Task :unityLibrary:mergeReleaseNativeLibs

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings
52 actionable tasks: 5 executed, 47 up-to-date
]
exit code: 1

**Comment by NVentimiglia** [comment]
Hi @mubsharrehman1 

It looks like you are missing some android dependencies.

```
Could not find com.google.firebase:firebase-analytics-unity:11.4.0.
Could not find com.google.firebase:firebase-app-unity:11.4.0.
Could not find com.google.firebase:firebase-config-unity:11.4.0.
Could not find com.mbridge.msdk.oversea:mbbid:16.6.34.
```

Try making sure these dependencies are included using the external dependency manager or gradle manifest and try again.

**Comment by Spud6703** [comment]
I'm having this problem too when I try to build for Android (iOS builds fine). I'm using Unity 2022.3.21f1 and I'm using Google Firebase Analytics 11.2.0, Google Play Game Services 11.01 and Google Mobile Ads 8.7.0. I removed all three SDKs and put them back into the build one by one and discovered that the build error occurs when I add Google Mobile Ads. This happens with 8.6.0 too but I haven't had time to see if any earlier versions build okay. The above replay "Try making sure these dependencies are included using the external dependency manager or gradle manifest and try again" doesn't mean much to me. Can you please explain how to do that ? Using Unity to build an Android version is always a nightmare for me.

**Comment by NVentimiglia** [comment]
Hi @Spud6703 

Try exporting the project into an Android Studio project and looking at the dependencies (`UnityLibary/build.gradle`). It should be there. 

Also, have you tried [using gradle directly](https://developers.google.com/admob/unity/gradle). Firebase and Google Mobile Ads leverages the external dependency manager to fetch these dependencies. It is possible that something is going wrong there. Alternatively you can use a `Custom Base Gradle Template` which will tell EDM4U to use gradle.

**Comment by PetrBodnar** [comment]
May be related - we've got 404 for version 16.6.34 of mbbid, but 16.6.61 is ok:

https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea/com/mbridge/msdk/oversea/mbbid/16.6.34/mbbid-16.6.34.pom

https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea/com/mbridge/msdk/oversea/mbbid/16.6.61/mbbid-16.6.61.pom

**Comment by joshh-devrel** [comment]
@PetrBodnar 
Mintegral Android adapter 16.6.61.0 is now live: https://maven.google.com/web/index.html#com.google.ads.mediation:mintegral:16.6.61.0.

However, please note that the Mintegral Unity adapter hasn't been updated to depend on Android adapter 16.6.61.0 yet.

**Comment by NVentimiglia** [comment]
This should be fixed now. Updated to the latest and try again. If you have future issues please reopen this case.
