### ISSUE TITLE
Unity 2022.3.20f1 + GoogleMobileAds-v5.4.0 raised error `java.lang.ClassNotFoundException: com.google.android.gms.ads.AdRequest$Builder`

### ISSUE THREAD

**Issue by flixyudh** [googleads/googleads-mobile-unity#3226]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.20f1
  * Google Mobile Ads Unity plugin version: v5.4.0
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: Android 13 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: Xiaomi Redmi Note 10 Pro
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem

I just new in unity and I've a project downloaded from internet, but when I installing the apk, I got an error `java.lang.ClassNotFoundException: com.google.android.gms.ads.AdRequest$Builder`. 

##### What I've tried:

1. add `Custom Proguard File` (https://github.com/googleads/googleads-mobile-unity/issues/2458#issuecomment-1368886188)
2. tried to find `Force Resolved` in EDM4U as @NVentimiglia mentions https://github.com/googleads/googleads-mobile-unity/issues/2606#issuecomment-1498267792 but I didn't see it. Below is what I got when importing packages v5.4.0

<img width="290" alt="Screen Shot 2024-03-16 at 15 19 40" src="https://github.com/googleads/googleads-mobile-unity/assets/19633881/5e0f508e-daa3-40e4-8c10-2a7cf4db6bbc">

also I got an error in Unity Editor console everytime I tried to reopen the project. and the error occurs when `Google.VersionHandlerImpl_v1.2.161.dll` auto checked list `Editor` in `Selected platforms for plugin`.

> Assembly 'Assets/ExternalDependencyManager/Editor/Google.VersionHandlerImpl_v1.2.161.dll' will not be loaded due to errors:
Assembly name 'Google.VersionHandlerImpl' does not match file name 'Google.VersionHandlerImpl_v1.2.161'

is there any way to resolved the issue?

`adb logcat`

```
03-16 15:10:54.394 27595  3416 E Unity   : AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.AdRequest$Builder
03-16 15:10:54.396 27595  3416 E FileUtils: err open mi_exception_log errno=2
03-16 15:10:54.396 27595  3416 E FileUtils: err write to mi_exception_log
03-16 15:10:54.402  1880  3474 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
03-16 15:10:54.402  1880  4333 W ActivityTaskManager:   Force finishing activity com.dotmob.waterpuzzle/com.unity3d.player.UnityPlayerActivity
03-16 15:10:54.402  1880  2398 W RescuePartyPlus: This device support and enable RescuePartyPlus! (Via cloud control)
03-16 15:10:54.405  1880  4333 D WindowManager: wms.Input focus has changed to null display=0 updateInputWindows = true
03-16 15:10:54.410  6304  6664 D DigestGenerator: digest=============com.dotmob.waterpuzzlejava.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/MobileAds;
03-16 15:10:54.410  6304  6664 D DigestGenerator: at com.google.unity.ads.RewardBasedVideo$.run(RewardBasedVideo.java:XX)
03-16 15:10:54.410  6304  6664 D DigestGenerator: at android.os.Handler.handleCallback(Handler.java:XX)
03-16 15:10:54.410  6304  6664 D DigestGenerator: at android.os.Handler.dispatchMessage(Handler.java:XX)
03-16 15:10:54.410  6304  6664 D DigestGenerator: at android.os.Looper.loopOnce(Looper.java:XX)
03-16 15:10:54.410  6304  6664 D DigestGenerator: at android.os.Looper.loop(Looper.java:XX)
03-16 15:10:54.410  6304  6664 D DigestGenerator: at android.app.ActivityThread.main(ActivityThread.java:XX)
03-16 15:10:54.410  6304  6664 D DigestGenerator: at java.lang.reflect.Method.invoke(Native Method)
03-16 15:10:54.410  6304  6664 D DigestGenerator: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:XX)
03-16 15:10:54.410  6304  6664 D DigestGenerator: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:XX)
03-16 15:10:54.410  6304  6664 D DigestGenerator: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.MobileAds" on path: DexPathList[[zip file "XXbase.apk!/lib/arm-va, /system/lib /system_ext/lib]]
03-16 15:10:54.410  6304  6664 D DigestGenerator: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:XX)
03-16 15:10:54.410  6304  6664 D DigestGenerator: at java.lang.ClassLoader.loadClass(ClassLoader.java:XX)
03-16 15:10:54.410  6304  6664 D DigestGenerator: at java.lang.ClassLoader.loadClass(ClassLoader.java:XX)
```

**Comment by NVentimiglia** [comment]
@flixyudh 

- When you import with EDM4U the files downloaded go into `Plugins/Android`, share that folder.
- Are there any errors when running Android Resolve in EDM4U ?
- `com.google.android.gms.ads.AdRequest$Builder` sounds like you are not including the main gms.ads package (which is very strange).
- The latest should be using EDM 1.2.177, try reinstalling the plugin and edm4u.

**Comment by NVentimiglia** [comment]
@flixyudh 

I would like to confirm this issue is caused by upgrading the plugin and that uninstalling and reinstalling the plugin fixed the issue.
