### ISSUE TITLE
Why Fill rate of Reward Admob is too Low?

### ISSUE THREAD

**Issue by ForestJungle** [googleads/googleads-mobile-unity#323]
Hello Admob Team.I integrated Vungle and Unity ads via Reward Admob.at this time Video only show unity ads without don't have Vungle.
I wanna why fill rate of admob is too low?I send request 1000 times but impression very low.
![image](https://cloud.githubusercontent.com/assets/21006187/21285676/d59c700e-c471-11e6-901c-62bd69f99df0.png)

**Comment by rampara** [comment]
This issue tracker is meant for bugs and feature requests specific to the Google Mobile Ads Unity plugin. The Google Mobile Ads [support forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) would be a more appropriate place to get support for low fill rate .
