### ISSUE TITLE
interstitials wont show at fullscreen when 'render outside safe area' is on

### ISSUE THREAD

**Issue by wenderRondonia** [googleads/googleads-mobile-unity#3235]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.22f1
  * Google Mobile Ads Unity plugin version: 8.7.0
  * Platform: Android
  * Platform OS version:  Android 12

### [REQUIRED] Step 2: Describe the problem

Interstitial Ads not showing full screen when "render outside safe area" is on.
Received an warning form google to fix it , had to turn it off.

Steps:
Toggling on "render outside safe area" at PlayerSettings/Resolution and Presentation

**Comment by NVentimiglia** [comment]
@wenderRondonia 

I am not seeing this issue on testing. Can you submit a bug ticket to [Sdk Support](https://developers.google.com/admob/support). Include an image of what you are seeing. If you can specific to the device(s) you see this on, that would be helpful.
