### ISSUE TITLE
Compile error with Liftoff Monetize Unity Mediation Plugin 5.0.0 package  at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:115)  ... 115 moreCaused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null  at com.android.tools.r8.graph.W0.<init>(SourceFile:5)  at

### ISSUE THREAD

**Issue by allenliuinvungle** [googleads/googleads-mobile-unity#3236]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: _____
  * Google Mobile Ads Unity plugin version: _8.6.0 or 8.7.0___
  * Platform: ____Android_ (iOS, Android, Unity Editor)
  * Platform OS version: __Android13___ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _No____
  * Mediation ad networks used, and their versions: _GoogleMobileAdsVungleMediation.unitypackage  5.0.0____

### [REQUIRED] Step 2: Describe the problem
The compile error shown below(txt and image)
[log.txt](https://github.com/googleads/googleads-mobile-unity/files/14681079/log.txt)

<img width="1817" alt="image" src="https://github.com/googleads/googleads-mobile-unity/assets/53548048/637d5d94-db58-4acc-b79b-9fcafd4c997b">

#### Steps to reproduce:
Please use my Android project or use my Unity project to build it, you will see the issue.

- https://drive.google.com/file/d/1H-Nopxj_3U1ffdnCOy5S3WkDaoDV1891/view?usp=sharing     android project
- https://github.com/AllenLiu20210507/Admob-Vungle-Unity  Unity project,

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

**Comment by allenliuinvungle** [comment]
Unity version is  2022.3.15

**Comment by MuhammadWaqasOfficial** [comment]
Liftoff 5.0 has compatibility issue with 8.7 and 8.6.
Downgrade to 4.0 or remove liftoff

**Comment by NVentimiglia** [comment]
Hi @allenliuinvungle 

I confirmed the issue and will get a fix out.

**Comment by allenliuinvungle** [comment]
@NVentimiglia   Hi How is the issue now? Any update now?

**Comment by NVentimiglia** [comment]
@allenliuinvungle This issue is market as fixed on my end. Closing issue. If you see this issue again, please reopen!
