### ISSUE TITLE
AdBehaviour.ResumeGame() change time scale

### ISSUE THREAD

**Issue by chef-cengiz** [googleads/googleads-mobile-unity#3259]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.13
  * Google Mobile Ads Unity plugin version: 9.0.0
  * Platform: iOS, Android, Unity Editor
  * Platform OS version: iOS 12+, Android 7+
  * Any specific devices issue occurs on: -
  * Mediation ad networks used, and their versions: -

### [REQUIRED] Step 2: Describe the problem
In my game my time scale is 2.5, when I show Interstitial or Rewarded ads the time scale is 0. this is not a problem. However, when these ads are closed, the time scale automatically becomes 1. But I want it to be 2.5. When I listen to the Close events and set it to 2.5, what I want doesn't happen. Afterwards, the ResumeGame in AdBehaviour runs. And time scale set 1.
I think we can solve our problem if the timescale parameter is added to GoogleMobileAdsSettings and its default value is 1.

I use VContainer, MessagePipe, UniTask

[goggleadsexternal.unitypackage.zip](https://github.com/googleads/googleads-mobile-unity/files/14811614/goggleadsexternal.unitypackage.zip)

**Comment by NVentimiglia** [comment]
I see the problem [here](https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/GoogleMobileAds/Platforms/Unity/AdBehaviour.cs#L28). I will let engineering know about this issue. That said, this issue is __Unity Editor__ only and will not affect Android or iOS playtime.
