### ISSUE TITLE
Banner ad clipped

### ISSUE THREAD

**Issue by spixy** [googleads/googleads-mobile-unity#326]
Hi, I am using responsive banner ad with
`new AdSize((int)(115200 / Screen.dpi), (int)(18000 / Screen.dpi))`
(its default banner size 350x50 but scaled with DPI)

But sometimes the ad content is clipped like this:
![admob](https://cloud.githubusercontent.com/assets/4542110/21500232/271628ee-cc3d-11e6-94a7-5d476cac6e20.jpg)

Is it problem in unity plugin or in AdMob or did I use not supported banner size? Im using Unity 5.5

**Comment by rampara** [comment]
Are you seeing this issue across all banners or only for certain requests? Are you able capture a Charles log for an ad request where you run into this issue?

**Comment by rampara** [comment]
Closing this issue due to the lack of response. If this problem still persists for you please re-open the issue.
