### ISSUE TITLE
Errors When Importing Package

### ISSUE THREAD

**Issue by nobby3344** [googleads/googleads-mobile-unity#3269]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.20
  * Google Mobile Ads Unity plugin version: 9.0.0
  * Platform: Unity editor
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem
I encountered two errors when importing the Google Mobile Ads package:

"Instance of GridPaintingState couldn't be created. The script class needs to derive from ScriptableObject."
"ScriptableSingleton already exists. Did you query the singleton in a constructor?"

I can successfully build in Unity, but encounter failures in Xcode. I tried in a new project, but the same error occurs.
<img width="1280" alt="ScreenShot" src="https://github.com/googleads/googleads-mobile-unity/assets/165957450/bea30864-be7d-444f-8845-8b83148ab38e">

**Comment by NVentimiglia** [comment]
@nobby3344 We do not include a `GridPaintingState` in our plugin. This error is probably caused by another plugin (naming conflict). At a minimum can you include the full stack trace of the error  or Editor Log ?

**Comment by nobby3344** [comment]
Thank you for your reply. Log below is the error logs.

Instance of GridPaintingState couldn't be created. The the script class needs to derive from ScriptableObject.
 #0 GetStacktrace(int)
 #1 DebugStringToFile(DebugStringToFileData const&)
 #2 ManagedMonoBehaviourRef::IsManagedClassCompatible(MonoScript*, ScriptingClassPtr)
 #3 SerializableManagedRef::FindMonoScriptFromClass(ScriptingClassPtr)
 #4 SerializableManagedRef::SetClass(Object*, ScriptingClassPtr, ScriptingObjectPtr)
 #5 Scripting::CreateScriptableObjectWithType(ScriptingSystemTypeObjectPtr, bool, ScriptingExceptionPtr*)
 #6 ScriptableObject_CUSTOM_CreateScriptableObjectInstanceFromType(ScriptingBackendNativeObjectPtrOpaque*, unsigned char)
 #7  (Mono JIT Code) (wrapper managed-to-native) UnityEngine.ScriptableObject:CreateScriptableObjectInstanceFromType (System.Type,bool)
 #8  (Mono JIT Code) [ScriptableObject.bindings.cs:36] UnityEngine.ScriptableObject:CreateInstance (System.Type)
 #9  (Mono JIT Code) [ScriptableObject.bindings.cs:41] UnityEngine.ScriptableObject:CreateInstance<T_REF> ()
 #10  (Mono JIT Code) [ScriptableSingleton.cs:109] UnityEditor.ScriptableSingleton`1<T_REF>:CreateAndLoad ()
 #11  (Mono JIT Code) [ScriptableSingleton.cs:74] UnityEditor.ScriptableSingleton`1<T_REF>:get_instance ()
 #12  (Mono JIT Code) [GridPaintingState.cs:643] UnityEditor.Tilemaps.GridPaintingState:get_savingPalette ()
 #13  (Mono JIT Code) [GridPaintPaletteClipboard.cs:1523] UnityEditor.Tilemaps.GridPaintPaletteClipboard/PaletteAssetModificationProcessor:SavePalettesIfRequired (string[])
 #14  (Mono JIT Code) [GridPaintPaletteClipboard.cs:1518] UnityEditor.Tilemaps.GridPaintPaletteClipboard/PaletteAssetModificationProcessor:OnWillSaveAssets (string[])
 #15  (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_object_object (object,intptr,intptr,intptr)
 #16 mono_jit_runtime_invoke
 #17 do_runtime_invoke
 #18 mono_runtime_try_invoke_array
 #19 ves_icall_InternalInvoke
 #20 ves_icall_InternalInvoke_raw
 #21  (Mono JIT Code) (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo:InternalInvoke (System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
 #22  (Mono JIT Code) System.Reflection.RuntimeMethodInfo:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
 #23  (Mono JIT Code) System.Reflection.MethodBase:Invoke (object,object[])
 #24  (Mono JIT Code) [AssetModificationProcessor.cs:165] UnityEditor.AssetModificationProcessorInternal:OnWillSaveAssets (string[],string[]&,string[]&,bool)
 #25  (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_void_object_intptr&_intptr&_byte (object,intptr,intptr,intptr)
 #26 mono_jit_runtime_invoke
 #27 do_runtime_invoke
 #28 mono_runtime_invoke
 #29 scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool)
 #30 ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)
 #31 Scripting::UnityEditor::AssetModificationProcessorInternalProxy::OnWillSaveAssets(ScriptingArrayPtr, ScriptingObjectPtr*, ScriptingObjectPtr*, bool, ScriptingExceptionPtr*)
 #32 AssetModificationCallbacks::ShouldSaveSingleFile(core::basic_string<char, core::StringStorageDefault<char>> const&)
 #33 WriteYamlString(core::basic_string<char, core::StringStorageDefault<char>> const&, core::basic_string<char, core::StringStorageDefault<char>> const&, unsigned int)
 #34 WriteTextMetaFile(UnityGUID const&, bool, UnityGUID const&, AssetTimeStamp&, dynamic_array<core::basic_string<char, core::StringStorageDefault<char>>, 0ul> const&, AssetImporter*, AssetDatabase::ImporterID const&)
 #35 WriteImportSettingsIfDirtyV2(AssetImporter*, UnityGUID const&)
 #36 RefreshInternalV2(AssetDatabase::UpdateAssetOptions, ScanFilter const&, InternalRefreshFlagsV2)
 #37 StopAssetImportingV2Internal(AssetDatabase::UpdateAssetOptions, InternalRefreshFlagsV2, ScanFilter const*, char const*)
 #38 RefreshV2(AssetDatabase::UpdateAssetOptions)
 #39 AssetDatabase::Refresh(AssetDatabase::UpdateAssetOptions)
 #40 ImportPackageAssets(core::basic_string<char, core::StringStorageDefault<char>> const&, dynamic_array<ImportPackageItem, 0ul> const&)
 #41 TickPackageImport()
 #42 Application::TickTimer()
 #43 -[EditorApplication TickTimer]
 #44 __NSFireTimer
 #45 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
 #46 __CFRunLoopDoTimer
 #47 __CFRunLoopDoTimers
 #48 __CFRunLoopRun
 #49 CFRunLoopRunSpecific
 #50 RunCurrentEventLoopInMode
 #51 ReceiveNextEventCommon
 #52 _BlockUntilNextEventMatchingListInModeWithFilter
 #53 _DPSNextEvent
 #54 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
 #55 -[NSApplication run]
 #56 NSApplicationMain
 #57 EditorMain(int, char const**)
 #58 main
 #59 start

ScriptableSingleton already exists. Did you query the singleton in a constructor?
 #0 GetStacktrace(int)
 #1 DebugStringToFile(DebugStringToFileData const&)
 #2 DebugLogHandler_CUSTOM_Internal_Log(LogType, LogOption, ScriptingBackendNativeStringPtrOpaque*, ScriptingBackendNativeObjectPtrOpaque*)
 #3  (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
 #4  (Mono JIT Code) [DebugLogHandler.cs:10] UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
 #5  (Mono JIT Code) [Logger.cs:61] UnityEngine.Logger:Log (UnityEngine.LogType,object)
 #6  (Mono JIT Code) [Debug.bindings.cs:130] UnityEngine.Debug:LogError (object)
 #7  (Mono JIT Code) [ScriptableSingleton.cs:84] UnityEditor.ScriptableSingleton`1<T_REF>:.ctor ()
 #8  (Mono JIT Code) [GridPaintingState.cs:92] UnityEditor.Tilemaps.GridPaintingState:.ctor ()
 #9  (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
 #10 mono_jit_runtime_invoke
 #11 do_runtime_invoke
 #12 mono_runtime_invoke
 #13 mono_runtime_invoke_profiled(MonoMethod*, ScriptingObjectPtr, void**, MonoException**, MonoClass*)
 #14 mono_runtime_object_init_exception(ScriptingObjectPtr, ScriptingCtorCache*, MonoException**)
 #15 scripting_unity_engine_object_new_and_invoke_default_constructor(ScriptingClassPtr, Object*, ScriptingExceptionPtr*)
 #16 SerializableManagedRef::RebuildMonoInstance(Object*, ScriptingClassPtr, ScriptingObjectPtr, MonoScript*)
 #17 void SerializableManagedRefTransfer::RestoreBackup<SerializableManagedRefBackupGenerator>(Object*, SerializableManagedRef&, IManagedObjectHost::EBackupStage, TransferInstructionFlags)
 #18 SerializableManagedRefsUtilities::RestoreBackups(DomainReloadingData const&)
 #19 MonoManager::FinalizeReload()
 #20 ScriptingInitializer::FinalizeReload()
 #21 RefreshInternalV2(AssetDatabase::UpdateAssetOptions, ScanFilter const&, InternalRefreshFlagsV2)
 #22 StopAssetImportingV2Internal(AssetDatabase::UpdateAssetOptions, InternalRefreshFlagsV2, ScanFilter const*, char const*)
 #23 RefreshV2(AssetDatabase::UpdateAssetOptions)
 #24 AssetDatabase::Refresh(AssetDatabase::UpdateAssetOptions)
 #25 ImportPackageAssets(core::basic_string<char, core::StringStorageDefault<char>> const&, dynamic_array<ImportPackageItem, 0ul> const&)
 #26 TickPackageImport()
 #27 Application::TickTimer()
 #28 -[EditorApplication TickTimer]
 #29 __NSFireTimer
 #30 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
 #31 __CFRunLoopDoTimer
 #32 __CFRunLoopDoTimers
 #33 __CFRunLoopRun
 #34 CFRunLoopRunSpecific
 #35 RunCurrentEventLoopInMode
 #36 ReceiveNextEventCommon
 #37 _BlockUntilNextEventMatchingListInModeWithFilter
 #38 _DPSNextEvent
 #39 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
 #40 -[NSApplication run]
 #41 NSApplicationMain
 #42 EditorMain(int, char const**)
 #43 main
 #44 start

**Comment by nobby3344** [comment]
Thank you for your advice. However, this error occurs when I import the package just after creating a new 2D mobile project. Do you have any idea what "GridPaintingState" is?

**Comment by dpravity** [comment]
I have the same issue.
Have you solved the problem?

**Comment by nobby3344** [comment]
Unfortunately no. I also asked directly to Google Ads, but couldn't solve
the problem.

2024年8月1日(木) 21:28 dpravity ***@***.***>:

**Comment by hehe605715432** [comment]
我也遇到了相同的错误，解决这个问题只需要新建一个3d buildin项目即可

**Comment by LouisDeGIt** [comment]
I have the exact same error when i import GoogleMobileAds, did someone find a way to fix this?

**Comment by madchick** [comment]
I had same issues, and following was worked.
1. close unity editor
2. delete Library folder
3. reopen the project
