### ISSUE TITLE
Android build starts fail after adding Google Ads to project

### ISSUE THREAD

**Issue by DenisK-Voodoo** [googleads/googleads-mobile-unity#3271]
Android build starts fail after adding Google Ads with all requirements from Getting Started

  * Unity version: 2021.3.17f1 (Silicon)
  * Google Mobile Ads Unity plugin version: 9.0.0
  * Platform: Android
  * Mediation ad networks used, and their versions: none

To solve this issue I needed to do some actions.

1. Adding lines to mainTemplate.gradle:
```
gradle.projectsEvaluated {
    apply from: 'GoogleMobileAdsPlugin.androidlib/validate_dependencies.gradle'
}
```
2. Increasing Min API Level to Android 7.0 (24) instead of recommended 21 from [Getting Started](https://developers.google.com/admob/unity/quick-start)

Is it possible to include to next version + update documentation?

**Comment by NVentimiglia** [comment]
@DenisK-Voodoo do you have an error / failure message?

**Comment by DenisK-Voodoo** [comment]
Unfortunately I can't copy it know, but it was typical gradle errors in console. Message helped to find solutions by similar problems on internet with few other packages but I can't say it obvious and straight forward.

**Comment by Iterbit** [comment]
This happens to me too in an empty project that compiled before adding GoogleMobileAds 9.0.0.

This is Error Log. I'm on Unity 2022.3.19f1

[error.1.txt](https://github.com/googleads/googleads-mobile-unity/files/15015848/error.1.txt)
[error2.txt](https://github.com/googleads/googleads-mobile-unity/files/15015849/error2.txt)

**Comment by NVentimiglia** [comment]
Closing, feel free to reopen if you have a log that I can look at.
