### ISSUE TITLE
Ad Inspector Black Screen Issue

### ISSUE THREAD

**Issue by tomurtogu** [googleads/googleads-mobile-unity#3279]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.2.48f1
  * Google Mobile Ads Unity plugin version: 9.0
  * Platform: Android
  * Platform OS version: Android 10, Android 13
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: AppLovin Meta
  * 
### [REQUIRED] Step 2: Describe the problem
Whether run by code or gesture, the Ad Inspector opens as a black screen with only a close button.

#### Steps to reproduce:
Open Ad inspector with code or gesture.

![ad-inspector (2)](https://github.com/googleads/googleads-mobile-unity/assets/68553713/e3d3ac11-7e71-45d8-885a-f2473f454966)

**Comment by NVentimiglia** [comment]
@tomurtogu 

Can you include a logcat of your session when this happens?

**Comment by tomurtogu** [comment]
I don't know if it's related, but after I changed the Ad inspector gesture settings to "Shake", the problem was fixed. There was no error in the logs during the black screen.

**Comment by tomurtogu** [comment]
I don't know if it's related, but after I changed the Ad inspector gesture settings to "Shake", the problem was fixed. There was no error in the logs during the black screen.

**Comment by shafaqat012** [comment]
i am having same issue?how to fix

**Comment by ankitChandora** [comment]
I'm also facing this issue very frequently. I've also tried opening using "Shake" gesture. But still same issue

**Comment by DeveshAnarchy** [comment]
Facing the same issue, Have you guys found any solution for this? I am using version 11.3.0
