### ISSUE TITLE
Debug Log functions are not working from callbacks

### ISSUE THREAD

**Issue by GameSeekerAtlas** [googleads/googleads-mobile-unity#328]
None of Debug Log methods are working if called from EventHandler.
inherited Debug Log methods are not working too.

````

using System;
using UnityEngine;
using UnityEngine.Events;
using GoogleMobileAds.Api;

public class InterstitialAdmob : MonoBehaviour
{
    public string idPlatform = "ca-app-pub-xxxxxxxxxxxx/xxxxxxxxxxx"; //Test ads id

    private InterstitialAd advertisement;
    private AdRequest request;


    #region Init
    private void Start()
    {
        if (idPlatform == null) return;

        advertisement = new InterstitialAd(idPlatform);
        advertisement.OnAdLoaded += OnLoaded;
    }

    private void OnDestroy()
    {
        advertisement.OnAdLoaded -= OnLoaded;
    }
    #endregion




    #region PublicMethods
    public void LoadAd()
    {
        Debug.Log("LoadAd:"); //working
        request = new AdRequest.Builder().Build();
        request.TestDevices.Add(AdRequest.TestDeviceSimulator);
        advertisement.LoadAd(request);
    }

    public void ShowAd()
    {
        Debug.Log("ShowAd"); //working
        if (!advertisement.IsLoaded()) return;
        advertisement.Show();
    }
    #endregion





    #region Callbacks
    public UnityEvent onLoaded;
    private void OnLoaded(object sender, EventArgs args)
    {
        Debug.Log("OnLoaded");    //Not Working
        onLoaded.Invoke();    //Partially Working (Not Debug Log again)
       //CustomDebug.Log("OnLoaded");     //Partially Working (Not Debug Log again)
    }
    #endregion


}

````

**Comment by rampara** [comment]
What platform are you deploying your Unity app to ? Did a quick test with the [sample app](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) included in this repo and the `MonoBehaviour.print()` (should be identical to `Debug.Log`) calls from ad event EventHandlers are working without issue for me on both iOS and Android.

**Comment by GameSeekerAtlas** [comment]
it is not a big deal but still can't manage to work Debug.Log() with debughandler from callbacks.
[drive link](https://drive.google.com/open?id=0B1exfgPdvHaxaTNmejRMb2dHQm8)

**Comment by rampara** [comment]
Using the project you linked, I'm seeing log output (under the `Unity` tag in logcat) from the ad loaded callbacks without issue. What platform (iOS or Android) are you seeing this issue on?

**Comment by GameSeekerAtlas** [comment]
unity 5.5.0f3
android x86 device
there is no outputs from helloworld sample too.

maybe that problem is about my setup.
thanks for looking, i workaround that with custom onsceen debug.
you may close this, or if you want more information i can support.

**Comment by rampara** [comment]
Closing the issue as it's not reproducible.
