### ISSUE TITLE
unity android putPublisherFirstPartyIdEnabled' signature='(Z)V' in class Ljava.lang.Object;

### ISSUE THREAD

**Issue by chengwenpo** [googleads/googleads-mobile-unity#3290]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: ___2021.2.30f1__
  * Google Mobile Ads Unity plugin version: ___9.0.0__
  * Platform: ___Android__ (iOS, Android, Unity Editor)
  * Platform OS version: ___Android12__ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: ___any__
  * Mediation ad networks used, and their versions: ___any__

#### Steps to reproduce:

1.Integration Unity plugin version 9.0.0
2.Set RequestConfiguration .PublisherFirstPartyIdEnabled before MobileAds.SetRequestConfiguration
3.Build android apk
4.Start app
5.Error:
java.lang.NoSuchMethodError: no static method with name='putPublisherFirstPartyIdEnabled' signature='(Z)V' in class Ljava.lang.Object;
stack traceback:
UnityEngine._AndroidJNIHelper:GetMethodID(IntPtr, String, String, Boolean)                                                                                                    UnityEngine.AndroidJavaObject:_CallStatic(String, Object[])
GoogleMobileAds.Android.MobileAdsClient:SetRequestConfiguration(RequestConfiguration)

#### Relevant Code:

```
RequestConfiguration requestConfiguration = new RequestConfiguration();
requestConfiguration.PublisherFirstPartyIdEnabled = true;
...
MobileAds.SetRequestConfiguration(requestConfiguration);
```

#### Maybe the reason
In plugin c# source code
source/plugin/Assets/GoogleMobileAds/Platforms/Android/MobileAdsClient.cs: line 80
```
                mobileAdsClass.CallStatic("putPublisherFirstPartyIdEnabled", requestConfiguration.PublisherFirstPartyIdEnabled.Value);
```
call fun putPublisherFirstPartyIdEnabled without return value

in android package
com.google.android.gms.ads.MobileAds.class
```
      public static boolean putPublisherFirstPartyIdEnabled(boolean enabled)
```
fun putPublisherFirstPartyIdEnabled has return value

modify MobileAdsClient.cs: line 80 should correct this error:
```
                mobileAdsClass.CallStatic<bool>("putPublisherFirstPartyIdEnabled", requestConfiguration.PublisherFirstPartyIdEnabled.Value);
```

**Comment by NVentimiglia** [comment]
@chengwenpo 

Correction, I was able to replicate this. This is a problem with the latest version so as a work around you can roll back to an earlier version of the plugin. I have spoken with the engineers and they are looking into this issue.

**Comment by NVentimiglia** [comment]
This should be fixed. Please update and try again. If you have issues please reopen this issue and let me know.
