### ISSUE TITLE
[Unity 5.5.0p3] Build failure : Unable to convert classes into dex format. (With Google Play Service plugin)

### ISSUE THREAD

**Issue by jun496** [googleads/googleads-mobile-unity#330]
I have already read all issues,
and I've check "Conflicts with Play games plugin #283", but that was not for me.

Google Mobile Ads and Google Play service plugin are lastest version,
I updated AdroidSDK to lastest,
There is no duplicated aar or jar files,
There is no firebase files,
but I have build error now.
Only way to make successful build is remove plugin for Google Mobile Ads.

Please let me know what is the problem.

Thanks!

------------------------------------------------------------------------------------

CommandInvokationFailure: Unable to convert classes into dex format.
/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/iMacDev/Library/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[

trouble writing output: Too many field references: 65698; max is 65536.
You may try using --multi-dex option.
References by package:
     3 android.accounts
    29 android.app
     2 android.content
    40 android.content.pm
     9 android.content.res
     3 android.database
    47 android.graphics
     1 android.hardware
     1 android.location
     2 android.media
     1 android.media.browse
     2 android.net
    36 android.os
     3 android.print
     1 android.provider
     3 android.support.annotation
  1645 android.support.customtabs
  1734 android.support.graphics.drawable
  1581 android.support.graphics.drawable.animated
  1581 android.support.v4
    13 android.support.v4.accessibilityservice
    17 android.support.v4.animation
   847 android.support.v4.app
   112 android.support.v4.content
     1 android.support.v4.content.pm
     1 android.support.v4.content.res
     9 android.support.v4.graphics
    42 android.support.v4.graphics.drawable
     4 android.support.v4.hardware.display
    12 android.support.v4.hardware.fingerprint
     9 android.support.v4.internal.view
   337 android.support.v4.media
   295 android.support.v4.media.session
     7 android.support.v4.net
    19 android.support.v4.os
    55 android.support.v4.print
     9 android.support.v4.provider
     5 android.support.v4.speech.tts
    55 android.support.v4.text
    74 android.support.v4.util
   431 android.support.v4.view
   113 android.support.v4.view.accessibility
     8 android.support.v4.view.animation
   501 android.support.v4.widget
   378 android.support.v7.app
  1581 android.support.v7.appcompat
  1581 android.support.v7.cardview
    18 android.support.v7.graphics.drawable
     1 android.support.v7.text
     2 android.support.v7.transition
    77 android.support.v7.view
   191 android.support.v7.view.menu
   835 android.support.v7.widget
     5 android.text
    13 android.util
    15 android.view
     7 android.webkit
    16 android.widget
     2 bitter.jnibridge
   158 bolts
  1575 com.YellowPurples.CrazySlots
  1595 com.android.vending.billing
  1982 com.facebook
  1581 com.facebook.android
   169 com.facebook.appevents
    39 com.facebook.appevents.internal
    46 com.facebook.applinks
     9 com.facebook.devicerequests.internal
   563 com.facebook.internal
   183 com.facebook.login
    81 com.facebook.login.widget
    32 com.facebook.messenger
    51 com.facebook.share
   360 com.facebook.share.internal
   113 com.facebook.share.model
   124 com.facebook.share.widget
    53 com.facebook.unity
    25 com.google.ads
    22 com.google.ads.mediation
    11 com.google.ads.mediation.customevent
  1575 com.google.android.gms
    20 com.google.android.gms.actions
  1618 com.google.android.gms.ads
    12 com.google.android.gms.ads.doubleclick
    19 com.google.android.gms.ads.formats
    14 com.google.android.gms.ads.identifier
  1575 com.google.android.gms.ads.impl
   255 com.google.android.gms.ads.internal
   177 com.google.android.gms.ads.internal.overlay
    49 com.google.android.gms.ads.internal.purchase
    22 com.google.android.gms.ads.mediation
     1 com.google.android.gms.ads.mediation.admob
    12 com.google.android.gms.ads.mediation.customevent
     7 com.google.android.gms.ads.purchase
     1 com.google.android.gms.ads.reward.mediation
    46 com.google.android.gms.ads.search
  1629 com.google.android.gms.auth
     6 com.google.android.gms.auth.account
  1596 com.google.android.gms.auth.api
    85 com.google.android.gms.auth.api.credentials
    44 com.google.android.gms.auth.api.proxy
    46 com.google.android.gms.auth.api.signin
    28 com.google.android.gms.auth.api.signin.internal
  1575 com.google.android.gms.base
  1575 com.google.android.gms.clearcut
    94 com.google.android.gms.common
    92 com.google.android.gms.common.api
    41 com.google.android.gms.common.data
    46 com.google.android.gms.common.images
   164 com.google.android.gms.common.internal
     1 com.google.android.gms.common.internal.safeparcel
     4 com.google.android.gms.common.server
    48 com.google.android.gms.common.stats
    24 com.google.android.gms.common.util
  1702 com.google.android.gms.drive
    60 com.google.android.gms.drive.events
    11 com.google.android.gms.drive.metadata
    24 com.google.android.gms.drive.metadata.internal
    41 com.google.android.gms.drive.query
    61 com.google.android.gms.drive.query.internal
     7 com.google.android.gms.drive.widget
    27 com.google.android.gms.dynamic
    18 com.google.android.gms.dynamite
     2 com.google.android.gms.dynamite.descriptors.com.google.android.gms.ads.dynamite
     2 com.google.android.gms.dynamite.descriptors.com.google.android.gms.flags
    16 com.google.android.gms.flags.impl
  1768 com.google.android.gms.games
    26 com.google.android.gms.games.achievement
    78 com.google.android.gms.games.appcontent
    14 com.google.android.gms.games.event
   264 com.google.android.gms.games.internal
   152 com.google.android.gms.games.internal.api
     1 com.google.android.gms.games.internal.constants
     3 com.google.android.gms.games.internal.data
     7 com.google.android.gms.games.internal.events
    17 com.google.android.gms.games.internal.experience
    14 com.google.android.gms.games.internal.game
     3 com.google.android.gms.games.internal.multiplayer
     1 com.google.android.gms.games.internal.notification
    59 com.google.android.gms.games.internal.player
     8 com.google.android.gms.games.internal.request
    61 com.google.android.gms.games.leaderboard
    64 com.google.android.gms.games.multiplayer
    41 com.google.android.gms.games.multiplayer.realtime
    50 com.google.android.gms.games.multiplayer.turnbased
    58 com.google.android.gms.games.quest
    36 com.google.android.gms.games.request
    50 com.google.android.gms.games.snapshot
     9 com.google.android.gms.games.social
    16 com.google.android.gms.games.stats
    50 com.google.android.gms.games.video
  1575 com.google.android.gms.gass
  1679 com.google.android.gms.gcm
  1621 com.google.android.gms.iid
  4740 com.google.android.gms.internal
     5 com.google.android.gms.location.places
  1582 com.google.android.gms.nearby
    18 com.google.android.gms.nearby.connection
    91 com.google.android.gms.nearby.messages
   137 com.google.android.gms.nearby.messages.internal
     6 com.google.android.gms.security
  1623 com.google.android.gms.tasks
  1575 com.google.example.games.mainlibproj
    36 com.google.games.bridge
  1581 com.google.unity
    82 com.google.unity.ads
  1581 com.unity.purchasing
    33 com.unity.purchasing.common
  1754 com.unity.purchasing.googleplay
  1611 com.unity3d.ads
    34 com.unity3d.ads.adunit
    37 com.unity3d.ads.api
     6 com.unity3d.ads.broadcast
    32 com.unity3d.ads.cache
    47 com.unity3d.ads.configuration
    13 com.unity3d.ads.connectivity
    39 com.unity3d.ads.device
    21 com.unity3d.ads.log
     7 com.unity3d.ads.metadata
     2 com.unity3d.ads.placement
    13 com.unity3d.ads.properties
    41 com.unity3d.ads.request
    33 com.unity3d.ads.video
    23 com.unity3d.ads.webview
    27 com.unity3d.ads.webview.bridge
   148 com.unity3d.player
     1 java.io
    23 java.lang
    11 java.lang.annotation
     1 java.math
     1 java.nio
     1 java.text
     6 java.util
     4 java.util.concurrent
     4 javax.microedition.khronos.egl
  1585 me.leolin.shortcutbadger
    42 me.leolin.shortcutbadger.impl
    20 org.fmod
     1 org.json
  1629 universal.tools.notifications
]
stdout[
processing archive /Users/iMacDev/Documents/Projects/CrazySlots/CrazySlots Facebook/Temp/StagingArea/android-libraries/GoogleAIDL/libs/./classes.jar...
processing com/android/vending/billing/BuildConfig.class...
processing com/android/vending/billing/IInAppBillingService.class...
processing com/android/vending/billing/IInAppBillingService$Stub.class...
processing com/android/vending/billing/IInAppBillingService$Stub$Proxy.class...
processing archive /Users/iMacDev/Documents/Projects/CrazySlots/CrazySlots Facebook/Temp/StagingArea/android-libraries/GoogleMobileAdsPlugin/libs/./unity-plugin-library.jar...
processing com/google/unity/BuildConfig.class...
processing com/google/unity/ads/Banner.class...
processing com/google/unity/ads/Banner$1.class...
processing com/google/unity/ads/Banner$1$1.class...
processing com/google/unity/ads/Banner$2.class...
processing com/google/unity/ads/Banner$3.class...
processing com/google/unity/ads/Banner$4.class...
processing com/google/unity/ads/Banner$5.class...
processing com/google/unity/ads/CustomNativeAd.class...
processing com/google/unity/ads/CustomNativeAd$1.class...
processing com/google/unity/ads/CustomNativeAd$2.class...
processing com/google/unity/ads/Interstitial.class...
processing com/google/unity/ads/Interstitial$1.class...
processing com/google/unity/ads/Interstitial$1$1.class...
processing com/google/unity/ads/Interstitial$2.class...
processing com/google/unity/ads/Interstitial$3.class...
processing com/google/unity/ads/Interstitial$4.class...
processing com/google/unity/ads/Interstitial$5.class...
processing com/google/unity/ads/NativeAdLoader.class...
processing com/google/unity/ads/NativeAdLoader$1.class...
processing com/google/unity/ads/NativeAdLoader$2.class...
processing com/google/unity/ads/NativeAdLoader$3.class...
processing com/google/unity/ads/NativeAdLoader$3$1.class...
processing com/google/unity/ads/NativeAdLoader$3$2.class...
processing com/google/unity/ads/NativeAdLoader$3$3.class...
processing com/google/unity/ads/NativeAdLoader$4.class...
processing com/google/unity/ads/NativeExpressAd.class...
processing com/google/unity/ads/NativeExpressAd$1.class...
processing com/google/unity/ads/NativeExpressAd$1$1.class...
processing com/google/unity/ads/NativeExpressAd$2.class...
processing com/google/unity/ads/NativeExpressAd$3.class...
processing com/google/unity/ads/NativeExpressAd$4.class...
processing com/google/unity/ads/NativeExpressAd$5.class...
processing com/google/unity/ads/NativeExpressAd$6.class...
processing com/google/unity/ads/PluginUtils.class...
processing com/google/unity/ads/RewardBasedVideo.class...
processing com/google/unity/ads/RewardBasedVideo$1.class...
processing com/google/unity/ads/RewardBasedVideo$1$1.class...
processing com/google/unity/ads/RewardBasedVideo$2.class...
processing com/google/unity/ads/RewardBasedVideo$3.class...
processing com/google/unity/ads/UnityAdListener.class...
processing com/google/unity/ads/UnityCustomNativeAdListener.class...
processing com/google/unity/ads/UnityRewardBasedVideoAdListener.class...
processing archive /Users/iMacDev/Documents/Projects/CrazySlots/CrazySlots Facebook/Temp/StagingArea/android-libraries/GooglePlay/libs/./classes.jar...
processing com/unity/purchasing/googleplay/ActivityLauncher.class...
processing com/unity/purchasing/googleplay/BillingServiceManager.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$2.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$2.class...
processing com/unity/purchasing/googleplay/BillingServiceProcessor.class...
processing com/unity/purchasing/googleplay/BuildConfig.class...
processing com/unity/purchasing/googleplay/Consts.class...
processing com/unity/purchasing/googleplay/Consts$PurchaseState.class...
processing com/unity/purchasing/googleplay/Consts$ResponseCode.class...
processing com/unity/purchasing/googleplay/GooglePlayBillingUnAvailableException.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$1.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$2.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$3.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$4.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$5.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$6.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$7.class...
processing com/unity/purchasing/googleplay/IActivityLauncher.class...
processing com/unity/purchasing/googleplay/IBillingServiceManager.class...
processing com/unity/purchasing/googleplay/IabException.class...
processing com/unity/purchasing/googleplay/IabHelper.class...
processing com/unity/purchasing/googleplay/IabHelper$1.class...
processing com/unity/purchasing/googleplay/IabHelper$2.class...
processing com/unity/purchasing/googleplay/IabHelper$2$1.class...
processing com/unity/purchasing/googleplay/IabHelper$3.class...
processing com/unity/purchasing/googleplay/IabHelper$4.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeMultiFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabPurchaseFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabSetupFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$QueryInventoryFinishedListener.class...
processing com/unity/purchasing/googleplay/IabResult.class...
processing com/unity/purchasing/googleplay/Inventory.class...
processing com/unity/purchasing/googleplay/Purchase.class...
processing com/unity/purchasing/googleplay/PurchaseActivity.class...
processing com/unity/purchasing/googleplay/PurchaseFailedEvent.class...
processing com/unity/purchasing/googleplay/SkuDetails.class...
processing archive /Users/iMacDev/Documents/Projects/CrazySlots/CrazySlots Facebook/Temp/StagingArea/android-libraries/MainLibProj/libs/./play-games-plugin-support.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/games/
ignored resource com/google/games/bridge/
processing com/google/games/bridge/BuildConfig.class...
processing com/google/games/bridge/NativeBridgeActivity.class...
processing com/google/games/bridge/TokenFragment.class...
processing com/google/games/bridge/TokenFragment$1.class...
processing com/google/games/bridge/TokenFragment$TokenRequest.class...
processing com/google/games/bridge/TokenPendingResult.class...
processing com/google/games/bridge/TokenResult.class...
processing archive /Users/iMacDev/Documents/Projects/CrazySlots/CrazySlots Facebook/Temp/StagingArea/android-libraries/ShortcutBadger-1.1.5/libs/./classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource me/
ignored resource me/leolin/
ignored resource me/leolin/shortcutbadger/
processing me/leolin/shortcutbadger/Badger.class...
processing me/leolin/shortcutbadger/BuildConfig.class...
processing me/leolin/shortcutbadger/ShortcutBadgeException.class...
processing me/leolin/shortcutbadger/ShortcutBadger.class...
ignored resource me/leolin/shortcutbadger/impl/
processing me/leolin/shortcutbadger/impl/AdwHomeBadger.class...
processing me/leolin/shortcutbadger/impl/ApexHomeBadger.class...
processing me/leolin/shortcutbadger/impl/AsusHomeLauncher.class...
processing me/leolin/shortcutbadger/impl/DefaultBadger.class...
processing me/leolin/shortcutbadger/impl/LGHomeBadger.class...
processing me/leolin/shortcutbadger/impl/NewHtcHomeBadger.class...
processing me/leolin/shortcutbadger/impl/NovaHomeBadger.class...
processing me/leolin/shortcutbadger/impl/SamsungHomeBadger.class...
processing me/leolin/shortcutbadger/impl/SolidHomeBadger.class...
processing me/leolin/shortcutbadger/impl/SonyHomeBadger.class...
processing me/leolin/shortcutbadger/impl/XiaomiHomeBadger.class...
ignored resource me/leolin/shortcutbadger/util/
processing me/leolin/shortcutbadger/util/BroadcastHelper.class...
processing me/leolin/shortcutbadger/util/CloseHelper.class...
processing archive /Users/iMacDev/Documents/Projects<message truncated>

**Comment by rampara** [comment]
Looks like your running into the [dex limit](https://developer.android.com/studio/build/multidex.html#about). As a workaround you can try the following:

1. Remove any libraries that are not required for you app.
2. Use the [Lite Ads SDK](https://firebase.google.com/docs/admob/android/lite-sdk) for your Unity app. To use the lite SDK update the Google Mobile Ads SDK dependency declaration in `AdMobDependencies.cs` at `Assets/GoogleMobileAds/Editor` from `play-services-ads` to `play-services-ads-lite`. You'll also need to ensure only the GMA Lite SDK AAR is present in the `Assets/Plugins/Android` directory of your project and not the full GMA Ads SDK AAR.
3. Export your Unity app to a Android Studio project and use proguard to bring down the dex count.

**Comment by rampara** [comment]
Closing this issue due to the lack of response. If this problem still persists for you please re-open the issue.
