### ISSUE TITLE
Ads don't show on Android when using Unity 5.6.0b3

### ISSUE THREAD

**Issue by roncrisostomo** [googleads/googleads-mobile-unity#331]
I'm running Google Mobile Ads 3.1.3 on an empty project. It works fine on Unity 5.5, but not on Unity 5.6 for Android (iOS runs fine). Logcat says "Ad finished loading", but nothing shows on screen.

I'm aware that the version of Unity I'm using is still a beta so problems like this are to be expected. Reverting to an older version is not an option for us unfortunately, because 5.6 brings something we need in the project.

I've attached the logcat of the project running on a Galaxy Tab 7.0 Plus (Android 4.1.2).
[AdMobTest5.6.0_logcat.txt](https://github.com/googleads/googleads-mobile-unity/files/680932/AdMobTest5.6.0_logcat.txt)

Hope someone can offer a solution. Thanks in advance!

**Comment by rampara** [comment]
Thanks for bringing this issue to light. Should be pushing a fix for this soon.

**Comment by rampara** [comment]
The latest version of the plugin (v3.2.0) resolves this issue.
