### ISSUE TITLE
View provider for loaded ad

### ISSUE THREAD

**Issue by kgooble** [googleads/googleads-mobile-unity#332]
I didn't see any documentation for this anywhere, so I was wondering if it is possible to know which provider provided the ad that we just loaded/showed the user? For example, I've integrated ad mediation for Vungle and AdColony. If AdMob provides me with an ad from Vungle, is it possible to know this in the code when the ad is finished loading?

Thank you!

**Comment by rampara** [comment]
The Google Mobile Ads SDK does provide the ability to get the mediation adapter class name for an ad view. Will add corresponding Unity APIs for this functionality.

**Comment by kgooble** [comment]
Thank you @rampara, looking forward to this change!

**Comment by kgooble** [comment]
Hi @rampara, is there any news on this? Is the feature available on the latest version of AdMob Unity?

**Comment by rampara** [comment]
@kgooble this feature hasn't been implemented yet. Is there a particular ad format you require it for?

**Comment by kgooble** [comment]
@rampara I'm not 100% sure on what you mean by ad format - but I need it for both interstitial and rewarded ads, if that's what you are asking.

**Comment by rampara** [comment]
@kgooble this has been implemented for all ad formats as of v3.8.0.

**Comment by kgooble** [comment]
Thank you @rampara!
