### ISSUE TITLE
 MobileAds.Initialize(initStatus => { }); Vs MobileAds.Initialize((InitializationStatus initStatus) => { });

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#3320]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: not required
  * Google Mobile Ads Unity plugin version: not required
  * Platform: not required
  * Platform OS version: not required
  * Any specific devices issue occurs on: not required
  * Mediation ad networks used, and their versions: not required

#### Steps to reproduce:
What's the difference between these two lines because its conflicting in [Admob Unity Plugin Docs](https://developers.google.com/admob/unity/quick-start). Sometime docs refers to **MobileAds.Initialize(initStatus => { });** 
 and sometime refers **MobileAds.Initialize((InitializationStatus initStatus) => { });**.

 **Why i am asking this?** -> Its leading to potential ANRs and crashes which i will update later in discussion.
 **How?** -> calling load ads without knowing status of initStatus can leads to ANRs and crashes.
 MobileAds.Initialize((InitializationStatus initStatus) =>
{
     //call load ads, like
    LoadBannerAd();
    LoadInterstitialAd();
    LoadRewardedAd();
    LoadRewardedInterstitialAd();
});

**To resolve this** either use 
MobileAds.Initialize(initStatus => { //call load ads }); 
where it goes in MobileAds.Initialize(initStatus => **{ //call load ads }**); when initStatus is true (as far i understand)

Or use below approach as implemented in sample projects 
MobileAds.Initialize((InitializationStatus initStatus) => 
{ 
   if(initStatus !=nulll)
  {
    //call load ads
   } 
});
I am sharing this for my understanding and someone else making same mistake.
I will facing huge anr spike. i will share my ANR and crashes stats after this.
Please discard this post if not helpful.

**Comment by NVentimiglia** [comment]
In both cases you are calling the same API method. The difference you are seeing is a feature of C# which allows it to infer the type `InitializationStatus` even if it is not included.

// All three of these snippets are the same.
```
MobileAds.Initialize(initStatus => { });

MobileAds.Initialize(InitializationStatus initStatus) => { });

MobileAds.Initialize(OnInit);

void OnInit(InitializationStatus initStatus);
```
