### ISSUE TITLE
[Google Mobile Ads Android SDK 23.0.0 Causing ANRs][Android]

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#3324]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: Not Required
  * Google Mobile Ads Unity plugin version: All supporting Google Mobile Ads Android SDK 23.0.0
  * Platform: Android

#### Steps to reproduce:

**All GMA Unity Packages supporting GMA 23.0.0 causing huge ANRs spike. All anrs refereeing to com.google.android.gms:play-services-ads:23.0.0 at com.google.android.gms.ads.initialization.OnInitializationCompleteListener.onInitializationComplete().**

I know its not under GMA unity, but you can refer them. because they are not giving any solution at any forum for GMA developers groups.

![anr](https://github.com/googleads/googleads-mobile-unity/assets/32755091/db5bcce2-0a6c-405c-8f0b-a39141d5c2fa)

for more detail please check 
1- https://github.com/googleads/googleads-mobile-unity/issues/3227
2- https://groups.google.com/g/google-admob-ads-sdk/c/TjU2YunGW-g

**Comment by MuhammadWaqasOfficial** [comment]
Google Mobile Ads Android SDK 22.5.0 & 22.6.0 supporting GMA unity (8.6.0 & 8.7.0) as well.

**Comment by MuhammadWaqasOfficial** [comment]
No ANR in GMA Unity 8.2.0 (GMA 22.0.0)

**Comment by NVentimiglia** [comment]
Thank you. I have confirmed the issue and we are looking into this.

**Comment by NVentimiglia** [comment]
I was able to get to the cause of the issue. The issue is we are missing the Unity Android JNI dependency in the project. The solution is to add the Android JNI dependency using package manager.

Open the Unity Editor menu  `Window -> Package Manager` select `Build In` packages and install `Android JNI`. 

Hope this helps,
Nick

**Comment by MuhammadWaqasOfficial** [comment]
I checked, Android JNI is already installed and enabled.
<img width="797" alt="Android JNI" src="https://github.com/googleads/googleads-mobile-unity/assets/32755091/71f39a56-d627-4f10-8cbe-719c5dde13af">
