### ISSUE TITLE
Interestial Ads Not Showing on Live Android Device for Game Build in Unity 4.6

### ISSUE THREAD

**Issue by devaniumesh** [googleads/googleads-mobile-unity#334]
Detailed Question posted on Stack-overflow 
[http://stackoverflow.com/questions/41531875/interestial-ads-not-showing-on-live-android-device-for-game-build-in-unity-4-6](http://stackoverflow.com/questions/41531875/interestial-ads-not-showing-on-live-android-device-for-game-build-in-unity-4-6)

**Comment by rampara** [comment]
@devaniumesh within the `Ads` and `Unity` tags under logcat, do you see any output that may indicate why you're not seeing ads? Are you also unable to request and display ads with the [sample app](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) included in this repo?

**Comment by rampara** [comment]
Closing this issue due to the lack of response. If this problem still persists for you please re-open the issue.
