### ISSUE TITLE
iOS build crashes on launch/watching ads after updating

### ISSUE THREAD

**Issue by vincent-savysoda** [googleads/googleads-mobile-unity#3344]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.37f1
  * Google Mobile Ads Unity plugin version: v9.1.0
  * Platform: iOS
  * Mediation ad networks used, and their versions: Audience Network, UnityAds

### [REQUIRED] Step 2: Describe the problem

So this is on the heels of resolving the issue regarding the Android build crashing on launch in #3334. The only thing I noticed that may potentially be causing this is the issue mentioned [here](https://github.com/googleads/googleads-mobile-unity/issues/3334#issuecomment-2081781906) regarding the Google.iOSResolver assembly getting an exception when importing the plugin.

I'll see about trying to get some crash logs if possible later.

**Comment by vincent-savysoda** [comment]
So just an update: After removing all mediation networks...the build managed to run successfully without crashing. However, this time it just crashes everytime i try to watch an ad.

**Comment by vincent-savysoda** [comment]
This is what I got from the crash logs:
{"app_cohort":"2|date=1714694400000&sf=143460&tid=f7c865cfb747ec20bc21d0832a0217a52d813c84a05bdd9a7392ec4d9c37ac1f&ttype=i","app_name":"PixelStarships","app_version":"0.999","timestamp":"2024-05-03 10:11:51.00 +1000","slice_uuid":"5c7c4ac1-a3ad-3c13-8ae7-24c438fc19c4","adam_id":321756558,"build_version":"13639","platform":0,"bundleID":"com.savysoda.pixelStarships","share_with_app_devs":1,"is_first_party":0,"bug_type":"109","os_version":"iPhone OS 14.4.2 (18D70)","incident_id":"9DA7CA84-4D02-4BEC-9834-3F62DE6734F2","name":"PixelStarships","is_beta":1}
Incident Identifier: 9DA7CA84-4D02-4BEC-9834-3F62DE6734F2
Beta Identifier:     F49090E9-E610-4CD6-98C5-92471BC16366
Hardware Model:      iPad6,7
Process:             PixelStarships [1078]
Path:                /private/var/containers/Bundle/Application/7E088169-7B6C-42A1-A2FA-845E6378872E/PixelStarships.app/PixelStarships
Identifier:          com.savysoda.pixelStarships
Version:             13639 (0.999)
AppStoreTools:       15E204
AppVariant:          1:iPad6,7:14
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.savysoda.pixelStarships [355]


Date/Time:           2024-05-03 10:11:51.1855 +1000
Launch Time:         2024-05-03 10:11:50.9663 +1000
OS Version:          iPhone OS 14.4.2 (18D70)
Release Type:        User
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, dyld: Using shared cache: 7D820DFD-DE05-386A-B006-CAB977C04802 | dependent dylib '@rpath/libswiftCore.dylib' not found for '/private/var/containers/Bundle/Application/7E088169-7B6C-42A1-A2FA-845E6378872E/PixelStarships.app/PixelStarships', tried but didn't find: '/private/var/containers/Bundle/Application/7E088169-7B6C-42A1-A2FA-845E6378872E/PixelStarships.app/Frameworks/libswiftCore.dylib' '@rpath/libswiftCore.dylib' '/usr/local/lib/libswiftCore.dylib' '/usr/lib/libswiftCore.dylib'
Highlighted by Thread:  0

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016b01dff0   x3: 0x00000000000000a0
    x4: 0x000000016b01dbf0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x202762696c79642e  x11: 0x696c2f7273752f27
   x12: 0x6c2f7273752f2720  x13: 0x777362696c2f6269  x14: 0x2e65726f43746669  x15: 0x00202762696c7964
   x16: 0x0000000000000209  x17: 0x00000000000000b0  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016b01dbf0  x21: 0x00000000000000a0  x22: 0x000000016b01dff0  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x000000016b01e8b8  x26: 0x00000001053c0778  x27: 0x00000001053c0000
   x28: 0x0000000000000000   fp: 0x000000016b01dbc0   lr: 0x00000001053a4ca4
    sp: 0x000000016b01db80   pc: 0x000000010539d3e8 cpsr: 0x00000000
   esr: 0x00000000  Address size fault

Binary images description not available

Error Formulating Crash Report:
Failed to create CSSymbolicatorRef - corpse still valid ¯\_(ツ)_/¯

**Comment by NVentimiglia** [comment]
Please submit this issue to [Admob SDK Support](https://developers.devsite.corp.google.com/admob/support). This is a complex issue and we may need to request help from the Android SDK team on this one.
