### ISSUE TITLE
Saving Prefab to immutable folder is not allowed.

### ISSUE THREAD

**Issue by ajeets1978** [googleads/googleads-mobile-unity#3350]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.21f1
  * Google Mobile Ads Unity plugin version: 9.1.0
  * Platform: Editor (iOS, Android, Unity Editor)
  * Platform OS version: Windows 10 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: Editor / Windows, Not tested on any other platforms.
  * Mediation ad networks used, and their versions: Only Google Admob

#### Steps to reproduce:

What happened? How can we make the problem occur?
Its happening in editor in each project I am importing the latest Google Admob Unity SDK.

Saving Prefab to immutable folder is not allowed: Packages/com.google.ads.mobile/GoogleMobileAds/Editor/Resources/PlaceholderAds/Interstitials/768x1024.prefab
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Saving Prefab to immutable folder is not allowed: Packages/com.google.ads.mobile/GoogleMobileAds/Editor/Resources/PlaceholderAds/Banners/BANNER.prefab
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

```
1. Create a project
2. Import Google Mobile Ads SDK Unity
3. Try running in Editor, you will see those errors.

It's not impacting the build but I think we should not see those errors in Editor.
```

**Comment by NVentimiglia** [comment]
I was not able to replicate this issue. I ran the project and loaded a banner and an interstital ad. Were other steps taken?

**Comment by JVimes** [comment]
@NVentimiglia Did you install [via Package Manager](https://developers.google.com/admob/unity/quick-start#openupm) (uses OpenUPM)? I believe that's required to repro the issue.

**Comment by umutakmak** [comment]
I am also having this issue, happened after I switched to OpenUPM
```
Saving Prefab to immutable folder is not allowed:
Packages/com.google.ads.mobile/GoogleMobileAds/Editor/Resources/PlaceholderAds/Rewarded/768x1024.prefab
```

**Comment by BhaumikSurani** [comment]
> I am also having this issue, happened after I switched to OpenUPM
> 
> ```
> Saving Prefab to immutable folder is not allowed:
> Packages/com.google.ads.mobile/GoogleMobileAds/Editor/Resources/PlaceholderAds/Rewarded/768x1024.prefab
> ```

I have faced the same issue after switching to OpenUPM.  
In my case below steps fixed that issue.  
1. Remove GoogleMobileAds from OpenUPM
2. Remove GoogleMobileAds related files in "Assets/Plugins"
3. Reinstall GoogleMobileAds via OpenUPM

**Comment by JVimes** [comment]
Sadly, that did not work for me.

**Comment by SamNeblett** [comment]
I'm encountering this issue as well. Yes, installed through UPM. Unity LTS 2022.3.49f1 and 2022.3.50f1

**Comment by AntonPetrov83** [comment]
The issue is still there in 10.2.0

**Comment by Liviuss76** [comment]
The issue is still there in 10.6.0 installed via OpenUPM. It does not affect builds but is nnoing in editor, keep popping the error every time the context is reloaded.

**Comment by HybridShivam** [comment]
Just do an asset refresh: (`Ctrl+ R`) in the unity editor to bypass it.
