### ISSUE TITLE
[ANRs Bug In 8.6.0 - 8.7.0 - 9.0.0 - 9.1.0] [GMA 22.4.0 and above]

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#3354]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.1.+, 2022.2.+
  * Google Mobile Ads Unity plugin version: 8.6.0 - 8.7.0 - 9.0.0 - 9.1.0
  * Platform: Android

### [REQUIRED] Step 2: Describe the problem
 Admob Unity 8.6.0 (GMA 22.5.0) - 8.7.0 (GMA 22.6.0) - 9.0.0 (GMA 23.0.0) - 9.1.0 (GMA 23.0.0) causing huge ANRs. Despite of raising and bringing this issue at [github's issue tracker](https://github.com/googleads/googleads-mobile-unity/issues) and at [our forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) didn't help at all. And both forums are unable to track this issue, even after sharing all information i can provide. In GMA developers forum they emailed me that we are working on this issue and that's it, no reply after that. 
I am linking post related to this ANR issue.
 - https://github.com/googleads/googleads-mobile-unity/issues/3227
 - https://github.com/googleads/googleads-mobile-unity/issues/3324
 - https://groups.google.com/g/google-admob-ads-sdk/c/TjU2YunGW-g
 - https://groups.google.com/g/google-admob-ads-sdk/c/Qffz1nJ9uv4
 
@NVentimiglia  i understand this issue is not comes under GMA Unity but we are affecting from it directly. I wonder everybody not pointing to this confirmed issue. 
Anyhow  as far i know this issue is introduced with GMA 22.4.0 and still carrying in latest 23.0.0.
I downgraded to 8.5.3 and so far anrs comes down to 1%(still high but better than 15% anr rate and play console adding our games in bad behavior).
So anyone facing this issue my suggestion is use 8.5.3 or below. Also don't follow current [this developer guide](https://developers.google.com/admob/unity/quick-start) if you're using 8.5.3 or below because its for 8.6.0 and above.

![Anr_History_1](https://github.com/googleads/googleads-mobile-unity/assets/32755091/13df7a28-a498-4e31-9d2a-4a81cecaa4a8)
![Anr_History_2](https://github.com/googleads/googleads-mobile-unity/assets/32755091/18e57a5c-0b50-4289-8b14-a31b0f95916b)

**Comment by NVentimiglia** [comment]
This looks to be an issue specific to Google Mobile Ads __Android__ SDK and not the Unity plugin (which wraps around the Android SDK). Can you open an issue on the Admob SDK [support site](https://developers.devsite.corp.google.com/admob/support). Once we have the issue there, we can direct the case to the appropriate team.

**Comment by MuhammadWaqasOfficial** [comment]
> This looks to be an issue specific to Google Mobile Ads **Android** SDK and not the Unity plugin (which wraps around the Android SDK). Can you open an issue on the Admob SDK [support site](https://developers.devsite.corp.google.com/admob/support). Once we have the issue there, we can direct the case to the appropriate team.

i am not google employee. Who can i login and submit the issue.
![image](https://github.com/googleads/googleads-mobile-unity/assets/32755091/6bfd4978-d969-4824-82db-f1081b53acfc)

**Comment by PrerakPrek** [comment]
Any update on the issue ? it seems like it hasn't been resolved yet.

**Comment by MuhammadWaqasOfficial** [comment]
Not resolved.
I moved back to 8.2.0 and unity below 2021.3.36f1 and below. (they upgrade the gradle to 4.2.2 from 4.0.1unity 2021.3.37f1+)
Removed the ump code as well (ump is included in 8.2 and google is auto generating ump message and handling it and i didn't need ump custom implementation)

**Comment by armnotstrong** [comment]
Hi, does anyone know if this has been solved? We are using Unity Editor 2022.3.24 and 8.6.0, still seeing this. We upgraded the SDK version because of UMP, does this relate to UMP SDK?

**Comment by MuhammadWaqasOfficial** [comment]
> Hi, does anyone know if this has been solved? We are using Unity Editor 2022.3.24 and 8.6.0, still seeing this. We upgraded the SDK version because of UMP, does this relate to UMP SDK?

not resolved.
didn't know if related to ump or not.

**Comment by cavallinii** [comment]
Hi @MuhammadWaqasOfficial Have you managed to find a stable version of Unity and AdMob that work nicely together? Thanks so much in advance!

**Comment by MuhammadWaqasOfficial** [comment]
> Hi [@MuhammadWaqasOfficial](https://github.com/MuhammadWaqasOfficial) Have you managed to find a stable version of Unity and AdMob that work nicely together? Thanks so much in advance!

No

**Comment by MuhammadWaqasOfficial** [comment]
> Hi [@MuhammadWaqasOfficial](https://github.com/MuhammadWaqasOfficial) Have you managed to find a stable version of Unity and AdMob that work nicely together? Thanks so much in advance!

Currently using 9.2.0 + compatible mediation networks and firebase 12.1.0

**Comment by MDThreye** [comment]
what is the update or solution for this ANR Spike as over app is also having now after GMA Update

**Comment by armnotstrong** [comment]
> what is the update or solution for this ANR Spike as over app is also having now after GMA Update

Can you share the old version and the upgraded version of GMA? Was the ANR ratio below the limit with the old version?
