### ISSUE TITLE
Compilación sin errores en Unity. No funciona la app en ningún dispositivo.

### ISSUE THREAD

**Issue by ReDPluto** [googleads/googleads-mobile-unity#3356]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.28f1
  * Google Mobile Ads Unity plugin version: 9.10
  * Plugin installation method: Unity package manager
  * Platform: Android, Unity Editor
  * Platform OS version: Todas
  * Any specific devices issue occurs on: Open app

#### Steps to reproduce:

Any application stops working when version 9.10 of Google Mobile Admo is added. In Unity it compiles without errors but when the .apk is installed on any device, opening the application closes. If we delete the Google Mobile and external dependency folders from the asset, the app works again. I assume you are aware of this serious problem since it is currently not possible to use the google mobile admon in Unity. We need an urgent solution to this problem.

Thank you

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by NVentimiglia** [comment]
Can you share the errors you are seeing?

**Comment by ReDPluto** [comment]
Sorry but I'm quite new to unity, I don't see any errors in unity. You can try to compile a new test project and add the google mobile ads to the project, it will compile without errors in Unity but then you will not be able to open that apk on any device. This happens to many people and I don't know if the problem is with Unity or Google Mobile, but I would like to know if there is a compatible version of Unity with a version of Google Mobile Ads in which the app can be opened and work normally .

**Comment by NVentimiglia** [comment]
Can you provide the logcats from the device when it crashes?

**Comment by ReDPluto** [comment]
Solved, the cause was the GMA ID that was not completely correct, this does not produce any failure in Unity but then the apk does not work on any device, it was driving me crazy!! Thanks for your help.
