### ISSUE TITLE
CommandInvokationFailure: Failed to re-package resources. See the Console for details.

### ISSUE THREAD

**Issue by 850176300** [googleads/googleads-mobile-unity#336]
CommandInvokationFailure: Failed to re-package resources. See the Console for details.
E:\Android\sdk\build-tools\25.0.0\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "E:/Android/sdk\platforms\android-25\android.jar" -F bin/resources.ap_ --extra-packages com.jellygame.nailsalon

stderr[
AndroidManifest.xml:16: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.IAPTheme').

AndroidManifest.xml:18: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

]

My unity version is v5.3.3f1. And I have update all frameworks below
Android SDK Tools
Android Build Tools
Google Play Services
Google Support Library
Google Repository
My pligun version is v3.1.3

**Comment by rampara** [comment]
It doesn't seem like the JarResolver library copied the required Google Play Services AARs into the `Assets/Plugins/Android` directory of your project. Can you post the contents of this directory? If this directory does not contain the required Play Services AARs you can force dependency resolution by selecting `Assets->Google Play Services->Resolve Client Jars` in the Unity editor.

**Comment by rampara** [comment]
Closing this issue due to the lack of response. If this problem still persists for you please re-open the issue.
