### ISSUE TITLE
Native Overlay Ad (Ad Position not working)

### ISSUE THREAD

**Issue by Shahzaibi1122** [googleads/googleads-mobile-unity#3369]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: _2021.3.11_
  * Google Mobile Ads Unity plugin version: _Version 9.0_
  * Plugin installation method: _____ (unitypackage import)
  * Platform: _____ (Android)

#### Steps to reproduce:

What happened? How can we make the problem occur?

Native Overlay Ad Always stays at top position

To Reproduce :- Load Ad, RenderAd  with RenderTemplate(Style, AdPosition.Center) or any other position

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by NVentimiglia** [comment]
Hi,

We have confirmed the problem and are looking to release a fix.

**Comment by NVentimiglia** [comment]
We are still working on a fix.

**Comment by Shahzaibi1122** [comment]
ok

**Comment by duchv1234** [comment]
> We are still working on a fix.

Can you please fix it soon? :(

**Comment by NVentimiglia** [comment]
@Baonguyen-devg 

I will let the engineering team know. I have created a new issue since this issue is specific to banner ad.

https://github.com/googleads/googleads-mobile-unity/issues/3455
