### ISSUE TITLE
CommandInvokationFailure: Failed to re-package resources. See the Console for details.

### ISSUE THREAD

**Issue by stantler** [googleads/googleads-mobile-unity#337]
Unity 5.5.0f3 - empty project
Plugin v3.1.3
Resolver version: 10101

```
CommandInvokationFailure: Failed to re-package resources.
D:\Work\Android\sdk\build-tools\25.0.2\aapt.exe package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "D:/Work/Android/sdk\platforms\android-25\android.jar" -F bin/resources.ap_ --extra-packages com.google.unity

stderr[
AndroidManifest.xml:16: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.IAPTheme').

AndroidManifest.xml:18: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

]
stdout[
Configurations:
 (default)
 v14
 v21
 mdpi-v4
 xhdpi-v4

Files:
  drawable\app_banner.png
    Src: (xhdpi-v4) res\drawable-xhdpi\app_banner.png
  drawable\app_icon.png
    Src: (mdpi-v4) res\drawable-mdpi\app_icon.png
  values\strings.xml
    Src: () res\values\strings.xml
  values\styles.xml
    Src: () res\values\styles.xml
    Src: (v14) res\values-v14\styles.xml
    Src: (v21) res\values-v21\styles.xml
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
  Type drawable
    drawable\app_banner.png
      Src: (xhdpi-v4) res\drawable-xhdpi\app_banner.png
    drawable\app_icon.png
      Src: (mdpi-v4) res\drawable-mdpi\app_icon.png
  Type values
    values\strings.xml
      Src: () res\values\strings.xml
    values\styles.xml
      Src: () res\values\styles.xml
      Src: (v14) res\values-v14\styles.xml
      Src: (v21) res\values-v21\styles.xml
Including resources from package: D:\Work\Android\sdk\platforms\android-25\android.jar
applyFileOverlay for drawable
applyFileOverlay for layout
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: res\drawable-xhdpi\app_banner.png
Processing image: res\drawable-mdpi\app_icon.png
    (processed image res\drawable-mdpi\app_icon.png: 90% size of source)
    (processed image res\drawable-xhdpi\app_banner.png: 93% size of source)
    (new resource id app_banner from xhdpi-v4\drawable\app_banner.png #generated)
    (new resource id app_icon from mdpi-v4\drawable\app_icon.png #generated)
]
exit code: 1
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.PostProcessor.Tasks.TasksCommon.Exec (System.String command, System.String args, System.String workingdir, System.String errorMsg, Int32 retriesOnFailure)
UnityEditor.HostView:OnGUI()
```

And when I start JarResolver (`Assets->Play Services Resolver->Android resolver->Resolve clients Jars`) it throws error:
`XmlException: Document element did not appear.  Line 1, position 1.
Mono.Xml2.XmlTextReader.Read ()
System.Xml.XmlTextReader.Read ()
Google.JarResolver.PlayServicesSupport.ProcessMetadata (Google.JarResolver.Dependency dep, System.String fname)
Google.JarResolver.PlayServicesSupport.FindCandidate (System.String repoPath, Google.JarResolver.Dependency dep)
Google.JarResolver.PlayServicesSupport.FindCandidate (Google.JarResolver.Dependency dep)
Google.JarResolver.PlayServicesSupport.GetDependencies (Google.JarResolver.Dependency dep)
Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest)
GooglePlayServices.ResolverVer1_1.DoResolutionNoAndroidPackageChecks (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation)
GooglePlayServices.ResolverVer1_1+<DoResolution>c__AnonStorey5.<>m__8 ()
GooglePlayServices.ResolverVer1_1.DoResolution (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation, System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.Resolve (System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.MenuResolve ()`

Folder `Assets/Plugins/Android` have only package default files

**Comment by rampara** [comment]
It doesn't seem like the JarResolver library copied the required Google Play Services AARs into the `Assets/Plugins/Android` directory of your project. Can you post the contents of this directory? If this directory does not contain the required Play Services AARs you can force dependency resolution by selecting `Assets->Google Play Services->Resolve Client Jars` in the Unity editor.

**Comment by stantler** [comment]
As I mentioned previously my `Assets/Plugins/Android` folder have only `GoogleMobileAdsPlugin` from plugin.

And `Assets->Google Play Services->Resolve Client Jars` throws error:

`XmlException: Document element did not appear. Line 1, position 1. Mono.Xml2.XmlTextReader.Read () System.Xml.XmlTextReader.Read () Google.JarResolver.PlayServicesSupport.ProcessMetadata (Google.JarResolver.Dependency dep, System.String fname) Google.JarResolver.PlayServicesSupport.FindCandidate (System.String repoPath, Google.JarResolver.Dependency dep) Google.JarResolver.PlayServicesSupport.FindCandidate (Google.JarResolver.Dependency dep) Google.JarResolver.PlayServicesSupport.GetDependencies (Google.JarResolver.Dependency dep) Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest) GooglePlayServices.ResolverVer1_1.DoResolutionNoAndroidPackageChecks (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation) GooglePlayServices.ResolverVer1_1+<DoResolution>c__AnonStorey5.<>m__8 () GooglePlayServices.ResolverVer1_1.DoResolution (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation, System.Action resolutionComplete) GooglePlayServices.PlayServicesResolver.Resolve (System.Action resolutionComplete) GooglePlayServices.PlayServicesResolver.MenuResolve ()`

SDK Manager
![1](https://cloud.githubusercontent.com/assets/255450/21955459/9e13c9e0-da7c-11e6-9bce-2bab4f74b6e0.PNG)
![0](https://cloud.githubusercontent.com/assets/255450/21955460/9e18b84c-da7c-11e6-9b7a-25419683e2df.PNG)

Also if I copy `\Android\sdk\extras\google\m2repository\com\google\android\gms\play-services\10.0.1` files to `Assets/Plugins/Android` I'll recieve this error:
```
IOException: Failed to Move File / Directory from 'Temp/StagingArea\android-libraries\play-services-10.0.1\classes.jar' to 'Temp/StagingArea\android-libraries\play-services-10.0.1\libs\classes.jar'.
UnityEditor.Android.PostProcessor.Tasks.ProcessAAR.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (BuildPostProcessArgs args)
UnityEditor.PostprocessBuildPlayer.Postprocess (BuildTarget target, System.String installPath, System.String companyName, System.String productName, Int32 width, Int32 height, System.String downloadWebplayerUrl, System.String manualDownloadWebplayerUrl, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.BuildReporting.BuildReport report) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:186)
UnityEditor.HostView:OnGUI()
```

**Comment by rampara** [comment]
Missed the stack trace you included at the bottom of your original post. That error looks like one of the Play Services pom files that describes Play Services dependencies in XML is malformed. Can you re-downloading the latest Play Services files.

**Comment by stantler** [comment]
I solved this problem by compete removal and fresh installation of Android Studio and SDK
