### ISSUE TITLE
Android Gradle build Error (version 9.1.0)

### ISSUE THREAD

**Issue by HiepEldest** [googleads/googleads-mobile-unity#3379]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.35f1
  * Google Mobile Ads Unity plugin version: 9.1.0
  * Plugin installation method: .unitypackage import
  * Platform: Android, Unity Editor
  * Platform OS version: _____
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: Applovin-7.2.2, IronSource-3.0.1, Liftoff-5.1.1, Mintegral-1.6.1, Unity-3.11.0

### [REQUIRED] Step 2: Describe the problem
I upgrade the SDK from 8.6.0 to 9.0.1 and got this message when build

`The minCompileSdk (34) specified in a dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties) is greater than this module's compileSdkVersion (android-33). Dependency: androidx.webkit:webkit:1.11.0-alpha02.`

Should I upgrade Android API to 34?

**Comment by HiepEldest** [comment]
Downgrade Unity mediation to version 3.10.0 to resolve issue

**Comment by NVentimiglia** [comment]
I was unable to confirm the issue using `3.11.1`

**Comment by phuc-nor** [comment]
Hi @NVentimiglia , I just upgrade my Applovin adapter from 7.2.2 to 7.3.0 which has same issue with dependency: androidx.webkit:webkit:1.11.0-alpha02.
