### ISSUE TITLE
`Google.VersionHandler' has already been imported.

### ISSUE THREAD

**Issue by Kaldarash** [googleads/googleads-mobile-unity#338]
Updating my project to the new version of this mobile plugin and the play games plugin, and I get this error:
`error CS1704: An assembly with the same name `Google.VersionHandler' has already been imported. Consider removing one of the references or sign the assembly
Assets/PlayServicesResolver/Editor/Google.VersionHandler.dll (Location of the symbol related to previous error)
Assets/PlayServicesResolver/Editor/Google.VersionHandler_v1.2.6.0.dll (Location of the symbol related to previous error)`

Is there an easy solution? I don't want to break everything, these plugins already give me enough headaches without throwing a wrench in there myself.

**Comment by rampara** [comment]
Can you try deleting the contents of the `Assets/PlayServicesResolver` directory of your Unity project and re-importing the latest version of this plugin.

**Comment by Rainking80** [comment]
I see the same thing! I did the reimporting and error still appears...

**Comment by rampara** [comment]
@Rainking80 Can you post the contents of your `Assets/PlayServicesResolver` directory?

**Comment by Rainking80** [comment]
You mean like this:
![pservices](https://cloud.githubusercontent.com/assets/5574367/22161246/d2c1a488-df49-11e6-8a13-c6a7ae660f51.PNG)

**Comment by Rainking80** [comment]
Me again: I reimported the plugin again - same issue. I restarted unity 2 or 3 times then a "Google plugin is ready to use" popup appeared and now it seems to work!

**Comment by rampara** [comment]
Glad you were able to get everything working.

**Comment by rampara** [comment]
Closing this issue due to the lack of response from @Kaldarash . If this problem still persists for you please re-open the issue.

**Comment by salami** [comment]
I had this issue after updating to v3.6.0, but restarting Unity fixed it.

**Comment by rampara** [comment]
Selecting `Assets -> Play Services Resolver -> Version Handler -> Update` in the Unity editor should also resolve this issue.

**Comment by doanlinhit24** [comment]
@rampara That really works .Thank you

**Comment by shafayat18** [comment]
I solved the issue..
here is the solving video only for unity developer 
https://www.youtube.com/watch?v=PeQDGBnhgxA&t=20s

**Comment by RenalPraba** [comment]
It works, Thanks!
