### ISSUE TITLE
AdInspector failed to load - AdMob 9.1.0

### ISSUE THREAD

**Issue by dcosmin-97** [googleads/googleads-mobile-unity#3389]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.32f1
  * Google Mobile Ads Unity plugin version: 9.1.0
  * Plugin installation method:  .unitypackage import
  * Platform: Android
  * Platform OS version: Android 14
  * Any specific devices issue occurs on: I think all
  * Mediation ad networks used, and their versions: applovin 7.3.0, chartboost 4.6.0, dt exchange 3.1.12, ironsource 3.1.0, liftoff 5.1.1, meta 3.12.0, mintegral 1.6.2, pangle 2.8.1, unity 3.11.0 , firebase analytics 12.0.0, firebase crashlytics 12.0.0
  * 

#### Steps to reproduce:

- even if the test is manually registered as a test device and call the ad Inspector programmatically or if the device is added as test in the admob dashboard, the ad inspector is not opening.
- I receive the following issue:
{
  "Code": 1,
  "Message": "Ad inspector failed to load.",
  "Domain": "com.google.android.gms.ads",
  "Cause": "null"
}
UnityEngine._AndroidJNIHelper:InvokeJavaProxyMethod(AndroidJavaProxy, IntPtr, IntPtr)

Are there any workarounds? 
I need to make some tests on the ads.

Thank you!

**Comment by NVentimiglia** [comment]
- Make sure you are using a test device (you said you are).
- Make a request to load an ad before invoking ad inspector.

If the issue continues, open an issue with [SDK support](https://developers.google.com/admob/support).
