### ISSUE TITLE
TestMode

### ISSUE THREAD

**Issue by openxcellstudio** [googleads/googleads-mobile-unity#339]
hi,
if you also provide test mode bool in your script than it will be good for check ads in test-mode.
so that if check box is on than it will automatically fetch device id and add in to create request.

this is for suggestion

thanks.

**Comment by rampara** [comment]
Requiring the device identifier to enable test mode was a conscious decision in the GMA SDK which has been mirrored in this plugin. Having test mode set with a bool means test mode applies universally to all devices and distributing an app without removing the test mode call would result in lost revenue.
