### ISSUE TITLE
Applovin 7.3.0 - iOS Crash - AppLovinSDK (no such file)

### ISSUE THREAD

**Issue by dcosmin-97** [googleads/googleads-mobile-unity#3395]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.32f1
  * Google Mobile Ads Unity plugin version: 9.1.0
  * Plugin installation method: .unitypackage import
  * Platform: iOS
  * Platform OS version: iOS 17.5.1
  * Any specific devices issue occurs on: -
  * Mediation ad networks used, and their versions: applovin 7.3.0, chartboost 4.6.0, dt exchange 3.1.12, ironsource 3.1.0, liftoff 5.1.1, meta 3.12.0, mintegral 1.6.2, pangle 3.0.0, unity 3.11.1 , firebase analytics 12.0.0, firebase crashlytics 12.0.0

#### Steps to reproduce:

This my final podfile:
source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs'

platform :ios, '13.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '10.25.0'
  pod 'Firebase/Core', '10.25.0'
  pod 'Firebase/Crashlytics', '10.25.0'
  pod 'GoogleMobileAdsMediationAppLovin', '12.5.0.0'
  pod 'GoogleMobileAdsMediationChartboost', '9.7.0.0'
  pod 'GoogleMobileAdsMediationFacebook', '6.15.0.0'
  pod 'GoogleMobileAdsMediationFyber', '8.2.8.0'
  pod 'GoogleMobileAdsMediationIronSource', '8.1.0.0.1'
  pod 'GoogleMobileAdsMediationMintegral', '7.6.4.0'
  pod 'GoogleMobileAdsMediationPangle', '5.9.0.9.0'
  pod 'GoogleMobileAdsMediationUnity', '4.11.3.1'
  pod 'GoogleMobileAdsMediationVungle', '7.3.2.0'
  pod 'Google-Mobile-Ads-SDK', '~> 11.3.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static

My game crashes instantly, with the following error:
Error loading /var/containers/Bundle/Application/52BB3E43-1486-4EB6-8DA2-F67521DD36DC/MathMaster.app/Frameworks/UnityFramework.framework/UnityFramework (137):  dlopen(/var/containers/Bundle/Application/52BB3E43-1486-4EB6-8DA2-F67521DD36DC/MathMaster.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): Library not loaded: @rpath/AppLovinSDK.framework/AppLovinSDK
  Referenced from: <70ED1D5C-0AF5-3D87-A30F-D2891DC51576> /private/var/containers/Bundle/Application/52BB3E43-1486-4EB6-8DA2-F67521DD36DC/MathMaster.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: tried: '/usr/lib/swift/AppLovinSDK.framework/AppLovinSDK' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/AppLovinSDK.framework/AppLovinSDK' (no such file), '/private/var/containers/Bundle/Application/52BB3E43-1486-4EB6-8DA2-F67521DD36DC/MathMaster.app/Frameworks/AppLovinSDK.framework/AppLovinSDK' (no such file), '/usr/lib/swift/AppLovinSDK.framework/AppLovinSDK' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/AppLovinSDK.framework/AppLovinSDK' (no such file), '/private/var/containers/Bundle/Application/52BB3E43-1486-4EB6-8DA2-F67521DD36DC/MathMaster.app/Frameworks/AppLovinSDK.framework/AppLovinSDK' (no such file), '/private/var/containers/Bundle/Application/52BB3E43-1486-4EB6-8DA2-F67521DD36DC/MathMaster.app/Frameworks/AppLovinSDK.framework/AppLovinSDK' (no such file)

Any workaround?
I will try to downgrade to the previous applovin version to test.

Thank you!

**Comment by amjaliks** [comment]
Here are some links with more details about AppLovin SDK switching to dynamic linking:
* https://github.com/AppLovin/AppLovin-MAX-SDK-iOS/issues/314
* https://forum.unity.com/threads/applovinsdk-12-4-1-changed-from-a-static-to-dynamic-library.1587963/

A workaround worked for me: add `AppLovinSDK.xcframework` as Embedded Framework to `Unity-iPhone` target.

**Comment by NVentimiglia** [comment]
I have submitted this issue to engineering to create a better work around.

**Comment by RomainBitard** [comment]
> I have submitted this issue to engineering to create a better work around.
updates on this problem ?

**Comment by farazk86** [comment]
A better work around as mentioned in the above Unity Discussions link is to open EDM settings from Assets>External Dependency Manager > iOS resolver > Settings and Uncheck “Link frameworks statically”

This will fix the crash and you wont have to manually add the applovinsdk.framework to build phases in XCode every time :)

**Comment by RomainBitard** [comment]
Thanks for sharing, I think I tried that without success in my case but I'll keep it in mind
