### ISSUE TITLE
[build] Failed to transform play-services-measurement-api-22.0.0.aar

### ISSUE THREAD

**Issue by dreamcodestudio** [googleads/googleads-mobile-unity#3397]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.33f1
  * Google Mobile Ads Unity plugin version: 9.1.0
  * Plugin installation method:  .unitypackage import
  * Platform: Android
  * Platform OS version: Any
  * Any specific devices issue occurs on: Any
  * Mediation ad networks used, and their versions: AppLovin-7.3.0, IronSource-3.1.0, LiftoffMonetize-5.1.1, Mintegral-1.6.3, Pangle-3.0.0, UnityAds-3.11.1

#### Steps to reproduce:

1. Setup Unity Environment by config:

> Android Minimum API Level = 23
> Android Target API Level = 34
> Target platform = Android
> Scripting Backend = Mono
> API Level  = .NET Standard 2.1

2. Build in APK or AAB format

In result Unity shows `Gradle build failed` :

```
* What went wrong:
Execution failed for task ':launcher:mergeExtDexDebug'.
> Could not resolve all files for configuration ':launcher:debugRuntimeClasspath'.
   > Failed to transform play-services-measurement-api-22.0.0.aar (com.google.android.gms:play-services-measurement-api:22.0.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-incremental-transform=true, dexing-is-debuggable=true, dexing-min-sdk=23, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: E:\Develop\Gradle_Custom_Cache\caches\transforms-2\files-2.1\e6412b3f412eb21e3a3fe30aa3f77d46\jetified-play-services-measurement-api-22.0.0-runtime.jar.
         > Error while dexing.
   > Failed to transform koin-core-jvm-3.5.3.jar (io.insert-koin:koin-core-jvm:3.5.3) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-incremental-transform=true, dexing-is-debuggable=true, dexing-min-sdk=23, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for DexingWithClasspathTransform: E:\Develop\Gradle_Custom_Cache\caches\transforms-2\files-2.1\8ec559f0e294fcb667680bde48958dc0\jetified-koin-core-jvm-3.5.3.jar.
         > Error while dexing.
   > Failed to transform koin-annotations-jvm-1.3.0.jar (io.insert-koin:koin-annotations-jvm:1.3.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-incremental-transform=true, dexing-is-debuggable=true, dexing-min-sdk=23, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for DexingWithClasspathTransform: E:\Develop\Gradle_Custom_Cache\caches\transforms-2\files-2.1\c95ba173d6118453dede757609d9a773\jetified-koin-annotations-jvm-1.3.0.jar.
         > Error while dexing.
   > Failed to transform kotlin-stdlib-1.9.21.jar (org.jetbrains.kotlin:kotlin-stdlib:1.9.21) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-incremental-transform=true, dexing-is-debuggable=true, dexing-min-sdk=23, org.gradle.category=library, org.gradle.jvm.environment=standard-jvm, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for DexingWithClasspathTransform: E:\Develop\Gradle_Custom_Cache\caches\transforms-2\files-2.1\0338abce55fea20d9562da3aa37e3c62\jetified-kotlin-stdlib-1.9.21.jar.
         > Error while dexing.
```

**Comment by nventimigli** [comment]
Hi, I was unable to replicate this issue. I installed the latest Google Mobile Ads plugin, the mentioned addapters, and made sure I executed the [gradle integration](https://developers.google.com/admob/unity/gradle#unity-integrated-builds) guide on Unity 2021.

That said, your error `mergeExtDexDebug` comes from trying to import too much java code. Some things you can try:

- Delete gradle caches
- Use R8 to minify.
- make sure you use multidex.

**Comment by NVentimiglia** [comment]
Hi, I was unable to replicate this issue. I installed the latest Google Mobile Ads plugin, the mentioned addapters, and made sure I executed the [gradle integration](https://developers.google.com/admob/unity/gradle#unity-integrated-builds) guide on Unity 2021.

That said, your error mergeExtDexDebug comes from trying to import too much java code. Some things you can try:

Delete gradle caches
Use R8 to minify.
make sure you use multidex.

**Comment by dreamcodestudio** [comment]
Ok i try it on empty sandbox project and post the results

**Comment by dreamcodestudio** [comment]
On sandbox project i get errror:
```
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (34) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-33).
     Dependency: androidx.webkit:webkit:1.11.0-alpha02.**
     **
     ```
     New versions sdks requirment target API 34?

**Comment by dreamcodestudio** [comment]
But after set target API 34, sandbox build completed.
I will collect more info in work project, maybe it collapse on some third-party plugins.

**Comment by dreamcodestudio** [comment]
On work project, build works fine after deleted Firebase Unity SDK, i will try update it to latest version `v12.1.0`

**Comment by dreamcodestudio** [comment]
About Firebase:
![image](https://github.com/googleads/googleads-mobile-unity/assets/7010398/d754a422-cae6-4f9a-b931-7060c9250fc2)

**Comment by NVentimiglia** [comment]
Glad you got this working,

Here is our guide for working with gradle in Unity.

https://developers.google.com/admob/unity/gradle

**Comment by iantierney** [comment]
> But after set target API 34, sandbox build completed. I will collect more info in work project, maybe it collapse on some third-party plugins.



> On work project, build works fine after deleted Firebase Unity SDK, i will try update it to latest version `v12.1.0`

I'm having the same error. Are you saying your project does not require firebase?
