### ISSUE TITLE
Error building Player: CommandInvokationFailure: Failed to re-package resources

### ISSUE THREAD

**Issue by SHAKEELABDULKARIM** [googleads/googleads-mobile-unity#340]
i am using unity 4.6.9 and this error is show i have updated android sdk. whatever plugin version is this error occurs when i make build for android

Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
/Users/Shakeel/Library/Android/sdk/build-tools/25.0.2/aapt package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "/Users/Shakeel/Library/Android/sdk/platforms/android-24/android.jar" -F bin/resources.ap_ --extra-packages com.google.unity

stderr[
AndroidManifest.xml:17: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.IAPTheme').

AndroidManifest.xml:19: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

]
stdout[
Configurations:
 (default)

Files:
  drawable/app_icon.png
    Src: () res/drawable/app_icon.png
  values/strings.xml
    Src: () res/values/strings.xml
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
  Type drawable
    drawable/app_icon.png
      Src: () res/drawable/app_icon.png
  Type values
    values/strings.xml
      Src: () res/values/strings.xml
Including resources from package: /Users/Shakeel/Library/Android/sdk/platforms/android-24/android.jar
applyFileOverlay for drawable
applyFileOverlay for layout
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: res/drawable/app_icon.png
    (processed image res/drawable/app_icon.png: 90% size of source)
    (new resource id app_icon from drawable/app_icon.png #generated)
]
<img width="214" alt="screen shot 2017-01-23 at 3 44 45 pm" src="https://cloud.githubusercontent.com/assets/6664291/22200873/eb91c656-e182-11e6-8515-5f49750e5b25.png">

**Comment by PAHeartBeat** [comment]
I think you missing "google-play-services_lib" folder in andorid folder
you can get this folder from "AndroidSDK/Extras/google/google-play-services/libproject/" and copy "google-play-services_lib" it to your Android folder inside Unity Project /Assets/Plugin/Android.

**Comment by SHAKEELABDULKARIM** [comment]
I have mac book and there is no libproject

**Comment by PAHeartBeat** [comment]
Please download ZIP file for "google_play_services_lib" it from above given link you can use 23 or 29 which I have used both version for my project it will work.

**Comment by SHAKEELABDULKARIM** [comment]
Thank you very much!

**Comment by rampara** [comment]
Closing this issue as it seems to have been resolved. Please re-open the issue if it persists for you.
