### ISSUE TITLE
Height of the smart banner

### ISSUE THREAD

**Issue by duchanhleo** [googleads/googleads-mobile-unity#341]
I have an issue with using SMART_BANNER
It is very important for me to know what height of banner, for example for prevention of overlay banner on some UI controls.
So as height of smart banner depends from device, i can't calculate banner height in Unity3D, as i can do for other banner types

Any ideas how this problem can be solved?

**Comment by PAHeartBeat** [comment]
Smart banner size  will be one of these
320 x 50 (mostly iPhone Portrait)
300 x 250 (Rare case)
468 x 60 (mostly iPad Portrait)
728 x 90 (mostly iPad Landscape)

you can calculate hight of banner on base of it I use Ortho camsize * 200 is pixel height of the game so I put space at top / bottom of 1 Unity Unit. its works for me.

**Comment by rampara** [comment]
How the ad heights (in density-independent pixel [dp]) is determinted is explained in our [banner developer docs](https://firebase.google.com/docs/admob/android/banner#smart_banners).
