### ISSUE TITLE
Module 'GoogleMobileAds' not found

### ISSUE THREAD

**Issue by AZERQSDF** [googleads/googleads-mobile-unity#343]
Hi im new I have problem on xcode
<img width="898" alt="capture d ecran 2017-01-31 a 19 30 39" src="https://cloud.githubusercontent.com/assets/25478076/22502440/c08c7dfa-e864-11e6-9013-6d38c0a2f994.png">

Libraries/Plugins/iOS/GADUNativeCustomTemplateAd.h:4:9: Module 'GoogleMobileAds' not found

without plugins GoogleMobileAds It works without problems plz how fix the problem

**Comment by rampara** [comment]
It looks like the GMA Framework wasn't added the the XCode project generated by Unity. Are you using the latest version of the plugin (3.2.0) ? Do you see any output in the Unity console that may indicate why the GMA SDK failed to be included in the generated XCode project? If you generate another iOS project, are you still seeing this issue?

**Comment by AZERQSDF** [comment]
yes I use v3.2.0 
in Unity console No problem

**Comment by rampara** [comment]
Is the problem reproducible when you try and generate a different Xcode project? Within the generated Xcode project, do you see the GoogleMobileAds framework under `Frameworks` as shown below?

<img width="459" alt="screen shot 2017-02-02 at 12 38 51 pm" src="https://cloud.githubusercontent.com/assets/11047881/22567436/b774d092-e944-11e6-8da4-b9a8bcfdceb8.png">

**Comment by AZERQSDF** [comment]
yes GoogleMobileAds framework  Does not exist
<img width="1440" alt="capture d ecran 2017-02-02 a 22 03 05" src="https://cloud.githubusercontent.com/assets/25478076/22570689/4ee1ae60-e994-11e6-85d2-a116425302a7.png">

**Comment by rampara** [comment]
Do you see any output at all in the Unity console when generating an Xcode project?

**Comment by AZERQSDF** [comment]
![capture d ecran 2017-02-03 a 10 05 59](https://cloud.githubusercontent.com/assets/25478076/22587182/8324eb1a-e9f8-11e6-8646-aa684c301171.jpg)

**Comment by rampara** [comment]
Can you [install Cocoapods](https://guides.cocoapods.org/using/getting-started.html) on your development machine and see if this issue persists for you?

**Comment by AZERQSDF** [comment]
thx I fix the problem https://www.youtube.com/watch?v=rxO_rcMxGU4
