### ISSUE TITLE
Applovin 7.3.0 build fail with Target API 33

### ISSUE THREAD

**Issue by phuc-nor** [googleads/googleads-mobile-unity#3435]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.27f1
  * Google Mobile Ads Unity plugin version: 9.1.0
  * Plugin installation method: Unity package manager
  * Platform OS version: Android, Unity Editor
  * Mediation ad networks used, and their versions: Applovin (7.3.0), Unity (3.10.0), DT(3.1.12), Inmobi (4.5.1), Ironsource(3.0.1),  Vungle(5.1.1), Meta(3.12.0), Mintegral(1.6.1), Pangle(2.8.0), Ogury

### [REQUIRED] Step 2: Describe the problem
The project build fine with Applovin 7.2.2 but when i tried to update adapter  to 7.3.0 the error occur when build

`The minCompileSdk (34) specified in a dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties) is greater than this module's compileSdkVersion (android-33). Dependency: androidx.webkit:webkit:1.11.0-alpha02.`

Should I upgrade Android API to 34 which need to update Unity Editor?

**Comment by NVentimiglia** [comment]
@phuc-nor 

Everything worked on my end using 2021 and the latest version of the aforementioned packages. Gradle / Android build issues can be super frustrating and I recommend following [Upgrade Gradle for Android](https://developers.google.com/admob/unity/gradle). Please note that the steps are ordered, and you may need to remove old gradle files for this to work.

**Comment by phuc-nor** [comment]
Hello @NVentimiglia. Thanks for your reply.
I'm build sucessful with Applovin 7.2.2 which mean I already have followed all the step that you recommended. (including custom Gradle v6.7.1 and set build tool to 4.2.0 in projectTemplate.gradle)
However, I managed to build with API target 34 along with [this guide](https://forum.unity.com/threads/unity-2021-3-38-with-android-api-34-build-fails.1590177) to pass the issue.
Thank you.
