### ISSUE TITLE
[Crash] [iOS] AppLovin mediation crash

### ISSUE THREAD

**Issue by OldSlash** [googleads/googleads-mobile-unity#3438]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.35f
  * Google Mobile Ads Unity plugin version: 9.1.0
  * Plugin installation method: unitypackage import
  * Platform: iOS, iPadOS
  * Platform OS version: 17.2.1 - 17.5.1 
  * Any specific devices issue occurs on: no
  * Mediation ad networks used, and their versions:  
AppLovin | 7.3.0
Chartboost | 4.6.0
Meta | 3.12.1
Liftoff | 5.1.0
Unity | 3.12.0
Pangle | 4.0.0

### [REQUIRED] Step 2: Describe the problem

We cannot reproduce this crash, but it is our top iOS crash in production.

Crash Reason:
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000050

File:
GoogleMobileAds.iOS.cpp
ReversePInvokeWrapper.RewardedAdClient_RewardedAdUserDidEarnRewardCallback

Also your crash looks like this one https://github.com/googleads/googleads-mobile-unity/issues/2840 , but this issue was closed and never fixed (see comments)

[crash.txt](https://github.com/user-attachments/files/16122928/com.Helium9Games.TennisArena2021_issue_6d7cae2acdc0dee6b623eb929426f2de_crash_session_57a5177a9055490bbcd3869bb419f183_DNE_0_v2_stacktrace.txt)

**Comment by NVentimiglia** [comment]
I did not experience this crash but I will submit this issue to the mediation team anyways because you have a crash log and it seems to be reoccurring.

**Comment by NVentimiglia** [comment]
Closing. Please reopen if AppLovin comes back with additional details.

**Comment by OldSlash** [comment]
> Closing. Please reopen if AppLovin comes back with additional details.

Why is this closed? It on GoogleMobileAdsMediationAppLovin , AppLovin SDK works fine
