### ISSUE TITLE
DummyClient.cs warnings

### ISSUE THREAD

**Issue by BaglGames** [googleads/googleads-mobile-unity#344]
I'm using Unity 5.5.1f1, how to fix it?

![image](https://cloud.githubusercontent.com/assets/25513945/22564799/d83e4e78-e996-11e6-8707-dd30507d9fcb.png)

**Comment by rampara** [comment]
You can ignore the warnings for now, they aren't indicative of any issues in the behavior of the plugin. Will address them in an upcoming update.

**Comment by BaglGames** [comment]
Ok, thank you very much!

**Comment by rampara** [comment]
No problem.

**Comment by rampara** [comment]
This issue has been resolved by #354.
