### ISSUE TITLE
IOs build errors

### ISSUE THREAD

**Issue by 2rusbekov** [googleads/googleads-mobile-unity#346]
Hi. Got next issues. v3.2.0. Unity 5.5.1

![shot](https://cloud.githubusercontent.com/assets/9072463/22617009/7d278582-eae4-11e6-9c70-d02a5c1b78ca.PNG)

**Comment by rampara** [comment]
Within your Xcode project, can you try navigating to the the project Build Settings panel, searching for “module” and setting `Enable Modules (C and Objective-C)` to `YES`.

**Comment by vain-g** [comment]
Most errors disapeared but next
Umbrella header "GoogleMobleAds.h" not found
Could not build module "GoogleMobileAds"

**Comment by 2rusbekov** [comment]
Most errors disapeared but next
Umbrella header "GoogleMobleAds.h" not found
Could not build module "GoogleMobileAds"

**Comment by PAHeartBeat** [comment]
Hi @2rusbekov,

I think its issue of Framework reference setting in XCode, we face that issue in past lots-of time when we use AdMob 3rd Party Plugin, that time we use a trick.

Just remove "GoogleMobileAds.framework" from "Target => General => Linked Framework and Libraries"  and re-drag n Drop in it there.

**Comment by 2rusbekov** [comment]
@PAHeartBeat 
Thanks for reply, but it didn't work for me.

**Comment by PAHeartBeat** [comment]
@2rusbekov 

I can understand may it not work for you cos its trick to make fool :) XCode, but may some time its not work. as I also used in few month ago when we used 3rd part AdMob.

you can use this link https://www.youtube.com/watch?v=rxO_rcMxGU4. may it will help you. you can download latest / older version of AdMob SDK for iOS as per your choice.

or you can also that Framework in you asset folder in bellow given folder structure 
- Assets
- - GoogleMobileAds
- - - <API, Common, Editor, Platforms> folders here from AdMob Unity Plug-in
- - - Plugins
- - - - iOS
- - - - - <.mm or .m files from Unity Plugin>
- - - - - GoogleMobileAds.framework

**Comment by rampara** [comment]
As @PAHeartBeat mentioned, it looks like the GMA framework didn't make it into the Unity generated Xcode project. Do you see any output in the Unity console when building the Xcode project that might indicate what went wrong? Do you have Cocoapods installed on your development machine?

**Comment by forest7194** [comment]
Admob Plug-in v3.2.0, Unity 5.5.1, Xcode 8.2.1
When I build an empty Unity project with Admob plug-in implemented. I got the same error just like @2rusbekov. After I Enable Modules (C and Objective-C) to YES, there is only one error left, it said "Module 'GoogleMobileAds' not found".

![screen shot 2017-02-10 at 9 04 41 am](https://cloud.githubusercontent.com/assets/25660223/22811201/00db2624-ef70-11e6-8022-35d8e42f1895.png)

I tried many ways like import GoogleMobileAds.framework file manually or modify some linker flag but the error still there.

There is one more thing, my mac have installed Cocoapods, but when I build Xcode project from Unity, it didn't create *.xcworkspace. Also when I manually initialize cocoapods for the project, this is what I got:

![screen shot 2017-02-10 at 9 15 46 am](https://cloud.githubusercontent.com/assets/25660223/22811462/94d7cf8e-ef71-11e6-94c4-544fef340392.png)

After I change settings in build setting of the project like it suggested, I run pod update again:

![screen shot 2017-02-10 at 9 21 10 am](https://cloud.githubusercontent.com/assets/25660223/22811612/7036358e-ef72-11e6-88da-2a52dd123d4c.png)

**Comment by PAHeartBeat** [comment]
Hi @forest7194,

This is the framework reference issue in xCode. its happen some time.

If you not fine "GoogleMobileAds.framework" in project file, just jump to step 3.
Try this trick
1. Remove  "GoogleMobileAds.framework" from "Target => General => Linked Framework and Libraries" 
2. Delete ""GoogleMobileAds.framework" from project.
3. Now re-add "GoogleMobileAds.framework" from downloaded location and keep check selected for "Copy if Required" during add file in project.
4. Try to build project.

**Comment by forest7194** [comment]
Thank @PAHeartBeat, you tried your solution and it work! You have saved my day!

After I fix that, there is another error with GoogleMobileAds framework file "Umbrella header 'GoogleMobileAds' not found". After digging around, I found out it is because my unzip tool make GoogleMobileAds framework .zip file broken. So I change to another unzip program and it work perfectly. Hope it will save someone headache.

**Comment by 2rusbekov** [comment]
@PAHeartBeat, thanks. Redownloaded framework and seems like everything works.

**Comment by rampara** [comment]
@2rusbekov Closing this issue as it seems to have been resolved for you. However, the JarResolver library included in this plugin has an IOSResolver component that should have included the required GMA framework in the generated XCode project. If this didn't occur, there should be output in the Unity console indicating the reason dependency resolution failed.
