### ISSUE TITLE
Implementing UMP with TagForUnderAgeOfConsent

### ISSUE THREAD

**Issue by batteredhedgehog** [googleads/googleads-mobile-unity#3461]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.37f1
  * Google Mobile Ads Unity plugin version: 9.1.1
  * Plugin installation method: .unitypackage import  (Unity package manager, .unitypackage import)
  * Platform: iOS / Android (iOS, Android, Unity Editor)
  * Platform OS version: Android 14 , iOS 17 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: admob only

### [REQUIRED] Step 2: Describe the problem

In attempting to implement UMP I am trying to satisfy EU consent requirements.  I am not allowed to request consent from children.  The age definition of under age of consent differs in the EU by country (e.g. see https://euconsent.eu/digital-age-of-consent-under-the-gdpr/ )
I have an age gate UI, but how am I supposed to determine the correct age of consent for a given user so that I can set the TagForUnderAgeOfConsent flag appropriately?

**Comment by NVentimiglia** [comment]
When using the UMP SDK, consent is not requested from the user when [tagForUnderAgeOfConsent](https://developers.google.com/admob/ios/privacy/api/reference/Classes/UMPRequestParameters#tagforunderageofconsent) (TFUA) is set to true. Mixed audience apps should set this parameter for child users to ensure consent is not requested. In practice, when using the UMP SDK, this means ad requests for child users won’t be eligible for personalized ads.

Important: The TFUA tag set on the UMP SDK is not forwarded to the Google Mobile Ads SDK. You must set the [tagForUnderAgeOfConsent](https://developers.google.com/admob/ios/api/reference/Classes/GADRequestConfiguration#tagforunderageofconsent) ad request parameter explicitly to have it applied for ad requests. See [Tag an ad request for EEA, the UK, and Switzerland users for restricted data processing](https://support.google.com/admob/answer/9009425) for more information about data processing restrictions for these users.

That said, yes a [neutral age screen](https://support.google.com/googleplay/android-developer/answer/9867159?sjid=2109930334227353215-NC) is a good way to collect the age of the user.
