### ISSUE TITLE
AndroidJavaException: java.lang.ClassNotFoundException: com.google.unity.ads.UnityAdListener

### ISSUE THREAD

**Issue by ipulcrimx** [googleads/googleads-mobile-unity#347]
Hi...
I got this same problem with admob today...
this is the error code from logcat
`AndroidJavaException: java.lang.ClassNotFoundException: com.google.unity.ads.UnityAdListener
                                                                    java.lang.ClassNotFoundException: com.google.unity.ads.UnityAdListener
                                                                        at java.lang.Class.classForName(Native Method)
                                                                        at java.lang.Class.forName(Class.java:324)
                                                                        at java.lang.Class.forName(Class.java:285)
                                                                        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                                                        at com.unity3d.player.UnityPlayer.a(Unknown Source)
                                                                        at com.unity3d.player.UnityPlayer$b$1.handleMessage(Unknown Source)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at com.unity3d.player.UnityPlayer$b.run(Unknown Source)`

this problem happen because I export the unity project to android project and build it from android studio (this is the only way to build apk for me, because unity limiting number of libraries when building in unity itself). I use the play service version 10.01 (I make all my plugins have the same version)

**Comment by rampara** [comment]
In your generated Android Studio project, do you have a dependency entry within your app-level build.gradle file compiles in the GMA Plugin lib project? The line should look like the following:

`compile project(':GoogleMobileAdsPlugin')`

**Comment by josephbk117** [comment]
This problem is still persisting , now that I am using play service 10.0.2. App keeps crashing on start up after the unity splash screen.

**Comment by rampara** [comment]
If your app is crashing due to the same java.lang.ClassNotFoundException from your original post, it seems for some reason the `unity-plugin-library` JAR file from `Assets/Plugins/Android/GoogleMobileAdsPlugin/libs` is not making it into your Unity build. I would try removing all plugin related files from your project and re-integrating the latest version of the plugin.

**Comment by rampara** [comment]
Closing this issue due to non-response. If this issue still persists for you please re-open.

**Comment by Mirkobil** [comment]
Hi I'm struggling with this issue for more then 5 day here is screenshot http://prntscr.com/oifvz5

![Screenshot](https://image.prntscr.com/image/gEUGFXXHTdatnt9FwfLfMw.png)

this is happen when i enable Minify Proguard http://prntscr.com/oifzsp
![Screenshot](https://image.prntscr.com/image/5gCPctN3RZGXg8HG0yPdjw.png)

I have tried with/without User Proguard File 
when i set Proguard to none, i get some com.google.android.gms error on first download and lunch the app from play market

[Proguard file](https://drive.google.com/file/d/1cclr1ZgEeXLptiY5JbeXjk0o1lkHects/view?usp=sharing)

**Comment by stowy** [comment]
[This video](https://youtu.be/va0FQNlBUX0) helps with configuring proguard.

It looks like you're missing a jar file from the unity plugin. Can you try re-importing the Google Mobile Ads unity package?

**Comment by Mirkobil** [comment]
> [This video](https://youtu.be/va0FQNlBUX0) helps with configuring proguard.
> 
> It looks like you're missing a jar file from the unity plugin. Can you try re-importing the Google Mobile Ads unity package?

Thank u for your feedback
I could find unity plugin library 
![Screenshot](https://image.prntscr.com/image/qHeioh_WRoSB0RHQiQfWVQ.png)
but I'll re-import google ads anyway and did everything just like on video even custom glade template 

but no luck.. same error

**Comment by stowy** [comment]
Can you share a sample app on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines)? If you want you could examine the jar to ensure the class is in there. Also check that it is included in the final APK.
