### ISSUE TITLE
GetTexture2DFromByteArray'

### ISSUE THREAD

**Issue by srikanthch888** [googleads/googleads-mobile-unity#348]
GetTexture2DFromByteArray'

**Comment by srikanthch888** [comment]
When I import asset in unity  it get's error
"GetTexture2DFromByteArray'"

**Comment by rampara** [comment]
Are you using the latest version of the plugin? Have you modified the plugin in any way? Are you able to reproduce this error in an empty Unity project?

**Comment by kujo87** [comment]
Do you have your own class somewhere called Utils that isn't in its own namespace? I had this issue, and so had to add in Common.Utils.GetTexture2DFromByteArray to the CustomNativeTemplate class to make it pass

**Comment by rampara** [comment]
+1 to @kujo87's comment.

**Comment by rampara** [comment]
Closing this issue due to non-response. If this issue persists for you, please re-open it.
