### ISSUE TITLE
Banner Will Pop Down

### ISSUE THREAD

**Issue by SyedSaadWajid** [googleads/googleads-mobile-unity#3480]
* Unity version: 2022.3.16
  * Google Mobile Ads Unity plugin version: 9.1.1
  * Plugin installation method: .unitypackage import (Unity package manager, .unitypackage import)
  * Platform: iOS

Problem:
When it records an impression, the banner will pop down from the top position in IOS.  While in Android it is working fine

**Comment by NVentimiglia** [comment]
@SyedSaadWajid 

We have identified the issue and are looking into a solution.

**Comment by NVentimiglia** [comment]
@SyedSaadWajid 

I am not seeing this issue. What steps do I need to take to see this issue. I am have tried `AdPosition.Top` and `AdPosition.Bottom`.

![image](https://github.com/user-attachments/assets/d86047e0-d4be-485a-9b90-5bdc3a95ea10)
