### ISSUE TITLE
Cant build because of admob on macbook

### ISSUE THREAD

**Issue by Vandora-41** [googleads/googleads-mobile-unity#3488]
### [REQUIRED] Step 1: Describe your environment

  * Unity version:2021
  * Google Mobile Ads Unity plugin version: 9.1.1
  * Plugin installation method: unitypackage
  * Platform: ios
  * Platform OS version: idk

 Undefined symbol: _CGSizeFromGADAdSize
Undefined symbol: _GADAdSizeEqualToSize
Undefined symbol: _GADAdSizeFromCGSize
Undefined symbol: _GADAdSizeFullWidthPortraitWithHeight
Undefined symbol: _GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth
Undefined symbol: _GADErrorUserInfoKeyResponseInfo
Undefined symbol: _GADLandscapeAnchoredAdaptiveBannerAdSizeWithWidth
Undefined symbol: _GADPortraitAnchoredAdaptiveBannerAdSizeWithWidth
Undefined symbol: _OBJC_CLASS_$_GADAppOpenAd
Undefined symbol: _OBJC_CLASS_$_GADBannerView
Undefined symbol: _OBJC_CLASS_$_GADExtras
Undefined symbol: _OBJC_CLASS_$_GADInterstitialAd
Undefined symbol: _OBJC_CLASS_$_GADMobileAds
Undefined symbol: _OBJC_CLASS_$_GADRequest
Undefined symbol: _OBJC_CLASS_$_GADRewardedAd
Undefined symbol: _OBJC_CLASS_$_GADRewardedInterstitialAd
Undefined symbol: _OBJC_CLASS_$_GADServerSideVerificationOptions
Undefined symbol: _kGADAdSizeSmartBannerLandscape
Undefined symbol: _kGADAdSizeSmartBannerPortrait

im getting this error when im trying to build on xcode. im so sick of looking for solution because of admob. Please tell me how can i fix this

**Comment by burakekici** [comment]
Hi, I've faced with the same issue on Xcode. How did you resolve your issue? In my setup, it started after upgrading Adjust to v5.0.2.

**Comment by cimved** [comment]
I'm having the same issue. I've also upgraded Adjust to 5.0.2.

How'd you solve it @Vandora-41 ?
