### ISSUE TITLE
[Suggestion] External Dependency Manager Conflicts in Admob And Firebase 

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#3490]
### [REQUIRED] Step 1: Describe your environment

  * Google Mobile Ads Unity plugin version: 9.1.1, 9.2.0
  * Plugin installation method:  .unitypackage import
  * Platform: Android, Unity Editor

#### Steps to reproduce:
External Dependency Manager Conflicts in Admob And Firebase. Even when both are using same EDM version (e.g 1.2.181).
When we import admob and firebase even same EDM version of admob and firebase conflicts and re-write the files.
Which can leads to unkown bug or error.
I don't know if admob and firebase modifying EDM code or not. Or it has impact on admob or firebase.
Or we can un-check EDM after import any of admob or firebase.
![image](https://github.com/user-attachments/assets/64f23874-9df5-4fef-a54c-cc3010c1594f)

**Comment by NVentimiglia** [comment]
@MuhammadWaqasOfficial This is a known issue with installing via `.unitypackage` as there are shared dependencies.

As a work around you can try installing via the package manager which solves dependency resolutions.

https://developers.google.com/admob/unity/quick-start#openupm
