### ISSUE TITLE
More positioning options for Banner Ads

### ISSUE THREAD

**Issue by sten360** [googleads/googleads-mobile-unity#351]
Hi, 

the past 2 days I've been working on implementing ads to my game with this plugin. I had planned to show the banners a specific way, but it didn't take long to figure out that there's pretty much no way to position them aside from top/bottom/left/right. After that I made the decision to just leave the banner at the top and move my UI accordingly while a banner is displayed, except that turned out to be incredibly annoying due to DPI, DP and varying screen resolutions across different devices complicating the calculations immensely (Unity's Screen.dpi is also unreliable on some devices from what I read). It'd be great if I could just run a function and get the width/height of the displayed Smart Banner, and I know these functions exist in the base SDK, but I can't seem to figure out a way to do that with this plugin. I tried something like
`int BannerHeight = AdSize.SmartBanner.Height;`
but it always just returns 0. Am I missing something here?
(Another weird issue I have, which could be completely unrelated though, is that for some reason my Debug.Log commands don't fire at all within the OnAdLoaded etc handlers, and yet other functions and commands are working just fine. It's plain weird...)

Hence I figured I'd make a request here. I think the following features would make a lot of people's lives much easier:
1) An option to add margins to banners (e.g align to top, with 10px margin)
2) An option to easily get the width/height of the displayed Smart Banner, preferably in pixels

Thank you for your time.

**Comment by rampara** [comment]
As of v3.2.0, `BannerView` objects can be instantiated with an x and y values for position in addition to an`AdPosition`. 

As for your second issue, when you say other functions are working fine, are you able to see `Debug.log` output when called from any other function other than ad event handlers?

**Comment by rampara** [comment]
Closing this issue due to non-response. Please re-open if this issue persists for you.
