### ISSUE TITLE
Wrong Banner Position for iOS

### ISSUE THREAD

**Issue by smumair06** [googleads/googleads-mobile-unity#352]
I have created a banner with Top Position specified and it works perfect on android devices but on iOS it is shown at top left of the screen, though adPosition is Top.
Even, I have printed the value of adPosition in GADUBanner.m class using NSLog and it prints 0, which is
kGADAdPositionTopOfScreen = 0,          ///< Top of screen.

I have iPhone 5S with OS 10.2.1

**Comment by rampara** [comment]
Thanks for reporting this issue. Will be pushing out a fix shortly.

**Comment by rampara** [comment]
This issue has been fixed in the latest version of the plugin (v3.3.0).
