### ISSUE TITLE
Wrong Banner Position.Bottom for Android(No Physical/Capacitive Buttons)

### ISSUE THREAD

**Issue by keepup** [googleads/googleads-mobile-unity#353]
For only On-Screen Buttons(No Physical/Capacitive Buttons) Android Device, set banner position at bottom. Banner show like this:
![screenshot_20170222-165434](https://cloud.githubusercontent.com/assets/6658290/23205125/bd4d25ca-f923-11e6-9161-b4875ca75c11.png)
![screenshot_20170222-165441](https://cloud.githubusercontent.com/assets/6658290/23205127/be4fcce8-f923-11e6-9a00-81923d395501.png)

**Comment by rampara** [comment]
A fix for this issue has been implemented and should be pushed out shortly.

**Comment by rampara** [comment]
This issue has been fixed in the latest version of the plugin (v3.3.0).
