### ISSUE TITLE
Admob ads does not show up after linking

### ISSUE THREAD

**Issue by yusufyildiz86** [googleads/googleads-mobile-unity#358]
Details of the issue is as follows:
- http://stackoverflow.com/questions/42527082/admob-ads-does-not-show-up-after-linking

**Comment by rampara** [comment]
Can you provide the ad unit for which you're experiencing this issue? Which version of Google Play services did you build your Unity app with? During testing, did you only utilize test ads, or were you able to receive live ads as well?

**Comment by yusufyildiz86** [comment]
This is solved by helping Google Admob Team. When I go to my AdSense account that warns me "Your ad units are not displaying ads because you haven't provided your account payments information yet.". I added a payment method and it works now.
