### ISSUE TITLE
PHOTO INTERSTITIAL OPENS IN APP BROWSER

### ISSUE THREAD

**Issue by athenaisoft** [googleads/googleads-mobile-unity#359]
I have a game on iOS and Android:
Some times when i show a photo interstitial, it loads inside a browser.
I don't like that! It feels like a bug for users of my game. 
Am i doing something wrong or is this normal??

**Comment by rampara** [comment]
Are you experiencing this behavior on Android, iOS or both platforms? Are you able to get a video of this behavior?

**Comment by athenaisoft** [comment]
I only tested it on Android. Now im going to test it on iOS and i will let you know.
Video interstitials seem to work fine, without the browser. 
The browser appears only for photo interstitials.

![17105783_10212309139189382_180269674_o 2](https://cloud.githubusercontent.com/assets/26154412/23536606/d9d9e94e-ffa4-11e6-9789-131a40e72328.png)

**Comment by athenaisoft** [comment]
Any idea of why this is happening? 

Here is the code im using to show ads:

`   AdRequest request;
    InterstitialAd deathVideoInterstitial;
    InterstitialAd deathPhotoInterstitial;
    

    void Awake()
    {
        if (instance == null)
        {
            instance = this;
        }
    }

    void Start()
    {
        request = new AdRequest.Builder().Build();
        LoadDeathVideoInterstitial();
        LoadDeathPhotoInterstitial();
    }

    public bool isRewardAdLoaded()
    {
       return Advertisement.IsReady("rewardedVideo") || deathVideoInterstitial.IsLoaded() || deathPhotoInterstitial.IsLoaded();
    }
    

    void LoadDeathPhotoInterstitial()
    {
        deathPhotoInterstitial = new InterstitialAd(deathPhotoID);
        deathPhotoInterstitial.LoadAd(request);
    }

    void LoadDeathVideoInterstitial()
    {
        deathVideoInterstitial = new InterstitialAd(deathVideoID);
        deathVideoInterstitial.LoadAd(request);
    }
    

    public bool ShowDeathVideo()
    {
        bool ok;
        if ((ok=Advertisement.IsReady()))
            Advertisement.Show();
        else if ((ok = deathVideoInterstitial.IsLoaded()))
        {
            deathVideoInterstitial.Show();
            LoadDeathVideoInterstitial();
        }
        else if ((ok = deathPhotoInterstitial.IsLoaded()))
        {
            deathPhotoInterstitial.Show();
            LoadDeathPhotoInterstitial();
        }
        return ok;
    }

    public bool ShowDeathPhotoInterstitial()
    {
        bool ok;
        if ((ok=deathPhotoInterstitial.IsLoaded()))
        {
            deathPhotoInterstitial.Show();
            LoadDeathPhotoInterstitial();
        }
        return ok;
    }

    public void ShowRewardAd()
    {
        if (Advertisement.IsReady("rewardedVideo"))
            ShowUnityRewardedAd();
        else if (deathVideoInterstitial.IsLoaded())
        {
            deathVideoInterstitial.Show();
            LoadDeathVideoInterstitial();
            LevelCompletedMenu.instance.rewardedAdFinished();
        }
        else if(deathPhotoInterstitial.IsLoaded())
        {
            deathPhotoInterstitial.Show();
            LoadDeathPhotoInterstitial();
            LevelCompletedMenu.instance.rewardedAdFinished();
        }
    }`

**Comment by athenaisoft** [comment]
anyone?? please help!!

**Comment by rampara** [comment]
@athenaisoft A small number interstitial ads can be rendered in [chrome custom tabs](https://developer.chrome.com/multidevice/android/customtabs). However, this behavior should only apply to a very small percentage of ads seen by your users and by in large the standard interstitial experience is what your users will see.
