### ISSUE TITLE
AdMob banner hides behind other activities

### ISSUE THREAD

**Issue by saqibhayatmalik** [googleads/googleads-mobile-unity#3596]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2023.2.20
  * Google Mobile Ads Unity plugin version: 9.2.0
  * Plugin installation method: .unitypackage import
  * Platform: Unity
  * Platform OS version: Android 14
  * Any specific devices issue occurs on: Every device
  * Mediation ad networks used, and their versions: No mediation

#### Steps to reproduce:

I am using a package for a WebView. By adding that package, admob banner is not visible but clickable. I am attaching a sample project.

[WebView.AdMob.zip](https://github.com/user-attachments/files/16846219/WebView.AdMob.zip)

**Comment by NVentimiglia** [comment]
Hi @saqibhayatmalik

This looks like an issue with the WebView plugin. The implementation of this plugin is an `.arr` file, which means I have no way of inspecting what is happening. Please talk to the plugin vendor and tell them about the issue.
