### ISSUE TITLE
RewardedVideo NOT working iOS with AdMob  SDK 7.18

### ISSUE THREAD

**Issue by YHSX88** [googleads/googleads-mobile-unity#360]
Using: 
Xcode: Version 8.2.1 (8C1002)
Unity: 5.5.0f3
AdMob SDK: cocopods:
source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :integrate_targets => false
platform :ios, ‘9.0’

target 'Unity-iPhone' do
pod 'Google-Mobile-Ads-SDK', '~> 7.18'
end

When click the reward button on the iPhone I'm gettting meesage in Xcode:
**"2017-03-04 20:46:33.158287 MyAppName[991:262895] <Google> Ignoring request. 
Another request is already in progress."**

MyCode Implementation:

```
private RewardBasedVideoAd rewardBasedVideo;
private bool rewardBasedEventHandlersSet;

```
1.Functions are part of a Singleton Object Script
```
public void RequestRewardBasedVideo()
{
    Debug.Log ("Start Loading... G rewards");
    string adUnitId = "ca-app-pub-REST OF THE CODE";
    rewardBasedVideo = RewardBasedVideoAd.Instance;

    AdRequest request = new AdRequest.Builder()
    .AddTestDevice("MY TEST DEVICE ID IS HERE")  // My test device.
    .Build();
    rewardBasedVideo.LoadAd(request, adUnitId);

    if (!rewardBasedEventHandlersSet)
    {
        Debug.Log ("registering callBacks");
        rewardBasedVideo.OnAdRewarded += HandleRewardBasedVideoRewarded;
        rewardBasedEventHandlersSet = true;
    }
}

public void ShowRewardBasedVideo()
{
    if (rewardBasedVideo.IsLoaded())
    {
        Debug.Log ("has Video ie..e Loaded");
        rewardBasedVideo.Show();
    } else {
        Debug.Log ("NO Video was Loaded");
        //RequestRewardBasedVideo ();
    }
}

public void HandleRewardBasedVideoRewarded(object sender, Reward args)
{
    string type = args.Type;
    double amount = args.Amount;
    print("User rewarded with: " + amount.ToString() + " " + type);
}
```

The problem is that I can't get the Ad showing + I tried with real apps ,
just to see if it will work but it it's not.
When reward button in my UI is clicked I two functions are executing:
```
TEST.instance.RequestRewardBasedVideo();
TEST.instance.ShowRewardBasedVideo();
```
_I'm not requesting anywhere in the code another Rewarded Video._

Please help, I can say by using the same versions of the tools I got successfully:
 banner and interstitial Test Ads

**Comment by rampara** [comment]
Taking a look at the code snippets you provided, it doesn't seem like there should be an issue. Are you waiting after making your initial request to receive either the `OnAdFailedToLoad` or `OnAdLoaded` ad events before making a second ad request?

**Comment by YHSX88** [comment]
Well how long I should wait I'm waiting like 10 - 30 sec and I tried again but the thing is that with the first attempt is saying that there is request already. That's the strange thing and with the editor I'm seeing the debug logs say that the add should Show. i.e. no issue at all.

**Comment by rampara** [comment]
After 30 seconds, your ad request should timeout and you should receive the `OnAdFailedToLoad` ad event. Getting the `Ignoring request. Another request is already in progress.` message on your first ad request is not expected behavior and I'm having trouble reproducing that. Are you also seeing the same behavior in the [sample app](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) included in this repo.

**Comment by YHSX88** [comment]
I just tried with the HelloWorld App and again not working very strange I just changed the device test ID and the ads Units IDs. Bear in mind the test were done by setting deployment targets to 6.0 and then to 9.0. My app was set to 9.0

Here is log from Xcode
```

2017-03-07 19:46:41.462938 ProductName[270:8922] [DYMTLInitPlatform] platform initialization successful

2017-03-07 19:46:41.505655 ProductName[270:8893] -> registered mono modules 0x1009adf20
2017-03-07 19:46:41.603213 ProductName[270:8893] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
-> applicationDidFinishLaunching()
2017-03-07 19:46:41.625530 ProductName[270:8893] Metal GPU Frame Capture Enabled
2017-03-07 19:46:41.626146 ProductName[270:8893] Metal API Validation Disabled
2017-03-07 19:46:41.719041 ProductName[270:8893] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-03-07 19:46:41.719847 ProductName[270:8893] [MC] Reading from public effective user settings.
-> applicationDidBecomeActive()
GfxDevice: creating device client; threaded=1
Init: screen size 750x1334
Initializing Metal device caps: Apple A9 GPU
Initialize engine version: 5.5.0f3 (38b4efef76f0)
UnloadTime: 0.243791 ms

//Here I clicked on the button Labeled: "Request Rewarded Video"
HandleRewardBasedVideoFailedToLoad event received with message: Failed to receive ad with error: Request Error: No ad to show.
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

//Here I clicked on the button Labeled: "Show Rewarded Video"
Reward based video ad is not ready yet
GoogleMobileAdsDemoScript:OnGUI()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
```

Something else to point out: I'm successfully getting banner and interstitial with the test hello world app. 

P.S. I succeeded in integrating Chartboost to show rewarded video but not AdMob.
Now I'll try with my app and I'll see if I'll get the OnAdFailedToLoad event. I'll keep you updated.
BTW I'm using iPhone 6S 64GB

**Comment by rampara** [comment]
Can making a request with the rewarded video test ad unit for iOS (ca-app-pub-3940256099942544/1712485313).

**Comment by YHSX88** [comment]
Hi just to let you know I subscribed for this event and below are the logs:

```
HandleRewardBasedVideoFailedToLoadFailed to receive ad with error: Request Error: No ad to show.
System.EventHandler`1:Invoke(Object, TEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
GoogleMobileAds.iOS.RewardBasedVideoAdClient:RewardBasedVideoAdDidFailToReceiveAdWithErrorCallback(IntPtr, String)
```

I'll try now to make request with the ad Unit you posted.

**Comment by YHSX88** [comment]
Same thing I can't believe it's something else what I'm missing can you please post the test project you are using i mean your version that is working. This is the debug log:

```
GfxDevice: creating device client; threaded=1
Init: screen size 750x1334
Initializing Metal device caps: Apple A9 GPU
Initialize engine version: 5.5.0f3 (38b4efef76f0)
UnloadTime: 0.249666 ms
HandleRewardBasedVideoFailedToLoad event received with message: Failed to receive ad with error: Request Error: No ad to show.
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Reward based video ad is not ready yet
GoogleMobileAdsDemoScript:OnGUI()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
```

**Comment by rampara** [comment]
Can you try removing the call to `AddTestDevice` with your device id when building your `AdRequest` object. The ad unit I provided in my earlier post is a test ad unit, so you shouldn't run into any issues when using it without adding a test device id.

**Comment by YHSX88** [comment]
Now with the test app and this adunit that you gave me is WORKING. I removed the test device and test emulator options. So how do you explain this ?

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

```
HandleRewardBasedVideoLoaded event received
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UnityEngine.MonoBehaviour:print(Object)
GoogleMobileAdsDemoScript:HandleRewardBasedVideoLoaded(Object, EventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
GoogleMobileAds.Api.RewardBasedVideoAd:<RewardBasedVideoAd>m__0(Object, EventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
GoogleMobileAds.iOS.RewardBasedVideoAdClient:RewardBasedVideoAdDidReceiveAdCallback(IntPtr)
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

HandleRewardBasedVideoOpened event received
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UnityEngine.MonoBehaviour:print(Object)
GoogleMobileAdsDemoScript:HandleRewardBasedVideoOpened(Object, EventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
GoogleMobileAds.Api.RewardBasedVideoAd:<RewardBasedVideoAd>m__2(Object, EventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
GoogleMobileAds.iOS.RewardBasedVideoAdClient:RewardBasedVideoAdDidOpenCallback(IntPtr)
GoogleMobileAds.iOS.Externs:GADUShowRewardBasedVideoAd(IntPtr)
GoogleMobileAds.iOS.RewardBasedVideoAdClient:ShowRewardBasedVideoAd()
GoogleMobileAds.Api.RewardBasedVideoAd:Show()
GoogleMobileAdsDemoScript:ShowRewardBasedVideo()
GoogleMobileAdsDemoScript:OnGUI()
 
```

BTW I tried to create a another adUnit in my AdMob Acc but it was not working , I also tried previously without test device option and it was not working i think I mentioned in the first post.
I'll make more tests tomorrow.

**Comment by rampara** [comment]
Not being able to receive rewarded video ads with the test device option set is currently an ad serving issue with AdMob. You can expect this issue to be addressed soon. For the time being to test rewarded video ads, you can remove the test device option and use the test ad unit as a workaround.

**Comment by YHSX88** [comment]
thanks

**Comment by yosun** [comment]
Still appears to be an issue for the latest unity admob

Test rewards ad id works.

Test device + custom rewards ad id does not work yields: 

Failed to receive ad with error: Request Error: No ad to show.
