### ISSUE TITLE
GADMediationAdapterFacebook failed to initialize

### ISSUE THREAD

**Issue by piascse10** [googleads/googleads-mobile-unity#3600]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.46f1
  * Google Mobile Ads Unity plugin version: 9.2.0
  * Plugin installation method: .unitypackage import
  * Platform: iOS
  * Platform OS version: iOS 17
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: Meta Audience Network Unity Mediation Plugin 3.12.2 (Meta Audience Network iOS Mediation Adapter 6.15.2.0)

#### Steps to reproduce:

Following https://developers.google.com/admob/unity/mediation/meta to integrate Meta Audience Network but encountering adapter failed to initialize error message.

```
Failed: Adapter failed to initialize. Adapter raised an exception during setup.
Adapter: GADMediationAdapterFacebook, Exception: FBAdInitSettings is a final class and cannot be subclassed.
FBAdInitSettings
```

I am using Xcode 15.4 and here is the pod,
```
source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs'

platform :ios, '12.0'

target 'UnityFramework' do
  pod 'FBSDKCoreKit', '~> 17.0.1'
  pod 'FBSDKCoreKit_Basics', '~> 17.0.1'
  pod 'FBSDKGamingServicesKit', '~> 17.0.1'
  pod 'FBSDKLoginKit', '~> 17.0.1'
  pod 'FBSDKShareKit', '~> 17.0.1'
  pod 'GoogleMobileAdsMediationAppLovin', '12.6.1.0'
  pod 'GoogleMobileAdsMediationFacebook', '6.15.2.0'
  pod 'Google-Mobile-Ads-SDK', '~> 11.5.0'
end
target 'Unity-iPhone' do
end
use_frameworks!
```

Possible duplicate: https://github.com/googleads/googleads-mobile-unity/issues/3355

**Comment by piascse10** [comment]
Adding use_frameworks! :linkage => :static solved that issue but then I got new exception related to ApplovinSDK and FBSDKCoreKit. As they are dynamic linkage I add them in Unity-iPhone -> Linked Framework and Libraries. Finally its working.

**Comment by takazawa-gg** [comment]
I am facing the same problem.
Do I need to make this change in the future?
https://github.com/googleads/googleads-mobile-unity/issues/3600#issuecomment-2348429742

**Comment by XOGamesHyoju** [comment]
I'm experiencing the exact same issue with the Meta Unity package version 3.13.0.
I wonder if there's any other way to make this initialize properly.
I need to keep the use_frameworks! :linkage setting because I encountered problems with another plugin that caused the iOS build to fail when launching, which is related to this setting. 

So, is there any alternative workaround available?
