### ISSUE TITLE
Lots of _GAD issues

### ISSUE THREAD

**Issue by cancaglar** [googleads/googleads-mobile-unity#3601]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.16
  * Google Mobile Ads Unity plugin version: v9.2.0
  * Plugin installation method:  .unitypackage 
  * Platform: iOS

I tried it with the latest version and the previous version but I get the same errors.

<img width="285" alt="Screenshot 2024-09-12 at 15 39 26" src="https://github.com/user-attachments/assets/64cf4c86-7995-4ea1-8fd2-1c3d0b65519b">

**Comment by shalinratna** [comment]
I am having the same exact issues. Any fix?

**Comment by cimved** [comment]
I'm having this issue as well

**Comment by cancaglar** [comment]
well there is no fixed yet I think nor help.

**Comment by vinkini** [comment]
GAD prefix is used by the Google Mobile Ads iOS SDK. The Unity plugin uses Cocoapods to  fetch dependencies when the iOS Project is built. The GoogleMobileAds framework is a dependency that should be pulled in at this point. Can you confirm the GoogleMobileAds framework exists in the Pods project of the xcworkspace.
![Screenshot 2024-09-26 at 10 24 46 PM](https://github.com/user-attachments/assets/4af4a374-fe87-4487-a91f-7e8adaddfa22)

**Comment by cancaglar** [comment]
I just fixed the issue. I downgrade the SDK version to 7.2 and delete the all cocoapods in my computer and reinstall it again and I ran these codes :
```

sudo gem uninstall cocoapods -n /usr/local/bin

sudo gem install cocoapods -n /usr/local/bin

sudo gem install activesupport -v 6.1.7.3

pod install (run this at project path)
```
