### ISSUE TITLE
Google User Messaging Platform SDK for iOS 2.5.0 and later versions, The return value of CanRequestAd has changed from False to True when offline

### ISSUE THREAD

**Issue by XuQK** [googleads/googleads-mobile-unity#3609]
As the title said, it seems import from 2.5.0, the feature below:
<img width="973" alt="image" src="https://github.com/user-attachments/assets/85e22f94-fcc0-4368-a789-36120d1f3794">

Android's same features don't cause this.

**Comment by NVentimiglia** [comment]
This API is only for the UMP context. Other things which block downloading ads (such as network interference) should be checked independently.
