### ISSUE TITLE
Empty Unity app crashes upon opening - showing error about ads config on android

### ISSUE THREAD

**Issue by BigBangKing** [googleads/googleads-mobile-unity#3612]
My problem is very basic but I could not resolve it. I tried to use admob ads in my Unity project but I saw ads config related issue. To find out the base problem, I tried several Unity versions and used empty Unity project where only the ads plugin installed and followed steps from [here](https://developers.google.com/admob/unity/quick-start). No script is present and not showing ads and the ads sdk is not even initialized, to find out base issue. The demo app id has been set, libs resolver resolved and all things works on editor. Only when built and opened on android 14, it crashes immediately and shows this error: 
________________
`FATAL EXCEPTION: main (Ask...)
Process: net.dicelacancion.app, PID: 2548
java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException:`

******************************************************************************
* Invalid application ID. Follow instructions here:                          *
* https://googlemobileadssdk.page.link/admob-android-update-manifest         *
* to find your app ID.                                                       *
* Google Ad Manager publishers should follow instructions here:              *
* https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
******************************************************************************
  
  
	at android.app.ActivityThread.installProvider(ActivityThread.java:8489)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7989)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7675)
	at android.app.ActivityThread.-$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.IllegalStateException:

******************************************************************************
* Invalid application ID. Follow instructions here:                          *
* https://googlemobileadssdk.page.link/admob-android-update-manifest         *
* to find your app ID.                                                       *
* Google Ad Manager publishers should follow instructions here:              *
* https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
******************************************************************************
  
  
	at com.google.android.gms.ads.internal.client.zzek.attachInfo(com.google.android.gms:play-services-ads-lite@@23.2.0:15)
	at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@23.2.0:1)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8484)
	... 11 more`
_______________

I could not find a reason for this to happen. I have exported the project and checked and there was a meta tag with the sample app id. I will attach my settings and a few photos for further inspection. Its just an empty project that is showing this error, so I will not write reproducible steps. 
Please provide some information on how to fix this, and if this is not an issue anyone else facing then where could I be wrong. 

![Screenshot 2024-09-24 123615](https://github.com/user-attachments/assets/5addda4e-7357-4608-a469-c61c4bd822f1)

![Screenshot 2024-09-24 123738](https://github.com/user-attachments/assets/c21042d0-cfdf-4fe1-ac33-8513753b2bd5)

Would like to mention that on my main project, with banner ads, it is showing banner ads on editor but the above error shows up upon phone and emulator installation.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 6.0.19.f1, 2023.2.5.f1, 2022.3.20f1
  * Google Mobile Ads Unity plugin version: 9.2.0, V9.1.0
  * Plugin installation method: .unitypackage
  * Platform: Android
  * Platform OS version: Android14

#### Steps to reproduce:
Just en empty unity project with ads plugins installed.

**Comment by NVentimiglia** [comment]
Hi @BigBangKing

That all looks correct.  Could you share your startup code so I could double check it? Alternatively you can upload the project and I can look at it. If the project has personal content, you can reach out to https://developers.google.com/admob/support with a project as well.

**Comment by BigBangKing** [comment]
@NVentimiglia 
Hi, the problem has been resolved. It was due to my app ID being incorrect. Please close this issue and if possible delete this.
