### ISSUE TITLE
Need a new release which supports Android SDK 23.3 and iOS SDK 11.10

### ISSUE THREAD

**Issue by burakekici** [googleads/googleads-mobile-unity#3614]
Hello, 
We are using a mediation SDK. I should update the Play Services Ads SDKs but the latest Google Mobile Ads SDK 9.2.0 supports Android 23.2.0 and iOS 11.7.0. 
It has been 1.5 months since Play Services Ads Android 23.3.0 is released. When will the new Unity package update released?

**Comment by vinkini** [comment]
The GMA Android SDK 23.4.0 is currently being released and the Unity package will release along with that. Thank you for your patience and apologies for the delay.
