### ISSUE TITLE
New version with updated iOS SDK

### ISSUE THREAD

**Issue by rossojr92** [googleads/googleads-mobile-unity#3621]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.37f1
  * Google Mobile Ads Unity plugin version: 9.2.0
  * Plugin installation method: .unitypackage import
  * Platform: iOS
  * Platform OS version: All

#### Steps to reproduce:

Is there any planned date for the release of Google Mobile Ads Unity SDK 9.3.0 with updated Google Mobile Ads iOS SDK included?
It would be great because it is preventing us on updating some other plugins because cocoapods cannot successfully resolve the dependencies.

**Comment by vinkini** [comment]
We are working on a release (v9.2.1) and are planning to have it available later today. This release will target v11.10 of the iOS SDK.
