### ISSUE TITLE
Android Builds Crashing on Open With “Google Mobile Ads for Unity” 9.2.1 in Project

### ISSUE THREAD

**Issue by SamNeblett** [googleads/googleads-mobile-unity#3638]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.50f1 and 2023.3.20f1
  * Google Mobile Ads Unity plugin version: 9.2.1
  * Plugin installation method: UPM (Unity package manager, .unitypackage import)
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: Android 14 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: All Android phones
  * Mediation ad networks used, and their versions: AdMob, whatever version "Google Mobile Ads for Unity" 9.2.1 uses

### [REQUIRED] Step 2: Describe the problem
All builds crash on open. Completely empty Unity projects, except with "Google Mobile Ads for Unity" (9.2.1) and "External Dependency Manager for Unity" (1.2.183), and a sample scene with a camera and light. No code to call any ad services in the scene. "Google Mobile Ads for Unity" being added in the project at all causes all projects to crash on Android imminently on open. Apps with just "Google Mobile Ads for Unity" run on Android fine.

#### Steps to reproduce:
1. Create blank project in Unity 2022.3.50f1 or 2023.3.20f1
2. Follow instructions for installing "Google Mobile Ads Unity" with UPM here (do not do the "Initialize the SDK" section, just add the plugins): https://developers.google.com/admob/unity/quick-start
3. Enabled the Custom Main Gradle Template and Custom Gradle Properties Template options under Build in Publishing settings (outlined here: https://developers.google.com/admob/unity/quick-start)
4. Resolve (or Force Resolve, doesn't matter) in the Android Resolver for the Google External Dependency Manager
5. Set a Google Mobile Ads App ID (use a test ID)
6. Build for Android
7. Observe a crash on open

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
On Android: "[App Name] has stopped" on opening the app

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
[TestAdsProject.zip](https://github.com/user-attachments/files/17361009/TestAdsProject.zip)

// TODO(you): code here to reproduce the problem
```
Open the project in Unity 2023.3.20f1 (or downgrade, there's nothing really in this project, other than the Google packages)
Build to an Android device
Observe the crash

**Comment by vinkini** [comment]
Hello, Thanks for sharing the test project with us. We took a look at it and it seems the Google Mobile Ads App ID is wrongly set. It seems to be using an Adapter Banner **Ad Unit ID** (ca-app-pub-3940256099942544/9214589741) instead. Can you try with the sample Android App ID (ca-app-pub-3940256099942544~3347511713) and see if you still get a crash. 
To find the App ID and Ad Unit IDs from your account you can follow the instructions [here](https://support.google.com/admob/answer/7356431?sjid=2680469499459971427-NC).

**Comment by SamNeblett** [comment]
That worked, I had them mixed up. Thanks!
