### ISSUE TITLE
Standard Banner Off Automatically

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#3642]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.29f1
  * Google Mobile Ads Unity plugin version: 9.2.0
  * Plugin installation method: .unitypackage import
  * Platform: iOS( issue not confirmed yet ), Android ( Issue Confirmed )
  * Mediation ad networks used, and their versions: Applovin, Liftoff, Mintegral. (any respective admob 9.2.0 compatible versions)

#### Steps to reproduce:
**Issue: Standard banner turns off automatically after some time when admob banner is shown in mediation configured build.**
Banner didn't turn off and works correctly when admob is used without any mediation.

Edits:
- Test with real ads
- when it off, didn't show again even on automatic refresh or with banner.Show call
- Happens only on wifi internet, on mobile data its working correctly

**Comment by MuhammadWaqasOfficial** [comment]
Banner Showing
![BannerShowing](https://github.com/user-attachments/assets/ca378d91-8a65-4b2a-9da2-c8c96a46eb31)


Banner Off Automatically 
![BannerOffAutomatically](https://github.com/user-attachments/assets/2e5b5cba-c094-458c-9de5-a009f75f0f15)

**Comment by vinkini** [comment]
Do you get any [callbacks](https://developers.google.com/admob/unity/banner#listen_to_banner_view_events) on this Banner. Is it happening every time?. I am wondering if this has to do with Banner refresh. Even if we see an OnBannerAdLoadFailed callback, the SDK will make calls to load a new banner as long as refresh is not disabled for that ad unit ID.

**Comment by MuhammadWaqasOfficial** [comment]
When banner is off, it didn't show up again even sdk loads new banner ad on OnBannerAdLoadFailed callback or even you call banner.show again and again.
Automatic refresh is not disabled. And when its off refresh also not helps

**Comment by MuhammadWaqasOfficial** [comment]
> Do you get any [callbacks](https://developers.google.com/admob/unity/banner#listen_to_banner_view_events) on this Banner. Is it happening every time?. I am wondering if this has to do with Banner refresh. Even if we see an OnBannerAdLoadFailed callback, the SDK will make calls to load a new banner as long as refresh is not disabled for that ad unit ID.

When banner is off, it didn't show up again even sdk loads new banner ad on OnBannerAdLoadFailed callback or even you call banner.show again and again.
Automatic refresh is not disabled. And when its off refresh also not helps

Happen every time, in all my games with mediation.
Games with admob only not experiencing this issue.

**Comment by MuhammadWaqasOfficial** [comment]
one more thing, this happens only on wifi internet, on mobile data it works fine

**Comment by NVentimiglia** [comment]
Hi, can you submit a support request [here](https://developers.devsite.corp.google.com/admob/support) please include your ad unit ids and the mediation adapters you are using.

**Comment by MuhammadWaqasOfficial** [comment]
> Hi, can you submit a support request [here](https://developers.devsite.corp.google.com/admob/support) please include your ad unit ids and the mediation adapters you are using.

no, i am not an google employee or have access to this
![image](https://github.com/user-attachments/assets/07443bdf-e8f2-4a5a-84dc-744112d5d200)

**Comment by NVentimiglia** [comment]
@MuhammadWaqasOfficial 

I sent the wrong link, try this https://developers.google.com/admob/support
