### ISSUE TITLE
NonClickable area behind banner though it was hidden

### ISSUE THREAD

**Issue by rchallenger** [googleads/googleads-mobile-unity#366]
We have a scene #2 with button at the bottom of the screen. The scene loading as second scene after application starts. The scene #1 is the first scene to start. It contains AdsManager, which performs initialization of GoogleAds api and requests bannerAd. This scene is empty and it loads scene #2 exactly after MonoBehaviour.Start().
After creating new BannerView with necessary params and calling bannerView.LoadAd (...) we receive event bannerView.OnAdLoaded() but it is not visible yet.
We will call bannerView.Show() only in scene #3. And we'll call bannerView.Hide() as scene #2 will be active.
So our button (UnityEngine.UI.Button) in scene #2 with no bannerView visible will be clickable only at its top border (center and bottom space wont be interactive, like there is something placed in front of it). The border of "invisible shield" is the same as the border of bannerAd, which will be shown at the scene #3.
So button is almost inactive.
But as soon as we go to scene #3, show bannerAd and go back to scene #2 - this button will become completely interactive, like somebody removed this "invisible shield". Same issue will appear if we will turn off internet connection on device.
If we disable ads and remove any bannerAd creation at scene #1 this "invisible shield won't appear any more.

Such an issue occurred after last few updates.
Will tell more after reverting plugin version to earlier.

We use Unity3D 5.3.4, Google Mobile Ads Unity Plugin v3.3.0

**Comment by rampara** [comment]
This has been fixed with f0efba71db9adc9bca18d2964bf20e629964ff53.
