### ISSUE TITLE
Banner problem Order in Layer and Dissapear if minimize the app

### ISSUE THREAD

**Issue by Rost4Love** [googleads/googleads-mobile-unity#3662]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.11f
  * Google Mobile Ads Unity plugin version: v9.2.0
  * Plugin installation method: .unitypackage import (Unity package manager, .unitypackage import)
  * Platform: Editor / Android (iOS, Android, Unity Editor)
  * Platform OS version: Android 11 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: Redmi Note 8 Pro
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:

![image](https://github.com/user-attachments/assets/5e8f24b0-898a-47b6-b49c-65ced8cc1fad)

The problem is that I put the code that initializes the ad order on the prefab, but for some reason this code is not on the prefab on the phone (I tested and wrote Debug.Log, there is no log on the phone, there is one in the editor). And the order is always lost in the prefab itself, even though I set it to 4. Why does my script disappear on the prefab (on the phone)?

#### Relevant Code:

```
using GoogleMobileAds.Api;
using UnityEngine;

namespace Ad
{
   public class AdBannerManager : BaseAdManager
   {
       private BannerView _bannerView;
       private bool _isAdShown;

       #region Control Ad

           protected override void LoadAd()
           {
           }

           public override void ShowAd()
           {
               if (!_adManager.GetAdData().AdEnabled) return;

               if (_bannerView != null) return;
               
               CreateBannerView();
               
               AdRequest request = new AdRequest();
               _bannerView?.LoadAd(request);
               
               RegisterAdEvents();
               _isAdShown = true;
           }

           private void CreateBannerView()
           {
               if(_bannerView != null) DestroyBanner();
               
               AdSize adSize = AdSize.GetCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth(AdSize.FullWidth);
               AdPosition adPosition = AdPosition.Bottom;
               _bannerView = new BannerView(_adId, adSize, adPosition);
           }

           public void HideAd()
           {
               _bannerView.Hide();
               _isAdShown = false;
           }

           private void DestroyBanner()
           {
               UnregisterAdEvents();
               
               if (_bannerView != null)
               {
                   _bannerView.Destroy();
               }
               
               _bannerView = null;
           }

       #endregion

       #region Event Handling

           protected override void RegisterAdEvents()
           {
           }

           protected override void UnregisterAdEvents()
           {
           }

           protected override void OnDestroy()
           {
               base.OnDestroy();
               
               DestroyBanner();
           }

           protected void OnApplicationPause(bool pauseStatus)
           {
               if (!pauseStatus && _isAdShown)
               {
                   DestroyBanner();
                   ShowAd();
               }        
           }

       #endregion
   }
}
```

And another:

```
using Sirenix.OdinInspector;
using UnityEngine;

namespace Unity.UI
{
    [RequireComponent(typeof(Canvas))]
    public class CanvasInitializer : MonoBehaviour
    {
        [BoxGroup("Setting")] [SerializeField] private int _orderLayer;
        
        private Canvas _canvas;

        private void Awake()
        {
            Debug.Log("[Banner] Prefab loaded: " + gameObject.name);
            
            _canvas = GetComponent<Canvas>();
            _canvas.renderMode = RenderMode.ScreenSpaceCamera;
            _canvas.worldCamera = Camera.main;
            _canvas.sortingOrder = _orderLayer;
        }
    }
}
```
![image](https://github.com/user-attachments/assets/f329482c-d0b1-435d-a7a2-557d9441f10e)

There's also the problem that if you minimize the app, the banner disappears. Well, the loading shows immediately, without the need for Show.

**Comment by Rost4Love** [comment]
![image](https://github.com/user-attachments/assets/9c3c8006-6624-4375-b8ca-e045283e6af5)

Also as a bug, the fact that the design reward ads as interstitial.

**Comment by NVentimiglia** [comment]
@Rost4Love 

The editor implementation is only a minimal example to give you a basic understanding of how things work and should not be relied upon. The phone implementation is what is important and the phone implementation does not render using Unity's canvas system. The phone uses the native rendering (UIView / Android Layout) to render the banner ontop of Unity.

**Comment by Rost4Love** [comment]
> @Rost4Love 
> 
> The editor implementation is only a minimal example to give you a basic understanding of how things work and should not be relied upon. The phone implementation is what is important and the phone implementation does not render using Unity's canvas system. The phone uses the native rendering (UIView / Android Layout) to render the banner ontop of Unity.

So the layer setting won't work, right? And it's better to turn it off/on?

And why does the banner disappear when you turn the program inactive? It also doesn't work in the Reward editor.

**Comment by Rost4Love** [comment]
Basically I made a control over how to turn it on. But two questions remain.

1. Why the banner disappears when the application is not active (minimize).
2. Why there is no example of the work of forward advertising in the unitor, and instead it shows Interstitial.
