### ISSUE TITLE
Interstitial is Appearing only once. 

### ISSUE THREAD

**Issue by AdnanNazir** [googleads/googleads-mobile-unity#367]
Hello guys. 
Do you think I need to destroy the interstitial ad each time ???
Here is my code, 
 I have even tried destroying interstitial ads but still no luck. 
`private InterstitialAd interstitial;
    private void RequestInterstitial()
    {
#if UNITY_EDITOR
        string adUnitId = "unused";
#elif UNITY_ANDROID
            string adUnitId = "cXXXX";
#elif UNITY_IOS
            string adUnitId = "cXXXXX";
#else
            string adUnitId = "unexpected_platform";
#endif
        // Create an interstitial.
        interstitial = new InterstitialAd(adUnitId);
        // Register for ad events.
        interstitial.OnAdLoaded += HandleInterstitialLoaded;
        //interstitial.OnAdFailedToLoad += HandleInterstitialFailedToLoad;
        this.interstitial.OnAdOpening += this.HandleInterstitialOpened;
        this.interstitial.OnAdClosed += this.HandleInterstitialClosed;
        this.interstitial.OnAdLeavingApplication += this.HandleInterstitialLeftApplication;
        // Load an interstitial ad.
        interstitial.LoadAd(createAdRequest());
    }
    public void HandleInterstitialLoaded(object sender, EventArgs args)
    {
        print("HandleInterstitialLoaded event received.");
        if (interstitial != null && interstitial.IsLoaded())
        {
            interstitial.Show();
        }
    }
    public void HandleInterstitialOpened(object sender, EventArgs args)
    {
        //MonoBehaviour.print("HandleInterstitialOpened event received");
        if (interstitial != null)
            interstitial.Destroy();
    }

    public void HandleInterstitialClosed(object sender, EventArgs args)
    {
        //MonoBehaviour.print("HandleInterstitialClosed event received");
        if (interstitial != null)
            interstitial.Destroy();
    }

    public void HandleInterstitialLeftApplication(object sender, EventArgs args)
    {
        //MonoBehaviour.print("HandleInterstitialLeftApplication event received");
        if (interstitial != null)
            interstitial.Destroy();
    }

    public void ShowInterstitial()
    {
        if (interstitial != null && interstitial.IsLoaded())
        {
            interstitial.Show();
        }
        else
        {
            print("Interstitial is not ready yet.");
            if (interstitial == null)
                RequestInterstitial();
        }
    }`

**Comment by rampara** [comment]
What behavior are you currently seeing with this code? What platform (iOS or Android) are you deploying to? Why are you destroying the interstitial from the `OnAdOpened` event?

**Comment by AdnanNazir** [comment]
I am on Testing it on Android. 
The Ads loads only once or sometimes twice thrice !
Never more than that. 
Even by destroying Interstitial .

**Comment by AdnanNazir** [comment]
Which sample project are you talking about ?
The HelloWorld Example doesn't show how to request and load and destroy interstitial . 
There are buttons for requesting, showing and destroying interstitial which can't be used in a real game. They are for just testing purposes. 
What would be best practice to load ads ?
Can anyone help ?

**Comment by rampara** [comment]
When you interstitial fails to load after the first time, what error code are you receiving in the `OnAdFailedToLoad` ad event?

**Comment by AdnanNazir** [comment]
the console says internal error

**Comment by rampara** [comment]
Do you experience the same behavior when loading test interstitials (adunit `ca-app-pub-3940256099942544/1033173712 `)?

**Comment by rampara** [comment]
Closing this issue due to non-response. Please re-open if this issue persists for you.

**Comment by stevenfg** [comment]
asdsd
