### ISSUE TITLE
Crash UnityNativeTemplateAd$10.run

### ISSUE THREAD

**Issue by mmsbba4** [googleads/googleads-mobile-unity#3670]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.32f1
  * Google Mobile Ads Unity plugin version: 9.2.0
  * Plugin installation method: unitypackage import 
  * Platform: Android
  * Platform OS version: Android 14 
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem
My game uses native overlay ads. This error shows up in firebase Crashlytics at a very high rate. did i make a mistake somewhere?
Below is the error code :

Fatal Exception: java.lang.Error
FATAL EXCEPTION [main] Unity version : 2022.3.32f1 Device model : OPPO CPH2495 Device fingerprint: OPPO/CPH2495/OP52F3L1:14/UP1A.230620.001/T.R4T2.18c46bd-594b:user/release-keys CPU supported ABI : [arm64-v8a, armeabi-v7a, armeabi] Build Type : Release Scripting Backend : IL2CPP Libs loaded from : lib/arm64 Strip Engine Code : true

Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'void com.google.android.ads.nativetemplates.TemplateView.setVisibility(int)' on a null object reference

com.google.unity.ads.nativead.UnityNativeTemplateAd$10.run (UnityNativeTemplateAd.java:403)
android.os.Handler.handleCallback (Handler.java:958)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loopOnce (Looper.java:257)
android.os.Looper.loop (Looper.java:368)
android.app.ActivityThread.main (ActivityThread.java:8826)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:572)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1049)

**Comment by NVentimiglia** [comment]
Hi,

Can you include some sample code / replication steps on how you found this error ? In what order did you call the APIs?

**Comment by NVentimiglia** [comment]
Hi, this was fixed in 9.4.0 release.
