### ISSUE TITLE
Unable to Click "Continue" Button on Consent Form in isiOSAppOnMac Mode on Apple Silicon macOS

### ISSUE THREAD

**Issue by malt03** [googleads/googleads-mobile-unity#3674]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 6000.0.26f1
  * Google Mobile Ads Unity plugin version: 9.2.1
  * Plugin installation method: Unity package manager
  * Platform: iOS app on mac
  * Platform OS version: macOS 15.0
  * Any specific devices issue occurs on: Apple Silicon mac (macOS running iOS app in isiOSAppOnMac mode)
  * Mediation ad networks used, and their versions: Admob only

#### Steps to reproduce:

1. Run an iOS app built with Unity on an Apple Silicon Mac in isiOSAppOnMac mode.
2. Use ConsentForm.LoadAndShowConsentFormIfRequired to display the consent form.
3. Attempt to click the "Continue" button on the consent form.

#### Relevant Code:

```
ConsentForm.LoadAndShowConsentFormIfRequired();
```

<img width="754" alt="スクリーンショット 2024-11-12 9 58 38" src="https://github.com/user-attachments/assets/02065cd2-6fd5-44c9-a854-601869a2999d">

**Comment by NVentimiglia** [comment]
Thanks for raising awareness, we are looking into a fix.

**Comment by malt03** [comment]
Hi @NVentimiglia,

Thank you for your response earlier. I noticed that the issue has been closed—has this problem been fixed?

Thanks!
