### ISSUE TITLE
Test ads are working but real ads never work

### ISSUE THREAD

**Issue by AdnanNazir** [googleads/googleads-mobile-unity#368]
Hello, I have a pretty old Unity game that I recently updated. I have removed all ads sdks and using newest ad mob sdk only. 
I am strange issues, Test ads are always working both interstitial and banners with ids (mentioned below) that are in the Demo/Sample example. 

Banner: ca-app-pub-3940256099942544/6300978111
Interstitial: ca-app-pub-3940256099942544/1033173712

I even get 
Calling loadAd() on Android
Calling show() on Android
on the logcat. 
Ad IDs for my game works fine on my other apps but not this app.

**Comment by rampara** [comment]
If you handle the `OnAdFailedLoad` ad event, what error code you do you see?

**Comment by AdnanNazir** [comment]
I'll check and let you know !

**Comment by AdnanNazir** [comment]
I am getting these logs.  

HandleInterstitialFailedToLoad event received with message: Internal error
 HandleFailedToReceiveAd event received with message: Internal error

**Comment by rampara** [comment]
If test ad units are serving without issue, the problem is likely to do with your ad unit configuration. You can try reaching out on the [Google Mobile Ads SDK Technical Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for more help.
