### ISSUE TITLE
App crash after App Open Ads on jailbroken IOS devices

### ISSUE THREAD

**Issue by kmt1108** [googleads/googleads-mobile-unity#3696]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.31f1
  * Google Mobile Ads Unity plugin version: 9.1.1
  * Plugin installation method:  .unitypackage import
  * Platform: iOS
  * Platform OS version: Any iOS Jaibroken
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: Applovin, Inmobi, Litoff, Meta, Mintegral, Pangle,Unity Ads 

#### Steps to reproduce:

I released the app on November 11, from the release to November 18 I did not see any crashes. But starting from November 19 my app recorded crashes related to the App Open ads. All crashes are in the background and devices are jailbroken. Where could the cause come from?

All crashes return the same error:

Crashed: com.apple.main-thread
0  UnityFramework                 0x4a5cd7c il2cpp::gc::GCHandle::GetTarget(unsigned int) + 207 (GCHandle.cpp:207)
1  UnityFramework                 0x195de4c (Missing UUID 8fb725dbd60a393b999e0e370ce8ce4f)
2  SolitaireClassicCardGames      0x469f4b4 ReversePInvokeWrapper.AppOpenAdClient_AdDidDismissFullScreenContentCallback (GoogleMobileAds.iOS.cpp)
3  UnityFramework                 0x2c6b678 GAD_GADAppOpenAd_arm64_11_6_0 + 2788
4  UnityFramework                 0x2c54dac GAD_GADFullScreenAd_arm64_11_6_0 + 6532
5  UnityFramework                 0x2c55160 GAD_GADFullScreenAd_arm64_11_6_0 + 7480
6  UnityFramework                 0x2caf880 GADPostNotificationFromMainQueue + 4028
7  Foundation                     0x29d08 -[__NSObserver _doit:] + 316
8  CoreFoundation                 0x7cd1c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
9  CoreFoundation                 0x7ccdc ___CFXRegistrationPost_block_invoke + 48
10 CoreFoundation                 0x7c2c8 _CFXRegistrationPost + 400
11 CoreFoundation                 0x7bcc0 _CFXNotificationPost + 696
12 Foundation                     0x68f4 -[NSNotificationCenter postNotificationName:object:userInfo:] + 60
13 UnityFramework                 0x2caf3a0 GADPostNotificationFromMainQueue + 2780
14 UnityFramework                 0x2cae898 GADPostNotification + 104
15 UnityFramework                 0x2c5d18c GAD_GADIntermission_arm64_11_6_0 + 4164
16 UnityFramework                 0x2c5cfe8 GAD_GADIntermission_arm64_11_6_0 + 3744
17 UnityFramework                 0x2c5c714 GAD_GADIntermission_arm64_11_6_0 + 1484
18 UnityFramework                 0x2caf880 GADPostNotificationFromMainQueue + 4028
19 Foundation                     0x29d08 -[__NSObserver _doit:] + 316
20 CoreFoundation                 0x7cd1c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
21 CoreFoundation                 0x7ccdc ___CFXRegistrationPost_block_invoke + 48
22 CoreFoundation                 0x7c2c8 _CFXRegistrationPost + 400
23 CoreFoundation                 0x7bcc0 _CFXNotificationPost + 696
24 Foundation                     0x68f4 -[NSNotificationCenter postNotificationName:object:userInfo:] + 60
25 UnityFramework                 0x2caf3a0 GADPostNotificationFromMainQueue + 2780
26 UnityFramework                 0x2cae898 GADPostNotification + 104
27 UnityFramework                 0x2c3d6b0 GAD_GADFullScreenAdViewController_arm64_11_6_0 + 3368
28 UIKitCore                      0x46f284 -[UIViewController _setViewAppearState:isAnimating:] + 360
29 UIKitCore                      0x46ff8c -[UIViewController __viewDidDisappear:] + 140
30 UIKitCore                      0x4700a0 -[UIViewController _endAppearanceTransition:] + 220
31 UIKitCore                      0x359574 __48-[UIPresentationController transitionDidFinish:]_block_invoke + 292
32 UIKitCore                      0x3592bc -[UIPresentationController transitionDidFinish:] + 928
33 UIKitCore                      0x3633d4 -[_UICurrentContextPresentationController transitionDidFinish:] + 40
34 UIKitCore                      0x35d9c4 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.502 + 208
35 UIKitCore                      0x4920fc -[_UIViewControllerTransitionContext completeTransition:] + 100
36 UIKitCore                      0x48ec74 -[UIViewControllerBuiltinTransitionViewAnimator animateTransition:] + 2956
37 UIKitCore                      0x49668c ___UIViewControllerTransitioningRunCustomTransition_block_invoke_2 + 72
38 UIKitCore                      0x5c4728 +[UIInputResponderController _pinInputViewsForInputResponderController:onBehalfOfResponder:duringBlock:] + 104
39 UIKitCore                      0x49660c ___UIViewControllerTransitioningRunCustomTransition_block_invoke.641 + 176
40 UIKitCore                      0x1021fc4 +[UIView(Animation) _setAlongsideAnimations:toRunByEndOfBlock:] + 172
41 UIKitCore                      0x496474 _UIViewControllerTransitioningRunCustomTransition + 572
42 UIKitCore                      0x35d488 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.466 + 2200
43 UIKitCore                      0x362cb4 +[UIPresentationController _scheduleTransition:] + 96
44 UIKitCore                      0x35c948 -[UIPresentationController runTransitionForCurrentState] + 1728
45 UIKitCore                      0x35a16c -[UIPresentationController _dismissWithAnimationController:interactionController:target:didEndSelector:] + 624
46 UIKitCore                      0x47f0d0 __99-[UIViewController _dismissViewControllerWithAnimationController:interactionController:completion:]_block_invoke_2 + 72
47 UIKitCore                      0x10222f0 +[UIView(Animation) performWithoutAnimation:] + 96
48 UIKitCore                      0x47ef08 -[UIViewController _dismissViewControllerWithAnimationController:interactionController:completion:] + 596
49 UIKitCore                      0x10222f0 +[UIView(Animation) performWithoutAnimation:] + 96
50 UIKitCore                      0x47e35c -[UIViewController _dismissViewControllerWithTransition:from:completion:] + 1644
51 UIKitCore                      0x47da74 -[UIViewController dismissViewControllerWithTransition:completion:] + 2724
52 UIKitCore                      0x47cdb8 -[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 504
53 UIKitCore                      0x47f950 -[UIViewController dismissViewControllerAnimated:completion:] + 124
54 UIKitCore                      0xb6dd04 __68-[UIWindow _removeAllViewControllersFromWindowHierarchyFromDealloc:]_block_invoke + 60
55 UIKitCore                      0x476f48 +[UIViewController _performWithoutDeferringTransitionsAllowingAnimation:actions:] + 156
56 UIKitCore                      0xb6d9a8 -[UIWindow _removeAllViewControllersFromWindowHierarchyFromDealloc:] + 276
57 UIKitCore                      0xb6deb0 -[UIWindow setRootViewController:] + 284
58 UnityFramework                 0x2903e1c UnityCleanupTrampoline + 172 (UnityAppController.mm:172)
59 UIKitCore                      0xb3a838 -[UIApplication _terminateWithStatus:] + 240
60 UIKitCore                      0x206378 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 124
61 UIKitCore                      0x205ffc -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 216
62 UIKitCore                      0xb30874 -[UIApplication workspaceShouldExit:withTransitionContext:] + 208
63 FrontBoardServices             0x551c -[FBSUIApplicationWorkspaceShim workspaceShouldExit:withTransitionContext:] + 84
64 FrontBoardServices             0x2fc44 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke_2 + 76
65 FrontBoardServices             0x16420 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 232
66 FrontBoardServices             0x2fbe0 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke + 104
67 libdispatch.dylib              0x61298 _dispatch_client_callout + 16
68 libdispatch.dylib              0x3a000 _dispatch_block_invoke_direct$VARIANT$armv81 + 216
69 FrontBoardServices             0x54e04 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 40
70 FrontBoardServices             0x54acc -[FBSSerialQueue _targetQueue_performNextIfPossible] + 404
71 FrontBoardServices             0x54fa0 -[FBSSerialQueue _performNextFromRunLoopSource] + 28
72 CoreFoundation                 0x9a780 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
73 CoreFoundation                 0x9a680 __CFRunLoopDoSource0 + 204
74 CoreFoundation                 0x999d4 __CFRunLoopDoSources0 + 256
75 CoreFoundation                 0x93ef0 __CFRunLoopRun + 768
76 CoreFoundation                 0x936a8 CFRunLoopRunSpecific + 572
77 GraphicsServices               0x3570 GSEventRunModal + 160
78 UIKitCore                      0xb2f370 -[UIApplication _run] + 1052
79 UIKitCore                      0xb348ec UIApplicationMain + 164
80 UnityFramework                 0x2908908 -[UnityFramework runUIApplicationMainWithArgc:argv:] + 96 (main.mm:96)
81 SolitaireClassicCardGames      0x417c main + 28 (main.mm:28)

**Comment by NVentimiglia** [comment]
Closing as I see this case is being tracked internally though the support tracker.
