### ISSUE TITLE
Latest Google Admob Plugin for Unity seems Broken 

### ISSUE THREAD

**Issue by AdnanNazir** [googleads/googleads-mobile-unity#370]
Please see this when I click PlayServiceResolver>PackageManage>Settings 
then I am seeing this 
![capture](https://cloud.githubusercontent.com/assets/6734301/24039458/116e9048-0b27-11e7-8971-dcdc1f0b6ca5.PNG)

**Comment by AdnanNazir** [comment]
This issue can be closed. It takes just a bit of time for downloading and then the issue resolves itself. Could be issue because of my internet.

**Comment by rampara** [comment]
Closing issue as requested.
