### ISSUE TITLE
Vedio

### ISSUE THREAD

**Issue by Allhawasya** [googleads/googleads-mobile-unity#3702]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: _____
  * Google Mobile Ads Unity plugin version: _____
  * Plugin installation method: _____ (Unity package manager, .unitypackage import)
  * Platform: _____ (iOS, Android, Unity Editor)
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by Allhawasya** [comment]
https://github.com/googleads/googleads-mobile-unity/issues/3702#issue-2706254731

**Comment by Allhawasya** [comment]
Nice wabsait so butifull

**Comment by NVentimiglia** [comment]
@Allhawasya 

Can you please describe what the problem is ?
