### ISSUE TITLE
native overlay not woking 

### ISSUE THREAD

**Issue by trungq108** [googleads/googleads-mobile-unity#3703]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: _____
  * Google Mobile Ads Unity plugin version: _____
  * Plugin installation method: _____ (Unity package manager, .unitypackage import)
  * Platform: _____ (iOS, Android, Unity Editor)
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by NVentimiglia** [comment]
@trungq108 Can you provide more details ?
