### ISSUE TITLE
Campaigns

### ISSUE THREAD

**Issue by KVinS** [googleads/googleads-mobile-unity#372]
Hello! I'm using this plugin.
Recently, I decided to try Mediated house ads to promote my new games inside my applications.
I made several companies. Requests go to them, but Impressions 0. What could be the matter? Has anyone come across? Does this plugin support the сampaigns?

**Comment by rampara** [comment]
@KVinS this plugin does support house ad campaigns. However, this issue tracker is strictly for issues related to the plugin. For help debugging your ad serving issue I would recommend reaching out on the [Google Mobile Ads SDK Technical Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
