### ISSUE TITLE
Plugin killing fps when downloading ads

### ISSUE THREAD

**Issue by martineca** [googleads/googleads-mobile-unity#373]
Hi folks, 

I'm using this plugin in a 2d scrolling game but whenever a new ad is requested there is significant drop in fps which affect my game as the scrolling camera become choppy. It's doing it on some phones like sony 4ge, lg g4s etc.. as on other like most samsungs the issue is not there. 

I need to find solution to this one because I can't go further with the game when I know it's lagging for some user and killing the fun. 

I've tried the last two releases of the plugin and the result is the same. Couldn't start the sample projects as it has 12 errors in it for missing namespaces. 

Thanks.

**Comment by rampara** [comment]
At ad request time, the plugin doesn't perform any operations that would impact the frame-rate in any meaningful way and the issue can be attributed to the GMA Android SDK. This frame-rate drop you're experiencing is likely only to be experienced on much slower Android hardware but the Android SDK team is aware of the issue and working on improvements. These improvements will make it into future releases of the GMA Android SDK.

**Comment by rampara** [comment]
@martineca are you seeing this issue for all ad types or just for specific ones? Do you see a pattern in Android OS version on the devices that experience a slowdown vs those that don't? Can you provide a list of all devices where you're experiencing the issue (I can try to reproduce the issue on an identical device).

**Comment by martineca** [comment]
It's lagging when loading banner content or interstitial. After it has loaded the data the lag stops but if for some reason it has failed to load a banner it keeps lagging. So far I've reproduced the issue on Sony 4ge and LG G4s. @rampara

**Comment by rampara** [comment]
Closing issue as all ad rendering is performed by the Google Mobile Ads SDK. SDK issues can be raised on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
