### ISSUE TITLE
I'm sorry guys, but I can't comment

### ISSUE THREAD

**Issue by DanteAndroid** [googleads/googleads-mobile-unity#378]
![image](https://cloud.githubusercontent.com/assets/10005563/24276366/58631420-1071-11e7-9817-344128546f40.png)

Never met this, forgive me.
@

**Comment by Seani6** [comment]
Disable adblock on github and it should fix it

**Comment by AdnanNazir** [comment]
yes disabling AdBlock is the only way to use Github properly.

**Comment by DanteAndroid** [comment]
I've tried disabling adblock, seems not work. Comment in another computer now.
