### ISSUE TITLE
Unity Plugin 3.3.0 cannot build Xcode Project.

### ISSUE THREAD

**Issue by Fasox** [googleads/googleads-mobile-unity#379]
How to reproduce:

Unity 5.5.1f1

- Download and open the HelloWorld Sample Scene
- Import 3.3.0 UnityPackage
- Change to IOS Platform on Unity
- Build the project.

The build process get stuck on "Converting Managed Assemblies to C++"

Last fragment of the log :

`Used Assets and files from the Resources folder, sorted by uncompressed size:
 4.1 kb	 0.1% /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/GUISystem/UnityEngine.UI.dll
 4.1 kb	 0.1% /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/GUISystem/Standalone/UnityEngine.UI.dll
 1.8 kb	 0.0% /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/Networking/UnityEngine.Networking.dll
 1.8 kb	 0.0% /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/Networking/Standalone/UnityEngine.Networking.dll
 0.7 kb	 0.0% /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityHoloLens/RuntimeEditor/UnityEngine.HoloLens.dll
 0.7 kb	 0.0% /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityHoloLens/Runtime/UnityEngine.HoloLens.dll
 0.4 kb	 0.0% /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/PlaymodeTestsRunner/UnityEngine.PlaymodeTestsRunner.dll
 0.3 kb	 0.0% /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/Advertisements/UnityEngine.Advertisements.dll
 0.1 kb	 0.0% Resources/unity_builtin_extra
 0.1 kb	 0.0% Assets/GoogleMobileAds/Common/IRewardBasedVideoAdClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Common/ICustomNativeTemplateClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/iOS/CustomNativeTemplateClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/GoogleMobileAdsClientFactory.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Common/INativeExpressAdClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/iOS/RewardBasedVideoAdClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/iOS/NativeExpressAdClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Api/CustomNativeTemplateAd.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Api/CustomNativeEventArgs.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Api/AdFailedToLoadEventArgs.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Common/IInterstitialClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Api/Mediation/MediationExtras.cs
 0.1 kb	 0.0% /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityAnalytics/UnityEngine.Analytics.dll
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/iOS/InterstitialClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Api/RewardBasedVideoAd.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Api/NativeExpressAdView.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Api/ICustomInAppPurchase.cs
 0.1 kb	 0.0% Assets/Scripts/GoogleMobileAdsDemoScript.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/iOS/MonoPInvokeCallbackAttribute.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/Android/CustomNativeTemplateClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Common/IBannerClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Common/IAdLoaderClient.cs
 0.1 kb	 0.0% /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityPurchasing/UnityEngine.Purchasing.dll
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/iOS/AdLoaderClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Api/InterstitialAd.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/Android/RewardBasedVideoAdClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/Android/NativeExpressAdClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Common/DummyClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/iOS/BannerClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Api/BannerView.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Api/AdRequest.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Api/AdPosition.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/Android/InterstitialClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Common/Utils.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/iOS/Utils.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/iOS/Externs.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Api/Reward.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Api/Gender.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Api/AdSize.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Api/AdLoader.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/Android/InAppPurchase.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/Android/AdLoaderClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/Android/BannerClient.cs
 0.1 kb	 0.0% Assets/GoogleMobileAds/Platforms/Android/Utils.cs
Invoking UnusedByteCodeStripper2 with arguments: --api NET_2_0_Subset -out "/Users/eliseoviola/AdmobTest/Temp/StagingArea/Data/Managed/tempStrip" -l none -c link -b True -x "/Applications/Unity/PlaybackEngines/iOSSupport/Whitelists/Core.xml" -f "/Applications/Unity/Unity.app/Contents/il2cpp/LinkerDescriptors" -x "/Users/eliseoviola/AdmobTest/Temp/StagingArea/Data/Managed/../platform_native_link.xml" -x "/Users/eliseoviola/AdmobTest/Temp/StagingArea/Data/methods_pointedto_by_uievents.xml" -x "/Users/eliseoviola/AdmobTest/Temp/StagingArea/Data/preserved_derived_types.xml" -d "/Users/eliseoviola/AdmobTest/Temp/StagingArea/Data/Managed" -a  "/Users/eliseoviola/AdmobTest/Temp/StagingArea/Data/Managed/Assembly-CSharp.dll"
/Applications/Unity/Unity.app/Contents/Tools/UnusedByteCodeStripper2/UnusedBytecodeStripper2.exe exited after 1214 ms.
/Applications/Unity/Unity.app/Contents/Tools/InternalCallRegistrationWriter/InternalCallRegistrationWriter.exe exited after 149 ms.
Invoking UnusedByteCodeStripper2 with arguments: --api NET_2_0_Subset -out "/Users/eliseoviola/AdmobTest/Temp/StagingArea/Data/Managed/tempStrip" -l none -c link -b True -x "/Applications/Unity/PlaybackEngines/iOSSupport/Whitelists/Core.xml" -f "/Applications/Unity/Unity.app/Contents/il2cpp/LinkerDescriptors" -x "/Users/eliseoviola/AdmobTest/Temp/StagingArea/Data/Managed/../platform_native_link.xml" -x "/Users/eliseoviola/AdmobTest/Temp/StagingArea/Data/methods_pointedto_by_uievents.xml" -x "/Users/eliseoviola/AdmobTest/Temp/StagingArea/Data/preserved_derived_types.xml" -x "/Applications/Unity/PlaybackEngines/iOSSupport/Whitelists/Audio.xml" -x "/Applications/Unity/PlaybackEngines/iOSSupport/Whitelists/UnityConnect.xml" -x "/Applications/Unity/PlaybackEngines/iOSSupport/Whitelists/IMGUI.xml" -x "/Applications/Unity/PlaybackEngines/iOSSupport/Whitelists/UnityWebRequest.xml" -x "/Applications/Unity/PlaybackEngines/iOSSupport/Whitelists/JSONSerialize.xml" -x "/Applications/Unity/PlaybackEngines/iOSSupport/Whitelists/TextRendering.xml" -d "/Users/eliseoviola/AdmobTest/Temp/StagingArea/Data/Managed" -a  "/Users/eliseoviola/AdmobTest/Temp/StagingArea/Data/Managed/Assembly-CSharp.dll"
/Applications/Unity/Unity.app/Contents/Tools/UnusedByteCodeStripper2/UnusedBytecodeStripper2.exe exited after 1181 ms.
/Applications/Unity/Unity.app/Contents/Tools/InternalCallRegistrationWriter/InternalCallRegistrationWriter.exe exited after 149 ms.
Invoking il2cpp with arguments: --convert-to-cpp --emit-null-checks --enable-array-bounds-check --enable-symbol-loading --development-mode --map-file-parser="/Applications/Unity/Unity.app/Contents/Tools/MapFileParser/MapFileParser" --extra-types.file="/Applications/Unity/Unity.app/Contents/il2cpp/il2cpp_default_extra_types.txt" --assembly="/Users/eliseoviola/AdmobTest/Temp/StagingArea/Data/Managed/Assembly-CSharp.dll" --assembly="/Users/eliseoviola/AdmobTest/Temp/StagingArea/Data/Managed/UnityEngine.dll" --generatedcppdir="/Users/eliseoviola/AdmobTest/Temp/il2cppOutput/il2cppOutput" 
/Applications/Unity/Unity.app/Contents/il2cpp/build/il2cpp.exe exited after 13081 ms.
WebCamTexture class is used but Camera Usage Description is empty. App will not work on iOS 10+.
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
UnityEditor.iOS.PostProcessiPhonePlayer:PostProcess(BuildSettings, ProjectPaths, RuntimeClassRegistry) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:623)
UnityEditor.iOS.PostProcessiPhonePlayer:PostProcess(PostProcessorSettings, BuildPostProcessArgs) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:487)
UnityEditor.iOS.iOSBuildPostprocessor:PostProcess(BuildPostProcessArgs) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:34)
UnityEditor.PostprocessBuildPlayer:Postprocess(BuildTarget, String, String, String, Int32, Int32, String, String, BuildOptions, RuntimeClassRegistry, BuildReport) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:186)
UnityEditor.BuildPipeline:BuildPlayerInternalNoCheck(String[], String, String, BuildTarget, BuildOptions, Boolean)
UnityEditor.BuildPlayerWindow:BuildPlayerWithDefaultSettings(Boolean, BuildOptions, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:464)
UnityEditor.BuildPlayerWindow:BuildPlayerWithDefaultSettings(Boolean, BuildOptions) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:321)
UnityEditor.BuildPlayerWindow:GUIBuildButtons(IBuildWindowExtension, Boolean, Boolean, Boolean, BuildPlatform) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:1359)
UnityEditor.BuildPlayerWindow:ShowBuildTargetSettings() (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:1286)
UnityEditor.BuildPlayerWindow:OnGUI() (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:887)
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
System.Reflection.MethodBase:Invoke(Object, Object[]) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView:Invoke(String, Object) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:249)
UnityEditor.HostView:Invoke(String) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:242)
UnityEditor.HostView:OnGUI() (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:76)
(Filename: /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs Line: 623)
Microphone class is used but Microphone Usage Description is empty. App will not work on iOS 10+.
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
UnityEditor.iOS.PostProcessiPhonePlayer:PostProcess(BuildSettings, ProjectPaths, RuntimeClassRegistry) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:627)
UnityEditor.iOS.PostProcessiPhonePlayer:PostProcess(PostProcessorSettings, BuildPostProcessArgs) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:487)
UnityEditor.iOS.iOSBuildPostprocessor:PostProcess(BuildPostProcessArgs) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:34)
UnityEditor.PostprocessBuildPlayer:Postprocess(BuildTarget, String, String, String, Int32, Int32, String, String, BuildOptions, RuntimeClassRegistry, BuildReport) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:186)
UnityEditor.BuildPipeline:BuildPlayerInternalNoCheck(String[], String, String, BuildTarget, BuildOptions, Boolean)
UnityEditor.BuildPlayerWindow:BuildPlayerWithDefaultSettings(Boolean, BuildOptions, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:464)
UnityEditor.BuildPlayerWindow:BuildPlayerWithDefaultSettings(Boolean, BuildOptions) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:321)
UnityEditor.BuildPlayerWindow:GUIBuildButtons(IBuildWindowExtension, Boolean, Boolean, Boolean, BuildPlatform) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:1359)
UnityEditor.BuildPlayerWindow:ShowBuildTargetSettings() (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:1286)
UnityEditor.BuildPlayerWindow:OnGUI() (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:887)
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
System.Reflection.MethodBase:Invoke(Object, Object[]) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView:Invoke(String, Object) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:249)
UnityEditor.HostView:Invoke(String) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:242)
UnityEditor.HostView:OnGUI() (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:76)
(Filename: /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs Line: 627)`

**Comment by rampara** [comment]
Can you ensure you Cocoapods Specs repository is setup correctly on your machine? If you run the command `pod repo update`, do you encounter an error?

**Comment by rampara** [comment]
Closing this issue due to non-response. Please re-open if this issue persists for you.
