### ISSUE TITLE
.xcworkspace does not generate

### ISSUE THREAD

**Issue by ZJNPRI** [googleads/googleads-mobile-unity#380]
Hi,I'm a beginner for unity.I use cocoaPods to install firebase and admob.
I import firebase_unity_sdk_3.0.1 and admob Ads plugin.
And then build IOS project, it does not generate .xcworkspace.
Project contain a default Podfile file.

source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :integrate_targets => false
platform :ios, '7.0'

target 'Unity-iPhone' do
pod 'Firebase/Analytics', '3.14.0'
pod 'Firebase/Core', '3.14.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.13'
end

After I delete "install! 'cocoapods', :integrate_targets => false",then pod install,the xxx.xcworkspace appered.
I want to know the meaning of the code, and is it appropriate for me to do so?
What can I do to generate correct default project or Podfile?

Thank you.

**Comment by rampara** [comment]
The iOSReolver component of the [JarResolver](https://github.com/googlesamples/unity-jar-resolver) library does not create an xcworkspace. Dependencies required by this plugin and any Firebase plugin should be added to the standard Xcode project generated by Unity.

**Comment by rampara** [comment]
Closing this issue due to non-response. Please re-open if this issue persists for you.

**Comment by vilas18** [comment]
In my case i had project with same folder name("Project") ending with 1 , 2 ,3 ,4 (total 5 folders). when i was trying to install cocoapods in "Project 4" directory it was getting installed in "Project" instead it should be for "Project 4".

Hence i need to delete other folders with same name and then install pods in "Project" folder
