### ISSUE TITLE
Banner ads make area of screen un-interactable even whilst banner ad is hidden

### ISSUE THREAD

**Issue by Seani6** [googleads/googleads-mobile-unity#381]
Note this report is **not related** to my previous issue post where I mentioned making changes to the plugin to make the plugin work on older SDK versions. This issues happens on the unmodified 3.3.0 release.

The issue is that if I load any banner into memory the area of the screen where the banner will display becomes un-interactable _(the app doesn't recognise any taps, swipes etc over the area where the banner should be - tapping the area does nothing, it does not act as if the banner was tapped)_. The issue happens both when just loading an advert without actually making it visible and when loading an advert, making it visible then hiding it.

I've only been able to test the issue on 2 devices but I can test on more if needed, although I'm pretty busy. The issue is tested and confirmed on both the Samsung S7 Edge (SM-G935F) (Stock android 7.0) and Nexus 9 (Stock android 6.0.1)

There is a workaround for anyone trying to fix this issue though. Instead of hiding the banner destroy it from memory instead with **"YourActiveBannerViewReference.Destroy();"**

This issue has been tested to happen in both Unity 4.7.2 and Unity 5.2.2f1

**Comment by jykgod** [comment]
That's it ! I also find this issue with native ads when I call the hide method  to load ads and show it after a moment. But I find that there is a new commit to fix it.I build a new jar replacing the old and then crashed.  I find an error that **PopupWindow** isn't instantiated in NativeExpressAd.java. Calling the **createPopupWindow** in **create** method and then all is ok.

**Comment by rampara** [comment]
Both the issue mentioned in the original post and the issue presented by @jykgod have been resolved in the latest commits to the plugin.
