### ISSUE TITLE
Support for Unity 4.7.x (for 3.3.0)

### ISSUE THREAD

**Issue by genuinefafa** [googleads/googleads-mobile-unity#384]
I was using and old version of this plugin, but when update (latest 3.3.0) version, it start complaining about some method not found.

```
MissingMethodException: Method not found: 'UnityEditor.AssetDatabase.IsValidFolder'.
Google.PackageManager.ProjectManagerController..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Google.PackageManager.ProjectManagerController
System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (RuntimeTypeHandle type) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs:101)
UnityEditor.EditorAssemblies.RunClassConstructors ()
```

My guess is that there is a missing `#UNITY_5` somewhere, but I cannot figure out where. I was looking for this newer version for some pods issues.

**Comment by rampara** [comment]
This crash was fixed in an updated version of the [JarResolver](https://github.com/googlesamples/unity-jar-resolver) library included in this plugin. To pull in these fixes for the JarResolver library, you can rebuild this plugin with the Gradle build script included in the root directory of this repository.

**Comment by genuinefafa** [comment]
I'm not entirely sure if I undertand. The 3.3.0 version do not include the latest version of the plugin and that's why it throws `MissingMethodException` is that so?

The solution will be to clone googleads-mobile-unity, build, and include again. Right?

**Comment by rampara** [comment]
This plugin uses the JarResolver library I linked above. However, release v3.3.0 of this plugin included a version of JarResolver that had the issue you're running into. If you were to rebuild this plugin, it will pull in the latest version of JarResolver and that should resolve your issue.
