### ISSUE TITLE
Interstitial ads not showing when loaded Unity

### ISSUE THREAD

**Issue by NikolaTotev** [googleads/googleads-mobile-unity#385]
Hello I am having a problem with interstitial ads. I have set a text to show me which function has been executed and it shows that the ad is loaded. But when I press the button to show the ad it says "showing ad" on the text but nothing appears on the screen. @rampara  I know you are the guru here so I'm hoping you could help :D. 
This is the code I'm using *with removed ad id's*

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GoogleMobileAds;
using GoogleMobileAds.Api;
using UnityEngine.UI;

public class AdMobScript : MonoBehaviour
{

      private InterstitialAd interstitial;
      int Coins;
        public Text Test;
 
    // Use this for initialization
    void Start()
    {
        RequestBanner();
        RequestInterstitial();
        Coins = PlayerPrefs.GetInt("Coins", 0);
        // Get singleton reward based video ad reference.
        //this.rewardBasedVideo = RewardBasedVideoAd.Instance;
        //this.rewardBasedVideo.OnAdRewarded += this.HandleRewardBasedVideoRewarded;
    }

    // Update is called once per frame
    private void RequestBanner()
    {
#if UNITY_EDITOR
        string adUnitId = "unused";
#elif UNITY_ANDROID
        string adUnitId = "";
#elif UNITY_IPHONE
        string adUnitId = "INSERT_IOS_BANNER_AD_UNIT_ID_HERE";
#else
        string adUnitId = "unexpected_platform";
#endif

        BannerView bannerView = new BannerView(adUnitId, AdSize.Banner, AdPosition.Bottom);
        AdRequest request = new AdRequest.Builder().Build();
        bannerView.LoadAd(request);
    }

    // Interstitial Ad 
    private void RequestInterstitial()
    {
#if UNITY_ANDROID
        string adUnitId = "";
#elif UNITY_IPHONE
        string adUnitId = "INSERT_IOS_INTERSTITIAL_AD_UNIT_ID_HERE";
#else
        string adUnitId = "unexpected_platform";
#endif

        // Initialize an InterstitialAd.
        interstitial = new InterstitialAd(adUnitId);
        // Create an empty ad request.
        AdRequest request = new AdRequest.Builder().Build();
        // Load the interstitial with the request.
        interstitial.LoadAd(request);
        Test.text = " Ad Loaded";
    }

    private void ShowIntersitital()
    {
            interstitial.Show();
            Test.text = "Showing Ad";
    }

    public void GetCoins ()
    {
        ShowIntersitital();
        Coins = Coins + 15;
        PlayerPrefs.SetInt("Coins", Coins);
        PlayerPrefs.Save();
    }
}

**Comment by rampara** [comment]
Based on your code snippet, it doesn't look like you're not ensuring the ad has loaded before you're attempting to show it. `InsterstitialAd` objects have and `OnAdLoaded` event you can handle and and an `IsLoaded` method you can invoke. ie. something like the following:

```
if (interstitial.IsLoaded()) {
    interstitial.Show();
}
else
{
  print("Ad is not ready to show yet.")
}
```

You should also handle the `OnAdFailedToLoadEvent` so you know when an ad failed to load and the reason for the failure.

**Comment by NikolaTotev** [comment]
@rampara Ok I will try this. And a question I have -  where should the "print" show up

**Comment by NikolaTotev** [comment]
@rampara  Ok I just got the interstitials to work! Thank you very much for the exceptionally quick and helpful response! Now I just have to fix rewarded videos ( the other thread I joined ). Once again thank you a lot for the help here!

**Comment by rampara** [comment]
Closing this thread as this issue seems to have been resolved.
