### ISSUE TITLE
My Application crashes after using latest version of plugin.

### ISSUE THREAD

**Issue by aamiryatoo** [googleads/googleads-mobile-unity#386]
after building the app.
the app crashes on the startup.

i m using the demo script for displaying the ads.
didn't edit the android manifest.

**Comment by rampara** [comment]
@aamiryatoo Can you check logcat at the time of crash and provide the stacktrace for issue causing the crash?

**Comment by aamiryatoo** [comment]
i am just using the Google Mobile Ads Unity Plugin v3.3.0 in my project as i am testing the ad system for mediation purpose later on.
and i haven't added any other plugin not even google play services.

**Comment by aamiryatoo** [comment]
i am using the following script
using System;
using UnityEngine;
using GoogleMobileAds;
using GoogleMobileAds.Api;
using UnityEngine.UI;



// Example script showing how to invoke the Google Mobile Ads Unity plugin.
public class GoogleMobileAdsDemoScript : MonoBehaviour
{

	private BannerView bannerView;
	private InterstitialAd interstitial;
	private RewardBasedVideoAd rewardBasedVideo;
	private float deltaTime = 0.0f;
	private static string outputMessage = "";

	public Text text;
	public static string OutputMessage
	{
		set { outputMessage = value; }
	}

	void Start()
	{
		// Get singleton reward based video ad reference.
		rewardBasedVideo = RewardBasedVideoAd.Instance;

		// RewardBasedVideoAd is a singleton, so handlers should only be registered once.
		rewardBasedVideo.OnAdLoaded += HandleRewardBasedVideoLoaded;
		rewardBasedVideo.OnAdFailedToLoad += HandleRewardBasedVideoFailedToLoad;
		rewardBasedVideo.OnAdOpening += HandleRewardBasedVideoOpened;
		rewardBasedVideo.OnAdStarted += HandleRewardBasedVideoStarted;
		rewardBasedVideo.OnAdRewarded += HandleRewardBasedVideoRewarded;
		rewardBasedVideo.OnAdClosed += HandleRewardBasedVideoClosed;
		rewardBasedVideo.OnAdLeavingApplication += HandleRewardBasedVideoLeftApplication;
	}

	void Update()
	{
		// Calculate simple moving average for time to render screen. 0.1 factor used as smoothing
		// value.
		deltaTime += (Time.deltaTime - deltaTime) * 0.1f;
	}

	void OnGUI()
	{
		GUIStyle style = new GUIStyle();

		Rect rect = new Rect(0, 0, Screen.width, Screen.height);
		style.alignment = TextAnchor.LowerRight;
		style.fontSize = (int)(Screen.height * 0.06);
		style.normal.textColor = new Color(0.0f, 0.0f, 0.5f, 1.0f);
		float fps = 1.0f / deltaTime;
		string text = string.Format("{0:0.} fps", fps);
		GUI.Label(rect, text, style);

		// Puts some basic buttons onto the screen.
		GUI.skin.button.fontSize = (int)(0.03f * Screen.height);

		Rect requestBannerRect = new Rect(0.1f * Screen.width, 0.05f * Screen.height,
			0.8f * Screen.width, 0.1f * Screen.height);
		if (GUI.Button(requestBannerRect, "Request Banner"))
		{
			RequestBanner();
		}

		Rect showBannerRect = new Rect(0.1f * Screen.width, 0.175f * Screen.height,
			0.8f * Screen.width, 0.1f * Screen.height);
		if (GUI.Button(showBannerRect, "Show Banner"))
		{
			bannerView.Show();
		}

		Rect destroyBannerRect = new Rect(0.1f * Screen.width, 0.3f * Screen.height,
			0.8f * Screen.width, 0.1f * Screen.height);
		if (GUI.Button(destroyBannerRect, "Destroy Banner"))
		{
			bannerView.Destroy();
		}

		Rect requestInterstitialRect = new Rect(0.1f * Screen.width, 0.425f * Screen.height,
			0.8f * Screen.width, 0.1f * Screen.height);
		if (GUI.Button(requestInterstitialRect, "Request Interstitial"))
		{
			RequestInterstitial();
		}

		Rect showInterstitialRect = new Rect(0.1f * Screen.width, 0.55f * Screen.height,
			0.8f * Screen.width, 0.1f * Screen.height);
		if (GUI.Button(showInterstitialRect, "Show Interstitial"))
		{
			ShowInterstitial();
		}

		Rect requestRewardedRect = new Rect(0.1f * Screen.width, 0.675f * Screen.height,
			0.8f * Screen.width, 0.1f * Screen.height);
		if (GUI.Button(requestRewardedRect, "Request Rewarded Video"))
		{
			RequestRewardBasedVideo();
		}

		Rect showRewardedRect = new Rect(0.1f * Screen.width, 0.8f * Screen.height,
			0.8f * Screen.width, 0.1f * Screen.height);
		if (GUI.Button(showRewardedRect, "Show Rewarded Video"))
		{
			ShowRewardBasedVideo();
		}

		Rect textOutputRect = new Rect(0.1f * Screen.width, 0.925f * Screen.height,
			0.8f * Screen.width, 0.05f * Screen.height);
		GUI.Label(textOutputRect, outputMessage);
	}

	private void RequestBanner()
	{
		#if UNITY_EDITOR
		string adUnitId = "unused";
		#elif UNITY_ANDROID
		string adUnitId = "id here";
		#elif UNITY_IPHONE
		string adUnitId = "ca-app-pub-6745644712123529/7733382898";
		#else
		string adUnitId = "unexpected_platform";
		#endif

		// Create a 320x50 banner at the top of the screen.
		bannerView = new BannerView(adUnitId, AdSize.SmartBanner, AdPosition.Top);
		// Register for ad events.
		bannerView.OnAdLoaded += HandleAdLoaded;
		bannerView.OnAdFailedToLoad += HandleAdFailedToLoad;
		bannerView.OnAdLoaded += HandleAdOpened;
		bannerView.OnAdClosed += HandleAdClosed;
		bannerView.OnAdLeavingApplication += HandleAdLeftApplication;
		// Load a banner ad.
		bannerView.LoadAd(createAdRequest());
		}

		private void RequestInterstitial()
		{
		#if UNITY_EDITOR
		string adUnitId = "unused";
		#elif UNITY_ANDROID
		string adUnitId = "id here";
		#elif UNITY_IPHONE
		string adUnitId = "ca-app-pub-6745644712123529/9980783695";
		#else
		string adUnitId = "unexpected_platform";
		#endif

		// Create an interstitial.
		interstitial = new InterstitialAd(adUnitId);
		// Register for ad events.
		interstitial.OnAdLoaded += HandleInterstitialLoaded;
		interstitial.OnAdFailedToLoad += HandleInterstitialFailedToLoad;
		interstitial.OnAdOpening += HandleInterstitialOpened;
		interstitial.OnAdClosed += HandleInterstitialClosed;
		interstitial.OnAdLeavingApplication += HandleInterstitialLeftApplication;
		// Load an interstitial ad.
		interstitial.LoadAd(createAdRequest());
		}

		// Returns an ad request with custom ad targeting.
		private AdRequest createAdRequest()
		{
		return new AdRequest.Builder()
		.Build();
		}

		private void RequestRewardBasedVideo() 
		{
		#if UNITY_EDITOR
		string adUnitId = "unused";
		#elif UNITY_ANDROID
		string adUnitId = "id here";
		#elif UNITY_IPHONE
		string adUnitId = "ca-app-pub-7850304550335702/1221009279";
		#else
		string adUnitId = "unexpected_platform";
		#endif

		rewardBasedVideo.LoadAd(createAdRequest(), adUnitId);
		//text.text = "Request Sent for  Video";
		}

		private void ShowInterstitial()
		{
		if (interstitial.IsLoaded())
		{
		interstitial.Show();
		}
		else
		{
		print("Interstitial is not ready yet.");
		}
		}

		private void ShowRewardBasedVideo()
		{
		if (rewardBasedVideo.IsLoaded())
		{
		rewardBasedVideo.Show();
		} else
		{
		print("Reward based video ad is not ready yet.");
		}
		}

		#region Banner callback handlers

		public void HandleAdLoaded(object sender, EventArgs args)
		{
		print("HandleAdLoaded event received.");
		}

		public void HandleAdFailedToLoad(object sender, AdFailedToLoadEventArgs args)
		{
		print("HandleFailedToReceiveAd event received with message: " + args.Message);
		}

		public void HandleAdOpened(object sender, EventArgs args)
		{
		print("HandleAdOpened event received");
		}

		void HandleAdClosing(object sender, EventArgs args)
		{
		print("HandleAdClosing event received");
		}

		public void HandleAdClosed(object sender, EventArgs args)
		{
		print("HandleAdClosed event received");
		}

		public void HandleAdLeftApplication(object sender, EventArgs args)
		{
		print("HandleAdLeftApplication event received");
		}

		#endregion

		#region Interstitial callback handlers

		public void HandleInterstitialLoaded(object sender, EventArgs args)
		{
		print("HandleInterstitialLoaded event received.");
		}

		public void HandleInterstitialFailedToLoad(object sender, AdFailedToLoadEventArgs args)
		{
		print("HandleInterstitialFailedToLoad event received with message: " + args.Message);
		}

		public void HandleInterstitialOpened(object sender, EventArgs args)
		{
		print("HandleInterstitialOpened event received");
		}

		void HandleInterstitialClosing(object sender, EventArgs args)
		{
		print("HandleInterstitialClosing event received");
		}

		public void HandleInterstitialClosed(object sender, EventArgs args)
		{
		print("HandleInterstitialClosed event received");
		}

		public void HandleInterstitialLeftApplication(object sender, EventArgs args)
		{
		print("HandleInterstitialLeftApplication event received");
		}

		#endregion

		#region RewardBasedVideo callback handlers

		public void HandleRewardBasedVideoLoaded(object sender, EventArgs args)
		{
		print("HandleRewardBasedVideoLoaded event received.");
		text.text = "Successfully Loaded Video";
		}

		public void HandleRewardBasedVideoFailedToLoad(object sender, AdFailedToLoadEventArgs args)
		{
		print("HandleRewardBasedVideoFailedToLoad event received with message: " + args.Message);
		text.text = "failed to Load Video";
		}

		public void HandleRewardBasedVideoOpened(object sender, EventArgs args)
		{
		print("HandleRewardBasedVideoOpened event received");
		}

		public void HandleRewardBasedVideoStarted(object sender, EventArgs args)
		{
		print("HandleRewardBasedVideoStarted event received");
		}

		public void HandleRewardBasedVideoClosed(object sender, EventArgs args)
		{
		print("HandleRewardBasedVideoClosed event received");
		}

		public void HandleRewardBasedVideoRewarded(object sender, Reward args)
		{
		string type = args.Type;
		double amount = args.Amount;
		print("HandleRewardBasedVideoRewarded event received for " + amount.ToString() + " " +
		type);
		}

		public void HandleRewardBasedVideoLeftApplication(object sender, EventArgs args)
		{
		print("HandleRewardBasedVideoLeftApplication event received");
		}

		#endregion
		}

**Comment by rampara** [comment]
The plugin will not work without Google Play services. You will have to add the plugin to your project by selecting `Assets -> Play Services Resolver -> Android Resolver -> Resolve Client Jars`. You should see the required Google Play services dependencies added to the `Assets/Plugins/Android` directory of your Unity project. If you're still experiencing crashes after adding the Play Services to your project, please provide a stack trace from logcat of the crash.

**Comment by aamiryatoo** [comment]
where can i get google play services plugin compatible with this version?

**Comment by rampara** [comment]
You don't need a separate plugin, corrected the first sentence in my previous post.

**Comment by aamiryatoo** [comment]
Thanks
My App doesn't crash now.
but i am not able to display the ads either.
should i need to edit Android Manifest?

**Comment by aamiryatoo** [comment]
This is the log cat if it helps my case.
[mylogcatfile.txt](https://github.com/googleads/googleads-mobile-unity/files/887391/mylogcatfile.txt)

**Comment by aamiryatoo** [comment]
I recieve these errors when i click on load banner or request banner buttons.
[errors.txt](https://github.com/googleads/googleads-mobile-unity/files/887401/errors.txt)

**Comment by aamiryatoo** [comment]
I solved this issue myself
But i m not able to load the rewarded video ads.
Please help me with that

**Comment by aamiryatoo** [comment]
I m getting the following log when i request reward video

W/dalvikvm( 2457): VFY: unable to resolve virtual method 1979: Landroid/os/PowerManager;.isPowerSaveMode ()Z
D/dalvikvm( 2457): VFY: replacing opcode 0x6e at 0x000b
D/dalvikvm( 2457): Trying to load lib /data/app-lib/com.whatsapp-1/libvlc.so 0x42549118
D/dalvikvm( 2457): Added shared lib /data/app-lib/com.whatsapp-1/libvlc.so 0x42549118
D/dalvikvm( 2457): No JNI_OnLoad found in /data/app-lib/com.whatsapp-1/libvlc.so 0x42549118, skipping init
D/dalvikvm( 2457): Trying to load lib /data/app-lib/com.whatsapp-1/libresample.so 0x42549118
D/dalvikvm( 2457): Added shared lib /data/app-lib/com.whatsapp-1/libresample.so 0x42549118
D/dalvikvm( 2457): No JNI_OnLoad found in /data/app-lib/com.whatsapp-1/libresample.so 0x42549118, skipping init
D/dalvikvm( 2457): Trying to load lib /data/app-lib/com.whatsapp-1/libwhatsapp.so 0x42549118
D/dalvikvm( 2457): Added shared lib /data/app-lib/com.whatsapp-1/libwhatsapp.so 0x42549118
D/dalvikvm( 2457): Trying to load lib /data/app-lib/com.whatsapp-1/libcurve25519.so 0x42549118
D/dalvikvm( 2457): Added shared lib /data/app-lib/com.whatsapp-1/libcurve25519.so 0x42549118
D/dalvikvm( 2457): No JNI_OnLoad found in /data/app-lib/com.whatsapp-1/libcurve25519.so 0x42549118, skipping init
I/dalvikvm( 2457): Could not find method android.support.v7.widget.Toolbar.setElevation, referenced from method com.whatsapp.mx.setContentView
W/dalvikvm( 2457): VFY: unable to resolve virtual method 8374: Landroid/support/v7/widget/Toolbar;.setElevation (F)V
D/dalvikvm( 2457): VFY: replacing opcode 0x6e at 0x0029
I/dalvikvm( 2457): Could not find method android.support.v7.widget.Toolbar.setElevation, referenced from method com.whatsapp.mr.P
W/dalvikvm( 2457): VFY: unable to resolve virtual method 8374: Landroid/support/v7/widget/Toolbar;.setElevation (F)V
D/dalvikvm( 2457): VFY: replacing opcode 0x6e at 0x0052
W/dalvikvm( 2457): Unable to resolve superclass of Landroid/support/v4/app/b$b; (83)
W/dalvikvm( 2457): Link of class 'Landroid/support/v4/app/b$b;' failed
E/dalvikvm( 2457): Could not find class 'android.support.v4.app.b$b', referenced from method android.support.v4.app.k.a
W/dalvikvm( 2457): VFY: unable to resolve new-instance 625 (Landroid/support/v4/app/b$b;) in Landroid/support/v4/app/k;
D/dalvikvm( 2457): VFY: replacing opcode 0x22 at 0x000b
I/dalvikvm( 2457): Could not find method android.app.Activity.postponeEnterTransition, referenced from method android.support.v4.app.k.a_
W/dalvikvm( 2457): VFY: unable to resolve virtual method 231: Landroid/app/Activity;.postponeEnterTransition ()V
D/dalvikvm( 2457): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm( 2457): Could not find method android.app.Activity.startPostponedEnterTransition, referenced from method android.support.v4.app.k.f_
W/dalvikvm( 2457): VFY: unable to resolve virtual method 246: Landroid/app/Activity;.startPostponedEnterTransition ()V
D/dalvikvm( 2457): VFY: replacing opcode 0x6e at 0x0006
W/dalvikvm( 2457): Unable to resolve superclass of Landroid/support/v4/app/b$b; (83)
W/dalvikvm( 2457): Link of class 'Landroid/support/v4/app/b$b;' failed
D/dalvikvm( 2457): DexOpt: unable to opt direct call 0x0cdd at 0x0d in Landroid/support/v4/app/k;.a
I/dalvikvm( 2457): Could not find method android.app.AlarmManager.setExactAndAllowWhileIdle, referenced from method com.whatsapp.AlarmService.b
W/dalvikvm( 2457): VFY: unable to resolve virtual method 263: Landroid/app/AlarmManager;.setExactAndAllowWhileIdle (IJLandroid/app/PendingIntent;)V
D/dalvikvm( 2457): VFY: replacing opcode 0x6e at 0x0062
I/dalvikvm( 2457): Could not find method android.app.AlarmManager.setExactAndAllowWhileIdle, referenced from method com.whatsapp.AlarmService.c
W/dalvikvm( 2457): VFY: unable to resolve virtual method 263: Landroid/app/AlarmManager;.setExactAndAllowWhileIdle (IJLandroid/app/PendingIntent;)V
D/dalvikvm( 2457): VFY: replacing opcode 0x6e at 0x005b
I/dalvikvm( 2457): Could not find method android.app.AlarmManager.setExactAndAllowWhileIdle, referenced from method com.whatsapp.AlarmService.d
W/dalvikvm( 2457): VFY: unable to resolve virtual method 263: Landroid/app/AlarmManager;.setExactAndAllowWhileIdle (IJLandroid/app/PendingIntent;)V
D/dalvikvm( 2457): VFY: replacing opcode 0x6e at 0x00fa
I/dalvikvm( 2457): Could not find method android.app.AlarmManager.setExactAndAllowWhileIdle, referenced from method com.whatsapp.AlarmService.e
W/dalvikvm( 2457): VFY: unable to resolve virtual method 263: Landroid/app/AlarmManager;.setExactAndAllowWhileIdle (IJLandroid/app/PendingIntent;)V
D/dalvikvm( 2457): VFY: replacing opcode 0x6e at 0x00a3
I/dalvikvm( 2457): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.e.a
W/dalvikvm( 2457): VFY: unable to resolve virtual method 732: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
D/dalvikvm( 2457): VFY: replacing opcode 0x6e at 0x000d
I/dalvikvm( 2457): Could not find method android.app.AlarmManager.setExactAndAllowWhileIdle, referenced from method com.whatsapp.messaging.c.d
W/dalvikvm( 2457): VFY: unable to resolve virtual method 263: Landroid/app/AlarmManager;.setExactAndAllowWhileIdle (IJLandroid/app/PendingIntent;)V
D/dalvikvm( 2457): VFY: replacing opcode 0x6e at 0x0051
I/dalvikvm( 2457): Could not find method android.app.AlarmManager.setExactAndAllowWhileIdle, referenced from method com.whatsapp.aox.a
W/dalvikvm( 2457): VFY: unable to resolve virtual method 263: Landroid/app/AlarmManager;.setExactAndAllowWhileIdle (IJLandroid/app/PendingIntent;)V
D/dalvikvm( 2457): VFY: replacing opcode 0x6e at 0x0066
D/dalvikvm( 2457): Trying to load lib /data/app-lib/com.whatsapp-1/libcurve25519.so 0x42549118
D/dalvikvm( 2457): Shared lib '/data/app-lib/com.whatsapp-1/libcurve25519.so' already loaded in same CL 0x42549118
I/dalvikvm( 2457): Total arena pages for JIT: 11
I/dalvikvm( 2457): Total arena pages for JIT: 12
I/dalvikvm( 2457): Total arena pages for JIT: 13
I/dalvikvm( 2457): Total arena pages for JIT: 14
I/dalvikvm( 2457): Total arena pages for JIT: 15
I/dalvikvm( 2457): Total arena pages for JIT: 16
I/dalvikvm( 2457): Total arena pages for JIT: 17
I/dalvikvm( 2457): Total arena pages for JIT: 18
I/dalvikvm( 2457): Total arena pages for JIT: 19
I/dalvikvm( 2371): Could not find method android.security.NetworkSecurityPolicy.getInstance, referenced from method com.google.android.gms.ads.internal.state.f.a
W/dalvikvm( 2371): VFY: unable to resolve static method 2821: Landroid/security/NetworkSecurityPolicy;.getInstance ()Landroid/security/NetworkSecurityPolicy;
D/dalvikvm( 2371): VFY: replacing opcode 0x71 at 0x00d5
I/dalvikvm( 2296): Total arena pages for JIT: 11
I/dalvikvm( 2296): Total arena pages for JIT: 12
I/dalvikvm( 2296): Total arena pages for JIT: 13
I/dalvikvm( 2296): Total arena pages for JIT: 14
D/dalvikvm( 2371): Trying to load lib /data/app-lib/com.google.android.gms-2/libleveldbjni.so 0x42555020
D/dalvikvm( 2371): Added shared lib /data/app-lib/com.google.android.gms-2/libleveldbjni.so 0x42555020
I/dalvikvm( 2259): Could not find method android.accounts.AccountManager.removeAccount, referenced from method dwq.a
W/dalvikvm( 2259): VFY: unable to resolve virtual method 649: Landroid/accounts/AccountManager;.removeAccount (Landroid/accounts/Account;Landroid/app/Activity;Landroid/accounts/AccountManagerCallback;Landroid/os/Handler;)Landroid/accounts/AccountManagerFuture;
D/dalvikvm( 2259): VFY: replacing opcode 0x6e at 0x0047
I/dalvikvm( 2259): Could not find method android.app.admin.DevicePolicyManager.getProfileOwner, referenced from method fdg.a
W/dalvikvm( 2259): VFY: unable to resolve virtual method 884: Landroid/app/admin/DevicePolicyManager;.getProfileOwner ()Landroid/content/ComponentName;
D/dalvikvm( 2259): VFY: replacing opcode 0x6e at 0x0012
I/dalvikvm( 2259): Could not find method android.app.admin.DevicePolicyManager.isProfileOwnerApp, referenced from method fdg.a
W/dalvikvm( 2259): VFY: unable to resolve virtual method 887: Landroid/app/admin/DevicePolicyManager;.isProfileOwnerApp (Ljava/lang/String;)Z
D/dalvikvm( 2259): VFY: replacing opcode 0x6e at 0x0011
I/dalvikvm( 2259): Could not find method android.content.ContextWrapper.createCredentialProtectedStorageContext, referenced from method hko.createCredentialProtectedStorageContext
W/dalvikvm( 2259): VFY: unable to resolve virtual method 2050: Landroid/content/ContextWrapper;.createCredentialProtectedStorageContext ()Landroid/content/Context;
D/dalvikvm( 2259): VFY: replacing opcode 0x6f at 0x0002
I/dalvikvm( 2259): Could not find method android.content.ContextWrapper.createDeviceProtectedStorageContext, referenced from method hko.createDeviceProtectedStorageContext
W/dalvikvm( 2259): VFY: unable to resolve virtual method 2051: Landroid/content/ContextWrapper;.createDeviceProtectedStorageContext ()Landroid/content/Context;
D/dalvikvm( 2259): VFY: replacing opcode 0x6f at 0x0002
D/dalvikvm( 2259): DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_64_BIT_ABIS
W/dalvikvm( 2259): VFY: unable to resolve static field 921 (SUPPORTED_64_BIT_ABIS) in Landroid/os/Build;
D/dalvikvm( 2259): VFY: replacing opcode 0x62 at 0x0012
D/dalvikvm( 2259): DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_32_BIT_ABIS
W/dalvikvm( 2259): VFY: unable to resolve static field 920 (SUPPORTED_32_BIT_ABIS) in Landroid/os/Build;
D/dalvikvm( 2259): VFY: replacing opcode 0x62 at 0x0021
D/dalvikvm( 2259): DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_ABIS
W/dalvikvm( 2259): VFY: unable to resolve static field 922 (SUPPORTED_ABIS) in Landroid/os/Build;
D/dalvikvm( 2259): VFY: replacing opcode 0x62 at 0x0008
D/dalvikvm( 2259): DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_64_BIT_ABIS
W/dalvikvm( 2259): VFY: unable to resolve static field 921 (SUPPORTED_64_BIT_ABIS) in Landroid/os/Build;
D/dalvikvm( 2259): VFY: replacing opcode 0x62 at 0x0008
D/dalvikvm( 2259): DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_64_BIT_ABIS
I/dalvikvm( 2259): DexOpt: unable to optimize static field ref 0x0399 at 0x17 in Lbxl;.a
D/dalvikvm( 2259): DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_32_BIT_ABIS
I/dalvikvm( 2259): DexOpt: unable to optimize static field ref 0x0398 at 0x26 in Lbxl;.a
D/dalvikvm( 2259): DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_64_BIT_ABIS
I/dalvikvm( 2259): DexOpt: unable to optimize static field ref 0x0399 at 0x0d in Lbxl;.b
I/dalvikvm( 2371): Total arena pages for JIT: 11
I/dalvikvm( 2371): Total arena pages for JIT: 12
I/dalvikvm( 2371): Total arena pages for JIT: 13
I/dalvikvm( 2371): Total arena pages for JIT: 14
I/dalvikvm( 2371): Could not find method android.telephony.CellIdentityLte.getEarfcn, referenced from method qjv.a
W/dalvikvm( 2371): VFY: unable to resolve virtual method 2391: Landroid/telephony/CellIdentityLte;.getEarfcn ()I
D/dalvikvm( 2371): VFY: replacing opcode 0x6e at 0x0031
D/dalvikvm( 2371): GC_EXPLICIT freed 2673K, 28% free 16304K/22576K, paused 2ms+12ms, total 59ms
D/dalvikvm( 2259): GC_EXPLICIT freed 2888K, 26% free 16908K/22576K, paused 5ms+12ms, total 72ms
I/dalvikvm( 2371): Could not find method android.webkit.WebSettings.setMixedContentMode, referenced from method com.google.android.gms.ads.internal.webview.o.<init>
W/dalvikvm( 2371): VFY: unable to resolve virtual method 3220: Landroid/webkit/WebSettings;.setMixedContentMode (I)V
D/dalvikvm( 2371): VFY: replacing opcode 0x6e at 0x0058
D/dalvikvm( 2371): GetMethodID: not returning static method Landroid/os/Process;.getTotalMemory ()J
D/dalvikvm( 2371): GetMethodID: not returning static method Landroid/os/Process;.getFreeMemory ()J
I/dalvikvm( 2371): Could not find method android.os.PowerManager.isInteractive, referenced from method jou.a
W/dalvikvm( 2371): VFY: unable to resolve virtual method 2754: Landroid/os/PowerManager;.isInteractive ()Z
D/dalvikvm( 2371): VFY: replacing opcode 0x6e at 0x0006
I/Unity   ( 2296): HandleRewardBasedVideoFailedToLoad event received with message: No fill
I/Unity   ( 2296):
I/Unity   ( 2296): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
I/Unity   ( 2296):
I/ActivityManager(  930): Start proc com.qualcomm.display for service com.qualcomm.cabl/.CABLService: pid=2624 uid=1000 gids={41000, 3002, 3001, 3003, 1028, 1015, 3006, 3007, 1007, 1021, 3004, 3005, 1000, 3009, 1023, 1010, 2001, 1035}
I/ActivityManager(  930): Waited long enough for: ServiceRecord{43837760 u0 com.whatsapp/.messaging.MessageService}
I/Unity   ( 2296): Reward based video ad is not ready yet.
I/Unity   ( 2296):
I/Unity   ( 2296): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
I/Unity   ( 2296):

**Comment by rampara** [comment]
Closing this issue as the original problem seems to have resolved. Discussion on your second problem can be continued at  #391.
