### ISSUE TITLE
Problem with NativeAds in 3.3.0

### ISSUE THREAD

**Issue by fzdravko** [googleads/googleads-mobile-unity#387]
When I hide native ad, touch is not responding in the place where ad was. This is happening on android 6.0, on previous versions of android everything working ok.

**Comment by rampara** [comment]
@fzdravko this has been fixed in f0efba71db9adc9bca18d2964bf20e629964ff53. You can build from head to get a version of this plugin that no longer has this issue.

**Comment by pijushmandal** [comment]
I have the similar issue when the internet is not working the banner ad area doesn't register the touch. @rampara  you have provided some info but can you please elaborate to fix the issue as I'm not an expert. Thanks!

**Comment by rampara** [comment]
@pijushmandal are you using the latest version of this plugin?
