### ISSUE TITLE
AdMob Rewarded video not pausing the game 

### ISSUE THREAD

**Issue by psavi** [googleads/googleads-mobile-unity#388]
When admob rewarded video runs on iOS, the game not stops. I've tried different things like try other versions and didn't work... At Android it not happen, is working fine...

**Comment by rampara** [comment]
@psavi can you link me to a Unity project that reproduces this issue?

**Comment by psavi** [comment]
@rampara I've got the solution! I had to write some lines with "UnityPause(true)" on GADURewardBased VideoAd.m file.

**Comment by ArmandCloud** [comment]
3.6.1 same here ios build.

On android , when i press close button, it gives reward. expected behaviour.
On ios , it rewards after video finish. not expected.
Also its not pausing game when showing some interactable full screen interstitials.

Best Regards,

**Comment by ArmandCloud** [comment]
3.6.3 same.
Simple work around is pause game OnVideoRewarded , and resume in OnVideoClosed

Best Regards,

**Comment by rampara** [comment]
As @ArmandCloud mentioned, the recommended approach is to use ad events to pause and resume games.

**Comment by sjvc** [comment]
@rampara using ad events to pause and resume it's a workaround. But, shouldn't it be fixed in this plugin? Shouldn't work on iOS the same way it does on Android?

**Comment by rampara** [comment]
In the latest version of the plugin (v3.11.0), there is a new API `MobileAds. SetiOSAppPauseOnBackground()`, which when set will cause iOS apps to pause when displaying a full screen ad.

**Comment by lucianocheng** [comment]
Note: This is now `GoogleMobileAds.Api.MobileAds.SetiOSAppPauseOnBackground(...)` for Unity.
