### ISSUE TITLE
native express view ad is hiding but still blocking input in game

### ISSUE THREAD

**Issue by aditya2** [googleads/googleads-mobile-unity#389]
in my game's homescreen i m loading native ad which working fine but when i go to another screen i m hiding this native ad but even in its hidden state this ad is blocking all inputs like for eg if i have a button in place of this ad that button is not working when native ad is loaded but hidden but that button is working all fine when i m not loading this ad for eg if i m playing my app with no internet connection .... one more thin i want to ask is that the reward ads are crashing my app always and my app is crashing without any error in logcat

**Comment by rampara** [comment]
@aditya2 this has been fixed in f0efba7. You can build from head to get a version of this plugin that no longer has this issue. There will also be a new release on Monday that includes this fix.
