### ISSUE TITLE
Cannot build due to wrong entry in gradle-wrapper.properties

### ISSUE THREAD

**Issue by bence98** [googleads/googleads-mobile-unity#393]
I got this message when I ran Gradlew:
https://pastebin.com/PxXYapJU
Updating the gradle-wrapper.properties accordingly fixed the issue.

**Comment by rampara** [comment]
Thanks for bringing this to our attention. Will be pushing a fix shortly to address this.

**Comment by rampara** [comment]
Fixed in 3265a57b0406e74b244eeea8fbccdb7e4a2a47d9.
