### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by iamrajajamal** [googleads/googleads-mobile-unity#394]
When I'm trying to build my project this error start appearing
Assets/Scripts/AdsController/GoogleMobileAdsDemoScript.cs(215,7): error CS1525: Unexpected symbol `this'.

[GoogleMobileAdsDemoScript.txt](https://github.com/googleads/googleads-mobile-unity/files/900967/GoogleMobileAdsDemoScript.txt)

**Comment by rampara** [comment]
You seem to have a missing semi-colon at line 207.

**Comment by iamrajajamal** [comment]
Awwww. So Annoying. Silly mistakes
