### ISSUE TITLE
RewardBasedAd can not appear, advertising requests are very many but not get ads.hoping to get help！

### ISSUE THREAD

**Issue by MFGAME** [googleads/googleads-mobile-unity#395]
RewardBasedAd can not appear, advertising requests are very many but not get ads.hoping to get help！

**Comment by rampara** [comment]
@MFGAME are you experiencing this issue on Android or iOS? Do you receive the `OnAdFailedToLoad` ad event? If so, which error code is presented in this event?

**Comment by rampara** [comment]
Closing this issue due to non-response. Please re-open if this issue persists for you.
