### ISSUE TITLE
When I try to comment or edit my previous issue i get error: You can't comment at this time.

### ISSUE THREAD

**Issue by icyh4mmer** [googleads/googleads-mobile-unity#397]
Am I missing something

**Comment by rampara** [comment]
In the past people have run into similar issues when using an ad blocker on the GitHub web site. Can you try disabling your ad blocker if you're using one?

**Comment by icyh4mmer** [comment]
Thank you, I didn't even think of this possibility.

**Comment by knagode** [comment]
THis is still an issue .. Ad blocker is not the reason :(

**Comment by ttunstall07** [comment]
This also happens to me occasionally when trying to comment. A workaround that seems to work is logging out of and logging back into my account.

**Comment by zixuan75** [comment]
ad blocker is not the reason

**Comment by jfranklin9000** [comment]
I encountered this and simply waited 5 minutes and tried again with success.

**Comment by henryhe1** [comment]
adblocker was an issue for me to react to comments. Turned it off and was able to react to above post haha

**Comment by LeonAppDev** [comment]
The same issue happens to me, no ad blocker

**Comment by avinash018** [comment]
I tried disabling the adblocker its working for me.

**Comment by avinash018** [comment]
@zixuan75 Try logout and login back after clearing cookies and cache. Then try it.

**Comment by JarreyZhou** [comment]
The same problem.

**Comment by kjeldflarup** [comment]
I also was it 4 days ago. But I wasn't able to comment here. Actually not event log properly into github. I guess something was broken @ github that day.

**Comment by ArminJo** [comment]
I had it too,
Waiting and using another browser (with saves me clearing cookies and cache) worked.
What a nasty problem!

**Comment by Alex-lowe** [comment]
Testing my ability to comment, because I'm running into the same error here.

My current theory is that our company's proxy blocking the gist.github.com URL.

**Comment by galishmann** [comment]
It can be related with current incendents on GitHub server: https://www.githubstatus.com/

**Comment by Sandhyakripalani** [comment]
Turning off adBlocker did the magic for me.

**Comment by ArminJo** [comment]
After disabling the uBlock origin adblocker I was able to comment and to update a comment.

**Comment by dinalo45** [comment]
For me the problem was that i was logged in different machines and after a logged out i could comment and open/close issues.

**Comment by maks-rafalko** [comment]
happens to me today from time to time. Adblocker is not the reason

**Comment by SANJAY072000** [comment]
Check internet connection. For me that was the reason.

**Comment by OBVYamaska** [comment]
Just letting you know that I still experience this today, even after disabling my AdBlock
