### ISSUE TITLE
Interstitial Ad not reflecting Admob Settings

### ISSUE THREAD

**Issue by skaraman** [googleads/googleads-mobile-unity#398]
I've added a cap to my Interstitial at no more than 1 per 5 minutes and also only of the Video type. However, on the app I'm still getting an Interstitial every time I call for it, and it's an Image type.

**Comment by rampara** [comment]
@skaraman this issue tracker is strictly for issues related to the Google Mobile Ads Unity plugin. For other mobile ads issues, I would recommend you reach out on the [Google Mobile Ads SDK Technical Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
