### ISSUE TITLE
Banner ad clipped (re-open #326)

### ISSUE THREAD

**Issue by spixy** [googleads/googleads-mobile-unity#399]
Hi, I want to re-open issue #326.
I have updated plugin to newest version 3.4.0 and still have this problem sometimes (I just changed size to full width)

![screenshot_6](https://cloud.githubusercontent.com/assets/4542110/25062619/ba8be784-21cf-11e7-817a-bce4df114c8f.png)
Unity 5.6.0, android build, its Samsung Galaxy S6
Do you still need a Charles log?

**Comment by rampara** [comment]
Yes, a Charles log would help a lot with getting to the bottom of what's causing this issue.

**Comment by rampara** [comment]
Closing this issue due to non-response. If this issue persists for you, please re-open it.
