### ISSUE TITLE
Project GPM data does not exist. Creating new object

### ISSUE THREAD

**Issue by anil4040** [googleads/googleads-mobile-unity#400]
Hi, Using Google Play Services v 0.9.37 Unity 5.5 I already tried to google it but didn't get any anything related to it. Problem is Google play services plugin not working properly even not showing any error except this in console

"Project GPM data does not exist. Creating new object. UnityEngine.Debug:Log(Object) Google.PackageManager.LoggingController:Log(String) Google.PackageManager.ProjectManagerController:InflateProjectRecord(String) Google.PackageManager.ProjectManagerController:.cctor() UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes() "

thanks in Advance. Really need help :)

**Comment by rampara** [comment]
@anil4040 Are you referring to the [Google Play Games Unity plugin](https://github.com/playgameservices/play-games-plugin-for-unity)? The latest version for this plugin is 3.4.0.

**Comment by anil4040** [comment]
I am using latest one 
https://github.com/playgameservices/play-games-plugin-for-unity/tree/master/current-build

I tried these solutions:
[video](https://www.youtube.com/watch?v=5Ae8GeRmdH0)
[one](https://groups.google.com/forum/#!topic/google-admob-ads-sdk/LVASxE9mmqY)
[two](https://github.com/googleads/googleads-mobile-unity/issues/376)

still it's not working...I tried to re-import plugin and tried to use it in a new project.

**Comment by anil4040** [comment]
showing same error in sample projects...any help..please ??

**Comment by rampara** [comment]
@anil4040 if you're having issues this the Google Play Games plugin you should open an issue on the issue tracker associated with that repo. This issue tracker is strictly for issues related to the Google Mobile Ads Unity plugin.
