### ISSUE TITLE
OnAdRewarded and OnRewardVideoClosed handlers not called

### ISSUE THREAD

**Issue by YouHusam** [googleads/googleads-mobile-unity#402]
Rewarded videos hosted by the new google do not call the `OnAdRewarded` and `OnRewardVideoClosed` event handlers when closing the ad after the video is done playing. I've been having this issue for a month now and can't figure out a solution. There's nothing in the logs when the ad is closed I'm running on the latest release (v3.4.0)

This issue is only occurring for Ads by Google videos, I have no issue with UnityAds on both iOS and Android and the devices are not set as test devices

**Comment by rampara** [comment]
@YouHusam is this issue consistently reproducible for you. Are you experiencing this issue when deploying to Android or iOS? Are you receiving mediated ads from third party ad networks or is this issue present for AdMob rewarded video ads?

**Comment by YouHusam** [comment]
@rampara yes, almost all AdMob ads don't fire the event handlers mentioned above, I noticed today that 1% of the times it randomly works, but most of the time it doesn't. I'm receiving mediated ads from UnityAds and they are working properly. This issue is happening on both Android and iOS.

I'm using Unity 5.5.0f3

**Comment by rampara** [comment]
Can't seem to reproduce this issue on my end. Are you running into the same issue with the [sample app](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) from this repo?

**Comment by YouHusam** [comment]
It seems to be working properly, I'll check my app for possible conflicting libraries. Thanks for the help

**Comment by YouHusam** [comment]
I managed to fix the problem, turns out I was using the same ad request every time. solved by creating a new ad request when the video is closed.
