### ISSUE TITLE
Video Ads seems set to landscape and show part of the game.

### ISSUE THREAD

**Issue by kenglou** [googleads/googleads-mobile-unity#403]
Hi,

Recently i started found that for the latest version, i had some video ads that shown as below:

![screenshot_2017-04-19-15-36-21](https://cloud.githubusercontent.com/assets/4876665/25169638/4ba3aa5c-251a-11e7-987a-f5861403ea07.png)

Want to see if anyone had this problem?
The game supposed to be portrait mode only, I mind when the video ads in are not only landscape, but also didn't finish cover the game. 
I'm using Unity3d 5.6.0f3 and Google Mobile Ads Unity Plugin 3.4.0.

Thank you.

**Comment by ShakedJuran** [comment]
I am having the exact same issue

**Comment by rampara** [comment]
Is this issue consistently reproducible across various devices? Would you be able to capture a Charles log for an ad request that results in this issue?

**Comment by kenglou** [comment]
This issue i tried in 2 devices and yes it is reproducible. At first the ads functional properly, after few times of watching ads the problem occurs. Happens on Android only.

**Comment by rampara** [comment]
@kenglou a wireshark log would be great.

**Comment by ShakedJuran** [comment]
It happens to me when the game is set to portrait mode only.
If it is set to landscape its ok, but if its both then if it was in portrait it will happen again.

**Comment by rampara** [comment]
@ShakedJuran can you provide the device and iOS version you used to reproduce this issue? A Charles or wireshark log would help too.

**Comment by ShakedJuran** [comment]
@rampara Issue is solved in v3.5.0, thank you very much!

**Comment by rampara** [comment]
hmmm, strange, there weren't any changes made to address this issue specifically. Please report back if you see the issue come up again.

**Comment by rampara** [comment]
Closing as it seems to have been resolved. If this issue persists for you, please re-open it.
