### ISSUE TITLE
Banner ads disapear after video or after "moveTaskToBack"

### ISSUE THREAD

**Issue by ShakedJuran** [googleads/googleads-mobile-unity#404]
On a Huawei CHC, I am creating a bottom banner (although same issue happens with other positions), and after watching an interstitial or a reward ad, or after calling com.unity3d.player.UnityPlayer "moveTaskToBack" and going back to the app, the bottom banner disappears (sometimes it comes back, sometimes it doesn't). no error, no nothing...

Please help

**Comment by rampara** [comment]
Could you break down the steps to reproduce this issue? I tried the following and the banner ad consistently remained on-screen.

1. Request and display banner ad.
2. Request and display interstitial ad.
3. Dismiss interstitial ad.
[banner remains on screen]
2. Request and display rewarded video ad.
3. Dismiss rewarded video ad ad.
[banner remains on screen]

**Comment by ShakedJuran** [comment]
Using those exact steps on my phone results by 3. the banner disappears.
Did you try on a Huawei CHC-U01?

**Comment by mostdeep123** [comment]
is a phone brand depends on the Ad View ? i try some API for using AdMob and never find this issues, but maybe some bad request , if i debug on Android Studio so the banner will show on another scene after the banner request, you know why this is happen ? it will be helpful.. thanks

**Comment by rampara** [comment]
@ShakedJuran I don't have access to that particular device, but am unable to reproduce the issue on a variety of other devices. Are you experiencing this issue on any other devices?

**Comment by rampara** [comment]
@mostdeep123 I'm not sure I understand the issue you're experiencing. Can you breakdown what the issue is and the steps to reproduce it?

**Comment by ShakedJuran** [comment]
same as #408 

I launch my app with a banner ad at the bottom.
Then i show an interstitial, when i close the interstitial, the banner disappears but still clickable.
I dont really have anything special for you to reproduce it, it seems to happen only on my Huawei CHC-U01, on my Samsung g s5 it doesn't happen.

**Comment by mostdeep123** [comment]
after i try to request the banner on the scene, in the current scene the banner doesn't view (it will happen when i requested any other ad like reward video ad or intertitial) and will be show after the next scene , why this is happen ? i already debug on android studio and it seems like a bad request happen on banner ad request..

**Comment by rampara** [comment]
For those of you running into this issue on Samsung devices, are you using the latest version of this plugin (v3.4.0)?

**Comment by rampara** [comment]
@ShakedJuran @mostdeep123 can you try testing with the latest version of the plugin (v3.5.0) to see if this issue is still present for you. I included a fix that should address this specific issue.

**Comment by strangestraw** [comment]
This issue had been appeared in LG G4 and Samsung Galaxy Note 5 / Unity 5.6.0p1 / GoogleAdsMobile(v3.4.0). But it works perfectly in the latest version of the plugin (v3.5.0).
Thank you for your great work!

**Comment by ShakedJuran** [comment]
@rampara Issue is solved in v3.5.0, thank you very much!

**Comment by rampara** [comment]
Glad the issue has been resolved.
