### ISSUE TITLE
Banner ad is wrong position on Android (Galaxy S6)

### ISSUE THREAD

**Issue by Youngchangoon** [googleads/googleads-mobile-unity#405]
Error Version : 3.4.0
Unity Version : 5.5.1

Banner ad is wrong position on Android (Galaxy S6).

I tried set position (0,0).
~~~
bannerView = new BannerView(andADInfo.bannerID, AdSize.SmartBanner, 0, 0);
~~~
but, Banner is wrong position.

---
+ I checked ios, ipad and some android device.
+ I think reason is "dpi".

**Comment by rampara** [comment]
@Youngchangoon this plugin uses a similar coordinate system to those in standard iOS and Android development where (0,0) is the top left of the screen. Is this not the behavior you're experiencing?

**Comment by rampara** [comment]
Closing this issue due to non-response. If this issue persists for you, please re-open it.
