### ISSUE TITLE
is_designed_for_families - how to address?

### ISSUE THREAD

**Issue by Piotr12** [googleads/googleads-mobile-unity#407]
Hi, 

This is a support question I believe. According to [this policy](https://support.google.com/admob/answer/6223431?hl=en#implement-kfa) I should be using:

`extras.putBoolean("is_designed_for_families", true); `

for "Designed for Families" program. Is 
```
AdRequest request = new AdRequest.Builder ()
	.TagForChildDirectedTreatment (true)
	.AddExtra ("is_designed_for_families", "true")
	.Build ();
```
the right way to address it in C# in Unity (and "true" will become true somewhere on its way) or I should follow the path defined [here](http://answers.unity3d.com/questions/1151324/using-admob-with-the-designed-for-families-program.html) and modify Utils.cs to properly putBoolean?

**Comment by rampara** [comment]
@Piotr12 the code snippet you posted is the correct way to request an ad that complies with the Designed for Families program.
