### ISSUE TITLE
banner is hidden after interstitial ads show off

### ISSUE THREAD

**Issue by nmtoan91** [googleads/googleads-mobile-unity#408]
The banner ads is working fine until the interstitial ads  show up and close.

**Comment by rampara** [comment]
@nmtoan91 can you explain the issue you're experiencing in greater detail. Is this issue on Android, iOS or both? Can you provide steps to reproduce the issue?

**Comment by strangestraw** [comment]
In Unity 5.5.0, it is worked well.
This situation is appeared in Unity 5.6(mine is 5.6.0p1) and devices are LG G4(LG-F400s, Android 4.4.2) & Samsung Galaxy Note 5.
Ad banner is shown when app is launched, but it is disappeared after showing and closing interstitial ad.
Banner is invisible but clickable.

**Comment by Jazzgazer** [comment]
I have same problem. 

I'm using Unity 5.6.0p3
Devices are Samsung Galaxy 7 & Note 3. 

At first, banner view i shown well.
however, when I go back home or play unity ads or do something, it's invisible but clickable.

**Comment by JillionStudio** [comment]
facing same issue
i am also using 5.6
Huawei

**Comment by rampara** [comment]
closing as duplicate of #404
