### ISSUE TITLE
MissingMethodException: Method not found: 'GooglePlayServices.UnityCompat.get_ApplicationId'.

### ISSUE THREAD

**Issue by Thornus** [googleads/googleads-mobile-unity#409]
Hi guys, I downloaded and imported the plugin into my Unity 5.6.0 project and I get an exception that continuously appears (if you have collapse set to on in Unity console you'll see the number increase rapidly). This is the exception text:
> MissingMethodException: Method not found: 'GooglePlayServices.UnityCompat.get_ApplicationId'.
> UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs:249)

I never experienced something like this, even while making other games with this plugin (although it might be a previous version). I can build the game but what is this error? Maybe it has something to do with the Google Play Services plugin?

**Comment by rampara** [comment]
@Thornus are you only using the Google Mobile Ads Unity plugin in your project are are you also including other Firebase Unity plugins? Also, are you using the latest version of this plugin?

**Comment by Thornus** [comment]
I'm using the latest version and Firebase Analytics is included in my project. By the way I kinda solved the problem by deleting and re-importing Play Services and Firebase Analytics plugins (the excepetion doesn't appear anymore). GitHub didn't let me modify the original post.

**Comment by rampara** [comment]
@Thornus Glad you were you able to resolve your problem. Closing this issue. Please reopen if you run into it again.
