### ISSUE TITLE
Google.JarResolver Cannot find artifact from.. error

### ISSUE THREAD

**Issue by jemerren16** [googleads/googleads-mobile-unity#410]
Hi guys,

I have the following error message:

` ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-ads-lite:[10.2.4]
Google.JarResolver.PlayServicesSupport.GetDependencies (Google.JarResolver.Dependency dep, System.Collections.Generic.List`1 repoPaths)
Google.JarResolver.PlayServicesSupport.GetTransitiveDependencies (System.Collections.Generic.Dictionary`2 dependencies, System.Collections.Generic.List`1 repoPaths)
Google.JarResolver.PlayServicesSupport.FindMissingDependencyPaths (System.String destinationDirectory, System.Collections.Generic.Dictionary`2& dependencyPaths, Google.JarResolver.ExplodeAar explodeAar)
GooglePlayServices.ResolverVer1_1.DoResolution (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation, System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.Resolve (System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.MenuResolve () `

I've searched in several websites, but I don´t seem to find the answer.
The following SDK Extras are already updated:
- Android Support Repository
- Google Play Services
- Google Repository

**Comment by Votrubec** [comment]
Any suggestions on how to fix this? Spent WAY too long searching for answers.

**Comment by JillionStudio** [comment]
same issue .
Even sdk is totally updated.

**Comment by DozeX** [comment]
**same error, someone how to fix ?**

**Comment by rampara** [comment]
Importing the [latest version](https://github.com/googlesamples/unity-jar-resolver/blob/master/play-services-resolver-1.2.17.0.unitypackage) (v1.2.17) of JarResolver should resolve this issue. You may have to perform version resolution by selecting `Assets -> Play Services Resovler -> Version Handler -> Update` after importing the updated JarResolver library.

**Comment by JillionStudio** [comment]
page not found

**Comment by JillionStudio** [comment]
you mean [this](https://github.com/googlesamples/unity-jar-resolver/blob/master/play-services-resolver-1.2.19.0.unitypackage)

**Comment by rampara** [comment]
@JillionStudio looks like the version was bumped since I made my post. The link you provided is correct. Updated my earlier post to reflect this.

**Comment by guilhermeouriques** [comment]
I had the same issue and I think it's solved now.

Open AdMobDependencies.cs file, located inside of Assets -> GoogleMobileAds -> Editor, with your text editor and find the line: 

> Google.VersionHandler.InvokeInstanceMethod(svcSupport, "DependOn", new object[] { "com.google.android.gms", "play-services-ads", "LATEST" },

 that is in SetupDeps() method.

Now change the string "LATEST" to "10.2.1". That worked for me, hope it helps someone.

**Comment by rampara** [comment]
The latest version of this plugin (v3.5.0) pulls in the latest version of the JarResovler library, which includes a fix for this issue. @guilhermeouriques once you update to v3.5.0, you'll no longer have to use older versions of Google Play services dependencies.
