### ISSUE TITLE
should consider package the file in a SDK specified folder

### ISSUE THREAD

**Issue by armnotstrong** [googleads/googleads-mobile-unity#411]
Hi, I found your unity package have a top-level folder named "Plugins" which is a common name be used by many packages, (Or even by our project), shall we package that to a more SDK specified folder, so that user could save some effort to delete/re-import the SDK? thanks.

![folder](https://cloud.githubusercontent.com/assets/3839691/25657862/840f616a-3032-11e7-8e55-b2014945bfe6.png)

**Comment by rampara** [comment]
The `Plugins` directory is meant to be used by all plugins in a Unity project. Did you mean you wanted specific sub-directories under `Plugins/Assets/Android` and `Plugins/Assets/iOS` ?

**Comment by armnotstrong** [comment]
@rampara that should be an option, if possible :+1:

**Comment by AdnanNazir** [comment]
yes, this will be so good. 
Like Facebook Official SDK for Unity. It just contains all of it's plugins folders and file in One Folder called FacebookSDK

thanks

**Comment by rampara** [comment]
This plugin relies on the [JarResolver](https://github.com/googlesamples/unity-jar-resolver) library to include Google Play Services dependencies, which copies the required AARs to the `Assets/Plugins/Android` directory of a Unity project. You'll want to open similar feature request in that repo.

**Comment by rampara** [comment]
Closing issue as new Unity directory structure will not permit this.
