### ISSUE TITLE
Rewarded Ads not triggering event

### ISSUE THREAD

**Issue by bilck** [googleads/googleads-mobile-unity#412]
"RewardBasedVideo.OnAdRewarded" event is never triggered.
Currently testing on Android devices.

The other events are called correctly.

As a suggestion, it would be **great** to be able to check if the Video Ad was fully displayed to the user, so that the user receives its reward only if deserved.

**Comment by NarsunProjects** [comment]
we're receiving the same issue.

**Comment by rampara** [comment]
@bilck are you able to reproduce this issue with the [sample project](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) that uses a test ad unit id?

**Comment by bilck** [comment]
We had some Unity 3D's issues due to the fact that the callbacks are on a separate thread.
We were triggering analytics events on callbacks, and Unity Analytics' calls must be performed on the main thread.

It is working properly now, thanks a lot!
