### ISSUE TITLE
It's not possible to call different Rewarded Ads with different Rewards

### ISSUE THREAD

**Issue by bilck** [googleads/googleads-mobile-unity#413]
I would like to be able to call different Rewarded Ads without having to keep track by myself what is the proper reward for that Ad.

Another thing to keep in mind is that it would be interesting to avoid loading multiple Ads just because of this feature, a rewarded video could be kept in cache if it shares categories among other possible Rewarded Ads.

**Comment by rampara** [comment]
Does using different ad units configured with different awards not meet your needs? You should then be able to access the different rewards from the `OnAdRewarded` event.

**Comment by bilck** [comment]
It is not enough, specially considering Unity 3D's SDK, which consider rewarded ads as a singleton. We know it's possible to change the SDK's source code, but it would be nice if this is supported out of the box.

We are currently tracking the reward type and amount manually (thus overriding the OnAdRewarded values), since the target ad unit is defined when creating the RewardedAd.
I would be nice, though, if we had a way to load the rewarded and set the ad unit id when displaying the ad.

**Comment by rampara** [comment]
There has been some consideration on "de-singletonifying" the rewarded video ad structure for the GMA SDK. Will take you feedback to the GMA SDK team.

**Comment by rampara** [comment]
Closing as this is an GMA SDK feature request. The GMA SDK is currently working on incorporating this functionality. I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for more information.
