### ISSUE TITLE
Interstitial Ads Not Showing

### ISSUE THREAD

**Issue by binarybehemoth** [googleads/googleads-mobile-unity#415]
Somehow, my Interstitial ads are not showing in my mobile phone after I updated Google Mobile Ads SDK to Version 3.5.0. All I am seeing is the closing X and empty circle (supposedly for the timer) at the corners, on a completely black screen.

Nevertheless, the banner ads are still showing. 

I wonder whether some of the others are experiencing the same problem.

**Comment by rampara** [comment]
@binarybehemoth are you experiencing this issue with both test ads and live ads? Are you able to reproduce the issue with the sample app in this repo? If so, can you provide a Wireshark or Charles log of the ad request which loads the incorrectly behaving interstitial?

**Comment by binarybehemoth** [comment]
I used to run live ads in my app. Actually I have been unable to upload the latest version of my APK at Google Developer Console for days, so I cannot tell you whether if downloaded from Google Play the ads will be seen correctly. I tried contacting Google support for the problem in Google Developer Console but they have not replied me. I wonder when I will be able to start uploading and releasing my app again.

**Comment by rampara** [comment]
@binarybehemoth for this issue, a can you provide a Wireshark or Charles log of the ad request which loads the incorrectly behaving interstitial? Also, can you provide details on device configuration (device type, os version etc.) on which you're able to reproduce the issue?

**Comment by binarybehemoth** [comment]
The Model number is Samsung GT-N7100. The Android version is 4.3.

I just downloaded Wireshark. How do I capture the log? What IP address should I look for?

**Comment by rampara** [comment]
@binarybehemoth if you're unfamiliar with how to collect network traffic logs we can try investigating through other avenues. Are you experiencing this issue with test ads? Are you able to reproduce the issue with the sample app in this repo?

**Comment by binarybehemoth** [comment]
How do I use test ads? Where is the sample app?

**Comment by rampara** [comment]
The sample app can be found in this [repo](https://github.com/googleads/googleads-mobile-unity/tree/master/samples). To use test ads either use the test ad unit id values found in the sample app, or follow the instructions in our [developer docs](https://developers.google.com/admob/unity/start#test_ads).

**Comment by binarybehemoth** [comment]
I just tested it in my phone. In the sample app, I could display all the ads except the rewarded video ads. But that was not the problem. Originally, my android phone could also display some interstitial ads, but only the static interstitial ads. The real problem now is with VIDEO interstitial ads, which are always blank as I described in the first post here.

**Comment by rampara** [comment]
@binarybehemoth are you able to repro this on any other device or is the issue only present on the Samsung GT-N7100?

**Comment by binarybehemoth** [comment]
I am only able to repro this issue on Samsung GT-N7100 so far. I tested it on two other phones which did not show the problem.

**Comment by rampara** [comment]
@binarybehemoth I currently don't have access to Samsung GT-N7100 to test against but this issue does not seem specific to this plugin as you're able to request and display non-video ads without issue. I would recommend reaching out on the [Google Mobile Ads support forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
