### ISSUE TITLE
Banner Ads not showing on android devices

### ISSUE THREAD

**Issue by jpollar4** [googleads/googleads-mobile-unity#416]
Hello, I'm not able to get my banner ad to show on devices. The test banners are showing up fine on my phone.

When I run logcat on my non-test phone i get this following error: 
`	05-14 11:41:33.949 19555 19555 I Ads     : Starting ad request.
	05-14 11:41:33.952 19555 19555 I Ads     : Use AdRequest.Builder.addTestDevice("XXXXXXXXXXXXX") to get test ads on this device.
	05-14 11:41:35.527  8030 20005 W Ads     : Received error HTTP response code: 400
	05-14 11:41:35.529 19555 19566 W Ads     : There was a problem getting an ad response. ErrorCode: 0
	05-14 11:41:35.532 19555 19555 W Ads     : Failed to load ad: 0`

my Code is:
`void Start () {
		
		string adUnitId = "ca-app-pub-7775828650687740/2458708512";
		BannerView bannerView = new BannerView(adUnitId, AdSize.SmartBanner, AdPosition.Bottom);
		// Create an empty ad request.
		AdRequest request = new AdRequest.Builder()
			.AddTestDevice("2EAD6F16BBC02AACA6EB5724669F3792")  // My test device.
			.Build();

		//AdRequest request = new AdRequest.Builder().Build();
		// Load the banner with the request.
		bannerView.LoadAd(request);
		bannerView.Show ();

	}`

**Comment by rampara** [comment]
@jpollar4 Strange, i'm able to request and display live ads using the ad unit from the code snippet in your post. Can you post the output you see in logcat under the `Ads` tag after you turn on verbose logging. Verbose logging can be turned on by running the following command:

`adb shell setprop log.tag.Ads VERBOSE`

**Comment by jpollar4** [comment]
Actually, the banner ad started working fine this morning. 

Its possible that the ad unit hadn't become active until now? Two days seems like a long time.

But, regardless. All seems well now.

Thanks for reaching out!

**Comment by rampara** [comment]
@jpollar4 ad units should normally be ready to serve in an hour but this can sometimes take longer. Glad you were able to get everything working.
