### ISSUE TITLE
Live ads blocked during development??

### ISSUE THREAD

**Issue by ghost** [googleads/googleads-mobile-unity#417]
Hello,

Is it possible that Google is blocking live ads from showing in development builds or on devices used during development?

I have an app on the store that shows the ads just fine but when I try to test  the live ads on a development build, the ads do not show.

Test ads work just fine.

**Comment by rampara** [comment]
@Mintonne live ads should load with a development build but it's recommended not to test with live ads. What error code do you receive when the ads fail to load? Can you provide a Charles or Wireshark log of the ad request that failed to load?

**Comment by rampara** [comment]
Closing issue due to it's age. Please re-open if this issue persists for you.
