### ISSUE TITLE
Banner and interstital ads not showing

### ISSUE THREAD

**Issue by freedom667** [googleads/googleads-mobile-unity#419]
i hav admob 3.5.0 everything is true. codes, anroidmanifest etc. but when i try in adnroid device ads not showing.  I looked alogcat and adb logcat but there is no error.

**Comment by Bozin3** [comment]
Same here! The test ads are working fine, but the real ads are not showing.

**Comment by rampara** [comment]
@freedom667 @Bozin3 can you post the the output you see in logcat under the `Ads` tag. Turning on verbose logging should provide additional information. To turn on verbose logging for the Android GMA SDK, run the following command:

`adb shell setprop log.tag.Ads VERBOSE`

Also, are you running into the same issue when using the sample app from this repo with live ad units swapped in? If so, can you provide me with the ad unit that's failing to load ads for you.

**Comment by Bozin3** [comment]
I am using these script, am i doing something wrong? Also i replaced the test adunitID with real one
`using UnityEngine;
using System.Collections;
using GoogleMobileAds.Api;

public class Ads : MonoBehaviour
{

    bool hasShownAdOneTime;

    // Use this for initialization
    void Start()
    {
        //Request Ad
        RequestInterstitialAds();
    }

    void Update()
    {
        if (Game.isGameOver)
        {
            if (!hasShownAdOneTime)
            {
                hasShownAdOneTime = true;
                Invoke("showInterstitialAd", 3.0f);
            }
        }
    }

    public void showInterstitialAd()
    {
        //Show Ad
        if (interstitial.IsLoaded())
        {
            interstitial.Show();

            //Stop Sound
            //

            Debug.Log("SHOW AD XXX");
        }

    }

    InterstitialAd interstitial;
    private void RequestInterstitialAds()
    {
        string adID = "ca-app-pub-3940256099942544/1033173712";

#if UNITY_ANDROID
        string adUnitId = adID;
#elif UNITY_IOS
        string adUnitId = adID;
#else
        string adUnitId = adID;
#endif

        // Initialize an InterstitialAd.
        interstitial = new InterstitialAd(adUnitId);

        //***Test***
        AdRequest request = new AdRequest.Builder()
       .AddTestDevice(AdRequest.TestDeviceSimulator)       // Simulator.
       .AddTestDevice("2077ef9a63d2b398840261c8221a0c9b")  // My test device.
       .Build();

        //***Production***
        //AdRequest request = new AdRequest.Builder().Build();

        //Register Ad Close Event
        interstitial.OnAdClosed += Interstitial_OnAdClosed;

        // Load the interstitial with the request.
        interstitial.LoadAd(request);

        Debug.Log("AD LOADED XXX");

    }

    //Ad Close Event
    private void Interstitial_OnAdClosed(object sender, System.EventArgs e)
    {
        //Resume Play Sound

    }
}`

**Comment by rampara** [comment]
@Bozin3 what output do you see in logcat under the `Ads` tag? The command in my previous post will turn on verbose logging to see additional output.

**Comment by Bozin3** [comment]
The log cat says
Ads:Starting ad request.
Ads:No fill from ad server.
Ads:Failed to load ad: 3

**Comment by rampara** [comment]
@Bozin3 can you post the entire out from logcat under the `Ads` tag once you turn on verbose logging?

**Comment by rampara** [comment]
Closing issue due to it's age. Please re-open if this issue persists for you.
