### ISSUE TITLE
Reward Video crashes app on start

### ISSUE THREAD

**Issue by artakino** [googleads/googleads-mobile-unity#420]
Reward Video often crashes when it is started with the error below.  It seems that it may be happing when GC.Collect() is called at some point between LoadAd() and ShowAd() calls.

`D/Unity   ( 1942): SetWindow 0 0x5f23f808
D/PanelView( 1248): mClearAll.setVisibility - mIsFullyOpened : false isShade : true mHasNotification : true mIsUpwardFling : false mQsFullyExpanded : true isShadeLocked : false mClearAllVisible : true
I/art     ( 1942): Alloc sticky concurrent mark sweep GC freed 18639(992KB) AllocSpace objects, 6(192KB) LOS objects, 3% free, 123MB/128MB, paused 868us total 11.411ms
I/art     ( 1942): Clamp target GC heap from 139MB to 128MB
I/art     ( 1942): Alloc partial concurrent mark sweep GC freed 4046(246KB) AllocSpace objects, 1(64KB) LOS objects, 3% free, 123MB/128MB, paused 786us total 22.172ms
I/art     ( 1942): Clamp target GC heap from 139MB to 128MB
I/art     ( 1942): Alloc concurrent mark sweep GC freed 117(16KB) AllocSpace objects, 0(0B) LOS objects, 3% free, 123MB/128MB, paused 805us total 30.923ms
I/art     ( 1942): Forcing collection of SoftReferences for 21MB allocation
I/art     ( 1942): Clamp target GC heap from 139MB to 128MB
I/art     ( 1942): Alloc concurrent mark sweep GC freed 11(344B) AllocSpace objects, 0(0B) LOS objects, 3% free, 123MB/128MB, paused 799us total 27.306ms
E/art     ( 1942): Throwing OutOfMemoryError "Failed to allocate a 22118412 byte allocation with 4865356 free bytes and 4MB until OOM"
D/AndroidRuntime( 1942): Shutting down VM
W/System.err( 1942): java.lang.OutOfMemoryError: Failed to allocate a 22118412 byte allocation with 4865356 free bytes and 4MB until OOM
W/System.err( 1942): 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
W/System.err( 1942): 	at android.graphics.Bitmap.nativeCreate(Native Method)
W/System.err( 1942): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
W/System.err( 1942): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
W/System.err( 1942): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:843)
W/System.err( 1942): 	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:719)
W/System.err( 1942): 	at com.unity3d.player.i.onLayoutChange(Unknown Source)
W/System.err( 1942): 	at android.view.View.layout(View.java:16703)
W/System.err( 1942): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
W/System.err( 1942): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
W/System.err( 1942): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
W/System.err( 1942): 	at android.view.View.layout(View.java:16694)
W/System.err( 1942): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
W/System.err( 1942): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
W/System.err( 1942): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
W/System.err( 1942): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
W/System.err( 1942): 	at android.view.View.layout(View.java:16694)
W/System.err( 1942): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
W/System.err( 1942): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
W/System.err( 1942): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
W/System.err( 1942): 	at android.view.View.layout(View.java:16694)
W/System.err( 1942): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
W/System.err( 1942): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2321)
W/System.err( 1942): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2034)
W/System.err( 1942): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
W/System.err( 1942): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6641)
W/System.err( 1942): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
W/System.err( 1942): 	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
W/System.err( 1942): 	at android.view.Choreographer.doFrame(Choreographer.java:560)
W/System.err( 1942): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
W/System.err( 1942): 	at android.os.Handler.handleCallback(Handler.java:739)
W/System.err( 1942): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err( 1942): 	at android.os.Looper.loop(Looper.java:145)
W/System.err( 1942): 	at android.app.ActivityThread.main(ActivityThread.java:5944)
W/System.err( 1942): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 1942): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 1942): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
W/System.err( 1942): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
W/FlurryAgent( 1942): Error logged: uncaught
E/AndroidRuntime( 1942): FATAL EXCEPTION: main
E/AndroidRuntime( 1942): Process: com.Lightbound.StarChasers, PID: 1942
E/AndroidRuntime( 1942): java.lang.Error: FATAL EXCEPTION [main]
E/AndroidRuntime( 1942): Unity version     : 5.6.0f3
E/AndroidRuntime( 1942): Device model      : samsung SAMSUNG-SM-N900A
E/AndroidRuntime( 1942): Device fingerprint: samsung/hlteuc/hlteatt:5.0/LRX21V/N900AUCSEOC3:user/release-keys
E/AndroidRuntime( 1942): 
E/AndroidRuntime( 1942): Caused by: java.lang.OutOfMemoryError: Failed to allocate a 22118412 byte allocation with 4865356 free bytes and 4MB until OOM
E/AndroidRuntime( 1942): 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
E/AndroidRuntime( 1942): 	at android.graphics.Bitmap.nativeCreate(Native Method)
E/AndroidRuntime( 1942): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
E/AndroidRuntime( 1942): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
E/AndroidRuntime( 1942): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:843)
E/AndroidRuntime( 1942): 	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:719)
E/AndroidRuntime( 1942): 	at com.unity3d.player.i.onLayoutChange(Unknown Source)
E/AndroidRuntime( 1942): 	at android.view.View.layout(View.java:16703)
E/AndroidRuntime( 1942): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
E/AndroidRuntime( 1942): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
E/AndroidRuntime( 1942): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
E/AndroidRuntime( 1942): 	at android.view.View.layout(View.java:16694)
E/AndroidRuntime( 1942): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
E/AndroidRuntime( 1942): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
E/AndroidRuntime( 1942): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
E/AndroidRuntime( 1942): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
E/AndroidRuntime( 1942): 	at android.view.View.layout(View.java:16694)
E/AndroidRuntime( 1942): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
E/AndroidRuntime( 1942): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
E/AndroidRuntime( 1942): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
E/AndroidRuntime( 1942): 	at android.view.View.layout(View.java:16694)
E/AndroidRuntime( 1942): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
E/AndroidRuntime( 1942): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2321)
E/AndroidRuntime( 1942): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2034)
E/AndroidRuntime( 1942): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
E/AndroidRuntime( 1942): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6641)
E/AndroidRuntime( 1942): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
E/AndroidRuntime( 1942): 	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
E/AndroidRuntime( 1942): 	at android.view.Choreographer.doFrame(Choreographer.java:560)
E/AndroidRuntime( 1942): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
E/AndroidRuntime( 1942): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 1942): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 1942): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime( 1942): 	at android.app.ActivityThread.main(ActivityThread.java:5944)
E/AndroidRuntime( 1942): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1942): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 1942): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime( 1942): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)`

**Comment by rampara** [comment]
@artakino is this crash consistently reproducible for you? Are you able to reproduce it with the sample app from this repo? Are you using mediation for your rewarded video ads?

**Comment by artakino** [comment]
Yes, it is reproducible but not consistent.  However, I seem to be get consistent crashes when I run GC.Collect() before ShowAd().  I have not tried the sample app on an Android device.  And yes, I am using mediation for rewarded video ads.

**Comment by rampara** [comment]
Can you test if this issue is still reproducible when using an ad unit that is configured for AdMob demand only?

**Comment by artakino** [comment]
Thanks, will test it and let you know.

**Comment by rampara** [comment]
Awaiting your follow up to continue investigating this.

**Comment by artakino** [comment]
Turning off all mediated networks did fix the issue.  I believe the next step is to see which network causes the issue.

**Comment by rampara** [comment]
Yep. Once that's done I can start digging into what's actually causing the crash.

**Comment by artakino** [comment]
I get the same exact OutOfMemory error every time the video ad is triggers.  To make things even more interesting there is this one ad, only that one ad, plays without crashing the game.  It's an ad that is served by Admob.

**Comment by artakino** [comment]
Hi rampara,
I found the source of the bug and it has nothing to do with the plugin.  It just happen to occur when the game would go out of focus.  It's actually a bug with Unity's static splash screen in Unity 5.6.  Here is the bug report incase you need it.
https://issuetracker.unity3d.com/issues/android-application-crashes-on-start-with-high-resolution-of-static-splash-image

Thanks for your help.
