### ISSUE TITLE
Admb Rewarded Video Not Showing.

### ISSUE THREAD

**Issue by EvilKiller123** [googleads/googleads-mobile-unity#422]
Admob Rewarded Video Not Showing getting the error "**Add Failed To Load**", Not Using any Mediation Just Wanted Simple AdMob Rewarded Video To Popup, I Have Tried Your Sample Project And Your Admob Test Id But The Result Is The Same.

**Comment by rampara** [comment]
What error code/ error message are you receiving when the  ad fails to load? Are you running into this issue when deploying to the Android or iOS platform?

**Comment by EvilKiller123** [comment]
i am using events to get this message "Error Failed To Load"

here's my code.



using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GoogleMobileAds;
using GoogleMobileAds.Api;
using System;
using UnityEngine.UI;

public class addscalling : MonoBehaviour {


	public GameObject Test;
	private RewardBasedVideoAd rewardBasedVideo;
	// Use this for initialization
	void Start () {
		rewardBasedVideo = RewardBasedVideoAd.Instance;

		rewardBasedVideo.OnAdLoaded += HandlerOnAdLoaded;
		// has failed to load.
		rewardBasedVideo.OnAdFailedToLoad += HandlerOnAdFailedToLoad;
		// is opened.
		rewardBasedVideo.OnAdOpening += HandlerOnAdOpening;
		// has started playing.
		rewardBasedVideo.OnAdStarted += HandlerOnAdStarted;
		// has rewarded the user.
		rewardBasedVideo.OnAdRewarded += HandlerOnAdRewarded;
		// is closed.
		rewardBasedVideo.OnAdClosed += HandlerOnAdClosed;
		// is leaving the application.
		rewardBasedVideo.OnAdLeavingApplication += HandlerOnAdLeavingApplication;
		
	}
	
	// Update is called once per frame
	void Update () {
		
	}

	public void ShowAd()
	{
		
		if (rewardBasedVideo.IsLoaded ()) {
			rewardBasedVideo.Show ();

		} else {
			Test.SetActive (true);
			Test.GetComponentInChildren<Text> ().text = "AddsNot Loaded".ToString ();
			RequestRewardBasedVideo ();
		
		}
	}

	public void RequestRewardBasedVideo()
	{
		#if UNITY_EDITOR
		string adUnitId = "unused";
		#elif UNITY_ANDROID
		string adUnitId = "ca-app-pub-3901152910751257/4441861722";
		#elif UNITY_IPHONE
		string adUnitId = "";
		#else
		string adUnitId = "unexpected_platform";
		#endif

		RewardBasedVideoAd rewardBasedVideo = RewardBasedVideoAd.Instance;

		AdRequest request = new AdRequest.Builder().Build();
		rewardBasedVideo.LoadAd(request, adUnitId);
		}


		public void HandlerOnAdLoaded(object sender, EventArgs args){
	
		Test.SetActive (false);
		Test.GetComponentInChildren<Text> ().text = "HandlerOnAdLoaded".ToString ();

		}
		public void HandlerOnAdFailedToLoad(object sender, AdFailedToLoadEventArgs args){

		Test.SetActive (true);
		Test.GetComponentInChildren<Text> ().text = "HandlerOnAdFailedToLoad".ToString ();

		}

		public void HandlerOnAdOpening(object sender, EventArgs args){



		}

		public void HandlerOnAdStarted(object sender, EventArgs args){



		}


		public void HandlerOnAdClosed(object sender, EventArgs args){



		}

		public void HandlerOnAdRewarded(object sender, Reward args){

		Test.SetActive (false);

		}
		public void HandlerOnAdLeavingApplication(object sender, EventArgs args){



		}


//		public event EventHandler<AdFailedToLoadEventArgs> OnAdFailedToLoad;
//
//		public event EventHandler<EventArgs> OnAdOpening;
//
//		public event EventHandler<EventArgs> OnAdStarted;
//
//		public event EventHandler<EventArgs> OnAdClosed;
//
//		public event EventHandler<Reward> OnAdRewarded;
//
//		public event EventHandler<EventArgs> OnAdLeavingApplication;

}

**Comment by rampara** [comment]
@EvilKiller123 are you running into this issue when deploying to Android or iOS?

**Comment by EvilKiller123** [comment]
In Android Didnt Try On Ios

**Comment by rampara** [comment]
@EvilKiller123 By taking the ad unit from your code snippet and plugging it into the sample app in the repo, I was able to request and display rewarded video ads without issue. By any chance are you making ad requests from China?

**Comment by EvilKiller123** [comment]
No From Pakistan

**Comment by rampara** [comment]
@EvilKiller123 since this issue is not specific to this plugin but rather a serving issue, I would recommend reaching out on the [Google Mobile Ads SDK Technical Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
