### ISSUE TITLE
Unable to merge manifest problem, i'm stuck.

### ISSUE THREAD

**Issue by ognjenmarcheta** [googleads/googleads-mobile-unity#423]
Hi there, 

Recently i switched quickly to another project (native android) which asked me to update android tools, sdk, etc. Now i go back to my unity project and i found out i can't build project, even i didn't touched it since last time when everything was ok.

Problem:
Unable to merge android manifests.
I'm using google analytics, google ads, play services and facebook.
[Some random screenshot](http://prntscr.com/f99ndt)
I tired to set in manifest files min and targets versions to equal values, but i still get same error.

Why i posted issue here? Well when i delete manifest of this plugin. That error is gone, but i get new one about missing manifest of this plugin xD

```
Error: Error while saving blame file, build will continue
Error: The prefix "tools" for attribute "tools:overrideLibrary" associated with an element type "uses-sdk" is not bound.
```

```
AndroidSDKToolsException: Unable to merge android manifests. See the Console for more details. 
UnityEditor.Android.AndroidSDKTools.DetectErrorsAndWarnings (System.String logMessages, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommand (System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommand (System.String[] sdkToolCommand, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommand (System.String[] sdkToolCommand, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.MergeManifests (System.String target, System.String mainManifest, System.String[] libraryManifests, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit)
UnityEditor.Android.PostProcessor.Tasks.GenerateManifest.MergeManifests (UnityEditor.Android.PostProcessor.PostProcessorContext context, System.String targetManifest, System.String mainManifest)
UnityEditor.Android.PostProcessor.Tasks.GenerateManifest.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.HostView:OnGUI()


```

**Comment by rampara** [comment]
Can you post the more information from the Unity console output that describes why the manifest file merge failed?

**Comment by ognjenmarcheta** [comment]
That is everything i get in console. Those two messages.

**Comment by ognjenmarcheta** [comment]
Solution found on unity issue tracker:

1) just open https://developer.android.com/studio/index.html 
2) scroll down to the bottom of that page 
3) go to downloads 
4) scroll down to the bottom of that page 
5) find Windows "tools_r25.2.3-windows.zip" download and unzip it 
5) find MacOSX "tools_r25.2.3-macosx.zip" download and unzip it. 
6) In the SDK path replace the tools folder.

**Comment by MuradDasi** [comment]
I managed to make a build using:
- Navigate to Plugins/Android/AndroidManifest
- add line: xmlns:tools="http://schemas.android.com/tools" **AFTER the line** manifest xmlns:android="http://schemas.android.com/apk/res/android"
**Note:** _I build it just now but I have not tested it yet_
