### ISSUE TITLE
Android gradle build error

### ISSUE THREAD

**Issue by brisa0730** [googleads/googleads-mobile-unity#424]
Google is updating a lot these days. Android SDK, Google Play Services, Google Ads, Firebase. Those assets are using so much methods that nothing else seems to fit inside 64k dex limit.

Well I am using all those assets and now I have no choice but to hope gradle build system would ease things a bit. 

Gradle build system is throwing this error when I add Google Ads:

- I double checked to make sure I don't have "android:debuggable" in AndroidManifest.xml.
- This can be reproduced by creating a new project and adding just the GoogleAds.
- I am using Unity 5.6.1f, GoogleAds 3.5.0

Error: Avoid hardcoding the debug mode; leaving it out allows debug and release builds to automatically assign one [HardcodedDebugMode]
	
&#60;application android:icon="&#64;drawable&#47; app_icon" android:label="&#64;string&#47; app_name" android:theme="&#64;style&#47; UnityThemeSelector" android:debuggable="false" android:isGame="true" android:banner="&#64;drawable&#47; app_banner"&#62;
                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "HardcodedDebugMode":
   It's best to leave out the android:debuggable attribute from the manifest.
   If you do, then the tools will automatically insert android:debuggable=true
   when building an APK to debug on an emulator or device. And when you
   perform a release build, such as Exporting APK, it will automatically set
   it to false.

   If on the other hand you specify a specific value in the manifest file,
   then the tools will always use it. This can lead to accidentally publishing
   your app with debug information.

1 errors, 0 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForRelease'.
&#62; com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/unity/BuildConfig;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by ognjenmarcheta** [comment]
Hi i recently had similiar problem too. Maybe this will help you:
https://github.com/googleads/googleads-mobile-unity/issues/423

**Comment by brisa0730** [comment]
Hello, yeah hmm I tried tools 25.2.3. Didn't work. Unity gradle is throwing the same error.

**Comment by rampara** [comment]
@brisa0730 Just pushed a commit to resolve this issue (98d9053c706ddd924b2bec4db0ba3bfbad6123c9).

**Comment by brisa0730** [comment]
It worked! Thank you. I can't believe I've spent numerous hours because of this one simple line.

**Comment by rampara** [comment]
Glad everything is working for you now.
