### ISSUE TITLE
xCode project doesn't build (Unity 5.6, AdMob 3.5.0)

### ISSUE THREAD

**Issue by iseeall** [googleads/googleads-mobile-unity#425]
Hi! After updating to Unity 5.6 and AdMob plugin 3.5.0 I can't build iOS versions of the games anymore.
Attaching screenshots of the errors in xCode:

![screen shot 2017-05-22 at 12 15 13](https://cloud.githubusercontent.com/assets/8617651/26303202/79e01c2c-3eef-11e7-9f98-fe41a3407da4.png)
![screen shot 2017-05-22 at 12 16 12](https://cloud.githubusercontent.com/assets/8617651/26303201/79da161a-3eef-11e7-9d46-709773c43be6.png)

That's when I tried opening the project with xcworkspace, as advised in the manual.
I've also tried just opening the xCode project and add the GoogleMobileAds.framework version 1.20.0, with the same result.
xCode version 8.3.2, macOS Sierra 10.12.5, MacBook Mid 2010

A project built with Unity 5.5 and AdMob plugin 3.3.0 used to build fine.

**Comment by Lights999** [comment]
I have the same problem

**Comment by rampara** [comment]
@iseeall @Lights999 can you trying setting `Enable Modules (C and Objective-C)` to `Yes` in the project build settings for the xcworkspace.

**Comment by iseeall** [comment]
Thanks but I can't that setting in xCode. This is what I see in project build settings:
![screen shot 2017-05-24 at 00 03 43](https://cloud.githubusercontent.com/assets/8617651/26376348/dd156736-4014-11e7-94ab-d236b9501148.png)

Was "Language - Modules" section removed from xCode?
It seems to come up until LLVM 7.0 but not the current LLVM 8 (?)
https://www.google.ru/search?q=xCode+Enable+Modules+(C+and+Objective-C)&newwindow=1&rlz=1C1GIGM_enRU672RU672&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj7wrnh9IbUAhVnIJoKHcVRAUcQ_AUIDCgD&biw=1920&bih=946

**Comment by rampara** [comment]
<img width="1167" alt="screen shot 2017-05-23 at 2 31 17 pm" src="https://cloud.githubusercontent.com/assets/11047881/26377479/5769b1ea-3fc5-11e7-9049-b3a8ff374c0c.png">

The option should still be available under LLVM 8. Do you have the correct target selected?

**Comment by iseeall** [comment]
Do you mean target iOS version? I've change target iOS version from 7.0 to 8.0 in Unity, but still xCode project doesn't show "Language - Modules".

**Comment by rampara** [comment]
I meant Xcode target. 

<img width="206" alt="screen shot 2017-05-23 at 3 20 58 pm" src="https://cloud.githubusercontent.com/assets/11047881/26379060/1b31eb3c-3fcc-11e7-8cda-264549245318.png">
<img width="1199" alt="screen shot 2017-05-23 at 3 24 40 pm" src="https://cloud.githubusercontent.com/assets/11047881/26379032/fd1987c2-3fcb-11e7-9d8b-a62a78d10639.png">

If your project is selected as the target, the enable modules option will not be present.

**Comment by iseeall** [comment]
That's weird. The target project was correct.
But I see the Modules when selecting "Unity-iPhone Tests" project as target.
![screen shot 2017-05-24 at 11 17 15](https://cloud.githubusercontent.com/assets/8617651/26393788/99e203c0-4073-11e7-86cb-fd62ad35c5de.png)
![screen shot 2017-05-24 at 11 21 40](https://cloud.githubusercontent.com/assets/8617651/26393789/99e21a72-4073-11e7-9c43-2424d37aa0a2.png)

**Comment by iseeall** [comment]
Are these settings correct?
![screen shot 2017-05-24 at 11 30 55](https://cloud.githubusercontent.com/assets/8617651/26394113/918354e4-4074-11e7-845f-48ab6b593245.png)

**Comment by iseeall** [comment]
Solved it. "Apple LLVM 8.1 - Language - Modules" shows if one selects "All" instead of "Basic".
![screen-shot-2017-05-28-at-17 39 32](https://cloud.githubusercontent.com/assets/8617651/26529671/134c6a64-43cd-11e7-9f85-4d8ccaece5b4.png)
And after setting `Enable Modules (C and Objective-C)` to `Yes` the ads show fine. Thanks!
