### ISSUE TITLE
Mediation example - 2

### ISSUE THREAD

**Issue by boris-741** [googleads/googleads-mobile-unity#427]
I configured account [https://support.google.com/admob/answer/3124703](url).
I use Unity Ads Mediation. 
Unity project config:
put files:
Assets/Plugins/Android/unity-ads.aar
Assets/Plugins/Android/GoogleMobileAdsPlugin/libs/unity-2.1.0.0.aar
add to manifest:
`
<uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<activity android:name="com.unity3d.ads.adunit.AdUnitActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:hardwareAccelerated="true" android:theme="@android:style/Theme.NoTitleBar.Fullscreen" />
    <activity android:name="com.unity3d.ads.adunit.AdUnitSoftwareActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:hardwareAccelerated="false" android:theme="@android:style/Theme.NoTitleBar.Fullscreen" />
`
As I said, AdMob shows the video, but not all users. Unity ads 0 views

OS Android 4.2 - 7.0

Sorry could not add to the previous topic due to an error "You can't comment at this time"

**Comment by rampara** [comment]
If you're running an ad blocker it may prevent you from replying to GitHub issues. Also, the Unity Ads adapter should be included in the `Assets/Plugins/Android` directory of your Unity project not `Assets/Plugins/Android/GoogleMobileAdsPlugin/libs/`. You can also try filtering logcat output for content containing the words "Ads" and "Unity" to see if there are any issues with your integration.

**Comment by boris-741** [comment]
Can I disable AdMob and leave active only Unity Ads Mediation for test?

**Comment by rampara** [comment]
You can try configuring your ad unit to give Unity Ads a high eCPM value, causing it to be more likely to be served.

**Comment by rampara** [comment]
Closing issue due to it's age. Please re-open if this issue persists for you.
