### ISSUE TITLE
Ads can not be displayed on the real machine（Android platform）

### ISSUE THREAD

**Issue by mmz1995** [googleads/googleads-mobile-unity#428]
Huawei can not display advertising, mobile phone model is HUAWEI P6-C00

**Comment by rampara** [comment]
@mmz1995 can you provide for information on your issue? What error code do you receive if you handle the `OnAdFailedToLoad` ad event? Can you post the content from logcat under the `Ads` tag? What OS version is your device? Are you running into this issue for all ad formats or just specific ones?

**Comment by mmz1995** [comment]
I'm sorry I'm late. I am dealing with the OnAdFailedToLoad function is to reload the ad, I tested the system version of the real machine including Android system 4.4.2 and 5.0.1. Is it because the Android phone does not support the Google framework reasons? It should be noted that this game project is developed in Unity3D, this time to test the phone is Meizu phone, the system version is 5.0.1, and the phone installed Google framework, and then released to the Android Studio development environment , Running this project directly in Android Studio is an ad that can be displayed, but the ad does not appear after being packaged into APK and installed on the phone. What is the difference between these two modes of operation? What is the reason for the failure to display the ad after installing APK?

**Comment by rampara** [comment]
@mmz1995 when you're building an APK through Unity's build system, are you including Google Play services dependencies in your Unity project? Can you post the contents of `Asserts/Plugins/Android` directory of your Unity project?

**Comment by mmz1995** [comment]
@rampara 
 ![0d07c7a3-3203-4128-8799-9a3546500189](https://cloud.githubusercontent.com/assets/28854764/26671406/edd89582-46e7-11e7-9f82-5d16177b15fd.png)
Can you see this picture? Directory structure is like this, android folder contains a lot of dependency library, do you think this is correct? When I started running the APK on my phone, I suggest the following: "AndroidJavaException: java.lang.ClassNotFoundException: com.google.unity.ads.UnityAdListener java.lang.ClassNotFoundException: com.google.unity.ads.UnityAdListener" But by Android Studio to start the project, the phone on the error disappeared, everything is normal. What is the reason for this?

**Comment by mmz1995** [comment]
@rampara 
I think I know why the package can not be advertised after APK. Android Studio has six kinds of packaging, I chose not to include advertising jar package package to the final APK kind, which led to the APK can not display ads. So I changed the way to package, select the jar package can be packaged into the APK way, but then there was an error, the error is as follows: "Error: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom / google / unity / buildConfig; ".  According to the prompt, I can not find duplicate files, leading to this error is the reason why? If this error can be resolved, I Think that this project may be successful.

**Comment by rampara** [comment]
@mmz1995 can you try building the plugin again from head using the build script in this repo. There was a commit made recently that should resolve the dex error you're running into.

**Comment by mmz1995** [comment]
@rampara    Do I need to re-import the ad plugin into the project? I looked at the latest question to submit, they did not help me. Do I need to rebuild the plugin because it conflicts with other files?

**Comment by rampara** [comment]
@mmz1995 build a new plugin package from HEAD of this repo and re-import the package.

**Comment by mmz1995** [comment]
@rampara  Okay, I started to do that, thank you.

**Comment by rampara** [comment]
@mmz1995 let me know if the Unity package built from HEAD resolve the build issue you were running into.

**Comment by mmz1995** [comment]
@rampara  I re-imported the ad plug-in, in the Andrews project appeared in the package repeated tips. I tried to delete the possibility of the same package, after the release of APK and installation, advertising does not appear, and show the inclusion of advertising jar package lost error.The unity project in the import of advertising before the empty, repeat the package is what?
![4f279ec6-8ecd-495c-a349-458bffcf7956](https://user-images.githubusercontent.com/28854764/27364834-72501ce0-566f-11e7-9551-c6e0b4841ecc.png)
This is an error message.

![dfc5b381-51bd-42a3-a1d5-bb952f48505b](https://user-images.githubusercontent.com/28854764/27364962-17d29e7c-5670-11e7-9d33-c193d2021167.png)
![Uploading DFC5B381-51BD-42A3-A1D5-BB952F48505B.png…]()
![2caa030a-a130-40ec-8936-2c3a970d8c14](https://user-images.githubusercontent.com/28854764/27364980-25b8fd06-5670-11e7-81b0-b739fc98a6b9.png)
This is the dependency structure of the project.

**Comment by rampara** [comment]
@mmz1995 missed your response on this thread. If you're still experiencing this issue, updating to the latest version of the plugin should resolve it.

**Comment by rampara** [comment]
Please re-open this issue if you're still experiencing it.

**Comment by mmz1995** [comment]
@rampara  Thank you for your patience to help, and this problem has been resolved.Thank you very much.
