### ISSUE TITLE
Banner ads are not showing. I am using latest admob and google play services plugin in the project

### ISSUE THREAD

**Issue by ani051092** [googleads/googleads-mobile-unity#431]
I am using following code:

public void RequestBanner()
	{
		#if UNITY_EDITOR
		string adUnitId = "unused";
		#elif UNITY_ANDROID
		string adUnitId = "actual_ad_unit_id_string";
		#elif UNITY_IPHONE
		string adUnitId = "INSERT_IOS_BANNER_AD_UNIT_ID_HERE";
		#else
		string adUnitId = "unexpected_platform";
		#endif
	
		// Create a 320x50 banner at the top of the screen.
		BannerView bannerView = new BannerView(adUnitId, AdSize.Banner, AdPosition.Bottom);
		// Create an empty ad request.
		//AdRequest request = new AdRequest.Builder().Build();
		AdRequest request = new 
                AdRequest.Builder().AddTestDevice("my_phone_android_device_id_string").Build();
		// Load the banner with the request.
		bannerView.LoadAd(request);
	}
Logcat:
AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.AdSize
I/Unity   ( 4339): java.lang.ClassNotFoundException: com.google.android.gms.ads.AdSize
I/Unity   ( 4339): 	at java.lang.Class.classForName(Native Method)
I/Unity   ( 4339): 	at java.lang.Class.forName(Class.java:308)
I/Unity   ( 4339): 	at java.lang.Class.forName(Class.java:272)
I/Unity   ( 4339): 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
I/Unity   ( 4339): 	at com.unity3d.player.UnityPlayer.a(Unknown Source)
I/Unity   ( 4339): 	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
I/Unity   ( 4339): 	at android.os.Handler.dispatchMessage(Handler.java:98)
I/Unity   ( 4339): 	at android.os.Looper.loop(Looper.java:135)
I/Unity   ( 4339): 	at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
I/Unity   ( 4339): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.AdSize" on path: DexPathList[[zip file "/data/app/com.animeshsuman.zipzapzop-1/base.apk"],nativeLibraryDirectories=[/data/app/com.animeshsuman.zipzapzop-1/lib/arm, /vendor/lib, /system/lib]]
I/Unity   ( 4339): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
I/Unity   ( 4339): 	at java.lang.ClassLoader.load

Please suggest me solution for this.

**Comment by rampara** [comment]
@ani051092 can you post the contents of the `Assets/Plugins/Android` directory of your Unity project?

**Comment by ani051092** [comment]
@rampara Thanks for response but i have figured out this. Actually some .arr file were missing so i used dependencies resolver thorough play service resolver and it worked for me. Closing this issue now.

**Comment by radi-cho** [comment]
I had similar issue and was able to solve it (or at least work around it).
If interested feel free to take a look over my blogpost: https://medium.com/@radicho/how-to-implement-admob-in-unity-a-bit-more-detailed-guide-4baed2821cce
