### ISSUE TITLE
Unity Admob rewarded video is showing but after video ad events are not getting called, below my code

### ISSUE THREAD

**Issue by TheMostWonderful** [googleads/googleads-mobile-unity#432]
using System.Collections;
using System.Collections.Generic;
using System;
using UnityEngine;
using GoogleMobileAds;
using GoogleMobileAds.Api;

public class AdManager : MonoBehaviour {
	private GameOver gameOver;
	private RewardBasedVideoAd rewardBasedVideoAd;
	//bool isWatched = false;

	// Use this for initialization
	void Start () {
		this.rewardBasedVideoAd = RewardBasedVideoAd.Instance;
		gameOver = FindObjectOfType<GameOver> ();
		this.LoadRewardBasedAd ();

		// has rewarded the user.
		this.rewardBasedVideoAd.OnAdRewarded += HandleOnAdRewarded;
		// is closed.
		this.rewardBasedVideoAd.OnAdClosed += HandleOnAdClosed;
		// is leaving the application.
		this.rewardBasedVideoAd.OnAdLeavingApplication += HandleOnAdLeavingApplication;
		this.rewardBasedVideoAd.OnAdFailedToLoad += HandleOnAdFailedToLoad;
		this.rewardBasedVideoAd.OnAdLoaded += HandleOnAdLoaded;
		this.rewardBasedVideoAd.OnAdOpening += HandleOnAdOpening;
		this.rewardBasedVideoAd.OnAdStarted += HandleOnAdStarted;
	}
	
	// Update is called once per frame
	void Update () {
		
	}
	private void LoadRewardBasedAd (){
		#if UNITY_EDITOR
		string adUnitId = "unused";
		#elif UNITY_ANDROID
		string adUnitId = "ca-app-pub-3940256099942544/5224354917";
		#elif UNITY_IPHONE
		string adUnitId = "ca-app-pub-3940256099942544/1712485313";
		#else
		string adUnitId = "unexpected_platform";
		#endif

		//Production
		//AdRequest adRequest = new AdRequest.Builder ().Build ();

		//Test
		//AdRequest adRequest = new AdRequest.Builder()
		//.AddTestDevice(AdRequest.TestDeviceSimulator)       // Simulator.
		//.AddTestDevice("c78b1468accb7ee846fa4f8e61bde0ff")  // My test device.
		//.Build();

		//Load ad
		this.rewardBasedVideoAd.LoadAd (new AdRequest.Builder ().Build (), adUnitId);
	}
		public void HandleOnAdLoaded(object sender, EventArgs args){

		}
		public void HandleOnAdFailedToLoad(object sender, AdFailedToLoadEventArgs args){

		}
		public void HandleOnAdOpening(object sender, EventArgs args){

		}
		public void HandleOnAdStarted(object sender, EventArgs args){

		}
		public void HandleOnAdRewarded (object sender, Reward args){
		Debug.Log ("resumed");
		gameOver.Resume ();
		}
		public void HandleOnAdClosed(object sender, EventArgs args){

		gameOver.Restart ();
		}
		public void HandleOnAdLeavingApplication (object sender,EventArgs args){

		gameOver.Restart ();
		}

		public void ShowRewardBasedAd (){
		if (this.rewardBasedVideoAd.IsLoaded ()) {
			this.rewardBasedVideoAd.Show ();

		} else {
			this.LoadRewardBasedAd ();
		}
	}
}

**Comment by ExtraFlash** [comment]
try to add this to your code:

public event EventHandler<EventArgs> OnAdLoaded;

    public event EventHandler<AdFailedToLoadEventArgs> OnAdFailedToLoad;

    public event EventHandler<EventArgs> OnAdOpening;

    public event EventHandler<EventArgs> OnAdStarted;

    public event EventHandler<EventArgs> OnAdClosed;

    public event EventHandler<Reward> OnAdRewarded;

    public event EventHandler<EventArgs> OnAdLeavingApplication;

I tried to do it today and it worked but the only problem is that when i click on the video button, if i close the video before it ends, the events wont work anymore

**Comment by rampara** [comment]
@TheMostWonderful are you also running into this issue when using the sample app included in this repo?

**Comment by TheMostWonderful** [comment]
I have fixed this issue, looks like I was getting, null reference, when I call object from event handler, thank you

**Comment by msureka** [comment]
How did you exactly fix this? Can you elaborate pls as I am facing the same issue. 
HandleOnAdRewarded() is not called after completing the reward video on iOS. But somehow on Android it is working.

Any ideas?

**Comment by habosoft** [comment]
I have the same issue with msureka. 
Any updates?

**Comment by ramkeshcse084** [comment]
public void ShowRewardBasedAd (){
	if (this.rewardBasedVideoAd.IsLoaded ()) {
		this.rewardBasedVideoAd.Show ();

	} else {
		this.LoadRewardBasedAd ();
	}

remove else{}:
public void ShowRewardBasedAd (){
	if (this.rewardBasedVideoAd.IsLoaded ()) {
		this.rewardBasedVideoAd.Show ();

	} 
		LoadRewardBasedAd ();
Starting method run only one times so first time your ad was showing coz you have called it. So you have to make a request again after 1st time reward. SO ,that"s why i removed else to make request again for reward.
For reference:https:[//www.youtube.com/watch?v=VzgrZhMnyn8](https://www.youtube.com/watch?v=VzgrZhMnyn8)
