### ISSUE TITLE
Can't create an ad unit on AdMob beta

### ISSUE THREAD

**Issue by vorora** [googleads/googleads-mobile-unity#433]
Hello, I just started to learn how to use AdMob. I tried to create a banner ad unit for my test app. But it struck and stayed on this following page forever.
![adunit](https://cloud.githubusercontent.com/assets/15316402/26618663/4fbd3c96-4605-11e7-986b-3db88335c337.png)
Later I used a dummy ad unit and it worked fine on my Android device (banners are shown). Do anyone know why I couldn't create an ad unit?

**Comment by rampara** [comment]
@vorora are you using an ad blocker? If so, you may run into issues (such as being unable to create an ad unit) when using AdMob beta.

**Comment by vorora** [comment]
I disable ad blocker and it worked perfectly now. Thank you very much!
