### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by ahmadhoo** [googleads/googleads-mobile-unity#435]
Hi 

I dont know if it will will sound silly for most of you or not.
Am a 0 experience in all of this, just need to make an app to run.

I keep receiving this error
"NullReferenceException: Object reference not set to an instance of an object
ShopManager.Start () (at Assets/Game_Assets/Scripts/Game/ShopManager.cs:23)
"

1 using UnityEngine;
2 using System.Collections;
3 using UnityEngine.UI;
4
5 public class ShopManager : MonoBehaviour {
6	
7	public GameObject[] itemSelectedGrps;
8	public GameObject[] itemLockedGrps;
9	public GameObject[] itemUnlockedGrps; 
10
11	public int[] itemAmts;
12	public Text killCountText; 
13	public Text[] itemAmtText;
14
15	int itemCount=0; 
16	// locked, unlocked, selected 
17	string[] items; 
18
19	// Use this for initialization
20	void Start () {
21		// hide the banner ad in the shop menu 
22
23		AdManager.manager.HideBannerAd();
24		items = new string[5];
25		itemCount = itemSelectedGrps.Length;
26		CheckItemStatus (false);
27		killCountText.text = PlayerPrefs.GetInt("thug_kill_count").ToString();
28
29		// set the unlock label value 
30		for(int i=0; i<itemAmts.Length;i++){
31			itemAmtText [i].text = itemAmts[i].ToString ();
32		}
33	}

I appreciate your support and patience.

Regards
AK

**Comment by rampara** [comment]
There is a [sample application](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) included in this repo that demonstrates how to use this plugin to request and display ads. This issue tracker is strictly for reporting issues with this plugin or feature requests.
