### ISSUE TITLE
Rewarded Video did't work in Unity 5.6.1

### ISSUE THREAD

**Issue by creamjun** [googleads/googleads-mobile-unity#436]
Development Environment.
1. Unity 5.6.1f1
2. Google Mobile Ads Unity 3.5.0

Android Build & Runtime  works fine.
iOS Build Okay. but Error occurs during iOS runtime.

Admob banner ads are good.
When I load RewardedVideoAds, see the following logs:

can not find com.google.DummyAdapter, check -ObjC option

 I definitely built it with the -ObjC option.
---------------------------------------------------------------------------------------------

**However, everything works fine with Unity 5.6.0.**

**Comment by rampara** [comment]
The "can not find com.google.DummyAdapter" error is indicative of a no-fill and isn't actually an error. Are you able to load ads without issue when using the rewarded video test ad unit (ca-app-pub-3940256099942544/5224354917)? That ad unit should return ads unless you have [Creative Preview](https://play.google.com/store/apps/details?id=com.google.android.apps.audition&hl=en) app already installed on your device.

**Comment by rampara** [comment]
Closing issue due to it's age. Please re-open if this issue persists for you.
