### ISSUE TITLE
Unity Cloud build error

### ISSUE THREAD

**Issue by eonyanov** [googleads/googleads-mobile-unity#438]
Help!
There is any way to successfull build GoogleAds for iOS with Unity Cloud Build?
I got error:
module.modulemap:2:19: error: umbrella header 'GoogleMobileAds.h' not found

I have included "GoogleMobileAds.framework" in "Assets\Plugins\iOS\".
And I have post-process script:

```
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEditor;
using UnityEditor.Callbacks;
#if UNITY_IOS
using UnityEditor.iOS.Xcode;
#endif

public static class XcodeProjectModifer {

    #if UNITY_CLOUD_BUILD
    // This method is added in the Advanced Features Settings on UCB
    // PostBuildProcessor.OnPostprocessBuildiOS
    public static void OnPostprocessBuildiOS (string exportPath)
    {
    Debug.Log("[UNITY_CLOUD_BUILD] OnPostprocessBuildiOS");
    OnPostProcessBuild(BuildTarget.iOS, exportPath);
    }
    #endif



    [PostProcessBuild]
    public static void OnPostProcessBuild(BuildTarget buildTarget, string path) {
        if (buildTarget == BuildTarget.iOS) {
            string projPath = path + "/Unity-iPhone.xcodeproj/project.pbxproj";

            PBXProject proj = new PBXProject();
            proj.ReadFromString(File.ReadAllText(projPath));
            string target = proj.TargetGuidByName("Unity-iPhone");

            // GoogleMobileAds (aka AdMob):
            proj.AddBuildProperty(target, "CLANG_ENABLE_MODULES", "YES");
            proj.AddBuildProperty(target, "OTHER_LDFLAGS", "$(inherited)");

            File.WriteAllText(projPath, proj.WriteToString());
        }
    }
}
```
I set up on unity cloud setting in "Advanced Options" section:
Post-Export Method	XcodeProjectModifer.OnPostprocessBuildiOS
Custom Defines	UNITY_CLOUD_BUILD

Originally the library "GoogleMobileAds.framework" had such a structure:
Modules\
Versions\
GoogleMobileAds
Headers

After several attempts to build project I extracted from the directory "GoogleMobileAds.framework\Versions\A\" two objects:
Headers\
GoogleMobileAds

And put them directly in "GoogleMobileAds.framework". All anothers files Other files have been deleted.
So I got the structure:
GoogleMobileAds.framework\Headers\
GoogleMobileAds.framework\GoogleMobileAds

After that I got error:
```
[xcode] In file included from /BUILD_PATH/evgeny-onyanov.platformer-2d.default-ios/temp.E6F7XT/Libraries/Plugins/iOS/GADUNativeCustomTemplateAd.m:3:
[xcode] /BUILD_PATH/evgeny-onyanov.platformer-2d.default-ios/temp.E6F7XT/Libraries/Plugins/iOS/GADUNativeCustomTemplateAd.h:4:9: fatal error: module 'GoogleMobileAds' not found
[xcode] @import GoogleMobileAds;
[xcode] 1 error generated.
[xcode] ** ARCHIVE FAILED **
```

**Comment by eonyanov** [comment]
This seems to be a problem on the side of the Unity during the generation of the project. Because when I build a project in Xcode, I ggot the same error that disappears if remove and re-add the plug-in.

**Comment by rampara** [comment]
I'm currently investigating why cloud build aren't working but last post in issue #333 has details on a workaround.
