### ISSUE TITLE
Plugin 3.5.0 nullreference

### ISSUE THREAD

**Issue by Thaflutter** [googleads/googleads-mobile-unity#440]
Hi.

I just updated the plugin for my unity project by deleting the plugins folder, and the googlemobileads folder.

Then i importet the new asset.

That leaves me with this error when requesting an ad (be it banner or interstitial)

NullReferenceException: Object reference not set to an instance of an object
GoogleMobileAds.Api.BannerView..ctor (System.String adUnitId, GoogleMobileAds.Api.AdSize adSize, AdPosition position) (at Assets/Standard Assets/GoogleMobileAds/Api/BannerView.cs:31)
NJAdScript.RequestSmartBanner () (at Assets/Standard Assets/NJAdScript.cs:30)
MenuScript+$Start$156+$.MoveNext () (at Assets/MenuScript.js:214)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

I am running unity 5.5.0f3 on a windows 10, using the latest android sdk (which might be the problem?)
Problem also happens on a fresh project. 

Any advise?

**Comment by rampara** [comment]
Can you post a code snippet from which you're able to reproduce this error? Can't seem to reproduce it on my end.

**Comment by Thaflutter** [comment]
Hi and thank you for your reply.

I tried a new project, with only the code snippet from the documentation:

```
// Create a 320x50 banner at the top of the screen.
    BannerView bannerView = new BannerView(adUnitId, AdSize.Banner, AdPosition.Top);
    // Create an empty ad request.
    AdRequest request = new AdRequest.Builder().Build();
    // Load the banner with the request.
    bannerView.LoadAd(request);

```
Even this gives me the error.

Thats why i think it might be an SDK thing.

**Comment by rampara** [comment]
Is the `GoogleMobileAdsClientFactory.cs` file present in your project at the `Assets/GoogleMobileAds/Platforms/` directory of your project? Does the state of that file match the latest version in the [repo](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Platforms/GoogleMobileAdsClientFactory.cs)?

**Comment by rampara** [comment]
Glad you were able to get the bottom of your problem.
