### ISSUE TITLE
Native ad not showing

### ISSUE THREAD

**Issue by hkk007** [googleads/googleads-mobile-unity#441]
i just build and run the unity admob sample. 
native ads not showing. all other ads are working 
i am tested on android 
why native ad is not working ?

**Comment by hkk007** [comment]
i build hello world sample

**Comment by hkk007** [comment]
i got worked. size of the add in admob same ad in game then it will work.

**Comment by rampara** [comment]
@hkk007 has your issue been resolved ?

**Comment by hkk007** [comment]
yeah. it working when i change the width and height of the ad in my code.

**Comment by rampara** [comment]
Glad you were able to resolve your issue.
