### ISSUE TITLE
Admob never deleted cached videos, "al" folder keeps inflating

### ISSUE THREAD

**Issue by icyh4mmer** [googleads/googleads-mobile-unity#444]
I noticed the "al" folder where the ads are cached. Do I have to delete this folder each time user exits the app manually, since they are never deleted by the plugin.

**Comment by rampara** [comment]
I'm not familiar with this folder and any files the GMA SDK caches on device should be removed automatically when they are no longer needed or when the total size of cached files exceeds a certain value. Are you using mediation? Third party SDKs may also be caching files.

**Comment by icyh4mmer** [comment]
Yes, I'm using mediation for 4 other providers.

**Comment by rampara** [comment]
Can you check if the files are still cached in the same location when using an ad unit that is not set up for mediation?

**Comment by icyh4mmer** [comment]
I'll check it out and I'll let you know.

**Comment by rampara** [comment]
Will continue investigating once you get back to me.

**Comment by rampara** [comment]
Closing issue due to it's age. Please re-open if this issue persists for you.
