### ISSUE TITLE
Unknown type name GADUTypeNativeCustomTemplateAdClientRef 

### ISSUE THREAD

**Issue by Bestlis** [googleads/googleads-mobile-unity#450]
While compiling I get error:
Unknown type name GADUTypeNativeCustomTemplateAdClientRef: did you mean GADUTypeNativeCustomTemplateAd

Also 
Unknown type name GADUTypeNativeCustomTemplateAd

I use Unity 5.6.1f1 and xCode 7.3.1

What am I doing wrong?

**Comment by Bestlis** [comment]
Solved!

I updated plugin but didn't delete old files.

**Comment by rampara** [comment]
@Bestlis Glad you were able to resolve your issue.
