### ISSUE TITLE
Banner in wrong position after closing

### ISSUE THREAD

**Issue by halgurdh** [googleads/googleads-mobile-unity#451]
```
private void Start()
{
#if UNITY_ENGINE
#elif UNITY_ANDROID
Admob.Instance().showBannerRelative(AdSize.SmartBanner, AdPosition.BOTTOM_CENTER, 0);
#endif
}
```
First time opening it works and the banner shows in the bottom center of the screen.
after closing and re opening the game it reappears slightly below visible screen (Samsung s6).
I know it's below the screen, because when I press the "show all apps" button it reappears for a second and the disappears again.

How can I fix this? I want the banner to stay in initial position after reopening app.

Thank you.

**Comment by rampara** [comment]
@halgurdh are you using the plugin from this repository as is or have you forked this plugin? The code snippet you provided doesn't seem to match up with this plugin.

**Comment by rampara** [comment]
Closing due to non-response. Please re-open if this issue persists for you.
