### ISSUE TITLE
Video Ads not showing, delegates not being called

### ISSUE THREAD

**Issue by timendez** [googleads/googleads-mobile-unity#454]
Hi there, I've been racking my brain about this for 2 days now. I've implemented Unity ads just fine but they don't work on Amazon, so I've decided to switch over to Admob.

Doesn't matter if it's in the editor or built for Android, the ads don't show and the delegates aren't called.

``` C#
using GoogleMobileAds.Api;
using GoogleMobileAds;

public class AdController : MonoBehaviour {
  private RewardBasedVideoAd rewardBasedVideo;

  void Start() {
    rewardBasedVideo = RewardBasedVideoAd.Instance;
    rewardBasedVideo.OnAdLoaded += HandleRewardBasedVideoLoaded;
    rewardBasedVideo.OnAdFailedToLoad += HandleRewardBasedVideoFailedToLoad;
    // rewardBasedVideo.OnAdOpening += HandleRewardBasedVideoOpened;
    rewardBasedVideo.OnAdStarted += HandleRewardBasedVideoStarted;
    rewardBasedVideo.OnAdRewarded += HandleRewardBasedVideoRewarded;
    rewardBasedVideo.OnAdClosed += HandleRewardBasedVideoClosed;
  }
  
  public void ShowRewardedAd() {
//    // Admob
//    #if UNITY_EDITOR
//    string adUnitId = "unused";
//    #elif UNITY_ANDROID
//    string adUnitId = "{REDACTED FOR ISSUE}";
//    #elif UNITY_IPHONE
//    string adUnitId = "{REDACTED FOR ISSUE}";
//    #else
//    LoadUnityAd();
//    return;
//    #endif
    string adUnitId = "unused";

    AdRequest request = new AdRequest.Builder().AddTestDevice(AdRequest.TestDeviceSimulator).Build();

    this.rewardBasedVideo.LoadAd(request, adUnitId);
    if (rewardBasedVideo.IsLoaded()) {
      Debug.Log("is loaded"); // prints
      rewardBasedVideo.Show();
    }
  }

  
  // It doesn't matter if it's just EventArgs or TEventArgs, I was just trying everything at this point
  private void HandleRewardBasedVideoLoaded<TEventArgs>(object sender, TEventArgs e) {
    // Never prints
    Debug.Log("My Video loaded!!!");
  }

  private void HandleRewardBasedVideoFailedToLoad(object sender, AdFailedToLoadEventArgs e) {
    // Never prints
    Debug.Log("MY VIDEO Failed to load!");
    LoadUnityAd();
  }

  private void HandleRewardBasedVideoStarted(object sender, EventArgs e) {
    // Never prints
    Debug.Log("MY VIDEO STARTED");
  }

  private void HandleRewardBasedVideoRewarded(object sender, Reward args) {
    // Never prints
    Debug.Log("reward!");
    AdWatched();
  }

  private void HandleRewardBasedVideoClosed(object sender, System.EventArgs e) {
    // Never prints
    Debug.Log("closed!");
    AdSkipped();
  }
```

Please help, I've been dying trying to figure it out.

**Comment by rampara** [comment]
@timendez are you running into the same issue when running the HelloWorld sample app from this repo?

**Comment by timendez** [comment]
@rampara yes I have the same issue. I only get `Dummy LoadAd` and `Dummy IsLoaded` and `Dummy ShowRewardBasedVideoAd`. No prints that I put in the handlers fire.

I am using Unity 5.6.1f1

**Comment by rampara** [comment]
Can you post the content in logcat under the `Ads` and `Unity` tags for Android when attempting to load and display an ad?

**Comment by TheMostWonderful** [comment]
I think you are requesting and loading video add in same method, it takes some time to load video ads, therefore it better to call load video add in start method and show it later in the game by using other method, below I provide sample code which I am using works fine in my project. 


using System.Collections;
using System.Collections.Generic;
using System;
using UnityEngine;
using GoogleMobileAds;
using GoogleMobileAds.Api;

public class AdManager : MonoBehaviour {

public RewardBasedVideoAd rewardBasedVideoAd;
private InterstitialAd fullAdmob;

private bool rewardBasedEventHandlersSet = false;
// reward initialized
public int scoreAmount = 100;

// Use this for initialization

void Start () {
//loading both rewarded and interstitial ads in start.
	LoadRewardBasedAd ();
	RequestFull ();
}

// Update is called once per frame
void Update () {
	
}

public void LoadRewardBasedAd (){
	#if UNITY_EDITOR
	string adUnitId = "unused";
	#elif UNITY_ANDROID
	//Production
	//string adUnitId = "ca-app-pub-5630039207485482/776643xxxx";
	//Test
	string adUnitId = "ca-app-pub-3940256099942544/522435xxxx";
	#elif UNITY_IPHONE
	string adUnitId = "ca-app-pub-5630039207485482/367430xxxx";
	#else
	string adUnitId = "unexpected_platform";
	#endif

	rewardBasedVideoAd = RewardBasedVideoAd.Instance;

	//Production
	AdRequest adRequest = new AdRequest.Builder ().Build ();

	//Test
	//AdRequest adRequest = new AdRequest.Builder()
	//.AddTestDevice(AdRequest.TestDeviceSimulator)       // Simulator.
	//.AddTestDevice("c78b1468accb7ee846fa4f8e61bde0ff")  // My test device.
	//.Build();


	//Load ad
	rewardBasedVideoAd.LoadAd(adRequest, adUnitId);

	if (!rewardBasedEventHandlersSet) {
	rewardBasedVideoAd.OnAdLoaded += HandleOnAdLoaded;
	rewardBasedVideoAd.OnAdFailedToLoad += HandleOnAdFailedToLoad;
	rewardBasedVideoAd.OnAdOpening += HandleOnAdOpening;
	rewardBasedVideoAd.OnAdStarted += HandleOnAdStarted;
	// is closed.
	rewardBasedVideoAd.OnAdClosed += HandleOnAdClosed;
	// has rewarded the user.
	rewardBasedVideoAd.OnAdRewarded += HandleOnAdRewarded;
	// is leaving the application.
	rewardBasedVideoAd.OnAdLeavingApplication += HandleOnAdLeavingApplication;
	rewardBasedEventHandlersSet = true;
	}
}

	void RequestFull(){
	//Production
	//string idFull = "ca-app-pub-5630039207485482/754534xxxx";
	//Test
	string idFull = "ca-app-pub-3940256099942544/103317xxxx";
	fullAdmob = new InterstitialAd (idFull);
	AdRequest adRequest = new AdRequest.Builder ().Build ();
	fullAdmob.LoadAd (adRequest);
	}


	public void HandleOnAdLoaded(object sender, EventArgs args){

	}
	public void HandleOnAdFailedToLoad(object sender, AdFailedToLoadEventArgs args){
	LoadRewardBasedAd ();
	}
	public void HandleOnAdOpening(object sender, EventArgs args){

	}
	public void HandleOnAdStarted(object sender, EventArgs args){

	}
	public void HandleOnAdRewarded (object sender, Reward args){
	// do your reward here	
	LevelManager refs = GameObject.Find ("LevelManager").GetComponent<LevelManager> ();
	refs.IncreaseScore (scoreAmount);

	}
	public void HandleOnAdClosed(object sender, EventArgs args){
	LoadRewardBasedAd ();

	}
	public void HandleOnAdLeavingApplication (object sender,EventArgs args){


	}

	public void ShowRewardBasedAd (){
	if (rewardBasedVideoAd.IsLoaded ()) {
		rewardBasedVideoAd.Show ();

	} else {
		LoadRewardBasedAd ();
	}
}
	public void ShowFullAds(){
	if (fullAdmob.IsLoaded ()) {
		fullAdmob.Show ();
		RequestFull ();
		}  else {
			RequestFull ();
		}
	}
}

**Comment by snoozinsquatch** [comment]
The events are not called in the dummy client if you look at the source

**Comment by rampara** [comment]
+1 to @snoozinsquatch comment that your handlers will only work as expected when deploying to iOS or Android.

**Comment by oc2pcoj** [comment]
`07-19 22:44:35.700 19134 19134 I Unity   : (Filename: ./artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
07-19 22:44:35.700 19134 19134 I Unity   : 
07-19 22:44:35.700 19134 19134 E Unity   : TrySetSetString can only be called from the main thread.
07-19 22:44:35.700 19134 19134 E Unity   : Constructors and field initializers will be executed from the loading thread when loading a scene.
07-19 22:44:35.700 19134 19134 E Unity   : Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
07-19 22:44:35.700 19134 19134 E Unity   :  
07-19 22:44:35.700 19134 19134 E Unity   : (Filename: ./Runtime/Scripting/ScriptingThreadAndSerializationSafeCheck.cpp Line: 81)
07-19 22:44:35.700 19134 19134 E Unity   : 
07-19 22:44:35.821 19134 19134 I Unity   : UnityException: TrySetSetString can only be called from the main thread.
07-19 22:44:35.821 19134 19134 I Unity   : Constructors and field initializers will be executed from the loading thread when loading a scene.
07-19 22:44:35.821 19134 19134 I Unity   : Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
07-19 22:44:35.821 19134 19134 I Unity   : 
07-19 22:44:35.821 19134 19134 I Unity   : Rethrow as TargetInvocationException: GoogleMobileAds.Android.RewardBasedVideoAdClient.onAdRewarded(System.String,System.Single)
07-19 22:44:35.821 19134 19134 I Unity   :   at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
07-19 22:44:35.821 19134 19134 I Unity   :   at UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, IntPtr jmethodName, IntPtr jargs) [0x00000] in <filename unknown>:0 
07-19 22:44:35.821 19134 19134 I Unity   :  
07-19 22:44:35.821 19134 19134 I Unity   : (Filename: currently not available on il2cpp Line: -1)`

**Comment by oc2pcoj** [comment]
Callbacks crash with these errors: https://pastebin.com/QusRLevy 
Fuck up with threading.

**Comment by rampara** [comment]
@oc2pcoj on Android, ad event handlers are not invoked on the main thread. This [blog post](http://googleadsdeveloper.blogspot.com/2016/04/handling-android-ad-events-in-unity.html) goes into more detail.

**Comment by rampara** [comment]
Closing due to lack of response from original poster.

**Comment by timendez** [comment]
I gave up, sorry
