### ISSUE TITLE
Callbacks not being called after Scene RELOADS 

### ISSUE THREAD

**Issue by Pacifist94** [googleads/googleads-mobile-unity#455]
@rampara Thank you for your time answering these questions, Now I know what the issue is.... 
But i still can't figure out how to solve it.... 

The plug-in works fine, and its firing the call backs correctly,  I requested many ads, and all of them are calling the events without a problem :)

The ISSUE is when the scene RELOADS example("SceneManager.LoadScene(0);")
after that the plugin will still show ads but is IT WON'T trigger any events such as 

OnAdLoaded
OnAdFailedToLoad 
OnAdOpening
OnAdStarted 
OnAdRewarded
OnAdClosed
OnAdLeavingApplication

These is probably because when you RELOAD the Scene, it creates another **Instance** of the Singleton (RewardBasedVideoAd.Instance)  and this new instance doesnt have the Events assigned.

If you find the answer could you tell us how to overcome this issue... 

I will upload the HelloWorld example that replicates this problem,
1. Build the apk and install it on your Device..
2. Request a couple of RewardedVideoAds add and you will see that Events are being called
3. Reload the Scene,  and Requet a new RewardedVideoAds,  ads will show up, but no event callbacks...

Here is the HelloWorldExample: 
https://mega.nz/#!0NMAGKzS!AUVJncYIAGuxPmvcZUsGSLntli_7_qOByGorRdUwX4A

Thanks in advance

**Comment by Pacifist94** [comment]
No issues now!

**Comment by rampara** [comment]
@Pacifist94 glad to hear your issue has been resolved.
