### ISSUE TITLE
Unity Admob 3.5.0 Rewarded Video not Working 

### ISSUE THREAD

**Issue by Tehnorg** [googleads/googleads-mobile-unity#456]
Hello everyone.
I have problem with integrated Admob Ads 3.5.0 on Ios Unity 5,4,3,  Xcode 8.3.3, Ios 10+.

My Integration code

    rewardBasedVideo = RewardBasedVideoAd.Instance;
    AdRequest request = new AdRequest.Builder().Build();
    rewardBasedVideo.LoadAd(request, adUnitID);

On that moment i have crash with that message 

    ibc++abi.dylib: terminating with uncaught exception of type Il2CppExceptionWrapper

my rewarded code is ca-app-pub-8469841583385574/3990948048

thx for help.

**Comment by rampara** [comment]
@Tehnorg I'm having trouble reproducing this crash. Are you able to reproduce this issue with the HelloWorld sample app in this repo?

**Comment by rampara** [comment]
Closing due to non-response. Please re-open if this issue persists for you.
