### ISSUE TITLE
Strange behaviour of rewarded video

### ISSUE THREAD

**Issue by dpershin** [googleads/googleads-mobile-unity#458]
Hi everyone, 

I've faced a strange bug in 3.5.0. Here are reproduction steps:

1. Download and install 3.5.0 package for Unity
2. Build and run HelloWorld project from the repo
3. Press Request Rewarded Video
4. Wait 3-5 seconds
5. Press Show Rewarded Video
6. The video starts playing but with some UI bugs:
6.1 No sound control button
6.2 Video is displayed in landscape layout though UI is in portrait layout
6.3 No download button and no any reaction on tapping on the screen
6.4 When video ends the counter freezes at 1 second
6.5 You can scroll video horizontally/vertically

I tested the very same project with 3.4.0 and it worked perfectly. My environment is:
 - Unity 5.5.4f1
 - Google Play Services 10.2.4 and 11.0.0 (same behavior)
 - Nexus 5 as a phone
 - Internal Build System (not Gradle, it won't work with Gradle build btw)

Here is the screenshot of this:![screenshot_20170708-024956](https://user-images.githubusercontent.com/21357218/27974497-6449184c-6388-11e7-9f30-90c04f58656e.png)

I hope it will help to fix the issue. Thank you!

**Comment by rampara** [comment]
@dpershin is this issue consistently reproducible for you? I'm having trouble reproducing it on my end.

**Comment by dpershin** [comment]
@rampara Thank you for the answer! 

Unfortunately, yes. I dug deeper and find out that I have the very same behavior with just very simple AdMob app (example from here: https://github.com/googleads/googleads-mobile-android-examples). I downloaded the example, run it and saw the same issue. I literally didn't change anything. 

I have tried it on two different PCs and on two different phones, today I will try it on more phones. I will let you know about results. 

PS. By the way, did you turn on the portrait mode in the settings of Unity project?

**Comment by dpershin** [comment]
Interesting, I've tested on BLU Advanced (Android 5.1) and DOOGEE X5 (Android 5.1) and everything works perfectly. But on my Nexus 5 (Android 6.0.1) I'm still having the problem with incorrect UI in portrait mode.

**Comment by rampara** [comment]
@dpershin since you're able to reproduce this on a standard android app, the issue doesn't seem specific to this Unity plugin. I would recommend you reach out on the [Google Mobile Ads SDK Technical Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).

**Comment by dpershin** [comment]
@rampara That is fair enough, so, I think, we can close the issue. Thank you!
