### ISSUE TITLE
Open source error

### ISSUE THREAD

**Issue by koljanich** [googleads/googleads-mobile-unity#459]
Hello! Please tell me how open this source. Android studio 2.1.2 show missing files (2). Eclipse compile, but after integrate to Unity and build total project show error convert classes to dex format.

**Comment by rampara** [comment]
@koljanich I'm not sure what you mean by open this source. What are you trying to accomplish?

**Comment by koljanich** [comment]
@rampara I mean open in Android Studio and build.

**Comment by koljanich** [comment]
I try to open Source in Android Studio and build it. And I get 
Error:
>  Gradle sync failed: CreateProcess error=2, File could not be found
    Consult IDE log for more details (Help | Show Log)

I don't understand this error - what file? Name of file? Nothing!

**Comment by koljanich** [comment]
The problem is open GitHub source in Studio. When I open as GitHub this error is gone, but found other 21 errors: 

> Error:(5, 34) java: package com.google.android.gms.ads does not exist
Error:(6, 34) java: package com.google.android.gms.ads does not exist
Error:(7, 34) java: package com.google.android.gms.ads does not exist
Error:(8, 34) java: package com.google.android.gms.ads does not exist
Error:(30, 11) java: cannot find symbol
  symbol:   class AdView
  location: class com.google.unity.ads.Banner
Error:(56, 54) java: cannot find symbol
  symbol:   class AdSize
  location: class com.google.unity.ads.Banner
Error:(125, 28) java: cannot find symbol
  symbol:   class AdRequest
  location: class com.google.unity.ads.Banner
Error:(60, 22) java: cannot find symbol
  symbol: class AdView
Error:(65, 34) java: cannot find symbol
  symbol: class AdListener

**Comment by koljanich** [comment]
The problem is open GitHub source in Studio. When I open as GitHub this error is gone, but found other 21 errors (Google Play Services are integrated): 

> Error:(5, 34) java: package com.google.android.gms.ads does not exist
Error:(6, 34) java: package com.google.android.gms.ads does not exist
Error:(7, 34) java: package com.google.android.gms.ads does not exist
Error:(8, 34) java: package com.google.android.gms.ads does not exist
Error:(30, 11) java: cannot find symbol
  symbol:   class AdView
  location: class com.google.unity.ads.Banner
Error:(56, 54) java: cannot find symbol
  symbol:   class AdSize
  location: class com.google.unity.ads.Banner
Error:(125, 28) java: cannot find symbol
  symbol:   class AdRequest
  location: class com.google.unity.ads.Banner
Error:(60, 22) java: cannot find symbol
  symbol: class AdView
Error:(65, 34) java: cannot find symbol
  symbol: class AdListener

**Comment by rampara** [comment]
Are you trying to build the android-library component of this plugin in Android Studio or are you trying to build a Unity app (generated by Unity) in Android Studio?

**Comment by koljanich** [comment]
@rampara Yes, I try to build the android-library component of this plugin in Android Studio

**Comment by rampara** [comment]
@koljanich have you modified the source in any way? I don't seem to be having any issues building the project and/or generating a library JAR. Can you link me to a project that doesn't build for you?

**Comment by koljanich** [comment]
I have not yet modified the source code. I was just trying to compile the library. Here is a clone of the GitHub project: https://github.com/koljanich/googleads-mobile-plugins  https://github.com/koljanich/AdmobUnity
In both clones of git I have an error: 

> Error:(70, 0) Process 'command 'git'' finished with non-zero exit value 128
<a href="openFile:C:\Docs\AndroidProj\googleads-mobile-unity-master\build.gradle">Open File</a>

This error generates if I build from AndroidStudio or if I build from gradlew.bat
The errors 
> Error:(5, 34) java: package com.google.android.gms.ads does not exist
show when I try to open GitHub project local. But I fixed it by choosing Android API 25 in project settings. Now I open local project from GitHub:
Unzip googleads-mobile-unity-master.zip to folder, open in Studio existing Android Studio Project, Choose folder googleads-mobile-unity-master. When open project in Studio found warning:

> Unregistered VCS root detected
		The directory C:\Docs\AndroidProj\googleads-mobile-unity-master\temp\jarresolver is under Git, but is not registered in the Settings.
		Add root  Configure  Ignore

I click Add root. After I click Build->Make Module... And nothing! Serach in all directories of project - no unity-plugin-library.jar files found!

**Comment by rampara** [comment]
Closing due to non-response. Please re-open if this issue persists for you.
