### ISSUE TITLE
Native Ads Problems and Doubts

### ISSUE THREAD

**Issue by BaltaKid** [googleads/googleads-mobile-unity#461]
Hello,
I'm trying yo implement the native ads but i can only get the example working with 2 image and the main text.

The plan is convert all data from the ad to a bunch of game object so i can put it inside a scroll, etc.

But i'm having a lot of problems knowing all the assets name (args.nativeAd.GetAvailableAssetNames())

and when i change this data to my values in the log cat appears Internal error.

public const string AdUnitId = "ca-app-pub-******************/******************";
public const string TemplateId = "S002";

Sorry about my bad english.
Best Regards.

**Comment by rampara** [comment]
@BaltaKid can you post the error you're are seeing in logcat, code snippet, and steps indicating how to reproduce the error.

**Comment by BaltaKid** [comment]
Hello @rampara here is the log cat and code example.
Log Cat Error:
(Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
07-13 10:42:49.698 11671-11671/? I/Unity: ----->>> Ad Loader fail event received with message: Internal error
```
//  A test ad unit for custom native template ads.
    public const string AdUnitId = "ca-app-pub-********/##########";
    public const string TemplateId = "S002";

   private void RequestNativeAd()
   {

      AdLoader adLoader = new AdLoader.Builder(AdUnitId)
          .ForCustomNativeAd(TemplateId)
  			 .Build();

  	 adLoader.OnCustomNativeTemplateAdLoaded += this.HandleCustomNativeAdLoaded;
  	 adLoader.OnAdFailedToLoad += this.HandleNativeAdFailedToLoad;

	   adLoader.LoadAd(new AdRequest.Builder().Build());
   }

   private void HandleCustomNativeAdLoaded(object sender, CustomNativeEventArgs args)
   {
      int i = 0;

      foreach(string name in args.nativeAd.GetAvailableAssetNames())
      {
          i++;
          Debug.Log("----->> Name Of Assets " + i + " = " + name + "<<-------");
      }
   }

   private void HandleNativeAdFailedToLoad(object sender, AdFailedToLoadEventArgs args)
   {

      Debug.Log("----->>> Ad Loader fail event received with message: " + args.Message);
   }

   ```

**Comment by rampara** [comment]
@BaltaKid can you provide me with the ad unit you're attempting to load ads from?

**Comment by BaltaKid** [comment]
Hello @rampara yes i can

Android: Ad unit ID: ca-app-pub-5739411022712118/8255787189
               Template: S002

iOS i'm waiting to put the android working :-)

I have put the template, but i want to create my google ads inside the app/game so i can put it inside a TV or a scroll(inside a gameobject).

Best Regards.

**Comment by rampara** [comment]
@BaltaKid the ad unit you posted is for a native express ad while the code snippet you posted is for a custom native template ad. To request and display native express ads, you should follow the instructions on our [developer docs](https://developers.google.com/admob/unity/native-express).

**Comment by BaltaKid** [comment]
Hello @rampara, thanks for your help.

To resume;
Problem: i'm trying to create a custom native template ad with the Id's of admob native express ad.
Solution: Register in DoubleClick get the ad unity and template and use the previous code to build my own ads.

Best Regards.

**Comment by rampara** [comment]
@BaltaKid as it seems your issue seems to have resolved, I'm closing this issue. Please reopen if that's not the case.
