### ISSUE TITLE
Only test ad unit ID works on android, everything fine on iOS

### ISSUE THREAD

**Issue by diabeticraptor** [googleads/googleads-mobile-unity#462]
I can request test ads fine, they show up and everything is good

Whenever I put my ad unit id in nothing shows up on any android device, ios build works fine

Any ideas what could be going wrong?

**Comment by coldev** [comment]
the same error ... android not show store ads  ... 

banner and intertial not show...

**Comment by rampara** [comment]
@diabeticraptor @coldev for which ad format are you running into this issue. Can you post the ad units you are unable to load ads from?

**Comment by diabeticraptor** [comment]
@rampara 
I'm using Banner Ads, Intersitial, and Rewarded videos, all fail to load but they work on iOS,

the ad unit ids that work for me are the ones from the unity example:

Banner: ca-app-pub-3940256099942544/6300978111
Intersitial: ca-app-pub-3940256099942544/1033173712
Reward Video: ca-app-pub-3940256099942544/5224354917

The ones to fail to load:
Banner: ca-app-pub-4731064129895917/8996888988
Intersitial: ca-app-pub-4731064129895917/2950355382
Video: ca-app-pub-4731064129895917/4484134186

**Comment by rampara** [comment]
@diabeticraptor I'm able to load banner ads from ca-app-pub-4731064129895917/8996888988 without issue. What error code are you receiving when the ads fail to load? Can you provide me a test app that reproduces this issue?

**Comment by diabeticraptor** [comment]
Hm, it loaded one interstitial and then hasn't loaded another one since.

Could it be an internet connection issue? My internet is kinda dooty, wouldnt really explain why ios is working though
