### ISSUE TITLE
Unity cloud build library not found error on ios

### ISSUE THREAD

**Issue by EtienneCollard** [googleads/googleads-mobile-unity#463]
So i start a new project with unity 2017.1 and add the GoogleMobileAds plugin and put that on collaborate and start a build for ios.

The build failed and that error was in the log:
[xcode] ld: library not found for -lPods-Unity-iPhone
[xcode] clang: error: linker command failed with exit code 1 (use -v to see invocation)

I also have these error when building from xcode
![capture](https://user-images.githubusercontent.com/11469647/28194010-420ca0ec-680f-11e7-9854-dd609ac05304.PNG)

**Comment by rampara** [comment]
This issue is currently being worked on. For the time being you can find workarounds to get Unity Cloud build working at #333.

**Comment by petersuwara** [comment]
@rampara any idea of a release date ? Likely we'll just move on to Jenkins until this is resolved. Thanks.
