### ISSUE TITLE
Rewardbasead callbacks not working help

### ISSUE THREAD

**Issue by martythegreat** [googleads/googleads-mobile-unity#464]
I have a  playad button that after the videoad plays it will revive the player, I tried implementing rewarded ads but thecall backs seem to be not working

**Comment by rampara** [comment]
@martythegreat are you running into this issue on iOS or Android? Have you tried reproducing this issue in the HelloWorld sample app from this repo?

**Comment by oc2pcoj** [comment]
https://gamedev.stackexchange.com/questions/141040/unity-admob-plugin-rewarding-the-user-on-the-main-thread

**Comment by rampara** [comment]
@martythegreat if the issue you're running into is the same one described in link from @oc2pcoj, you may also find this [blog post](http://googleadsdeveloper.blogspot.com/2016/04/handling-android-ad-events-in-unity.html) useful.

**Comment by rampara** [comment]
Closing this issue due to its age and non response from original poster.
