### ISSUE TITLE
Admob tgkill Crash on Unity Game

### ISSUE THREAD

**Issue by demirersin** [googleads/googleads-mobile-unity#466]
We are developed game using Unity & Admob. We got too many crashes. 

When I kill app on focus-out , Game is crashed (not all time. It is hard to reproduce)

Stack Trace :

    Caused by java.lang.Error: signal 6 (SIGABRT), code -6 (?), fault addr --------
    Build fingerprint: 'samsung/dreamltexx/dreamlte:7.0/NRD90M/G950FXXU1AQF7:user/release-keys'
    Revision: '10'
    
    at libc.tgkill(tgkill:12)
           at libc.pthread_kill(pthread_kill:34)
           at libc.raise(raise:10)
           at libc.__libc_android_abort(__libc_android_abort:34)
           at libc.abort(abort:4)
           at libc.abort(abort:4)
           at libc.abort(abort:4)
           at libc.abort(abort:4)
           at libc.abort(abort:4)
           at libc.abort(abort:4)
           at libc.abort(abort:4)
           at libc.abort(abort:4)
           at libc.abort(abort:4)

Tools and SDK versions :

    Unity 5.5.3f1
    Admob 3.4.0
    Google Play Services 10.2.0
    	play-services-ads-lite-10.2.0
    	play-services-base-10.2.0
    	play-services-basement-10.2.0
    	play-services-gcm-10.2.0
    	play-services-iid-10.2.0
    	
    Game On Focus : 99% Not Focus , 1% Focus
    Operating System : 97% Android 7.x

How can we fix it ?

**Comment by rampara** [comment]
@demirersin what is pointing you towards the GMA SDK or GMA Unity plugin being responsible for the crash? The stack trace you provided doesn't give much information on the cause of the crash.

**Comment by demirersin** [comment]
I known I dont have enough info about it. But I can say that when I remove admob operations , I did not get any crash.

**Comment by rampara** [comment]
Can you provide a test app or steps I can follow to reproduce the crash?

**Comment by tienhagioi** [comment]
demirersin   could you tell me how to fix this problem ? Thanks !
