### ISSUE TITLE
Mediation networks doesn't work

### ISSUE THREAD

**Issue by fazol** [googleads/googleads-mobile-unity#467]
Hi, I have a problem with Admob mediation. 
I am using Applovin, Adcolony and Unity ads. I downloaded SDKs and adapters, they are in plugins/android folder. The problem is that I can see only Admob ads. I have tried to set manually high ecpm like 100$ and still nothing. In Logcat I don't see anything wrong. How can I check that adapters are working? Or if it is network problems?

**Comment by rampara** [comment]
@fazol what content do you see in logact under the `Ads` tag?

**Comment by rampara** [comment]
Closing this issue due to non-response.
