### ISSUE TITLE
iOS Simulator getting real ads

### ISSUE THREAD

**Issue by absrndm** [googleads/googleads-mobile-unity#468]
Hi, I'm trying to get test ads running my app with the iphone simulator but I keep getting real ads.

This is my Ad request:

string testDeviceiOS = AdRequest.TestDeviceSimulator; //IOS SIMULATOR
...
AdRequest request = new AdRequest.Builder().AddTestDevice(testDeviceiOS).Build();

If i check request.TestDevices I can see that the id is "SIMULATOR".

This is happening with version 3.5.0 and 3.6.1 as well

**Comment by ArmandCloud** [comment]
Same here 3.6.1

**Comment by rampara** [comment]
This is a bug is the GMA Unity plugin. Thanks for bringing this to our attention. Will be pushing a fix shortly.

**Comment by rampara** [comment]
This issue has been resolved in the latest release of the plugin (v3.6.3).
