### ISSUE TITLE
AdMob banners are not shown

### ISSUE THREAD

**Issue by SamuraiCoder** [googleads/googleads-mobile-unity#469]
Hi, 

I´m trying to implement banners in a Unity project. 

It worked before, but suddenly did not work. I dunno why.

Some perspective:

The ClientResolver always forces to put 10.2.0.aar libraries but I got some 10.2.1 and was conflicting when generating the apk.

I have now all of this *.aar and now I can deploy my project. No errors or warnings whatsoever. 

In my code I call a banner in this way:

AdsManager.SINGLETON.ShowBannerAdMob(AdPosition.Bottom, AdSize.Banner);

And in that singleton, I use it in this way:

    public void ShowBannerAdMob(AdPosition bannerPos, AdSize bannerSize)
    {
#if UNITY_IOS
        bannerView = new BannerView(banner_IOS, bannerSize, bannerPos);
#elif UNITY_ANDROID
        DEBUG.Log("[AdsManager] Init showBanner....");
        bannerView = new BannerView(banner_Android, bannerSize, bannerPos);
#else
     
       return;
#endif
        DEBUG.Log("[AdsManager] ShowBannerAdMob....");
        AdRequest request = new AdRequest.Builder().Build();
        bannerView.LoadAd(request);

        bannerView.OnAdLoaded += HandleOnBannerLoaded;
        DEBUG.Log("[AdsManager] ShowBannerAdMob FIN....");
    }

In HandleOnBannerLoaded I just do bannerView.Show() but I tried without it and is not working either.

I have a window when I display all the messages in DEBUG.Log so with all the execution I just only see this:

  DEBUG.Log("[AdsManager] Init showBanner....");

But not afterwards.

So I´m assuming the new BannerView(banner_Android, bannerSize, bannerPos); is not working nicely but I cannot tell why. 

 Type googleMobileAdsClientFactory = Type.GetType(
                "GoogleMobileAds.GoogleMobileAdsClientFactory,Assembly-CSharp");

This it´s called in this constructor, so I guess I don´t have the assemblies to work with Ads but I imported the latest project and created everything in AdMob. 

Please, some help!

**Comment by rampara** [comment]
@SamuraiCoder do you see any content in logcat under the `Ads` tag that might indicate why banner ads are not working correctly for you?

**Comment by rampara** [comment]
Closing issue due to non-response.
