### ISSUE TITLE
First ads show welll, not the next one.

### ISSUE THREAD

**Issue by Honikou** [googleads/googleads-mobile-unity#471]
`
 if (rewardBasedVideo.IsLoaded())
        {
            rewardBasedVideo.Show();
            RequestRewardBasedVideo();
        }
`
That is my last setup, I also try to move RequestRewardBasedVideo on :
rewardBasedVideo.OnAdRewarded
rewardBasedVideo.OnAdClosed

The next time I try to show ads here is the problem
rewardBasedVideo.IsLoaded() is True.
BUT
07-31 11:00:48.936: W/AdsUnity(9483): Reward based video ad is not ready to be shown.

The rewardBasedVideo.Destroy() don't exist, I also try to put rewardBasedVideo = null.

I think the problem came from "rewardBasedVideo.IsLoaded()" once he is true, he will always be true for next video even if the video isn't loaded yet

**Comment by rampara** [comment]
@Honikou are running into this issue with the HelloWorld sample app as well?

**Comment by cgfred** [comment]
Hello!

I have the same issue too with reward based ads. After the first ad is viewed then I see the error in the Android log reader: "Reward based video ad is not ready to be shown." but rewardBasedVideo.IsLoaded() is true. 

The sample also have the same behaviour if you call it a 2nd time during the same runtime session. 

Also at times there is a crash in the ad handler with the following trace:

08-23 23:55:11.815: W/Ads(17820): Could not show rewarded video ad from adapter.
08-23 23:55:11.815: W/Ads(17820): java.lang.NullPointerException
08-23 23:55:11.815: W/Ads(17820): 	at com.google.ads.mediation.AbstractAdViewAdapter.showVideo(:com.google.android.gms.DynamiteModulesA:228)
08-23 23:55:11.815: W/Ads(17820): 	at com.google.android.gms.ads.internal.mediation.client.u.f(:com.google.android.gms.DynamiteModulesA:193)
08-23 23:55:11.815: W/Ads(17820): 	at com.google.android.gms.ads.internal.reward.b.a(:com.google.android.gms.DynamiteModulesA:29)
08-23 23:55:11.815: W/Ads(17820): 	at com.google.android.gms.ads.internal.reward.client.e.onTransact(:com.google.android.gms.DynamiteModulesA:11)
08-23 23:55:11.815: W/Ads(17820): 	at android.os.Binder.transact(Binder.java:361)
08-23 23:55:11.815: W/Ads(17820): 	at com.google.android.gms.internal.zzed.zzb(Unknown Source)
08-23 23:55:11.815: W/Ads(17820): 	at com.google.android.gms.internal.zzaem.show(Unknown Source)
08-23 23:55:11.815: W/Ads(17820): 	at com.google.android.gms.internal.zzaex.show(Unknown Source)
08-23 23:55:11.815: W/Ads(17820): 	at com.google.unity.ads.RewardBasedVideo$3.run(RewardBasedVideo.java:138)
08-23 23:55:11.815: W/Ads(17820): 	at android.os.Handler.handleCallback(Handler.java:733)
08-23 23:55:11.815: W/Ads(17820): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-23 23:55:11.815: W/Ads(17820): 	at android.os.Looper.loop(Looper.java:146)
08-23 23:55:11.815: W/Ads(17820): 	at android.app.ActivityThread.main(ActivityThread.java:5635)
08-23 23:55:11.815: W/Ads(17820): 	at java.lang.reflect.Method.invokeNative(Native Method)
08-23 23:55:11.815: W/Ads(17820): 	at java.lang.reflect.Method.invoke(Method.java:515)
08-23 23:55:11.815: W/Ads(17820): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
08-23 23:55:11.815: W/Ads(17820): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
08-23 23:55:11.815: W/Ads(17820): 	at dalvik.system.NativeStart.main(Native Method)
08-23 23:55:11.815: W/Ads(17820): Could not call showVideo.
08-23 23:55:11.815: W/Ads(17820): android.os.RemoteException
08-23 23:55:11.815: W/Ads(17820): 	at com.google.android.gms.ads.internal.mediation.client.u.f(:com.google.android.gms.DynamiteModulesA:197)
08-23 23:55:11.815: W/Ads(17820): 	at com.google.android.gms.ads.internal.reward.b.a(:com.google.android.gms.DynamiteModulesA:29)
08-23 23:55:11.815: W/Ads(17820): 	at com.google.android.gms.ads.internal.reward.client.e.onTransact(:com.google.android.gms.DynamiteModulesA:11)
08-23 23:55:11.815: W/Ads(17820): 	at android.os.Binder.transact(Binder.java:361)
08-23 23:55:11.815: W/Ads(17820): 	at com.google.android.gms.internal.zzed.zzb(Unknown Source)
08-23 23:55:11.815: W/Ads(17820): 	at com.google.android.gms.internal.zzaem.show(Unknown Source)
08-23 23:55:11.815: W/Ads(17820): 	at com.google.android.gms.internal.zzaex.show(Unknown Source)
08-23 23:55:11.815: W/Ads(17820): 	at com.google.unity.ads.RewardBasedVideo$3.run(RewardBasedVideo.java:138)
08-23 23:55:11.815: W/Ads(17820): 	at android.os.Handler.handleCallback(Handler.java:733)
08-23 23:55:11.815: W/Ads(17820): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-23 23:55:11.815: W/Ads(17820): 	at android.os.Looper.loop(Looper.java:146)
08-23 23:55:11.815: W/Ads(17820): 	at android.app.ActivityThread.main(ActivityThread.java:5635)
08-23 23:55:11.815: W/Ads(17820): 	at java.lang.reflect.Method.invokeNative(Native Method)
08-23 23:55:11.815: W/Ads(17820): 	at java.lang.reflect.Method.invoke(Method.java:515)
08-23 23:55:11.815: W/Ads(17820): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
08-23 23:55:11.815: W/Ads(17820): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
08-23 23:55:11.815: W/Ads(17820): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by Baalzamon** [comment]
Hi,

I'm experiencing the exact same problem.

First video runs fine, but the second video won't show unless you restart the app. Funny thing though, this problem only appears on Android devices. Any iOS device using the same code runs fine.

08-25 12:04:27.118 22438 22454 I Unity   : reward video loaded = True
:
08-25 12:04:27.120 22438 22438 W AdsUnity: Reward based video ad is not ready to be shown.

**Comment by Baalzamon** [comment]
@rampara 

I just tested the HelloWorld app from the repository. Without delving deeper into the issue, the HelloWorld works just fine and as expected (it doesn't show the described behaviour).

**Comment by Baalzamon** [comment]
I was able to fix the error. Indeed it was no problem with the plugin, but the execution timing of my code.

I requested the new video in the Rewarded-Callback. The video was loaded correctly, but after that I got a Loaded-Callback, I received a Closed-Callback, when I closed the Ad.

Somehow this sequence of events doesn't play well. I removed the request from the Rewarded-Callback and but it in the Closed-Callback, so they can't interfere with each other.

If you experience a similar problem, maybe this will hint you in the right direction. =)

**Comment by cgfred** [comment]
Hey @Baalzamon thanks for the solution, that solved my problem too. Thanks again!

**Comment by rampara** [comment]
Seems like you've figured out the issue. Ad requests should be made from the OnAdClosed ad event for subsequent ads, not the OnAdRewarded ad event.

**Comment by sushantingle** [comment]
Thank you very much for the solution.
