### ISSUE TITLE
Test Ads shown but Real Ads not shown on iOS real device

### ISSUE THREAD

**Issue by Evsun** [googleads/googleads-mobile-unity#472]
Just tired for searching around from all forum i dig deep and read some manuals, still don't know what happen.
I using AppAdvisory Easy Mobile Ads plugin to create the ads and showing it. On other apps this run smoothly, but on this newest app that i developing now, something goes wrong.
After download the last googleads plugin, i import it to Unity and setting up the ads as usual.
But when run it on iOS (which is exported to xCode), what i get is no ads at all, no ads show up in the screen. But if i change the ad id to a test id, the test ads showing up normally. 
On the log screen of xCode i got nothing related to ads, but this line of log is a catching my eyes, i think there are something that not going well with this but i don't know.

> You are using download over http. Currently unity adds NSAllowsArbitraryLoads to Info.plist to simplify transition, but it will be removed soon. Please consider updating to https.

Please help guys,

**Comment by rampara** [comment]
@Evsun this issue tracker is strictly for issues related to this plugin. The issue seems related to the AppAdvisory Easy Mobile Ads plugin.
