### ISSUE TITLE
Object reference not set to an instance of an object GMobilesAd.RequestRewardBasedVideo ()

### ISSUE THREAD

**Issue by QuanHuynhM** [googleads/googleads-mobile-unity#473]
Hi everyone, I have a problem but I can't solve it. Please help me.
I try to change RequestRewardBasedVideo() from PRIVATE to public and I call it from another file
`    public void RequestRewardBasedVideo()
    {
#if UNITY_EDITOR
        string adUnitId = "unused";
#elif UNITY_ANDROID
        string adUnitId = "ca-app-pub-3940256099942544/5224354917";
#elif UNITY_IPHONE
        string adUnitId = "ca-app-pub-3940256099942544/1712485313";
#else
        string adUnitId = "unexpected_platform";
#endif

        rewardBasedVideo.LoadAd(this.CreateAdRequest(), adUnitId);        
    }`

And

`
 	public GMobilesAd admob;

	void Awake() {
		admob.RequestRewardBasedVideo();
	}`

When I run app with unity

> Object reference not set to an instance of an object GMobilesAd.RequestRewardBasedVideo ()

Please help me. Thanks!

**Comment by rampara** [comment]
@QuanHuynhM if you're modifying the HelloWorld sample app, you should pay attention to the `RewardBasedVideoAd ` object initialization in the `Start()` method of the `GoogleMobileAdsDemoScript ` script.

**Comment by QuanHuynhM** [comment]
@rampara  Can you tell me more details with use `RewardBasedVideoAd ` object initialization in the `Start()`?. Thank you!

**Comment by rampara** [comment]
You can find the code for the `Start()` method I referenced [here](https://github.com/googleads/googleads-mobile-unity/blob/master/samples/HelloWorld/Assets/Scripts/GoogleMobileAdsDemoScript.cs#L21). Our [developer docs](https://developers.google.com/admob/unity/rewarded-video) are also a good resource.
