### ISSUE TITLE
Reward Video only show with APP ID and ID Test.My ID not show?

### ISSUE THREAD

**Issue by ForestJungle** [googleads/googleads-mobile-unity#474]
When I test reward video.I only see the video show with id test default in project Hello World.If I replace my ID and then not show video.

**Comment by rampara** [comment]
@ForestJungle as this issue tracker is only for issues specific to the GMA Unity plugin, I would recommend you reach out on the [Google Mobile Ads SDK Technical Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
