### ISSUE TITLE
Test Ads shown but Real Ads not shown on iOS Device 

### ISSUE THREAD

**Issue by Evsun** [googleads/googleads-mobile-unity#475]
Hello, this actually issues that i have open 2 days ago [here](https://github.com/googleads/googleads-mobile-unity/issues/472) but didn't get any answer and just closed immediately. Lastly @rampara think that this problem because AppAdvisory or Easy Mobile ads plugin in unity that i use. But i think the problem isn't came from that. Because  i have use the plugin for many other apps and working so well. But not for this. 
Also i have got a new message from xCode Log after updating the googleads mobile unity plugin to the latest version, here's the message : 

> Cannot determine request type. Is your ad unit id correct?

I have check and recheck so many times and make sure my ad unit id is  correct. I have use my friends ad unit id also and still have same result. But whenever i use test id, everything goes right and nothing wrong.

Please give me any solution about this, 
Thanks

**Comment by rampara** [comment]
@Evsun are you integrating directly with the AppAdvisory or Easy Mobile ads plugin to display ads or the plugin from this repo?

**Comment by rampara** [comment]
Closing this issue due to non-response.
