### ISSUE TITLE
"The ad content in your app is not consistent with the app's content rating." Child directed problem.

### ISSUE THREAD

**Issue by ArmandCloud** [googleads/googleads-mobile-unity#478]
Hello ,

I am using ".tagForChildDirectedTreatment(true)" when requesting my ads. But my app update submission rejected for showing 13+ ads.

How avoid showing 13+ ads to children under 13 with Admob Unity plugin.
Or what can i do to pass "Designed For Families" ad conditions. 

Best Regards,

**Comment by rampara** [comment]
@ArmandCloud setting `tagForChildDirectedTreatment` to true is not the only thing required to be compliant with the Designed For Families program, as described in this [help center article](https://support.google.com/admob/answer/6223431?hl=en).

**Comment by ArmandCloud** [comment]
Thank you @rampara ,

`AdRequest request = new AdRequest.Builder()
        .AddExtra("is_designed_for_families", "true")
        .TagForChildDirectedTreatment(true)
        .Build();`

I will add this code to my build.

Best Regards,

**Comment by rampara** [comment]
Glad to be of help.
