### ISSUE TITLE
Way higher income then expected

### ISSUE THREAD

**Issue by maxsundell** [googleads/googleads-mobile-unity#482]
So i just released my first android game and it has like basically no active players except me and a friend but somehow the admob admin panel says it has showed over 2400 banner ads and i've gained about 5 dollars. Maybe i'm just being really paranoid and i've actually managed to show that many ads (me and my friend have played a lot after all) i just really don't want to get my account flagged because of some bug.

Here is the code regarding admob:
https://github.com/maxsundell/BlockTapper/blob/master/Scripts/GameManager.cs

Screenshot of Admob:
https://gyazo.com/3b4ecbeeec59f429e83e29c96629c0aa

**Comment by rampara** [comment]
@maxsundell during development and testing of your app, it is important to use [test ads](https://developers.google.com/admob/unity/start#test_ads) to avoid getting your account flagged.

**Comment by maxsundell** [comment]
Yeah I know, but not when it's actually on Google Play right?

**Comment by rampara** [comment]
You can ship your app with your app configured as a test device to avoid this issue.
