### ISSUE TITLE
Problem with folder names

### ISSUE THREAD

**Issue by RafaelC2** [googleads/googleads-mobile-unity#483]
When I install admob it creates a folder called "Plugins" that is recreated if it is deleted or removed, I am trying to implement admob and with unity in-app-purchasing but it creates a folder with the same name "Plugins" causing a conflict how can I solve this problem?

**Comment by rampara** [comment]
@RafaelC2 the `Plugins` folder is a special Unity folder that more than one plugin can use. What kind of conflict are you running into.

**Comment by RafaelC2** [comment]
![conflito](https://user-images.githubusercontent.com/31190316/29517214-6189a4e8-864a-11e7-92a3-60dba17a38c7.png)

I think the folder will be overwritten.

**Comment by rampara** [comment]
@RafaelC2 the folder shouldn't be overwritten. Plugins should add files to the same directory.

**Comment by rampara** [comment]
Closing this issue due to its age. Please re-open if this issue persists for you.
