### ISSUE TITLE
JS: Uncaught (in promise) TypeError: e.join is not a function

### ISSUE THREAD

**Issue by Ruco** [googleads/googleads-mobile-unity#484]
When I try to get AdMob working I am getting the following output in logcat (Ads tag):

> 08-21 17:44:43.224: D/AdsUnity(26409): Calling loadAd() on Android
08-21 17:44:43.567: I/Ads(26409): Starting ad request.
08-21 17:44:43.569: I/Ads(26409): Use AdRequest.Builder.addTestDevice("4AE9389FC691ED8783A760A7ED29881E") to get test ads on this device.
08-21 17:44:43.865: E/Ads(22314): JS: Uncaught (in promise) TypeError: e.join is not a function (https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js:322)
08-21 17:44:53.894: W/Ads(26409): There was a problem getting an ad response. ErrorCode: 0
08-21 17:44:53.902: W/Ads(26409): Failed to load ad: 0

Before this I had a 403 error while retrieving an ad. This was without adding my device as a testdevice. Now, after removing data+cache of several Google Play Services apps. I received the error above.

Any help given would be highly appreciated.

**Comment by rampara** [comment]
@Ruco as this issue is not related to this plugin but the Android GMA SDK instead, you should reach out on the [Google Mobile Ads SDK Technical Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
