### ISSUE TITLE
3.6.3 ios not call OnAdRewarded

### ISSUE THREAD

**Issue by hendlake8** [googleads/googleads-mobile-unity#485]
use 3.6.3

in ios call RewardBasedVideoAd show

<Google:HTML> You are currently using version 7.21.0 of the SDK. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be downloaded from http://goo.gl/iGzfsP. A full list of release notes is available at https://developers.google.com/admob/ios/rel-notes.

**Comment by rampara** [comment]
@hendlake8 this warning output to the console when the version of GMA iOS SDK used by your app is not up to date. Rebuilding the Xcode project should pull in the latest version of GMA iOS SDK and get rid of this warning.
