### ISSUE TITLE
Impossible merge AndroidManifest.xml

### ISSUE THREAD

**Issue by SiERRAeStudio** [googleads/googleads-mobile-unity#486]
Hi,
I have a error, using Unity version 5.4.1f1 and googleads-mobile-unity v3.6.3. This is error:

CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/Jaime/android-sdks/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[

]
stdout[
Warning: [Temp/StagingArea/AndroidManifest-main.xml:12, /Users/Jaime/Documents/PROY_DIES/ProyectosUnity/Mars 9 ver Android TAPPX 1.26/Temp/StagingArea/android-libraries/GooglePlay/AndroidManifest.xml:3] Main manifest has <uses-sdk android:targetSdkVersion='23'> but library uses targetSdkVersion='24'
]
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.HostView:OnGUI()

What's the solution for my problem?

Regards

**Comment by hwilliams82** [comment]
It's because the minsdkversion of unity's manifest is 16 and the Google ads version is 14. I'm having the same issue and waiting to hear back from the ads team

**Comment by SiERRAeStudio** [comment]
Hi hwilliams82,
I decided to delete it, but I had the same problem with google-play-services, and I found the following solution:
1) Download Android SDK Tools:
    If your computer is Windows: http://dl-ssl.google.com/android/repository/tools_r25.2.5-windows.zip
    If your computer is MAC: https://dl.google.com/android/repository/tools_r26.0.2-macosx.zip
2) Go to your Android SDK Folder. There may be 2 folders of Android SDK, you must go the one in Unity Preferences.
3) Rename the old Android sdk "Tool" folder : [Your Android SDK root]/tools -> toolsXXXX
4) Extract that to Android SDK root folder.
5) Check the platforms folder, you must have the versions that you have in conflict, but you must upgrade with Android Studio or Android SDK Manager. These can be in another folder, if so the copies and paste in the platforms folder of the Android SDK that Unity uses.
6) In Unity go to Edit>Preferences>External Tools and check again, that the path for Android SDK points to the correct folder. (The correct path is the SDK root folder, not the tools folder which is inside the root folder!)
7) Build your project.

Excuse my English, I'm Chilean.

**Comment by rampara** [comment]
@SiERRAeStudio looks like you ran into two separate issues. The first is that older versions of Unity (< Unity 5.5) are not compatible with the latest Android SDK tools. This can be solved by either downgrading Android SDK tools or upgrading Unity. The second issue you ran into is exactly as described by @hwilliams82. The minimum API level for Android setting in Unity conflicts the minimum SDK declared in an Android plugin AndroidManifest file.

Closing issue as you seem to have resolved both issues.
