### ISSUE TITLE
Unity keeps trying to install SDK tools after Admob integration

### ISSUE THREAD

**Issue by vargabbarua** [googleads/googleads-mobile-unity#488]
I am trying to get this plugin working with Unity 5.6.0f3. After the package has been imported, Unity keeps 'Quering about Android SDK components' and after a couple of minutes displays a message saying I am missing tools-25.2.5. However, Android SDK Manager shows that I do have this version installed. I uninstalled & reinstalled the SDK tools but it didn't help. Do I need any additional SDK components? Also, 'Build & Run' is working fine so I know the SDK path is correct.

This is what my component window looks like right now -

![100847-sdk](https://user-images.githubusercontent.com/31437860/29816077-6e80e3aa-8cd0-11e7-809b-79d0a725f02a.jpg)

**Comment by rampara** [comment]
@vargabbarua are you using the latest version of this plugin?

**Comment by rampara** [comment]
Closing due to non-response.
