### ISSUE TITLE
Amazon Fire OS DFP won't run without Google Play Services

### ISSUE THREAD

**Issue by sam-eller** [googleads/googleads-mobile-unity#489]
I understand that Fire OS does not include Google Play Services, so what, does that mean this SDK does not support Amazon devices? Everytime I build this for Android, it works fine, just Amazon devices have a warning pop up that won't go away until I click "OK"

**Comment by rampara** [comment]
@sam-eller can you post of screenshot of the warning pop up you are encountering?

**Comment by rampara** [comment]
Closing due to non-response.
