### ISSUE TITLE
Vungle SDK 5.x - "At least one placement should be specified!"

### ISSUE THREAD

**Issue by Deathwing** [googleads/googleads-mobile-unity#490]
So we just updated Google Ad Mobs for Unity and wanted to update also the Vungle Mediator.
So we installed the newest Vungle SDK (5.1.1) for Unity with the newest mediators from Google Ads.
The problem here is, the newest Vungle SDK needs placements, which you also implemented into your adapters. But your adapters are not listening on the serverParameters for it, they need to be passed by networkExtras. So I created at runtime a AdRequest.Builder, for which I called:
builder.AddExtra("allPlacements", "xxx"); <- allPlacements is the keyString for VungleExtrasBuilder.EXTRA_ALL_PLACEMENTS.

But nevertheless I still get the following error in logcat:
09-01 19:02:03.281: E/VungleManager(25418): At least one placement should be specified!

Cheers and thanks for the help!

**Comment by paradizIscool** [comment]
Hi, this is due to strange Vungle uses of extras. You should contact vungle.

**Comment by rsodre** [comment]
I'm having the same issue with Unity 5.6.3, Vungle 5.2 and Android adaptor 5.1.0
@Deathwing , did you contact Vungle? Is there any support case open for that?

**Comment by Deathwing** [comment]
@rsodre Yeah, we contacted Vungle. They wrote me: 'I am currently waiting on a response from plugin developer who wrote the AdMob side, as this is an edge case integration.I will follow up again.'
So time to wait I guess :)

**Comment by rsodre** [comment]
Instead of this error, I started seeing "VungleManager: networkExtras is null". Same thing.

Vungle support team told me that the Android adaptor is not working with Unity and we should use Vungle SDK v4 for the time being.

Downgraded to Vungle Unity SDK 4.1.0 and android adaptor 2.2.0 and now I saw my first Vungle ad with AdMob mediation :)

**Comment by rampara** [comment]
@Deathwing @paradizIscool @rsodre Currently network extras for Vungle is not supported with this plugin but we're working on resolving this issue. I'll update this issue as soon as support for Vungle SDK 5.x is ironed out.

For the time being, if you would like you use Vungle mediation with this plugin, you will have to use the older version of Vungle's SDK and mediation adapter, as @rsodre mentioned.

**Comment by rampara** [comment]
The latest version of the GMA Unity plugin (v3.8.0) does include support for Vungle mediation extras. Mediation extras functionality will not be included in the standard plugin but distributed in separate add-on Unity packages, specific to ad networks. Updated documentation on how to use these extras and the hosting of the separate Vungle mediation Unity package is upcoming but publishers looking to get a head start can build and use this package from the build script located [here](https://github.com/googleads/googleads-mobile-unity/blob/master/mediation/Vungle/build.gradle). Running the `gradle` command in the same directory as that build script will generate the Vungle mediation Unity package that should be included alongside v.3.8.0+ of the GMA Unity plugin. 

Publishers will need to use the VungleInterstitialMediationExtras class to declare all placements for an interstitial ad request

`
VungleInterstitialMediationExtras extras = new VungleInterstitialMediationExtras();
extras.SetAllPlacements(new string[] { "INSERT_PLACEMENT_ID_HERE", "INSERT_PLACEMENT_ID_HERE" });
AdRequest request = new AdRequest.Builder().AddMediationExtras(extras).Build();
`
  
and the VungleRewardedVideoMediationExtras class to declare all placements for rewarded video ad request

`
VungleRewardedVideoMediationExtras extras = new VungleRewardedVideoMediationExtras();
extras.SetAllPlacements(new string[] { "INSERT_PLACEMENT_ID_HERE", "INSERT_PLACEMENT_ID_HERE" });
AdRequest request = new AdRequest.Builder().AddMediationExtras(extras).Build();
`

**Comment by pineda100** [comment]
any updates about the official release of this vungle mediation unity package and documentation?

**Comment by rampara** [comment]
@pineda100 should be out this quarter but as my previous post mentioned, you can already build the support package if you want a head start.
