### ISSUE TITLE
OnAdRewarded and OnAdClosed callbacks are not firing for unity rewarded ads while using admob mediation.

### ISSUE THREAD

**Issue by soundeos** [googleads/googleads-mobile-unity#491]
When using admob mediation, if the ad is serving from Unity, OnAdRewarded and OnAdClosed callbacks are not firing. The admob ads works fine. Here're what I did to produce the problem.

1- Modify the HelloWorld sample app to use my own rewarded ad mediation id. (https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld)
2- Install Google Mobile Ads Unity Plugin v3.6.3. (https://github.com/googleads/googleads-mobile-unity/releases)
3- Install Unity Ads SDK through Unity editor. From Window -> Services menu. Link to my Unity project which has the rewarded ad.
4- Install Unity Ads adapter v2.1.0.0 from (https://bintray.com/google/mobile-ads-adapters-android/com.google.ads.mediation.unity#files/com/google/ads/mediation/unity) as described here (https://groups.google.com/forum/#!topic/google-admob-ads-sdk/0klwA5IbkBA)
5- Run the app. Request for a rewarded video ad. And show it.

I can see the ad running and the OnAdLoaded and OnAdOpening events are called. When the video finishes I close the ad. But OnAdRewarded and OnAdClosed events are not fired.

I've attached the logcat and the sample app.

[logcat for unity admob mediation.txt](https://github.com/googleads/googleads-mobile-unity/files/1272582/logcat.for.unity.admob.mediation.txt)

[HelloWorld.zip](https://github.com/googleads/googleads-mobile-unity/files/1272579/HelloWorld.zip)

**Comment by rampara** [comment]
@soundeos this issue seems specific the the Unity Ads adapter and not this plugin. I would recommend you reach out on the [Google Mobile Ads SDK Technical Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).

**Comment by rsodre** [comment]
Fixed that problem by not calling Advertisement.Initialize(appId);
AdMob already Initializes Unity Ads, calling it twice will break it.
