### ISSUE TITLE
Banner is not always shown (only after refresh or with click on the empty space)

### ISSUE THREAD

**Issue by Russel1** [googleads/googleads-mobile-unity#492]
Hello,

why is my medium rectangle banner not always shown after BannerViewBottom.Show() on an Android Device?
It seems like he already exists, but not shown. When I click on the empty space, it appears. Or it apears after the RefreshRate from Google Mobile Ads Settings.

The first shown always works, but the second shown doesn't always work (after BannerViewBottom.Hide()).

Best regards,
Oli

**Comment by rampara** [comment]
@Russel1 are able to reproduce this issue in the HelloWorld sample app in this repo?

**Comment by rampara** [comment]
@Russel1 this issue should be resolved in that latest version of the plugin (v3.7.1).
