### ISSUE TITLE
Delegate events problem

### ISSUE THREAD

**Issue by MadeForThisCommment** [googleads/googleads-mobile-unity#494]
I dont whats causing the problem but there are a lot of errors

> Assets/GoogleMobileAds/Platforms/Android/InterstitialClient.cs(42,46): error CS0066: `GoogleMobileAds.Android.InterstitialClient.OnAdOpening': event must be of a delegate type

**Comment by rampara** [comment]
@MadeForThisCommment have you modified the source code for this plugin in any way?

**Comment by MadeForThisCommment** [comment]
I didnt delete the plug-in and other folders from the old plug-in that I installed.

**Comment by rampara** [comment]
@MadeForThisCommment updating from an older version of this plugin shouldn't cause this issue. If you link me to a Unity project that reproduces this issue, I can dig into what is causing it.

**Comment by rampara** [comment]
Closing due to non-response.
