### ISSUE TITLE
Why not fix the incorrect thread issue?

### ISSUE THREAD

**Issue by larku** [googleads/googleads-mobile-unity#496]
Opened a new issues as I can not comment on the previous one I opened since it was closed before I could reply (a bit hasty).

Previous bug report: 
---------
( https://github.com/googleads/googleads-mobile-unity/issues/495#issuecomment-327736193 )

The event callbacks are invoked on a different thread than the event callbacks are registered on (ie, the Unity Update() thread)

This causes many issues/bugs.

Most developers would expect the callbacks to occur on the main Unity Update() thread.
---------

I have no issue handling the events now I know - but why not invoke them on the correct thread (it's reasonably trivial to do).

I've lost 2 days development on this and given the number of threads/topics on this and bugs which look very much like they're being caused by this (for others) it seems crazy that it's not changed to behave like every other Unity plugin that I've ever seen.

Invoking these events on any thread other than the one they were registered on IMO is a broken design and leads to nothing but trouble for unsuspecting Unity devs. Every dev will be registering them on the Unity main thread and will expect they are invoked on the same thread.

By design the Unity API is single threaded, and IMO this plugin should adhere to the same philosophy. Especially since this is not obvious and it's only discovered once bugs appear and hair is pulled determining what's going wrong.

Surely you want to make integrating this plugin a simple as practical - this IMO is a very unnecessary nuance that likely wastes hundreds of hours of devs time every week.

Is there any rationale for not fixing this?

**Comment by ArmandCloud** [comment]
Same here, running lot of coroutines to manage all events. It causes crash after hard quit from the game.
Is there a best practice for this thread issue?
Best Regards,

**Comment by rampara** [comment]
@ArmandCloud the current best practice is described in this [blog post](http://googleadsdeveloper.blogspot.com/2016/04/handling-android-ad-events-in-unity.html).

**Comment by rampara** [comment]
In the latest version of the plugin (v3.11.0) Android ad events are invoked on the main thread by default.
