### ISSUE TITLE
Can't get it to work.

### ISSUE THREAD

**Issue by xxPillsxx** [googleads/googleads-mobile-unity#502]
So I just downloaded, imported the plugin and followed the tutorial on Admob's website, but couldn't get it to work. These errors always show up when running in the editor:

**Gradle failed to fetch dependencies.**

> 
> Failed to run 'Temp\PlayServicesResolverGradle\gradlew.bat -b Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle "-PANDROID_HOME=D:/Android/sdk1" "-PTARGET_DIR=D:\Unity Projects\Slider\Slider\Assets\Plugins\Android" "-PMAVEN_REPOS=https://maven.google.com" "-PPACKAGES_TO_COPY=com.google.android.gms:play-services-ads:11.2.2"'
> stdout:
> 
> ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
> 
> Please set the JAVA_HOME variable in your environment to match the
> location of your Java installation.
> 

and

**Resolution failed**

> Failed to fetch the following dependencies:
> com.google.android.gms:play-services-ads:11.2.2
> 
**I've tried running the Resolver, but it didn't do anything at all.** There are no .Arr files in my Plugins/Android folder, there's only the GoogleMobileAdsPlugin folder. 
I've also downloaded the Google repository and Google Play Services in Android Studio. I also have the latest version of JDK.

When I tried deploying it to my android device, I get this error:

> AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.AdSize
> java.lang.ClassNotFoundException: com.google.android.gms.ads.AdSize

Any help is appreciated.

**Comment by rampara** [comment]
@xxPillsxx can you ensure values for the Android SDK and JDK path are set under External Tools tab in Unity preferences?

**Comment by xxPillsxx** [comment]
Forgot to reply back to this after I fixed the issue by setting a JAVA_HOME variable.
