### ISSUE TITLE
Useless clearJar task

### ISSUE THREAD

**Issue by paradizIscool** [googleads/googleads-mobile-unity#503]
clearJar task try to remove a file that cannot exist
unity-plugin-library.jar
is create by copyAndroidLibraryJar
into ${pluginBuildDir}/Assets/Plugins/Android/GoogleMobileAdsPlugin/libs

this folder is cleared by clearTempBuildFolder, there is no need to remove this jar specifically

**Comment by rampara** [comment]
@paradizIscool the `android-library` project may have been built separately from running the top-level gradle task in the build script for this plugin.
