### ISSUE TITLE
Ads not showing - designed for families + Unity

### ISSUE THREAD

**Issue by ishmar** [googleads/googleads-mobile-unity#504]
Hi,

I'm developing a game with Unity 2017, and I want to add admob ads to it.

I've been trying to show admob ads for the last week with no luck. I tried to install/reinstall package (using v3.6.3). My first approach was to use banners, but I ended up giving up and trying rewarded videos.  Still got nothing.

Today, I've found that using a new package name (just removing last char for example), ads are shown, but building apk again with my real package name (already registered on google play console I get usual message from logcat:

```
I Ads      : No fill from ad server.
W Ads      : Failed to load ad: 3
```

The 'fake' package name for testing purposes isn't even listed on google play console as an app. 
Being unsure about reasons for not getting either banners or videos, I've tried (all possible maybe?) combinations on building AdRequest:

```
AdRequest request = new AdRequest.Builder().Build();
AdRequest request = new AdRequest.Builder().AddExtra("is_designed_for_families", "true").Build();
AdRequest request = new AdRequest.Builder().TagForChildDirectedTreatment(true).Build();
AdRequest request = new AdRequest.Builder().AddExtra("is_designed_for_families", "true").TagForChildDirectedTreatment(true).Build();

```
All of them with/without 

> .AddTestDevice("MY_TEST_DEVICE")

For rewarded videos, I've used both [tutorial](https://developers.google.com/admob/unity/rewarded-video) adUnitID and my own ID. Sadly, tutorial gives no info on how to show ads with designed for families apps, and [targeting tutorial](https://developers.google.com/admob/android/targeting) which gives such info, uses **boolean** Extra key not available on Unity package.

All in all, I need to know what must I write to show either banners, videos or whatever inside my app.

Last but not least, my app is still alpha (published just as that, alpha, no production apk published yet, but is already approved in the 'designed for families'   Age Group: Ages 6-8, Ages 5 & Under.

Thanks

**Comment by rampara** [comment]
@ishmar are you receiving ads without issue when removing the `is_designed_for_families` and `TagForChildDirectedTreatment` options on the ad request? If so, there may be no issue at all, only the expected lower fill rate when requesting ads with those options as mentioned in the [AdMob help center](https://support.google.com/admob/answer/6223431?hl=en).

**Comment by ishmar** [comment]
Nevermind, after creating project from scratch it finally worked. Thanks for your time.
