### ISSUE TITLE
CommandInvokationFailure: Unable to convert classes into dex format

### ISSUE THREAD

**Issue by wenderRondonia** [googleads/googleads-mobile-unity#505]
Got this error after importing googleads-mobile-unity
other plugins: UnityIAP and Google Play Games Services

**Comment by gmikhail** [comment]
I had the same problem. I use Google Play Games Services.

**Comment by gmikhail** [comment]
I found a temporary solution:

**1. Disable automatic version replacement.** Unity menu -> Assets ->Player Services Resolver -> Android Resolver -> Settings -> deactivate "Enable Auto-Resolution" -> OK - NO (just read the dialog carefully).
**2.** Replace **play-services-ads**, **play-services-ads-lite**, **play-services-basement**, **play-services-gass** (libraries related to ads, they will have the same version) to the main version of Google Play Services in your project. You can find the required files in the **Android SDK\extras\google\m2repository\com\google\android\gms** (if they are not there - download them through the Android SDK manager).

Now the build is successful. Screenshot of my plugins folder:  

![](https://i.imgur.com/V0inA7a.png)

**Comment by wenderRondonia** [comment]
thanks ! everything works now!
