### ISSUE TITLE
Hiding and showing banner ads breaks them

### ISSUE THREAD

**Issue by LeonardoDipilato** [googleads/googleads-mobile-unity#506]
I'm working on a game with a Menu->Game->GameOver->Menu setup and my plan was to hide the banner ad on the Menu and show it in Game and GameOver, hiding it again when entering the Menu.
However, the setup only works on the first loop. To explain:
1. Menu screen, no ads showing. Here the AdsManager is initialized and loads the ad in the background.
2. Game screen, ads showing. Here the AdsManager gets its ShowBanner method called from another object.
3. GameOver screen, ads showing. The AdsManager isn't touched at all here.
4. Menu screen, no ads showing. An external object calls AdsManager's HideBanner method to hide ads.
5. Game Screen, **no ads showing**, while the banner should be up there.
6. From here on, ads never show unless I close the app and restart it, in which case the loop starts back from point 1.

To debug, I've also added a public bool to the AdsManager that is set to true whenever the ShowBanner method is called and is set to false whenever the HideBanner method is called. The bool behaves correctly, being on when it should, and off when it shouldn't, while the ads don't appear.

**Comment by rampara** [comment]
@LeonardoDipilato are you running into this issue on Android, iOS or both platforms?

**Comment by LeonardoDipilato** [comment]
I've only tried on Android, which, as of now, is the only platform I'm developing for.

Also, perhaps this is worthy of note, I found I have the same problem with interstitials which only show once before never appearing again.

**Comment by rampara** [comment]
@LeonardoDipilato thanks for bringing this issue to our attention. Will be pushing out a fix for this shortly.

**Comment by rampara** [comment]
@LeonardoDipilato this issue should be resolved in that latest version of the plugin (v3.7.1).
