### ISSUE TITLE
Error: No ad to show.

### ISSUE THREAD

**Issue by JohnnyIsHereNow** [googleads/googleads-mobile-unity#508]
I am trying to implement rewarded video ads in my application.
Everything worked well for that past few months but for last couple of days I got this error:

 ["No ad to show."]

This only happens on iOS.
I have tried to do the same with the sample app and it works only for test ads. If I change the ID I receive the same error.
I must specify that it works ok on Android.
Thanks in advance.

**Comment by rampara** [comment]
@JohnnyIsHereNow as this issue is not related to this plugin but to the performance of your specific ad plamcement, I would recommend you reach out on the [Google Mobile Ads SDK Technical Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).

**Comment by phuocnb** [comment]
The same with me

**Comment by phuocnb** [comment]
@rampara the support link you is not working https://groups.google.com/forum/#!forum/google-admob-ads-sdk

**Comment by rampara** [comment]
@phuocnb strange that link works for me. What do you see when attempting to click through?

**Comment by cubixstd** [comment]
@rampara the link works well on pc. Look like this issue is on mobile only
https://imgur.com/a/oZ3iB
