### ISSUE TITLE
Issues on IOS. OnAdRewarded called with wrong ShowResult

### ISSUE THREAD

**Issue by 2rusbekov** [googleads/googleads-mobile-unity#509]
Using Google Mobile Ads Unity Plugin v3.7.0.

Google Mobile Ads SDK 7.23.0 not gonna build in xcode with error "some header not found".
Someone here on git adviced to use sdk 7.22, and it builds without errors.

Issue: Only every second watched ad returns ShowResult.Finished, first - ShowResult.Skipped.

**Comment by rampara** [comment]
@2rusbekov can you provide more information on the header error you're running into? I'm able to build and run the plugin with the latest version of the GMA iOS SDK without issue. When you build your Xcode project do you see any content in the Unity console that may indicate the cause of your issue?

As for your second issue, I'm not sure what you're referring to by `ShowResult.Finished` or `ShowResult.Skipped`.

**Comment by 2rusbekov** [comment]
@rampara I handled that header issue. Previously I unpacked 7.23 zip on windows pc and moved to mac, i dont know why, but it didnt work. But issue dissapears when I unpacked on mac.

> As for your second issue, I'm not sure what you're referring to by ShowResult.Finished or ShowResult.Skipped.

Oh, sorry, wrote wrong.

RewardBasedVideoAd.Instance.OnAdClosed always called if I watching ad first time.
RewardBasedVideoAd.Instance.OnAdRewarded called every second watch.

**Comment by rampara** [comment]
Correct me if I'm not understanding the issue correctly. You are only receiving the `OnAdClosed` ad event for the first rewarded ad you show. All subsequent rewarded video ads do not receive this ad event (but the other ad events work as expected. Is that the issue you're experiencing?

**Comment by 2rusbekov** [comment]
Hi @rampara 
Here logs with sdk 7.23.0. I watched 4 ads till end.

**[CODE] Purchaser.OnAdMobLoaded**
//Here I pressed "watch ad" button
**[CODE] Purchaser.OnAdMobRewarded**
//I get reward. Fine

**[CODE] Purchaser.OnAdMobLoaded**
//Here I pressed "watch ad" button
**[CODE] Purchaser.OnAdMobRewarded**
//I get rewarded again. Fine

**[CODE] Purchaser.OnAdMobLoaded**
//Here I pressed "watch ad" button again
**[CODE] Purchaser.OnAdMobRewarded 
[CODE] Purchaser.OnAdMobClosed**
//Here 2 events fired at same time. But previously only OnAdMobClosed was firing
//Now it's not so critical as users get reward.

**[CODE] Purchaser.OnAdMobLoaded
[CODE] Purchaser.OnAdMobRewarded
[CODE] Purchaser.OnAdMobClosed**
//And again


Sdk 7.22.0 called only OnAdMobClosed without OnAdMobRewarded even if I watched full ad.

**Comment by rampara** [comment]
@2rusbekov were the first two ads served by AdMob or are you using mediation as well?

**Comment by 2rusbekov** [comment]
We are using mediation.

**Comment by rampara** [comment]
@2rusbekov identifying which ad network is returning the ad that causes the issue would help with getting to the bottom of what the cause is.

**Comment by 2rusbekov** [comment]
How can I do it? Except of enabling them one by one.

**Comment by rampara** [comment]
@2rusbekov enabling them one by one does like quite a bit of work. Should be pushing out an update soon that includes a new API for `getAdapterClassName`. If you're willing to wait, that API would make identifying the ad network much easier.

**Comment by 2rusbekov** [comment]
@rampara Hi!

Tested with new release and got next.

Platform: IOs. RewardBasedVideoAd.Instance.MediationAdapterClassName() is GADMAdapterGoogleAdMobAds.
Sometimes OnAdClosed and OnAdRewarded events called at same time. Android still fine.

**Comment by rampara** [comment]
@2rusbekov I may be misunderstanding the issue you're facing. What is the behavior you expect versus the behavior you are encountering?

**Comment by 2rusbekov** [comment]
@rampara actually issue from first post is fixed, at least I didnt encounter it. 

Current issue is that Sometimes OnAdClosed and OnAdRewarded events called at same time. I expect OnAdClosed to be called when user interrupted ad, didnt watch to the end. And OnAdRewarded to be called when user watch the full ad to the end, in this case I should give him a reward.

**Comment by rampara** [comment]
@2rusbekov expected behavior is the `OnAdClosed` will always be called. `OnAdRewarded` can be called at any time before `OnAdClosed` if a user should be rewarded.
