### ISSUE TITLE
Reward Video Ads Not Showing On Iphone

### ISSUE THREAD

**Issue by iceherosubzero** [googleads/googleads-mobile-unity#511]
I am unable to see Rewarding Video Ads at all on IPhone.
Whereas I am able to see Rewarding Video Ads on Android without any problem.
Every time I try to show ad after requesting an ad it is always failing.
Is there any problem on the server side??? because I was able to see a few weeks back the Rewarding Video Ads on IPhone.

Regards,
Iceheros

**Comment by edscodeblenders** [comment]
Same issue here. Could it be related to the fact that the app has not been approved yet by Apple? Is it a must that the app is live to show rewarded ads?

**Comment by rampara** [comment]
@iceherosubzero @edscodeblenders can you try setting you device to be a test device before making ad requests for unreleased apps?

**Comment by edscodeblenders** [comment]
Apple just approved our app, we linked the app, and now rewarded ads are showing properly. Thanks.

**Comment by rampara** [comment]
@edscodeblenders glad your issue has been resolved.

**Comment by rampara** [comment]
Closing issue due to non-response from original poster.
