### ISSUE TITLE
I see console logs just fine in Editor, but can't build (unable to convert classes into dex format)

### ISSUE THREAD

**Issue by HasnLal** [googleads/googleads-mobile-unity#512]
![picture 2017-09-24 20_29_25](https://user-images.githubusercontent.com/32243483/30784062-29198780-a167-11e7-9051-659970423a7c.png)
Play Games version : 0.9.40 (near 2 weaks old)
Google Mobile ads (latest to this date)
I have play games working fine, leaderboards etc. But after play games I imported this plugin for admob unity, I deselected 'PlayServicesResolver/Editor/Google.VersionHandler.dll' (since I don't want to mess up my working Play Games plugins). (Also tried with replacing it with this plugin's, same error)
But after all this, it doesn't build the game, giving error "CommandInvokationFailure: Unable to convert classes into dex format." (console log is spammed) and I know you pretty well know about this.
So what can be the solution?

**Comment by rampara** [comment]
Closing due to non-response.
