### ISSUE TITLE
iOS framework addition failed due to a Cocoapods installation failure

### ISSUE THREAD

**Issue by dps999** [googleads/googleads-mobile-unity#516]
Cocoapods installation detected /usr/local/bin/pod
Then

iOS framework addition failed due to a Cocoapods installation failure. This will will likely result in an non-functional Xcode project.

After the failure, "pod repo update" was executed and succeeded. "pod install" was then attempted again, and still failed. This may be due to a broken Cocoapods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.

pod install output:

Analyzing dependencies
Downloading dependencies
Installing Google-Mobile-Ads-SDK (7.24.1)
Generating Pods project

    [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    [0m

**Comment by rampara** [comment]
@dps999 did you try re-building after the adding the recommended lines to your bash profile?

**Comment by rampara** [comment]
Closing due to non-response.
