### ISSUE TITLE
BannerView always top

### ISSUE THREAD

**Issue by stantler** [googleads/googleads-mobile-unity#518]
Hello, I have folowing code:
`_bannerView = new BannerView("id", AdSize.SmartBanner, AdPosition.Bottom)`

But banner appears always at the top position. Center position also not working

Plugin version 3.7.1 or 3.7.0
Device - samsung galaxy 7e

**Comment by kangoo13** [comment]
Exactly the same problem. I think it's due to the last update ? Because the last version I didn't have this problem !

**Comment by stantler** [comment]
@kangoo13 what is "google play 11.0.0"?
I downgraded to 3.7.0 plugin version and it didn't work

**Comment by rampara** [comment]
@stantler @kangoo13 are you able to reproduce this issue across devices or only on a specific one?

**Comment by JorgeRomano** [comment]
I had the same problem. I  downgraded to 3.7.0 and it's working now.

**Comment by kangoo13** [comment]
@rampara only on specified, for exemple on mine (samsung galaxy S7) it's working, on an 1+one it's working but on samsung galaxy S7 edge it's not working. (as for my tests)

**Comment by rampara** [comment]
Haven't been able to get my hands on a S7 Edge. @JorgeRomano what device are you running this issue with?

**Comment by JorgeRomano** [comment]
The device that I'm using is just a S7 Edge.

**Comment by rampara** [comment]
@JorgeRomano @stantler @kangoo13 shooting in the dark without having a device I can reproduce the issue with but can you trying replacing `unity-plugin-library.jar` at the `Assets/Plugins/Android/GoogleMobileAdsPlugin/libs` directory of your Unity project with the file in attached zip?

[unity-plugin-library.jar.zip](https://github.com/googleads/googleads-mobile-unity/files/1354107/unity-plugin-library.jar.zip)

**Comment by JorgeRomano** [comment]
It's working!

**Comment by rampara** [comment]
@JorgeRomano thanks for confirming. Will push out an updated release shortly with the fix.

**Comment by SnnYsf** [comment]
i tested samsung s8 android 7.0 

We expect the updated version.
Remove from 3.7.1

**Comment by petrescusilviu** [comment]
@rampara when will the release happen for this bug?

**Comment by SnnYsf** [comment]
sory i dont know

2017-10-20 18:22 GMT+03:00 petrescusilviu <notifications@github.com>:

**Comment by rampara** [comment]
The latest version of this plugin (v3.8.0) resolves this issue.
