### ISSUE TITLE
[Feature Request] Mediation Adapters and SDKs - Resolution through Play Services Resolver

### ISSUE THREAD

**Issue by anmolmahatpurkar** [googleads/googleads-mobile-unity#519]
Hi, Just noticed that the play service resolver downloads its required libraries through the maven repository. The Mediation adapters also seem to be available here. Is it possible to somehow automate the inclusion of the required mediation adapters through the play services resolver as well?

**Comment by rampara** [comment]
@anmolmahatpurkar this functionality in upcoming and you can expect an update on it soon.

**Comment by rampara** [comment]
This has started to roll out. Open new issues for any specific networks you would like to see.
