### ISSUE TITLE
‘GoogleMobileAds/GoogleMobileAds.h’ file not found

### ISSUE THREAD

**Issue by icyh4mmer** [googleads/googleads-mobile-unity#524]
When I'm building project in xcode, I get this error; 
Lexical or Preprocessor issue: ‘GoogleMobileAds/GoogleMobileAds.h’ file not found

I just freshly imported admob plugin, so it's latest version. Does anyone have any idea what's going on?

Edit: I'm using Xcode 9.0 (9A235) and Unity 5.6.2f1. I just tried to add the plugin in the empty unity project and build it and I get the same error. I'm Also adding a [screenshot](https://imgur.com/6QX3FKZ).

**Comment by rampara** [comment]
@icyh4mmer is the GMA iOS SDK included in your Xcode project? Did the Unity plugin generate an xcworkspace? Can you try building a new Xcode project from Unity?

**Comment by icyh4mmer** [comment]
@rampara Hey, thanks for the response :) I'm not experienced with Xcode so I'm attaching [screenshot](https://imgur.com/MIlEE9y), where I can't see GMA under frameworks but there are some GADU* files in the plugin folder.  

To the second and third question, I did build new Xcode project from Unity and nothing chnaged, Unity did not generate xcworkspace file, only xcodeproj file and other stuff which can be seen on [this](https://imgur.com/CCkxKDX)screenshot. Here can you also see the state of the iosresolver, and the context menu. I wasn't sure if the editor check has to be enabled? I enabled it before and it still didn't work. If you have any further questions/requests/ideas please let me know.

**Comment by rampara** [comment]
@icyh4mmer it doesn't look like you're using the latest version of this plugin. Can you update and try and build another Xcode project?

**Comment by icyh4mmer** [comment]
I'll download it again and rebuild.

**Comment by icyh4mmer** [comment]
@rampara I deleted everything from the project, closed unity, opened unity, downloaded this plugin, imported it to unity, built project, and again workspace wasn't created and the same error exists. I must be missing something obvious :(

**Comment by rampara** [comment]
@icyh4mmer is there any content in the Unity console that may indicate the cause of your issue?

**Comment by icyh4mmer** [comment]
@rampara There is only 1 console log after build, and it's a warning that I didn't provide splash screen images.

**Comment by icyh4mmer** [comment]
@rampara Is there anything else I could check or try so we can figure out why this is happening?

**Comment by rampara** [comment]
Can you try turning on verbose logging (by selecting `Assets -> Play Services Resolver -> iOS Resolver -> Settings` and selecting `Verbose Logging`) before attempting to build an Xcode project?

**Comment by icyh4mmer** [comment]
@rampara As you can see in [this](https://imgur.com/CCkxKDX) screenshot, I can only select 
Assets -> Play Services Resolver -> Version Handler

There is no iOS Resolver in the context menu. So I guess the iOS resolver doesn't even load in the editor,  in the same screenshot you can also see that Google.IOSResolver_v1.2.48.0 is not enabled for any of the platforms. I tried to enable it for editor but I still didn't get the context menu. Do I have to enable anything else, since this might be the source of the issue.

**Comment by icyh4mmer** [comment]
@rampara I just found out what was the issue. I had to select Version Handler -> Update and then IosResolver became visible and the build succeeds. Is this normal that you have to manually update veraion handler?  Anyhow thanks for the help 😃

**Comment by craftyfirefox** [comment]
Got the same problem in Unity Cloud Build, tried to apply wisdom from #333 but am missing AdMobDependencies.cs . Any Help?

**Comment by rampara** [comment]
@icyh4mmer glad you were able to get it working. Version Updates should occur automatically when importing a new version of the plugin but looks like that didn't happen for you.

@craftyfirefox the workarounds listed in #333 are no longer required when using the latest version of the plugin.

**Comment by icyh4mmer** [comment]
Issue fixed.

**Comment by angerdy** [comment]
> When I'm building project in xcode, I get this error;
> Lexical or Preprocessor issue: ‘GoogleMobileAds/GoogleMobileAds.h’ file not found
> 
> I just freshly imported admob plugin, so it's latest version. Does anyone have any idea what's going on?
> 
> Edit: I'm using Xcode 9.0 (9A235) and Unity 5.6.2f1. I just tried to add the plugin in the empty unity project and build it and I get the same error. I'm Also adding a [screenshot](https://imgur.com/6QX3FKZ).

I have the same error when build in Xcode 10 "Lexical or Preprocessor issue: ‘GoogleMobileAds/GoogleMobileAds.h’ file not found". I used unity 5.6.5f1 build project Xcode. If Issue fixed, please help me fix it. Thanks so much!
