### ISSUE TITLE
Interstatial  ad is not working 

### ISSUE THREAD

**Issue by MarouaneIdd** [googleads/googleads-mobile-unity#529]
**I'm using the last GoogleAds plugin ,I Update the Sdk to lasts version too 
Rewarded video is working fine , but the interstitial / banner not working properly
sometimes it actually works (interstitial) the first call , after the first show it dosnot shows again
and it shows the error : no fill (even with test ads) ,[ the project deployed to Android ] ,
The problem become clearer when I add Firebase (Analytics) and OnsSignal plugin
i think its related to (Google.Handler version)
cos When i import OnSignal plugin it add  (Google.Handler version) too , then the editor ask me to delete on of this files [Google.VersionHandler or Google.VersionHandler_v1.2.9.0] 
when i delete the 2nd one it build  , but interstitial dont work fine 
when i delete the 1st one i shows this error at the end of building 
 ** 

_MissingMethodException: Method not found: 'Google.VersionHandler.GetUnityVersionMajorMinor'.
GooglePlayServices.ResolverVer1_1+<GradleResolution>c__AnonStorey14.<>m__20 (GooglePlayServices.Result result)
GooglePlayServices.ResolverVer1_1+<GradleResolution>c__AnonStorey14+<GradleResolution>c__AnonStorey15.<>m__29 ()
GooglePlayServices.PlayServicesResolver.PumpUpdateQueue ()
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs:249)_

And also this 

_FormatException: Input string was not in the correct format
System.Int64.Parse (System.String s) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Int64.cs:458)
System.Convert.ToInt64 (System.String value) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Convert.cs:1404)
Google.VersionHandler+FileMetadata.CalculateVersion (System.String versionString)
Google.VersionHandler+FileMetadata.CalculateVersion ()
Google.VersionHandler+FileMetadataByVersion.Add (Google.FileMetadata metadata)
Google.VersionHandler+FileMetadataSet.Add (Google.FileMetadata metadata)
Google.VersionHandler+FileMetadataSet.ParseFromFilenames (System.String[] filenames)
Google.VersionHandler.UpdateVersionedAssets (Boolean forceUpdate)
Google.VersionHandler..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Google.VersionHandler
FirebaseAnalyticsDeps.SetupDeps () (at Assets/Firebase/Editor/AnalyticsDeps.cs:31)
FirebaseAnalyticsDeps..cctor () (at Assets/Firebase/Editor/AnalyticsDeps.cs:23)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for FirebaseAppDeps
System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (RuntimeTypeHandle type) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs:101)
UnityEditor.EditorAssemblies.ProcessEditorInitializeOnLoad (System.Type type) (at C:/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:136)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:519)
System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:528)
System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/ConstructorInfo.cs:77)
System.Activator.CreateInstance (System.Type type, Boolean nonPublic) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Activator.cs:372)
System.Activator.CreateInstance (System.Type type) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Activator.cs:254)
UnityEditor.AssetPostprocessingInternal.InitPostprocessors (System.String pathName) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:117)
UnityEditor.AssetDatabase:ImportAsset(String, ImportAssetOptions)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Boolean, Boolean)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__20(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__29()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()_

**Comment by rampara** [comment]
As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
