### ISSUE TITLE
Banner flickering

### ISSUE THREAD

**Issue by Junker-Anders** [googleads/googleads-mobile-unity#530]
Every time I show a new banner in my game the banner flickers/blinks for a second before stabilizing. This only happens on banners and not interstitials. I've tried both smart- and normal banners and I'm sure that I only call the function once. I have also tried changing the targetframerate but the result is the same. The problem occurs on both test ads as well on real ads. This happens on all test devices (android).

Does anyone have a clue what the problem is and how it is fixed?

**Comment by rampara** [comment]
@Junker-Anders as banner ads are rendered by the Google Mobile Ads Android SDK, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
