### ISSUE TITLE
I have an error while importing this plugin to Unity "Resolution Failed".Please help me to fix this.

### ISSUE THREAD

**Issue by imbadal** [googleads/googleads-mobile-unity#532]
![image](https://user-images.githubusercontent.com/26278801/31336544-f62b6f82-ad14-11e7-86c6-af9484add781.png)

When I am trying to import, PlayServicesResolver package is not loaded.

**Comment by rampara** [comment]
As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
