### ISSUE TITLE
Unity 2017.1 Gradle

### ISSUE THREAD

**Issue by 3583Bytes** [googleads/googleads-mobile-unity#533]
This plugin seems to have issues when you use the Gradle build system in Unity 2017.1 (maybe other versions).  Although the ad shows the on OnAdClosed event does not seem to fire.  Using the Default Built System does not exhibit this behaviour.

**Comment by rampara** [comment]
@3583Bytes the build system shouldn't influence plugin behavior. Are you also experiencing this issue on the [HelloWorld sample app](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) from this repo?

**Comment by rampara** [comment]
Closing due to non-response.
