### ISSUE TITLE
Ios rewarded videos not showing, real and test ads too

### ISSUE THREAD

**Issue by badrdouah** [googleads/googleads-mobile-unity#535]
Hello, 
i'm having little issue with admob and unity, i'm wondering if you could help me  sort this out , i have interstitials  working fine on IOS , but rewarded videos are not , test and real ads , none of them works  , no error is shown in the console , same code is working on android perfectly , 

i'm just wondering if  this is due to not linking the app to appstore app page , cause we did for android and this is the only thing that we have done differently from ios ,
please help , 
thanx ,

**Comment by rampara** [comment]
@badrdouah As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
