### ISSUE TITLE
Custom Events for Unity AdMob

### ISSUE THREAD

**Issue by remingtonchan** [googleads/googleads-mobile-unity#536]
Hello,

I've been trying to make Custom Events work for a third party network but I think I'm missing something in my implementation.

I'm sure that in the dashboard side, mediation works, because using the same ad unit ID in a native Android environment apparently registers successful fills. But in the Unity implementation, I'm only receiving Google Ads and I see requests from the Custom Event but isn't being filled.

Can anybody provide insight on this issue?

**Comment by rampara** [comment]
@remingtonchan As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
