### ISSUE TITLE
Getting banner size in pixels issue

### ISSUE THREAD

**Issue by rchallenger** [googleads/googleads-mobile-unity#538]
Hello, I've always used such a method to get a real size of banner (I use 320x50 size only, so have no deal with smart banners)
```
public Vector2 GetBannerSizeInPX ()
	{
		Vector2 b_size = banner_size != null ? new Vector2 ( banner_size.w, banner_size.h ) : Vector2.zero;
		float coef = (Screen.dpi / 160f);
		return b_size * coef;
	}
```

But recently I've tried to launch my application on Moto G4 (XT1602) and saw that banner can be of different size than we can think.
Unity tells that device's DPI is 295.265, so according to formula 
width = 320 * (295.265/160) = 590.5
height = 50 * (295.265/160) = 92.3

But according to screenshots below it differs from what we receive.

So the question is how to know the size of actual content?

PS: I've tried to receive ads through NeatPlug. It has own method that returns banner size in pixels. But it told me that banner was of size (640.0 x 100.0). So it was right only about banner's height. Banner's width is more that was expected to be (680.0 x 100.0).

![real banner](https://user-images.githubusercontent.com/20810488/31447740-64d347ba-aeab-11e7-9ff1-a4f411296e8b.png)
![calculated banner size + border](https://user-images.githubusercontent.com/20810488/31447742-651a2284-aeab-11e7-97d9-b1ee26402e5c.png)

**Comment by rampara** [comment]
This will be implemented in an upcoming release of the plugin.

**Comment by rchallenger** [comment]
Hello, in v3.9.0 I saw some changes to banner in native android part of plugin (Banner.java). 
```
int adViewWidth = mAdView.getAdSize().getWidthInPixels(mUnityPlayerActivity);
int adViewHeight = mAdView.getAdSize().getHeightInPixels(mUnityPlayerActivity);
```
Is there any way to get ad size of certain bannerView in Unity?

**Comment by rampara** [comment]
@rchallenger currently there isn't but it will be implemented in a future release.

**Comment by rchallenger** [comment]
Here is another device, where banner size is not same as we get according to formula 
real_dimension = dimension*(dpi/160)
We have Samsung J120H. Its DPI=216.942
According to formula banner size on this screen should be 434x68.
But in fact real application shows banner 480x75 which is much bigger then expected.
![screenshot_2017-12-18-09-07-45](https://user-images.githubusercontent.com/20810488/34094538-4b73a1d8-e3d6-11e7-81ae-a8e3686febfc.png)

**Comment by rchallenger** [comment]
Also Ipad would show desired banner size. It always bigger then we can predict by formula.

**Comment by rampara** [comment]
@rchallenger the latest version of the plugin (v3.10.0) includes an API to get the width and height of banner ads in pixels.

**Comment by rchallenger** [comment]
Methods for banner worked well.
But there are no methods to get size in pixels for NativeAdView.
SetPosition method is missing for this ad type too.

**Comment by rampara** [comment]
@rchallenger as support for Native Express will be discontinued soon we have decided to halt the addition of new features/ API for this ad format.
