### ISSUE TITLE
Current scene paused when returning from banner

### ISSUE THREAD

**Issue by Nepohyte** [googleads/googleads-mobile-unity#540]
When I return from a banner click to the app the current scene remains paused. If I have button on the scene the app resumes when I click on the button but otherwise I have to restart the application. I presume that the main thread is paused when I click on a banner. I have tried to alter Time.timeScale on the banner events to no avail. How do I fix this?

**Comment by rampara** [comment]
@Nepohyte are you experiencing this behavior in the [HelloWorld sample app](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) from this repo as well?

**Comment by rampara** [comment]
Closing due to non-response.
