### ISSUE TITLE
"Lexical or Preprocessor issue: ‘GoogleMobileAds/GoogleMobileAds.h’ file not found"

### ISSUE THREAD

**Issue by Shafeyee** [googleads/googleads-mobile-unity#543]
I'm getting this issue whenever I try to build from xcworkspace ---
"Lexical or Preprocessor issue: ‘GoogleMobileAds/GoogleMobileAds.h’ file not found"

This is similar to #524 and I have tried all the steps from there. Also tried adding the GoogleMobileAds.Framework manually to the xcworkspace, but the error remains. Here is a [picture](https://imgur.com/XtJA6I6) of the issue. Any help would be really appreciated.

Edit: I'm using Unity 2017.1.2f and the latest version of xcode if that helps.

**Comment by rampara** [comment]
@Shafeyee did the xcworkspcace not include the GoogleMobileAds framework before you manually included it?

**Comment by Shafeyee** [comment]
@rampara Thanks for replying. The xcworkspace didn't include the framework. I've seen it work for some people but didn't work for me. I have firebase plugin in my project, but I don't think it should be an issue as I have other projects without firebase where similar problem occurred.

**Comment by rampara** [comment]
@Shafeyee when building for iOS, do you see any output in the Unity console that may indicate why the framework wasn't added to your xcworkspace?

**Comment by Shafeyee** [comment]
@rampara Yes, there seems to be a related error in unity console.

"iOS framework addition failed due to a Cocoapods installation failure. This will will likely result in an non-functional Xcode project.

After the failure, "pod repo update" was executed and failed. "pod install" was then attempted again, and still failed. This may be due to a broken Cocoapods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.

pod install output:

Analyzing dependencies
[!] Unable to find a specification for `Firebase/Auth (= 4.2.0)`"

Looks like my cocoapods installation was a failure. I've uninstalled & reinstalled cocoapods using terminal. Do I have to manually setup podfile? Sorry I'm kinda new to iOS development.

**Comment by Shafeyee** [comment]
Uninstalling & reinstalling cocoapods fixed this issue for me. Now my project successfully builds. Thanks @rampara
