### ISSUE TITLE
XCode 9.0.1 - Parse issue - Module 'GoogleMobileAds' not found

### ISSUE THREAD

**Issue by lambdor** [googleads/googleads-mobile-unity#544]
Since XCode 9.0.1 I'm receiving the error "Parse issue - Module 'GoogleMobileAds' not found". I could successfully build the same project with XCode 8.3.3 and 9.0.0. The workflow is usually to delete old framework, unpack framework again, move into frameworks folder and "Enable C and Obj-C modules: Yes". Since 9.0.0 the framework doesn't automatically get added to frameworks in the settings tab, so I also have to add it there, but the build works.

iOS SDK version 7.11

**Comment by rampara** [comment]
@lambdor the GMA Unity plugin should use Cocoapods to retrieve and integrate the latest version of the GMA iOS SDK when building an iOS project. You shouldn't have to manually update frameworks.

**Comment by rampara** [comment]
Closing this issue due to its age. Please re-open if the issue persists for you.

**Comment by Jeet007das** [comment]
parse issue module HyperTrack not found
