### ISSUE TITLE
The banners do not appear

### ISSUE THREAD

**Issue by Christopher117** [googleads/googleads-mobile-unity#547]
636/5000
I followed a lot of tutorial and it seems to me to do things right, but in spite of efforts I can not display the Admob banner on my Android device.
I tried several versions of the plugin, several versions of Unity and several versions of the SDK, but every time nothing happens.
Yet my Admob test project is very simple, I just run a script to display a banner and I have no compilation error.
Any solution or search path to the problem would be welcome.
Hoping to have been clear on the problem, thanks ;)

My test code :

`using GoogleMobileAds.Api;
using GoogleMobileAds;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AdScript : MonoBehaviour {

	// Use this for initialization
	void Start () {
		showBannerAd ();
	}

	private void showBannerAd()
	{
		string adID = "my Banner ID";

		//***For Testing in the Device***
		AdRequest request = new AdRequest.Builder()
			.AddTestDevice(AdRequest.TestDeviceSimulator)       // Simulator.
			.AddTestDevice("A0E0462BF85FDDA0")  // My test device.
			.Build();

		//***For Production When Submit App***
		//AdRequest request = new AdRequest.Builder().Build();

		BannerView bannerAd = new BannerView(adID, AdSize.Banner, AdPosition.Bottom);
		bannerAd.LoadAd(request);
	}

	// Update is called once per frame
	void Update () {

	}
}`

**Comment by rampara** [comment]
@Christopher117 As this is an integration issue, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
