### ISSUE TITLE
Didn't find class "com.google.android.gms.ads.reward.RewardedVideoAd" 

### ISSUE THREAD

**Issue by LiuYuFenFei** [googleads/googleads-mobile-unity#549]
10-24 18:18:57.715  5849  5873 I Unity   : AndroidJavaException: java.lang.NoClassDefFoundError: com.google.android.gms.ads.reward.RewardedVideoAd
10-24 18:18:57.715  5849  5873 I Unity   : java.lang.NoClassDefFoundError: com.google.android.gms.ads.reward.RewardedVideoAd
10-24 18:18:57.715  5849  5873 I Unity   : 	at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
10-24 18:18:57.715  5849  5873 I Unity   : 	at java.lang.Class.getDexCacheType(Class.java:476)
10-24 18:18:57.715  5849  5873 I Unity   : 	at java.lang.reflect.Method.getReturnType(Method.java:183)
10-24 18:18:57.715  5849  5873 I Unity   : 	at java.lang.Class.getDeclaredMethods(Class.java:672)
10-24 18:18:57.715  5849  5873 I Unity   : 	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source)
10-24 18:18:57.715  5849  5873 I Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
10-24 18:18:57.715  5849  5873 I Unity   : 	at com.unity3d.player.UnityPlayer.a(Unknown Source)
10-24 18:18:57.715  5849  5873 I Unity   : 	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
10-24 18:18:57.715  5849  5873 I Unity   : 	at android.os.Handler.dispatchMessage(Handler.java:98)
10-24 18:18:57.715  5849  5873 I Unity   : 	at android.os.Looper.loop(Looper.java:148)
10-24 18:18:57.715  5849  5873 I Unity   : 	at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
10-24 18:18:57.715  5849  5873 I Unity   : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.reward.RewardedVideoAd" on path: DexPathList[[zip file "/data/app/com.hk.pixelrunsurfer-1/base.apk"],na
10-24 18:18:57.812  5849  5849 E AndroidRuntime: FATAL EXCEPTION: main
10-24 18:18:57.812  5849  5849 E AndroidRuntime: Process: com.hk.pixelrunsurfer, PID: 5849
10-24 18:18:57.812  5849  5849 E AndroidRuntime: java.lang.Error: FATAL EXCEPTION [main]
10-24 18:18:57.812  5849  5849 E AndroidRuntime: Unity version     : 5.5.2f1
10-24 18:18:57.812  5849  5849 E AndroidRuntime: Device model      : LGE Nexus 5X
10-24 18:18:57.812  5849  5849 E AndroidRuntime: Device fingerprint: google/bullhead/bullhead:6.0/MDA89E/2296692:user/release-keys
10-24 18:18:57.812  5849  5849 E AndroidRuntime:
10-24 18:18:57.812  5849  5849 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/MobileAds;
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 	at com.google.unity.ads.RewardBasedVideo$1.run(RewardBasedVideo.java:65)
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-24 18:18:57.812  5849  5849 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.MobileAds" on path: DexPathList[[zip file "/data/app/com.hk.pixelrunsurfer-1/base.apk"],nativeLibraryDirectories=[/data/app/com.hk.pixelrunsurfer-1/lib/arm, /data/app/com.hk.pixelrunsurfer-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 	... 8 more
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.ads.MobileAds
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 		... 9 more
10-24 18:18:57.812  5849  5849 E AndroidRuntime: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
10-24 18:18:57.813   880  3532 W ActivityManager:   Force finishing activity com.hk.pixelrunsurfer/com.unity3d.player.UnityPlayerActivity
10-24 18:18:57.897   880  2819 I OpenGLRenderer: Initialized EGL, version 1.4
10-24 18:18:58.336   880   893 W ActivityManager: Activity pause timeout for ActivityRecord{4be6b33 u0 com.hk.pixelrunsurfer/com.unity3d.player.UnityPlayerActivity t385 f}
10-24 18:18:58.361   880  2815 I InputReader: Reconfiguring input devices.  changes=0x00000004
10-24 18:18:58.362   880  2815 I InputReader: Device reconfigured: id=7, name='synaptics_rmi4_i2c', size 1080x1920, orientation 0, mode 1, display id 0
10-24 18:18:58.362   880   893 I ActivityManager: Config changes=480 {1.0 ?mcc?mnc zh_CN ldltr sw411dp w411dp h659dp 420dpi nrml port finger -keyb/v/h -nav/h s.613}
10-24 18:18:58.701   880   898 I WindowManager: Screen frozen for +356ms due to Window{62740b8 u0 com.android.systemui.ImageWallpaper}
10-24 18:19:00.713   880   898 I art     : Starting a blocking GC Explicit
10-24 18:19:00.813   880   898 I art     : Explicit concurrent mark sweep GC freed 3664(192KB) AllocSpace objects, 0(0B) LOS objects, 33% free, 27MB/41MB, paused 1.326ms total 99.552ms

**Comment by rampara** [comment]
@LiuYuFenFei based on the logcat snippet you provided, it looks like you're not including the Google Mobile Ads SDK in your Unity project. However, as this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.

**Comment by LiuYuFenFei** [comment]
The interstitial ad can be displayed properly, but the reward video can not be requested. Sorry, the language comes from Google Translate.

**Comment by rampara** [comment]
@LiuYuFenFei are you using an outdated version of Google Play services?
