### ISSUE TITLE
Since 3.7.1 ads don't show on Galaxy Tab 2

### ISSUE THREAD

**Issue by iseeall** [googleads/googleads-mobile-unity#550]
No ads are shown anymore on Samsung Galaxy Tab 2 (tested on version 3.7.1 and 3.8.0). With plugin version 3.5.0 the ads were loading and showing fine. 
The ads do show fine on a few other, more modern devices where I tested. 
Is simply the device too old? Are there any  minimum requirement for the current AdMob version: Android OS version, hardware specs? 
I'm attaching screenshots of logcat. 

![admob_3 8 0_galaxytab2](https://user-images.githubusercontent.com/8617651/31956467-3d9eff74-b8f4-11e7-88c4-06167c729c26.PNG)
![admob_3 8 0_galaxytab2_1](https://user-images.githubusercontent.com/8617651/31956468-3dbce566-b8f4-11e7-98d7-0ec9df12b068.PNG)
![admob_3 8 0_galaxytab2_2](https://user-images.githubusercontent.com/8617651/31956469-3ddf54de-b8f4-11e7-82c6-d9bd50f057c2.PNG)

Thanks

**Comment by iseeall** [comment]
Seems like Firebase initialization is crashing because of missing AppMeasurement on this specific device (I've seen messages about AppMeasurement on a few other plugins previously while testing on Galaxy Tab 2).
Though AppMeasurement itself is deprecated, why is it even called...
https://developers.google.com/android/reference/com/google/android/gms/measurement/AppMeasurement

**Comment by rampara** [comment]
@iseeall you can ignore the Firebase warning, it's just log spam that will be cleaned up in a future release of the GMA Ads SDK. Are you able to reproduce the issue of the ads not showing on any other device (other than the Galaxy Tab 2) ?

**Comment by iseeall** [comment]
Oh ok. Actually, I've tried restarting the device and the ads show fine now. This seems to be an issue on Galaxy Tab 2 which I have been seeing for years with AdMob. Sometimes the device will get into a state where it will never show AdMob anymore, even though there is an internet connection available. It may be just a problem with the device itself.
Sorry for the confusion, I was mislead by the outdated error message.
I guess you can just close the issue since it isn't even specific to this version of the AdMob SDK and is largely outdated...

**Comment by rampara** [comment]
@iseeall closing issue as it's not related this plugin.
