### ISSUE TITLE
Xcode 9, Unity 2017, Build errors for iOS

### ISSUE THREAD

**Issue by kunal2619** [googleads/googleads-mobile-unity#551]
I am trying to implement admob ads in my project targeted to build for iOS platform. I am facing the errors mentioned below in xCode while building,

```
Unknown type name 'GADNativeExpressAdView'; did you mean 'GADUNativeExpressAd'?

ARC Semantic Issue
No known class method for selector 'configureWithApplicationID:'
```

I tried setting 'Enable Modules' to yes and pods folder contains the GoogleMobileAds.framework as well. Moreover, I also tried building the Hello World project from the samples and it throws the same errors. I'll be glad if anyone can help me complete the build process?

**Comment by rampara** [comment]
@kunal2619 it looks like the GMA iOS SDK what not included in your generated iOS project. As this is a plugin integration issue, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
