### ISSUE TITLE
Banner always on top if you show it back

### ISSUE THREAD

**Issue by leoHN** [googleads/googleads-mobile-unity#554]
I can reproduce the bug:
- Create BannerView and show it at bottom
- Hide that banner by bannerView.Hide() method
- Show it back by bannerView.Show() method (without creating another instance of banner). It always appear at top.

**Comment by thanh-nguyen-kim** [comment]
I have the same problem in unity 5.4.1p1 and admob 3.8.0

**Comment by duchanhleo** [comment]
@thanh-nguyen-kim do you know any solution for that bug?

**Comment by thanh-nguyen-kim** [comment]
destroy old one and request new one or downgrade to lowwer version

**Comment by hanhnd76** [comment]
destroy banner view can't help. It will return error "No Fill" after one or two requests.
which version you are using that not include that bug?

**Comment by rampara** [comment]
@thanh-nguyen-kim @duchanhleo what devices are you able to reproduce this issue with. Banners continue to remain in the specified position for with the latest version of the plugin.

**Comment by thanh-nguyen-kim** [comment]
i'm using Xiaomi mi4c with admob plugin version 3.8.0, fire base 4.2.1 and currently using google play resolved version 1.2.59.0.
At the first time i show the banner, it displays correctly at the bottom. When i call HideBanner() function, I show a glitch "Banner display in the top and after 1 frame it disappear". The next time i call ShowBanner(), my banner will display at top of the screen

**Comment by duchanhleo** [comment]
I'm getting same issue with Galaxy S7 Edge and Sony Z3 plus.

**Comment by rampara** [comment]
A fix for this issue has been implemented in the latest version of this plugin (v3.9.0).
