### ISSUE TITLE
Slow rendering >5% in Android vitals

### ISSUE THREAD

**Issue by iseeall** [googleads/googleads-mobile-unity#557]
Hi! I have this game 
https://play.google.com/store/apps/details?id=com.twoplayergamesfree.twoplayergames
using Unity with AdMob, and no other plugins using UI Toolkit.
Since introduction of Android vitals on GooglePlay I'm seeing "Slow rendering" as constant source of ranking penalty. At times slow rending was 10% or even up to 15%, with plugin version 3.8.0 and Unity 2017.2 it's now around 5% (attaching screenshot).
Is AdMob really causing this? Did you notice this while testing? 
I have a guess that my game is simply played on too many older devices where slow rendering is simply caused by a slower processor (?)
I have no idea how to test UI rendering time, or if it all this can be tested in a Unity game because Unity renders in OpenGL.
![slowrendering](https://user-images.githubusercontent.com/8617651/32336766-398ba57c-c001-11e7-8368-a214ec8c5580.PNG)

**Comment by iseeall** [comment]
Another screenshot with more details
![slowrendering_details](https://user-images.githubusercontent.com/8617651/32336885-94116306-c001-11e7-8421-1a743059a0b3.PNG)

**Comment by iseeall** [comment]
Also a comparison of Android versions:
![slowrendering_androidversions](https://user-images.githubusercontent.com/8617651/32337083-1789c69c-c002-11e7-85e2-bb680eec7369.PNG)

Are animated banners causing this? Or video interstitials?

**Comment by ZhaoTianze** [comment]
I have same issue. 

What advice does the development team have?

**Comment by ZhaoTianze** [comment]
Other discussions:
https://www.reddit.com/r/androiddev/comments/78z6wv/google_play_search_algorithm_may_be_wrongly/

https://forums.coronalabs.com/topic/70688-android-vitals-and-slow-rendering/

https://forum.unity.com/threads/do-android-vitals-slow-rendering-statistics-show-on-your-developer-console.501799/

https://forum.unity.com/threads/do-android-vitals-slow-rendering-statistics-show-on-your-developer-console.501799/

**Comment by iseeall** [comment]
@ZhaoTianze Thanks for the links!
Here https://forums.coronalabs.com/topic/70688-android-vitals-and-slow-rendering/
the guy says that a Google's representative said slow rendering doesn't count in rankings if they are caused by "edge cases" (like ads).
@rampara Would be great to have an official confirmation on this. Could you please ask your colleagues at other teams within Google about this? Or actually the dev console team could find a way to adjust how the numbers are shown.

If the apps are indeed punished for showing AdMob bunners it would be a funny situation indeed: Google punishing for using its own SDK. As a quick fix I could think of switching to UnityAds at least for the interstitials (if the interstitials are causing the slow rendering metric, which I doubt). But with the banners, any banners would probably cause slow rendering? (FAN, MMedia also don't have comparable fill rate) 
If all apps with ad banners are now punished, this essentially discourages monetization with ads entirely. A huge blow to Google's own revenues. If that's the case, it's something Google should address internally asap. But I guess it's just too unlikely. More like, the dev console is showing inaccurate values, and all Unity games publishers should ignore that yellow exclamation mark.

**Comment by ZhaoTianze** [comment]
@rampara 

ignore this issue?

**Comment by rampara** [comment]
After speaking to the Android vitals team, I was able confirm that Google is unable to collect frame render times when Open GL is used directly (as with Unity apps). However, currently rendering data is not used for app ranking. The Android team plans to make announcements in the near future about Android vitals and what data is used.

**Comment by iseeall** [comment]
@rampara Thank you very much for the update
