### ISSUE TITLE
The Ads close if the players press back button

### ISSUE THREAD

**Issue by rachidev84** [googleads/googleads-mobile-unity#561]
It's was 1 week when I use the admob and I succesful to display ads in my game but if I press back button the ads will close without waiting 5 seconds.

**Comment by rampara** [comment]
@rachidev84 this behavior is determined by the Google Mobile Ads SDK and not this plugin. To raise concerns about SDK behavior, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
