### ISSUE TITLE
feature request: dynamic position change for banner view

### ISSUE THREAD

**Issue by rchallenger** [googleads/googleads-mobile-unity#563]
Is it possible to avoid multiple banner requests for those situations, when some number of short scenes require the banner to be placed in some specific position, which is different from previous one (eg: to avoid content overlap)? Usually we use banner auto refresh.
Today all we can do to move banner is creating new one and requesting it again.

PS: old NeatPlug plugin could do that perfect, even mediating other networks.

**Comment by rampara** [comment]
We're currently looking into implementing this feature.

**Comment by rampara** [comment]
@rchallenger an API for this feature has been added in the latest version of this plugin (v.3.10.0).

**Comment by rchallenger** [comment]
3.10.0 has trouble when display orientation is changed:
portrait > landscape - banner is hidden and no event about it is unavailable was generated;
landscape > portrait - banner changes its place from bottom_centered to middle_right.
landscape > portrait > landscape - banner changes its place from bottom_right to middle_right, and turns back to bottom_center shifted to the left (rare occasion)

**Comment by rchallenger** [comment]
Also there is no methods to get size in pixels for NativeAdView.
SetPosition method also missing for this ad type.
