### ISSUE TITLE
ios: after close the interstitial video ad, the game sound will be set muted.

### ISSUE THREAD

**Issue by zhouguangjie** [googleads/googleads-mobile-unity#565]

**Comment by rampara** [comment]
@zhouguangjie can you provide a test app that reproduces this behavior?

**Comment by zhouguangjie** [comment]
@rampara 
here is the key code, it's just like the demo code, and i use a oc bridge fix this issue
fix:
`
#include <GoogleMobileAds/GADAudioVideoManager.h>
#include <GoogleMobileAds/GADMobileAds.h>

void _iOSAdmobFixAudioMutedIssue() {
    [[GADMobileAds sharedInstance]audioVideoManager].audioSessionIsApplicationManaged = true;
}

`

admob key code:
`
public void RequestInterstitial ()
	{

		// Clean up interstitial ad before creating a new one.
		if (this.interstitial != null) {
			this.interstitial.Destroy ();
		}

		// Create an interstitial.
		this.interstitial = new InterstitialAd (admobConfig.interstitialPlacement);

		// Load an interstitial ad.
		this.interstitial.LoadAd (this.CreateAdRequest ());
	}

public bool ShowInterstitial ()
	{
		if (this.interstitial.IsLoaded ()) {
			this.interstitial.Show ();
			return true;
		} else {
			return false;
		}
	}
`

**Comment by rampara** [comment]
@zhouguangjie still having trouble reproducing this on my end. Would you be able to provide a test app ?

**Comment by zhouguangjie** [comment]
It seems everything is ok. I remove my fix code, and there are no more problem raise.

**Comment by rampara** [comment]
@zhouguangjie glad to hear your problem has been resolved.

**Comment by PEZO19** [comment]
I had the same problem (muted app after admob ad close) with my Unity project when I updated to Xcode 10 from 9.4 (from High Sierra to Mojave). After updating to the latest GoogleMobileAds unity plugin it has been solved.
