### ISSUE TITLE
Ready for iphone x?

### ISSUE THREAD

**Issue by ceceomer** [googleads/googleads-mobile-unity#566]
Admob has released a policy update for iPhone x and Admob said that we should be ready for iphone x. Is this plugin ready for iPhone X?
![iphonex](https://user-images.githubusercontent.com/10334894/32835070-c78ac34e-ca15-11e7-8745-a16d749a6502.png)

**Comment by stowy** [comment]
Hi @ceceomer, thanks for asking! The latest versions of the plugin - 3.8.0 and 3.9.0 - have support for positioning ads in the safe area, using the standard positions (top left, bottom right, etc). So if you are using banner ads, we recommend positioning them using the standard positions.

The GoogleMobileAds iOS SDK itself will have another release this week, which will complete the support for Interstitial and Rewarded Video ads. 

As long as you are using standard positions for your banner ads (and native ads where applicable), with plugin version 3.8.0 or later, and keep the GoogleMobileAds pod up to date when releasing your apps, then you are ready for iPhone X. 

If you are using custom ad positions, we recommend checking them on an iPhone X simulator to check that they are rendering in the safe area.
