### ISSUE TITLE
Test Ad is showing, but real ad is not showing at all

### ISSUE THREAD

**Issue by Guyleung** [googleads/googleads-mobile-unity#567]
I am using the "GoogleMobileAdsDemoScript.cs", i follow every step to setting up the scene, when i test on the devices, the test ad is showing , but when i plug in to my real ad, nothing happen, may i know what's going on?

Test APP ID : ca-app-pub-1005045795524431~8618733653
Test Banner AD ID : ca-app-pub-1005045795524431/6772311278
Test Interstitial : ca-app-pub-1005045795524431/8088621743

Console: no error, no warning
Minium API level: android 4.1
Target API level : auto
Android SDK : tools_r25.2.5-windows
JDK : jdk1.8.0_151

**Comment by rampara** [comment]
@Guyleung as test ads are working without issue, the issue likely lies with your ad placements/ ad units. As this issue tracker is strictly for bugs related to this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
