### ISSUE TITLE
 `Gender' does not contain a definition for `Unknown'

### ISSUE THREAD

**Issue by armnotstrong** [googleads/googleads-mobile-unity#574]
Assets/GoogleMobileAds/Platforms/Android/Utils.cs(141,33): error CS0117: `Gender' does not contain a definition for `Unknown'

**Comment by armnotstrong** [comment]
It seems that the Gender enum has conflict with another plugin we are using, have created a [pull request](https://github.com/googleads/googleads-mobile-unity/pull/575) to fix this

**Comment by rampara** [comment]
@armnotstrong shouldn't this not be an issue since the `Gender` enum is part of the `GoogleMobileAds.Api` namespace?

**Comment by rampara** [comment]
Closing due to non-response.
