### ISSUE TITLE
Unable to configure Payments

### ISSUE THREAD

**Issue by quantumproducer** [googleads/googleads-mobile-unity#577]
Hello, I'm getting errors trying to configure Payments on the website.

I'm posting here because I need to reach a Human Being who can relay the bug to the right team.

![kxbizvcr](https://user-images.githubusercontent.com/11827932/33459141-e41d57fa-d5f6-11e7-8052-faf8dd2a1f80.png)

Javascript console:
```
buy_flow Failed to load resource: the server responded with a status of 401 ()
17:45:57.331 buy_flow?wst=1512081957134&cst=1512081957148&ipi=amlixp6tcpp9&hostOrigin=aHR0cHM6Ly9hcHBzLmFkbW9iLmNvbQ..&mm=e&hl=en_US&style=%3Amd&cn=%24p_od0w06qiyub10:151  [  0.007s] [goog.net.xpc] CrossPageChannel created: $p_od0w06qiyub10
17:46:00.522 DevTools failed to parse SourceMap: https://apps.admob.com/v2/payments/material_ripple.scss.css.map
```

**Comment by rampara** [comment]
As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
