### ISSUE TITLE
Admob Banner ads are not showing

### ISSUE THREAD

**Issue by pta271996** [googleads/googleads-mobile-unity#578]
OK I've tried the latest admob and google play services plugin 3.9.0 and the version 3.4.0 and had the same error in the logcat : 
E/Unity   ( 8155): AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.AdSize
E/Unity   ( 8155): java.lang.ClassNotFoundException: com.google.android.gms.ads.AdSize
E/Unity   ( 8155):      at java.lang.Class.classForName(Native Method)
E/Unity   ( 8155):      at java.lang.Class.forName(Class.java:308)
E/Unity   ( 8155):      at java.lang.Class.forName(Class.java:272)
E/Unity   ( 8155):      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
E/Unity   ( 8155):      at com.unity3d.player.UnityPlayer.c(Unknown Source)
E/Unity   ( 8155):      at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
E/Unity   ( 8155):      at android.os.Handler.dispatchMessage(Handler.java:98)
E/Unity   ( 8155):      at android.os.Looper.loop(Looper.java:145)
E/Unity   ( 8155):      at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
E/Unity   ( 8155): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.AdSize" on path: DexPathList[[zip file "/data/app/com.a.a-1/base.apk"],nativeLibraryDirectories=[/data/app/com.a.a-1/lib/arm, /vendor/lib, /system/lib]]
E/Unity   ( 8155):      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/Unity   ( 8155):      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/Unity   ( 8155):      at java.l
///////////////////////////////////////////////
my code to display banner ads : 
public class AdManager : MonoBehaviour {

    void Start()
    {
        RequestBanner();
    }

    public void RequestBanner()
    {
        string adUnitId = "ca-app-pub-3940256099942544/6300978111";

        //***For Testing in the Device***
        AdRequest request = new AdRequest.Builder()
       .AddTestDevice(AdRequest.TestDeviceSimulator)       // Simulator.
       .AddTestDevice("6BC81F06817BFD3CBEA5D1F75C6621E7") // My test device.
       .Build();
        
        BannerView bannerView = new BannerView(adUnitId, AdSize.Banner, AdPosition.Top);

        bannerView.LoadAd(request);

        bannerView.Show();    
    }

Please show me some workarounds I been spending lot of times and couldn't fix this!!

**Comment by rampara** [comment]
@pta271996 based on the stack trace you provided, it looks like you are not including the required Google Play services AARs in the `Assets/Plugins/Android` directory of your Android project. As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
