### ISSUE TITLE
Banner ads not showing anymore

### ISSUE THREAD

**Issue by jdelange** [googleads/googleads-mobile-unity#579]
I had Admob working, then I installed the Google Play plugin and then I could not get Admob working again. All compiles and builds onto the Android device, but no ads are shown. Trying to resolve the issue, I did following:

1. Upgrade to VS2017
2. Upgrade to Unity 2017.2.0f3
3. Updated Android Studio: SDK tools 26.1.1, SDK platform tools 26.0.2
4. Downloaded and re-imported mobile Ads unity package to V3.9.0
5. Rebuilt and loaded following sample application [Get started](https://developers.google.com/admob/unity/start)

```
public class AdManager : MonoBehaviour {

    private BannerView bannerView;

    // Use this for initialization
    void Start ()
    {
#if UNITY_ANDROID
        string appId = " my appId here ";
#else
        string appId = "unexpected_platform";
#endif
        // Initialize the Google Mobile Ads SDK.
        MobileAds.Initialize(appId);

        this.RequestBanner();
    }

    private void RequestBanner()
    {
#if UNITY_ANDROID        
        string sampleAdUnitId = "ca-app-pub-3940256099942544/6300978111";
#else
        string sampleAdUnitId = "unexpected_platform";
#endif

        // Create a 320x50 banner at the top of the screen.
        bannerView = new BannerView(sampleAdUnitId, AdSize.Banner, AdPosition.Top);

        // Create an empty ad request.
        AdRequest request = new AdRequest.Builder().Build();

        // Load the banner with the request.
        bannerView.LoadAd(request);
    }
}

Attached is a dump of the Logcat taken with Android Studio from my Samsung phone, Verbose, sorted on keyword "Ads". This is my first time Logcat, so if something is missing, let me know.

Why are my ads not shown? Really appreciate your effort in creating this plugin. Hope you can help me out. Thanks, Jan

[Admob test logcat dump 5-12.txt](https://github.com/googleads/googleads-mobile-unity/files/1532549/Admob.test.logcat.dump.5-12.txt)

**Comment by rampara** [comment]
@jdelange based off the logcat dump you provided, it seems your device does not have full network connectivity and was unable to load the ad creative. As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
