### ISSUE TITLE
[Ios] Reward Sample Ads ID works but mine doesn't

### ISSUE THREAD

**Issue by alaslipknot** [googleads/googleads-mobile-unity#580]
Hello, 

Banner and Interstitial works fine using the Test IDs, but the RewardAds doesn't giving this error : 

```
Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
ADMOB - OnRewardedVideoFailedToLoad - error = GoogleMobileAds.Api.AdFailedToLoadEventArgs
AppAdvisory.Ads.AAAdmob:OnRewardedVideoFailedToLoad(Object, AdFailedToLoadEventArgs)
```

While on Android All Test Ads works, but in the other hand, my Ads ID which is using AdMob mediation doesn't work and it gives me this error : 

```
ADMOB - OnRewardedVideoFailedToLoad - error = GoogleMobileAds.Api.AdFailedToLoadEventArgs
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
AppAdvisory.Ads.AAAdmob:OnRewardedVideoFailedToLoad(Object, AdFailedToLoadEventArgs)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
UnityEngine.AndroidJavaProxy:Invoke(String, Object[])
UnityEngine._AndroidJNIHelper:InvokeJavaProxyMethod(AndroidJavaProxy, IntPtr, IntPtr)
```

Here is the game dashboard : 

![image](https://user-images.githubusercontent.com/4387645/33636752-dd6d5a56-da1d-11e7-9f36-23285fc3c164.png)

![image](https://user-images.githubusercontent.com/4387645/33636812-15d01d98-da1e-11e7-8d8c-907d27f73e44.png)

![image](https://user-images.githubusercontent.com/4387645/33636820-28d12eaa-da1e-11e7-910b-ac1dfa6388af.png)

Thank you!

**Comment by rampara** [comment]
@alaslipknot as both issues you're facing are not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
