### ISSUE TITLE
Some times AdMob rewarded video ad failed to load.

### ISSUE THREAD

**Issue by mechwarr** [googleads/googleads-mobile-unity#582]
I used the plugin version 3.9.0 , and update the Google Mobile Ads SDK framework v7.26.0, device is iOS 11 beta v4 ,and used EasyMobile Plugin on Unity last version , the same c # script android all no problem , but when I build to iOS alway show load admob rewarded failed delegate event,very few times will load success.
ps. 1. when used test device mode will always work.
2. I don't think this error from EasyMobile plugin.
I dont understand why get this error.

**Comment by rampara** [comment]
@mechwarr what error code are you receiving when the ad fails to load?

**Comment by mechwarr** [comment]
@rampara 
I always got the error message is "rewarded video ad failed to load." , I think this is not get video source.
I dont know why it worked automatically after a few days now.

**Comment by rampara** [comment]
@mechwarr glad to hear the issue has been resolved for you.
