### ISSUE TITLE
Rewarded video did not Show on Device.

### ISSUE THREAD

**Issue by khalilhoti** [googleads/googleads-mobile-unity#585]
Hi, I integrate both interstitial and rewarded video in my game. Interstitial works good loaded and also shown on device but Rewarded video only load mean in console it show dummy ad loaded and also show dummy load but on device it can't show any rewarded video.. I download hello world example it also did not show rewarded video. So what i did wrong?

**Comment by rampara** [comment]
@khalilhoti As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
