### ISSUE TITLE
3.10.0 banner has wrong position when display orientation is changed

### ISSUE THREAD

**Issue by rchallenger** [googleads/googleads-mobile-unity#586]
3.10.0 has trouble when display orientation is changed:
landscape > portrait:
banner changes its place from bottom in landscape to middle in portrait.
bottom_right & bottom_center position in landscape cause banner to move to the middle_right in portrait.
bottom_left position of banner is changed to middle_left.

portrait > landscape:
top_center & top_right in portrait switches to top_left in landscape with small padding (80% from 320x50 banner height )
bottom_center, bottom_right or bottom_left in portrait cause hiding banner in landscape and no event about it became unavailable was generated, show/hide banner methods won't make it visible again in landscape (changing orientation back to portrait makes banner visible), probably it has same bug, but in landscape banner is hidden behind the screen.

PS: haven't tried middle positions (we don't use them at all).

**Comment by rampara** [comment]
@rchallenger a fix for this issue will make it into the next release for this plugin.

**Comment by rampara** [comment]
This should be fixed in the latest version of the plugin (v3.11.0).
