### ISSUE TITLE
AdMob banner ad not showing!

### ISSUE THREAD

**Issue by nikolaev013** [googleads/googleads-mobile-unity#587]
Hello everyone!

I need some help. Our game is almost done and one of the last things that are left are adding some ads to it. I've done it before and it works in other of our games. But now the banner ad isn't showing at all! I haven't tried with interstitial ads or rewarded videos yet. It is working in the editor (I'm getting the "Dummy Initialize", "Dummy LoadAd", "Dummy CreateBannerView"), but not on an actual android device. It isn't working with test ads either!

First I'm initialising in with the script:

`using System.Collections; 
using System.Collections.Generic; 
using UnityEngine; 
using GoogleMobileAds; 
using GoogleMobileAds.Api;

public class InitialiseAds : MonoBehaviour {

 // Use this for initialization
 void Start () {
if UNITY_ANDROID
    string appId = "ca-app-ID...";
elif UNITY_IPHONE
        string appId = "ca-app-ID...";
else
        string appId = "unexpected_platform";
endif
     // Initialize the Google Mobile Ads SDK.
     MobileAds.Initialize(appId);
 }
 
}
`
and then after that script I'm creating and loading the banner ad through that script:

`using System.Collections; 
using System.Collections.Generic; 
using UnityEngine; 
using GoogleMobileAds;
using GoogleMobileAds.Api;

public class BannerScript : MonoBehaviour {

 private BannerView bannerView;
 
 // Use this for initialization
 void Start () {
     this.RequestBanner();
 }
 private void RequestBanner()
 {
if UNITY_ANDROID
        string adUnitId = "ca-app-pub-unitID";
elif UNITY_IPHONE
        string adUnitId = "ca-app-pub-unitID";
else
    string adUnitId = "unexpected_platform";
endif
     // Create a 320x50 banner at the top of the screen.
     bannerView = new BannerView(adUnitId, AdSize.Banner, AdPosition.Top);
     // Create an empty ad request.
     AdRequest request = new AdRequest.Builder().Build();
     // Load the banner with the request.
     bannerView.LoadAd(request);
 }
}`

Unity version: 2017.2.0f3 
Google AdMob version: 3.10.0 ( also tried with 3.7.1 )

Thank you in advance and have a great holidays! :)

**Comment by rchallenger** [comment]
if UNITY_ANDROID
such directives should be written with # symbol - #if, #elif , #endif

bannerView.LoadAd shouldn't show ad immediately.
In request builder you should sign up for banner events (OnAdLoaded, etc). In your callbacks you can manage making banner visible and invisible as it is loaded. Or just call bannerView.Show()

**Comment by nikolaev013** [comment]
Hi again! 

1st: The directives, you mentioned all have the "#" symbol, I don't know why they haven't appeared when I pasted the code in here.

2nd: I've added banner events and on the OnAdLoaded I've called the bannerView.Show() function and it isn't showing on my android tablet (again - it is working in the Editor)..

Could it be a problem with my AdMob account? Or some of the settings of the AdMob? Because our other games has a working banner, interstitial and rewarded video ads and I've done everything the same in this particular game. 

I just want to mention that the other games were built on a separate PC, and this is the first time I'm working on a project on my laptop.

I've attached the two scripts in txt format.

Thank you very much! 

[BannerScript.txt](https://github.com/googleads/googleads-mobile-unity/files/1589048/BannerScript.txt)
[InitialiseAds.txt](https://github.com/googleads/googleads-mobile-unity/files/1589049/InitialiseAds.txt)

**Comment by rchallenger** [comment]
you should use test values for ad placements:
banner - "ca-app-pub-3940256099942544/6300978111"
interstitial - "ca-app-pub-3940256099942544/4411468910"

**Comment by rampara** [comment]
@nikolaev013 as rchallenger mentioned, the first step to debugging why ads are not showing would be registering for the `OnAdFailedToLoad` ad event. However, as this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
