### ISSUE TITLE
Which Version will be Obsolete?

### ISSUE THREAD

**Issue by binarybehemoth** [googleads/googleads-mobile-unity#588]
When I got back to Google Admob Console I received this announcement:

"Beginning on 23 Jan 2018, Google Mobile Ads SDK versions older than 7.0.0 for Android and 7.0.0 for iOS will no longer be supported. Publishers with these older versions will not be able to serve ads in their apps(s). Please ensure that you have upgraded to the latest version of the Google Mobile Ads SDK."

I am concerned about whether the Unity game I released eight months ago will continue to serve Admob ads.

I think this pertains to many Unity developers. It seems that the Google Mobile Ads for Unity uses a different versioning system. 

So what is the latest version of Admob Unity Plugin that will be affected by this? Will we be affected at all?

Thanks. Merry Christmas.

**Comment by arcv** [comment]
You can check [https://github.com/googleads/googleads-mobile-unity/blob/master/ChangeLog.txt](changelog.txt) file for Google Mobile SDK version. 

If you are using Google Ads Unity 3.0.0 or newer, you will not be affected by this.

**Comment by rampara** [comment]
@binarybehemoth as arcv mentioned, if you're using a version of this plugin newer than v3.0.0, you will not be affected by this.
