### ISSUE TITLE
No fill issue for rewarded video ad 

### ISSUE THREAD

**Issue by araintechno** [googleads/googleads-mobile-unity#591]
Hi,
I am developing a game in unity 5.6.4f1 and i want to use rewarded video ads.But rewarded video ads are not working for both test ids and original ids, I always receive a error of "no fill" while loading the video ad.I also tried sample project but it also did not wok. I am using admob version 3.10.0

**Comment by rampara** [comment]
@araintechno are you running into this issue on Android, iOS or on both platforms. Do you see any content in the logs that may indicate why ads not not loading successfully?

**Comment by araintechno** [comment]
If i change my location to France or USA through VPN on android device then it works otherwise it does not work.

**Comment by rampara** [comment]
@araintechno As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
