### ISSUE TITLE
v 3.10: CommandInvokationFailure: Unable to convert classes into dex format

### ISSUE THREAD

**Issue by smaritem** [googleads/googleads-mobile-unity#596]
Dear Sir or Madam,

I have installed the new version 3.10 of the package and I get all the time this error

CommandInvokationFailure: Unable to convert classes into dex format.
C:/Program Files/Java/jdk1.8.0_31\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/MyPC/AppData/Local/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[

trouble writing output: Too many field references to fit in one dex file: 71292; max is 65536.
You may try using multi-dex. If multi-dex is enabled then the list of classes for the main dex list is too large.
References by package:
1 android.accounts
29 android.app
1 android.content
37 android.content.pm
10 android.content.res
2 android.database
48 android.graphics
5 android.hardware
1 android.location
10 android.media
1 android.media.browse
2 android.net
6 android.net.wifi
3 android.opengl
44 android.os
3 android.print
2 android.provider
13 android.support.annotation
1993 android.support.compat
1993 android.support.coreui
1993 android.support.coreutils
2095 android.support.customtabs
1993 android.support.fragment
2152 android.support.graphics.drawable
1993 android.support.graphics.drawable.animated
1993 android.support.mediacompat
1993 android.support.v4
13 android.support.v4.accessibilityservice
17 android.support.v4.animation
885 android.support.v4.app
114 android.support.v4.content
1 android.support.v4.content.pm
1 android.support.v4.content.res
11 android.support.v4.graphics
41 android.support.v4.graphics.drawable
4 android.support.v4.hardware.display
12 android.support.v4.hardware.fingerprint
10 android.support.v4.internal.view
388 android.support.v4.media
379 android.support.v4.media.session
10 android.support.v4.net
19 android.support.v4.os
63 android.support.v4.print
10 android.support.v4.provider
55 android.support.v4.text
6 android.support.v4.text.util
118 android.support.v4.util
434 android.support.v4.view
138 android.support.v4.view.accessibility
8 android.support.v4.view.animation
495 android.support.v4.widget
409 android.support.v7.app
1993 android.support.v7.appcompat
1993 android.support.v7.cardview
8 android.support.v7.content.res
18 android.support.v7.graphics.drawable
1 android.support.v7.text
2 android.support.v7.transition
77 android.support.v7.view
249 android.support.v7.view.menu
856 android.support.v7.widget
5 android.text
1 android.text.util
15 android.util
15 android.view
8 android.view.accessibility
7 android.webkit
20 android.widget
2 bitter.jnibridge
158 bolts
2007 com.android.vending.billing
2027 com.everyplay.Everyplay
19 com.everyplay.Everyplay.a
16 com.everyplay.Everyplay.b
154 com.everyplay.Everyplay.c
67 com.everyplay.Everyplay.c.a
137 com.everyplay.Everyplay.communication
13 com.everyplay.Everyplay.communication.a
19 com.everyplay.Everyplay.communication.b
26 com.everyplay.Everyplay.communication.c
1 com.everyplay.Everyplay.communication.d
15 com.everyplay.Everyplay.communication.socialnetworks
40 com.everyplay.Everyplay.communication.upload
33 com.everyplay.Everyplay.d
33 com.everyplay.Everyplay.device
30 com.everyplay.Everyplay.e
85 com.everyplay.Everyplay.encoding
4 com.everyplay.Everyplay.unity
252 com.everyplay.Everyplay.view
12 com.everyplay.Everyplay.view.a
26 com.everyplay.Everyplay.view.auth
39 com.everyplay.Everyplay.view.browser
155 com.everyplay.Everyplay.view.videoplayer
284 com.everyplay.Everyplay.view.videoplayer.a
55 com.everyplay.external.aspectj.internal.lang.reflect
13 com.everyplay.external.aspectj.lang
19 com.everyplay.external.aspectj.lang.reflect
1 com.everyplay.external.aspectj.runtime
5 com.everyplay.external.aspectj.runtime.internal
5 com.everyplay.external.aspectj.runtime.internal.cflowstack
46 com.everyplay.external.aspectj.runtime.reflect
16 com.everyplay.external.iso
476 com.everyplay.external.iso.boxes
48 com.everyplay.external.iso.boxes.apple
6 com.everyplay.external.iso.boxes.dece
142 com.everyplay.external.iso.boxes.fragment
8 com.everyplay.external.iso.boxes.mdat
105 com.everyplay.external.iso.boxes.sampleentry
25 com.everyplay.external.iso.boxes.threegpp26244
24 com.everyplay.external.iso.boxes.vodafone
39 com.everyplay.external.iso14496.part12
178 com.everyplay.external.iso14496.part15
53 com.everyplay.external.iso23001.part7
22 com.everyplay.external.iso23009.part1
50 com.everyplay.external.mp4parser
40 com.everyplay.external.mp4parser.authoring
25 com.everyplay.external.mp4parser.authoring.builder
25 com.everyplay.external.mp4parser.authoring.samples
138 com.everyplay.external.mp4parser.authoring.tracks
128 com.everyplay.external.mp4parser.boxes
3 com.everyplay.external.mp4parser.boxes.adobe
175 com.everyplay.external.mp4parser.boxes.apple
10 com.everyplay.external.mp4parser.boxes.basemediaformat
15 com.everyplay.external.mp4parser.boxes.cenc
46 com.everyplay.external.mp4parser.boxes.dece
15 com.everyplay.external.mp4parser.boxes.mp4
109 com.everyplay.external.mp4parser.boxes.mp4.objectdescriptors
40 com.everyplay.external.mp4parser.boxes.mp4.samplegrouping
32 com.everyplay.external.mp4parser.boxes.piff
26 com.everyplay.external.mp4parser.boxes.threegpp26244
6 com.everyplay.external.mp4parser.boxes.threegpp26245
9 com.everyplay.external.mp4parser.contentprotection
2 com.everyplay.external.mp4parser.h264
122 com.everyplay.external.mp4parser.h264.model
7 com.everyplay.external.mp4parser.h264.read
36 com.everyplay.external.mp4parser.util
2398 com.facebook
1993 com.facebook.android
170 com.facebook.appevents
43 com.facebook.appevents.internal
46 com.facebook.applinks
9 com.facebook.devicerequests.internal
574 com.facebook.internal
190 com.facebook.login
81 com.facebook.login.widget
32 com.facebook.messenger
43 com.facebook.places
102 com.facebook.places.internal
70 com.facebook.places.model
51 com.facebook.share
360 com.facebook.share.internal
114 com.facebook.share.model
124 com.facebook.share.widget
53 com.facebook.unity
25 com.google.ads
22 com.google.ads.mediation
11 com.google.ads.mediation.customevent
1987 com.google.android.gms
20 com.google.android.gms.actions
1987 com.google.android.gms.admob.impl.license
1987 com.google.android.gms.admob.license
2041 com.google.android.gms.ads
12 com.google.android.gms.ads.doubleclick
48 com.google.android.gms.ads.formats
21 com.google.android.gms.ads.identifier
1987 com.google.android.gms.ads.impl
308 com.google.android.gms.ads.internal
67 com.google.android.gms.ads.internal.gmsg
69 com.google.android.gms.ads.internal.js
63 com.google.android.gms.ads.internal.overlay
25 com.google.android.gms.ads.mediation
1 com.google.android.gms.ads.mediation.admob
12 com.google.android.gms.ads.mediation.customevent
1 com.google.android.gms.ads.reward.mediation
20 com.google.android.gms.ads.search
79 com.google.android.gms.common
36 com.google.android.gms.common.api
27 com.google.android.gms.common.api.internal
96 com.google.android.gms.common.internal
1987 com.google.android.gms.common.license
35 com.google.android.gms.common.stats
27 com.google.android.gms.common.util
5 com.google.android.gms.dynamic
20 com.google.android.gms.dynamite
2 com.google.android.gms.dynamite.descriptors.com.google.android.gms.ads.dynamite
1987 com.google.android.gms.gass
1987 com.google.android.gms.gass.license
3981 com.google.android.gms.internal
5 com.google.android.gms.location.places
6 com.google.android.gms.security
6 com.google.unity
2085 com.google.unity.ads
1987 com.mrappcore.games.neuralnetworknumber
1993 com.unity.purchasing
34 com.unity.purchasing.common
2171 com.unity.purchasing.googleplay
159 com.unity3d.player
1 java.io
28 java.lang
11 java.lang.annotation
1 java.math
2 java.nio
1 java.nio.channels
1 java.text
6 java.util
4 java.util.concurrent
6 java.util.logging
4 javax.microedition.khronos.egl
20 org.fmod
1 org.json
]
stdout[
processing archive C:\Users\Public\Documents\Unity Projects\My Game\Temp\StagingArea\android-libraries\GoogleAIDL\libs.\classes.jar...
processing com/android/vending/billing/BuildConfig.class...
processing com/android/vending/billing/IInAppBillingService.class...
processing com/android/vending/billing/IInAppBillingService$Stub.class...
processing com/android/vending/billing/IInAppBillingService$Stub$Proxy.class...
processing archive C:\Users\Public\Documents\Unity Projects\My Game\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\libs.\unity-plugin-library.jar...
processing com/google/unity/BuildConfig.class...
processing com/google/unity/ads/AdNetworkExtras.class...
processing com/google/unity/ads/Banner.class...
processing com/google/unity/ads/Banner$1.class...
processing com/google/unity/ads/Banner$2.class...
processing com/google/unity/ads/Banner$3.class...
processing com/google/unity/ads/Banner$4.class...
processing com/google/unity/ads/Banner$5.class...
processing com/google/unity/ads/Banner$6.class...
processing com/google/unity/ads/Banner$7.class...
processing com/google/unity/ads/CustomNativeAd.class...
processing com/google/unity/ads/CustomNativeAd$1.class...
processing com/google/unity/ads/CustomNativeAd$2.class...
processing com/google/unity/ads/Interstitial.class...
processing com/google/unity/ads/Interstitial$1.class...
processing com/google/unity/ads/Interstitial$1$1.class...
processing com/google/unity/ads/Interstitial$2.class...
processing com/google/unity/ads/Interstitial$3.class...
processing com/google/unity/ads/NativeAdLoader.class...
processing com/google/unity/ads/NativeAdLoader$1.class...
processing com/google/unity/ads/NativeAdLoader$2.class...
processing com/google/unity/ads/NativeAdLoader$3.class...
processing com/google/unity/ads/NativeAdLoader$3$1.class...
processing com/google/unity/ads/NativeAdLoader$3$2.class...
processing com/google/unity/ads/NativeAdLoader$3$3.class...
processing com/google/unity/ads/NativeAdLoader$4.class...
processing com/google/unity/ads/NativeExpressAd.class...
processing com/google/unity/ads/NativeExpressAd$1.class...
processing com/google/unity/ads/NativeExpressAd$2.class...
processing com/google/unity/ads/NativeExpressAd$3.class...
processing com/google/unity/ads/NativeExpressAd$4.class...
processing com/google/unity/ads/NativeExpressAd$5.class...
processing com/google/unity/ads/NativeExpressAd$6.class...
processing com/google/unity/ads/NativeExpressAd$7.class...
processing com/google/unity/ads/NativeExpressAd$8.class...
processing com/google/unity/ads/PluginUtils.class...
processing com/google/unity/ads/RewardBasedVideo.class...
processing com/google/unity/ads/RewardBasedVideo$1.class...
processing com/google/unity/ads/RewardBasedVideo$1$1.class...
processing com/google/unity/ads/RewardBasedVideo$2.class...
processing com/google/unity/ads/RewardBasedVideo$3.class...
processing com/google/unity/ads/UnityAdListener.class...
processing com/google/unity/ads/UnityAdLoaderListener.class...
processing com/google/unity/ads/UnityRewardBasedVideoAdListener.class...
processing archive C:\Users\Public\Documents\Unity Projects\My Game\Temp\StagingArea\android-libraries\GooglePlay\libs.\classes.jar...
processing com/unity/purchasing/googleplay/ActivityLauncher.class...
processing com/unity/purchasing/googleplay/BillingServiceManager.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$2.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$2.class...
processing com/unity/purchasing/googleplay/BillingServiceProcessor.class...
processing com/unity/purchasing/googleplay/BuildConfig.class...
processing com/unity/purchasing/googleplay/Consts.class...
processing com/unity/purchasing/googleplay/Consts$PurchaseState.class...
processing com/unity/purchasing/googleplay/Consts$ResponseCode.class...
processing com/unity/purchasing/googleplay/GooglePlayBillingUnAvailableException.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$1.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$2.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$3.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$4.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$5.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$6.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$7.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$Features.class...
processing com/unity/purchasing/googleplay/IActivityLauncher.class...
processing com/unity/purchasing/googleplay/IBillingServiceManager.class...
processing com/unity/purchasing/googleplay/IabException.class...
processing com/unity/purchasing/googleplay/IabHelper.class...
processing com/unity/purchasing/googleplay/IabHelper$1.class...
processing com/unity/purchasing/googleplay/IabHelper$2.class...
processing com/unity/purchasing/googleplay/IabHelper$2$1.class...
processing com/unity/purchasing/googleplay/IabHelper$3.class...
processing com/unity/purchasing/googleplay/IabHelper$4.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeMultiFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabPurchaseFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabSetupFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$QueryInventoryFinishedListener.class...
processing com/unity/purchasing/googleplay/IabResult.class...
processing com/unity/purchasing/googleplay/Inventory.class...
processing com/unity/purchasing/googleplay/Purchase.class...
processing com/unity/purchasing/googleplay/PurchaseActivity.class...
processing com/unity/purchasing/googleplay/PurchaseFailedEvent.class...
processing com/unity/purchasing/googleplay/SkuDetails.class...
processing com/unity/purchasing/googleplay/VRPurchaseActivity.class...
processing archive C:\Users\Public\Documents\Unity Projects\My Game\Temp\StagingArea\android-libraries\animated-vector-drawable-25.3.1\libs.\classes.jar...
processing android/support/graphics/drawable/Animatable2Compat.class...
processing android/support/graphics/drawable/Animatable2Compat$AnimationCallback.class...
processing android/support/graphics/drawable/Animatable2Compat$AnimationCallback$1.class...
processing android/support/graphics/drawable/AnimatedVectorDrawableCompat.class...
processing android/support/graphics/drawable/AnimatedVectorDrawableCompat$1.class...
processing android/support/graphics/drawable/AnimatedVectorDrawableCompat$2.class...
processing android/support/graphics/drawable/AnimatedVectorDrawableCompat$AnimatedVectorDrawableCompatState.class...
processing android/support/graphics/drawable/AnimatedVectorDrawableCompat$AnimatedVectorDrawableDelegateState.class...
processing android/support/graphics/drawable/animated/BuildConfig.class...
processing archive C:\Users\Public\Documents\Unity Projects\My Game\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\libs.\classes.jar...
processing android/support/v7/app/ActionBar.class...

The gms repository looks like this

![gms](https://user-images.githubusercontent.com/22933667/34588134-bb77ca30-f1ab-11e7-86c0-b380ae819f90.PNG)

Then the

![playservicead](https://user-images.githubusercontent.com/22933667/34588148-c7e8a44c-f1ab-11e7-9bed-1b658994a1b9.PNG)

And when i choose one for example 7.00, i have this content

![7 00](https://user-images.githubusercontent.com/22933667/34600791-94b4a456-f1f9-11e7-9a86-57fc8859b7b7.PNG)

And you can find the same content in the oder files

And in the asset/plugins/android/ of unity, I have this

![asset_plugin_android](https://user-images.githubusercontent.com/22933667/34588164-ddbfd38a-f1ab-11e7-8192-8c0f374c9023.PNG)

**With the old version 3.9, everything was fine.**

Can you please help me ?

Thanks

**Comment by rampara** [comment]
It looks like you're running into the [dex limit](https://developer.android.com/studio/build/multidex.html#about). Using the Gradle build system in Unity, you either use proguard and minify settings to reduce your dex count or use multidex. However, as this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
