### ISSUE TITLE
"Test Ad" label is not mention on test ad

### ISSUE THREAD

**Issue by araintechno** [googleads/googleads-mobile-unity#597]
Hi,
I am making a game in unity3d 5.6.4 and using admob 3.10.0 and test ads were working fine but from last few days device is showing real ads and "Test ad" label is not mentioned any where.How can i fix this issues?

**Comment by rampara** [comment]
@araintechno this is working as intended. We just made a [blog post](http://googleadsdeveloper.blogspot.com/2018/01/simpler-testing-with-new-admob-test-ads.html) explaining this change in more detail.

**Comment by araintechno** [comment]
it was working fine as mentioned in blog but from last 3 or 4 days "Test Ad" label is not mentioned on ad,So it is creating confusion for us to test ads for our game

**Comment by araintechno** [comment]
One thing more i want to mention is that test ad for rewarded video ads are working fine

**Comment by rampara** [comment]
@araintechno when you say banner and interstitial ads are showing real ads, do you mean you are not seeing the test ad label?

**Comment by araintechno** [comment]
yes

**Comment by rampara** [comment]
@araintechno this issue is related to a bug in the GMA Android SDK where test labels are not rendered correctly when using the Unity plugin. This issue will be resolved in an upcoming release of the GMA Android SDK.

**Comment by araintechno** [comment]
ok thanks
