### ISSUE TITLE
I can't find Google mobile Ad SDK Version for Unity latest then 3.10

### ISSUE THREAD

**Issue by maliktariq49** [googleads/googleads-mobile-unity#599]
I can't find Google mobile Ad SDK Version for Unity latest then 3.10. Please tell me they way how to update the latest version which must be latest then 7.0.0 .

**Comment by arcv** [comment]
That  won't affect you. That message is talking about almost 2-3 years old SDK.

googleads/googleads-mobile-unity#599

**Comment by rampara** [comment]
@arcv is correct in that if you're using a newer version of this plugin you will be using a version of the SDK newer that 7.0.0.
