### ISSUE TITLE
how can i know about Google Mobile Ad SDK version which i am using in unity ?

### ISSUE THREAD

**Issue by maliktariq49** [googleads/googleads-mobile-unity#600]
how can i know about Google Mobile Ad SDK version which i am using in unity ? Please tell me the way that  how can i find the Version no of the (GMA) SDK .?

**Comment by arcv** [comment]
Check the "AndroidResolverDependencies.xml" file in "ProjectSettings" folder. It should contain Android packages used by your project.

**Comment by rampara** [comment]
As @arcv mentioned, the `GoogleMobileAdsDependencies.xml` file in the `Assets/GoogleMobileAds/Editor` directory of your project will indicate the version of the GMA SDK used by the plugin.
