### ISSUE TITLE
stuck on Converting managed assemblies to C++

### ISSUE THREAD

**Issue by wangyw72** [googleads/googleads-mobile-unity#601]
hi~
I imported GoogleMobileAds plugin
And always stuck on "Converting managed assemblies to C++" when build iOS project.

**Comment by rampara** [comment]
As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
