### ISSUE TITLE
Rewarded Ad callback can only be called from the main thread Error

### ISSUE THREAD

**Issue by alaslipknot** [googleads/googleads-mobile-unity#602]
Hello, 

Rewarded Ad callback are working correctly, however, calling any method from the handler will return this error : 

```
get_gameObject can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
```

Nothing will be execute except "print()", so for example i have this code : 

```
 public void HandleRewardBasedVideoClosed(object sender, EventArgs args)
    {
        MonoBehaviour.print("HandleRewardBasedVideoClosed event received");
        rewardNotComplete();
    }
```
that print line will be written in the console, then the rewardNotComplete() method is this : 

```
void rewardNotComplete()
    {
        print("Reward not complete CALLED");

       // Application.LoadLevel(Application.loadedLevel);

        _PlManager.newGame();

        isLife = isDoubleCoins = false;
    }
```
Also that method is going to be called, it will print that first line, but then anything else will return that "thread error".

What's happening please ?

Thank you

**Comment by rampara** [comment]
@alaslipknot when deploying to Android, ad events will not be invoked on the main thread. This [blog post](http://googleadsdeveloper.blogspot.com/2016/04/handling-android-ad-events-in-unity.html) explains in greater detail. The plugin will be updated in a future release to support invoking ad events on the main thread.

**Comment by alimertcetin** [comment]
@rampara any updates on this? It seems almost 4 years past but this is still happening.
