### ISSUE TITLE
Banner and Videoads arent showing

### ISSUE THREAD

**Issue by PaulKeXD** [googleads/googleads-mobile-unity#603]
I wanted to use Admob in my app with banners and rewarded videos. As the banners werent working, i rewrote the code for rewarded videos, but these arent showing to.
Here is the code:

`

	public class AdManager : MonoBehaviour
	{
	public static AdManager Instance { get; set; }
	public RewardBasedVideoAd CoinVideo;

	public void Start()
	{
		MobileAds.Initialize("ca-app-pub-3940256099942544/5224354917");
		Instance = this;
		if (MainMenu.DestroyAdManager)
		{
			Destroy(gameObject);
		}
		else if (MainMenu.DestroyAdManager == false)
		{
			DontDestroyOnLoad(gameObject);
		}

		CoinVideo = RewardBasedVideoAd.Instance;
		CoinVideo.OnAdLoaded += HandleRewardBasedVideoLoadedCoin;
		CoinVideo.OnAdFailedToLoad += HandleRewardBasedVideoFailedToLoadCoin;
		CoinVideo.OnAdOpening += HandleRewardBasedVideoOpened;
		CoinVideo.OnAdStarted += HandleRewardBasedVideoStarted;
		CoinVideo.OnAdRewarded += HandleRewardBasedVideoRewarded;
		CoinVideo.OnAdClosed += HandleRewardBasedVideoClosed;
		CoinVideo.OnAdLeavingApplication += HandleRewardBasedVideoLeftApplication;
		LoadCoinVideo();
	}

	public void LoadCoinVideo()
	{
		Debug.Log("LoadCoinVid");
		AdRequest request = new AdRequest.Builder().Build();
		CoinVideo.LoadAd(request, "ca-app-pub-3940256099942544/5224354917");
	}
//This method is called with a button.
	public void ShowCoinVideo()
	{
		if (CoinVideo.IsLoaded())
		{
			CoinVideo.Show();
		}
		else
		{
			LoadCoinVideo();
		}
	}

	public void HandleRewardBasedVideoLoadedCoin(object sender, EventArgs args)
	{
	}
	public void HandleRewardBasedVideoFailedToLoadCoin(object sender, AdFailedToLoadEventArgs args)
	{
		LoadCoinVideo();
	}
	public void HandleRewardBasedVideoOpened(object sender, EventArgs args)
	{

	}
	public void HandleRewardBasedVideoStarted(object sender, EventArgs args)
	{

	}
	public void HandleRewardBasedVideoClosed(object sender, EventArgs args)
	{

	}
	public void HandleRewardBasedVideoRewarded(object sender, Reward args)
	{
		string type = args.Type;
		double amount = args.Amount;
		if (type == "Coin")
		{
			Debug.Log("Coin" + amount);
		}
	}
	public void HandleRewardBasedVideoLeftApplication(object sender, EventArgs args)
	{

	}
}
`

**Comment by rampara** [comment]
@PaulKeXD As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
