### ISSUE TITLE
Google Mobile Ads for Unity causes Android application to pause

### ISSUE THREAD

**Issue by suntabu** [googleads/googleads-mobile-unity#605]
![](https://storage.googleapis.com/support-kms-prod/91E0E29ADFA1A1BF42097E0699CC491BE874)
As showing in the picture, we need the game running under the interstitial ads for next page.
But on android platform, the unity activity is paused by the interstitial ads, how could we follow this rules?

**Comment by rampara** [comment]
@suntabu the game being paused is a tied to the Unity game engine implementation and not this plugin.

**Comment by suntabu** [comment]
Hi, @rampara  
But google policies recommend this kind of interstitial ways and sent warnings to our games.

So do you have any ideas for these problems?

**Comment by rampara** [comment]
@suntabu if you're having issues with AdMob policy, I would recommend you reach out to the Product Support team from the Contact Us button on the [AdMob Help Center](https://support.google.com/admob/?hl=en#).

**Comment by suntabu** [comment]
OK, thanks
