### ISSUE TITLE
XCode 7.3.1 does not compile the project

### ISSUE THREAD

**Issue by defic** [googleads/googleads-mobile-unity#606]
I setup AdMob for our game. Android seems to work fine, but on iOS XCode does not compile and gives the following error:

`ld: framework not found FileProvider for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

XCode version: 7.3.1
Unity 5.5.2p4

**Comment by rampara** [comment]
@defic the FileProvider framework is only available in Xcode 9. Can you try updating to the latest version of Xcode?

**Comment by defic** [comment]
I could narrow down the problem to the Vungle mediation adapter. Without it, XCode 7.3.1 compiles fine. However, according to the Admob Vungle documentation, the adapter should work on XCode 7 and up ( https://developers.google.com/admob/unity/mediation/vungle ).

It seems that some of the other adapters might share the same issue, as I found this issue from the googleads ios mediation repository: https://github.com/googleads/googleads-mobile-ios-mediation/issues/25

Our project has had some compability issues with newer Xcode versions before, but I will give it a try with XCode 9.

**Comment by rampara** [comment]
@defic I'm closing this issue as it is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
