### ISSUE TITLE
Temp Staging Area Problem After Upgrading

### ISSUE THREAD

**Issue by brunovals** [googleads/googleads-mobile-unity#615]
After i upgraded to the latest admob, my unity started to pop up this when i build

IOException: Failed to Move File / Directory from 'Temp/StagingArea\android-libraries\play-services-ads-license-11.8.0\classes.jar' to 'Temp/StagingArea\android-libraries\play-services-ads-license-11.8.0\libs\classes.jar'.

Can anyone help ?

**Comment by rampara** [comment]
@brunovals can you try selecting `Assets -> Play Services Resolver -> Android Resolver -> Force Resolve ` in the Unity Editor?

**Comment by brunovals** [comment]
@rampara  i've tried force resolve the first time, it didn't resolve the issue

Appearantly, this issue only appear when you also add and or upgrade admob and also upgrade Google Play Game Services v 0.95 in your project [ it's a little rough because GPG services 0.95 remove Quest API which will cause some errors ]

I solved this problem by : 
- Uninstall Admob package ( By Deleting GoogleMobileAds Folder )
- Delete these folders : 
   - GooglePlayGames
   - PlayServicesResolver
   - plugins > Android
- It is customary to re-open the project, but i didn't do it, still succeded
- Import Google Play Games 0.95 
- Re-Setup Google Play Games
- Import Admob
- Assets > PlayServicesResolver > Android Resolver > Force Resolve
- Build

Credits : iosnock => https://github.com/playgameservices/play-games-plugin-for-unity/issues/2085

^^ thanks
