### ISSUE TITLE
Banner not always showing and strange reports

### ISSUE THREAD

**Issue by paradizIscool** [googleads/googleads-mobile-unity#616]
Banner seems to show only one first run on android and ios devices. After killing application I get no fill. 

Moreover, I get stranges reports from admob
Day 1: 200 Android beta testers, 280 sessions, 734 requests, 729 matched, 500 impressions, 3 clicks 
Day 2: 468  Android beta testers, 756 sessions, 303 requests, 285 matched 6 impressions 2 clicks.

![capture d ecran 2018-02-15 a 11 08 07](https://user-images.githubusercontent.com/11227595/36251190-8d01a0e4-1240-11e8-8cee-d41216cbf74d.png)

No problem on test devices, banner are always visible.
No problem with interstitials and rewarded

version 3.11.0
Admob only

**Comment by rampara** [comment]
@paradizIscool ss this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
