### ISSUE TITLE
How to fix this issues for iOS

### ISSUE THREAD

**Issue by faiguago** [googleads/googleads-mobile-unity#624]
Undefined symbols for architecture armv7

"_OBJC_CLASS_$_GLKView", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
"_OBJC_CLASS_$_MFMessageComposeViewController", referenced from:
      objc-class-ref in GoogleMobileAds(flat-armv7)
"_kUTTagClassMIMEType", referenced from:
      l5460 in GoogleMobileAds(flat-armv7)
      l5592 in GoogleMobileAds(flat-armv7)
"_GLKMatrix4Identity", referenced from:
      l4149 in GoogleMobileAds(flat-armv7)
      l4160 in GoogleMobileAds(flat-armv7)

**Comment by yassinos69** [comment]
Same 😢

**Comment by rampara** [comment]
@faiguago @yassinos69 does adding the MessageUI framework to your project resolve the issue?

**Comment by rampara** [comment]
Closing due to non-response.

**Comment by shahbazofficial** [comment]
Remove admob and never add it again .
