### ISSUE TITLE
How to stop showing Ads from AdMob and force use other networks to test them properly ?

### ISSUE THREAD

**Issue by alaslipknot** [googleads/googleads-mobile-unity#626]
Hi,
Am making a game and the client said that when he get a reward Ad from UnityAds the reward callback are not executing properly, i need to test that but i can't because i am exclusively getting Ads from AdMob even thought that our mediation group contain UnityAds, Vungle and Nend, is there a way to force another network to show ? i tried lowering the eCPM of AdMob to $0.01 and keeping others in $10 but i still get AdMob only.

Any help please ?

PS: me and my clients are in different countries, probably this is why he get unityAds and i almost never did.

Thank you.

**Comment by rampara** [comment]
@alaslipknot the Google Mobile Ads SDK team is currently working on a new feature to make testing and verifying mediation integrations easier. You can check for updates on the [Google Ads developer blog](http://googleadsdeveloper.blogspot.com/).

**Comment by rchallenger** [comment]
We used to disable admob optimizzations in AdUnit Networks and set min price to $1000.
This helped us to get ads from other networks set to adUnit
