### ISSUE TITLE
[Feature request] Facebook mediation dependencies import too much libraries

### ISSUE THREAD

**Issue by rchallenger** [googleads/googleads-mobile-unity#627]
We've tried to resolve our mediation plugins dependecies by importing you XML files for adapters we needed. But after resolution we've noticed that our project got appcompat and recycleview libraries with all other stuff, so we met DEX limit (75K). Though we used Facebook before and it was not necessary to import all that libraries (If we talk about banner and interstitial). Probably their rewarded demands that libs.
So I'd like to ask you to make a separate item in XML dependencies for this pack off libraries as they are optional.

(Oftopic) PS: Maybe there is a way to minimize DEX size in Unity 5.4 ?
Prebuilding aar plugins with graddle didn't work for us (it fails, even with latest platform-tools installed).
Also latest Unity has "build with Graddle" option. But it fails too due to some file dublicates in aar/jar plugins (meta) or manifest conflicts. For example empty project with google ads failed to build using graddle. Do you have any ideas about that?

**Comment by rampara** [comment]
@rchallenger to resolve your problem Proguard stripping and/ or multidex are your best options. Both will require resolving your issues with Gradle builds. Once you've done that, you can export an Android Studio project and configure Proguard and/or multidex. Newer versions of Unity allow you to configure Proguard stripping right from the player settings for Gradle builds. Using a Custom Gradle template is an also an option for setting up multidex.

As for the appcompat and recyclerview dependencies, those are declared by the Facebook SDK, and we have no control over that.
