### ISSUE TITLE
Rewarded Ads always returns NO_FILL

### ISSUE THREAD

**Issue by JAOOOOO** [googleads/googleads-mobile-unity#631]
I've implemented the admob rewarded video ads, identically like the documentation, but always returns NO_FILL, I've interstitial ad implemented and it's working, the Dummy client is working well, too.
but on live device it gives NO_FILL error

**Comment by rampara** [comment]
@JAOOOOO are you experiencing this issue on iOS or Android? Are you able to load test rewarded video ads without issue?

**Comment by keepup** [comment]
@rampara 
I have the same issue in Android device recent days.
I have received feedback from several players in recent days. They all say that there is no advertising to see. Then I try request reward ad in our android device, it always returns error "No fill"(Failed to load ad: 3). It's the same result after AddTestDevice in the request. 
If you need me, I would be happy to provide more information.

**Comment by rampara** [comment]
@keepup are you able to load test ads by using the test ad placements listed in the [developer docs](https://developers.google.com/admob/unity/test-ads)?

**Comment by keepup** [comment]
@rampara I can get reward videos now.  But I don't know why it's always "No Fill" after request a reward video before.

**Comment by rampara** [comment]
Closing as the issue seems to have been resolved for @keepup and no response from @JAOOOOO.
