### ISSUE TITLE
App crashes when I request interstitial (firebase)

### ISSUE THREAD

**Issue by jojizaidi** [googleads/googleads-mobile-unity#634]
I integrated Firebase and log events and everything seems to be working fine.
I then integrated Google Mobile Ads and the app crashes when I request an interstitial.

Attached is the log file.
[log.txt](https://github.com/googleads/googleads-mobile-unity/files/1828257/log.txt)

**Comment by perseus25** [comment]
I used last version admob plugin.
Unity 5.6.5p2
Script backend : IL2CPP
App crash when request interstitial.

BUT when i switch to Mono2x, app display interstitial normally.

**Comment by rampara** [comment]
@jojizaidi are you able to consistently reproduce this crash?

**Comment by jojizaidi** [comment]
Yes this is happening consistently.

I'll try doing what @perseus25  has mentioned tomorrow.

**Comment by rampara** [comment]
@jojizaidi can you provide a test Unity project that reproduces this issue?

**Comment by jojizaidi** [comment]
So I think its an issue with my device.
The same project works fine on a Google Pixel and Galaxy S7 Edge but crashes on an Experia Z3.

I'll try and debug with that.

Thanks.
