### ISSUE TITLE
"Moving File Failed" After I integrated the Admob Plugin

### ISSUE THREAD

**Issue by oldnewusers** [googleads/googleads-mobile-unity#635]
Hi All,

I have been building a game for several months. It was only a couple days ago I decided to integrate Admob into my game. However, when I integrated the GoogleMobileAds Unity Package into my project, the project would start getting stuck in this "Resolving Android Dependencies" idalog, as shown in image below:
https://ibb.co/fkVEfH

When I try to build the game, it would show a dialog:

"Moving Temp/StagingArea\android-libraries\com.google.android.gms.play-services-ads.license-11.8.0\classjar to Temp Moving Temp/StagingArea\android-libraries\com.google.android.gms.play-services-ads.license-11.8.0\libs\classjar.jar.
The system cannot find the file specified"

Some more Information:
(1) I have updated the Android sdk to the latest version
(2) I use the newest Admob plugin
(3) Same problem occurs no matter I used Unity 5.6.1f or 5.6.4 or the newest Unity 2017 4.0f1
(4) Problem occurs no matter I used Internal or Gradle build systems in my build settings.

Most importantly, the problem does NOT occur if I am using a blank new project, but it occurs when I incorporate the plugin into my existing game project.

I saw that this problem has been reported in a few occasions, but no good solutions have been provided thus far.

This issue has cost me two full days of development time , would appreciate if I can get the way to solve the problem.

**Comment by rchallenger** [comment]
Try to reimport PlayServicesResolver.
Remove all play-service libraries from Plugins folder and restart Unity.
That should help.

**Comment by oldnewusers** [comment]
Thanks for your response rchallenger.

It did not work.

I have tried removing all the three plugin folders and reimporting the plugin package several times. I have even tried removing Unity (the version I was using was 5.6.4) and reinstalling both Unity 5.6.4 and the newest version of Unity.

For your information, I started developing the game in last summer using 5.6.1f, I imported Google Play Services Plugin for a short while but then removed. Not sure if it would cause the conflict. 

I also tried removing all project settings in the Project Settings folders and reimport the game, but of no avail.

**Comment by rchallenger** [comment]
strange question, but check if your assets folder not deep enough to exceed file name length limit.
Try to move assets to drive's root folder. 
I remember same stuff used to happen before, but somehow I've overcome it.

**Comment by rampara** [comment]
@oldnewusers can you try the following steps.

1. Turn of automatic dependency resolution by selecting `Assets -> Play Services Resolver -> Android Resolver -> Settings` and unselecting `Enable  auto-resolution`.
2. Remove all plugin related files (Including all Play services files under `Assets/Plugins/Android`).
3. Import the latest version of this plugin.
4. Import the latest version of the [Play services resolver](https://github.com/googlesamples/unity-jar-resolver/raw/master/play-services-resolver-1.2.64.0.unitypackage).
5. Force resolve Android dependencies by selecting `Assets -> Play Services Resolver -> Android Resolver -> Force resolve`

**Comment by oldnewusers** [comment]
@rchallenger 
Thanks, the solution is simple, I just moved my Unity Project file's location from somewhere deep to somewhere closer to the root folder, then the error disappears.

Hard to imagine the bug that has haunted me for 2 full development days was solved in this manner!

**Comment by rampara** [comment]
@oldnewusers glad you were able to resolve your issue.
