### ISSUE TITLE
Crash on startup when When implementing Rewarded Video

### ISSUE THREAD

**Issue by i08jineq** [googleads/googleads-mobile-unity#637]
I tried to do testing of my game.
This is what I've got... is there anything I missed?

E/AndroidRuntime(12512): FATAL EXCEPTION: main
E/AndroidRuntime(12512): Process: com.darklordgame.jumpbasket, PID: 12512
E/AndroidRuntime(12512): java.lang.Error: FATAL EXCEPTION [main]
E/AndroidRuntime(12512): Unity version     : 2017.4.0f1
E/AndroidRuntime(12512): Device model      : ZTE 402ZT
E/AndroidRuntime(12512): Device fingerprint: SBM/ZTE-402ZT/ZTE-402ZT:4.4.4/KTU84P/eng.root.20150901.190157:user/release-keys
E/AndroidRuntime(12512):
E/AndroidRuntime(12512): Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.ads.MobileAds
E/AndroidRuntime(12512): 	at com.google.unity.ads.RewardBasedVideo$1.run(RewardBasedVideo.java:65)
E/AndroidRuntime(12512): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(12512): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(12512): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(12512): 	at android.app.ActivityThread.main(ActivityThread.java:5095)
E/AndroidRuntime(12512): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(12512): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(12512): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime(12512): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
E/AndroidRuntime(12512): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  810):   Force finishing activity com.darklordgame.jumpbasket/com.unity3d.player.UnityPlayerActivity
W/dalvikvm(12512): VFY: unable to find class referenced in signature (Lcom/google/android/gms/ads/InterstitialAd;)
W/dalvikvm(12512): VFY: unable to find class referenced in signature (Lcom/google/android/gms/ads/InterstitialAd;)
W/dalvikvm(12512): VFY: unable to find class referenced in signature (Lcom/google/android/gms/ads/InterstitialAd;)
I/dalvikvm(12512): Could not find method com.google.android.gms.ads.InterstitialAd.getMediationAdapterClassName, referenced from method com.google.unity.ads.Interstitial.getMediationAdapterClassName
W/dalvikvm(12512): VFY: unable to resolve virtual method 280: Lcom/google/android/gms/ads/InterstitialAd;.getMediationAdapterClassName ()Ljava/lang/String;
D/dalvikvm(12512): VFY: replacing opcode 0x6e at 0x0006
W/dalvikvm(12512): VFY: unable to find class referenced in signature (Lcom/google/android/gms/ads/AdRequest;)
W/dalvikvm(12512): VFY: unable to find class referenced in signature (Lcom/google/android/gms/ads/AdRequest;)
W/dalvikvm(12512): Unable to match class for part: 'Lcom/google/android/gms/ads/AdRequest;)V'
E/dalvikvm(12512): Could not find class 'com.google.android.gms.ads.InterstitialAd', referenced from method com.google.unity.ads.Interstitial$1.run
W/dalvikvm(12512): VFY: unable to resolve new-instance 112 (Lcom/google/android/gms/ads/InterstitialAd;) in Lcom/google/unity/ads/Interstitial$1;
D/dalvikvm(12512): VFY: replacing opcode 0x22 at 0x0002
D/dalvikvm(12512): DexOpt: unable to opt direct call 0x0117 at 0x0a in Lcom/google/unity/ads/Interstitial$1;.run
W/dalvikvm(12512): Unable to resolve superclass of Lcom/google/unity/ads/Interstitial$1$1; (106)
W/dalvikvm(12512): Link of class 'Lcom/google/unity/ads/Interstitial$1$1;' failed
D/dalvikvm(12512): DexOpt: unable to opt direct call 0x0186 at 0x23 in Lcom/google/unity/ads/Interstitial$1;.run
D/dalvikvm(  810): GC_FOR_ALLOC freed 564K, 29% free 17407K/24208K, paused 94ms, total 94ms
D/StatusBarManagerService(  810): disableLocked userId=0 what=0x0 pkg=WindowManager.LayoutParams
D/KeyguardViewMediator(  923): setHidden false
D/KeyguardViewMediator(  923): setHidden false
D/StatusBar.NetworkController(  923): onDataActivity: direction=2
D/TelephonyIcons(  923): getDataActivity, sub=0, activity=2
D/StatusBar.NetworkController(  923): updateDataIcon, mDataDirectionIconId = com.android.systemui:drawable/stat_sys_signal_out mDataConnected = true
D/StatusBar.NetworkController(  923): refreshViews connected={ data } level=4 combinedSignalIconId=0x7f02028a/com.android.systemui:drawable/stat_sys_signal_4_fully mobileLabel=SoftBank wifiLabel= emergencyOnly=false combinedLabel=SoftBank mAirplaneMode=false mDataActivity=2 mPhoneSignalIconId=0x7f02028a/com.android.systemui:drawable/stat_sys_signal_4_fully mQSPhoneSignalIconId=0x7f020052/com.android.systemui:drawable/ic_qs_signal_4 mDataDirectionIconId=0x7f0202d6/com.android.systemui:drawable/stat_sys_signal_out mDataSignalIconId=0x7f02028a/com.android.systemui:drawable/stat_sys_signal_4_fully mDataTypeIconId=0x7f0200b2/com.android.systemui:drawable/stat_sys_data_fully_connected_4g mQSDataTypeIconId=0x7f020053/com.android.systemui:drawable/ic_qs_signal_4g mNoSimIconId=0x0/(null) mWifiIconId=0x7f0202e5/com.android.systemui:drawable/stat_sys_wifi_signal_null mQSWifiIconId=0x7f02007c/com.android.systemui:drawable/ic_qs_wifi_no_network mWifiActivityIconId=0x0/(null) mBluetoothTetherIconId=0x10805da/android:drawable/stat_sys_tether_bluetooth
W/Settings(  923): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.

**Comment by i08jineq** [comment]
It seems to be the request made the crash

**Comment by rampara** [comment]
@i08jineq are you including the required Google Play services dependencies in your Unity project? If not, select `Assets -> Play Services Resolver -> Android -> Resolve` to add the required files to the `Assets/Plugins/Android` directory of your Unity project.

**Comment by i08jineq** [comment]
@rampara Hi, I didn't put anything but admob.
I tried Assets -> Play Services Resolver -> Android -> Resolve too.. 
but no files added thanks

**Comment by i08jineq** [comment]
@rampara There is a popup said it successful. but no new files is added

**Comment by rampara** [comment]
@i08jineq can you post the contents of `Assets/Plugins/Android` directory of your project? Also, you can turn on verbose logging for Play Services resolver (select `Assets -> Play Services Resolver -> Android -> Settings` and select verbose logging) and post the contents listed in the console when you attempt to resolve dependencies.

**Comment by vongsomxai** [comment]
@rampara Thank you for your replay.
Here is how it looks like in Assets/Plugins/Android
<img width="1673" alt="2018-03-22 10 21 18" src="https://user-images.githubusercontent.com/22186879/37746924-e1cfe9f6-2dbf-11e8-8feb-5313918a59bb.png">

I also select verbose logging and do the resolve again
It shows 
<img width="423" alt="2018-03-22 10 55 27" src="https://user-images.githubusercontent.com/22186879/37746946-0783a43a-2dc0-11e8-91e5-054642cba6de.png">

And then 
2 log messages after press OK
Reading Android dependency XML file Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml
UnityEngine.Debug:Log(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.AndroidXmlDependencies:Read(String, Logger)
GooglePlayServices.XmlDependencies:ReadAll(Logger)
GooglePlayServices.AndroidXmlDependencies:ReadAll(Logger)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean)
GooglePlayServices.<Resolve>c__AnonStorey11:<>m__19()
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob()
GooglePlayServices.PlayServicesResolver:Resolve(Action, Boolean, Action`1)
GooglePlayServices.PlayServicesResolver:ExecuteMenuResolve(Boolean)
GooglePlayServices.PlayServicesResolver:MenuResolve()


DependOn - group: com.google.android.gms artifact: play-services-ads version: 11.8.0 packageIds:  repositories: https://maven.google.com
UnityEngine.Debug:Log(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:LogDelegate(String, LogLevel)
Google.JarResolver.PlayServicesSupport:Log(String, LogLevel, Boolean)
Google.JarResolver.PlayServicesSupport:DependOn(String, String, String, String[], String[], String)
GooglePlayServices.<Read>c__AnonStoreyC:<>m__E(XmlTextReader, String, Boolean, String, List`1)
Google.XmlUtilities:ParseXmlTextFileElements(String, Logger, ParseElement)
GooglePlayServices.AndroidXmlDependencies:Read(String, Logger)
GooglePlayServices.XmlDependencies:ReadAll(Logger)
GooglePlayServices.AndroidXmlDependencies:ReadAll(Logger)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean)
GooglePlayServices.<Resolve>c__AnonStorey11:<>m__19()
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob()
GooglePlayServices.PlayServicesResolver:Resolve(Action, Boolean, Action`1)
GooglePlayServices.PlayServicesResolver:ExecuteMenuResolve(Boolean)
GooglePlayServices.PlayServicesResolver:MenuResolve()


Thank you

**Comment by i08jineq** [comment]
Proved!

**Comment by rampara** [comment]
@i08jineq you should see a lot more messages in the console that describe the dependency resolution process. However, as this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
