### ISSUE TITLE
Broadcast of Intent error/ANR

### ISSUE THREAD

**Issue by bernardz** [googleads/googleads-mobile-unity#640]
Hi,

We have in several games an issue what we cannot find or reproduce.
Some information:

- Unity 2017.3
- Admob 3.12.0 
- Firebase 4.5.0

I hope someone can help us.
Thank you!

The only information what we have is this from the ANR info:

Broadcast of Intent { act=android.intent.action.SCREEN_ON flg=0x50000010 launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } (has extras) }

"main" tid=1 Native 
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x762b24d0 self=0xb4427800
  | sysTid=18259 nice=-4 cgrp=default sched=0/0 handle=0xb6faabec
  | state=S schedstat=( 0 0 0 ) utm=2130 stm=459 core=2 HZ=100
  | stack=0xbe3c0000-0xbe3c2000 stackSize=8MB
  | held mutexes=
  #00  pc 000000000003a7c0  /system/lib/libc.so (nanosleep+12)
  #01  pc 0000000000362984  /data/app/com.xx.mygame-2/lib/arm/libunity.so (???)
  #02  pc 00000000004ede24  /data/app/com.xx.mygame-2/lib/arm/libunity.so (???)
  #03  pc 0000000000128db4  /data/app/com.xx.mygame-2/lib/arm/libmono.so (???)
  #04  pc 0000000000022868  /data/app/com.xx.mygame-2/lib/arm/libmono.so (???)
  #05  pc 00000000002c3e75  /data/app/com.xx.mygame-2/lib/arm/libmono.so (???)
  #06  pc 0000000000001db9  /system/bin/app_process32 (InvokeUserSignalHandler+76)
  #07  pc 00000000002407df  /system/lib/libart.so (_ZN3art12FaultManager11HandleFaultEiP7siginfoPv+178)
  #08  pc 0000000000013260  /system/lib/libc.so (???)
  #09  pc 0000000000013260  /system/lib/libc.so (???)
  #10  pc 0000000000013260  /system/lib/libc.so (???)
  #11  pc 0000000000013260  /system/lib/libc.so (???)
  #12  pc 0000000000013260  /system/lib/libc.so (???)
  #13  pc 0000000000013260  /system/lib/libc.so (???)
  #14  pc 0000000000013260  /system/lib/libc.so (???)
  #15  pc 0000000000013260  /system/lib/libc.so (???)
  #16  pc 0000000000013260  /system/lib/libc.so (???)
  #17  pc 0000000000013260  /system/lib/libc.so (???)
  #18  pc 0000000000013260  /system/lib/libc.so (???)
  #19  pc 0000000000013260  /system/lib/libc.so (???)
  #20  pc 0000000000013260  /system/lib/libc.so (???)
  #21  pc 0000000000013260  /system/lib/libc.so (???)
  #22  pc 0000000000013260  /system/lib/libc.so (???)
  #23  pc 0000000000013260  /system/lib/libc.so (???)
  #24  pc 0000000000013260  /system/lib/libc.so (???)
  #25  pc 0000000000013260  /system/lib/libc.so (???)
  #26  pc 0000000000013260  /system/lib/libc.so (???)
  #27  pc 0000000000013260  /system/lib/libc.so (???)
  #28  pc 0000000000013260  /system/lib/libc.so (???)
  #29  pc 0000000000013260  /system/lib/libc.so (???)
  #30  pc 0000000000013260  /system/lib/libc.so (???)
  #31  pc 0000000000013260  /system/lib/libc.so (???)
  #32  pc 0000000000013260  /system/lib/libc.so (???)
  #33  pc 0000000000013260  /system/lib/libc.so (???)
  #34  pc 0000000000013260  /system/lib/libc.so (???)
  #35  pc 0000000000013260  /system/lib/libc.so (???)
  #36  pc 0000000000013260  /system/lib/libc.so (???)
  #37  pc 0000000000013260  /system/lib/libc.so (???)
  #38  pc 0000000000013260  /system/lib/libc.so (???)
  #39  pc 0000000000013260  /system/lib/libc.so (???)
  #40  pc 0000000000013260  /system/lib/libc.so (???)
  #41  pc 0000000000013260  /system/lib/libc.so (???)
  #42  pc 0000000000013260  /system/lib/libc.so (???)
  #43  pc 0000000000013260  /system/lib/libc.so (???)
  #44  pc 0000000000013260  /system/lib/libc.so (???)
  #45  pc 0000000000013260  /system/lib/libc.so (???)
  #46  pc 0000000000013260  /system/lib/libc.so (???)
  #47  pc 0000000000013260  /system/lib/libc.so (???)
  #48  pc 0000000000013260  /system/lib/libc.so (???)
  #49  pc 0000000000013260  /system/lib/libc.so (???)
  #50  pc 0000000000013260  /system/lib/libc.so (???)
  #51  pc 0000000000013260  /system/lib/libc.so (???)
  #52  pc 0000000000013260  /system/lib/libc.so (???)
  #53  pc 0000000000013260  /system/lib/libc.so (???)
  #54  pc 0000000000013260  /system/lib/libc.so (???)
  #55  pc 0000000000013260  /system/lib/libc.so (???)
  #56  pc 0000000000013260  /system/lib/libc.so (???)
  #57  pc 0000000000013260  /system/lib/libc.so (???)
  #58  pc 0000000000013260  /system/lib/libc.so (???)
  #59  pc 0000000000013260  /system/lib/libc.so (???)
  #60  pc 0000000000013260  /system/lib/libc.so (???)
  #61  pc 0000000000013260  /system/lib/libc.so (???)
  #62  pc 0000000000013260  /system/lib/libc.so (???)
  #63  pc 0000000000013260  /system/lib/libc.so (???)
  at com.unity3d.player.ReflectionHelper.nativeProxyInvoke (Native method)
  at com.unity3d.player.ReflectionHelper.a (unavailable)
  at com.unity3d.player.ReflectionHelper$1.invoke (unavailable)
  at java.lang.reflect.Proxy.invoke (Proxy.java:397)
  at com.google.unity.ads.UnityRewardBasedVideoAdListener.onAdFailedToLoad (UnityRewardBasedVideoAdListener.java)
  at com.google.unity.ads.RewardBasedVideo$1$1.onRewardedVideoAdFailedToLoad (RewardBasedVideo.java:75)
  at com.google.android.gms.internal.zzadu.onRewardedVideoAdFailedToLoad (unavailable)
  at com.google.android.gms.internal.zzadq.onTransact (unavailable)
  at android.os.Binder.transact (Binder.java:380)
  at android.os.Handler.handleCallback (Handler.java:739)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:145)
  at android.app.ActivityThread.main (ActivityThread.java:7007)
  at java.lang.reflect.Method.invoke! (Native method)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1404)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)

**Comment by rampara** [comment]
@bernardz this ANR seems to be caused by the JNI bridge in Unity for plugins and not the plugin itself? As such, there's not much this plugin can to to resolve this issue.

**Comment by waqasahmeddevbatch** [comment]
@bernardz Have you resolved this issue?

**Comment by msureka** [comment]
Any idea what can be done to resolve this?

**Comment by dermarder** [comment]
I have the same issue. Any ideas?

**Comment by rampara** [comment]
Closing as duplicate of #707
