### ISSUE TITLE
Facebook Adapter 4.27 and 4.28 cannot receive OnAdRewarded event

### ISSUE THREAD

**Issue by llmagicll** [googleads/googleads-mobile-unity#642]
I am facing the problem that iOS Facebook Adapter 4.27.0 4.27.1 4.27.2 (with audience network 4.27.0)and 4.28 (with audience network 4.28.0) cannot receive OnAdRewarded event, and also cannot show interstitial ad after call m_AdInstance.Show (); with 3.12.0 GoogleMobileAd
Could anyone help?? Every other mediations are fine (e.g. Unity, Chartboost, etc...)

**Comment by llmagicll** [comment]
I found the reason after i look into the Facebook adapter (4.28.0)

The facebook rewarded video delegate is:
- (void)rewardedVideoAdVideoComplete:(FBRewardedVideoAd *)rewardedVideoAd;

However in Facebook adapter is implemented as:
- (void)rewardedVideoAdComplete:(FBRewardedVideoAd *)rewardedVideoAd

That is a big mistake, i'm still finding the problem of interstitial.

**Comment by rampara** [comment]
@llmagicll thanks for reporting this issue. The mediation team is investigating and a fix should be pushed out shortly

**Comment by rampara** [comment]
Closing as this has been fixed.

https://github.com/googleads/googleads-mobile-ios-mediation/blob/master/adapters/Facebook/FacebookAdapter/GADFBAdapterDelegate.m
