### ISSUE TITLE
Ads always return NO-FILL (Failed to load ad: 3)

### ISSUE THREAD

**Issue by vanminh2501** [googleads/googleads-mobile-unity#645]
I'm using admob for showing android ads, identically like the documentation. The test ads are working fine but real ads are not shown, it always returns error "No fill from ad server"(Failed to load ad: 3), It's the same result after AddTestDevice in the request.

**Comment by rampara** [comment]
@vanminh2501 if test ads are working then your issue is not related to this plugin but ad serving for the GMA SDK. I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.

**Comment by leoHN** [comment]
@vanminh2501 I got same issues sometime. Admob may block your device id (or unit id...) if you sent to many request in short time. Just wait or change package name or unit id (for testing). It works for me

**Comment by jalalkira** [comment]
Hello,
I have some problems , can you give me your status @hirenvaja @leoHN ?
Test Ad are showing, but Real ad are not showing (I/Ads: Ad failed to load : 3)

**Comment by parker9904** [comment]
i have same problem ...please help me😣😣😣

**Comment by PandeyAradhana** [comment]
I have same problem to...

**Comment by PandeyAradhana** [comment]
I have same problem...I don't know why  test ads are showing but real ads not...

Exact message : 
I/Ads: No fill from ad server.
 W/Ads: Failed to load ad: 3

Any suggestions will appreciated......thanks in advance

**Comment by hirenvaja** [comment]
Hello Aradhana

Firstly I asked one question

Is your previous admob account are banned ????

**Comment by PandeyAradhana** [comment]
Hi,

No my account is not banned for admob

Thanks for your support but now real ads are showing so no worries at all.


Regards,
Aradhana pandey

**Comment by AnkitPatill** [comment]
i have also Same problem

**Comment by parker9904** [comment]
I'm fix this issue

**Comment by kk3hi3123** [comment]
Same problem here.
I want to add reward video ads into my app, which already contains banner and interstitial ads for several months. But reward video always return no fill even if I set the testing device ID.

**Comment by lmjssjj** [comment]
i have same problem ...please help mepersevereperseverepersevere

**Comment by Daulet777** [comment]
same problem...

**Comment by GioPan04** [comment]
Same problem here...

**Comment by MUSKANDESAI** [comment]
> i have same problem ...please help me😣😣😣

**Comment by xeeshansami** [comment]
**Error: Ads load to failed : 3** 
i have same issue test ads are showing(working) but when i set the real ads ids so then not working 
My application is now live on playstore
please help me app is live and develop since 2 weeks ago and still im stuck. this problem

**Comment by pandeyVishakha** [comment]
Don't worry, nothing need to do from your end just recheck banner_id once.
If it is correct then you should wait for some time, it will get reflected
automatically.

**Comment by myflyingfish** [comment]
my rewordAd, bannerAd and Interstitial ad is all OK both on  test and  real.   but when I add   native ad use test AdId, the same error   LoadAdError--{
      "Code": 3,
      "Message": "No fill.",
      "Domain": "com.google.android.gms.ads",
      "Cause": "null",
      "Response Info": {
        "Response ID": "null",
        "Mediation Adapter Class Name": "",
        "Adapter Responses": []
      }
    }

**Comment by manbeing** [comment]
Has anyone in this thread resolved this code 3 -No fill issue ?

I have published my app for one month and am still getting code 3 error. The test ad unit id works even in production .

**Comment by lmjssjj** [comment]
这是来自QQ邮箱的自动回复邮件。
 
我将尽快给您回复。

**Comment by andikaputraputu22** [comment]
Hello, I got this issue too, No Fill when request native ads.
Is there still fight with this issue? Or there already a correct way to fix this issue?
Thank you.

**Comment by lmjssjj** [comment]
这是来自QQ邮箱的自动回复邮件。
 
我将尽快给您回复。

**Comment by WuGaoXiang** [comment]
I got the same error. But my test ad is not wroking either.
