### ISSUE TITLE
Please give us the exact banner size in Unity units

### ISSUE THREAD

**Issue by rotter** [googleads/googleads-mobile-unity#647]
I've had this problem around a year ago and though "ok, the SDK is still new, let me make a hack and wait until the next update which they will certainly add a way for us to know the banner size, I wont annoy them with this".

Fast forward a year and it's still almost impossible to tell the banner exact size on the screen without hacks.

One has to make several hacks to convert from DP to Pixels to Unity Screen.width/height equivalent, also put some conditions to see if the device is landscape or portrait, and which screen size range to know if it's gonna be 32 DP height or 50 or 90. And then keep monitoring the documentation to see if those rules changes. All this annoys the players due to miscalculation of the banner height causing overlap with screen content, which ultimately may cause a suspension by AdMob (I'm currently facing a problem).

I have used AdMob for 5 years, and on my past engines it was native Java so there was a method like banner.getHeight() which would give me the exact banner height for the current banner, so I didnt need to do any hack. I dont know why on Unity it isnt like that.

Encapsulate all those AdMob rules which we shouldnt know or care about, and give us a standard method like GetWidthUnity/GetHeightUnity for the banners which returns in the same unit as Screen.Width/Screen.Height, so we can easily convert it to Canvas units or anything else we need, and also make them work dynamically for Smart Banners as well.

Please give us that.

Thanks.

**Comment by rampara** [comment]
@rotter closing this issue as the new APIs introduced in v3.10.0 of the plugin seem to meet your use case. The dev docs will be updated shortly to reflect the addition of these new methods.
