### ISSUE TITLE
Interstitial Ads Do Not SHow Up 

### ISSUE THREAD

**Issue by oldnewusers** [googleads/googleads-mobile-unity#648]
Hi All,

I am trying to import Admob Interstitials into my game. I have imported the latest Admob plugin successfully. But the interstitial does not show up on my mobile when the "ShowAd" method is called.

I use the following code:

`
public class AdManager : MonoBehaviour {
    public static AdManager instance;
    InterstitialAd interstitial;
    // Use this for initialization
    void Start () {
        //singleton
        if (instance == null)
            instance = this;
        else if (instance != this)
            Destroy (gameObject);
     
        DontDestroyOnLoad (gameObject); 
        //initialize
        #if UNITY_ANDROID
        string appId = "[app id hidden]";
        #elif UNITY_IPHONE
        string appId = "[app id hidden]";
        #else
        string appId = "unexpected_platform";
        #endif
        MobileAds.Initialize(appId);
        //request interstitial immediately
        RequestInterstitial ();
 
    }
 
    // Update is called once per frame
    void Update () {
     
    }
    private void RequestInterstitial()
    {
        #if UNITY_ANDROID
        string adUnitId = "ca-app-pub-3940256099942544/1033173712";
        #elif UNITY_IPHONE
        string adUnitId = "ca-app-pub-3940256099942544/4411468910";
        #else
        string adUnitId = "unexpected_platform";
        #endif
        // Initialize an InterstitialAd.
        interstitial = new InterstitialAd(adUnitId);
        AdRequest request = new AdRequest.Builder().Build();
        // Load the interstitial with the request.
        interstitial.LoadAd(request);
    }
        public void ShowAd()
        {
        if (interstitial.IsLoaded()) {
            print ("interstitial loaded");
        interstitial.Show();
        }
    }
 
}`

A couple More information:
1. I try to load and show a test interstitial.
2. Also, when I am on editor, the "interstitial loaded" is printed in the console, so " interstitial.Show();" must have been gone through during the running of the game.
3. I have already created an app on admob and retrieved the Appid and pasted it into the code above (which I have hidden it here).

Any one please help me identify if anything gone wrong? Many thanks!

**Comment by rampara** [comment]
@oldnewusers for integration issues I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
