### ISSUE TITLE
CRASH on Build: `MobileAds.SetiOSAppPauseOnBackground()` method to pause iOS apps when displaying full screen ads.

### ISSUE THREAD

**Issue by mole84** [googleads/googleads-mobile-unity#649]
`MobileAds.SetiOSAppPauseOnBackground()` method to pause iOS apps when displaying full screen ads.

This crashes on build in xcode , it says "property (class) is not defined."

Downgrade to v. 3.10 helps me.

Please fix for newest version 3.12

**Comment by rampara** [comment]
@mole84 looks like you're not pulling in all of the changes included v3.12.0 of this plugin. Can you try removing all files related to this plugin and re-importing the latest plugin package.

**Comment by rampara** [comment]
Closing issue due to non-response.
