### ISSUE TITLE
How to completely uninstall the plugin

### ISSUE THREAD

**Issue by koljanich** [googleads/googleads-mobile-unity#651]
Hello! My ECPM is down to $0.4 from $1.7!!! I want completely remove the plug-in along with services, mediation and linked libraries. I will no longer use the Google libraries, Google Play services and other related libraries. Please tell me how I can remove all this from the Unity project so that when the Google Play Service Resolver does not return all the libraries back.

**Comment by rchallenger** [comment]
Would you reveal to us a secreat of what you have been using when you had such ECPM?

**Comment by rampara** [comment]
The way to uninstall the plugin would be to manually remove all plugin related files from your project. The `Assets/GoogleMobileAds` and `Assets/PlayServicesResolver` directories would be a good place to start. There are also files from this plugin in `Assets/Plugin/Android` and `Assets/Plugin/iOS`.
