### ISSUE TITLE
UnityAds reward videos callback not working on iOS

### ISSUE THREAD

**Issue by alaslipknot** [googleads/googleads-mobile-unity#652]
Hi, 

this is some pretty weird issue, the game works perfectly on Android, but on iOS only Vungle and GoogleAds are performing correctly, unityAds reward videos just don't do ANY callback.

I really can't think of anything in this situation, as the code used there is the exact same one used in another project which works just fine, also i double checked  that everything is setup correctly in the dashboard (it is otherwise i wont even get ads from unity) 

any help please?

thanks!

**Comment by rampara** [comment]
@alaslipknot just so to clarify, your issue is that Vungle callbacks are working as expected in one project but not another?

**Comment by alaslipknot** [comment]
@rampara  on Android everything is working, on iOS, only Vungle and AdMob are working, when i get Ads from UnityAds, i don't get any callback within the game. and yes it's the same project.

**Comment by rampara** [comment]
@alaslipknot can you retest with the latest mediation support package for UnityAds?

**Comment by rampara** [comment]
Closing issue due to non-response.
