### ISSUE TITLE
GoogleMobileAds.Android.Utils' does not contain a definition for `NativeExpressAdViewClassName'

### ISSUE THREAD

**Issue by samieti02** [googleads/googleads-mobile-unity#656]
Hi, 
there is a new error, using the new release of the sdk in unity

GoogleMobileAds.Android.Utils' does not contain a definition for `NativeExpressAdViewClassName' 

Can you please help us to fix it, 
Thanks

**Comment by eklebanski** [comment]
Same here

**Comment by rampara** [comment]
@samieti02 @eklebanski Support for Native Ads Express were removed in v3.13.0 of this plugin. Are you using outdated plugin files that still may be referencing Native Ads Express functionality?

**Comment by eklebanski** [comment]
Removing all previous package and importing Admob plugin anew solved the issue

**Comment by rampara** [comment]
@eklebanski glad you issue has been resolved.
