### ISSUE TITLE
Receiving real ads on test device.

### ISSUE THREAD

**Issue by ArmandCloud** [googleads/googleads-mobile-unity#658]
Using Google Mobile Ads Unity Plugin v3.13.1, Unity 2017.3.1.p4,  Android (Min API 16,Target API Max.)

Logs after request.
> I/Ads: Starting ad request.
>     This request is sent from a test device.

On android test devices, it shows real ads. ios is fine.

Best Regards,

**Comment by rampara** [comment]
@ArmandCloud are you not seeing the test ad label on ads loaded on Android? Are you able to get a Charles log for an ad request and response?

**Comment by ArmandCloud** [comment]
Some how it solved by itself 1-2 week ago. I assume something is changed on admob side. Thank you @rampara .
