### ISSUE TITLE
AdColony mediation Unity READ_PHONE_STATE

### ISSUE THREAD

**Issue by sebastianteres** [googleads/googleads-mobile-unity#659]
Hey guys,

I'm sorry if this is not the right place for this issue, I couldn't find a better one.
AdColony mediation unity package is causing that READ_PHONE_STATE permission problem.

> I'm talking about the unity package downloaded from this guide: https://developers.google.com/admob/unity/mediation/adcolony

When trying to upload the apk to the Play Console it causes an error with a message saying I need a Privacy Policy because my app is requesting that permission. This only happened after importing AdColony Mediation extras.

The reason is that the package AndroidManifext.xml is missing the following:

`Assets/Plugins/Android/GoogleMobileAdsAdColonyMediation/AndroidManifest.xml`
```xml
<uses-sdk android:minSdkVersion="16"
      android:targetSdkVersion="25" />
```

Once I edited the file I was able to upload the APK without any issues.

Cheers!

**Comment by rampara** [comment]
@sebastianteres this will be fixed in an upcoming release of this plugin.

**Comment by rampara** [comment]
closing as this has been resolved.
