### ISSUE TITLE
Ad content filtering not working

### ISSUE THREAD

**Issue by malyawka** [googleads/googleads-mobile-unity#660]
Hello!

- Unity 2017.1 final
- Google Mobile Ads Unity Plugin v3.13.1
- Service Ads 12.0.1
- All (my - Nexus 5 Android 6.0.1 , but phone of testers from Google Play don't know)

I have an application that I can not publish for several days. 
It is rejected due to violations of the display of advertising. 
The application is designed for children and shown advertising should match this, but as it turned out - it's not.

That's generated a request:

AdRequest adRequest = new AdRequest.Builder()
                            .AddTestDevice("A70E4EBF3743D588FFFA76DDCB5A5CD7")
                            .AddTestDevice("9DC9EE65FC6F5DEE471F36C43B5A55BA")
                            .TagForChildDirectedTreatment(true)
                            .AddExtra("max_ad_content_rating", contantRating)
                            .Build();  

All the same, even the ads appear to the show 18+. 

Tried many different combinations, with the tag, without, with the indication of the test device and without. The result is the same. 
There is a suspicion that the string "contantRating" is not processed in AdMob in any way.

Help Please! (((

**Comment by rampara** [comment]
@malyawka would you be able to capture a network log of your ad request?

**Comment by rampara** [comment]
Closing issue due to non-response.
