### ISSUE TITLE
iOS - The reward ads is loaded, but you can not watch it. 

### ISSUE THREAD

**Issue by stzminji** [googleads/googleads-mobile-unity#662]
Hello.

There is a problem with the Reward ad.

I've loaded a reward ad in my mobile Unity project, and I've tried to run it,
 but I can't see it with the error 'No ads to show ... log from MobvsitaAdapter'.

Ad load completion callback was called normally.

True is returned when the RewardBasedVideoAd.isLoaded () is called before the show is called.

Using :
Unity 5.6.3p4
iOS 11.2 ( iPhone 7 Plus )
Google Ads 3.6.0

      if (rewardBasedVideo.IsLoaded())
       {
           SoundManager.it.PauseAll();
            STZDebug.Log(“[ADX Play AD] SoundManager PauseAll!“);

            STZDebug.Log(“[ADX Play AD] rewardBasedVideo Show! Before”);
           rewardBasedVideo.Show();

            STZDebug.Log(“[ADX Play AD] rewardBasedVideo Show! After”);
       }

log : 

![2018-04-27 7 36 27](https://user-images.githubusercontent.com/37064201/39359085-7b1ab92e-4a53-11e8-8bfd-837b052dcc94.png)

Help Please..

**Comment by rampara** [comment]
@stzminji can you ensure you're using the latest version of the Google Mobile Ads iOS SDK. There was a fix for this issue included in a recent version of the SDK.

**Comment by rampara** [comment]
Closing due to non-response.
