### ISSUE TITLE
"GADUPluginUtil.h" (Unknown property attribute 'class') on @property(class) BOOL pauseOnBackground;

### ISSUE THREAD

**Issue by taimoor1989** [googleads/googleads-mobile-unity#663]
Just downloaded and installed this and was trying to test it out with iOS. I was getting some errors that I was unable to resolve.
<img width="1151" alt="screen shot 2018-04-28 at 2 48 09 pm" src="https://user-images.githubusercontent.com/38808552/39395077-7dba5d6a-4af3-11e8-83c9-46b98f2a38c3.png">

also getting error here in GADUInterface.m

<img width="1155" alt="screen shot 2018-04-28 at 2 48 38 pm" src="https://user-images.githubusercontent.com/38808552/39395086-a8370afc-4af3-11e8-9b2d-44fd357cc1d9.png">

Although i put GoogleMobileAds framework in FrameWorks

**Comment by rampara** [comment]
@taimoor1989 does setting the property directly resolve your issue?

**Comment by taimoor1989** [comment]
i solved it by updating my xcode.it was'nt working on xcode7.3
