### ISSUE TITLE
Publish updated GoogleMobileAdsAdColonyMediation on Bintray

### ISSUE THREAD

**Issue by akwkong** [googleads/googleads-mobile-unity#665]
One of our publishers noticed that AdColony Rewarded videos on Android were rewarding even when the video was not completely viewed. That was fixed in version 3.3.0.1 of the AdColony adapter:
https://github.com/googleads/googleads-mobile-android-mediation/issues/49

I saw that the Assets/GoogleMobileAds/Editor/AdColonyMediationDependencies.xml file in the 1.0.0 version of GoogleMobileAdsAdColonyMediation was still referring to the 3.3.0.0 AdColony adapter. The file on GitHub refers to a later version, 3.3.2.0, where the bug is fixed:
https://github.com/googleads/googleads-mobile-unity/blob/master/mediation/AdColony/source/plugin/Assets/GoogleMobileAds/Editor/AdColonyMediationDependencies.xml#L3

Would it be possible to update GoogleMobileAdsAdColonyMediation on Bintray with the latest files from GitHub? I saw there was a 1.0.1 version made but it does not contain any files:
https://bintray.com/google/mobile-ads-adapters-unity/GoogleMobileAdsAdColonyMediation/1.0.1#files

Thanks!

**Comment by rampara** [comment]
@akwkong closing this issue as the AdColony dependencies file has been updated to reference v3.3.2.0.

**Comment by akwkong** [comment]
@rampara I am not seeing a new version of the adapter on Bintray:
https://bintray.com/google/mobile-ads-adapters-unity/GoogleMobileAdsAdColonyMediation

The existing versions, 1.0.0 and 1.0.1, have not been updated recently either. Could you please make sure the updated .unitypackage is available on Bintray?

**Comment by akwkong** [comment]
Saw that there is a 1.0.2 version available on Bintray now that uses version 3.3.4 of the AdColony SDK, thanks!
