### ISSUE TITLE
Banner not destroyed on certain devices

### ISSUE THREAD

**Issue by msureka** [googleads/googleads-mobile-unity#666]
Hello,

We have implemented Admob Banner Ad in the Main Menu of our game, and are destroying the Ad when the user clicks on Play button.

On most of our test devices (iOS & Android) this seems to be running fine, but we have got several reviews (especially on Android), that this banner doesn't get destroyed and stays even during the gameplay.

We are unable to reproduce this as it is working fine on our device, but we have several users complaining about this.

We are using the below code to destroy the banner when the user clicks on Play button.
public void DestroyAd()
{
    bannerView.Destroy();
}

Is this behaviour possible? Could it be due to internet issues? Android OS versions?

We have also put checks to load the banner only if it in Menu state, and not in game state. But we have got several negative reviews due to the banner in the gameplay as it overlaps with the in-game UI.

Any suggestions would be great!

**Comment by rampara** [comment]
@msureka if you're provide more information on which devices this issue in present I can investigate further.

**Comment by rampara** [comment]
Closing issue due to non-response.
