### ISSUE TITLE
on ios when you change the screen rotation the banners are not positioned correctly

### ISSUE THREAD

**Issue by cabanel** [googleads/googleads-mobile-unity#667]
Hi

on IOS when you change the screen rotation the banners are not positioned correctly

on Android work fine

test on iphone6
googleads-mobile-unity Version 3.13.1

thanks
![img_0282](https://user-images.githubusercontent.com/4569650/39616467-cac3edba-4f7b-11e8-851c-55010dfde2ba.jpg)

**Comment by rampara** [comment]
A fix for this issue will be included in an upcoming release of the plugin.
