### ISSUE TITLE
Will the Consent SDK be released before May 25, 2018?

### ISSUE THREAD

**Issue by aratn0n** [googleads/googleads-mobile-unity#668]
I saw that the Consent SDK for Android and iOS will be released before May 25, 2018, but I'm not sure about the Unity SDK.  

Will it be released for Unity SDK too?

**Comment by sjvc** [comment]
Same question here

**Comment by flashwade03** [comment]
I think this page will help you.

(https://groups.google.com/forum/#!msg/google-admob-ads-sdk/Penk7_E9fIo/prC3cRjhCQAJ)

**Comment by sjvc** [comment]
Thanks @flashwade03 but we need to use the AdMob SDK to do more things like detect EU users or get providers list

**Comment by flashwade03** [comment]
@sjvc This url is helpful to you getting provider list (https://support.google.com/admob/answer/9012903).

I think those 2 logic(detecting EU users, get provider list) will be made by programmer not SDK.

**Comment by Tanek81** [comment]
Any updates on this **VERY IMPORTANT** topic?

**Comment by rampara** [comment]
The [Unity developer docs](https://developers.google.com/admob/unity/eu-consent) include information on how to forward user consent status to the Google Mobile Ads SDK. At this time, there is no Unity Consent SDK offered.
