### ISSUE TITLE
banner ad not loading

### ISSUE THREAD

**Issue by nbhavani2016** [googleads/googleads-mobile-unity#670]
i downloaded this google mobile ads unity plugin (3.13.1) and added in to my unity game-unity version(2018.1.0f2).created admob account and got app,banner,video id and used it in my unpublished game but it is not showing any test ads.please help me!
thank u.

**Comment by nbhavani2016** [comment]
help me

**Comment by nbhavani2016** [comment]
even sample program of Hello World is not working .test ads are not showing in my android phone.

**Comment by rampara** [comment]
@nbhavani2016 this issue tracker is for technical issues, bug reports and feature requests for this plugin. For technical support, I would recommend you reach out on the [Google Mobile Ads Technical forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for assistance.
