### ISSUE TITLE
Ads not showing on Android 7.0

### ISSUE THREAD

**Issue by naveedrawan** [googleads/googleads-mobile-unity#672]
Hi,
I am using latest unity ads plugin but ads are not showing on Android 7.0?

Please  let me know soon.

**Comment by gammlstudio** [comment]
I had a similar problem with Admob. Issue:
https://github.com/googleads/googleads-mobile-unity/issues/230
Found out that the quick solution for me was, that (after android 6.0.) the location information had to be turned on for the ads to be displayed. Turning it off prevents the ads from showing.

**Comment by rampara** [comment]
This issue tracker is for technical issues, bug reports and feature requests for this plugin. For technical support, I would recommend you reach out on the [Google Mobile Ads Technical forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for assistance.
