### ISSUE TITLE
Native Advanced Error Spam

### ISSUE THREAD

**Issue by sathyaraj-shettigar** [googleads/googleads-mobile-unity#673]
@rampara 
I tried the preview version of Admob which supports Native Advanced. Implemented it in unity but when displaying the ad I get the following error spam.

 NullReferenceException: Object reference not set to an instance of an object
   at _7DwxoIFqo4msA2gd7qefalu8Sdo._0l2RBGguR8VFeD0boB90jm7FgPF () [0x00000] in <filename unknown>:0
   at _7DwxoIFqo4msA2gd7qefalu8Sdo.CheckForImpressionWithoutRenderer () [0x00000] in <filename unknown>:0

Also, there is no CallToAction Link in the SDK to redirect the user when tapped on the Ad.
I am guessing there must be a separate repo of the new SDK but I could not find one so I am asking for assistance here.

**Comment by rampara** [comment]
@sathyaraj-shettigar is this issue still present for you on the latest version of the Unity plugin that supports Native Advanced (3.13.1.1) ?

**Comment by sathyaraj-shettigar** [comment]
You can't comment at this time.

**Comment by sathyaraj-shettigar** [comment]
@rampara Yes it does exist

**Comment by rampara** [comment]
@sathyaraj-shettigar can you provide the full stack trace to NullReferenceException from the latest plugin.

**Comment by rampara** [comment]
Closing issue due to non-response.
