### ISSUE TITLE
Rewarded Video Problem

### ISSUE THREAD

**Issue by gokhandem** [googleads/googleads-mobile-unity#674]
I've an unity android project with latest googlemobileads sdk.  I tried to show test ads for interstitial and rewarded video and it's working perfect. When i tried to change test ads to real ones, interstitial works great but reward video has problem about loading ads.  

Issue is:
No fill from ad server
Failed to load ad: 3
HandleRewardBasedVideoFailedToLoad event received with message: No Fill

I have an old project that made with unity 5.0 and old mobileads sdk. It's working perfect for both interstitial and reward based video. I created new empty project and called it test, coppied things from old project to test. I tried to build it witihout changing anything but it gives the same error than given above. I send this test project to my friend to build. He said reward based videos working great.  I just couldn't understand what is the difference between old projects and new unity 2017 projects. Any suggestions ?

**Comment by rampara** [comment]
@gokhandem can you capture a network log for and request made with a Unity 5.x build vs a Unity 2017 build?

**Comment by rampara** [comment]
Closing due to non-response.
