### ISSUE TITLE
Net speed 2.6 mbps 

### ISSUE THREAD

**Issue by KamranMahmood** [googleads/googleads-mobile-unity#677]
but still file not download wt...........................................................................
???????//?/

**Comment by rampara** [comment]
@KamranMahmood this issue tracker is for technical issues, bug reports and feature requests for this plugin. For technical support, I would recommend you reach out on the [Google Mobile Ads Technical forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for assistance.
