### ISSUE TITLE
CAN'T check these box these are freeze (ADMOB SDK)

### ISSUE THREAD

**Issue by KamranMahmood** [googleads/googleads-mobile-unity#679]
![33583415_1787273717999922_7151195641048203264_n](https://user-images.githubusercontent.com/37421905/40565776-af8af306-6022-11e8-89f4-2839fde5c17a.jpg)

**Comment by rampara** [comment]
@KamranMahmood this issue tracker is for technical issues, bug reports and feature requests for this plugin. For technical support, I would recommend you reach out on the [Google Mobile Ads Technical forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for assistance.
