### ISSUE TITLE
Getting Error On Activity In Manifest 

### ISSUE THREAD

**Issue by Jbstudio425** [googleads/googleads-mobile-unity#681]
CommandInvokationFailure: Unable to merge android manifests. 
C:/Program Files/Java/jdk1.8.0_151\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="E:/SDK/adt-bundle-windows-x86-20140702/adt-bundle-windows-x86-20140702/sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Error: [Temp\StagingArea\AndroidManifest-main.xml:12, D:\HeyZap Plugin\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-ads-lite-11.8.0\AndroidManifest.xml:12] Trying to merge incompatible /manifest/application/activity[@name=com.google.android.gms.ads.AdActivity] element:
  <activity
--    @android:name="com.google.android.gms.ads.AdActivity"
--    @android:theme="@android:style/Theme.Translucent">
--</activity>
  <activity
++    @android:exported="false"
++    @android:name="com.google.android.gms.ads.AdActivity"
++    @android:theme="@android:style/Theme.Translucent">
]
stdout[

]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by yawarabbasshah** [comment]
<activity
-- @android:name="com.google.android.gms.ads.AdActivity"
-- @android:theme="@android:style/Theme.Translucent">
--



<activity
++ @android:exported="false"
++ @android:name="com.google.android.gms.ads.AdActivity"
++ @android:theme="@android:style/Theme.Translucent">
]

You can see the difference of this in both manifest files try coping (android:exported="false") to androidmanifest-main at the same location

**Comment by Jbstudio425** [comment]
Solve this by deleting the manifest file in project.
The manifest is auto generated by unity & it has all stuff needed.
