### ISSUE TITLE
When the video is finished, the application crashes when you try to change "TextMesh.text"

### ISSUE THREAD

**Issue by pedicagames** [googleads/googleads-mobile-unity#683]
1) I used the sample project here.
2) I added a "TextMesh" object to the scene (Game object name: "Screen Text").
3) I have added the following lines;
```
public class GoogleMobileAdsDemoScript : MonoBehaviour 
{
    TextMesh screenText;
    ...
    ...


public void Start()
{
    screenText = GameObject.Find("Screen Text").GetComponent<TextMesh>();
    ...
    ...

public void HandleRewardBasedVideoClosed(object sender, EventArgs args)
{
    screenText.text = "Test 1";
    ...
    ...

public void HandleRewardBasedVideoRewarded(object sender, Reward args)
{
    screenText.text = "Test 2";
    ...
    ...
```
4) When the video is finished or canceled, the app is crashes.
5) Here is Log file when video rewarded:
[log.txt](https://github.com/googleads/googleads-mobile-unity/files/2064854/log.txt)

**Comment by rampara** [comment]
@pedicagames you shouldn't be using Unity API from ad events as discussed in this [blog post](https://ads-developers.googleblog.com/2016/04/handling-android-ad-events-in-unity.html).
