### ISSUE TITLE
AdMob Banner - Unity Plugin Position incorrect

### ISSUE THREAD

**Issue by cowboybkit** [googleads/googleads-mobile-unity#687]
Hi, 
I have a bottom banner but incorrect position.
The banner position is above the bottom line (contain virtual key).
I use GoogleMobileAds v3.13.1, test device Asus zenphone 5, android version 8.0.0
Please see the screenshots in the attachment.
![1527668281570](https://user-images.githubusercontent.com/450528/41012358-5c481136-696b-11e8-8fcf-4ffe1b1abca1.JPEG)

**Comment by muxapet** [comment]
Try to build unity project with Gradle build system, it works for me.

**Comment by rampara** [comment]
@cowboybkit is this issue present for you on all devices with soft keys or just the Asus Zenphone 5?

**Comment by perseus25** [comment]
@rampara : I also get same issue on Redmi 5 (Android 7.1.2). I use latest admob plugin version and Unity 5.6.5p2.
Please fix it. My app on Play store get many 1 star rating because this.
:(

**Comment by perseus25** [comment]
@cowboybkit Mình dùng bản unity 2017.3.1f1 thì không bị lỗi này nữa, còn unity 2018 với unity 5.6 thì bị. Bạn thử xem sao.

**Comment by rampara** [comment]
@cowboybkit currently don't have access to a Redmi 5. Are you able to reproduce the issue with the latest version of the plugin on any other devices?

**Comment by abiaocom** [comment]
this bug show in HUAWEI nova 3e (ANE-AL00). I use GoogleMobileAds v3.15.0

**Comment by perseus25** [comment]
This bug show in OnePlus6
I use lastest version plugin. Unity 2017.3.1f1

**Comment by rampara** [comment]
Attempting to get a hold of one of the devices mentioned to reproduce the issue. Will follow up when I have more information.

**Comment by tucano** [comment]
I have also this issue I'm oneplus6 and Wiko view 2. any news on this? Seems that you are correcting for a "safe area" but Unity is not.

**Comment by WhatWapp** [comment]
We have the same issue on devices like Zenphone and OnePlus. Any news on this?

**Comment by MushoodMunir** [comment]
I'm facing same issue on Nexus6P

**Comment by itayganor** [comment]
After some research, this problem is not related to the software navigation bar, but to the notch (display cutout). When using `AdPosition.Bottom`, the space between the banner and the bottom of the screen is **the height of the notch**. Currently I couldn't find any way to get the height of the notch, because with this measure the solution is easy:
`new BannerView(adUnitId, adSize, 0, (int)ConvertPixelsToDP(Screen.height - adHeight + notchHeight));`

I'm using OnePlus 6 but could successfully reproduce the issue on an emulated Pixel 2 and 2 XL with display cutout enabled from Developer Options.

**Comment by Dharmesh1993** [comment]
@itayganor How you convert Pixels To DP. Please post code for ConvertPixelsToDP method

**Comment by itayganor** [comment]
...Any updates?

**Comment by tiance7** [comment]
This bug show in Nexus 5X
I use admob 3.15.0 version plugin. 
Unity 2017.4.16
it display correct most of the time, but sometimes error jump above the bottom,and will auto correct the position in 30s

**Comment by rubelmusicwould8374** [comment]
Admob Account Adjust-App I'd  Please System Update Settings Ads

**Comment by daolm** [comment]
Any update on this case?

**Comment by UragayalaDeepika** [comment]
@daolm Please refer to this issue- https://github.com/googleads/googleads-mobile-unity/issues/734 if your concern is regarding the main issue reported here about the banner ad.

**Comment by StariMarco** [comment]
For unity 2019:
Project Settings > Resolution and Presentation > Render outside safe area
