### ISSUE TITLE
Crash in сloud build during assembly under ios.

### ISSUE THREAD

**Issue by Klonium** [googleads/googleads-mobile-unity#692]
Hello, I can not find a solution to the problem. I found a lot of topics in Google, but none of them really helped me. I use the plugin admob https://github.com/googleads/googleads-mobile-unity/releases/tag/v3.13.1 version v3.13.1 in the project, but when I try to build a project under the IOS in a cloud build, a number of errors appear in the logs connected with this plugin.
Unity Version 2018.1.1f1. XCode 9.3.

292: ⚠;️ ld: directory not found for option '-F /BUILD_PATH/yops-ltd.shipscops.ios/temp.XXXXXX20180609-5865-n6141/Pods/Google-Mobile-Ads-SDK/Frameworks/frameworks'
293: ❌; Undefined symbols for architecture armv7
294: ⚠;️ ld: directory not found for option '-F /BUILD_PATH/yops-ltd.shipscops.ios/temp.XXXXXX20180609-5865-n6141/Pods/Google-Mobile-Ads-SDK/Frameworks/frameworks'
295: ⚠;️ ld: arm64 function not 4-byte aligned: ltmp0 from /BUILD_PATH/yops-ltd.shipscops.ios/temp.XXXXXX20180609-5865-n6141/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
296: ⚠;️ ld: arm64 function not 4-byte aligned: _unwind_tester from /BUILD_PATH/yops-ltd.shipscops.ios/temp.XXXXXX20180609-5865-n6141/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
297: ❌; Undefined symbols for architecture arm64
298: ❌; ld: symbol(s) not found for architecture arm64
299: ❌; clang: error: linker command failed with exit code 1 (use -v to see invocation)
300: ▸ clang: error: linker command failed with exit code 1 (use -v to see invocation)
301: fastlane finished with errors
302: /BUILD_PATH/.mason/buildpacks/xcode/bin/compile:253:in `block in build': ! xcode build failed. (RuntimeError)
303: ! build of 'ios' failed. compile failed

**Comment by Wanderer13** [comment]
Hi, had same issue. Adding framework dependencies resolved this for me.
FrameworkDependencies: AdSupport;CoreData;CoreFoundation;CoreTelephony;MobileCoreServices;Security;StoreKit;CoreBluetooth;EventKit;GLKit;MessageUI;SafariServices;
![unity-2017 2 1](https://user-images.githubusercontent.com/22817174/41978208-fe84c1c8-7a29-11e8-8771-f1a39c3c1642.png)

**Comment by rampara** [comment]
@Klonium can you try testing with the latest version of the plugin (which includes an updated Play Services Resolver build) and incorporating the steps mentioned by @Wanderer13.

**Comment by rampara** [comment]
Closing due to non-response.
