### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by yosiharan** [googleads/googleads-mobile-unity#693]
It would be great to have one or more of the following options:
1. An API for showing a consent dialog, like in the native iOS & Android SDKs.
2. An option to serve non-personalized ads with no capping capabilities or any other actions which require consent. Basically, an option which would make the usage of the SDK fully GDPR compliant even without showing a consent dialog.

Are any of these features in active development?

Thanks :)

**Comment by rampara** [comment]
@yosiharan a Consent SDK similar to the one offered for the Android and iOS SDKs is planned for Unity. As for you second point, under the Google EU User Consent Policy consent is required for non-personalized ads. For more information on policies, I would recommend you reach out on the [Google Mobile Ads Product Support Forum](https://productforums.google.com/forum/#!forum/google-admob-help-forum).

**Comment by yasirkula** [comment]
@rampara Is the Consent SDK for Unity still in the to-do list?
