### ISSUE TITLE
com.google.android.gms.ads.MobileAds Issue With Firebase

### ISSUE THREAD

**Issue by Jbstudio425** [googleads/googleads-mobile-unity#694]
`: AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.MobileAds
: java.lang.ClassNotFoundException: com.google.android.gms.ads.MobileAds
:      at java.lang.Class.classForName(Native Method)
:      at java.lang.Class.forName(Class.java:309)
:      at java.lang.Class.forName(Class.java:273)
:      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
:      at com.unity3d.player.UnityPlayer.c(Unknown Source)
:      at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
:      at android.os.MessageQueue.next(MessageQueue.java:211)
:      at android.os.Looper.loop(Looper.java:130)
:      at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.MobileAds" on path: DexPathList[[zip file "/data/app/com.google.firebase.unity.analytics.testapp-2/base.apk"],nativeLibraryDirectories=[/data/app/com.google.firebase.unity.analytics.testapp-2/lib/arm, /vendor/lib, /system/lib]]
E/Unity   (17646):      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.`

![plugins folder](https://user-images.githubusercontent.com/37201702/41348711-f1489358-6f26-11e8-9634-28043aabab59.PNG)

Get this error on using Firebase plugin with AdMob & build using Gradle System Unity.

> Tried this solution
`https://github.com/googleads/googleads-mobile-unity/issues/598`

But the problem didn't solve.
Any workaround for this error ?

**Comment by kemalsen** [comment]
Same here

**Comment by rampara** [comment]
@Jbstudio425 @kemalsen updating the version of the Google Mobile Ads SDK from 12.0.1 to 15.0.1 in `Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml` should resolve this issue.

**Comment by rampara** [comment]
Closing at duplicate of #695.

**Comment by Jbstudio425** [comment]
Error is gone but the ads are still not showing @rampara

**Comment by rampara** [comment]
@Jbstudio425 please open a new issue with additional details.
