### ISSUE TITLE
Native Advanced Ads

### ISSUE THREAD

**Issue by msureka** [googleads/googleads-mobile-unity#703]
Hello,

We are trying to show Native Ads along with other ad formats like banner, interstitial and rewarded.

As per https://developers.google.com/admob/unity/native-advanced, we downloaded the early access build unitypackage, but on importing it to the project, there are only 2-3 files. There is no API, Mediation, etc. folders in this package?

Are we suppose to remove the old GoogleMobileAds folder and replace it with this one or import it on top of this?

What is the exact process?

Thanks
Mohit

**Comment by rampara** [comment]
@msureka yes, as mentioned in the developer docs integration instructions, you should remove all existing plugin files before integration the Native Advanced version of the plugin.
