### ISSUE TITLE
AdMob desn't work on Huawei/Apple/Xiaomi phones | Reward ADs doesn't show on IOS

### ISSUE THREAD

**Issue by KiVo16** [googleads/googleads-mobile-unity#704]
Hey,

2 Problems:

**1. AdMob desn't work on Huawei/Apple/Xiaomi phones**

So, i always test my games, apps etc.. on huawei phones.

**Everything was working, but now something is wrong.**

I just figured out that AD like Banners and Interstitials don't work on Huawei, Xiaomi and Apple phones. _**- No fill error**_
_**- HandleFailedToReceiveAd event received with message: No fill**_
_**- HandleInterstitialFailedToLoad event received with message: No fill**_

Also i tested the same app on Altacet and Samsung phones - it was working perfectly. 

I tried same thing on yours sample app Hello Word and here's same thing (on Huawei, Xiaomi and Apple phones don't work)
In the past like 1 month ago all ADs work on all phones (Huawei, Apple, Samsung etc...)

I tested app from Android Studio and game from Unity.
**I also tested Official Test AD ids and i tried create new app in AdMob**
**I wrote on AdMob help forum and support wrote that my code implementation is OK.**

**2. Rewarded ADs don't show on IOS**

It's never worked.

When my program try request a Rewarded AD form AdMob this log is showing up:
_**- Cannot find an ad network adapter with the name(s): com.google.ads.mediation.admob.AdMobAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
HandleRewardBasedVideoFailedToLoad event received with message: Failed to receive ad with error: No ad returned from any ad server.**_

-----------------------------------------------------------------------------------------
**Really don't know what to do.**
**I ended coding my game and it's last thing which i need to fix**

**I hope, you'll help me :)**

**I'm working on newsest plugins from Google.**
**Unity 2017.3.1f1**

Regards,
Jacob

**Comment by rampara** [comment]
@KiVo16 on iOS, are you testing with a bundle id that corresponds to an app published on the App Store? Are you able to load test ads without issue?

**Comment by rampara** [comment]
Closing due to non-response.
