### ISSUE TITLE
Rewarded Ad not showing

### ISSUE THREAD

**Issue by mianyaasiraali** [googleads/googleads-mobile-unity#705]
Hi,
I've been using Admob for banners and interstitials and have never encountered a problem. But now i want to implement admob rewarded ad and for some reason i am not getting anything out of it. I've imported the latest admob, my sdk has latest play services and the I'm using the GoogleMobileAdsDemoScript.

**Comment by rampara** [comment]
As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
