### ISSUE TITLE
Ads not showing and crash on request interstitial 

### ISSUE THREAD

**Issue by davegabe** [googleads/googleads-mobile-unity#709]
This is the function I call when it crash
`public void showInt()
    {
        if (interstitial != null && interstitial.IsLoaded())
        {
            interstitial.Show();
        }
        else
        {
           if (interstitial == null)
                RequestInterstitial();//error seems to be in this function
        }
    }
`
This is the function:
`    void RequestInterstitial()
    {
        // These ad units are configured to always serve test ads.
#if UNITY_EDITOR
        string adUnitId = "unused";
#elif UNITY_ANDROID
        string adUnitId = "ca-app-pub-********************/*********";
#elif UNITY_IPHONE
        string adUnitId = "ca-app-pub-********************/*********";
#else
        string adUnitId = "unexpected_platform";
#endif

        // Clean up interstitial ad before creating a new one.
        if (interstitial != null)
        {
            interstitial.Destroy();
        }

        // Create an interstitial.
        interstitial = new InterstitialAd(adUnitId);

        // Register for ad events.
        interstitial.OnAdClosed += HandleOnAdClosed;

        // Load an interstitial ad.
        interstitial.LoadAd(CreateAdRequest());
    }

    private AdRequest CreateAdRequest()
    {
        return new AdRequest.Builder().Build();
    }
`

And here's the error I get:
`E/Unity   (17420): AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ad
s.MobileAds
E/Unity   (17420): java.lang.ClassNotFoundException: com.google.android.gms.ads.MobileAds
E/Unity   (17420):      at java.lang.Class.classForName(Native Method)
E/Unity   (17420):      at java.lang.Class.forName(Class.java:309)
E/Unity   (17420):      at java.lang.Class.forName(Class.java:273)
E/Unity   (17420):      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
E/Unity   (17420):      at com.unity3d.player.UnityPlayer.c(Unknown Source)
E/Unity   (17420):      at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
E/Unity   (17420):      at android.os.Handler.dispatchMessage(Handler.java:98)
E/Unity   (17420):      at android.os.Looper.loop(Looper.java:135)
E/Unity   (17420):      at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
E/Unity   (17420): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.androi
d.gms.ads.MobileAds" on path: DexPathList[[zip file "/data/app/com.AppAndApp.BrawlCards-2/base.apk"]
,nativeLibraryDirectories=[/data/app/com.AppAndApp.BrawlCards-2/lib/arm, /vendor/lib, /system/lib]]
E/Unity   (17420):      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/Unity   (17420):      at java.lang.ClassLoader
`

**Comment by rampara** [comment]
@davegabe looks like you may not be including the required Google Play services dependencies in your project. For technical support regarding integration of this plugin, I would recommend you reach out the [Google Mobile Ads Technical Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
