### ISSUE TITLE
AdMob Ads Not Showing in Android

### ISSUE THREAD

**Issue by siddharth3322** [googleads/googleads-mobile-unity#713]
I have just integrated Admob plugin within my game project. I only want to display Admob fullscreen ads in Android build of game.

I have followed this document from first to last to display ads:
[https://developers.google.com/admob/unity/start](url)

I was getting this kind of messages in debug log:
![yman_log_ads_tag](https://user-images.githubusercontent.com/3082151/42410282-eaff02b6-8204-11e8-9406-ff3d81070a93.png)
![yman_log_unity_tag](https://user-images.githubusercontent.com/3082151/42410285-f00bfb24-8204-11e8-9f5f-def3baf48171.png)

Yes I have just downloaded plugin and using for showing advertisement.
Also plugin files imported completely within project that I have checked but my Admob account is complete new, I have published any game using this.
It may be possible some process is remaining to perform, so can you guide me for this?

Apart from this, I was doing AdMob advertisement setup from few years so I am not a new person in this.

**Comment by rampara** [comment]
@siddharth3322 for technical support with integrating this plugin, I would recommend you reach out on the [Google Mobile Ads Technical Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
