### ISSUE TITLE
Banner not showing up on iOS 10.3.3

### ISSUE THREAD

**Issue by mstfcbn** [googleads/googleads-mobile-unity#714]
Hi. I have integrated Admob plugin within my project. When tested on my iPad with iOS 11.4 it worked fine, but on iPhone 5 with iOS 10.3.3, the banner not showing up. Also I didn't receive an error message with related this issue on Xcode console while bulding and running. I noticed only a warning and error but I'm not sure this is the why. Because I tested about two months ago and worked fine on both of these devices. Maybe helps to solve this issue. Here is the warning and error that I received:

WARNING: 0:4: extension 'GL_EXT_frag_depth' is not supported
ERROR: 0:38: Use of undeclared identifier 'gl_FragDepthEXT'

Also I handled "OnAdFailedToLoad" event and received the following message:
"Failed to receive ad with error: Request Error: No ad to show."

I'm using the followings:
- Unity 2018.1.7f1
- Admob plugin v3.13.1
- Xcode 9.4.1

**Comment by rampara** [comment]
@mstfcbn the `no ad to show` message indicates there wasn't an ad available for your ad request. 
If you are able to load test ads without issue, everything is working as intended. Mediation is a good option for increasing fill rates.

**Comment by mstfcbn** [comment]
I have updated Unity and Admob plugin to latest version and tried again. The issue still exists. On my iPad (iOS 11.4.1) Ads always working fine but on my iPhone (iOS 10.3.3) never works.

**Comment by rampara** [comment]
@mstfcbn I would recommend handling on `OnAdFailedToLoad` ad event to receive more information on why ads failed to load and attempting to load our test ad unit (`ca-app-pub-3940256099942544/2934735716 `). For additional integration support, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
