### ISSUE TITLE
AdMob Ads Not Showing

### ISSUE THREAD

**Issue by blueveno** [googleads/googleads-mobile-unity#715]
I have just downloaded plugin and using for showing advertisement, but not ads show.
If i use old plugin version, ads ready to show. Can you fix this bugs? Thank you so much

**Comment by rampara** [comment]
@blueveno for technical support with integrating this plugin, I would recommend you reach out on the [Google Mobile Ads Technical Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
