### ISSUE TITLE
Rewarded Video Events Are not Working

### ISSUE THREAD

**Issue by rahat10120141** [googleads/googleads-mobile-unity#716]
I opened this issue few months earlier, I show them a video that actually the events are not working even with their hello world file. But unfortunately they closed the issue instead of solving it. Then I switched back to Unity Ads. Now I again I am opening this issue because I need to integrate Admob Video Add Badly. 

Again I am submitting the video file that your events are not working. Please fix this issue instead of closing the issue.
[Video](https://www.youtube.com/watch?v=ASe5WTE6gpo&t=9s)

**Comment by rampara** [comment]
For integration issues, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support. Keep in mind, you shouldn't be using Unity API from ad event callbacks as described in this [blog post](https://ads-developers.googleblog.com/2016/04/handling-android-ad-events-in-unity.html).
