### ISSUE TITLE
Separate iOS GMA Adapter and Network SDK

### ISSUE THREAD

**Issue by MartinGonzalez** [googleads/googleads-mobile-unity#717]
Is there a way that the GMA adapter for any network (ex: Tapjoy) and the network SDK to be separated for iOS?

Right now in the mediations, adapters and SDKS are in the same PodFile

https://cocoapods.org/pods/GoogleMobileAdsMediationTapjoy

In Android this is separated but in iOS not. This would be really useful to not couple the sdk with the adpater.

**Comment by rampara** [comment]
@MartinGonzalez Android will soon be updated to follow the iOS approach. Why would you want the adapters without the SDK?

**Comment by MartinGonzalez** [comment]
@rampara Thanks for your answer!

This is to avoid 3rd parties classes collisions. There are other mediators that also bring 3rd party sdks and classes collide when building because we have duplicate code.

Splitting this file into XXXAdapterDependencies.xml and XXXSDKDependencies.xml would be the best approach, so if we already have that sdk or other mediator integrates it, we can only remove a file from GMA.

I will show you what we've done to avoid collisions with IronSource

First we have to ask IronSource for EmptyAdapters (empty meaning no sdk)

The we split the files like this:

**GMATapjoyAdapterDependencies.xml**
```<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.ads.mediation:tapjoy:11.12.2.0">
    </androidPackage>
  </androidPackages>

  <iosPods>
    <iosPod name="Google-Mobile-Ads-SDK" version="7.31.0">
      <sources>
        <source>https://github.com/CocoaPods/Specs</source>
      </sources>
    </iosPod>
  </iosPods>
</dependencies>
```

**TapjoySDKDependencies.xml**
```<dependencies>
  <androidPackages>
    <androidPackage spec="com.tapjoy:tapjoy-android-sdk:11.12.2">
    </androidPackage>
  </androidPackages>

  <iosPods>
    <iosPod name="TapjoySDK" version="11.12.2">
      <sources>
        <source>https://github.com/CocoaPods/Specs</source>
      </sources>
    </iosPod>
  </iosPods>
</dependencies>
```

This approach is really useful. :D

**Comment by MartinGonzalez** [comment]
Hi there!
So this cannot be done?
