### ISSUE TITLE
AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.MobileAds

### ISSUE THREAD

**Issue by AsilKan38** [googleads/googleads-mobile-unity#718]
Hello iam still learning about unity and android game developing. i make a simple game and i want to use admobs but ads not showing 
İ try Unity Jar Resolver and i change the androidPackage spec="com.google.android.gms:play-services-ads:12.0.1 to 15.0.1

here is the Logcat
AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.MobileAds
07-13 14:04:52.215  2086  2126 E Unity   : java.lang.ClassNotFoundException: com.google.android.gms.ads.MobileAds
07-13 14:04:52.215  2086  2126 E Unity   :      at java.lang.Class.classForName(Native Method)
07-13 14:04:52.215  2086  2126 E Unity   :      at java.lang.Class.forName(Class.java:324)
07-13 14:04:52.215  2086  2126 E Unity   :      at java.lang.Class.forName(Class.java:285)
07-13 14:04:52.215  2086  2126 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
07-13 14:04:52.215  2086  2126 E Unity   :      at com.unity3d.player.UnityPlayer.c(Unknown Source)
07-13 14:04:52.215  2086  2126 E Unity   :      at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
07-13 14:04:52.215  2086  2126 E Unity   :      at android.os.MessageQueue.next(MessageQueue.java:392)
07-13 14:04:52.215  2086  2126 E Unity   :      at android.os.Looper.loop(Looper.java:141)
07-13 14:04:52.215  2086  2126 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
07-13 14:04:52.215  2086  2126 E Unity   : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.MobileAds" on path: DexPathList[[zip file "/data/app/deneme.flappybird-1/base.apk"],nativeLibraryDirectories=[/data/app/deneme.flappybird-1/lib/arm, /data/app/deneme.flappybird-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]`

**Comment by AsilKan38** [comment]
Yes I did it

**Comment by arcv** [comment]
Check if Minify option is active in the Unity publising settings. 
Edit -> Project Settings -> Player -> Publishing Settings -> Minify options to None

**Comment by AsilKan38** [comment]
both of them are none

**Comment by rampara** [comment]
@AsilKan38 can you provide a Unity test project that reproduces this issue. It would help get to the bottom of what is causing this issue for you.
