### ISSUE TITLE
Interstitial ads is played when run rewardBasedVideo.Show();

### ISSUE THREAD

**Issue by ciogenis** [googleads/googleads-mobile-unity#719]
I've tested in
- Unity : 2017.4.1f1
- google mobile ads : 3.14.0, 3.13.1

Test app ID is working good. But if I use my admob app id, fail message is showed.
And I don't understand why interstital ads is showing when I run rewardBasedVideo.Show() function in this case. Is it normal?

- logcat log
------------------------------------------------------------------------------------------------
W/Ads     ( 1106): Fail to instantiate adapter com.google.DummyAdapter
W/Ads     ( 1106): android.os.RemoteException
W/Ads     ( 1106):      at com.google.android.gms.internal.zzwe.zzbj(Unknown Source)
W/Ads     ( 1106):      at com.google.android.gms.internal.zzwe.zzbi(Unknown Source)
W/Ads     ( 1106):      at com.google.android.gms.internal.zzwe.zzbg(Unknown Source)
W/Ads     ( 1106):      at com.google.android.gms.internal.zzwg.onTransact(Unknown Source)
W/Ads     ( 1106):      at android.os.Binder.transact(Binder.java:380)
W/Ads     ( 1106):      at nb.a(:com.google.android.gms.dynamite_adsdynamite@12872010@12.8.72 (020400-202717283):10)
W/Ads     ( 1106):      at com.google.android.gms.ads.internal.mediation.client.d.a(:com.google.android.gms.dynamite_adsdynamite@12872010@12.8.72 (020400-202717283):5)
W/Ads     ( 1106):      at com.google.android.gms.ads.internal.reward.a.a(:com.google.android.gms.dynamite_adsdynamite@12872010@12.8.72 (020400-202717283):16)
W/Ads     ( 1106):      at com.google.android.gms.ads.internal.reward.mediation.j.b(:com.google.android.gms.dynamite_adsdynamite@12872010@12.8.72 (020400-202717283):54)
W/Ads     ( 1106):      at com.google.android.gms.ads.internal.util.b.run(:com.google.android.gms.dynamite_adsdynamite@12872010@12.8.72 (020400-202717283):4)
W/Ads     ( 1106):      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/Ads     ( 1106):      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/Ads     ( 1106):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/Ads     ( 1106):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/Ads     ( 1106):      at java.lang.Thread.run(Thread.java:818)
W/Ads     ( 1106): Failed to load ad: 3
I/Unity   ( 1106): HandleRewardBasedVideoFailedToLoad event received with message: No fill
I/Unity   ( 1106):
I/Unity   ( 1106): (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
I/Unity   ( 1106):
I/Unity   ( 1106): HandleInterstitialLoaded event received
I/Unity   ( 1106):
I/Unity   ( 1106): (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by rampara** [comment]
@ciogenis can you provide the code you're using to request and display rewarded video ads?

**Comment by rampara** [comment]
Closing issue due to non-response.
