### ISSUE TITLE
Rewarded video callbacks not occurring in this particular scenario.

### ISSUE THREAD

**Issue by sarthakz9** [googleads/googleads-mobile-unity#724]
Rewarded video callbacks don't work as expected in the following case.

This is how you can reproduce this error for Admob unity & android phones.

1. make 2 scenes, say A and B.
2. you can go from scene A to scene B and vice versa.
3. All your rewarded video adv. logics and callbacks should be written in script present in scene B.
4. now, when you will go to scene B for the first time your callbacks will be init. for the first time and 
    everything will work fine.
5. go back from scene B to scene A and then back to scene B.
6. this time your rewarded video callback will be setup for the second time. you will see that most of the callbacks in this script are not called as expected.

I think the singleton behavior of admob rewarded video ads is causing the issue and callbacks when initialized the 2nd time are not working correctly.

7. Also when you close the game and do the same thing again. The callbacks will work again for the first time you are in scene B.

**Comment by programmermattsrum** [comment]
@sarthakz9 I have the same issue and figured out a hacky solution

In the RewardBasedVideoAd.cs file I changed a couple things so it always creates a new instance.
```
//Original Version
private static readonly RewardBasedVideoAd instance = new RewardBasedVideoAd();

public static RewardBasedVideoAd Instance
        {
            get
            {
                return instance;
            }
        }

//My version
//Remove readonly
private static RewardBasedVideoAd instance = new RewardBasedVideoAd();
public static RewardBasedVideoAd Instance
        {
            get
            {
                instance = new RewardBasedVideoAd();  //ADDED to create instance every time
                return instance;
            }
        }
```

Maybe they will take note what worked for me and fix the problem.

**Comment by rampara** [comment]
@sarthakz9 @programmermattsrum this issue is caused by the singleton design pattern employed for rewarded video ads. There is an upcoming refactor of rewarded ads in the GMA SDK that should address this issue.

**Comment by programmermattsrum** [comment]
@rampara Can we be notified when this is released?

**Comment by rampara** [comment]
Don't have any release dates to share at the moment.
