### ISSUE TITLE
Error: ??????????????? "uses-sdk" ?????????????????? "tools:overrideLibrary" ????????? "tools" ????????????

### ISSUE THREAD

**Issue by ItsGodHand** [googleads/googleads-mobile-unity#726]
`/Volumes/mac/Use/Project/DHSCLI/Client/unity.proj/Temp/StagingArea/AndroidManifest-main.xml:3:3-72 Error:
	uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library /Volumes/mac/Use/Project/DHSCLI/Client/unity.proj/Temp/StagingArea/android-libraries/com.android.support.customtabs-26.1.0/AndroidManifest.xml as the library might be using APIs not available in 14
	Suggestion: use a compatible library with a minSdk of at most 14,
		or increase this project's minSdk version to at least 15,
		or use tools:overrideLibrary="android.support.customtabs" to force usage (may lead to runtime failures)

UnityEditor.HostView:OnGUI()`
How to do it?

**Comment by rampara** [comment]
@ItsGodHand Increasing the minimum SDK version under Android build settings should resolve this issue for you.
