### ISSUE TITLE
Does not show any thing

### ISSUE THREAD

**Issue by coderpavel** [googleads/googleads-mobile-unity#728]
I wrote code, but ad does not appear
HERE IS MY CODE

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GoogleMobileAds.Api;

public class GoogleMobileAdsDemoScript : MonoBehaviour {

	private InterstitialAd interstitial;

    public void Start()
    {
        #if UNITY_ANDROID
            string appId = "ca-app-pub-6424440213593674~9492123081";
        #elif UNITY_IPHONE
            string appId = "ca-app-pub-3940256099942544~1458002511";
        #else
            string appId = "unexpected_platform";
        #endif

        // Initialize the Google Mobile Ads SDK.
        MobileAds.Initialize(appId);
    }

	
	private void RequestInterstitial()
	{
		#if UNITY_ANDROID
			string adUnitId = "ca-app-pub-6424440213593674/3136869238";
		#elif UNITY_IPHONE
			string adUnitId = "ca-app-pub-3940256099942544/4411468910";
		#else
			string adUnitId = "unexpected_platform";
		#endif

		// Initialize an InterstitialAd.
		interstitial = new InterstitialAd(adUnitId);
		    // Create an empty ad request.
    AdRequest request = new AdRequest.Builder().Build();
    // Load the interstitial with the request.
    interstitial.LoadAd(request);

	}

	public void GameOver()
     {
       if (interstitial.IsLoaded()) {
       interstitial.Show();
      }
     }

     }

**Comment by z5084633** [comment]
Are you calling the GameOver function at all? Also you will not see an ad unless you build it and run it on a device. Do you get Loading dummy ad in the console when running it in the unity editor?

**Comment by rampara** [comment]
For plugin integration issues I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.

**Comment by coderpavel** [comment]
Yes, I got dummy message and also I have built my app, but on the device I did not get add.

**Comment by coderpavel** [comment]
GameOver function is called after clicking on a btn

**Comment by coderpavel** [comment]
I do not know what is a problem
