### ISSUE TITLE
Memory Leak in the HelloWorld project

### ISSUE THREAD

**Issue by assafcohen1** [googleads/googleads-mobile-unity#729]
Hi,
When using the plugin in iOS, It looks like the memory consumption only goes up, until the app crashes.
on iPad2, Unity 2018.2, SDK 3.14, Xcode 9.4 and the default HelloWorld Project (also tested with 3.13 and 3.12 and other iOS devices)
![screen shot 2018-07-22 at 12 03 44](https://user-images.githubusercontent.com/10744930/43044045-5d1e4c96-8da7-11e8-9dad-7419e13adcad.png)
All I did is clicking "Request Interstitial", waiting a few seconds, Clicking "Show", waiting a few seconds and clicking "Destroy", the spike usually happen after clicking destroy.

**Comment by UragayalaDeepika** [comment]
@assafcohen1 Are you still seeing this issue with the latest verison of the plugin? If you could confirm this, we will take a look into this issue again.

**Comment by UragayalaDeepika** [comment]
@SozapBo I'm unable to reproduce this memory leak when using the latest version of the Unity plugin and using Instruments to test. You can notice in the attached screenshot that the memory that was utilized when the Interstitial was requested and shown is later flushed when it is closed and/or destroyed. I'm unable to reproduce any memory leaks.
![2019-06-24](https://user-images.githubusercontent.com/25670474/60211745-bb9ba200-982d-11e9-82c6-b98673669540.png)

**Comment by assafcohen1** [comment]
Hi, confirmed, it does not happen with the latest version.
