### ISSUE TITLE
Admob banner ads not showing up after building but test ads worked.

### ISSUE THREAD

**Issue by z5084633** [googleads/googleads-mobile-unity#730]
While I was making the game I used the Admob test IDs and when I built the game and tested it on my phone everything worked fine, I would get a banner ad saying, this is a admob test ad. Once I finished making the game, all I did was replace the AppID and unitID with the real ones that were in my admob account but when I published the game today I see that there are no banner ads showing. Any ideas why it is not working when I change to the real IDs? Using Plugin v3.14.0. Any Help is appreciated!

    private string appId = "ca-app-pub-xxxxxxxxx";
    private BannerView bannerView;

    private void Start()
    {
        MobileAds.Initialize(appId);
    }

    public void RequestBanner() {

        string adUnitId = "ca-app-pub-xxxxxxxxxx";

        bannerView = new BannerView(adUnitId, AdSize.Banner, AdPosition.Bottom);
        bannerView.OnAdLoaded += DisplayBanner;
        AdRequest request = new AdRequest.Builder().Build();
        bannerView.LoadAd(request);

    }

    private void DisplayBanner(object sender, EventArgs args) {
        bannerView.Show();
    }

**Comment by rampara** [comment]
@z5084633 as test ads are working without issue, the problem you are encountering does not seem to be caused by this plugin but rather a serving issue. I would recommend you reach out on the  [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
