### ISSUE TITLE
How to know when MobileAds is initialized?

### ISSUE THREAD

**Issue by rotter** [googleads/googleads-mobile-unity#731]
I am trying to use:
MobileAds.SetApplicationVolume(xxxx);

But am getting an error/exception saying MobileAds isnt initialized yet. I dont think I am supposed to call MobileAds.Initialize(), right? Because I have never called this in the past, so I think it is called automatically internally.

So my question is, is there a way to know if MobileAds is initialized? This way I can call SetApplicationVolume without throwing an exception.

In fact after some more tests it seems it's never initialized. Even when I call SetAppVolume after showing a couple interstitials and banners it still gives me the same error:

AndroidJavaException: java.lang.IllegalStateException: MobileAds.initialize() must be called prior to setting the app volume.

**Comment by arcv** [comment]
According to [MobileAds.cs](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Api/MobileAds.cs) source, you should call `MobileAds.Initialize(appId)` before calling `SetApplicationVolume`

**Comment by rampara** [comment]
@rotter there is currently no API to poll initialization state of the GMA SDK. As @arcv mentioned, it is best practice to call `MobileAds.Initialize()` as early as possible.

**Comment by rotter** [comment]
Thanks! But just to make sure, I need to call this MobileAds.Initialize() myself (even if I dont use the SetAppVolume)? This seems to be an important part of the admob plugin workflow, and I have never called this method before (on Unity at least, dont remember back when my game was native Android).

**Comment by rampara** [comment]
@rotter yep. You should call `MobileAds.Initialize()` before interacting with any GMA SDK API.
