### ISSUE TITLE
admob banner height issue 

### ISSUE THREAD

**Issue by guyhazi** [googleads/googleads-mobile-unity#734]
in galaxy 9s+ show admob banner at bottom.
swipe bottom of screen for bottom navigation bar to pop up.
press the left button to view all open apps.
select the same app.
**banner will raise above the navigation bar and after few seconds/refresh will go down again.
the last stage doesnt happen all the time.

so the banner is higher then expected for few seconds, any idea how to handle this issue?

**Comment by rchallenger** [comment]
Try playing with immersive mode. It helped me sometimes

**Comment by rampara** [comment]
closing as duplicate of #687.
