### ISSUE TITLE
UnityAds Unity Mediation Plugin needs to be updated

### ISSUE THREAD

**Issue by mgrogin** [googleads/googleads-mobile-unity#738]
I think UnityAds Unity Mediation Plugin needs to be updated to match the new versions that are here
https://bintray.com/google/mobile-ads-adapters-ios/UnityAdapter/2.3.0.0#files/UnityAdapter/2.3.0.0

**Comment by mgrogin** [comment]
I updated Assets/GoogleMobileAds/Editor/UnityMediationDependencies.xml

changed line
`    <iosPod name="GoogleMobileAdsMediationUnity" version="2.2.1.0">`
to
`    <iosPod name="GoogleMobileAdsMediationUnity" version="2.2.1.1">`

**whole file:**
```
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.ads.mediation:unity:2.2.1.0">
      <repositories>
        <repository>https://jcenter.bintray.com/</repository>
      </repositories>
    </androidPackage>
    <androidPackage spec="com.unity3d.ads:unity-ads:2.2.1">
      <repositories>
        <repository>https://jcenter.bintray.com/</repository>
      </repositories>
    </androidPackage>
  </androidPackages>

  <iosPods>
    <iosPod name="GoogleMobileAdsMediationUnity" version="2.2.1.1">
      <sources>
        <source>https://github.com/CocoaPods/Specs</source>
      </sources>
    </iosPod>
  </iosPods>
</dependencies>
```

I know theres already 2.3 out but no pod and I didn't change android version yet.

Any chance I'm breaking something by making this change?

**Comment by rampara** [comment]
@mgrogin updates are pushed to mediation packages on a weekly basis after recertifying that there are no breaking 3rd party SDK changes. I wouldn't be able to tell if you if there are breaking changes until the updated 3rd party SDK is certified against a new build of the adapter.
