### ISSUE TITLE
Admob does not work at all

### ISSUE THREAD

**Issue by coderpavel** [googleads/googleads-mobile-unity#740]
I used latest release of the plugin. for the test I used Hello world scene, I added  Test adds into code

Banner | ca-app-pub-3940256099942544/6300978111
-- | --
Interstitial | ca-app-pub-3940256099942544/1033173712

in Unity I see dummy message, but when I build and test on several devices, ad does not work, it does not show anything on a device

**Comment by rampara** [comment]
@coderpavel are you receiving an ad failed to load ad event? If so, what error information did your receive?

**Comment by coderpavel** [comment]
I didn't get any message

**Comment by rampara** [comment]
For integration issues with this plugin, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
