### ISSUE TITLE
java.lang.ClassNotFoundException: com.google.android.gms.ads.MobileAds

### ISSUE THREAD

**Issue by mongpoo94** [googleads/googleads-mobile-unity#743]
![dd](https://user-images.githubusercontent.com/20275074/43878556-c2fb7da4-9bda-11e8-9656-4f2b3fd3becd.png)
![sdf](https://user-images.githubusercontent.com/20275074/43878571-d2113824-9bda-11e8-8b0d-ebfc4a4717c1.png)
i want put ad in my game made by unity. but error comes out. is there any solution for it?

**Comment by mongpoo94** [comment]
I did all documentation told(https://developers.google.com/admob/unity/start). but still not work.

**Comment by mongpoo94** [comment]
![dddsd](https://user-images.githubusercontent.com/20275074/43884454-1ea5ca22-9bf1-11e8-8bda-f2007fad0e08.png)

**Comment by rchallenger** [comment]
Here is what [Developer guide](https://firebase.google.com/docs/admob/unity/start) says:
![alt text](https://developers.google.com/admob/images/unity_dependencies.png)

**Comment by mongpoo94** [comment]
i don't have that option.. Resove or Force Resove

**Comment by rampara** [comment]
@mongpoo94 As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
