### ISSUE TITLE
Rewarded Videos fail to load on iOS

### ISSUE THREAD

**Issue by fschaar** [googleads/googleads-mobile-unity#745]
I'm getting crazy on this.

While this Plugin works on Android and shows some Ads, loading of video always fails on iOS. I tried the test-Ads as well as own ads. I also added unity Ads network to my admob account, to make sure there are ads available. nothing works.
It always fires the ad failed to load event.

Any Idea, what i'm doing wrong?

Here is my code:

`public class AdmobManager : MonoBehaviour {
	private static AdmobManager _admobManager;

	private static RewardBasedVideoAd rewardBasedVideo;
	private static InterstitialAd interstitial;
	private static BannerView banner;
	private string appId = "";
	private string adVideoUnitId = "";
	private string adInterstitialId = "";
	private string adBannerUnitId = "";

	public static AdmobManager instance
	{
		get
		{
			return _admobManager;
		}
	}

	void Awake()
	{
		_admobManager = this;
		DontDestroyOnLoad(this.gameObject);

		appId = "unused";
		#if UNITY_ANDROID
        appId = "<appid>";
		#elif UNITY_IOS
        //ApoRed
        appId = "<appid>";
       
		#else
			appId = "unexpected_platform";
		#endif

		MobileAds.Initialize(appId);
		rewardBasedVideo = RewardBasedVideoAd.Instance;

		InitRewardBasedVideoCallback();
		RequestRewardBasedVideo();

		//LoadInterstitial();
	}

	private AdRequest CreateAdRequest()
	{
		return new AdRequest.Builder()
			.AddTestDevice(AdRequest.TestDeviceSimulator)
			.AddTestDevice("0123456789ABCDEF0123456789ABCDEF")
			.AddKeyword("game")
			.SetGender(Gender.Male)
			.SetBirthday(new DateTime(1985, 1, 1))
			.TagForChildDirectedTreatment(false)
			.AddExtra("color_bg", "9B30FF")
			.Build();
	}

	private void InitRewardBasedVideoCallback()
	{
		rewardBasedVideo.OnAdLoaded += HandleRewardBasedVideoLoaded;    // Called when an ad request has successfully loaded.
		rewardBasedVideo.OnAdFailedToLoad += HandleRewardBasedVideoFailedToLoad;    // Called when an ad request failed to load.
		rewardBasedVideo.OnAdOpening += HandleRewardBasedVideoOpened;   // Called when an ad is shown.
		rewardBasedVideo.OnAdStarted += HandleRewardBasedVideoStarted;  // Called when the ad starts to play.
		rewardBasedVideo.OnAdRewarded += HandleRewardBasedVideoRewarded;    // Called when the user should be rewarded for watching a video.
		rewardBasedVideo.OnAdClosed += HandleRewardBasedVideoClosed;    // Called when the ad is closed.
		rewardBasedVideo.OnAdLeavingApplication += HandleRewardBasedVideoLeftApplication;   // Called when the ad click caused the user to leave the application.
	}

	#region Control RewardBasedVideo
	/// <summary>
	///	admob rewarded video
	/// </summary>
	public void RequestRewardBasedVideo()
	{
		adVideoUnitId = "unused";
		#if UNITY_ANDROID
			adVideoUnitId = "<adid>";
      
        #elif UNITY_IOS
        adVideoUnitId = "<adid>";
      
        #else
			adVideoUnitId = "unexpected_platform";
		#endif

		AdRequest adRequest = new AdRequest.Builder().Build();
        print("AdUnitId: " + adVideoUnitId + " appid: " + appId);
		rewardBasedVideo.LoadAd(adRequest, adVideoUnitId);
	}

	public bool ShowRewardBasedVideo()
	{
		if (rewardBasedVideo.IsLoaded())
		{
            print("Reward based video ad is loaded");
			rewardBasedVideo.Show();
			//Debug.LogError("---------------------------show rewarded video-------------------");
			return true;
		}
		else
		{
			print("Reward based video ad is not ready yet");
			//MessagePanel.ShowMessage("Ad is not ready. Please try again later.");
			return false;
		}
	}
	#endregion

	#region RewardBasedVideo callback handlers

	public void HandleRewardBasedVideoLoaded(object sender, EventArgs args)
	{
        print("Reward based video Loaded");
		//print("HandleRewardBasedVideoLoaded event received");

	}

	public void HandleRewardBasedVideoFailedToLoad(object sender, AdFailedToLoadEventArgs args)
	{
		//print("HandleRewardBasedVideoFailedToLoad event received with message: " + args.Message);
		
        print("Reward based video Failed");
	}

	public void HandleRewardBasedVideoOpened(object sender, EventArgs args)
	{
		//print("HandleRewardBasedVideoOpened event received");
	}

	public void HandleRewardBasedVideoStarted(object sender, EventArgs args)
	{
		//print("HandleRewardBasedVideoStarted event received");
	}

	public void HandleRewardBasedVideoClosed(object sender, EventArgs args)
	{
		//print("HandleRewardBasedVideoClosed event received");
		RequestRewardBasedVideo();
	}

	public void HandleRewardBasedVideoRewarded(object sender, Reward args)
	{
		string type = args.Type;
		double amount = args.Amount;
        print("Reward based video Rewarded");
		//print("HandleRewardBasedVideoRewarded event received for " + amount.ToString() + " " + type);
		RequestRewardBasedVideo();
	}

	public void HandleRewardBasedVideoLeftApplication(object sender, EventArgs args)
	{
		//print("HandleRewardBasedVideoLeftApplication event received");
	}

	public void HandleRewardBasedVideoCompleted(object sender, EventArgs args)
	{
		print("Reward based video completed");
        RequestRewardBasedVideo();
	}

	#endregion

}
`

Hope somebody can hint me in the right direction. I'm really desperate!

**Comment by ericleich** [comment]
If you haven't already, can you post this question to the [AdMob developer forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) in the game engines section? This looks like a support question and you'll get a quicker response there. Nothing in particular looks wrong with the code, and the fact that the code is working on Android means that the only difference in implementation would be the ad unit ID, so the conversation will likely boil down around the ad unit being valid.

**Comment by fschaar** [comment]
Hi,

thanks for the reply. That's what i  thought to. I also checked the ID several times. One tester also said he saw some ad already. The App was not in store at that time. May it be possible, that it doesn't work, when the app isn't connected to the AdMob Account, which can only be done, when the app is published in the store?

**Comment by rampara** [comment]
@fschaar this is a known issue on our end where if bundle id/package name for an app does not correspond to a published app, you may notice fill issues. A quick way to verify would to test with a bundle id/ package name of a published app. Once your app is published, the app will receive ads as expected.

**Comment by rampara** [comment]
As @ericleich mentioned, for further support with this issue, you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
