### ISSUE TITLE
Native Advance Ads Loaded Game Hang For iOS

### ISSUE THREAD

**Issue by karanvariya** [googleads/googleads-mobile-unity#747]
hi..

I have use this example,see link below
https://developers.google.com/admob/unity/native-advanced-unified

The problem is native ads texture downloaded time iOS device hang.android native ads smooth work.

I have also try multithread request.but this not work.

Anyone suggest?how to solve this issue?

Thanks in advance.

**Comment by rampara** [comment]
@karanvariya there is an upcoming update to this plugin to address this issue.

**Comment by rampara** [comment]
Addressed in v3.15.1.2 on the plugin.
