### ISSUE TITLE
wrong position of SmartBanner on some devices

### ISSUE THREAD

**Issue by Piotr12** [googleads/googleads-mobile-unity#749]
Seems a duplicate of #744 but I am unable to post my comment there for some reason.

This screen is from pre-launch report:

 * Galaxy S7 edge
 * Spanish (United States)
 * Android 6.0 
 * Unity 2018.2
 * Admob package v3.15

`banner = new BannerView(Config.BANNER_AD_ID, AdSize.SmartBanner, AdPosition.Top);`

I was unable to replicate this on my device (but its not S7 edge).

![admob_wrong_position](https://user-images.githubusercontent.com/9336697/44616054-30d2cb00-a849-11e8-8925-9103b3f7c08b.png)

**Comment by serge-shaldanov** [comment]
Are any news there? I have the same problem for Huawei Honor 8X. It seems the right corner of screen (cutout) is ignored when positioning of banner, so it always displayed at ~80px from right corner of screen.

**Comment by stowy** [comment]
Please try [version 3.17.0](https://github.com/googleads/googleads-mobile-unity/releases/tag/3.17.0).

**Comment by UragayalaDeepika** [comment]
@Piotr12 Can you please check with the latest verison and let us know?

**Comment by UragayalaDeepika** [comment]
Closing this for now. Feel free to comment here so that we can reinvestigate this issue if it is still reproducible with the latest version.
