### ISSUE TITLE
Can't seem to position (smart) banner ad where I want.

### ISSUE THREAD

**Issue by devingDev** [googleads/googleads-mobile-unity#751]
In Unity :
I have some sort of navigation bar on the bottom. ( i guess something like BottomNavigationBar )
I have canvas set to scale with screen size and match width/height set to 0.5 and reference resolution is 1080x1920 (portrait game)

So I now want to place the ad right above the bar on the bottom which in the editor is like 150 px high (at least thats what I set it to when I was in 1080x1920 in screen size selection in Game tab in unity)

problem is I don't get anything. I tried lots of different calculations but I just can't seem to get it right. Sometimes its just 10 pixels away from being perfect sometimes it doesn't appear at all. I don't know how to solve this

The black area is more game area, its fullscreen. No statusbar
Testing it on my iPhone SE . which has 326 dpi , 1136 height and 640 width as reported by unity Screen. values

I had this problem once before but gave up as it was really frustating trying it so many times without luck. Before I think I was using standard ad size. Right now I am using Smartbanner size.

        bannerView = new BannerView(ADMOB_BANNER_ID, AdSize.SmartBanner, 0, yValueBanner);

I wanna know how to calculate yValueBanner so it comes out on any phone (dpi / screen size) as this image :

![how](https://user-images.githubusercontent.com/17065236/44629446-c6f11900-a94f-11e8-8755-84c5a8ffbea0.png)

**Comment by UragayalaDeepika** [comment]
Hello there,

Do you still have any issue with this? If you are looking to determine the height fo a SMART_BANNER, then you can go through this article: https://developers.google.com/admob/ios/banner#smart_banners

"Smart Banners on iPhones have a height of 50 points in portrait and 32 points in landscape. On iPads, height is 90 points in both portrait and landscape."

Let us know if you need anything else.

**Comment by stowy** [comment]
Please try [version 3.17.0](https://github.com/googleads/googleads-mobile-unity/releases/tag/3.17.0).

**Comment by UragayalaDeepika** [comment]
@devingDev Can you please try with the latest version and let us know?

**Comment by UragayalaDeepika** [comment]
Closing this for now. Feel free to comment here so that we can reinvestigate this issue if it is still reproducible with the latest version.
