### ISSUE TITLE
Interstitial ad not showing on iOS

### ISSUE THREAD

**Issue by devingDev** [googleads/googleads-mobile-unity#752]
hi i have the banner ad working but the interstitial does not work.
I get the callback that ad is loaded, IsLoaded() returns true.
But calling .Show() does not show anything and I do not see any callback like cancel or error or similiar.
And nothing shows up on screen.

**Comment by rampara** [comment]
@devingDev are you able to consistently reproduce the issue? If so, can you provide a Unity project that in which this issue is present.

**Comment by rampara** [comment]
@devingDev glad to here the issue has been resolved for you.
