### ISSUE TITLE
v3.15.0 version

### ISSUE THREAD

**Issue by scorp2007** [googleads/googleads-mobile-unity#754]
Why do not I show ads in this version at all? Although earlier I worked with previous versions and I had no problems. Also I see that the weight of the plug-in of this version is less than 300 kb, and in other versions of the plug-in it is about 8 mb. Maybe it's some kind of mistake?

**Comment by rampara** [comment]
@scorp2007 For integration issues with this plugin, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
