### ISSUE TITLE
BannerView.MediationAdapterClassName() is causing a Crash on Android

### ISSUE THREAD

**Issue by kobyle69** [googleads/googleads-mobile-unity#756]
After 20 hours, and 100 unknown crashes, I found out that calling BannerView.MediationAdapterClassName() is causing a crash on my S8+ device.

It seems to work for interstitial/rewardvideos though I encountered rare issues with it on them as well.

Code Snippet:
```
private string m_MediationNetworkName { get { return m_BannerView != null ? m_BannerView.MediationAdapterClassName() : "AdMob"; } }


private void HandleOnAdLoaded(object i_Sender, EventArgs i_Args)
{
        Debug.LogErrorFormat("Banner-Loaded, Network: {0}", m_MediationNetworkName);
}
```

Without the above Debug.Log, the game won't crash and the banner will be shown succesfully.

This happens on v3.13.1 (12.0.1) + v3.15.1 (15.0.1)

**Comment by rampara** [comment]
Closing due to non-response.
