### ISSUE TITLE
multiple dex files define Error with android build

### ISSUE THREAD

**Issue by armnotstrong** [googleads/googleads-mobile-unity#758]
Hi, I am using the latest AdMob unity plugin(V3.15.1) together with firebase SDK to build an android apk

The problem is that it will complain about this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/common/api/internal/zzcc;
```

Have been struggling with this problem whole day and really need some help

here is the hierarchy of the project folder of Unity:

![qq 20180905212158](https://user-images.githubusercontent.com/3839691/45095908-d3e0ea00-b151-11e8-9249-c25f62497d58.png)

**Comment by kobyle69** [comment]
Same here

**Comment by rampara** [comment]
@armnotstrong @kobyle69 it looks like the issue you're experiencing is caused by using multiple conflicting versions of Google Play services dependencies. Can you ensure you're using the latest version of this plugin and the Firebase plugin. Can you also force a clean dependency resolution by selecting `Assets -> Play Services Resolver -> Android Resolver -> Force Resolve`.

**Comment by armnotstrong** [comment]
Thanks, @rampara things work now after A Force Resolve of the Android Resolver

But the interesting thing is I have tried deleting all the `com.google.xxx` plugins and let the resolver do a fresh resolve but didn't get any luck, So why a Force Resolve will work?

Thanks anyway @kobyle69 you could also try if a ForceResolve will give you luck :+1:

**Comment by rampara** [comment]
I believe some of the dependency resolution steps are cached where as force resolve starts from scratch. Though the [Play Services Resolver repo](https://github.com/googlesamples/unity-jar-resolver) is a better bet to get a more thorough answer.
