### ISSUE TITLE
Video Rewarded Getting Called Twice After Reloading The Scene

### ISSUE THREAD

**Issue by 1exip** [googleads/googleads-mobile-unity#759]
I have tried reimporting the plugin, reinstalling the jdk and the sdk. Nothing works, Video Rewarded and Video Closed gets called twice

**Comment by rampara** [comment]
@1exip I'm having trouble reproducing this behavior. Can you provide a test project that demonstrates this issue?

**Comment by rampara** [comment]
Closing due to non-response.
