### ISSUE TITLE
Compilation errors related to missing interfaces

### ISSUE THREAD

**Issue by 08irfan** [googleads/googleads-mobile-unity#760]
Getting following errors on Xcode while building the code.

**No visible @interface for 'GADNativeCustomTemplateAd' declares the selector 'setCustomClickHandler:'**

**No visible @interface for 'GADNativeCustomTemplateAd' declares the selector 'performClickOnAssetWithKey:'**

![screen shot 2018-09-11 at 11 36 26 am](https://user-images.githubusercontent.com/6177881/45342316-fe4dff80-b5b6-11e8-940e-3d96142e0bae.png)

**Comment by rampara** [comment]
@08irfan I wasn't able to reproduce this issue. Can you provide a sample or test project that does?

**Comment by rampara** [comment]
Closing due to non-response.
