### ISSUE TITLE
MonoPInvokeCallback ambiguous reference

### ISSUE THREAD

**Issue by ajon542** [googleads/googleads-mobile-unity#761]
The MonoPInvokeCallbackAttribute is in the global namespace which is conflicting with other 3rd party libraries. Shall I create a pull request for moving it into a GoogleMobileAds namespace?

**Comment by rampara** [comment]
@ajon542 Pull requests are always encouraged.

**Comment by superbderrick** [comment]
Hi there, is it merged the commit?

When I tried to build latest admob sdk ,I met build error while building for iOS Platfrom

`Library/PackageCache/com.unity.mobile.notifications@1.0.3/Runtime/iOS/iOSNotificationsWrapper.cs(140,4): error CS0433: The type 'MonoPInvokeCallbackAttribute' exists in both 'GoogleMobileAds.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'MobileNativePopups, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
`
