### ISSUE TITLE
MoPub mediation unity package missing MoPub.cs

### ISSUE THREAD

**Issue by arminho** [googleads/googleads-mobile-unity#762]
When following the instructions to add the MoPub mediation unity package to a unity project, MoPub.cs is missing from the unity package.

https://developers.google.com/admob/unity/mediation/mopub#step_3_import_the_mopub_sdk_and_adapter

![image](https://user-images.githubusercontent.com/453716/45580769-f74b1980-b862-11e8-9c04-a7d618c60b43.png)

I would expect to see this file in the above image, so that I can call MoPub.initialize, but it is missing.

https://github.com/googleads/googleads-mobile-unity/blob/master/mediation/MoPub/source/plugin/Assets/GoogleMobileAds/Api/Mediation/MoPub/MoPub.cs

**Comment by rampara** [comment]
@arminho This should no longer be an issue on the latest version of the MoPub mediation support package.
