### ISSUE TITLE
can not found ForUnifiedNativeAd function in AdLoader.Builder

### ISSUE THREAD

**Issue by xbhuang1994** [googleads/googleads-mobile-unity#763]
Hi,
I can not found ForUnifiedNativeAd function in AdLoader.Builder.
How can I use it？
![image](https://user-images.githubusercontent.com/6432896/45606813-d8bf6b00-ba7a-11e8-8b32-01f1024134c9.png)

**Comment by ajon542** [comment]
Under the "Prerequisites" section on this page https://developers.google.com/admob/unity/native-advanced-unified, you can download an "early access build" which contains the method you are looking for.

**Comment by rampara** [comment]
@xbhuang1994 as @ajon542 mentioned you must download the special Native Advanced build of this plugin, linked in the developer docs.
