### ISSUE TITLE
How to decide with Adapter version will work with specific google ads version

### ISSUE THREAD

**Issue by nostel** [googleads/googleads-mobile-unity#770]
Hi,
I'm using google ads version 3.15.1 and FAN adapter 1.2.1 (https://bintray.com/google/mobile-ads-adapters-unity/GoogleMobileAdsFacebookMediation)
I want to use FAN adapter 1.1.3 since it use less Method (avoiding 65k method limit).

Is there anyway to know which adapter version will compatible with google ads version 3.15.1
I don't know where to find it.

**Comment by rampara** [comment]
@nostel Although we always recommend using the latest version across the board, there shouldn't be incompatibility issues with mediation support packages and this plugin.
