### ISSUE TITLE
java.lang.IllegalStateException: Only fullscreen activities can request orientation

### ISSUE THREAD

**Issue by vitorfgd** [googleads/googleads-mobile-unity#772]
Hello, I've recently updated all my projects and assets to the newer versions. These are my current settings and workspace:

OS: MacOS 10.13
Unity: Unity 2018.2.10f1
Admob: Admob v3.15.1

I'm implementing a simple interstitial in my game and as usual, before submitting my APK to production I release in closed and open beta and wait for the prelaunch report by Google on Google Play Console.

This time, I got 3 errors, every single one of them in Android 8. Here's the message I'm getting:

```
FATAL EXCEPTION: main
Process: com.dreamroadproductions.watchyourstep, PID: 9796
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dreamroadproductions.watchyourstep/com.google.android.gms.ads.AdActivity}: java.lang.IllegalStateException: Only fullscreen activities can request orientation
```

I've read some solutions and setting the target API SDK to 27 seems to solve the problem for many people, but I'm already using this setting: Minimum is 21 and Target is 27.

I'm building using gradle:

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }

**Comment by rampara** [comment]
@vitorfgd this issue is caused by the GMA SDK and not this plugin. A fix will be rolling out in the next release of the GMA SDK.
