### ISSUE TITLE
Unable to convert classes into dex format.

### ISSUE THREAD

**Issue by RafaelCmk** [googleads/googleads-mobile-unity#778]
I got "Unable to convert classes into dex format." error when trying to compile my game. I'm using Admob v3.15.1, Ads Mediation v1.2.0, Unity v2018.2.6f1, Unity ads and Unity In-app purchasing.

Deleting "UnityMediationDependencies" from Assets/Editor fix it but it dosen't work then.

**Comment by RafaelCmk** [comment]
I already fixed it, the problem was that I enabled Unity Ads in the service tab and the plugin from Google already imports all the files I needed so disabling it solved.

**Comment by rampara** [comment]
@RafaelCmk glad you were able to resolve your issue.
