### ISSUE TITLE
How to mute sound for Interstitial ads? (Android & IOS)

### ISSUE THREAD

**Issue by mgrogin** [googleads/googleads-mobile-unity#779]
When the sound is turned off in my game's settings if I show an Interstitial ad I want the sound to be muted.
How do I do that?
I see that there are functions called SetApplicationMuted(bool muted) but they don't seem to work for me or Im not using them correctly 
TIA!

**Comment by rampara** [comment]
@mgrogin are you able to capture a Charles log for an ad request where the `SetApplicationMuted` option is not working as expected for you?

**Comment by UragayalaDeepika** [comment]
@mgrogin Are you still seeing this issue? If yes, can you please provide us the charles log to take a look?

**Comment by UragayalaDeepika** [comment]
@mgrogin Closing this issue. Please comment if you are still able to reproduce the issue and provide us the requested details.
