### ISSUE TITLE
Rewarded ad is showing just once.

### ISSUE THREAD

**Issue by vitorfgd** [googleads/googleads-mobile-unity#782]
Hello, I'm using Unity 2012.2.10f and the most recent googleads-mobile-unity.

I've recently integrated the rewarded ads on my app. It's working like magic on the first time. The ad works, all callbacks are fired, I get the reward and everything. After firing the rewarded ad, I also request a new one. 

The action on my app only show up when I get true from rewardBasedVideo.IsLoaded() so I'm sure that the ad is indeed loaded but when I do: rewardBasedVideo.Show(); the ad is never showed and no callback is fired, not even failed to load or start.

I'm using the code suggested here: https://developers.google.com/admob/unity/rewarded-video

Can anyone help me?

**Comment by R---K** [comment]
Propably you destroy object with callbacks script. In this case rewarded handlers points to null.

**Comment by vitorfgd** [comment]
Hey, I believe there was some problems when I imported google play services. That might have erased some important file or something like that. I reimported Admob SDK to the project and created a new script from scratch, it seems to be working now. I'm going to test some more.
