### ISSUE TITLE
libPods-Unity-iPhone.a is red in XCode

### ISSUE THREAD

**Issue by HakimLeee** [googleads/googleads-mobile-unity#786]
libPods-Unity-iPhone.a is red in XCode, so when running times wrong "library not found ford-lpods Unity-iPhone", where can I find libPods-Unity-iPhone.a or not add libPods-Unity-iPhone.a to the Framework when exporting XCode?

**Comment by rampara** [comment]
As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
