### ISSUE TITLE
iOS ignoring methods

### ISSUE THREAD

**Issue by flynetstudios** [googleads/googleads-mobile-unity#787]
Hi, my ads are working just fine in Android. In iOS, im using both methods, for pause the game and low the sound volume. 

```
  public static void HandleInterstitialOpened(object sender, EventArgs args)
    {
	  Time.timeScale = 0;
          AudioListener.volume= 0;
    }

    public static void HandleInterstitialClosed(object sender, EventArgs args)
    {
           Time.timeScale = 1;
           AudioListener.volume= 1;
    }
```

When the interstitial is closed,  the sound don't back to normal volume and the game still paused.

**Comment by rampara** [comment]
@flynetstudios just to clarify, the issue you're experiencing is the `OnAdClosed` ad event is never fired for interstitials on iOS? Are you using the latest version of the plugin? Are you using mediation?

**Comment by rampara** [comment]
Closing due to non-response.
