### ISSUE TITLE
Can't get the ads to work and I tried everything

### ISSUE THREAD

**Issue by nvdg** [googleads/googleads-mobile-unity#788]
At first, I had some trouble getting the ads to work with Google Play Services, when I import the latest ads package with the latest services package. As soon as the game starts it crashes.

After some researching, I decided to give an older version of the ads package a try so I downloaded version 3.11. Now the game runs and the resolver didn't give any errors. In the editor it says it's loading dummy ads but on my phone, it's not doing anything, there also aren't any error outputs.

Then I tried reinstalling all my Android SDK's to the latest versions, and still no luck.

Then I tried a new Unity project with the latest ads package and the following script:

```using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GoogleMobileAds.Api;
using System;

public class Test : MonoBehaviour {

    private BannerView bannerView;

    public void Start()
    {
#if UNITY_ANDROID
            string appId = "ca-app-pub-3940256099942544~3347511713";
#elif UNITY_IPHONE
            string appId = "ca-app-pub-3940256099942544~1458002511";
#else
            string appId = "unexpected_platform";
#endif

        // Initialize the Google Mobile Ads SDK.
        MobileAds.Initialize(appId);

        this.RequestBanner();
    }

    private void RequestBanner()
    {
#if UNITY_ANDROID
            string adUnitId = "ca-app-pub-3940256099942544/6300978111";
#elif UNITY_IPHONE
            string adUnitId = "ca-app-pub-3940256099942544/2934735716";
#else
            string adUnitId = "unexpected_platform";
#endif

        // Create a 320x50 banner at the top of the screen.
        bannerView = new BannerView(adUnitId, AdSize.Banner, AdPosition.Top);

        bannerView.OnAdLoaded += HandleOnAdLoaded;

        // Create an empty ad request.
        AdRequest request = new AdRequest.Builder().Build();

        // Load the banner with the request.
        bannerView.LoadAd(request);
    }

    private void HandleOnAdLoaded(object sender, EventArgs e)
    {
        bannerView.Show();
    }
}
```
It's all resolving/compiling with no errors and still, nothing is showing up, not with the test ID's and not with my own app ID's.

I was hoping to only use the Admob SDK and use its mediation but now it looks like I will have to add all the other SDK's except the Admob one...

**Comment by rampara** [comment]
@nvdg @Mecze Our developer docs have been updated to include instructions on [setting your AppID](https://developers.google.com/admob/unity/start#set_your_admob_app_id), which is a required step when using the latest version of Google Play services.

**Comment by SaturnExoplanetsOnline** [comment]
I've encountered 2 settings in Unity that break the Admob plugin: (Unity 2018.3)

1: Make sure Managed Code Stripping level set to Low. (Inside Player Settings>Other Settings)

2: Make Sure ProGuard is disabled.  (Inside Player Settings>Publishing Settings)

**Comment by rampara** [comment]
Closing this issue due to non-response from the original poster.
