### ISSUE TITLE
 different Reward

### ISSUE THREAD

**Issue by moni69** [googleads/googleads-mobile-unity#790]
I'm using AdMob for Unity for an Android game I'm building I reward different things on each button, The problem is that each button gives its reward and the rest of the reward from the other buttons. For example : There is a button that gives 100 coins and another button gives extra life The problem that the button of life gives 100 coins and life And the button of the coins gives both coins and life.

I have tried different scripts for each button (didn't work).

first script:

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using GoogleMobileAds;
using GoogleMobileAds.Api;

public class AdsManager : MonoBehaviour
{   
    private RewardBasedVideoAd _RewardBasedVideoAd;

	void Start ()
    {
        _RewardBasedVideoAd = RewardBasedVideoAd.Instance;

        // Called when an ad request has successfully loaded.
        _RewardBasedVideoAd.OnAdLoaded += HandleOnAdLoaded;
        // Called when an ad request failed to load.
        _RewardBasedVideoAd.OnAdFailedToLoad += HandleOnAdFailedToLoad;
        // Called when an ad is shown.
        _RewardBasedVideoAd.OnAdOpening += HandleOnAdOpening;
        // Called when the ad starts to play.
        _RewardBasedVideoAd.OnAdStarted += HandleOnAdStarted;
        // Called when the ad is closed.
        _RewardBasedVideoAd.OnAdClosed += HandleOnAdClosed;
        // Called when the user should be rewarded for watching a video.
        _RewardBasedVideoAd.OnAdRewarded += HandleOnAdRewarded;
        // Called when the ad click caused the user to leave the application.
        _RewardBasedVideoAd.OnAdLeavingApplication += HandleOnAdLeavingApplication;
        // Called when the ad click caused the user to leave the application.
        _RewardBasedVideoAd.OnAdCompleted += HandleOnAdCompleted;

        LoadRewardBasedAd();
    }

    public void RequestAds()
    {
        LoadRewardBasedAd();
    }
    public void ShowADS()
    {
        ShowRewardBasedAd();
    }

    private void ShowRewardBasedAd()
    {
        if (_RewardBasedVideoAd.IsLoaded())
        {
            _RewardBasedVideoAd.Show();
        }
        else
        {
            MonoBehaviour.print("Your ad not loaded yet. ");
        }
    }

    private void LoadRewardBasedAd()
    {
        #if UNITY_EDITOR
        string adUnitId = "unused";
        #elif UNITY_ANDROID
        string adUnitId = "ca-app-pub-3940256099942544/5224354917";
        #elif UNITY_IPHONE
            string adUnitId = "ca-app-pub-3940256099942544/1712485313";
        #else
            string adUnitId = "unexpected_platform";
        #endif

        _RewardBasedVideoAd.LoadAd(new AdRequest.Builder().Build(), adUnitId);
    }

    public void HandleOnAdLoaded(object sender, EventArgs args)
    {
       
    }

    public void HandleOnAdFailedToLoad(object sender, AdFailedToLoadEventArgs args)
    {
        RequestAds();
    }

    public void HandleOnAdOpening(object sender, EventArgs args)
    {
    }

    public void HandleOnAdStarted(object sender, EventArgs args)
    {
    }

    public void HandleOnAdClosed(object sender, EventArgs args)
    {
        RequestAds();
    }

    public void HandleOnAdRewarded(object sender, Reward args)
    {
        //Reward the user
        GameManager.Instance._Player.UpdateGems(100);
        UIManager.Instance.OpenShop(GameManager.Instance._Player._diamond);
        RequestAds();
        MonoBehaviour.print(String.Format("You Just got {0} {1}!", args.Amount, args.Type));

    }

    public void HandleOnAdLeavingApplication(object sender, EventArgs args)
    {
        RequestAds();
    }
    public void HandleOnAdCompleted(object sender, EventArgs args)
    {
        RequestAds();
    }

}
`
Second script:

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using GoogleMobileAds;
using GoogleMobileAds.Api;

public class FreeHealthAds : MonoBehaviour
{
    private RewardBasedVideoAd _RewardBasedVideoAdH;
    Player _Player;

    void Start()
    {
        _Player = GameObject.FindGameObjectWithTag("Player").GetComponent<Player>();

        _RewardBasedVideoAdH = RewardBasedVideoAd.Instance;

        // Called when an ad request has successfully loaded.
        _RewardBasedVideoAdH.OnAdLoaded += HandleOnAdLoadedH;
        // Called when an ad request failed to load.
        _RewardBasedVideoAdH.OnAdFailedToLoad += HandleOnAdFailedToLoadH;
        // Called when an ad is shown.
        _RewardBasedVideoAdH.OnAdOpening += HandleOnAdOpeningH;
        // Called when the ad starts to play.
        _RewardBasedVideoAdH.OnAdStarted += HandleOnAdStartedH;
        // Called when the ad is closed.
        _RewardBasedVideoAdH.OnAdClosed += HandleOnAdClosedH;
        // Called when the user should be rewarded for watching a video.
        _RewardBasedVideoAdH.OnAdRewarded += HandleOnAdRewardedH;
        // Called when the ad click caused the user to leave the application.
        _RewardBasedVideoAdH.OnAdLeavingApplication += HandleOnAdLeavingApplicationH;
        // Called when the ad click caused the user to leave the application.
        _RewardBasedVideoAdH.OnAdCompleted += HandleOnAdCompletedH;

        LoadRewardBasedAdH();
    }

    public void RequestAdsH()
    {
        LoadRewardBasedAdH();
    }
    public void ShowADSH()
    {
        ShowRewardBasedAdH();
    }

    private void ShowRewardBasedAdH()
    {
        if (_RewardBasedVideoAdH.IsLoaded())
        {
            _RewardBasedVideoAdH.Show();
        }
        else
        {
            MonoBehaviour.print("Your ad not loaded yet. ");
        }
    }

    private void LoadRewardBasedAdH()
    {
#if UNITY_EDITOR
        string adUnitId = "unused";
#elif UNITY_ANDROID
        string adUnitId = "ca-app-pub-3940256099942544/5224354917";
#elif UNITY_IPHONE
            string adUnitId = "ca-app-pub-3940256099942544/1712485313";
#else
            string adUnitId = "unexpected_platform";
#endif

        _RewardBasedVideoAdH.LoadAd(new AdRequest.Builder().Build(), adUnitId);
    }

    public void HandleOnAdLoadedH(object sender, EventArgs args)
    {

    }

    public void HandleOnAdFailedToLoadH(object sender, AdFailedToLoadEventArgs args)
    {
        RequestAdsH();
    }

    public void HandleOnAdOpeningH(object sender, EventArgs args)
    {
    }

    public void HandleOnAdStartedH(object sender, EventArgs args)
    {
    }

    public void HandleOnAdClosedH(object sender, EventArgs args)
    {
        RequestAdsH();
    }

    public void HandleOnAdRewardedH(object sender, Reward args)
    {
        //Reward the user
        
        _Player._PlayerCurrectHealth = _Player._PlayerMaxHealth;
        _Player._HealthBar.value = _Player.CalculateHealth();
        _Player._PlayerAnim.BackToLife();
        _Player._GameOverPanel.SetActive(false);
        RequestAdsH();
        MonoBehaviour.print(String.Format("You Just got {0} {1}!", args.Amount, args.Type));

    }

    public void HandleOnAdLeavingApplicationH(object sender, EventArgs args)
    {
        RequestAdsH();
    }
    public void HandleOnAdCompletedH(object sender, EventArgs args)
    {
        RequestAdsH();
    }

}
`

**Comment by rampara** [comment]
@moni69 Rewarded ads in this plugin follow a singleton design pattern. You can only load and display a single ad at a time. When you register ad event handlers from multiple scripts, you're pointing to the same underlying ad object.
