### ISSUE TITLE
Unstable app when Limit Ad Tracking is turned on in iOS

### ISSUE THREAD

**Issue by paulocode** [googleads/googleads-mobile-unity#793]
I'm getting crashes when Limit Ad Tracking is turned on. Sometimes, I get a blank ad.

Here is the stack trace of the crashing thread:
`Thread 43 name:  Dispatch queue: com.apple.CFNetwork.LoaderQ
Thread 43 Crashed:
0   libdispatch.dylib             	0x00000001b339d5c8 dispatch_source_set_timer$VARIANT$armv81 + 40
1   CFNetwork                     	0x00000001b40c18a8 URLConnectionLoader::_private_ScheduleOriginLoad+ 1681576 (NSURLRequest const*, _CFCachedURLResponse const*) + 176
2   CFNetwork                     	0x00000001b40c18a8 URLConnectionLoader::_private_ScheduleOriginLoad+ 1681576 (NSURLRequest const*, _CFCachedURLResponse const*) + 176
3   CFNetwork                     	0x00000001b40c1174 URLConnectionLoader::loadWithWhatToDo+ 1679732 (NSURLRequest const*, _CFCachedURLResponse const*, long, URLConnectionLoader::WhatToDo) + 924
4   CFNetwork                     	0x00000001b40c169c invocation function for block in URLConnectionLoader::continueWithCacheLookupResult+ 1681052 (NSURLRequest const*, _CFCachedURLResponse const*, CFURLRequestCachePolicy) + 72
5   CFNetwork                     	0x00000001b40bf4bc invocation function for block in URLConnectionLoader::withExistingProtocolAsync(void + 1672380 (URLProtocol*) block_pointer) const + 32
6   CFNetwork                     	0x00000001b419444c invocation function for block in QCoreSchedulingSet::performAsync(void + 2544716 () block_pointer) const + 52
7   libdispatch.dylib             	0x00000001b33b76c8 _dispatch_call_block_and_release + 24
8   libdispatch.dylib             	0x00000001b33b8484 _dispatch_client_callout + 16
9   libdispatch.dylib             	0x00000001b3392fb0 _dispatch_lane_serial_drain$VARIANT$armv81 + 548
10  libdispatch.dylib             	0x00000001b3393b2c _dispatch_lane_invoke$VARIANT$armv81 + 468
11  libdispatch.dylib             	0x00000001b3394d70 _dispatch_workloop_invoke$VARIANT$armv81 + 1892
12  libdispatch.dylib             	0x00000001b339bf14 _dispatch_workloop_worker_thread + 584
13  libsystem_pthread.dylib       	0x00000001b359a0f0 _pthread_wqthread + 312
14  libsystem_pthread.dylib       	0x00000001b359cd00 start_wqthread + 4
`

I hope that helps.

**Comment by rampara** [comment]
@paulocode as this crash is not caused by this plugin but by the GMA iOS SDK, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.

**Comment by 9639146531** [comment]
Vishal Gupta
