### ISSUE TITLE
Error while building for IOS

### ISSUE THREAD

**Issue by OniTheC4t** [googleads/googleads-mobile-unity#797]
I get this error:

`GADUMUnityAdsInterface.m:19:8: initializing 'BOOL' (aka 'signed char') with an expression of incompatible type 'void'`

Referred to this:

<img width="579" alt="schermata 2018-11-01 alle 15 08 52" src="https://user-images.githubusercontent.com/7911705/47856709-1dfbea00-dde8-11e8-95ac-a836da1076d4.png">

**Comment by joshuajplagonera** [comment]
I'm not able to replicate this issue on my end. 

Can you show how you are using the UnityAds.SetGDPRConsentMetaData() method? It's possible that you're providing a non-boolean value which causes this error.

**Comment by lazarevich-carx** [comment]
I get this error too. I've updated admob with GoogleMobileAdsUnityAdsMediation 2.0.0 to show unity ads.

**Comment by guanshichao** [comment]
<img width="747" alt="image" src="https://user-images.githubusercontent.com/44183966/50033476-a6022000-0033-11e9-8d5b-14ead83121cc.png">
@joshuajplagonera

**Comment by joshuajplagonera** [comment]
Updated the Unity Ads Unity Mediation plugin which should fix this issue: 0a2af6a9bac5cf0830a13f140c3bf3b9f893e363
