### ISSUE TITLE
AdMob & Firebase Build Error

### ISSUE THREAD

**Issue by Drostina** [googleads/googleads-mobile-unity#800]
Hi, I can't seem to get Firebase and GMU to work together, I have tried so many ways of importing them, but I can't seem to build the project at all due to the following errors:

![screenshot1](https://user-images.githubusercontent.com/28703972/47959056-3f202e80-dfd2-11e8-93a7-d6965545abe1.PNG)

![screenshot2](https://user-images.githubusercontent.com/28703972/47959057-421b1f00-dfd2-11e8-9c2f-04a831a58d4e.PNG)

CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Java\jdk1.8.0_191\bin\java.exe -classpath "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.2.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx2048m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/measurement/zzdz;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
]
stdout[
:preBuild UP-TO-DATE
:Firebase:preBuild UP-TO-DATE
:Firebase:preReleaseBuild UP-TO-DATE
:Firebase:checkReleaseManifest
:Firebase:processReleaseManifest
:GoogleMobileAdsPlugin:preBuild UP-TO-DATE
:GoogleMobileAdsPlugin:preReleaseBuild UP-TO-DATE
:GoogleMobileAdsPlugin:checkReleaseManifest
:GoogleMobileAdsPlugin:processReleaseManifest
:preReleaseBuild UP-TO-DATE
:Firebase:compileReleaseAidl
:GoogleMobileAdsPlugin:compileReleaseAidl
:compileReleaseAidl UP-TO-DATE
:Firebase:packageReleaseRenderscript NO-SOURCE
:GoogleMobileAdsPlugin:packageReleaseRenderscript NO-SOURCE
:compileReleaseRenderscript UP-TO-DATE
:checkReleaseManifest UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:prepareLintJar UP-TO-DATE
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:Firebase:compileReleaseRenderscript
:Firebase:generateReleaseResValues
:Firebase:generateReleaseResources
:Firebase:packageReleaseResources
:GoogleMobileAdsPlugin:compileReleaseRenderscript
:GoogleMobileAdsPlugin:generateReleaseResValues
:GoogleMobileAdsPlugin:generateReleaseResources
:GoogleMobileAdsPlugin:packageReleaseResources
:mergeReleaseResources UP-TO-DATE
:createReleaseCompatibleScreenManifests UP-TO-DATE
:processReleaseManifest
:splitsDiscoveryTaskRelease UP-TO-DATE
:Firebase:platformAttrExtractor
:GoogleMobileAdsPlugin:platformAttrExtractor
:Firebase:generateReleaseBuildConfig
:Firebase:prepareLintJar UP-TO-DATE
:Firebase:javaPreCompileRelease
:Firebase:processReleaseJavaRes NO-SOURCE
:GoogleMobileAdsPlugin:generateReleaseBuildConfig
:GoogleMobileAdsPlugin:prepareLintJar UP-TO-DATE
:GoogleMobileAdsPlugin:javaPreCompileRelease
:GoogleMobileAdsPlugin:processReleaseJavaRes NO-SOURCE
:compileReleaseNdk NO-SOURCE
:mergeReleaseShaders UP-TO-DATE
:compileReleaseShaders UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:Firebase:mergeReleaseShaders
:Firebase:compileReleaseShaders
:Firebase:generateReleaseAssets
:Firebase:mergeReleaseAssets
:GoogleMobileAdsPlugin:mergeReleaseShaders
:GoogleMobileAdsPlugin:compileReleaseShaders
:GoogleMobileAdsPlugin:generateReleaseAssets
:GoogleMobileAdsPlugin:mergeReleaseAssets
:mergeReleaseAssets
:mergeReleaseJniLibFolders UP-TO-DATE
:Firebase:compileReleaseNdk NO-SOURCE
:Firebase:mergeReleaseJniLibFolders
:Firebase:transformNativeLibsWithMergeJniLibsForRelease
:Firebase:transformNativeLibsWithIntermediateJniLibsForRelease
:GoogleMobileAdsPlugin:compileReleaseNdk NO-SOURCE
:GoogleMobileAdsPlugin:mergeReleaseJniLibFolders
:GoogleMobileAdsPlugin:transformNativeLibsWithMergeJniLibsForRelease
:GoogleMobileAdsPlugin:transformNativeLibsWithIntermediateJniLibsForRelease
:processReleaseJavaRes NO-SOURCE
:validateSigningRelease
:Firebase:mergeReleaseConsumerProguardFiles UP-TO-DATE
:Firebase:transformNativeLibsWithSyncJniLibsForRelease
:Firebase:mergeReleaseResources
:Firebase:verifyReleaseResources
:GoogleMobileAdsPlugin:mergeReleaseConsumerProguardFiles UP-TO-DATE
:GoogleMobileAdsPlugin:transformNativeLibsWithSyncJniLibsForRelease
:GoogleMobileAdsPlugin:mergeReleaseResources
:GoogleMobileAdsPlugin:verifyReleaseResources
:GoogleMobileAdsPlugin:processReleaseResources
:GoogleMobileAdsPlugin:generateReleaseSources
:GoogleMobileAdsPlugin:compileReleaseJavaWithJavac
:GoogleMobileAdsPlugin:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:GoogleMobileAdsPlugin:extractReleaseAnnotations
:GoogleMobileAdsPlugin:transformResourcesWithMergeJavaResForRelease
:GoogleMobileAdsPlugin:transformClassesAndResourcesWithSyncLibJarsForRelease
:GoogleMobileAdsPlugin:bundleRelease
:GoogleMobileAdsPlugin:compileReleaseSources
:GoogleMobileAdsPlugin:assembleRelease
:Firebase:processReleaseResources
:processReleaseResources
:generateReleaseSources
:Firebase:generateReleaseSources
:Firebase:compileReleaseJavaWithJavac
:Firebase:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:javaPreCompileRelease UP-TO-DATE
:compileReleaseJavaWithJavac UP-TO-DATE
:compileReleaseSources UP-TO-DATE
:lintVitalRelease
:transformClassesWithPreDexForRelease
:transformDexWithDexForRelease FAILED
72 actionable tasks: 53 executed, 19 up-to-date
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <fdd3823527dc4dde8316302bb5a76d3b>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <fdd3823527dc4dde8316302bb5a76d3b>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <fdd3823527dc4dde8316302bb5a76d3b>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <fdd3823527dc4dde8316302bb5a76d3b>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <fdd3823527dc4dde8316302bb5a76d3b>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <fdd3823527dc4dde8316302bb5a76d3b>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <fdd3823527dc4dde8316302bb5a76d3b>:0)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

**Comment by carsonvo** [comment]
Hello, You can try to use the firebase version 5.3.1. It will be fixed.

**Comment by Steljoy** [comment]
> Hello, You can try to use the firebase version 5.3.1. It will be fixed.

Thanks for the reply! I can try that for sure but is there any updates that are coming out soon to allow me to use the current firebase version whilst I use this plugin?

**Comment by carsonvo** [comment]
> > Hello, You can try to use the firebase version 5.3.1. It will be fixed.
> 
> Thanks for the reply! I can try that for sure but is there any updates that are coming out soon to allow me to use the current firebase version whilst I use this plugin?

I faced to this problems when I used the newest firebase version (5.4.0) and Admob 3.15.1. After I downgrade firebase to 5.3.1, everything was fine.

**Comment by dralv3s** [comment]
Good day everyone, I'm having the same issues over here with Firebase Auth + Db + Admob, after two days with no succes, I'll try the 3.5.1 but I can't find a download anywhere on the web, does anyone here has any idea where to get old sdk versions?

Thanks.

**Comment by Steljoy** [comment]
> Good day everyone, I'm having the same issues over here with Firebase Auth + Db + Admob, after two days with no succes, I'll try the 3.5.1 but I can't find a download anywhere on the web, does anyone here has any idea where to get old sdk versions?
> 
> Thanks.

Hey, I managed to find it the other day but I can't seem to find it now, as stupid as that sounds haha!
We really need an update on this Plugin because my whole update runs on their rewarded video and I can't get the update out.

**Comment by carsonvo** [comment]
> Good day everyone, I'm having the same issues over here with Firebase Auth + Db + Admob, after two days with no succes, I'll try the 3.5.1 but I can't find a download anywhere on the web, does anyone here has any idea where to get old sdk versions?
> 
> Thanks.

Hello @dralv3s ,

Please https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_5.3.1.zip :)

**Comment by dralv3s** [comment]
> > Good day everyone, I'm having the same issues over here with Firebase Auth + Db + Admob, after two days with no succes, I'll try the 3.5.1 but I can't find a download anywhere on the web, does anyone here has any idea where to get old sdk versions?
> > Thanks.
> 
> Hello @dralv3s ,
> 
> Please https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_5.3.1.zip :)

Thanks mate.

**Comment by rampara** [comment]
@dralv3s @Drostina @carsonvo can you also try updating the [dependencies file](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml) to use the latest version of the Google Mobile Ads SDK.

**Comment by Drostina** [comment]
> 
> 
> @dralv3s @Drostina @carsonvo can you also try updating the [dependencies file](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml) to use the latest version of the Google Mobile Ads SDK.

I will look into this tonight, thanks for getting back

**Comment by Drostina** [comment]
> 
> 
> @dralv3s @Drostina @carsonvo can you also try updating the [dependencies file](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml) to use the latest version of the Google Mobile Ads SDK.

It seems to work when I downloaded the files again, did you update the dependencies here?

**Comment by dralv3s** [comment]
> @dralv3s @Drostina @carsonvo can you also try updating the [dependencies file](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml) to use the latest version of the Google Mobile Ads SDK.

Will try, but I can't do it until Sunday, I'm away from my machine for the week, will post a reply on Monday.

**Comment by dralv3s** [comment]
> > @dralv3s @Drostina @carsonvo can you also try updating the [dependencies file](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml) to use the latest version of the Google Mobile Ads SDK.
> 
> I will look into this tonight, thanks for getting back

Turns out my GoogleMobileAdsDependencies.xml is already like yours, it's working fine now, with test ads.

**Comment by rampara** [comment]
Closing as issue seems to have been resolved.
