### ISSUE TITLE
Test Mode Ads works, but not work Real Test Mode Ads or Real Ads

### ISSUE THREAD

**Issue by vpelegrin** [googleads/googleads-mobile-unity#801]
Hi, I have used "Hello Word" sample with **Test Mode Ads** and it works!

However, if I use **Real Ads in Test Mode**    or    **Real Ads in Real Mode**  it doesn't work.
I change to ID Real logically.

When I click in my phone , request interstitial button appear this:
**"HandleRewardBasedVideoFailedToLoad event received with message: Internal error"**

**MY CODE**
private AdRequest CreateAdRequest()
    {
        //TEST REAL AD ON TEST MODE
        
//AdRequest request=newAdRequest.Builder().AddTestDevice("61297578A6A90F00AF351C87A272C57D").Build();
        

     //REAL AD
        AdRequest request = new AdRequest.Builder().Build();
            return request;
    }

I saw that other people have the same problem in forums but I didn't search solution.
I have done all what appears in guides:

https://developers.google.com/admob/unity/start
https://developers.google.com/admob/unity/test-ads

Regards, Victor

**Comment by rampara** [comment]
@vpelegrin if you're able to load test ads then there isn't an issue with your integration or this plugin. I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
