### ISSUE TITLE
App crash on launch - Unable to use Google Ads with Google Sign unity packages

### ISSUE THREAD

**Issue by FaiyazMdAbdul** [googleads/googleads-mobile-unity#802]
I am able to both plugins individually but not together . 
I found this warning while resolving dependencies .

> Some conflicting dependencies were found.
The following dependency versions were modified:
com.google.android.gms:play-services-ads:15.0.1 --> com.google.android.gms:play-services-ads:+
com.google.android.gms:play-services-auth:16+ --> com.google.android.gms:play-services-auth:+

**Comment by rampara** [comment]
@FaiyazMdAbdul does updating the [dependencies file](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml) to use the latest version of the Google Mobile Ads SDK resolve your issue?

**Comment by UragayalaDeepika** [comment]
@FaiyazMdAbdul Feel free to comment and let us know if you are still having this issue with the latest verison of the SDK.
