### ISSUE TITLE
CommandInvokationFailure: Unable to convert classes into dex format - Unity

### ISSUE THREAD

**Issue by siddharth3322** [googleads/googleads-mobile-unity#803]
I have imported Google Admob and Google Ads Mediation Unity plugins within the game project and I started getting this kind of error:

![unity_android_build_error](https://user-images.githubusercontent.com/3082151/48141879-bf47dc00-e2d1-11e8-818b-bf131842a4a1.png)
Here is my Plugins/Android folder content: 
![android_plugins_folder](https://user-images.githubusercontent.com/3082151/48141907-cc64cb00-e2d1-11e8-8750-ed068ee2dc59.png)
Before I have just imported Google Admob plugin and its working properly but after importing Google Ads Mediation Unity plugin, it's started giving me the above problem.

**Comment by choheh** [comment]
remove old version of admob resources.

**Comment by siddharth3322** [comment]
> remove old version of admob resources.
> (maybe that is aar files)

how can I identify old version files? what files to remove? 
Can you please help me into this?

**Comment by rampara** [comment]
@siddharth3322 it looks like you're adding multiple versions of classes from the Unity Ads SDK. You may want to try removing the unity ads AAR you have in your 'Plugins/Assets/Android' directory. Closing this issue as it's not related to this plugin.
