### ISSUE TITLE
Banner bottom position wrong 3.15.1

### ISSUE THREAD

**Issue by querywilly** [googleads/googleads-mobile-unity#806]
When I click on the text box. 
bottom position changing.

Tested device:
Samsung note 10.1 
Android 4.1.2
Unity 5.6.5p4

Please look up to video.
https://www.youtube.com/watch?v=z9r64f5_66s

Thanks

**Comment by rampara** [comment]
This looks like a plugin banner positioning bug.

**Comment by stowy** [comment]
Please try [version 3.17.0](https://github.com/googleads/googleads-mobile-unity/releases/tag/3.17.0).

**Comment by UragayalaDeepika** [comment]
@querywilly @pz789as Can you please try version 3.17.0 and let us know if you are still seeing this issue?

**Comment by querywilly** [comment]
> @querywilly @pz789as Can you please try version 3.17.0 and let us know if you are still seeing this issue?

it is ok. 
not problem 3.17
