### ISSUE TITLE
Please help, admob mediation with Ironsource  adapter Resolution failed

### ISSUE THREAD

**Issue by takaaptech** [googleads/googleads-mobile-unity#807]
Hi!
I just download Google Mobile Ads Unity Plugin v3.15.1 and Iron Source mediation GoogleMobileAdsIronSourceMediation-1.0.4
Press Force Resolver and the resolve conflict with info:
```
Some conflicting dependencies were found.
The following dependency versions were modified:
com.ironsource.sdk:mediationsdk:6.7.11 --> com.ironsource.sdk:mediationsdk:+

UnityEngine.Debug:LogWarning(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.<GradleResolution>c__AnonStorey17:<>m__27(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey19:<>m__32()
Google.RunOnMainThread:ExecuteNext()
Google.RunOnMainThread:<ExecuteAll>m__6()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAll()
Google.RunOnMainThread:Run(Action, Boolean)
GooglePlayServices.<GradleResolution>c__AnonStorey17:<>m__28(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey17:<>m__29(Result)
GooglePlayServices.ProgressReporter:SignalComplete()
GooglePlayServices.ProgressReporter:CommandLineToolCompletion(Result)
GooglePlayServices.<RunAsync>c__AnonStorey2:<>m__3()
Google.RunOnMainThread:ExecuteNext()
Google.RunOnMainThread:<ExecuteAll>m__6()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAll()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

```

```
Resolution failed

Failed to fetch the following dependencies:
com.ironsource.sdk:sdk5:+


UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.ResolverVer1_1:LogMissingDependenciesError(List`1)
GooglePlayServices.<DoResolutionUnsafe>c__AnonStorey1C:<>m__2E(List`1)
GooglePlayServices.<GradleResolution>c__AnonStorey18:<>m__31()
GooglePlayServices.<ProcessAars>c__AnonStorey1F:<>m__30()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:<ExecuteAll>m__6()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAll()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

```

**Comment by takaaptech** [comment]
[Project.zip](https://github.com/googleads/googleads-mobile-unity/files/2597892/Project.zip)
Project for testing is here. Thank you

**Comment by asarazan** [comment]
Also having this issue. Please fix.

**Comment by ManiDev11** [comment]
What about the issue is it resolve or not? Please Help

**Comment by JHermansson** [comment]
We got the same issue!

**Comment by SodaSaft** [comment]
Same here, help us please!

**Comment by sp-jordi-vilalta** [comment]
I think it could be caused by an update on unity-jar-resolver, which introduced a regression: https://github.com/googlesamples/unity-jar-resolver/issues/174
I tried downgrading unity-jar-resolver to version 1.2.88 and it fixed a similar issue.

**Comment by rampara** [comment]
Changed label to support issue as JAR resolver is responsible for the issue.

**Comment by apautrot** [comment]
I can't downgrade my unity-jar-resolver to a version below 1.2.95 as I'm using Firebase Analytics which forbid it (I tried unity-jar-resolver version 1.2.89 but it issued error messages due to methods not found by Firebase).
Is there a way to bypass something on some level ? A workaround someone ?

**Comment by joshuajplagonera** [comment]
Hi All,
I'm not able to replicate this issue on my end anymore. Can you verify on your end?

**Comment by apautrot** [comment]
Hi
Me neither. I have tested it on the project that previously had this issue ( Unity 2018.2.20f1, GoogleMobileAdsIronSourceMediation-1.0.4, Play Service Resolver 1.2.95 ).

IronSource team must have fixed the issue on their side, in the dependency declaration files.

Notice that the log now display
> com.ironsource.sdk:mediationsdk:6.7.11 --> com.ironsource.sdk:mediationsdk:6.+
while it previously displayed
> com.ironsource.sdk:mediationsdk:6.7.11 --> com.ironsource.sdk:mediationsdk:+

Regards.
