### ISSUE TITLE
Why not call GoogleMobileAdsClientFactory directly

### ISSUE THREAD

**Issue by zmer007** [googleads/googleads-mobile-unity#809]
Hello sir, I viewed the whole sample code, it is so clear and beauty. But I found two points that I cannot understand. Could you teach me why :)
1. Uses a reflector to instance `GoogleMobileAdsClientFactory`. It can be used directly, isn't it?
2. Each callback in the Android plugin will creates a new Thread. Can replace it with `Executors.newSingleThreadExecutor()`?

**Comment by rampara** [comment]
@zmer007 this is due this code being reused in the [Native Advanced version]() of this plugin, which calls into code from a separate compiled assembly.
