### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by wkq87** [googleads/googleads-mobile-unity#812]
Hi:
i export this package to unity,then export to xcode,and here is the compile error

`ndefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GADRewardedAd", referenced from:
      objc-class-ref in unity-plugin-library.a(GADURewardedAd_c1dfc5b3cd508e3a135d57a18ca0e00f.o)
ld: symbol(s) not found for architecture arm64
`
But i cannot find any useful information in google,pls help

**Comment by wkq87** [comment]
i already import lastly GoogleAdsApi Unitypackage，what should i do to using Native Advanced version of this plugin?

**Comment by rampara** [comment]
The Native Advanced version of this plugin is available on our [dev docs](https://developers.google.com/admob/unity/native-advanced-unified). If you are migrating from the public version of the Google Mobile Ads plugin on GitHub, first remove all existing Google Mobile Ads files.
