### ISSUE TITLE
Resolve fail resolution

### ISSUE THREAD

**Issue by mohammadmahdi123** [googleads/googleads-mobile-unity#814]
When I use force resolve, I get failed resolutions.
I have to use old google play services 0.9.39. It is OK for me and resolved successfully with Resolve client jars When I add google ad mob to my project, I do not import new resolver (because of problems I referred).
I build and when the app is started, the app is crashed "class not found exception"
Which version of ad mob is suitable for google play services 0.9.39?

**Comment by mohammadmahdi123** [comment]
Can I add the following expressions to GPGS dependencies?

I can see aar files in Plugins/android after clicking on resolve client jars:
play-services-ads-11.0.4
play-services-ads-lite-11.0.4

`   Google.VersionHandler.InvokeInstanceMethod(
                svcSupport, "DependOn",
                new object[] { "com.google.android.gms", "play-services-ads",
                    PluginVersion.PlayServicesVersionConstraint },
                namedArgs: new Dictionary<string, object>() {
                    {"packageIds", new string[] { "extra-google-m2repository" } }
                });
`

**Comment by mohammadmahdi123** [comment]
I added it and now it is OK. google ads and ads lite 11.0.4 aar were added.
I do not know why I can not resolve with new resolve version.
I do not have google ads 15.1.0  in my android sdk and can not download it.

**Comment by kingkhan90** [comment]
hi i had the same issue now i have fixed:
Here Solution on Youtube: https://www.youtube.com/watch?v=jJI_ztP-X5U
I hope that help.
