### ISSUE TITLE
Latest Admob (3.15.1 ) couses crashes on Launch now & Resolver Fail

### ISSUE THREAD

**Issue by alpsaltera** [googleads/googleads-mobile-unity#819]
1. Import Latest Google Play Service
2. Importing Latest Google ADS 

then Resolver error.

and application can not run. when starting app, app is down with crahsed message.

I need help.

the similar problem  was reported but not find solution....

how can i solve this problem.

<RESOLVER FAIL MESSAGE>
Some conflicting dependencies were found.
The following dependency versions were modified:
com.google.android.gms:play-services-auth-api-phone:16.0.0 --> com.google.android.gms:play-services-auth-api-phone:16.0.1
com.google.android.gms:play-services-gass:15.0.1 --> com.google.android.gms:play-services-gass:16.0.1
com.google.android.gms:play-services-games:16.0.0 --> com.google.android.gms:play-services-games:16.0.1
com.google.android.gms:play-services-ads-identifier:15.0.1 --> com.google.android.gms:play-services-ads-identifier:16.0.1
com.google.android.gms:play-services-auth-base:16.0.0 --> com.google.android.gms:play-services-auth-base:16.0.1
com.google.android.gms:play-services-ads:15.0.1 --> com.google.android.gms:play-services-ads:16.0.1
com.google.android.gms:play-services-ads-lite:15.0.1 --> com.google.android.gms:play-services-ads-lite:16.0.1
com.google.android.gms:play-services-nearby:16.0.0 --> com.google.android.gms:play-services-nearby:16.0.1
com.google.android.gms:play-services-ads-base:15.0.1 --> com.google.android.gms:play-services-ads-base:16.0.1
com.google.android.gms:play-services-drive:16.0.0 --> com.google.android.gms:play-services-drive:16.0.1

UnityEngine.Debug:LogWarning(Object)
Google.Logger:Log(String, LogLevel) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:87)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:691)
GooglePlayServices.<GradleResolution>c__AnonStorey17:<>m__28(Result) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:636)
GooglePlayServices.<GradleResolution>c__AnonStorey19:<>m__33() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:708)
Google.RunOnMainThread:ExecuteNext() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:363)
Google.RunOnMainThread:<ExecuteAll>m__6() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:394)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:392)
Google.RunOnMainThread:Run(Action, Boolean) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:349)
GooglePlayServices.<GradleResolution>c__AnonStorey17:<>m__29(Result) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:709)
GooglePlayServices.<GradleResolution>c__AnonStorey17:<>m__2A(Result) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:760)
GooglePlayServices.ProgressReporter:SignalComplete() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/CommandLineDialog.cs:116)
GooglePlayServices.ProgressReporter:CommandLineToolCompletion(Result) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/CommandLineDialog.cs:107)
GooglePlayServices.<RunAsync>c__AnonStorey2:<>m__3() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/CommandLine.cs:136)
Google.RunOnMainThread:ExecuteNext() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:363)
Google.RunOnMainThread:<ExecuteAll>m__6() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:394)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:392)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by leoHN** [comment]
I'm getting the same issue.

**Comment by leoHN** [comment]
I checked and see "method" is null in class "RewardBasedVideoAd"

> private RewardBasedVideoAd()
        {
            Type googleMobileAdsClientFactory = Type.GetType(
                "GoogleMobileAds.GoogleMobileAdsClientFactory,Assembly-CSharp");
            MethodInfo method = googleMobileAdsClientFactory.GetMethod(
                "BuildRewardBasedVideoAdClient",
                BindingFlags.Static | BindingFlags.Public);
            this.client = (IRewardBasedVideoAdClient)method.Invoke(null, null);
            client.CreateRewardBasedVideoAd();

**Comment by kingkhan90** [comment]
hi i had the same issue now i have fixed:
Here on Youtube: https://www.youtube.com/watch?v=jJI_ztP-X5U
I hope that help.

**Comment by alpsaltera** [comment]
# @[ ] 1. Resolver Error has solved.
[ ] 2. 
[ ] 3. But starting crash is continuing.

**Comment by kingkhan90** [comment]
Hi I would require you the lastest version of google ads unity plugin to download not SDK only plugin.
https://developers.google.com/admob/unity/start

Or try with unity 2018.3 
Because unity old version  missing some files. So try with new version.
Hope it help

**Comment by sptkjs** [comment]
Hi. I have same issue.
I Imported play-game-plugin-for-unity-Version 0.9.57. And I Imported admob-plugin-Version 3.15.1. Then I resolved Android dependency by play-service-resolver-Version 1.2.95. Resolving is Successing. But application is shutdown as soon as application is driven.

**Comment by alpsaltera** [comment]
thanks your reply.
 
1. Resolver Fail : When i am using Unity3D 2018.2.20f, it was solved.
 
2. crashes on Launches : it was revealed menifest's problem.
 
manifest
 
3. Result.
 
   - all problem was gone.
 
Thanks you're appreciating.
 
 
-----Original Message-----

**Comment by alpsaltera** [comment]
1. Resolver Fail : Use Unity3d 2018.2.20f
2. Crash : menifest's problem.

it's my solution.
