### ISSUE TITLE
OnAdLeavingApplication not firing for Rewarded Ads on iOS

### ISSUE THREAD

**Issue by pz789as** [googleads/googleads-mobile-unity#820]
Hi,

Unity version : 2018.1.4f1
GoogleMobileAds-3.15.1.unitypackage

OnAdLeavingApplication in Unity doesn't seem to be working for rewardedAds on iOS.

I'm adding all callbacks from Unity, and all callbacks work, except OnAdLeavingApplication.

It might be linked to the fact that users are no longer redirected to the store, but instead a popup of the store is shown within the app?

Thanks

**Comment by rampara** [comment]
Can you provide the ad unit for which you're experiencing this issue?
