### ISSUE TITLE
Ads are not showing after publishing the game

### ISSUE THREAD

**Issue by muhammadfar** [googleads/googleads-mobile-unity#822]
I am using the admob lateset sdk with play services plugin 9.4, everything was working fine before publising the game but when i publish the game ads are not showing in the game and play services are not working too. Is that the plugin issue or there is some other mistake i am doing.
Please guide

**Comment by SaturnExoplanetsOnline** [comment]
Make sure ProGuard is disabled and managed code stripping is set to low.

Those broke the plugin for me.

**Comment by rampara** [comment]
@muhammadfar publishing your app should not have any effect on ad serving. Are you unable to load any ads with the same ad unit ids you used in your published app? If so, what error code are you receiving?

**Comment by UragayalaDeepika** [comment]
@muhammadfar Please comment on the thread if you need support on this issue. We will reopen this. Marking this as closed for now.
