### ISSUE TITLE
No .xcworkspace generated

### ISSUE THREAD

**Issue by dylsg** [googleads/googleads-mobile-unity#825]
In the Get Started guide, for iOS, it says

> When using Unity 5.6 and above, an xcworkspace is generated that includes the required dependency libraries. Use the generated xcworkspace instead of the standard Xcode project.
> When using older versions of Unity, the dependencies are included inside the standard Xcode project.

I'm using Unity 2018.3, but no xcworkspace is generated. 

After digging around for a bit, I discovered that with the newer versions of the Unity Jar Resolver, it seems that the default "resolution strategy" is to not generate the xcworkspace. 

> The CocoaPods are either:
> 
> Downloaded and injected into the Xcode project file directly, rather than creating a separate xcworkspace. We call this Xcode project integration.
> If the Unity version supports opening a xcworkspace file, the pod tool is used as intended to generate a xcworkspace which references the CocoaPods. We call this Xcode workspace integration.
> The resolution strategy can be changed via the Assets > Play Services Resolver > iOS Resolver > Settings menu.

Hopefully this will help someone out, and that the docs can be updated to avoid confusion.

**Comment by Munyola** [comment]
Nice work big up I would like to compine contents with your ability to discover future locks.Yet am not qualified but practical I do software development.I will join you soon if the hackersbay.io will give me opportunity of responding thanks ...

**Comment by rampara** [comment]
@dylsg Under the iOS resolver settings (reached by selecting Assets -> Play Services Resolver -> iOS Resolver -> Settings), do you have `Generate an xcworkspace` selected in the `Cocoapods Integration` drop-down?

**Comment by UragayalaDeepika** [comment]
@dylsg Feel free to comment here if you still have an issue. Closing this thread for now.

**Comment by ashiokaii** [comment]
hi, I have done those settings but my unity 2019.1.6.f1 still does not produce the Xcode workspace in the ios build

**Comment by Mansur959595** [comment]
> hi, I have done those settings but my unity 2019.1.6.f1 still does not produce the Xcode workspace in the ios build

hey, I don't know if you use "Facebook SDK for Unity" https://developers.facebook.com/docs/unity/ 
After i installed the SDK and build my project it produced workspace

**Comment by stowy** [comment]
You only need to have the plugin imported which should include [External Dependency Manager](https://github.com/googlesamples/unity-jar-resolver). Follow the instructions on their ReadMe to ensure that dependencies are resolved and cocoapods runs correctly.

**Comment by julianstopher** [comment]
> > hi, I have done those settings but my unity 2019.1.6.f1 still does not produce the Xcode workspace in the ios build
> 
> hey, I don't know if you use "Facebook SDK for Unity" https://developers.facebook.com/docs/unity/
> After i installed the SDK and build my project it produced workspace

This worked for me!

1. I installed this: https://github.com/googlesamples/unity-jar-resolver/blob/master/external-dependency-manager-latest.unitypackage
2. I installed Facebook SDK for unity 

Workspace is now generated.

**Comment by a405457747** [comment]
> > > 嗨，我已经完成了这些设置，但是我的 unity 2019.1.6.f1 仍然没有在 ios 构建中生成 Xcode 工作区
> > 
> > 
> > 嘿，我不知道你是否使用“Facebook SDK for Unity” https://developers.facebook.com/docs/unity/
> > 在我安装了 SDK 并构建了我的项目之后，它产生了工作区
> 
> 这对我有用！
> 
> 1. 我安装了这个：[https ://github.com/googlesamples/unity-jar-resolver/blob/master/external-dependency-manager-latest.unitypackage](https://github.com/googlesamples/unity-jar-resolver/blob/master/external-dependency-manager-latest.unitypackage)
> 2. 我为统一安装了 Facebook SDK
> 
> 工作区现已生成。
> 
> 不幸的是，现在我在 Xcode 中收到很多与 Google 纸板相关的未定义参考符号错误。

How can I solve this problem
