### ISSUE TITLE
Android build error after adding GoogleMobileAdsUnityAdsMediation.unitypackage

### ISSUE THREAD

**Issue by nitzanwilnai** [googleads/googleads-mobile-unity#829]
I get the following build error after adding the unity ads mediation package. 

Everything was running great before.

Ads are turned on and Enable Built-in Extension is turned off (although I get the same error regardless).

I have tried 2.0.1, 2.0.0 and 1.2.0 to no avail.

I also added Admob and the Mediation package to a brand new project and got the same error.

Can anyone offer any help?

CommandInvokationFailure: Gradle build failed. 
/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/OpenJDK/MacOS/bin/java -classpath "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/gradle/lib/gradle-launcher-4.6.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[
D8: Program type already present: com.unity3d.ads.UnityAds$PlacementState

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForRelease'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/0.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/1.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/2.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/3.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/8.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/9.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/10.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/11.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/12.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/13.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/14.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/15.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/16.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/17.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/18.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/19.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/20.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/21.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/22.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/23.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/24.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/25.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/26.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/27.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/28.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/29.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/30.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/31.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/32.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/33.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/34.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/35.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/36.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/37.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/38.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/39.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/40.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/41.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/42.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/43.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/44.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/45.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/46.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/47.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/48.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/49.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/50.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/51.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/52.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/53.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/54.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/55.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/56.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/57.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/58.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/59.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/60.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/61.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/62.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/63.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/64.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/73.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/74.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/75.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/76.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/77.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/78.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/79.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/80.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/81.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/82.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/83.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/84.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/85.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/86.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/87.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/88.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/89.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/90.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/91.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/92.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/93.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/94.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/95.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/96.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/97.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/98.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/99.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/100.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/101.jar, /Programming/Unity/OUJX/BuildAndDestroyOUJX/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/102.jar
  Program type already present: com.unity3d.ads.UnityAds$PlacementState
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
]
stdout[
:checkReleaseClasspath
:preBuild UP-TO-DATE
:Firebase:preBuild UP-TO-DATE
:Firebase:preReleaseBuild UP-TO-DATE
:Firebase:checkReleaseManifest
:Firebase:processReleaseManifest
:GoogleMobileAdsPlugin:preBuild UP-TO-DATE
:GoogleMobileAdsPlugin:preReleaseBuild UP-TO-DATE
:GoogleMobileAdsPlugin:checkReleaseManifest
:GoogleMobileAdsPlugin:processReleaseManifest
:preReleaseBuild
:Firebase:compileReleaseAidl NO-SOURCE
:GoogleMobileAdsPlugin:compileReleaseAidl NO-SOURCE
:compileReleaseAidl NO-SOURCE
:Firebase:packageReleaseRenderscript NO-SOURCE
:GoogleMobileAdsPlugin:packageReleaseRenderscript NO-SOURCE
:compileReleaseRenderscript UP-TO-DATE
:checkReleaseManifest UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:prepareLintJar UP-TO-DATE
:mainApkListPersistenceRelease UP-TO-DATE
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:Firebase:compileReleaseRenderscript
:Firebase:generateReleaseResValues
:Firebase:generateReleaseResources
:Firebase:packageReleaseResources
:GoogleMobileAdsPlugin:compileReleaseRenderscript
:GoogleMobileAdsPlugin:generateReleaseResValues
:GoogleMobileAdsPlugin:generateReleaseResources
:GoogleMobileAdsPlugin:packageReleaseResources
:mergeReleaseResources UP-TO-DATE
:createReleaseCompatibleScreenManifests UP-TO-DATE
:processReleaseManifest
:splitsDiscoveryTaskRelease UP-TO-DATE
:Firebase:generateReleaseRFile
:GoogleMobileAdsPlugin:generateReleaseRFile
:processReleaseResources
:generateReleaseSources
:Firebase:generateReleaseBuildConfig
:Firebase:prepareLintJar UP-TO-DATE
:Firebase:generateReleaseSources
:Firebase:javaPreCompileRelease
:Firebase:compileReleaseJavaWithJavac
:Firebase:processReleaseJavaRes NO-SOURCE
:Firebase:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:GoogleMobileAdsPlugin:generateReleaseBuildConfig
:GoogleMobileAdsPlugin:prepareLintJar UP-TO-DATE
:GoogleMobileAdsPlugin:generateReleaseSources
:GoogleMobileAdsPlugin:javaPreCompileRelease
:GoogleMobileAdsPlugin:compileReleaseJavaWithJavac
:GoogleMobileAdsPlugin:processReleaseJavaRes NO-SOURCE
:GoogleMobileAdsPlugin:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:javaPreCompileRelease
:compileReleaseJavaWithJavac
:compileReleaseNdk NO-SOURCE
:compileReleaseSources
:lintVitalRelease
:mergeReleaseShaders UP-TO-DATE
:compileReleaseShaders UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:Firebase:mergeReleaseShaders
:Firebase:compileReleaseShaders
:Firebase:generateReleaseAssets
:Firebase:packageReleaseAssets
:GoogleMobileAdsPlugin:mergeReleaseShaders
:GoogleMobileAdsPlugin:compileReleaseShaders
:GoogleMobileAdsPlugin:generateReleaseAssets
:GoogleMobileAdsPlugin:packageReleaseAssets
:mergeReleaseAssets
:transformClassesWithDexBuilderForRelease
:transformDexArchiveWithExternalLibsDexMergerForRelease FAILED
49 actionable tasks: 36 executed, 13 up-to-date
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by YeminaIM** [comment]
What solved my issue in Unity 2018.3.0f2 (latest) is by
using
1. google play games servises version 0.9.50
2. fb version should be 7.14.0, import it but dont forget to uncheck play services resolver cuz we already had it from google play games plugin.
3. Goto fb settings put ids and regenerate android manifest
4. complete GPG setup then goto AndroidManifest.xml and remove this
 "<meta-data    android:name="com.google.android.gms.version"
    android:value="@integer/google_play_services_version" />"
5. If App ID has space in androidmanifest then remove that as well on my end its like this
" <meta-data android:name="com.google.android.gms.games.APP_ID"
            android:value="\9998.........." />"
6. on player settings check "User proguard file" then select none for release and none for debug 
7. search "proguard-user" text file in project and open it then put this code there:
-dontwarn com.google.vr.ndk.base.DaydreamApi 
in older version these steps worked like a charm and I was able to create the build easily but in latest version there are some conflicts in unity ads plugins and facebook plugins, to fix that I removed all supports files from audience network folder and then build worked perfectly.

**Comment by joshuajplagonera** [comment]
Can you try turning OFF the Ads service? The UnityAds Mediation plugin is incompatible with the Ads Service.

**Comment by charlesqu-thinkcube** [comment]
Had Exact same problem and found this post. 
In Unity, go to Tools -> Package Manager, and Uninstall "Advertisement" Fixed the problem

**Comment by UragayalaDeepika** [comment]
@nitzanwilnai Please comment here if you are still having this issue. We will reopen this and will assist you further. Marking this as closed for now.
