### ISSUE TITLE
MyTarget Adapter v5.2.5 trouble

### ISSUE THREAD

**Issue by rchallenger** [googleads/googleads-mobile-unity#833]
After adding dependency with latest adapter version application starts with MyTarget adapter and displays white banner wthout any content (and it is non clickable). All other networks adapters work fine. Also version 5.2.2 was good.

**Comment by rchallenger** [comment]
Here is a screenshot
![screenshot_2019-01-21-12-42-33](https://user-images.githubusercontent.com/20810488/51469472-165e3880-1d7a-11e9-9c1c-109e6807be7e.png)

**Comment by UragayalaDeepika** [comment]
@rchallenger Closing this for now. Feel free to comment here so that we can reopen this issue for you and we will take a look.
