### ISSUE TITLE
Banner AdPosition.Top has offset on iPhone X

### ISSUE THREAD

**Issue by Deja1100** [googleads/googleads-mobile-unity#835]
Hello,
I am using Unity 5.5.2f1 and Google Mobile Ads v3.15.1 and I have an issue with banner position on iPhone X device.
My unity app currently does not fully support iPhone X and I am displaying the app inside the safe area (by setting iPhone Launch Screen to None in Player Settings/Splash Image).
The problem is that the banner behaves like there is a notch involved, and it is positioned with some offset from the top of the screen.
I've tried setting banner position with AdPosition.Top and with x:0, y:0 coordinates, but I get the same result.
This position works fine with older iOS devices.
![img_20190123_095040](https://user-images.githubusercontent.com/46955953/51594420-a9bb7900-1ef4-11e9-92c0-21d4fa559550.jpg)

**Comment by itayganor** [comment]
Yeah, banners positioning is totally broken on devices with a notch. Check out #792

**Comment by UragayalaDeepika** [comment]
#792
