### ISSUE TITLE
Admob jar files are not included if Proguard is turned on!

### ISSUE THREAD

**Issue by xtrecoolx** [googleads/googleads-mobile-unity#836]
Hi,
In Unity player settings, I turned on proguard minification because I thought a smaller APK would be better before I release my game to play store. However, I had no clue that it would mess up Admob.
It took me several hours to figure out what was wrong and the only error message I was getting was:

AndroidJavaException: java.lang.ClassNotFoundException: com.google.unity.ads.UnityAdListener

Please talk about Proguard and write it to your integration guideline. It should be turned off

I thought the resolver got messed up but it was actually Proguard's fault.

**Comment by rampara** [comment]
@xtrecoolx have you tried adding proguard file that keeps `com.google.unity.ads *` ?

**Comment by xtrecoolx** [comment]
@rampara I am not familiar with Proguard so I don't know where to add it.

**Comment by takaaptech** [comment]
@xtrecoolx In the Assets/Plugin/Android there is proguard-user.txt file that you can add the content to:

# Google ads unity wrapper
-keep class com.google.unity.** { *; }

**Comment by xtrecoolx** [comment]
I don't see such file like that. Should I create it ?

**Comment by takaaptech** [comment]
Usually, It is will auto create if you check to checkbox
![screen shot 2019-01-24 at 11 54 29 am](https://user-images.githubusercontent.com/6276251/51655359-e52a7600-1fce-11e9-8377-8003008259ed.png)
 under build setting/ publishing setting:

**Comment by xtrecoolx** [comment]
Issue is solved.
