### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type Il2CppExceptionWrapper 

### ISSUE THREAD

**Issue by FaiyazMdAbdul** [googleads/googleads-mobile-unity#838]
`libc++abi.dylib: terminating with uncaught exception of type Il2CppExceptionWrapper `
Getting this error only on iOS.
App crashes after video loads .
unity - 2018.1.8
admob - latest sdk

**Comment by rampara** [comment]
@FaiyazMdAbdul are there any additional details in the crash trace? Are you able to consistently reproduce the problem? Can you provide a test app the reproduces the problem?

**Comment by FaiyazMdAbdul** [comment]
@rampara there are no other logs . and i will try to send app once i get access to mac.
Also , i am using firebase and google sign-in plugins in the app.

**Comment by DaniyarGilimov** [comment]
Have you found the any solution? Im getting the same error

**Comment by adampound** [comment]
Im having the same issue. with the exact same plugins as @FaiyaxMdAbdul.  Did you guys ever figure out a work around?

**Comment by UragayalaDeepika** [comment]
Closing this for now. Feel free to comment here so that we can reopen and investigate this issue if it is still reproducible with the latest version of the plugin.

**Comment by mancj** [comment]
I get this error when network is disabled. No any logs, just the message that @FaiyazMdAbdul mentioned. I have 11% crashes in firebase and whole day spent trying to fix it, you have to do something)
