### ISSUE TITLE
Banner issue!! Please help! I can`t hide the banner in gameplay

### ISSUE THREAD

**Issue by sorinpatent** [googleads/googleads-mobile-unity#839]
bannerView.Destroy(); is not working...the banner still appears after 2 sec
Also bannerView.Hide(); is not working.
How to fix this ?
Hee is my entire script:

public string AppID = "id";
    public string BannerAdUnitID = "id";

    private BannerView bannerView;

    public void HideBanner(){
    
        {
            bannerView.Hide();
        }
    }

   
public void DestroyBannerView(){
    if (this.bannerView != null)
        {
            this.bannerView.Destroy();
        }
    }
    void Start () {

        MobileAds.Initialize(AppID);

        bannerView = new BannerView(BannerAdUnitID, AdSize.Banner, AdPosition.Top);
        bannerView.LoadAd(new AdRequest.Builder().Build());
    }

	 
    void OnDestroy(){
    bannerView.Destroy();
}

void OnHide(){
    bannerView.Hide();

}
public void DestroyBanner(){
    
        {
            bannerView.Destroy();

**Comment by stowy** [comment]
Please try [version 3.17.0](https://github.com/googleads/googleads-mobile-unity/releases/tag/3.17.0).

**Comment by UragayalaDeepika** [comment]
@sorinpatent Closing this for now. Feel free to comment here so that we reopen and reinvestigate this issue if it is still reproducible with the latest version.
