### ISSUE TITLE
Applitaction Has Stopped!

### ISSUE THREAD

**Issue by rigby00** [googleads/googleads-mobile-unity#848]
**Hi,

Import admob to my Unity 2018.3.5. I builed apk and i installed it to my phone, when i start app it says "Applicaion Has Stopped". It's happening when i import admob plugin to my project. Can you help guys please.

Thanks.**

**Comment by arcv** [comment]
You should add `adb logcat` log to your issue report. My guess is missing Android library. Some problems can be solved with `Assets/Play Service Resolver/Android Resolver/Force Resolve`.

Do you use other libraries/plugins in Unity?

**Comment by rigby00** [comment]
> You should add `adb logcat` log to your issue report. My guess is missing Android library. Some problems can be solved with `Assets/Play Service Resolver/Android Resolver/Force Resolve`.
> 
> Do you use other libraries/plugins in Unity?

I solved it new package have some bugs. You need to add Application id to AndroidManifest.

**Comment by rchallenger** [comment]
There had to be a message in LogCat that could lead you to an article where they will explain you the reason of the issue.

PS: add this to your <application> section in manifest
`
<meta-data android:name="com.google.android.gms.ads.AD_MANAGER_APP" android:value="true"/>
`

**Comment by keyserjaya** [comment]
> > You should add `adb logcat` log to your issue report. My guess is missing Android library. Some problems can be solved with `Assets/Play Service Resolver/Android Resolver/Force Resolve`.
> > Do you use other libraries/plugins in Unity?
> 
> I solved it new package have some bugs. You need to add Application id to AndroidManifest.

Thank you! and many thanks! @rigby00 
That's right! we need to add Admob ID on AndroidManifest.xml (located in: Assets/Plugins/Android/GoogleMobileAdsPlugin)

Replace "[ADMOB APPLICATION ID]" to our "Admob appId" we are good to go!
No more crash on runtime.

Thank you again ^_^
