### ISSUE TITLE
Ads not displaying while app runs over Lockscreen

### ISSUE THREAD

**Issue by E-Reg** [googleads/googleads-mobile-unity#849]
No ads will be displayed, as long as the user does not unlock his phone.
Is there a way to solve this, or do I have to change the unity behavior to not run the app while the phone is locked.

**Comment by UragayalaDeepika** [comment]
@E-Reg I'm not sure I follow you. So you want to make sure to remove the ads if its backgrounded? can you elaborate? It sounds like an unity/iOS specific issue and not our plugin issue.

**Comment by E-Reg** [comment]
This only refers to using the unity development build option for Android.

**Comment by UragayalaDeepika** [comment]
@E-Reg This doesn't seem like an issue with the Plugin or our SDKs. This issue tracker is for the issues related to our Google Mobile Ads Unity plugin. Please post your Unity concerns on Unity [support forum](https://forum.unity.com/?_ga=2.215190164.2063929437.1564590361-1792095737.1543936422).
