### ISSUE TITLE
RewardBasedVideo.isLoaded does not check the same value as RewardBasedVideo.show

### ISSUE THREAD

**Issue by guusw** [googleads/googleads-mobile-unity#850]
In certain cases where ads are requested during a playing ad, the RewardBasedVideo will always return true for isLoaded. It seems to check a local boolean value while the show function checks rewardBasedVideo.isLoaded.

Is there any reason the isLoaded function can not also check the same internal rewardBasedVideo.isLoaded?

Relevant location: https://github.com/googleads/googleads-mobile-unity/blob/1c08a82eb1394ac6c49e8db5d4c8e293039d9f0a/source/android-library/app/src/main/java/com/google/unity/ads/RewardBasedVideo.java#L204

Related issue: https://github.com/googleads/googleads-mobile-unity/issues/471

I might submit a pull request if I get my build environment working.

**Comment by UragayalaDeepika** [comment]
@guusw This is WAI at this point. If the Reward Video is being shown, then the SDK allows you to preload another ad while this is being presented. You make a Reward Video request > Ad is loaded > Show it to the user > The is_loaded is set to false > You can fetch another ad as soon as you show the current ad to the user > Continue the flow. 

Let us know if you need anything else.
