### ISSUE TITLE
App crash with admob [added ad id android manifest]

### ISSUE THREAD

**Issue by onurigdi** [googleads/googleads-mobile-unity#853]
I ve got a game ready to publish. i am trying to integrate ads on it. game was working well till i install admob plugin. first i didnt add to androidmanifest.xml file game id. i found some topic about this and i copied "Temp\StagingArea\AndroidManifest.xml" file to  "Assets\Plugins\Android\AndroidManifest.xml"
and added 

" <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="your admob app id"/>" this code with my game id which starts with "
ca-app-pub-...." i build again. i check "Temp\StagingArea\AndroidManifest.xml" this file my game ids was there. but problem stils goes on app is carsh as soon as i touch on the game. i cant see unity splash screen. and cant see any thing on the logcat. how can i solve this issue.

**Comment by arcv** [comment]
Be sure you added meta-data between `<application>` tag, not `<activity>`

```xml
<application android:label="@string/app_name" android:debuggable="true" android:icon="@mipmap/app_icon">
  <activity>
    ...
  </activity>
  ...
  <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="[appId]" />
  <meta-data android:name="com.google.android.gms.ads.AD_MANAGER_APP" android:value="true" />
</application>```

**Comment by fdoumhan** [comment]
Is this row required?
`  <meta-data android:name="com.google.android.gms.ads.AD_MANAGER_APP" android:value="true" />`

What is Ad manager? I couldn't find any information.

**AdMob Unity Integration Docs:** (https://developers.google.com/admob/unity/start)

> If your app uses Ad Manager instead of AdMob, add the following <meta-data> tag to the AndroidManifest.xml file in the Assets/Plugins/Android/GoogleMobileAdsPlugin directory of your Unity app, instead of the tag shown above.

```
<manifest>
    <application>
        <meta-data
            android:name="com.google.android.gms.ads.AD_MANAGER_APP"
            android:value="true"/>
    </application>
</manifest>
```

**Comment by arcv** [comment]
@fdoumhan No, you don't have to. Add that meta-data if you use [Ad Manager](https://admanager.google.com/home/). It is Admob-like product from Google aswell.

**Comment by BEAKPICK** [comment]
I have a same problem. I put <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="[appId]" />
 to AndroidManifest.xml and suddenly app crashed. Something weird is the line I put in AndroidManifest.xml is deleted after build is done

**Comment by stowy** [comment]
Please set your app id using the settings editor ui -
https://developers.google.com/admob/unity/start#set_your_admob_app_id.

**Comment by UragayalaDeepika** [comment]
@BEAKPICK Please feel free to leave a comment here if you still have this issue. We will take a look into it.

**Comment by DivyeshKevadiya** [comment]
Add
<manifest>
    <application>
        <meta-data
            android:name="com.google.android.gms.ads.AD_MANAGER_APP"
            android:value="true"/>
    </application>
</manifest>

in your manifest and it will work seamlessly
