### ISSUE TITLE
InvalidOperationException: StandardIn has not been redirected

### ISSUE THREAD

**Issue by duhaonur** [googleads/googleads-mobile-unity#855]
After I import Mobile Ads Unity plugin I switched platform to android and this happened I deleted mobile ads plugin and tried to import when platform is android same thing happened again. How can I fix it

`InvalidOperationException: StandardIn has not been redirected.
System.Diagnostics.Process.get_StandardInput () (at <3845a180c26b4889bc2d47593a665814>:0)
(wrapper remoting-invoke-with-check) System.Diagnostics.Process.get_StandardInput()
GooglePlayServices.CommandLine.RunViaShell (System.String toolPath, System.String arguments, System.String workingDirectory, System.Collections.Generic.Dictionary`2[TKey,TValue] envVars, GooglePlayServices.CommandLine+IOHandler ioHandler, System.Boolean useShellExecution, System.Boolean stdoutRedirectionInShellMode) (at <0ea28fee5338451fbecc93319b91e068>:0)
GooglePlayServices.CommandLine.Run (System.String toolPath, System.String arguments, System.String workingDirectory, System.Collections.Generic.Dictionary`2[TKey,TValue] envVars, GooglePlayServices.CommandLine+IOHandler ioHandler) (at <0ea28fee5338451fbecc93319b91e068>:0)
GooglePlayServices.CommandLine+<RunAsync>c__AnonStorey1.<>m__0 () (at <0ea28fee5338451fbecc93319b91e068>:0)
System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Threading.ThreadHelper.ThreadStart () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
UnityEngine.UnhandledExceptionHandler:<RegisterUECatcher>m__0(Object, UnhandledExceptionEventArgs)`

![gmap](https://user-images.githubusercontent.com/25394262/53101432-c7532100-353a-11e9-94dd-63da1757fa9f.png)

**Comment by rchallenger** [comment]
Does it happen right after package was imported and scripts were compiled?
Or you call Resolve from PlayServicesResolver menu manually?

**Comment by duhaonur** [comment]
> Does it happen right after package was imported and scripts were compiled?
> Or you call Resolve from PlayServicesResolver menu manually?

Right after package imported and scripts compiled this and cmd shows up after a few seconds later cmd closing but Resolving Android Dependencies stays
I tried second one too tried to resolve from menu but when I click Resolve nothing happens

**Comment by NautisShadrick** [comment]
I'm having the same Issue have you figured it out yet?

**Comment by stowy** [comment]
What version of Unity are you using?

**Comment by duhaonur** [comment]
> I'm having the same Issue have you figured it out yet? just with googleAds

I think I reinstalled windows to solve this problem

**Comment by UragayalaDeepika** [comment]
Closing this for now. Feel free to comment here so that we can reopen and investigate this issue if it is still reproducible with the latest version.

**Comment by James805** [comment]
I'm having same issue on StandardIn has not been redirected

**Comment by nikunjkareliya** [comment]
Still facing this issue.
Platform switching doesn't work!

Anyone found proper fix?

**Comment by timrach** [comment]
I resolved this issue a minute ago by removing all special characters from the directory name. 
I had an apostrophe in the folder's name...

**Comment by mohammadmdp** [comment]
I'm having the same issue with Unity 2019.3.0 and GoogleMobileAds-v4.2.1.unitypackage
