### ISSUE TITLE
Can't use .asmdef on this plugin

### ISSUE THREAD

**Issue by macagu** [googleads/googleads-mobile-unity#856]
Unity's [AssemblyDefinitionFiles](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html) cannot be used on GoogleMobileAds.

Here are the steps to reproduce this:

1. Create an **Assembly Definition** on GoogleMobileAds, and anotherone in GoogleMobileAds/Editor for Editor.
2. Run the test app on the any Android device.
3. Notice the following exception:
```
NullReferenceException: Object reference not set to an instance of an object
at GoogleMobileAds.Api.MobileAds.GetMobileAdsClient () [0x0000a] in <7da0ddc89f8a4e30b05720ae4ee5d893>:0 
at GoogleMobileAds.Api.MobileAds..cctor () [0x00000] in <7da0ddc89f8a4e30b05720ae4ee5d893>:0 
Rethrow as TypeInitializationException: The type initializer for 'GoogleMobileAds.Api.MobileAds' threw an exception.
at GoogleMobileAdsDemoScript.Start () [0x00000] in <a20268e07fbe45a7abc29eec279334bc>:0 
```

I believe this is due Reflection being used like:
`Type googleMobileAdsClientFactory = Type.GetType("GoogleMobileAds.GoogleMobileAdsClientFactory,Assembly-CSharp");`

**Comment by GreenGateMaster** [comment]
i changed that line to 
Type googleMobileAdsClientFactory = typeof(GoogleMobileAds.GoogleMobileAdsClientFactory);
and its working now.

**Comment by keepup** [comment]
@GreenGateMaster 
Does this cause other problems? If not, why not designed in this way before?

**Comment by GreenGateMaster** [comment]
@keepup 
I'm facing no problems, but i don't know will it cause any problems in future.
I'm asking your second question to designers as well :)

**Comment by lukaszkn** [comment]
This happens because of Managed Stripping Level (Player Settings/Other settings) when IL2CPP scripting backend is used. Avoid using Type.GetType("") anywhere in the code cause referenced assembly will be stripped out if not used using strong name typing.

**Comment by UragayalaDeepika** [comment]
Closing the issue. Please comment here if you have any questions on this issue so that we can reopen the issue and investigate further.
