### ISSUE TITLE
Vungle Adapter - Manifest Not Found

### ISSUE THREAD

**Issue by thomasjohnwolfe** [googleads/googleads-mobile-unity#859]
I have multiple adapters for iOS and Android setup and working correctly. However the only malfunctioning one is **Vungle on Android**.

When I run the _Mediation Test Suite_  from https://developers.google.com/admob/unity/mediation-test-suite , it says "manifest not found" only on Vungle in Android builds. 

![screenshot_20190220-172828_two dots](https://user-images.githubusercontent.com/4453372/53197593-831e5a00-35e8-11e9-8e57-84c55609604e.jpg)

I do not see any steps in the Vungle documentation https://developers.google.com/admob/unity/mediation/vungle  that mention a "manifest" of any sort.  

`AndroidManifest` seems to be setup properly for Admob, because the rest of my app works correctly. I am not sure what "manifest not found" means.
Please advise. Thanks.

Unity 2018.1.9f2
Google Mobile Ads SDK - v3.15.1
Vungle Mediation Adapter - 3.1.1
GP Resolver - v1.2.99
Test Device - Galaxy S8 - Android 8.0.0

**Comment by rchallenger** [comment]
You'd better use version 6.3.24 that Vungle recomends to download on their official website. 
3.1 is too old version.
Here you can find dependencies XML to use in combination with PlayServicesResolver.
[https://github.com/googleads/googleads-mobile-unity/tree/master/mediation/Vungle](url)

**Comment by thomasjohnwolfe** [comment]
Nice. Will try and let you know. Thanks.

**Comment by thomasjohnwolfe** [comment]
@rchallenger  Are you saying to use this https://github.com/Vungle/Unity-Plugin  ? Is this the same as the mediation plug-in? 
https://support.vungle.com/hc/en-us/articles/360003455452-Get-Started-with-Vungle-SDK-v-6-Unity#Step1SetUpUnityProjectWithPlugin says "Unity 2018 is not officially support yet as of Unity Plugin v6.3.0"

I don't see 6.3.24 for Unity. I see 6.3.24 for the native for Android SDK at https://dashboard.vungle.com/sdk However, I'm not entirely sure how to plug this into Unity.

Also why don't the steps highlighted at Admob Vungle mediation work?

**Comment by thomasjohnwolfe** [comment]
@rchallenger 
I think there might be confusion with the `Vungle mediation plug-in` version and the `Vungle SDK` version.
I am using `Vungle SDK 6.3.24.0` which is specified here: https://github.com/googleads/googleads-mobile-unity/blob/master/mediation/Vungle/source/plugin/Assets/GoogleMobileAds/Editor/VungleMediationDependencies.xml 

but if you look at the top of that commit that file is from https://github.com/googleads/googleads-mobile-unity/commit/abcd36c539573a05b75e931b33e6ab747f9d5ac5  its using `Vungle Mediation Adapter version 3.1.1`.

Can you please advise, knowing that I am using the current version you suggested.
Thank you!
- Thomas.

**Comment by thomasjohnwolfe** [comment]
It looks like Vugle is actually working and serving Vungle ads. I think the problem may be with mediation test suite.

I’m closing this issue for now.

Thanks.

**Comment by Thaina** [comment]
Still have the same problem. I am not sure Vungle are really served but cannot be test in the suite is bugged me
