### ISSUE TITLE
Unity 3D Admob + Facebook Audience Network Rewarded Video Mediation Problem

### ISSUE THREAD

**Issue by aceloq** [googleads/googleads-mobile-unity#861]
Hello,
I am using admob mediation in my unity 3D project.

I using ad networks :
Admob Network,
UnityAds,
Applovin,
Facebook Audience Network.

Interstitial ad works in all of them. 
Rewarded video ad works in Admob, Unityads and Applovin. There is no problem.
Rewarded video ad works on Facebook Audience Network but HandleRewardBasedVideoRewarded event not called.

Unity 3D Version : Unity 2018.3.5f1
Google Mobile Ads Unity Plugin Version : v3.15.1
Google Mobile Ads Facebook Mediation Adapter Version : 2.1.1

Note : I checked Apply to all networks in mediation groups box in Admob Rewarded Settings Panel.

**Comment by ahmetyazir22** [comment]
Hello, 

I have a similar setup and similar problem. In my case, I use Admob and Unity Ads(through mediation). Admob rewarded video callbacks work, however Unity Ads callbacks do not work consistently. Could you find a solution to your problem? It might help me, too. 

Thanks.

**Comment by stowy** [comment]
Please try latest versions, I believe this is resolved.

**Comment by UragayalaDeepika** [comment]
Closing this for now. Feel free to comment here so that we can reopen and investigate this issue if it is still reproducible with the latest version.
