### ISSUE TITLE
Unable to send ad network extras for custom event requests

### ISSUE THREAD

**Issue by SeanPONeil** [googleads/googleads-mobile-unity#864]
Right now the `Utils.GetAdRequestJavaObject(AdRequest request)` does not call `addCustomEventExtrasBundle()`, so no extra parameters are being sent to custom events.

I created #862 to resolve this issue.

**Comment by stowy** [comment]
Thanks for the fix @SeanPONeil - sorry for the delay in merging. Should be much quicker going forward.
