### ISSUE TITLE
Please add API to set the current device as test device

### ISSUE THREAD

**Issue by Thaina** [googleads/googleads-mobile-unity#870]
It really counter productive that we can't just set the current device as test device programmatically. If we don't use a remote setting we then need to build our project, try to scan adb logcat just for seeing id, then rebuild again just to add that id in the list. When what we really want is just to test an ads

The SDK should do something about this by itself. We don't even need to know the ID of the device. We just need to set the current device as a test device. And we can make any device test the test ads easily with userID or any interface

Your process that we need to scan the log is really blocking issue. It is actually designing bug

**Comment by rchallenger** [comment]
Why you wouldn't just use `SystemInfo.deviceUniqueIdentifier` to get your device identifier?

**Comment by Thaina** [comment]
@rchallenger I don't think it is the same id admob want to use. I think admob use ads tracking id or something, I'm not sure, but I was quite sure that it is not `SystemInfo.deviceUniqueIdentifier`

**Comment by rchallenger** [comment]
But you didn't even check this ...
In my case they are the same!

**Comment by Thaina** [comment]
@rchallenger If it is the same I would require that it should just mention in the official document, which it's not

And you could search google for it and you can see a workaround that we need to get native id and do MD5 hashing on it to get the id admob needed, and only that was worked in my device

**Comment by matie** [comment]
Hi,

Have a look at: https://developers.google.com/admob/unity/test-ads

We are using odd version codes for our beta's and so all devices using a beta (internal build) will show test ads only.

You could also choose for using a button somewhere in your game (only show it when running as beta :-)) to change the id's to the test ones and reload the ads.

**Comment by ericleich** [comment]
It is working as intended not to provide a setTestDevice(currentDevice) API, as someone would accidentally forget to take out that line of code, release, and then no traffic would generate revenue. This DID HAPPEN when we used to have a setTesting(true) API years ago. The current API is admittedly harder to use, but it also prevents you from shooting yourself in the foot.
