### ISSUE TITLE
NativeAds native java crash: GetStarRating

### ISSUE THREAD

**Issue by rotter** [googleads/googleads-mobile-unity#873]
Calling GetStarRating() is causing the crash below in production in a significative percentage of players. Since it's a native (java) crash, I can't try/catch it, and there's no workaround method to check if it's null from what I see (something like a bool ContainsStarRating())

```
java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
com.google.unity.ads.NativeAdvancedUnifiedNativeAd.getStarRating(NativeAdvancedUnifiedNativeAd.java:82)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.c(Unknown Source:0)
```

**Comment by UragayalaDeepika** [comment]
@rotter Are you still seeing these crashes? And, are you able to reproduce the issue locally?

**Comment by UragayalaDeepika** [comment]
Closed this for now. Feel free to comment so that we can reopen the issue and we will debug further.
