### ISSUE TITLE
Banner is invisible but still clickable

### ISSUE THREAD

**Issue by guplem** [googleads/googleads-mobile-unity#874]
I'm working on an app that displays a banner depending on the scene. I use Show and Hide to control this behavior.

It works perfectly the first time that the banner is shown, but the second (after being hidden) the banner does not appear. However, the banner zone still clickable and it performs as expected.

I'm using the last release of the AdMob plugin for unity (v3.15.1) and I have not been able of finding any solution to the problem.

You have all the information and code in this Stackoverflow post ( https://stackoverflow.com/questions/55132388/admob-banner-is-invisible-but-still-clickable-in-unity ) alongside with the solution that I've found (Destroying and Loading it every time instead of working with Showing and Hiding). However, I'm not sure of being a proper solution.

**Comment by stowy** [comment]
Please try [version 3.17.0](https://github.com/googleads/googleads-mobile-unity/releases/tag/3.17.0).

**Comment by UragayalaDeepika** [comment]
@guplem Closing this for now. Feel free to comment here so that we can reopen and  investigate this issue if it is still reproducible with the latest version.
