### ISSUE TITLE
Firebase + GooglePlayGame + ADMobs Gradle Build Error

### ISSUE THREAD

**Issue by cwysms** [googleads/googleads-mobile-unity#875]
CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Java/jdk1.8.0_202\bin\java.exe -classpath "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-2.14.jar" org.gradle.launcher.GradleMain "assembleRelease"

stderr[
Dex: Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
    UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
	at com.android.dx.command.dexer.Main.processClass(Main.java:761)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:727)
	at com.android.dx.command.dexer.Main.access$1200(Main.java:87)
	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1655)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:681)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:546)
	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:370)
	at com.android.dx.command.dexer.Main.run(Main.java:284)
	at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:52)
	at com.android.builder.core.AndroidBuilder$2.call(AndroidBuilder.java:1511)
	at com.android.builder.core.AndroidBuilder$2.call(AndroidBuilder.java:1507)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.parseClass(Main.java:773)
	at com.android.dx.command.dexer.Main.access$1600(Main.java:87)
	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1694)
	at com.android.dx.command.dexer.Main.processClass(Main.java:758)
	... 17 more

1 error; aborting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
]
stdout[
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:Firebase:preBuild UP-TO-DATE
:Firebase:preReleaseBuild UP-TO-DATE
:Firebase:compileReleaseNdk UP-TO-DATE
:Firebase:compileLint
:Firebase:copyReleaseLint UP-TO-DATE
:Firebase:mergeReleaseProguardFiles UP-TO-DATE
:Firebase:packageReleaseRenderscript UP-TO-DATE
:Firebase:checkReleaseManifest
:Firebase:prepareReleaseDependencies
:Firebase:compileReleaseRenderscript
:Firebase:generateReleaseResValues UP-TO-DATE
:Firebase:generateReleaseResources
:Firebase:packageReleaseResources
:Firebase:compileReleaseAidl
:Firebase:generateReleaseBuildConfig
:Firebase:mergeReleaseShaders
:Firebase:compileReleaseShaders
:Firebase:generateReleaseAssets
:Firebase:mergeReleaseAssets
:Firebase:processReleaseManifest
:Firebase:processReleaseResources
:Firebase:generateReleaseSources
:Firebase:incrementalReleaseJavaCompilationSafeguard
:Firebase:compileReleaseJavaWithJavac
:Firebase:processReleaseJavaRes UP-TO-DATE
:Firebase:transformResourcesWithMergeJavaResForRelease
:Firebase:transformClassesAndResourcesWithSyncLibJarsForRelease
:Firebase:mergeReleaseJniLibFolders
:Firebase:transformNative_libsWithMergeJniLibsForRelease
:Firebase:transformNative_libsWithSyncJniLibsForRelease
:Firebase:bundleRelease
:GoogleMobileAdsPlugin:preBuild UP-TO-DATE
:GoogleMobileAdsPlugin:preReleaseBuild UP-TO-DATE
:GoogleMobileAdsPlugin:compileReleaseNdk UP-TO-DATE
:GoogleMobileAdsPlugin:compileLint
:GoogleMobileAdsPlugin:copyReleaseLint UP-TO-DATE
:GoogleMobileAdsPlugin:mergeReleaseProguardFiles UP-TO-DATE
:GoogleMobileAdsPlugin:packageReleaseRenderscript UP-TO-DATE
:GoogleMobileAdsPlugin:checkReleaseManifest
:GoogleMobileAdsPlugin:prepareReleaseDependencies
:GoogleMobileAdsPlugin:compileReleaseRenderscript
:GoogleMobileAdsPlugin:generateReleaseResValues UP-TO-DATE
:GoogleMobileAdsPlugin:generateReleaseResources
:GoogleMobileAdsPlugin:packageReleaseResources
:GoogleMobileAdsPlugin:compileReleaseAidl
:GoogleMobileAdsPlugin:generateReleaseBuildConfig
:GoogleMobileAdsPlugin:mergeReleaseShaders
:GoogleMobileAdsPlugin:compileReleaseShaders
:GoogleMobileAdsPlugin:generateReleaseAssets
:GoogleMobileAdsPlugin:mergeReleaseAssets
:GoogleMobileAdsPlugin:processReleaseManifest
:GoogleMobileAdsPlugin:processReleaseResources
:GoogleMobileAdsPlugin:generateReleaseSources
:GoogleMobileAdsPlugin:incrementalReleaseJavaCompilationSafeguard
:GoogleMobileAdsPlugin:compileReleaseJavaWithJavac
:GoogleMobileAdsPlugin:processReleaseJavaRes UP-TO-DATE
:GoogleMobileAdsPlugin:transformResourcesWithMergeJavaResForRelease
:GoogleMobileAdsPlugin:transformClassesAndResourcesWithSyncLibJarsForRelease
:GoogleMobileAdsPlugin:mergeReleaseJniLibFolders
:GoogleMobileAdsPlugin:transformNative_libsWithMergeJniLibsForRelease
:GoogleMobileAdsPlugin:transformNative_libsWithSyncJniLibsForRelease
:GoogleMobileAdsPlugin:bundleRelease
:GooglePlayGamesManifest.plugin:preBuild UP-TO-DATE
:GooglePlayGamesManifest.plugin:preReleaseBuild UP-TO-DATE
:GooglePlayGamesManifest.plugin:compileReleaseNdk UP-TO-DATE
:GooglePlayGamesManifest.plugin:compileLint
:GooglePlayGamesManifest.plugin:copyReleaseLint UP-TO-DATE
:GooglePlayGamesManifest.plugin:mergeReleaseProguardFiles UP-TO-DATE
:GooglePlayGamesManifest.plugin:packageReleaseRenderscript UP-TO-DATE
:GooglePlayGamesManifest.plugin:checkReleaseManifest
:GooglePlayGamesManifest.plugin:prepareReleaseDependencies
:GooglePlayGamesManifest.plugin:compileReleaseRenderscript
:GooglePlayGamesManifest.plugin:generateReleaseResValues UP-TO-DATE
:GooglePlayGamesManifest.plugin:generateReleaseResources
:GooglePlayGamesManifest.plugin:packageReleaseResources
:GooglePlayGamesManifest.plugin:compileReleaseAidl
:GooglePlayGamesManifest.plugin:generateReleaseBuildConfig
:GooglePlayGamesManifest.plugin:mergeReleaseShaders
:GooglePlayGamesManifest.plugin:compileReleaseShaders
:GooglePlayGamesManifest.plugin:generateReleaseAssets
:GooglePlayGamesManifest.plugin:mergeReleaseAssets
:GooglePlayGamesManifest.plugin:processReleaseManifest
:GooglePlayGamesManifest.plugin:processReleaseResources
:GooglePlayGamesManifest.plugin:generateReleaseSources
:GooglePlayGamesManifest.plugin:incrementalReleaseJavaCompilationSafeguard
:GooglePlayGamesManifest.plugin:compileReleaseJavaWithJavac
:GooglePlayGamesManifest.plugin:processReleaseJavaRes UP-TO-DATE
:GooglePlayGamesManifest.plugin:transformResourcesWithMergeJavaResForRelease
:GooglePlayGamesManifest.plugin:transformClassesAndResourcesWithSyncLibJarsForRelease
:GooglePlayGamesManifest.plugin:mergeReleaseJniLibFolders
:GooglePlayGamesManifest.plugin:transformNative_libsWithMergeJniLibsForRelease
:GooglePlayGamesManifest.plugin:transformNative_libsWithSyncJniLibsForRelease
:GooglePlayGamesManifest.plugin:bundleRelease
:prepareAndroidArchLifecycleRuntime100Library UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2610Library UP-TO-DATE
:prepareComAndroidSupportAppcompatV72610Library UP-TO-DATE
:prepareComAndroidSupportCardviewV72610Library UP-TO-DATE
:prepareComAndroidSupportCustomtabs2610Library UP-TO-DATE
:prepareComAndroidSupportMultidex101Library UP-TO-DATE
:prepareComAndroidSupportSupportCompat2610Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUi2610Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUtils2610Library UP-TO-DATE
:prepareComAndroidSupportSupportFragment2610Library UP-TO-DATE
:prepareComAndroidSupportSupportMediaCompat2610Library UP-TO-DATE
:prepareComAndroidSupportSupportV42610Library UP-TO-DATE
:prepareComAndroidSupportSupportVectorDrawable2610Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAds1720Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAdsBase1720Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAdsIdentifier1600Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAdsLite1720Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAuth1601Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAuthApiPhone1600Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAuthBase1600Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase1601Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBasement1610Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesDrive1600Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesFlags1601Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesGames1600Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesGass1720Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMeasurementApi1630Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMeasurementBase1630Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMeasurementSdkApi1630Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesNearby1600Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesStats1601Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesTasks1601Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseAnalytics1630Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseAnalyticsImpl1630Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseAppUnity550Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseAuth1620Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseAuthInterop1601Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseAuthUnity550Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseCommon1610Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseCore1607Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseIid1703Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseIidInterop1601Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseMeasurementConnector1701Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseMeasurementConnectorImpl1705Library UP-TO-DATE
:prepareComGoogleGamesGpgsPluginSupport0962Library UP-TO-DATE
:prepareFacebookAndroidWrapper7151Library UP-TO-DATE
:prepareFacebookApplinksLibrary UP-TO-DATE
:prepareFacebookCommonLibrary UP-TO-DATE
:prepareFacebookCoreLibrary UP-TO-DATE
:prepareFacebookLoginLibrary UP-TO-DATE
:prepareFacebookMarketingLibrary UP-TO-DATE
:prepareFacebookMessengerLibrary UP-TO-DATE
:prepareFacebookPlacesLibrary UP-TO-DATE
:prepareFacebookShareLibrary UP-TO-DATE
:prepareGradleOutFirebaseUnspecifiedLibrary
:prepareGradleOutGoogleMobileAdsPluginUnspecifiedLibrary
:prepareGradleOutGooglePlayGamesManifestPluginUnspecifiedLibrary
:prepareReleaseDependencies
:compileReleaseAidl UP-TO-DATE
:compileReleaseRenderscript UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:mergeReleaseShaders UP-TO-DATE
:compileReleaseShaders UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:mergeReleaseResources UP-TO-DATE
:processReleaseManifest UP-TO-DATE
:processReleaseResources
:generateReleaseSources
:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:compileReleaseJavaWithJavac
:compileReleaseNdk UP-TO-DATE
:compileReleaseSources
:lintVitalRelease
:prePackageMarkerForRelease
:transformClassesWithJarMergingForRelease
:collectReleaseMultiDexComponents UP-TO-DATE
:transformClassesWithMultidexlistForRelease
ProGuard, version 5.2.1
Reading program jar [C:\Users\cwysm\Documents\Work\Firebase2\Temp\gradleOut\build\intermediates\transforms\jarMerging\release\jars\1\1f\combined.jar]
Reading library jar [C:\Users\cwysm\AppData\Local\Android\Sdk\build-tools\25.0.3\lib\shrinkedAndroid.jar]
Preparing output jar [C:\Users\cwysm\Documents\Work\Firebase2\Temp\gradleOut\build\intermediates\multi-dex\release\componentClasses.jar]
  Copying resources from program jar [C:\Users\cwysm\Documents\Work\Firebase2\Temp\gradleOut\build\intermediates\transforms\jarMerging\release\jars\1\1f\combined.jar]
:transformClassesWithDexForRelease FAILED

BUILD FAILED

Total time: 59.309 secs
]
exit code: 1
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.GradleWrapper.RunJava (System.String args, System.String workingdir, UnityEditor.Android.Progress progress)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.RunJava (System.String args, System.String workingdir, UnityEditor.Android.Progress progress)
UnityEditor.Android.GradleWrapper.Run (System.String workingdir, System.String task, UnityEditor.Android.Progress progress)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.HostView:OnGUI()

If I build without ADMob, it works fine without errors.
When I add ADMob, an error occurs as above.

I wonder if there is a solution.
If you need more information, we will forward it to you.

Thank you.

**Comment by stowy** [comment]
Please confirm the environment you are using - gradle version, etc. This should not occur on recent versions of gradle. Does it work for you using AdMob alone?

**Comment by UragayalaDeepika** [comment]
@cwysms Can you please confirm whether you are still having this issue? 

We are closing this for now. Feel free to comment here so that we can reopen and investigate this issue if it is still reproducible with the latest version.
