### ISSUE TITLE
Unity plugin out of date for iOS?

### ISSUE THREAD

**Issue by yosun** [googleads/googleads-mobile-unity#878]
Just downloaded the latest Unity plugin for Admob and ran it on a test device. Received the out of date in log: 

You are currently using version 7.32.0 of the SDK. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be downloaded from https://goo.gl/UoiJ8F. A full list of release notes is available at https://developers.google.com/admob/ios/rel-notes.

**Comment by UragayalaDeepika** [comment]
Hello @yosun 

The log message that you have seen is suggesting you to download the latest version of the iOS SDK which is available here- https://developers.google.com/admob/ios/rel-notes and it is not about the Unity Plugin. Please update the SDK and let us know if you have any issue while Integrating the Google Mobile Ads Unity plugin into your app. You can go through this documentation as well - https://developers.google.com/admob/unity/start

**Comment by ericleich** [comment]
If you grabbed version 3.16.0 of the plugin, it specifies the iOS SDK dependency at https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml#L11 which is currently set to 7.41 or higher. My guess is you didn't have 3.16.0 of the plugin.
