### ISSUE TITLE
RewardAd can not destroy.

### ISSUE THREAD

**Issue by wdc997669919** [googleads/googleads-mobile-unity#879]
I use the latest sdk,an error of memory leaked with not close the response of body  When i load and show the reward ad video .How can i destroy it when close the ad? I can not find the api in doc.

**Comment by perseus25** [comment]
I read this on tutorial: "RewardedAd is a one-time-use object. This means once a rewarded ad is shown, the object can't be used to load another ad. To request another rewarded ad, you'll need to create a new RewardedAd object."
And I think when finished with a InterstitialAd, I must call the Destroy() method before dropping reference to it. But I can't found Detroy method.

**Comment by stowy** [comment]
There is no destroy API on Rewarded ads. If there are leaks occurring then it is an issue with the iOS SDK. 

If this is still occurring, can you report it on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines? They will be able to help debug your issue with you efficiently.

**Comment by wdc997669919** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
