### ISSUE TITLE
project not building in Xcode 

### ISSUE THREAD

**Issue by cgerard78** [googleads/googleads-mobile-unity#880]
My project is not building in Xcode, and that is using the sample project provided here https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld

All 4 frameworks have been imported in Xcode
Admob SDK Google Utilities Admeasurement nanopb

I've built the project in unity, imported it in Xcode, added the 4 frameworks in Xcode and also added them manually using cocoa pods in a terminal file

I keep getting the same error preventing me to build the project in Xcode

ld: warning: directory not found for option '-L/Users/xxx/Downloads/testbuild/DerivedData/Unity-iPhone/Build/Products/ReleaseForProfiling-iphoneos/GoogleUtilities'
ld: warning: directory not found for option '-L/Users/xxx/Downloads/testbuild/DerivedData/Unity-iPhone/Build/Products/ReleaseForProfiling-iphoneos/nanopb'

ld: library not found for -lGoogleUtilities

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by UragayalaDeepika** [comment]
@cgerard78 You can test with this [sample app](https://drive.google.com/drive/folders/1GL7SakPsPGMEM4WeUuaiippGuH3T3zID?usp=sharing) and let us know if you need anything else.

**Comment by UragayalaDeepika** [comment]
@cgerard78  Did that resolve your issue?

**Comment by saqibkhan2523** [comment]
I have the same issue. What are GoogleUtillities and is this issue related to Xocde or Unity?

**Comment by saqibkhan2523** [comment]
@UragayalaDeepika the sample app is also giving the same error. I use same thing for another project and it build fine but i don't know what causing this issue.

**Comment by saqibkhan2523** [comment]
Ok so I imported the plugin again then set `Enable-Bitcode` to `No` and it build successfully.

**Comment by RatsLoveCats** [comment]
I have the same problem, I put Enable-Bitcode to No, but I have not built it successfully.

**Comment by RatsLoveCats** [comment]
@saqibkhan2523 I have the same problem, I put Enable-Bitcode to No, but I have not built it successfully.

**Comment by RatsLoveCats** [comment]
@UragayalaDeepika
