### ISSUE TITLE
iOS namespace error and no resolver option after import.

### ISSUE THREAD

**Issue by wooden-coder** [googleads/googleads-mobile-unity#882]
When I import this admob plugin (v 3.16) i get an error:

> Assets/GoogleMobileAds/Editor/PListProcessor.cs(5,19): error CS0234: The type or namespace name `iOS' does not exist in the namespace `UnityEditor'. Are you missing an assembly reference?

Also, i have no option "play services resolver" after plugin import.

This script "PListProcessor.cs" uses namespace "UnityEditor.iOS.Xcode;", i guess this is the issue.

I have no iOS support in my Unity, i don't need it and everything used to work well before.

I have this error in my newest **Unity 2018.3.9f1**. The same goes with older **2018.2.11** 

Previous version of admob plugin (Jan 2019) shows no errors in both versions of Unity.

So, it looks like something is wrong with the newest version of Admob Plugin for Unity. How to solve this problem?

**Comment by stowy** [comment]
Hi, we added this support for adding the plist entry GADAdIdentifier in Xcode projects.

Can you try wrapping the whole [PListProcessor.cs](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Editor/PListProcessor.cs) file with   #if UNITY_IPHONE and see if this resolves the issue?

Are you also saying that play services resolver is not included in your unity project?

**Comment by wooden-coder** [comment]
> Can you try wrapping the whole PListProcessor.cs file with #if UNITY_IPHONE and see if this resolves the issue?

That helped. Now i don't have any errors and Play Services Resolver is available again. Resolution for Android ended with successful result. Thank you! I hope everything will be ok now.

Here is the new (wrapped) version of the PListProcessor.cs, if anyone cares.
```
#if UNITY_IPHONE
using System.IO;

using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;

public static class PListProcessor
{
    [PostProcessBuild]
    public static void OnPostProcessBuild(BuildTarget buildTarget, string path)
    {
        
          // Replace with your iOS AdMob app ID. Your AdMob App ID will look
          // similar to this sample ID: ca-app-pub-3940256099942544~1458002511
          string appId = "ADMOB_APPLICATION_ID";

          string plistPath = Path.Combine(path, "Info.plist");
          PlistDocument plist = new PlistDocument();

          plist.ReadFromFile(plistPath);
          plist.root.SetString("GADApplicationIdentifier", appId);
          File.WriteAllText(plistPath, plist.WriteToString());
        
    }
}
#endif
```

> Are you also saying that play services resolver is not included in your unity project?

The folder itself existed after the import but menu option wasn't.

**Comment by stowy** [comment]
np. Updated code, will be in next version.
