### ISSUE TITLE
No option for setting ServerSideVerificationOptions for new RewardedAd APIs

### ISSUE THREAD

**Issue by halfdevil** [googleads/googleads-mobile-unity#888]
There is no option to pass user id or set ServerSideVerificationOptions in the new RewardedAd APIs.

**Comment by Opeth001** [comment]
I didn't found it too! :( 
There is no way to set the user id within the new rewarded ads API.

The documentation do not have any example about it too. 

I hope Google didn't forget to implement it, it will be a shame for non setting the userid into a rewarded ad.

**Comment by halfdevil** [comment]
I have added an option to set ServerSideVerificationOptions for new Rewarded API. The package for the same can be found here:
https://github.com/halfdevil/googleads-mobile-unity/releases/download/v3.16.1/GoogleMobileAds.unitypackage
