### ISSUE TITLE
(iOS) Can't exit Reward Ad to receive reward after viewing

### ISSUE THREAD

**Issue by truusongz** [googleads/googleads-mobile-unity#889]
Hi, a small percentage of our iOS users are experiencing an issue where they cannot exit the rewarded video ad to receive their reward after completely viewing the ad. The exit (X) button appears but clicking on it does not exit the ad.

I'm using the latest version of the plugin 3.16 . Could it be an issue with the Google-Mobile-Ads-SDK version? Currently my podfile says:

target 'Unity-iPhone' do
pod 'Crashlytics', '3.12.0'
pod 'Fabric', '1.9.0'
pod 'Firebase/Analytics', '5.20.0'
pod 'Firebase/Auth', '5.20.0'
pod 'Firebase/Core', '5.20.0'
pod 'Firebase/Messaging', '5.20.0'
pod 'Firebase/Storage', '5.20.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.41'
end

Am I using the correct 7.41 version? Might this be a known bug and fixed in the later version? I cannot update the 'Google-Mobile-Ads-SDK' to the newest version 7.42.2 through cocoapods. 

Once again, this is only happening to a small percentage of our users but it is a problem that we would like to fix. I've tested the ads myself and it seems to be working so I can't provide the bug-steps.

Any help would be appreciated - thank you in advance!

**Comment by sberogames** [comment]
We are seeing the same issue on both Android and iOS using version 3.16.

Pod file on iOS:
```
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'Unity-iPhone' do
pod 'GoogleMobileAdsMediationUnity', '3.0.0.3'
pod 'Google-Mobile-Ads-SDK', '~> 7.41'
end
```

We'll be happy to provide any additional details required to resolve this.

**Comment by jonathanleang** [comment]
same bug here using v3.16 also tried downgrading to v3.15.1 same bug

**Comment by ha-quang-vu** [comment]
@truusongz @jonathanleang 
Did the movie reward come out is "Homescapes" game?
I have same bug. 
If "Homescapes" came out, I cannot close. But other reward game, It's okay.

**Comment by Final3514** [comment]
I'm having the same issue on my dev devices - hitting 'x' in the top right corner does not exit ads on the iphone ( I have received both gardenscape and wordscape ads, and neither can be exited )

Manually resetting my advertising identifier allowed me to exit ads again, but I don't know how prevalent this issue would be in the wild if released, which makes me very nervous

**Comment by AlekseySimonenko** [comment]
We'r get the same user reports on last 2 weeks!  
Android + Ios 
Unity 2018.2.20f1
Admob sdk 15.0.1
We can reproduce error on device: Huawei P20 OS 9
Users devices: device model:iPhone 8,1 os:iOS 12.1.4

**Comment by truusongz** [comment]
> @truusongz @jonathanleang
> Did the movie reward come out is "Homescapes" game?
> I have same bug.
> If "Homescapes" came out, I cannot close. But other reward game, It's okay.

@ha-quang-vu I didn't get the exact bug step information from the users regarding which ad it was. But it seems like that might be part of the issue, @Final3514 is reporting the same problem for the Gardenscape ad and they're from the same publisher.

Can we get some answers/input from the developers regarding the scope of this issue?

**Comment by stowy** [comment]
Hi,

This could be creative specific, if you are seeing the same ad regularly
that causes this, please try the ad review center -
https://support.google.com/admob/answer/3480906?hl=en - this should enable
you to block the ad.

It would also be a good idea to report this on the developer forum (
https://groups.google.com/forum/#!forum/google-admob-ads-sdk) since this is
definitely not a unity plugin issue.

Regards

Sam

**Comment by alokkora154-debug** [comment]
***

**Comment by krushna-ux** [comment]
35322091

**Comment by ididucifig-oss** [comment]
hqn
