### ISSUE TITLE
No way to set the UserId within the new RewardedAds Api

### ISSUE THREAD

**Issue by Opeth001** [googleads/googleads-mobile-unity#891]
The title describes everything.

**Comment by halfdevil** [comment]
I have added an option to set ServerSideVerificationOptions for new Rewarded API. You can found the package here:
https://github.com/halfdevil/googleads-mobile-unity/releases/download/v3.16.1/GoogleMobileAds.unitypackage

**Comment by stowy** [comment]
thanks for the fix @halfdevil
