### ISSUE TITLE
libc.tgkill application crash

### ISSUE THREAD

**Issue by SnnYsf** [googleads/googleads-mobile-unity#892]
if I switch to new admob version, crashes are increasing. just android 8.0.0
  
if i use plugin 3.7.0 everythings is okey.

I can't get the update for 1 year.
all updates are problematic :)

| libc.tgkill (tgkill:12)
-- | --
  | libc.abort (abort:54)
  | libart.art::detail::CmdlineParseArgument<std::__1::vector<art::Plugin,  std::__1::allocator<art::Plugin> >  >::ParseArgumentSingle(std::__1::basic_string<char,  std::__1::char_traits<char>, std::__1::allocator<char> >  const&) (detail:822)
  | libart.art::CmdlineType<std::__1::vector<art::Plugin,  std::__1::allocator<art::Plugin> >  >::ParseAndAppend(std::__1::basic_string<char,  std::__1::char_traits<char>, std::__1::allocator<char> >  const&, std::__1::vector<art::Plugin,  std::__1::allocator<art::Plugin> >&) (CmdlineType:146)
  | libart.art::Thread::GetNativePriority() (Thread:180)
  | libart.art::gc::space::RegionSpace::LogFragmentationAllocFailure(std::__1::basic_ostream<char,  std::__1::char_traits<char> >&, unsigned int) (gc:226)
  | libart.art::interpreter::UnstartedRuntime::UnstartedMemoryPeekByteArray(art::Thread*,  art::ShadowFrame*, art::JValue*, unsigned int) (interpreter:210)
  | libart.art::interpreter::UnstartedRuntime::UnstartedClassGetEnclosingClass(art::Thread*,  art::ShadowFrame*, art::JValue*, unsigned int) (interpreter:82)
  | libart.art::InlineInfo::Dump(art::VariableIndentationOutputStream*,  art::CodeInfo const&, art::MethodInfo const&, unsigned short*)  const (art:2474)
  | libart.std::__1::__function::__func<art::CmdlineParser<art::RuntimeArgumentMap,   art::RuntimeArgumentMap::Key>::ArgumentBuilder<art::verifier::VerifyMode>::IntoKey(art::RuntimeArgumentMapKey<art::verifier::VerifyMode>  const&)::{lambda(art::verifier::VerifyMode&)#1},  std::__1::allocator<{lambda(art::verifier::VerifyMode&)#1}>,  void (art::verifier::VerifyMode&)>::__clone() const (__1:6)
  | libart.art::CmdlineParser<art::RuntimeArgumentMap,

**Comment by UragayalaDeepika** [comment]
@SnnYsf  Please be on the latest version of our plugin and  let us know if you are still having issues. We will take a look into this issue.

**Comment by UragayalaDeepika** [comment]
Closing the issue. Please comment here if you still need assistance on this so that we can reopen the issue.
