### ISSUE TITLE
Interstitial ad callbacks not firing on iOS

### ISSUE THREAD

**Issue by bartofzo** [googleads/googleads-mobile-unity#895]
Hello,

I'm running into a problem where the callbacks of an interstitial ad are suddenly not being fired.
It does work when test mode is enabled. Doesn't with the real id's.

Seems like the ad won't load, but OnAdFailedToLoad does not get called. IsLoaded() reports false.

The problem is 100% not in my code because it works on Android and in test mode. 
Bottom ad is working. Rewarded video ad is also working.

May also be useful to note that I have recently updated to Unity 2018.3.13f1 because of a crash related to android:

    https://forum.unity.com/threads/crashes-on-android-after-migrating-to-unity-2018-3-when-use-androidjavaproxy-class.627637/page-4

But I'm not exactly sure if the problem started after this update. 

Hoping you can be of assistance. Thanks.

**Comment by adamjsutcliffe** [comment]
I'm getting a similar issue using Unity ads through AdMob mediation. I can display Unity ads fine but the closed handler is never getting called so my app gets stuck. It doesn't seem to matter if the ad plays all the way to the end or is exited early. 

I'm using the latest mediation package via Unity GoogleMobileAdsMediationUnity version 3.0.0.3 with Unity 2017.4.25 and exporting to Xcode 10.2.1. Other ad networks work fine, so I'm assuming its an issue here??

**Comment by stowy** [comment]
@adamjsutcliffe can you clarify, using AdMob mediation you are seeing callbacks for some mediated networks but not for Unity ads?

**Comment by adamjsutcliffe** [comment]
@stowy That's correct, I have AdMob mediation setup with Unity ads, FAN, AppLovin, Tapjoy and Vungle and the interstitial closed callback doesn't fire for Unity Ads the rest work fine.
