### ISSUE TITLE
The display position of the banner is incorrect on Android

### ISSUE THREAD

**Issue by Itetsukuhadou** [googleads/googleads-mobile-unity#896]
The banner may not be displayed in the correct position.
Please let me know how to handle it or a version that does not exhibit this symptom.

v3.16
AQUOS R2（SG706SH）
Android8.0

`var banner = new BannerView(adUnitId, AdSize.Banner, AdPosition.Bottom);`

**Comment by Itetsukuhadou** [comment]
Thank you for comment.
![clip_now_20190428_154748 copy](https://user-images.githubusercontent.com/15720502/57495254-479e4c80-7308-11e9-8561-7a21248f8dac.png)

**Comment by itayganor** [comment]
Does your device has a cutout (notch)?

**Comment by Itetsukuhadou** [comment]
Yes, there is a notch at the top of the screen.
model name: Sharp AQUOS R2
https://www.softbank.jp/mobile/products/smartphone/aquos-r2/

**Comment by stowy** [comment]
Please try [version 3.17.0](https://github.com/googleads/googleads-mobile-unity/releases/tag/3.17.0).
