### ISSUE TITLE
(Android Only) Facebook mediation not working with new Google Mobile Ads SDK (17.2.0), if SDK is initialised with AdManager.

### ISSUE THREAD

**Issue by halfdevil** [googleads/googleads-mobile-unity#898]
Facebook mediation for Android is failing with following exception:

05-06 12:02:01.663 2043 2043 E Ads : java.lang.IllegalStateException: MobileAds.initialize() must be called prior to getting version string.
05-06 12:02:01.663 2043 2043 E Ads : at com.google.android.gms.common.internal.Preconditions.checkState(Unknown Source:29)
05-06 12:02:01.663 2043 2043 E Ads : at com.google.android.gms.internal.ads.zzabc.getVersionString(Unknown Source:87)
05-06 12:02:01.663 2043 2043 E Ads : at com.google.android.gms.ads.MobileAds.getVersionString(Unknown Source:16)
05-06 12:02:01.663 2043 2043 E Ads : at com.google.ads.mediation.facebook.FacebookInitializer.initialize(FacebookInitializer.java:51)
05-06 12:02:01.663 2043 2043 E Ads : at com.google.ads.mediation.facebook.FacebookInitializer.initialize(FacebookInitializer.java:33)
05-06 12:02:01.663 2043 2043 E Ads : at com.google.ads.mediation.facebook.FacebookMediationAdapter.loadRewardedAd(FacebookMediationAdapter.java:116)
05-06 12:02:01.663 2043 2043 E Ads : at com.google.android.gms.internal.ads.zzanm.zzb(Unknown Source:275)
05-06 12:02:01.663 2043 2043 E Ads : at com.google.android.gms.internal.ads.zzamu.dispatchTransaction(Unknown Source:184)
05-06 12:02:01.663 2043 2043 E Ads : at com.google.android.gms.internal.ads.zzfn.onTransact(Unknown Source:12)
05-06 12:02:01.663 2043 2043 E Ads : at android.os.Binder.transact(Binder.java:622)
05-06 12:02:01.663 2043 2043 E Ads : at ox.b(:com.google.android.gms.policy_ads_fdr_dynamite@30000@30000.238272502.238272502:2)
05-06 12:02:01.663 2043 2043 E Ads : at com.google.android.gms.ads.internal.mediation.client.g.b(:com.google.android.gms.policy_ads_fdr_dynamite@30000@30000.238272502.238272502:3)
05-06 12:02:01.663 2043 2043 E Ads : at com.google.android.gms.ads.nonagon.render.bz.a(:com.google.android.gms.policy_ads_fdr_dynamite@30000@30000.238272502.238272502:4)
05-06 12:02:01.663 2043 2043 E Ads : at com.google.android.gms.ads.nonagon.render.dc.a(Unknown Source:10)
05-06 12:02:01.663 2043 2043 E Ads : at com.google.android.gms.ads.nonagon.util.concurrent.p.call(Unknown Source:2)
05-06 12:02:01.663 2043 2043 E Ads : at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-06 12:02:01.663 2043 2043 E Ads : at android.os.Handler.handleCallback(Handler.java:789)
05-06 12:02:01.663 2043 2043 E Ads : at android.os.Handler.dispatchMessage(Handler.java:98)
05-06 12:02:01.663 2043 2043 E Ads : at aai.a(Unknown Source:0)
05-06 12:02:01.663 2043 2043 E Ads : at com.google.android.gms.ads.internal.util.e.a(:com.google.android.gms.policy_ads_fdr_dynamite@30000@30000.238272502.238272502:1)
05-06 12:02:01.663 2043 2043 E Ads : at aai.dispatchMessage(Unknown Source:0)
05-06 12:02:01.663 2043 2043 E Ads : at android.os.Looper.loop(Looper.java:164)
05-06 12:02:01.663 2043 2043 E Ads : at android.app.ActivityThread.main(ActivityThread.java:6798)
05-06 12:02:01.663 2043 2043 E Ads : at java.lang.reflect.Method.invoke(Native Method)
05-06 12:02:01.663 2043 2043 E Ads : at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-06 12:02:01.663 2043 2043 E Ads : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
05-06 12:02:01.664 2043 2043 W Ads : Fail to load ad from adapter com.google.ads.mediation.facebook.FacebookAdapter
05-06 12:02:01.664 2043 2043 W Ads : android.os.RemoteException
05-06 12:02:01.664 2043 2043 W Ads : at com.google.android.gms.internal.ads.zzanm.zzb(Unknown Source:279)
05-06 12:02:01.664 2043 2043 W Ads : at com.google.android.gms.internal.ads.zzamu.dispatchTransaction(Unknown Source:184)
05-06 12:02:01.664 2043 2043 W Ads : at com.google.android.gms.internal.ads.zzfn.onTransact(Unknown Source:12)
05-06 12:02:01.664 2043 2043 W Ads : at android.os.Binder.transact(Binder.java:622)
05-06 12:02:01.664 2043 2043 W Ads : at ox.b(:com.google.android.gms.policy_ads_fdr_dynamite@30000@30000.238272502.238272502:2)
05-06 12:02:01.664 2043 2043 W Ads : at com.google.android.gms.ads.internal.mediation.client.g.b(:com.google.android.gms.policy_ads_fdr_dynamite@30000@30000.238272502.238272502:3)
05-06 12:02:01.664 2043 2043 W Ads : at com.google.android.gms.ads.nonagon.render.bz.a(:com.google.android.gms.policy_ads_fdr_dynamite@30000@30000.238272502.238272502:4)
05-06 12:02:01.664 2043 2043 W Ads : at com.google.android.gms.ads.nonagon.render.dc.a(Unknown Source:10)
05-06 12:02:01.664 2043 2043 W Ads : at com.google.android.gms.ads.nonagon.util.concurrent.p.call(Unknown Source:2)
05-06 12:02:01.664 2043 2043 W Ads : at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-06 12:02:01.664 2043 2043 W Ads : at android.os.Handler.handleCallback(Handler.java:789)
05-06 12:02:01.664 2043 2043 W Ads : at android.os.Handler.dispatchMessage(Handler.java:98)
05-06 12:02:01.664 2043 2043 W Ads : at aai.a(Unknown Source:0)
05-06 12:02:01.664 2043 2043 W Ads : at com.google.android.gms.ads.internal.util.e.a(:com.google.android.gms.policy_ads_fdr_dynamite@30000@30000.238272502.238272502:1)
05-06 12:02:01.664 2043 2043 W Ads : at aai.dispatchMessage(Unknown Source:0)
05-06 12:02:01.664 2043 2043 W Ads : at android.os.Looper.loop(Looper.java:164)
05-06 12:02:01.664 2043 2043 W Ads : at android.app.ActivityThread.main(ActivityThread.java:6798)
05-06 12:02:01.664 2043 2043 W Ads : at java.lang.reflect.Method.invoke(Native Method)
05-06 12:02:01.664 2043 2043 W Ads : at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-06 12:02:01.664 2043 2043 W Ads : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
05-06 12:02:13.757 2043 2043 I Ads : Use AdRequest.Builder.addTestDevice("E6BB7733C20BD5232B8382DC8DCBFC5A") to get test ads on this device.
05-06 12:02:13.805 2043 2043 I Ads : Use AdRequest.Builder.addTestDevice("E6BB7733C20BD5232B8382DC8DCBFC5A") to get test ads on this device.
05-06 12:02:13.823 5302 2732 W Ads : App does not have the required permissions to get location
05-06 12:02:13.828 2043 2722 W Ads : Not retrying to fetch app settings
05-06 12:02:13.839 5302 2758 W Ads : App does not have the required permissions to get location
05-06 12:02:13.881 5302 2757 I Ads : SDK version: afma-sdk-a-v15376999.15000000.1
05-06 12:02:13.893 5302 2759 I Ads : SDK version: afma-sdk-a-v15376999.15000000.1
05-06 12:02:21.663 2043 2043 I Ads : Ad failed to load : 0

This issue is occurring with the new Google Mobile Ads SDK 17.2.0.
MobileAds.getVersionString() is getting called in the initialize method of FacebookInitializer. If we remove the getVersionString() method call, then everything is working fine.

**Comment by stowy** [comment]
Hi thanks for reporting. I think this is a race condition. I will investigate. I would guess that it would work if you waited a few seconds after launching and calling initialize before loading the ad.
