### ISSUE TITLE
(Android) Interstitial OnAdClosed event has a 5 sec delay if a banner has been shown

### ISSUE THREAD

**Issue by pablorengo** [googleads/googleads-mobile-unity#901]
On some devices, like Samsung J7, when showing a banner and then an interstitial, the interstitial close event has a delay of 5 seconds. Pull Request #817

**Comment by stowy** [comment]
Please try [version 3.17.0](https://github.com/googleads/googleads-mobile-unity/releases/tag/3.17.0).

**Comment by pablorengo** [comment]
Thanks! I'll let you know if that version fixed this issue.

**Comment by pablorengo** [comment]
Thanks @stowy, there's no delay after updating to version 3.17.0
