### ISSUE TITLE
Banner is not showing!

### ISSUE THREAD

**Issue by rigby00** [googleads/googleads-mobile-unity#904]
Hello, today i updated admob plugin after that banner is not showing but interstitial and rewarded ads are working fine.

What is the problem?

**Comment by rigby00** [comment]
@keyserjaya Can you help?

**Comment by rigby00** [comment]
**Anyone can help please?**

**Comment by stowy** [comment]
Can you provide more specifics in regards to your implementation and environment? What position are you using for the banner, can you share your implementation code, which platform is this on, and what device and OS version is it running?

**Comment by rigby00** [comment]
I'm trying on Samsung device.(Android). I'm using singelation code. As i said it was working fine when i updated Admob Plugin version it happend. I'm using banner on bottom. Code link in down. Thanks for reply @stowy 

https://pastebin.com/PykfjNGj

**Comment by rigby00** [comment]
Any solutions pls?

**Comment by stowy** [comment]
There will be a new release today, can you please try this when it is
published, the release will be 3.17.0.

**Comment by stowy** [comment]
Please try [version 3.17.0](https://github.com/googleads/googleads-mobile-unity/releases/tag/3.17.0).

**Comment by rigby00** [comment]
> Please try [version 3.17.0](https://github.com/googleads/googleads-mobile-unity/releases/tag/3.17.0).

Still same i'm trying with test ads but same. Interstetial ads is showing but banner is not. Now i will try it with another pc and Unity 2019 i will reply result. @stowy

**Comment by rigby00** [comment]
Still same problem @stowy

**Comment by stowy** [comment]
Which model Samsung are you referring to?   Have you tested / reproduced on
other devices? Does it reproduce on the emulator?  Can you share device
logs and if possible charles logs from when the issue is occurring?

**Comment by rigby00** [comment]
Problem not solved.

**Comment by stowy** [comment]
@rigby00  for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.
