### ISSUE TITLE
Update compilation error inside Assets/GoogleMobileAds/PlistProcessor.cs

### ISSUE THREAD

**Issue by studentutu** [googleads/googleads-mobile-unity#905]
Please update inside Assets/GoogleMobileAds/PlistProcessor.cs : 
wrap whole code in 

#if UNITY_IPHONE || UNITY_IOS || UNITY_TVOS
...
#endif

**Comment by rigby00** [comment]
**Paste this one. On this version #if and #endif at wrong places.**

`#if UNITY_IPHONE
using System.IO;

using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;

public static class PListProcessor
{
    [PostProcessBuild]
    public static void OnPostProcessBuild(BuildTarget buildTarget, string path)
    {
        
          // Replace with your iOS AdMob app ID. Your AdMob App ID will look
          // similar to this sample ID: ca-app-pub-3940256099942544~1458002511
          string appId = "ADMOB_APPLICATION_ID";

          string plistPath = Path.Combine(path, "Info.plist");
          PlistDocument plist = new PlistDocument();

          plist.ReadFromFile(plistPath);
          plist.root.SetString("GADApplicationIdentifier", appId);
          File.WriteAllText(plistPath, plist.WriteToString());
        
    }
}
#endif
`

**Comment by rigby00** [comment]
**Paste this one. On this version #if and #endif at wrong places.** @studentutu 

> `#if UNITY_IPHONE

using System.IO;

using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;

public static class PListProcessor
{
    [PostProcessBuild]
    public static void OnPostProcessBuild(BuildTarget buildTarget, string path)
    {
        
          // Replace with your iOS AdMob app ID. Your AdMob App ID will look
          // similar to this sample ID: ca-app-pub-3940256099942544~1458002511
          string appId = "ADMOB_APPLICATION_ID";

          string plistPath = Path.Combine(path, "Info.plist");
          PlistDocument plist = new PlistDocument();

          plist.ReadFromFile(plistPath);
          plist.root.SetString("GADApplicationIdentifier", appId);
          File.WriteAllText(plistPath, plist.WriteToString());
        
    }
}
#endif

 `>

**Comment by studentutu** [comment]
> **Paste this one. On this version #if and #endif at wrong places.** @studentutu
> 
> #if UNITY_IPHONE
> 
> using System.IO;
> 
> using UnityEditor;
> using UnityEditor.Callbacks;
> using UnityEditor.iOS.Xcode;
> 
> public static class PListProcessor
> {
> [PostProcessBuild]
> public static void OnPostProcessBuild(BuildTarget buildTarget, string path)
> {
> 
> ```
>       // Replace with your iOS AdMob app ID. Your AdMob App ID will look
>       // similar to this sample ID: ca-app-pub-3940256099942544~1458002511
>       string appId = "ADMOB_APPLICATION_ID";
> 
>       string plistPath = Path.Combine(path, "Info.plist");
>       PlistDocument plist = new PlistDocument();
> 
>       plist.ReadFromFile(plistPath);
>       plist.root.SetString("GADApplicationIdentifier", appId);
>       File.WriteAllText(plistPath, plist.WriteToString());
>     
> }
> ```
> 
> }
> #endif

It is also applicable to TV OS.... (UNITY_IPHONE is deprected)

**Comment by stowy** [comment]
Should be fixed in v3.17.0.
