### ISSUE TITLE
About ios banner ads causing device frame rate issues

### ISSUE THREAD

**Issue by yyh9488** [googleads/googleads-mobile-unity#908]
Some banner ads, such as banner ads that are dynamic picture ads the device's frame rate drops to 40, but when the banner switches to static ads the frame rate goes back to 60. The device used 50 percent of the CPU in the 2017 ipad.

**Comment by gering** [comment]
I got exactly the same issue. But I think the CPU isn't actually using 50 % of the CPU but waiting for the screen sync.
