### ISSUE TITLE
facing crash while doing mobileAds.initialize()

### ISSUE THREAD

**Issue by mubshar1** [googleads/googleads-mobile-unity#909]
using Google Mobile Ads Unity Plugin v3.16 facing crash while doing mobileAds.initialize() 

![crash](https://user-images.githubusercontent.com/45542019/57688265-72650980-7656-11e9-94b8-c588b8bcf5aa.PNG)

**Comment by stowy** [comment]
This is most likely fixed in v3.17.0.
