### ISSUE TITLE
How to get fixes that are done after the release package ?

### ISSUE THREAD

**Issue by Jbstudio425** [googleads/googleads-mobile-unity#912]
Hi , after the official package release some error occurs which are then fixed but the release package is not updated i think , so how can we update these fixes ?

**Comment by stowy** [comment]
Hi, there are a couple more fixes pending and I will be providing a new release shortly thereafter in the next couple of days. 

You can also create a build directly yourself using the source code and running the `exportPackage` gradle command from the build.gradle file. This can be run from command line (`gradle exportPackage`) or in android studio.
