### ISSUE TITLE
Google Ads with Iron Source mediation graddle build error

### ISSUE THREAD

**Issue by nostel** [googleads/googleads-mobile-unity#914]
Hi, I'm using newest Google Ads and Ironsource Mediation version. It seem new version move all dependencies into MainGradle file.

 and I got this error:

> FAILURE: Build failed with an exception.

> What went wrong:

> Could not resolve all files for configuration ':releaseCompileClasspath'.

> Could not find com.ironsource.sdk:sdk5:unspecified.
  Searched in the following locations:
      file:/D:/AndroidSDK/SDKOld/SDKOld/extras/m2repository/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.pom
      file:/D:/AndroidSDK/SDKOld/SDKOld/extras/m2repository/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.jar
      file:/D:/AndroidSDK/SDKOld/SDKOld/extras/google/m2repository/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.pom
      file:/D:/AndroidSDK/SDKOld/SDKOld/extras/google/m2repository/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.jar
      file:/D:/AndroidSDK/SDKOld/SDKOld/extras/android/m2repository/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.pom
      file:/D:/AndroidSDK/SDKOld/SDKOld/extras/android/m2repository/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.jar
      file:/C:/Projects/Skychamp/Temp/gradleOut/libs/sdk5-unspecified.jar
      file:/C:/Projects/Skychamp/Temp/gradleOut/libs/sdk5.jar
      https://maven.google.com/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.pom
      https://maven.google.com/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.jar
      file:/C:/Projects/Skychamp/Assets/Firebase/m2repository/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.pom
      file:/C:/Projects/Skychamp/Assets/Firebase/m2repository/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.jar
      https://jcenter.bintray.com/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.pom
      https://jcenter.bintray.com/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.jar
      https://dl.bintray.com/ironsource-mobile/android-sdk/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.pom
      https://dl.bintray.com/ironsource-mobile/android-sdk/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.jar
      file:/C:/Projects/Skychamp/Assets/GooglePlayGames/Editor/m2repository/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.pom
      file:/C:/Projects/Skychamp/Assets/GooglePlayGames/Editor/m2repository/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.jar
      file:/C:/Users/Son/.m2/repository/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.pom
      file:/C:/Users/Son/.m2/repository/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.jar
      https://repo1.maven.org/maven2/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.pom
      https://repo1.maven.org/maven2/com/ironsource/sdk/sdk5/unspecified/sdk5-unspecified.jar
  Required by:
      project : > com.ironsource.sdk:mediationsdk:6.8.1

Do anyone know how to fix it?

**Comment by PinkPanter** [comment]
I changed versions in GoogleMobileAds/Editor/IronSourceMediationDependencies.xml to 
`  
    <androidPackage spec="com.google.ads.mediation:ironsource:6.8.4.1">
    <androidPackage spec="com.ironsource.sdk:mediationsdk:6.8.4">
`

And it works now

**Comment by nostel** [comment]
Thank @PinkPanter
This solution worked.
