### ISSUE TITLE
App Crashing while calling Interstitial Ads Android 

### ISSUE THREAD

**Issue by Shahab-Mirza** [googleads/googleads-mobile-unity#916]
I  am now using Latest Google Ads but still facing the same problem in the pervious version of Google Ads. Most of the time app is crashing while calling interstitial Ads and  this problem is occurring on some devices.

**Comment by stowy** [comment]
Hi, please provide a stack trace, also which devices and API versions is this occurring on? And this is happening with version 3.17.0?  Please reopen with relevant information.
