### ISSUE TITLE
Unity Ads mediation is crashing on iOS devices

### ISSUE THREAD

**Issue by Olszewskim** [googleads/googleads-mobile-unity#919]
Our team has serious problem with Unity Ads mediation adapter on iOS. Application is crashing every time when user has closed it. It gives error:

`
objc[1216]: Cannot form weak reference to instance (0x280fc8ab0) of class GADMAdapterUnityRewardedAd. It is possible that this object was over-released, or is in the process of deallocation.
`

Ad is playing correctly. We are using Unity 2017.4.27f1 and according to UnityMediationDependencies.xml -` <iosPod name="GoogleMobileAdsMediationUnity" version="3.0.0.3">`

**Comment by JelmHoek** [comment]
I have the same issue, did you resolve this?

**Comment by DarkFlameDX** [comment]
+1

**Comment by stowy** [comment]
This should be fixed in the latest update of UnityAds mediation - 3.1.0.0.
