### ISSUE TITLE
Admob App Id initialize

### ISSUE THREAD

**Issue by ceceomer** [googleads/googleads-mobile-unity#922]
Hello,
İ want to ensure which app id preferential. 
For example, there are two different app id in the project. One of them in manifest.xml and other one in initialize script (MobileAds.Initialize(appId);) so which one will be used by sdk?
Thanks.

**Comment by MuhammadWaqasOfficial** [comment]
also want to know the answer.

**Comment by MuhammadWaqasOfficial** [comment]
as far i know. we have to use only one of them. if you initialize it with MobileAds.Initialize(appId) you will false it in manifest file.
else if you init with manifest then don't init with MobileAds.Initialize(appId).

**Comment by stowy** [comment]
you need both for now. The next GMA SDK release will have an initialize call that doesn't require an app id.
