### ISSUE TITLE
Unity 2019 - IL2CPP Builded Android App Not Showing Ads

### ISSUE THREAD

**Issue by PayandaOnline** [googleads/googleads-mobile-unity#923]
GoogleMobileAds-v3.17.0 (Bug)
Ads don't work when I get il2cpp build with unity 2019.1.0f2. It works with mono when I get it build. what can we do to solve this problem?

**Comment by PayandaOnline** [comment]
I Found Solution.
Problem is IL2CPP Stripping.
"GoogleMobileAds\Platforms\GoogleMobileAdsClientFactory.cs" Script Edited And Added PreserveAttribute.
https://docs.unity3d.com/ScriptReference/Scripting.PreserveAttribute.html

Edited Script is Here; http://pasted.co/65aa0f02

**Comment by stowy** [comment]
Sounds good, thanks @PayandaOnline - do you want to create a pull request?

**Comment by PayandaOnline** [comment]
> 
> 
> Sounds good, thanks @PayandaOnline - do you want to create a pull request?

Of course I would be happy to help.
I'm creating a pull request immediately.

**Comment by stowy** [comment]
This should be resolved in the latest version of the plugin.
