### ISSUE TITLE
applovin adapter on android doesn't work

### ISSUE THREAD

**Issue by liang1020** [googleads/googleads-mobile-unity#924]
I have Unity 2018.3.2f1, downloaded AppLovin Adapter plugin for Google Mobile Ads SDK version 4.1.0 which supports AppLovin Android adapter version 9.2.1.1. and AppLovin iOS adapter version 6.3.0.0.

I setup like in integration guides: https://developers.google.com/admob/unity/mediation/applovin

When I run on IOS everything working properly, But when I did Android build and run it I got these error:

AndroidJavaException: java.lang.ClassNotFoundException: com.applovin.sdk.AppLovinSdk

**Comment by UragayalaDeepika** [comment]
@liang1020 Are you still having this issue? Can you please make sure that you are on the latest version of the SDKs, adapters and try again?

**Comment by arpaplus** [comment]
I can confirm, we loosing money everyday with this Exception! 
Latest Applovin mediation plugin (using along with Chartboost) with the latest Unity 2019.3.14f.

Please, do something ASAP!
