### ISSUE TITLE
Need help on implementing mediation on already published app.

### ISSUE THREAD

**Issue by AmitDigga** [googleads/googleads-mobile-unity#925]
So I have released my app with only Admob ads on playstore.

Now for the next update I will be adding Admob-UnityAds mediation. If I enable admob mediation in its console with proper settings, what will happen to previous users without admob mediation sdk for that network. Will they crash? Or they will only get admob ads not mediated ads?

**Comment by stowy** [comment]
These users will only get AdMob ads since you won't have included the
client libraries for the mediated ads.

**Comment by UragayalaDeepika** [comment]
@AmitDigga Closing this. Feel free to reopen if you have any other questions.
