### ISSUE TITLE
Admob Server to Server CallBacks are not sent

### ISSUE THREAD

**Issue by Opeth001** [googleads/googleads-mobile-unity#926]
Hello
i have integrated Unity Admob ads plugin,  everything is working using the new rewarded ads api but im not able to receive the callbacks from admob servers.
can someone confirm it's working for him ?

**Comment by halfdevil** [comment]
Hello,

I have tested this and it is working fine for both Android & iOS. If you are facing this issue only in iOS, then the issue was with the admob server and now they have fixed it.

Thanks

**Comment by Opeth001** [comment]
Thank You!!! @halfdevil 
i was testing in android using version 3.17.

can you please share an example of your code and the link you added to the server ?
im facing this problem from one week now :(

**Comment by stowy** [comment]
hi @Opeth001 - if you are continuing to have trouble, for support debugging your apps, can we request that you make a request on our [support forum]https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
