### ISSUE TITLE
OnAdLeavingApplication callback not firing on Android

### ISSUE THREAD

**Issue by adamjsutcliffe** [googleads/googleads-mobile-unity#931]
I'm having an issue with the OnAdLeavingApplication callback not firing for Interstitials and Rewarded Videos on Android. The same code works fine on iOS devices. When clicking an ad it takes me to the play store but no callback is fired? All the other callbacks work fine.

`this.interstitial.OnAdLeavingApplication += this.HandleInterstitialLeftApplication;`
`this.rewardBasedVideo.OnAdLeavingApplication += this.HandleRewardBasedVideoLeftApplication;`

I'm using Unity 2017.4.28 LTS with the latest Google Mobile Ads Unity Plugin, v3.17.

**Comment by UragayalaDeepika** [comment]
@adamjsutcliffe Can you try with our [sample app](https://github.com/googleads/googleads-mobile-unity/tree/master/samples) and see if you are able to reproduce the issue?

**Comment by adamjsutcliffe** [comment]
I've tried with the sample app and they fire fine there. I've now done a rebuild of my project and they now seem to run fine with test ads. Am about to run a test in live now.
