### ISSUE TITLE
banner and inter ads doesn't work on mobile unity 2019.1

### ISSUE THREAD

**Issue by wheatleyscience** [googleads/googleads-mobile-unity#933]
Hi,

I am trying to implement google ads. I get normal debug logs in editor. But when i try at android phone, i don't get any banner or inter ads.

**Comment by UragayalaDeepika** [comment]
@wheatleyscience Have you tried with our [sample apps](https://github.com/googleads/googleads-mobile-unity/tree/master/samples)? You can run Android Studio and connect your device to get all of your app/device logs in the logcat  and know when an ad is loaded. You can find additional instructions on how to use logcat [here](https://answers.unity.com/questions/492681/how-to-use-adb-logcat.html).

**Comment by wheatleyscience** [comment]
> 
> 
> @wheatleyscience Have you tried with our [sample apps](https://github.com/googleads/googleads-mobile-unity/tree/master/samples)? You can run Android Studio and connect your device to get all of your app/device logs in the logcat and know when an ad is loaded. You can find additional instructions on how to use logcat [here](https://answers.unity.com/questions/492681/how-to-use-adb-logcat.html).

hi, i tried with sample project and everything was working and i only changed ad ids from the sample project now i have a same problem. google ads wont show any rewarded and banner ads, only interstitials.

**Comment by UragayalaDeepika** [comment]
@wheatleyscience Can you please open a thread on our [support forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) and share your Ad unit Ids and complete device logs so that our team can take a look and assist you further?
