### ISSUE TITLE
Rewarded video closes itself

### ISSUE THREAD

**Issue by AllanRW** [googleads/googleads-mobile-unity#942]
After playing a reward video(or cancel it before reward), then if I request to play another one on sequence it start to play the video and close itself after 1 or 2 seconds, its not everytime but very frequent.
Here is the logcat error:

2019/06/15 19:26:42.125 5082 5100 Error System: Uncaught exception thrown by finalizer
2019/06/15 19:26:42.125 5082 5100 Error System: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
2019/06/15 19:26:42.125 5082 5100 Error System: at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7769)
2019/06/15 19:26:42.125 5082 5100 Error System: at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1332)
2019/06/15 19:26:42.125 5082 5100 Error System: at android.view.ViewGroup.invalidateChild(ViewGroup.java:5446)
2019/06/15 19:26:42.125 5082 5100 Error System: at android.view.View.invalidateInternal(View.java:14750)
2019/06/15 19:26:42.125 5082 5100 Error System: at android.view.View.invalidate(View.java:14714)
2019/06/15 19:26:42.125 5082 5100 Error System: at android.view.View.onFocusChanged(View.java:6801)
2019/06/15 19:26:42.125 5082 5100 Error System: at android.webkit.WebView.onFocusChanged(WebView.java:2575)
2019/06/15 19:26:42.125 5082 5100 Error System: at android.view.View.clearFocusInternal(View.java:6686)
2019/06/15 19:26:42.125 5082 5100 Error System: at android.view.View.unFocus(View.java:6719)
2019/06/15 19:26:42.125 5082 5100 Error System: at android.view.ViewGroup.unFocus(ViewGroup.java:996)
2019/06/15 19:26:42.125 5082 5100 Error System: at android.view.ViewGroup.unFocus(ViewGroup.java:998)
2019/06/15 19:26:42.125 5082 5100 Error System: at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4943)
2019/06/15 19:26:42.125 5082 5100 Error System: at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4930)
2019/06/15 19:26:42.125 5082 5100 Error System: at android.view.ViewGroup.removeView(ViewGroup.java:4861)
2019/06/15 19:26:42.125 5082 5100 Error System: at com.google.android.gms.ads.internal.overlay.d.i(:com.google.android.gms.policy_ads_fdr_dynamite@20290004@20290004.249178941.249178941:1)
2019/06/15 19:26:42.125 5082 5100 Error System: at com.google.android.gms.ads.internal.webview.v.destroy(:com.google.android.gms.policy_ads_fdr_dynamite@20290004@20290004.249178941.249178941:2)
2019/06/15 19:26:42.125 5082 5100 Error System: at com.google.android.gms.ads.internal.webview.t.destroy(:com.google.android.gms.policy_ads_fdr_dynamite@20290004@20290004.249178941.249178941:10)
2019/06/15 19:26:42.125 5082 5100 Error System: at com.google.android.gms.ads.nonagon.ad.rewardedvideo.c.finalize(:com.google.android.gms.policy_ads_fdr_dynamite@20290004@20290004.249178941.249178941:2)
2019/06/15 19:26:42.125 5082 5100 Error System: at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
2019/06/15 19:26:42.125 5082 5100 Error System: at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
2019/06/15 19:26:42.125 5082 5100 Error System: at java.lang.Thread.run(Thread.java:762)

Unity 2019.1.5f1
Admob plugin 3.17.0.1

**Comment by stowy** [comment]
Thanks for reporting, this is a known issue and the fix should be rolling out in an upcoming version in the next couple of weeks.

**Comment by AllanRW** [comment]
I've tried the version 3.18 and have the same issue, any ETA for the next release?
 I'm getting some bad reviews because of this issue... :(

**Comment by AllanRW** [comment]
After implemented the new beta API it seems to work fine now,  I'm just getting a warning everytime I close the rewarded video:

2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: Handler (android.os.Handler) {b179ca1} sending message to a Handler on a dead thread
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {b179ca1} sending message to a Handler on a dead thread
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at android.os.Handler.enqueueMessage(Handler.java:643)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at android.os.Handler.sendMessageAtTime(Handler.java:612)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at android.os.Handler.sendMessageDelayed(Handler.java:582)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at android.os.Handler.sendEmptyMessageDelayed(Handler.java:546)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at android.os.Handler.sendEmptyMessage(Handler.java:531)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at com.google.android.gms.ads.exoplayer1.h.c(:com.google.android.gms.policy_ads_fdr_dynamite@20295004@20295004.251939570.251939570:2)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at com.google.android.gms.ads.internal.video.exoplayer1.f.b(:com.google.android.gms.policy_ads_fdr_dynamite@20295004@20295004.251939570.251939570:1)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at com.google.android.gms.ads.internal.webview.t.E(:com.google.android.gms.policy_ads_fdr_dynamite@20295004@20295004.251939570.251939570:5)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at com.google.android.gms.ads.internal.webview.j.onPageFinished(:com.google.android.gms.policy_ads_fdr_dynamite@20295004@20295004.251939570.251939570:2)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at uU.d(PG:307)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at aIV.handleMessage(PG:73)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at android.os.Handler.dispatchMessage(Handler.java:102)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at android.os.Looper.loop(Looper.java:154)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at android.app.ActivityThread.main(ActivityThread.java:6692)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at java.lang.reflect.Method.invoke(Native Method)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
2019/06/27 13:37:51.588 16951 16951 Warn MessageQueue: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
2019/06/27 13:37:51.588 16951 16951 Warn ExoPlayerImplInternal: Sent message(1) after release. Message ignored.
2019/06/27 13:37:51.588 16951 16951 Warn Ads: #004 The webview is destroyed. Ignoring action.
2019/06/27 13:37:51.589 16951 16951 Warn Ads: #004 The webview is destroyed. Ignoring action.

**Comment by NVentimiglia** [comment]
Closing stale issue. Please update and if still an issue please reopen.
