### ISSUE TITLE
3.18 deletes meta-data from admob manifest

### ISSUE THREAD

**Issue by Enekiller** [googleads/googleads-mobile-unity#946]
The mandatory meta-data content including the AdMob app ID is automatically deleted when building for Android

`<meta-data
    android:name="com.google.android.gms.ads.APPLICATION_ID"
    android:value="[INSERT ADMOB APP ID HERE]"/>`

Obviously the app crashes at startup becaouse AdMob needs that info fot initialize.

**Comment by rigby00** [comment]
You need to add app id in here;
Assets > Google Mobile Ads > Settings

**Comment by dayjur** [comment]
You can add App ID via Assets > Google Mobile Ads..   
But still crashes with unable to get provider Invalid Application ID

**Comment by stowy** [comment]
Please review [the documentation](https://developers.google.com/admob/unity/start#set_your_admob_app_id) at https://developers.google.com/admob/unity/start#set_your_admob_app_id, and let us know if there are any issues.
