### ISSUE TITLE
Interstitials and rewarded not showing IOS ad mediation

### ISSUE THREAD

**Issue by dayjur** [googleads/googleads-mobile-unity#948]
Using 3.17.0 and latest mediation adapters
I have Unity Admob, ADS,In Mobi and chartboost set up everything.
On Android Banner Ads, Interstials and Rewards show from the different networks.

However after switching to IOS can only get banners to show from different networks
Interstials and Rewards only show from Admob no other networks
and do not see any ad reqauests in xcode console output for Interstials and Rewards
Tried 3.18.0 same thing
Any ideas ?

**Comment by UragayalaDeepika** [comment]
@dayjur Can you please share your Ad unit id and sample project for us to take a look? Also, can you check again with our [sample script](https://github.com/googleads/googleads-mobile-unity/tree/master/samples) with the latest version of plugin and let us know?

**Comment by dayjur** [comment]
Hi there,
Whilst testing I could not get the Unity Test ADS to show Instersitial and rewarded on IOS, fine on Android, however I released anyway and it appears ADS are appearing Interstitial and rewarded IOS as Unity reports show they are, so appears live ads are working

**Comment by UragayalaDeepika** [comment]
@dayjur Thanks for providing an update.
