### ISSUE TITLE
IL2CPP shows live ads with  .AddTestDevice("<Device_ID>")

### ISSUE THREAD

**Issue by SeharshS** [googleads/googleads-mobile-unity#949]
Building app using mono and .AddTestDevice("<Device_ID>") shows test ads but when building using IL2CPP and .AddTestDevice("<Device_ID>") it shows live ads. At first I thought the ads were test ads because I've read that some test ads don't show the "test" box (correct me if I'm wrong) but it was happening all the time so I got suspicious. I checked the admob console and I saw request being made from my app in test mode

**Comment by stowy** [comment]
Can you check this again with the latest release? is this on iOS or Android?
