### ISSUE TITLE
GoogleMobileAds initialization ANR

### ISSUE THREAD

**Issue by pablorengo** [googleads/googleads-mobile-unity#955]
<img width="744" alt="Screen Shot 2019-06-29 at 12 24 15" src="https://user-images.githubusercontent.com/2294911/60386361-4f59b200-9a6a-11e9-9062-ba3022e08e57.png">

<img width="927" alt="Screen Shot 2019-06-29 at 12 24 56" src="https://user-images.githubusercontent.com/2294911/60386362-4f59b200-9a6a-11e9-98a6-e69ef0d25c05.png">

Hi!! Searching for this ANR I found this conversation in Google Mobile Ads group -> https://groups.google.com/forum/#!topic/google-admob-ads-sdk/QFEoEJUbXjk

In that conversation, Steven Balan from Google Team said that the `MobileAds.initialize()` method should be called from the main thread (UI thread), but in the Unity plugin it is called from the UnityMain thread. 

Should you use [this Unity solution](https://docs.unity3d.com/ScriptReference/AndroidJavaRunnable.html) to call initialize from the UI thread? Is this ANR caused because `MobileAds.initialize()` is being called from 2 different threads?

The stacktrace is from a build using GoogleMobileAds Unity plugin version 3.15.1.

**Comment by mastef** [comment]
I'm also wondering if there's a threading issue, since this callback doesn't seem to fire on the main thread :

```
Debug.Log("[ADS] Initializing");
GoogleMobileAds.Api.MobileAds.Initialize(initStatus => {
		Debug.Log("[ADS] Initialized");
		Config.adsInitialized = true;
}); 
```

I don't get the `Debug.Log` on the log handler in the game and have to inspect `adb logcat` instead - which tells me that the callback fires on another thread?

```
12-30 23:43:47.641 19366 19546 I Unity   : [ADS] Initializing
12-30 23:44:18.129 19366 19366 I Unity   : [ADS] Initialized // ~30 secs ( device offline, facebook timeout )
12-31 00:00:09.845 21651 21804 I Unity   : [ADS] Initializing
12-31 00:00:40.362 21651 21651 I Unity   : [ADS] Initialized // ~30 secs ( device offline, facebook timeout )

12-31 00:07:11.056 24304 24434 I Unity   : [ADS] Initializing
12-31 00:07:14.833 24304 24304 I Unity   : [ADS] Initialized // 3 secs ( device online )
```
