### ISSUE TITLE
How to save Google ads banner while leaving scene?

### ISSUE THREAD

**Issue by wooden-coder** [googleads/googleads-mobile-unity#956]
I have an advertisement banner in my android game **in the game menu.**
Player leaves game menu to play game and then comes back to the menu to choose game level he wants **quite often** (can be 3 times a minute).
How to save banner from destroying and display it again only when the player comes back to the menu?

_**Why?**_ I don't wanna request a new banner each time, it looks like a bad practice and Google Admob may be not so happy about that kind of actions (i think).
**Or** is it ok to request it at a such high rate?

**Comment by AliahmadDev** [comment]
Hi,
There is of course a solution for that; i can guide you if you are working with unity platform.
Attach your advertisement script with an object in the very first scene in which you wanna start showing the banner and then call the banner Ad also "you have to apply Don't DestroyOnLoad" for that object. Then you will not lose the banner ad while switching the different scenes.
