### ISSUE TITLE
Loading ad gives Internal error with newest version

### ISSUE THREAD

**Issue by JoshNC** [googleads/googleads-mobile-unity#962]
Title says it all. I followed the get started and rewarded ads tutorial on developers.google. In the past it always worked but now every version gives internal error problem. Also restarted device etc. The problem occurs with loading a test ad. 

Also next to this problem I have the following error:
Assets\GoogleMobileAds\Editor\ManifestProcessor.cs(18,34): warning CS0618: 'IPreprocessBuild' is obsolete: 'Use IPreprocessBuildWithReport instead'

Help?

**Comment by stowy** [comment]
Are you using our test ads ad units? If so, the reason is that the test
account has been temporarily down for the last day or so. It should be back
up within 24 hours. Apologies for the inconvenience.
