### ISSUE TITLE
INTERNAL F***** ERROR

### ISSUE THREAD

**Issue by kadirkoca** [googleads/googleads-mobile-unity#963]
WHY HANDLER CANNOT RETURN SOME DETAILS ONLY INTERNAL ERRORS FROM MORNING I VE F* TRIED EVERY DIFFERENT WAY, DIFFERENT IDS EVERY F*** SHIT I VE TRIED BUT IVE GOT ONLY INTERNAL ERROR MESSAGE. BULLSHIT

**Comment by stowy** [comment]
Sorry we can't assist with nonspecific issues such as this. In general you'll get a better response if you share specific problems that you're experiencing and ways to reproduce.

Additionally we have a [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) which is more actively maintained, please try posting there in future.
