### ISSUE TITLE
Mobile Ads Settings scriptable object location is static, breaks when moved

### ISSUE THREAD

**Issue by rnakrani** [googleads/googleads-mobile-unity#964]
Hack fix below, but it appears to allow the settings scriptable object to be located anywhere in a Unity project, for anybody who likes to organize their files their own way in their project.

`using System.IO;

using UnityEditor;
using UnityEngine;

namespace GoogleMobileAds.Editor {

    internal class GoogleMobileAdsSettings : ScriptableObject
    {
        private string MobileAdsSettingsDir = "Assets/GoogleMobileAds";

        private string MobileAdsSettingsResDir = "Assets/GoogleMobileAds/Resources";

        private string MobileAdsSettingsFile =
            "Assets/GoogleMobileAds/Resources/GoogleMobileAdsSettings.asset";

        private static GoogleMobileAdsSettings instance;

        [SerializeField]
        private bool isAdManagerEnabled = false;

        [SerializeField]
        private bool isAdMobEnabled = false;

        [SerializeField]
        private string adMobAndroidAppId = string.Empty;

        [SerializeField]
        private string adMobIOSAppId = string.Empty;

        [SerializeField]
        private bool delayAppMeasurementInit = false;

        public bool IsAdManagerEnabled
        {
            get
            {
                return Instance.isAdManagerEnabled;
            }

            set
            {
                Instance.isAdManagerEnabled = value;
            }
        }

        public bool IsAdMobEnabled
        {
            get
            {
                return Instance.isAdMobEnabled;
            }

            set
            {
                Instance.isAdMobEnabled = value;
            }
        }

        public string AdMobAndroidAppId
        {
            get
            {
                return Instance.adMobAndroidAppId;
            }

            set
            {
                Instance.adMobAndroidAppId = value;
            }
        }

        public string AdMobIOSAppId
        {
            get
            {
                return Instance.adMobIOSAppId;
            }

            set
            {
                Instance.adMobIOSAppId = value;
            }
        }

        public bool DelayAppMeasurementInit
        {
            get
            {
                return Instance.delayAppMeasurementInit;
            }

            set
            {
                Instance.delayAppMeasurementInit = value;
            }
        }

        public static GoogleMobileAdsSettings Instance
        {
            get
            {
                if (instance == null)
                {
                    string[] results = Directory.GetDirectories(Application.dataPath, "GoogleMobileAds");

                    if (results.Length > 0)
                    {
                        string strMobileAdsDir = results[0];
                        if (!string.IsNullOrEmpty(strMobileAdsDir))
                        {
                            Instance.MobileAdsSettingsDir = strMobileAdsDir;
                            Instance.MobileAdsSettingsResDir = Instance.MobileAdsSettingsDir + "/Resources";
                            Instance.MobileAdsSettingsFile = Instance.MobileAdsSettingsResDir = "/GoogleMobileAdsSettings.asset";
                        }
                    }

                    if (!AssetDatabase.IsValidFolder(Instance.MobileAdsSettingsResDir))
                    {
                        AssetDatabase.CreateFolder(Instance.MobileAdsSettingsDir, "Resources");
                    }

                    instance = (GoogleMobileAdsSettings) AssetDatabase.LoadAssetAtPath(
                        Instance.MobileAdsSettingsFile, typeof(GoogleMobileAdsSettings));

                    if (instance == null)
                    {
                        instance = ScriptableObject.CreateInstance<GoogleMobileAdsSettings>();
                        AssetDatabase.CreateAsset(instance, Instance.MobileAdsSettingsFile);
                    }
                }
                return instance;
            }
        }

        internal void WriteSettingsToFile()
        {
            AssetDatabase.SaveAssets();
        }
    }
}
`

**Comment by Watcher3056** [comment]
+1 Fix this dump issue
