### ISSUE TITLE
Request Interstitial Ads can not finish

### ISSUE THREAD

**Issue by SturgeonDu** [googleads/googleads-mobile-unity#966]
Hi everybody!!
my project incloud GooglePlay Games SDK and GoogleMobileAds.
so i found a interist interesting thing,if i set **RequestServerAuthCode(true)** in GooglePlay SDK,like this code:
`PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
            // enables saving game progress.
            ////.EnableSavedGames()
            // registers a callback to handle game invitations received while the game is not running.
            ////.WithInvitationDelegate(< callback method >)
            // registers a callback for turn based match notifications received while the
            // game is not running.
            ////.WithMatchDelegate(< callback method >)
            // requests the email address of the player be available.
            // Will bring up a prompt for consent.
            .RequestEmail()
            // requests a server auth code be generated so it can be passed to an
            //  associated back end server application and exchanged for an OAuth token.
            .RequestServerAuthCode(true)
            // requests an ID token be generated.  This OAuth token can be used to
            //  identify the player to other services such as Firebase.
            .RequestIdToken()
            .Build();

            PlayGamesPlatform.InitializeInstance(config);
            // recommended for debugging:
            PlayGamesPlatform.DebugLogEnabled = GS_Debug.DebugModel;
            PlayGamesPlatform.Activate();`

the GoogleMobileAds request well,but i set **RequestServerAuthCode(false)** , GoogleMobileAds can not be load.

i do'nt know why ??

**Comment by stowy** [comment]
Hi, thanks for your query.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.
