### ISSUE TITLE
Rythmic Audio Crackling On Android

### ISSUE THREAD

**Issue by OdinKong** [googleads/googleads-mobile-unity#967]
My audio on Android has been flawless, until I installed this plugin. Now there is a rhythmic crackling sound throughout the entire game. The only place I don't hear the sound is in the ad mob rewarded video ads. They sound fine. It almost sounds like the sampling rate is off. Is there anything in this plugin that messes with the sound or would it download any dependencies that would overwrite any audio settings?

I know it seems strange, but the only thing I've done to the game since this issue occurred is add the ad mob plugin.

**Comment by stowy** [comment]
Hi Shane, can you confirm that removing the plugin removes the sound issue?

Are you able to provide a simplified sample that replicates the issue? You
can also post on our [support forum](
https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines)
at
https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines
- they will be able to help debug your issue with you efficiently.

**Comment by OdinKong** [comment]
Hey sorry apparently the older build that I thought was fine was actually only fine on certain devices. I tried using an older build before the ads plugin was imported and the audio issue is still there on the problem device. Looks like there's no issue with the ad mob plugin. Sorry for the trouble.
