### ISSUE TITLE
3.18.0 PodSpec for Google-Mobile-Ads-SDK limits to '~>7.42.1' whereas the change-log indicates it was tested with 7.45.0

### ISSUE THREAD

**Issue by sanderson82** [googleads/googleads-mobile-unity#968]
The change-log for 3.18.0 indicates that:

> Built and tested with:
> Google Play services 18.0.0
> Google Mobile Ads iOS SDK 7.45.0
> Unity Jar Resolver 1.2.119

Whereas the PodSpec included with the plugin limits Google Mobile Ads iOS SDK to `'~>7.42.1'`  which will not update to `7.45.0` or `7.46.0`.

Request the PodSpec be updated to 
`pod 'Google-Mobile-Ads-SDK', '~>7.45'`

So that it matches the minimum version it was tested with and greater.

**Comment by Tanek81** [comment]
Confirmed also here: https://github.com/googleads/googleads-mobile-unity/issues/961

**Comment by stowy** [comment]
Resolved with release v3.18.1
