### ISSUE TITLE
GADCustomEventInterstitial does not pass adNetworkExtras when used from the unity plugin with iOS

### ISSUE THREAD

**Issue by sanderson82** [googleads/googleads-mobile-unity#970]
Sending ad network extras for custom event requests works in iOS but not in iOS Unity.

In `GADURequest.m `I can see adNetworkExtras being added in 

```
- (GADRequest *)request {
  GADRequest *request = [GADRequest request];
  request.testDevices = self.testDevices;
  request.keywords = self.keywords;
  request.birthday = self.birthday;
  request.gender = self.gender;
  request.requestAgent = self.requestAgent;
  [request tagForChildDirectedTreatment:self.tagForChildDirectedTreatment];
  GADExtras *extras = [[GADExtras alloc] init];
  extras.additionalParameters = self.extras;
  [request registerAdNetworkExtras:extras];

  for (id<GADAdNetworkExtras> mediationExtras in self.mediationExtras) {
    **[request registerAdNetworkExtras:mediationExtras];**
  }
  return request;
}
```

but when accessed from 

```
GADCustomEventInterstitial
- (void)requestInterstitialAdWithParameter:(NSString *)serverParameter
                                     label:(NSString *)serverLabel
                                   request:(GADCustomEventRequest *)request
```

the `request.additionalParameters` are nil.

**Comment by stowy** [comment]
So, two things, firstly, you need to ensure that you have a MediationExtras
class in C# that supplies the `IOSMediationExtraBuilderClassName`.

Secondly, you must ensure that that class exists in your iOS project /
plugin, that it implements the `GADUAdNetworkExtras` protocol, which has
one method:

```objc

- (*id*<GADAdNetworkExtras>)adNetworkExtrasWithDictionary:

    (NSDictionary<NSString *, NSString *> *)extras;
```

If it doesn't work, you should see a log in iOS saying `Unable to create
mediation ad network class: <class>`.

Have you done all this? If so, please provide a sample project reproducing
the issue.

Regards

Sam

**Comment by sanderson82** [comment]
We've done that and the adNetworkExtras are making their way to the rewarded adapter correctly.  Our adapter uses both protocols (GADMRewardBasedVideoAdNetworkAdapter, GADCustomEventInterstitial) and the same setup for adding the extras.  Breakpointing `GADURequest.m` at `- (GADRequest *)request` I see the events being added for both rewarded and interstitial requests.  When the request get to `requestInterstitialAdWithParameter` they are not there.  I'll send you a demo app demonstrating this.

**Comment by sanderson82** [comment]
Hi Samuel, 
Did you receive the sample app I sent via email?  
Were you able to reproduce the issue?  Is there anything I can do to help provide more information?
Thanks
Steve

**Comment by sanderson82** [comment]
@stowy 
I think I see the issue.  The AdMob unity adapter does not fully support GADCustomEventInterstitial with GADCustomEventExtras for Unity iOS.

In Android support was added with this PR:
https://github.com/googleads/googleads-mobile-unity/pull/862/files

In iOS the GADCustomEventInterstitial uses 
`
GADRequest *request = [GADRequest request];
GADCustomEventExtras *extras = [[GADCustomEventExtras alloc] init];
[extras setExtras:@{@"SampleExtra": @(YES)} forLabel:@"SampleCustomEvent"];
[request registerAdNetworkExtras:extras];
` 

where the label is the label of the custom event you defined in the AdMob dashboard.  There does not appear to be any API from Unity to add custom extras with a label from Unity.

**Comment by stowy** [comment]
@sanderson82 sorry for delay and thanks for this info. I think you could return a `GADCustomEventExtras` object with the relevant extras in the code that you implement for `GADUAdNetworkExtras`:

```
- (*id*<GADAdNetworkExtras>)adNetworkExtrasWithDictionary:
    (NSDictionary<NSString *, NSString *> *)extras;
```

For example:

```
- (*id*<GADAdNetworkExtras>)adNetworkExtrasWithDictionary:
    (NSDictionary<NSString *, NSString *> *)extras {
  GADCustomEventExtras *customEventExtras = [[GADCustomEventExtras alloc] init];
  [customEventExtras setExtras:extras forLabel:@"SampleCustomEvent"];
  return customEventExtras;
}
```

Do you think this would work for you?

**Comment by sanderson82** [comment]
@stowy 
Thank you for the workaround.  I was able to get this to work using your suggestion.

**Comment by stowy** [comment]
Excellent! No problem.
