### ISSUE TITLE
I'm having trouble displaying video ads on some devices.

### ISSUE THREAD

**Issue by a-to-z-27-815** [googleads/googleads-mobile-unity#971]
The image below is a picture taken of the problem with the "ASUS ROG Phone".
As shown in the image, there is a problem with the banner display during playback.
Also, I think that there is a problem in acquiring the resolution in the full screen display when the playback is completed.

These issues only occur with Landscape.
There is no problem with Portrait.

After checking with some devices, it did not reproduce with most devices.

SDK Version: 3.18.0, 3.17.0
Unity Version: 2017.4.29, 2018.4.3

![banner](http://drive.google.com/uc?export=view&id=1-ygi5M79RLl18IBzxXRYSSpsyOhT2N8C)
![screen size](http://drive.google.com/uc?export=view&id=107Zu2BTfbTS6IMAXTa3Jd-qTp8q8mZTf)

**Comment by stowy** [comment]
Hi, thanks for your query.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.
