### ISSUE TITLE
Urgent : Game Start Crashing From Second Time And So On

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#977]
Game works okay for the first time. All ads works.
Then start crashing from second time and keep crashing.
Note:
- Game opens successfully then crashes right before showing banner.
- Not crash when internet is off.
This same issue happening with other developer from my circle.
Unity: 2019.1.2f1
Admob : 3.18.1
Admob Mediation : Using
Target Architecture : Armv7 & 64

**Comment by stowy** [comment]
Thanks for the feedback, please provide crash logs, device type, and
Android version where you're seeing the crashes.

**Comment by MuhammadWaqasOfficial** [comment]
Crash logs : Don't know how to see.
Device : Samsung Galaxy s6 edge
Version : 1.0

**Comment by stowy** [comment]
Sorry there is not enough information here for us to triage. Please re-open if you can at least provide a stack trace of the crash from your device logs.
