### ISSUE TITLE
com.unity3d.ads.unity-ads-3.1.0 Conflicts With UnityAds.aar

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#979]
Build is failing at the end of build. (See screenshots)
com.unity3d.ads.unity-ads-3.1.0 Conflicts With UnityAds.aar.
Build successful after deleting one of these files.
Is it safe to "com.unity3d.ads.unity-ads-3.1.0"?
Effects on ads if i delete this file?
![Error Screen 1](https://user-images.githubusercontent.com/32755091/61948075-54097b80-afc0-11e9-9b5a-244ab2348b29.png)
![Error Screen 2](https://user-images.githubusercontent.com/32755091/61948077-54097b80-afc0-11e9-928b-ef6619cd62b8.png)
I am using admob mediation.(Admob+Unity+Chartboost).

**Comment by stowy** [comment]
Yes it appears that there are two aars which both are the UnityAds SDK. Which one comes from which source?

**Comment by MuhammadWaqasOfficial** [comment]
Com.unity3d.ads.unity-ads-3.1.0 is from admob package and unityads.aar from unity monotization package

**Comment by MuhammadWaqasOfficial** [comment]
any update?

**Comment by stowy** [comment]
There is certainly a conflict. I assume you used this guide -
https://developers.google.com/admob/unity/mediation/unity#step_3_import_the_unity_sdk_and_adapter
?

Can you link to the setup guide you followed for Unity Ads monetization?
Also, what version of Unity are you using?

**Comment by stowy** [comment]
I suggest contacting Unity Ads regarding this. This isn't really a use case
we support - you are using two different versions of Unity Ads. I would
suggest you either use Unity Ads monetization, or you mediate to Unity Ads
using Google AdMob. Trying to do both results in the conflicts you are
seeing. But please contact Unity Ads as they're familiar with how their SDK
works and can advise if this configuration is viable.
