### ISSUE TITLE
#Unsupported (warnings) at Developer Console After Using AdMob SDK v3.18.1 and If i use AdMob SDK v3.15.1 then this warnings removed successfully

### ISSUE THREAD

**Issue by Catch-dvp** [googleads/googleads-mobile-unity#980]
![9a99ac3b-e6be-4830-a2b0-a28beb84c657](https://user-images.githubusercontent.com/20943024/62028703-bd8eb300-b195-11e9-963c-720694c88906.jpg)

**Comment by zhouzhuli** [comment]
I also have the same problem. I still don't know how to solve it. Have you solved it?

**Comment by UragayalaDeepika** [comment]
@Catch-dvp @zhouzhuli Can you provide us steps to reproduce this issue? Plus, can you confirm the Mobile Ads SDK version you are using and the target SDK for your Android project?

**Comment by zhouzhuli** [comment]
@UragayalaDeepika The Mobile Ads SDK is 3.18.1 now, but I have the issue after the version 3.15.1, and the target SDK is 28, mini SDK is 16
