### ISSUE TITLE
Game not smooth when showing animated banner 

### ISSUE THREAD

**Issue by phuc149** [googleads/googleads-mobile-unity#983]
My demo project demonstrates a simple dragging function.  Without banner or image banner, dragging looks very smooth.
Then I load an animated banner and the motion doesn't look smooth anymore. 
The FPS doesn't drop, it stays 59-60 fps during the test.

Tested in: Unity 2018.2.11f1, Google Mobile Ads Unity Plugin 3.18.2

Here is my recording videos:
- Smooth: https://drive.google.com/open?id=1CSXoj0pTvu12Ko_UOsF7-C-sWhPRH_Ap
- Not smooth with animated banner: https://drive.google.com/open?id=1SEqWfUIPVg2xJNO1YIems4kP-6Pa7Qu-

Here is my dragging code:
`

    void Update()
    {
        if (Input.GetMouseButtonDown(0)) {
            
        }
        if (Input.GetMouseButton(0)) {
            TouchMoved();
        }
        if (Input.GetMouseButtonUp(0)) {
        }
    }

    void TouchMoved() {
        Vector3 v3touch = Input.mousePosition;
        tileObj.transform.position = Camera.main.ScreenToWorldPoint(new Vector3(v3touch.x, v3touch.y, 0));
    }`

**Comment by UragayalaDeepika** [comment]
@phuc149 I can barely notice any difference between both of the videos. However, can you run a Timer Profile via Instruments and see if there are any methods being called that might be causing this lag that you notice? This might help us in debugging this further. Also, can you send us a sample script of this issue as well for us to look into this?

**Comment by phuc149** [comment]
Hi there,

May be you should play 2 videos side by side to see the difference.
My device is Samsung Galaxy S8 (SM-G950FD), Android 9.
Here is my demo project: https://drive.google.com/open?id=1jqDgcUEK_Hxx6pcK3WZQ-VNe6slcAHLi
Please replace with your app id and banner id in the GoogleMobileAdsDemoScript.cs file. You should try real ads to see the problem. 

Thank you.

**Comment by gering** [comment]
I think this issue could be related to #1086 and #908.
