### ISSUE TITLE
advertising is shown only 1 time after installing the application

### ISSUE THREAD

**Issue by scorp2007** [googleads/googleads-mobile-unity#992]
Advertising is displayed only on the first launch of the application, if I close it and open it again, all advertising in the game will show an error "no fill" until I delete the application, after I delete the application and install the new version I can watch advertisements again in the first launch of the application, but after restart again, "no fill" error.

Unity 2019.1.7f1
Android
Google Mobile Ads Unity Plugin v3.18.2
Resolver 1.2.124

Help, what could be the problem? I used the exact same code earlier in my other applications and there has never been anything like it.

**Comment by UragayalaDeepika** [comment]
@scorp2007 Have you tested your Ad unit Ids with our sample apps? Can you test with our samples and see what is the error that is being thrown?

**Comment by lucianbaciu** [comment]
I have the same issue. 

Unity 2018.4.8 
Target Android 28
Scripting backend: IL2CPP
Google Mobile Ads Unity Plugin v3.18.3

If I downgrade to Google Mobile Ads Unity Plugin v3.18.0 it works.
