### ISSUE TITLE
Ads not showing when exporting Android project

### ISSUE THREAD

**Issue by PavelDoGreat** [googleads/googleads-mobile-unity#996]
I'm trying to show rewarded video ads. Here is 3 scenarios:

1. When building directly, it shows an ad properly for test and production Ad Unit Ids.
2. When exporting project with test Ad Unit Id, works perfectly too.
3. When exporting project with production Ad Unit Id, it doesn't show an ad.

Some errors that I have received in log:
```
E/UnityAds: com.unity3d.services.core.webview.bridge.Invocation.nextInvocation() (line:55) :: Error handling invocation com.unity3d.services.core.api.Listener.sendErrorEvent([INVALID_ARGUMENT, Provided Game ID '29018317-00d5-499b-87d2-5177b9d551c9' is invalid. Game ID may contain only digits (0-9).]): null
E/UnityAds: com.unity3d.services.core.api.Sdk.logError() (line:57) :: Initialization error: undefined
I/chromium: [INFO:CONSOLE(4537)] "Uncaught (in promise) [object Array]", source: file:///storage/emulated/0/Android/data/games.paveldogreat.fluidsimfree/cache/UnityAdsCache/UnityAdsWebApp.html?platform=android&origin=https%3A%2F%2Fwebview.unityads.unity3d.com%2Fwebview%2F3.1.0%2F0c3dfd05b3b389348972b1d20b5027d6c4938f83%2Frelease%2Findex.html&version=0c3dfd05b3b389348972b1d20b5027d6c4938f83 (4537)
I/Ads: Ad failed to load : 0
W/Unity: Video ad failed to load: Internal error
    System.EventHandler`1:Invoke(Object, TEventArgs)
    System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
    UnityEngine.AndroidJavaProxy:Invoke(String, Object[])
    UnityEngine._AndroidJNIHelper:InvokeJavaProxyMethod(AndroidJavaProxy, IntPtr, IntPtr)
```

Also I had an error at gradle sync saying that: `Manifest merger failed : uses-sdk:minSdkVersion 1 cannot be smaller than version 14 declared in library`. Fixed it by commenting out this line in AndroidManifest: `<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="19" />`. That shouldn't happen.

**Comment by PavelDoGreat** [comment]
I have figured out the problem. Production ads are not showing when you build project with debug key. When I have built with release key, it started working. You could have put that info in logs instead of just giving `Video ad failed to load: Internal error`.

**Comment by IvanBgd011** [comment]
I know this was 2 years ago but how do i know if my key is a release key, i have the same problem.
